### ISSUE TITLE
Distributed training issue

### ISSUE THREAD

**Issue by putcn** [PaddlePaddle/Paddle#10071]
I was trying to start vgg16 benchmark testing with cifar10 in aws, but trainer failed with following error. machine is a GPU machine with 8 GPUs, training started with nvidia-docker
```
Traceback (most recent call last):
  File "vgg16_fluid.py", line 292, in <module>
    main()
  File "vgg16_fluid.py", line 260, in main
    exe.run(fluid.default_startup_program())
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 336, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Cannot run operator on place CUDAPlace(0) at [/paddle/paddle/fluid/framework/operator.cc:87]
PaddlePaddle Call Stacks: 
0       0x7f041ff076acp paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 572
1       0x7f0420708c8ep paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 302
2       0x7f041ffab97ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool) + 414
3       0x7f041ffacd52p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 114
4       0x7f041ff27337p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::operator()(pybind11::detail::function_call) const + 567
5       0x7f041ff274fep void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 14
6       0x7f041ff24094p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
7             0x4c37edp PyEval_EvalFrameEx + 31165
8             0x4b9ab6p PyEval_EvalCodeEx + 774
9             0x4c16e7p PyEval_EvalFrameEx + 22711
10            0x4b9ab6p PyEval_EvalCodeEx + 774
11            0x4c1e6fp PyEval_EvalFrameEx + 24639
12            0x4b9ab6p PyEval_EvalCodeEx + 774
13            0x4eb30fp
14            0x4e5422p PyRun_FileExFlags + 130
15            0x4e3cd6p PyRun_SimpleFileExFlags + 390
16            0x493ae2p Py_Main + 1554
17      0x7f04757d4830p __libc_start_main + 240
18            0x4933e9p _start + 41
```
command to start this trainer is:
```
nvidia-docker run --network="host" -i  -e "MASTER_ENDPOINT=172.31.48.87:5436" -e "TASK_NAME=fervent_brahmagupta" -e "TRAINER_COUNT=2" -e "TRAINERS=2" -e "TRAINER_INDEX=1"  -e "PADDLE_INIT_TRAINER_ID=1" -e "TRAINING_ROLE=TRAINER"  -e "PSERVER_HOSTS=172.31.48.93:5436"  -e "PSERVERS=172.31.48.93:5436" putcn/vgg16_test:latest-mainrepo --device GPU --local no --batch_size 20
```

`putcn/vgg16_test:latest-mainrepo`'s Dockerfile is based on the docker GPU distribued build from yesterday. The python code is basiclly `https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/cluster/vgg16/vgg16_fluid.py`

tried with 1 or 2 pserver, all failed similarly.

for more info, please find the master log from:
http://18.216.252.233:5436/status
trainer log:
http://18.216.252.233:5436/log/trainer_0.log
trainer error log:
http://18.216.252.233:5436/log/trainer_0_err.log
pserver log:
http://18.216.252.233:5436/log/pserver_172.31.48.93.log
perver error log:
http://18.216.252.233:5436/log/pserver_172.31.48.93_err.log

Also, is ParallelExecutor ready for distributed training? I also tried training script from `https://github.com/typhoonzero/fluid_gpu_benchmark/blob/master/vgg16_fluid.py` not working either, but with different error though.

**Comment by Yancey1989** [comment]
It seems that the Paddle wasn't build with cmake flag `WITH_GPU=OFF`: 
```bash
$ nvidia-docker run --rm -it --entrypoint=/bin/bash putcn/vgg16_test:latest-mainrepo paddle version
PaddlePaddle 0.11.1a2, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: ON
    with_mkldnn: ON
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF
```

**Comment by putcn** [comment]
ah, my bad, compile was performed in docker instead of nvidia-docker, which disabled `with_gpu` setting.
