### ISSUE TITLE
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory错误

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/Paddle#10098]
我是用docker源码编译安装的，然后使用的时候出现上面的错误。我的环境是ubuntu16.04,gtx1080,cuda8.0,cudnn5.1,然而docker编译的时候出现cudnn7.0，请问是cudnn的原因吗？
全部错误是这样的：
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    main()
  File "train.py", line 31, in main
    paddle.init(use_gpu=True, trainer_count=1)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/__init__.py", line 128, in init
    import py_paddle.swig_paddle as api
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

**Comment by seiriosPlus** [comment]
这是是缺了libmklml_intel.so， 尝试加入环境变量
``` export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib ```

**Comment by yyhlvdl** [comment]
多谢，请问你可以把完整的命令写出来吗？我在.bashrc中添加了，还是同样的错误。

**Comment by yyhlvdl** [comment]
@seiriosPlus 多谢，我在.bashrc中这样添加：
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"，然而还是出现上面的错误。

**Comment by yyhlvdl** [comment]
多谢。
