### ISSUE TITLE
Could NOT find NumPy (missing: PYTHON_NUMPY_INCLUDE_DIR)

### ISSUE THREAD

**Issue by prettyboyning** [PaddlePaddle/Paddle#10156]
[CMakeOutput.log](https://github.com/PaddlePaddle/Paddle/files/1940566/CMakeOutput.log)

B000000093756K:build ningliujie$ brew install openssl
Updating Homebrew...
Warning: openssl 1.0.2o_1 is already installed, it's just not linked
You can use `brew link openssl` to link this version.
B000000093756K:build ningliujie$ brew link openssl --force
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib

 Found PythonInterp: /usr/local/bin/python2.7 (found suitable version "2.7.14", minimum required is "2.7") 
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found suitable version "2.7.10", minimum required is "2.7") 
-- Found PY_pip: /usr/local/lib/python2.7/site-packages/pip  
-- Found PY_numpy: /usr/local/lib/python2.7/site-packages/numpy  
-- Found PY_wheel: /usr/local/lib/python2.7/site-packages/wheel  
-- Found PY_google.protobuf: /usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf  
/usr/include/python2.7
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
/usr/local/lib/python2.7/site-packages/numpy/core/include
PYTHON_NUMPY_INCLUDE_DIR-NOTFOUND
CMake Error at /usr/local/Cellar/cmake/3.11.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find NumPy (missing: PYTHON_NUMPY_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.11.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindNumPy.cmake:42 (find_package_handle_standard_args)
  cmake/external/python.cmake:33 (FIND_PACKAGE)
  CMakeLists.txt:136 (include)

**Comment by luotao1** [comment]
请问是碰到了什么问题？从log和上面的comment中，没有看到和paddle相关的问题。

**Comment by prettyboyning** [comment]
运行 cmake .. ，然后报错  Could NOT find NumPy (missing: PYTHON_NUMPY_INCLUDE_DIR) 找不到 NumPy, 然后安装 easy_install install pip ， 报错，ERROR:root:code for hash md5 was not found. 无法安装

**Comment by luotao1** [comment]
- 建议可以用docker来安装和编译paddle。
- 和paddle无关的环境问题，建议去stackoverflow等其他社区寻求答案。

**Comment by prettyboyning** [comment]
这个是 iOS 环境，不能使用 docker

**Comment by Yancey1989** [comment]
可以在cmake中用`message`把变量打印出来看下具体的报错信息。

**Comment by typhoonzero** [comment]
Closing due to low activity, feel free to reopen.
