### ISSUE TITLE
从 paddlepaddle/paddle:latest-noavx-openblas 构建的镜像以非 root 用户运行出错!

### ISSUE THREAD

**Issue by Zhaoyangzhen** [PaddlePaddle/Paddle#10196]
Dockerfile 里 useradd 的部分：
"
FROM paddlepaddle/paddle:latest-noavx-openblas

RUN groupadd -g 1000 user
RUN useradd -s /sbin/nologin -g 1000 -G user -u 1000 -r user
RUN echo 'user ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN echo 'user:hHjkyJKY&JKUhgkjkdu8d89fU7653%i#^86HJj' | chpasswd
RUN echo 'root:vMSdldhY9iPfJqAuN2MyE215VrP26GmsJEzkQx' | chpasswd
RUN mkdir -p /home/user/project

WORKDIR /home/user/project
"

按照如上方法构建好镜像 test/paddle 镜像以后  

执行docker run -ti -u user test/paddle:latest /bin/bash 启动镜像后   
在这个容器里面：  
执行 echo $HOME 会输出 /root    
执行 cd ~ 的时候会出现 bash: cd: /root: Permission denied  
正常情况下 ：    
echo $HOME 应该输出的是 /home/user  
cd ~ 应该会进到 /home/user 目录

这个镜像是做过什么限制吗？  
可以解决吗？

**Comment by typhoonzero** [comment]
您好，目前镜像还没有考虑docker 内使用其他用户的场景，此问题我会继续跟进，可以暂时先用容器内root运行。

**Comment by Zhaoyangzhen** [comment]
好吧，感谢您的回答！

**Comment by Zhaoyangzhen** [comment]
请问从源码编译可以解决这个问题吗？或者有其他解决方案吗？  
急，在线等。。

**Comment by typhoonzero** [comment]
`docker run -e "HOME=xxx"`可以在run的时候改变。

**Comment by Zhaoyangzhen** [comment]
非常感谢！老哥给力！

**Comment by zhou-wj** [comment]
> 您好，目前镜像还没有考虑docker 内使用其他用户的场景，此问题我会继续跟进，可以暂时先用容器内root运行。

请问现在docker内可以使用非root用户运行了吗？在服务器上只能在docker下用当前用户运行，请问有什么解决方案可以使用paddle吗？

paddle版本：paddlepaddle-gpu==1.4.1.post97
非root用户运行报错如下：

> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/__init__.py", line 25, in <module>
    import paddle.dataset
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/dataset/__init__.py", line 18, in <module>
    import paddle.dataset.mnist
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/dataset/mnist.py", line 23, in <module>
    import paddle.dataset.common
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/dataset/common.py", line 55, in <module>
    must_mkdirs(DATA_HOME)
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/dataset/common.py", line 48, in must_mkdirs
    os.makedirs(DATA_HOME)
  File "/usr/local/python3/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/python3/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/python3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'

**Comment by Yajing-Z** [comment]
同问，现在docker内可以使用非root用户运行paddlepaddle了吗？有什么解决办法能够在非root用户下运行paddlepaddle?
paddle版本：docker pull paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7

 File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dataloader/__init__.py", line 17, in <module>
    from . import dataset
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/dataloader/dataset.py", line 18, in <module>
    import paddle.dataset.common
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/dataset/__init__.py", line 18, in <module>
    import paddle.dataset.mnist
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/dataset/mnist.py", line 23, in <module>
    import paddle.dataset.common
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/dataset/common.py", line 54, in <module>
    must_mkdirs(DATA_HOME)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/dataset/common.py", line 47, in must_mkdirs
    os.makedirs(DATA_HOME)
  File "/usr/local/python3.5.1/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/python3.5.1/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/python3.5.1/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/root/.cache'

**Comment by SystemErrorWang** [comment]
同样的问题，docker内非root权限跑不起来，和楼上一样mkdir的时候报错
能不能不要import的时候直接mkdir，在调用的时候再mkdir和下载呢？

**Comment by NYcleaner** [comment]
这个问题有解决么？

**Comment by wanghaoran-ucas** [comment]
同问，这个怎么解决

**Comment by NYcleaner** [comment]
修改源代码 将对应的文件的需要下载数据的代码都屏蔽掉 就可以了
