### ISSUE TITLE
seqToseq预测输入数据时报错

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#1023]
报错信息如下：
```
I1227 20:44:49.066433 30847 Util.cpp:158] commandline:  --use_gpu=0
I1227 20:44:49.066570 30847 Util.cpp:132] Calling runInitFunctions
I1227 20:44:49.066891 30847 Util.cpp:146] Call runInitFunctions done.
  File "<string>", line 13
    paddle version:
                 ^
SyntaxError: invalid syntax
[INFO 2016-12-27 20:44:49,263 networks.py:1466] The input order is [source_language_word, sent_id]
[INFO 2016-12-27 20:44:49,263 networks.py:1472] The output order is [__beam_search_predict__]
I1227 20:44:49.476338 30847 GradientMachine.cpp:124] Loading parameters from /home/liujiaxiang/paddle_predit/exp1/thirdparty/pass-00017
Traceback (most recent call last):
  File "model.py", line 57, in <module>
    result = model.predict('头疼怎么办')
  File "model.py", line 51, in predict
    result = self.network.forwardTest([inArg])
  File "/home/liujiaxiang/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/util.py", line 146, in forwardTest
    self.forward(inArgs, outArgs, swig_paddle.PASS_TEST)
  File "/home/liujiaxiang/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 1342, in forward
    return _swig_paddle.GradientMachine_forward(self, *args)
TypeError: in method 'GradientMachine_forward', argument 2 of type 'Arguments const &'
```

我的使用方式如下：
```
class Model():
    def __init__(self, pass_path=None, trg_lang_dict=None):
        if not pass_path:
            pass_path = PASS_PATH
        self.trg_dict = dict()
        for line_count, line in enumerate(open(trg_lang_dict, "r")):
            self.trg_dict[line.strip()] = line_count
        self.network = self.init_network(pass_path)

    def init_network(self, pass_path):
        swig_paddle.initPaddle("--use_gpu=0")
        conf = parse_config(pass_path+"/trainer_config.conf", "is_predict=1")
        network = swig_paddle.GradientMachine.createFromConfigProto(conf.model_config)
        assert isinstance(network, swig_paddle.GradientMachine)  # For code hint.
        network.loadParameters(pass_path)
        return network

    def predict(self, sentence):
        ids = dataprovider._get_ids(sentence, self.trg_dict)
        self.converter = DataProviderConverter([integer_value_sequence(50000)])
        inArg = self.converter.convert([[ids]])
        result = self.network.forwardTest([inArg])
        return result
```

**Comment by jacquesqiao** [comment]
result = self.network.forwardTest([inArg])  ==>  result = self.network.forwardTest(inArg)
这样呢

**Comment by OleNet** [comment]
那就会报这样的错误：
```
I1228 12:02:13.976418 20603 Util.cpp:158] commandline:  --use_gpu=0
I1228 12:02:13.976547 20603 Util.cpp:132] Calling runInitFunctions
I1228 12:02:13.976843 20603 Util.cpp:146] Call runInitFunctions done.
  File "<string>", line 13
    paddle version:
                 ^
SyntaxError: invalid syntax
[INFO 2016-12-28 12:02:14,159 networks.py:1466] The input order is [source_language_word, sent_id]
[INFO 2016-12-28 12:02:14,159 networks.py:1472] The output order is [__beam_search_predict__]
I1228 12:02:14.354822 20603 GradientMachine.cpp:124] Loading parameters from /home/liujiaxiang/paddle_predict/exp1/thirdparty/pass-00017
F1228 12:02:14.411664 20603 NeuralNetwork.cpp:238] Check failed: inArgs.size() == dataLayers_.size() (1 vs. 2)
*** Check failure stack trace: ***
    @     0x7f3bdd068668  google::LogMessage::Fail()
    @     0x7f3bdd0685c0  google::LogMessage::SendToLog()
    @     0x7f3bdd068055  google::LogMessage::Flush()
    @     0x7f3bdd06ae16  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3bdc70368a  paddle::NeuralNetwork::forward()
    @     0x7f3bdc697cd6  _wrap_GradientMachine_forward
    @           0x4b4cb9  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b5d10  PyEval_EvalFrameEx
    @           0x4b5fb8  PyEval_EvalFrameEx
    @           0x4b6b28  PyEval_EvalCodeEx
    @           0x4b6c52  PyEval_EvalCode
    @           0x4e1c7d  PyRun_FileExFlags
    @           0x4e3501  PyRun_SimpleFileExFlags
    @           0x4159dd  Py_Main
    @     0x7f3be440abd5  __libc_start_main
    @           0x414b71  (unknown)
已放弃
```

**Comment by OleNet** [comment]
我用的就是demo的网络：seqToseq_net.py

```
def gru_encoder_decoder(data_conf,
                        is_generating,
                        word_vector_dim=512,
                        encoder_size=512,
                        decoder_size=512,
                        beam_size=3,
                        max_length=250):
    """
    A wrapper for an attention version of GRU Encoder-Decoder network
    is_generating: whether this config is used for generating
    encoder_size: dimension of hidden unit in GRU Encoder network
    decoder_size: dimension of hidden unit in GRU Decoder network
    word_vector_dim: dimension of word vector
    beam_size: expand width in beam search
    max_length: a stop condition of sequence generation
    """
    for k, v in data_conf.iteritems():
        globals()[k] = v
    source_dict_dim = len(open(src_dict_path, "r").readlines())
    target_dict_dim = len(open(trg_dict_path, "r").readlines())
    gen_trans_file = gen_result

    src_word_id = data_layer(name='source_language_word', size=source_dict_dim)
    src_embedding = embedding_layer(
        input=src_word_id,
        size=word_vector_dim,
        param_attr=ParamAttr(name='_source_language_embedding'))
    src_forward = simple_gru(input=src_embedding, size=encoder_size)
    src_backward = simple_gru(
        input=src_embedding, size=encoder_size, reverse=True)
    encoded_vector = concat_layer(input=[src_forward, src_backward])

    with mixed_layer(size=decoder_size) as encoded_proj:
        encoded_proj += full_matrix_projection(input=encoded_vector)

    backward_first = first_seq(input=src_backward)
    with mixed_layer(
            size=decoder_size,
            act=TanhActivation(), ) as decoder_boot:
        decoder_boot += full_matrix_projection(input=backward_first)
    def gru_decoder_with_attention(enc_vec, enc_proj, current_word):
        decoder_mem = memory(
            name='gru_decoder', size=decoder_size, boot_layer=decoder_boot)

        context = simple_attention(
            encoded_sequence=enc_vec,
            encoded_proj=enc_proj,
            decoder_state=decoder_mem, )

        with mixed_layer(size=decoder_size * 3) as decoder_inputs:
            decoder_inputs += full_matrix_projection(input=context)
            decoder_inputs += full_matrix_projection(input=current_word)

        gru_step = gru_step_layer(
            name='gru_decoder',
            input=decoder_inputs,
            output_mem=decoder_mem,
            size=decoder_size)
        with mixed_layer(
                size=target_dict_dim, bias_attr=True,
                act=SoftmaxActivation()) as out:
            out += full_matrix_projection(input=gru_step)
        return out

    decoder_group_name = "decoder_group"
    group_inputs = [
        StaticInput(
            input=encoded_vector, is_seq=True), StaticInput(
                input=encoded_proj, is_seq=True)
    ]

    if not is_generating:
        trg_embedding = embedding_layer(
            input=data_layer(
                name='target_language_word', size=target_dict_dim),
            size=word_vector_dim,
            param_attr=ParamAttr(name='_target_language_embedding'))

        # For decoder equipped with attention mechanism, in training,
        # target embeding (the groudtruth) is the data input,
        # while encoded source sequence is accessed to as an unbounded memory.
        # Here, the StaticInput defines a read-only memory
        # for the recurrent_group.
        decoder = recurrent_group(
            name=decoder_group_name,
            step=gru_decoder_with_attention,
            input=group_inputs)

        lbl = data_layer(name='target_language_next_word', size=target_dict_dim)
        cost = classification_cost(input=decoder, label=lbl)
        outputs(cost)
    else:
        # In generation, the decoder predicts a next target word based on
        # the encoded source sequence and the last generated target word.

        # The encoded source sequence (encoder's output) must be specified by

        # StaticInput, which is a read-only memory.
        # Embedding of the last generated word is automatically gotten by
        # GeneratedInputs, which is initialized by a start mark, such as <s>,
        # and must be included in generation.

        trg_embedding = GeneratedInput(
            size=target_dict_dim,
            embedding_name='_target_language_embedding',
            embedding_size=word_vector_dim)
        group_inputs.append(trg_embedding)

        beam_gen = beam_search(
            name=decoder_group_name,
            step=gru_decoder_with_attention,
            input=group_inputs,
            bos_id=0,
            eos_id=1,
            beam_size=beam_size,
            max_length=max_length)

        seqtext_printer_evaluator(
            input=beam_gen,
            id_input=data_layer(
                name="sent_id", size=1),
            dict_file=trg_dict_path,
            result_file=gen_trans_file)
        outputs(beam_gen)
```

**Comment by luotao1** [comment]
请贴出dataprovider.py和预测的命令。
```
inArgs.size() == dataLayers_.size() (1 vs. 2)
```
应该是dataprovider.py里面只传了1个layer。而网络配置里要2个。

**Comment by OleNet** [comment]
dataprovider.py : 
```
from paddle.trainer.PyDataProvider2 import *

UNK_IDX = 2
START = "<s>"
END = "<e>"


def hook(settings, src_dict, trg_dict, file_list, **kwargs):
    # job_mode = 1: training mode
    # job_mode = 0: generating mode
    settings.job_mode = trg_dict is not None
    settings.src_dict = src_dict
    settings.logger.info("src dict len : %d" % (len(settings.src_dict)))
    settings.sample_count = 0

    if settings.job_mode:
        settings.trg_dict = trg_dict
        settings.slots = [
            integer_value_sequence(len(settings.src_dict)),
            integer_value_sequence(len(settings.trg_dict)),
            integer_value_sequence(len(settings.trg_dict))
        ]
        settings.logger.info("trg dict len : %d" % (len(settings.trg_dict)))
    else:
        settings.slots = [
            integer_value_sequence(len(settings.src_dict)),
            integer_value_sequence(len(open(file_list[0], "r").readlines()))
        ]


def _get_ids(s, dictionary):
    words = s.strip().split()
    return [dictionary[START]] + \
           [dictionary.get(w, UNK_IDX) for w in words] + \
           [dictionary[END]]


@provider(init_hook=hook, pool_size=50000)
def process(settings, file_name):
    with open(file_name, 'r') as f:
        for line_count, line in enumerate(f):
            line_split = line.strip().split('\t')
            if settings.job_mode and len(line_split) <= 2:
                continue
            src_seq = line_split[0]  # one source sequence
            src_ids = _get_ids(src_seq, settings.src_dict)

            if settings.job_mode:
                trg_seq = line_split[1]  # one target sequence
                trg_words = trg_seq.split()
                trg_ids = [settings.trg_dict.get(w, UNK_IDX) for w in trg_words]

                # remove sequence whose length > 80 in training mode
                if len(src_ids) > 80 or len(trg_ids) > 80:
                    continue
                trg_ids_next = trg_ids + [settings.trg_dict[END]]
                trg_ids = [settings.trg_dict[START]] + trg_ids
                yield src_ids, trg_ids, trg_ids_next
            else:
                yield src_ids, [line_count]
```

**Comment by OleNet** [comment]
上面的Model类就是我的预测类：
调用方式如下：
if __name__ == '__main__':
    model = Model(PASS_PATH, VCB_PATH)
    result = model.predict('头疼怎么办')
    print result

**Comment by OleNet** [comment]
问题解决了。
以下是解决思路和方法：

**Comment by OleNet** [comment]
先贴个这个：

> 28. 训练模型报错：NeuralNetwork.cpp:167] Check failed: inArgs.size() == dataLayers_.size() (2 vs. 5)
> 网络配置错误，用户在Inputs列表中指定了5个slot，但输入的数据只有2个slot。我们强烈推荐用户在配置完网络后，仔细检查一遍，最好画个网络连接示意图。
> （1）预处理数据中的slot对应网络配置中type="data"的Layer（注意：数据预处理时，label也是一个slot）
> （2）对于ProtoBuf数据，预处理生成的二进制数据会把label放到行尾。例如，假设预处理前的样本为label;slot0;slot1;，预处理后变成slot0;slot1;label
> （3）网络配置中Inputs列表的顺序和预处理后数据的slot排列顺序相同。例如，Inputs("input0", "input1", "label")，其中Layer input0对应slot0，Layer input1对应slot1，Layer label对于label

**Comment by OleNet** [comment]
问题出现在  **self.converter.convert** 这句话
```
    def predict(self, sentence):
        ids = dataprovider._get_ids(sentence, self.trg_dict)
        self.converter = DataProviderConverter([integer_value_sequence(50000)])
        inArg = self.converter.convert([[ids]])
        result = self.network.forwardTest([inArg])
        return result
```
根据网络文件的定义，网络的输入应该是[ids, [line_count]]的格式才可以，之前的代码显然少了一个元素

**Comment by OleNet** [comment]
改过的代码：
```
import sys
import json
from py_paddle import swig_paddle, DataProviderConverter
from paddle.trainer.PyDataProvider2 import *
from paddle.trainer.config_parser import *
from operator import itemgetter
from seqToseq_net import *
import dataprovider


HERE = os.path.split(os.path.realpath(__file__))[0]
PASS_PATH = os.path.join(HERE, 'pass-00017')
VCB_PATH = os.path.join(HERE, 'vcb/trg.dict')


class Model():

    def __init__(self, pass_path=None, trg_lang_dict=None):
        if not pass_path:
            pass_path = PASS_PATH
        self.trg_dict = dict()
        self.inv_dict = dict()
        for line_count, line in enumerate(open(trg_lang_dict, "r")):
            self.trg_dict[line.strip()] = line_count
            self.inv_dict[line_count] = line.strip()
        self.network = self.init_network(pass_path)

    def init_network(self, pass_path):
        swig_paddle.initPaddle("--use_gpu=0")
        conf = parse_config(pass_path+"/trainer_config.conf", "is_predict=1")
        network = swig_paddle.GradientMachine.createFromConfigProto(conf.model_config)
        assert isinstance(network, swig_paddle.GradientMachine)  # For code hint.
        network.loadParameters(pass_path)
        return network

    def predict(self, sentence):
        ids = dataprovider._get_ids(sentence, self.trg_dict)
        self.converter = DataProviderConverter([integer_value_sequence(50000), \
                                                integer_value_sequence(50)])
        inArg = self.converter.convert(self.get_data(sentence))
        result = self.network.forwardTest(inArg)
        return result
    def speak(self, result):
        ids = self.get_ids(result)
        if ids is None:
            return None
        words = self.map_id(ids)
        return ''.join(words)

    def get_ids(self, result):
        if len(result) <= 0: return None
        if 'id' not in result[0]: return None
        return result[0]['id']

    def map_id(self, ids):
        return [self.inv_dict[max(int(i),0)] for i in ids]

    def get_data(self, sentence):
        """
        Get input data of paddle format.
        """
        ids = dataprovider._get_ids(sentence, self.trg_dict)
        yield ids, [1]


if __name__ == '__main__':
    model = Model(PASS_PATH, VCB_PATH)
    result = model.predict('你的输入语句')
    print model.speak(result)
```
