### ISSUE TITLE
跑chinese_ner模型，在最后出现了异常

### ISSUE THREAD

**Issue by xymyeah** [PaddlePaddle/Paddle#10252]
```
precision:0.897720033378, recall:0.863661475778, f1:0.880361471757                                                                                                       
pass_id353time_cost:503.007745981                                                                                                                                        
Pass353finished.!                                                                                                                                                        
Traceback (most recent call last):                                                                                                                                       
  File "trainer.py", line 338, in <module>                                                                                                                               
    parallel=True)                                                                                                                                                       
  File "trainer.py", line 300, in main                                                                                                                                   
    exe, chunk_evaluator, inference_program, test_reader, place, [num_infer_chunks.name, num_label_chunks.name, num_correct_chunks.name])                                
  File "trainer.py", line 188, in test                                                                                                                                   
    share_vars_from=exe)                                                                                                                                                 
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 127, in __init__                                                                 
    customize_loss_grad)                                                                                                                                                 
paddle.fluid.core.EnforceNotMet: CUDNN_STATUS_INTERNAL_ERROR at [/paddle/paddle/fluid/platform/device_context.cc:156]                                                    
PaddlePaddle Call Stacks:                                                                                                                                                
0       0x7fee929f1246p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486                                      
1       0x7fee9372ac24p paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace) + 3908                                                       
2       0x7fee92a99e12p paddle::platform::NCCLContextMap::NCCLContextMap(std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::plat
form::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant
::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost
::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::vari
ant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boo
st::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::va
riant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, 
boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail:
:variant::void_> > > const&) + 386                                                                                                                                       
3       0x7fee92a966b3p paddle::framework::ParallelExecutor::ParallelExecutor(unsigned long, bool, std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platfo
rm::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::voi
d_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::det
ail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::
void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::plat
form::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant
::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost
::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::vari
ant::void_, boost::detail::variant::void_> > > const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > 
const&, std::unordered_set<std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::string> > const&, paddle::framework::ProgramDesc const&, 
std::string const&, paddle::framework::Scope*, std::vector<paddle::framework::Scope*, std::allocator<paddle::framework::Scope*> > const&, bool, bool) + 323              
4       0x7fee929e80e7p                                                                                                                                                  
5       0x7fee92a02354p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596                                                                          
6       0x7feeef341273p PyObject_Call + 83                                                                                                                               
7       0x7feeef3538afp                                                                                                                                                  
8       0x7feeef341273p PyObject_Call + 83                                                                                                                               
9       0x7feeef3ad5d0p                                                                                                                                                  
10      0x7feeef3a4168p                                                                                                                                                  
11      0x7feeef341273p PyObject_Call + 83               
```

**Comment by kuke** [comment]
是不是出现了显存溢出的情况？如果长时间才挂掉的话，比较难以定位问题。。。

**Comment by panyx0718** [comment]
能贴下模型代码吗?似乎是ParallelExecutor被多次创建了？

**Comment by chengduoZH** [comment]
@xymyeah issue中描述的问题解决了吗？

**Comment by chengduoZH** [comment]
该issue长时间没有回复，再切关闭了。如需继续讨论，请再打开。
