### ISSUE TITLE
issue while using flowers dataset

### ISSUE THREAD

**Issue by putcn** [PaddlePaddle/Paddle#10298]
looks cv2 failed to import when trying to use flowers dataset in vgg16 test.
and the import error is ignored due to the following line in paddle/v2/image.py

``` python
try:
    import cv2
except ImportError:
    cv2 = None

```
the error message is as follows:

```
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
    r = mapper(sample)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/dataset/flowers.py", line 63, in default_mapper
    img = load_image_bytes(img)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 131, in load_image_bytes
    img = cv2.imdecode(file_bytes, flag)
AttributeError: 'NoneType' object has no attribute 'imdecode'
```

currently the opencv dependency is resolved by 
``` dockerfile
RUN pip install opencv-python
```
not sure if we need to change to/ add
```dockerfile
RUN apt install -y python-opencv
```

**Comment by luotao1** [comment]
After I change to `RUN apt install -y python-opencv`, its OK now.
