### ISSUE TITLE
vgg16 test fails

### ISSUE THREAD

**Issue by putcn** [PaddlePaddle/Paddle#10302]
here is the command to start the test
```bash
nvidia-docker run -it --rm putcn/vgg16_test:latest-gpu-dist --local yes --device GPU --batch_size 80 --data_set flowers
```
the error is 
```
Traceback (most recent call last):
  File "vgg16_fluid.py", line 289, in <module>
    main()
  File "vgg16_fluid.py", line 228, in main
    train_loop(exe, fluid.default_main_program())
  File "vgg16_fluid.py", line 195, in train_loop
    fetch_list=[avg_cost, batch_acc, batch_size])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 336, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: enforce allocating <= available failed, 10484135494 > 1346502400
 at [/paddle/paddle/fluid/platform/gpu_info.cc:119]
```

any clue?

**Comment by putcn** [comment]
thanks! @helinwang
