### ISSUE TITLE
cannot import name CUDAPinnedPlace

### ISSUE THREAD

**Issue by zhxfl** [PaddlePaddle/Paddle#10447]
After update paddle develop, get the followingtraceback 
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    import paddle.fluid as fluid
  File "xxxx/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 46, in <module>
    from core import LoDTensor, CPUPlace, CUDAPlace, CUDAPinnedPlace
ImportError: cannot import name CUDAPinnedPlace

**Comment by Yancey1989** [comment]
Please try the following steps:
1. rebase the latest code
1. find `core.so` in the source code folder and delete it 
1. rebuild paddle

**Comment by zhxfl** [comment]
fix,tks
