### ISSUE TITLE
读取灰度图错误

### ISSUE THREAD

**Issue by sky-2016yty** [PaddlePaddle/Paddle#10555]
在调用img = paddle.image.load_and_transform(image_path, 60, 50, True)报错:
Traceback (most recent call last):
  File "/home/sosky/PycharmProjects/vgg16-nxpcar/infer.py", line 46, in <module>
    out=out, imageSize=imageSize)
  File "/home/sosky/PycharmProjects/vgg16-nxpcar/infer.py", line 18, in to_prediction
    img = paddle.image.load_and_transform(image_path, 60, 50, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 363, in load_and_transform
    im = simple_transform(im, resize_size, crop_size, is_train, is_color, mean)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 307, in simple_transform
    im = resize_short(im, resize_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 166, in resize_short
    assert im.shape[-1] == 1 or im.shape[-1] == 3
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by seiriosPlus** [comment]
能贴一下完整代码么， 目前看到的情况是未知错误导致了NoneType
