### ISSUE TITLE
Python unitest "test_network_with_dtype" keeps failing.

### ISSUE THREAD

**Issue by wanglei828** [PaddlePaddle/Paddle#10604]
When running "test_all_ops", the "test_network_with_dtype" keeps failing. The error message as follows:
======================================================================
ERROR: test_cpu (test_network_with_dtype.TestNetWithDtype)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_network_with_dtype.py", line 58, in test_cpu
    self.set_network()
  File "test_network_with_dtype.py", line 30, in set_network
    self.x = fluid.layers.data(name='x', shape=[13], dtype=self.dtype)
  File "/paddle/build/python/paddle/fluid/layers/io.py", line 82, in data
    is_data=True)
  File "/paddle/build/python/paddle/fluid/layer_helper.py", line 344, in create_global_variable
    *args, persistable=persistable, **kwargs)
  File "/paddle/build/python/paddle/fluid/framework.py", line 763, in create_var
    var = Variable(block=self, *args, **kwargs)
  File "/paddle/build/python/paddle/fluid/framework.py", line 195, in __init__
    "matched.".format(self.name, old_shape, shape))
ValueError: Variable x has been created before. the previous shape is (-1L, 3L); the new shape is (-1, 13). They are not matched.

======================================================================
ERROR: test_gpu (test_network_with_dtype.TestNetWithDtype)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_network_with_dtype.py", line 65, in test_gpu
    self.set_network()
  File "test_network_with_dtype.py", line 30, in set_network
    self.x = fluid.layers.data(name='x', shape=[13], dtype=self.dtype)
  File "/paddle/build/python/paddle/fluid/layers/io.py", line 82, in data
    is_data=True)
  File "/paddle/build/python/paddle/fluid/layer_helper.py", line 344, in create_global_variable
    *args, persistable=persistable, **kwargs)
  File "/paddle/build/python/paddle/fluid/framework.py", line 763, in create_var
    var = Variable(block=self, *args, **kwargs)
  File "/paddle/build/python/paddle/fluid/framework.py", line 195, in __init__
    "matched.".format(self.name, old_shape, shape))
ValueError: Variable x has been created before. the previous shape is (-1L, 3L); the new shape is (-1, 13). They are not matched.

**Comment by wanglei828** [comment]
Hi, I don't think this has been fixed. In CI and local dev, we can still see this test failure. 
The error message as follows:
======================================================================
ERROR: test_cpu (test_network_with_dtype.TestNetWithDtype)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_network_with_dtype.py", line 63, in test_cpu
    self.run_net_on_place(place)
  File "test_network_with_dtype.py", line 49, in run_net_on_place
    exe.run(fluid.default_startup_program())
  File "/paddle/build/python/paddle/fluid/executor.py", line 337, in run
    fetch_var_name=fetch_var_name)
  File "/paddle/build/python/paddle/fluid/executor.py", line 209, in _add_feed_fetch_ops
    tmp_program = program.clone()
  File "/paddle/build/python/paddle/fluid/framework.py", line 1055, in clone
    p.sync_with_cpp()
  File "/paddle/build/python/paddle/fluid/framework.py", line 1160, in sync_with_cpp
    block.sync_with_cpp()
  File "/paddle/build/python/paddle/fluid/framework.py", line 909, in sync_with_cpp
    op = Operator(self, op_desc)
  File "/paddle/build/python/paddle/fluid/framework.py", line 409, in __init__
    "`type` to initilized an Operator can not be None.")
ValueError: `type` to initilized an Operator can not be None.

======================================================================
ERROR: test_gpu (test_network_with_dtype.TestNetWithDtype)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_network_with_dtype.py", line 70, in test_gpu
    self.run_net_on_place(place)
  File "test_network_with_dtype.py", line 49, in run_net_on_place
    exe.run(fluid.default_startup_program())
  File "/paddle/build/python/paddle/fluid/executor.py", line 337, in run
    fetch_var_name=fetch_var_name)
  File "/paddle/build/python/paddle/fluid/executor.py", line 209, in _add_feed_fetch_ops
    tmp_program = program.clone()
  File "/paddle/build/python/paddle/fluid/framework.py", line 1055, in clone
    p.sync_with_cpp()
  File "/paddle/build/python/paddle/fluid/framework.py", line 1160, in sync_with_cpp
    block.sync_with_cpp()
  File "/paddle/build/python/paddle/fluid/framework.py", line 909, in sync_with_cpp
    op = Operator(self, op_desc)
  File "/paddle/build/python/paddle/fluid/framework.py", line 409, in __init__
    "`type` to initilized an Operator can not be None.")
ValueError: `type` to initilized an Operator can not be None.
