### ISSUE TITLE
docker 指定使用哪个 GPU的问题

### ISSUE THREAD

**Issue by linrio** [PaddlePaddle/Paddle#10661]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

## 问题一：
1。信息：
```
$ uname -a
Linux ccrfox246 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

(venv2) linlf@ccrfox246:~/project/linlf/$ nvidia-smi
Tue May 15 17:09:28 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:85:00.0 Off |                    0 |
| N/A   56C    P0    91W / 149W |   3025MiB / 11439MiB |     81%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:86:00.0 Off |                    0 |
| N/A   38C    P0    74W / 149W |   1649MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 00000000:8C:00.0 Off |                    0 |
| N/A   50C    P0    60W / 149W |   1649MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 00000000:8D:00.0 Off |                    0 |
| N/A   39C    P0    73W / 149W |   1649MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+


```

2 . 我的机器上有4块GPU，我目前使用了GPU-0运行docker，我想利用第二块GPU跑 MLperf 的 sentiment_analysis workload，同样也是在docker执行， 我的操作是：

```
$ export CUDA_VISIBLE_DEVICES=2
$ export NV_GPU=2
$ export FLAGS_fraction_of_gpu_memory_to_use=0.16
$ sudo nvidia-docker run -it -v `pwd`:/paddle sidgoyal78/paddle:benchmark12042018 /bin/bash
```
但是报错了：

```
root@402f3708b9fe:/paddle/sentiment_analysis/paddle# ./run_and_time.sh 1
STARTING TIMING RUN AT 2018-05-14 01:16:21 AM
Running sentiment benchmark with seed 1
Cache file /root/.cache/paddle/dataset/imdb/aclImdb_v1.tar.gz not found, downloading http://ai.stanford.edu/%7Eamaas/data/sentiment/aclImdb_v1.tar.gz
[==================================================]Traceback (most recent call last):
  File "train.py", line 217, in <module>
    save_dirname="understand_sentiment_conv.inference.model")
  File "train.py", line 191, in main
    save_dirname=save_dirname)
  File "train.py", line 176, in train
    train_loop(fluid.default_main_program())
  File "train.py", line 140, in train_loop
    exe.run(fluid.default_startup_program())
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 336, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: enforce allocating <= available failed, 10484135494 > 8700690176
 at [/paddle/paddle/fluid/platform/gpu_info.cc:119]
PaddlePaddle Call Stacks: 
0       0x7f82064e0628p paddle::platform::GpuMaxChunkSize() + 5080
1       0x7f820421496dp paddle::memory::GetGPUBuddyAllocator(int) + 253
2       0x7f8204214b3bp void* paddle::memory::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace, unsigned long) + 43
3       0x7f820416fdc8p paddle::framework::Tensor::PlaceholderImpl<paddle::platform::CUDAPlace>::PlaceholderImpl(paddle::platform::CUDAPlace, unsigned long, std::type_index) + 72
4       0x7f82041766a0p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::type_index) + 336
5       0x7f82044af2b9p paddle::operators::FillConstantOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1177
6       0x7f82042186bep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool) + 414
7       0x7f8204219a57p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 103
8       0x7f820418a253p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 579
9       0x7f8204186e14p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
10            0x4c37edp PyEval_EvalFrameEx + 31165
11            0x4b9ab6p PyEval_EvalCodeEx + 774
12            0x4c16e7p PyEval_EvalFrameEx + 22711
13            0x4b9ab6p PyEval_EvalCodeEx + 774
14            0x4c1e6fp PyEval_EvalFrameEx + 24639
15            0x4b9ab6p PyEval_EvalCodeEx + 774
16            0x4c16e7p PyEval_EvalFrameEx + 22711
17            0x4b9ab6p PyEval_EvalCodeEx + 774
18            0x4c16e7p PyEval_EvalFrameEx + 22711
19            0x4b9ab6p PyEval_EvalCodeEx + 774
20            0x4eb30fp
21            0x4e5422p PyRun_FileExFlags + 130
22            0x4e3cd6p PyRun_SimpleFileExFlags + 390
23            0x493ae2p Py_Main + 1554
24      0x7f823b87c830p __libc_start_main + 240
25            0x4933e9p _start + 41

ENDING TIMING RUN AT 2018-05-14 01:35:19 AM
RESULT,sentiment,1,1138,,2018-05-14 01:16:21 AM
```

我也试了export NV_GPU=1，export NV_GPU=3，依然没法使用。对应的问题，[mlperf #40](https://github.com/mlperf/reference/issues/40)
我参考了 #6725,  和 #9230 的方法，但是没有用。

## 问题二：
每一次重启docker时都会重新拉取数据，请问已经下载的数据如何保存在本地？
```
Cache file /root/.cache/paddle/dataset/imdb/aclImdb_v1.tar.gz not found, downloading http://ai.stanford.edu/%7Eamaas/data/sentiment/aclImdb_v1.tar.gz
[==================================================]
```

**Comment by pkuyym** [comment]
从log上看是显存不够，所以想确认一下，如果停掉gpu0的任务，可以正常运行对吧
```
paddle.fluid.core.EnforceNotMet: enforce allocating <= available failed, 10484135494 > 8700690176
 at [/paddle/paddle/fluid/platform/gpu_info.cc:119]
PaddlePaddle Call Stacks: 
```
docker gpu隔离的话，有尝试过这个文档么：
https://github.com/NVIDIA/nvidia-docker/wiki/GPU-isolation-(version-1.0)

**Comment by pkuyym** [comment]
启动docker的时候试试把本地的文件映射到对应路径
`docker run -v ${LOCAL_PATH}/imdb/: /root/.cache/paddle/dataset/imdb/ ...`
```
问题二：
每一次重启docker时都会重新拉取数据，请问已经下载的数据如何保存在本地？

Cache file /root/.cache/paddle/dataset/imdb/aclImdb_v1.tar.gz not found, downloading http://ai.stanford.edu/%7Eamaas/data/sentiment/aclImdb_v1.tar.gz
[==================================================]
```

**Comment by linrio** [comment]
可以运行，但是没法指定GPU。我使用了 NV_GPU=0,1 指定GPU了。
