### ISSUE TITLE
使用gpu训练时，提示： No module named  _swig_paddle

### ISSUE THREAD

**Issue by xianming90** [PaddlePaddle/Paddle#10788]
自己拉最新版本编译的
环境 ：ubuntu16.04， python2.7 ,cuda9.1 ,cudnn 5.0 ，nvida driver:390
编译选项，已经开启 gpu, swig_py 选项开启，其它默认 

Traceback (most recent call last):
  File "/media/yanfa/data/userData/liuxianming/workplace/python/paddlepaddleDemo/models-develop/ssd/train.py", line 71, in <module>
    paddle.init(use_gpu=True, trainer_count=4)
  File "/home/yanfa/.local/lib/python2.7/site-packages/paddle/v2/__init__.py", line 128, in init
    import py_paddle.swig_paddle as api
  File "/home/yanfa/.local/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/home/yanfa/.local/lib/python2.7/site-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/home/yanfa/.local/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 17, in <module>
    _swig_paddle = swig_import_helper()
  File "/home/yanfa/.local/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 16, in swig_import_helper
    return importlib.import_module('_swig_paddle')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _swig_paddle

**Comment by jacquesqiao** [comment]
貌似有两个Python？
`/home/yanfa/.local/lib/python2.7/site-packages/` 和 `/usr/lib/python2.7/`

**Comment by xianming90** [comment]
修改python环境过后，还是一样的问题

**Comment by xianming90** [comment]
Traceback (most recent call last):
  File "/media/yanfa/data/userData/liuxianming/workplace/python/paddlepaddleDemo/book/03.image_classification/train.py", line 136, in <module>
    main()
  File "/media/yanfa/data/userData/liuxianming/workplace/python/paddlepaddleDemo/book/03.image_classification/train.py", line 30, in main
    paddle.init(use_gpu=True, trainer_count=1)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/__init__.py", line 128, in init
    import py_paddle.swig_paddle as api
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 17, in <module>
    _swig_paddle = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 16, in swig_import_helper
    return importlib.import_module('_swig_paddle')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _swig_paddle

**Comment by jacquesqiao** [comment]
`/usr/local/lib/python2.7/dist-packages/py_paddle/_swig_paddle.so`
有这个文件么

**Comment by xianming90** [comment]
没有此文件？

**Comment by xianming90** [comment]
按照你的说法做，依然报此错误。

**Comment by jacquesqiao** [comment]
最新的报错是 
```
 libmklml_intel.so cannot open shared object file:No such file or directory
```
怀疑mklml有问题，正在测试编译时候指定  -DWITH_MKL=OFF
