### ISSUE TITLE
从文件夹中读取模型parameters

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#10838]
模型的tar.gz文件删除了，只留了解压后的文件夹。问下python环境下用什么函数能一次读取解压文件夹中的所有参数给parameters?

**Comment by dzhwinter** [comment]
tar  -cvf 打包一下，可以满足需求吗

**Comment by hyo009** [comment]
自己再打包成tar.gz后读取时报
```
Traceback (most recent call last):
  File "traffic_predict_cloud_beijing.py", line 696, in <module>
    parameters = paddle.parameters.Parameters.from_tar(f)
  File "/home/map01/.jumbo/lib/python2.7/site-packages/paddle/v2/parameters.py", line 382, in from_tar
    f = tar.extractfile(param_name)
  File "/home/map01/.jumbo/lib/python2.7/tarfile.py", line 2112, in extractfile
    tarinfo = self.getmember(member)
  File "/home/map01/.jumbo/lib/python2.7/tarfile.py", line 1796, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename u'_proj_cur_stream' not found"
```

**Comment by dzhwinter** [comment]
看着是tarfile包出错了，打包目录对了吗？ 本地随便打包一个文件，用tarfile读取一下能成功么

**Comment by Yancey1989** [comment]
这个issue很久没有更新的信息，先关闭它了，如仍然有问题请随时打开它，多谢！
