### ISSUE TITLE
cann't set name of some fluid layers

### ISSUE THREAD

**Issue by walloollaw** [PaddlePaddle/Paddle#10996]
there is no way so set `name` of `fluid.layers.topk`,  which is supported in other layers like: `fluid.layers.conv2d`

now, i found these layers is not supported:
- topk 
- softmax
- concat
- dropout
- (maybe there are other layers that neither support name setting)

test code:
```
import sys
import numpy as np


def get_data(shape=[1, 1024]):
    sz = reduce(lambda x,y: x*y, shape)
    d = range(sz)
    data = 1 + np.array(d, dtype='float32').reshape(shape)
    return data


def test_topk():
    import paddle.fluid as fluid

    data = get_data()

    x = fluid.layers.data(name='x', shape=data.shape[1:], dtype='float32')
    out, _ = fluid.layers.topk(input=x, k=1, name='topk')

    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    fetch_list = [out]

    exe.run(fluid.default_startup_program())

    program = fluid.default_main_program()
    #for v in program.list_vars():
    #    print v

    y = exe.run(
            program=program,
            feed={'x': data},
            fetch_list=fetch_list)

    print('results:')
    print y

test_topk()
```

results:
```
$>python test_topk.py 

Traceback (most recent call last):
  File "test_topk.py", line 39, in <module>
    test_topk()
  File "test_topk.py", line 19, in test_topk
    out, _ = fluid.layers.topk(input=x, k=1, name='topk')
TypeError: topk() got an unexpected keyword argument 'name'
```

**Comment by chengduoZH** [comment]
Thanks for your reminding. 
In fact, layer's name is meanless in most case, users mostly take care of the name of var.

**Comment by walloollaw** [comment]
i checked the code in paddle, the parameter 'name' passed to fluid.layers.xxx will affect the name of output variable.
For me, it's useful when convert model from Caffe to Fluid. So, i commited a PR for the layers that i want to set name. @chengduoZH

**Comment by chengduoZH** [comment]
I see, thanks @walloollaw .
