### ISSUE TITLE
运行快速入门里的例子报错ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ftry** [PaddlePaddle/Paddle#11002]
错误细节：
Traceback (most recent call last):
  File "/home/puncy/PycharmProjects/paai/housing1.py", line 4, in <module>
    paddle.init(use_gpu=False, trainer_count=1)
  File "/home/puncy/paddle/local/lib/python2.7/site-packages/paddle/v2/__init__.py", line 128, in init
    import py_paddle.swig_paddle as api
  File "/home/puncy/paddle/local/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/home/puncy/paddle/local/lib/python2.7/site-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/home/puncy/paddle/local/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/home/puncy/paddle/local/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory
此文件libmklml_intel.so去那里可以下载

**Comment by luotao1** [comment]
duplicated with #10989

**Comment by ftry** [comment]
你直接把文件发我吧！这个真没有

**Comment by ftry** [comment]
文件我找到了！不是文件缺失的bug

**Comment by luotao1** [comment]
@ftry 请问是在哪个路径下找到的？

**Comment by chengduoZH** [comment]
This issue is similar with https://github.com/PaddlePaddle/Paddle/issues/11008.

**Comment by Albelt** [comment]
问题同上，请问怎么解决的？
