### ISSUE TITLE
fluid可学习layer设置name无效

### ISSUE THREAD

**Issue by bipedalBit** [PaddlePaddle/Paddle#11047]
修改[fuid图像分类例子](https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification)中的se_resnext.py，为所有可学习layer设置name。
在train.py执行`fluid.io.save_persistables(exe, model_path)`之前执行`print list(fluid.default_main_program().list_vars())`，发现各layer的name没有设置成功。
但是执行infer.py中`fluid.io.load_vars(exe, args.model_dir, predicate=fluid.io.is_persistable)`时，报错如下：
Traceback (most recent call last):
  File "infer.py", line 75, in <module>
    infer(args)
  File "infer.py", line 43, in infer
    fluid.io.load_vars(exe, args.model_dir, predicate=fluid.io.is_persistable)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 187, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 218, in load_vars
    executor.run(load_prog)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 340, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Cannot open file models/se_resnext/0/conv0_conv.w_0 for load op at [/root/Paddle/paddle/fluid/operators/load_op.cc:40]
conv0_conv这个layer name确实是我设置而不是自动命名的。
怎样才能成功修改layer name？

**Comment by kuke** [comment]
你应该可以打开模型保存目录，看下这些参数是否是你的命名来命名的。

**Comment by bipedalBit** [comment]
模型保存目录下，参数文件名与我的命名并不相同，显然是默认的参数命名。

**Comment by bipedalBit** [comment]
```python
def conv_bn_layer(input, num_filters, filter_size, stride=1, groups=1,
                  act=None, name=''):
    conv = fluid.layers.conv2d(
        input=input,
        num_filters=num_filters,
        filter_size=filter_size,
        stride=stride,
        padding=(filter_size - 1) / 2,
        groups=groups,
        act=None,
        param_attr=fluid.param_attr.ParamAttr(
            initializer=fluid.initializer.MSRA()),
        bias_attr=False,
        name=(name + '_conv'))
    return fluid.layers.batch_norm(input=conv, act=act, name=(name + '_bn'))


def squeeze_excitation(input, num_channels, reduction_ratio, name):
    pool = fluid.layers.pool2d(
        input=input, pool_size=0, pool_type='avg', global_pooling=True)
    stdv = 1.0 / math.sqrt(pool.shape[1] * 1.0)
    squeeze = fluid.layers.fc(input=pool,
                              size=num_channels / reduction_ratio,
                              act='relu',
                              name=(name + '_s_fc'),
                              param_attr=fluid.param_attr.ParamAttr(
                                  initializer=fluid.initializer.Uniform(-stdv,
                                                                        stdv)))
    stdv = 1.0 / math.sqrt(squeeze.shape[1] * 1.0)
    excitation = fluid.layers.fc(input=squeeze,
                                 size=num_channels,
                                 act='sigmoid',
                                 name=(name + '_e_fc'),
                                 param_attr=fluid.param_attr.ParamAttr(
                                     initializer=fluid.initializer.Uniform(
                                         -stdv, stdv)))
    scale = fluid.layers.elementwise_mul(x=input, y=excitation, axis=0)
    return scale


def shortcut(input, ch_out, stride, name):
    ch_in = input.shape[1]
    if ch_in != ch_out or stride != 1:
        filter_size = 1
        return conv_bn_layer(input, ch_out, filter_size, stride, name=name)
    else:
        return input


def bottleneck_block(input, num_filters, stride, cardinality, reduction_ratio, name):
    conv0 = conv_bn_layer(
        input=input, num_filters=num_filters, filter_size=1, act='relu', name=(name + '_conv_bn_0'))
    conv1 = conv_bn_layer(
        input=conv0,
        num_filters=num_filters,
        filter_size=3,
        stride=stride,
        groups=cardinality,
        act='relu',
        name=(name + '_conv_bn_1'))
    conv2 = conv_bn_layer(
        input=conv1, num_filters=num_filters * 2, filter_size=1, act=None, name=(name + '_conv_bn_2'))
    scale = squeeze_excitation(
        input=conv2,
        num_channels=num_filters * 2,
        reduction_ratio=reduction_ratio, name=(name + '_se'))

    short = shortcut(input, num_filters * 2, stride, name=(name + '_shortcut'))

    return fluid.layers.elementwise_add(x=short, y=scale, act='relu')


def SE_ResNeXt(input, class_dim, infer=False, layers=50):
    supported_layers = [50, 152]
    if layers not in supported_layers:
        print("supported layers are", supported_layers, \
              "but input layer is ", layers)
        exit()
    if layers == 50:
        cardinality = 32
        reduction_ratio = 16
        depth = [3, 4, 6, 3]
        num_filters = [128, 256, 512, 1024]

        conv = conv_bn_layer(
            input=input, num_filters=64, filter_size=7, stride=2, act='relu', name='conv0')
        conv = fluid.layers.pool2d(
            input=conv,
            pool_size=3,
            pool_stride=2,
            pool_padding=1,
            pool_type='max')
    elif layers == 152:
        cardinality = 64
        reduction_ratio = 16
        depth = [3, 8, 36, 3]
        num_filters = [128, 256, 512, 1024]

        conv = conv_bn_layer(
            input=input, num_filters=64, filter_size=3, stride=2, act='relu', name='conv0')
        conv = conv_bn_layer(
            input=conv, num_filters=64, filter_size=3, stride=1, act='relu', name='conv1')
        conv = conv_bn_layer(
            input=conv, num_filters=128, filter_size=3, stride=1, act='relu', name='conv2')
        conv = fluid.layers.pool2d(
            input=conv, pool_size=3, pool_stride=2, pool_padding=1, \
            pool_type='max')

    for block in range(len(depth)):
        for i in range(depth[block]):
            conv = bottleneck_block(
                input=conv,
                num_filters=num_filters[block],
                stride=2 if i == 0 and block != 0 else 1,
                cardinality=cardinality,
                reduction_ratio=reduction_ratio,
                name=('res_group%d_block%d' % (block, i)))

    pool = fluid.layers.pool2d(
        input=conv, pool_size=7, pool_type='avg', global_pooling=True)
    stdv = 1.0 / math.sqrt(pool.shape[1] * 1.0)
    out = fluid.layers.fc(input=pool,
                          size=class_dim,
                          act='softmax',
                          name='fc0',
                          param_attr=fluid.param_attr.ParamAttr(
                              initializer=fluid.initializer.Uniform(-stdv,
                                                                    stdv)))
    return out
```

**Comment by bipedalBit** [comment]
发现问题出在训练脚本的命令行参数解析阶段，谢谢。
