### ISSUE TITLE
float() argument must be a string or a number

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#11163]
When running the `benchmark/fluid/fluid_benchmark.py` script the following error crops up:

Command:
```
$ python fluid_benchmark.py --model resnet --iterations 2 --pass_num 1 --device CPU --data_set cifar10 --no_test
```

```
Traceback (most recent call last):
  File "fluid_benchmark.py", line 391, in <module>
    main()
  File "fluid_benchmark.py", line 382, in main
    train(*train_args)
  File "fluid_benchmark.py", line 240, in train
    if not args.no_test and batch_acc != None:
  File "/paddle/build/python/paddle/fluid/layers/math_op_patch.py", line 118, in __impl__
    self.block, value=other_var, dtype=lhs_dtype)
  File "/paddle/build/python/paddle/fluid/layers/math_op_patch.py", line 49, in create_scalar
    return create_tensor(block, value, dtype, shape=[1])
  File "/paddle/build/python/paddle/fluid/layers/math_op_patch.py", line 34, in create_tensor
    value = float(value)
TypeError: float() argument must be a string or a number
```

```
----------- resnet Configuration Arguments -----------
batch_size: 32
data_format: NCHW
data_set: cifar10
device: CPU
gpus: 1
infer_only: False
iterations: 2
learning_rate: 0.001
memory_optimize: False
model: resnet
no_test: False
pass_num: 1
profile: False
skip_batch_num: 5
update_method: local
use_cprof: False
use_fake_data: False
use_nvprof: False
------------------------------------------------
```

**Comment by luotao1** [comment]
@wojtuss Thanks for your issue, I have reproduced it.
