### ISSUE TITLE
编译capi出错

### ISSUE THREAD

**Issue by wrchow** [PaddlePaddle/Paddle#11294]
序列化网络时出错：
Traceback (most recent call last):
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/utils/dump_config.py", line 29, in <module>
    conf = parse_config(sys.argv[1], sys.argv[2])
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 4367, in parse_config
    make_config_environment(trainer_config, config_args))
  File "trainer_config.py", line 28, in <module>
    outputs(fc_layer(input=[conv_3, conv_4], size=class_dim, act=paddle.activation.Softmax))
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 415, in wrapper
    return method(*args, **kwargs)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 1080, in fc_layer
    active_type=act.name,
AttributeError: type object 'Softmax' has no attribute 'name'

以下是我定义的网络:
WORD_DIM = 3000  #dict length
emb_dim = 64
hid_dim = 128
class_dim =2
sentence = data_layer(name='sentence', size=WORD_DIM)
emb = embedding_layer(input=sentence, size=64)
conv_3 = paddle.networks.sequence_conv_pool(input=emb, context_len=3, hidden_size=hid_dim)
conv_4 = paddle.networks.sequence_conv_pool(input=emb, context_len=4, hidden_size=hid_dim)

# AttributeError: type object 'Softmax' has no attribute 'name'
outputs(fc_layer(input=[conv_3, conv_4], size=class_dim, act=paddle.activation.Softmax))

**Comment by Superjomn** [comment]
可以多一些信息？ 是softmax 用错了么

**Comment by wrchow** [comment]
我再训练的时候用的是
output = paddle.layer.fc(input=[conv_3, conv_4],
                      size=class_dim,
                             act=paddle.activation.Softmax())

为何capi里面是：
outputs(fc_layer(input=[conv_3, conv_4], size=class_dim, act=SoftmaxActivation()))

是版本不一样么？都是paddle.v2啊

**Comment by Superjomn** [comment]
有两者的代码片段或者链接么，看不懂描述的背景和疑问

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
