### ISSUE TITLE
当数据集最后一个batch的样本数少于GPU卡数时，Parallel Executor是会挂掉

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#11368]
**参数如下：**
batch_size: 64
cpus: 1
data_format: NCHW
data_path: 
data_set: flowers
device: GPU
gpus: 8
infer_only: False
iterations: 80
learning_rate: 0.001
memory_optimize: True
model: resnet
no_test: False
pass_num: 100
profile: False
skip_batch_num: 5
update_method: local
use_cprof: False
use_fake_data: False
use_nvprof: False
use_reader_op: False
**结果如下：**
```
Traceback (most recent call last):
  File "fluid_benchmark.py", line 455, in <module>
    main()
  File "fluid_benchmark.py", line 451, in main
    train_parallel(*train_args)
  File "fluid_benchmark.py", line 362, in train_parallel
    loss, = exe.run([avg_loss.name], feed=feeder.feed(data))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 213, in run
    feed_tensor_dict)
paddle.fluid.core.EnforceNotMet: enforce member_->places_.size() == lod_tensors.size() failed, 8 != 5
The number of samples of current batch is less than the count of devices, currently, it is not allowed. (8 vs 5) at [/paddle/paddle/fluid/framework/parallel_executor.cc:233]
PaddlePaddle Call Stacks: 
0       0x7fa80c1d72f6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fa80c28b639p paddle::framework::ParallelExecutor::FeedAndSplitTensorIntoLocalScopes(std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > const&) + 2153
2       0x7fa80c223f11p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::ParallelExecutor, std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::ParallelExecutor::*)(std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::ParallelExecutor*, std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > const&)#1}, void, paddle::framework::ParallelExecutor*, std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > const&, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::ParallelExecutor, std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::ParallelExecutor::*)(std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::ParallelExecutor*, std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > const&)#1}&&, void (*)(paddle::framework::ParallelExecutor*, std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 257
3       0x7fa80c1e8ab4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
4             0x4c37edp PyEval_EvalFrameEx + 31165
5             0x4b9ab6p PyEval_EvalCodeEx + 774
6             0x4c16e7p PyEval_EvalFrameEx + 22711
7             0x4b9ab6p PyEval_EvalCodeEx + 774
8             0x4d54b9p
9             0x4a577ep PyObject_Call + 62
10            0x4bed3dp PyEval_EvalFrameEx + 12045
11            0x4c136fp PyEval_EvalFrameEx + 21823
12            0x4b9ab6p PyEval_EvalCodeEx + 774
13            0x4eb30fp
14            0x4e5422p PyRun_FileExFlags + 130
15            0x4e3cd6p PyRun_SimpleFileExFlags + 390
16            0x493ae2p Py_Main + 1554
17      0x7fa863f0d830p __libc_start_main + 240
18            0x4933e9p _start + 41
```

**Comment by chengduoZH** [comment]
当用feed方式向模型传数据并且数据集的最后一个batch的样本个数少于GPU卡的个数时，Parallel Executor是会挂掉的。
一种解决方法是把最后一组样本丢弃，可以调用这个函数：
https://github.com/PaddlePaddle/Paddle/blob/bfa3fd6f152227c5a527b3fa89bbdd34e37ca94a/python/paddle/batch.py#L18

**Comment by ccmeteorljh** [comment]
thanks
