### ISSUE TITLE
"pip install paddlepaddle-gpu==0.13.0" error

### ISSUE THREAD

**Issue by sneaxiy** [PaddlePaddle/Paddle#11394]
After installing paddle using `pip install paddlepaddle-gpu==0.13.0`, error occurs when `import paddle.fluid as fluid`:

```
$ python -m yep -v resnet.py
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/zengjinle/.local/lib64/python2.7/site-packages/yep.py", line 174, in <module>
    main()
  File "/home/zengjinle/.local/lib64/python2.7/site-packages/yep.py", line 148, in main
    __main__.__dict__)
  File "/home/zengjinle/.local/resnet.py", line 1, in <module>
    import paddle.fluid as fluid
  File "/home/zengjinle/.local/lib64/python2.7/site-packages/paddle/fluid/__init__.py", line 17, in <module>
    import framework
  File "/home/zengjinle/.local/lib64/python2.7/site-packages/paddle/fluid/framework.py", line 22, in <module>
    from . import core
ImportError: libmkldnn.so.0: cannot open shared object file: No such file or directory
PROFILE: interrupts/evictions/bytes = 147/0/1456
```

**Comment by typhoonzero** [comment]
Try: `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`, same to https://github.com/PaddlePaddle/Paddle/issues/11008

**Comment by yeyupiaoling** [comment]
可以把`/usr/local/lib`下的`os`文件复制到`/usr/lib`就OK了

**Comment by sneaxiy** [comment]
@yeyupiaoling There's no libmkldnn.so in `/usr/local/lib`

**Comment by typhoonzero** [comment]
Oh, try find it under your customized path like `/home/zengjinle/.local/lib` or `/home/zengjinle/.local/lib64`

**Comment by sneaxiy** [comment]
@typhoonzero I've found it in ~/.local/lib. Thanks a lot!
