### ISSUE TITLE
pip install error in official docker image

### ISSUE THREAD

**Issue by tonyyang-svail** [PaddlePaddle/Paddle#11452]
```
λ / pip install paddlepaddle
Collecting paddlepaddle
  Downloading https://files.pythonhosted.org/packages/bb/dc/6325d2c9a2d66d882656b924f76cbb4bd7ad1c01a172cb2a12283e082f4b/paddlepaddle-0.13.0-cp27-cp27mu-manylinux1_x86_64.whl (65.4MB)
    100% |████████████████████████████████| 65.4MB 22kB/s 
Requirement already satisfied: graphviz in /usr/local/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: scipy>=0.19.0 in /usr/local/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: nltk>=3.2.2 in /usr/local/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: opencv-python in /usr/local/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: LinkChecker in /usr/local/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: numpy>=1.12 in /usr/local/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: Pillow in /usr/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: matplotlib in /usr/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: recordio>=0.1.0 in /usr/local/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: requests==2.9.2 in /usr/local/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: rarfile in /usr/local/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: protobuf==3.1 in /usr/local/lib/python2.7/dist-packages (from paddlepaddle)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from nltk>=3.2.2->paddlepaddle)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf==3.1->paddlepaddle)
Installing collected packages: paddlepaddle
Successfully installed paddlepaddle-0.13.0
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
λ / python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from paddle import fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/__init__.py", line 17, in <module>
    import framework
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 22, in <module>
    from . import core
ImportError: libmkldnn.so.0: cannot open shared object file: No such file or directory
```

the LD_LIBRARY_PATH needs to be manually exported to `/usr/local/lib`.

**Comment by chengduoZH** [comment]
Similar with https://github.com/PaddlePaddle/Paddle/issues/9034 https://github.com/PaddlePaddle/Paddle/issues/10989 https://github.com/PaddlePaddle/Paddle/issues/11002
