### ISSUE TITLE
Some node fails with insufficient GPU memory when running test

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#11456]
Train with:
- 4 nodes
- 8 P40 GPUs per node
- NCCL2 distributed training
- Resnet 50 with ImageNet using recordio and readerop

Some node run the test successfully but some node report the following error:

```
Total examples: 2997248, total time: 5574.28641, 537.69178 examples/sed
W0613 10:18:30.682221   182 system_allocator.cc:100] Cannot malloc 20031.3 MB GPU memory. Please shrink FLAGS_fraction_of_gpu_memory_to_use environment variable to a lower value. Current value is 0.92
W0613 10:18:30.684809   182 malloc.cc:99] Cannot allocate 102760448 bytes in GPU 0, available 2650865664 bytes
W0613 10:18:30.684828   182 malloc.cc:101] total 24032378880
W0613 10:18:30.684834   182 malloc.cc:102] GpuMinChunkSize 256
Traceback (most recent call last):
  File "fluid_benchmark.py", line 466, in <module>
    main()
  File "fluid_benchmark.py", line 462, in main
    train_parallel(*train_args)
  File "fluid_benchmark.py", line 392, in train_parallel
    batch_acc, args)
  File "fluid_benchmark.py", line 216, in test
    return accuracy_evaluator.eval()
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/metrics.py", line 167, in eval
    "There is no data in Accuracy Metrics. Please check layers.accuracy output has added to Accuracy."
ValueError: There is no data in Accuracy Metrics. Please check layers.accuracy output has added to Accuracy.
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  out of memory at [/paddle/paddle/fluid/platform/device_context.cc:179]
PaddlePaddle Call Stacks:
0       0x7fa45f18e9b2p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 482
1       0x7fa45ff64814p paddle::platform::CUDADeviceContext::Wait() const + 468
2       0x7fa45ff64912p paddle::platform::CUDADeviceContext::~CUDADeviceContext() + 50
3       0x7fa45ff65051p paddle::platform::CUDADeviceContext::~CUDADeviceContext() + 17
4       0x7fa45f2a5a16p paddle::operators::reader::DoubleBufferReader::~DoubleBufferReader() + 214
5       0x7fa45f1920c9p std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() + 57
6       0x7fa45f192820p paddle::framework::Variable::PlaceholderImpl<paddle::framework::ReaderHolder>::~PlaceholderImpl() + 48
7       0x7fa45fe3e8bdp paddle::framework::Scope::~Scope() + 141
8       0x7fa45fe3f95ep paddle::framework::Scope::DeleteScope(paddle::framework::Scope*) const + 206
9       0x7fa45f235bc1p paddle::framework::ParallelExecutor::~ParallelExecutor() + 65
10      0x7fa45f18c363p pybind11::class_<paddle::framework::ParallelExecutor>::dealloc(_object*) + 35
11      0x7fa45f19c12dp pybind11_object_dealloc + 45
```

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
