### ISSUE TITLE
厂内v100机器编译错误  

### ISSUE THREAD

**Issue by guochaorong** [PaddlePaddle/Paddle#11967]
有一台产内v100 机器，cuda 版本8.0
报下面错误：
请春老师帮忙看下是不是cuda的问题

```sh
 99%] Linking CXX executable test_inference_recognize_digits_conv
[ 99%] Linking CXX executable test_inference_image_classification_resnet
[ 99%] Linking CXX executable test_inference_nlp
../../../fluid/inference/libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_CUDA()':
reshape_op.cc:(.text+0x370): multiple definition of `TouchOpKernelRegistrar_reshape_CUDA()'
../../../fluid/inference/libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2e0): first defined here
../../../fluid/inference/libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_grad_CUDA()':
reshape_op.cc:(.text+0x380): multiple definition of `TouchOpKernelRegistrar_reshape_grad_CUDA()'
../../../fluid/inference/libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2f0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/contrib/inference/demo/ocr_inference_demo] Error 1
make[1]: *** [paddle/contrib/inference/demo/CMakeFiles/ocr_inference_demo.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../../../fluid/inference/libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_CUDA()':
reshape_op.cc:(.text+0x370): multiple definition of `TouchOpKernelRegistrar_reshape_CUDA()'
../../../fluid/inference/libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2e0): first defined here
../../../fluid/inference/libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_grad_CUDA()':
reshape_op.cc:(.text+0x380): multiple definition of `TouchOpKernelRegistrar_reshape_grad_CUDA()'
../../../fluid/inference/libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2f0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/contrib/inference/demo/se_resnext50_inference_demo] Error 1
make[1]: *** [paddle/contrib/inference/demo/CMakeFiles/se_resnext50_inference_demo.dir/all] Error 2
[ 99%] Built target paddle_fluid_shared
[ 99%] Built target test_paddle_inference_api_impl
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_CUDA()':
reshape_op.cc:(.text+0x370): multiple definition of `TouchOpKernelRegistrar_reshape_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o.):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(..text+0x2e0)/: first../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_CUDA defined here
()../../'libpaddle_fluid.a(:
reshape_op.cc:(.reshape_op.cc.o): Intext+0x370):  functionmultiple definition of  `TouchOpKernelRegistrar_reshape_grad_CUDA()':`TouchOpKernelRegistrar_reshape_CUDA(
)reshape_op.cc:(.'
text+0x380.): multiple./../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o definition) of: `TouchOpKernelRegistrar_reshape_grad_CUDAtmpxft_00000890_00000000()-5_reshape_op.compute_70.cudafe1.cpp:(.text'
+0x2e0): first.. defined here
./.../../libpaddle_fluid.a/libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o(reshape_op.cc.o):)tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp: In function: (.text+`TouchOpKernelRegistrar_reshape_grad_CUDA0x2f0()): first defined': here

reshape_op.cc:(.text+0x380): multiple definition of `TouchOpKernelRegistrar_reshape_grad_CUDA()'
../.collect2: error: ld returned 1 exit status
./libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2f0): first defined here
collect2: error: ld returned 1 exit status
make[2]: make[2]: *** [paddle/fluid/inference/tests/book/test_inference_recommender_system] Error 1
*** [paddle/fluid/inference/tests/book/test_inference_label_semantic_roles] Error 1
make[1]: *** [paddle/fluid/inference/tests/book/CMakeFiles/test_inference_recommender_system.dir/all] Error 2
make[1]: *** [paddle/fluid/inference/tests/book/CMakeFiles/test_inference_label_semantic_roles.dir/all] Error 2
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_CUDA()':
reshape_op.cc:(.text+0x370): multiple definition of `TouchOpKernelRegistrar_reshape_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2e0): first defined here
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_grad_CUDA()':
reshape_op.cc:(.text+0x380): multiple definition of `TouchOpKernelRegistrar_reshape_grad_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2f0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/fluid/inference/tests/book/test_inference_recognize_digits_conv] Error 1
make[1]: *** [paddle/fluid/inference/tests/book/CMakeFiles/test_inference_recognize_digits_conv.dir/all] Error 2
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_CUDA()':
reshape_op.cc:(.text+0x370): multiple definition of `TouchOpKernelRegistrar_reshape_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2e0): first defined here
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_grad_CUDA()':
reshape_op.cc:(.text+0x380): multiple definition of `TouchOpKernelRegistrar_reshape_grad_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2f0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/fluid/inference/tests/book/test_inference_image_classification_resnet] Error 1
make[1]: *** [paddle/fluid/inference/tests/book/CMakeFiles/test_inference_image_classification_resnet.dir/all] Error 2
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_CUDA()':
reshape_op.cc:(.text+0x370): multiple definition of `TouchOpKernelRegistrar_reshape_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2e0): first defined here
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_grad_CUDA()':
reshape_op.cc:(.text+0x380): multiple definition of `TouchOpKernelRegistrar_reshape_grad_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2f0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/fluid/inference/tests/book/test_inference_word2vec] Error 1
make[1]: *** [paddle/fluid/inference/tests/book/CMakeFiles/test_inference_word2vec.dir/all] Error 2
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_CUDA()':
reshape_op.cc:(.text+0x370): multiple definition of `TouchOpKernelRegistrar_reshape_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2e0): first defined here
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_grad_CUDA()':
reshape_op.cc:(.text+0x380): multiple definition of `TouchOpKernelRegistrar_reshape_grad_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2f0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/fluid/inference/tests/book/test_inference_recognize_digits_mlp] Error 1
make[1]: *** [paddle/fluid/inference/tests/book/CMakeFiles/test_inference_recognize_digits_mlp.dir/all] Error 2
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_CUDA()':
reshape_op.cc:(.text+0x370): multiple definition of `TouchOpKernelRegistrar_reshape_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2e0): first defined here
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_grad_CUDA()':
reshape_op.cc:(.text+0x380): multiple definition of `TouchOpKernelRegistrar_reshape_grad_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2f0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/fluid/inference/tests/book/test_inference_image_classification_vgg] Error 1
make[1]: *** [paddle/fluid/inference/tests/book/CMakeFiles/test_inference_image_classification_vgg.dir/all] Error 2
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_CUDA()':
reshape_op.cc:(.text+0x370): multiple definition of `TouchOpKernelRegistrar_reshape_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2e0): first defined here
../../libpaddle_fluid.a(reshape_op.cc.o): In function `TouchOpKernelRegistrar_reshape_grad_CUDA()':
reshape_op.cc:(.text+0x380): multiple definition of `TouchOpKernelRegistrar_reshape_grad_CUDA()'
../../libpaddle_fluid.a(reshape_op_generated_reshape_op.cu.o):tmpxft_00000890_00000000-5_reshape_op.compute_70.cudafe1.cpp:(.text+0x2f0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/fluid/inference/tests/book/test_inference_nlp] Error 1
make[1]: *** [paddle/fluid/inference/tests/book/CMakeFiles/test_inference_nlp.dir/all] Error 2
[ 99%] Linking CXX shared library libpaddle_pybind.so
[ 99%] Built target paddle_pybind
make: *** [all] Error 2
Requirement 'python/dist/*.whl' looks like a filename, but the file does not exist
*.whl is not a valid wheel filename.
Traceback (most recent call last):
  File "/usr/local/bin/xonsh", line 3, in <module>
    main()
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 344, in main
    _failback_to_other_shells(args, err)
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 308, in _failback_to_other_shells
    raise err
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 342, in main
    return main_xonsh(args)
  File "/usr/local/lib/python3.5/site-packages/xonsh/main.py", line 383, in main_xonsh
    loc=None, mode='exec')
  File "/usr/local/lib/python3.5/site-packages/xonsh/codecache.py", line 162, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/usr/local/lib/python3.5/site-packages/xonsh/codecache.py", line 68, in run_compiled_code
    func(code, glb, loc)
  File "./build_paddle.xsh", line 36, in <module>
  File "/usr/local/lib/python3.5/site-packages/xonsh/built_ins.py", line 881, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured='hiddenobject')
  File "/usr/local/lib/python3.5/site-packages/xonsh/built_ins.py", line 844, in run_subproc
    command.end()
  File "/usr/local/lib/python3.5/site-packages/xonsh/proc.py", line 2014, in end
    self._end(tee_output=tee_output)
  File "/usr/local/lib/python3.5/site-packages/xonsh/proc.py", line 2033, in _end
    self._raise_subproc_error()
  File "/usr/local/lib/python3.5/site-packages/xonsh/proc.py", line 2154, in _raise_subproc_error
    output=self.output)
subprocess.CalledProcessError: Command '['/opt/_internal/cpython-2.7.11-ucs4/bin/python', '/opt/python/cp27-cp27mu/bin/pip', 'install', '--upgrade', 'python/dist/*.whl']' returned non-zero exit status 1
```

**Comment by luotao1** [comment]
不是cuda问题，请先删除`rm -rf build/paddle/fluid/inference`目录，重新编译即可。
