### ISSUE TITLE
奇怪的报错："paddle.fluid.core.EnforceNotMet: enforce framework::product(lr_dims) == 1 failed, 0 != 1"

### ISSUE THREAD

**Issue by bipedalBit** [PaddlePaddle/Paddle#11976]
```python
    def train(self):
        """模型训练"""
        # 创建模型
        avg_cost, acc, prediction = self._build_model()
        # 初始化模型并为模型测试做准备
        test_exe = fluid.Executor(fluid.CPUPlace())
        test_exe.run(fluid.default_startup_program())
        infer_program = fluid.default_main_program().clone(for_test=True)
        # 获取数据reader
        train_reader = self._train_reader()
        test_reader = self._test_reader()
        # 训练配置
        optimizer = fluid.optimizer.Adamax(learning_rate=self.lr)
        optimizer.minimize(avg_cost)
        train_exe = fluid.ParallelExecutor(
            use_cuda=self.use_gpu, loss_name=avg_cost.name)
        fetch_vars = [avg_cost, acc, prediction]
        var_names = [var.name for var in fetch_vars]
        place = fluid.CUDAPlace(0) if self.use_gpu else fluid.CPUPlace()
        feeder = fluid.DataFeeder(place=place, feed_list=['embs', 'label'])
        # 训练并测试模型
        for epoch_id in range(self.epoch_num):
            # 训练
            for batch_id, data in enumerate(train_reader()):
                avg_cost, acc, prediction = train_exe.run(
                    feed=feeder.feed(data),
                    fetch_list=var_names)
                print('Train: epoch %d, batch %d, average cost: %f, accuracy: %f',
                    (epoch_id, batch_id, avg_cost, acc))
            # 测试
            for test_batch_id, data in enumerate(test_reader()):
                avg_cost, acc, prediction = test_exe.run(
                    program=infer_program,
                    feed=feeder.feed(data),
                    fetch_list=var_names)
                print('Test: epoch %d, batch %d, average cost: %f, accuracy: %f',
                    (epoch_id, batch_id, avg_cost, acc))
            # 保存模型
            self._save_model(epoch_id, exe, infer_model=True, target_vars=[fetch_vars[-1]])
```
训练模型时报错很奇怪：
```
Traceback (most recent call last):
  File "./hidden_danger_classify.py", line 241, in <module>
    model.train()
  File "./hidden_danger_classify.py", line 173, in train
    fetch_list=var_names)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 336, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: enforce framework::product(lr_dims) == 1 failed, 0 != 1
Learning rate should have 1 dimension at [/paddle/paddle/fluid/operators/adamax_op.cc:48]
PaddlePaddle Call Stacks:
0       0x7f2d9fc5c246p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f2d9fefaa78p paddle::operators::AdamaxOp::InferShape(paddle::framework::InferShapeContext*) const + 5960
2       0x7f2da0372a8bp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 91
3       0x7f2da0370b38p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 56
4       0x7f2d9fce38e0p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool) + 336
5       0x7f2d9fce4044p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 100
6       0x7f2d9fc72ccbp void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 555
7       0x7f2d9fc6ca34p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
8             0x4c37edp PyEval_EvalFrameEx + 31165
9             0x4b9ab6p PyEval_EvalCodeEx + 774
10            0x4c16e7p PyEval_EvalFrameEx + 22711
11            0x4c136fp PyEval_EvalFrameEx + 21823
12            0x4b9ab6p PyEval_EvalCodeEx + 774
13            0x4eb30fp
14            0x4e5422p PyRun_FileExFlags + 130
15            0x4e3cd6p PyRun_SimpleFileExFlags + 390
16            0x493ae2p Py_Main + 1554
17      0x7f2db7a21830p __libc_start_main + 240
18            0x4933e9p _start + 41
```
有什么建议吗？

**Comment by wanghaoshuang** [comment]
把`self.lr`相关代码也贴出来？你使用了learning rate decay么？

**Comment by bipedalBit** [comment]
没有使用lr decay`self.lr = 1e-3`

**Comment by wanghaoshuang** [comment]
print 一下program, 然后把结果贴上来？有没有为某个layer单独设置lr?
```
        avg_cost, acc, prediction = self._build_model()
        # 初始化模型并为模型测试做准备
        test_exe = fluid.Executor(fluid.CPUPlace())
        test_exe.run(fluid.default_startup_program())
        infer_program = fluid.default_main_program().clone(for_test=True)
       
        print fluid.default_main_program()
```

**Comment by bipedalBit** [comment]
```
blocks {
  idx: 0
  parent_idx: -1
  vars {
    name: "top_k_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "avg_cost.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 1
        }
      }
    }
    persistable: false
  }
  vars {
    name: "cross_entropy_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "prediction.tmp_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 12
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "prediction.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 12
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "prediction.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 12
        }
      }
    }
    persistable: true
  }
  vars {
    name: "embs"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 1
        }
        lod_level: 1
      }
    }
    persistable: false
  }
  vars {
    name: "label"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: INT64
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "accuracy_0.tmp_2"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: INT64
          dims: 1
        }
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_conv_0.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 3
          dims: 128
        }
      }
    }
    persistable: true
  }
  vars {
    name: "top_k_0.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: INT64
          dims: -1
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_conv_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 128
        }
        lod_level: 1
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_pool_0.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 128
        }
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_conv_0.b_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 128
        }
      }
    }
    persistable: true
  }
  vars {
    name: "accuracy_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 1
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_conv_0.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 128
        }
        lod_level: 1
      }
    }
    persistable: false
  }
  vars {
    name: "accuracy_0.tmp_1"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: INT64
          dims: 1
        }
      }
    }
    persistable: false
  }
  vars {
    name: "sequence_pool_0.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 128
        }
      }
    }
    persistable: false
  }
  vars {
    name: "prediction.tmp_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: -1
          dims: 12
        }
        lod_level: 0
      }
    }
    persistable: false
  }
  vars {
    name: "prediction.w_0"
    type {
      type: LOD_TENSOR
      lod_tensor {
        tensor {
          data_type: FP32
          dims: 128
          dims: 12
        }
      }
    }
    persistable: true
  }
  ops {
    inputs {
      parameter: "Filter"
      arguments: "sequence_conv_0.w_0"
    }
    inputs {
      parameter: "PaddingData"
    }
    inputs {
      parameter: "X"
      arguments: "embs"
    }
    outputs {
      parameter: "Out"
      arguments: "sequence_conv_0.tmp_0"
    }
    type: "sequence_conv"
    attrs {
      name: "paddingTrainable"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "contextStride"
      type: INT
      i: 1
    }
    attrs {
      name: "contextStart"
      type: INT
      i: -1
    }
    attrs {
      name: "contextLength"
      type: INT
      i: 3
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "sequence_conv_0.tmp_0"
    }
    inputs {
      parameter: "Y"
      arguments: "sequence_conv_0.b_0"
    }
    outputs {
      parameter: "Out"
      arguments: "sequence_conv_0.tmp_1"
    }
    type: "elementwise_add"
    attrs {
      name: "axis"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "sequence_conv_0.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "sequence_conv_0.tmp_1"
    }
    type: "tanh"
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "sequence_conv_0.tmp_1"
    }
    outputs {
      parameter: "MaxIndex"
      arguments: "sequence_pool_0.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "sequence_pool_0.tmp_0"
    }
    type: "sequence_pool"
    attrs {
      name: "pooltype"
      type: STRING
      s: "MAX"
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "sequence_pool_0.tmp_0"
    }
    inputs {
      parameter: "Y"
      arguments: "prediction.w_0"
    }
    outputs {
      parameter: "Out"
      arguments: "prediction.tmp_0"
    }
    type: "mul"
    attrs {
      name: "y_num_col_dims"
      type: INT
      i: 1
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "x_num_col_dims"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "prediction.tmp_0"
    }
    inputs {
      parameter: "Y"
      arguments: "prediction.b_0"
    }
    outputs {
      parameter: "Out"
      arguments: "prediction.tmp_1"
    }
    type: "elementwise_add"
    attrs {
      name: "axis"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "prediction.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "prediction.tmp_2"
    }
    type: "softmax"
    attrs {
      name: "is_test"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "data_format"
      type: STRING
      s: "AnyLayout"
    }
    attrs {
      name: "use_cudnn"
      type: BOOLEAN
      b: false
    }
    attrs {
      name: "use_mkldnn"
      type: BOOLEAN
      b: false
    }
  }
  ops {
    inputs {
      parameter: "Label"
      arguments: "label"
    }
    inputs {
      parameter: "X"
      arguments: "prediction.tmp_2"
    }
    outputs {
      parameter: "Y"
      arguments: "cross_entropy_0.tmp_0"
    }
    type: "cross_entropy"
    attrs {
      name: "soft_label"
      type: BOOLEAN
      b: false
    }
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "cross_entropy_0.tmp_0"
    }
    outputs {
      parameter: "Out"
      arguments: "avg_cost.tmp_0"
    }
    type: "mean"
  }
  ops {
    inputs {
      parameter: "X"
      arguments: "prediction.tmp_2"
    }
    outputs {
      parameter: "Indices"
      arguments: "top_k_0.tmp_1"
    }
    outputs {
      parameter: "Out"
      arguments: "top_k_0.tmp_0"
    }
    type: "top_k"
    attrs {
      name: "k"
      type: INT
      i: 1
    }
  }
  ops {
    inputs {
      parameter: "Indices"
      arguments: "top_k_0.tmp_1"
    }
    inputs {
      parameter: "Label"
      arguments: "label"
    }
    inputs {
      parameter: "Out"
      arguments: "top_k_0.tmp_0"
    }
    outputs {
      parameter: "Accuracy"
      arguments: "accuracy_0.tmp_0"
    }
    outputs {
      parameter: "Correct"
      arguments: "accuracy_0.tmp_1"
    }
    outputs {
      parameter: "Total"
      arguments: "accuracy_0.tmp_2"
    }
    type: "accuracy"
  }
}
```
没有为某个layer单独设置lr

**Comment by bipedalBit** [comment]
上面贴的是Mac下用docker、latest镜像跑训练报的错。
下面是Ubuntu16下用paddlepaddle-gpu==0.14.0.post87跑训练报的错：
```
Traceback (most recent call last):
  File "./hidden_danger_classify.py", line 193, in <module>
    model.train()
  File "./hidden_danger_classify.py", line 138, in train
    feed=feeder.feed(data),
  File "/opt/conda/envs/py27/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 194, in feed
    ret_dict[each_name] = each_converter.done()
  File "/opt/conda/envs/py27/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 77, in done
    t.set_recursive_sequence_lengths(self.lod)
paddle.fluid.core.EnforceNotMet: the provided recursive_sequence_lengths info is invalid at [/paddle/paddle/fluid/pybind/pybind.cc:190]
PaddlePaddle Call Stacks:
0       0x7f501fe46c76p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f501fe3e417p
2       0x7f501fe56b44p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
3       0x7f5079aba9d2p PyEval_EvalFrameEx + 29874
4       0x7f5079abccedp PyEval_EvalCodeEx + 2061
5       0x7f5079ab9e72p PyEval_EvalFrameEx + 26962
6       0x7f5079abccedp PyEval_EvalCodeEx + 2061
7       0x7f5079ab9e72p PyEval_EvalFrameEx + 26962
8       0x7f5079ab9f8dp PyEval_EvalFrameEx + 27245
9       0x7f5079abccedp PyEval_EvalCodeEx + 2061
10      0x7f5079abce22p PyEval_EvalCode + 50
11      0x7f5079ae8d72p PyRun_FileExFlags + 146
12      0x7f5079aea0e9p PyRun_SimpleFileExFlags + 217
13      0x7f5079b0000dp Py_Main + 3149
14      0x7f5078cd6830p __libc_start_main + 240
15            0x4007b1p
```
两个环境报错不一样 有什么建议吗？

**Comment by bipedalBit** [comment]
找到问题了 
```python
optimizer = fluid.optimizer.Adamax(learning_rate=self.lr)
optimizer.minimize(avg_cost)
```
优化器调用一定要在模型初始化
```python
exe = fluid.Executor(fluid.CPUPlace())
exe.run(fluid.default_startup_program())
```
之前。
