### ISSUE TITLE
使用官方的02.recognize_digits/train.py 代码报错

### ISSUE THREAD

**Issue by githwd2016** [PaddlePaddle/Paddle#12235]
报错信息如下：
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    import paddle
  File "/home/hwd/.local/lib/python2.7/site-packages/paddle/__init__.py", line 25, in <module>
    import dataset
  File "/home/hwd/.local/lib/python2.7/site-packages/paddle/dataset/__init__.py", line 28, in <module>
    import mq2007
  File "/home/hwd/.local/lib/python2.7/site-packages/paddle/dataset/mq2007.py", line 28, in <module>
    import rarfile
  File "/home/hwd/.local/lib/python2.7/site-packages/rarfile.py", line 2950, in <module>
    _check_unrar_tool()
  File "/home/hwd/.local/lib/python2.7/site-packages/rarfile.py", line 2931, in _check_unrar_tool
    custom_check([ORIG_UNRAR_TOOL], True)
  File "/home/hwd/.local/lib/python2.7/site-packages/rarfile.py", line 2823, in custom_check
    p = custom_popen(cmd)
  File "/home/hwd/.local/lib/python2.7/site-packages/rarfile.py", line 2813, in custom_popen
    creationflags=creationflags)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by guoshengCS** [comment]
这个貌似是权限问题，直接`import   rarfile`应该也会报错同样的错误，可以使用user的python和pip重新安装下rarfile这个包试下

**Comment by yeyupiaoling** [comment]
>OSError: [Errno 13] Permission denied

这个应该是权限不够，用root试试

**Comment by githwd2016** [comment]
使用sudo python 运行程序的话是没问题的，但是这样就需要把程序包装到系统目录下，有没有可以用用户身份运行的办法

**Comment by ktlichkid** [comment]
有试过重新安装rarfile这个包吗？有效果没

**Comment by seiriosPlus** [comment]
https://github.com/markokr/rarfile/issues/38

**Comment by erichhhhho** [comment]
这个更新似乎没有release啊@seiriosPlus
