### ISSUE TITLE
IfElse Layer failed in some case.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#12245]
```python
import numpy as np
import paddle.fluid as fluid

def ifop(target):
    max_gap = fluid.layers.fill_constant([1], dtype='float32', value=-5.0)
    max_gap.stop_gradient = True
    ifcond = fluid.layers.less_than(x=target, y=max_gap)
    ie = fluid.layers.IfElse(ifcond)

    with ie.true_block():
        true_target = ie.input(target)
        true_target = fluid.layers.exp(true_target)
        ie.output(true_target)

    with ie.false_block():
        false_target = ie.input(target)
        ie.output(false_target)
    res = ie()
    return res

def testifelse():
    input = fluid.layers.data(name='image', shape=[1], dtype='float32')
    res = ifop(input)
    avg_cost = fluid.layers.mean(x=res)

    optimizer = fluid.optimizer.SGD(learning_rate=0.0001)
    opts = optimizer.minimize(avg_cost)

    place = fluid.CUDAPlace(0)

    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())

    feeder = fluid.DataFeeder(place=place, feed_list=[input])
    fetch_list = [avg_cost.name]
    data = np.random.rand(25, 1).astype(np.float32)
    loss = exe.run(
                fluid.default_main_program(),
                feed={'image': data},
                fetch_list=fetch_list
            )
    print loss

if __name__ == "__main__":
    testifelse()
```

Above code failed:

```txt
Traceback (most recent call last):
  File "test_ifelse.py", line 45, in <module>
    testifelse()


  File "test_ifelse.py", line 40, in testifelse
    fetch_list=fetch_list
  File "/paddle/work/pyenv/local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 449, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/paddle/Paddle/paddle/fluid/framework/tensor.cc:22]
PaddlePaddle Call Stacks:
0       0x7fb38408abecp paddle::framework::Tensor::check_memory_size() const + 9100
1       0x7fb382fe4328p float const* paddle::framework::Tensor::data<float>() const + 40
2       0x7fb38345ea92p paddle::framework::EigenVector<float, 1, long>::Flatten(paddle::framework::Tensor const&) + 82
3       0x7fb383c53160p paddle::operators::ActivationGradKernel<paddle::platform::CUDADeviceContext, paddle::operators::ExpGradFunctor<float> >::Compute(paddle::framework::ExecutionContext const&) const + 384
4       0x7fb383c534bfp std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::ActivationGradKernel<paddle::platform::CUDADeviceContext, paddle::operators::ExpGradFunctor<float> >, paddle::operators::ActivationGradKernel<paddle::platform::CUDADeviceContext, paddle::operators::ExpGradFunctor<double> > >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 47
5       0x7fb383fd2cebp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 747
6       0x7fb383fce5adp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 221
7       0x7fb3830cbb28p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 328
8       0x7fb3830ccc1ap paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 154
9       0x7fb383a08699p paddle::operators::ConditionalBlockGradOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 489
10      0x7fb383fce5adp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 221
11      0x7fb3830cbb28p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 328
12      0x7fb3830ccc1ap paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 154
13      0x7fb382fbeeb2p
14      0x7fb382ffcdd4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
15            0x4c37edp PyEval_EvalFrameEx + 31165
16            0x4b9ab6p PyEval_EvalCodeEx + 774
17            0x4c16e7p PyEval_EvalFrameEx + 22711
18            0x4c136fp PyEval_EvalFrameEx + 21823
19            0x4b9ab6p PyEval_EvalCodeEx + 774
20            0x4eb30fp
21            0x4e5422p PyRun_FileExFlags + 130
22            0x4e3cd6p PyRun_SimpleFileExFlags + 390
23            0x493ae2p Py_Main + 1554
24      0x7fb3d86bf830p __libc_start_main + 240
25            0x4933e9p _start + 41
```

**Comment by qingqing01** [comment]
There is  still other bug:

```txt
[13:16:32]  File "test_if_else_op.py", line 83, in test_raw_api
[13:16:32]    fetch_list=[avg_loss])
[13:16:32]  File "/paddle/build/python/paddle/fluid/executor.py", line 449, in run
[13:16:32]    self.executor.run(program.desc, scope, 0, True, True)
[13:16:32]EnforceNotMet: enforce ctx->GetInputDim("Out") == ctx->GetInputDim(framework::GradVarName("Out")) failed, 0, 10 != 0
[13:16:32]Input(Out) and its gradients should have a same shape. at [/paddle/paddle/fluid/operators/softmax_op.cc:138]
[13:16:32]PaddlePaddle Call Stacks: 
[13:16:32]0       0x7fdc0e419dccp paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 572
[13:16:32]1       0x7fdc0f23593fp paddle::operators::SoftmaxOpGrad::InferShape(paddle::framework::InferShapeContext*) const + 1183
[13:16:32]2       0x7fdc0f4a281ep paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1614
```


https://paddleci.ngrok.io/viewLog.html?buildId=2314&buildTypeId=Paddle_PrCi&tab=buildLog

**Comment by luotao1** [comment]
The same error to me in some CIs.

**Comment by qingqing01** [comment]
@luotao1 you can disable this unit test. I'll fix it later.

**Comment by dzhwinter** [comment]
Meet the same one..
