### ISSUE TITLE
layers.fc output之后的数据维度，为什么会是(-1,128)

### ISSUE THREAD

**Issue by Emma-Ding** [PaddlePaddle/Paddle#12358]
` user_cross0 = fluid.layers.fc(name="user_cross_0", input=user_fc0, size=128)
    print user_cross0.shape
    user_cross_raw1 = fluid.layers.matmul(name="user_cross_raw1", x=user_cross0, y=user_cross0, transpose_x=True, transpose_y=True)
    user_cross_scale_1 = fluid.layers.fc(input=user_cross_raw1, size=128)
    user_cross_1 = user_cross_scale_1 + user_cross0`

I0725 15:29:54.756508 35564 init.cc:44] Init commandline: dummy conf/trainer_config.conf --tryfromenv=use_pinned_memory,check_nan_inf,benchmark,warpctc_dir,eager_delete_scope,use_mkldnn,initial_cpu_memory_in_mb,init_allocated_mem,rpc_deadline
(-1L, 128L)
128 -1
128 -1
Traceback (most recent call last):
  File "conf/trainer_config.conf", line 288, in <module>
    model_output_dir=model_output_dir,
  File "conf/trainer_config.conf", line 146, in train
    user_cross_raw1 = fluid.layers.matmul(name="user_cross_raw1", x=user_cross0, y=user_cross0, transpose_x=True, transpose_y=True)
  File "/home/dingweiyue/tools/cp01-rdqa-qianyi-038.cp01.baidu.com/home/work/jiangyuzhu/fluid/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 3428, in matmul
    __check_input(x, y)
  File "/home/dingweiyue/tools/cp01-rdqa-qianyi-038.cp01.baidu.com/home/work/jiangyuzhu/fluid/feedbsq_paddle/paddle/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 3421, in __check_input
    raise ValueError("Invalid inputs for matmul.")
ValueError: Invalid inputs for matmul.

**Comment by Superjomn** [comment]
-1 代表会变的 batch_size

**Comment by ktlichkid** [comment]
Issue已经解答，如有进一步问题欢迎重开。
