### ISSUE TITLE
Print pserver program meets error

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#12370]
Print pserver program meets error:
```
6 Traceback (most recent call last):
      7   File "train.py", line 685, in <module>
      8     train(args)
      9   File "train.py", line 659, in train
     10     print pserver_prog
     11   File "/paddle/build/build_develop/python/paddle/fluid/framework.py", line 1358, in __str__
     12     return self.to_string(True)
     13   File "/paddle/build/build_develop/python/paddle/fluid/framework.py", line 1389, in to_string
     14     res_str = _debug_string_(proto, throw_on_error)
     15   File "/paddle/build/build_develop/python/paddle/fluid/framework.py", line 127, in _debug_string_
     16     format(error_fields, proto))
     17 ValueError: ['blocks[0].ops[0].attrs[8].type'] are not initialized.
```

**Comment by typhoonzero** [comment]
Can not reproduce for now.
