### ISSUE TITLE
Caffe转Fluid报错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#12437]
我是使用[这些模型的](https://github.com/PaddlePaddle/models/tree/develop/fluid/image_classification/caffe2fluid#tested-models)，其中测试的是ResNet101，根据官方的教程就会报以下错误：
```
root@test:/home/test/paddlepaddle/models/fluid/image_classification/caffe2fluid# python convert.py ResNet-101-deploy.prototxt --caffemodel ResNet-101-model.caffemodel --data-output-path ResNet101.npy --code-output-path ResNet101.py
register layer[Axpy]
register layer[Flatten]
register layer[ArgMax]
register layer[Reshape]
register layer[ROIPooling]
register layer[PriorBox]
register layer[Permute]
register layer[DetectionOutput]
register layer[Normalize]
register layer[Select]
Traceback (most recent call last):
  File "convert.py", line 80, in <module>
    ret = main()
  File "convert.py", line 76, in main
    args.code_output_path, args.phase)
  File "convert.py", line 35, in convert
    transformer = Transformer(def_path, caffemodel_path, phase=phase)
  File "/home/test/paddlepaddle/models/fluid/image_classification/caffe2fluid/kaffe/paddle/transformer.py", line 293, in __init__
    self.load(def_path, data_path, phase)
  File "/home/test/paddlepaddle/models/fluid/image_classification/caffe2fluid/kaffe/paddle/transformer.py", line 299, in load
    graph = GraphBuilder(def_path, phase).build()
  File "/home/test/paddlepaddle/models/fluid/image_classification/caffe2fluid/kaffe/graph.py", line 177, in __init__
    self.load()
  File "/home/test/paddlepaddle/models/fluid/image_classification/caffe2fluid/kaffe/graph.py", line 181, in load
    self.params = get_caffe_resolver().NetParameter()
  File "/home/test/paddlepaddle/models/fluid/image_classification/caffe2fluid/kaffe/caffe/resolver.py", line 43, in get_caffe_resolver
    SHARED_CAFFE_RESOLVER = CaffeResolver()
  File "/home/test/paddlepaddle/models/fluid/image_classification/caffe2fluid/kaffe/caffe/resolver.py", line 18, in __init__
    self.import_caffe()
  File "/home/test/paddlepaddle/models/fluid/image_classification/caffe2fluid/kaffe/caffe/resolver.py", line 28, in import_caffe
    self.caffepb = import_caffepb()
  File "/home/test/paddlepaddle/models/fluid/image_classification/caffe2fluid/kaffe/caffe/resolver.py", line 12, in import_caffepb
    import caffe_pb2
ImportError: No module named caffe_pb2
```

然后我把`caffepb.py`改成`caffe_pb2.py`，上面的错误就没有了，但是在执行以下这一步的时候就报错了
```
root@test:/home/test/paddlepaddle/models/fluid/image_classification/caffe2fluid# python ResNet101.py ResNet101.npy ./fluid
  File "ResNet101.py", line 467
    class ResNet-101(Network):
                ^
SyntaxError: invalid syntax
```

**Comment by luotao1** [comment]
> ResNet-101

改成ResNet_101呢？

**Comment by yeyupiaoling** [comment]
@luotao1 我改成ResNet，就报以下错误
```
root@test:/home/test/paddlepaddle/models/fluid/image_classification/caffe2fluid# python ResNet101.py ResNet101.npy ./fluid
Traceback (most recent call last):
  File "ResNet101.py", line 969, in <module>
    exit(main())
  File "ResNet101.py", line 957, in main
    ret = ResNet.convert(npy_weight, fluid_model, outputs)
  File "ResNet101.py", line 514, in convert
    net = cls(feed_data)
  File "ResNet101.py", line 54, in __init__
    self.setup()
  File "ResNet101.py", line 565, in setup
    self.relu(name='res2a_relu')
  File "ResNet101.py", line 29, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "ResNet101.py", line 246, in relu
    name=self.get_unique_output_name(name, 'relu'), x=input)
TypeError: relu() got an unexpected keyword argument 'name'
```

**Comment by qingqing01** [comment]
@yeyupiaoling  Error about `TypeError: relu() got an unexpected keyword argument 'name' ` is due to  https://github.com/PaddlePaddle/models/issues/1068  . And it is fixed by  https://github.com/PaddlePaddle/Paddle/pull/12438
