### ISSUE TITLE
develop 分支最新代码, Transformer 模型执行会失败

### ISSUE THREAD

**Issue by velconia** [PaddlePaddle/Paddle#12500]
模型代码为: [transformer](https://github.com/PaddlePaddle/models/tree/develop/fluid/neural_machine_translation/transformer)

环境为:
```
单机, V100 * 8
```

报错栈为: 
```
epoch: 0, batch: 24, sum loss: 236580.812500, avg loss: 10.413805, ppl: 33316.398438
epoch: 0, batch: 25, sum loss: 235767.593750, avg loss: 10.378008, ppl: 32144.861328
Traceback (most recent call last):
  File "train.py", line 550, in <module>
    train(args)
  File "train.py", line 506, in train
    lr_scheduler, token_num, predict)
  File "train.py", line 418, in train_loop
    feed=feed_list)
  File "/home/paddle/minqiyang/miniconda2/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 269, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: enforce allocating <= available failed, 2413512130 > 1833238272
 at [/paddle/Paddle/paddle/fluid/platform/gpu_info.cc:119]
PaddlePaddle Call Stacks:
0       0x7f3fce8eaa02p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 482
1       0x7f3fcf813e01p paddle::platform::GpuMaxChunkSize() + 769
2       0x7f3fcf743fcbp void* paddle::memory::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace, unsigned long) + 475
3       0x7f3fcf739a68p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::type_index)
+ 824
4       0x7f3fceed93f7p paddle::operators::MatMulGradKernel<paddle::platform::CUDADeviceContext, float>::MatMul(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, paddle::framework::Tensor*) const + 135
5       0x7f3fceed9641p paddle::operators::MatMulGradKernel<paddle::platform::CUDADeviceContext, float>::CalcInputGrad(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const&, bool, bool, paddle::framework::Tensor const&, bool, bool, paddle::framework::Tensor*) const + 145

```

**Comment by gongweibao** [comment]
显存不够了
```
paddle.fluid.core.EnforceNotMet: enforce allocating <= available failed, 2413512130 > 1833238272
```

**Comment by dzhwinter** [comment]
开显存优化了吗？ 使用fluid.memory_optimize(program)打开

**Comment by velconia** [comment]
>使用fluid.memory_optimize(program)打开

赞, 使用显存优化后问题解决了
