### ISSUE TITLE
test_recognize_digits_conv and test_image_classification_resnet failed in CI

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#12506]
http://ci.paddlepaddle.org/viewLog.html?buildId=3313&tab=buildLog&buildTypeId=Paddle_PrCi&logTab=tree&filter=all

```
[13:22:30]	        Start 369: test_recognize_digits_conv
[13:22:37]	351/381 Test #369: test_recognize_digits_conv ......................***Failed    6.32 sec
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from ._ufuncs import *
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from ._solve_toeplitz import levinson
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from ._decomp_update import *
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from . import _bspl
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from . import _csparsetools
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from ._tools import csgraph_to_dense, csgraph_from_dense,\
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from ._traversal import breadth_first_order, depth_first_order, \
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from ._min_spanning_tree import minimum_spanning_tree
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from .ckdtree import *
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from .qhull import *
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from . import _voronoi
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from . import _hausdorff
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/optimize/_trlib/__init__.py:1: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from ._trlib import TRLIBQuadraticSubproblem
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/optimize/_numdiff.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from ._group_columns import group_dense, group_sparse
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/stats/_continuous_distns.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from . import _stats
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio4.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from .mio_utils import squeeze_element, chars_to_strings
[13:22:37]	/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio5.py:98: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:22:37]	  from .mio5_utils import VarReader5
[13:22:37]	Traceback (most recent call last):
[13:22:37]	  File "test_recognize_digits_conv.py", line 138, in <module>
[13:22:37]	    main(use_cuda=core.is_compiled_with_cuda())
[13:22:37]	  File "test_recognize_digits_conv.py", line 129, in main
[13:22:37]	    params_dirname=params_dirname)
[13:22:37]	  File "test_recognize_digits_conv.py", line 72, in train
[13:22:37]	    parallel=True)
[13:22:37]	  File "/paddle/build/python/paddle/fluid/trainer.py", line 280, in __init__
[13:22:37]	    exe.run(self.startup_program)
[13:22:37]	  File "/paddle/build/python/paddle/fluid/executor.py", line 466, in run
[13:22:37]	    self.executor.run(program.desc, scope, 0, True, True)
[13:22:37]	paddle.fluid.core.EnforceNotMet: enforce allocating <= available failed, 1822361026 > 409206528
[13:22:37]	 at [/paddle/paddle/fluid/platform/gpu_info.cc:119]
[13:22:37]	PaddlePaddle Call Stacks: 
[13:22:37]	0       0x7f474498bf38p paddle::platform::GpuMaxChunkSize() + 5080
[13:22:37]	1       0x7f47448922c2p
[13:22:37]	2       0x7f478a98da99p
[13:22:37]	3       0x7f4744891aacp paddle::memory::GetGPUBuddyAllocator(int) + 108
[13:22:37]	4       0x7f4744891b4bp void* paddle::memory::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace, unsigned long) + 43
[13:22:37]	5       0x7f4744884e54p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::type_index) + 1492
[13:22:37]	6       0x7f4743a5aa4cp paddle::operators::FillConstantOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 988
[13:22:37]	7       0x7f47447e1dd4p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 340
[13:22:37]	8       0x7f4743804658p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 328
[13:22:37]	9       0x7f474380574ap paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 154
[13:22:37]	10      0x7f47436f8332p
[13:22:37]	11      0x7f4743737814p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
[13:22:37]	12            0x4c37edp PyEval_EvalFrameEx + 31165
[13:22:37]	13            0x4b9ab6p PyEval_EvalCodeEx + 774
[13:22:37]	14            0x4c16e7p PyEval_EvalFrameEx + 22711
[13:22:37]	15            0x4b9ab6p PyEval_EvalCodeEx + 774
[13:22:37]	16            0x4d55f3p
[13:22:37]	17            0x4eebeep
[13:22:37]	18            0x4ee7f6p
[13:22:37]	19            0x4aa9abp
[13:22:37]	20            0x4c15bfp PyEval_EvalFrameEx + 22415
[13:22:37]	21            0x4b9ab6p PyEval_EvalCodeEx + 774
[13:22:37]	22            0x4c1e6fp PyEval_EvalFrameEx + 24639
[13:22:37]	23            0x4b9ab6p PyEval_EvalCodeEx + 774
[13:22:37]	24            0x4c1e6fp PyEval_EvalFrameEx + 24639
[13:22:37]	25            0x4b9ab6p PyEval_EvalCodeEx + 774
[13:22:37]	26            0x4eb30fp
[13:22:37]	27            0x4e5422p PyRun_FileExFlags + 130
[13:22:37]	28            0x4e3cd6p PyRun_SimpleFileExFlags + 390
[13:22:37]	29            0x493ae2p Py_Main + 1554
[13:22:37]	30      0x7f478a5d5830p __libc_start_main + 240
[13:22:37]	31            0x4933e9p _start + 41
[13:22:37]	
[13:22:37]	
[13:22:37]	        Start 370: test_image_classification_resnet
[13:22:40]	352/381 Test #368: test_recognize_digits_mlp .......................   Passed   14.12 sec
[13:22:40]	        Start 371: test_image_classification_vgg
[13:22:43]	353/381 Test #364: test_machine_translation ........................   Passed   29.36 sec
[13:22:43]	        Start 372: test_understand_sentiment_conv
[13:24:06]	354/381 Test #370: test_image_classification_resnet ................***Failed   89.38 sec
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/special/__init__.py:640: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from ._ufuncs import *
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/linalg/basic.py:17: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from ._solve_toeplitz import levinson
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/linalg/__init__.py:207: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from ._decomp_update import *
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/special/_ellip_harm.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/interpolate/_bsplines.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from . import _bspl
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/lil.py:19: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from . import _csparsetools
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:165: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from ._shortest_path import shortest_path, floyd_warshall, dijkstra,\
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/_validation.py:5: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from ._tools import csgraph_to_dense, csgraph_from_dense,\
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:167: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from ._traversal import breadth_first_order, depth_first_order, \
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:169: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from ._min_spanning_tree import minimum_spanning_tree
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/sparse/csgraph/__init__.py:170: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from ._reordering import reverse_cuthill_mckee, maximum_bipartite_matching, \
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:95: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from .ckdtree import *
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/spatial/__init__.py:96: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from .qhull import *
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/spatial/_spherical_voronoi.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from . import _voronoi
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/spatial/distance.py:122: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from . import _hausdorff
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/optimize/_trlib/__init__.py:1: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from ._trlib import TRLIBQuadraticSubproblem
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/optimize/_numdiff.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from ._group_columns import group_dense, group_sparse
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/stats/_continuous_distns.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from . import _stats
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio4.py:18: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from .mio_utils import squeeze_element, chars_to_strings
[13:24:06]	/usr/local/lib/python2.7/dist-packages/scipy/io/matlab/mio5.py:98: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
[13:24:06]	  from .mio5_utils import VarReader5
[13:24:06]	Loss 5.4e+01, Acc 0.1
[13:24:06]	infer results:  [array([[1.6038109e-28, 1.0000000e+00, 1.6038109e-28, 1.6038109e-28,
[13:24:06]	        1.6038109e-28, 1.6038109e-28, 1.6038109e-28, 1.6147344e-25,
[13:24:06]	        1.6038109e-28, 1.6038109e-28]], dtype=float32)]
[13:24:06]	Traceback (most recent call last):
[13:24:06]	  File "test_image_classification_resnet.py", line 160, in <module>
[13:24:06]	    main(use_cuda=use_cuda)
[13:24:06]	  File "test_image_classification_resnet.py", line 150, in main
[13:24:06]	    params_dirname=save_path)
[13:24:06]	  File "test_image_classification_resnet.py", line 119, in train
[13:24:06]	    train_func=train_program, optimizer_func=optimizer_func, place=place)
[13:24:06]	  File "/paddle/build/python/paddle/fluid/trainer.py", line 280, in __init__
[13:24:06]	    exe.run(self.startup_program)
[13:24:06]	  File "/paddle/build/python/paddle/fluid/executor.py", line 466, in run
[13:24:06]	    self.executor.run(program.desc, scope, 0, True, True)
[13:24:06]	paddle.fluid.core.EnforceNotMet: enforce allocating <= available failed, 1822361026 > 409206528
[13:24:06]	 at [/paddle/paddle/fluid/platform/gpu_info.cc:119]
[13:24:06]	PaddlePaddle Call Stacks: 
[13:24:06]	0       0x7fe24aee3f38p paddle::platform::GpuMaxChunkSize() + 5080
[13:24:06]	1       0x7fe24adea2c2p
[13:24:06]	2       0x7fe2610f3a99p
[13:24:06]	3       0x7fe24ade9aacp paddle::memory::GetGPUBuddyAllocator(int) + 108
[13:24:06]	4       0x7fe24ade9b4bp void* paddle::memory::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace, unsigned long) + 43
[13:24:06]	5       0x7fe24addce54p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::type_index) + 1492
[13:24:06]	6       0x7fe249fb2a4cp paddle::operators::FillConstantOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 988
[13:24:06]	7       0x7fe24ad39dd4p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 340
[13:24:06]	8       0x7fe249d5c658p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 328
[13:24:06]	9       0x7fe249d5d74ap paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 154
[13:24:06]	10      0x7fe249c50332p
[13:24:06]	11      0x7fe249c8f814p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
[13:24:06]	12            0x4c37edp PyEval_EvalFrameEx + 31165
[13:24:06]	13            0x4b9ab6p PyEval_EvalCodeEx + 774
[13:24:06]	14            0x4c16e7p PyEval_EvalFrameEx + 22711
[13:24:06]	15            0x4b9ab6p PyEval_EvalCodeEx + 774
[13:24:06]	16            0x4d55f3p
[13:24:06]	17            0x4eebeep
[13:24:06]	18            0x4ee7f6p
[13:24:06]	19            0x4aa9abp
[13:24:06]	20            0x4c15bfp PyEval_EvalFrameEx + 22415
[13:24:06]	21            0x4b9ab6p PyEval_EvalCodeEx + 774
[13:24:06]	22            0x4c1e6fp PyEval_EvalFrameEx + 24639
[13:24:06]	23            0x4b9ab6p PyEval_EvalCodeEx + 774
[13:24:06]	24            0x4c1e6fp PyEval_EvalFrameEx + 24639
[13:24:06]	25            0x4b9ab6p PyEval_EvalCodeEx + 774
[13:24:06]	26            0x4eb30fp
[13:24:06]	27            0x4e5422p PyRun_FileExFlags + 130
[13:24:06]	28            0x4e3cd6p PyRun_SimpleFileExFlags + 390
[13:24:06]	29            0x493ae2p Py_Main + 1554
[13:24:06]	30      0x7fe260d3b830p __libc_start_main + 240
[13:24:06]	31            0x4933e9p _start + 41
```

**Comment by guochaorong** [comment]
198 has five cards， maybe some one has used it. I have changed the passwd
