### ISSUE TITLE
Paddlepaddle如何求一个矩阵的MAX？类似fluid.layers.XXX的运算API

### ISSUE THREAD

**Issue by jayxio** [PaddlePaddle/Paddle#12706]
大家好！

现在在用paddle fluid写一些计算图，但是想写求矩阵中最大元素的值的时候，发现写不了。
我想用argmax先得坐标，然后再用crop把最大值切出来，但是报错，说是offset和input向量的维度不一致。但是paddlepaddle好像也没有类似numpy.squeeze的API。
```
logits_i_not_t = fluid.layers.elementwise_mul(screen_target_logit,logits)
logit_target = fluid.layers.elementwise_mul(target,logits)
maxlogit_i_not_t = fluid.layers.argmax(logits_i_not_t,axis=1)
crop = fluid.layers.crop(logits_i_not_t, shape=shape, offsets=maxlogit_i_not_t)
```
报错：
```
Traceback (most recent call last):
  File "cw_unit_test.py", line 219, in <module>
    fetch_list=[loss])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 449, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: enforce rank == offsets_tensor->dims()[0] failed, 2 != 1
Offsets size should be equal to dimension size of input tensor. at [/paddle/paddle/fluid/operators/crop_op.h:41]
PaddlePaddle Call Stacks:
0       0x7f303e122896p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
```
请求大神指点一下怎么做。感谢各位！

**Comment by QiJune** [comment]
Maybe reduce_max will help you.
http://paddlepaddle.org/documentation/api/zh/0.14.0/layers.html#reduce-max

**Comment by jayxio** [comment]
thank you man! This helps!!
