### ISSUE TITLE
GPU memory increases over time on transformer model.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#12749]
```
epoch: 0, batch: 1273, sum loss: 50075.968750, avg loss: 6.643137, ppl: 767.499207
batch_id:1274 data_len:4
epoch: 0, batch: 1274, sum loss: 46797.867188, avg loss: 6.571811, ppl: 714.663086
batch_id:1275 data_len:4
epoch: 0, batch: 1275, sum loss: 49036.671875, avg loss: 6.614956, ppl: 746.172180
batch_id:1276 data_len:4
epoch: 0, batch: 1276, sum loss: 51264.742188, avg loss: 6.851743, ppl: 945.527710
batch_id:1277 data_len:4
epoch: 0, batch: 1277, sum loss: 50207.035156, avg loss: 6.602714, ppl: 737.092651
batch_id:1278 data_len:4
epoch: 0, batch: 1278, sum loss: 49609.812500, avg loss: 6.864510, ppl: 957.676514
batch_id:1279 data_len:4
epoch: 0, batch: 1279, sum loss: 49413.003906, avg loss: 6.634399, ppl: 760.821655
batch_id:1280 data_len:4
Traceback (most recent call last):
  File "train.py", line 552, in <module>
    train(args)
  File "train.py", line 508, in train
    lr_scheduler, token_num, predict)
  File "train.py", line 420, in train_loop
    feed=feed_list)
  File "/paddle/build/build_develop/python/paddle/fluid/parallel_executor.py", line 272, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: enforce allocating <= available failed, 10485338341 > 1344995072
 at [/paddle/paddle/fluid/platform/gpu_info.cc:119]
PaddlePaddle Call Stacks:
0       0x7fcb409fb0b8p paddle::platform::GpuMaxChunkSize() + 5080
1       0x7fcb4091aa7bp void* paddle::memory::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace, unsigned long) + 507
2       0x7fcb4090ddd4p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::type_index) + 1492
3       0x7fcb3ff58c4cp paddle::operators::MatMulGradKernel<paddle::platform::CUDADeviceContext, float>::MatMul(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, paddle::framework::Tensor*) const + 156
4       0x7fcb3ff58ea5p paddle::operators::MatMulGradKernel<paddle::platform::CUDADeviceContext, float>::CalcInputGrad(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const&, bool, bool, paddle::framework::Tensor const&, bool, bool, paddle::framework::Tensor*) const + 165
5       0x7fcb3ff59a13p paddle::operators::MatMulGradKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1539
6       0x7fcb3ff59c8fp std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulGradKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulGradKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 47
7       0x7fcb40858951p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 705
8       0x7fcb40853e04p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 292
9       0x7fcb406606d6p
10      0x7fcb40685fedp
11      0x7fcb40685045p paddle::framework::details::OpHandleBase::RunAndRecordEvent(std::function<void ()> const&) + 869
12      0x7fcb406601f3p paddle::framework::details::ComputationOpHandle::RunImpl() + 83
13      0x7fcb40688a49p paddle::framework::details::OpHandleBase::Run(bool) + 393
14      0x7fcb4063a678p
15      0x7fcb4063b290p
16      0x7fcb3f8970cep std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) + 46
17      0x7fcb7c48aa99p
18      0x7fcb40639fddp
19      0x7fcb3f8983c3p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 339
20      0x7fcb76b55c80p
21      0x7fcb7c4836bap
22      0x7fcb7c1b941dp clone + 109
```

**Comment by chengduoZH** [comment]
This is because GPU memory is insufficient. You should cut down the batch_size.
