### ISSUE TITLE
08 demo machine translate "beam_search() got multiple values for keyword argument 'end_id'"

### ISSUE THREAD

**Issue by zhuantouer** [PaddlePaddle/Paddle#12855]
error message:
```
Traceback (most recent call last):
  File "infer.py", line 196, in <module>
    main(use_cuda)
  File "infer.py", line 191, in main
    decode_main(False)  # Beam Search does not support CUDA
  File "infer.py", line 133, in decode_main
    translation_ids, translation_scores = decode(context)
  File "infer.py", line 98, in decode
    beam_size, end_id=10, level=0)
TypeError: beam_search() got multiple values for keyword argument 'end_id'
```

**Comment by guoshengCS** [comment]
It might be caused by the version of paddle, please update your paddle and try again.

**Comment by zhuantouer** [comment]
@guoshengCS 用的就是fluid 0.14 cpu版

**Comment by guoshengCS** [comment]
beamseach有在0.14发版之后有修改

**Comment by zhuantouer** [comment]
api改了，demo还没改是么？

**Comment by guoshengCS** [comment]
demo也相应的修改了，感觉应该是demo的用法和你那边paddle版本的api不匹配

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
