### ISSUE TITLE
更新本地提交package中的paddle二进制后集群报错

### ISSUE THREAD

**Issue by JayEworld** [PaddlePaddle/Paddle#12859]
本地提交集群训练任务
之前是从wget http://paddle-mpi-package.gz.bcebos.com/cluster_train_cpu_nordma.tar.gz下载的提交程序包，但是发现不支持layer.factorization_machine，考虑是版本太低问题，于是按照“ 更新本地提交package中的paddle二进制”的步骤更新了程序包里的paddle。
更新时使用的whl是：paddlepaddle-latest-cp27-cp27m-linux_x86_64.whl
![image](https://user-images.githubusercontent.com/16730384/44443219-3346e200-a609-11e8-9f9f-0a349ba599a5.png)

集群是http://nmg-hpc-hlan-mon.dmop.baidu.com:8919/
提交的任务是app-user-20180822115211-3409
报错信息如下：
```
Wed Aug 22 12:10:41 2018[1,28]<stderr>:RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Wed Aug 22 12:10:41 2018[1,28]<stderr>:Traceback (most recent call last):
Wed Aug 22 12:10:41 2018[1,28]<stderr>:  File "conf/trainer_config.conf", line 184, in <module>
Wed Aug 22 12:10:41 2018[1,28]<stderr>:    pservers=os.getenv("PADDLE_PSERVERS", "127.0.0.1"))
Wed Aug 22 12:10:41 2018[1,28]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20180822115211-3409/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/__init__.py", line 128, in init
Wed Aug 22 12:10:41 2018[1,28]<stderr>:    import py_paddle.swig_paddle as api
Wed Aug 22 12:10:41 2018[1,28]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20180822115211-3409/workspace/python27-gcc482/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
Wed Aug 22 12:10:41 2018[1,28]<stderr>:    from util import DataProviderWrapperConverter
Wed Aug 22 12:10:41 2018[1,28]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20180822115211-3409/workspace/python27-gcc482/lib/python2.7/site-packages/py_paddle/util.py", line 18, in <module>
Wed Aug 22 12:10:41 2018[1,28]<stderr>:    import swig_paddle
Wed Aug 22 12:10:41 2018[1,28]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20180822115211-3409/workspace/python27-gcc482/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 28, in <module>
Wed Aug 22 12:10:41 2018[1,28]<stderr>:    _swig_paddle = swig_import_helper()
Wed Aug 22 12:10:41 2018[1,28]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20180822115211-3409/workspace/python27-gcc482/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
Wed Aug 22 12:10:41 2018[1,28]<stderr>:    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
Wed Aug 22 12:10:41 2018[1,28]<stderr>:ImportError: numpy.core.multiarray failed to import

```

**Comment by wanghaoshuang** [comment]
可以参考这里：https://stackoverflow.com/questions/33859531/runtimeerror-module-compiled-against-api-version-a-but-this-version-of-numpy-is

可以尝试在`before_hook.sh`脚本里升级下numpy

**Comment by JayEworld** [comment]
@wanghaoshuang 我看有好几个issue都提到按照“更新本地提交package中的paddle二进制”步骤不成功，比如 #11905 ，还有https://github.com/PaddlePaddle/Paddle/issues/12623，各种尝试都会出各种错，能像wget http://paddle-mpi-package.gz.bcebos.com/cluster_train_cpu_nordma.tar.gz一样提供一个0.12.0版本的包么

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
