### ISSUE TITLE
运行models下面的ocr_recognition模型时报错

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#12897]
运行命令

python train.py --model=attention --parallel=True

Traceback (most recent call last):
  File "train.py", line 218, in <module>
    main()
  File "train.py", line 214, in main
    train(args)
  File "train.py", line 97, in train
    use_cuda=True if args.use_gpu else False, loss_name=sum_cost.name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 165, in __init__
    build_strategy, num_trainers, trainer_id)
IndexError: _Map_base::at

**Comment by JiayiFeng** [comment]
将paddle和ocr_recognition都升级到最新代码并重新编译paddle，可以解决这个问题。
