### ISSUE TITLE
fluid.io.save_inference_model报错

### ISSUE THREAD

**Issue by wfeagle** [PaddlePaddle/Paddle#12891]
Traceback (most recent call last):
  File "train.py", line 206, in <module>
    main(args)
  File "train.py", line 180, in main
    args.num_passes)
  File "train.py", line 84, in train_net
    fluid.io.save_inference_model(epoch_model, ["words", "label"], prediction, exe)
  File "/home/disk1/wangfang20/.jumbo/lib/python2.7/site-packages/paddle/fluid/io.py", line 636, in save_inference_model
    prepend_feed_ops(inference_program, feeded_var_names)
  File "/home/disk1/wangfang20/.jumbo/lib/python2.7/site-packages/paddle/fluid/io.py", line 526, in prepend_feed_ops
    out = global_block.var(name)
  File "/home/disk1/wangfang20/.jumbo/lib/python2.7/site-packages/paddle/fluid/framework.py", line 898, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var label not in this block

**Comment by JiayiFeng** [comment]
这个错误的意思是在模型中没有发现名为`label`的Variable，请用`xxx.name`检查一下layers.data产生的Variable的名字。

**Comment by wfeagle** [comment]
```python
def train_net(train_reader,
        word_dict,
        label_dict,
        network,
        use_gpu,
        parallel,
        save_dirname,
        lr=1e-3,
        batch_size=256,
        pass_num=55):
    """
    train network
    """
    if network == "bilstm_net":
        network = bilstm_net
    elif network == "lstm_net":
        network = lstm_net
    elif network == "gru_net":
        network = gru_net
    else:
        print ("unknown network type")
        return
    # word seq data
    data = fluid.layers.data(
        name="words", shape=[1], dtype="int64", lod_level=1)
    # label data
    label = fluid.layers.data(name="label", shape=[1], dtype="int64")

    # set network
    cost, acc, prediction = network(data, label, len(word_dict), len(label_dict))

    # set optimizer
    sgd_optimizer = fluid.optimizer.Adam(learning_rate=lr,
            regularization=fluid.regularizer.L2Decay(8e-4))
    sgd_optimizer.minimize(cost)

    # set place, datafeeder, executor
    place = fluid.CUDAPlace(0) if use_gpu else fluid.CPUPlace()
    feeder = fluid.DataFeeder(feed_list=[data, label], place=place)
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program()) if parallel:
        train_exe = fluid.ParallelExecutor(use_cuda=True if use_gpu else False, loss_name=cost.name)
    else:
        train_exe = exe

    # start training...
    for pass_id in xrange(pass_num):
        pass_start = time.time()
        data_size, data_count, total_acc, total_cost = 0, 0, 0.0, 0.0
        for data in train_reader():
            # train a batch
            cost_np, acc_np = train_exe.run(feed=feeder.feed(data),
                 fetch_list=[cost.name, acc.name])
            avg_cost_np = np.array(cost_np).sum()
            avg_acc_np = np.array(acc_np).sum()
            data_size = len(data)
            total_cost += data_size * avg_cost_np
            total_acc += data_size * avg_acc_np
            data_count += data_size
        avg_cost = total_cost / data_count
        avg_acc = total_acc / data_count
        print("[train info]: pass_id: %d, avg_acc: %f, avg_cost: %f" %
            (pass_id, avg_acc, avg_cost))
        epoch_model = save_dirname + "/" + "epoch" + str(pass_id)
        # save the model
        fluid.io.save_inference_model(epoch_model, ["words"], prediction, exe)
```

这个是整个代码，我看words跟label出现的情况是一样的，为啥words可以但是label不可以呢？ 还有最后一行是该存储exe 还是train_exe呢？ 有没有相关文档介绍

**Comment by JiayiFeng** [comment]
在做`save_inference_model`的时候会对program进行裁剪，删除掉其中对于生成target（对你这里来说就是`prediction`）不必要的op和var。你的`label`对于inference时候生成prediction是不必要的，因此被裁剪掉了。

最后那个不是存储exe，是用exe来执行存储这个过程。传一个普通的Executor进去就行。
