### ISSUE TITLE
安装matplot问题

### ISSUE THREAD

**Issue by 1145520074** [PaddlePaddle/Paddle#1293]
在demo中用到了matplot，我尝试安装，但是出错了
![machi 2017-02-08 16-11-44](https://cloud.githubusercontent.com/assets/12948853/22728598/d3bbb7d2-ee19-11e6-948f-9addb6c14dbe.png)

然后看/home/tuku/.jumbo/var/jumbo/log/python-six.201702081609，提示如下
Installing python-six, version 1.10.0-1
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    import six
  File "/home/tuku/.jumbo/var/jumbo/tmp/jumbo.y5VAysVSE/python-six/src/six-1.10.0/six.py", line 27, in <module>
    import operator
ImportError: /home/tuku/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-dynload/operator.so: undefined symbol: _PyUnicodeUCS2_AsDefaultEncodedString
貌似跟paddle的python有关，求大神解答一二。

**Comment by luotao1** [comment]
应该用pip install matplotlib

**Comment by 1145520074** [comment]
多谢，这样确实可以安装了，但是出现了新的问题，
![machi 2017-02-08 16-11-44](https://cloud.githubusercontent.com/assets/12948853/22730836/7c696114-ee23-11e6-9716-30bc8bcef75a.png)
请问这是要安装什么，多谢！

**Comment by luotao1** [comment]
参考 #1292 
另外，以后直接贴错误信息的文字吧（用代码格式），图的话不方便其他用户搜索。

**Comment by 1145520074** [comment]
好的，错误信息如下
[tuku@bjyz-tuku-gpu1.bjyz.baidu.com mnist]$ python predict.py -c vgg_16_mnist.py -d .data/raw_data/ -m mnist_vgg_model/pass-00037
Traceback (most recent call last):
  File "predict.py", line 30, in <module>
    import matplotlib.pyplot as plt
  File "/home/tuku/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/tuku/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/tuku/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/home/tuku/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/home/tuku/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/tuku/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/home/tuku/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk

**Comment by VamWolf** [comment]
昨天也遇到了这个问题，是 一件安装工具python 里面没有带matplot . jumbo 安装python-matplotlib 应该就可以了. 看下PYTHONPATH 的路径.

**Comment by 1145520074** [comment]
我用jumbo 安装会出错啊

**Comment by leanna62** [comment]
这个问题我运行mnist demo预测时也遇到了，import _tkinter 出错，这个跟#1292没有关系吧，matplotlib也安装过了，但是还是不能解决。麻烦再看下吧 @luotao1 ，可能跟生成测试图片的那个部分有关系。

**Comment by dayhaha** [comment]
mnist demo那个predict.py的import matplotlib.pyplot as plt可以去掉，下面的代码里面没有用到matplotlib

**Comment by leanna62** [comment]
是因为导入了load_data这个文件中的read_data，这个文件中需要matplotlib来生成图片，所以不是predict.py中的import matplotlib.pyplot as plt影响的。@dayhaha

**Comment by dayhaha** [comment]
@leanna62  load_data里面其实就是main函数里面用matplotlib来画图了，但是predict.py在import read_data的时候不会调用load_data.py里面的main函数，所以我觉得应该还是 import matplotlib.pyplot as plt这行命令的影响。  我觉得解决方案应该就是 @VamWolf 所说的。  jumbo安装出错的原因我也不太清楚，我刚刚试了在CentOS 4.3 kernel 2.6.32_1-17-0-0的机器上用jumbo安装 python-matplotlib 正常。

**Comment by leanna62** [comment]
我用的是pip安装的matplotlib，已经安装成功了，本地是可以直接导入的，但运行的时候还是提示这个，我看网上有说是需要先安装tk，再编译python，才能导入import _tkinter，但paddle的python是自带的，所以还没想好怎么解决，不知道这边有什么解决方案吗？ @dayhaha

**Comment by jacquesqiao** [comment]
看起来是系统环境问题，与paddle无关，暂时close掉，如有需要请随时reopen
