### ISSUE TITLE
Nccl2 implemention check num_trainers.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#13035]
```
yq01-jpaas-ai00-let0039:853:1527 [0] INFO Using 256 threads
yq01-jpaas-ai00-let0039:853:1527 [0] INFO Min Comp Cap 6
yq01-jpaas-ai00-let0039:853:1527 [0] INFO NCCL_SINGLE_RING_THRESHOLD=131072
yq01-jpaas-ai00-let0039:853:1527 [0] INFO Ring 00 :    0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15
yq01-jpaas-ai00-let0039:853:1529 [2] INFO Ring 00 : 2[2] -> 3[3] via P2P/direct pointer
yq01-jpaas-ai00-let0039:853:1527 [0] INFO 15 -> 0 via NET/Socket/0
yq01-jpaas-ai00-let0039:853:1533 [6] INFO Ring 00 : 6[6] -> 7[7] via P2P/direct pointer
yq01-jpaas-ai00-let0039:853:1530 [3] INFO Ring 00 : 3[3] -> 4[4] via P2P/direct pointer
yq01-jpaas-ai00-let0039:853:1531 [4] INFO Ring 00 : 4[4] -> 5[5] via P2P/direct pointer
yq01-jpaas-ai00-let0039:853:1532 [5] INFO Ring 00 : 5[5] -> 6[6] via P2P/direct pointer
yq01-jpaas-ai00-let0039:853:1528 [1] INFO Ring 00 : 1[1] -> 2[2] via P2P/direct pointer
yq01-jpaas-ai00-let0039:853:1527 [0] INFO Ring 00 : 0[0] -> 1[1] via P2P/direct pointer
yq01-jpaas-ai00-let0039:853:853 [0] INFO Launch mode Group
Traceback (most recent call last):
  File "train.py", line 666, in <module>
    train(args)
  File "train.py", line 634, in train
    lr_scheduler, token_num, predict, trainers, trainer_id)
  File "train.py", line 457, in train_loop
    token_num)
  File "train.py", line 373, in test_context
    share_vars_from=train_exe)
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 161, in __init__
    build_strategy, num_trainers, trainer_id)
paddle.fluid.core.EnforceNotMet: enforce num_trainers > 1 failed, 1 <= 1
 at [/paddle/paddle/fluid/platform/nccl_helper.h:109]
```

**Comment by typhoonzero** [comment]
This is already fixed before.
