### ISSUE TITLE
多机同步时如果reduce_strategy使用fluid.BuildStrategy.ReduceStrategy.Reduce报错

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#13041]
```
Traceback (most recent call last):
  File "dist_mnist.py", line 163, in <module>
    runtime_main(TestDistMnist)
  File "/work/weike/svn/baidu/paddle/test/cts_test/dist_base.py", line 243, in runtime_main
    model.run_trainer(endpoints, trainer_id, trainers, run_params)
  File "/work/weike/svn/baidu/paddle/test/cts_test/dist_base.py", line 176, in run_trainer
    build_strategy=build_strategy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 165, in __init__
    build_strategy, num_trainers, trainer_id)
paddle.fluid.core.EnforceNotMet: can not find the right place for rpc op: recv at [/paddle/paddle/fluid/framework/details/multi_devices_graph_pass.cc:822]
PaddlePaddle Call Stacks:
```

**Comment by kolinwei** [comment]
已修复
