### ISSUE TITLE
run start_program 报：holder_ should not be null

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#13044]
paddle version:0.15.0
运行环境：多机单卡
运行命令：
```bash
python -u thirdparty/benchmark/fluid/fluid_benchmark.py --update_method pserver --model resnet --gpus 1 --batch_size 16 --pass_num 300 --iterations 1000
```
报错如下：
```bash
Traceback (most recent call last):
  File "thirdparty/benchmark/fluid_py_reader/fluid_benchmark.py", line 365, in <module>
    main()
  File "thirdparty/benchmark/fluid_py_reader/fluid_benchmark.py", line 336, in main
    train_parallel(*all_args)
  File "thirdparty/benchmark/fluid_py_reader/fluid_benchmark.py", line 169, in train_parallel
    startup_exe.run(startup_prog)
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:139]
PaddlePaddle Call Stacks: 
0       0x7f9b002c3d96p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f9b002c61f7p paddle::framework::Tensor::type() const + 151
2       0x7f9b012b0e05p paddle::framework::OperatorWithKernel::IndicateDataType(paddle::framework::ExecutionContext const&) const + 149
3       0x7f9b012b113fp paddle::framework::OperatorWithKernel::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 47
4       0x7f9b012b1627p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 199
5       0x7f9b012ae7fcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 252
6       0x7f9b0038bdd9p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 393
7       0x7f9b0038cbb0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
8       0x7f9b002a9a0dp
9       0x7f9b002d4a84p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
10      0x7f9b5edc8631p PyEval_EvalFrameEx + 24497
11      0x7f9b5edc9bcep PyEval_EvalCodeEx + 2190
12      0x7f9b5edc820ap PyEval_EvalFrameEx + 23434
13      0x7f9b5edc9bcep PyEval_EvalCodeEx + 2190
14      0x7f9b5ed477a1p
15      0x7f9b5ed18273p PyObject_Call + 83
16      0x7f9b5edc67c5p PyEval_EvalFrameEx + 16709
17      0x7f9b5edc8560p PyEval_EvalFrameEx + 24288
18      0x7f9b5edc9bcep PyEval_EvalCodeEx + 2190
19      0x7f9b5edc9ce2p PyEval_EvalCode + 50
20      0x7f9b5ede99e0p PyRun_FileExFlags + 176
21      0x7f9b5ede9bbfp PyRun_SimpleFileExFlags + 239
22      0x7f9b5edff454p Py_Main + 3188
23      0x7f9b5e0b3cddp __libc_start_main + 253
24            0x400649p
```

**Comment by typhoonzero** [comment]
使用 PR https://github.com/PaddlePaddle/Paddle/pull/12305 中 新的fluid_benchmark.py，
- 修改使用with guard将transpile扩起来
- 修改`if args.gpus >= 1 and os.getenv("PADDLE_TRAINING_ROLE") == "TRAINER":`，

按照上述命令并未复现。

详细方法：在一台物理机上模拟多机单卡，

pserver.sh:

```bash
export FLAGS_fraction_of_gpu_memory_to_use=0.0
export FLAGS_rpc_deadline=6000000
export PADDLE_TRAINING_ROLE=PSERVER
export PADDLE_PSERVER_ENDPOINTS=127.0.0.1:5002,127.0.0.1:5003
export PADDLE_TRAINERS=2
export GLOG_logtostderr=1
export GLOG_v=3

PADDLE_CURRENT_ENDPOINT=127.0.0.1:5002 PADDLE_TRAINER_ID=0 CUDA_VISIBLE_DEVICES=0,1 python fluid_benchmark.py --update_method pserver --model resnet --gpus 1 --batch_size 16 --pass_num 300 --iterations 1000 &> ps0 &
PADDLE_CURRENT_ENDPOINT=127.0.0.1:5003 PADDLE_TRAINER_ID=1 CUDA_VISIBLE_DEVICES=2,3 python fluid_benchmark.py --update_method pserver --model resnet --gpus 1 --batch_size 16 --pass_num 300 --iterations 1000 &> ps1 &
```

trainer.sh

```bash
export FLAGS_fraction_of_gpu_memory_to_use=0.0
export FLAGS_rpc_deadline=6000000
export PADDLE_TRAINING_ROLE=TRAINER
export PADDLE_PSERVER_ENDPOINTS=127.0.0.1:5002,127.0.0.1:5003
export PADDLE_TRAINERS=2
export GLOG_logtostderr=1
export GLOG_v=3

PADDLE_CURRENT_ENDPOINT=127.0.0.1:5002 PADDLE_TRAINER_ID=0 CUDA_VISIBLE_DEVICES=0 python fluid_benchmark.py --update_method pserver --model resnet --gpus 1 --batch_size 16 --pass_num 300 --iterations 1000 &> t0 &
PADDLE_CURRENT_ENDPOINT=127.0.0.1:5003 PADDLE_TRAINER_ID=1 CUDA_VISIBLE_DEVICES=1 python fluid_benchmark.py --update_method pserver --model resnet --gpus 1 --batch_size 16 --pass_num 300 --iterations 1000 &> t1 &
```

**Comment by typhoonzero** [comment]
I think it's fixed now.
