### ISSUE TITLE
fluid/core.so: undefined symbol: mkldnn_softmax_backward_desc_init

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#13059]
```
(paddle_v014_dev) [xxx.xxx]$ python -c "import paddle.fluid"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ar/shaoxiong/envs/vrts/paddle_v014_dev/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 17, in <module>
    from . import framework
  File "/home/ar/shaoxiong/envs/vrts/paddle_v014_dev/lib/python2.7/site-packages/paddle/fluid/framework.py", line 33, in <module>
    directory. The original error is: \n""" + cpt.get_exception_message(e))
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
    if you encounters "libmkldnn.so not found" errors. If you have python
    installed in other directory, replace "/usr/local/lib" with your own
    directory. The original error is: 
/home/ar/shaoxiong/envs/vrts/paddle_v014_dev/lib/python2.7/site-packages/paddle/fluid/core.so: undefined symbol: mkldnn_softmax_backward_desc_init
```
说明：
1. 使用 paddLe 官网docker gpu 环境编译
2. paddle code clone from github develop 分支
3. 在本地编译完成后，在服务器上部署，python -c "import paddle.fluid"， 出错

**Comment by Superjomn** [comment]
可编译时可以设置 CMAKE开关

```
-DWITH_MKL=ON -DWITH_MKLDNN=OFF
```

来去掉 mkldnn

**Comment by youngstu** [comment]
但是，关掉该选项，就不能使用mkldnn 加速库了吧。

**Comment by Superjomn** [comment]
mkldnn 现在只能在有限几个模型上加速，可以先关了

**Comment by velconia** [comment]
mkldnn 用于在支持MKL的机器上做预测加速, 请问 @youngstu 需要这个特性吗?

**Comment by velconia** [comment]
Seems solved, close this issue, please feel free to reopen it if you meet some error
