### ISSUE TITLE
model下rnn_search模型，多机运行时报错

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#13055]
Traceback (most recent call last):
  File "dist_rnn_search.py", line 141, in <module>
    runtime_main(TestDistRnnSearch)
  File "/work/weike/svn/baidu/paddle/test/cts_test/dist_base.py", line 246, in runtime_main
    model.run_trainer(endpoints, trainer_id, trainers, run_params)
  File "/work/weike/svn/baidu/paddle/test/cts_test/dist_base.py", line 142, in run_trainer
    train_prog = t.get_trainer_program()
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 358, in get_trainer_program
    self.origin_program.__str__()
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1445, in __str__
    return self.to_string(True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1477, in to_string
    res_str = _debug_string_(proto, throw_on_error)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 136, in _debug_string_
    format(error_fields, proto))
ValueError: ['blocks[0].vars[122].type.lod_tensor.tensor.data_type', 'blocks[0].vars[135].type.lod_tensor.tensor.data_type'] are not initialized.

**Comment by jacquesqiao** [comment]
这个是print(program)挂了是吧

**Comment by jacquesqiao** [comment]
我们的program有时候有些filed没有填完整，会导致这个问题，可以试试不加print

**Comment by kolinwei** [comment]
没有加print呀

**Comment by typhoonzero** [comment]
是transpile内有一个强制serilize的hack，在`get_trainer_program`，需要去掉这个hack。

另外这个问题应该是模型的配置会触发的transpile的bug。这个模型的case需要增加到单测

**Comment by yma-admin** [comment]
有没有对这个问题的系统解决方法？

**Comment by jacquesqiao** [comment]
我们的python layer实现现在是缺乏单测的，完善layer单测可以解决这个问题。

**Comment by kolinwei** [comment]
已修复
