### ISSUE TITLE
Operator测试test_grad报错

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#13067]
错误栈信息如下，请问如何解决？

```
308: Traceback (most recent call last):
308:   File "/mnt/tree_conv/build/python/paddle/fluid/tests/unittests/test_tree_conv_op.py", line 88, in test_check_grad
308:     self.check_grad(['NodesVector', 'Filter'], 'Out', max_relative_error=0.5)
308:   File "/mnt/tree_conv/build/python/paddle/fluid/tests/unittests/op_test.py", line 405, in check_grad
308:     user_defined_grads)
308:   File "/mnt/tree_conv/build/python/paddle/fluid/tests/unittests/op_test.py", line 441, in check_grad_with_place
308:     output_names, no_grad_set)
308:   File "/mnt/tree_conv/build/python/paddle/fluid/tests/unittests/op_test.py", line 519, in _get_gradient
308:     executor.run(prog, feed_dict, fetch_list, return_numpy=False)))
308:   File "/mnt/tree_conv/build/python/paddle/fluid/executor.py", line 470, in run
308:     self.executor.run(program.desc, scope, 0, True, True)
308: EnforceNotMet: cudaMemcpyAsync failed in paddle::platform::GpuMemcpyAsync: an illegal memory access was encountered at [/mnt/tree_conv/paddle/fluid/platform/gpu_info.cc:128]
308: PaddlePaddle Call Stacks: 
308: 0       0x7fd702ad02c6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
308: 1       0x7fd703b42bcap paddle::platform::GpuMemcpyAsync(void*, void const*, unsigned long, cudaMemcpyKind, CUstream_st*) + 234
308: 2       0x7fd703a6bdb6p paddle::framework::TensorCopy(paddle::framework::Tensor const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::platform::DeviceContext const&, paddle::framework::Tensor*) + 758
308: 3       0x7fd703a6c719p paddle::framework::TensorCopy(paddle::framework::Tensor const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::Tensor*) + 89
308: 4       0x7fd7039175dbp paddle::framework::Vector<short>::ImmutableCUDA(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>) const + 603
308: 5       0x7fd703917c16p paddle::framework::Vector<short>::CUDAMutableData(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>) + 134
308: 6       0x7fd703919927p paddle::operators::math::ConcatFunctor<paddle::platform::CUDADeviceContext, double>::operator()(paddle::platform::CUDADeviceContext const&, std::vector<paddle::framework::Tensor, std::allocator<paddle::framework::Tensor> > const&, int, paddle::framework::Tensor*) + 695
308: 7       0x7fd703736630p paddle::operators::TreeConvGradKernel<paddle::platform::CUDADeviceContext, double>::Compute(paddle::framework::ExecutionContext const&) const + 3056
308: 8       0x7fd703736ac0p _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm1EINS0_9operators18TreeConvGradKernelINS7_17CUDADeviceContextEfEENSA_ISB_dEEEEclEPKcSG_EUlS4_E_E9_M_invokeERKSt9_Any_dataS4_ + 32
308: 9       0x7fd7039cea16p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 534
308: 10      0x7fd7039cba9cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 252
308: 11      0x7fd702b97a69p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 393
308: 12      0x7fd702b98840p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
308: 13      0x7fd702ab60bdp
308: 14      0x7fd702ae0d64p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
308: 15      0x7fd73091dce8p PyEval_EvalFrameEx + 28264
```

**Comment by zzhzz** [comment]
尝试Concat了dim为(0, 30）的Tensor

**Comment by zzhzz** [comment]
该问题只在GPU下出现，疑似ConcatFunctor CUDA实现的BUG。

**Comment by reyoung** [comment]
我们现在立刻看一下，稍等

**Comment by chengduoZH** [comment]
@zzhzz 请问您的dim怎么会是(0, 30)呢？因为Tensor中element的个数是dim中各个维度的乘积，如果dim是(0, 30)，那么Tensor中element的个数就是0了。

**Comment by zzhzz** [comment]
手动make_ddim的结果，我想padding数据

**Comment by chengduoZH** [comment]
那您可能需要使用padding操作 而不是concat，这里有padding的functor，您可以参考一下，https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/math/padding.h
