### ISSUE TITLE
save_inference_model target_vars 问题

### ISSUE THREAD

**Issue by Renwb1991** [PaddlePaddle/Paddle#13071]
你好，我从[官网](http://paddlepaddle.org/)下载了入门案例，然后将其中的一句
```fluid.io.save_inference_model(save_dirname, ['x'], [y_predict], exe)``` 
更改为 
```fluid.io.save_inference_model(save_dirname, ['x'], [y_predict, avg_cost], exe)```。 

再执行，居然报错了。错误信息如下：
```
Traceback (most recent call last):
  File "example.py", line 88, in <module>
    infer(save_dirname)
  File "example.py", line 61, in infer
    fetch_list=fetch_targets)
  File "/home/renwenbin/tools/python276.dev/lib/python2.7/site-packages/paddle/fluid/executor.py", line 443, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:139]
PaddlePaddle Call Stacks:
0       0x7fbb738a2736p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fbb738a4ae7p paddle::framework::Tensor::type() const + 151
2       0x7fbb746d97bdp paddle::framework::OperatorWithKernel::IndicateDataType(paddle::framework::ExecutionContext const&) const + 109
3       0x7fbb746d9affp paddle::framework::OperatorWithKernel::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 47
4       0x7fbb746da00bp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::
platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::d
etail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::de
tail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::det
ail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 235
5       0x7fbb746d76edp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::
CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::var
iant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::vari
ant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::varia
nt::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 205
6       0x7fbb7393e4afp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, b
ool) + 255
7       0x7fbb7393f500p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
```

**Comment by xuezhong** [comment]
cost在预测网络不能计算，因为预测的时候没有label
