### ISSUE TITLE
请问训练出现这个问题是哪里错了呢....错误如下

### ISSUE THREAD

**Issue by lianqingsong** [PaddlePaddle/Paddle#13282]
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
    r = mapper(sample)
  File "/home/qingsong/pycharm项目/shuzi/MyReader.py", line 14, in train_mapper
    img = paddle.image.simple_transform(img, 256, self.imageSize, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 321, in simple_transform
    im = resize_short(im, resize_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 179, in resize_short
    h, w = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
    r = mapper(sample)
  File "/home/qingsong/pycharm项目/shuzi/MyReader.py", line 14, in train_mapper
    img = paddle.image.simple_transform(img, 256, self.imageSize, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 321, in simple_transform
    im = resize_short(im, resize_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 179, in resize_short
    h, w = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
    r = mapper(sample)
  File "/home/qingsong/pycharm项目/shuzi/MyReader.py", line 14, in train_mapper
    img = paddle.image.simple_transform(img, 256, self.imageSize, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 321, in simple_transform
    im = resize_short(im, resize_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 179, in resize_short
    h, w = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
    r = mapper(sample)
  File "/home/qingsong/pycharm项目/shuzi/MyReader.py", line 14, in train_mapper
    img = paddle.image.simple_transform(img, 256, self.imageSize, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 321, in simple_transform
    im = resize_short(im, resize_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 179, in resize_short
    h, w = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
    r = mapper(sample)
  File "/home/qingsong/pycharm项目/shuzi/MyReader.py", line 14, in train_mapper
    img = paddle.image.simple_transform(img, 256, self.imageSize, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 321, in simple_transform
    im = resize_short(im, resize_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 179, in resize_short
    h, w = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
    r = mapper(sample)
  File "/home/qingsong/pycharm项目/shuzi/MyReader.py", line 14, in train_mapper
    img = paddle.image.simple_transform(img, 256, self.imageSize, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 321, in simple_transform
    im = resize_short(im, resize_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 179, in resize_short
    h, w = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
    r = mapper(sample)
  File "/home/qingsong/pycharm项目/shuzi/MyReader.py", line 14, in train_mapper
    img = paddle.image.simple_transform(img, 256, self.imageSize, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 321, in simple_transform
    im = resize_short(im, resize_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 179, in resize_short
    h, w = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
    r = mapper(sample)
  File "/home/qingsong/pycharm项目/shuzi/MyReader.py", line 14, in train_mapper
    img = paddle.image.simple_transform(img, 256, self.imageSize, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 321, in simple_transform
    im = resize_short(im, resize_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 179, in resize_short
    h, w = im.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by chengduoZH** [comment]
您用的是很版本的Paddle? 0.10, 0.11, 0.12还是其他的。

**Comment by lucywsq** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题， 我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持!
