### ISSUE TITLE
fluid版本如何实现自定义线性回归？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#13397]
以下是tensorflow的自定义线性回归的例子，我按照这个改成PaddleFluid
```python
import tensorflow as tf
import numpy as np

# 定义数据
X = np.array([1., 2., 3., 4., 5.])
y = np.array([3., 5., 7., 9., 11.])

# 定义占位符
X_ = tf.placeholder(dtype=tf.float32)
y_ = tf.placeholder(dtype=tf.float32)
a = tf.get_variable('a', dtype=tf.float32, shape=[], initializer=tf.zeros_initializer)
b = tf.get_variable('b', dtype=tf.float32, shape=[], initializer=tf.zeros_initializer)

# 定义计算公式和损失函数
y_pred = a * X_ + b
loss = tf.constant(0.5) * tf.reduce_sum(tf.square(y_pred - y_))
# 定义优化方法
train_op = tf.train.GradientDescentOptimizer(learning_rate=1e-3).minimize(loss)

# 开始训练
num_epoch = 10000
learning_rate = 1e-3
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    for e in range(num_epoch):
        sess.run(train_op,
                 feed_dict={X_: X, y_: y})
        
    # 答应a和b
    print(sess.run([a, b]))
```

以下是PaaddleFluid的例子，运行没有通过，应该要怎么修改呢？
```python
import paddle.fluid as fluid
import numpy as np

X = np.array([1., 2., 3., 4., 5.])
y = np.array([3., 5., 7., 8., 11.])

X_ = fluid.layers.create_tensor(dtype="float32")
y_ = fluid.layers.create_tensor(dtype="float32")
a = fluid.layers.create_global_var(shape=[], dtype="float32", name='a', value=0)
b = fluid.layers.create_global_var(shape=[], dtype="float32", name='b', value=0)

y_pred = fluid.layers.mul(a, X_) + b
loss = fluid.layers.mul(fluid.layers.fill_constant(shape=[1], value=0.5, dtype="float32"),
                        fluid.layers.reduce_sum(fluid.layers.square(y_pred - y_)))

optimizer = fluid.optimizer.SGDOptimizer(learning_rate=1e-3)
optimizer.minimize(loss)

cpu = fluid.CPUPlace()
exe = fluid.executor.Executor(cpu)
exe.run(fluid.default_startup_program())


for pass_id in range(100):
    out = exe.run(fluid.default_main_program(),
                  feed={X_: X, y_: y},
                  fetch_list=[loss])
    print(out)
```

**Comment by velconia** [comment]
你好, 请问具体错误是什么呢? 另外你的变量都未定义正确的纬度

**Comment by yeyupiaoling** [comment]
@velconia 错误如下，其实我也不清楚我写的对不对
```
Traceback (most recent call last):
  File "/home/test/PycharmProjects/test1/test2.py", line 12, in <module>
    y_pred = fluid.layers.mul(a, X_) + b
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/layer_function_generator.py", line 198, in func
    type=op_type, inputs=inputs, outputs=outputs, attrs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 46, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1043, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 579, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: enforce x_dims.size() > x_num_col_dims failed, 1 <= 1
The input tensor X's rank of MulOp should be larger than x_num_col_dims. at [/paddle/paddle/fluid/operators/mul_op.cc:48]
PaddlePaddle Call Stacks: 
0       0x7f1787aa0376p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f1787dc76fep paddle::operators::MulOp::InferShape(paddle::framework::InferShapeContext*) const + 1582
2       0x7f1787b20691p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 881
3       0x7f1787af3915p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}, void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}&&, void (*)(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 213
4       0x7f1787aaf46cp pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2540
5             0x4c37edp PyEval_EvalFrameEx + 31165
6             0x4b9ab6p PyEval_EvalCodeEx + 774
7             0x4d55f3p
8             0x4eebeep
9             0x4ee7f6p
10            0x4aa9abp
11            0x4a577ep PyObject_Call + 62
12            0x4bed3dp PyEval_EvalFrameEx + 12045
13            0x4b9ab6p PyEval_EvalCodeEx + 774
14            0x4d55f3p
15            0x4a577ep PyObject_Call + 62
16            0x4bed3dp PyEval_EvalFrameEx + 12045
17            0x4b9ab6p PyEval_EvalCodeEx + 774
18            0x4c1e6fp PyEval_EvalFrameEx + 24639
19            0x4b9ab6p PyEval_EvalCodeEx + 774
20            0x4c1e6fp PyEval_EvalFrameEx + 24639
21            0x4b9ab6p PyEval_EvalCodeEx + 774
22            0x4eb30fp
23            0x4e5422p PyRun_FileExFlags + 130
24            0x4e3cd6p PyRun_SimpleFileExFlags + 390
25            0x493ae2p Py_Main + 1554
26      0x7f17a940c830p __libc_start_main + 240
27            0x4933e9p _start + 41
```

**Comment by velconia** [comment]
```fluid.layers.mul(x=[a, X_])``` 这是正确的使用方式, ```+```也请替换为```fluid.layers.sum```, 另外请保证变量的纬度是正确的, 具体纬度信息可以通过 print(a.shape) 打印出来

**Comment by yeyupiaoling** [comment]
@velconia 好像不行，因为那些不是单纯的变量，有的是占位符。

**Comment by velconia** [comment]
> 有的是占位符。

Fluid中是没有占位符的概念的, 全是变量, 类比于占位符的是 fluid.layers.data

**Comment by yeyupiaoling** [comment]
@velconia 还是报错呢，代码已经修改如下
```python
import paddle.fluid as fluid
import numpy as np

X = np.array([1., 2., 3., 4., 5.])
y = np.array([3., 5., 7., 8., 11.])

X_ = fluid.layers.data(name="X", shape=[5], dtype='float32')
y_ = fluid.layers.data(name="y", shape=[5], dtype='float32')
a = fluid.layers.create_global_var(shape=[], dtype="float32", name='a', value=0)
b = fluid.layers.create_global_var(shape=[], dtype="float32", name='b', value=0)

y_pred = fluid.layers.sum(x=[fluid.layers.mul(x=[a, X_]), b])
loss = fluid.layers.mul(fluid.layers.fill_constant(shape=[1], value=0.5, dtype="float32"),
                        fluid.layers.reduce_sum(fluid.layers.square(y_pred - y_)))

optimizer = fluid.optimizer.SGDOptimizer(learning_rate=1e-3)
optimizer.minimize(loss)

cpu = fluid.CPUPlace()
exe = fluid.executor.Executor(cpu)
exe.run(fluid.default_startup_program())

for pass_id in range(100):
    out = exe.run(fluid.default_main_program(),
                  feed={X_: X, y_: y},
                  fetch_list=[loss])
    print(out)
```

我觉得应该是这两行代码有问题
```
y_pred = fluid.layers.sum(x=[fluid.layers.mul(x=[a, X_]), b])
loss = fluid.layers.mul(fluid.layers.fill_constant(shape=[1], value=0.5, dtype="float32"),
                        fluid.layers.reduce_sum(fluid.layers.square(y_pred - y_)))
```

**Comment by velconia** [comment]
请问有具体报错信息吗?另外square的使用方式也请参考mul

**Comment by yeyupiaoling** [comment]
@velconia 报错如下：
```
Traceback (most recent call last):
  File "/home/test/PycharmProjects/test1/test.py", line 12, in <module>
    y_pred = fluid.layers.sum(x=[fluid.layers.mul(x=[a, X_]), b])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/layer_function_generator.py", line 174, in func
    dtype = infer_and_check_dtype(op_proto, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/layer_function_generator.py", line 154, in infer_and_check_dtype
    val = [args[0]]
IndexError: tuple index out of range
```

**Comment by yeyupiaoling** [comment]
@velconia 
>另外square的使用方式也请参考mul

在前面就报错啦，

**Comment by velconia** [comment]
还是希望明确一下你到底要做些什么, 我看了下你的代码, 这里应该使用 scale, 而不是 mul

**Comment by velconia** [comment]
另外sum_op中, 两个tensor的纬度需要保持一直, 所以b的shape也需要设置为 [5]

**Comment by yeyupiaoling** [comment]
@velconia 好的，我先明确一下我的需求，我就是要做一个线性回归的例子，当值如下是：
```
X = np.array([1., 2., 3., 4., 5.])
y = np.array([3., 5., 7., 9., 11.])
```
函数为：
```
y = a * x + b
```

损失函数为：

![image](https://user-images.githubusercontent.com/26297768/45659320-6f953180-bb26-11e8-882d-8df535aa6488.png)

求w和b
就是这样子。

**Comment by velconia** [comment]
对的, 但问题在于, x的shape是[5], 所以 a * X 如果要在数学上有理的话, 应该是对 x 这个 tensor scale 到 a 倍, + b 这个部分则要保证 b 这个 tensor 和 X 的 shape 是一致的

**Comment by yeyupiaoling** [comment]
@velconia 
a和b是一个常量，不是张量。

**Comment by yeyupiaoling** [comment]
@velconia 比如上面提问中的TensorFlow例子输出的a和b是：
```
[2.0000324, 0.9998889]
```

**Comment by velconia** [comment]
张量是不能和常量相加的, 所以你需要把b改成一个[5]的张量

**Comment by velconia** [comment]
Seems no more questions, I will close it
