### ISSUE TITLE
test_se_resnext meets error on CI.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#13450]
```
[01:27:20][Step 1/1] local_loss: 
[01:27:20][Step 1/1] local_stderr: b'Traceback (most recent call last):\n  File "dist_se_resnext.py", line 258, in <module>\n    runtime_main(DistSeResneXt2x2)\n  File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_base.py", line 147, in runtime_main\n    model.run_trainer(use_cuda, args)\n  File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_base.py", line 108, in run_trainer\n    data = next(reader_generator)\n  File "/paddle/build/python/paddle/batch.py", line 35, in batch_reader\n    for instance in r:\n  File "/paddle/build/python/paddle/reader/decorator.py", line 52, in reader\n    for e in map(func, *rs):\n  File "/paddle/build/python/paddle/dataset/flowers.py", line 129, in reader\n    data = batch[\'data\']\nKeyError: \'data\'\n'
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 50
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 49
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 48
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 47
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 46
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 45
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 44
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 43
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 42
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 41
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 40
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 39
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 38
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 37
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 36
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.591.port', left retry 35
[01:27:20][Step 1/1] dist_stderr: b'Traceback (most recent call last):\n  File "dist_se_resnext.py", line 258, in <module>\n    runtime_main(DistSeResneXt2x2)\n  File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_base.py", line 147, in runtime_main\n    model.run_trainer(use_cuda, args)\n  File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_base.py", line 108, in run_trainer\n    data = next(reader_generator)\n  File "/paddle/build/python/paddle/batch.py", line 35, in batch_reader\n    for instance in r:\n  File "/paddle/build/python/paddle/reader/decorator.py", line 52, in reader\n    for e in map(func, *rs):\n  File "/paddle/build/python/paddle/dataset/flowers.py", line 129, in reader\n    data = batch[\'data\']\nKeyError: \'data\'\n'
[01:27:20][Step 1/1] dist_loss: 
[01:27:20][Step 1/1] local_loss: 
[01:27:20][Step 1/1] local_stderr: b'Traceback (most recent call last):\n  File "dist_se_resnext.py", line 258, in <module>\n    runtime_main(DistSeResneXt2x2)\n  File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_base.py", line 147, in runtime_main\n    model.run_trainer(use_cuda, args)\n  File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_base.py", line 108, in run_trainer\n    data = next(reader_generator)\n  File "/paddle/build/python/paddle/batch.py", line 35, in batch_reader\n    for instance in r:\n  File "/paddle/build/python/paddle/reader/decorator.py", line 52, in reader\n    for e in map(func, *rs):\n  File "/paddle/build/python/paddle/dataset/flowers.py", line 129, in reader\n    data = batch[\'data\']\nKeyError: \'data\'\n'
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 50
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 49
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 48
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 47
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 46
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 45
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 44
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 43
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 42
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 41
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 40
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 39
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 38
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 37
[01:27:20][Step 1/1] waiting for pserver: [Errno 2] No such file or directory: '/tmp/paddle.977.port', left retry 36
[01:27:20][Step 1/1] dist_stderr: b'Traceback (most recent call last):\n  File "dist_se_resnext.py", line 258, in <module>\n    runtime_main(DistSeResneXt2x2)\n  File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_base.py", line 147, in runtime_main\n    model.run_trainer(use_cuda, args)\n  File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_base.py", line 108, in run_trainer\n    data = next(reader_generator)\n  File "/paddle/build/python/paddle/batch.py", line 35, in batch_reader\n    for instance in r:\n  File "/paddle/build/python/paddle/reader/decorator.py", line 52, in reader\n    for e in map(func, *rs):\n  File "/paddle/build/python/paddle/dataset/flowers.py", line 129, in reader\n    data = batch[\'data\']\nKeyError: \'data\'\n'
[01:27:20][Step 1/1] dist_loss: 
[01:27:20][Step 1/1] test_dist_se_resnext failed
[01:27:20][Step 1/1]  EE
[01:27:20][Step 1/1] ======================================================================
[01:27:20][Step 1/1] ERROR: test_se_resnext (test_dist_se_resnext.TestDistSeResneXt2x2)
[01:27:20][Step 1/1] ----------------------------------------------------------------------
[01:27:20][Step 1/1] Traceback (most recent call last):
[01:27:20][Step 1/1]   File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_se_resnext.py", line 25, in test_se_resnext
[01:27:20][Step 1/1]     self.check_with_place("dist_se_resnext.py", delta=1e-7)
[01:27:20][Step 1/1]   File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_base.py", line 321, in check_with_place
[01:27:20][Step 1/1]     dist_first_loss = eval(lines[0].replace(" ", ","))[0]
[01:27:20][Step 1/1]   File "<string>", line 0
[01:27:20][Step 1/1]     
[01:27:20][Step 1/1]     ^
[01:27:20][Step 1/1] SyntaxError: unexpected EOF while parsing
[01:27:20][Step 1/1] 
[01:27:20][Step 1/1] ======================================================================
[01:27:20][Step 1/1] ERROR: test_se_resnext (test_dist_se_resnext.TestDistSeResneXt2x2Async)
[01:27:20][Step 1/1] ----------------------------------------------------------------------
[01:27:20][Step 1/1] Traceback (most recent call last):
[01:27:20][Step 1/1]   File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_se_resnext.py", line 33, in test_se_resnext
[01:27:20][Step 1/1]     self.check_with_place("dist_se_resnext.py", delta=100)
[01:27:20][Step 1/1]   File "/paddle/build/python/paddle/fluid/tests/unittests/test_dist_base.py", line 321, in check_with_place
[01:27:20][Step 1/1]     dist_first_loss = eval(lines[0].replace(" ", ","))[0]
[01:27:20][Step 1/1]   File "<string>", line 0
[01:27:20][Step 1/1]     
[01:27:20][Step 1/1]     ^
[01:27:20][Step 1/1] SyntaxError: unexpected EOF while parsing
[01:27:20][Step 1/1] 
[01:27:20][Step 1/1] ----------------------------------------------------------------------
[01:27:20][Step 1/1] Ran 2 tests in 168.369s
[01:27:20][Step 1/1] 
[01:27:20][Step 1/1] FAILED (errors=2)
```

**Comment by typhoonzero** [comment]
Seems like the cached dataset on the CI server is of an old version. Clean that cached data should work.

**Comment by typhoonzero** [comment]
see https://github.com/PaddlePaddle/Paddle/pull/13707
