### ISSUE TITLE
如何移植v2模型到fluid?

### ISSUE THREAD

**Issue by yuzhichang** [PaddlePaddle/Paddle#13827]
我打算把deep fm从paddlepaddle v2 版模型https://github.com/PaddlePaddle/models/tree/develop/legacy/deep_fm移植到fluid。但是我找不到移植指导文档。特别是v2中的数据类型如何对应到fluid中：
paddle.data_type.dense_vector
paddle.data_type.sparse_binary_vector
paddle.data_type.integer_value

**Comment by JiabinYang** [comment]
1. layers.data只需要指定lod_level即可，dense_vector, interge_value默认都可以不用制定lod_level
2.  reader的返回还可以复用v2的reader， dense_vector返回numpy.array      


如果有更细节的问题麻烦 @qingqing01 @jacquesqiao 帮忙跟进一下

**Comment by yuzhichang** [comment]
我改动的代码在[这里](https://github.com/yuzhichang/models/tree/develop_yuzhichang)。
利用deep_fm/preprocess.py预处理生成了output/train.txt, output/test.txt。

遇到的问题：
```
(paddle_workdir) zhichyu@ak47:~/paddle_workdir/deep_fm$ python train.py --train_data_path /home/zhichyu/paddle_workdir/output/train.txt --test_data_path /home/zhichyu/paddle_workdir/output/test.txt
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    train(USE_GPU)
  File "train.py", line 101, in train
    train_func=train_program, place=place, optimizer_func=optimizer_func)
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/fluid/contrib/trainer.py", line 259, in __init__
    program_func_outs = train_func()
  File "train.py", line 71, in train_program
    predict = DeepFM(args.factor_size)
  File "/home/zhichyu/paddle_workdir/deep_fm/network_conf.py", line 59, in DeepFM
    fm_param_attr=fluid.ParamAttr(name="DenseFeatFactors"))
  File "/home/zhichyu/paddle_workdir/deep_fm/network_conf.py", line 31, in fm_layer
    param_attr=fm_param_attr)
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 417, in wrapper
    return method(*args, **kwargs)
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 7599, in factorization_machine
    assert isinstance(input, LayerOutput)
AssertionError
```

**Comment by yuzhichang** [comment]
我基于fluid重写了[legacy/deep_fm/network_conf.py](https://github.com/yuzhichang/models/blob/develop/legacy/deep_fm/network_conf.py)。

```
    dense_param = fluid.ParamAttr(name="DenseFeatFactors",
                                  initializer=fluid.initializer.Constant(0.0),
                                  trainable=True)
    sparse_param = fluid.ParamAttr(name="SparseFeatFactors",
                                   initializer=fluid.initializer.Constant(0.0),
                                   trainable=True)

    # ---------- second order term ---------------
    input_reshaped = fluid.layers.reshape(x=input, shape=[-1, 1])  # (N, 1)
    embeddings = fluid.layers.elementwise_mul(
        input_reshaped, fm_param_attr)  # (N, F)

```

遇到的问题是：
```
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    train(USE_GPU)
  File "train.py", line 101, in train
    train_func=train_program, place=place, optimizer_func=optimizer_func)
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/fluid/contrib/trainer.py", line 259, in __init__
    program_func_outs = train_func()
  File "train.py", line 71, in train_program
    predict = DeepFM(args.factor_size)
  File "/home/zhichyu/cpp/paddlepaddle/models/legacy/deep_fm/network_conf.py", line 87, in DeepFM
    fm_param_attr=dense_param)
  File "/home/zhichyu/cpp/paddlepaddle/models/legacy/deep_fm/network_conf.py", line 34, in fm_layer
    input_reshaped, fm_param_attr)  # (N, F)
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 6776, in elementwise_mul
    return _elementwise_op(LayerHelper('elementwise_mul', **locals()))
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 6723, in _elementwise_op
    'use_mkldnn': use_mkldnn})
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 50, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1207, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/home/zhichyu/paddle_workdir/lib/python2.7/site-packages/paddle/fluid/framework.py", line 656, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Input(Y) of elementwise op should not be null. at [/paddle/paddle/fluid/operators/elementwise_op.h:36]
```

我的疑问是：
1. 为什么ParamAttr没有初始化？
2. 是否需要设置ParamAttr的shape？我期望它的shape是N*F。

**Comment by jacquesqiao** [comment]
请参考https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleRec/ctr

**Comment by jacquesqiao** [comment]
因为长时间没有反馈，先关掉，有疑问再打开
