### ISSUE TITLE
paddle.fluid.core.EnforceNotMet: op gather does not have kernel for data_type ...

### ISSUE THREAD

**Issue by LihangLiu** [PaddlePaddle/Paddle#13899]
请问在用layers.gather的时候，碰到如下error是什么原因呢，issue里面没找到：

```
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    y_value = exe.run(main_program, feed={'x': x_tensor, 'ids':id_tensor}, fetch_list=[y])
  File "/home/disk2/ol/tools/anaconda2/envs/paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)

paddle.fluid.core.EnforceNotMet: op gather does not have kernel for data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN] at [/work/workspace/Paddle/paddle/fluid/framework/operator.cc:678]
PaddlePaddle Call Stacks: 
0       0x7f2ada55007cp paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 572
1       0x7f2adb5d7262p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1522
2       0x7f2adb5d2354p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 292
3       0x7f2ada63ff8fp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 559
4       0x7f2ada640ddap paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 154
5       0x7f2ada5317f2p
6       0x7f2ada570dc4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
7       0x7f2b70749fc7p PyEval_EvalFrameEx + 28695
8       0x7f2b7074c4e9p PyEval_EvalCodeEx + 2025
9       0x7f2b707499b8p PyEval_EvalFrameEx + 27144
10      0x7f2b7074c4e9p PyEval_EvalCodeEx + 2025
11      0x7f2b7074c70ap PyEval_EvalCode + 26
12      0x7f2b707659cdp
13      0x7f2b70766b48p PyRun_FileExFlags + 120
14      0x7f2b70767d68p PyRun_SimpleFileExFlags + 232
15      0x7f2b70779f8cp Py_Main + 2988
16      0x7f2b6f9b2bd5p __libc_start_main + 245
17      0x7f2b70a478bfp
```

源代码如下：
```python
import paddle
import paddle.fluid as fluid
from paddle.fluid import layers
import numpy as np

def net():
~~x = layers.data(name='x', shape=[2], dtype='float32', lod_level=0)
~~ids = layers.data(name='ids', shape=[-1], dtype='int64', lod_level=0)
~~y = layers.gather(x, ids)
~~return y


main_program = fluid.Program()
with fluid.program_guard(main_program):
~~y = net()

place = fluid.CUDAPlace(0)
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())

array = np.zeros([10, 2], dtype=int)
x_tensor = fluid.LoDTensor()
x_tensor.set(array, place)
x_tensor.set_lod([])

array = np.array([0, 3, 7], dtype=int)
id_tensor = fluid.LoDTensor()
id_tensor.set(array, place)
id_tensor.set_lod([])

y_value = exe.run(main_program, feed={'x': x_tensor, 'ids':id_tensor}, fetch_list=[y])
print ('return', y_value)
```

谢谢！

**Comment by LihangLiu** [comment]
Problem solved by change the type of `x` to float32 and `ids` to int32. But other data type should also work, right?

**Comment by Superjomn** [comment]
有一些 op 只能支持指定格式，比如lookup_table, 只能支持 int64_t

**Comment by cserken** [comment]
为什么gather这个op只能支持特定的数据类型呢?
