### ISSUE TITLE
模型训练完以后使用load_inference_model加载模型并输入测试数据格式错误

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#13942]
有三类input：

第一个：一维Id特征，例如input=9：
``` 
self.query_data = fluid.layers.data(
         name="query",
         shape=[1],
         dtype='int64')
```

第二个：不定长id序列，例如input=[2,4,17,8]
```
 self.query_char_data = fluid.layers.data(
         name="query_char",
         shape=[1],
         dtype='int64',
         lod_level=1)
```

第三个：4维定长vector,input=[0.2,0.4,0.1,0.5]：
```
self.query_history_cate1_ctr_data = fluid.layers.data(
        name="query_history_cate1_ctr",
        shape=[4],
        dtype='float32')
```

在预测时候，首先加载模型
```
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(model_path, exe)
```
然后:
```
score_list = exe.run(inference_program,
                feed={
                    feed_target_names[0]: fluid.create_lod_tensor([[9]], [[1]],, place),   #一维id
                    feed_target_names[1]: fluid.create_lod_tensor[[1,4,3,6,6,2]], [[6]], place), #id 序列
                    feed_target_names[2]: fluid.create_lod_tensor([[0.2,0.4,0.1,0.5]], [[1]], place), #4维定长
                },
                fetch_list=fetch_targets,
                return_numpy=False)
```
但是报错：
AssertionError: data and recursive_seq_lens do not match
如果将上述
```
 feed_target_names[2]: fluid.create_lod_tensor([[0.2,0.4,0.1,0.5]], [[1]], place),
```
替换成
```
 feed_target_names[2]: fluid.create_lod_tensor([[0.2,0.4,0.1,0.5]], [[4]], place),
```
则报错：
```
Traceback (most recent call last):
  File "infer.py", line 226, in <module>
    infer(input_data, str_data, use_cuda=False, model_path=epoch_path)
  File "infer.py", line 157, in infer
    return_numpy=False)
  File "/home/aladdin/caowei07/development/py_env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected out_dims[j] == ins[i][j], but received out_dims[j]:1 != ins[i][j]:44.
Input tensors should have the same elements except the specify axis. at [/paddle/paddle/fluid/operators/concat_op.cc:52]
PaddlePaddle Call Stacks:
0       0x7fc1b34ddd06p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fc1b40c68fep paddle::operators::ConcatOp::InferShape(paddle::framework::InferShapeContext*) const + 1438
2       0x7fc1b44d7969p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 73

```

不知道我用上述方法进行infer哪里不对，应该如何input数据

**Comment by colourful-tree** [comment]
同学可以尝试下面的使用方式试试看：
```
import paddle.fluid as fluid

main = fluid.Program()
startup = fluid.Program()
with fluid.program_guard(main, startup):
    query_data = fluid.layers.data(
         name="query",
         shape=[1],
         dtype='int64')
    query_char_data = fluid.layers.data(
         name="query_char",
         shape=[1],
         dtype='int64',
         lod_level=1)
    query_history_cate1_ctr_data = fluid.layers.data(
        name="query_history_cate1_ctr",
        shape=[4],
        dtype='float32')

place = fluid.CPUPlace()
exe = fluid.Executor(place)

feeder = fluid.DataFeeder(feed_list=[query_data, query_char_data, query_history_cate1_ctr_data], place=place)
score_list = exe.run(main,
                feed=feeder.feed([[[9], [1,2,3,4,5,6], [0.2, 0.3, 0.1, 0.1]]]),
                fetch_list=[query_data])
print score_list
```
