### ISSUE TITLE
'float64' datatype overflow when take computation

### ISSUE THREAD

**Issue by Albelt** [PaddlePaddle/Paddle#14002]
* Hi, I'm training a VGG16 network on image data, at first I set the image datatype to 'float32' and it's OK.
 But when I want to get a more accurate result and  set the image datatype ot 'float64' , it calls back:
```
Traceback (most recent call last):
  File "/home/albelt/.vscode/extensions/ms-python.python-2018.9.1/pythonFiles/experimental/ptvsd_launcher.py", line 115, in <module>
    vspd.run(filename, port_num, run_as, *sys.argv[1:])
  File "/home/albelt/.vscode/extensions/ms-python.python-2018.9.1/pythonFiles/experimental/ptvsd/ptvsd/debugger.py", line 43, in run
    run_main(address, filename, run_as, *args, **kwargs)
  File "/home/albelt/.vscode/extensions/ms-python.python-2018.9.1/pythonFiles/experimental/ptvsd/ptvsd/_local.py", line 52, in run_main
    runner(addr, name, kind == 'module', *extra, **kwargs)
  File "/home/albelt/.vscode/extensions/ms-python.python-2018.9.1/pythonFiles/experimental/ptvsd/ptvsd/runner.py", line 32, in run
    set_trace=False)
  File "/home/albelt/.vscode/extensions/ms-python.python-2018.9.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1107, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/albelt/.vscode/extensions/ms-python.python-2018.9.1/pythonFiles/experimental/ptvsd/ptvsd/_vendored/pydevd/pydevd.py", line 1114, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/albelt/paddle_test/train.py", line 171, in <module>
    train(train_config)
  File "/home/albelt/paddle_test/train.py", line 136, in train
    loss, lr = train_exe.run(fetch_list = fetch_list, feed=feeder.feed(data))
  File "/home/albelt/anaconda2/envs/paddle-14/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 269, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: op sign does not have kernel for data_type[double]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN] at [/paddle/paddle/fluid/framework/operator.cc:640]
PaddlePaddle Call Stacks:
0       0x7f9abe5ee376p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f9abee0a456p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_,boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 3014
2       0x7f9abee07450p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace,paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 208
3       0x7f9abed7bc5cp
4       0x7f9abed7b89cp paddle::framework::details::ComputationOpHandle::RunImpl() + 92
5       0x7f9abed9d98cp paddle::framework::details::OpHandleBase::Run(bool) + 28
6       0x7f9abed95a9ap
7       0x7f9abec86993p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
8       0x7f9abec87127p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
9       0x7f9aef694a99p
10      0x7f9abed946e2p
11      0x7f9abed98f36p std::thread::_Impl<std::_Bind_simple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1} ()> >::_M_run() + 406
12      0x7f9ad3b7a678p
13      0x7f9aef68d6bap
14      0x7f9aeecb341dp clone + 109

*** Aborted at 1540052044 (unix time) try "date -d @1540052044" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0xd) received by PID 15688 (TID 0x7f9ae5901700) from PID 13; stack trace: ***
    @     0x7f9aef697390 (unknown)
    @     0x7f9abee15623 paddle::framework::Scope::FindVarLocally()
    @     0x7f9abee15a42 paddle::framework::Scope::FindVarInternal()
    @     0x7f9abee159ae paddle::framework::Scope::FindVar()
    @     0x7f9abed7bb7a _ZNSt17_Function_handlerIFvvEZN6paddle9framework7details19ComputationOpHandle7RunImplEvEUlvE_E9_M_invokeERKSt9_Any_data
    @     0x7f9abed7b89c paddle::framework::details::ComputationOpHandle::RunImpl()
    @     0x7f9abed9d98c paddle::framework::details::OpHandleBase::Run()
    @     0x7f9abed95a9a _ZZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpEPNS0_13BlockingQueueIPNS1_13VarHandleBaseEEEPNS1_12OpHandleBaseEENKUlvE_clEv
    @     0x7f9abec86993 std::_Function_handler<>::_M_invoke()
    @     0x7f9abec87127 std::__future_base::_State_base::_M_do_set()
    @     0x7f9aef694a99 __pthread_once_slow
    @     0x7f9abed946e2 _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details24ThreadedSSAGraphExecutor5RunOpEPNS3_13BlockingQueueIPNS4_13VarHandleBaseEEEPNS4_12OpHandleBaseEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7f9abed98f36 _ZNSt6thread5_ImplISt12_Bind_simpleIFZN10ThreadPoolC1EmEUlvE_vEEE6_M_runEv
    @     0x7f9ad3b7a678 execute_native_thread_routine_compat
    @     0x7f9aef68d6ba start_thread
    @     0x7f9aeecb341d clone
    @                0x0 (unknown)
Segmentation fault (core dumped)
```
paddle version is 0.14.0 (cpu)

**Comment by Yancey0623** [comment]
I think we have supported mixed-precision training, maybe @dzhwinter is working on this feature, can you confirm this, please?

**Comment by dzhwinter** [comment]
mixed precision training is use float16 to training models, has nothing to do with this. 
Back to this issue, it's just because sign op doesn't register a double kernel.

**Comment by dzhwinter** [comment]
By the way, float32 is enough for VGG model. trust me.
