### ISSUE TITLE
在SSD网络中如何使用save_inference_model接口保存模型

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#14191]
在这个目标检测例子：https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/object_detection
我想使用使用save_inference_model接口来保存模型，但有一个参数我搞不懂
```python
fluid.io.save_inference_model('./model', ['image'], [????], exe)
```
就是第三个参数`target_vars`的值应该是什么呢？搞不懂。

**Comment by qingqing01** [comment]
@yeyupiaoling It should be the output of [`fluid.layers.detection_output`](https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/train.py#L118) .

**Comment by yeyupiaoling** [comment]
@qingqing01 
嗯嗯，我修改了一下，
我把：https://github.com/PaddlePaddle/models/blob/a8dc7ed3d95cf83d7ae0f7988628e6910f018a49/fluid/PaddleCV/object_detection/train.py#L165-L169
修改成：
```python
    test_py_reader, map_eval, nmsed_out, img = build_program(
        main_prog=test_prog,
        startup_prog=startup_prog,
        train_params=train_params,
        is_train=False)
```

在这一行https://github.com/PaddlePaddle/models/blob/a8dc7ed3d95cf83d7ae0f7988628e6910f018a49/fluid/PaddleCV/object_detection/train.py#L254 之后加上
```python
fluid.io.save_inference_model('./model', ['image'], [nmsed_out], exe)
```

这里https://github.com/PaddlePaddle/models/blob/a8dc7ed3d95cf83d7ae0f7988628e6910f018a49/fluid/PaddleCV/object_detection/train.py#L23 设置为False

但是报错，错误如下：
```
Traceback (most recent call last):
  File "train.py", line 319, in <module>
    val_file_list=val_file_list)
  File "train.py", line 256, in train
    fluid.io.save_inference_model('./model', ['image'], [nmsed_out], exe)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 637, in save_inference_model
    pruned_program = copy_program._prune(targets=target_vars)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1726, in _prune
    "The target variable must have an "
ValueError: The target variable must have an associated operator that generates it.
*** Aborted at 1541120574 (unix time) try "date -d @1541120574" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x8) received by PID 8657 (TID 0x7f0048045700) from PID 8; stack trace: ***
    @     0x7f004c64b390 (unknown)
    @           0x4bd63d PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4d55f3 (unknown)
    @           0x4a577e PyObject_Call
    @           0x4bed3d PyEval_EvalFrameEx
    @           0x4c136f PyEval_EvalFrameEx
    @           0x4c136f PyEval_EvalFrameEx
    @           0x4b9ab6 PyEval_EvalCodeEx
    @           0x4d54b9 (unknown)
    @           0x4eebee (unknown)
    @           0x4a577e PyObject_Call
    @           0x4c5e10 PyEval_CallObjectWithKeywords
    @           0x589172 (unknown)
    @     0x7f004c6416ba start_thread
    @     0x7f004c37741d clone
    @                0x0 (unknown)
Segmentation fault (core dumped)
```

**Comment by qingqing01** [comment]
@yeyupiaoling 

Feed var的name写错了，因为用了py_reader，对应的输入的name不在是 ‘image’，是img.name。

```
fluid.io.save_inference_model('./model', [img.name], [nmsed_out], exe)
```

我们在量化训练中的使用方式：

https://github.com/PaddlePaddle/models/blob/a8dc7ed3d95cf83d7ae0f7988628e6910f018a49/fluid/PaddleCV/object_detection/main_quant.py#L214

**Comment by yeyupiaoling** [comment]
@qingqing01 好的，我试试看。

**Comment by yeyupiaoling** [comment]
@qingqing01 可以了，谢谢青青姐。女神出手，bug快走。
