### ISSUE TITLE
预测时softmax激活函数速度较慢，请问如何加速

### ISSUE THREAD

**Issue by wfeagle** [PaddlePaddle/Paddle#14217]
神经网络的最后一层softmax，用于预测时速度比较慢，能否复用训练的模型参数，然后将最后一层softmax换成线性的，其实就是想去除softmax的归一化因子。
尝试过，发现最后一层的参数不认，报如下错误：
Traceback (most recent call last):
  File "infer.py", line 186, in <module>
    main(args)
  File "infer.py", line 177, in main
    args.model_path)
  File "infer.py", line 112, in infer_net
    output_layer=pred_layer, parameters=parameters)
  File "/home/disk1/wangfang20/software/python27-gcc482/lib/python2.7/site-packages/paddle/v2/inference.py", line 50, in __init__
    val.copyFromNumpyArray(parameters.get(name).flatten())
  File "/home/disk1/wangfang20/software/python27-gcc482/lib/python2.7/site-packages/paddle/v2/parameters.py", line 242, in get
    return self.__getitem__(key=parameter_name)
  File "/home/disk1/wangfang20/software/python27-gcc482/lib/python2.7/site-packages/paddle/v2/parameters.py", line 186, in __getitem__
    return self.__getter_inner(key, api.PARAMETER_VALUE)
  File "/home/disk1/wangfang20/software/python27-gcc482/lib/python2.7/site-packages/paddle/v2/parameters.py", line 153, in __getter_inner
    shape = self.get_shape(key)
  File "/home/disk1/wangfang20/software/python27-gcc482/lib/python2.7/site-packages/paddle/v2/parameters.py", line 200, in get_shape
    raise ValueError("No such parameter %s" % key)
ValueError: No such parameter ____fc_layer_0__.w0
PS：我不关心训练速度，只想在预测时加速，因为想放到线上使用

**Comment by phlrain** [comment]
可以将softmax 激活因子改成linear

**Comment by wsy1991** [comment]
大佬请问您解决这个问题了嘛。我也遇到了@phlrain

**Comment by wsy1991** [comment]
请问您解决这个问题了吗。我也遇到了相同
