### ISSUE TITLE
some error with pre-commit

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#14383]
尝试使用git commit时报错如下：

[INFO] Initializing environment for https://github.com/Lucas-C/pre-commit-hooks.git
An unexpected error has occurred: CalledProcessError: Command: ('/usr/libexec/git-core/git', '-C', '/root/.cache/pre-commit/repoE8NYe8', 'clone', '--no-checkout', 'https://github.com/Lucas-C/pre-commit-hooks.git', '.')
Return code: 129
Expected return code: 0
Output: (none)
Errors: 
    Unknown option: -C
    usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
               [-p|--paginate|--no-pager] [--no-replace-objects]
               [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
               [--help] COMMAND [ARGS]
    

Check the log at /root/.cache/pre-commit/pre-commit.log

请问如何解决

**Comment by zzhzz** [comment]
Log中的TraceBack如下：
Traceback (most recent call last):
 14   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/pre_commit/error_handler.py", line 47, in error_hand    ler
 15     yield
 16   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/pre_commit/main.py", line 260, in main
 17     return run(runner, args)
 18   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/pre_commit/commands/run.py", line 256, in run
 19     for _, hook in repo.hooks:
 20   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/cached_property.py", line 32, in __get__
 21     value = obj.__dict__[self.func.__name__] = self.func(obj)
 22   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/pre_commit/repository.py", line 161, in hooks
 23     if hook['id'] not in self.manifest_hooks:
 24   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/cached_property.py", line 32, in __get__
 25     value = obj.__dict__[self.func.__name__] = self.func(obj)
 26   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/pre_commit/repository.py", line 154, in manifest_hoo    ks
 27     repo_path = self.store.clone(repo, rev)
 28   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/pre_commit/store.py", line 153, in clone
 29     return self._new_repo(repo, ref, deps, clone_strategy)
 30   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/pre_commit/store.py", line 131, in _new_repo
 31     make_strategy(directory)
 32   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/pre_commit/store.py", line 149, in clone_strategy
 33     _git_cmd('clone', '--no-checkout', repo, '.')
 34   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/pre_commit/store.py", line 147, in _git_cmd
 35     return cmd_output('git', '-C', directory, *args, env=env)
 36   File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/pre_commit/util.py", line 178, in cmd_output
 37     returncode, cmd, retcode, output=(stdout, stderr),
 38 CalledProcessError: Command: ('/usr/libexec/git-core/git', '-C', '/root/.cache/pre-commit/repoE8NYe8', 'clone', '--no-check    out', 'https://github.com/Lucas-C/pre-commit-hooks.git', '.')
 39 Return code: 129
 40 Expected return code: 0
 41 Output: (none)
 42 Errors: 
 43     Unknown option: -C
 44     usage: git [--version] [--exec-path[=GIT_EXEC_PATH]] [--html-path]
 45                [-p|--paginate|--no-pager] [--no-replace-objects]
 46                [--bare] [--git-dir=GIT_DIR] [--work-tree=GIT_WORK_TREE]
 47                [--help] COMMAND [ARGS]
