### ISSUE TITLE
expand op 对第0维（size=-1）expand时，编译存在问题

### ISSUE THREAD

**Issue by zenghsh3** [PaddlePaddle/Paddle#14427]
```python
#!/usr/bin/env python
# coding=utf8
# File: test_expand.py

from paddle import fluid
import numpy as np

x = fluid.layers.data(name='x', shape=[1], dtype='float32')
y = fluid.layers.data(name='y', shape=[1], dtype='float32')
expanded_x = fluid.layers.expand(x, expand_times=[3, 1])
output = fluid.layers.concat([expanded_x, y], axis=1)

place = fluid.CPUPlace()
exe = fluid.Executor(place=place)
exe.run(fluid.default_startup_program())

feed = {'x': np.array([[0]], dtype='float32'),
        'y': np.array([[0], [0], [0]], dtype='float32')}
output_np = exe.run(feed=feed, fetch_list=[output])

print(output_np)

```
异常输出：
```plain
Traceback (most recent call last):
  File "test_expand.py", line 11, in <module>
    output = fluid.layers.concat([expanded_x, y], axis=1)
  File "/home/disk1/zenghongsheng/tools/paddle_py3/lib/python3.5/site-packages/paddle/fluid/layers/tensor.py", line 192, in concat
    attrs={'axis': axis})
  File "/home/disk1/zenghongsheng/tools/paddle_py3/lib/python3.5/site-packages/paddle/fluid/layer_helper.py", line 50, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/disk1/zenghongsheng/tools/paddle_py3/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1207, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/home/disk1/zenghongsheng/tools/paddle_py3/lib/python3.5/site-packages/paddle/fluid/framework.py", line 656, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected out_dims[j] == ins[i][j], but received out_dims[j]:-3 != ins[i][j]:-1.
Input tensors should have the same elements except the specify axis. at [/paddle/paddle/fluid/operators/concat_op.cc:52]
```

**Comment by zenghsh3** [comment]
感觉在编译过程中，对size为-1的维度做expand之后应该还是-1，但这里是-3

**Comment by velconia** [comment]
我觉得expand为-3是合理的，因为[128, 1]应该被expand为[384, 1], 所以在做sum等操作时，维度是无法和和[128, 1]对齐的

**Comment by zenghsh3** [comment]
size为正数是合理的，但是如果size为-1时，编译时不应该为-3吧（-3没有实际含义？）

**Comment by gavin1332** [comment]
这个op确实有问题，变成-3后可能导致后续shape匹配不通过

**Comment by velconia** [comment]
>size为正数是合理的，但是如果size为-1时，编译时不应该为-3吧（-3没有实际含义？）

确实，我和op的开发同学了解了一下，似乎在compile time确实有问题, -1 应该代表待推理值，我之前的解释有误， @wanghaoshuang 请问你方便看一下吗？

**Comment by gavin1332** [comment]
嗯，需要再infer_shape期间区分编译时和运行时
