### ISSUE TITLE
我在运行物体检测（SSD模型）的demo时候报错

### ISSUE THREAD

**Issue by Ouyangtengfang** [PaddlePaddle/Paddle#14476]
错误信息如下，请帮忙解决，谢谢！

```
root@64a1c51915ef:/object_detection# python -u train.py --batch_size=64 --dataset='pascalvoc' --pretrained_model='pretrained/ssd_mobilenet_v1_coco/'
-----------  Configuration Arguments -----------
ap_version: 11point
batch_size: 64
data_dir: data/pascalvoc
dataset: pascalvoc
enable_ce: False
epoc_num: 120
image_shape: 3,300,300
learning_rate: 0.001
mean_BGR: 127.5,127.5,127.5
model_save_dir: model
parallel: False
pretrained_model: pretrained/ssd_mobilenet_v1_coco/
use_gpu: False
------------------------------------------------
/usr/local/lib/python2.7/dist-packages/paddle/fluid/evaluator.py:71: Warning: The DetectionMAP is deprecated, because maintain a modified program inside evaluator cause bug easily, please use fluid.metrics.DetectionMAP instead.
  % (self.__class__.__name__, self.__class__.__name__), Warning)
train on pascalvoc with 16551 images
test on pascalvoc with 4952 images
*** Aborted at 1542547654 (unix time) try "date -d @1542547654" if you are using GNU date ***
    @     0x7f87a88d3390 (unknown)
    @     0x7f87a88d251d __libc_read
    @     0x7f87a06660ee (unknown)
    @     0x7f879987e02e ImagingConvert
    @     0x7f8799863fd3 (unknown)
    @     0x7f879986f560 ImagingResample
    @           0x4d54b9 (unknown)
    @           0x4eebee (unknown)
    @           0x4ee7f6 (unknown)
    @           0x4aa9ab (unknown)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/io.py", line 658, in __provider_thread__
    for tensors in func():
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/io.py", line 701, in __tensor_provider__
    for slots in paddle_reader():
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/data_feeder.py", line 277, in __reader_creator__
    yield self.feed(item)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/data_feeder.py", line 188, in feed
    for each_sample in iterable:
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "train.py", line 317, in <module>
    val_file_list=val_file_list)
  File "train.py", line 242, in train
    loss_v, = exe.run(train_prog, fetch_list=[loss])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected posix_memalign(&p, 4096ul, size) == 0, but received posix_memalign(&p, 4096ul, size):12 != 0:0.
Alloc 129482112 error! at [/paddle/paddle/fluid/memory/detail/system_allocator.cc:52]
PaddlePaddle Call Stacks:
0       0x7f878a626d86p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f878b066a5ap paddle::memory::detail::CPUAllocator::Alloc(unsigned long*, unsigned long) + 394
2       0x7f878b064525p paddle::memory::detail::BuddyAllocator::RefillPool() + 53
3       0x7f878b064d3cp paddle::memory::detail::BuddyAllocator::Alloc(unsigned long) + 716
4       0x7f878b05dae5p void* paddle::memory::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace, unsigned long) + 181
5       0x7f878b0581f9p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::type_index) + 441
6       0x7f878a631f31p float* paddle::framework::Tensor::mutable_data<float>(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>) + 65
7       0x7f878ab52ecap paddle::operators::BatchNormGradKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1098
8       0x7f878ab54ce3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::BatchNormGradKernel<paddle::platform::CPUDeviceContext, float>, 
```

**Comment by qingqing01** [comment]
```
TypeError: 'NoneType' object is not iterable
```

从错误来看是数据没有读取正确，返回的是None的。 可以在`reader.py`里下面两处，打印检查下数据：

数据产生的地方：https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/reader.py#L221
Python多进程加速的地方：https://github.com/PaddlePaddle/models/blob/develop/fluid/PaddleCV/object_detection/reader.py#L322

**Comment by qingqing01** [comment]
@Ouyangtengfang 请问解决了吗？

**Comment by Ouyangtengfang** [comment]
我把训练图片的尺寸从原来的1920*1080改成640*480后，这个问题就修复了，请问是最大的训练图片尺寸是什么？

**Comment by qingqing01** [comment]
@Ouyangtengfang 标准的SSD模型，可以是300*300， 512 * 512等，尺寸的大小、batch size会影响显存大小。 这个取决于你机器的显存大小。 另外，可以使用 http://www.paddlepaddle.org/documentation/docs/zh/1.1/api/fluid.html#permalink-18-memory_optimize  ，也可以参考图像分类、faster-rcnn模型使用方法。

**Comment by xiaochunWu** [comment]
> @Ouyangtengfang 标准的SSD模型，可以是300*300， 512 * 512等，尺寸的大小、batch size会影响显存大小。 这个取决于你机器的显存大小。 另外，可以使用 http://www.paddlepaddle.org/documentation/docs/zh/1.1/api/fluid.html#permalink-18-memory_optimize ，也可以参考图像分类、faster-rcnn模型使用方法。

您好，请问这个训练图片的尺寸是在哪里修改呀？是在reader.py中吗？reader.py中不是统一的将图片大小改变为300x300吗？麻烦您~

**Comment by qingqing01** [comment]
@Renewing 你的问题还是在 https://github.com/PaddlePaddle/Paddle/issues/14601 里讨论吧

**Comment by Ouyangtengfang** [comment]
问题已经解决了，谢谢！
