### ISSUE TITLE
ValueError: Operator "gen_nccl_id" has not been registered.

### ISSUE THREAD

**Issue by LihangLiu** [PaddlePaddle/Paddle#14533]
我在跑多机多卡的时候碰到了 ValueError: Operator "gen_nccl_id" has not been registered 的错误，

    config = fluid.DistributeTranspilerConfig()
    config.mode = "nccl2"
    t = fluid.DistributeTranspiler(config=config)
    t.transpile(trainer_id, trainers=trainers, current_endpoint=current_endpoint)

具体错误如下：

    Traceback (most recent call last):
      File "train.py", line 442, in <module>
        main(args, conf) 
      File "train.py", line 193, in main
        td_ct = PointerComputationTask(td_algorithm, args.train_mode, args.trainer_id)
      File "/home/ol/repos/gr-context-rnn/src/pointer_computation_task.py", line 54, in __init__
        self._define_executor(mode)
      File "/home/ol/repos/gr-context-rnn/src/pointer_computation_task.py", line 111, in _define_executor
        t.transpile(trainer_id, trainers=trainers, current_endpoint=current_endpoint)
      File "/home/ol/anaconda2/envs/paddle-dev/lib/python2.7/site-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 280, in transpile
        startup_program=startup_program)
      File "/home/ol/anaconda2/envs/paddle-dev/lib/python2.7/site-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 232, in _transpile_nccl2
        "trainer_id": trainer_id
      File "/home/ol/anaconda2/envs/paddle-dev/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1207, in append_op
        op = Operator(block=self, desc=op_desc, *args, **kwargs)
      File "/home/ol/anaconda2/envs/paddle-dev/lib/python2.7/site-packages/paddle/fluid/framework.py", line 578, in __init__
        proto = OpProtoHolder.instance().get_op_proto(type)
      File "/home/ol/anaconda2/envs/paddle-dev/lib/python2.7/site-packages/paddle/fluid/framework.py", line 482, in get_op_proto
        raise ValueError("Operator \"%s\" has not been registered." % type)
    ValueError: Operator "gen_nccl_id" has not been registered.

**Comment by LihangLiu** [comment]
版本是fluid1.1

**Comment by kuke** [comment]
Solved by `-DWITH_DISTRIBUTE=ON` in cmake

**Comment by haideeyuan** [comment]
> Solved by `-DWITH_DISTRIBUTE=ON` in cmake

遇见完全一样的问题，能具体解释一下如何操作吗？

**Comment by Longer767** [comment]
请问，这个问题解决了吗

**Comment by galaxystatistics** [comment]
同问
