### ISSUE TITLE
fluid.layers.scale 函数调用问题

### ISSUE THREAD

**Issue by Renwb1991** [PaddlePaddle/Paddle#14760]
在调用 fluid.layers.scale 出现如下的问题:
1）相同的输入，执行下面两条预计，出现的结果不一致。
```
scale, shift  = 2.0, 1.0
scale_out = fluid.layers.scale(input, scale=scale, bias=shift)
scale_out = fluid.layers.scale(input, scale, shift)
```
自己调试了下，发现第二种情况没有把`scale`的值传过去。

2）于是就使用第一种情况，进行调用。但是发现，即便使用
``` 
scale_out = fluid.layers.scale(input, scale=scale, bias=shift)
``` 
调用， `shift` 的值也没有传递过去。

求解决，谢谢。

**Comment by NHZlX** [comment]
我先复现一下问题。

**Comment by NHZlX** [comment]
**test_scale.py**
```
import paddle.fluid as fluid

x = fluid.layers.data(name='x', shape=[2, 1, 1], dtype='float32')

scale, shift = 2.0, 100.0
#scale_out = fluid.layers.scale(x, scale=scale, bias=shift)
scale_out = fluid.layers.scale(x, scale, shift)
```

**infer_test.py**
```
import paddle.fluid as fluid
import numpy as np
from test_scale import scale_out

img = np.ones([1, 2, 1, 1])

place = fluid.CPUPlace()
exe = fluid.Executor(place)
#exe.run(fluid.default_startup_program())
infer_program = fluid.default_main_program()

results = exe.run(infer_program,
		feed={'x': img},
		    fetch_list=[scale_out])

print results
```
打印的结果是：
```
[array([[[[102.]],

        [[102.]]]])]
```

我这里测试是没有问题的，请按照我的脚本测试一下，看是否有问题。
如果再有问题，请麻烦提供paddle的版本以及本地环境。

**Comment by Renwb1991** [comment]
按照上述的代码运行，结果为
```
[array([[[[1.]],

        [[1.]]]])]
```

paddle的版本: 0.14.0
commit: 9470a340ce36410df3b319915681d4472a29fb07
本地环境: Python 2.7.6

**Comment by NHZlX** [comment]
那可能是历史版本的bug， 麻烦升级一下paddle 版本。

**Comment by NHZlX** [comment]
你好，请问问题解决了么

**Comment by Renwb1991** [comment]
使用```pip install paddlepaddle-gpu``` 按照新版paddle.
然后，再次运行时，出现如下错误：
```
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/renwenbin/tools/python276.dev/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 17, in <module>
    from . import framework
  File "/home/renwenbin/tools/python276.dev/lib/python2.7/site-packages/paddle/fluid/framework.py", line 33, in <module>
    directory. The original error is: \n""" + cpt.get_exception_message(e))
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
    if you encounters "libmkldnn.so not found" errors. If you have python
    installed in other directory, replace "/usr/local/lib" with your own
    directory. The original error is: 
libmkldnn.so.0: cannot open shared object file: No such file or directory
```
将paddle 0.14.0中的libmkldnn.so.0拷贝过去时，再次运行，出现如下错误：
```
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/renwenbin/tools/python276.dev/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 17, in <module>
    from . import framework
  File "/home/renwenbin/tools/python276.dev/lib/python2.7/site-packages/paddle/fluid/framework.py", line 33, in <module>
    directory. The original error is: \n""" + cpt.get_exception_message(e))
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
    if you encounters "libmkldnn.so not found" errors. If you have python
    installed in other directory, replace "/usr/local/lib" with your own
    directory. The original error is: 
/home/renwenbin/tools/python276.dev/lib/python2.7/site-packages/paddle/fluid/core.so: undefined symbol: mkldnn_softmax_backward_desc_init
```

**Comment by NHZlX** [comment]
refer here: https://github.com/PaddlePaddle/Paddle/issues/14784
