### ISSUE TITLE
paddle  安装问题

### ISSUE THREAD

**Issue by Renwb1991** [PaddlePaddle/Paddle#14784]
使用 ```pip install paddlepaddle-gpu``` 按照新版paddle.
然后，再次运行时，出现如下错误：
```
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/renwenbin/tools/python276.dev/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 17, in <module>
    from . import framework
  File "/home/renwenbin/tools/python276.dev/lib/python2.7/site-packages/paddle/fluid/framework.py", line 33, in <module>
    directory. The original error is: \n""" + cpt.get_exception_message(e))
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
    if you encounters "libmkldnn.so not found" errors. If you have python
    installed in other directory, replace "/usr/local/lib" with your own
    directory. The original error is: 
libmkldnn.so.0: cannot open shared object file: No such file or directory
```
将paddle 0.14.0中的libmkldnn.so.0拷贝过去时，再次运行，出现如下错误：
```
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/renwenbin/tools/python276.dev/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 17, in <module>
    from . import framework
  File "/home/renwenbin/tools/python276.dev/lib/python2.7/site-packages/paddle/fluid/framework.py", line 33, in <module>
    directory. The original error is: \n""" + cpt.get_exception_message(e))
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
    if you encounters "libmkldnn.so not found" errors. If you have python
    installed in other directory, replace "/usr/local/lib" with your own
    directory. The original error is: 
/home/renwenbin/tools/python276.dev/lib/python2.7/site-packages/paddle/fluid/core.so: undefined symbol: mkldnn_softmax_backward_desc_init
```
求解答，谢谢

**Comment by JiabinYang** [comment]
请问下您使用的操作系统是什么呢

**Comment by Renwb1991** [comment]
```
Linux yq01-gpu-88-151-15-00.epc.baidu.com 3.10.0_3-0-0-15 #1 SMP Fri Jan 12 18:18:11 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by JiabinYang** [comment]
export LD_LIBRARY_PATH=/lib/python2.7/site-packages/paddle/libs:LD_LIBRARY_PATH
