### ISSUE TITLE
caffe2fluid工具保存的模型参数在fine tune时报错

### ISSUE THREAD

**Issue by nizihan** [PaddlePaddle/Paddle#14913]
利用https://github.com/PaddlePaddle/models/tree/develop/fluid/PaddleCV/caffe2fluid提供的工具对inceptionv3.caffemodel进行转换，利用如下代码进行保存参数：
    def convert(cls, npy_model, fluid_path, outputs=None):
        fluid = import_fluid()
        shapes = cls.input_shapes()
        input_name = shapes.keys()[0]
        feed_data = {}
        for name, shape in shapes.items():
            data_layer = fluid.layers.data(
                name=name, shape=shape, dtype="float32")
            feed_data[name] = data_layer

        net = cls(feed_data)
        place = fluid.CPUPlace()
        exe = fluid.Executor(place)
        exe.run(fluid.default_startup_program())
        net.load(data_path=npy_model, exe=exe, place=place)
        fluid.io.save_params(exe, "fluid")

加入到训练代码中进行训练，加载方式：
fluid.io.load_params(exe, "fluid_out")

训练结果：
loss没有正常收敛，在一个epoch结束后存参数的时候报错：
fluid.io.save_params(exe, save_path)

Traceback (most recent call last):
  File "train_spatial_attention.py", line 223, in <module>
    train(args)
  File "train_spatial_attention.py", line 216, in train
    fluid.io.save_params(exe, save_path)
  File "/ssd3/wangjian/test_new_tools_fold/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/io.py", line 267, in save_params
    filename=filename)
  File "/ssd3/wangjian/test_new_tools_fold/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/io.py", line 171, in save_vars
    filename=filename)
  File "/ssd3/wangjian/test_new_tools_fold/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/io.py", line 219, in save_vars
    executor.run(save_program)
  File "/ssd3/wangjian/test_new_tools_fold/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: cudaMemcpyAsync failed in paddle::platform::GpuMemcpyAsync: invalid device ordinal at [/paddle/paddle/fluid/platform/gpu_info.cc:178]

**Comment by hjchen2** [comment]
请问一下，模型已经转换成功了么？有生成对应的fluid模型么

**Comment by nizihan** [comment]
> 请问一下，模型已经转换成功了么？有生成对应的fluid模型么

有转换成功，生成了每一层的参数

**Comment by hjchen2** [comment]
请参考这个转换脚本进行模型转换，https://github.com/hjchen2/paddle-test/blob/master/convert_caffe2fluid/convert_googlenet.sh

**Comment by nizihan** [comment]
> 请参考这个转换脚本进行模型转换，https://github.com/hjchen2/paddle-test/blob/master/convert_caffe2fluid/convert_googlenet.sh
谢谢，已经能正常fine tune了～

**Comment by hjchen2** [comment]
好的，我先关闭这个issue了。如果有问题请重新开issue，谢谢。
