### ISSUE TITLE
fluid.io.load_inference_model读入model后op重复

### ISSUE THREAD

**Issue by Kayven** [PaddlePaddle/Paddle#14947]
fluid.io.load_inference_model保存的模型后部分feed重复了（save_inference_model能看到），exe.run测试的时候报错

``` text
` Traceback (most recent call last):

  File "infer_vis2.py", line 114, in <module>
    infer(test_reader, word_reverse_dict, use_cuda=False, model_path=epoch_path)
  File "infer_vis2.py", line 48, in infer
    return_numpy=False)
  File "/home/spider/xingzhihui/book/08.machine_translation/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 467, in run
    fetch_var_name=fetch_var_name)
  File "/home/spider/xingzhihui/book/08.machine_translation/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 313, in _add_feed_fetch_ops
    if not has_feed_operators(global_block, feed, feed_var_name):
  File "/home/spider/xingzhihui/book/08.machine_translation/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 130, in has_feed_operators
    "Feed operators in program desc do not match 'feed_targets'")
Exception: Feed operators in program desc do not match 'feed_targets'
```

预测的程序

``` python
  exe = fluid.Executor(place)
  inference_scope = fluid.core.Scope()
  with fluid.scope_guard(inference_scope):
      [inference_program, feed_target_names,
       fetch_targets] = fluid.io.load_inference_model(model_path, exe)
      print fetch_targets
      print feed_target_names

     for data in test_reader():
         cost1,acc,prediction, content_attention_weight, sent_attention_weight = exe.run(inference_program,
                       feed=utils_bak.data2tensor(data, place),
                       fetch_list=fetch_targets,
                       return_numpy=False)
```

**Comment by Yancey0623** [comment]
是book中的代码么？有复现的方法么？

**Comment by Yancey0623** [comment]
由于长时间未有更新的消息，先关闭这个issue了，如有更新可随时重新打开。
