### ISSUE TITLE
language_model lstm 下cudnn_model 训练错误

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#15033]
执行命令：
```bash
CUDA_VISIBLE_DEVICES=7 python train.py --data_path data/simple-examples/data/ --model_type small --use_gpu True --rnn_model cudnn --enable_ce
```

- 版本、环境信息：
    1）PaddlePaddle版本：develop分支 commitid=79bd6dfa18c6
    2）GPU：cuda8 cudnn5 mkl
- 训练信息
    1）单机单卡

错误日志如下：
```bash
finished load data
epoch id 0
Traceback (most recent call last):
  File "train.py", line 305, in <module>
    train()
  File "train.py", line 265, in train
    use_program_cache=True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: CUDNN_STATUS_BAD_PARAM at [/paddle/paddle/fluid/operators/cudnn_lstm_op.cu.cc:191]
PaddlePaddle Call Stacks: 
0       0x7f3cda4f318dp void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 365
1       0x7f3cda5ee37ap paddle::platform::EnforceNotMet::EnforceNotMet<char const*>(char const*, int, char const*) + 90
2       0x7f3cdaf9ac78p paddle::operators::CudnnRNNCache::init(cudnnContext*, paddle::framework::ExecutionContext const&, unsigned long, int, int, int, int, float, bool, int, int) + 4856
3       0x7f3cdaf9dabep paddle::operators::CudnnLSTMGPUKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 2990
4       0x7f3cdaf9df03p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CudnnLSTMGPUKernel<float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7f3cdbda743dp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 621
6       0x7f3cdbda338fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 479
7       0x7f3cda5cd59ap paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 218
8       0x7f3cda5cf2d5p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 261
9       0x7f3cda4d865bp
10      0x7f3cda518c7ep
11            0x4c5326p PyEval_EvalFrameEx + 37958
12            0x4b9b66p PyEval_EvalCodeEx + 774
13            0x4c17c6p PyEval_EvalFrameEx + 22758
14            0x4b9b66p PyEval_EvalCodeEx + 774
15            0x4c1f56p PyEval_EvalFrameEx + 24694
16            0x4b9b66p PyEval_EvalCodeEx + 774
17            0x4eb69fp
18            0x4e58f2p PyRun_FileExFlags + 130
19            0x4e41a6p PyRun_SimpleFileExFlags + 390
20            0x4938cep Py_Main + 1358
21      0x7f3d3a1d7830p __libc_start_main + 240
22            0x493299p _start + 41
```

**Comment by guoshengCS** [comment]
可以换cudnn6试下
