### ISSUE TITLE
What should be done if I need to repeatedly build a newly added op? 

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/Paddle#15043]
Suppose that I have a new op which is called my_op which contains `my_op.cc` and `my_op.h` file under the operators directory.  
The op can be built successfully via command "make -j$(nproc)". 
Now I changed something in `my_op.h ` or `my_op.cc` and run "make my_op" again, I found that the `Paddle/build/paddle/fluid/operators/CMakeFiles/my_op.dir/my_op.cc.o` and `Paddle/build/paddle/fluid/operators/libmy_op.a` is not been revised and still has the same revise date as when the first built was made.
So what's wrong with it, in my opinion, they should be changed.
Another question, after building, should I run "pip uninstall paddlepaddle-gpu" and reinstall the .whl file under "python/dist/"?

**Comment by guoshengCS** [comment]
I have tried but can not reproduce，the lib I got is revised indeed
```
λ instance-anrj0y4j /guosheng/repos/Paddle/build {beamsearch-return-parentidx} ll paddle/fluid/operators/libmul_op.a
-rw-r--r-- 1 root root 787K Dec 25 09:08 paddle/fluid/operators/libmul_op.a
λ instance-anrj0y4j /guosheng/repos/Paddle/build {beamsearch-return-parentidx}
λ instance-anrj0y4j /guosheng/repos/Paddle/build {beamsearch-return-parentidx} date
Tue Dec 25 09:08:51 UTC 2018
λ instance-anrj0y4j /guosheng/repos/Paddle/build {beamsearch-return-parentidx}
λ instance-anrj0y4j /guosheng/repos/Paddle/build {beamsearch-return-parentidx} vi ../paddle/fluid/operators/mul_op.cu.cc
λ instance-anrj0y4j /guosheng/repos/Paddle/build {beamsearch-return-parentidx}
λ instance-anrj0y4j /guosheng/repos/Paddle/build {beamsearch-return-parentidx} vi ../paddle/fluid/operators/mul_op.cu.cc
λ instance-anrj0y4j /guosheng/repos/Paddle/build {beamsearch-return-parentidx}
λ instance-anrj0y4j /guosheng/repos/Paddle/build {beamsearch-return-parentidx} make mul_op
[ 12%] Built target extern_gflags
[ 12%] Built target extern_glog
[ 12%] Built target header
[ 12%] Built target extern_snappy
[ 12%] Built target extern_zlib
[ 12%] Built target extern_snappystream
[ 12%] Built target chunk
[ 12%] Built target scanner
[ 12%] Built target writer
[ 12%] Generating recordio.dir/scanner.objdir
[ 12%] Generating recordio.dir/chunk.objdir
[ 12%] Generating recordio.dir/header.objdir
[ 12%] Generating recordio.dir/writer.objdir
[ 12%] Generating recordio.dir/scanner.objdir
[ 12%] Generating recordio.dir/chunk.objdir
[ 12%] Generating recordio.dir/header.objdir
[ 12%] Generating recordio.dir/writer.objdir
[ 12%] Built target recordio
[ 12%] Built target extern_boost
[ 12%] Built target boost
[ 12%] Built target extern_protobuf
[ 12%] Built target extern_mklml
[ 12%] Built target extern_mkldnn
[ 12%] Built target mkldnn
[ 12%] Built target extern_xbyak
[ 25%] Built target extern_cub
[ 25%] Built target extern_threadpool
[ 25%] Built target enforce
[ 25%] Built target dynamic_loader
[ 25%] Built target dynload_mklml
[ 25%] Built target cblas
[ 25%] Built target extern_xxhash
[ 25%] Built target extern_eigen3
[ 25%] Built target cpu_info
[ 25%] Built target memory_block
[ 25%] Built target gpu_info
[ 25%] Built target system_allocator
[ 25%] Built target buddy_allocator
[ 37%] Built target place
[ 37%] Built target allocator
[ 37%] Built target retry_allocator
[ 37%] Built target legacy_allocator
[ 50%] Built target locked_allocator
[ 50%] Built target cpu_allocator
[ 50%] Built target pinned_allocator
[ 50%] Built target aligned_allocator
[ 62%] Built target auto_increment_allocator
[ 62%] Built target cuda_device_guard
[ 62%] Built target cuda_allocator
[ 62%] Built target buffered_allocator
[ 75%] Built target zero_size_allocator
[ 75%] Built target conditional_allocator
[ 75%] Built target allocator_strategy
[ 75%] Built target best_fit_allocator
[ 75%] Built target allocator_facade
[ 75%] Built target malloc
[ 75%] Built target memcpy
[ 75%] Generating memory.dir/memcpy.objdir
[ 75%] Generating memory.dir/malloc.objdir
[ 75%] Generating memory.dir/memcpy.objdir
[ 75%] Generating memory.dir/malloc.objdir
[ 75%] Built target memory
[ 75%] Built target cpu_helper
[ 75%] Built target framework_proto
[ 87%] Built target profiler_proto
[ 87%] Built target dynload_cuda
[ 87%] Built target device_tracer
[ 87%] Built target stringpiece
[ 87%] Built target device_context
[ 87%] Built target profiler
[ 87%] Built target ddim
[ 87%] Built target data_type
[ 87%] Built target tensor
[ 87%] Built target selected_rows
[ 87%] Built target threadpool
[ 87%] Built target scope
[ 87%] Built target version
[ 87%] Built target lod_tensor
[ 87%] Built target data_device_transform
[ 87%] Built target data_type_transform
[ 87%] Built target blas
[ 87%] Built target math_function
[ 87%] Built target data_layout_transform
[ 87%] Built target data_transform
[ 87%] Built target transfer_scope_cache
[ 87%] Built target attribute
[100%] Built target op_info
[100%] Built target shape_inference
[100%] Built target operator
[100%] Built target op_proto_maker
[100%] Built target proto_desc
[100%] Built target op_registry
Scanning dependencies of target mul_op
[100%] Building CXX object paddle/fluid/operators/CMakeFiles/mul_op.dir/mul_op.cu.cc.o
[100%] Linking CXX static library libmul_op.a
[100%] Built target mul_op
λ instance-anrj0y4j /guosheng/repos/Paddle/build {beamsearch-return-parentidx} ll paddle/fluid/operators/libmul_op.a
-rw-r--r-- 1 root root 827K Dec 25 09:09 paddle/fluid/operators/libmul_op.a
λ instance-anrj0y4j /guosheng/repos/Paddle/build {beamsearch-return-parentidx}
```

Yes， `pip uninstall paddlepaddle-gpu` is suggested before install.

**Comment by TheodoreG** [comment]
Ok it seems  my fault, the `libmy_op.a` did update. But when I try to test the new op I got:
```
λ  /home/work/gaochenhao/detection/paddle_detection CUDA_VISIBLE_DEVICES=5 python test_my_op.py
Traceback (most recent call last):
  File "test_my_op.py", line 26, in <module>
    'positive_overlap': 2.9}
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 50, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1207, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 656, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Input X cannot be found in Op my at [/home/work/gaochenhao/code/Paddle/paddle/fluid/framework/op_desc.cc:179
]
PaddlePaddle Call Stacks:
0       0x7f06e1693bfcp paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 572
1       0x7f06e176c74cp paddle::framework::OpDesc::Input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > cons
t&) const + 524
2       0x7f06e176d412p paddle::framework::CompileTimeInferShapeContext::HasInput(std::__cxx11::basic_string<char, std::char_traits<char>, st
d::allocator<char> > const&) const + 50
3       0x7f06e1b773e2p paddle::operators::MyOp::InferShape(paddle::framework::InferShapeContext*) const + 82
4       0x7f06e176ccb0p
5       0x7f06e177128ap paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1050
6       0x7f06e170f80fp void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::f
ramework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::Bl
ockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*
, paddle::framework::BlockDesc const&)#1}, void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybin
d11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, p
ybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind
11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDes
c const&)#1}&&, void (*)(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method c
onst&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 223
7       0x7f06e16b4234p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
8             0x4c5326p PyEval_EvalFrameEx + 37958
9             0x4b9b66p PyEval_EvalCodeEx + 774
10            0x4d57a3p
11            0x4eef5ep
12            0x4eeb66p
13            0x4aaafbp
14            0x4a587ep PyObject_Call + 62
15            0x4be51ep PyEval_EvalFrameEx + 9790
16            0x4b9b66p PyEval_EvalCodeEx + 774
17            0x4d57a3p
18            0x4a587ep PyObject_Call + 62
19            0x4be51ep PyEval_EvalFrameEx + 9790
20            0x4b9b66p PyEval_EvalCodeEx + 774
21            0x4c1f56p PyEval_EvalFrameEx + 24694
22            0x4b9b66p PyEval_EvalCodeEx + 774
23            0x4eb69fp
24            0x4e58f2p PyRun_FileExFlags + 130
25            0x4e41a6p PyRun_SimpleFileExFlags + 390
26            0x4938cep Py_Main + 1358
27      0x7f0769c4c830p __libc_start_main + 240
28            0x493299p _start + 41
 at [/home/work/gaochenhao/code/Paddle/paddle/fluid/operators/my_op.cc:30]
PaddlePaddle Call Stacks:
0       0x7f06e1693bfcp paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 572
1       0x7f06e1b78332p paddle::operators::MyOp::InferShape(paddle::framework::InferShapeContext*) const + 4002
```


But I am sure `my_op.cc` has folloing 30th line:
`PADDLE_ENFORCE(ctx->HasInput("overlaps"), "Input(overlaps) of MyOp should not be null.");`
Actually I have revised input "X" into "overlaps" but it seems still use the old version. I am not sure what's wrong since `libmy_op.a` and `my_op.cc.o` is both up-to-date and I did reinstall paddlepaddle-gpu

**Comment by guoshengCS** [comment]
Please check to make sure that the python code uses `X` rather than `overlaps`. If it indeed uses `X`, maybe `make clean` can help.

**Comment by guoshengCS** [comment]
close this issue temporarily since no activity，please feel free to reopen.
