### ISSUE TITLE
version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by Datian1993** [PaddlePaddle/Paddle#15082]
在开发机环境下(centos6.3，python2.7.12)，使用pip install paddlepaddle==0.10.0后，在python下运行paddle.init(use_gpu=False, trainer_count=1)出现：

`>>> import paddle.v2 as paddle`
`>>> paddle.init(use_gpu=False, trainer_count=1)`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/martechAuditSTWeb/Python-2.7.12/lib/python2.7/site-packages/paddle/v2/__init__.py", line 66, in init
    import py_paddle.swig_paddle as api
  File "/home/work/martechAuditSTWeb/Python-2.7.12/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/home/work/martechAuditSTWeb/Python-2.7.12/lib/python2.7/site-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/home/work/martechAuditSTWeb/Python-2.7.12/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/home/work/martechAuditSTWeb/Python-2.7.12/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: /opt/compiler/gcc-4.8.2/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/work/martechAuditSTWeb/Python-2.7.12/lib/python2.7/site-packages/py_paddle/_swig_paddle.so)
```

**Comment by reyoung** [comment]
看起来是Python，Paddle和GCC三者编译的版本不同。。有几种解决办法

1. 用docker image
2. 如果是阡陌环境的话，阡陌有Paddle的镜像
3. 如果一定要用0.10.0版本的话，您可以下载Paddle代码自行编译。
4. 如果可以升级的话，升级一下Paddle的版本
