### ISSUE TITLE
Windows下pip安装失败

### ISSUE THREAD

**Issue by hellohuxg** [PaddlePaddle/Paddle#15125]
系统环境
1) PaddlePaddle版本1.2
2) CPU型号Intel(R) Core(TM) i5-5257U
3) 操作系统 Windows10 专业版

安装方式
1. 下载安装python
https://www.python.org/ftp/python/3.7.2/python-3.7.2-amd64.exe
2. 安装PaddlePaddle
pip3 install paddlepaddle
3. 执行python
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python-3.7.2\lib\site-packages\paddle\__init__.py", line 25, in <module>
    import paddle.dataset
  File "D:\Python-3.7.2\lib\site-packages\paddle\dataset\__init__.py", line 29, in <module>
    import paddle.dataset.flowers
  File "D:\Python-3.7.2\lib\site-packages\paddle\dataset\flowers.py", line 38, in <module>
    import scipy.io as scio
  File "D:\Python-3.7.2\lib\site-packages\scipy\io\__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "D:\Python-3.7.2\lib\site-packages\scipy\io\matlab\__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "D:\Python-3.7.2\lib\site-packages\scipy\io\matlab\mio.py", line 10, in <module>
    from .miobase import get_matfile_version, docfiller
  File "D:\Python-3.7.2\lib\site-packages\scipy\io\matlab\miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "D:\Python-3.7.2\lib\site-packages\scipy\misc\__init__.py", line 68, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "D:\Python-3.7.2\lib\site-packages\scipy\interpolate\__init__.py", line 175, in <module>
    from .interpolate import *
  File "D:\Python-3.7.2\lib\site-packages\scipy\interpolate\interpolate.py", line 21, in <module>
    import scipy.special as spec
  File "D:\Python-3.7.2\lib\site-packages\scipy\special\__init__.py", line 641, in <module>
    from ._ufuncs import *
  File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs
ImportError: DLL load failed: 找不到指定的模块。

**Comment by dzhwinter** [comment]
@wopeizl 请确认一下windows 3.7已经支持pip安装了吗？

**Comment by wopeizl** [comment]
支持，这个应该跟用户环境有关系，scipy重装一下


发自我的 iPhone

在 2019年1月1日，下午7:19，dzhwinter <notifications@github.com<mailto:notifications@github.com>> 写道：


@wopeizl<https://github.com/wopeizl> 请确认一下windows 3.7已经支持pip安装了吗？
