### ISSUE TITLE
fluid 集群训练 pserver报错RuntimeError: all distributed lookup_table_ops should have only one table

### ISSUE THREAD

**Issue by CruiseSun** [PaddlePaddle/Paddle#15133]
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    main(use_cuda, is_local)
  File "train.py", line 174, in main
    train(use_cuda=use_cuda, save_dirname=save_dirname, is_local=is_local)
  File "train.py", line 93, in train
    optimizer.minimize(avg_cost)
  File "/home/disk1/normandy/maybach/app-user-20181228115951-2365/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 310, in minimize
    self._process_distribute_lookuptable(params_grads, loss, startup_program)
  File "/home/disk1/normandy/maybach/app-user-20181228115951-2365/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 262, in _process_distribute_lookuptable
    table_name = find_distributed_lookup_table(program)
  File "/home/disk1/normandy/maybach/app-user-20181228115951-2365/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/distribute_lookup_table.py", line 33, in find_distributed_lookup_table
    raise RuntimeError("all distributed lookup_table_ops"
RuntimeError: all distributed lookup_table_ops should have only one table

**Comment by CruiseSun** [comment]
任务地址：http://10.74.179.26:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20181228115951-2365/

**Comment by velconia** [comment]
@CruiseSun 这里是说一个 program 不支持多个 embedding 表设置为 is_distributed=True

@jacquesqiao @seiriosPlus 辛苦看下有没有绕过的方法吗？

**Comment by velconia** [comment]
绕过方法已通过配置提供，close this issue

**Comment by LihangLiu** [comment]
我也碰到了这个问题，请问是怎样的配置可以绕过？

**Comment by jacquesqiao** [comment]
只能配置一个is_distributed=true的lookup table
