### ISSUE TITLE
在训练的时候报CUDNN_STATUS_EXECUTION_FAILED错误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15140]
# 环境
 - PaddlePaddle 1.2.0 GPU版本
 - Ubuntu 16.04
 - CUDA 9.0     CUDNN 7.4
 - 模型MobileNet V1

# 问题
在使用MobileNet V1训练图像分类的是报错，错误如下：
```
W0102 15:54:15.308672  4412 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 75, Driver Version: 10.0, Runtime Version: 9.0
W0102 15:54:15.308725  4412 device_context.cc:210] device: 0, cuDNN Version: 7.0.
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    fetch_list=[avg_cost, accuracy, param_name])
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: CUDNN_STATUS_EXECUTION_FAILED at [/paddle/paddle/fluid/operators/conv_cudnn_op.cu.cc:230]
PaddlePaddle Call Stacks: 
```

在跑官方的房价预测例子种正常运行。

**Comment by velconia** [comment]
请问Call Stacks能截取全部吗？这个问题的原因可能比较多，你的batch_size是多少？是几卡训练呢？

**Comment by velconia** [comment]
我看到你的CUDA Driver Version是cuda 10, 请问具体的卡是什么呢？可以考虑使用cuda 9.0 + cudnn 7.3试试

**Comment by yeyupiaoling** [comment]
@velconia 
**All logs:**
```
W0102 17:34:50.031576  2398 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 75, Driver Version: 10.0, Runtime Version: 9.0
W0102 17:34:50.031602  2398 device_context.cc:210] device: 0, cuDNN Version: 7.0.
Traceback (most recent call last):
  File "train.py", line 72, in <module>
    fetch_list=[avg_cost, accuracy, param_name])
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: CUDNN_STATUS_EXECUTION_FAILED at [/paddle/paddle/fluid/operators/conv_cudnn_op.cu.cc:230]
PaddlePaddle Call Stacks: 
0       0x7fc419a29e96p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fc41a1424e4p paddle::operators::CUDNNConvOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 4500
2       0x7fc41a143083p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvOpKernel<float>, paddle::operators::CUDNNConvOpKernel<double>, paddle::operators::CUDNNConvOpKernel<paddle::platform::float16> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
3       0x7fc41b22eafcp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 492
4       0x7fc41b22ac3fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
5       0x7fc419afeb63p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 227
6       0x7fc419aff590p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
7       0x7fc419a15c3bp
8       0x7fc419a5181ep
9             0x4ea137p PyCFunction_Call + 119
10            0x53c176p PyEval_EvalFrameEx + 23030
11            0x53fc97p
12            0x53b83fp PyEval_EvalFrameEx + 20671
13            0x53fc97p
14            0x5409bfp PyEval_EvalCode + 31
15            0x60cb42p
16            0x60efeap PyRun_FileExFlags + 154
17            0x60f7dcp PyRun_SimpleFileExFlags + 444
18            0x640256p Py_Main + 1110
19            0x4d0001p main + 225
20      0x7fc44c57d830p __libc_start_main + 240
21            0x5d6999p _start + 41

```

**cuda version:**
```
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

```

**Comment by yeyupiaoling** [comment]
> 我看到你的CUDA Driver Version是cuda 10, 请问具体的卡是什么呢？可以考虑使用cuda 9.0 + cudnn 7.3试试

![image](https://user-images.githubusercontent.com/26297768/50586959-c268de00-0eb6-11e9-9235-4244aadaf808.png)

**Comment by velconia** [comment]
可以用```nvidia-smi```看下```Driver Version```嘛？有可能是cudnn版本的问题，辛苦尝试一下cudnn 7.3, 也有可能是batch_size过大的原因，调小batch_size也有可能绕过这个问题

**Comment by yeyupiaoling** [comment]
@velconia 
```
test@test:~/Downloads$ nvidia-smi
Thu Jan  3 08:43:56 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   36C    P8     3W / 175W |    202MiB /  7949MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1018      G   /usr/lib/xorg/Xorg                           201MiB |
+-----------------------------------------------------------------------------+

```

**Comment by yeyupiaoling** [comment]
@velconia 
I tried CUDNN_7.3.1 and  CUDNN_7.0.5. Fail.
As same time, I set batch_size to 2. Fail.

ps: My computer can't input Chinses. I fixing it.

**Comment by velconia** [comment]
conv层可以不设置cudnn,

在[这里](http://www.paddlepaddle.org/documentation/docs/zh/1.2/api_cn/layers_cn.html#paddle.fluid.layers.conv2d)，设置use_cudnn=False

**Comment by yeyupiaoling** [comment]
@velconia 我在#15151 问题提到，并不能解决问题。最好是使用cudnn。

**Comment by yeyupiaoling** [comment]
@velconia 我真的想不到什么原因了，我安装过程是没有问题的，我检查了好多次了。

**Comment by velconia** [comment]
降低CUDA Driver Version呢？Paddle现在还没有对10.0作支持，怀疑也有可能是问题原因，可以降低到9.0试试

**Comment by yeyupiaoling** [comment]
@velconia 我不知道这个`CUDA Driver Version`东西是啥，我安装的cuda是9.0的。貌似那个安装驱动的时候自带的。
```
test@test:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```

**Comment by yeyupiaoling** [comment]
@velconia 有没有全局禁用cudnn 的？

**Comment by xuezhong** [comment]
先从cudnn安装这块再看下

**Comment by yeyupiaoling** [comment]
@velconia 我测试了7.4，7.3，7.0.5都是一样的结果。我的安装方式是解压cudnn，然后把文件复制到cuda-9.0中，如果过没有复制，所报的错误不是这个。

**Comment by yeyupiaoling** [comment]
@velconia 是不是我的显卡不能用?
![image](https://user-images.githubusercontent.com/26297768/50586959-c268de00-0eb6-11e9-9235-4244aadaf808.png)

**Comment by yeyupiaoling** [comment]
@velconia 我觉得可以怀疑是显卡驱动的问题了。因为我使用了官方提供的docker镜像：
```
hub.baidubce.com/paddlepaddle/paddle:1.2.0-gpu-cuda9.0-cudnn7
```
也是报同样错：
```
Traceback (most recent call last):
  File "train.py", line 78, in <module>
    fetch_list=[avg_cost, accuracy, param_name])
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: CUDNN_STATUS_EXECUTION_FAILED at [/paddle/paddle/fluid/operators/batch_norm_op.cu.cc:183]
PaddlePaddle Call Stacks: 
0       0x7f9e2c1dee96p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f9e2c9f05fcp paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 3340
2       0x7f9e2c9f1993p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
3       0x7f9e2d9e3afcp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 492
4       0x7f9e2d9dfc3fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
5       0x7f9e2c2b3b63p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 227
6       0x7f9e2c2b4590p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
7       0x7f9e2c1cac3bp
8       0x7f9e2c20681ep
9             0x4ea137p PyCFunction_Call + 119
10            0x53c176p PyEval_EvalFrameEx + 23030
11            0x53fc97p
12            0x53b83fp PyEval_EvalFrameEx + 20671
13            0x53fc97p
14            0x5409bfp PyEval_EvalCode + 31
15            0x60cb42p
16            0x60efeap PyRun_FileExFlags + 154
17            0x60f7dcp PyRun_SimpleFileExFlags + 444
18            0x640256p Py_Main + 1110
19            0x4d0001p main + 225
20      0x7f9e5ddcc830p __libc_start_main + 240
21            0x5d6999p _start + 41
```

**Comment by yeyupiaoling** [comment]
初步的结论是显卡RTX2070 只支持CUDA 10以上的，之前安装低于CUDA 10版本导致的错误。这一结论是通过测试Pytorch得到的。

**Comment by yeyupiaoling** [comment]
因为显卡RTX2070 只能使用CUDA 10以上，所以之前的错误就是这个原因。
我通过自己基于CUDA 10 和 CUDNN 7.4 编译得到的PaddlePaddle，能够正常使用。

**Comment by carychai** [comment]
@yeyupiaoling  有没有自行编译的过程参考

**Comment by yeyupiaoling** [comment]
@carychai 具体的没有，你可以先参考这个：https://yeyupiaoling.blog.csdn.net/article/details/83052060#UbuntuDocker_237
修改docker里面的CUDA
