### ISSUE TITLE
PaddlePaddle什么时候支持CUDA 10？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15172]
也不知道是不是我显卡RTX2070的问题，好像用不来cuda 9.0，如果使用cdua 9.0就使用不来cudnn。问题是：#15140
所以我觉得只能使用CUDA 10，所以想问一下，PaddlePaddle什么时候支持cuda 10

**Comment by sneaxiy** [comment]
您可以在CUDA 10的机器上本地编译Paddle源码试试。

**Comment by yeyupiaoling** [comment]
@sneaxiy 您们有没有测试过，PaddlePaddle能用 显卡RTX2070 吗？我的用不了cudnn。

**Comment by sneaxiy** [comment]
十分抱歉，我们还未在RTX2070上进行过测试。

**Comment by yeyupiaoling** [comment]
@sneaxiy 我用官方提供的docker镜像都用不了
```
hub.baidubce.com/paddlepaddle/paddle:1.2.0-gpu-cuda9.0-cudnn7
```

报错如下：
```
Traceback (most recent call last):
  File "train.py", line 78, in <module>
    fetch_list=[avg_cost, accuracy, param_name])
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: CUDNN_STATUS_EXECUTION_FAILED at [/paddle/paddle/fluid/operators/batch_norm_op.cu.cc:183]
PaddlePaddle Call Stacks: 
0       0x7f9e2c1dee96p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f9e2c9f05fcp paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 3340
2       0x7f9e2c9f1993p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
3       0x7f9e2d9e3afcp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 492
4       0x7f9e2d9dfc3fp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
5       0x7f9e2c2b3b63p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 227
6       0x7f9e2c2b4590p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
7       0x7f9e2c1cac3bp
8       0x7f9e2c20681ep
9             0x4ea137p PyCFunction_Call + 119
10            0x53c176p PyEval_EvalFrameEx + 23030
11            0x53fc97p
12            0x53b83fp PyEval_EvalFrameEx + 20671
13            0x53fc97p
14            0x5409bfp PyEval_EvalCode + 31
15            0x60cb42p
16            0x60efeap PyRun_FileExFlags + 154
17            0x60f7dcp PyRun_SimpleFileExFlags + 444
18            0x640256p Py_Main + 1110
19            0x4d0001p main + 225
20      0x7f9e5ddcc830p __libc_start_main + 240
21            0x5d6999p _start + 41
```

在docker中查看显卡信息是正常的：
```
root@f37ec4238ac2:/fruit# nvidia-smi
Mon Jan  7 02:47:25 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 2070    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   53C    P0    35W / 175W |    466MiB /  7949MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
官方提供的镜像应该环境是正确的吧？为什么会这样？

**Comment by yeyupiaoling** [comment]
估计是显卡RTX2070只支持CUDA 10的问题。

**Comment by yeyupiaoling** [comment]
@sneaxiy 
我使用参考官方文档：http://www.paddlepaddle.org/documentation/docs/zh/1.2/beginners_guide/install/compile/compile_Ubuntu.html
能正常编译CUDA 10的PaddlePaddle，并能够正常使用，

**Comment by qixuxiang** [comment]
@yeyupiaoling 我也是2080ti，训练不起来，求一份CUDA 10的paddle的pip安装包，邮箱1223790892@qq.com，多谢！！

**Comment by hang245141253** [comment]
@yeyupiaoling 你好 我也是RTX2070 cuda9装不上 装cuda10跑paddle又报错，请问可以稍微详细下说明本地编译的步骤吗？是直接源码编译还是Docker编译的呢？
我刚刚接触paddle ，虽然Tensorflow可以在cuda10运行，但还是想支持下国产，望回复

**Comment by yeyupiaoling** [comment]
@qixuxiang 晚点我发给你，安装包在另一个电脑上。你也可以自己编译。我的显卡时2070的

**Comment by yeyupiaoling** [comment]
@hang245141253 我用的是docker编译，更新里面的cuda和cudnn。编译教程：https://yeyupiaoling.blog.csdn.net/article/details/83052060#UbuntuDocker_237

**Comment by hang245141253** [comment]
@yeyupiaoling 我用的是Ubuntu18.04 不是16.04也可以吗？

我在安装NVIDIA-docker的时候报告依赖错误，缺乏一些包，但是貌似18.04没有哪些包，Docker安装不上

我想试一下pip安装包，折腾这个实在是疯掉了，想赶紧进入paddle的学习。

我的邮箱是245141253@qq.com 拜托您了

**Comment by yeyupiaoling** [comment]
@hang245141253 发给你了
