### ISSUE TITLE
在使用docker容器PaddlePaddle环境执行训练时报错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15183]
# 环境
 - Ubuntu 16.04
 - Docker ：`hub.baidubce.com/paddlepaddle/paddle:1.2.0-gpu-cuda8.0-cudnn5`
 - 显卡：RTX2070 8G

报错信息如下：
```
W0107 06:40:34.550292  1086 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 75, Driver Version: 10.0, Runtime Version: 8.0
W0107 06:40:34.550344  1086 device_context.cc:210] device: 0, cuDNN Version: 5.1.
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    exe.run(fluid.default_startup_program())
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
RuntimeError: function_attributes(): after cudaFuncGetAttributes: invalid device function
```

**Comment by chengduoZH** [comment]
这是因为Paddle在编译的时候没有添加`CUDA Capability: 75`，已经提PR进行修复。

**Comment by yeyupiaoling** [comment]
@chengduoZH 好的，如果有时间，我希望能够尽快能够支持CUDA 10
