### ISSUE TITLE
Ngraph compile error in debug mode

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#15230]
In nighly debug job, there is ngraph compiler error.
http://ci.paddlepaddle.org/viewLog.html?buildId=46821&tab=buildLog&buildTypeId=Paddle_CiDebug&logTab=tree&filter=all&_focus=18816
```
[16:00:27][Step 1/1] Traceback (most recent call last):
[16:00:27][Step 1/1]   File "setup.py", line 207, in <module>
[16:00:27][Step 1/1]     shutil.copy('/paddle/build/third_party/install/ngraph/lib/libtbb.so.2', libs_path)
[16:00:27][Step 1/1]   File "/usr/lib/python2.7/shutil.py", line 119, in copy
[16:00:27][Step 1/1]     copyfile(src, dst)
[16:00:27][Step 1/1]   File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
[16:00:27][Step 1/1]     with open(src, 'rb') as fsrc:
[16:00:27][Step 1/1] IOError: [Errno 2] No such file or directory: '/paddle/build/third_party/install/ngraph/lib/libtbb.so.2'
[16:00:27][Step 1/1] python/CMakeFiles/paddle_python.dir/build.make:565: recipe for target 'python/build/.timestamp' failed
[16:00:27][Step 1/1] CMakeFiles/Makefile2:86866: recipe for target 'python/CMakeFiles/paddle_python.dir/all' failed
[16:00:27][Step 1/1] make[2]: *** [python/build/.timestamp] Error 1
[16:00:27][Step 1/1] make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
[16:00:27][Step 1/1] make[1]: *** Waiting for unfinished jobs....
```

**Comment by baojun-nervana** [comment]
@luotao1 How can I run debug mode to reproduce this issue?

**Comment by luotao1** [comment]
`cmake .. -DCMAKE_BUILD_TYPE=Debug`
