### ISSUE TITLE
在训练时报错Assertion `label[i] >= 0 && label[i] < D || label[i] == ignore_index` failed.

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15260]
# 环境
 - PaddlePaddle 自己编译的，应该比较1.2.0高一些
 - Python 3.5
 - Ubuntu 16.04

# 问题
在训练的时候报以下错误：
```
/home/test/Downloads/Paddle/paddle/fluid/operators/math/cross_entropy.cu:40 Assertion `label[i] >= 0 && label[i] < D || label[i] == ignore_index` failed.
/home/test/Downloads/Paddle/paddle/fluid/operators/math/cross_entropy.cu:40 Assertion `label[i] >= 0 && label[i] < D || label[i] == ignore_index` failed.
/home/test/Downloads/Paddle/paddle/fluid/operators/math/cross_entropy.cu:40 Assertion `label[i] >= 0 && label[i] < D || label[i] == ignore_index` failed.
/home/test/Downloads/Paddle/paddle/fluid/operators/math/cross_entropy.cu:40 Assertion `label[i] >= 0 && label[i] < D || label[i] == ignore_index` failed.
Traceback (most recent call last):
  File "train.py", line 79, in <module>
    fetch_list=[avg_cost, accuracy, param_name])
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: CUDNN_STATUS_EXECUTION_FAILED at [/home/test/Downloads/Paddle/paddle/fluid/operators/batch_norm_op.cu.cc:289]
PaddlePaddle Call Stacks: 
0       0x7f1ee6150a27p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7f1ee651a823p paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 4499
2       0x7f1ee651b0afp std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormGradKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 47
3       0x7f1ee7b4c6e2p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 658
4       0x7f1ee7b465a0p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 544
5       0x7f1ee6247778p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 248
6       0x7f1ee624944ap paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 154
7       0x7f1ee612e56ap
8       0x7f1ee617f16dp
9             0x4ea137p PyCFunction_Call + 119
10            0x53c176p PyEval_EvalFrameEx + 23030
11            0x53fc97p
12            0x53b83fp PyEval_EvalFrameEx + 20671
13            0x53fc97p
14            0x5409bfp PyEval_EvalCode + 31
15            0x60cb42p
16            0x60efeap PyRun_FileExFlags + 154
17            0x60f7dcp PyRun_SimpleFileExFlags + 444
18            0x640256p Py_Main + 1110
19            0x4d0001p main + 225
20      0x7f1f33c1f830p __libc_start_main + 240
21            0x5d6999p _start + 41

```

**Comment by yeyupiaoling** [comment]
问题解决：
原因是我使用官方的预训练模型进行初步训练时，设置的label为8，但是之后更新了数据集，类别的数量以及是9了，所以再使用以前的预训练模型进行初始化模型，并训练的时候，就会报这个错误。

**Comment by frankwhzhang** [comment]
问题已经解决，关闭这个issue
