### ISSUE TITLE
faster_rcnn运行失败ValueError: Shape not match. What is defined in data layer is (-1L, 3L, 1333L, 1333L), but receive (1, 3, 800, 1205)

### ISSUE THREAD

**Issue by zhengya01** [PaddlePaddle/Paddle#15317]
- 标题：faster_rcnn训练过程失败
ValueError: Shape not match. What is defined in data layer is (-1L, 3L, 1333L, 1333L), but receive (1, 3, 800, 1205)

- 版本、环境信息：
    1）PaddlePaddle版本：a92860a3b1dce1ddd25885e06514dfe02839aabc
    3）GPU：GPU型号V100、CUDA9、CUDNN7
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本

- 训练信息
    1）单机，单卡/多卡

- 复现信息：
FLAGS_benchmark=true  python train.py --model_save_dir=output/ --data_dir=dataset/coco/ --max_iter=10 --enable_ce --pretrained_model=./imagenet_resnet50_fusebn

- 问题描述：
```
W0114 15:51:07.217496 116714 device_context.cc:262] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.0, Runtime API Version: 9.0
W0114 15:51:07.217563 116714 device_context.cc:270] device: 0, cuDNN Version: 7.0.
W0114 15:51:07.217572 116714 device_context.cc:294] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.1, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/paddle/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/paddle/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/paddle/anaconda2/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 563, in __provider_thread__
    for tensors in func():
  File "/home/paddle/anaconda2/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 610, in __tensor_provider__
    for slots in paddle_reader():
  File "/home/paddle/anaconda2/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 287, in __reader_creator__
    yield self.feed(item)
  File "/home/paddle/anaconda2/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 206, in feed
    ret_dict[each_name] = each_converter.done()
  File "/home/paddle/anaconda2/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 92, in done
    self._check_shape(arr.shape)
  File "/home/paddle/anaconda2/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 79, in _check_shape
    format(self.shape, shape))
ValueError: Shape not match. What is defined in data layer is (-1L, 3L, 1333L, 1333L), but receive (1, 3, 800, 1205)
```

**Comment by Xreki** [comment]
就如error信息所示，faster-rcnn要求输入数据的shape为`(-1L, 3L, 1333L, 1333L)`，如果batch_size是1，那就是`(1, 3, 1333, 1333)`，你给的输入数据的shape是`(1, 3, 800, 1205)`

**Comment by zhengya01** [comment]
3e8408429d4b7fbb402ef33d776f8c343e565bdf 这个版本就不会报错

**Comment by Xreki** [comment]
faster-rcnn这个模式应该是支持变长数据的。你用的是`develop`版本吗？

**Comment by Xreki** [comment]
似乎是这个修改 https://github.com/PaddlePaddle/Paddle/commit/d752177b8f1fafe3588fe7f77a4960813f1bab4f#diff-eb827f0da22617956805e833749e250f 引起的，@sneaxiy
