### ISSUE TITLE
minimize时出现问题

### ISSUE THREAD

**Issue by sonofaeolus** [PaddlePaddle/Paddle#15321]
```
Traceback (most recent call last): 
File "policy_gan.py", line 74, in <module> train()
File "policy_gan.py", line 52, in train opt.minimize(loss = dg_loss, parameter_list = g_params)
File "/home/work/wangxiaoyu/fpython/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 259, in minimize [error_clip_callback])
File "/home/work/wangxiaoyu/fpython/lib/python2.7/site-packages/paddle/fluid/backward.py", line 590, in append_backward _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
File "/home/work/wangxiaoyu/fpython/lib/python2.7/site-packages/paddle/fluid/backward.py", line 426, in _append_backward_vars_ op_desc.infer_shape(block.desc) 
paddle.fluid.core.EnforceNotMet: Input(X) of LoDTensorToArrayOp should not be null. at [/paddle/paddle/fluid/operators/lod_tensor_to_array_op.cc:183] 
```

**Comment by sonofaeolus** [comment]
error log
```
Traceback (most recent call last):
  File "policy_gan.py", line 74, in <module>
    train()
  File "policy_gan.py", line 52, in train
    opt.minimize(loss = dg_loss, parameter_list = g_params)
  File "/home/work/wangxiaoyu/fpython/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 259, in minimize
    [error_clip_callback])
  File "/home/work/wangxiaoyu/fpython/lib/python2.7/site-packages/paddle/fluid/backward.py", line 590, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/home/work/wangxiaoyu/fpython/lib/python2.7/site-packages/paddle/fluid/backward.py", line 426, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core.EnforceNotMet: Input(X) of LoDTensorToArrayOp should not be null. at [/paddle/paddle/fluid/operators/lod_tensor_to_array_op.cc:183]
PaddlePaddle Call Stacks:
0       0x7fb5e4bd9d06p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fb5e5de083ep paddle::operators::LoDTensorToArrayInferShape::operator()(paddle::framework::InferShapeContext*) const + 510
2       0x7fb5e5de0b63p std::_Function_handler<void (paddle::framework::InferShapeContext*), paddle::framework::details::OpInfoFiller<paddle::operators::LoDTensorToArrayInferShape, (paddle::framework::details::OpInfoFillType)4>::operator()(char const*, paddle::framework::OpInfo*) const::{lambda(paddle::framework::InferShapeContext*)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::InferShapeContext*) + 35
3       0x7fb5e4c8fe56p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 886
```

**Comment by Xreki** [comment]
错误信息为：
```
Input(X) of LoDTensorToArrayOp should not be null. at [/paddle/paddle/fluid/operators/lod_tensor_to_array_op.cc:183]
```
这个错误跟`fluid.layers.tensor_array_to_tensor`的配置有关，它的输入`X`应该是一个`tensor_array`，可以贴一下相关配置吗？

**Comment by sonofaeolus** [comment]
找的问题了 是因为argmax不可导导致的
