### ISSUE TITLE
前向计算可以得到值 但是反向传播报错 paddle.fluid.core.EnforceNotMet: holder_ should not be null

### ISSUE THREAD

**Issue by sonofaeolus** [PaddlePaddle/Paddle#15330]

**Comment by sonofaeolus** [comment]
error log
        data: 4.17265,
Traceback (most recent call last):
  File "policy_gan.py", line 97, in <module>
    train()
  File "policy_gan.py", line 94, in train
    dg_loss = exe.run(dg_program, df_dg.feed(data), fetch_list = [dg_loss])
  File "/home/work/wangxiaoyu/fpython/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/paddle/paddle/fluid/framework/tensor.cc:22]
PaddlePaddle Call Stacks: 
0       0x7f645691ed06p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f6457f25314p paddle::framework::Tensor::check_memory_size() const + 228
2       0x7f6457f256bfp paddle::framework::Tensor::ShareDataWith(paddle::framework::Tensor const&) + 31
3       0x7f645707d02dp paddle::operators::LoDResetGradKernel<paddle::platform::CPUPlace, long>::Compute(paddle::framework::ExecutionContext const&) const + 253
4       0x7f645707d0c3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 3ul, paddle::operators::LoDResetGradKernel<paddle::platform::CPUPlace, float>, paddle::operators::LoDResetGradKernel<paddle::platform::CPUPlace, double>, paddle::operators::LoDResetGradKernel<paddle::platform::CPUPlace, int>, paddle::operators::LoDResetGradKernel<paddle::platform::CPUPlace, long> >::operator()(char const*, char const*) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7f6457ea8bbcp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 492
6       0x7f6457ea53ffp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 463
7       0x7f64569ec9cbp paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 219
8       0x7f64569ed620p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 128
9       0x7f6456901fedp
10      0x7f6456935414p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
11            0x4b8a47p PyEval_EvalFrameEx + 30279
12            0x4ba968p PyEval_EvalCodeEx + 2040
13            0x4b81c8p PyEval_EvalFrameEx + 28104
14            0x4b86edp PyEval_EvalFrameEx + 29421
15            0x4ba968p PyEval_EvalCodeEx + 2040
16            0x4baa92p PyEval_EvalCode + 50
17            0x4e897dp PyRun_FileExFlags + 285
18            0x4ea201p PyRun_SimpleFileExFlags + 209
19            0x415afdp Py_Main + 2925
20        0x318ae1ecddp __libc_start_main + 253
21            0x414cd1p

**Comment by sonofaeolus** [comment]
相关代码
 clf_prob = cnn_net(words_id, dict_size, emb_size, conv_dim, filter_size, hidden_size)
 print clf_prob.shape
 ce = fluid.layers.cross_entropy(input = words_prob, label = ctr_label)
 seq_ce = fluid.layers.sequence_pool(input = ce, pool_type = "average")
 one_value = fluid.layers.fill_constant_batch_size_like(input = src_word_id, dtype = "float32", shape = [-1, 1], value = 1.0)
 dg_loss = fluid.layers.reduce_mean(fluid.layers.elementwise_mul(x = fluid.layers.elementwise_sub(x = one_value, y = clf_prob), y = seq_ce))
opt.minimize(loss = dg_loss, parameter_list = g_params)

**Comment by sonofaeolus** [comment]
由于反向传播部分值不可导 导致该问题
