### ISSUE TITLE
neural_machine_translation/rnn_search/no_attention_model.py 进行分布式训练时出现如下错误

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#15670]
Traceback (most recent call last):
  File "dist_rnn_search.py", line 141, in <module>
    runtime_main(TestDistRnnSearch)
  File "/home/paddle/weike/cts_test/dist_base.py", line 315, in runtime_main
    model.run_pserver(endpoints, trainers, current_endpoint, trainer_id, run_params)
  File "/home/paddle/weike/cts_test/dist_base.py", line 67, in run_pserver
    run_params)
  File "/home/paddle/weike/cts_test/dist_base.py", line 49, in get_transpiler
    sync_mode=sync_mode)
  File "/root/.jumbo/lib/python2.7/site-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 361, in transpile
    self._init_splited_vars()
  File "/root/.jumbo/lib/python2.7/site-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 1178, in _init_splited_vars
    splited_var)
  File "/root/.jumbo/lib/python2.7/site-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 1023, in _get_slice_var_info
    orig_dim1_flatten = reduce(lambda x, y: x * y, slice_vars[0].shape[1:])
TypeError: reduce() of empty sequence with no initial value

**Comment by typhoonzero** [comment]
@seiriosPlus maybe this is introduced by: https://github.com/PaddlePaddle/Paddle/commit/8b50ad80ff6934512d3959947ac1e71ea3fb9ea3#diff-3a23ecb6a98b666c84525f3f6fcd2bb6R1268
