### ISSUE TITLE
当使用with块时无法保存预测模型

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#15835]
我训练一个对抗生成网络，我想保存预测模型，以便预之后直接使用这个预测模型生成更多的图片，但是我在保存模型的时候就会报错，错误如下所示。

不知道是不是使用with的原因，还是对抗网络模型本身就不允许保存模型。麻烦路过的同学解答下，谢谢。

错误信息：
```
Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/LearnPaddle2/note13/train.py", line 210, in <module>
    fluid.io.save_inference_model(save_path, feeded_var_names=[z.name], target_vars=[fake], executor=exe)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/io.py", line 681, in save_inference_model
    main_program = main_program._prune(targets=target_vars)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 1741, in _prune
    "The target variable must have an "
ValueError: The target variable must have an associated operator that generates it.
```

全部代码：
```python
import os
import shutil

import numpy as np
import paddle
import paddle.fluid as fluid

image_size = 32

# 定义生成器
def Generator(y, name="G"):
    def deconv(x, num_filters, filter_size=5, stride=2, dilation=1, padding=2, output_size=None, act=None):
        return fluid.layers.conv2d_transpose(input=x,
                                             num_filters=num_filters,
                                             output_size=output_size,
                                             filter_size=filter_size,
                                             stride=stride,
                                             dilation=dilation,
                                             padding=padding,
                                             act=act)

    with fluid.unique_name.guard(name + "/"):
        # 第一组全连接和BN层
        y = fluid.layers.fc(y, size=2048)
        y = fluid.layers.batch_norm(y)
        # 第二组全连接和BN层
        y = fluid.layers.fc(y, size=128 * 8 * 8)
        y = fluid.layers.batch_norm(y)
        # 进行形状变换
        y = fluid.layers.reshape(y, shape=(-1, 128, 8, 8))
        # 第一组转置卷积运算
        y = deconv(x=y, num_filters=128, act='relu', output_size=[16, 16])
        # 第二组转置卷积运算
        y = deconv(x=y, num_filters=3, act='sigmoid', output_size=[image_size, image_size])
    return y


# 判别器 Discriminator
def Discriminator(images, name="D"):
    # 定义一个卷积池化组
    def conv_pool(input, num_filters, act=None):
        return fluid.nets.simple_img_conv_pool(input=input,
                                               filter_size=3,
                                               num_filters=num_filters,
                                               pool_size=2,
                                               pool_stride=2,
                                               act=act)

    with fluid.unique_name.guard(name + "/"):
        y = fluid.layers.reshape(x=images, shape=[-1, 3, image_size, image_size])
        # 第一个卷积池化组
        y = conv_pool(input=y, num_filters=64, act='leaky_relu')
        # 第一个卷积池化加回归层
        y = conv_pool(input=y, num_filters=128)
        y = fluid.layers.batch_norm(input=y, act='leaky_relu')
        # 第二个卷积池化加回归层
        y = fluid.layers.fc(input=y, size=1024)
        y = fluid.layers.batch_norm(input=y, act='leaky_relu')
        # 最后一个分类器输出
        y = fluid.layers.fc(input=y, size=1, act='sigmoid')
    return y


# 创建判别器D识别生成器G生成的假图片程序
train_d_fake = fluid.Program()
# 创建判别器D识别真实图片程序
train_d_real = fluid.Program()
# 创建生成器G生成符合判别器D的程序
train_g = fluid.Program()

# 创建共同的一个初始化的程序
startup = fluid.Program()

# 噪声维度
z_dim = 100


# 从Program获取prefix开头的参数名字
def get_params(program, prefix):
    all_params = program.global_block().all_parameters()
    return [t.name for t in all_params if t.name.startswith(prefix)]


# 训练判别器D识别真实图片
with fluid.program_guard(train_d_real, startup):
    # 创建读取真实数据集图片的data，并且label为1
    real_image = fluid.layers.data('image', shape=[3, image_size, image_size])
    ones = fluid.layers.fill_constant_batch_size_like(real_image, shape=[-1, 1], dtype='float32', value=1)

    # 判别器D判断真实图片的概率
    p_real = Discriminator(real_image)
    # 获取损失函数
    real_cost = fluid.layers.sigmoid_cross_entropy_with_logits(p_real, ones)
    real_avg_cost = fluid.layers.mean(real_cost)

    # 获取判别器D的参数
    d_params = get_params(train_d_real, "D")

    # 创建优化方法
    optimizer = fluid.optimizer.Adam(learning_rate=2e-4)
    optimizer.minimize(real_avg_cost, parameter_list=d_params)

# 训练判别器D识别生成器G生成的图片为假图片
with fluid.program_guard(train_d_fake, startup):
    # 利用创建假的图片data，并且label为0
    z = fluid.layers.data(name='z', shape=[z_dim])
    zeros = fluid.layers.fill_constant_batch_size_like(z, shape=[-1, 1], dtype='float32', value=0)

    # 判别器D判断假图片的概率
    p_fake = Discriminator(Generator(z))

    # 获取损失函数
    fake_cost = fluid.layers.sigmoid_cross_entropy_with_logits(p_fake, zeros)
    fake_avg_cost = fluid.layers.mean(fake_cost)

    # 获取判别器D的参数
    d_params = get_params(train_d_fake, "D")

    # 创建优化方法
    optimizer = fluid.optimizer.Adam(learning_rate=2e-4)
    optimizer.minimize(fake_avg_cost, parameter_list=d_params)

# 训练生成器G生成符合判别器D标准的假图片
with fluid.program_guard(train_g, startup):
    # 噪声生成图片为真实图片的概率，Label为1
    z = fluid.layers.data(name='z', shape=[z_dim])
    ones = fluid.layers.fill_constant_batch_size_like(z, shape=[-1, 1], dtype='float32', value=1)

    # 生成图片
    fake = Generator(z)
    # 克隆预测程序
    infer_program = train_g.clone(for_test=True)

    # 生成符合判别器的假图片
    p = Discriminator(fake)

    # 获取损失函数
    g_cost = fluid.layers.sigmoid_cross_entropy_with_logits(p, ones)
    g_avg_cost = fluid.layers.mean(g_cost)

    # 获取G的参数
    g_params = get_params(train_g, "G")

    # 只训练G
    optimizer = fluid.optimizer.Adam(learning_rate=2e-4)
    optimizer.minimize(g_avg_cost, parameter_list=g_params)


# 噪声生成
def z_reader():
    while True:
        yield np.random.uniform(-1.0, 1.0, (z_dim)).astype('float32')


# 读取cifar数据集，不使用label
def cifar_reader(reader):
    def r():
        for img, label in reader():
            yield img.reshape(3, 32, 32)

    return r


# 生成真实图片reader
mydata_generator = paddle.batch(reader=cifar_reader(paddle.dataset.cifar.train10()), batch_size=128)
# 生成假图片的reader
z_generator = paddle.batch(z_reader, batch_size=128)()

# 创建执行器，最好使用GPU，CPU速度太慢了
# place = fluid.CPUPlace()
place = fluid.CUDAPlace(0)
exe = fluid.Executor(place)
# 初始化参数
exe.run(startup)

# 测试噪声
test_z = np.array(next(z_generator))

# 开始训练
for pass_id in range(100):
    for i, real_image in enumerate(mydata_generator()):
        # 训练判别器D识别真实图片
        r_fake = exe.run(program=train_d_fake,
                         fetch_list=[fake_avg_cost],
                         feed={'z': test_z})

        # 训练判别器D识别生成器G生成的假图片
        r_real = exe.run(program=train_d_real,
                         fetch_list=[real_avg_cost],
                         feed={'image': np.array(real_image)})

        # 训练生成器G生成符合判别器D标准的假图片
        r_g = exe.run(program=train_g,
                      fetch_list=[g_avg_cost],
                      feed={'z': test_z})

        if i % 100 == 0:
            print("Pass：%d, Batch：%d, 训练判别器D识别真实图片Cost：%0.5f, "
                  "训练判别器D识别生成器G生成的假图片Cost：%0.5f, "
                  "训练生成器G生成符合判别器D标准的假图片Cost：%0.5f" % (pass_id, i, r_fake[0], r_real[0], r_g[0]))


    # 保存预测模型
    save_path = 'infer_model/'
    # 删除旧的模型文件
    shutil.rmtree(save_path, ignore_errors=True)
    # 创建保持模型文件目录
    os.makedirs(save_path)
    # 保存预测模型
    fluid.io.save_inference_model(save_path, feeded_var_names=[z.name], target_vars=[fake], executor=exe)
```

**Comment by wanghaoshuang** [comment]
```
  with fluid.program_guard(train_g, startup):
    z = fluid.layers.data(name='z', shape=[z_dim])
    ones = fluid.layers.fill_constant_batch_size_like(z, shape=[-1, 1], dtype='float32', value=1)
    fake = Generator(z)
```
```
fluid.io.save_inference_model(save_path, feeded_var_names=[z.name], target_vars=[fake], executor=exe)
```

因为`fake`是定义在with block里边的，所以在with block之外的`save_inference_model`不认识`fake`，一个解决办法是：
在with block之前定义fake = None.

还有一个问题：
你在调用save_inference_model时，要指定下main_program=train_g, 改参数的意思可以参考[这里](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/io.py#L881)

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 好的，非常感谢，我先试试看。

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 您好，经过上面的修改以及可正常保存预测模型了，但是我觉得保存的模型不完全正确。

在生成器中，最后一层转置卷积运算运算中，我使用sigmoid激活函数，是为了输出的数据都是在[0, 1]区间内，因为在保存彩色图片时，提示数据需要在[0.0, 1.0]或者[0, 255]。

在训练中输出是[0, 1]区间内，但是在使用预测模型进行生成的数据不是这个区间的，按理来说，输出的数应该跟训练中输出的格式一样才对的，是不是有什么其他问题呢？

预测代码：
```python
import os
import shutil

import numpy as np
import paddle
import paddle.fluid as fluid
import matplotlib.pyplot as plt
import image_reader

image_size = 32

# 定义生成器
def Generator(y, name="G"):
    def deconv(x, num_filters, filter_size=5, stride=2, dilation=1, padding=2, output_size=None, act=None):
        return fluid.layers.conv2d_transpose(input=x,
                                             num_filters=num_filters,
                                             output_size=output_size,
                                             filter_size=filter_size,
                                             stride=stride,
                                             dilation=dilation,
                                             padding=padding,
                                             act=act)

    with fluid.unique_name.guard(name + "/"):
        # 第一组全连接和BN层
        y = fluid.layers.fc(y, size=2048)
        y = fluid.layers.batch_norm(y)
        # 第二组全连接和BN层
        y = fluid.layers.fc(y, size=128 * 8 * 8)
        y = fluid.layers.batch_norm(y)
        # 进行形状变换
        y = fluid.layers.reshape(y, shape=(-1, 128, 8, 8))
        # 第一组转置卷积运算
        y = deconv(x=y, num_filters=128, act='relu', output_size=[16, 16])
        # 第二组转置卷积运算
        y = deconv(x=y, num_filters=3, act='sigmoid', output_size=[image_size, image_size])
    return y


# 判别器 Discriminator
def Discriminator(images, name="D"):
    # 定义一个卷积池化组
    def conv_pool(input, num_filters, act=None):
        return fluid.nets.simple_img_conv_pool(input=input,
                                               filter_size=3,
                                               num_filters=num_filters,
                                               pool_size=2,
                                               pool_stride=2,
                                               act=act)

    with fluid.unique_name.guard(name + "/"):
        y = fluid.layers.reshape(x=images, shape=[-1, 3, image_size, image_size])
        # 第一个卷积池化组
        y = conv_pool(input=y, num_filters=64, act='leaky_relu')
        # 第一个卷积池化加回归层
        y = conv_pool(input=y, num_filters=128)
        y = fluid.layers.batch_norm(input=y, act='leaky_relu')
        # 第二个卷积池化加回归层
        y = fluid.layers.fc(input=y, size=1024)
        y = fluid.layers.batch_norm(input=y, act='leaky_relu')
        # 最后一个分类器输出
        y = fluid.layers.fc(input=y, size=1, act='sigmoid')
    return y


# 创建判别器D识别生成器G生成的假图片程序
train_d_fake = fluid.Program()
# 创建判别器D识别真实图片程序
train_d_real = fluid.Program()
# 创建生成器G生成符合判别器D的程序
train_g = fluid.Program()

# 创建共同的一个初始化的程序
startup = fluid.Program()

# 噪声维度
z_dim = 100


# 从Program获取prefix开头的参数名字
def get_params(program, prefix):
    all_params = program.global_block().all_parameters()
    return [t.name for t in all_params if t.name.startswith(prefix)]


# 训练判别器D识别真实图片
with fluid.program_guard(train_d_real, startup):
    # 创建读取真实数据集图片的data，并且label为1
    real_image = fluid.layers.data('image', shape=[3, image_size, image_size])
    ones = fluid.layers.fill_constant_batch_size_like(real_image, shape=[-1, 1], dtype='float32', value=1)

    # 判别器D判断真实图片的概率
    p_real = Discriminator(real_image)
    # 获取损失函数
    real_cost = fluid.layers.sigmoid_cross_entropy_with_logits(p_real, ones)
    real_avg_cost = fluid.layers.mean(real_cost)

    # 获取判别器D的参数
    d_params = get_params(train_d_real, "D")

    # 创建优化方法
    optimizer = fluid.optimizer.Adam(learning_rate=2e-4)
    optimizer.minimize(real_avg_cost, parameter_list=d_params)

# 训练判别器D识别生成器G生成的图片为假图片
with fluid.program_guard(train_d_fake, startup):
    # 利用创建假的图片data，并且label为0
    z = fluid.layers.data(name='z', shape=[z_dim])
    zeros = fluid.layers.fill_constant_batch_size_like(z, shape=[-1, 1], dtype='float32', value=0)

    # 判别器D判断假图片的概率
    p_fake = Discriminator(Generator(z))

    # 获取损失函数
    fake_cost = fluid.layers.sigmoid_cross_entropy_with_logits(p_fake, zeros)
    fake_avg_cost = fluid.layers.mean(fake_cost)

    # 获取判别器D的参数
    d_params = get_params(train_d_fake, "D")

    # 创建优化方法
    optimizer = fluid.optimizer.Adam(learning_rate=2e-4)
    optimizer.minimize(fake_avg_cost, parameter_list=d_params)

# 训练生成器G生成符合判别器D标准的假图片
fake = None
with fluid.program_guard(train_g, startup):
    # 噪声生成图片为真实图片的概率，Label为1
    z = fluid.layers.data(name='z', shape=[z_dim])
    ones = fluid.layers.fill_constant_batch_size_like(z, shape=[-1, 1], dtype='float32', value=1)

    # 生成图片
    fake = Generator(z)
    # 克隆预测程序
    infer_program = train_g.clone(for_test=True)

    # 生成符合判别器的假图片
    p = Discriminator(fake)

    # 获取损失函数
    g_cost = fluid.layers.sigmoid_cross_entropy_with_logits(p, ones)
    g_avg_cost = fluid.layers.mean(g_cost)

    # 获取G的参数
    g_params = get_params(train_g, "G")

    # 只训练G
    optimizer = fluid.optimizer.Adam(learning_rate=2e-4)
    optimizer.minimize(g_avg_cost, parameter_list=g_params)


# 噪声生成
def z_reader():
    while True:
        yield np.random.uniform(-1.0, 1.0, (z_dim)).astype('float32')


# 读取cifar数据集，不使用label
def cifar_reader(reader):
    def r():
        for img, label in reader():
            yield img.reshape(3, 32, 32)

    return r


# 保存图片
def show_image_grid(images):
    for i, image in enumerate(images[:64]):
        image = image.transpose((2, 1, 0))
        if not os.path.exists('train_image/'):
            os.makedirs('train_image/')
        plt.imsave("train_image/test_%d.png" % i, image)


# 生成真实图片reader
mydata_generator = paddle.batch(reader=cifar_reader(paddle.dataset.cifar.train10()), batch_size=128)
# 生成假图片的reader
z_generator = paddle.batch(z_reader, batch_size=128)()

# 创建执行器，最好使用GPU，CPU速度太慢了
# place = fluid.CPUPlace()
place = fluid.CUDAPlace(0)
exe = fluid.Executor(place)
# 初始化参数
exe.run(startup)

# 测试噪声
test_z = np.array(next(z_generator))

# 开始训练
for pass_id in range(100):
    for i, real_image in enumerate(mydata_generator()):
        # 训练判别器D识别真实图片
        r_fake = exe.run(program=train_d_fake,
                         fetch_list=[fake_avg_cost],
                         feed={'z': test_z})

        # 训练判别器D识别生成器G生成的假图片
        r_real = exe.run(program=train_d_real,
                         fetch_list=[real_avg_cost],
                         feed={'image': np.array(real_image)})

        # 训练生成器G生成符合判别器D标准的假图片
        r_g = exe.run(program=train_g,
                      fetch_list=[g_avg_cost],
                      feed={'z': test_z})

        if i % 100 == 0:
            print("Pass：%d, Batch：%d, 训练判别器D识别真实图片Cost：%0.5f, "
                  "训练判别器D识别生成器G生成的假图片Cost：%0.5f, "
                  "训练生成器G生成符合判别器D标准的假图片Cost：%0.5f" % (pass_id, i, r_fake[0], r_real[0], r_g[0]))

    # 测试生成的图片
    r_i = exe.run(program=infer_program,
                  fetch_list=[fake],
                  feed={'z': test_z})

    r_i = np.array(r_i).astype(np.float32)
    # 显示生成的图片
    show_image_grid(r_i[0])

    # 保存预测模型
    save_path = 'infer_model/'
    # 删除旧的模型文件
    shutil.rmtree(save_path, ignore_errors=True)
    # 创建保持模型文件目录
    os.makedirs(save_path)
    # 保存预测模型
    fluid.io.save_inference_model(save_path, feeded_var_names=[z.name], target_vars=[fake], executor=exe, main_program=train_g)
```


预测代码：
```python
import os

import paddle

import matplotlib.pyplot as plt
import numpy as np
import paddle.fluid as fluid

# 创建执行器
place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())

# 保存预测模型路径
save_path = 'infer_model/'
# 从模型中获取预测程序、输入数据名称列表、分类器
[infer_program, feeded_var_names, target_var] = fluid.io.load_inference_model(dirname=save_path, executor=exe)

# 噪声维度
z_dim = 100


# 噪声生成
def z_reader():
    while True:
        yield np.random.uniform(-1.0, 1.0, (z_dim)).astype('float32')


# 保存图片
def save_image(images):
    for i, image in enumerate(images[:64]):
        image = image.transpose((2, 1, 0))
        if not os.path.exists('infer_image/'):
            os.makedirs('infer_image/')
        plt.imsave("infer_image/test_%d.png" % i, image)


z_generator = paddle.batch(z_reader, batch_size=128)()
test_z = np.array(next(z_generator))

# 执行预测
result = exe.run(program=infer_program,
                 feed={feeded_var_names[0]: test_z},
                 fetch_list=target_var)


# 测试生成的图片
r_i = exe.run(program=infer_program,
              feed={feeded_var_names[0]: test_z},
              fetch_list=target_var)

r_i = np.array(r_i).astype(np.float32)

# 显示生成的图片
save_image(r_i[0])
```

**Comment by wanghaoshuang** [comment]
>save_image(r_i[0])

麻烦你print下r_i[0]，然后把数据贴出来看看？

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 

训练时的`r_i[0]`:
```
(32, 3, 32, 32)
[[[[9.88795638e-01 5.50048411e-01 9.99464333e-01 ... 1.23688482e-01
    9.95592892e-01 5.20641148e-01]
   [1.47403115e-02 2.10948102e-02 1.27115403e-03 ... 1.05750002e-01
    2.01849025e-02 7.55249381e-01]
   [9.99413013e-01 7.10094273e-02 9.99992847e-01 ... 1.00703293e-03
    9.99862194e-01 4.93900120e-01]
   ...
   [2.15410814e-01 4.19171005e-01 1.87825978e-01 ... 2.88430870e-01
    1.07954279e-01 3.54531258e-01]
   [9.07878458e-01 7.46864557e-01 9.78789508e-01 ... 4.05638337e-01
    7.30011046e-01 5.88595867e-01]
   [3.41619670e-01 3.80550206e-01 2.25628972e-01 ... 3.79594237e-01
    3.22078139e-01 4.22768295e-01]]

  [[2.33749598e-02 9.96901691e-01 2.58537203e-01 ... 9.96139228e-01
    6.25073463e-02 7.60597527e-01]
   [5.48727334e-01 1.00634582e-01 6.14606500e-01 ... 8.85804519e-02
    1.55271575e-01 1.13714777e-01]
   [2.08097041e-01 9.98359859e-01 2.76380442e-02 ... 9.98712063e-01
    1.45556703e-01 9.02745366e-01]
   ...
   [2.57315874e-01 1.44513622e-01 4.48696017e-01 ... 1.45416006e-01
    2.89715439e-01 2.64266372e-01]
   [7.01880306e-02 9.08656418e-01 1.65450603e-01 ... 8.61361027e-01
    1.95848867e-01 6.62895739e-01]
   [4.76166815e-01 3.57955545e-01 5.55473983e-01 ... 3.68712842e-01
    4.67289656e-01 3.88945550e-01]]

  [[8.57750654e-01 9.85501766e-01 9.80074406e-01 ... 9.81732190e-01
    9.31989610e-01 6.68305635e-01]
   [8.18017781e-01 6.03527904e-01 7.36026764e-01 ... 4.75189954e-01
    2.95609415e-01 5.71364127e-02]
   [9.26403224e-01 9.99925733e-01 9.96973038e-01 ... 9.99938369e-01
    9.87483323e-01 7.44319320e-01]
   ...
   [4.28183675e-01 1.05636671e-01 4.73502874e-01 ... 2.45029315e-01
    3.60348225e-01 3.15638959e-01]
   [8.72602403e-01 6.13869071e-01 9.07568276e-01 ... 6.65485859e-01
    6.63430512e-01 5.89182973e-01]
   [4.83192325e-01 3.11368257e-01 6.53420269e-01 ... 3.57544333e-01
    4.77686137e-01 4.13510531e-01]]]


 [[[9.98608828e-01 9.72433686e-01 9.99947071e-01 ... 5.79816341e-01
    9.75584507e-01 1.86312556e-01]
   [1.16441562e-03 1.86899025e-03 5.73725458e-07 ... 7.47231916e-02
    1.15964515e-02 4.36537206e-01]
   [9.99979734e-01 9.93477464e-01 1.00000000e+00 ... 6.96190119e-01
    9.94727254e-01 7.60223493e-02]
   ...
```

使用预测模型预测时的`r_i[0]`:
```
(32, 3, 32, 32)
[[[[ 4.02750635e+00 -4.17260021e-01  7.31279945e+00 ...  9.00042951e-01
     1.31304288e+00 -1.69461131e-01]
   [-6.58095694e+00 -7.97698116e+00 -1.41761389e+01 ... -1.37995780e+00
    -2.16387129e+00 -5.61953008e-01]
   [ 6.43280220e+00 -1.92689312e+00  1.00946989e+01 ...  1.98791301e+00
     2.04971218e+00  3.02664284e-02]
   ...
   [-1.73007941e+00 -1.25821161e+00 -2.48909354e+00 ... -6.57973826e-01
    -1.67073405e+00 -2.11830124e-01]
   [ 1.11862409e+00 -1.15285885e+00  2.12501144e+00 ... -1.08158238e-01
     1.25318694e+00  2.97029257e-01]
   [-1.02419126e+00 -1.02564096e+00 -1.49956942e+00 ... -4.51788515e-01
    -5.02016723e-01 -1.96133822e-01]]

  [[-8.02820683e+00  5.42674732e+00 -8.72735691e+00 ...  1.19578326e+00
    -8.71994436e-01  3.65514398e-01]
   [-4.80619097e+00 -7.45476723e+00 -7.09920788e+00 ... -2.41086197e+00
    -1.08644497e+00 -7.49604344e-01]
   [-1.00966558e+01  8.43736076e+00 -1.63446827e+01 ...  2.52849126e+00
    -2.49947596e+00  4.81721729e-01]
   ...
   [-1.21024907e+00 -2.32434249e+00 -1.55953372e+00 ... -1.03449440e+00
    -4.68692213e-01 -6.11491561e-01]
   [-1.97201812e+00  1.69503009e+00 -1.26160014e+00 ...  1.51859379e+00
    -9.05804098e-01  2.82559663e-01]
   [-6.55251145e-01 -1.07032573e+00 -1.02541439e-01 ... -4.84709650e-01
    -1.78523168e-01 -2.86259979e-01]]

  [[ 3.40235877e+00  3.33432388e+00  4.54275560e+00 ...  1.09995866e+00
     3.49132299e-01  3.98787320e-01]
   [-4.34579563e+00 -7.24655485e+00 -5.49701262e+00 ... -2.41583204e+00
```

可以看到使用预测模型的时候就出现了负数，而训练的时候是没有的。

上面的代码是完整的，你执行的是也会发现这种情况。

**Comment by wanghaoshuang** [comment]
>可以看到使用预测模型的时候就出现了负数，而训练的时候是没有的。
上面的代码是完整的，你执行的是也会发现这种情况。

很奇怪的现象，我尝试复现一下，晚会儿再反馈给你吧，很抱歉。

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 好的。麻烦您 了。

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 您好，这问题可以解决吗？
