### ISSUE TITLE
the output tensor's 'dtype' of 'uniform_random' is not set

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#15853]
**Brief**
According to the API doc of 'uniform_random' (see http://paddlepaddle.org/documentation/docs/zh/1.2/api/layers.html#uniform-random), the default 'dtype' is:
> dtype (INT) – Output tensor data type. [default 5(FP32)].

But in fact, the dtype of returned tensor is not set to 5.
**System information**
-PaddlePaddle version: 1.2.1
-OS Platform and Distribution: Ubuntu 18.04
-Python version: Python 2.7.15rc1
**To Reproduce**
Just use the code provided in API doc:
```python
import paddle.fluid as fluid
result = fluid.layers.uniform_random(shape=[32, 784])
print result
```
**Describe your current behavior**
```
Traceback (most recent call last):
  File "uniform_random.py", line 3, in <module>
    print result
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 350, in __str__
    return self.to_string(True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 370, in to_string
    res_str = _debug_string_(proto, throw_on_error)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 201, in _debug_string_
    format(error_fields, proto))
ValueError: ['type.lod_tensor.tensor.data_type'] are not initialized.
```

**Comment by qingqing01** [comment]
I use your code to test, the output is:

```
name: "uniform_random_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP64
      dims: 32
      dims: 784
    }
  }
}
persistable: false
```

The def of `uniform_random`:

https://github.com/PaddlePaddle/Paddle/blob/afc885dace69d97531ebe1066af2636d1adbfeea/python/paddle/fluid/layers/ops.py#L63-L66

->

https://github.com/PaddlePaddle/Paddle/blob/afc885dace69d97531ebe1066af2636d1adbfeea/python/paddle/fluid/framework.py#L131-L146

Found that python 2.7 converts None to float64:

```python
Python 2.7.3 (default, Sep  7 2018, 13:59:46)
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> dtype = np.dtype(None)
>>> print dtype
float64
>>>
```

**Comment by houj04** [comment]
```
hj@ubuntu:~/my_paddle$ cat uniform_random.py 
import paddle.fluid as fluid
result = fluid.layers.uniform_random(shape=[32, 784])
print result
hj@ubuntu:~/my_paddle$ python -V
Python 2.7.15rc1
hj@ubuntu:~/my_paddle$ uname -a
Linux ubuntu 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
hj@ubuntu:~/my_paddle$ python uniform_random.py 
Traceback (most recent call last):
  File "uniform_random.py", line 3, in <module>
    print result
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 350, in __str__
    return self.to_string(True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 370, in to_string
    res_str = _debug_string_(proto, throw_on_error)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 201, in _debug_string_
    format(error_fields, proto))
ValueError: ['type.lod_tensor.tensor.data_type'] are not initialized.
The message is name: "uniform_random_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      dims: 32
      dims: 784
    }
  }
}
persistable: false
:

hj@ubuntu:~/my_paddle$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> print paddle.__version__
1.2.1
>>> quit()
hj@ubuntu:~/my_paddle$ 
hj@ubuntu:~/my_paddle$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> dtype = np.dtype(None)
>>> print dtype
float64
```
