### ISSUE TITLE
ValueError: could not broadcast input array from shape * into *

### ISSUE THREAD

**Issue by XipengY** [PaddlePaddle/Paddle#16029]
- 版本、环境信息：
    1）PaddlePaddle版本：1.3
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：CUDA8.0 cuDNN7.5
    4）系统环境：centos ，Python2.7
- 训练信息
    1）单机多卡
    2）显存信息 k40m
    3）Operator信息
错误信息如下：
Exception in thread Thread-1:
Traceback (most recent call last):
  File "*/apps/anaconda-install/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "*/apps/anaconda-install/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "*/apps/anaconda-install/anaconda2/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 566, in __provider_thread__
    for tensors in func():
  File "*/apps/anaconda-install/anaconda2/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 613, in __tensor_provider__
    for slots in paddle_reader():
  File "*/apps/anaconda-install/anaconda2/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 287, in __reader_creator__
    yield self.feed(item)
  File "*/apps/anaconda-install/anaconda2/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 206, in feed
    ret_dict[each_name] = each_converter.done()
  File "*/apps/anaconda-install/anaconda2/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 82, in done
    arr = numpy.array(self.data, dtype=self.dtype)
ValueError: could not broadcast input array from shape (3,425,640) into shape (3)

**Comment by Superjomn** [comment]
```
ValueError: could not broadcast input array from shape (3,425,640) into shape (3)
```

这是 input 的shape 和 输入数据不对应

是inputshape设错了？ 或者数据的numpy的shape准备错了吧

**Comment by XipengY** [comment]
@Superjomn 已经解决，是线程的问题，多线程读取数据存在问题，具体为什么不能用多线程，正在找问题。

**Comment by tago-tech** [comment]
> @Superjomn 已经解决，是线程的问题，多线程读取数据存在问题，具体为什么不能用多线程，正在找问题。

前辈你好，请问你是如何发现这个问题的？最后怎么解决的？
