### ISSUE TITLE
训练时invalid device function错误

### ISSUE THREAD

**Issue by yuanyc06** [PaddlePaddle/Paddle#16052]
Traceback (most recent call last):
  File "train.py", line 607, in <module>
    main()
  File "train.py", line 603, in main
    train(args)
  File "train.py", line 295, in train
    exe.run(startup_prog)
  File "/home/slurm/job/tmp/job-19102/python-paddle-0.11.0/lib/python2.7/site-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
RuntimeError: function_attributes(): after cudaFuncGetAttributes: invalid device function

训练时报如上错误，请问是什么问题？

**Comment by seiriosPlus** [comment]
咨询了一下GPU的同学，建议检查一下本地的GPU环境。
https://discuss.pytorch.org/t/function-attributes-after-cudafuncgetattributes-an-illegal-memory-access-was-encountered/12007
