### ISSUE TITLE
conv2d Tensor not initialized yet when Tensor::type() is called.

### ISSUE THREAD

**Issue by superwj1990** [PaddlePaddle/Paddle#16133]
```
I0309 15:50:09.520256 28672 operator.cc:165] CUDAPlace(0) Op(conv2d), inputs:{Bias[], Filter[conv2d_0.w_0:float[64, 3, 5, 5]({})], Input[image:[-1]({{}})], ResidualData[]}, outputs:{Output[conv2d_0.tmp_0:[-1]({{}})]}.
Traceback (most recent call last):
  File "train_classifier_distributed_version.py", line 425, in <module>
    main()
  File "train_classifier_distributed_version.py", line 313, in main
    run_pserver(train_program, startup_program)
  File "train_classifier_distributed_version.py", line 162, in run_pserver
    server_exe.run(train_prog)
  File "/home/ssd2/wangjian/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "/home/ssd2/wangjian/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 591, in _run
    exe.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Invoke operator conv2d error.
Python Callstacks:
  File "/home/ssd2/wangjian/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/ssd2/wangjian/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/ssd2/wangjian/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 1976, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "../models/sphere_resnet_128.py", line 113, in conv_bn_layer
    bias_attr=False)
  File "../models/sphere_resnet_128.py", line 58, in net
    input=input, num_filters=64, filter_size=5, stride=2, act='relu')
  File "train_classifier_distributed_version.py", line 277, in build_program
    loss, acc = model.net(image, label, iter)
  File "train_classifier_distributed_version.py", line 303, in main
    train_out = build_program(train_program, startup_program, True)
  File "train_classifier_distributed_version.py", line 425, in <module>
    main()
C++ Callstacks:
holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:145]
```

**Comment by xuezhong** [comment]
错误提示是某个tensor为空。建议运行时加上环境变量GLOG_vmodule=operator=4 GLOG_logtostderr=1看看运行到哪个op，哪个tensor为空。

**Comment by LeLiu** [comment]
> 错误提示是某个tensor为空。建议运行时加上环境变量GLOG_vmodule=operator=4 GLOG_logtostderr=1看看运行到哪个op，哪个tensor为空。

我遇到了同样的问题，打开日志后输出：
```
I0326 17:07:46.249222 48804 operator.cc:165] CPUPlace Op(feed), inputs:{X[feed:[-1]({{}})]}, outputs:{Out[label:[-1]({{}})]}.
I0326 17:07:46.249267 48804 operator.cc:188] CPUPlace Op(feed), inputs:{X[feed:[-1]({{}})]}, outputs:{Out[label:int[128, 1]({})]}.
I0326 17:07:46.249279 48804 operator.cc:165] CPUPlace Op(feed), inputs:{X[feed:[-1]({{}})]}, outputs:{Out[input_b:[-1]({{}})]}.
I0326 17:07:46.249289 48804 operator.cc:188] CPUPlace Op(feed), inputs:{X[feed:[-1]({{}})]}, outputs:{Out[input_b:float[128, 1, 864, 400]({})]}.
I0326 17:07:46.249303 48804 operator.cc:165] CPUPlace Op(feed), inputs:{X[feed:[-1]({{}})]}, outputs:{Out[input_a:[-1]({{}})]}.
I0326 17:07:46.249316 48804 operator.cc:188] CPUPlace Op(feed), inputs:{X[feed:[-1]({{}})]}, outputs:{Out[input_a:float[128, 1, 864, 400]({})]}.
I0326 17:07:46.249327 48804 operator.cc:165] CPUPlace Op(conv2d), inputs:{Bias[], Filter[conv1_conv.w_0:[-1]({{}})], Input[input_a:float[128, 1, 864, 400]({})], ResidualData[]}, outputs:{Output[conv1_conv.tmp_0:[-1]({{}})]}.
```
`({{}})`这种括号套括号是什么意思，就是您说的空Tensor吗？

我用如下方式输入数据：
```python
train_reader = paddle.batch(dataset.get_data_reader(cfg.train_data_path), batch_size=cfg.batch_size)
      for epoch_id in range(cfg.epoch_num):
           for step_id, data in enumerate(train_reader()):
               train_loss, train_acc = exe.run(main_program, feed=feeder.feed(data), fetch_list=[loss, acc])
```
已确定data中读入是有数据的。

**Comment by OliverLPH** [comment]
遇到了类似的问题，可以看下面是不是这个配置打开了，注释了这个配置应该就正常了
```c++
config->SwitchUseFeedFetchOps(false);
```

**Comment by luotao1** [comment]
@OliverLPH 应该不是这个原因哈。你贴的是预测C++配置里的，但这个issue的python文件是`train_classifier_distributed_version.py`，看上去是训练的。

**Comment by OliverLPH** [comment]
> @OliverLPH 应该不是这个原因哈。你贴的是预测C++配置里的，但这个issue的python文件是`train_classifier_distributed_version.py`，看上去是训练的。

哦对，刚刚没注意，但报错感觉还有点类似。
下面的是我遇到的问题的报错，可以参考下哈。
```
C++ exception with description "Invoke operator conv2d_fusion error.
Python Call stacks:
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 2181, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "/Paddle_models/save_inference_model/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/mobilenet.py", line 81, in _conv_norm
    bias_attr=False)
  File "/Paddle_models/save_inference_model/models/PaddleCV/PaddleDetection/ppdet/modeling/backbones/mobilenet.py", line 154, in __call__
    out = self._conv_norm(input, 3, int(32 * scale), 2, 1, name="conv1")
  File "/Paddle_models/save_inference_model/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/ssd.py", line 62, in build
    body_feats = self.backbone(im)
  File "/Paddle_models/save_inference_model/models/PaddleCV/PaddleDetection/ppdet/modeling/architectures/ssd.py", line 82, in test
    return self.build(feed_vars, 'test')
  File "tools/infer.py", line 169, in main
    test_fetches = model.test(feed_vars)
  File "tools/infer.py", line 272, in <module>
    main()
C++ Call stacks:
holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/sys/paddle_infer/Paddle/paddle/fluid/framework/tensor.h:139]
PaddlePaddle Call Stacks:
0       0x7f845bde434bp std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > paddle::platform::GetTraceBackString<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int) + 395
1       0x7f845bde48f7p paddle::platform::EnforceNotMet::EnforceNotMet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int) + 55
```

**Comment by xueeinstein** [comment]
Paddle 1.6版本，遇到了类似的问题，但我是训练几个batch后出现问题，非常奇怪。
![image](https://user-images.githubusercontent.com/3424201/69301243-8a929280-0c50-11ea-86d4-50e5472bdcef.png)

![屏幕快照 2019-11-21 上午11 17 16](https://user-images.githubusercontent.com/3424201/69301261-967e5480-0c50-11ea-8476-dc6c0cc63017.png)
