### ISSUE TITLE
conv2d Tensor not initialized yet when Tensor::type() is called.

### ISSUE THREAD

**Issue by superwj1990** [PaddlePaddle/Paddle#16134]
I0309 15:50:09.520256 28672 operator.cc:165] CUDAPlace(0) Op(conv2d), inputs:{Bias[], Filter[conv2d_0.w_0:float[64, 3, 5, 5]({})], Input[image:[-1]({{}})], ResidualData[]}, outputs:{Output[conv2d_0.tmp_0:[-1]({{}})]}.
Traceback (most recent call last):
  File "train_classifier_distributed_version.py", line 425, in <module>
    main()
  File "train_classifier_distributed_version.py", line 313, in main
    run_pserver(train_program, startup_program)
  File "train_classifier_distributed_version.py", line 162, in run_pserver
    server_exe.run(train_prog)
  File "/home/ssd2/wangjian/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "/home/ssd2/wangjian/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 591, in _run
    exe.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Invoke operator conv2d error.
Python Callstacks:
  File "/home/ssd2/wangjian/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/ssd2/wangjian/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/ssd2/wangjian/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 1976, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "../models/sphere_resnet_128.py", line 113, in conv_bn_layer
    bias_attr=False)
  File "../models/sphere_resnet_128.py", line 58, in net
    input=input, num_filters=64, filter_size=5, stride=2, act='relu')
  File "train_classifier_distributed_version.py", line 277, in build_program
    loss, acc = model.net(image, label, iter)
  File "train_classifier_distributed_version.py", line 303, in main
    train_out = build_program(train_program, startup_program, True)
  File "train_classifier_distributed_version.py", line 425, in <module>
    main()
C++ Callstacks:
holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:145]

**Comment by sneaxiy** [comment]
The same as #16133
