### ISSUE TITLE
安装完from paddle.fluid import fluid时不能加载core.pyd文件

### ISSUE THREAD

**Issue by Tianhuo007** [PaddlePaddle/Paddle#16234]
版本、环境信息：
   1）PaddlePaddle版本：1.3
   2）CPU：Intel(R) Core(TM) i5-7500
   3）操作系统：Windows10 + anconda3安装python3.7
   4）环境变量设置也没有问题

安装方式信息：
pip安装：pip3 install paddlepaddle

问题：
### import paddle.fluid as fluid 时出现：
Traceback (most recent call last):
  File "C:\Users\longfei\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 38, in <module>
    from . import core
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\longfei\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\ptvsd_launcher.py", line 45, in <module>
    main(ptvsdArgs)
  File "c:\Users\longfei\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\__main__.py", line 357, in main
    run()
  File "c:\Users\longfei\.vscode\extensions\ms-python.python-2019.2.5558\pythonFiles\lib\python\ptvsd\__main__.py", line 257, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\longfei\Anaconda3\envs\paddle\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\longfei\Anaconda3\envs\paddle\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\longfei\Anaconda3\envs\paddle\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\longfei\andrew coursework\paddlepaddle\Lod-tensor.py", line 3, in <module>
    import paddle.fluid as fluid
  File "C:\Users\longfei\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\__init__.py", line 18, in <module>
    from . import framework
  File "C:\Users\longfei\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 47, in <module>
    (executable_path, executable_path, cpt.get_exception_message(e)))
ImportError: NOTE: You may need to run "set PATH=C:\Users\longfei\Anaconda3\envs\paddle;%PATH%"
        if you encounters "DLL load failed" errors. If you have python
        installed in other directory, replace "C:\Users\longfei\Anaconda3\envs\paddle" with your own
        directory. The original error is:
 DLL load failed: 找不到指定的模块。
请按任意键继续. . .

**Comment by wopeizl** [comment]
可以参考一下 https://github.com/PaddlePaddle/Paddle/issues/15423#issuecomment-473631912

**Comment by wangguibao** [comment]
该issue已经超过1个月没有反馈，先关闭了。如有需要可reopen。多谢
