### ISSUE TITLE
复现PNet网络问题

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16249]
# 环境
 - PaddlePaddle 1.2 GPU
 - Ubuntu 16.04
 - Python 3.5

# 问题
我想复现一个tensorflow的模型：
```python
def P_Net(inputs, label=None, bbox_target=None, landmark_target=None, training=True):
    '''pnet的结构'''
    with tf.variable_scope('PNet'):
        with slim.arg_scope([slim.conv2d], activation_fn=prelu,
                            weights_initializer=slim.xavier_initializer(),
                            weights_regularizer=slim.l2_regularizer(0.0005),
                            padding='VALID'):
            net = slim.conv2d(inputs, 10, 3, scope='conv1')
            net = slim.max_pool2d(net, kernel_size=[2, 2], stride=2, padding='SAME', scope='pool1')
            net = slim.conv2d(net, 16, 3, scope='conv2')
            net = slim.conv2d(net, 32, 3, scope='conv3')
            # 二分类输出通道数为2
            conv4_1 = slim.conv2d(net, 2, 1, activation_fn=tf.nn.softmax, scope='conv4_1')
            bbox_pred = slim.conv2d(net, 4, 1, activation_fn=None, scope='conv4_2')
            landmark_pred = slim.conv2d(net, 10, 1, activation_fn=None, scope='conv4_3')

            if training:
                cls_prob = tf.squeeze(conv4_1, [1, 2], name='cls_prob')  # [batch,2]
                cls_loss = cls_ohem(cls_prob, label)

                bbox_pred = tf.squeeze(bbox_pred, [1, 2], name='bbox_pred')  # [bacth,4]
                bbox_loss = bbox_ohem(bbox_pred, bbox_target, label)

                landmark_pred = tf.squeeze(landmark_pred, [1, 2], name='landmark_pred')  # [batch,10]
                landmark_loss = landmark_ohem(landmark_pred, landmark_target, label)

                accuracy = cal_accuracy(cls_prob, label)
                L2_loss = tf.add_n(slim.losses.get_regularization_losses())
                return cls_loss, bbox_loss, landmark_loss, L2_loss, accuracy
            else:
                # 测试时batch_size=1
                cls_pro_test = tf.squeeze(conv4_1, axis=0)
                bbox_pred_test = tf.squeeze(bbox_pred, axis=0)
                landmark_pred_test = tf.squeeze(landmark_pred, axis=0)
                return cls_pro_test, bbox_pred_test, landmark_pred_test
```

我写的PaddlePad代码如下：
```python
import paddle.fluid as fluid
from paddle.fluid.param_attr import ParamAttr

def P_Net():
    # 定义输入层
    image = fluid.layers.data(name='image', shape=[3, 12, 12], dtype='float32')
    label = fluid.layers.data(name='label', shape=[1], dtype='int64')
    bbox_target = fluid.layers.data(name='bbox_target', shape=[4], dtype='float32')
    landmark_target = fluid.layers.data(name='landmark_target', shape=[10], dtype='float32')

    conv1 = fluid.layers.conv2d(input=image,
                                num_filters=10,
                                filter_size=3,
                                param_attr=ParamAttr(initializer=fluid.initializer.Xavier()),
                                name='conv1')
    conv1_prelu = fluid.layers.prelu(x=conv1, mode='channel', name='conv1_prelu')

    pool1 = fluid.layers.pool2d(input=conv1_prelu,
                                pool_size=2,
                                pool_stride=2,
                                name='pool1')

    conv2 = fluid.layers.conv2d(input=pool1,
                                num_filters=16,
                                filter_size=3,
                                param_attr=ParamAttr(initializer=fluid.initializer.Xavier()),
                                name='conv2')
    conv2_prelu = fluid.layers.prelu(x=conv2, mode='channel', name='conv2_prelu')

    conv3 = fluid.layers.conv2d(input=conv2_prelu,
                                num_filters=32,
                                filter_size=3,
                                param_attr=ParamAttr(initializer=fluid.initializer.Xavier()),
                                name='conv3')
    conv3_prelu = fluid.layers.prelu(x=conv3, mode='channel', name='conv3_prelu')

    conv4_1 = fluid.layers.conv2d(input=conv3_prelu,
                                  num_filters=2,
                                  filter_size=1,
                                  act='softmax',
                                  name='conv4_1')

    conv4_2 = fluid.layers.conv2d(input=conv3_prelu,
                                  num_filters=4,
                                  filter_size=1,
                                  name='conv4_2')

    conv4_3 = fluid.layers.conv2d(input=conv3_prelu,
                                  num_filters=10,
                                  filter_size=1,
                                  name='conv4_3')

    cls_prob = fluid.layers.squeeze(input=conv4_1, axes=[2], name='cls_prob')
    label_cost = fluid.layers.cross_entropy(input=cls_prob, label=label)

    bbox_pred = fluid.layers.squeeze(input=conv4_1, axes=[2], name='bbox_pred')
    bbox_loss = fluid.layers.square_error_cost(input=bbox_pred, label=bbox_target)

    landmark_pred = fluid.layers.squeeze(input=conv4_1, axes=[2], name='landmark_pred')
    landmark_loss = fluid.layers.square_error_cost(input=landmark_pred, label=landmark_target)

    return image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, conv4_1, conv4_2, conv4_3
```

报错如下：
```
Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/train_PNet.py", line 12, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, conv4_1, conv4_2, conv4_3 = P_Net()
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/P_Net.py", line 54, in P_Net
    label_cost = fluid.layers.cross_entropy(input=cls_prob, label=label)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layers/nn.py", line 1345, in cross_entropy
    "ignore_index": ignore_index})
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layer_helper.py", line 50, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 1208, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 657, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected rank == label_dims.size(), but received rank:3 != label_dims.size():2.
Input(X) and Input(Label) shall have the same rank. at [/home/test/Downloads/Paddle/paddle/fluid/operators/cross_entropy_op.cc:34]
PaddlePaddle Call Stacks: 
0       0x7f5f679f0a27p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7f5f67b8325dp paddle::operators::CrossEntropyOp::InferShape(paddle::framework::InferShapeContext*) const + 1741
2       0x7f5f67ac98a0p
3       0x7f5f67acdc5ap paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1050
4       0x7f5f67a77e24p
5       0x7f5f67a1f16dp
6             0x4ea137p PyCFunction_Call + 119
7             0x53c176p PyEval_EvalFrameEx + 23030
8             0x540b0bp PyEval_EvalCodeEx + 315
9             0x4ec3f7p
10            0x5c20e7p PyObject_Call + 71
11            0x4fbfcep
12            0x5c20e7p PyObject_Call + 71
13            0x574c19p
14            0x57f58cp
15            0x5c20e7p PyObject_Call + 71
16            0x538cabp PyEval_EvalFrameEx + 9515
17            0x540b0bp PyEval_EvalCodeEx + 315
18            0x4ec3f7p
19            0x5c20e7p PyObject_Call + 71
20            0x538cabp PyEval_EvalFrameEx + 9515
21            0x53fc97p
22            0x53bc93p PyEval_EvalFrameEx + 21779
23            0x53fc97p
24            0x53b83fp PyEval_EvalFrameEx + 20671
25            0x53b294p PyEval_EvalFrameEx + 19220
26            0x53fc97p
27            0x5409bfp PyEval_EvalCode + 31
28            0x60cb42p
29            0x60efeap PyRun_FileExFlags + 154
30            0x60f7dcp PyRun_SimpleFileExFlags + 444
31            0x640256p Py_Main + 1110
32            0x4d0001p main + 225
33      0x7f5fb65f9830p __libc_start_main + 240
34            0x5d6999p _start + 41


Process finished with exit code 1

```

**Comment by yeyupiaoling** [comment]
顺便也问一下，`fluid.layers.prelu`这个激活函数的model参数的值应该是什么呢？

**Comment by yeyupiaoling** [comment]
还多问一下，tensorflow的在每一个卷积层中都添加了`weights_regularizer=slim.l2_regularizer(0.0005)`，PaddlePaddle是如果添加的呢？

**Comment by yeyupiaoling** [comment]
tensorflow使用的损失函数是以下的，我的是PaddlePaddle自带的损失函数，不知道是否正确？
```python
num_keep_radio = 0.7

def cls_ohem(cls_prob, label):
    '''计算类别损失
    参数：
      cls_prob：预测类别，是否有人
      label：真实值
    返回值：
      损失
    '''
    zeros = tf.zeros_like(label)
    # 只把pos的label设定为1,其余都为0
    label_filter_invalid = tf.where(tf.less(label, 0), zeros, label)
    # 类别size[2*batch]
    num_cls_prob = tf.size(cls_prob)
    cls_prob_reshpae = tf.reshape(cls_prob, [num_cls_prob, -1])
    label_int = tf.cast(label_filter_invalid, tf.int32)
    # 获取batch数
    num_row = tf.to_int32(cls_prob.get_shape()[0])
    # 对应某一batch而言，batch*2为非人类别概率，batch*2+1为人概率类别,indices为对应 cls_prob_reshpae
    # 应该的真实值，后续用交叉熵计算损失
    row = tf.range(num_row) * 2
    indices_ = row + label_int
    # 真实标签对应的概率
    label_prob = tf.squeeze(tf.gather(cls_prob_reshpae, indices_))
    loss = -tf.log(label_prob + 1e-10)
    zeros = tf.zeros_like(label_prob, dtype=tf.float32)
    ones = tf.ones_like(label_prob, dtype=tf.float32)
    # 统计neg和pos的数量
    valid_inds = tf.where(label < zeros, zeros, ones)
    num_valid = tf.reduce_sum(valid_inds)
    # 选取70%的数据
    keep_num = tf.cast(num_valid * num_keep_radio, dtype=tf.int32)
    # 只选取neg，pos的70%损失
    loss = loss * valid_inds
    loss, _ = tf.nn.top_k(loss, k=keep_num)
    return tf.reduce_mean(loss)


# In[4]:


def bbox_ohem(bbox_pred, bbox_target, label):
    '''计算box的损失'''
    zeros_index = tf.zeros_like(label, dtype=tf.float32)
    ones_index = tf.ones_like(label, dtype=tf.float32)
    # 保留pos和part的数据
    valid_inds = tf.where(tf.equal(tf.abs(label), 1), ones_index, zeros_index)
    # 计算平方差损失
    square_error = tf.square(bbox_pred - bbox_target)
    square_error = tf.reduce_sum(square_error, axis=1)
    # 保留的数据的个数
    num_valid = tf.reduce_sum(valid_inds)
    keep_num = tf.cast(num_valid, dtype=tf.int32)
    # 保留pos和part部分的损失
    square_error = square_error * valid_inds
    square_error, _ = tf.nn.top_k(square_error, k=keep_num)
    return tf.reduce_mean(square_error)


# In[5]:


def landmark_ohem(landmark_pred, landmark_target, label):
    '''计算关键点损失'''
    ones = tf.ones_like(label, dtype=tf.float32)
    zeros = tf.zeros_like(label, dtype=tf.float32)
    # 只保留landmark数据
    valid_inds = tf.where(tf.equal(label, -2), ones, zeros)
    # 计算平方差损失
    square_error = tf.square(landmark_pred - landmark_target)
    square_error = tf.reduce_sum(square_error, axis=1)
    # 保留数据个数
    num_valid = tf.reduce_sum(valid_inds)
    keep_num = tf.cast(num_valid, dtype=tf.int32)
    # 保留landmark部分数据损失
    square_error = square_error * valid_inds
    square_error, _ = tf.nn.top_k(square_error, k=keep_num)
    return tf.reduce_mean(square_error)
```

**Comment by gavin1332** [comment]
我加了一点打印代码：
![image](https://user-images.githubusercontent.com/1552048/54517254-1eaeaa80-499c-11e9-8422-9be00368b16c.png)
得到的结果是
(-1L, 2L, 1L, 1L)
(-1L, 2L, 1L)
(-1L, 1L)
可以看出cls_prob和label的shape对不上，跟错误信息一致：
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected rank == label_dims.size(), but received rank:3 != label_dims.size():2.
你再检查下你的网络配置

**Comment by gavin1332** [comment]
其中-1是batch size，是运行时确定的

**Comment by gavin1332** [comment]
> `fluid.layers.prelu`这个激活函数的model参数的值应该是什么呢？

这是个可学习的参数layer

**Comment by gavin1332** [comment]
> weights_regularizer=slim.l2_regularizer(0.0005)

参考：http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/fluid_cn.html#paramattr
regularizer (WeightDecayRegularizer) – 正则因子. 默认为None

**Comment by yeyupiaoling** [comment]
>可以看出cls_prob和label的shape对不上，跟错误信息一致：
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected rank == label_dims.size(), but received rank:3 != label_dims.size():2.
你再检查下你的网络配置

@gavin1332 我对比了tensorflow的代码，应该是正确的哦。

然后我修改了输入层如下：就正确了。但是这样修改好像不是正确的做法吧？
```python
label = fluid.layers.data(name='label', shape=[2, 1], dtype='int64')
```

**Comment by yeyupiaoling** [comment]
@gavin1332 按照我上面的修改方式，错误如下：
```
W0318 17:27:26.187537  9404 device_context.cc:203] Please NOTE: device: 0, CUDA Capability: 75, Driver Version: 10.0, Runtime Version: 10.0
W0318 17:27:26.187561  9404 device_context.cc:210] device: 0, cuDNN Version: 7.0.
Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/train_PNet.py", line 41, in <module>
    fetch_list=[avg_total_loss])
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 472, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected framework::slice_ddim(x_dims, 0, rank - 1) == framework::slice_ddim(label_dims, 0, rank - 1), but received framework::slice_ddim(x_dims, 0, rank - 1):32, 2 != framework::slice_ddim(label_dims, 0, rank - 1):16, 2.
Input(X) and Input(Label) shall have the same shape except the last dimension. at [/home/test/Downloads/Paddle/paddle/fluid/operators/cross_entropy_op.cc:38]
PaddlePaddle Call Stacks: 
0       0x7f087be2ea27p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7f087bfc14fdp paddle::operators::CrossEntropyOp::InferShape(paddle::framework::InferShapeContext*) const + 2413
2       0x7f087d82a8b9p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1129
3       0x7f087d8245a0p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 544
4       0x7f087bf25778p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 248
5       0x7f087bf2744ap paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 154
6       0x7f087be0c56ap
7       0x7f087be5d16dp
8             0x4ea137p PyCFunction_Call + 119
9             0x53c176p PyEval_EvalFrameEx + 23030
10            0x53fc97p
11            0x53b83fp PyEval_EvalFrameEx + 20671
12            0x53fc97p
13            0x5409bfp PyEval_EvalCode + 31
14            0x60cb42p
15            0x60efeap PyRun_FileExFlags + 154
16            0x60f7dcp PyRun_SimpleFileExFlags + 444
17            0x640256p Py_Main + 1110
18            0x4d0001p main + 225
19      0x7f08caa37830p __libc_start_main + 240
20            0x5d6999p _start + 41


Process finished with exit code 1

```

**Comment by yeyupiaoling** [comment]
@gavin1332 能否帮我调试调试吗？

**Comment by yeyupiaoling** [comment]
@gavin1332 tensorflow的下面代码的处理是正确的。
```python
conv4_1 = slim.conv2d(net, 2, 1, activation_fn=tf.nn.softmax, scope='conv4_1')
print(conv4_1)
cls_prob = tf.squeeze(conv4_1, [1, 2], name='cls_prob')
print(cls_prob)
```

输出的维度信息：
```
Tensor("PNet/conv4_1/Reshape_1:0", shape=(384, 1, 1, 2), dtype=float32)
Tensor("PNet/cls_prob:0", shape=(384, 2), dtype=float32)
```

Tensorflow可以正常进行维度转换，但是PaddlePpaddle就报错，而且维度顺序不一样的
```python
conv4_1 = fluid.layers.conv2d(input=conv3_prelu,
                              num_filters=2,
                              filter_size=1,
                              act='softmax',
                              param_attr=ParamAttr(initializer=Xavier(),
                                                   regularizer=L2DecayRegularizer(0.0005)),
                              name='conv4_1')

print(conv4_1)
cls_prob = fluid.layers.squeeze(input=conv4_1, axes=[1, 2], name='cls_prob')
```


从下面的输出信息可以看出，维度顺序跟Tensorflow的不一样，tensorflow的是`1,1,2`，PaddlePaddle的是`2,1,1`。所以在执行`fluid.layers.squeeze`的时候 就报错。
```
name: "conv4_1.tmp_2"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 2
      dims: 1
      dims: 1
    }
    lod_level: 0
  }
}
persistable: false

Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/train_PNet.py", line 12, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, conv4_1, conv4_2, conv4_3 = P_Net()
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 66, in P_Net
    cls_prob = fluid.layers.squeeze(input=conv4_1, axes=[1, 2], name='cls_prob')
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layers/nn.py", line 5550, in squeeze
    "XShape": x_shape})
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layer_helper.py", line 50, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 1208, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 657, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Invalid axis index, the axis that will be squeezed should be equal to 1. at [/home/test/Downloads/Paddle/paddle/fluid/operators/squeeze_op.cc:76]
PaddlePaddle Call Stacks: 
0       0x7f90c463aa27p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7f90c4e4f6d5p paddle::operators::SqueezeOpInferShape::GetOutputShape(std::vector<int, std::allocator<int> >, paddle::framework::DDim const&) + 597

```

**Comment by gavin1332** [comment]
我理解这是个二分类问题？如果是的话，可以按照如下方式squeeze：
cls_prob = fluid.layers.squeeze(input=conv4_1, axes=[2,3], name='cls_prob')
我在你代码基础上尝试成功。

**Comment by yeyupiaoling** [comment]
@gavin1332 谢谢你的回答，我把axes设置为[]就可以了，然后正确的PNet网络如下:
```python
def P_Net():
    # 定义输入层
    image = fluid.layers.data(name='image', shape=[3, 12, 12], dtype='float32')
    label = fluid.layers.data(name='label', shape=[1], dtype='float32')
    bbox_target = fluid.layers.data(name='bbox_target', shape=[4], dtype='float32')
    landmark_target = fluid.layers.data(name='landmark_target', shape=[10], dtype='float32')

    conv1 = fluid.layers.conv2d(input=image,
                                num_filters=10,
                                filter_size=3,
                                param_attr=ParamAttr(initializer=Xavier(),
                                                     regularizer=L2DecayRegularizer(0.0005)),
                                name='conv1')
    conv1_prelu = fluid.layers.prelu(x=conv1, mode='all', name='conv1_prelu')

    pool1 = fluid.layers.pool2d(input=conv1_prelu,
                                pool_size=2,
                                pool_stride=2,
                                name='pool1')

    conv2 = fluid.layers.conv2d(input=pool1,
                                num_filters=16,
                                filter_size=3,
                                param_attr=ParamAttr(initializer=Xavier(),
                                                     regularizer=L2DecayRegularizer(0.0005)),
                                name='conv2')
    conv2_prelu = fluid.layers.prelu(x=conv2, mode='all', name='conv2_prelu')

    conv3 = fluid.layers.conv2d(input=conv2_prelu,
                                num_filters=32,
                                filter_size=3,
                                param_attr=ParamAttr(initializer=Xavier(),
                                                     regularizer=L2DecayRegularizer(0.0005)),
                                name='conv3')
    conv3_prelu = fluid.layers.prelu(x=conv3, mode='all', name='conv3_prelu')

    conv4_1 = fluid.layers.conv2d(input=conv3_prelu,
                                  num_filters=2,
                                  filter_size=1,
                                  act='softmax',
                                  param_attr=ParamAttr(initializer=Xavier(),
                                                       regularizer=L2DecayRegularizer(0.0005)),
                                  name='conv4_1')

    conv4_2 = fluid.layers.conv2d(input=conv3_prelu,
                                  num_filters=4,
                                  filter_size=1,
                                  param_attr=ParamAttr(initializer=Xavier(),
                                                       regularizer=L2DecayRegularizer(0.0005)),
                                  name='conv4_2')

    conv4_3 = fluid.layers.conv2d(input=conv3_prelu,
                                  num_filters=10,
                                  filter_size=1,
                                  param_attr=ParamAttr(initializer=Xavier(),
                                                       regularizer=L2DecayRegularizer(0.0005)),
                                  name='conv4_3')

    cls_prob = fluid.layers.squeeze(input=conv4_1, axes=[], name='cls_prob')
    label_cost = cls_ohem(cls_prob=cls_prob, label=label)

    bbox_pred = fluid.layers.squeeze(input=conv4_2, axes=[], name='bbox_pred')
    bbox_loss = bbox_ohem(bbox_pred=bbox_pred, bbox_target=bbox_target, label=label)

    landmark_pred = fluid.layers.squeeze(input=conv4_3, axes=[], name='landmark_pred')
    landmark_loss = landmark_ohem(landmark_pred=landmark_pred, landmark_target=landmark_target, label=label)

    return image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, conv4_1, conv4_2, conv4_3
```
