### ISSUE TITLE
MTCNN模型的交叉熵损失函数

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16273]
# 环境
 - PaddlePaddle
 - Ubuntu 16.04
 - Python 3.5

# 问题
我想用PaddlePaddle复现MTCNN模型的交叉熵损失函数，以下的tensorflow的代码
```python
def cls_ohem(cls_prob, label):
    '''计算类别损失
    参数：
      cls_prob：预测类别，是否有人
      label：真实值
    返回值：
      损失
    '''
    zeros = tf.zeros_like(label)

    # 只把pos的label设定为1,其余都为0
    label_filter_invalid = tf.where(tf.less(label, 0), zeros, label)

    # 类别size[2*batch]
    num_cls_prob = tf.size(cls_prob)
    cls_prob_reshpae = tf.reshape(cls_prob, [num_cls_prob, -1])
    label_int = tf.cast(label_filter_invalid, tf.int32)

    # 获取batch数
    num_row = tf.to_int32(cls_prob.get_shape()[0])

    # 对应某一batch而言，batch*2为非人类别概率，batch*2+1为人概率类别,indices为对应 cls_prob_reshpae
    # 应该的真实值，后续用交叉熵计算损失
    row = tf.range(num_row) * 2
    indices_ = row + label_int

    # 真实标签对应的概率
    label_prob = tf.squeeze(tf.gather(cls_prob_reshpae, indices_))
    loss = -tf.log(label_prob + 1e-10)
    zeros = tf.zeros_like(label_prob, dtype=tf.float32)
    ones = tf.ones_like(label_prob, dtype=tf.float32)

    # 统计neg和pos的数量
    valid_inds = tf.where(label < zeros, zeros, ones)
    num_valid = tf.reduce_sum(valid_inds)

    # 选取70%的数据
    keep_num = tf.cast(num_valid * num_keep_radio, dtype=tf.int32)

    # 只选取neg，pos的70%损失
    loss = loss * valid_inds
    loss, _ = tf.nn.top_k(loss, k=keep_num)
    return tf.reduce_mean(loss)
```

我用PaddlePaddle大概复现了一下，逻辑也不知道对不对的。
```python
def cls_ohem(cls_prob, label):
    '''计算类别损失
    参数：
      cls_prob：预测类别，是否有人
      label：真实值
    返回值：
      损失
    '''
    # 只把pos的label设定为1,其余都为0
    zeros = fluid.layers.zeros(shape=[int(i) for i in label.shape], dtype=label.dtype)
    cond = fluid.layers.less_than(x=label, y=fluid.layers.fill_constant(shape=[],dtype='float32', value=0))
    ie = fluid.layers.IfElse(cond)
    with ie.true_block():
        ie.output(zeros)

    with ie.false_block():
        ie.output(label)
    label_filter_invalid = ie()

    # 类别size[2*batch]
    num_cls_prob = sum(cls_prob.shape)
    cls_prob_reshpae = fluid.layers.reshape(cls_prob, [num_cls_prob, -1])
    label_int = fluid.layers.cast(label_filter_invalid[0], dtype='int32')

    # 获取batch数
    num_row = fluid.layers.fill_constant(shape=[],dtype='int32', value=cls_prob.shape[0])

    # 对应某一batch而言，batch*2为非人类别概率，batch*2+1为人概率类别,indices为对应 cls_prob_reshpae
    # 应该的真实值，后续用交叉熵计算损失
    indices_ = []
    i = fluid.layers.fill_constant(shape=[], dtype='int32', value=0)
    cond = fluid.layers.less_than(x=i, y=num_row)
    print(cond)
    while_op = fluid.layers.While(cond=cond)
    with while_op.block():
        indices_.append(i + label_int)
        i = i + 1
        fluid.layers.less_than(x=i, y=num_row, cond=cond)

    # 真实标签对应的概率
    indices_ = fluid.layers.cast(indices_, dtype='int32')
    label_prob = fluid.layers.squeeze(fluid.layers.gather(cls_prob_reshpae, indices_))
    loss = -fluid.layers.log(label_prob + 1e-10)
    zeros = fluid.layers.zeros(shape=[int(i) for i in label_prob.shape], dtype='float32')
    ones = fluid.layers.ones(shape=[int(i) for i in label_prob.shape], dtype='float32')

    # 统计neg和pos的数量
    cond2 = fluid.layers.less_than(x=label, y=zeros)
    ie2 = fluid.layers.IfElse(cond2)
    with ie2.true_block():
        ie2.output(zeros)
    with ie2.false_block():
        ie2.output(ones)
    valid_inds = ie2()
    num_valid = fluid.layers.reduce_sum(valid_inds)

    # 选取70%的数据
    keep_num = fluid.layers.cast(num_valid * num_keep_radio, dtype='int32')

    # 只选取neg，pos的70%损失
    loss = loss * valid_inds
    loss, _ = fluid.layers.nn.topk(loss, k=keep_num)
    return fluid.layers.reduce_mean(loss)
```

在使用的时候报错：
```
Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/train_PNet.py", line 12, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, conv4_1, conv4_2, conv4_3 = P_Net()
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 67, in P_Net
    label_cost = cls_ohem(cls_prob=cls_prob, label=label)
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 114, in cls_ohem
    while_op = fluid.layers.While(cond=cond)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layers/control_flow.py", line 693, in __init__
    raise TypeError("condition should be a bool scalar")
TypeError: condition should be a bool scalar
```

恳请各位老师帮忙复现一下，谢谢。

**Comment by Xreki** [comment]
```python
    # 获取batch数
    num_row = fluid.layers.fill_constant(shape=[],dtype='int32', value=cls_prob.shape[0])

    # 对应某一batch而言，batch*2为非人类别概率，batch*2+1为人概率类别,indices为对应 cls_prob_reshpae
    # 应该的真实值，后续用交叉熵计算损失
    indices_ = []
    i = fluid.layers.fill_constant(shape=[], dtype='int32', value=0)
    cond = fluid.layers.less_than(x=i, y=num_row)
    print(cond)
    while_op = fluid.layers.While(cond=cond)
```

错误在于`cond`这个tensor。`cond`这个tensor用于while里面，其维度必须是1，而它是`less_than`产生的，这就要求`less_than`的两个输入的维度也必须是1。建议改成如下：

```python
    # 获取batch数
    num_row = fluid.layers.fill_constant(shape=[1],dtype='int32', value=cls_prob.shape[0], force_cpu=True)

    # 对应某一batch而言，batch*2为非人类别概率，batch*2+1为人概率类别,indices为对应 cls_prob_reshpae
    # 应该的真实值，后续用交叉熵计算损失
    indices_ = []
    i = fluid.layers.fill_constant(shape=[1], dtype='int32', value=0, force_cpu=True)
    cond = fluid.layers.less_than(x=i, y=num_row)
    print(cond)
    while_op = fluid.layers.While(cond=cond)
```

**Comment by yeyupiaoling** [comment]
@Xreki 在下面有个数组拼接，这个如果出来呢？

```python
    indices_ = []
    i = fluid.layers.fill_constant(shape=[1], dtype='int32', value=0)
    cond = fluid.layers.less_than(x=i, y=num_row)
    while_op = fluid.layers.While(cond=cond)
    with while_op.block():
        indices_.append(fluid.layers.sum(i, label_int))
        i = fluid.layers.sum(i, 1)
        fluid.layers.less_than(x=i, y=num_row, cond=cond)
```

保存如下：
```
Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/train_PNet.py", line 12, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, conv4_1, conv4_2, conv4_3 = P_Net()
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 68, in P_Net
    label_cost = cls_ohem(cls_prob=cls_prob, label=label)
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 114, in cls_ohem
    indices_.append(fluid.layers.sum(i, label_int))
TypeError: sum() takes 1 positional argument but 2 were given
```

**Comment by yeyupiaoling** [comment]
@Xreki 请问使用PaddlePaddle如何实现以下代码呢？主要是最后两行。
```python
label_int = tf.cast(label_filter_invalid, tf.int32)

# 获取batch数
num_row = tf.to_int32(cls_prob.get_shape()[0])

row = tf.range(num_row) * 2
indices_ = row + label_int
```

**Comment by yeyupiaoling** [comment]
@Xreki 妳好，能否指点以下如何使用PaddlePaddle实现以下代码
```
row = tf.range(num_row) * 2
indices_ = row + label_int
```

**Comment by Xreki** [comment]
`tf.range`是获取一个tensor，data为`0,1,2,...,num_row-1`？目前PR https://github.com/PaddlePaddle/Paddle/pull/15431 ，还在review中。

`*2`这个操作，你需要使用`fill_constant`或者`fill_constant_batch_size`初始化一个值为2的tensor，然后用`elementwise_mul`实现`*`。

**Comment by yeyupiaoling** [comment]
@Xreki 我目前是这样实现，但是报错的。PaddlePaddle对是不是不能执行广播呢？

```python
    indices_ = fluid.layers.create_array(dtype='int32')
    i = fluid.layers.fill_constant(shape=[1], dtype='int32', value=0)
    one = fluid.layers.fill_constant(shape=[1], dtype='int32', value=1)
    two = fluid.layers.fill_constant(shape=[1], dtype='int32', value=2)
    cond = fluid.layers.less_than(x=i, y=num_row)
    while_op = fluid.layers.While(cond=cond)
    with while_op.block():
        temp1 = fluid.layers.elementwise_mul(i, two)
        indices_ = fluid.layers.concat([indices_, temp1])
        i = fluid.layers.elementwise_add(i, one)
        fluid.layers.less_than(x=i, y=num_row, cond=cond)
    print(indices_)
    print(label_int)
    indices_ = fluid.layers.elementwise_add(indices_, label_int)
```

报错信息：
```
name: "concat_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT32
      dims: 1
    }
    lod_level: 0
  }
}
persistable: false

name: "cast_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT32
      dims: -1
      dims: 1
    }
    lod_level: 0
  }
}
persistable: false

Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/train_PNet.py", line 13, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, conv4_1, conv4_2, conv4_3 = P_Net()
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 68, in P_Net
    label_cost = cls_ohem(cls_prob=cls_prob, label=label)
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 125, in cls_ohem
    indices_ = fluid.layers.elementwise_add(indices_, label_int)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layers/nn.py", line 8081, in elementwise_add
    return _elementwise_op(LayerHelper('elementwise_add', **locals()))
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layers/nn.py", line 8040, in _elementwise_op
    'use_mkldnn': use_mkldnn})
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layer_helper.py", line 50, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 1208, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 657, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected x_dim.size() >= y_dim.size(), but received x_dim.size():1 < y_dim.size():2.
Rank of first input must >= rank of second input. at [/home/test/Downloads/Paddle/paddle/fluid/operators/elementwise/elementwise_op.h:54]
PaddlePaddle Call Stacks: 
0       0x7fb17e0dca27p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7fb17f68387bp paddle::operators::ElementwiseOp::InferShape(paddle::framework::InferShapeContext*) const + 1627
2       0x7fb17e1b58a0p
3       0x7fb17e1b9c5ap paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1050

```

还有这样写的逻辑正确吗？

**Comment by yeyupiaoling** [comment]
@Xreki 我把他们换了个位置
```python
    indices_ = fluid.layers.create_array(dtype='int32')
    i = fluid.layers.fill_constant(shape=[1], dtype='int32', value=0)
    one = fluid.layers.fill_constant(shape=[1], dtype='int32', value=1)
    two = fluid.layers.fill_constant(shape=[1], dtype='int32', value=2)
    cond = fluid.layers.less_than(x=i, y=num_row)
    while_op = fluid.layers.While(cond=cond)
    with while_op.block():
        temp1 = fluid.layers.elementwise_mul(i, two)
        indices_ = fluid.layers.concat([indices_, temp1])
        i = fluid.layers.elementwise_add(i, one)
        fluid.layers.less_than(x=i, y=num_row, cond=cond)
    indices_ = fluid.layers.elementwise_add(label_int, indices_)
```

报错如下：
```
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 120, in cls_ohem
    indices_ = fluid.layers.elementwise_add(label_int, indices_)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layers/nn.py", line 8081, in elementwise_add
    return _elementwise_op(LayerHelper('elementwise_add', **locals()))
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layers/nn.py", line 8040, in _elementwise_op
    'use_mkldnn': use_mkldnn})
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layer_helper.py", line 50, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 1208, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 657, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Input(Y) of elementwise op should not be null. at [/home/test/Downloads/Paddle/paddle/fluid/operators/elementwise/elementwise_op.h:39]
PaddlePaddle Call Stacks: 

```

**Comment by Xreki** [comment]
`indices_ = fluid.layers.concat([indices_, temp1])`

这么执行的目的是什么？`indices_`是一个tensor_array，temp1是一个tensor，应该不能`concat`，或者结果不可预料。

while_op和tensor_array使用的例子，请参考：
https://github.com/PaddlePaddle/models/blob/bbdb2469ab676f562c6a3666879425474f57046a/fluid/PaddleCV/ocr_recognition/attention_model.py#L246-L335

**Comment by yeyupiaoling** [comment]
@Xreki 因为我要生成下面tensorflow的row，这个row的维度更batch一样大小，然后跟输入层的label相加，就有了上面的代码。
```
   row = tf.range(num_row) * 2
    indices_ = row + label_int

```

**Comment by yeyupiaoling** [comment]
@Xreki  我把`elementwise_add`换成`sum`就可以通过，但是不知道是否正确，还请老师赐教。
```
    indices_ = fluid.layers.create_array(dtype='int32')
    i = fluid.layers.fill_constant(shape=[1], dtype='int32', value=0)
    one = fluid.layers.fill_constant(shape=[1], dtype='int32', value=1)
    two = fluid.layers.fill_constant(shape=[1], dtype='int32', value=2)
    cond = fluid.layers.less_than(x=i, y=num_row)
    while_op = fluid.layers.While(cond=cond)
    with while_op.block():
        temp1 = fluid.layers.elementwise_mul(i, two)
        indices_ = fluid.layers.concat([indices_, temp1])
        i = fluid.layers.elementwise_add(i, one)
        fluid.layers.less_than(x=i, y=num_row, cond=cond)
    indices_ = fluid.layers.sum([label_int, indices_])
```


我只是想复现tensorflow的以下两行代码而已
```

   row = tf.range(num_row) * 2
    indices_ = row + label_int
```

**Comment by Xreki** [comment]
你期望得到的`indices_`应该是一个tensor，值为`[0 *2 + label_int, 1 * 2 + label_int, 2 * 2 + label_int, ..., (num_row - 1) * 2 + label_int]`，这里你定义的`indices_`为一个tensor_array，我觉得你应该希望使用`tensor_array_to_tensor`将`indices_`转成一个普通的tensor。这里用`sum`应该是不对的，`sum`会对所有的tensor求和，http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#sum 。

用这种组合的方式，即使实现了，效率也会很低，所以建议你可以尝试：
1. merge PR：https://github.com/PaddlePaddle/Paddle/pull/15431 到你的Paddle，从源码编译Paddle，并直接使用range
2. 可以尝试[py_func op](http://paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#py-func) ，在python端实现自定义的op，参考示例：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_py_func_op.py

另外，据说Paddle也定义了`*`和`+`运算符的，可尝试直接使用`*`和`+`。

**Comment by yeyupiaoling** [comment]
@Xreki 感谢老师回答，编译的是`develop`的分支吧。
还有，我现在使用的PaddlePaddle 1.2是不支持`*`和`+`的，我的反正是报错的。

**Comment by Xreki** [comment]
> 编译的是develop的分支吧

你可以拉取develop分支，然后merge #15431 的代码

> 我现在使用的PaddlePaddle 1.2是不支持*和+的，我的反正是报错的。

我确认过，`+`和`*`应该是很早就支持了，请问你是报什么错？

**Comment by yeyupiaoling** [comment]
@Xreki 哈哈，我不知道怎么merge #15431 的代码，develop中还么有合并这个代码。

我发现`fluid.layers.py_func`贼好用，我用这个解决了，不需要用range了。

**Comment by yeyupiaoling** [comment]
@Xreki 还剩下最后一个问题了
```python
# 是否有人脸交叉熵损失函数
def cls_ohem(cls_prob, label):
    # 只把pos的label设定为1,其余都为0
    def my_where1(x):
        zeros, label = x
        label_filter_invalid = np.where(np.less(label, 0), zeros, label)
        return label_filter_invalid

    zeros = fluid.layers.zeros(shape=label.shape, dtype=label.dtype)
    label_filter_invalid = create_tmp_var(name='label_filter_invalid', dtype=label.dtype, shape=label.shape)
    label_filter_invalid = fluid.layers.py_func(func=my_where1, x=[zeros, label], out=label_filter_invalid)

    # 类别size[2*batch]
    num_cls_prob = sum(cls_prob.shape)
    cls_prob_reshpae = fluid.layers.reshape(cls_prob, [-1, num_cls_prob])
    label_int = fluid.layers.cast(label_filter_invalid, dtype='int32')

    # 获取batch数
    num_row = fluid.layers.fill_constant(shape=[1], dtype='int32', value=cls_prob.shape[0])

    # 对应某一batch而言，batch*2为非人类别概率，batch*2+1为人概率类别,indices为对应 cls_prob_reshpae
    # 应该的真实值，后续用交叉熵计算损失
    def my_range(x):
        row = [i * 2 for i in range(x)]
        return row

    row = create_tmp_var(name='row', dtype=label_int.dtype, shape=label_int.shape)
    row = fluid.layers.py_func(func=my_range, x=num_row, out=row)
    indices_ = label_int + row

    # 真实标签对应的概率
    label_prob = fluid.layers.squeeze(fluid.layers.gather(cls_prob_reshpae, indices_), axes=[])
    loss = 0 - fluid.layers.log(label_prob * 1e-10)

    # 统计neg和pos的数量
    def my_where2(x):
        zeros, ones = x
        valid_inds = np.where(label < zeros, zeros, ones)
        return valid_inds

    zeros = fluid.layers.zeros(shape=label_prob.shape, dtype='float32')
    ones = fluid.layers.ones(shape=label_prob.shape, dtype='float32')
    valid_inds = create_tmp_var(name='valid_inds', dtype=zeros.dtype, shape=zeros.shape)
    valid_inds = fluid.layers.py_func(func=my_where2, x=[zeros, ones], out=valid_inds)
    num_valid = fluid.layers.reduce_sum(valid_inds)

    # 选取70%的数据
    num_keep_radio = 0.7
    keep_num = fluid.layers.cast(num_valid * num_keep_radio, dtype='int32')

    # 只选取neg，pos的70%损失
    loss = loss * valid_inds
    loss, _ = fluid.layers.nn.topk(loss, k=keep_num)
    print(loss)
    return fluid.layers.reduce_mean(loss)
```

报错如下：
```
    loss, _ = fluid.layers.nn.topk(loss, k=keep_num)
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layers/nn.py", line 4761, in topk
    attrs=attrs)
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/framework.py", line 727, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected input_dims[input_dims.size() - 1] >= k, but received input_dims[input_dims.size() - 1]:-1 < k:1.
input must have >= k columns at [/paddle/paddle/fluid/operators/top_k_op.cc:38]
PaddlePaddle Call Stacks: 
0       0x7fd7ba00f5edp void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 365
1       0x7fd7ba00f937p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fd7ba198ca7p paddle::operators::TopkOp::InferShape(paddle::framework::InferShapeContext*) const + 1879
3       0x7fd7ba107779p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 841
```

最后一步了，这个问题是什么原因呢？

**Comment by Xreki** [comment]
```
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected input_dims[input_dims.size() - 1] >= k, but received input_dims[input_dims.size() - 1]:-1 < k:1.
input must have >= k columns at [/paddle/paddle/fluid/operators/top_k_op.cc:38]
```

这个错在`topk`里面，`topk` op要求输入tensor的维度一般为：`[batch][num_classes]`，然后会在`num_classes`这个维度上求`topk`，输出的维度为`[batch][k]`，所以要求`num_classes >= k`。

这里你输入的最后一个维度为`-1`，k为`1`，所以不满足。你检查下`loss`的维度吧。

**Comment by yeyupiaoling** [comment]
@Xreki 我大概发现问题了，
tensorflow的代码原本是这样的
```python
    num_cls_prob = tf.size(cls_prob)
    cls_prob_reshpae = tf.reshape(cls_prob, [num_cls_prob, -1])
```

我上面错误的错误做法是
```python
    num_cls_prob = sum(cls_prob.shape)
    cls_prob_reshpae = fluid.layers.reshape(cls_prob, [-1, num_cls_prob])
    label_int = fluid.layers.cast(label_filter_invalid, dtype='int32')
```

我修改成如下方式：
```python
    def my_size(x):
        num_cls_prob = np.size(x)
        return num_cls_prob

    num_cls_prob = create_tmp_var(name='num_cls_prob', dtype='int32', shape=[1])
    num_cls_prob = fluid.layers.py_func(func=my_size, x=cls_prob, out=num_cls_prob)
    cls_prob_reshpae = fluid.layers.reshape(cls_prob, [num_cls_prob, -1])
```

但是报错为
```
Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/train_PNet.py", line 14, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, accuracy, conv4_1, conv4_2, conv4_3 = P_Net()
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 75, in P_Net
    label_cost = cls_ohem(cls_prob=cls_prob, label=label)
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 286, in cls_ohem
    cls_prob_reshpae = fluid.layers.reshape(cls_prob, [num_cls_prob, -1])
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layers/nn.py", line 5979, in reshape
    "Only one dimension in shape can be unknown.")
AssertionError: Only one dimension in shape can be unknown.
```

我想问以下如果获取张量`num_cls_prob`中的第一维度的值呢？

**Comment by yeyupiaoling** [comment]
@Xreki 其实我也想这般处理，但是遇到这个中类型的问题 #16374 ，为什么py_func可变化的输出张量？
```python
    def my_size(x):
        num_cls_prob = np.size(x)
        cls_prob_reshpae = fluid.layers.reshape(x, [num_cls_prob, -1])
        return cls_prob_reshpae

    cls_prob_reshpae = create_tmp_var(name='num_cls_prob', dtype=cls_prob.dtype, shape=cls_prob.dtype)
    cls_prob_reshpae = fluid.layers.py_func(func=my_size, x=cls_prob, out=cls_prob_reshpae)
```

**Comment by yeyupiaoling** [comment]
@Xreki 然后得知py_func中不能有Fluid代码，所需修改成如下：
```python
    def my_size(x):
        num_cls_prob = np.size(x)
        return num_cls_prob

    num_cls_prob = create_tmp_var(name='num_cls_prob', dtype='int32', shape=[1])
    num_cls_prob = fluid.layers.py_func(func=my_size, x=cls_prob, out=num_cls_prob)
    cls_prob_reshpae = fluid.layers.reshape(label_filter_invalid, [num_cls_prob, -1])
    print(cls_prob_reshpae)
```

报错如下：
```
Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/train_PNet.py", line 14, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, accuracy, conv4_1, conv4_2, conv4_3 = P_Net()
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 75, in P_Net
    label_cost = cls_ohem(cls_prob=cls_prob, label=label)
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 282, in cls_ohem
    cls_prob_reshpae = fluid.layers.reshape(num_cls_prob, [num_cls_prob, -1])
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layers/nn.py", line 5979, in reshape
    "Only one dimension in shape can be unknown.")
AssertionError: Only one dimension in shape can be unknown.
```

因为`fluid.layers.reshape`的`shape`需要是整数，上面得到的`num_cls_prob`是一个张量，这个怎么解决？

**Comment by yeyupiaoling** [comment]
@Xreki 工程师姐姐是否可以帮我调试调试呢？直接运行`train_PNet.py`，完整的，包括数据集。万分感谢。

[TestMTCNN.tar.gz](https://github.com/PaddlePaddle/Paddle/files/3001340/TestMTCNN.tar.gz)

**Comment by Xreki** [comment]
#15431 range op已经merge到develop中，可更新Paddle代码试用。

**Comment by yeyupiaoling** [comment]
@Xreki 是的，我发现了，我已编译。谢谢您。
