### ISSUE TITLE
machine_reading_comprehension 模型多机实现pserver模式报错

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#16298]
```bash
Traceback (most recent call last):
  File "dist_machine_reading_comprehension.py", line 151, in <module>
    runtime_main(TestDistMrc)
  File "/home/work/ljh_test/baidu/paddle/test/cts_test.machine_reading/dist_base.py", line 376, in runtime_main
    model.run_trainer(endpoints, trainer_id, trainers, run_params)
  File "/home/work/ljh_test/baidu/paddle/test/cts_test.machine_reading/dist_base.py", line 277, in run_trainer
    return_numpy=False)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 303, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator lookup_table error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 364, in embedding
    'padding_idx': padding_idx
  File "./models_lib/machine_reading_comprehension/rc_model.py", line 83, in embedding
    param_attr=fluid.ParamAttr(name='embedding_para'))
  File "./models_lib/machine_reading_comprehension/rc_model.py", line 282, in rc_model
    q_embs = embedding(q_ids, emb_shape, args)
  File "dist_machine_reading_comprehension.py", line 115, in get_model
    args.hidden_size, vocab, args)
  File "/home/work/ljh_test/baidu/paddle/test/cts_test.machine_reading/dist_base.py", line 154, in run_trainer
    prepare_list = self.get_model()
  File "/home/work/ljh_test/baidu/paddle/test/cts_test.machine_reading/dist_base.py", line 376, in runtime_main
    model.run_trainer(endpoints, trainer_id, trainers, run_params)
  File "dist_machine_reading_comprehension.py", line 151, in <module>
    runtime_main(TestDistMrc)
C++ Callstacks: 
Enforce failed. Expected ids_dims[ids_rank - 1] == 1, but received ids_dims[ids_rank - 1]:0 != 1:1.
The last dimension of the 'Ids' tensor must be 1. at [/paddle/paddle/fluid/operators/lookup_table_op.cc:39]
PaddlePaddle Call Stacks: 
0       0x7f9262a19e2dp void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 365
1       0x7f9262a1a177p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f9262e3d037p paddle::operators::LookupTableOp::InferShape(paddle::framework::InferShapeContext*) const + 1447
3       0x7f926442ab7bp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 603
4       0x7f9264428425p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 341
5       0x7f926429e79ap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
6       0x7f9264297e76p paddle::framework::details::OpHandleBase::Run(bool) + 118
7       0x7f926423008dp
8       0x7f9264230a8dp paddle::framework::details::ThreadedSSAGraphExecutor::RunOp(std::shared_ptr<paddle::framework::BlockingQueue<paddle::framework::details::VarHandleBase*> > const&, paddle::framework::details::OpHandleBase*) + 1309
9       0x7f9264232704p paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 2324
10      0x7f926422978ap paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 394
11      0x7f9262b57c92p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 562
12      0x7f9262a0a28ep
13      0x7f9262a451fep
14            0x4c37edp PyEval_EvalFrameEx + 31165
15            0x4b9ab6p PyEval_EvalCodeEx + 774
16            0x4c16e7p PyEval_EvalFrameEx + 22711
17            0x4b9ab6p PyEval_EvalCodeEx + 774
18            0x4c16e7p PyEval_EvalFrameEx + 22711
19            0x4c136fp PyEval_EvalFrameEx + 21823
20            0x4b9ab6p PyEval_EvalCodeEx + 774
21            0x4eb30fp
22            0x4e5422p PyRun_FileExFlags + 130
23            0x4e3cd6p PyRun_SimpleFileExFlags + 390
24            0x493ae2p Py_Main + 1554
25      0x7f92d01e1830p __libc_start_main + 240
26            0x4933e9p _start + 41
```

**Comment by xuezhong** [comment]
这个代码改过吗

**Comment by ccmeteorljh** [comment]
> 这个代码改过吗
数据feed错了，已经可以跑起来了，关掉这个issue了
