### ISSUE TITLE
softmax_with_cross_entropy报错Tensor holds the wrong type

### ISSUE THREAD

**Issue by nizihan** [PaddlePaddle/Paddle#16308]
fluid 1.3
CUDNN_VERSION=5.1
CUDA_VERSION=8.0

代码内容：
```
    prediction_0 = fluid.layers.cast(prediction_0, 'float64')
    last_h_0 = fluid.layers.sequence_last_step(h_0)
    label_out = fluid.layers.cast(x=label_out, dtype='int64')
    label_out_onehot = fluid.layers.one_hot(input=label_out, depth=args.num_classes_0 + 2)
    smooth_label_out_onehot = fluid.layers.label_smooth(label=label_out_onehot, epsilon=0.1, dtype="float64")                                                                                                      
    #cost_0 = fluid.layers.cross_entropy(input=prediction_0, label=smooth_label_out_onehot, soft_label=True)
    cost_0 = fluid.layers.softmax_with_cross_entropy(logits=prediction_0, label=smooth_label_out_onehot, soft_label=True, numeric_stable_mode=True)
```
其中：

1553050837      smooth_label_out_onehot Tensor[label_smooth_0.tmp_0]
        shape: [13,92,]
        dtype: f
        LoD: [[ 0,13, ]]
        data: 0.00108696,0.00108696,0.00108696,0.901087,0.00108696,0.00108696,0.00108696,0.00108696,0.00108696,0.00108696,
1553050837      prediction_0    Tensor[cast_6.tmp_0]
        shape: [13,92,]
        dtype: d
        LoD: [[ 0,13, ]]
        data: 0.415811,-0.0547745,0.415684,6.82353,0.0195829,-0.0889864,-0.109916,-0.211977,-0.0444689,-0.267735,

报错内容：

```
Traceback (most recent call last):
  File "train_fupan_momentum_64.py", line 515, in <module>
    train(args)
  File "train_fupan_momentum_64.py", line 186, in train
    return_numpy=False)
  File "python2.7/site-packages/paddle/fluid/parallel_executor.py", line 303, in run
    self.executor.run(fetch_list, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator softmax_with_cross_entropy error.
Python Callstacks: 
  File "python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 5759, in softmax_with_cross_entropy
    'numeric_stable_mode': numeric_stable_mode
  File "train_fupan_momentum_64.py", line 342, in spatial_attention_train
    cost_0 = fluid.layers.softmax_with_cross_entropy(logits=prediction_0, label=smooth_label_out_onehot, soft_label=True, numeric_stable_mode=True)
  File "train_fupan_momentum_64.py", line 86, in train
    = spatial_attention_train(args)
  File "train_fupan_momentum_64.py", line 515, in <module>
    train(args)
C++ Callstacks: 
Tensor holds the wrong type, it holds float at [/paddle/paddle/fluid/framework/tensor_impl.h:29]
PaddlePaddle Call Stacks: 
0       0x7f6f81175f15p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 357
1       0x7f6f81176299p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f6f8117d392p double const* paddle::framework::Tensor::data<double>() const + 194
3       0x7f6f81aa69a2p paddle::operators::SoftmaxWithCrossEntropyCUDAKernel<double>::Compute(paddle::framework::ExecutionContext const&) const + 1298
4       0x7f6f81aa9b83p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 2ul, paddle::operators::SoftmaxWithCrossEntropyCUDAKernel<float>, paddle::operators::SoftmaxWithCrossEntropyCUDAKernel<paddle::platform::float16>, paddle::operators::SoftmaxWithCrossEntropyCUDAKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7f6f82c69d43p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 659
6       0x7f6f82c675b5p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 341
7       0x7f6f82add92ap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
8       0x7f6f82ad7006p paddle::framework::details::OpHandleBase::Run(bool) + 118
9       0x7f6f82a6f21dp
10      0x7f6f81d8c643p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
11      0x7f6f81d4f967p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
12      0x7f6fefb0f973p pthread_once + 83
13      0x7f6f82a6df02p
14      0x7f6f81d50d94p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
15      0x7f6f9d37e8a0p
16      0x7f6fefb0a1c3p
17      0x7f6fef13212dp clone + 109
```

**Comment by shippingwang** [comment]
测试了一下 可以使用float64 

- [x]  已解决， 用户将one hot输出cast 64

**Comment by nizihan** [comment]
谢谢，问题解决了，label_smooth的输出类型好像只与输入类型有关，所以将fluid.layers.one_hot的输出cast成float64，再送入到label_smooth中就能得到float64的结果，softmax_with_cross_entropy接收到两个float64类型的数据，可以正常运行。
