### ISSUE TITLE
save_inference_model 报错 

### ISSUE THREAD

**Issue by djh123** [PaddlePaddle/Paddle#16336]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号（如1.1）或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本（如Mac OS 10.14），Python版本
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that th
If there is no solution,please make sure that this is an inference issue including the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Cmake orders
-C++version.txt
-API information
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by djh123** [comment]
save models to ./checkpoints/model_1
['read_file_0.tmp_0', 'read_file_0.tmp_2', 'read_file_0.tmp_1', 'read_file_0.tmp_3', 'read_file_0.tmp_5']
Traceback (most recent call last):
  File "run_classifier.py", line 290, in <module>
    main(args)
  File "run_classifier.py", line 237, in main
    fluid.io.save_inference_model(model_path, feed_targets_name, [probs], exe)
  File "/data0/home/djh/.local/lib/python3.6/site-packages/paddle/fluid/io.py", line 953, in save_inference_model
    var1 = layers.scale(var, 1.)
  File "/data0/home/djh/.local/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 8793, in scale
    'bias_after_scale': bias_after_scale
  File "/data0/home/djh/.local/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/data0/home/djh/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/data0/home/djh/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 726, in __init__
    self.desc.infer_var_type(self.block.desc)
paddle.fluid.core.EnforceNotMet:  at [/paddle/paddle/fluid/operators/detail/safe_ref.h:28]
PaddlePaddle Call Stacks: 
0       0x7f21967ef8d5p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 357
1       0x7f21967efc59p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f21970579dfp paddle::operators::ScaleOpVarTypeInference::operator()(paddle::framework::OpDesc const&, paddle::framework::BlockDesc*) const + 431
3       0x7f2197057ac3p std::_Function_handler<void (paddle::framework::OpDesc const&, paddle::framework::BlockDesc*), paddle::framework::details::OpInfoFiller<paddle::operators::ScaleOpVarTypeInference, (paddle::framework::details::OpInfoFillType)3>::operator()(char const*, paddle::framework::OpInfo*) const::{lambda(paddle::framework::OpDesc const&, paddle::framework::BlockDesc*)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::OpDesc const&, paddle::framework::BlockDesc*) + 35
4       0x7f21968f1642p paddle::framework::OpDesc::InferVarType(paddle::framework::BlockDesc*) const + 98
5       0x7f2196865713p
6       0x7f219681ac9ep
7       0x55643953b744p _PyCFunction_FastCallDict + 340
8       0x5564395c257ep
9       0x5564395e738ap _PyEval_EvalFrameDefault + 778
10      0x5564395bb8e4p
11      0x5564395bce6ap _PyFunction_FastCallDict + 986
12      0x55643953bb0fp _PyObject_FastCallDict + 623
13      0x5564395406a3p _PyObject_Call_Prepend + 99
14      0x55643953b54ep PyObject_Call + 62
15      0x5564395950fbp
16      0x5564395c2767p
17      0x55643953b92bp _PyObject_FastCallDict + 139
18      0x5564395bca5ap _PyObject_FastCallKeywords + 170
19      0x5564395c257ep
20      0x5564395e8147p _PyEval_EvalFrameDefault + 4295
21      0x5564395bb8e4p
22      0x5564395bce6ap _PyFunction_FastCallDict + 986
23      0x55643953bb0fp _PyObject_FastCallDict + 623
24      0x5564395406a3p _PyObject_Call_Prepend + 99
25      0x55643953b54ep PyObject_Call + 62
26      0x5564395e8a6cp _PyEval_EvalFrameDefault + 6636
27      0x5564395bb8e4p
28      0x5564395bc771p
29      0x5564395c2505p
30      0x5564395e8147p _PyEval_EvalFrameDefault + 4295
31      0x5564395bb8e4p
32      0x5564395bc771p
33      0x5564395c2505p
34      0x5564395e738ap _PyEval_EvalFrameDefault + 778
35      0x5564395bb8e4p
36      0x5564395bc771p
37      0x5564395c2505p
38      0x5564395e738ap _PyEval_EvalFrameDefault + 778
39      0x5564395bc53bp
40      0x5564395c2505p
41      0x5564395e738ap _PyEval_EvalFrameDefault + 778
42      0x5564395bd289p PyEval_EvalCodeEx + 809
43      0x5564395be01cp PyEval_EvalCode + 28
44      0x5564396403c4p
45      0x5564396407c1p PyRun_FileExFlags + 161
46      0x5564396409c3p PyRun_SimpleFileExFlags + 451
47      0x5564396444b3p Py_Main + 1555
48      0x55643950d02ep main + 238
49      0x7f21dc4ed830p __libc_start_main + 240
50      0x5564395ede0ep

**Comment by djh123** [comment]
当我制定main_program，可以了，尴尬
