### ISSUE TITLE
py_func接口当遇到输出值维度会变化的如何处理

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16374]
# 环境
 - PaddlePaddle
 - Ubuntu 16.04
 - Python 3.5

# 问题
例如下面的代码，输出的cond的的可变的[2, ?]这种情况怎么处理？
```python
    def my_where(x):
        cond = np.where(np.greater_equal(x, 0))
        return cond

    cond = create_tmp_var(name='cond', dtype=label_int.dtype, shape=label_int.shape)
    cond = fluid.layers.py_func(func=my_where, x=label_int, out=cond)
    picked = fluid.layers.squeeze(cond, axes=[])
```

**Comment by hjchen2** [comment]
输出shape支持可变的，会自动推断网络后续变量的shape

**Comment by yeyupiaoling** [comment]
@hjchen2 不行啊，像这种就不行了。下面的作用是把`[-1, 2]`，转换成`[-1, 1]`，比如在实际情况下把`[32, 2]`转换为`[64, 1]`。代码如下：
```python
    def my_size(x):
        num_cls_prob = np.size(x)
        cls_prob_reshpae = fluid.layers.reshape(x, [num_cls_prob, -1])
        return cls_prob_reshpae

    cls_prob_reshpae = create_tmp_var(name='num_cls_prob', dtype=cls_prob.dtype, shape=cls_prob.shape)
    cls_prob_reshpae = fluid.layers.py_func(func=my_size, x=cls_prob, out=cls_prob_reshpae)
    print(cls_prob_reshpae)
```

这种情况不是断掉后续的问题了，而是整个shape都变化了。

**Comment by hjchen2** [comment]
@yeyupiaoling 因为python function是在executor运行时执行的，所以在python function中只能写纯python的代码，不要调用fluid的接口。另外直接print cls_prob_reshpae是不对的，需要执行时python function才会被执行

**Comment by yeyupiaoling** [comment]
@hjchen2 我修改成这样下面就跑不了了。因为`fluid.layers.reshape`的shape需要一个整数输入。
```python
    def my_size(x):
        num_cls_prob = np.size(x)
        return num_cls_prob

    num_cls_prob = create_tmp_var(name='num_cls_prob', dtype='int32', shape=[1])
    num_cls_prob = fluid.layers.py_func(func=my_size, x=cls_prob, out=num_cls_prob)
    cls_prob_reshpae = fluid.layers.reshape(num_cls_prob, [num_cls_prob, -1])
    print(cls_prob_reshpae)
```

错误信息：
```
Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/train_PNet.py", line 14, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, accuracy, conv4_1, conv4_2, conv4_3 = P_Net()
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 75, in P_Net
    label_cost = cls_ohem(cls_prob=cls_prob, label=label)
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 282, in cls_ohem
    cls_prob_reshpae = fluid.layers.reshape(num_cls_prob, [num_cls_prob, -1])
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layers/nn.py", line 5979, in reshape
    "Only one dimension in shape can be unknown.")
AssertionError: Only one dimension in shape can be unknown.
```

**Comment by hjchen2** [comment]
> @hjchen2 不行啊，像这种就不行了。下面的作用是把`[-1, 2]`，转换成`[-1, 1]`，比如在实际情况下把`[32, 2]`转换为`[64, 1]`。代码如下：
> 
> ```python
>     def my_size(x):
>         num_cls_prob = np.size(x)
>         cls_prob_reshpae = fluid.layers.reshape(x, [num_cls_prob, -1])
>         return cls_prob_reshpae
> 
>     cls_prob_reshpae = create_tmp_var(name='num_cls_prob', dtype=cls_prob.dtype, shape=cls_prob.shape)
>     cls_prob_reshpae = fluid.layers.py_func(func=my_size, x=cls_prob, out=cls_prob_reshpae)
>     print(cls_prob_reshpae)
> ```
> 
> 这种情况不是断掉后续的问题了，而是整个shape都变化了。

改成下面这样试试呢
```python
def my_size(x):
        num_cls_prob = np.size(np.array(x))
        cls_prob_reshpae = np.reshape(np.array(x), [num_cls_prob, -1])
        return cls_prob_reshpae

    cls_prob_reshpae = create_tmp_var(name='num_cls_prob', dtype=cls_prob.dtype, shape=cls_prob.shape)
    cls_prob_reshpae = fluid.layers.py_func(func=my_size, x=cls_prob, out=cls_prob_reshpae)
    print(cls_prob_reshpae)
```

**Comment by yeyupiaoling** [comment]
@hjchen2 这样就得不到预期的维度了，如:
```python
    def my_size(x):
        num_cls_prob = np.size(x)
        cls_prob_reshpae = np.reshape(x, [num_cls_prob, -1])
        return cls_prob_reshpae

    cls_prob_reshpae = create_tmp_var(name='cls_prob_reshpae', dtype=cls_prob.dtype, shape=cls_prob.shape)
    cls_prob_reshpae = fluid.layers.py_func(func=my_size, x=cls_prob, out=cls_prob_reshpae)
```

得到的是
```
name: "cls_prob_reshpae"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 2
    }
  }
}
```

**Comment by hjchen2** [comment]
需要executor执行起来，py function才会被执行

**Comment by yeyupiaoling** [comment]
@hjchen2 但是输入的`cls_prob.shape`是`[-1, 2]`，输出预期得到的是`[-1 * 2， 1]`，py_func不是根据指定的类型和shape输出的吗? 难道执行exe就会改变吗?更现在的输出不同吗?

**Comment by hjchen2** [comment]
@yeyupiaoling 根据文档的意思是需要先指定输出的shape和数据类型，http://www.paddlepaddle.org/documentation/docs/zh/1.3/api_cn/layers_cn.html#py-func。如果是变长的话，你可以创建一个预期shape和data type的lod tensor作为输出，比如
```python
    cls_prob_reshpae = create_tmp_var(name='cls_prob_reshpae', dtype=cls_prob.dtype, shape=[-1, 1])
    cls_prob_reshpae = fluid.layers.py_func(func=my_size, x=cls_prob, out=cls_prob_reshpae)
```

**Comment by hjchen2** [comment]
根据py_func文档的解释，在使用这个接口时是需要指定输出的shape和data type的，但不意味着这个函数在构建模型时就已经被执行。如果你只是希望将可变长shape从[-1, 2]变成[-1, 1]，你可以这么试试，
```python
import paddle.fluid as fluid
import numpy as np

def create_tmp_var(name, dtype, shape):
       return fluid.default_main_program().current_block().create_var(
           name=name, dtype=dtype, shape=shape)

def my_size(x):
        num_cls_prob = np.size(np.array(x))
        cls_prob_reshpae = np.reshape(np.array(x), [num_cls_prob, -1])
        return cls_prob_reshpae

cls_prob = create_tmp_var(name='num_cls', dtype='int64', shape=[-1, 2])
cls_prob_reshpae = create_tmp_var(name='num_cls_prob', dtype='int64', shape=[-1, 1])
cls_prob_reshpae = fluid.layers.py_func(func=my_size, x=cls_prob, out=cls_prob_reshpae)
print(cls_prob_reshpae)
```
这样print的cls_prob_reshpae如下：
```shell
name: "num_cls_prob"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT64
      dims: -1
      dims: 1
    }
  }
}
```

**Comment by yeyupiaoling** [comment]
@hjchen2 实际的问题是 把`cls_prob`，也就是网络输出的值，转换成batch大小为`cls_prob`维度的总大小`num_cls_prob`，剩下的在后面自动展开。也不仅仅是shape从[-1, 2]变成[-1, 1]，不过从实际情况下来看，第二个维度的确是2。
```python
    def my_size(x):
        num_cls_prob = np.size(x)
        cls_prob_reshpae = np.reshape(x, [num_cls_prob, -1])
        return cls_prob_reshpae

    cls_prob_reshpae = create_tmp_var(name='cls_prob_reshpae', dtype=cls_prob.dtype, shape=cls_prob.shape)
    cls_prob_reshpae = fluid.layers.py_func(func=my_size, x=cls_prob, out=cls_prob_reshpae)
```


如果输出的`cls_prob_reshpae`是可变的，那就好办了。

**Comment by hjchen2** [comment]
@yeyupiaoling 这个例子中，我是指定了cls_prob的维度是[-1, 2]，其实如果你的网络输出是其他的维度，我觉得也没问题，你只需要指定py_func的输出shape就行。

**Comment by yeyupiaoling** [comment]
@hjchen2 
>你只需要指定py_func的输出shape就行。

关键就是这个，我本来就是需要通过`np.size(x)`获取维度大小的。
