### ISSUE TITLE
请教zeros接口的使用问题?

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16404]
# 环境
 - PaddlePaddle 1.3
 - Ubuntu 16.04
 - Python 3.5

# 问题
我想用PaddlePaddle复写下面tensorflow的代码:
```
 zeros = tf.zeros_like(label)
```

我写的PaddlePaddle代码:
```
zeros = fluid.layers.zeros(shape=label.shape, dtype=label.dtype)
```

报错如下:
```
paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.


C++ Callstacks: 
Enforce failed. Expected numel() >= 0, but received numel():-1 < 0:0.
When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::Resize has been called first. at [/paddle/paddle/fluid/framework/tensor.cc:44]
PaddlePaddle Call Stacks: 

```

**Comment by junjun315** [comment]
报错信息里看到的是 Invoke operator fill_constant error. 应该是在fill_constant的输入检查时错了，往后的代码有用到这个么？

**Comment by junjun315** [comment]
检查一下label.shape? 看看是否满足fill_constant的输入。本质上zeros op是调用value=0.0的fill_constant op

**Comment by yeyupiaoling** [comment]
@junjun315 label的定义如下:
```
label = fluid.layers.data(name='label', shape=[1], dtype='float32')
```

唯一变的应该是batch size了

**Comment by yeyupiaoling** [comment]
@junjun315   我使用代码：
```python
# 是否有人脸交叉熵损失函数
def cls_ohem(cls_prob, label):
    # 只把pos的label设定为1,其余都为0
    def my_where1(x):
        zeros, label = x
        label_filter_invalid = np.where(np.less(label, 0), zeros, label)
        return label_filter_invalid

    zeros = fluid.layers.zeros(shape=label.shape, dtype=label.dtype)
    label_filter_invalid = create_tmp_var(name='label_filter_invalid', dtype=label.dtype, shape=label.shape)
    label_filter_invalid = fluid.layers.py_func(func=my_where1, x=[zeros, label], out=label_filter_invalid)
```


全部的报错信息:
```
Traceback (most recent call last):
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/train_PNet.py", line 47, in <module>
    fetch_list=[avg_total_loss, accuracy, learning_rate])
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/executor.py", line 591, in _run
    exe.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks: 
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layers/tensor.py", line 386, in fill_constant
    stop_gradient=True)
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layers/tensor.py", line 606, in zeros
    return fill_constant(value=0.0, **locals())
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 268, in cls_ohem
    zeros = fluid.layers.zeros(shape=label.shape, dtype=label.dtype)
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/model.py", line 75, in P_Net
    label_cost = cls_ohem(cls_prob=cls_prob, label=label)
  File "/media/test/5C283BCA283BA1C6/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train_PNet/train_PNet.py", line 14, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, accuracy, conv4_1, conv4_2, conv4_3 = P_Net()
C++ Callstacks: 
Enforce failed. Expected numel() >= 0, but received numel():-1 < 0:0.
When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::Resize has been called first. at [/paddle/paddle/fluid/framework/tensor.cc:44]
PaddlePaddle Call Stacks: 

```

**Comment by junjun315** [comment]
能否在zeros op调用前把label.shape打印出来？或者如果是公共的数据集的话，代码发到我们支持邮箱里。 可能是在某一步操作时丢失了shape信息，导致其中一个环节进行输入reshape时触发检查不满足

**Comment by yeyupiaoling** [comment]
@junjun315  以下就是我的代码和数据集，数据集只是获取一小部分，所以非常小。您直接运行`train_PNet.py`即可。谢谢。

**Comment by junjun315** [comment]
@yeyupiaoling 看了一下你的程序，貌似是reader读入的数据有问题？ label应该是一个数组标签，而实际拿到的值是一个数字？
`....[0.6431373 , 0.61960787, 0.59607846, 0.5921569 , 0.5568628 ,
         0.49019608, 0.5058824 , 0.58431375, 0.58431375, 0.6627451 ,
         0.52156866, 0.31764707]]], dtype=float32), 1, [-0.03, -0.15, -0.15, 0.19], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]`

**Comment by yeyupiaoling** [comment]
@junjun315 我修改了一下，`    label = [int(sample[1])]`。输出如下：
```
        0.76862746, 0.7058824 ],
        [0.7882353 , 0.7882353 , 0.7921569 , 0.7882353 , 0.81960785,
         0.83137256, 0.77254903, 0.69411767, 0.57254905, 0.5411765 ,
         0.5372549 , 0.5019608 ],
        [0.75686276, 0.76862746, 0.76862746, 0.7529412 , 0.79607844,
         0.79607844, 0.7019608 , 0.60784316, 0.61960787, 0.5882353 ,
         0.53333336, 0.49803922]]], dtype=float32), [1], [0.03, 0.01, 0.01, 0.5], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]
```

但是还是有错误呢。


报错是：
```
Traceback (most recent call last):
  File "D:/yeyupiaoling/PyCharm/TestMTCNN/train/train_PNet.py", line 48, in <module>
    fetch_list=[avg_total_loss, accuracy, learning_rate])
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\executor.py", line 591, in _run
    exe.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks: 
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\framework.py", line 1317, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\layer_helper.py", line 56, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\layers\tensor.py", line 386, in fill_constant
    stop_gradient=True)
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\layers\tensor.py", line 606, in zeros
    return fill_constant(value=0.0, **locals())
  File "D:\yeyupiaoling\PyCharm\TestMTCNN\train\model.py", line 267, in cls_ohem
    zeros = fluid.layers.zeros(shape=label.shape, dtype=label.dtype)
  File "D:\yeyupiaoling\PyCharm\TestMTCNN\train\model.py", line 75, in P_Net
    label_cost = cls_ohem(cls_prob=cls_prob, label=label)
  File "D:/yeyupiaoling/PyCharm/TestMTCNN/train/train_PNet.py", line 14, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, accuracy, conv4_1, conv4_2, conv4_3 = P_Net()
C++ Callstacks: 
Enforce failed. Expected numel() >= 0, but received numel():-1 < 0:0.
When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::Resize has been called first. at [D:\1.3.1\paddle\paddle\fluid\framework\tensor.cc:44]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.

Process finished with exit code 1

```

**Comment by junjun315** [comment]
@yeyupiaoling 你好，很抱歉因为一些事情耽搁了排错。 我看了一下整个模型结构，里面`zeros`的使用可能有一些误区。zero op中输入的`shape`期望得到的是一个常量，而非attribute中的属性，这会导致它不能正常获取。满足你需求的或许是使用 `fluid.layers.fill_constant_batch_size_like(input=label, shape=[-1, 1], value=0, dtype="float32")` 能满足你的需要。

 此外，由于运行图的特性，类似你代码里实现的python方法中，根据传入的label获取label.shape一类的操作也应该工作不正常。如果shape可以预见，尝试使用常量代替。 

总之，看了一下您整个模型结构，是一个很复杂的结构，了不起的工作！我修改了一下zeros的使用。报了`Process finished with exit code 3 `, 可能是在某处存在其他问题。

**Comment by yeyupiaoling** [comment]
@junjun315 我根据您的建议我再修改一下。

**Comment by yeyupiaoling** [comment]
@junjun315 非常感谢您的回答，我全部的ones和zeros都是用`fill_constant_batch_size_like`了，目前没有在这个地方报错了，出现的其他错误，我再另起issue。
