### ISSUE TITLE
py_func execute twice occurs an error

### ISSUE THREAD

**Issue by alexqdh** [PaddlePaddle/Paddle#16416]
环境:
python 2.7
paddle 1.3

下面的代码连续执行两遍的时候就报错，测试py_func的功能
```
def py_func_binomial(input):
    """
        Binormial python function definition
    """
    input_array = np.array(input)
    print(input_array)
    input_len = input_array.shape
    sample = np.random.binomial(1, 0.5, size=input_len)
    ret = sample + input_array
    return ret

def test_debug():
    """
        If execute the function twice, it occurs an error
    """
    a = fluid.layers.data(name="a", shape=[1], dtype='float32')
    binomial_ret_var = create_tmp_var(name='binomial_result_var',
                dtype=a.dtype, shape=a.shape)
    hidden = fluid.layers.py_func(func=py_func_binomial, x=a,
                out=binomial_ret_var, backward_func=None,
                skip_vars_in_backward_input=None)
    x = np.zeros(10000)
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    outs = exe.run(
            feed={'a':x},
            fetch_list=[binomial_ret_var.name])
    print(outs)
    print(np.sum(outs[0]))

    b = fluid.layers.data(name="b", shape=[1], dtype='float32')
    multinomial_ret_var = create_tmp_var(name='multinomial_ret_var',
                dtype=b.dtype, shape=b.shape)
    hidden2 = fluid.layers.py_func(func=py_func_binomial, x=b,
                out=multinomial_ret_var, backward_func=None,
                skip_vars_in_backward_input=None)
    x = np.zeros(10000)
    place1 = fluid.CPUPlace()
    exe1 = fluid.Executor(place1)
    outs1 = exe1.run(
            feed={'b':x},
            fetch_list=[multinomial_ret_var.name])
    print(outs1)
    print(np.sum(outs1[0]))
```

报错信息:

```
Traceback (most recent call last):
  File "test_py_func.py", line 98, in <module>
    test_debug() #Wrong
  File "test_py_func.py", line 57, in test_debug
    fetch_list=[binomial_ret_var.name])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 525, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 591, in _run
    exe.run(program.desc, scope, 0, True, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 9970, in __call__
    func_ret = self._func(*args[idx:], **kwargs)
  File "test_py_func.py", line 31, in py_func_multinomial
    ret = sample + input_array
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

**Comment by hjchen2** [comment]
@alexqdh 欢迎使用paddlepaddle！

其实你可以用一个executor执行整个网络的，我稍微改了一下你的代码，是没问题的。
```python
import paddle.fluid as fluid
import numpy as np

def create_tmp_var(name, dtype, shape):
       return fluid.default_main_program().current_block().create_var(
           name=name, dtype=dtype, shape=shape)

def py_func_binomial(input):
    """
        Binormial python function definition
    """
    input_array = np.array(input)
    print(input_array)
    input_len = input_array.shape
    sample = np.random.binomial(1, 0.5, size=input_len)
    ret = sample + input_array
    return ret

def test_debug():
    """
        If execute the function twice, it occurs an error
    """
    a = fluid.layers.data(name="a", shape=[1], dtype='float32')
    binomial_ret_var = create_tmp_var(name='binomial_result_var',
                dtype=a.dtype, shape=a.shape)
    hidden = fluid.layers.py_func(func=py_func_binomial, x=a,
                out=binomial_ret_var, backward_func=None,
                skip_vars_in_backward_input=None)

    b = fluid.layers.data(name="b", shape=[1], dtype='float32')
    multinomial_ret_var = create_tmp_var(name='multinomial_ret_var',
                dtype=b.dtype, shape=b.shape)
    hidden2 = fluid.layers.py_func(func=py_func_binomial, x=b,
                out=multinomial_ret_var, backward_func=None,
                skip_vars_in_backward_input=None)

    x = np.zeros(10000)
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    binomial_ret, multinomial_ret = exe.run(
            feed={'a':x, 'b':x},
            fetch_list=[binomial_ret_var.name, multinomial_ret_var.name])
    print(binomial_ret)
    print(np.sum(binomial_ret))
    print(multinomial_ret)
    print(np.sum(multinomial_ret))

test_debug()
```

paddle在构建图的时候，会把python中所有的layer都加到default program中，因此在执行第二个executor时a是没有指定输入的，所以执行时在py_func_binomial中报错input_array是NoneType。有三种方法可以避免这个问题：
1、在定义program时使用program_guard，将hidden和hidden2定义到不同的program中，两个executor分别执行两个program。
2、将hidden和hidden2定义到一个program中，只使用一个executor执行，指定a和b两个输入
3、什么都不改，在第二个executor中同时指定a输入。与2用法类似。
