### ISSUE TITLE
 Cannot get attribute mean by type float

### ISSUE THREAD

**Issue by LeLiu** [PaddlePaddle/Paddle#16426]
PaddlePaddle版本： paddlepaddle-gpu 1.3.0.post97

```python
 def fc_block(input, size, drop_prob, name):
     w_init = fluid.initializer.NormalInitializer(0,0, 2e-1)
     b_init = fluid.initializer.NormalInitializer(0.5, 1e-2)
     w_regular = fluid.regularizer.L2DecayRegularizer(0.1)
     b_regular = fluid.regularizer.L2DecayRegularizer(0.1)
     w_attr = fluid.ParamAttr(name+'_w', w_init, regularizer=w_regular)
     b_attr = fluid.ParamAttr(name+'_b', b_init, regularizer=b_regular)

     w_attr = fluid.ParamAttr(name+'_w', w_init)
     b_attr = fluid.ParamAttr(name+'_b', b_init)

     fc = fluid.layers.fc(input, size, act='relu', name=name+'_fc')
     #fc = fluid.layers.fc(input, size, param_attr=w_attr, bias_attr=b_attr, act='relu', name=name+'_fc')
     out = fluid.layers.dropout(fc, drop_prob, name=name+'_dropout')
     return out
```
使用`fc = fluid.layers.fc(input, size, act='relu', name=name+'_fc')`没有问题，使用` fc = fluid.layers.fc(input, size, param_attr=w_attr, bias_attr=b_attr, act='relu', name=name+'_fc')`会报错：
```
train network ...
W0325 11:13:56.417274 17074 device_context.cc:263] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.1, Runtime API Version: 9.0
W0325 11:13:56.417320 17074 device_context.cc:271] device: 0, cuDNN Version: 7.0.
W0325 11:13:56.417345 17074 device_context.cc:295] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.3, but CUDNN version in your machine is 7.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    main(sys.argv)
  File "train.py", line 104, in main
    train()
  File "train.py", line 72, in train
    predict, loss, acc = train_program()
  File "train.py", line 41, in train_program
    predict = network.siamese_net()
  File "/nfs/data/raid0/user/liule/spoof/script/network.py", line 57, in siamese_net
    embeding_a = sub_net(input_a)
  File "/nfs/data/raid0/user/liule/spoof/script/network.py", line 50, in sub_net
    fc1 = fc_block(flatten, 2048, 0.7, 'fc1')
  File "/nfs/data/raid0/user/liule/spoof/script/network.py", line 27, in fc_block
    fc = fluid.layers.fc(input, size, param_attr=w_attr, bias_attr=b_attr, act='relu', name=name+'_fc')
  File "/nfs/user/liule/opt/anaconda3/envs/paddle-gpu/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 276, in fc
    attr=param_attr, shape=param_shape, dtype=dtype, is_bias=False)
  File "/nfs/user/liule/opt/anaconda3/envs/paddle-gpu/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 339, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/nfs/user/liule/opt/anaconda3/envs/paddle-gpu/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1300, in create_parameter
    initializer(param, self)
  File "/nfs/user/liule/opt/anaconda3/envs/paddle-gpu/lib/python3.6/site-packages/paddle/fluid/initializer.py", line 316, in __call__
    stop_gradient=True)
  File "/nfs/user/liule/opt/anaconda3/envs/paddle-gpu/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1382, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/nfs/user/liule/opt/anaconda3/envs/paddle-gpu/lib/python3.6/site-packages/paddle/fluid/framework.py", line 723, in __init__
    self.desc.check_attrs()
paddle.fluid.core.EnforceNotMet: Cannot get attribute mean by type float, its type is int at [/paddle/paddle/fluid/framework/attribute.h:42]
PaddlePaddle Call Stacks:
0       0x7f3edf57ee0dp void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 365
1       0x7f3edf57f157p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f3edf747822p paddle::framework::ExtractAttribute<float>::operator()(boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>&) const + 370
3       0x7f3edf74c062p std::_Function_handler<void (std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*), paddle::framework::TypedAttrChecker<float> >::_M_invoke(std::_Any_data const&, std::unordered_map<std::string, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >*) + 178
4       0x7f3edf680d68p paddle::framework::OpDesc::CheckAttrs() + 168
5       0x7f3edf5f50cfp
6       0x7f3edf5a9c9ep
7       0x7f3f369e0302p _PyCFunction_FastCallDict + 258
8       0x7f3f36a6595bp
9       0x7f3f36a68d40p _PyEval_EvalFrameDefault + 11328
10      0x7f3f36a64100p
11      0x7f3f36a6439cp _PyFunction_FastCallDict + 268
12      0x7f3f36988ce6p _PyObject_FastCallDict + 358
13      0x7f3f36988f3cp _PyObject_Call_Prepend + 204
14      0x7f3f36988fd6p PyObject_Call + 86
15      0x7f3f36a01ad3p
16      0x7f3f369f72acp
17      0x7f3f36988c1ep _PyObject_FastCallDict + 158
18      0x7f3f36988dd8p _PyObject_FastCallKeywords + 168
19      0x7f3f36a6595bp
20      0x7f3f36a692ccp _PyEval_EvalFrameDefault + 12748
21      0x7f3f36a64100p
22      0x7f3f36a65b2ap
23      0x7f3f36a692ccp _PyEval_EvalFrameDefault + 12748
24      0x7f3f36a63514p
25      0x7f3f36a64515p _PyFunction_FastCallDict + 645
26      0x7f3f36988ce6p _PyObject_FastCallDict + 358
27      0x7f3f36988f3cp _PyObject_Call_Prepend + 204
28      0x7f3f36988fd6p PyObject_Call + 86
29      0x7f3f36a0144fp
30      0x7f3f36988c1ep _PyObject_FastCallDict + 158
31      0x7f3f36a6595bp
32      0x7f3f36a68d40p _PyEval_EvalFrameDefault + 11328
33      0x7f3f36a64100p
34      0x7f3f36a6439cp _PyFunction_FastCallDict + 268
35      0x7f3f36988ce6p _PyObject_FastCallDict + 358
36      0x7f3f36988f3cp _PyObject_Call_Prepend + 204
37      0x7f3f36988fd6p PyObject_Call + 86
38      0x7f3f36a69fc9p _PyEval_EvalFrameDefault + 16073
39      0x7f3f36a64100p
40      0x7f3f36a65b2ap
41      0x7f3f36a692ccp _PyEval_EvalFrameDefault + 12748
42      0x7f3f36a64100p
43      0x7f3f36a65b2ap
44      0x7f3f36a692ccp _PyEval_EvalFrameDefault + 12748
45      0x7f3f36a63514p
46      0x7f3f36a65c88p
47      0x7f3f36a68d40p _PyEval_EvalFrameDefault + 11328
48      0x7f3f36a63514p
49      0x7f3f36a65c88p
50      0x7f3f36a68d40p _PyEval_EvalFrameDefault + 11328
51      0x7f3f36a63514p
52      0x7f3f36a65c88p
53      0x7f3f36a68d40p _PyEval_EvalFrameDefault + 11328
54      0x7f3f36a63514p
55      0x7f3f36a65c88p
56      0x7f3f36a68d40p _PyEval_EvalFrameDefault + 11328
57      0x7f3f36a63514p
58      0x7f3f36a65c88p
59      0x7f3f36a68d40p _PyEval_EvalFrameDefault + 11328
60      0x7f3f36a63514p
61      0x7f3f36a65c88p
62      0x7f3f36a68d40p _PyEval_EvalFrameDefault + 11328
63      0x7f3f36a64100p
64      0x7f3f36a64583p PyEval_EvalCodeEx + 99
65      0x7f3f36a645cbp PyEval_EvalCode + 59
66      0x7f3f36a96ee0p PyRun_FileExFlags + 304
67      0x7f3f36a984a3p PyRun_SimpleFileExFlags + 371
68      0x7f3f36ab38d5p Py_Main + 3621
69            0x400c1dp main + 365
70      0x7f3f35a4ec05p __libc_start_main + 245
71            0x4009e9p
```

**Comment by LeLiu** [comment]
mean的类型是什么时候变成了int？

**Comment by qingqing01** [comment]
>      w_init = fluid.initializer.NormalInitializer(0,0, 2e-1)

这里应该是0.0，不是0,0: 

```python
w_init = fluid.initializer.NormalInitializer(0.0, 2e-1)
```

**Comment by LeLiu** [comment]
嗯嗯，多谢。看来是要写上参数名。

**Comment by LeLiu** [comment]
> > ```
> >  w_init = fluid.initializer.NormalInitializer(0,0, 2e-1)
> > ```
> 
> 这里应该是0.0，不是0,0:
> 
> ```python
> w_init = fluid.initializer.NormalInitializer(0.0, 2e-1)
> ```
多谢。 看来调用函数是要写上参数名。
