### ISSUE TITLE
请教range接口问题。

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16459]
# 环境
 - PaddlePaddle （develop）
 - Python 3.5
 - Ubuntu 16.04

# 问题
`fluid.layers.range`这个是接口。

目标是根据batch的大小来计算一个range。
```
# 获取batch数
num_row = fluid.layers.fill_constant(shape=[1], dtype='int32', value=cls_prob.shape[0])
row = fluid.layers.range(0, num_row, 1, dtype='int32') * 2
indices_ = row + label_int
```

其实是想复现tensorflow的以下代码
```
# 获取batch数
num_row = tf.to_int32(cls_prob.get_shape()[0])
row = tf.range(num_row) * 2
indices_ = row + label_int
```

但是报错如下：
```
  File "train_PNet.py", line 47, in <module>
    fetch_list=[avg_total_loss, accuracy, learning_rate])
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 533, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 601, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layers/nn.py", line 10400, in __call__
    func_ret = self._func(*args[idx:], **kwargs)
  File "/mnt/d/yeyupiaoling/PyCharm/TestMTCNN/train/model.py", line 123, in my_range
    row = np.arange(x) * 2
TypeError: unsupported operand type(s) for -: 'paddle.fluid.core.LoDTensor' and 'int'
root@DESKTOP-JSJ9G9P:/mnt/d/yeyupiaoling/PyCharm/TestMTCNN/train# python3 train_PNet.py
Traceback (most recent call last):
  File "train_PNet.py", line 47, in <module>
    fetch_list=[avg_total_loss, accuracy, learning_rate])
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 533, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/executor.py", line 601, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator range error.
Python Callstacks:
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/framework.py", line 1384, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/fluid/layers/tensor.py", line 828, in range
    outputs={'Out': [out]})
  File "/mnt/d/yeyupiaoling/PyCharm/TestMTCNN/train/model.py", line 129, in cls_ohem
    row = fluid.layers.range(0, num_row, 1, dtype='int32') * 2
  File "/mnt/d/yeyupiaoling/PyCharm/TestMTCNN/train/model.py", line 75, in P_Net
    label_cost = cls_ohem(cls_prob=cls_prob, label=label)
  File "train_PNet.py", line 14, in <module>
    image, label, bbox_target, landmark_target, label_cost, bbox_loss, landmark_loss, accuracy, conv4_1, conv4_2, conv4_3 = P_Net()
C++ Callstacks:
The step should be greater than 0 while start < end. And the step should be less than 0 while start > end. at [/paddle/paddle/fluid/operators/range_op.h:29]
PaddlePaddle Call Stacks:
0       0x7f0c07e3d7fap void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 506
```

**Comment by wanghaoshuang** [comment]
```
num_row = fluid.layers.fill_constant(shape=[1], dtype='int32', value=cls_prob.shape[0])
row = fluid.layers.range(0, num_row, 1, dtype='int32') * 2
indices_ = row + label_int
```

在fill_constant op中，value不能动态的设置，只能设置为常数，你现在设置的cls_prob.shape[0]相当与value=-1, 所以num_row永远都是-1.

正确的做法应该是：
```
num_row = fluid.layers.slice(fluid.layers.shape(cls_prob), start=[0], ends=[1], axis=0)
row = fluid.layers.range(0, num_row, 1, dtype='int32') * 2
indices_ = row + label_int
```

你可能用到的API:
http://paddlepaddle.org/documentation/docs/zh/1.3/api/layers.html#slice
http://paddlepaddle.org/documentation/docs/zh/1.3/api/layers.html#shape

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 解决了，谢谢您的回答。
