### ISSUE TITLE
DGC 问题记录

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#16519]
1. 训练失败
```bash
Traceback (most recent call last):                                                                                      
  File "train_with_orig_data.py", line 800, in <module>                                                                 
    ret = main()                                                                                                        
  File "train_with_orig_data.py", line 795, in main                                                                     
    return train(args)                                                                                                  
  File "train_with_orig_data.py", line 766, in train                                                                    
    return nccl_train(train_args, test_args, args)                                                                      
  File "train_with_orig_data.py", line 680, in nccl_train                                                               
    return parallel_train(train_args, test_args, args)                                                                  
  File "train_with_orig_data.py", line 488, in parallel_train                                                           
    trainer_id=int(args.node_conf['trainer_id']))                                                                       
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 128, in __init__                
    self._compiled_program._compile(place=self._place, scope=self._scope)                                               
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/compiler.py", line 282, in _compile                         
    scope=self._scope)                                                                                                  
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/compiler.py", line 253, in _compile_data_parallel           
self._exec_strategy, self._build_strategy, self._graph)                                                                                               
paddle.fluid.core.EnforceNotMet: can't find var's name conv2d_51.w_0@GRAD and batch_norm_32.tmp_0 in opdesc at [/paddle/                                  
paddle/fluid/framework/details/all_reduce_deps_pass.cc:105]                                                                                               
PaddlePaddle Call Stacks:                                                                                                                                 
0       0x7f8c97ae4670p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352                                      
1       0x7f8c97ae49e9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*,                                  
 int) + 137                                                                                                                                               
2       0x7f8c994914a4p                                                                                                                                   
3       0x7f8c99491866p                                                                                                                                   
4       0x7f8c99492019p paddle::framework::details::AllReduceDepsPass::ApplyImpl(std::unique_ptr<paddle::framework::ir::                                  
Graph, std::default_delete<paddle::framework::ir::Graph> >) const + 1193                                                                                  
5       0x7f8c996532fep paddle::framework::ir::Pass::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_de                                  
lete<paddle::framework::ir::Graph> >) const + 238 
```

**Comment by gongweibao** [comment]
mem_opt设置为false。
暂时不支持memory optimize.
