### ISSUE TITLE
对于图片小但数量很大的数据集有什么好的处理方法？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#16592]
# 环境
 - PaddlePaddle 1.3
 - Ubuntu 16.04
 - Python 3.5

# 问题

例如有很多的图片，大小为`12*12`，这是非常小的，但是他的量很大。这样有两个问题。
第一，在Pycharm中打开会导致pycharm加载过多的文件而出现内存溢出。
第二，在训练过程中读取图片非常慢，训练时间很快，时间计划花在读取数据上。

有没有这样一个可能性，就是把这些众多的图片转换成一个二进制文件。

我觉得普通的压缩，再在训练中利用代码读取压缩包中的文件，这样的效率会更低。

有没有其他办法呢？

**Comment by kuke** [comment]
有个办法是可以用多线程/多进程读取，可以参考这里

https://github.com/PaddlePaddle/Paddle/blob/4cc9809caeb660919ddcf31af300f5702a5d9e22/python/paddle/reader/decorator.py#L360

**Comment by yeyupiaoling** [comment]
好的，谢谢。

**Comment by yeyupiaoling** [comment]
@kuke 在我的项目中是这个reader：https://github.com/yeyupiaoling/PaddlePaddle-MTCNN/blob/ed9f29ecff2e8f3333f742ba8117ef567aa1d966/train/reader.py#L34-L43
应当如果使用这个函数呢？

我这样使用是错误的：
```python
reader1 = reader.train_reader('../data/12/all_data_list.txt')
reader2 = reader.train_reader('../data/12/all_data_list.txt')
reader3 = reader.train_reader('../data/12/all_data_list.txt')
train_reader = paddle.batch(reader=reader.multiprocess_reader(readers=[reader1, reader2, reader3]), batch_size=batch_size)
```


报错如下：
```
Traceback (most recent call last):
  File "D:/yeyupiaoling/PyCharm/PaddlePaddle-MTCNN/train/train_PNet.py", line 47, in <module>
    for batch_id, data in enumerate(train_reader()):
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\batch.py", line 35, in batch_reader
    for instance in r:
  File "D:\yeyupiaoling\PyCharm\PaddlePaddle-MTCNN\train\reader.py", line 106, in pipe_reader
    p.start()
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 212, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\multiprocessing\context.py", line 313, in _Popen
    return Popen(process_obj)
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\multiprocessing\popen_spawn_win32.py", line 66, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\multiprocessing\reduction.py", line 59, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'xmap_readers.<locals>.xreader'
```

**Comment by kuke** [comment]
https://github.com/PaddlePaddle/Paddle/blob/566a3259397464a605d792965ff625a39f65140d/python/paddle/reader/tests/decorator_test.py#L196

用法可以参考这里

**Comment by lgone2000** [comment]
这个我们内部标准做法是把很多小文件打包到一个大文件，用偏移量访问。直接访问很多文件的目录会很慢 多线程未必很好解决

**Comment by yeyupiaoling** [comment]
@lgone2000 对，就是这个问题。TensorFlow就有一个TFRecord，它把全部的小文件打包成一个打文件，读取数据很快。

**Comment by lgone2000** [comment]
可以参考我之前写的一个教程示例里面的打包方式
打包成kv格式，可以参考 test_convert_facems1m_train，这个把facems1m 识别数据集合打包成一个文件。代码在
https://github.com/lgone2000/paddle-tutorial/blob/master/image_feature/formatconverter.py

读取看下面代码中 ImageData 这个类
https://github.com/lgone2000/paddle-tutorial/blob/master/image_feature/myreader.py

**Comment by lgone2000** [comment]
https://github.com/lgone2000/paddle-tutorial/blob/master/image_feature/viewdataset.py
这里面也提供了一个web查看数据集缩图的简单示例，供你参考

**Comment by yeyupiaoling** [comment]
@lgone2000 好的，谢谢您。
