### ISSUE TITLE
使用dataset 跑text_classification模型报错

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#16642]
paddle version:1.4.0
1. dataset executor run报错
```bash
Traceback (most recent call last):
  File "local_train.py", line 55, in <module>
    dataset=dataset)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 799, in train_from_dataset
    if self.place == paddle.fluid.CUDAPlace():
NameError: global name 'paddle' is not defined
```
2. set -o pipefail 错误
```bash
root@yq01-jpaas-ai00-let0048:/ssd2/ljh_test/pipe_reader/text_classification#  python local_train.py 
sh: 1: set: Illegal option -o pipefail
sh: 1: set: Illegal option -o pipefail
sh: 1: set: Illegal option -o pipefail
sh: 1: set: Illegal option -o pipefail
sh: 1: set: Illegal option -o pipefail*** Aborted at 1554212213 (unix time) try "date -d @1554212213" if you are using GNU date ***

sh: 1: set: Illegal option -o pipefail
sh: 1: set: Illegal option -o pipefail
sh: 1: set: Illegal option -o pipefailsh: 1: set: 
Illegal option -o pipefail
sh: 1: set: Illegal option -o pipefail
sh: 1: set: Illegal option -o pipefail
sh: 1: set: Illegal option -o pipefail
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 756 (TID 0x7fec94d33700) from PID 0; stack trace: ***
    @     0x7fecba24b390 (unknown)
    @     0x7fec4daaa7a6 _ZNSt19_Sp_counted_deleterIP8_IO_FILEZN6paddle9framework11shell_popenERKSsS5_PiEUlS1_E_SaIiELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv
    @     0x7fec4bf3a569 std::_Sp_counted_base<>::_M_release()
    @     0x7fec4c0bc067 paddle::framework::MultiSlotDataFeed::ReadThread()
    @     0x7fec6b87dc80 (unknown)
    @     0x7fecba2416ba start_thread
    @     0x7fecb9f7741d clone
    @                0x0 (unknown)
Segmentation fault
```

**Comment by ccmeteorljh** [comment]
在Ubuntu下直接执行set -o pipefail会报错；
测试了下发现在Ubuntu下的 sh 是dash的软连接，如果将其修改为bash的软连接执行，则正常运行
