### ISSUE TITLE
使用dataset 测试simnet-bow infer报错

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#16679]
```bash
Traceback (most recent call last):
  File "infer.py", line 117, in <module>
    infer_from_dataset(model_path=epoch_path)
  File "infer.py", line 74, in infer_from_dataset
    debug=False)
TypeError: infer_from_dataset() got an unexpected keyword argument 'fetch_info'
```

**Comment by xjqbest** [comment]
already solved by pulling pr code last Thursday

**Comment by ccmeteorljh** [comment]
simnet infer值较高，无法对齐pyreader
