### ISSUE TITLE
test_elementwise_mul_mkldnn_op fails

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#16764]
In a new CI machine `Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz`, `test_elementwise_mul_mkldnn_op` fails
```
[08:21:40]550/624 Test #583: test_elementwise_mul_mkldnn_op ......................***Failed    5.15 sec
[08:21:40]W0410 08:21:38.063987 53917 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 9.1, Runtime API Version: 8.0
[08:21:40]W0410 08:21:38.066761 53917 device_context.cc:269] device: 0, cuDNN Version: 7.0.
[08:21:40]test_elementwise_mul_mkldnn_op failed
[08:21:40] .......Fssss....................................................
[08:21:40]======================================================================
[08:21:40]FAIL: test_check_output (test_elementwise_mul_mkldnn_op.TestElementwiseMulMKLDNNOp_BroadcastNCHW16c)
[08:21:40]----------------------------------------------------------------------
[08:21:40]Traceback (most recent call last):
[08:21:40]  File "/paddle/build/python/paddle/fluid/tests/unittests/test_elementwise_mul_op.py", line 44, in test_check_output
[08:21:40]    self.check_output()
[08:21:40]  File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 503, in check_output
[08:21:40]    check_dygraph)
[08:21:40]  File "/paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 451, in check_output_with_place
[08:21:40]    str(actual_t) + " in class " + self.__class__.__name__)
[08:21:40]AssertionError: Output (Out) has diff at CPUPlace
[08:21:40]Expect [[[[0.00125048 0.08492047]
[08:21:40]   [0.29046938 0.386396  ]]
[08:21:40]
[08:21:40]  [[0.36969334 0.11319863]
[08:21:40]   [0.21415007 0.1986888 ]]
[08:21:40]
[08:21:40]  [[0.00177243 0.25010154]
[08:21:40]   [0.40215877 0.04279045]]
[08:21:40]
[08:21:40]  [[0.41721553 0.3375377 ]
[08:21:40]   [0.46301916 0.00820544]]
[08:21:40]
[08:21:40]  [[0.10934631 0.40422767]
[08:21:40]   [0.2904416  0.22166422]]
[08:21:40]
[08:21:40]  [[0.49167052 0.0152072 ]
[08:21:40]   [0.12244622 0.41933575]]
[08:21:40]
[08:21:40]  [[0.10907405 0.1227215 ]
[08:21:40]   [0.00730317 0.6629001 ]]
[08:21:40]
[08:21:40]  [[0.5631185  0.8816506 ]
[08:21:40]   [0.4704359  0.36099708]]
[08:21:40]
[08:21:40]  [[0.2228665  0.8427488 ]
[08:21:40]   [0.07571415 0.1031361 ]]
[08:21:40]
[08:21:40]  [[0.01434026 0.22389263]
[08:21:40]   [0.06033051 0.18588263]]
[08:21:40]
[08:21:40]  [[0.15922903 0.2645933 ]
[08:21:40]   [0.05752328 0.9053555 ]]
[08:21:40]
[08:21:40]  [[0.25251266 0.14107876]
[08:21:40]   [0.0689055  0.0038731 ]]
[08:21:40]
[08:21:40]  [[0.08460373 0.29914436]
[08:21:40]   [0.16119799 0.5224081 ]]
[08:21:40]
[08:21:40]  [[0.15163004 0.05331361]
[08:21:40]   [0.13301256 0.23944747]]
[08:21:40]
[08:21:40]  [[0.04832048 0.0109666 ]
[08:21:40]   [0.3521237  0.81271416]]
[08:21:40]
[08:21:40]  [[0.51281095 0.8913848 ]
[08:21:40]   [0.33166745 0.04245876]]]]
[08:21:40]But Got[[[[0.00125048 0.10934631]
[08:21:40]   [0.2228665  0.08460373]]
[08:21:40]
[08:21:40]  [[0.08492047 0.40422767]
[08:21:40]   [0.8427488  0.29914436]]
[08:21:40]
[08:21:40]  [[0.29046938 0.2904416 ]
[08:21:40]   [0.07571415 0.16119799]]
[08:21:40]
[08:21:40]  [[0.386396   0.22166422]
[08:21:40]   [0.1031361  0.5224081 ]]
[08:21:40]
[08:21:40]  [[0.36969334 0.49167052]
[08:21:40]   [0.01434026 0.15163004]]
[08:21:40]
[08:21:40]  [[0.11319863 0.0152072 ]
[08:21:40]   [0.22389263 0.05331361]]
[08:21:40]
[08:21:40]  [[0.21415007 0.12244622]
[08:21:40]   [0.06033051 0.13301256]]
[08:21:40]
[08:21:40]  [[0.1986888  0.41933575]
[08:21:40]   [0.18588263 0.23944747]]
[08:21:40]
[08:21:40]  [[0.00177243 0.10907405]
[08:21:40]   [0.15922903 0.04832048]]
[08:21:40]
[08:21:40]  [[0.25010154 0.1227215 ]
[08:21:40]   [0.2645933  0.0109666 ]]
[08:21:40]
[08:21:40]  [[0.40215877 0.00730317]
[08:21:40]   [0.05752328 0.3521237 ]]
[08:21:40]
[08:21:40]  [[0.04279045 0.6629001 ]
[08:21:40]   [0.9053555  0.81271416]]
[08:21:40]
[08:21:40]  [[0.41721553 0.5631185 ]
[08:21:40]   [0.25251266 0.51281095]]
[08:21:40]
[08:21:40]  [[0.3375377  0.8816506 ]
[08:21:40]   [0.14107876 0.8913848 ]]
[08:21:40]
[08:21:40]  [[0.46301916 0.4704359 ]
[08:21:40]   [0.0689055  0.33166745]]
[08:21:40]
[08:21:40]  [[0.00820544 0.36099708]
[08:21:40]   [0.0038731  0.04245876]]]] in class TestElementwiseMulMKLDNNOp_BroadcastNCHW16c
[08:21:40]
[08:21:40]----------------------------------------------------------------------
[08:21:40]Ran 64 tests in 3.246s
[08:21:40]
[08:21:40]FAILED (failures=1, skipped=4)
```
http://ci.paddlepaddle.org/viewLog.html?buildId=82557&tab=buildLog&buildTypeId=Paddle_PrCi&logTab=tree&filter=all&_focus=37940

**Comment by LeoZhao-BJ** [comment]
@luotao1 did this issue only happen on Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz ?

**Comment by LeoZhao-BJ** [comment]
reproduced on E5-2699

**Comment by LeoZhao-BJ** [comment]
https://github.com/PaddlePaddle/Paddle/blob/aa46caf3d95f75b3c540290f0ff8882672287d9d/python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py#L31

Seems it's the rootcause, without this line, the case is passed, but wondering why it didn't happen on old CI machine. On my E5-2699, I can reproduce it stably.

**Comment by luotao1** [comment]
It fails both on E5-2620 v2 and E5-2620 v3, but successes on 6148.

**Comment by LeoZhao-BJ** [comment]
it may be related with AVX512, 2620/2699 don't support avx512, while 6148 supports, there is different branch for avx512 in mkldnn mul op.

**Comment by kbinias** [comment]
The problem is related to AVX SIMD. `TestElementwiseMulMKLDNNOp_BroadcastNCHW16c` test expects `nchw16c` output format. With AVX-512 `elementwise_mul` returns `nchw16c`, but with AVX2 operator returns `nchw`.
We will probably add a new attribute `out_data_format` and convert format depending on AVX inside `elementwise_mul` kernel.

**Comment by LeoZhao-BJ** [comment]
Agree, it is just output format issue, data is correct, the problem is how to define the rule of output format,  set out_data_format equals to "x_data_format" or need a explicit setting? we may need a unified format definition for both avx2 and avx512.

**Comment by LeoZhao-BJ** [comment]
I made a PR to do format convertion in avx512 mode, hope it can unblock CI.

**Comment by LeoZhao-BJ** [comment]
almost reach agreement on final solution, see comments in PR.

**Comment by ghost** [comment]
I go through this issue and feel "not comfortable" on current solution, i.e. add reorder in kernel. This is "test script" issue. Nothing wrong in kernel.

Let's revisit this issue. CI fail when run a test case [TestElementwiseMulMKLDNNOp_BroadcastNCHW16c](https://github.com/PaddlePaddle/Paddle/blob/072db0938b56e68d0a5b3b8682c5a41a5a5d09c8/python/paddle/fluid/tests/unittests/mkldnn/test_elementwise_mul_mkldnn_op.py#L24) on a AVX2 machine (no issue on AVX512 machine). This test case is trying to cover [a special code snip](https://github.com/PaddlePaddle/Paddle/blob/072db0938b56e68d0a5b3b8682c5a41a5a5d09c8/paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc#L89) in elementwise_mul MKLDNN kernel. What this test case do is to feed X tensor (nChw16c format) and Y tensor (nc format)  into elementwise_mul OP (kernel) and check it's output (expect it's format same as X, i.e. nChw16c).

Unfortunately,  [that special code snip](https://github.com/PaddlePaddle/Paddle/blob/072db0938b56e68d0a5b3b8682c5a41a5a5d09c8/paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc#L89) will be hit only when:
1. X with nChw16c, Y with nc
&&
2. on AVX512 machine

So when this test case run on AVX2 machine, it create X with nChw16c (**stupid**!) and expect the output is also nChw16c. But the kernel will actually output nchw due to fall back into "naive" code.

Kernel doesn't do anything wrong! Instead, this test case should NEVER be run on a non-AVX512 machine since it try to test the [behavior](https://github.com/PaddlePaddle/Paddle/blob/072db0938b56e68d0a5b3b8682c5a41a5a5d09c8/paddle/fluid/operators/elementwise/mkldnn/elementwise_mul_mkldnn_op.cc#L92) ONLY existing on AVX512.

In another word, this test case is HW dependant! It should be tested only when on specific HW (i.e. AVX512).

So my suggestion: change the UT and make this test case only tested on AVX512 machine. No any change (e.g. reorder) should be DONE on kernel itself.

**Comment by luotao1** [comment]
Thanks for the detail comments from @jianhang-liu!
For the sake of urgent need from @tianshuo78520a, we should disable this case on non-avx512 machine at first, which blocks the deployment of the new CI machine. @LeoZhao-Intel

**Comment by tensor-tang** [comment]
Thanks @jianhang-liu 

As of this issue itself, just disabling `nchw16c` test on AVX2 make sense since `nchw16c` is not designed for AVX2. Instead, we should test `nchw8c` on AVX2.

But, as we go through the code why this issue comes out, we figure out that it's caused by adding `x_data_format` and `y_data_format` in elementwise_op [here](https://github.com/PaddlePaddle/Paddle/pull/14351/files#diff-6932cf8a29f0870ab93621ef2237fe15R101) . This makes things completed. And actually the unit test did not cover all the data_format cases. (however that's not the key point here).

We thought these two attrs should not be attr of elementwise_op itself. The data format should be handled inside the mkldnn kernel so the op itself should only care about `use_mkldnn=True`.

And the test cases of mkldnn unit test must cover could just be the same of `test_elementwise_mul_op.py`  with only setting `use_mkldnn=True` just like nGraph did. That's the key point here.

So as for this issue itself, we thought you could just disable is to unblock CI. Then should deal with the data_format and resolve this issue.

**Comment by Sand3r-** [comment]
> We thought these two attrs should not be attr of elementwise_op itself. The data format should be handled inside the mkldnn kernel so the op itself should only care about `use_mkldnn=True`.
> 
> And the test cases of mkldnn unit test must cover could just be the same of `test_elementwise_mul_op.py` with only setting `use_mkldnn=True` just like nGraph did. That's the key point here.

These two attrs indeed shouldn't be members of elementwise_op, however the problem is that currently there is no way of setting tensor format in python in any other way. If these would be removed, it would be impossible to test the code path running the optimized kernel (nchw16c & nc case).

Adding use_mkldnn flag isn't going to change anything because the kernel itself doesn't use mkl-dnn engine and kernel, but uses a handcrafted JIT kernel. 

One idea that I came up with that would greatly simplify the kernel code, would be to move the code checking the format to specialised GetExpectedKernelType function override that would exist in elementwise_mul_op.h.

That way the fallback to naive version and reorders would happen automatically.

**Comment by tensor-tang** [comment]
> These two attrs indeed shouldn't be members of elementwise_op, however the problem is that currently there is no way of setting tensor format in python in any other way. If these would be removed, it would be impossible to test the code path running the optimized kernel (nchw16c & nc case).

So we should do this in mkldnn kernel. runtime choose on AVX512 or AVX2. Then python test should be simple enough.

> Adding use_mkldnn flag isn't going to change anything because the kernel itself doesn't use mkl-dnn engine and kernel, but uses a handcrafted JIT kernel.

That's should be a problem of why `use_mkldnn` is not what it means in this op. From user perspective, by setting  `use_mkldnn=True` should use mkldnn.

> One idea that I came up with that would greatly simplify the kernel code, would be to move the code checking the format to specialised GetExpectedKernelType function override that would exist in elementwise_mul_op.h.
That way the fallback to naive version and reorders would happen automatically.

Did not get your pint here, however `GetExpectedKernelType` is designed to override. Hope it cloud reduce the  attrs.

**Comment by LeoZhao-BJ** [comment]
> > So we should do this in mkldnn kernel. runtime choose on AVX512 or AVX2. Then python test should be simple enough.

But may still have problem on output checking, python test still need to know the CPU SKU details if the output format is not unified, if we just set a general format "nchw" in "data_format".

**Comment by Sand3r-** [comment]
> So we should do this in mkldnn kernel. runtime choose on AVX512 or AVX2. Then python test should be simple enough.

1. There is no MKL-DNN kernel that would support elementwise multiplication - hence the handcrafted JIT kernel.
2. Choosing AVX512 or AVX2 implementation depends on the data format of tensors. When tensors are created in python, they always have `nchw` data format, so the code path supporting AVX512/2 would never be executed.

> That's should be a problem of why `use_mkldnn` is not what it means in this op. From user perspective, by setting `use_mkldnn=True` should use mkldnn.
It's true - the naming might be a bit misleading, however it was denoted as 'mkldnn' because the execution of this kernel only makes sense in mkldnn environment. In non-mkldnn environment, the input tensor format would never be nchw16c, and hence the kernel would never be executed.

> Did not get your pint here, however `GetExpectedKernelType` is designed to override. Hope it cloud reduce the attrs.

What I mean is that if we design `GetExpectedKernelType` for this elementwise mul kernel in such a way:
```C++
// very simplified pseudocode
Kernel GetExpectedKernelType(...) {
   if(x->format() == nchw16c && y->format()  == nc)
      return mkldnn_kernel;
  else
      return reference_kernel;
}
```
Then we would avoid doing any reorders in the kernel code, because it would never have to do a manual fallback to reference version. The fallback and related reorders would happen automatically due to https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/data_layout_transform.cc#L117

**Comment by tensor-tang** [comment]
Thanks @Sand3r-  

We have discussed this offline in our weekly meeting with @jianhang-liu @LeoZhao-Intel  @luotao1 ,  the attrs should be removed and disable the explicit format test in python unit test. 

I assume the conclusion would be deliver to you soon.
Any questions please let us know, thanks.
