### ISSUE TITLE
import paddle.fluid DLL load failed

### ISSUE THREAD

**Issue by lluck42** [PaddlePaddle/Paddle#16784]
os window 10 1803

python 3.6.3
python 3.7.3

pip install paddlepaddle
success

py
import paddle.fluid

Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import paddle.fluid
  File "D:\Program Files\Python36\lib\site-packages\paddle\fluid\__init__.py", line 18, in <module>
    from . import framework
  File "D:\Program Files\Python36\lib\site-packages\paddle\fluid\framework.py", line 47, in <module>
    (executable_path, executable_path, cpt.get_exception_message(e)))
ImportError: NOTE: You may need to run "set PATH=D:\Program Files\Python36;%PATH%"
        if you encounters "DLL load failed" errors. If you have python
        installed in other directory, replace "D:\Program Files\Python36" with your own
        directory. The original error is:
 DLL load failed: 找不到指定的模块。

看到之前有人说3.6.6可以用就装了下3.6.3，结果还是没法用

**Comment by lluck42** [comment]
好坑啊，竟然是cpu缺少指令集，要去官网上下个不需要指令集的版本

**Comment by sidneyz139** [comment]
怎么下载？
