### ISSUE TITLE
paddle.fluid.install_check.run_check()报错

### ISSUE THREAD

**Issue by chyj4747** [PaddlePaddle/Paddle#17009]
GPU版本的paddle
系统win10
cuda8.0+cudnn7.0
python3.7

错误1：paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.
错误2：cudaGetDeviceProperties failed in paddle::platform::GetCUDAComputeCapability: unknown error at [D:\1.4.0\paddle\paddle\fluid\platform\gpu_info.cc:111]

请问要如何解决？

```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\install_check.py", line 63, in run_check
    exe.run(default_startup_program())
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 534, in run
    use_program_cache=use_program_cache)
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line 606, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks:
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line 1725, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\initializer.py", line 167, in __call__
    stop_gradient=True)
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line 1619, in create_parameter
    initializer(param, self)
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\layer_helper_base.py", line 316, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 88, in create_parameter
    default_initializer)
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\dygraph\nn.py", line 904, in build_once
    attr=self._bias_attr, shape=size, dtype=self._dtype, is_bias=True)
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 155, in __call__
    self.build_once(*inputs)
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\install_check.py", line 37, in forward
    x = self._fc1(inputs)
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 157, in __call__
    outputs = self.forward(*inputs)
  File "C:\Users\Jog\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\install_check.py", line 58, in run_check
    out = simple_layer(inp)
  File "<stdin>", line 1, in <module>
C++ Callstacks:
cudaGetDeviceProperties failed in paddle::platform::GetCUDAComputeCapability: unknown error at [D:\1.4.0\paddle\paddle\fluid\platform\gpu_info.cc:111]
PaddlePaddle Call Stacks:
Windows not support stack backtrace yet.
```

**Comment by heavengate** [comment]
看报错信息是cudaGetDeviceProperties， CUDA驱动等是否正确安装了呢

**Comment by chyj4747** [comment]
> 看报错信息是cudaGetDeviceProperties， CUDA驱动等是否正确安装了呢

```
C:\Users\Jog>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Mon_Jan__9_17:32:33_CST_2017
Cuda compilation tools, release 8.0, V8.0.60
```
百度上说版本输出正常应该安装没问题

**Comment by wopeizl** [comment]
错误2：cudaGetDeviceProperties failed in paddle::platform::GetCUDAComputeCapability: unknown error  一般情况下是编译版本和当前显卡算力不匹配的问题，如果这种情况下可以考虑自己编一个版本，可以参考 http://paddlepaddle.org/documentation/docs/zh/1.4/beginners_guide/install/compile/compile_Windows.html

**Comment by chyj4747** [comment]
> 错误2：cudaGetDeviceProperties failed in paddle::platform::GetCUDAComputeCapability: unknown error 一般情况下是编译版本和当前显卡算力不匹配的问题，如果这种情况下可以考虑自己编一个版本，

哦，好的，谢谢

**Comment by iamqiz** [comment]
老哥你怎么解决的?

**Comment by iamqiz** [comment]
> 老哥你怎么解决的?

我的原因是显卡驱动失效导致的,重新去官网下个显卡驱动安装就好了
