### ISSUE TITLE
libmkldnn.so  not found

### ISSUE THREAD

**Issue by fty8788** [PaddlePaddle/Paddle#17045]
按照命令安装完后（curl 10.86.69.44:8192/install.sh | bash -s paddlepaddle_gpu-1.3.0.post97-cp27-cp27mu-linux_x86_64.whl），执行训练出错：
fluid train.py
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/disk1/yitengfei/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 18, in <module>
    from . import framework
  File "/home/disk1/yitengfei/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 53, in <module>
    directory. The original error is: \n""" + cpt.get_exception_message(e))
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
        if you encounters "libmkldnn.so not found" errors. If you have python
        installed in other directory, replace "/usr/local/lib" with your own
        directory. The original error is:
/home/disk1/yitengfei/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/core.so: undefined symbol: mkldnn_primitive_attr_destroy

**Comment by shippingwang** [comment]
export 发下您的LD path

**Comment by fty8788** [comment]
export LD_LIBRARY_PATH=/home/disk1/yitengfei/news-rerank-dnn/bin/:$LD_LIBRARY_PATH

**Comment by fty8788** [comment]
解决了：
export LD_LIBRARY_PATH=/home/disk1/yitengfei/paddle_release_home/python/lib/python2.7/site-packages/paddle/libs/:$LD_LIBRARY_PATH

新的问题：机器没有外网，能否跳过download
Cache file /home/disk1/yitengfei/.cache/paddle/dataset/imikolov/simple-examples.tgz not found, downloading http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgzTraceback (most recent call last):
  File "train.py", line 30, in <module>
    word_dict = paddle.dataset.imikolov.build_dict()
  File "/home/disk1/yitengfei/paddle_release_home/python/lib/python2.7/site-packages/paddle/dataset/imikolov.py", line 63, in build_dict
    paddle.dataset.imikolov.MD5)) as tf:
  File "/home/disk1/yitengfei/paddle_release_home/python/lib/python2.7/site-packages/paddle/dataset/common.py", line 88, in download
    r = requests.get(url, stream=True)
  File "/home/disk1/yitengfei/paddle_release_home/python/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/home/disk1/yitengfei/paddle_release_home/python/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/disk1/yitengfei/paddle_release_home/python/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/disk1/yitengfei/paddle_release_home/python/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/disk1/yitengfei/paddle_release_home/python/lib/python2.7/site-packages/requests/adapters.py", line 442, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.fit.vutbr.cz', port=80): Max retries exceeded with url: /~imikolov/rnnlm/simple-examples.tgz (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6de6f07950>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by shippingwang** [comment]
机器没有网 数据不能下载 可以尝试自己手动load下数据
