### ISSUE TITLE
test_calibration fails on E5-2650 V4

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#17159]
```
[08:08:38]======================================================================
[08:08:38]ERROR: test_calibration (__main__.TestCalibrationForMobilenetv1)
[08:08:38]----------------------------------------------------------------------
[08:08:38]Traceback (most recent call last):
[08:08:38]  File "test_calibration_mobilenetv1.py", line 44, in test_calibration
[08:08:38]    int8_acc1) = self.run_program("calibration_out")
[08:08:38]  File "/paddle/build/python/paddle/fluid/contrib/tests/test_calibration_resnet50.py", line 242, in run_program
[08:08:38]    fetch_list=fetch_targets)
[08:08:38]  File "/paddle/build/python/paddle/fluid/executor.py", line 565, in run
[08:08:38]    use_program_cache=use_program_cache)
[08:08:38]  File "/paddle/build/python/paddle/fluid/executor.py", line 642, in _run
[08:08:38]    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
[08:08:38]EnforceNotMet: Invoke operator conv2d error.
[08:08:38]Python Callstacks: 
[08:08:38]  File "/paddle/build/python/paddle/fluid/framework.py", line 1672, in _insert_op
[08:08:38]    op = Operator(block=self, desc=op_desc, *args, **kwargs)
[08:08:38]  File "/paddle/build/python/paddle/fluid/transpiler/inference_transpiler.py", line 510, in _fuse_conv_bias
[08:08:38]    attrs=attrs)
[08:08:38]  File "/paddle/build/python/paddle/fluid/transpiler/inference_transpiler.py", line 293, in _fuse_conv_bias_mkldnn
[08:08:38]    self._fuse_conv_bias(i, current_op, next_op)
[08:08:38]  File "/paddle/build/python/paddle/fluid/transpiler/inference_transpiler.py", line 73, in transpile
[08:08:38]    self._fuse_conv_bias_mkldnn(program)
[08:08:38]  File "/paddle/build/python/paddle/fluid/contrib/tests/test_calibration_resnet50.py", line 204, in run_program
[08:08:38]    t.transpile(infer_program, fluid.CPUPlace())
[08:08:38]  File "test_calibration_mobilenetv1.py", line 40, in test_calibration
[08:08:38]    self.model_cache_folder + "/model", True, algo=self.algo)
[08:08:38]  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
[08:08:38]    testMethod()
[08:08:38]  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
[08:08:38]    return self.run(*args, **kwds)
[08:08:38]  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
[08:08:38]    test(result)
[08:08:38]  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
[08:08:38]    return self.run(*args, **kwds)
[08:08:38]  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
[08:08:38]    test(result)
[08:08:38]  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
[08:08:38]    return self.run(*args, **kwds)
[08:08:38]  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
[08:08:38]    test(result)
[08:08:38]  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
[08:08:38]    self.result = testRunner.run(self.test)
[08:08:38]  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
[08:08:38]    self.runTests()
[08:08:38]  File "test_calibration_mobilenetv1.py", line 59, in <module>
[08:08:38]    unittest.main()
[08:08:38]C++ Callstacks: 
[08:08:38]Enforce failed. Expected in_dims[1] == filter_dims[1] * groups, but received in_dims[1]:64 != filter_dims[1] * groups:32.
[08:08:38]The number of input channels should be equal to filter channels * groups. at [/paddle/paddle/fluid/operators/conv_op.cc:65]
[08:08:38]PaddlePaddle Call Stacks: 
[08:08:38]0       0x7ff3f0b13badp void paddle::platform::EnforceNotMet::Init<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int) + 509
[08:08:38]1       0x7ff3f0b1489dp paddle::platform::EnforceNotMet::EnforceNotMet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int) + 125
[08:08:38]2       0x7ff3f1336618p paddle::operators::ConvOp::InferShape(paddle::framework::InferShapeContext*) const + 4472
[08:08:38]3       0x7ff3f2c28c1fp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 895
[08:08:38]4       0x7ff3f2c29707p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 567
[08:08:38]5       0x7ff3f2c22c5ep paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 318
[08:08:38]6       0x7ff3f0cdeedep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 302
[08:08:38]7       0x7ff3f0ce1dedp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) + 189
[08:08:38]8       0x7ff3f0af88b6p
```
http://ci.paddlepaddle.org/viewLog.html?buildId=91050&tab=buildLog&buildTypeId=Paddle_PrCi&logTab=tree&filter=all

**Comment by luotao1** [comment]
@hshen14 Could you help see it?

**Comment by hshen14** [comment]
@guomingz , please take a look.

**Comment by chuanqi129** [comment]
@luotao1 May I know which pr start to fail at this test?

**Comment by luotao1** [comment]
I don't know which pr start to fail, you can look at the history of this machine:http://ci.paddlepaddle.org/agentDetails.html?id=120&tab=agentHistory

**Comment by tensor-tang** [comment]
http://ci.paddlepaddle.org/viewLog.html?buildId=91088&tab=buildLog&buildTypeId=Paddle_PrCi&logTab=tail this one is on AVX512, but still failed on test_calibration_resnet50

**Comment by guomingz** [comment]
> http://ci.paddlepaddle.org/viewLog.html?buildId=91088&tab=buildLog&buildTypeId=Paddle_PrCi&logTab=tail this one is on AVX512, but still failed on test_calibration_resnet50

this issue is not like the issue raised by @luotao1 . Do you use the latest paddle? i'll have a try on avx512.

**Comment by luotao1** [comment]
```
[09:49:13]======================================================================
[09:49:13]ERROR: test_calibration (__main__.TestCalibrationForResnet50)
[09:49:13]----------------------------------------------------------------------
[09:49:13]Traceback (most recent call last):
[09:49:13]  File "test_calibration_resnet50.py", line 298, in test_calibration
[09:49:13]    int8_acc1) = self.run_program("calibration_out")
[09:49:13]  File "test_calibration_resnet50.py", line 201, in run_program
[09:49:13]    fetch_targets] = fluid.io.load_inference_model(model_path, exe)
[09:49:13]  File "/paddle/build/python/paddle/fluid/io.py", line 1106, in load_inference_model
[09:49:13]    load_persistables(executor, dirname, program, params_filename)
[09:49:13]  File "/paddle/build/python/paddle/fluid/io.py", line 710, in load_persistables
[09:49:13]    filename=filename)
[09:49:13]  File "/paddle/build/python/paddle/fluid/io.py", line 581, in load_vars
[09:49:13]    filename=filename)
[09:49:13]  File "/paddle/build/python/paddle/fluid/io.py", line 616, in load_vars
[09:49:13]    executor.run(load_prog)
[09:49:13]  File "/paddle/build/python/paddle/fluid/executor.py", line 565, in run
[09:49:13]    use_program_cache=use_program_cache)
[09:49:13]  File "/paddle/build/python/paddle/fluid/executor.py", line 642, in _run
[09:49:13]    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
[09:49:13]EnforceNotMet: Invoke operator load error.
[09:49:13]Python Callstacks: 
[09:49:13]  File "/paddle/build/python/paddle/fluid/framework.py", line 1654, in append_op
[09:49:13]    attrs=kwargs.get("attrs", None))
[09:49:13]  File "/paddle/build/python/paddle/fluid/io.py", line 602, in load_vars
[09:49:13]    attrs={'file_path': os.path.join(dirname, new_var.name)})
[09:49:13]  File "/paddle/build/python/paddle/fluid/io.py", line 581, in load_vars
[09:49:13]    filename=filename)
[09:49:13]  File "/paddle/build/python/paddle/fluid/io.py", line 710, in load_persistables
[09:49:13]    filename=filename)
[09:49:13]  File "/paddle/build/python/paddle/fluid/io.py", line 1106, in load_inference_model
[09:49:13]    load_persistables(executor, dirname, program, params_filename)
[09:49:13]  File "test_calibration_resnet50.py", line 201, in run_program
[09:49:13]    fetch_targets] = fluid.io.load_inference_model(model_path, exe)
[09:49:13]  File "test_calibration_resnet50.py", line 298, in test_calibration
[09:49:13]    int8_acc1) = self.run_program("calibration_out")
[09:49:13]  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
[09:49:13]    testMethod()
[09:49:13]  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
[09:49:13]    return self.run(*args, **kwds)
[09:49:13]  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
[09:49:13]    test(result)
[09:49:13]  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
[09:49:13]    return self.run(*args, **kwds)
[09:49:13]  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
[09:49:13]    test(result)
[09:49:13]  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
[09:49:13]    return self.run(*args, **kwds)
[09:49:13]  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
[09:49:13]    test(result)
[09:49:13]  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
[09:49:13]    self.result = testRunner.run(self.test)
[09:49:13]  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
[09:49:13]    self.runTests()
[09:49:13]  File "test_calibration_resnet50.py", line 313, in <module>
[09:49:13]    unittest.main()
[09:49:13]C++ Callstacks: 
[09:49:13]Cannot open file calibration_out/depthwise_conv2d_4.w_0_fuse_bn for load op at [/paddle/paddle/fluid/operators/load_op.h:37]
[09:49:13]PaddlePaddle Call Stacks: 
```

**Comment by luotao1** [comment]
> Do you use the latest paddle

CI always use the latest paddle.

**Comment by guomingz** [comment]
the issue raised by @tensor-tang is weird as the resnet50 won't use the depthwise weights. But the mobilenet v1 testing will use the depthwise-related variable. 
And i doubt that when we tested the test_calibration_resnet50 case, the **__ model __** file under the python/paddle/fluid/contrib/tests/calibration_out/ directory is the mobilenet_v1 actually, though the weights files are belong to resnet50.  It may be the disk error that failed to update __model__file. @luotao1
