### ISSUE TITLE
set_lod时报错paddle.fluid.core.EnforceNotMet: the provided lod info is invalid at [/paddle/paddle/fluid/pybind/pybind.cc:449]

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#17359]
paddle版本：Fluid1.4 latest
环境：centos 6u3

设置特征lod时报错：

```Traceback (most recent call last):
  File "keras_2_fluid_all_part_map_diff_direction2_fix_multi_sum_output2.py", line 372, in <module>
    lod_tensor,lod_attention = to_lodtensor(d, place)
  File "keras_2_fluid_all_part_map_diff_direction2_fix_multi_sum_output2.py", line 356, in to_lodtensor
    expand_res.set_lod([lod,expand_lod])
paddle.fluid.core.EnforceNotMet: the provided lod info is invalid at [/paddle/paddle/fluid/pybind/pybind.cc:449]
PaddlePaddle Call Stacks: 
0       0x7f42e0b9e072p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 354
1       0x7f42e0b9e3f6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 134
2       0x7f42e0b92e69p
3       0x7f42e0bcd5fcp
4       0x7f4311e9e3e4p PyEval_EvalFrameEx + 25956
5       0x7f4311e9dc56p PyEval_EvalFrameEx + 24022
6       0x7f4311e9f130p PyEval_EvalCodeEx + 2240
7       0x7f4311e9f242p PyEval_EvalCode + 50
8       0x7f4311eb962cp
9       0x7f4311eb9700p PyRun_FileExFlags + 144
10      0x7f4311ebac0cp PyRun_SimpleFileExFlags + 220
11      0x7f4311ecc4ccp Py_Main + 3164
12        0x318ae1ecddp __libc_start_main + 253
13            0x400659p
```

to_lodtensor函数如下：

```python
def to_lodtensor(data, place):
    size = len(data[0][0])
    seq_lens = [len(seq) for seq in data]
    cur_len = 0
    lod = [cur_len]
    for l in seq_lens:
        cur_len += l
        lod.append(cur_len)
        
    flattened_data = np.concatenate(data, axis=0).astype("float32")
    res = fluid.LoDTensor()
    res.set(flattened_data, place)
    res.set_lod([lod])

    expand_lod = []
    for i in range(0,cur_len+1):
        expand_lod.append(i*cur_len)
    expand_res = fluid.LoDTensor()
    expand_res.set( np.zeros((1,size),dtype=np.float32), place)

    print "set_lod: ",[lod,expand_lod]
    expand_res.set_lod([lod,expand_lod])

    return res,expand_res
```

特征是类似nlp的变长序列，之前使用0.11版本的paddle时用这个函数设置lod没有问题，改为最新版fluid后报错。报错时expand_res.set_lod([lod,expand_lod]) 中装填的lod信息为[[0, 2], [0, 2, 4]]

**Comment by Superjomn** [comment]
看了是lod的格式不合法。

lod本身信息看起来没问题，是否是 `expand_res` 的 shape[0] != 4 ？ 否则跟LoD对不上
