### ISSUE TITLE
fluid.io.load_inference_model出错：Cannot open file ../models/chepai/car_plate-MobileNetSSD_CAR_PLATE_V2_fluid/conv11_mbox_conf_new_weights for load op at [/paddle/paddle/fluid/operators/load_op.h:37]

### ISSUE THREAD

**Issue by ysh329** [PaddlePaddle/Paddle#17391]
fluid.io.load_inference_model出错：Cannot open file ../models/chepai/car_plate-MobileNetSSD_CAR_PLATE_V2_fluid/conv11_mbox_conf_new_weights for load op at [/paddle/paddle/fluid/operators/load_op.h:37]

- py2.7, cpu
- 安装方式pip install paddlepaddle==1.4

疑问：我之前使用`fluid.io.load_inference_model`接口都没有出现这个问题（模型是权重分散的那种形式），但这次出现问题的权重文件`params`是单独一个，是否和这个有关？（因为我看似乎报错是有关load op的问题），感谢~

## 代码
```python
#!/usr/bin/python

import sys 
import os
import paddle.fluid as fluid

DEBUG = False

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python ./{} <model_dir>".format(os.path.basename(__file__)))
        exit(0)

    # input parameters
    model_dir = sys.argv[1] 
    exe = fluid.Executor(fluid.CPUPlace())

    print("[INFO] model_dir:{}".format(model_dir))

    # load model
    [inference_program, feed_target_names, fetch_targets] = \ 
      fluid.io.load_inference_model(dirname=model_dir, executor=exe)

    model_op_set = set()
    for blocks_idx in range(len(inference_program.blocks)):
        blocks = inference_program.blocks[blocks_idx]
        if DEBUG: print("[DEBUG] ==== {} ====".format(blocks_idx))
        if DEBUG: print("[DEBUG] {}".format(blocks))
        for op in list(blocks.ops):
            if DEBUG: print("[DEBUG] {}".format(op.type))
            model_op_set.add(op.type)

    # output operators
    model_op_list = list(model_op_set)
    for op_idx in range(len(model_op_list)):
        op = model_op_list[op_idx]
        print("[INFO] op_idx:{}, {}".format(op_idx, op))
```

## 错误日志
```shell
Traceback (most recent call last):
  File "./output_model_ops_from_fluid.py", line 22, in <module>
    fluid.io.load_inference_model(dirname=model_dir, executor=exe)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 1100, in load_inference_model
    load_persistables(executor, dirname, program, params_filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 704, in load_persistables
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 575, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 610, in load_vars
    executor.run(load_prog)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 534, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 606, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator load error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 596, in load_vars
    attrs={'file_path': os.path.join(dirname, new_var.name)})
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 575, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 704, in load_persistables
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 1100, in load_inference_model
    load_persistables(executor, dirname, program, params_filename)
  File "./output_model_ops_from_fluid.py", line 22, in <module>
    fluid.io.load_inference_model(dirname=model_dir, executor=exe)
C++ Callstacks: 
Cannot open file ../models/chepai/car_plate-MobileNetSSD_CAR_PLATE_V2_fluid/conv11_mbox_conf_new_weights for load op at [/paddle/paddle/fluid/operators/load_op.h:37]
PaddlePaddle Call Stacks: 
0       0x7fc3a5923520p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fc3a5923899p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fc3a5ef1f76p paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 774
3       0x7fc3a5ef21e3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::Lo
adOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int
>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int)
 const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
4       0x7fc3a6aca8c6p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinne
dPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::de
tail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::vo
id_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 662
5       0x7fc3a6acb3c4p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinne
dPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::de
tail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::vo
id_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
6       0x7fc3a6ac959bp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, bo
ost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::vari
ant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost
::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 267
7       0x7fc3a5a8a0dep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 158
8       0x7fc3a5a8d0efp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, 
bool) + 143
9       0x7fc3a591430ep
10      0x7fc3a59532fep
11            0x4c5326p PyEval_EvalFrameEx + 37958
12            0x4b9b66p PyEval_EvalCodeEx + 774
13            0x4c1f56p PyEval_EvalFrameEx + 24694
14            0x4b9b66p PyEval_EvalCodeEx + 774
15            0x4c17c6p PyEval_EvalFrameEx + 22758
16            0x4b9b66p PyEval_EvalCodeEx + 774
17            0x4c17c6p PyEval_EvalFrameEx + 22758
18            0x4b9b66p PyEval_EvalCodeEx + 774
19            0x4c17c6p PyEval_EvalFrameEx + 22758
20            0x4b9b66p PyEval_EvalCodeEx + 774
21            0x4c17c6p PyEval_EvalFrameEx + 22758
22            0x4b9b66p PyEval_EvalCodeEx + 774
23            0x4c17c6p PyEval_EvalFrameEx + 22758
24            0x4b9b66p PyEval_EvalCodeEx + 774
25            0x4eb69fp
26            0x4e58f2p PyRun_FileExFlags + 130
27            0x4e41a6p PyRun_SimpleFileExFlags + 390
28            0x4938cep Py_Main + 1358
29      0x7fc3c76a4830p __libc_start_main + 240
30            0x493299p _start + 41
```

**Comment by ysh329** [comment]
Fixed, according to api of docs...

```python
    # input parameters
    model_dir = sys.argv[1]
    is_model_single_file = True if sys.argv[2]=="1" else False
    params_filename = None if is_model_single_file==True else model_dir+"/params"
    exe = fluid.Executor(fluid.CPUPlace())

    print("[INFO] model_dir:{}".format(model_dir))

    # load model
    [inference_program, feed_target_names, fetch_targets] = \ 
      fluid.io.load_inference_model(dirname=model_dir, executor=exe, params_filename=params_filename)
```
