### ISSUE TITLE
请问使用fluid.io.save_inference_model保存的模型如何输出每一层的结果？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#17413]
我想使用`fluid.io.save_inference_model`保存的模型在预测的时候，输出指定层的结果，这样可以坐到吗，如何做呢？

**Comment by Superjomn** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/paddle_api.h#L235

可以试下 GetInputTensor, GetOutputTensor 这两个接口，前者可写，后者只读

**Comment by yeyupiaoling** [comment]
@Superjomn 是C++的啊，有没有Python的接口呢？

**Comment by Superjomn** [comment]
executor.run ，类似训练拿 fetch 应该就可以。 就是执行一个 infer 的 program

**Comment by yeyupiaoling** [comment]
@Superjomn 是的，PaddleMobile可以通过这样找到输出的名字，然后输出，但是我测试了一下PaddlePaddle，报错了。
![image](https://user-images.githubusercontent.com/26297768/57820352-0651e500-77bf-11e9-8ae4-861e0566bc96.png)

**Comment by Superjomn** [comment]
啥错误，可以附上代码

**Comment by yeyupiaoling** [comment]
@Superjomn 
```python
import os
import time
from tqdm import tqdm
import paddle.fluid as fluid
from PIL import Image
import config as cfg
import numpy as np

# 获取执行器
# place = fluid.CUDAPlace(0)
place = fluid.CPUPlace()
exe = fluid.Executor(place)

# 从保存的模型文件中获取预测程序、输入数据的名称和分类器
[infer_program, feeded_var_names, target_vars] = fluid.io.load_inference_model(dirname=cfg.TRAIN.SAVE_INFER_MODEL_PATH,
                                                                               executor=exe,
                                                                               model_filename='model.paddle',
                                                                               params_filename='params.paddle')


# 对图片进行预处理
def load_image(path):
    img = Image.open(path)
    # 统一图像大小
    img = img.resize((cfg.READER.CROP_SIZE, cfg.READER.CROP_SIZE), Image.ANTIALIAS)
    # 转换成numpy值
    img = np.array(img).astype(np.float32)
    # 转换成CHW
    img = img.transpose((2, 0, 1))
    # 转换成BGR
    img = img[(2, 1, 0), :, :] / 255.0
    return img


def infer(path):
    # 添加待预测的图片
    infer_data = load_image(path)[np.newaxis, ]

    # 执行预测
    results = exe.run(program=infer_program,
                      feed={feeded_var_names[0]: infer_data},
                      fetch_var_name='conv2d_13.tmp_0')

    print(results)
    print(results.shape)

if __name__ == '__main__':
    infer('392b7ecd-7079-11e9-9969-c8ff285a4318.jpg')
```


错误信息：
```
Traceback (most recent call last):
  File "D:/yeyupiaoling/FuGuanWanjia/PyCharm/VegetablesClassification/infer.py", line 81, in <module>
    infer('392b7ecd-7079-11e9-9969-c8ff285a4318.jpg')
  File "D:/yeyupiaoling/FuGuanWanjia/PyCharm/VegetablesClassification/infer.py", line 42, in infer
    fetch_var_name='conv2d_13.tmp_0')
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\executor.py", line 639, in _run
    fetch_var_name=fetch_var_name)
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\executor.py", line 351, in _add_feed_fetch_ops
    if not has_fetch_operators(global_block, fetch_list, fetch_var_name):
  File "C:\Users\1596\AppData\Local\Programs\Python\Python35\lib\site-packages\paddle\fluid\executor.py", line 167, in has_fetch_operators
    assert op.desc.output('Out')[0] == fetch_holder_name
AssertionError
```

**Comment by Superjomn** [comment]
哦，save_inference_model 存下来的，已经进行了图的剪枝，只能获取存储时设置的 fetch_list 中的变量，中间变量不可取

训练中的是可以通过 exe.run 获得，因为没有剪枝，是完整的图

**Comment by yeyupiaoling** [comment]
@Superjomn 哦哦，原来是这样子，谢谢。
