### ISSUE TITLE
fluid dev版本单GPU下segmentation fault

### ISSUE THREAD

**Issue by zenghsh3** [PaddlePaddle/Paddle#17429]
paddle 版本：http://paddlepaddle.org/documentation/docs/zh/1.4/beginners_guide/install/Tables.html “多版本whl包列表-dev” 下载的开发版本（paddlepaddle_gpu-latest-cp36-cp36m-linux_x86_64.whl）

机器信息：centos, cuda8, cudnn7

在Paddle1.4.1下正常训练，但存在内存泄漏问题 #17176；下载fix内存泄漏的最新开发版本发现单卡运行时(export CUDA_VISIBLE_DEVICES="0")报如下segmentation fault错误，在多卡环境(export CUDA_VISIBLE_DEVICES="0,1")启动正常。

![image](https://user-images.githubusercontent.com/5762635/57772208-72910200-7747-11e9-8d45-baa208120819.png)

**Comment by velconia** [comment]
你用到了memory_optimize吗？

**Comment by zenghsh3** [comment]
应该是没有的
```python
exec_strategy = fluid.ExecutionStrategy()
exec_strategy.use_experimental_executor = True
exec_strategy.num_threads = 4
build_strategy = fluid.BuildStrategy()
build_strategy.remove_unnecessary_lock = True

# Use ParallelExecutor to make learn program run faster
self.learn_exe = fluid.ParallelExecutor(
    use_cuda=use_cuda,
    main_program=self.learn_program,
    build_strategy=build_strategy,
    exec_strategy=exec_strategy,
    )
```

**Comment by zenghsh3** [comment]
基于PR #17433 后编译的dev版本Fluid，没有出现上面的segmentation fault，但是训练时出现下面异常，请问能定位这是什么原因导致的吗？

```plain
I0517 10:19:26.879052  2704 operator.cc:166] CUDAPlace(0) Op(recurrent), inputs:{initial_states[fill_constant_batch_size_like_0.tmp_0:float[20]({})], inputs[reverse_0.tmp_0:float[49, 20]({}), reverse_1.tmp_0:float[49, 20]({}), reverse_2.tmp_0:float[49, 20]({})], parameters[]}, outputs:{outputs[static_rnn_0.tmp_0:float[49, 20]({})], step_scopes[_generated_var_0:[-1]({{}})]}.
I0517 10:19:26.879063  2704 recurrent_op.cc:247] Static RNN input sequence length = 49
I0517 10:19:26.936410  2704 fast_threaded_ssa_graph_executor.cc:245] caught exception EnforceNotMet, rethrow it
I0517 10:19:26.948675  2704 node.h:52] ir::Node deleting a wrapper node fetch
I0517 10:19:26.948719  2704 node.h:52] ir::Node deleting a wrapper node fetch
I0517 10:19:26.948732  2704 node.h:52] ir::Node deleting a wrapper node fetch
I0517 10:19:26.948745  2704 node.h:52] ir::Node deleting a wrapper node fetch
I0517 10:19:26.948760  2704 node.h:52] ir::Node deleting a wrapper node fetch
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/zenghongsheng/miniconda3/envs/parl/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/zenghongsheng/miniconda3/envs/parl/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zenghongsheng/PARL_hadoop/examples/IMPALA/learner.py", line 127, in run_learn
    total_loss, pi_loss, vf_loss, entropy, kl = self.agent.learn()
  File "/home/zenghongsheng/PARL_hadoop/examples/IMPALA/atari_agent.py", line 133, in learn
    fetch_list=self.learn_outputs)
  File "/home/zenghongsheng/miniconda3/envs/parl/lib/python3.6/site-packages/paddle/fluid/parallel_executor.py", line 286, in run
    return_numpy=return_numpy)
  File "/home/zenghongsheng/miniconda3/envs/parl/lib/python3.6/site-packages/paddle/fluid/executor.py", line 640, in run
    return_numpy=return_numpy)
  File "/home/zenghongsheng/miniconda3/envs/parl/lib/python3.6/site-packages/paddle/fluid/executor.py", line 502, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EnforceNotMet:  at [/paddle/paddle/fluid/operators/recurrent_op.cc:66]
PaddlePaddle Call Stacks:
0       0x7fc7dec163f0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7fc7dec16769p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7fc7df29539cp paddle::operators::RecurrentOp::CreateStepScopes(paddle::framework::Scope const&, unsigned long) const + 732
3       0x7fc7df297255p paddle::operators::RecurrentOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 277
4       0x7fc7e0a9880cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
5       0x7fc7e08a68a9p
6       0x7fc7e0897a2dp
7       0x7fc7e0898714p paddle::framework::details::OpHandleBase::RunAndRecordEvent(std::function<void ()> const&) + 116
8       0x7fc7e08a653cp paddle::framework::details::ComputationOpHandle::RunImpl() + 124
9       0x7fc7e0898cb0p paddle::framework::details::OpHandleBase::Run(bool) + 160
10      0x7fc7e087b236p paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*) + 310
11      0x7fc7e0876587p paddle::framework::details::FastThreadedSSAGraphExecutor::RunTracedOps(std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> > const&) + 71
12      0x7fc7e0879c10p paddle::framework::details::FastThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 2192
13      0x7fc7e07e597ap paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 378
14      0x7fc7dedce1d2p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 562
15      0x7fc7dec05ceep
16      0x7fc7dec4b716p
17      0x7fc84956fdf2p _PyCFunction_FastCallDict + 258
18      0x7fc8495f52bbp
19      0x7fc8495f815dp _PyEval_EvalFrameDefault + 9981
20      0x7fc8495f3a60p
21      0x7fc8495f548ap
22      0x7fc8495f78ddp _PyEval_EvalFrameDefault + 7805
23      0x7fc8495f3a60p
24      0x7fc8495f548ap
25      0x7fc8495f78ddp _PyEval_EvalFrameDefault + 7805
26      0x7fc8495f3a60p
27      0x7fc8495f548ap
28      0x7fc8495f78ddp _PyEval_EvalFrameDefault + 7805
29      0x7fc8495f2e74p
30      0x7fc8495f55e8p
31      0x7fc8495f815dp _PyEval_EvalFrameDefault + 9981
32      0x7fc8495f2e74p
33      0x7fc8495f3e75p _PyFunction_FastCallDict + 645
34      0x7fc849518ba6p _PyObject_FastCallDict + 358
35      0x7fc849518dfcp _PyObject_Call_Prepend + 204
36      0x7fc849518e96p PyObject_Call + 86
37      0x7fc8495f9236p _PyEval_EvalFrameDefault + 14294
38      0x7fc8495f2e74p
39      0x7fc8495f55e8p
40      0x7fc8495f815dp _PyEval_EvalFrameDefault + 9981
41      0x7fc8495f2e74p
42      0x7fc8495f55e8p
43      0x7fc8495f815dp _PyEval_EvalFrameDefault + 9981
44      0x7fc8495f2e74p
45      0x7fc8495f3e75p _PyFunction_FastCallDict + 645
46      0x7fc849518ba6p _PyObject_FastCallDict + 358
47      0x7fc849518dfcp _PyObject_Call_Prepend + 204
48      0x7fc849518e96p PyObject_Call + 86
49      0x7fc849645ae2p
50      0x7fc8492961c3p
51      0x7fc8486b512dp clone + 109
```
