### ISSUE TITLE
Python2.7安装paddlepaddle失败

### ISSUE THREAD

**Issue by MrRace** [PaddlePaddle/Paddle#17498]
-  版本、环境信息：
   1）GPU：CUDA版本=9，CUDNN版本=7。GPU设备为2080Ti，在TensorFlow-gpu和PyTorch-gpu上可以正常安装和使用GPU。
   2）系统环境：系统=16.04.1-Ubuntu、Python版本=Python 2.7.12
安装方式信息：
1）pip安装：pip install paddlepaddle-gpu
问题描述：安装过程报错，报错信息如下：
```
Collecting scipy>=0.19.0 (from paddlepaddle-gpu)
  Downloading https://pypi.doubanio.com/packages/cb/97/361c8c6ceb3eb765371a702ea873ff2fe112fa40073e7d2b8199db8eb56e/scipy-1.3.0.tar.gz (23.6MB)
     |████████████████████████████████| 23.6MB 994kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Complete output from command /home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py27_even/bin/python2 /home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py27_even/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpY21PUy:
  ERROR: Traceback (most recent call last):
    File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py27_even/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py27_even/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py27_even/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py27_even/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 145, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py27_even/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 126, in _get_build_requires
      self.run_setup()
    File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py27_even/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 234, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py27_even/local/lib/python2.7/site-packages/setuptools/build_meta.py", line 141, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 31, in <module>
      raise RuntimeError("Python version >= 3.5 required.")
  RuntimeError: Python version >= 3.5 required.
  ----------------------------------------
ERROR: Command "/home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py27_even/bin/python2 /home/lab/liujiepeng/MachineComprehension/DuReader/paddle_py27_even/local/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpY21PUy" failed with error code 1 in /tmp/pip-install-k1uXKL/scipy
```

**Comment by JiabinYang** [comment]
看起来是豆瓣源上的scipy只有python3.5的版本：
<img width="1436" alt="MacHi 2019-05-20 19-09-00" src="https://user-images.githubusercontent.com/22361972/58017435-ce3a0180-7b32-11e9-95b3-2045f729d177.png">
直接使用pypi源安装就可以了
<img width="1436" alt="MacHi 2019-05-20 19-09-15" src="https://user-images.githubusercontent.com/22361972/58017449-da25c380-7b32-11e9-97e7-123e9530429c.png">

**Comment by MrRace** [comment]
> 看起来是豆瓣源上的scipy只有python3.5的版本：
> <img alt="MacHi 2019-05-20 19-09-00" width="1436" src="https://user-images.githubusercontent.com/22361972/58017435-ce3a0180-7b32-11e9-95b3-2045f729d177.png">
> 直接使用pypi源安装就可以了
> <img alt="MacHi 2019-05-20 19-09-15" width="1436" src="https://user-images.githubusercontent.com/22361972/58017449-da25c380-7b32-11e9-97e7-123e9530429c.png">

多谢，安装是可以正常安装了，check时候报错。有劳帮忙看下这两个issue：
https://github.com/PaddlePaddle/Paddle/issues/17504
https://github.com/PaddlePaddle/Paddle/issues/17496
