### ISSUE TITLE
多卡训练PaddleRec中gnn模型时出现shape不一致错误

### ISSUE THREAD

**Issue by MoZhonglin** [PaddlePaddle/Paddle#17510]
- 版本、环境信息：
    1）PaddlePaddle版本：1.4.1
    2）GPU：Tesla K40m   CUDA 8.0   CuDNN 5.1   nccl_2.1.4-1+cuda8.0_x86_64
    3）系统环境：CentOS release 6.3 (Final)   Python 2.7.13
- 训练信息
    1）单机，多卡
    2）显存 12GB
- 问题描述：

复现过程：
```bash
git clone https://github.com/PaddlePaddle/models/tree/develop/PaddleRec/gnn
cd data && sh download.sh
fluid preprocess.py --dataset diginetica
cd ..
CUDA_VISIBLE_DEVICES=10,11,12,14 fluid -u train.py --use_cuda 1 > log.txt 2>&1 &
```

此时会报错，log.txt中的全文如下：

```
2019-05-21 00:24:19,336-INFO: load data complete
W0521 00:24:20.547624   465 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 35, Driver API Version: 9.0, Runtime API Version: 8.0
W0521 00:24:20.549405   465 device_context.cc:269] device: 0, cuDNN Version: 5.1.
ParallelExecutor is deprecated. Please use CompiledProgram and Executor. CompiledProgram is a central place for optimization and Executor is the unified executor. Example can be found in compiler.py.
W0521 00:24:23.793253   465 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid using the `OriginProgram()` method!
2019-05-21 00:24:23,793-WARNING: 
     You can try our memory optimize feature to save your memory usage:
         # create a build_strategy variable to set memory optimize option
         build_strategy = compiler.BuildStrategy()
         build_strategy.enable_inplace = True
         build_strategy.memory_optimize = True
         
         # pass the build_strategy to with_data_parallel API
         compiled_prog = compiler.CompiledProgram(main).with_data_parallel(
             loss_name=loss.name, build_strategy=build_strategy)
      
     !!! Memory optimize is our experimental feature !!!
         some variables may be removed/reused internal to save memory usage, 
         in order to fetch the right value of the fetch_list, please set the 
         persistable property to true for each variable in fetch_list

         # Sample
         conv1 = fluid.layers.conv2d(data, 4, 5, 1, act=None) 
         # if you need to fetch conv1, then:
         conv1.persistable = True

                 
I0521 00:24:28.669422   465 build_strategy.cc:285] SeqOnlyAllReduceOps:0, num_trainers:1
2019-05-21 00:24:28,685-INFO: begin train
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    train()
  File "train.py", line 125, in train
    fetch_list=[loss.name, acc.name])
  File "/home/disk0/jiaokui/suidong/Paddle-1.4.1/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 205, in run
    return_numpy=return_numpy)
  File "/home/disk0/jiaokui/suidong/Paddle-1.4.1/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 580, in run
    return_numpy=return_numpy)
  File "/home/disk0/jiaokui/suidong/Paddle-1.4.1/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 446, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator reshape2 error.
Python Callstacks: 
  File "/home/disk0/jiaokui/suidong/Paddle-1.4.1/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/disk0/jiaokui/suidong/Paddle-1.4.1/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/disk0/jiaokui/suidong/Paddle-1.4.1/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 6424, in reshape
    "XShape": x_shape})
  File "/home/disk0/jiaokui/mozhonglin/gnn_py2/network.py", line 72, in network
    x=pre_state, shape=[batch_size, -1, hidden_size])
  File "train.py", line 75, in train
    args.step)
  File "train.py", line 172, in <module>
    train()
C++ Callstacks: 
Enforce failed. Expected output_shape[unk_dim_idx] * capacity == -in_size, but received output_shape[unk_dim_idx] * capacity:-60000 != -in_size:-62500.
Invalid shape is given. at [/paddle/paddle/fluid/operators/reshape_op.cc:101]
PaddlePaddle Call Stacks: 
0       0x7f00dc74bd68p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f00dc74c0b7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f00dce344c4p paddle::operators::ReshapeOp::ValidateShape(std::vector<int, std::allocator<int> >, paddle::framework::DDim const&) + 1956
3       0x7f00dce36441p paddle::operators::ReshapeOp::InferShape(paddle::framework::InferShapeContext*) const + 689
4       0x7f00dce36b59p paddle::operators::Reshape2Op::InferShape(paddle::framework::InferShapeContext*) const + 521
5       0x7f00de4d8c78p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 584
6       0x7f00de4d9434p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 292
7       0x7f00de4d6d5cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
8       0x7f00de2e62fap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
9       0x7f00de2d93b0p paddle::framework::details::OpHandleBase::Run(bool) + 160
10      0x7f00de240a7dp
11      0x7f00dd4e9ad3p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
12      0x7f00dc819e97p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
13      0x7f013e5d9973p pthread_once + 83
14      0x7f00de240612p
15      0x7f00dc81b1d4p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
16      0x7f011082c8a0p
17      0x7f013e5d41c3p
18      0x7f013dbfc12dp clone + 109
```
其中，如果将复现过程的第5步替换为
```bash
CUDA_VISIBLE_DEVICES=10 fluid -u train.py --use_cuda 1 > log.txt 2>&1 &
```
也就是只使用任意一张卡进行训练，则不会出现任何错误。

**Comment by hutuxian** [comment]
Training with multi GPU cards is not yet supported well now, and we will fix this or accelerate the training speed by other means soon.
