### ISSUE TITLE
训练好的模型，python加载create_paddle_predictor出core。

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#17559]
- 标题：训练好的模型（content-dnn2），python加载create_paddle_predictor出core。
- 版本、环境信息：
    1）PaddlePaddle版本：1.3 和 1.4
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：cuda9, cudnn7
    4）系统环境：ubuntu_1604和centos6.3

- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

pip直接安装的Paddle1.3和1.4。cpu和gpu报错一致
预测代码
```python
model_path = "/infer_model" #储存fluid模型的路径
config = fluid.core.AnalysisConfig("content_dnn2")
config.set_model(model_path)
config.disable_gpu()
predict = fluid.core.create_paddle_predictor(config)
outputs = predict.run(input_value)
```
报错信息
```shell
I0522 11:57:35.364528  5599 analysis_predictor.cc:387] == optimize end ==
Traceback (most recent call last):
  File "content-dnn2.py", line 177, in <module>
    run_inference(input_tensor)
  File "content-dnn2.py", line 144, in run_inference
    predict = fluid.core.create_paddle_predictor(config)
paddle.fluid.core.EnforceNotMet: Cannot get attribute height_sections by type std::vector<int, std::allocator<int> >, its type is std::vector<long, std::allocator<long> > at [/paddle/paddle/fluid/framework/attribute.h:42]
PaddlePaddle Call Stacks:
0       0x7f6605b7959dp void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 365
1       0x7f6605b798e7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f6605d0a4e2p paddle::framework::ExtractAttribute<std::vector<int, std::allocator<int> > >::operator()(boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>&) const + 354
```
报错的信息和这个issue遇到的问题基本一致https://github.com/PaddlePaddle/Paddle/issues/17345 
所以怀疑是预测库版本和训练的版本不一致，但目前我也不太确定训练模型用的是哪一个版本。

然后我用自己编译的Paddle来试了一下，
Cmake命令如下
```shell
cmake .. -DPY_VERSION=3.5 \
		-DWITH_FLUID_ONLY=ON \
		-DWITH_GPU=ON \
		-DWITH_TESTING=ON \
		-DCMAKE_BUILD_TYPE=Release \
		-DWITH_PYTHON=OFF \
      	        -DWITH_MKL=ON \
      	        -DON_INFER=ON 
```
报错如下
![image](https://user-images.githubusercontent.com/14963836/58153102-d617b400-7ca0-11e9-8b00-1c857f74d732.png)

**Comment by OliverLPH** [comment]
采取load_inference_model的方式也是出一样的错误，代码如下
```python
place = fluid.CPUPlace()
exe = fluid.Executor(place)
params_dirname = "/infer_model"
with fluid.scope_guard(fluid.core.Scope()):
    [program, feed, fetch] = fluid.io.load_inference_model(
        params_dirname,
        exe,
        model_filename='__model__')

config = fluid.core.AnalysisConfig("/infer_model")
program = fluid.compiler.CompiledProgram(program)
program.with_inference_optimize(config)
outputs = exe.run(program, feed=input_value)
```

**Comment by Superjomn** [comment]
该 API 还未发布，目前没有支持计划
建议使用 C++ API，方便聚焦和查找问题

**Comment by Superjomn** [comment]
paddle.fluid.core.EnforceNotMet: Cannot get attribute height_sections by type 

这个问题之前遇到过，初步看是相关 Op 的定义有修改，导致训好的模型中 Op 定义与预测中的不一致。 训练和预测版本改成一致就不会有问题了
