### ISSUE TITLE
mask-rcnn在最新paddle下报错：Invoke operator scale error

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#17574]
mask-rcnn 模型报错
paddle_commit_id: 43d15b9d96530ec60a631fe252510d6fb90190ab

复现代码：
https://github.com/PaddlePaddle/benchmark/blob/master/Mask-RCNN/paddle/rcnn/run.sh

执行命令：
```bash
CUDA_VISIBLE_DEVICES=0 python -u train.py --model_save_dir=output/ --pretrained_model=../imagenet_resnet50_fusebn/ --data_dir=./dataset/coco --im_per_batch=1 --MASK_ON=True
```

```bash
Traceback (most recent call last):
  File "train.py", line 243, in <module>
    train()
  File "train.py", line 234, in train
    train_loop_pyreader()
  File "train.py", line 173, in train_loop_pyreader
    outs = train_exe.run(fetch_list=[v.name for v in fetch_list])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 286, in run
    return_numpy=return_numpy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 640, in run
    return_numpy=return_numpy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 502, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator scale error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1702, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/regularizer.py", line 173, in __call__
    attrs={"scale": self._regularization_coeff})
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/regularizer.py", line 55, in append_regularization_ops
    regularization_term = param.regularizer(param, grad, grad.block)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/optimizer.py", line 439, in apply_gradients
    self.regularization)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/optimizer.py", line 469, in apply_optimize
    optimize_ops = self.apply_gradients(params_grads)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/optimizer.py", line 500, in minimize
    loss, startup_program=startup_program, params_grads=params_grads)
  File "train.py", line 98, in train
    optimizer.minimize(loss)
  File "train.py", line 243, in <module>
    train()
C++ Callstacks: 
Input X(0)is not initialized at [/paddle/paddle/fluid/framework/operator.cc:1146]
PaddlePaddle Call Stacks: 
0       0x7f55c785bc90p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f55c785c009p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f55c95f32bfp paddle::framework::OperatorWithKernel::IndicateDataType(paddle::framework::ExecutionContext const&) const + 1343
3       0x7f55c95f34afp paddle::framework::OperatorWithKernel::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 47
4       0x7f55c95f4d6bp paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 235
5       0x7f55c95f6ec8p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 728
6       0x7f55c95f7141p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
7       0x7f55c95f474cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
8       0x7f55c940199ap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
9       0x7f55c93f4010p paddle::framework::details::OpHandleBase::Run(bool) + 160
10      0x7f55c93d6596p paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*) + 310
11      0x7f55c93d52ffp paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*) + 47
12      0x7f55c93d56bfp
13      0x7f55c863a993p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
14      0x7f55c792acd7p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
15      0x7f5654c9aa99p
16      0x7f55c93d1432p
17      0x7f55c792c254p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
18      0x7f564fd1cc80p
19      0x7f5654c936bap
20      0x7f56549c941dp clone + 109
```

**Comment by ccmeteorljh** [comment]
有时候是这个错误
```bash
Filtered 2042 roidb entries: 236574 -> 234532
train on coco2017 with 236574 roidbs
Traceback (most recent call last):
  File "train.py", line 243, in <module>
    train()
  File "train.py", line 234, in train
    train_loop_pyreader()
  File "train.py", line 173, in train_loop_pyreader
    outs = train_exe.run(fetch_list=[v.name for v in fetch_list])
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 286, in run
    return_numpy=return_numpy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 640, in run
    return_numpy=return_numpy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 502, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator increment error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1773, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 6496, in autoincreased_step_counter
    stop_gradient=True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/learning_rate_scheduler.py", line 46, in _decay_step_counter
    counter_name='@LR_DECAY_COUNTER@', begin=begin, step=1)
  File "/ssd1/ljh/benchmark_daily/benchmark/Mask-RCNN/paddle/rcnn/learning_rate.py", line 26, in exponential_with_warmup_decay
    global_step = lr_scheduler._decay_step_counter()
  File "train.py", line 93, in train
    warmup_factor=cfg.warm_up_factor)
  File "train.py", line 243, in <module>
    train()
C++ Callstacks: 
Input X(0)is not initialized at [/paddle/paddle/fluid/framework/operator.cc:1146]
PaddlePaddle Call Stacks: 
0       0x7f12e9385c90p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f12e9386009p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f12eb11d2bfp paddle::framework::OperatorWithKernel::IndicateDataType(paddle::framework::ExecutionContext const&) const + 1343
3       0x7f12eb11d4afp paddle::framework::OperatorWithKernel::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 47
4       0x7f12e9aef938p paddle::operators::IncrementOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const + 40
5       0x7f12eb11ed6bp paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 235
6       0x7f12eb120ec8p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 728
7       0x7f12eb121141p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
8       0x7f12eb11e74cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
9       0x7f12eaf2b99ap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
10      0x7f12eaf1e010p paddle::framework::details::OpHandleBase::Run(bool) + 160
11      0x7f12eaf00596p paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*) + 310
12      0x7f12eaeff2ffp paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*) + 47
13      0x7f12eaeff6bfp
14      0x7f12ea164993p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
15      0x7f12e9454cd7p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
16      0x7f13765c2a99p
17      0x7f12eaefb432p
18      0x7f12e9456254p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
19      0x7f1371644c80p
20      0x7f13765bb6bap
21      0x7f13762f141dp clone + 109
```

**Comment by jerrywgz** [comment]
本地尝试未能复现，使用相同的paddle commit

**Comment by ccmeteorljh** [comment]
fixed
