### ISSUE TITLE
paddingrnn large static 模型在最新paddle编译下报错，small，static 和 large，padding正常运行

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#17581]
正常运行paddle version： develop 分支。commit-id：97f0ec23578123bea229374686d299098facd320
报错paddle version： develop 分支。commit-id=43d15b9d96530ec60a631fe252510d6fb90190ab；（运行4次，报错3次）

复现方法：
https://github.com/PaddlePaddle/benchmark/blob/master/PaddingRNN/lstm_paddle/run.sh
CUDA_VISIBLE_DEVICES=0 bash run.sh speed large static 20

```bash
I0523 02:55:08.152362 42453 build_strategy.cc:319] SeqOnlyAllReduceOps:0, num_trainers:1
begin to load data
vocab word num 10000
finished load data
Traceback (most recent call last):
  File "train.py", line 511, in <module>
    main()
  File "train.py", line 505, in main
    train()
  File "train.py", line 420, in train
    train_ppl = train_an_epoch(epoch_id, batch_times)
  File "train.py", line 392, in train_an_epoch
    use_program_cache=True)
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/executor.py", line 640, in run
    return_numpy=return_numpy)
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/executor.py", line 502, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator reshape2 error.
Python Callstacks: 
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1702, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 6608, in reshape
    "XShape": x_shape})
  File "/ssd1/ljh/benchmark_daily/benchmark/PaddingRNN/lstm_paddle/lm_model.py", line 253, in lm_model
    init_hidden, shape=[num_layers, -1, hidden_size])
  File "train.py", line 192, in main
    rnn_model=rnn_model)
  File "train.py", line 511, in <module>
    main()
C++ Callstacks: 
VarId 532865824 is not registered. at [/paddle/paddle/fluid/framework/var_type_traits.cc:81]
PaddlePaddle Call Stacks: 
0       0x7f05dac39c90p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f05dac3a009p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f05dca23892p paddle::framework::VarTraitIdToTypeIndex(int) + 962
3       0x7f05dca23929p paddle::framework::ToTypeName(int) + 9
4       0x7f05dc9d8ed9p paddle::framework::RuntimeInferShapeContext::SetOutputDim(std::string const&, paddle::framework::DDim const&) + 153
5       0x7f05db5dd47cp paddle::operators::Reshape2Op::InferShape(paddle::framework::InferShapeContext*) const + 380
6       0x7f05dc9d4d20p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 304
7       0x7f05dc9d5053p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 291
8       0x7f05dc9d274cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
9       0x7f05dc7df99ap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
10      0x7f05dc7d2010p paddle::framework::details::OpHandleBase::Run(bool) + 160
11      0x7f05dc73339cp paddle::framework::details::ThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*) + 316
12      0x7f05dc72e2a7p paddle::framework::details::ThreadedSSAGraphExecutor::RunTracedOps(std::vector<paddle::framework::details::OpHandleBase*, std::allocator<paddle::framework::details::OpHandleBase*> > const&) + 71
13      0x7f05dc7365bbp paddle::framework::details::ThreadedSSAGraphExecutor::RunImpl(std::vector<std::string, std::allocator<std::string> > const&) + 3547
14      0x7f05dc732dc2p paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 482
15      0x7f05dc71ed1ap paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 378
16      0x7f05dadf2c12p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 562
17      0x7f05dac2962ep
18      0x7f05dac6f126p
19      0x7f06b1712ce8p PyEval_EvalFrameEx + 28264
20      0x7f06b171537dp PyEval_EvalCodeEx + 2061
21      0x7f06b1712d70p PyEval_EvalFrameEx + 28400
22      0x7f06b171537dp PyEval_EvalCodeEx + 2061
23      0x7f06b1712d70p PyEval_EvalFrameEx + 28400
24      0x7f06b171537dp PyEval_EvalCodeEx + 2061
25      0x7f06b1712d70p PyEval_EvalFrameEx + 28400
26      0x7f06b171537dp PyEval_EvalCodeEx + 2061
27      0x7f06b1712d70p PyEval_EvalFrameEx + 28400
28      0x7f06b171537dp PyEval_EvalCodeEx + 2061
29      0x7f06b1712d70p PyEval_EvalFrameEx + 28400
30      0x7f06b171537dp PyEval_EvalCodeEx + 2061
31      0x7f06b17154b2p PyEval_EvalCode + 50
32      0x7f06b173f1c2p PyRun_FileExFlags + 146
33      0x7f06b1740559p PyRun_SimpleFileExFlags + 217
34      0x7f06b17561ddp Py_Main + 3149
35      0x7f06b09e9d20p __libc_start_main + 256
36            0x4006b1p
```

**Comment by chengduoZH** [comment]
是模型脚本问题，已经修复
