### ISSUE TITLE
fluid.io.save_inference_model 重复调用报错，提示 var is  not in block

### ISSUE THREAD

**Issue by honghu0829** [PaddlePaddle/Paddle#17744]
paddle 版本 fluid.1.3
 异常现象：
  希望在每次跑完一轮训练后保存模型参数，并执行测试训练任务，发现第一个epoch能够成功没保存模型，但第二个epoch就会失败，见 334 行；
 发现问题后，尝试在第一个epoch就执行两次模型保存，同样出现一样的错误。错误如下：

`
Traceback (most recent call last):
  File "do_Parallel_train.py", line 341, in <module>
    save_infer_params(start_exe, user_infer_params_path, user_infer, config.get_feeding(0)['names'], test_prog)
  File "do_Parallel_train.py", line 103, in save_infer_params
    fluid.io.save_inference_model(path, feeding, [cost], exe, prog)
  File "/home/users/huhong01/baidu/pa/dnn-rec-syc/local_python_venv/lib/python2.7/site-packages/paddle/fluid/io.py", line 995, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "/home/users/huhong01/baidu/pa/dnn-rec-syc/local_python_venv/lib/python2.7/site-packages/paddle/fluid/io.py", line 837, in prepend_feed_ops
    out = global_block.var(name)
  File "/home/users/huhong01/baidu/pa/dnn-rec-syc/local_python_venv/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1129, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var cid not in this block
`

但是两次使用list_vars（） 获取参数列表，都包含 cid 这个lod：
![image](https://user-images.githubusercontent.com/19143947/58606789-8607a580-82cf-11e9-9aab-e2a1b215d346.png)

 ```
import basic_reader
# import cProfile
import basic_network
# from visualdl import LogWriter
# import basic_network
import paddle
from basic_config import BasicConfig
import args
import math
# import cProfile
import time
import os
import sys
import traceback
import numpy as np
import paddle.fluid as fluid
import paddle.fluid.core as core
import paddle.fluid.profiler as profiler
import paddle.fluid.transpiler.distribute_transpiler as distribute_transpiler

# 指定在训练中，每次使用测试集测试时，运行多少个batch
TEST_BATCH = 50
# 指定是否每个epoch结束后，使用验证集合数据获取评估数据
EPOCH_TEST = True

def run_cmd(command):
    log("try run cmd[%s]" % command)
    log("=========== start =============")
    p = os.popen(command)
    res = p.read()
    log("finish and get result:%s" % res)
    log("=========== end ============")

def logerr(line):
    """ print log to stderr """
    print >> sys.stderr, line


def log(line):
    """ print log to stdout"""
    print >> sys.stderr, line


def append_nccl2_prepare(trainer_id, startup_prog):
    """
    see the name
    """
    if trainer_id >= 0:
        # append gen_nccl_id at the end of startup program
        trainer_id = int(os.getenv("PADDLE_TRAINER_ID"))
        port = os.getenv("PADDLE_PSERVER_PORT")
        worker_ips = os.getenv("PADDLE_TRAINER_IPS")
        worker_endpoints = []
        for ip in worker_ips.split(","):
            worker_endpoints.append(':'.join([ip, port]))
        num_trainers = len(worker_endpoints)
        current_endpoint = os.getenv("PADDLE_CURRENT_IP") + ":" + port
        worker_endpoints.remove(current_endpoint)

        nccl_id_var = startup_prog.global_block().create_var(
            name="NCCLID",
            persistable=True,
            type=fluid.core.VarDesc.VarType.RAW)
        startup_prog.global_block().append_op(
            type="gen_nccl_id",
            inputs={},
            outputs={"NCCLID": nccl_id_var},
            attrs={
                "endpoint": current_endpoint,
                "endpoint_list": worker_endpoints,
                "trainer_id": trainer_id
            })
        return nccl_id_var, num_trainers, trainer_id
    else:
        raise Exception("failed to append nccl2, "
                        "must set positive PADDLE_TRAINER_ID env variables for "
                        "nccl-based dist train.")


def save_params(exe, prog, path):
    """
    0 号实例，或本地训练才需要保存参数
    save persistable params
    for incremental training;
    """
    fluid.io.save_persistables(exe, path, prog)
    log("success save params, path=%s" % path)


def save_infer_params(exe, path, cost, feeding, prog):
    """
    保存用于预测的网络参数
    """
    fluid.io.save_inference_model(path, feeding, [cost], exe, prog)
    log("success save params for infer, path=%s" % (path))


def test(cost, tprogram, exe, reader, feeder):
    """
    在训练时，使用验证集来做验证
    """
    costs = []
    aucs = []
    train_begin_time = time.time()
    for idx, data in enumerate(reader()):
        if tprogram is not None:
            avg_cost, auc = exe.run(program=tprogram, feed=feeder.feed(data), fetch_list=cost)
        else:
            avg_cost, auc = exe.run(feed=feeder.feed(data), fetch_list=cost)
        costs.append(avg_cost[0])
        aucs.append(auc[0])
        if idx >= TEST_BATCH: # 避免占用太多时间， 100 个batch 后退出
            break
    train_end_time = time.time()
    return float(sum(costs)) / len(costs), float(sum(aucs)) / len(aucs), (train_end_time - train_begin_time)


if __name__ == '__main__':
    arg = args.parse_args()
    args.print_arg(arg)

    if arg.local == True and arg.gpu == True:
        logerr("failed to start local training, only cpu traing is supported")
        exit(1)
    if arg.local == False and arg.gpu == False:
        logerr("failed to start nccl2 training, only gpu training is supported")
        exit(1)

    # 基础网络配置
    config = BasicConfig(arg.vocab_path, arg.is_vector_input)
    place = basic_network.place_func(arg.gpu)

    # 定义训练过程
    # 定义训练程序
    train_prog = fluid.Program()
    startup_prog = fluid.Program()
    with fluid.program_guard(train_prog, startup_prog):
        with fluid.unique_name.guard():
            [avg_cost, correct, scale_infer, neg_infer, user_infer, prod_infer, reader] = basic_network.basic_cost(config, arg.is_py_reader, arg.batch_size * arg.thread_num)
            sgd_optimizer = basic_network.optimizer_func()
            sgd_optimizer.minimize(avg_cost)
    # 定义test程序
    test_prog = fluid.Program()
    with fluid.program_guard(test_prog, startup_prog):
        with fluid.unique_name.guard():
            test_avg_cost, test_correct, test_scale, test_neg, test_user, test_prod, _ = basic_network.basic_cost(config)
    # 定义数据feeder, 如果使用pyreader，feeder仅在测试和存储网络参数时使用
    # print config.get_feeding(3)
    feed_var_list = [
        train_prog.global_block().var(var_name) for var_name in config.get_feeding(3)["names"]
    ]
    feeder = fluid.DataFeeder(feed_var_list, place)

    if arg.local:
        nccl_id_var, trainer_num, trainer_id = (None, -1, -1)
    else:
        nccl_id_var, trainer_num, trainer_id = (None, 1, int(os.getenv("PADDLE_TRAINER_ID", "0")))
        nccl_id_var, trainer_num, trainer_id = append_nccl2_prepare(trainer_id, startup_prog)
        if trainer_id == 0:
            time.sleep(30) # waite for other trainer
    log("try to start. trainer_num=%d trainer_num=%d" % (trainer_num, trainer_id))

    start_exe = fluid.Executor(place) # start executor
    start_exe.run(startup_prog)
    if arg.local:
        train_exe = fluid.Executor(place)
        test_exe = fluid.Executor(place)
    else:
        strategy = fluid.ExecutionStrategy()
        strategy.num_threads = arg.thread_num
        strategy.allow_op_delay = False
        build_strategy = fluid.BuildStrategy()
        build_strategy.reduce_strategy = fluid.BuildStrategy().ReduceStrategy.AllReduce
        # if args.reduce_strategy == "reduce":
        #    build_strategy.reduce_strategy = fluid.BuildStrategy(
        #    ).ReduceStrategy.Reduce
        #else:
        train_exe = fluid.ParallelExecutor(
            True,
            avg_cost.name,
            main_program=train_prog,
            num_trainers=trainer_num,
            trainer_id=trainer_id,
            exec_strategy=strategy,
            build_strategy=build_strategy
        )
        test_exe = fluid.ParallelExecutor(True,
                main_program=test_prog,
                share_vars_from=train_exe)
    log("success set executor ...")

    # train reader, 可以支持pyreader
    train_f_reader = basic_reader.general_reader(arg.train_data, config, 3) # 3 表示以训练数据的格式读入数据
    if arg.is_py_reader:
        train_reader = reader
        train_reader.decorate_paddle_reader(paddle.batch(train_f_reader, arg.batch_size))
            # paddle.reader.shuffle(paddle.batch(train_f_reader, 256), buf_size=arg.batch_size * 1))
    else:
        train_batchs = paddle.batch(
                paddle.reader.shuffle(train_f_reader, buf_size=arg.batch_size * 2), batch_size=arg.batch_size, drop_last=True)

    # test reader, 暂不支持pyreader
    test_f_reader = basic_reader.general_reader(arg.test_data, config, 3)
    test_reader = paddle.batch(test_f_reader, batch_size=arg.batch_size)
    log("success get reader ...")

    # try load pre train result
    try:
        fluid.io.load_persistables(start_exe, arg.params_path, startup_prog)
        logerr("load pre params success ...")
    except:
        traceback.print_exc()
        logerr("load pre params failed ...")

    # add visualdl_log
    """
    if arg.add_visualdl_log:
        log_writter = LogWriter("./vdl_log", sync_cycle=10)
        with log_writter.mode("train") as logger:
            scalar_loss = logger.scalar(tag="loss")
            histogram = logger.histogram(tag="histogram", num_buckets=30)

    for i in test_prog.global_block().all_parameters():
        print i.name
    """

    over_start_time = time.time()
    step = 0
    for pass_id in range(arg.epoch_num):
        epoch_start_time = time.time() # epoch reset
        log("try start epoch=%d at time %f" % (pass_id, epoch_start_time))

        try:
            if arg.is_py_reader:
                log("epoch=%d, start py reader" % (pass_id))
                train_reader.start()
            else:
                train_reader=train_batchs()

            batch_id = 0
            while True:
                batch_start_time = time.time()
                batch_id += 1

                # train
                if arg.local:
                    if arg.is_py_reader:
                        acost, acorr, p_infer, n_infer, params = train_exe.run(program=train_prog, fetch_list=[avg_cost.name, correct.name, scale_infer.name, neg_infer.name, 'user_1_w'])
                    else:
                        data = next(train_reader)
                        #print data
                        acost, acorr, p_infer, n_infer, params = train_exe.run(program=train_prog, feed=feeder.feed(data), fetch_list=[avg_cost.name, correct.name, scale_infer.name, neg_infer.name, 'user_1_w'])
                else:
                    if arg.is_py_reader:
                        outs = train_exe.run(fetch_list=[avg_cost.name])
                    else:
                        data = next(train_reader)
                        outs = train_exe.run(feed=feeder.feed(data), fetch_list=[avg_cost.name])

                # log train info
                time_cost = time.time() - batch_start_time
                acost = np.array(acost)
                acorr = np.array(acorr)
                #ap = np.array(p_infer)
                #an = np.array(n_infer)
                #print "ap",scale_infer.name
                #print "an",neg_infer.name
                #print "ap",scale_infer.name,ap
                #print "an",neg_infer.name,an
                if batch_id % 100 == 1:
                    log("finish train, epochid=%d batchid=%d time=%f train_cost=%f correct=%f"
                        % (pass_id, batch_id, time_cost, float(acost), float(acorr)/arg.batch_size))
                if arg.add_visualdl_log:
                    step += 1
                    scalar_loss.add_record(step, out)
                    histogram.add_record(step, params.flatten())
                """

                # 训练时，发生cost为无穷大时，直接退出
                # 不再保存相关数据
                # 避免污染模型？？？
                if math.isnan(float(acost)):
                    logerr("failed to train, got NaN loss")
                    exit(1)

                # test job
                if batch_id % arg.batch_for_test == 0:
                    test_cost, test_avg_auc, test_time = test(
                        [avg_cost.name, test_auc.name],
                        test_prog if arg.local else None,
                        test_exe,
                        test_reader,
                        feeder)
                    log("[test] epochid=%d batch_id=%d, time=%f cost=%f auc=%f" %
                                (pass_id, batch_id, test_time, test_cost, test_avg_auc))

                    # 是否需要防止过度训练待验证
                    # if float(np.mean(test_cost, axis = 0)) < 0.09:
                    #    log("epoch=%s, test cost less than 0.1 break" % pass_id)
                    #    break

                # 保存网络参数，可用于增量训练
                if trainer_id <= 0 and batch_id % arg.batch_for_save == 0:
                    save_params(start_exe, train_prog, arg.params_path)

                """

                #if batch_id > 1:
                #    break

        except fluid.core.EOFException as eof:
            logerr("get eof Exception, epoch=%d ..." % (pass_id))
            pass
        except StopIteration:
            logerr("get stop iteration Exception, epoch=%d" % (pass_id))
            pass
        log("finish a epoch, epochid=%d, time_cost=%f" % (pass_id, time.time()-epoch_start_time))

        # epoch 完成后，存储模型参数，并进行一轮测试
        if EPOCH_TEST == True:
            user_infer_params_path = arg.user_infer_params_path + (("_batch_%d") % (pass_id))
            prod_infer_params_path = arg.prod_infer_params_path + (("_batch_%d") % (pass_id))
            save_params(start_exe, train_prog, arg.params_path)
            for i in test_prog.list_vars():
                print i
            print 'ddddddfdfdfdf-------------'
            save_infer_params(start_exe, user_infer_params_path, user_infer, config.get_feeding(0)['names'], test_prog)
            save_infer_params(start_exe, prod_infer_params_path, prod_infer, config.get_feeding(1)['names'], test_prog)

            for i in test_prog.list_vars():
                print i
            save_infer_params(start_exe, user_infer_params_path, user_infer, config.get_feeding(0)['names'], test_prog)
            save_infer_params(start_exe, prod_infer_params_path, prod_infer, config.get_feeding(1)['names'], test_prog)

            prod_result_file = "prod_infer_result.batch_%d" % (pass_id)
            user_result_file = "user_infer_result.batch_%d" % (pass_id)
            prod_infer_cmd="sh do_prod_infer.sh %s %s" % (prod_infer_params_path, prod_result_file)
            user_infer_cmd="sh do_user_infer.sh %s %s %s" % (user_infer_params_path, user_result_file, prod_result_file)
            run_cmd(prod_infer_cmd)
            run_cmd(user_infer_cmd)

        # 注意，如果异常break， py-reader的reset 会异常导致下一个epoch无法正确读入数据
        if arg.is_py_reader:
            log("epoch=%d reset py reader" % (pass_id))
            train_reader.reset()
        else:
            del train_reader

    log("finish train, time_cost=%f" % (time.time()-over_start_time))
    #test_cost, test_batch, test_time = train_test(
    #    avg_cost.name,
    #    test_prog if arg.local else None,
    #    test_exe,
    #    test_reader,
    #    feeder)
    #log("finish test, test_cost=%f, time_cost=%f" % (float(np.mean(test_cost, axis=0)), test_time))

    # 保存网络参数用于预测
    # 由于训练时如果使用py-reader
    # 其如参list会存在异常
    # 保存参数时，统一使用 test-prog 来完成
    if trainer_id <= 0:
        save_params(start_exe, train_prog, arg.params_path)
        # 使用save-infer-params 时，发现第一次调用存储的结果在进行预测时发生异常
        # 原因未知，先额外存储异常user-infer 绕过这个问题
        # save_infer_params(start_exe, arg.user_infer_params_path, user_infer, config.get_feeding(0)['names'], test_prog)
        # save_infer_params(start_exe, arg.complete_infer_params_path, train_score, config.get_feeding(2)['names'], test_prog)
        save_infer_params(start_exe, arg.user_infer_params_path, user_infer, config.get_feeding(0)['names'], test_prog)
        save_infer_params(start_exe, arg.prod_infer_params_path, prod_infer, config.get_feeding(1)['names'], test_prog)
```

**Comment by junjun315** [comment]
save_inference_model 在保存时会进行一些裁剪，有些处理会导致非persistable参数被覆盖。 由于静态图下执行过后网络是固定的，建议只执行一遍save_inference_model, 然后配合save/load _persistable接口来保存断点参数
