### ISSUE TITLE
【1.5】fleet import 失败

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/Paddle#17980]
paddle branch: release/1.5
paddle commit-id : ed3228b73948246ba0f322647b9adde67709e134
```bash
>>> from paddle.fluid.incubate.fleet.parameter_server.distributed_transpiler import fleet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/incubate/fleet/parameter_server/distributed_transpiler/__init__.py", line 23, in <module>
    from ...base.fleet_base import DistributedOptimizer
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/incubate/fleet/base/fleet_base.py", line 18, in <module>
    from enum import Enum
ImportError: No module named enum
```

**Comment by ccmeteorljh** [comment]
#17675
