### ISSUE TITLE
怎样将infer.py打包成一个exe?

### ISSUE THREAD

**Issue by LALAliyao** [PaddlePaddle/Paddle#18007]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by luotao1** [comment]
请问能详细描述下需求么？

**Comment by LALAliyao** [comment]
你好，好的，就是我现在将infer.py写成了一个可执行的脚本文件，传入两个参数，想将其封装为exe供其他程序调用，但是我在封装后，exe文件很大，到了G 的级别，然后传入参数后，也没有反应，就是想知道怎样才可以将exe封装正确。下图就是那个infer.py文件的运行及其参数,谢谢！






------------------ 原始邮件 ------------------
发件人: "Tao Luo"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 晚上8:27
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "一梦千年"<1907381057@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 怎样将infer.py打包成一个exe? (#18007)




请问能详细描述下需求么？

**Comment by luotao1** [comment]
你是用什么程序转的，是windows上的需求么？
> 下图就是那个infer.py文件的运行及其参数

没有看到图。

**Comment by LALAliyao** [comment]
是的，是Windows上的需求，我把那个infer.py给您看下，辛苦了，我把运行的cmd的图再给您发下，，再用附件给您一份，那个TIM 的png格式的就是运行图片，辛苦您啦！
------------------ 原始邮件 ------------------
发件人: "Tao Luo"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 晚上8:41
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "一梦千年"<1907381057@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 怎样将infer.py打包成一个exe? (#18007)




你是用什么程序转的，是windows上的需求么？
  
下图就是那个infer.py文件的运行及其参数
  
没有看到图。

**Comment by luotao1** [comment]
请直接在issue上贴图，邮件回复，issue上看不到图的。

**Comment by LALAliyao** [comment]
python infer.py E:\MFC\ssd_model\ssd_model\000001.jpg  E:\MFC\ssd_model\ssd_model\ssd-model
后面两个路径就是参数，是把infer.py变成了一个函数，然后在下面加了main来调用并执行。

**Comment by LALAliyao** [comment]
D:\test_cloth>infer.exe E:\MFC\ssd_model\ssd_model\000001.jpg E:\MFC\ssd_model\ssd_model\ssd-model
Traceback (most recent call last):
  File "paddle\fluid\framework.py", line 41, in <module>
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer.py", line 9, in <module>
    import paddle.fluid as fluid
  File "C:\Users\19073\AppData\Roaming\Python\Python35\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\fluid\__init__.py", line 18, in <module>
  File "C:\Users\19073\AppData\Roaming\Python\Python35\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\fluid\framework.py", line 50, in <module>
ImportError: NOTE: You may need to run "set PATH=D:\test_cloth;%PATH%"
        if you encounters "DLL load failed" errors. If you have python
        installed in other directory, replace "D:\test_cloth" with your own
        directory. The original error is:
 DLL load failed: 找不到指定的模块。
[448] Failed to execute script infer
报的错误是这样的

**Comment by LALAliyao** [comment]
D:\test_cloth>infer.exe E:\MFC\ssd_model\ssd_model\000001.jpg E:\MFC\ssd_model\ssd_model\ssd-model
Traceback (most recent call last):
  File "paddle\fluid\framework.py", line 41, in <module>
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "infer.py", line 9, in <module>
    import paddle.fluid as fluid
  File "C:\Users\19073\AppData\Roaming\Python\Python35\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\fluid\__init__.py", line 18, in <module>
  File "C:\Users\19073\AppData\Roaming\Python\Python35\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "paddle\fluid\framework.py", line 50, in <module>
ImportError: NOTE: You may need to run "set PATH=D:\test_cloth;%PATH%"
        if you encounters "DLL load failed" errors. If you have python
        installed in other directory, replace "D:\test_cloth" with your own
        directory. The original error is:
 DLL load failed: 找不到指定的模块。
[448] Failed to execute script infer
报的错误是这样的

**Comment by luotao1** [comment]
请问直接运行`python infer.py`，可以正常运行么？

**Comment by wopeizl** [comment]
当前有一个对msvcr120.dll的依赖，需要在系统环境中找到手工打进去（可以放在paddle\libs\目录下，里面有warpctc.dll等其他文件的那个目录），另外python打包exe会比较大，因为相关环境都要打包

**Comment by LALAliyao** [comment]
可以的，而且为什么这个exe会把我的c盘内存吞没看




------------------ 原始邮件 ------------------
发件人: "Tao Luo"<notifications@github.com>;
发送时间: 2019年6月12日(星期三) 上午10:35
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "一梦千年"<1907381057@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 怎样将infer.py打包成一个exe? (#18007)




请问直接运行python infer.py，可以正常运行么？

**Comment by wopeizl** [comment]
内存占用高可能跟打包有关系，你是用pyinstaller这种类似软件么？有可能它在解压过程中会占用大量内存，其实如非的确有必要，不一定非要打包成exe，如果打包exe工具本身有问题，很难最终定位bug在哪里

**Comment by LALAliyao** [comment]
可是我想用c++来调用这个infer.py,之前试过直接用c++调，没有成功，请问这个思路有什么建议吗

------------------ 原始邮件 ------------------
发件人: "wopeizl"<notifications@github.com>;
发送时间: 2019年6月12日(星期三) 上午10:53
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "一梦千年"<1907381057@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [PaddlePaddle/Paddle] 怎样将infer.py打包成一个exe? (#18007)




内存占用高可能跟打包有关系，你是用pyinstaller这种类似软件么？有可能它在解压过程中会占用大量内存，其实如非的确有必要，不一定非要打包成exe，如果打包exe工具本身有问题，很难最终定位bug在哪里

**Comment by wopeizl** [comment]
如果只是预测，用c++直接写也不会太麻烦，如果非要用python，实际上用bat文件也是一样，bat中调用python infer.py即可，其实效果是一样的

**Comment by LALAliyao** [comment]
Traceback (most recent call last):  File "<string>", line 1, in <module>  File "C:\Users\19073\AppData\Local\Programs\Python\Python36\lib\site-packages\infer.py", line 6, in <module>    import paddle.fluid as fluid  File "C:\Users\19073\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\__init__.py", line 194, in <module>    __bootstrap__()  File "C:\Users\19073\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\__init__.py", line 184, in __bootstrap__    core.init_gflags([sys.argv[0]] +AttributeError: module 'sys' has no attribute 'argv'Traceback (most recent call last):  File "<string>", line 1, in <module>NameError: name 'infer' is not defined

 
---原始邮件---
发件人: "wopeizl"<notifications@github.com>
发送时间: 2019年6月12日(星期三) 下午3:54
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"LALAliyao"<1907381057@qq.com>;
主题: Re: [PaddlePaddle/Paddle] 怎样将infer.py打包成一个exe? (#18007)



如果只是预测，用c++直接写也不会太麻烦，如果非要用python，实际上用bat文件也是一样，bat中调用python infer.py即可，其实效果是一样的

**Comment by LALAliyao** [comment]
Traceback (most recent call last):  File "<string>", line 1, in <module>  File "C:\Users\19073\AppData\Local\Programs\Python\Python36\lib\site-packages\infer.py", line 6, in <module>    import paddle.fluid as fluid  File "C:\Users\19073\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\__init__.py", line 194, in <module>    __bootstrap__()  File "C:\Users\19073\AppData\Local\Programs\Python\Python36\lib\site-packages\paddle\fluid\__init__.py", line 184, in __bootstrap__    core.init_gflags([sys.argv[0]] +AttributeError: module 'sys' has no attribute 'argv'Traceback (most recent call last):  File "<string>", line 1, in <module>NameError: name 'infer' is not defined

请问这个错误，是为什么？
 
---原始邮件---
发件人: "wopeizl"<notifications@github.com>
发送时间: 2019年6月12日(星期三) 下午3:54
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"LALAliyao"<1907381057@qq.com>;
主题: Re: [PaddlePaddle/Paddle] 怎样将infer.py打包成一个exe? (#18007)



如果只是预测，用c++直接写也不会太麻烦，如果非要用python，实际上用bat文件也是一样，bat中调用python infer.py即可，其实效果是一样的

**Comment by Microkitty** [comment]
> 
> 
> 当前有一个对msvcr120.dll的依赖，需要在系统环境中找到手工打进去（可以放在paddle\libs\目录下，里面有warpctc.dll等其他文件的那个目录），另外python打包exe会比较大，因为相关环境都要打包

我在linux打包完的程序也不能跑，一直卡着不动，该怎么解决？
