### ISSUE TITLE
Enforce failed. Expected numel() >= 0, but received numel():-3673471787385661952 < 0:0.

### ISSUE THREAD

**Issue by YCYCYCY** [PaddlePaddle/Paddle#18180]
调用parallel_executor，抛出异常
C++ Callstacks: 
Enforce failed. Expected numel() >= 0, but received numel():-3673471787385661952 < 0:0.
When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::Resize has been called first. at [/root/code/Paddle/paddle/fluid/framework/tensor.cc:43]

**Comment by chengduoZH** [comment]
你的模型是怎样的 @YCYCYCY

**Comment by YCYCYCY** [comment]
https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/models/classification/nets.py
ernie_base_net

**Comment by chengduoZH** [comment]
完整的错误log是什么

**Comment by YCYCYCY** [comment]
```
I0618 14:12:29.273175 168684 build_strategy.cc:338] SeqOnlyAllReduceOps:0, num_trainers:1
Traceback (most recent call last):
  File "run_ernie_classifier.py", line 520, in <module>
    main(args)
  File "run_ernie_classifier.py", line 486, in main
    [probs.name], os.path.basename(infer_phase))
  File "run_ernie_classifier.py", line 154, in infer
    batch_probs = exe.run(fetch_list=fetch_list, return_numpy=True)
  File "/home/slurm/job/tmp/job-44875/python/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 280, in run
    return_numpy=return_numpy)
  File "/home/slurm/job/tmp/job-44875/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 665, in run
    return_numpy=return_numpy)
  File "/home/slurm/job/tmp/job-44875/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 527, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator sequence_unpad error.
Python Callstacks: 
  File "/home/slurm/job/tmp/job-44875/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1712, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/slurm/job/tmp/job-44875/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/slurm/job/tmp/job-44875/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 4253, in sequence_unpad
    outputs={'Out': out})
  File "../models/representation/ernie.py", line 52, in ernie_encoder
    unpad_enc_out = fluid.layers.sequence_unpad(enc_out, length=ernie_inputs["seq_lens"])
  File "run_ernie_classifier.py", line 288, in main
    embeddings = ernie_encoder(ernie_inputs, ernie_config=ernie_config)
  File "run_ernie_classifier.py", line 520, in <module>
    main(args)
C++ Callstacks: 
Enforce failed. Expected numel() >= 0, but received numel():-3673471787385661952 < 0:0.
When calling this method, the Tensor's numel must be equal or larger than zero. Please check Tensor::Resize has been called first. at [/root/code/Paddle/paddle/fluid/framework/tensor.cc:43]
PaddlePaddle Call Stacks: 
0       0x7f63d68a40c8p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f63d68a4417p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f63d859ce98p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, paddle::framework::proto::VarType_Type, unsigned long) + 776
3       0x7f63d7649041p paddle::operators::SequenceUnpadOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 961
4       0x7f63d7649293p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CUDADeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7f63d854adaap paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 394
6       0x7f63d854b1a1p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
7       0x7f63d854888cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
8       0x7f63d83864bap paddle::framework::details::ComputationOpHandle::RunImpl() + 298
9       0x7f63d83787c0p paddle::framework::details::OpHandleBase::Run(bool) + 160
10      0x7f63d8359186p paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*) + 310
11      0x7f63d8357defp paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*) + 47
12      0x7f63d83581afp
13      0x7f63d7b91f23p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
14      0x7f63d696f5f7p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
15      0x7f64bfd63973p pthread_once + 83
16      0x7f63d8353b86p
17      0x7f63d83542e6p
18      0x7f63d6970ba4p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 420
19      0x7f64b34108a0p
20      0x7f64bfd5e1c3p
21      0x7f64bf38612dp clone + 109
```

**Comment by kuke** [comment]
@YCYCYCY paddle1.5已经修复这个问题了，本月月底回发布
