### ISSUE TITLE
Deepin Linux 安装错误： /home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/core.so: undefined symbol: mkldnn_primitive_desc_query_pd

### ISSUE THREAD

**Issue by ddayzzz** [PaddlePaddle/Paddle#18254]
- 版本、环境信息：
    1）PaddlePaddle版本：release 1.4
    2）CPU：INTEL I7 6700HQ，MKL=ON，系统中存在MKL
    3）GPU：NVIDIA GTX950M，CUDA9.0和CUDNN7.0
    4）系统环境：Deepin 15, Python3.6(Anaconda)
- 安装方式信息：
1）本地编译：cmake ..  -DPY_VERSION=3.6 -DWITH_FLUID_ONLY=ON -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release; make -j8

编译成功后的输出：
```
[100%] Built target paddle_python
(ml) shu@shu-deepin-laptop:~/Paddle/build$ cd python/dist/
(ml) shu@shu-deepin-laptop:~/Paddle/build/python/dist$ ll
总用量 132324
-rw-r--r-- 1 shu shu 135498974 6月  21 14:17 paddlepaddle_gpu-0.0.0-cp36-cp36m-linux_x86_64.whl
(ml) shu@shu-deepin-laptop:~/Paddle/build/python/dist$ file paddlepaddle_gpu-0.0.0-cp36-cp36m-linux_x86_64.whl 
paddlepaddle_gpu-0.0.0-cp36-cp36m-linux_x86_64.whl: Zip archive data, at least v2.0 to extract
(ml) shu@shu-deepin-laptop:~/Paddle/build/python/dist$ ls -al
总用量 132332
drwxr-xr-x 2 shu shu      4096 6月  21 14:17 .
drwxr-xr-x 7 shu shu      4096 6月  21 14:17 ..
-rw-r--r-- 1 shu shu 135498974 6月  21 14:17 paddlepaddle_gpu-0.0.0-cp36-cp36m-linux_x86_64.whl
(ml) shu@shu-deepin-laptop:~/Paddle/build/python/dist$ ls -al
```
在环境的 python 中输入：
```python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid 
Traceback (most recent call last):
  File "/home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/framework.py", line 41, in <module>
    from . import core
ImportError: /home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/core.so: undefined symbol: mkldnn_primitive_desc_query_pd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 18, in <module>
    from . import framework
  File "/home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/framework.py", line 56, in <module>
    directory. The original error is: \n""" + cpt.get_exception_message(e))
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
        if you encounters "libmkldnn.so not found" errors. If you have python
        installed in other directory, replace "/usr/local/lib" with your own
        directory. The original error is: 
/home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/core.so: undefined symbol: mkldnn_primitive_desc_query_pd
>>> exit()
```
尝试：`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/libs`在 pycharm 中可以正常导入 fluid， 但在终端中，无效（已经 ldconfig）：
```bash
(ml) shu@shu-deepin-laptop:~/Paddle/build/python/dist$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/libs
(ml) shu@shu-deepin-laptop:~/Paddle/build/python/dist$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
Traceback (most recent call last):
  File "/home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/framework.py", line 41, in <module>
    from . import core
ImportError: /home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/core.so: undefined symbol: mkldnn_primitive_desc_query_pd

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 18, in <module>
    from . import framework
  File "/home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/framework.py", line 56, in <module>
    directory. The original error is: \n""" + cpt.get_exception_message(e))
ImportError: NOTE: You may need to run "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH"
        if you encounters "libmkldnn.so not found" errors. If you have python
        installed in other directory, replace "/usr/local/lib" with your own
        directory. The original error is: 
/home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/core.so: undefined symbol: mkldnn_primitive_desc_query_pd
>>> exit()

```

**Comment by luotao1** [comment]
> 在 pycharm 中可以正常导入 fluid， 但在终端中，无效（已经 ldconfig）

请问系统有多个python么？

**Comment by ddayzzz** [comment]
对。使用了anaconda 3, pycharm和终端都指定为同一个虚拟环境。

**Comment by luotao1** [comment]
如果是多个python的话，能否看下
```
ldd /home/shu/miniconda3/envs/ml/lib/python3.6/site-packages/paddle/fluid/core.so
```
mkldnn有没有链接到其他python环境下。

**Comment by ddayzzz** [comment]
系统中有两个 mkl库：
![深度截图_选择区域_20190621221502](https://user-images.githubusercontent.com/22568844/59929076-a5c75f00-9472-11e9-8b10-e564ec2d09ba.png)

是不是paddlepaddle编译所使用自行下载的MKL库与系统的 MKL 库冲突所致？
![深度截图_选择区域_20190621221958](https://user-images.githubusercontent.com/22568844/59929290-1c645c80-9473-11e9-8ccb-3f44b96dce4f.png)

**Comment by luotao1** [comment]
- 从你的ldd截图来看，是指向了`/usr/local/lib`下mkl和mkldnn库了，不是paddle自带的库。两者有冲突的。
- 你能把`/usr/local/lib`从`LD_LIBRARY_PATH`中移走么？或者去掉`/usr/local/lib`里的mkl和mkldnn库，再尝试一下。

**Comment by dagongji10** [comment]
@ddayzzz 请问你解决了这个问题吗？
根据 @luotao1 说的，我移除了`/usr/local/ib64/`里面的库，但是仍然会报错？

**Comment by ddayzzz** [comment]
> 

可以, 我把系统自带的 MKL路径从`LD_LIBRARY_PATH`移除，再开一个终端，然后paddle可以加载自己的MKL库，这个库好像在编译的时候会自动下载，应该在 paddle的安装目录下。
