### ISSUE TITLE
训练提示 TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by XipengY** [PaddlePaddle/Paddle#18276]
确认数据没有问题，batch size也改为1尝试了，还是同样的错误。
Traceback (most recent call last):
  File "apps/anaconda-install/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "apps/anaconda-install/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "apps/anaconda-install/anaconda2/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 585, in __provider_thread__
    raise ex
TypeError: 'NoneType' object is not iterable

应该是数据读取的时候哪里有问题，但是现在根据提示信息，定位不到报错位置。麻烦帮忙看一下。

**Comment by XipengY** [comment]
![image](https://user-images.githubusercontent.com/17317650/59977694-2919b980-9607-11e9-8177-c73f50f88a8f.png)
上图是数据输入的定义
![image](https://user-images.githubusercontent.com/17317650/59977700-38006c00-9607-11e9-8e06-876cc7aae95d.png)
这里是报错中对应的io.py的函数

**Comment by sneaxiy** [comment]
能否给出你使用py_reader训练的那部分代码？

**Comment by XipengY** [comment]
问题解决，修改了reader后，有错误。调试方法是将 multi-processing改为False，单进程读数据，定位reader错误的位置。
