### ISSUE TITLE
py_reader中异常会导致进程夯住无法退出

### ISSUE THREAD

**Issue by walloollaw** [PaddlePaddle/Paddle#18298]
问题描述：
  当py_reader中的用户reader抛出异常后， 程序会被夯住，最终导致进程无法退出，具体复现代码见下面的 `_my_reader`中的  `raise ValueError()`

版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==1.3.1
    3）GPU：K40 cuda9.0 cudnn7
    4）系统环境：python2.7

测试代码如下：
```
import paddle
import paddle.fluid as fluid
import numpy as np


def loss_net(hidden, label):
    prediction = fluid.layers.fc(input=hidden, size=10, act='softmax')
    loss = fluid.layers.cross_entropy(input=prediction, label=label)
    avg_loss = fluid.layers.mean(loss)
    acc = fluid.layers.accuracy(input=prediction, label=label)
    return prediction, avg_loss, acc


def network(img, label):
    img = fluid.layers.fc(input=img, size=200, act='tanh')
    hidden = fluid.layers.fc(input=img, size=200, act='tanh')
    return loss_net(hidden, label)


def test():
    img_data = np.random.rand(20, 3, 20, 20)
    label_data = np.random.randint(0, 10, (20, 1))
    def _my_reader():
        def _reader():
            for i in range(len(img_data)):
                yield (img_data[i], label_data[i])
                if i == 1:
                    raise ValueError('test exception in pyreader') # this line will cause process to be hanged

        return _reader

    reader = fluid.layers.py_reader(capacity=64,
                                    shapes=[(-1, 3, 20, 20), (-1, 1)],
                                    dtypes=['float32', 'int64'])
    reader.decorate_paddle_reader(paddle.batch(_my_reader(), 2))
    img, label = fluid.layers.read_file(reader)
    loss = network(img, label)[1]
    fluid.Executor(fluid.CUDAPlace(0)).run(fluid.default_startup_program())

    exe = fluid.ParallelExecutor(use_cuda=True, loss_name=loss.name)
    for epoch_id in range(10):
        reader.start()
        try:
            while True:
                exe.run(fetch_list=[loss.name])
        except fluid.core.EOFException:
            reader.reset()

if __name__ == "__main__":
    test()
    print('go to exit')
```

错误信息如下(进程处于夯住状态)：
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/wanglong03/tool/python276.withsem/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/wanglong03/tool/python276.withsem/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/wanglong03/tool/python276.withsem/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 566, in __provider_thread__
    for tensors in func():
  File "/home/wanglong03/tool/python276.withsem/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 613, in __tensor_provider__
    for slots in paddle_reader():
  File "/home/wanglong03/tool/python276.withsem/lib/python2.7/site-packages/paddle/fluid/data_feeder.py", line 286, in __reader_creator__
    for item in reader():
  File "/home/wanglong03/tool/python276.withsem/lib/python2.7/site-packages/paddle/batch.py", line 35, in batch_reader
    for instance in r:
  File "test_pyreader.py", line 28, in _reader
    raise ValueError('test exception in pyreader')
ValueError: test exception in pyreader
```

**Comment by JiabinYang** [comment]
这个问题已经在1.4的版本中修复了，请使用最新版本PaddlePaddle

**Comment by walloollaw** [comment]
确认，在paddlepaddle-gpu.1.4.1验证通过
