### ISSUE TITLE
StopIteration

### ISSUE THREAD

**Issue by zheng5yu9** [PaddlePaddle/Paddle#1834]
文本处理，在执行  bash ./preprocess.sh  报错，什么原因
root@74060277ac06:/home/Paddle/demo/quick_start# bash ./preprocess.sh 
Start to preprcess...
Traceback (most recent call last):
  File "preprocess.py", line 359, in <module>
    main()
  File "preprocess.py", line 355, in main
    data_creator.create_dataset()
  File "preprocess.py", line 172, in create_dataset
    train_data, train_lab_set = self.data_list(self.train_dir)
  File "preprocess.py", line 132, in data_list
    label_set = get_label_set_from_dir(path)
  File "/usr/local/lib/python2.7/dist-packages/paddle/utils/preprocess_util.py", line 88, in get_label_set_from_dir
    dirs = list_dirs(path)
  File "/usr/local/lib/python2.7/dist-packages/paddle/utils/preprocess_util.py", line 55, in list_dirs
    os.path.join(path, d) for d in next(os.walk(path))[1]
StopIteration

**Comment by qingqing01** [comment]
这是demo里的quick start吗？ 看运行输出的log不像是这个demo吧，如果是quick start，可以依据脚本  https://github.com/PaddlePaddle/Paddle/blob/develop/demo/quick_start/data/get_data.sh 下载已经处理好的数据~

**Comment by QiJune** [comment]
长时间没有更新，暂时close；如有进一步更新，欢迎reopen
