### ISSUE TITLE
deeplab模型cpu预测，报错：dilation in convolution is not implemented yet

### ISSUE THREAD

**Issue by OliverLPH** [PaddlePaddle/Paddle#18363]
- 标题：deeplab模型cpu预测，报错：dilation in convolution is not implemented yet
- 版本、环境信息：
    1）PaddlePaddle版本：1.5 或CommitID：401c03fc20478f5cc067440422fc3a7b306d0e32
    2）CPU：Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    4）系统环境：centos 6.1，Python版本 2.7
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
```
GIT COMMIT ID: 401c03fc20478f5cc067440422fc3a7b306d0e32
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
CUDA version: 10.0
CUDNN version: v7
```
    2）CMake包含路径的完整命令
```shell
cmake .. -DPY_VERSION=2.7 -DWITH_FLUID_ONLY=ON -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_PYTHON=ON  -DWITH_ANAKIN=ON -DPYTHON_EXECUTABLE:FILEPATH=/opt/_internal/cpython-2.7.11-ucs2/bin/python2.7 -DPYTHON_INCLUDE_DIR:PATH=/opt/_internal/cpython-2.7.11-ucs2/include/python2.7 -DPYTHON_LIBRARIES:FILEPATH=/opt/_internal/cpython-2.7.11-ucs2/lib/libpython2.7.so
```
    3）API信息（如调用请提供）
    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）
- 复现信息：如为报错，请给出复现环境、复现步骤

用的python api的预测，
```python
config = core.AnalysisConfig(prog_file, params_file)
config = core.AnalysisConfig('benchmark')
config.set_model("./deeplabv3pluse_gn_model")
config.disable_gpu()
config.set_cpu_math_library_num_threads(8)
config.enable_mkldnn()
predictor = core.create_paddle_predictor(config)
output = predictor.run(tensor)
```
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

```
Traceback (most recent call last):
  File "main.py", line 60, in <module>
    main()
  File "main.py", line 37, in main
    model.run(tensor, warmup, repeat)
  File "/lipeihan01/inference_benchmark1.5/benchmark/benchmark.py", line 110, in run
    output = self.predictor.run(tensor)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator conv2d error.
Python Callstacks:
  File "/home/users/dangqingqing/.jumbo/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1469, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/dangqingqing/.jumbo/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/dangqingqing/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 2062, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "/home/users/dangqingqing/tmp/models/fluid/PaddleCV/deeplabv3+/models.py", line 87, in conv
    return append_op_result(fluid.layers.conv2d(*args, **kargs), 'conv')
  File "/home/users/dangqingqing/tmp/models/fluid/PaddleCV/deeplabv3+/models.py", line 165, in seperate_conv
    use_cudnn=depthwise_use_cudnn)
  File "/home/users/dangqingqing/tmp/models/fluid/PaddleCV/deeplabv3+/models.py", line 206, in xception_block
    act=relu)
  File "/home/users/dangqingqing/tmp/models/fluid/PaddleCV/deeplabv3+/models.py", line 254, in exit_flow
    activation_fn_in_separable_conv=True)
  File "/home/users/dangqingqing/tmp/models/fluid/PaddleCV/deeplabv3+/models.py", line 324, in deeplabv3p
    data = exit_flow(data)
  File "eval.py", line 87, in <module>
    logit = deeplabv3p(img)

C++ Callstacks:
dilation in convolution is not implemented yet at [/lipeihan01/Paddle/paddle/fluid/operators/mkldnn/conv_mkldnn_op.cc:136]
PaddlePaddle Call Stacks:
0       0x7f6df43cdf00p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f6df43ce279p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f6df4892531p paddle::operators::ConvMKLDNNOpKernel<float, float>::ComputeFP32(paddle::framework::ExecutionContext const&) const + 5409
3       0x7f6df48937ecp _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform8CPUPlaceELb0ELm0EINS0_9operators18ConvMKLDNNOpKernelIffEEEEclEPKcSE_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_ + 76
4       0x7f6df6247627p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
5       0x7f6df6247913p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 291
6       0x7f6df6244ffcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
7       0x7f6df61faaa3p paddle::framework::NaiveExecutor::Run() + 211
8       0x7f6df45d83d8p paddle::AnalysisPredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int) + 184
9       0x7f6df44eabf6p
10      0x7f6df4400e26p
11      0x7f6e58b36b68p PyEval_EvalFrameEx + 28264
12      0x7f6e58b391fdp PyEval_EvalCodeEx + 2061
13      0x7f6e58b36bf0p PyEval_EvalFrameEx + 28400
14      0x7f6e58b36d1ep PyEval_EvalFrameEx + 28702
15      0x7f6e58b391fdp PyEval_EvalCodeEx + 2061
16      0x7f6e58b39332p PyEval_EvalCode + 50
17      0x7f6e58b630c2p PyRun_FileExFlags + 146
18      0x7f6e58b64459p PyRun_SimpleFileExFlags + 217
19      0x7f6e58b7a27dp Py_Main + 3149
20      0x7f6e57e0dd20p __libc_start_main + 256
21            0x4006b1p
```
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/14963836/60232989-09b5b180-98d1-11e9-966a-607cd667dead.png">

**Comment by luotao1** [comment]
从代码截图看，conv_mkldnn_op没有实现这个功能。可以去掉`config.enable_mkldnn()`这行。

**Comment by OliverLPH** [comment]
> 从代码截图看，conv_mkldnn_op没有实现这个功能。可以去掉`config.enable_mkldnn()`这行。

噢噢，确实是mkldnn的问题，多谢
