### ISSUE TITLE
分布式MPI集群训练，使用multiprocess_reader出错

### ISSUE THREAD

**Issue by wawltor** [PaddlePaddle/Paddle#18367]
具体日志地址:http://10.104.150.48:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20190627134148-8206/

使用multiprocess_reader会出现如下问题：

Traceback (most recent call last):
  File "/home/disk1/normandy/maybach/app-user-20190627134148-8206/workspace/python27-gcc482/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/disk1/normandy/maybach/app-user-20190627134148-8206/workspace/python27-gcc482/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/disk1/normandy/maybach/app-user-20190627134148-8206/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/reader/decorator.py", line 218, in read_worker
    for d in r:
  File "/home/disk1/normandy/maybach/app-user-20190627134148-8206/workspace/env_run/reader.py", line 169, in work
    for data in rd():
  File "/home/disk1/normandy/maybach/app-user-20190627134148-8206/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/reader/decorator.py", line 400, in queue_reader
    queue = multiprocessing.Queue(queue_size)
  File "/home/disk1/normandy/maybach/app-user-20190627134148-8206/workspace/python27-gcc482/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/home/disk1/normandy/maybach/app-user-20190627134148-8206/workspace/python27-gcc482/lib/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/home/disk1/normandy/maybach/app-user-20190627134148-8206/workspace/python27-gcc482/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/home/disk1/normandy/maybach/app-user-20190627134148-8206/workspace/python27-gcc482/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied

**Comment by frankwhzhang** [comment]
厂内mpi 不支持share memory通信 改为use_pipe=True
