### ISSUE TITLE
tf2fluid加载转换后的模型时报错

### ISSUE THREAD

**Issue by yanwb** [PaddlePaddle/Paddle#18404]
```shell
C:\program\Anaconda3\python.exe D:/python/Python_workspace/tf2fluid/result.py
Traceback (most recent call last):
  File "D:/python/Python_workspace/tf2fluid/result.py", line 4, in <module>
    model = ml.ModelLoader("paddle_model", use_cuda=False)
  File "D:\python\Python_workspace\tf2fluid\model_loader.py", line 42, in __init__
    fluid.io.load_vars(self.exe, model_dir, vars=var_list)
  File "C:\program\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 610, in load_vars
    executor.run(load_prog)
  File "C:\program\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 565, in run
    use_program_cache=use_program_cache)
  File "C:\program\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 642, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator load error.
Python Callstacks: 
  File "C:\program\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\program\Anaconda3\lib\site-packages\paddle\fluid\io.py", line 596, in load_vars
    attrs={'file_path': os.path.join(dirname, new_var.name)})
  File "D:\python\Python_workspace\tf2fluid\model_loader.py", line 42, in __init__
    fluid.io.load_vars(self.exe, model_dir, vars=var_list)
  File "D:/python/Python_workspace/tf2fluid/result.py", line 4, in <module>
    model = ml.ModelLoader("paddle_model", use_cuda=False)
C++ Callstacks: 
Enforce failed. Expected version == 0U, but received version:10 != 0U:0.
Only version 0 is supported at [D:\1.4.1\paddle\paddle\fluid\framework\tensor_util.cc:453]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.

Process finished with exit code 1
```

**Comment by jiangjiajun** [comment]
你好，X2Paddle目前在Windows环境中转换存在问题，此问题我们后续会更新代码解决，目前建议先使用Linux/Mac进行转换，谢谢。
