### ISSUE TITLE
 Mac 1.5版本python2.7下用VSCode运行代码报RuntimeError: already started

### ISSUE THREAD

**Issue by imistyrain** [PaddlePaddle/Paddle#18491]
- 标题：Mac 1.5版本python2.7下用VSCode运行代码报RuntimeError: already started
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号 1.5
    2）CPU：厂内标配i5, 无mkl
    3）GPU：无
    4）系统环境：Mac OS 10.14
之前用1.4版本在VSCode运行的好好的代码，在VSCode里跑报RuntimeError: already started, 在外面单独跑的话没问题，用python3.5在VSCode里跑也没问题
```
            Traceback (most recent call last):
              File "/Users/***/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/log.py", line 110, in g
                return f(*args, **kwargs)
              File "/Users/***/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/pydevd_hooks.py", line 74, in start_client
                sock, start_session = daemon.start_client((host, port))
              File "/Users/gongyanhe/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 214, in start_client
                with self.started():
              File "/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 17, in __enter__
                return self.gen.next()
              File "/Users/***/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 110, in started
                self.start()
              File "/Users/***/.vscode/extensions/ms-python.python-2019.3.6558/pythonFiles/lib/python/ptvsd/daemon.py", line 145, in start
                raise RuntimeError('already started')
            RuntimeError: already started
```

**Comment by biubug6** [comment]
@imistyrain 请问解决了吗？ 也在厂内遇到这个问题....

**Comment by imistyrain** [comment]
没, 换python3了
