### ISSUE TITLE
ctr训练中出现Invoke operator create_double_buffer_reader error.

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#18608]
[13:15:25]W:	 [Step 3/3] 2019-07-11 13:15:25,286 - INFO - run local training
[13:15:25]W:	 [Step 3/3] I0711 13:15:25.293337 26634 parallel_executor.cc:355] The number of CPUPlace, which is used in ParallelExecutor, is 8. And the Program will be copied 8 copies
[13:15:31]W:	 [Step 3/3] Traceback (most recent call last):
[13:15:31]W:	 [Step 3/3]   File "train.py", line 262, in <module>
[13:15:31]W:	 [Step 3/3]     train()
[13:15:31]W:	 [Step 3/3]   File "train.py", line 232, in train
[13:15:31]W:	 [Step 3/3]     train_loop(args, main_program, py_reader, loss, auc_var, batch_auc_var, 1, 0)
[13:15:31]W:	 [Step 3/3]   File "train.py", line 167, in train_loop
[13:15:31]W:	 [Step 3/3]     loss_val, auc_val, batch_auc_val = pe.run(fetch_list=[loss.name, auc_var.name, batch_auc_var.name])
[13:15:31]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 280, in run
[13:15:31]W:	 [Step 3/3]     return_numpy=return_numpy)
[13:15:31]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/executor.py", line 644, in run
[13:15:31]W:	 [Step 3/3]     raise e
[13:15:31]W:	 [Step 3/3] paddle.fluid.core_avx.EnforceNotMet: Invoke operator create_double_buffer_reader error.
[13:15:31]W:	 [Step 3/3] Python Callstacks: 
[13:15:31]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1773, in append_op
[13:15:31]W:	 [Step 3/3]     attrs=kwargs.get("attrs", None))
[13:15:31]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 1004, in __create_unshared_decorated_reader__
[13:15:31]W:	 [Step 3/3]     attrs=attrs)
[13:15:31]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 1111, in double_buffer
[13:15:31]W:	 [Step 3/3]     'create_double_buffer_reader', reader, attrs, name=name)
[13:15:31]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 563, in _py_reader
[13:15:31]W:	 [Step 3/3]     double_buffer_reader = double_buffer(reader, name=double_buffer_name)
[13:15:31]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/layers/io.py", line 885, in create_py_reader_by_data
[13:15:31]W:	 [Step 3/3]     feed_list=feed_list)
[13:15:31]W:	 [Step 3/3]   File "/workspace/modelce/tasks/ctr/network_conf.py", line 136, in ctr_dnn_model
[13:15:31]W:	 [Step 3/3]     use_double_buffer=True)
[13:15:31]W:	 [Step 3/3]   File "train.py", line 211, in train
[13:15:31]W:	 [Step 3/3]     loss, auc_var, batch_auc_var, py_reader, _ = ctr_dnn_model(args.embedding_size, args.sparse_feature_dim)
[13:15:31]W:	 [Step 3/3]   File "train.py", line 262, in <module>
[13:15:31]W:	 [Step 3/3]     train()
[13:15:31]W:	 [Step 3/3] C++ Callstacks: 
[13:15:31]W:	 [Step 3/3] reader_ should not be null
[13:15:31]W:	 [Step 3/3]  at [/workspace/paddle/fluid/framework/reader.h:71]
[13:15:31]W:	 [Step 3/3] PaddlePaddle Call Stacks: 
[13:15:31]W:	 [Step 3/3] 0       0x7fbf70f0d558p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
[13:15:31]W:	 [Step 3/3] 1       0x7fbf70f0d8a7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
[13:15:31]W:	 [Step 3/3] 2       0x7fbf72e16579p paddle::operators::reader::BufferedReader::BufferedReader(std::shared_ptr<paddle::framework::ReaderBase> const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 2873
[13:15:31]W:	 [Step 3/3] 3       0x7fbf71d566ebp paddle::operators::reader::CreateDoubleBufferReaderOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 587
[13:15:31]W:	 [Step 3/3] 4       0x7fbf72ef3b5cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
[13:15:31]W:	 [Step 3/3] 5       0x7fbf72cf6c75p paddle::framework::details::OpHandleBase::RunAndRecordEvent(std::function<void ()()> const&) + 773
[13:15:31]W:	 [Step 3/3] 6       0x7fbf72cf027bp paddle::framework::details::ComputationOpHandle::RunImpl() + 107
[13:15:31]W:	 [Step 3/3] 7       0x7fbf72cb7396p paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*) + 310
[13:15:31]W:	 [Step 3/3] 8       0x7fbf72cb5fffp paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*) + 47
[13:15:31]W:	 [Step 3/3] 9       0x7fbf72cb63bfp
[13:15:31]W:	 [Step 3/3] 10      0x7fbf71151b83p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()(), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
[13:15:31]W:	 [Step 3/3] 11      0x7fbf70fd8497p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()()>&, bool&) + 39
[13:15:31]W:	 [Step 3/3] 12      0x7fbfa650ce03p pthread_once + 83
[13:15:31]W:	 [Step 3/3] 13      0x7fbf72cb1a42p
[13:15:31]W:	 [Step 3/3] 14      0x7fbf70fd9a14p _ZZN10ThreadPoolC1EmENKUlvE_clEv + 404
[13:15:31]W:	 [Step 3/3] 15      0x7fbf9aba9470p
[13:15:31]W:	 [Step 3/3] 16      0x7fbfa6507aa1p
[13:15:31]W:	 [Step 3/3] 17      0x7fbfa5bc9bcdp clone + 109

**Comment by kolinwei** [comment]
commit id:1c10dac4f2903524f801061ef4eb684c4ad636d3 是好的
commit id: 076f83311094e073eb2a60b495fa48ae25793a5e 出现改问题

**Comment by kolinwei** [comment]
怀疑PR17911/PR18255

**Comment by kolinwei** [comment]
已修复
