### ISSUE TITLE
EnforceNotMet: Invoke operator elementwise_add error.

### ISSUE THREAD

**Issue by SunChao3555** [PaddlePaddle/Paddle#18749]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5
    2）aistudio 环境

- 问题描述：
**我使用RetinaNet利用aistudio进行训练时，FPN中的纵向横向拼接出现维度不一致无法对应相加，**
FPN部分代码如下
class FPN(object):
    """
    Feature Pyramid Network, see https://arxiv.org/abs/1612.03144

    Args:
        num_chan (int): number of feature channels
        min_level (int): lowest level of the backbone feature map to use
        max_level (int): highest level of the backbone feature map to use
        spatial_scale (list): feature map scaling factor
        has_extra_convs (bool): whether has extral convolutions in higher levels
    """

    def __init__(self,
                 num_chan=256,
                #  min_level=2,
                #  max_level=6,
                #  spatial_scale=[1. / 32., 1. / 16., 1. / 8., 1. / 4.],
                #  has_extra_convs=False
                 min_level=3,
                 max_level=7,
                 spatial_scale=[0.03125,0.0625,0.125],
                 has_extra_convs=True
                 ):
        self.num_chan = num_chan
        self.min_level = min_level
        self.max_level = max_level
        self.spatial_scale = spatial_scale
        self.spatial_scale_cp=spatial_scale
        self.has_extra_convs = has_extra_convs

    def _add_topdown_lateral(self, body_name, body_input, upper_output):
        lateral_name = 'fpn_inner_' + body_name + '_lateral'
        topdown_name = 'fpn_topdown_' + body_name
        fan = body_input.shape[1]
        # print('body_input:',body_input[1],body_input[2],body_input[3],) #19
        
        lateral = fluid.layers.conv2d(
            body_input,
            self.num_chan,
            1,
            param_attr=ParamAttr(
                name=lateral_name + "_w", initializer=Xavier(fan_out=fan)),
            bias_attr=ParamAttr(
                name=lateral_name + "_b",
                learning_rate=2.,
                regularizer=L2Decay(0.)),
            name=lateral_name)
        # lateral=np.expand_dims(lateral,-1)
        #UpSampling
        shape = fluid.layers.shape(upper_output)
        # print('upper_output:',upper_output.shape[1],upper_output.shape[2],upper_output.shape[3],)### 10 
        shape_hw = fluid.layers.slice(shape, axes=[0], starts=[2], ends=[4])
        shape_hw.stop_gradient = True
        out_shape_ = shape_hw * 2
        out_shape = fluid.layers.cast(out_shape_, dtype='int32')
        out_shape.stop_gradient = True
        topdown = fluid.layers.resize_nearest(
            upper_output, scale=2., actual_shape=out_shape, name=topdown_name)
        print('td:',topdown.shape[1],topdown.shape[2],topdown.shape[3])              #20
        print('lat:',lateral.shape[1],lateral.shape[2],lateral.shape[3],)            #19
        
        return lateral + topdown
        # return fluid.layers.elementwise_add(lateral,topdown)

    def get_output(self, body_dict):
        """
        Add FPN onto backbone.

        Args:
            body_dict(OrderedDict): Dictionary of variables and each element is the
                output of backbone.

        Return:
            fpn_dict(OrderedDict): A dictionary represents the output of FPN with
                their name.
            spatial_scale(list): A list of multiplicative spatial scale factor.
        """
        self.spatial_scale=[0.03125, 0.0625, 0.125]  #########################################################
        body_name_list = list(body_dict.keys())[::-1]
        num_backbone_stages = len(body_name_list)
        self.fpn_inner_output = [[] for _ in range(num_backbone_stages)]
        fpn_inner_name = 'fpn_inner_' + body_name_list[0]
        body_input = body_dict[body_name_list[0]]
       
        fan = body_input.shape[1]
        self.fpn_inner_output[0] = fluid.layers.conv2d(
            body_input,
            self.num_chan,
            1,
            param_attr=ParamAttr(
                name=fpn_inner_name + "_w", initializer=Xavier(fan_out=fan)),
            bias_attr=ParamAttr(
                name=fpn_inner_name + "_b",
                learning_rate=2.,
                regularizer=L2Decay(0.)),
            name=fpn_inner_name)
       
        for i in range(1, num_backbone_stages):
            body_name = body_name_list[i]
            body_input = body_dict[body_name]
            top_output = self.fpn_inner_output[i - 1]
            fpn_inner_single = self._add_topdown_lateral(body_name, body_input,top_output)
            self.fpn_inner_output[i] = fpn_inner_single
        fpn_dict = {}
        fpn_name_list = []
        for i in range(num_backbone_stages):
            fpn_name = 'fpn_' + body_name_list[i]
            fan = self.fpn_inner_output[i].shape[1] * 3 * 3
            fpn_output = fluid.layers.conv2d(
                self.fpn_inner_output[i],
                self.num_chan,
                filter_size=3,
                padding=1,
                param_attr=ParamAttr(
                    name=fpn_name + "_w", initializer=Xavier(fan_out=fan)),
                bias_attr=ParamAttr(
                    name=fpn_name + "_b",
                    learning_rate=2.,
                    regularizer=L2Decay(0.)),
                name=fpn_name)
            fpn_dict[fpn_name] = fpn_output
            fpn_name_list.append(fpn_name)
        if not self.has_extra_convs and self.max_level - self.min_level == len(
                self.spatial_scale):
            body_top_name = fpn_name_list[0]
            body_top_extension = fluid.layers.pool2d(
                fpn_dict[body_top_name],
                1,
                'max',
                pool_stride=2,
                name=body_top_name + '_subsampled_2x')
            fpn_dict[body_top_name + '_subsampled_2x'] = body_top_extension
            fpn_name_list.insert(0, body_top_name + '_subsampled_2x')
            self.spatial_scale.insert(0, self.spatial_scale[0] * 0.5)
        # Coarser FPN levels introduced for RetinaNet
        highest_backbone_level = self.min_level + len(self.spatial_scale) - 1
        print('********',self.spatial_scale)
        if self.has_extra_convs and self.max_level > highest_backbone_level:
          
            fpn_blob = body_dict[body_name_list[0]]
            for i in range(highest_backbone_level + 1, self.max_level + 1):
                fpn_blob_in = fpn_blob
                fpn_name = 'fpn_' + str(i)
                if i > highest_backbone_level + 1:
                    fpn_blob_in = fluid.layers.relu(fpn_blob)
                fan = fpn_blob_in.shape[1] * 3 * 3
                fpn_blob = fluid.layers.conv2d(
                    input=fpn_blob_in,
                    num_filters=self.num_chan,
                    filter_size=3,
                    stride=2,
                    padding=1,
                    param_attr=ParamAttr(
                        name=fpn_name + "_w", initializer=Xavier(fan_out=fan)),
                    bias_attr=ParamAttr(
                        name=fpn_name + "_b",
                        learning_rate=2.,
                        regularizer=L2Decay(0.)),
                    name=fpn_name)
                fpn_dict[fpn_name] = fpn_blob
                fpn_name_list.insert(0, fpn_name)
                self.spatial_scale.insert(0, self.spatial_scale[0] * 0.5)
        res_dict = OrderedDict([(k, fpn_dict[k]) for k in fpn_name_list])
        return res_dict, self.spatial_scale
**但是用自己的linux环境跑官方给出的也会出现维度少一维的情况但并没有报错**
希望能够帮忙解决一下，弄了好久了，谢谢！！！！
td: 256 20 20
lat: 256 19 19
td: 256 38 38
lat: 256 38 38
******** [0.03125, 0.0625, 0.125]
5 5
loading annotations into memory...
Done (t=26.15s)
creating index...
index created!
loading annotations into memory...

import ujson error: No module named 'ujson' use json

Done (t=0.52s)
creating index...
index created!
----------------------------------------------------------------------------------------
错误信息如下
---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-210-df2a10a8e915> in <module>
     30           train_file_list=train_file_list,
     31           val_file_list=val_file_list)
---> 32 main()
<ipython-input-210-df2a10a8e915> in main()
     29           train_parameters,
     30           train_file_list=train_file_list,
---> 31           val_file_list=val_file_list)
     32 main()
<ipython-input-208-32f2592d8d20> in train(data_args, train_params, train_file_list, val_file_list)
    142                 start_time = time.time()
    143                 if parallel:
--> 144                     loss_v, = train_exe.run(fetch_list=[loss.name])
    145                 else:
    146                     loss_v, = exe.run(train_prog, fetch_list=[loss])
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/parallel_executor.py in run(self, fetch_list, feed, feed_dict, return_numpy)
    278                              feed=feed,
    279                              fetch_list=fetch_list,
--> 280                              return_numpy=return_numpy)
    281 
    282     @property
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    663                 fetch_list=fetch_list,
    664                 fetch_var_name=fetch_var_name,
--> 665                 return_numpy=return_numpy)
    666         elif program._is_inference:
    667             return self._run_inference(program._executor, feed)
/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/executor.py in _run_parallel(self, program, scope, feed, fetch_list, fetch_var_name, return_numpy)
    525 
    526         fetch_var_names = list(map(_to_name_str, fetch_list))
--> 527         exe.run(fetch_var_names, fetch_var_name)
    528         arr = scope.find_var(fetch_var_name).get_lod_tensor_array()
    529 
EnforceNotMet: Invoke operator elementwise_add error.
Python Callstacks: 
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/layers/math_op_patch.py", line 149, in __impl__
    attrs={'axis': axis})
  File "<ipython-input-200-906ca1ec6f03>", line 77, in _add_topdown_lateral
    return lateral + topdown
  File "<ipython-input-200-906ca1ec6f03>", line 117, in get_output
    fpn_inner_single = self._add_topdown_lateral(body_name, body_input,top_output)
  File "<ipython-input-201-21fc0d0484a8>", line 41, in build
    body_feats, spatial_scale = self.fpn.get_output(body_feats)
  File "<ipython-input-201-21fc0d0484a8>", line 57, in train
    return self.build(feed_vars, 'train')
  File "<ipython-input-206-46e9e565bf81>", line 30, in build_program
    train_var=model.train(feed_vars={'image':image, 'im_info':im_info, 'gt_box':gt_box, 'gt_label':gt_label, 'is_crowd':is_crowd})
  File "<ipython-input-208-32f2592d8d20>", line 35, in train
    is_train=True)
  File "<ipython-input-210-df2a10a8e915>", line 31, in main
    val_file_list=val_file_list)
  File "<ipython-input-210-df2a10a8e915>", line 32, in <module>
    main()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3265, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3189, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3018, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2843, in _run_cell
    return runner(coro)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2817, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tornado/gen.py", line 1080, in __init__
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tornado/gen.py", line 346, in wrapper
    runner = Runner(result, future, yielded)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 370, in dispatch_queue
    yield self.process_one()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/asyncio/base_events.py", line 1425, in _run_once
    handle._run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
C++ Callstacks: 
Enforce failed. Expected x_dims[i + axis] == y_dims[i], but received x_dims[i + axis]:19 != y_dims[i]:20.
Broadcast dimension mismatch. at [/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:63]

**Comment by SunChao3555** [comment]
希望能提供一下解决方案，感谢感谢！！
