### ISSUE TITLE
fluid1.5 PyReader设置了iterable=True，TypeError: object of type 'generator' has no len()

### ISSUE THREAD

**Issue by sshilei** [PaddlePaddle/Paddle#18778]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/map/program/paddlepaddle/bin/incubator/cpu/1.5.0/paddle_release_home/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/map/program/paddlepaddle/bin/incubator/cpu/1.5.0/paddle_release_home/python/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/map/program/paddlepaddle/bin/incubator/cpu/1.5.0/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/reader.py", line 428, in __thread_main__
    raise ex
TypeError: object of type 'generator' has no len()

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/map/program/paddlepaddle/bin/incubator/cpu/1.5.0/paddle_release_home/python/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/map/program/paddlepaddle/bin/incubator/cpu/1.5.0/paddle_release_home/python/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/map/program/paddlepaddle/bin/incubator/cpu/1.5.0/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/reader.py", line 428, in __thread_main__
    raise ex
TypeError: object of type 'generator' has no len()

![image](https://user-images.githubusercontent.com/18701471/61773864-373a4000-ae28-11e9-8e33-11c7f464f099.png)

![image](https://user-images.githubusercontent.com/18701471/61775752-170c8000-ae2c-11e9-808c-c0d6adf919e3.png)

**Comment by sshilei** [comment]
通过， yield SamplePyReader.generate_sample(dataset_instance, line) 生成样本就会报上面的错误，把generate_sample函数展开到调用的地方就没问题

![image](https://user-images.githubusercontent.com/18701471/61777869-4624f080-ae30-11e9-9cb4-a3814ea8ebde.png)

**Comment by sshilei** [comment]
辛苦帮忙确认一下原因

**Comment by guoshengCS** [comment]
` 通过， yield SamplePyReader.generate_sample(dataset_instance, line) 生成样本就会报上面的错误，把generate_sample函数展开到调用的地方就没问题`
这两个是有差别的，红框中那行调用`SampleReader.generate_sample(dataset_instance, line)`是一个generator，这个应该不是期望的，期望的应该是yield数据，就像展开到调用的地方那种
