### ISSUE TITLE
ValueError: Data Type mismatch: 2 to 5

### ISSUE THREAD

**Issue by Cristhine** [PaddlePaddle/Paddle#18783]
概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.5
    2）CPU
    3）GPU：GPU，cuda0.8
    4）系统环境：python2.7
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    train()
  File "train.py", line 46, in train
    model.build_model()
  File "/home/*/code/yolov3_drive/models/yolov3.py", line 222, in build_model
    combine_lbls = fluid.layers.concat(input=[self.gt_attrib_smoke_labels, self.gt_attrib_phone_labels, self.gt_attrib_safe_labels, self.gt_attrib_hand_labels, self.gt_attrib_forward_labels], axis=1)
  File "/home/*/app/python-cuda8-paddle-0.15.1/lib/python2.7/site-packages/paddle/fluid/layers/tensor.py", line 205, in concat
    out = helper.create_variable_for_type_inference(dtype=helper.input_dtype())
  File "/home/*/app/python-cuda8-paddle-0.15.1/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 98, in input_dtype
    (dtype, each.dtype))
ValueError: Data Type mismatch: 2 to 5

报错代码是：combine_lbls = fluid.layers.concat(input=[self.gt_attrib_smoke_labels, self.gt_attrib_phone_labels, self.gt_attrib_safe_labels, self.gt_attrib_hand_labels, self.gt_attrib_forward_labels], axis=1) 
concat的数据例如（self.gt_attrib_smoke_labels）格式是：
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT32
      dims: -1
      dims: 1
    }
    lod_level: 1
  }
}
persistable: false

**Comment by guoshengCS** [comment]
这个是因为concat的`self.gt_attrib_smoke_labels, self.gt_attrib_phone_labels, self.gt_attrib_safe_labels, self.gt_attrib_hand_labels, self.gt_attrib_forward_labels`这些输入中存在数据类型不同的，还请确认下
