### ISSUE TITLE
请教一些使用问题？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#18837]
# 环境
 - PaddlePaddle  dev 版本

# 问题
话不多少，上一个demo，
```python
import paddle.fluid as fluid
import numpy as np

BATCH_SIZE = 384
data1 = fluid.layers.data(name="input1", shape=[2], dtype="float32")
data2 = fluid.layers.data(name="input2", shape=[1], dtype="float32")


def cls_ohem(cls_prob, label):
    zeros = fluid.layers.zeros_like(label)
    ones = fluid.layers.zeros_like(label) + 1

    # 把小于等于0的都设置为0
    cond = fluid.layers.cast(fluid.layers.greater_than(label, zeros), dtype='int64')
    ie = fluid.layers.IfElse(cond)
    with ie.true_block():
        ie.output(ones)

    with ie.false_block():
        ie.output(zeros)
    label_filter_invalid = ie()[0]

    # 类别size[2*batch]
    num_cls_prob = fluid.layers.size(cls_prob)
    cls_prob_reshpae = fluid.layers.reshape(cls_prob, [num_cls_prob, -1])
    label_int = fluid.layers.cast(label_filter_invalid, np.int32)
    label_int = fluid.layers.squeeze(label_int, axes=[])

    # 获取batch数
    num_row = BATCH_SIZE
    # 对应某一batch而言，batch*2为非人类别概率，batch*2+1为人概率类别,indices为对应 cls_prob_reshpae
    # 应该的真实值，后续用交叉熵计算损失
    row = fluid.layers.range(0, num_row * 2, 2, np.int32)
    indices_ = row + label_int

    # 真实标签对应的概率
    label_prob = fluid.layers.squeeze(fluid.layers.gather(cls_prob_reshpae, indices_), axes=[])
    loss = 0 - fluid.layers.log(label_prob + 1e-10)
    zeros = fluid.layers.zeros_like(label_prob)

    # 统计 0 和 1 的数量
    valid_inds = fluid.layers.where(fluid.layers.greater_equal(label, zeros))
    num_valid = fluid.layers.reduce_sum(valid_inds)

    # 选取70%的数据
    keep_num = fluid.layers.cast(num_valid * 0.7, dtype=np.int32)

    # 只选取 0 和 1的70%损失
    loss1 = loss * valid_inds
    loss, _ = fluid.layers.topk(loss1, k=keep_num)
    return fluid.layers.reduce_mean(loss)


loss = cls_ohem(data1, data2)

place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())

d1 = []
for i in range(BATCH_SIZE):
    r = np.random.rand()
    d1.append([r, 1 - r])

d1 = np.random.rand(BATCH_SIZE, 2).astype(np.float32)
d2 = np.array(np.random.randint(-2, 2, [BATCH_SIZE, 1])).astype('float32')


r = exe.run(program=fluid.default_main_program(),
            feed={"input1": d1, "input2": d2},
            fetch_list=[loss])

print(r)
```

错误信息为
```
C++ Callstacks: 
Tensor holds the wrong type, it holds int64_t, but desires to be bool at [/paddle/paddle/fluid/framework/tensor_impl.h:45]
PaddlePaddle Call Stacks: 
```

**Comment by Superjomn** [comment]
有更全的 stack 信息吗？

**Comment by yeyupiaoling** [comment]
@Superjomn 
全部错误信息，上面是完整的代码，你可以测试一下
```
Traceback (most recent call last):
  File "/media/test/50480C02480BE596/Users/1596/PycharmProjects/PaddlePaddle-MTCNN/train/test.py", line 71, in <module>
    fetch_list=[loss])
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/executor.py", line 644, in run
    raise e
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/executor.py", line 640, in run
    use_program_cache=use_program_cache)
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/executor.py", line 669, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/executor.py", line 766, in _run_program
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator merge_lod_tensor error.
Python Callstacks: 
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/framework.py", line 1773, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layers/control_flow.py", line 133, in merge_lod_tensor
    attrs={'level': level})
  File "/home/test/PaddlePaddle_Python3.5/lib/python3.5/site-packages/paddle/fluid/layers/control_flow.py", line 1696, in __call__
    level=0))
  File "/media/test/50480C02480BE596/Users/1596/PycharmProjects/PaddlePaddle-MTCNN/train/test.py", line 21, in cls_ohem
    label_filter_invalid = ie()[0]
  File "/media/test/50480C02480BE596/Users/1596/PycharmProjects/PaddlePaddle-MTCNN/train/test.py", line 54, in <module>
    loss = cls_ohem(data1, data2)
C++ Callstacks: 
Tensor holds the wrong type, it holds int64_t, but desires to be bool at [/paddle/paddle/fluid/framework/tensor_impl.h:45]
PaddlePaddle Call Stacks: 
0       0x7f3e8e9cf550p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f3e8e9cf8c9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f3e8e9da6a7p bool* paddle::framework::Tensor::data<bool>() + 231
3       0x7f3e8f1b7f01p paddle::operators::MergeLoDTensorOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 881
4       0x7f3e90b4835cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
5       0x7f3e8eb5875ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 398
6       0x7f3e8eb5b7afp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
7       0x7f3e8e9c0d3dp
8       0x7f3e8ea01e46p
9             0x4e9bc7p PyCFunction_Call + 119
10            0x529885p PyEval_EvalFrameEx + 23173
11            0x52d2e3p
12            0x529332p PyEval_EvalFrameEx + 21810
13            0x52d2e3p
14            0x529332p PyEval_EvalFrameEx + 21810
15            0x52d2e3p
16            0x528eeep PyEval_EvalFrameEx + 20718
17            0x52d2e3p
18            0x52dfdfp PyEval_EvalCode + 31
19            0x5fd2c2p
20            0x5ff76ap PyRun_FileExFlags + 154
21            0x5ff95cp PyRun_SimpleFileExFlags + 444
22            0x63e7d6p Py_Main + 1110
23            0x4cfe41p main + 225
24      0x7f3ecb439830p __libc_start_main + 240
25            0x5d5f29p _start + 41
```

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/62101733-08f5ae00-b2c9-11e9-9091-681ff9ee70a0.png)

看起来，cond 必须返回 bool 型

**Comment by yeyupiaoling** [comment]
@Superjomn 我把类型设置为bool也是报同样的错误
```python
# 把小于等于0的都设置为0
    cond = fluid.layers.cast(fluid.layers.greater_than(label, zeros), dtype='bool')
    ie = fluid.layers.IfElse(cond)
```

**Comment by yeyupiaoling** [comment]
@Superjomn 您能帮我跑通这个例子吗？真的很需要呢、
