### ISSUE TITLE
如何动态获取lod_level=1 shape=[fea_size] data的batch_size，以动态构造一个[batch_size, fea_size]的0矩阵

### ISSUE THREAD

**Issue by kelvict** [PaddlePaddle/Paddle#18851]
如何动态获取lod_level=1 shape=[fea_size] data的batch_size，以动态构造一个[batch_size, fea_size]的0矩阵

**Comment by Superjomn** [comment]
带 lod 与否 tensor 的 batch_size 应该是不变的，直接获取应该就可以了

**Comment by kelvict** [comment]
下面的demo是利用lod_level=1的tensor **key**来获取一个[batch_size, fea_size]的0 tensor，但我用的是fluid 1.4.1，不能通过变换key来获得[batch_size, fea_size]的tensor，然后再用zeros_like。
下面的程序会报错。
````
import numpy as np
import paddle.fluid as fluid

key = fluid.layers.data(name="key", shape=[3], lod_level=1, dtype='float32')
query = fluid.layers.data(name="query", shape=[4], dtype='float32')
expanded_query = fluid.layers.sequence_expand_as(query, key)

query_key = fluid.layers.concat([expanded_query, key], axis=1)
place = fluid.core.CPUPlace()
exe = fluid.Executor(place) #创建执行器
exe.run(fluid.default_startup_program()) #网络参数初始化
key_val = np.asarray(range(12), dtype=np.float32).reshape([4, 3])
key_lod = [[3, 1]]
query_val = -np.asarray(range(8), dtype=np.float32).reshape([2, 4])

new_zeros = fluid.layers.zeros(shape=[fluid.layers.shape(key)[0], 3], dtype="float32")

ret = exe.run(feed={'key': fluid.create_lod_tensor(key_val, key_lod, place),
					'query': query_val},
			  fetch_list=[key, query, expanded_query,
			              query_key, new_zeros,
			              ], return_numpy=False)
print key
print query
print [np.asarray(i) for i in ret]
````

````
Traceback (most recent call last):
  File "/Users/kelvin_zhang/PycharmProjects/learn_fluid/test_sequence_expand.py", line 20, in <module>
    new_zeros = fluid.layers.zeros(shape=[fluid.layers.shape(key)[0], 3], dtype="float32")
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/layers/tensor.py", line 626, in zeros
    return fill_constant(value=0.0, **locals())
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/layers/tensor.py", line 402, in fill_constant
    stop_gradient=True)
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1654, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1053, in __init__
    self._update_desc_attr(attr_name, attr_val)
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1228, in _update_desc_attr
    self.desc._set_attr(name, val)
TypeError: _set_attr(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core.OpDesc, arg0: unicode, arg1: Variant) -> None

Invoked with: <paddle.fluid.core.OpDesc object at 0x121bca570>, u'shape', [name: "s.h.a.p.e._.0...t.m.p._.0_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT32
      dims: 1
    }
  }
}
persistable: false
, 3]

Process finished with exit code 1
````

**Comment by Superjomn** [comment]
@phlrain 是不是需要runtime shape 推导的支持？

**Comment by kelvict** [comment]
```
key_size = 3
key = fluid.layers.data(name="key", shape=[key_size], lod_level=1, dtype='float32')
param = fluid.layers.create_parameter(shape=[1, key_size], dtype="float32")
const_bs_like = fluid.layers.fill_constant_batch_size_like(key, shape=[1, 1], dtype="float32", value=1.0)
param_expand = fluid.layers.matmul(const_bs_like, param)
```
