### ISSUE TITLE
data loader 部分多进程训练失败

### ISSUE THREAD

**Issue by XipengY** [PaddlePaddle/Paddle#18916]
版本、环境信息：
   1）PaddlePaddle版本：1.5.0
   2）GPU：GPU：k40， cuda：9.0 cudnn：7.0
   4）系统环境：centos6.3，Python2.7

问题描述：
data reader部分，如果use_multiprocess = False,能正常train；设置use_multiprocess = True，train报错，错误信息如下：
Exception in thread Thread-1:
Traceback (most recent call last):
  File "python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "python2.7/site-packages/paddle/fluid/layers/io.py", line 593, in __provider_thread__
    raise ex
TypeError: 'NoneType' object is not iterable

**Comment by NHZlX** [comment]
把reader的代码贴上来吧

```
TypeError: 'NoneType' object is not iterable
```

看起来是reader中没有读出东西来，检查一下reader是否有写错

**Comment by XipengY** [comment]
应该没问题，同样的reader，但进程能正常train

**Comment by NHZlX** [comment]
重新rerun后，目前没有问题。
