### ISSUE TITLE
保存了inference model，预测时希望使用ParallelExecutor，应该怎么操作？

### ISSUE THREAD

**Issue by Renwb1991** [PaddlePaddle/Paddle#18922]
保存了inference model，预测时希望使用ParallelExecutor，应该怎么操作？

**Comment by NHZlX** [comment]
您好，请问用parallel Executor是为了模型加速么？

**Comment by Renwb1991** [comment]
这边有很多图片，需要进行预测。使用多卡ParallelExecutor应该会快些吧。

**Comment by Renwb1991** [comment]
现在是这样写的，直接使用parallel_predict进行预测，会出错。
```
class NeXtVLADClassifier:
    """base classification predict"""
    def __init__(self, use_gpu, dirname):
        """ init """
        place = fluid.CUDAPlace(0) if use_gpu else fluid.CPUPlace()
        self.exe = fluid.Executor(place)

        [inference_program, feed_target_names, fetch_list] = \
            fluid.io.load_inference_model(dirname=dirname, executor=self.exe, \
            model_filename=dirname+'/model', params_filename=dirname+'/params')

        self.parallel_exe = fluid.ParallelExecutor(use_cuda=True, main_program=inference_program.clone(for_test=True))

        feed_list = [inference_program.global_block().var(var_name) for var_name in feed_target_names]
        self.feeder = fluid.DataFeeder(place=place, feed_list=feed_list)
        self.inference_program = inference_program
        self.fetch_list = fetch_list

    def predict(self, batch_data):
        """ predict """
        result = self.exe.run(self.inference_program, fetch_list=self.fetch_list, feed=self.feeder.feed(batch_data))
        return result

    def parallel_predict(self, batch_data):
        result = self.parallel_exe.run(fetch_list=self.fetch_list, feed=self.feeder.feed(batch_data))
        return result
```
错误信息如下：
```
*** EnforceNotMet: Invoke operator feed error.
Python Callstacks: 
  File "/home/renwenbin/tools/python276.withsem/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1725, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/home/renwenbin/tools/python276.withsem/lib/python2.7/site-packages/paddle/fluid/io.py", line 845, in prepend_feed_ops
    attrs={'col': i})
  File "/home/renwenbin/tools/python276.withsem/lib/python2.7/site-packages/paddle/fluid/io.py", line 1000, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "convert_model.py", line 107, in save_inference_model
    model_filename='model', params_filename='params')
  File "convert_model.py", line 140, in convert
    infer.save_inference_model(args.model_path)
  File "convert_model.py", line 146, in main
    convert(args)
  File "convert_model.py", line 150, in <module>
    main()
C++ Callstacks: 
Enforce failed. Expected static_cast<size_t>(col) < feed_list.size(), but received static_cast<size_t>(col):0 >= feed_list.size():0.
```

**Comment by NHZlX** [comment]
确认一下读取 batch_data的reader是否有把数据正确读出

**Comment by Renwb1991** [comment]
有的，相同的batch_data数据，使用predict方法进行预测，是能够正常产出的。

**Comment by Renwb1991** [comment]
而使用 parallel_predict 方法进行预测，则提示出错。

如果先使用 predict 方法进行预测，然后再使用 parallel_predict 方法预测，那么parallel_predict 方法就不会出错了。是不是中间漏了些什么步骤？

**Comment by NHZlX** [comment]
把所有的log信息贴出来把

**Comment by Renwb1991** [comment]
```
Traceback (most recent call last):
  File "infer_aiflow.py", line 31, in <module>
    infermain()
  File "infer_aiflow.py", line 27, in infermain
    infer.main()
  File "/home/renwenbin/icode/baidu/aiflow-tools/game-video/nextvlad_infer/infer.py", line 96, in main
    infer(args)
  File "/home/renwenbin/icode/baidu/aiflow-tools/game-video/nextvlad_infer/infer.py", line 66, in infer
    loss, test_label_eval, test_predictions_eval = classifier.parallel_predict(test_data_feat)
  File "/home/renwenbin/icode/baidu/aiflow-tools/game-video/nextvlad_infer/nextvlad_classifier.py", line 53, in parallel_predict
    result = self.parallel_exe.run(fetch_list=self.fetch_list, feed=self.feeder.feed(batch_data))
  File "/home/renwenbin/tools/python276.withsem/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 205, in run
    return_numpy=return_numpy)
  File "/home/renwenbin/tools/python276.withsem/lib/python2.7/site-packages/paddle/fluid/executor.py", line 580, in run
    return_numpy=return_numpy)
  File "/home/renwenbin/tools/python276.withsem/lib/python2.7/site-packages/paddle/fluid/executor.py", line 446, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator feed error.
Python Callstacks: 
  File "/home/renwenbin/tools/python276.withsem/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1725, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/home/renwenbin/tools/python276.withsem/lib/python2.7/site-packages/paddle/fluid/io.py", line 845, in prepend_feed_ops
    attrs={'col': i})
  File "/home/renwenbin/tools/python276.withsem/lib/python2.7/site-packages/paddle/fluid/io.py", line 1000, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "convert_model.py", line 107, in save_inference_model
    model_filename='model', params_filename='params')
  File "convert_model.py", line 140, in convert
    infer.save_inference_model(args.model_path)
  File "convert_model.py", line 146, in main
    convert(args)
  File "convert_model.py", line 150, in <module>
    main()
C++ Callstacks: 
Enforce failed. Expected static_cast<size_t>(col) < feed_list.size(), but received static_cast<size_t>(col):1 >= feed_list.size():0.
 at [/paddle/paddle/fluid/operators/controlflow/feed_op.cc:53]
PaddlePaddle Call Stacks: 
0       0x7f0fe3163b68p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f0fe3163eb7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f0fe48d5a2ap paddle::operators::FeedOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 3050
3       0x7f0fe4df378cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
4       0x7f0fe4c0202ap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
5       0x7f0fe4bf50e0p paddle::framework::details::OpHandleBase::Run(bool) + 160
6       0x7f0fe4b5c7adp
7       0x7f0fe3ecfdf3p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
8       0x7f0fe3231c97p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
9       0x7f102959e973p pthread_once + 83
10      0x7f0fe4b5c342p
11      0x7f0fe3232fd4p ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const + 404
12      0x7f101976e8a0p
13      0x7f10295991c3p
14      0x7f102831212dp clone + 109
```

**Comment by Renwb1991** [comment]
给出一个简单的demo, 在单卡的情况下，使用 parallel_exe 进行预测，总是出错。而使用 exe 预测则没有问题。
```
import os
import paddle
import paddle.fluid as fluid
import numpy as np

def build_progrom(is_train, main_prog, startup_prog):
    with fluid.program_guard(main_prog, startup_prog):
        x = fluid.layers.data(name='x', shape=[13], dtype='float32')
        y = fluid.layers.data(name='y', shape=[1], dtype='float32')
        y_predict = fluid.layers.fc(input=x, size=1, act=None)
        cost = fluid.layers.square_error_cost(input=y_predict, label=y)
        avg_cost = fluid.layers.mean(cost)
        if is_train:
            moment_optimizer = fluid.optimizer.MomentumOptimizer(learning_rate=0.001, momentum=0.9)
            moment_optimizer.minimize(avg_cost)
    return [avg_cost, x, y]


def save_model(model_save_dir, exe, train_prog, test_prog, test_feed_list, test_fetch_list):
    """ save model """
    model_path = os.path.join(model_save_dir + "/model")
    if model_path is not None:
        if not os.path.isdir(model_path):
            os.makedirs(model_path)
        fluid.io.save_persistables(exe, model_path + '/persistable', main_program=train_prog)
        fluid.io.save_inference_model(
            model_path + '/inference', feeded_var_names=[feed.name for feed in test_feed_list],
            target_vars=test_fetch_list, executor=exe, main_program=test_prog,
            model_filename='model', params_filename='params')

def train():
    place = fluid.CPUPlace()
    startup_prog = fluid.Program()
    train_prog = fluid.Program()
    test_prog = fluid.Program()
    
    train_vars = build_progrom(True, train_prog, startup_prog)
    test_vars = build_progrom(False, test_prog, startup_prog)
    test_prog = test_prog.clone(for_test=True)
    
    train_fetch_list = [train_vars[0]]
    train_reader = paddle.batch(
        paddle.dataset.uci_housing.test(), batch_size=1)
    train_feeder = fluid.DataFeeder(place=place, feed_list=train_vars[1:])

    test_fetch_list = [test_vars[0], test_vars[2]]
    test_reader = paddle.batch(
        paddle.dataset.uci_housing.test(), batch_size=1)
    test_feed_list = test_vars[1:]
    test_feeder = fluid.DataFeeder(place=place, feed_list=test_feed_list)
    exe = fluid.Executor(place)
    exe.run(startup_prog)
    for i in range(1):
        for data in train_reader():
            result = exe.run(train_prog, feed=train_feeder.feed(data), fetch_list=train_fetch_list)
            print "train:", result
        
        for data in test_reader():
            result = exe.run(test_prog, feed=test_feeder.feed(data), fetch_list=test_fetch_list)
            print "test:", result
    save_model('output', exe, train_prog, test_prog, test_feed_list, test_fetch_list) 


def infer():
    place = fluid.CUDAPlace(0)
    exe = fluid.Executor(place)
    dirname = 'output/model/inference'
    [inference_program, feed_target_names, fetch_list] = \
            fluid.io.load_inference_model(dirname=dirname, executor=exe, \
            model_filename=dirname+'/model', params_filename=dirname+'/params')

    parallel_exe = fluid.ParallelExecutor(use_cuda=True, main_program=inference_program)

    feed_list = [inference_program.global_block().var(var_name) for var_name in feed_target_names]
    feeder = fluid.DataFeeder(place=place, feed_list=feed_list)

    
    infer_reader = paddle.batch(
        paddle.dataset.uci_housing.test(), batch_size=1)
    for data in infer_reader(): 
        #result = exe.run(inference_program, fetch_list=fetch_list, feed=feeder.feed(data))
        result = parallel_exe.run(fetch_list=fetch_list, feed=feeder.feed(data))
        print "infer:", result


if __name__ == "__main__":
    train()
    infer()
```

**Comment by NHZlX** [comment]
这个问题现在怀疑是个bug， 已经进行反馈

**Comment by chengduoZH** [comment]
该问题正在修复中。
