### ISSUE TITLE
dialogue_general_understanding 报Invoke operator lookup_table error

### ISSUE THREAD

**Issue by kolinwei** [PaddlePaddle/Paddle#18994]
18:23:55]W:	 [Step 3/3] I0803 18:23:55.831578 27089 build_strategy.cc:308] SeqOnlyAllReduceOps:0, num_trainers:1
[18:23:55]W:	 [Step 3/3] I0803 18:23:55.935079 27089 parallel_executor.cc:331] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
[18:24:25]W:	 [Step 3/3] Traceback (most recent call last):
[18:24:25]W:	 [Step 3/3]   File "train.py", line 444, in <module>
[18:24:25]W:	 [Step 3/3]     main(args)
[18:24:25]W:	 [Step 3/3]   File "train.py", line 299, in main
[18:24:25]W:	 [Step 3/3]     outputs = train_exe.run(fetch_list=fetch_list)
[18:24:25]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 280, in run
[18:24:25]W:	 [Step 3/3]     return_numpy=return_numpy)
[18:24:25]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/executor.py", line 614, in run
[18:24:25]W:	 [Step 3/3]     raise e
[18:24:25]W:	 [Step 3/3] paddle.fluid.core_avx.EnforceNotMet: Invoke operator lookup_table error.
[18:24:25]W:	 [Step 3/3] Python Callstacks: 
[18:24:25]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1776, in append_op
[18:24:25]W:	 [Step 3/3]     attrs=kwargs.get("attrs", None))
[18:24:25]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
[18:24:25]W:	 [Step 3/3]     return self.main_program.current_block().append_op(*args, **kwargs)
[18:24:25]W:	 [Step 3/3]   File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 507, in embedding
[18:24:25]W:	 [Step 3/3]     'padding_idx': padding_idx
[18:24:25]W:	 [Step 3/3]   File "../../models/dialogue_model_toolkit/dialogue_general_understanding/bert.py", line 96, in _build_model
[18:24:25]W:	 [Step 3/3]     is_sparse=False)
[18:24:25]W:	 [Step 3/3]   File "../../models/dialogue_model_toolkit/dialogue_general_understanding/bert.py", line 86, in __init__
[18:24:25]W:	 [Step 3/3]     self._build_model(src_ids, position_ids, sentence_ids, input_mask)
[18:24:25]W:	 [Step 3/3]   File "../../models/dialogue_model_toolkit/dialogue_general_understanding/create_model.py", line 59, in create_model
[18:24:25]W:	 [Step 3/3]     use_fp16=args.use_fp16)
[18:24:25]W:	 [Step 3/3]   File "train.py", line 160, in main
[18:24:25]W:	 [Step 3/3]     paradigm_inst=paradigm_inst)
[18:24:25]W:	 [Step 3/3]   File "train.py", line 444, in <module>
[18:24:25]W:	 [Step 3/3]     main(args)
[18:24:25]W:	 [Step 3/3] C++ Callstacks: 
[18:24:25]W:	 [Step 3/3] holder_ should not be null
[18:24:25]W:	 [Step 3/3] Tensor holds no memory. Call Tensor::mutable_data first. at [/workspace/paddle/fluid/framework/tensor.cc:23]
[18:24:25]W:	 [Step 3/3] PaddlePaddle Call Stacks: 
[18:24:25]W:	 [Step 3/3] 0       0x7f4169087b58p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
[18:24:25]W:	 [Step 3/3] 1       0x7f4169087ea7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
[18:24:25]W:	 [Step 3/3] 2       0x7f416b1b2529p paddle::framework::Tensor::check_memory_size() const + 185
[18:24:25]W:	 [Step 3/3] 3       0x7f41690924d9p long const* paddle::framework::Tensor::data<long>() const + 25
[18:24:25]W:	 [Step 3/3] 4       0x7f4169b3c23ep paddle::operators::LookupTableCUDAKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 1134
[18:24:25]W:	 [Step 3/3] 5       0x7f4169b3c943p _ZNSt17_Function_handlerIFvRKN6paddle9framework16ExecutionContextEEZNKS1_24OpKernelRegistrarFunctorINS0_8platform9CUDAPlaceELb0ELm0EINS0_9operators21LookupTableCUDAKernelIfEENSA_IdEENSA_INS7_7float16EEEEEclEPKcSH_iEUlS4_E_E9_M_invokeERKSt9_Any_dataS4_ + 35
[18:24:25]W:	 [Step 3/3] 6       0x7f416b15eacbp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 411
[18:24:25]W:	 [Step 3/3] 7       0x7f416b15f0c1p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
[18:24:25]W:	 [Step 3/3] 8       0x7f416b15c43cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
[18:24:25]W:	 [Step 3/3] 9       0x7f416af5ea26p paddle::framework::details::ComputationOpHandle::RunImpl() + 166
[18:24:25]W:	 [Step 3/3] 10      0x7f416ae9b5bcp paddle::framework::details::ThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*) + 316
[18:24:25]W:	 [Step 3/3] 11      0x7f416ae963b5p
[18:24:25]W:	 [Step 3/3] 12      0x7f41692c5c13p std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()(), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&) + 35
[18:24:25]W:	 [Step 3/3] 13      0x7f4169152be7p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()()>&, bool&) + 39
[18:24:25]W:	 [Step 3/3] 14      0x7f41f5a48e03p pthread_once + 83
[18:24:25]W:	 [Step 3/3] 15      0x7f416ae95ea2p
[18:24:25]W:	 [Step 3/3] 16      0x7f4169154164p _ZZN10ThreadPoolC1EmENKUlvE_clEv + 404
[18:24:25]W:	 [Step 3/3] 17      0x7f4188f00470p
[18:24:25]W:	 [Step 3/3] 18      0x7f41f5a43aa1p
[18:24:25]W:	 [Step 3/3] 19      0x7f41f5105bcdp clone + 109

**Comment by kolinwei** [comment]
怀疑 PR18836

**Comment by sneaxiy** [comment]
该错误是挂在了BERT模型4卡处，在训练阶段第2个epoch的第70个step后报lookup_table op错。

CE运行脚本在[此处](https://github.com/PaddlePaddle/models/blob/develop/PaddleNLP/dialogue_model_toolkit/dialogue_general_understanding/.run_ce.sh)，报错信息为：
```
Traceback (most recent call last):
  File "train.py", line 447, in <module>
    main(args)
  File "train.py", line 300, in main
    outputs = train_exe.run(fetch_list=fetch_list)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 280, in run
    return_numpy=return_numpy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 614, in run
    raise e
paddle.fluid.core_avx.EnforceNotMet: Invoke operator lookup_table error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1776, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 507, in embedding
    'padding_idx': padding_idx
  File "../../models/dialogue_model_toolkit/dialogue_general_understanding/bert.py", line 96, in _build_model
    is_sparse=False)
  File "../../models/dialogue_model_toolkit/dialogue_general_understanding/bert.py", line 86, in __init__
    self._build_model(src_ids, position_ids, sentence_ids, input_mask)
  File "../../models/dialogue_model_toolkit/dialogue_general_understanding/create_model.py", line 59, in create_model
    use_fp16=args.use_fp16)
  File "train.py", line 160, in main
    paradigm_inst=paradigm_inst)
  File "train.py", line 447, in <module>
    main(args)
C++ Callstacks: 
holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/Paddle/Paddle/paddle/fluid/framework/tensor.cc:23]
PaddlePaddle Call Stacks: 
0       0x7fd8c78fc47dp void paddle::platform::EnforceNotMet::Init<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int) + 509
1       0x7fd8c9ab9f2ap paddle::framework::Tensor::check_memory_size() const + 2906
2       0x7fd8c7907276p long const* paddle::framework::Tensor::data<long>() const + 38
3       0x7fd8c8768930p paddle::operators::LookupTableCUDAKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 864
4       0x7fd8c8768f3fp std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::LookupTableCUDAKernel<float>, paddle::operators::LookupTableCUDAKernel<double>, paddle::operators::LookupTableCUDAKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 47
5       0x7fd8c9a45a07p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 359
6       0x7fd8c9a468d7p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 487
7       0x7fd8c9a3fb7ep paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 318
8       0x7fd8c9769056p paddle::framework::details::ComputationOpHandle::RunImpl() + 166
9       0x7fd8c967c6ccp paddle::framework::details::ThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*) + 364
10      0x7fd8c9676320p
11      0x7fd8c9676840p
12      0x7fd8c7a04a8ep std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) + 46
13      0x7fd92f50da99p
14      0x7fd8c967616dp
15      0x7fd8c7a065c4p std::thread::_Impl<std::_Bind_simple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1} ()> >::_M_run() + 340
16      0x7fd922df1c80p
17      0x7fd92f5066bap
18      0x7fd92f23c41dp clone + 109
```

这个[PR#18836](https://github.com/PaddlePaddle/Paddle/pull/18836)将GC默认打开。但我发现BERT这个模型可能有问题，表现在：
1. 单卡运行不会报错。
2. 关闭GC后，用原CE脚本（`exec_strategy.num_iteration_per_drop_scope = 10`）不会报错；但如果将`exec_strategy.num_iteration_per_drop_scope = 1` 同样在lookup_table op处报错，报错信息为：
```
Traceback (most recent call last):
  File "train.py", line 444, in <module>
    main(args)
  File "train.py", line 299, in main
    outputs = train_exe.run(fetch_list=fetch_list)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/parallel_executor.py", line 280, in run
    return_numpy=return_numpy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 614, in run
    raise e
paddle.fluid.core_avx.EnforceNotMet: Invoke operator lookup_table error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1776, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 507, in embedding
    'padding_idx': padding_idx
  File "../../models/dialogue_model_toolkit/dialogue_general_understanding/bert.py", line 96, in _build_model
    is_sparse=False)
  File "../../models/dialogue_model_toolkit/dialogue_general_understanding/bert.py", line 86, in __init__
    self._build_model(src_ids, position_ids, sentence_ids, input_mask)
  File "../../models/dialogue_model_toolkit/dialogue_general_understanding/create_model.py", line 59, in create_model
    use_fp16=args.use_fp16)
  File "train.py", line 160, in main
    paradigm_inst=paradigm_inst)
  File "train.py", line 444, in <module>
    main(args)
C++ Callstacks: 
Enforce failed. Expected ids_dims[ids_rank - 1] == 1, but received ids_dims[ids_rank - 1]:0 != 1:1.
The last dimension of the 'Ids' tensor must be 1. at [/Paddle/Paddle/paddle/fluid/operators/lookup_table_op.cc:43]
PaddlePaddle Call Stacks: 
0       0x7fca481f247dp void paddle::platform::EnforceNotMet::Init<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char const*, int) + 509
1       0x7fca481f316dp paddle::platform::EnforceNotMet::EnforceNotMet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, int) + 125
2       0x7fca490533eap paddle::operators::LookupTableOp::InferShape(paddle::framework::InferShapeContext*) const + 2010
3       0x7fca4a33be19p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 1401
4       0x7fca4a33c8d7p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 487
5       0x7fca4a335b7ep paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 318
6       0x7fca4a05f056p paddle::framework::details::ComputationOpHandle::RunImpl() + 166
7       0x7fca49f726ccp paddle::framework::details::ThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*) + 364
8       0x7fca49f6c320p
9       0x7fca49f6c840p
10      0x7fca482faa8ep std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) + 46
11      0x7fcaafe03a99p
12      0x7fca49f6c16dp
13      0x7fca482fc5c4p std::thread::_Impl<std::_Bind_simple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1} ()> >::_M_run() + 340
14      0x7fcaa36e7c80p
15      0x7fcaafdfc6bap
16      0x7fcaafb3241dp clone + 109
```

3. 设置环境变量`GLOG_vmodule=operator=4,eager_deletion_op_handle=4`发现，在运行lookup_table op前GC并没有将lookup_table的输入删除，且lookup_table和read这两个op的执行顺序貌似有问题，在某些设备上read还没跑完，lookup_table就已经开始跑了，导致lookup_table报错。
```
I0805 04:28:37.573513  7574 operator.cc:169] CUDAPlace(0) Op(read), inputs:{Reader[train_reader_double_buffer:[-1]({{}})]}, outputs:{Out[read_file_0.tmp_0:[-1]({{}}), read_file_0.tmp_1:[-1]({{}}), read_file_0.tmp_2:[-1]({{}}), read_file_0.tmp_3:[-1]({{}}), read_file_0.tmp_4:[-1]({{}})]}.
I0805 04:28:37.573535  7576 operator.cc:169] CUDAPlace(3) Op(read), inputs:{Reader[train_reader_double_buffer:[-1]({{}})]}, outputs:{Out[read_file_0.tmp_0:[-1]({{}}), read_file_0.tmp_1:[-1]({{}}), read_file_0.tmp_2:[-1]({{}}), read_file_0.tmp_3:[-1]({{}}), read_file_0.tmp_4:[-1]({{}})]}.
I0805 04:28:37.594492  7574 operator.cc:169] CUDAPlace(1) Op(read), inputs:{Reader[train_reader_double_buffer:[-1]({{}})]}, outputs:{Out[read_file_0.tmp_0:[-1]({{}}), read_file_0.tmp_1:[-1]({{}}), read_file_0.tmp_2:[-1]({{}}), read_file_0.tmp_3:[-1]({{}}), read_file_0.tmp_4:[-1]({{}})]}.
I0805 04:28:37.594565  7574 operator.cc:190] CUDAPlace(1) Op(read), inputs:{Reader[train_reader_double_buffer:[-1]({{}})]}, outputs:{Out[read_file_0.tmp_0:int64_t[30, 128, 1]({}), read_file_0.tmp_1:int64_t[30, 128, 1]({}), read_file_0.tmp_2:int64_t[30, 128, 1]({}), read_file_0.tmp_3:float[30, 128, 1]({}), read_file_0.tmp_4:int64_t[30, 128]({})]}.
I0805 04:28:37.598073  7576 operator.cc:169] CUDAPlace(2) Op(read), inputs:{Reader[train_reader_double_buffer:[-1]({{}})]}, outputs:{Out[read_file_0.tmp_0:[-1]({{}}), read_file_0.tmp_1:[-1]({{}}), read_file_0.tmp_2:[-1]({{}}), read_file_0.tmp_3:[-1]({{}}), read_file_0.tmp_4:[-1]({{}})]}.
I0805 04:28:37.598111  7576 operator.cc:190] CUDAPlace(2) Op(read), inputs:{Reader[train_reader_double_buffer:[-1]({{}})]}, outputs:{Out[read_file_0.tmp_0:int64_t[32, 128, 1]({}), read_file_0.tmp_1:int64_t[32, 128, 1]({}), read_file_0.tmp_2:int64_t[32, 128, 1]({}), read_file_0.tmp_3:float[32, 128, 1]({}), read_file_0.tmp_4:int64_t[32, 128]({})]}.
I0805 04:28:37.599509  7575 operator.cc:169] CUDAPlace(3) Op(lookup_table), inputs:{Ids[read_file_0.tmp_2:[-1]({{}})], W[sent_embedding:float[2, 768]({})]}, outputs:{Out[embedding_2.tmp_0:[-1]({{}})]}.
I0805 04:28:37.705209  7577 operator.cc:169] CUDAPlace(3) Op(lookup_table), inputs:{Ids[read_file_0.tmp_1:[-1]({{}})], W[pos_embedding:float[512, 768]({})]}, outputs:{Out[embedding_1.tmp_0:[-1]({{}})]}.
I0805 04:28:37.745697  7575 operator.cc:169] CUDAPlace(3) Op(lookup_table), inputs:{Ids[read_file_0.tmp_0:[-1]({{}})], W[word_embedding:float[30522, 768]({})]}, outputs:{Out[embedding_0.tmp_0:[-1]({{}})]}.
I0805 04:28:37.836273  7577 operator.cc:169] CUDAPlace(0) Op(lookup_table), inputs:{Ids[read_file_0.tmp_2:[-1]({{}})], W[sent_embedding:float[2, 768]({})]}, outputs:{Out[embedding_2.tmp_0:[-1]({{}})]}.
I0805 04:28:37.879535  7576 operator.cc:169] CUDAPlace(0) Op(lookup_table), inputs:{Ids[read_file_0.tmp_1:[-1]({{}})], W[pos_embedding:float[512, 768]({})]}, outputs:{Out[embedding_1.tmp_0:[-1]({{}})]}.
I0805 04:28:37.948709  7577 operator.cc:169] CUDAPlace(0) Op(lookup_table), inputs:{Ids[read_file_0.tmp_0:[-1]({{}})], W[word_embedding:float[30522, 768]({})]}, outputs:{Out[embedding_0.tmp_0:[-1]({{}})]}.
I0805 04:28:37.974840  7574 operator.cc:169] CUDAPlace(1) Op(lookup_table), inputs:{Ids[read_file_0.tmp_2:int64_t[30, 128, 1]({})], W[sent_embedding:float[2, 768]({})]}, outputs:{Out[embedding_2.tmp_0:[-1]({{}})]}.
I0805 04:28:37.974895  7574 operator.cc:190] CUDAPlace(1) Op(lookup_table), inputs:{Ids[read_file_0.tmp_2:int64_t[30, 128, 1]({})], W[sent_embedding:float[2, 768]({})]}, outputs:{Out[embedding_2.tmp_0:float[30, 128, 768]({})]}.
I0805 04:28:37.974911  7575 operator.cc:169] CUDAPlace(1) Op(lookup_table), inputs:{Ids[read_file_0.tmp_1:int64_t[30, 128, 1]({})], W[pos_embedding:float[512, 768]({})]}, outputs:{Out[embedding_1.tmp_0:[-1]({{}})]}.
I0805 04:28:37.974920  7574 operator.cc:169] CUDAPlace(1) Op(lookup_table), inputs:{Ids[read_file_0.tmp_0:int64_t[30, 128, 1]({})], W[word_embedding:float[30522, 768]({})]}, outputs:{Out[embedding_0.tmp_0:[-1]({{}})]}.
I0805 04:28:37.974977  7575 operator.cc:190] CUDAPlace(1) Op(lookup_table), inputs:{Ids[read_file_0.tmp_1:int64_t[30, 128, 1]({})], W[pos_embedding:float[512, 768]({})]}, outputs:{Out[embedding_1.tmp_0:float[30, 128, 768]({})]}.
I0805 04:28:37.974989  7574 operator.cc:190] CUDAPlace(1) Op(lookup_table), inputs:{Ids[read_file_0.tmp_0:int64_t[30, 128, 1]({})], W[word_embedding:float[30522, 768]({})]}, outputs:{Out[embedding_0.tmp_0:float[30, 128, 768]({})]}.
I0805 04:28:37.979024  7574 operator.cc:169] CUDAPlace(2) Op(lookup_table), inputs:{Ids[read_file_0.tmp_2:int64_t[32, 128, 1]({})], W[sent_embedding:float[2, 768]({})]}, outputs:{Out[embedding_2.tmp_0:[-1]({{}})]}.
I0805 04:28:37.979074  7574 operator.cc:190] CUDAPlace(2) Op(lookup_table), inputs:{Ids[read_file_0.tmp_2:int64_t[32, 128, 1]({})], W[sent_embedding:float[2, 768]({})]}, outputs:{Out[embedding_2.tmp_0:float[32, 128, 768]({})]}.
I0805 04:28:37.979079  7575 operator.cc:169] CUDAPlace(2) Op(lookup_table), inputs:{Ids[read_file_0.tmp_1:int64_t[32, 128, 1]({})], W[pos_embedding:float[512, 768]({})]}, outputs:{Out[embedding_1.tmp_0:[-1]({{}})]}.
I0805 04:28:37.979107  7574 operator.cc:169] CUDAPlace(2) Op(lookup_table), inputs:{Ids[read_file_0.tmp_0:int64_t[32, 128, 1]({})], W[word_embedding:float[30522, 768]({})]}, outputs:{Out[embedding_0.tmp_0:[-1]({{}})]}.
I0805 04:28:37.979161  7575 operator.cc:190] CUDAPlace(2) Op(lookup_table), inputs:{Ids[read_file_0.tmp_1:int64_t[32, 128, 1]({})], W[pos_embedding:float[512, 768]({})]}, outputs:{Out[embedding_1.tmp_0:float[32, 128, 768]({})]}.
I0805 04:28:37.979172  7574 operator.cc:190] CUDAPlace(2) Op(lookup_table), inputs:{Ids[read_file_0.tmp_0:int64_t[32, 128, 1]({})], W[word_embedding:float[30522, 768]({})]}, outputs:{Out[embedding_0.tmp_0:float[32, 128, 768]({})]}.
```
