### ISSUE TITLE
win10 2070super 安装完GPU版本后，检测安装是否完好时出错

### ISSUE THREAD

**Issue by fire717** [PaddlePaddle/Paddle#19048]
1）PaddlePaddle版本：paddlepaddle-gpu==1.5.1.post97
    2）CPU：i7-9700kf  
    3）GPU：2070super，CUDA9.0, CUDNN7.6.1
    4）系统环境：win10、Python3.7
- 安装方式信息：pip安装
      
- 问题描述：在win10上安装时参考官网，https://www.paddlepaddle.org.cn/start。报错。

```
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ...
W0807 01:14:14.697468  8948 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 9.0
W0807 01:14:14.705452  8948 device_context.cc:267] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\install_check.py", line 123, in run_check
    test_simple_exe()
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\install_check.py", line 121, in test_simple_exe
    fetch_list=[out0.name, param_grads[1].name])
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\executor.py", line 749, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator mul error.
Python Callstacks:
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\dygraph\layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\dygraph\nn.py", line 945, in forward
    "y_num_col_dims": 1
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 162, in __call__
    outputs = self.forward(*inputs)
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\install_check.py", line 40, in forward
    x = self._fc1(inputs)
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\dygraph\layers.py", line 162, in __call__
    outputs = self.forward(*inputs)
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\install_check.py", line 123, in run_check
    test_simple_exe()
  File "<stdin>", line 1, in <module>
C++ Callstacks:
CUBLAS: execution failed,  at [D:/1.5.1/release_cuda97/paddle\paddle/fluid/operators/math/blas_impl.cu.h:34]
PaddlePaddle Call Stacks:
Windows not support stack backtrace yet.
```

**Comment by gavin1332** [comment]
已反馈，请等待答复

**Comment by frogcjn** [comment]
@fire717 您好，方便联系加一下qq群432676488，到时候需要您帮忙解决一下这个问题。

**Comment by fire717** [comment]
> @fire717 您好，方便联系加一下qq群432676488，到时候需要您帮忙解决一下这个问题。

已加

**Comment by frogcjn** [comment]
> > @fire717 您好，方便联系加一下qq群432676488，到时候需要您帮忙解决一下这个问题。
> 
> 已加

我还是没找到您，您找一下群里的frogcjn

**Comment by liupluswei** [comment]
问题已解决，需要安装cuda9的patch: https://developer.nvidia.com/cuda-90-download-archive?target_os=Windows&target_arch=x86_64&target_version=10&target_type=exelocal

**Comment by fire717** [comment]
你好，在你们的帮助下，之前跑paddle.fluid.install_check.run_check()的确没问题了，但是我尝试跑https://aistudio.baidu.com/aistudio/projectdetail/60139   这里的代码，还是会报错Windows not support stack backtrace yet， 详细报错如下，麻烦看一下呢。

`2019-08-26 01:37:12,415 - train.py[line:395] - INFO: create prog success
2019-08-26 01:37:12,415 - train.py[line:396] - INFO: train config: {'input_size': [3, 512, 512], 'class_dim': 5, 'image_count': 2947, 'label_dict': {'daisy': 0, 'dandelion': 1, 'roses': 2, 'sunflowers': 3, 'tulips': 4}, 'data_dir': 'data/', 'train_file_list': 'train.txt', 'label_file': 'label_list.txt', 'save_freeze_dir': './freeze-model', 'save_persistable_dir': './persistable-params', 'continue_train': True, 'pretrained': False, 'pretrained_dir': 'data/data6593/DenseNet_pretrained', 'mode': 'train', 'num_epochs': 120, 'train_batch_size': 11, 'mean_rgb': [127.5, 127.5, 127.5], 'use_gpu': True, 'dropout_prob': 0.2, 'dropout_seed': None, 'image_enhance_strategy': {'need_distort': True, 'need_rotate': True, 'need_crop': True, 'need_flip': True, 'hue_prob': 0.5, 'hue_delta': 18, 'contrast_prob': 0.5, 'contrast_delta': 0.5, 'saturation_prob': 0.5, 'saturation_delta': 0.5, 'brightness_prob': 0.5, 'brightness_delta': 0.125, 'rotate_prob': 0.5, 'rotate_range': 14}, 'early_stop': {'sample_frequency': 50, 'successive_limit': 5, 'good_acc1': 0.92}, 'rsm_strategy': {'learning_rate': 0.001, 'lr_epochs': [20, 40, 60, 80, 100], 'lr_decay': [1, 0.5, 0.25, 0.1, 0.05, 0.01]}}
2019-08-26 01:37:12,415 - train.py[line:397] - INFO: build input custom reader and data feeder
2019-08-26 01:37:12,417 - train.py[line:411] - INFO: build newwork
2019-08-26 01:37:32,020 - train.py[line:437] - INFO: current pass: 0, start read image
Traceback (most recent call last):
  File "F:\Workshop\BD_OCR\densenet\train.py", line 491, in <module>
    train()
  File "F:\Workshop\BD_OCR\densenet\train.py", line 443, in train
    fetch_list=train_fetch_list) 
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\executor.py", line 749, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator conv2d error.
Python Callstacks: 
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "F:\Software\Anaconda\lib\site-packages\paddle\fluid\layers\nn.py", line 2181, in conv2d
    'fuse_relu_before_depthwise_conv': False
  File "F:\Workshop\BD_OCR\densenet\train.py", line 123, in net
    filter_size=7, stride=2, padding=3, name='densenet_conv0')
  File "F:\Workshop\BD_OCR\densenet\train.py", line 413, in train
    out = model.net(input=img, class_dim=train_parameters['class_dim'])
  File "F:\Workshop\BD_OCR\densenet\train.py", line 491, in <module>
    train()
C++ Callstacks: 
CUDNN_STATUS_EXECUTION_FAILED at [D:\1.5.1\release_cuda97\paddle\paddle\fluid\operators\conv_cudnn_op.cu.cc:271]
PaddlePaddle Call Stacks: 
Windows not support stack backtrace yet.
W0826 01:37:16.545986   832 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 9.0
W0826 01:37:16.551970   832 device_context.cc:267] device: 0, cuDNN Version: 7.6.
[Finished in 27.5s]`
