### ISSUE TITLE
Paddle最新develop分支编译报错：OverflowError: size does not fit in an int

### ISSUE THREAD

**Issue by wzzju** [PaddlePaddle/Paddle#19129]
- 版本、环境信息：
    1）PaddlePaddle版本：CommitID:3f4c088ad8fe99286649194b438fef5a4784056c
    2）CPU：Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
    3）GPU：Tesla V100
- 安装方式信息：
docker编译：
    * docker镜像: chengduozh/paddle:cuda9.0-cudnn7.0_ubuntu_16_4
    * 编译命令 :
```bash
    cmake .. -DPY_VERSION=2.7 -DWITH_GPU=ON -DWITH_TESTING=ON - 
    DWITH_INFERENCE_API_TEST=ON -DON_INFER=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo      
```
- 问题报错信息：
```bash
adding 'paddlepaddle_gpu-0.0.0.dist-info/RECORD'
Traceback (most recent call last):
  File "setup.py", line 253, in <module>
    distclass=BinaryDistribution
  File "/work/.virtualenvs/paddlepaddle-venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/work/.virtualenvs/paddlepaddle-venv/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 254, in run
    wf.write_files(archive_root)
  File "/work/.virtualenvs/paddlepaddle-venv/local/lib/python2.7/site-packages/wheel/wheelfile.py", line 124, in write_files
    self.write(path, arcname)
  File "/work/.virtualenvs/paddlepaddle-venv/local/lib/python2.7/site-packages/wheel/wheelfile.py", line 138, in write
    self.writestr(zinfo, data, compress_type)
  File "/work/.virtualenvs/paddlepaddle-venv/local/lib/python2.7/site-packages/wheel/wheelfile.py", line 141, in writestr
    ZipFile.writestr(self, zinfo_or_arcname, bytes, compress_type)
  File "/usr/lib/python2.7/zipfile.py", line 1236, in writestr
    zinfo.CRC = crc32(bytes) & 0xffffffff       # CRC-32 checksum
OverflowError: size does not fit in an int
python/CMakeFiles/paddle_python.dir/build.make:828: recipe for target 'python/build/.timestamp' failed
make[2]: *** [python/build/.timestamp] Error 1
CMakeFiles/Makefile2:99865: recipe for target 'python/CMakeFiles/paddle_python.dir/all' failed
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by wopeizl** [comment]
一定要用RelWithDebInfo,如果可以用-DCMAKE_BUILD_TYPE=Release试一下

**Comment by vincentXiyu** [comment]
+1 我也遇到这个问题，不知道怎么解决
