### ISSUE TITLE
StarGAN在GPU环境下正常运行，在CPU环境下运行报错

### ISSUE THREAD

**Issue by sucuicong** [PaddlePaddle/Paddle#19230]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：请提供GPU型号，CUDA和CUDNN版本号
    4）系统环境：请说明系统类型、版本（例如Mac OS 10.14），Python版本
- 模型信息
    1）模型名称   StarGAN 
    2）使用数据集名称 celeba
    3）使用算法名称 StarGAN 
    4）模型链接  https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/PaddleGAN
- 复现信息：如为报错，请给出复现环境、复现步骤
命令行调用
!python PaddleGAN/train.py   --model_net StarGAN \
                             --dataset celeba \
                             --data_dir ./data/data11404 \
                             --crop_size 178 \
                             --image_size 128 \
                             --train_list ./data/data11404/celeba/list_attr_celeba.txt \
                             --test_list ./data/data11404/celeba/test_list_attr_celeba.txt  \
                             --gan_mode wgan \
                             --batch_size 8 \
                             --epoch 10 \
                             --print_freq 350 \
                             --output ./PaddleGAN/star_output \
                             --use_gpu False
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
在GPU环境下正常运行，在CPU环境下报错如下
Traceback (most recent call last):
  File "PaddleGAN/train.py", line 89, in <module>
    train(cfg)
  File "PaddleGAN/train.py", line 73, in train
    model.build_model()
  File "/home/aistudio/PaddleGAN/trainer/StarGAN.py", line 288, in build_model
    self.batch_num)
  File "/home/aistudio/PaddleGAN/trainer/StarGAN.py", line 165, in __init__
    optimizer.minimize(self.d_loss, parameter_list=vars)
  File "<decorator-gen-20>", line 2, in minimize
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/dygraph/base.py", line 88, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/optimizer.py", line 593, in minimize
    no_grad_set=no_grad_set)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/optimizer.py", line 493, in backward
    no_grad_set, callbacks)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/backward.py", line 577, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.5/site-packages/paddle/fluid/backward.py", line 392, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core_avx.EnforceNotMet: conv2d_grad_grad's infer_shape has not been registered at [/paddle/paddle/fluid/framework/op_desc.cc:686]

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github.Probably there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a issue of models including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Python version
-Name of Models&Dataset/details of operator
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by sandyhouse** [comment]
出错的原因的话是 conv2d_grad_grad's infer_shape has not been registered,我反馈一下这个问题。
