### ISSUE TITLE
There is no next data

### ISSUE THREAD

**Issue by liuguolian** [PaddlePaddle/Paddle#19311]
训练过程报错，错误信息如下：
Traceback (most recent call last):
File "run_dssm.py", line 254, in <module>
main(args)
File "run_dssm.py", line 218, in main
train_exe.run(fetch_list=[])
File "/home/slurm/job/tmp/job-124154/python_new/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 193, in run
return_numpy=return_numpy)
File "/home/slurm/job/tmp/job-124154/python_new/lib/python2.7/site-packages/paddle/fluid/executor.py", line 543, in run
return_numpy=return_numpy)
File "/home/slurm/job/tmp/job-124154/python_new/lib/python2.7/site-packages/paddle/fluid/executor.py", line 444, in _run_parallel
exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EOFException: There is no next data. at [/ssd2/liyukun01/paddle-env/repos/Paddle/paddle/fluid/operators/reader/read_op.cc:92]

**Comment by Shixiaowei02** [comment]
您好，报错发生在 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/reader/read_op.cc#L88-L90 ，根据提示怀疑输入遇到 EOFException，请检查输入数据完整性。谢谢！
