### ISSUE TITLE
Docker(nvidia官方镜像构建)  cuda10+python3 构建 报错（Can not find library: libcublas.so.）

### ISSUE THREAD

**Issue by qjaden** [PaddlePaddle/Paddle#19382]
- 标题：Docker 构建 报错（Can not find library: libcublas.so.）【查阅资料无果】
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.1
    2）CPU：请提供CPU型号，英特尔至强E5-2630V4
    3）GPU：RTX 2080，CUDA10.0
    4）系统环境：Ubuntu18.04
环境变量为：
```
#>>>>>cuda
export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export CUDA_HOME=/usr/local/cuda
#<<<<<cuda
```

- 安装方式信息：
1）pip安装/docker安装 
`python -m pip install paddlepaddle-gpu -i https://pypi.tuna.tsinghua.edu.cn/simple`
2）python 环境：python3.7
3）docker编译：请提供docker镜像，编译命令        
编译文件用的NVIDIA官方[](https://gitlab.com/nvidia/cuda/blob/master/dist/ubuntu18.04/10.0/runtime/cudnn7/Dockerfile)

```
ARG IMAGE_NAME
FROM ${IMAGE_NAME}:10.0-runtime-ubuntu18.04
LABEL maintainer "NVIDIA CORPORATION <cudatools@nvidia.com>"

ENV CUDNN_VERSION 7.6.2.24
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

RUN apt-get update && apt-get install -y --no-install-recommends \
    libcudnn7=$CUDNN_VERSION-1+cuda10.0 \
&& \
    apt-mark hold libcudnn7 && \
    rm -rf /var/lib/apt/lists/*
```

  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤

```
In [1]: import paddle.fluid

In [2]: paddle.fluid.install_check.run_check()

Running Verify Fluid Program ...
W0823 05:25:31.557361  6182 dynamic_loader.cc:109] Can not find library: libcublas.so. The process maybe hang. Please try to add the lib path to LD_LIBRARY_PATH.
---------------------------------------------------------------------------
EnforceNotMet                             Traceback (most recent call last)
<ipython-input-2-f42e4608cc2a> in <module>
----> 1 paddle.fluid.install_check.run_check()

~/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/install_check.py in run_check()
    121                              fetch_list=[out0.name, param_grads[1].name])
    122
--> 123     test_simple_exe()
    124
    125     print("Your Paddle Fluid works well on SINGLE GPU or CPU.")

~/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/install_check.py in test_simple_exe()
    117                         core.CUDAPlace(0) if core.is_compiled_with_cuda() and
    118                         (core.get_cuda_device_count() > 0) else core.CPUPlace())
--> 119                     exe0.run(startup_prog)
    120                     exe0.run(feed={inp0.name: np_inp_single},
    121                              fetch_list=[out0.name, param_grads[1].name])

~/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/executor.py in run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    649                 scope=scope,
    650                 return_numpy=return_numpy,
--> 651                 use_program_cache=use_program_cache)
    652         else:
    653             if fetch_list and program._is_data_parallel and program._program and (

~/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/executor.py in _run(self, program, exe, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache)
    747         self._feed_data(program, feed, feed_var_name, scope)
    748         if not use_program_cache:
--> 749             exe.run(program.desc, scope, 0, True, True, fetch_var_name)
    750         else:
    751             exe.run_cached_prepared_ctx(ctx, scope, False, False, False)

EnforceNotMet: Invoke operator fill_constant error.
Python Callstacks:
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1842, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 189, in __call__
    stop_gradient=True)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1727, in create_parameter
    initializer(param, self)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 316, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 90, in create_parameter
    default_initializer)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/dygraph/nn.py", line 930, in _build_once
    attr=self._bias_attr, shape=size, dtype=self._dtype, is_bias=True)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 158, in __call__
    self._build_once(*inputs)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 40, in forward
    x = self._fc1(inputs)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 162, in __call__
    outputs = self.forward(*inputs)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 123, in run_check
    test_simple_exe()
  File "<ipython-input-2-f42e4608cc2a>", line 1, in <module>
    paddle.fluid.install_check.run_check()
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3058, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
    return runner(coro)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2855, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 489, in interact
    self.run_cell(code, store_history=True)
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 498, in mainloop
    self.interact()
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/root/anaconda3/envs/ai-pp/lib/python3.7/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/root/anaconda3/envs/ai-pp/bin/ipython", line 10, in <module>
    sys.exit(start_ipython())
C++ Callstacks:
Failed to find dynamic library: libcublas.so ( libcublas.so: cannot open shared object file: No such file or directory )
 Please specify its path correctly using following ways:
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS.
 For instance, issue command: export LD_LIBRARY_PATH=...
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. at [/paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:166]
PaddlePaddle Call Stacks:
0       0x7f0d72cb1950p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f0d72cb1cc9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f0d74de54d5p paddle::platform::dynload::GetCublasDsoHandle() + 1813
3       0x7f0d74dc2ac9p void std::__once_call_impl<std::_Bind_simple<paddle::platform::dynload::DynLoad__cublasCreate_v2::operator()<cublasContext**>(cublasContext**)::{lambda()#1} ()> >() + 9
4       0x7f0e1b380827p
5       0x7f0d74dc3c69p paddle::platform::CublasHandleHolder::CublasHandleHolder(CUstream_st*, cublasMath_t) + 153
6       0x7f0d74dbf797p paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace) + 567
7       0x7f0d74dc4608p std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >, std::allocator<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&) + 104
8       0x7f0d74dc2bbap std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&) + 42
9       0x7f0d72d7b6b7p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&) + 39
10      0x7f0e1b380827p
11      0x7f0d74dc5efcp std::__future_base::_Deferred_state<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> >, std::allocator<std::pair<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred() + 220
12      0x7f0d74dc0379p paddle::platform::DeviceContextPool::Get(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 137
13      0x7f0d74d3ff1ap paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 58
14      0x7f0d74d40431p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
15      0x7f0d74d3da2cp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
16      0x7f0d72e3c73ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
17      0x7f0d72e3f7dfp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
18      0x7f0d72ca2fddp
19      0x7f0d72ce4286p
20      0x558085184744p _PyMethodDef_RawFastCallKeywords + 596
21      0x558085184861p _PyCFunction_FastCallKeywords + 33
22      0x5580851f06e8p _PyEval_EvalFrameDefault + 21240
23      0x558085134539p _PyEval_EvalCodeWithName + 761
24      0x558085183f57p _PyFunction_FastCallKeywords + 903
25      0x5580851ec8ccp _PyEval_EvalFrameDefault + 5340
26      0x558085134539p _PyEval_EvalCodeWithName + 761
27      0x558085183ef5p _PyFunction_FastCallKeywords + 805
28      0x5580851eba93p _PyEval_EvalFrameDefault + 1699
29      0x55808513481ap _PyEval_EvalCodeWithName + 1498
30      0x558085183f57p _PyFunction_FastCallKeywords + 903
31      0x5580851eb806p _PyEval_EvalFrameDefault + 1046
32      0x558085134d09p _PyEval_EvalCodeWithName + 2761
33      0x558085183f57p _PyFunction_FastCallKeywords + 903
34      0x5580851eff29p _PyEval_EvalFrameDefault + 19257
35      0x558085134539p _PyEval_EvalCodeWithName + 761
36      0x558085135424p PyEval_EvalCodeEx + 68
37      0x55808513544cp PyEval_EvalCode + 28
38      0x5580851faf8dp
39      0x5580851845d9p _PyMethodDef_RawFastCallKeywords + 233
40      0x558085184861p _PyCFunction_FastCallKeywords + 33
41      0x5580851efb94p _PyEval_EvalFrameDefault + 18340
42      0x55808518d592p _PyGen_Send + 674
43      0x5580851ece69p _PyEval_EvalFrameDefault + 6777
44      0x55808518d592p _PyGen_Send + 674
45      0x5580851ece69p _PyEval_EvalFrameDefault + 6777
46      0x55808518d592p _PyGen_Send + 674
47      0x55808518457dp _PyMethodDef_RawFastCallKeywords + 141
48      0x55808518c3cfp _PyMethodDescr_FastCallKeywords + 79
49      0x5580851f007cp _PyEval_EvalFrameDefault + 19596
50      0x558085183ccbp _PyFunction_FastCallKeywords + 251
51      0x5580851eb806p _PyEval_EvalFrameDefault + 1046
52      0x558085183ccbp _PyFunction_FastCallKeywords + 251
53      0x5580851eba93p _PyEval_EvalFrameDefault + 1699
54      0x558085134539p _PyEval_EvalCodeWithName + 761
55      0x558085183f57p _PyFunction_FastCallKeywords + 903
56      0x5580851ec8ccp _PyEval_EvalFrameDefault + 5340
57      0x558085134539p _PyEval_EvalCodeWithName + 761
58      0x558085183ef5p _PyFunction_FastCallKeywords + 805
59      0x5580851eba93p _PyEval_EvalFrameDefault + 1699
60      0x558085134539p _PyEval_EvalCodeWithName + 761
61      0x558085183ef5p _PyFunction_FastCallKeywords + 805
62      0x5580851eba93p _PyEval_EvalFrameDefault + 1699
63      0x558085183ccbp _PyFunction_FastCallKeywords + 251
64      0x5580851eba93p _PyEval_EvalFrameDefault + 1699
65      0x558085134539p _PyEval_EvalCodeWithName + 761
66      0x558085135860p _PyFunction_FastCallDict + 1024
67      0x558085153e53p _PyObject_Call_Prepend + 99
68      0x558085146dbep PyObject_Call + 110
69      0x5580851ed232p _PyEval_EvalFrameDefault + 7746
70      0x558085134539p _PyEval_EvalCodeWithName + 761
71      0x558085183f57p _PyFunction_FastCallKeywords + 903
72      0x5580851eb806p _PyEval_EvalFrameDefault + 1046
73      0x558085134539p _PyEval_EvalCodeWithName + 761
74      0x558085135424p PyEval_EvalCodeEx + 68
75      0x55808513544cp PyEval_EvalCode + 28
76      0x55808524ab74p
77      0x558085254eb1p PyRun_FileExFlags + 161
78      0x5580852550a3p PyRun_SimpleFileExFlags + 451
79      0x558085256195p
80      0x5580852562bcp _Py_UnixMain + 60
81      0x7f0e1afa1b97p __libc_start_main + 231
82      0x5580851fb062p
```

**Comment by ysh329** [comment]
感觉是
1. 这个CUDA没有装好：`/usr/local/cuda/bin`这个目录有东西吗
2. 好像你的环境变量写的有点问题，我稍微改了下：

```shell
#>>>>>cuda
export CUDA_HOME=/usr/local/cuda
export PATH=${CUDA_HONE}/bin:${PATH}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
#<<<<<cuda
```

**Comment by qjaden** [comment]
> 感觉是
> 
> 1. 这个CUDA没有装好：`/usr/local/cuda/bin`这个目录有东西吗
> 2. 好像你的环境变量写的有点问题，我稍微改了下：
> 
> ```shell
> #>>>>>cuda
> export CUDA_HOME=/usr/local/cuda
> export PATH=${CUDA_HONE}/bin:${PATH}
> export LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH}
> #<<<<<cuda
> ```

cuda和cudnn的环境都是配置好的（用的NVIDIA官方的镜像构建），`/usr/local/cuda/bin`都有，感觉是PaddlePaddle的问题，百度官方提供的镜像只支持python2。

**Comment by ysh329** [comment]
@ZhengHui-Z 你这里可以使用装好的Paddle的NV-Docker景象嘛，自己就不需要装了，只需要下载paddle的nv-docker的镜像直接拿来用就行了？

----

抱歉，我后来看了下，目前还不支持

![image](https://user-images.githubusercontent.com/7320657/63683485-0edda100-c82d-11e9-8c4e-307488cbdd61.png)
