### ISSUE TITLE
深度注意力机制模型（Deep Attention Matching Network）在CPU环境下训练过程无法跑通

### ISSUE THREAD

**Issue by sucuicong** [PaddlePaddle/Paddle#19389]
模型信息
    1）模型名称 Deep Attention Matching Network
    2）使用数据集名称 ubuntu
    3）使用算法名称 Deep Attention Matching Network
    4）模型链接 https://github.com/PaddlePaddle/models/tree/release/1.5/PaddleNLP/dialogue_model_toolkit/deep_attention_matching
- 复现信息：如为报错，请给出复现环境、复现步骤

```shell
$ cd deep_attention_matching && python main.py \
  --do_train True \
  --data_path ./data/ubuntu/data_small.pkl \
  --save_path ./model_files/ubuntu \
  --vocab_size 434512 \
  --_EOS_ 28270 \
  --batch_size 16
```

```shell
Traceback (most recent call last):
  File "main.py", line 492, in <module>
    train(args)
  File "main.py", line 343, in train
    global_step, last_cost = train_with_feed(global_step)
  File "main.py", line 249, in train_with_feed
    cost = train_exe.run(feed=feed_list, fetch_list=[loss.name])
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 280, in run
    return_numpy=return_numpy)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 665, in run
    return_numpy=return_numpy)
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 507, in _run_parallel
    "Feed a list of tensor, the list should be the same size as places"
ValueError: Feed a list of tensor, the list should be the same size as places
```

**Comment by ysh329** [comment]
建议

```shell
  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 507, in _run_parallel
    "Feed a list of tensor, the list should be the same size as places"
ValueError: Feed a list of tensor, the list should be the same size as places
```

检查list size

**Comment by sucuicong** [comment]
代码是paddle github上的源码，没有做过任何修改，在GPU环境下可以跑通，在CPU下会有这样的报错，请告知该代码的作者修改

发件人: Yuan Shuai <notifications@github.com>
答复: PaddlePaddle/Paddle <reply@reply.github.com>
日期: 2019年8月23日 星期五 下午7:05
收件人: PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送: "Su,Cuicong" <sucuicong@baidu.com>, Author <author@noreply.github.com>
主题: Re: [PaddlePaddle/Paddle] 深度注意力机制模型（Deep Attention Matching Network）在CPU环境下训练过程无法跑通 (#19389)


建议

  File "/opt/conda/envs/python27-paddle120-env/lib/python2.7/site-packages/paddle/fluid/executor.py", line 507, in _run_parallel



    "Feed a list of tensor, the list should be the same size as places"



ValueError: Feed a list of tensor, the list should be the same size as places
