### ISSUE TITLE
test_slim_int8_googlenet, test_analyzer_int8_googlenet etc fails on new 5117 machine

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#19505]
### CI log
- test_slim_int8_googlenet
```
[21:44:36]2019-08-27 21:44:34,027-INFO: FP32: avg top1 accuracy: 0.7200
[21:44:36]2019-08-27 21:44:34,027-INFO: INT8: avg top1 accuracy: 0.7000
[21:44:36]F
[21:44:36]======================================================================
[21:44:36]FAIL: test_compression (__main__.TestMKLDNNPostTrainingQuantStrategy)
[21:44:36]----------------------------------------------------------------------
[21:44:36]Traceback (most recent call last):
[21:44:36]  File "/paddle/python/paddle/fluid/contrib/slim/tests/test_mkldnn_int8_quantization_strategy.py", line 263, in test_compression
[21:44:36]    accuracy_diff_threshold)
[21:44:36]  File "/paddle/python/paddle/fluid/contrib/slim/tests/test_mkldnn_int8_quantization_strategy.py", line 228, in _compare_accuracy
[21:44:36]    assert fp32_acc1 - int8_acc1 <= threshold
[21:44:36]AssertionError
[21:44:36]
[21:44:36]----------------------------------------------------------------------
[21:44:36]Ran 1 test in 33.041s
```
- test_transpose_int8_mkldnn_op
```
[21:43:04]C++ Call stacks: 
[21:43:04]op transpose2 does not have kernel for data_type[double]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN] at [/paddle/paddle/fluid/framework/operator.cc:1003]
[21:43:04]PaddlePaddle Call Stacks: 
[21:43:04]0       0x7f7b5cf8870fp void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 255
[21:43:04]1       0x7f7b5cf88c5bp paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 139
```
- test_analyzer_seq_pool1
```
[21:39:11]I0827 21:39:09.997370 74239 analysis_predictor.cc:475] == optimize end ==
[21:39:11]I0827 21:39:09.998457 74239 tester_helper.h:332] Thread 0, number of threads 1, run 1 times...
[21:39:11]W0827 21:39:09.999147 74239 naive_executor.cc:43] The NaiveExecutor can not work properly if the cmake flag ON_INFER is not set.
[21:39:11]W0827 21:39:09.999157 74239 naive_executor.cc:45] Unlike the training phase, all the scopes and variables will be reused to save the allocation overhead.
[21:39:11]W0827 21:39:09.999162 74239 naive_executor.cc:48] Please re-compile the inference library by setting the cmake flag ON_INFER=ON if you are running Paddle Inference
[21:39:11]I0827 21:39:10.004389 74239 helper.h:322] ====== threads: 1, thread id: 0 ======
[21:39:11]I0827 21:39:10.004412 74239 helper.h:324] ====== batch size: 1, iterations: 1, repetitions: 1 ======
[21:39:11]I0827 21:39:10.004423 74239 helper.h:326] ====== batch latency: 5.90201ms, number of samples: 1, sample latency: 5.90201ms, fps: 169.434, data type: float ======
[21:39:11]F0827 21:39:10.012611 74239 tester_helper.h:119] Check failed: std::abs(pdata_ref[j] - pdata[j]) <= FLAGS_accuracy (0.03125 vs. 0.001) 
[21:39:11]*** Check failure stack trace: ***
```
- test_analyzer_int8_googlenet
```
[21:38:54]I0827 21:38:52.514907 74251 tester_helper.h:455] --- Accuracy summary --- 
[21:38:54]I0827 21:38:52.514912 74251 tester_helper.h:456] Accepted top1_accuracy drop threshold: 0.01. (condition: (FP32_top1_accuracy  - INT8_top1_accuracy ) <= threshold)
[21:38:54]I0827 21:38:52.514920 74251 tester_helper.h:460] FP32: avg top1_accuracy 0.7200
[21:38:54]I0827 21:38:52.514926 74251 tester_helper.h:462] INT8: avg top1_accuracy 0.7000
[21:38:54]F0827 21:38:52.514963 74251 tester_helper.h:527] Check failed: avg_acc_ref - avg_acc_quant <= FLAGS_quantized_accuracy (0.02 vs. 0.01) 
```
http://ci.paddlepaddle.org/viewLog.html?tab=buildLog&buildTypeId=Paddle_PrCiCoverage&buildId=149605   
### Error machine
```
processor	: 27
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz
stepping	: 4
microcode	: 0x2000043
cpu MHz		: 2000.000
cache size	: 19712 KB
physical id	: 1
siblings	: 14
core id		: 14
cpu cores	: 14
apicid		: 60
initial apicid	: 60
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx avx512f avx512dq rdseed adx smap clflushopt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc
bogomips	: 4004.54
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```
### successful machine
```
processor	: 15
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) Gold 5117 CPU @ 2.00GHz
stepping	: 4
microcode	: 0x1
cpu MHz		: 2000.071
cache size	: 4096 KB
physical id	: 15
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 15
initial apicid	: 15
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl eagerfpu pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch arat fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap avx512cd xsaveopt xsavec xgetbv1
bogomips	: 4015.45
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

**Comment by ghost** [comment]
@bingyanghuang could you or PL team to have a check? Thanks!

**Comment by bingyanghuang** [comment]
@wojtuss @Sand3r- Could you help investigate this problem, thanks very much.

**Comment by wojtuss** [comment]
I have verified the tests on a few CLX machines, all passed.
To be verified on SKX machines.

**Comment by wojtuss** [comment]
I have submitted a diagnostic PR to check the CI machines' AVX configuration using the `leaf7_test` test: https://github.com/PaddlePaddle/Paddle/pull/19540

**Comment by wojtuss** [comment]
I have reproduced the `test_analyzer_seq_pool1` failure on SKX 8180 and CLX 6248 machines.
I have reproduced the `test_*_int8_googlenet` failure on a SKX 8180 machine.

**Comment by Sand3r-** [comment]
The 'successful' machine is incorrectly configured, as its missing many available instruction sets as listed here:
https://www.diffchecker.com/KiuINQ6J
(on the left hand side you can see instruction sets for the 'successful' machine while on the  right hand side the instruction sets for the 'error' machine).

Here you can find the instructions sets available for Intel(R) Xeon(R) Gold 5117 here https://en.wikichip.org/wiki/intel/xeon_gold/5117#Features

**Comment by luotao1** [comment]
Thus, you mean the new machine is correct, and these three unit-tests indeed have some bugs?

**Comment by Sand3r-** [comment]
Partially yes. It is better configured than the older one (it provides access to more instruction sets).
Speaking of tests:
* googlenet tests - in some of the recent commits an accuracy regression has been introduced. What commit has caused it is currently being determined.
* transpose  - it looks like a bug in `GetExpectedKernelType` to me, but I'll need to investigate it.
* test_analyzer_seq_pool1 - this test always fails on correctly configured machines. As far as I remember it relies on MKL calling AVX2 code for gemm (fc/mul). If any other version of gemm kernel is called, the test fails due to insufficient accuracy.

**Comment by Sand3r-** [comment]
I've managed to find out that the commit which caused the googlenet test to fail is 492a00f53ea0b265bcac29a21c8c33d7284dd289 (Add conv reqantize squash (#18754)).
On earlier commit c548e370f1ebbfef249d788a50ba0e12410f8809 the test passes just fine.

**Comment by luotao1** [comment]
Thanks very much for your investigation, and how to solve the `test_analyzer_seq_pool1 `?

**Comment by Sand3r-** [comment]
I think that the reference data (to which inference results compare to) should be modified. It fails on the native (non-mkldnn-optimized) paddle layers.

As a temporary fix, you could add an MKL flag for forcing AVX2 implementations to be called:
`MKL_CBWR=AVX2`. With this flag, the test passes.

**Comment by Sand3r-** [comment]
I have talked to @wozna and she's currently investigating the issue with `test_transpose_int8_mkldnn_op`. Once done, she'll examine `test_slim_int8_googlenet` and `test_analyzer_int8_googlenet`.

**Comment by Sand3r-** [comment]
@wozna has managed to find what the issue was with `test_transpose_int8_mkldnn_op` and she'll post a fix to it in her transpose int8 PR #19424

**Comment by luotao1** [comment]
@bingyanghuang 
- #20041 only temporarily fix `test_slim_int8_googlenet` and `test_analyzer_int8_googlenet`. 
- but `test_analyzer_seq_pool1` (see https://github.com/PaddlePaddle/Paddle/issues/19505#issuecomment-526561551, set `MKL_CBWR=AVX2`) and `test_transpose_int8_mkldnn_op` (see https://github.com/PaddlePaddle/Paddle/issues/19505#issuecomment-526601557 #19424) don't be fixed.

**Comment by bingyanghuang** [comment]
> I think that the reference data (to which inference results compare to) should be modified. It fails on the native (non-mkldnn-optimized) paddle layers.
> 
> As a temporary fix, you could add an MKL flag for forcing AVX2 implementations to be called:
> `MKL_CBWR=AVX2`. With this flag, the test passes.

This is related with issue #16470 .

**Comment by Sand3r-** [comment]
@luotao @bingyanghuang @wojtuss 
I have carried out investigation `test_analyzer_seq_pool1` to find out what the problem may be.
If we look at the topology using netron, we see that at the very end it contains a `reduce_sum` operator.

![image](https://user-images.githubusercontent.com/4967505/68390274-30c89d80-0165-11ea-8bde-3356cbf97bd2.png)

I have decided to print what are the inputs and outputs of these layers and found out that they are all large in magnitude. Inside [this diff](https://www.diffchecker.com/2C3eiziW) you can find the inputs and output for toplogy without passes applied (left) and topology with passes applied (right).

From the magnitudes of the numbers, it is clear that the threshold for an absolute difference is too small (0.001) as for a topology that doesn't have a layer that normalizes the values (such as softmax).

Of course, it'd be much cleaner to use a [relative error metric](https://en.wikipedia.org/wiki/Approximation_error#Uses_of_relative_error) here and in other unit tests to measure the acceptable difference in outputs.  This metric is well suited for consistent measuring of approximation errors when the examined numbers vary in magnitudes (for example 10000 vs 0.0001) and is hence more universal.

Hence I propose to either:
* Increase the threshold
or 
* Introduce relative error measure for analzyer tests

**Comment by luotao1** [comment]
@Sand3r- Thanks for your explanation, and [this diff](https://www.diffchecker.com/2C3eiziW) is easy to use and see the result.

Discussed with @NHZlX, we think:
```
if result > 1, use relative error measure;
else, use absolute error measure
``` 
Indeed, we should compare the number of significant digits for a floating-point type

**Comment by bingyanghuang** [comment]
@luotao1 

- #20041 only temporarily fix test_slim_int8_googlenet and test_analyzer_int8_googlenet.

- test_analyzer_seq_pool1 can be fixed by https://github.com/PaddlePaddle/Paddle/issues/19505#issuecomment-551366848

- test_transpose_int8_mkldnn_op fixed by #19424 

We think that new machines' random fails have all been fixed. Could you help try to move the CI to the new machines?

**Comment by luotao1** [comment]
> test_analyzer_seq_pool1 can be fixed by #19505 (comment)

I don't see the fixed PR now.

**Comment by bingyanghuang** [comment]
> > test_analyzer_seq_pool1 can be fixed by #19505 (comment)
> 
> I don't see the fixed PR now.

@Sand3r- Please a create a PR to fix this.

**Comment by grygielski** [comment]
PR that should fix ```test_analyzer_seq_pool1``` fail: https://github.com/PaddlePaddle/Paddle/pull/21144

**Comment by luotao1** [comment]
Close this issue since the above 4 tests are already fixed now.
