### ISSUE TITLE
stop_gradient报错

### ISSUE THREAD

**Issue by mensaochun** [PaddlePaddle/Paddle#19569]
我想固定主干网络的权重，我设置了某一层stop_gradient=True，但是报错了，如下。取消这个恢复正常，请问怎么回事。
```
Traceback (most recent call last):
  File "train_classifier.py", line 200, in <module>
    main(args)
  File "train_classifier.py", line 145, in main
    train_pyreader, train_out = build_program(train_program, startup_program, True)
  File "train_classifier.py", line 50, in build_program
    optimizer.minimize(loss)
  File "<decorator-gen-20>", line 2, in minimize
  File "/home/ssd3/yourenchun/python_yrc/python/lib/python2.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/ssd3/yourenchun/python_yrc/python/lib/python2.7/site-packages/paddle/fluid/dygraph/base.py", line 87, in __impl__
    return func(*args, **kwargs)
  File "/home/ssd3/yourenchun/python_yrc/python/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 594, in minimize
    no_grad_set=no_grad_set)
  File "/home/ssd3/yourenchun/python_yrc/python/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 493, in backward
    no_grad_set, callbacks)
  File "/home/ssd3/yourenchun/python_yrc/python/lib/python2.7/site-packages/paddle/fluid/backward.py", line 578, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/home/ssd3/yourenchun/python_yrc/python/lib/python2.7/site-packages/paddle/fluid/backward.py", line 392, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core_avx.EnforceNotMet:  at [/paddle/paddle/fluid/operators/batch_norm_op.cc:357]
PaddlePaddle Call Stacks:
0       0x7f0eefc33ad0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f0eefc33e49p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f0ef0513aa3p paddle::operators::BatchNormGradOp::InferShape(paddle::framework::InferShapeContext*) const + 2083
3       0x7f0eefda788ep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7f0eefcdfd4cp
5       0x7f0eefc66936p
6       0x7f0f626b1bb8p PyEval_EvalFrameEx + 25016
7       0x7f0f626b50bdp PyEval_EvalCodeEx + 2061
8       0x7f0f626b2345p PyEval_EvalFrameEx + 26949
9       0x7f0f626b50bdp PyEval_EvalCodeEx + 2061
10      0x7f0f626b2345p PyEval_EvalFrameEx + 26949
11      0x7f0f626b50bdp PyEval_EvalCodeEx + 2061
12      0x7f0f626b2345p PyEval_EvalFrameEx + 26949
13      0x7f0f626b50bdp PyEval_EvalCodeEx + 2061
14      0x7f0f6262bf85p
15      0x7f0f625f9df3p PyObject_Call + 67
16      0x7f0f626aef97p PyEval_EvalFrameEx + 13719
17      0x7f0f626b50bdp PyEval_EvalCodeEx + 2061
18      0x7f0f6262bf85p
19      0x7f0f625f9df3p PyObject_Call + 67
20      0x7f0f626aef97p PyEval_EvalFrameEx + 13719
21      0x7f0f626b50bdp PyEval_EvalCodeEx + 2061
22      0x7f0f626b2345p PyEval_EvalFrameEx + 26949
23      0x7f0f626b50bdp PyEval_EvalCodeEx + 2061
24      0x7f0f626b2345p PyEval_EvalFrameEx + 26949
25      0x7f0f626b2460p PyEval_EvalFrameEx + 27232
26      0x7f0f626b2460p PyEval_EvalFrameEx + 27232
27      0x7f0f626b50bdp PyEval_EvalCodeEx + 2061
28      0x7f0f626b51f2p PyEval_EvalCode + 50
29      0x7f0f626ddf42p PyRun_FileExFlags + 146
30      0x7f0f626df2d9p PyRun_SimpleFileExFlags + 217
31      0x7f0f626f500dp Py_Main + 3149
32      0x7f0f618f2bd5p __libc_start_main + 245
33            0x4007a1p
```

**Comment by chengduoZH** [comment]
@mensaochun 请问是什么模型，可以贴一下吗？
