### ISSUE TITLE
Operator "deformable_conv" has not been registered. PaddlePaddle 1.5.0

### ISSUE THREAD

**Issue by brodra** [PaddlePaddle/Paddle#19637]
为什么paddle提供的operator会未注册，是版本或安装问题还是有些op确实要手动注册？

训练阶段，更准确地说就是执行了`fluid.layers.deformable_conv`函数时报错。
进去追踪到`helper.append_op(type='deformable_conv')`抛出如上错误。

paddle的包是按官网教程安装的
`python3 -m pip install paddlepaddle==1.5.0 -i https://pypi.tuna.tsinghua.edu.cn/simple`

系统环境Ubuntu14.04，anaconda 1.6.5, python 3.6.3, pip 9.0.1, 无显卡

复现代码如下（官方文档实例）：
```python
from paddle import fluid

data = fluid.layers.data(name='data', shape=[3, 32, 32], dtype='float32')
offset = fluid.layers.data(name='offset', shape=[18, 32, 32], dtype='float32')
mask = fluid.layers.data(name='mask', shape=[9, 32, 32], dtype='float32')
out = fluid.layers.deformable_conv(input=data, offset=offset, mask=mask, num_filters=2, filter_size=3, padding=1)

pass
```
结果是
```
Traceback (most recent call last):
  File "deconv.py", line 6, in <module>
    out = fluid.layers.deformable_conv(input=data, offset=offset, mask=mask, num_filters=2, filter_size=3, padding=1)
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 12095, in deformable_conv
    'im2col_step': im2col_step,
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1061, in __init__
    proto = OpProtoHolder.instance().get_op_proto(type)
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 950, in get_op_proto
    raise ValueError("Operator \"%s\" has not been registered." % type)
ValueError: Operator "deformable_conv" has not been registered.
```

**Comment by Superjomn** [comment]
这是训练还预测？ 另外，这个包是正式的版本吗？

**Comment by phlrain** [comment]
能否提供下复现的代码和环境

**Comment by brodra** [comment]
训练阶段，更准确地说就是执行了`fluid.layers.deformable_conv`函数时报错。
进去追踪到`helper.append_op(type='deformable_conv')`抛出如上错误。

paddle的包是按官网教程安装的
`python3 -m pip install paddlepaddle==1.5.0 -i https://pypi.tuna.tsinghua.edu.cn/simple`

系统环境Ubuntu14.04，anaconda 1.6.5, python 3.6.3, pip 9.0.1, 无显卡

复现代码如下（官方文档实例）：
```python
from paddle import fluid

data = fluid.layers.data(name='data', shape=[3, 32, 32], dtype='float32')
offset = fluid.layers.data(name='offset', shape=[18, 32, 32], dtype='float32')
mask = fluid.layers.data(name='mask', shape=[9, 32, 32], dtype='float32')
out = fluid.layers.deformable_conv(input=data, offset=offset, mask=mask,
                                   num_filters=2, filter_size=3, padding=1)
pass
```
结果是
```
Traceback (most recent call last):
  File "/home/brodra/JetBrains/pycharm-2019.1.2/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/home/brodra/JetBrains/pycharm-2019.1.2/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/brodra/JetBrains/pycharm-2019.1.2/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/brodra/JetBrains/pycharm-2019.1.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/brodra/astar2019/coco2017/deconv.py", line 7, in <module>
    num_filters=2, filter_size=3, padding=1)
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 12095, in deformable_conv
    'im2col_step': im2col_step,
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1061, in __init__
    proto = OpProtoHolder.instance().get_op_proto(type)
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 950, in get_op_proto
    raise ValueError("Operator \"%s\" has not been registered." % type)
ValueError: Operator "deformable_conv" has not been registered.
```

**Comment by brodra** [comment]
为什么paddle提供的operator会未注册，是版本或安装问题还是有些op确实要手动注册？

训练阶段，更准确地说就是执行了`fluid.layers.deformable_conv`函数时报错。
进去追踪到`helper.append_op(type='deformable_conv')`抛出如上错误。

paddle的包是按官网教程安装的
`python3 -m pip install paddlepaddle==1.5.0 -i https://pypi.tuna.tsinghua.edu.cn/simple`

系统环境Ubuntu14.04，anaconda 1.6.5, python 3.6.3, pip 9.0.1, 无显卡

复现代码如下（官方文档实例）：
```python
from paddle import fluid

data = fluid.layers.data(name='data', shape=[3, 32, 32], dtype='float32')
offset = fluid.layers.data(name='offset', shape=[18, 32, 32], dtype='float32')
mask = fluid.layers.data(name='mask', shape=[9, 32, 32], dtype='float32')
out = fluid.layers.deformable_conv(input=data, offset=offset, mask=mask, num_filters=2, filter_size=3, padding=1)

pass
```
结果是
```
Traceback (most recent call last):
  File "deconv.py", line 6, in <module>
    out = fluid.layers.deformable_conv(input=data, offset=offset, mask=mask, num_filters=2, filter_size=3, padding=1)
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 12095, in deformable_conv
    'im2col_step': im2col_step,
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1061, in __init__
    proto = OpProtoHolder.instance().get_op_proto(type)
  File "/home/brodra/python/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 950, in get_op_proto
    raise ValueError("Operator \"%s\" has not been registered." % type)
ValueError: Operator "deformable_conv" has not been registered.
```

**Comment by phlrain** [comment]
这个op没有cpu 的kernel，所以注册的时候会出现问题，如果你安装一个gpu的paddle就没有这个问题，cpu kernel的问题 我们修复下

**Comment by brodra** [comment]
了解，多谢

本意是想先在cpu把模型跑通再推到服务器上，没想遇到这种情况。

建议在文档说明中讲清楚哪些op是只能在gpu跑的，哪些是都能用的。

**Comment by phlrain** [comment]
op说明这个事情 我们再规范下
