### ISSUE TITLE
Python 预测 API调用报错【提示编译ON_INFER=ON】

### ISSUE THREAD

**Issue by Bond-H** [PaddlePaddle/Paddle#19784]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.1【非自己编译】
    2）CPU：Intel Xeon E312xx
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：CentOS 6.3
-预测信息
    1）基于官网进行pip install 安装的paddle
    2)  使用Python接口进行预测

- 复现信息：
```
git clone https://github.com/Bond-SYSU/paddle_deploy_test
cd paddle_deploy_test
python deploy_test.py
```
- 问题描述：

- 使用load_inference_model能够正常调用该模型

```
python LAC.py
```

但根据https://www.paddlepaddle.org.cn/documentation/docs/zh/advanced_usage/deploy/inference/python_infer_cn.html 编写调用接口，执行代码
```
python deploy_test.py

# 该文件内容如下
import argparse
import numpy as np

from paddle.fluid.core import PaddleBuf
from paddle.fluid.core import PaddleDType
from paddle.fluid.core import PaddleTensor
from paddle.fluid.core import AnalysisConfig
from paddle.fluid.core import create_paddle_predictor
import reader
import utils

class Args():
    model_dir = 'infer_model'
    prog_file = 'infer_model/model.pdmodel'
    params_file = 'infer_model/params.pdparams'
    batch_size = 1
    word_dict_path = "./conf/word.dic"
    label_dict_path = "./conf/tag.dic"
    word_rep_dict_path = "./conf/q2b.dic"
    
    
args = Args()
dataset = reader.Dataset(args)

# def text2inds(text_list):
def text2tensor(text):
    
    tensor = PaddleTensor()
    tensor.name = "words"
    tensor.shape = [len(text), 1]
    tensor.dtype = PaddleDType.INT64
    
    UNK = dataset.word2id_dict[u'OOV']
    tensor.data = PaddleBuf([dataset.word2id_dict.get(word, UNK) for word in text])
    
    return tensor

test_data = [u'百度是一家高科技公司', u'中山大学是岭南第一学府']
tensor = [text2tensor(text) for text in test_data]

config = AnalysisConfig(args.model_dir)
config.set_prog_file(args.prog_file)
config.set_params_file(args.params_file)
config.disable_gpu()

# Create PaddlePredictor
predictor = create_paddle_predictor(config)
print(predictor)

outputs = predictor.run([tensor[0]])
print(outputs)
```
会出现下述错误信息：
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/23732409/64763472-a56ec980-d572-11e9-972f-c73f8e9a6466.png">

**Comment by Shixiaowei02** [comment]
您好，我使用 Paddle develop 分支复现了一下您的脚本，得到如下报错信息，和你的不同。
段错误的原因可能与系统环境相关，请检查一下下面的报错。

```
# python ./deploy_test.py
WARNING: Do not have avx core. You may not build with AVX, but AVX is supported on local machine.
 You could build paddle WITH_AVX=ON to get better performance.
The original error is: No module named core_avx
W0912 16:00:17.655975 14293 init.cc:164] AVX is available, Please re-compile on local machine
W0912 16:00:17.731292 14293 init.cc:164] AVX is available, Please re-compile on local machine
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [fc_lstm_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
---  detected 4 subgraphs
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [fc_fuse_pass]
---  detected 1 subgraphs
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I0912 16:00:17.759228 14293 analysis_predictor.cc:475] == optimize end ==
<paddle.fluid.core_noavx.AnalysisPredictor object at 0x7ff2c8da14c8>
Traceback (most recent call last):
  File "./deploy_test.py", line 50, in <module>
    outputs = predictor.run([tensor[0]])
paddle.fluid.core_noavx.EnforceNotMet: Invoke operator lookup_table error.
Python Call stacks:
  File "/home/work/huangdingbang/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/work/huangdingbang/anaconda3/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/work/huangdingbang/anaconda3/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 414, in embedding
    'padding_idx': padding_idx
  File "../models/sequence_labeling/nets.py", line 85, in _net_conf
    low=-init_bound, high=init_bound)))
  File "../models/sequence_labeling/nets.py", line 124, in lex_net
    return _net_conf(word)
  File "/home/work/huangdingbang/models/PaddleNLP/lexical_analysis/creator.py", line 27, in create_model
    crf_decode = nets.lex_net(words, args, vocab_size, num_labels, for_infer=True, target=None)
  File "inference_model.py", line 45, in save_inference_model
    args, dataset.vocab_size, dataset.num_labels, mode='infer')
  File "inference_model.py", line 116, in <module>
    save_inference_model(args)
C++ Call stacks:
Enforce failed. Expected ids[i] < row_number, but received ids[i]:1094713344 >= row_number:20941.
Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 20941, but got 1094713344. Please check input value. at [/shixiaowei02/Paddle_matmul/Paddle/paddle/fluid/operators/lookup_table_op.h:94]
PaddlePaddle Call Stacks:
0       0x7ff2bc07d6dap std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int) + 378
1       0x7ff2bc07d998p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 40
2       0x7ff2bc559327p paddle::operators::LookupTableKernel<float>::Compute(paddle::framework::ExecutionContext const&) const + 3239
3       0x7ff2bc559790p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LookupTableKernel<float>, paddle::operators::LookupTableKernel<double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 32
4       0x7ff2bd1273cdp paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 381
5       0x7ff2bd127c78p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 296
6       0x7ff2bd122d46p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 246
7       0x7ff2bd0e2afdp paddle::framework::NaiveExecutor::Run() + 205
8       0x7ff2bc261483p paddle::AnalysisPredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int) + 179
9       0x7ff2bc1811fcp
10      0x7ff2bc0ab109p
11      0x7ff31062fd82p PyEval_EvalFrameEx + 29874
12      0x7ff31063209dp PyEval_EvalCodeEx + 2061
13      0x7ff3106321d2p PyEval_EvalCode + 50
14      0x7ff31065e202p PyRun_FileExFlags + 146
15      0x7ff31065f599p PyRun_SimpleFileExFlags + 217
16      0x7ff31067550dp Py_Main + 3149
17      0x7ff30f86ebd5p __libc_start_main + 245
18            0x4007a1p
```

**Comment by Bond-H** [comment]
通过打印输入的list的数值如下所示：

百度是一家高科技公司
[407, 910, 1178, 150, 120, 123, 170, 2655, 526, 992]
中山大学是岭南第一学府
[168, 137, 117, 154, 1178, 700, 211, 1873, 150, 154, 1072]

并未发现错误信息中提示的边界错误问题：ids[i]:1094713344，是不是调用方法上存在错误，原本的模型的输入是LOD Tensor

**Comment by Bond-H** [comment]
该问题已解决，通过定义Tensor的lod属性即可，从文本到lod tensor的定义如下所示
```
def texts2tensor(texts):
    tensor = PaddleTensor()
    tensor.name = "words"
    lod = [0]
    data = []
    UNK = dataset.word2id_dict[u'OOV']
    for i,text  in enumerate(texts):
        lod.append(len(text)+lod[i])
        data += [dataset.word2id_dict.get(word, UNK) for word in text]
        
    tensor.lod = [lod]
    tensor.shape = [lod[-1], 1]
    tensor.dtype = PaddleDType.INT64
    tensor.data = PaddleBuf(data)

    return tensor
```
