### ISSUE TITLE
孔明集群demo多机使用paddle1.5.2运行失败

### ISSUE THREAD

**Issue by bit-pku-zdf** [PaddlePaddle/Paddle#20168]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.2
    3）GPU：孔明集群
    1）多机多卡

使用孔明集群的demo http://wiki.baidu.com/display/HICHAC/paddle+fluid+nccl2+demo,   
wget -e "http_proxy=cp01-sys-hic-gpu-02.cp01:8888" http://cp01-sys-hic-gpu-02.cp01/HGCP_DEMO/fluid_1.1.0_for_slurm.tar.gz
的nccl2模式可以进行正常训练，但是使用paddle1.5.2版本有出问题了
http://yq01-sys-hic-v100-box-a223-0151.yq01.baidu.com:8388/v1/slurmjobs/80162/workspace

Traceback (most recent call last): File "fluid_benchmark.py", line 368, in <module> main() File "fluid_benchmark.py", line 364, in main train_parallel(*all_args) File "fluid_benchmark.py", line 169, in train_parallel startup_exe.run(startup_prog) File "/home/slurm/job/tmp/job-80162/python2_paddle_release/lib/python2.7/site-packages/paddle/fluid/executor.py", line 657, in run use_program_cache=use_program_cache) File "/home/slurm/job/tmp/job-80162/python2_paddle_release/lib/python2.7/site-packages/paddle/fluid/executor.py", line 755, in _run exe.run(program.desc, scope, 0, True, True, fetch_var_name) paddle.fluid.core_avx.EnforceNotMet: Invoke operator gen_nccl_id error. Python Call stacks:  File "/home/slurm/job/tmp/job-80162/python2_paddle_release/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1774, in append_op attrs=kwargs.get("attrs", None)) File "fluid_benchmark.py", line 55, in append_nccl2_prepare "trainer_id": trainer_id File "fluid_benchmark.py", line 359, in main trainer_id, startup_prog) File "fluid_benchmark.py", line 368, in <module> main() C++ Call stacks:  trainer_id:0 must be in trainers.size range at [/paddle/paddle/fluid/operators/distributed_ops/gen_nccl_id_op.cc:49] PaddlePaddle Call Stacks:  0 0x7f5f5d780ff0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352 1 0x7f5f5d781369p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137 2 0x7f5f5e5a9d4ep paddle::operators::GenNCCLIdOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 4334 3 0x7f5f5f6f9833p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 307 4 0x7f5f5d90e6aep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 398 5 0x7f5f5d91174fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143 6 0x7f5f5d77242dp 7 0x7f5f5d7b4476p 8 0x4b8c9fp PyEval_EvalFrameEx + 32943 9 0x4ba7c8p PyEval_EvalCodeEx + 2040 10 0x4b83b7p PyEval_EvalFrameEx + 30663 11 0x4ba7c8p PyEval_EvalCodeEx + 2040 12 0x4b83b7p PyEval_EvalFrameEx + 30663 13 0x4ba7c8p PyEval_EvalCodeEx + 2040 14 0x52ee40p 15 0x422f4ap PyObject_Call + 58 16 0x4b2e19p PyEval_EvalFrameEx + 8745 17 0x4b88afp PyEval_EvalFrameEx + 31935 18 0x4ba7c8p PyEval_EvalCodeEx + 2040 19 0x4ba8f2p PyEval_EvalCode + 50 20 0x4e6e9dp PyRun_FileExFlags + 285 21 0x4e8721p PyRun_SimpleFileExFlags + 209 22 0x415bbdp Py_Main + 2925 23 0x7f605df5bbd5p __libc_start_main + 245 24 0x414d51p

麻烦帮忙看看，谢谢

**Comment by bjjwwang** [comment]
@gongweibao  @sandyhouse  求大佬帮忙看下这个issue有没有解决方法 谢谢。

**Comment by sandyhouse** [comment]
> 使用孔明集群的demo http://wiki.baidu.com/display/HICHAC/paddle+fluid+nccl2+demo,
wget -e "http_proxy=cp01-sys-hic-gpu-02.cp01:8888" http://cp01-sys-hic-gpu-02.cp01/HGCP_DEMO/fluid_1.1.0_for_slurm.tar.gz
的nccl2模式可以进行正常训练，但是使用paddle1.5.2版本有出问题了
这句话是什么意思？在哪个版本可以正常运行？
另外，日志链接已经失效了，上面的报错是运行demo程序的错误吗？还是改动过的程序？
@bit-pku-zdf
