### ISSUE TITLE
batch_size>8出现Segmentation fault

### ISSUE THREAD

**Issue by wangsouc** [PaddlePaddle/Paddle#2038]
当batch_size<=8时能正常跑完所有数据，batch_size>8则core，

batch_size=16时，错误如下：
```
I0507 18:18:38.280385 29055 TrainerInternal.cpp:165]  Batch=450 samples=7200 AvgCost=0.160137 CurrentCost=0.131799 Eval: __auc_evaluator_0__=0.577332 classification_error_evaluator=0.0363889  CurrentEval: __auc_evaluator_0__=0.716129 classification_error_evaluator=0.03125

*** Aborted at 1494152318 (unix time) try "date -d @1494152318" if you are using GNU date ***

PC: @          0x2458938 (unknown)

*** SIGILL (@0x2458938) received by PID 29055 (TID 0x7f40804ae700) from PID 38111544; stack trace: ***

    @     0x7f40bb1eb160 (unknown)

    @          0x2458938 (unknown)
/home/work/wangsijiang/deepctr/thirdparty/output/bin/paddle: line 46: 29055 Illegal instruction     ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
```

batch_size=32时，错误如下：
```
I0507 18:19:23.252508 31606 TrainerInternal.cpp:165]  Batch=10 samples=320 AvgCost=0.581496 CurrentCost=0.581496 Eval: __auc_evaluator_0__=0.480892 classification_error_evaluator=0.2625  CurrentEval: __auc_evaluator_0__=0.480892 classification_error_evaluator=0.2625

*** Aborted at 1494152363 (unix time) try "date -d @1494152363" if you are using GNU date ***

PC: @                0x1 (unknown)
/home/work/wangsijiang/deepctr/thirdparty/output/bin/paddle: line 46: 31606 Segmentation fault      ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
```

batch_size=64时，直接挂了：
```
*** Aborted at 1494152447 (unix time) try "date -d @1494152447" if you are using GNU date ***

PC: @                0x1 (unknown)
/home/work/wangsijiang/deepctr/thirdparty/output/bin/paddle: line 46:  4128 Segmentation fault      ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
```

**Comment by wangsouc** [comment]
在另外一条机器上测试也是如此，gdb查看错误如下：
```
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/users/wangsijiang01/.jumbo/bin/../opt/paddle/bin/paddle_trainer...
done.
[New LWP 4259]
[New LWP 3799]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/tls/libthread_db.so.1".
Core was generated by `/home/users/wangsijiang01/.jumbo/bin/../opt/paddle/bin/paddle_trainer --config='.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  x86_64_fallback_frame_state (fs=0x41332bb0, context=<optimized out>)
    at /home/users/wangsijiang01/.jumbo/var/jumbo/tmp/jumbo.yryc30742/gcc46/src/gcc-4.6.3/libgcc/../gcc/config/i386/linux-unwind.h:47
47	/home/users/wangsijiang01/.jumbo/var/jumbo/tmp/jumbo.yryc30742/gcc46/src/gcc-4.6.3/libgcc/../gcc/config/i386/linux-unwind.h: No such file or directory.
[Current thread is 1 (Thread 0x41334960 (LWP 4259))]
warning: File "/home/users/wangsijiang01/.jumbo/opt/gcc46/lib64/libstdc++.so.6.0.16-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /home/users/wangsijiang01/.jumbo/opt/gcc46/lib64/libstdc++.so.6.0.16-gdb.py
line to your configuration file "/home/users/wangsijiang01/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/users/wangsijiang01/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
(gdb)
(gdb)
(gdb) bt
#0  x86_64_fallback_frame_state (fs=0x41332bb0, context=<optimized out>)
    at /home/users/wangsijiang01/.jumbo/var/jumbo/tmp/jumbo.yryc30742/gcc46/src/gcc-4.6.3/libgcc/../gcc/config/i386/linux-unwind.h:47
#1  uw_frame_state_for (fs=0x41332bb0, context=0x41332d30)
    at /home/users/wangsijiang01/.jumbo/var/jumbo/tmp/jumbo.yryc30742/gcc46/src/gcc-4.6.3/libgcc/../gcc/unwind-dw2.c:1145
#2  uw_frame_state_for (context=0x41332d30, fs=0x41332bb0)
    at /home/users/wangsijiang01/.jumbo/var/jumbo/tmp/jumbo.yryc30742/gcc46/src/gcc-4.6.3/libgcc/../gcc/unwind-dw2.c:1124
#3  0x00007f4ed2701cdd in _Unwind_Backtrace (trace=0x3f0b0d71e0 <backtrace_helper>, trace_argument=0x41332e60)
    at /home/users/wangsijiang01/.jumbo/var/jumbo/tmp/jumbo.yryc30742/gcc46/src/gcc-4.6.3/libgcc/../gcc/unwind.inc:290
#4  0x0000003f0b0d729f in backtrace () from /lib64/tls/libc.so.6
#5  0x00007f4ed2d3ea91 in google::GetStackTrace(void**, int, int) () from /home/users/wangsijiang01/.jumbo/lib/libglog.so.0
#6  0x00007f4ed2d438e5 in google::(anonymous namespace)::FailureSignalHandler(int, siginfo*, void*) () from /home/users/wangsijiang01/.jumbo/lib/libglog.so.0
#7  <signal handler called>
#8  0x0000000000000001 in ?? ()
#9  0x00007f4ed2ec96b0 in list_dealloc (op=0x7f4e9cbd0b48) at Objects/listobject.c:309
#10 0x00007f4ed2f2efd0 in PyEval_EvalFrameEx (f=0x7f4e9cc10080, throwflag=<optimized out>) at Python/ceval.c:2211
#11 0x00007f4ed2f33cf6 in call_function (pp_stack=0x41333bb8, oparg=<optimized out>) at Python/ceval.c:4107
#12 0x00007f4ed2f33cf6 in PyEval_EvalFrameEx (f=0x7f4e9cc03f90, throwflag=<optimized out>) from /home/users/wangsijiang01/.jumbo/lib/libpython2.7.so.1.0
#13 0x00007f4ed2f33cf6 in call_function (pp_stack=0x41333df8, oparg=<optimized out>) at Python/ceval.c:4107
#14 0x00007f4ed2f33cf6 in PyEval_EvalFrameEx (f=0x1c908f0, throwflag=<optimized out>) from /home/users/wangsijiang01/.jumbo/lib/libpython2.7.so.1.0
#15 0x00007f4ed2ebc00d in gen_send_ex (gen=0x7f4ed03e7f50, arg=0x0, exc=2) at Objects/genobject.c:84
#16 0x00007f4ed2ea253b in PyIter_Next (iter=0x7f4e9ccec640) at Objects/abstract.c:3107
#17 0x00000000005b749f in paddle::py::iterNext (atEnd=<synthetic pointer>, context=...)
    at /home/users/wangsijiang01/.jumbo/var/jumbo/tmp/jumbo.Pgvb32429/paddle/src/paddle/paddle/utils/PythonUtil.h:315
#18 paddle::PyDataProvider2::loadThread (this=0x1c36b88)
    at /home/users/wangsijiang01/.jumbo/var/jumbo/tmp/jumbo.Pgvb32429/paddle/src/paddle/paddle/gserver/dataproviders/PyDataProvider2.cpp:333
#19 0x00007f4ed2972108 in execute_native_thread_routine () from /home/users/wangsijiang01/.jumbo/opt/gcc46/lib64/libstdc++.so.6
#20 0x0000003f0b90610a in start_thread () from /lib64/tls/libpthread.so.0
#21 0x0000003f0b0c5ee3 in clone () from /lib64/tls/libc.so.6
#22 0x0000000000000000 in ?? ()
```
