### ISSUE TITLE
提交任务报错

### ISSUE THREAD

**Issue by AWSWXY** [PaddlePaddle/Paddle#20478]
使用receiver提交任务报错如下：
connect to receiver:  yq01-idl-gpu-offline14.yq01.baidu.com:9295
compressing thirdparty files
finished to pack request
starting to submit to server
Traceback (most recent call last):
  File "/home/disk5/wuyongchao/paddle/output/submit.py", line 303, in <module>
    no_prefix_train_args_dict, ).run()
  File "/home/disk5/wuyongchao/paddle/output/submit.py", line 77, in run
    self._do_poster_request()
  File "/home/disk5/wuyongchao/paddle/output/submit.py", line 168, in _do_poster_request
    connection = urllib2.urlopen(request)
  File "/home/work/.jumbo/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/home/work/.jumbo/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/home/work/.jumbo/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/home/work/.jumbo/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/home/work/.jumbo/lib/python2.7/site-packages/poster-0.8.1-py2.7.egg/poster/streaminghttp.py", line 142, in http_open
  File "/home/work/.jumbo/lib/python2.7/urllib2.py", line 1177, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>

**Comment by yongqiangma** [comment]
应该是receiver的问题，改了端口号解决了
