### ISSUE TITLE
paddle 优化器问题

### ISSUE THREAD

**Issue by kebinC** [PaddlePaddle/Paddle#20561]
```
import paddle
import paddle.fluid as fluid
import numpy as np
import math

#boundaries2 = [10000, 20000]
#values2 = [1.0, 0.5, 0.1]
#optimizer2 = fluid.optimizer.Momentum(
#    momentum=0.9,
#    learning_rate=fluid.layers.piecewise_decay(boundaries=boundaries2, values=values2),
#    regularization=fluid.regularizer.L2Decay(1e-4))

class arcmarginloss():
    def __init__(self, class_dim, margin=0.2, scale=30.0, easy_margin=False):
        self.class_dim = class_dim
        self.margin = margin
        self.scale = scale
        self.easy_margin = easy_margin

    def loss(self, input, label):
        out = self.arc_margin_product(input, label, self.class_dim, self.margin, self.scale, self.easy_margin)
        loss = fluid.layers.softmax_with_cross_entropy(logits=out, label=label)
        return loss, out

    def arc_margin_product(self, input, label, out_dim, m, s, easy_margin=False):
        #input = fluid.layers.l2_normalize(input, axis=1)
        input_norm = fluid.layers.sqrt(fluid.layers.reduce_sum(fluid.layers.square(input), dim=1))
        input = fluid.layers.elementwise_div(input, input_norm, axis=0)

        weight = fluid.layers.create_parameter(
                    shape=[out_dim, input.shape[1]],
                    dtype='float32',
                    name='weight_norm',
                    attr=fluid.param_attr.ParamAttr(
                                  initializer=fluid.initializer.Constant(value=1.0)))
        #weight = fluid.layers.l2_normalize(weight, axis=1)
        weight_norm = fluid.layers.sqrt(fluid.layers.reduce_sum(fluid.layers.square(weight), dim=1))
        weight = fluid.layers.elementwise_div(weight, weight_norm, axis=0)
        weight = fluid.layers.transpose(weight, perm = [1, 0])
        cosine = fluid.layers.mul(input, weight)
        sine = fluid.layers.sqrt(1.0 - fluid.layers.square(cosine))

        cos_m = math.cos(m)
        sin_m = math.sin(m)
        phi = cosine * cos_m - sine * sin_m

        th = math.cos(math.pi - m)
        mm = math.sin(math.pi - m) * m
        if easy_margin:
            phi = self.paddle_where_more_than(cosine, 0, phi, cosine)
        else:
            phi = self.paddle_where_more_than(cosine, th, phi, cosine-mm)

        fluid.layers.Print(label)
        one_hot = fluid.layers.one_hot(input=label, depth=out_dim)
        output = fluid.layers.elementwise_mul(one_hot, phi) + fluid.layers.elementwise_mul((1.0 - one_hot), cosine)
        output = output * s
        return output

    def paddle_where_more_than(self, target, limit, x, y):
        mask = fluid.layers.cast(x=(target>limit), dtype='float32')
        output = fluid.layers.elementwise_mul(mask, x) + fluid.layers.elementwise_mul((1.0 - mask), y)
        return output


def test():

    startup_prog = fluid.Program()
    train_prog = fluid.Program()

    def build_net(startup_prog, train_prog):
        with fluid.program_guard(train_prog, startup_prog):
            input_np = np.load('./tmp2.npy')
            input = fluid.layers.create_global_var(
                        shape=[10, 100], value=0, dtype='float32', persistable=True)
            fluid.layers.assign(input_np, input)

            label = fluid.layers.create_global_var(
                        shape=[10, 1], value=1, dtype='int64', persistable=True)
            with fluid.unique_name.guard():
                loss = arcmarginloss(class_dim=100)
                output = loss.loss(input, label)
                avg_loss = fluid.layers.mean(x=output[0])
        return avg_loss

    def build_optimizer():
        optimizer = fluid.optimizer.Momentum(
            momentum=0.9,
            learning_rate=fluid.layers.piecewise_decay(boundaries=[10000,20000], values=[0.1,0.01,0.001]),
            regularization=fluid.regularizer.L2Decay(1e-4))
        return optimizer

    def build_backward(main_prog, startup_prog, avg_cost):
        with fluid.program_guard(main_prog, startup_prog):
            with fluid.unique_name.guard():
                optimizer = build_optimizer()
                optimizer.minimize(avg_cost)
                global_lr = optimizer._global_learning_rate()
        return global_lr

    loss = build_net(startup_prog, train_prog)
    global_lr = build_backward(train_prog, startup_prog, loss)
    fetch_list = [loss.name]
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(startup_prog)

    res = exe.run(
                train_prog,
                fetch_list=fetch_list
            )
    print res

test()
```

直接运行log：
```
Traceback (most recent call last):
  File "test_arcmargin2.py", line 114, in <module>
    test()
  File "test_arcmargin2.py", line 102, in test
    global_lr = build_backward(train_prog, startup_prog, loss)
  File "test_arcmargin2.py", line 96, in build_backward
    optimizer = build_optimizer()
  File "test_arcmargin2.py", line 89, in build_optimizer
    learning_rate=fluid.layers.piecewise_decay(boundaries=[10000,20000], values=[0.1,0.01,0.001]),
  File "/home/users/chenkaibing/env/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/layers/learning_rate_scheduler.py", line 384, in piecewise_decay
    tensor.assign(value_var, lr)
  File "/home/users/chenkaibing/env/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/layers/control_flow.py", line 1322, in __exit__
    self.block.complete()
  File "/home/users/chenkaibing/env/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/layers/control_flow.py", line 1395, in complete
    type=core.VarDesc.VarType.STEP_SCOPES)
  File "/home/users/chenkaibing/env/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1600, in create_var
    var = Variable(block=self, *args, **kwargs)
  File "/home/users/chenkaibing/env/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/framework.py", line 457, in __init__
    type))
ValueError: Variable _generated_var_0 has been created before. The previous type is VarType.LOD_TENSOR; the new type is VarType.STEP_SCOPES. They are not matched
```

打开开头的注释运行log：
```
Traceback (most recent call last):
  File "test_arcmargin2.py", line 114, in <module>
    test()
  File "test_arcmargin2.py", line 102, in test
    global_lr = build_backward(train_prog, startup_prog, loss)
  File "test_arcmargin2.py", line 97, in build_backward
    optimizer.minimize(avg_cost)
  File "<decorator-gen-20>", line 2, in minimize
  File "/home/users/chenkaibing/env/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/users/chenkaibing/env/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/dygraph/base.py", line 88, in __impl__
    return func(*args, **kwargs)
  File "/home/users/chenkaibing/env/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 593, in minimize
    no_grad_set=no_grad_set)
  File "/home/users/chenkaibing/env/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 493, in backward
    no_grad_set, callbacks)
  File "/home/users/chenkaibing/env/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/backward.py", line 577, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/home/users/chenkaibing/env/paddle-release/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/backward.py", line 392, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core_avx.EnforceNotMet: Enforce failed. Expected in_dim.size() == x_dim.size(), but received in_dim.size():1 != x_dim.size():2.
Input tensors must have same shape size at [/paddle/paddle/fluid/operators/sum_op.cc:74]
PaddlePaddle Call Stacks:
0       0x7fdcb66f02c8p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7fdcb66f0617p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7fdcb721d6d0p paddle::operators::SumOp::InferShape(paddle::framework::InferShapeContext*) const + 4912
3       0x7fdcb6860baep paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 862
4       0x7fdcb679c19cp
5       0x7fdcb6722d86p
6       0x7fdd05a2b55fp PyEval_EvalFrameEx + 29855
7       0x7fdd05a2d86dp PyEval_EvalCodeEx + 2061
8       0x7fdd05a2a9fcp PyEval_EvalFrameEx + 26940
9       0x7fdd05a2d86dp PyEval_EvalCodeEx + 2061
10      0x7fdd05a2a9fcp PyEval_EvalFrameEx + 26940
11      0x7fdd05a2d86dp PyEval_EvalCodeEx + 2061
12      0x7fdd05a2a9fcp PyEval_EvalFrameEx + 26940
13      0x7fdd05a2d86dp PyEval_EvalCodeEx + 2061
14      0x7fdd059a4015p
15      0x7fdd05971f13p PyObject_Call + 67
16      0x7fdd05a27657p PyEval_EvalFrameEx + 13719
17      0x7fdd05a2d86dp PyEval_EvalCodeEx + 2061
18      0x7fdd059a4015p
19      0x7fdd05971f13p PyObject_Call + 67
20      0x7fdd05a27657p PyEval_EvalFrameEx + 13719
21      0x7fdd05a2d86dp PyEval_EvalCodeEx + 2061
22      0x7fdd05a2a9fcp PyEval_EvalFrameEx + 26940
23      0x7fdd05a2d86dp PyEval_EvalCodeEx + 2061
24      0x7fdd05a2a9fcp PyEval_EvalFrameEx + 26940
25      0x7fdd05a2d86dp PyEval_EvalCodeEx + 2061
26      0x7fdd05a2a9fcp PyEval_EvalFrameEx + 26940
27      0x7fdd05a2d86dp PyEval_EvalCodeEx + 2061
28      0x7fdd05a2a9fcp PyEval_EvalFrameEx + 26940
29      0x7fdd05a2d86dp PyEval_EvalCodeEx + 2061
30      0x7fdd05a2d9a2p PyEval_EvalCode + 50
31      0x7fdd05a56782p PyRun_FileExFlags + 146
32      0x7fdd05a57af9p PyRun_SimpleFileExFlags + 217
33      0x7fdd05a6d82dp Py_Main + 3149
34      0x7fdd04c6abd5p __libc_start_main + 245
35            0x4007a1p
```

**Comment by MyPandaShaoxiang** [comment]
你好，看起来好像是模型构建问题，我在这边复现一下

**Comment by kebinC** [comment]
> 这边复现一下
不加optimizer是可以跑的

**Comment by HaoLiuHust** [comment]
@kebinC 你这个loss经过验证了么。。我使用的时候loss一直为0

**Comment by kebinC** [comment]
> @kebinC 你这个loss经过验证了么。。我使用的时候loss一直为0

 验证过的，可以参考：
https://github.com/PaddlePaddle/models/blob/release/1.8/PaddleCV/metric_learning/losses/arcmarginloss.py

**Comment by HaoLiuHust** [comment]
多谢，想问一下，为啥代码里不直接用l2_normalization layer，而要自己算norm去除呢 @kebinC

**Comment by kebinC** [comment]
> 多谢，想问一下，为啥代码里不直接用l2_normalization layer，而要自己算norm去除呢 @kebinC

早些时候l2_normalization op存在问题，现在没问题了，可以直接用了，只是没改回去。
