### ISSUE TITLE
mac下安装cpu版本，安装成功，运行失败

### ISSUE THREAD

**Issue by zhuantouer** [PaddlePaddle/Paddle#20582]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.2
    2）系统环境：MacBook Pro (Retina, 13-inch, Early 2015)
- 安装方式信息：
1）pip安装

```
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fuild
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xx/anaconda3/envs/py3env/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    import paddle.dataset
  File "/Users/xx/anaconda3/envs/py3env/lib/python3.7/site-packages/paddle/dataset/__init__.py", line 28, in <module>
    import paddle.dataset.mq2007
  File "/Users/xx/anaconda3/envs/py3env/lib/python3.7/site-packages/paddle/dataset/mq2007.py", line 30, in <module>
    import rarfile
  File "/Users/xx/anaconda3/envs/py3env/lib/python3.7/site-packages/rarfile.py", line 2950, in <module>
    _check_unrar_tool()
  File "/Users/xx/anaconda3/envs/py3env/lib/python3.7/site-packages/rarfile.py", line 2931, in _check_unrar_tool
    custom_check([ORIG_UNRAR_TOOL], True)
  File "/Users/xx/anaconda3/envs/py3env/lib/python3.7/site-packages/rarfile.py", line 2823, in custom_check
    p = custom_popen(cmd)
  File "/Users/xx/anaconda3/envs/py3env/lib/python3.7/site-packages/rarfile.py", line 2813, in custom_popen
    creationflags=creationflags)
  File "/Users/xx/anaconda3/envs/py3env/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/xx/anaconda3/envs/py3env/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'unrar'
```

**Comment by MyPandaShaoxiang** [comment]
你好，pip3 install unrar安装一下unrar

**Comment by zhuantouer** [comment]
@MyPandaShaoxiang 试过了，还是上面的错误

**Comment by baomengxue** [comment]
@zishuaiz 请问conda env list中还存在其他conda环境吗？

**Comment by baomengxue** [comment]
@zishuaiz 或者 py3env环境是在(base)环境下create的吗？建议退出所有conda虚拟环境后再create 新环境安装paddle，尝试一下哈。

**Comment by zhuantouer** [comment]
还有一个py2env， 只开了一个3环境，还是报错
我再试试其他方法吧，多谢
