### ISSUE TITLE
input data_feeder order  bug

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#2062]
which index determine the data_feeder order during training a model? it is the generator, the feeding argument in trainer or the layer order in model?

```python
# data generater
yield relevance_score_list[i], np.array(feature_vector_list[i])
# their type is int, np.array(shape=(1, 46)) respectively
```

```python
#model layer order
  label = paddle.layer.data("label", paddle.data_type.integer_value_sequence(1))
  data = paddle.layer.data("data", paddle.data_type.dense_vector(feature_dim))
```

```python
#feeding dict order with index
  feeding = {"label":0,
             "data": 1}
  trainer.train(reader=train_reader,
                event_handler=event_handler,
                feeding=feeding,
                num_passes=num_passes)
```
everywhere in my model i configurate the order of  `[label,data]`, but the log information tell that input order is ` [data, label]`
```c++
I0508 21:56:25.619045 17006 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=4
[INFO 2017-05-08 21:56:25,626 networks.py:1472] The input order is [data, label]
[INFO 2017-05-08 21:56:25,626 networks.py:1478] The output order is [__lambda_cost_0__]
[INFO 2017-05-08 21:56:25,630 networks.py:1472] The input order is [data, label]
[INFO 2017-05-08 21:56:25,630 networks.py:1478] The output order is [__lambda_cost_0__]
```

the error log as shown, which is the reason for my suspicion. it complain about int type input, which should be the second input in my configuration.l

```python
Traceback (most recent call last):
  File "lambdaRank.py", line 100, in <module>
    train_lambdaRank(2)
  File "lambdaRank.py", line 79, in train_lambdaRank
    num_passes=num_passes)
  File "/home/work/fengjiayi/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/paddle/v2/trainer.py", line 114, in t
rain
    feeder(data_batch), out_args, pass_type)
  File "/home/work/fengjiayi/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py"$
 line 249, in __call__
    return self.convert(dat, argument)
  File "/home/work/fengjiayi/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 134,
in convert
    return DataProviderConverter.convert(self, reorder_data(dat), argument)
  File "/home/work/fengjiayi/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py",
 line 234, in convert
    scanner.pre_scan(each_step)
  File "/home/work/fengjiayi/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py",
 line 191, in pre_scan
    for each in dat:
TypeError: 'int' object is not iterable
```

**Comment by qingqing01** [comment]
> everywhere in my model i configurate the order of [label,data], but the log information tell that input order is [data, label]

The two order can be different. The data_feeder would reorder the input data and feed the correct order of data to C++ code based on the `feeding` dictionary（ `feeding = {"label":0,"data": 1}`).

**Comment by dzhwinter** [comment]
Ok, I see. the score vector should be a list of int value, not a single value. That's the bug. But how can I construct the parameter to the lambda_cost with a list of instance?

**Comment by qingqing01** [comment]
Do you use the `paddle.batch`  interface?

**Comment by qingqing01** [comment]
> label = paddle.layer.data("label", paddle.data_type.integer_value_sequence(1))

- For the type of `integer_value_sequence`, the input data format should be: [label], a list of integer value
- For the type of `integer_value`, the input data format should be:  label, a single integer value

> But how can I construct the parameter to the lambda_cost with a list of instance?

For training, you can use `paddle.batch` interface.

**Comment by dzhwinter** [comment]
after i change the input type as sequence,  get this error message 

```c++
Thread [140350399067904] Forwarding __lambda_cost_0__, label, /output, data,
*** Aborted at 1494330029 (unix time) try "date -d @1494330029" if you are using GNU date ***

PC: @                0x0 (unknown)

*** SIGSEGV (@0x0) received by PID 19709 (TID 0x7fa5dfae3700) from PID 0; stack trace: ***

    @     0x7fa5ed031160 (unknown)

    @     0x7fa5e6ba6a96 paddle::LambdaCost::forward()

    @     0x7fa5e6c83940 paddle::NeuralNetwork::forward()

    @     0x7fa5e6c77d85 paddle::TrainerThread::forward()

    @     0x7fa5e6c7a445 paddle::TrainerThread::computeThread()

    @     0x7fa5e66858a0 execute_native_thread_routine

    @     0x7fa5ed0291c3 start_thread

    @     0x7fa5ec65112d __clone

    @                0x0 (unknown)
Segmentation fault (core dumped)
```

**Comment by lcy-seso** [comment]
Is this helpful?
```
label = paddle.layer.data("label", paddle.data_type.dense(1))
data = paddle.layer.data("data", paddle.data_type.dense_vector_sequence(feature_dim))
```

**Comment by lcy-seso** [comment]
It is probably due to data with a wrong format is returned.
Could you give more details about how data are generated and how you cost layer is defined (with input layers connected to it)?

**Comment by qingqing01** [comment]
>   label = paddle.layer.data("label", paddle.data_type.integer_value_sequence(1))

Maybe the type should be as follows base on the code: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/CostLayer.cpp#L385

```
label = paddle.layer.data("label", paddle.data_type. dense_vector_sequence(1))
```

**Comment by dzhwinter** [comment]
the data generator shows
```python
def gen_list(querylist):
  """
  gen item in list for list-wise learning to rank algorithm
  Paramters:
  --------
  querylist : querylist, one query match many docment pairs in list, see QueryList

  return :
  ------
  label : np.array, shape=(samples_num, )
  querylist : np.array, shape=(samples_num, feature_dimension)
  """
  if not isinstance(querylist, QueryList):
    querylist = QueryList(querylist)                                                                                                                            querylist._correct_ranking_()
  relevance_score_list = [query.relevance_score for query in querylist]
  feature_vector_list = [query.feature_vector for query in querylist]                                                                                           yield np.array(relevance_score_list).T, np.array(feature_vector_list)
```
cost layer definition here 
```python
  label = paddle.layer.data("label", paddle.data_type.integer_value_sequence(1))
  data = paddle.layer.data("data", paddle.data_type.dense_vector_sequence(feature_dim))

  output = paddle.layer.fc(
    name="/output",
    input=data,
    size=1,
    act=paddle.activation.Linear(),
    param_attr=paddle.attr.Param(initial_std=0.01, name="output"))
  cost = paddle.layer.lambda_cost(input=output,
                                  score=label,
                                  NDCG_num=1,
                                  max_sort_size = -1)
```

**Comment by dzhwinter** [comment]
just as @qingqing01  suggestions, 
when i change the model definition to 
```python
  label = paddle.layer.data("label", paddle.data_type.dense_vector(1))
  data = paddle.layer.data("data", paddle.data_type.dense_vector_sequence(feature_dim))
```
the error log 
```c++
Traceback (most recent call last):
  File "lambdaRank.py", line 100, in <module>
    train_lambdaRank(2)
  File "lambdaRank.py", line 79, in train_lambdaRank
    num_passes=num_passes)
  File "/home/work/fengjiayi/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/paddle/v2/trainer.py", line 114, in train
    feeder(data_batch), out_args, pass_type)
  File "/home/work/fengjiayi/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 249, in __call__
    return self.convert(dat, argument)
  File "/home/work/fengjiayi/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 134, in convert
    return DataProviderConverter.convert(self, reorder_data(dat), argument)
  File "/home/work/fengjiayi/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 241, in convert
    scanner.scan(each_step)
  File "/home/work/fengjiayi/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 109, in scan
    self.__mat__[self.__height__] = dat
ValueError: could not broadcast input array from shape (40) into shape (1)
```

**Comment by lcy-seso** [comment]
Accordding to the source code, data layer should be defined like this.
```
label = paddle.layer.data("label", paddle.data_type.dense_vector_sequence(1))
data = paddle.layer.data("data", paddle.data_type.dense_vector_sequence(feature_dim))
```

**Comment by dzhwinter** [comment]
see models/ltr case, we had finished it.
