### ISSUE TITLE
Docker镜像中的paddle查询版本返回0.0.0

### ISSUE THREAD

**Issue by fengyuentau** [PaddlePaddle/Paddle#20667]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7
    2）CPU/GPU：无关
    3）系统环境：无关
    4）Python版本号：无关
    5）显存信息：无关
- 复现信息：
```shell
$ docker pull paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7
$ nvidia-docker run -it paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7 bash
# 容器内
$ python3.6
>>> import paddle
>>> paddle.__version__
0.0.0
# 运行镜像时不加bash也会打印出来版本0.0.0
$ nvidia-docker run -it paddlepaddle/paddle:latest-gpu-cuda9.0-cudnn7
PaddlePaddle 0.0.0, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON
$
```
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
在paddlepaddle.org中查询了一下诸如'version'，'版本'的关键字，但是都没有关于查询版本的方法介绍。也没有发现在Github issue中有讨论这个问题的。在这样的情况下还有查询版本的方法吗？只知道是latest但是不知道版本号，不利于以后的维护。

**Comment by JepsonWong** [comment]
latest镜像是根据Paddle的develop分支构建的，develop分支本身就没有版本号。

**Comment by fengyuentau** [comment]
@JepsonWong 谢谢。请考虑在docker项目主页提示。刚刚尝试用这个镜像运行PaddlePaddle/models下的PyramidBox，但是总提示找不到模型，怀疑是这个develop分支镜像的问题。正在拉1.5.0再试试。

**Comment by JepsonWong** [comment]
![image](https://user-images.githubusercontent.com/16509038/66912124-903efc00-f044-11e9-852a-8a552f282448.png)
paddle官网页面有镜像说明 https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/install/install_Docker.html

**Comment by JepsonWong** [comment]
> @JepsonWong 谢谢。请考虑在docker项目主页提示。刚刚尝试用这个镜像运行PaddlePaddle/models下的PyramidBox，但是总提示找不到模型，怀疑是这个develop分支镜像的问题。正在拉1.5.0再试试。

这个镜像内部只是安装了paddle环境，您是怎么执行PyramidBox模型的？能把错误log打出来吗？

**Comment by fengyuentau** [comment]
```shell
root@df3a17988b31:~/pyramidbox# python3.6 -u widerface_eval.py --model_dir=/root/pyramidbox/models/PyramidBox_WiderFace
-----------  Configuration Arguments -----------
confs_threshold: 0.15
data_dir: data/WIDER_val/images/
file_list: data/wider_face_split/wider_face_val_bbx_gt.txt
image_path:
infer: False
model_dir: /root/pyramidbox/models/PyramidBox_WiderFace
pred_dir: pred
use_gpu: True
use_pyramidbox: True
------------------------------------------------
Traceback (most recent call last):
  File "widerface_eval.py", line 328, in <module>
    exe, args.model_dir, main_program=infer_program)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/io.py", line 803, in load_persistables
    filename=filename)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/io.py", line 643, in load_vars
    filename=filename)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/io.py", line 664, in load_vars
    assert var_temp != None, "can't not find var: " + each_var.name
AssertionError: can't not find var: conv2d_61.w_0

```
用`ll /root/pyramidbox/models/PyramidBox_WiderFace | grep conv2d_61.w_0`查过是有这个文件的。刚使用paddle，而且在容器内也不好debug。没找到究竟是哪里有错。

**Comment by JepsonWong** [comment]
> ```shell
> root@df3a17988b31:~/pyramidbox# python3.6 -u widerface_eval.py --model_dir=/root/pyramidbox/models/PyramidBox_WiderFace
> -----------  Configuration Arguments -----------
> confs_threshold: 0.15
> data_dir: data/WIDER_val/images/
> file_list: data/wider_face_split/wider_face_val_bbx_gt.txt
> image_path:
> infer: False
> model_dir: /root/pyramidbox/models/PyramidBox_WiderFace
> pred_dir: pred
> use_gpu: True
> use_pyramidbox: True
> ------------------------------------------------
> Traceback (most recent call last):
>   File "widerface_eval.py", line 328, in <module>
>     exe, args.model_dir, main_program=infer_program)
>   File "/usr/local/lib/python3.6/site-packages/paddle/fluid/io.py", line 803, in load_persistables
>     filename=filename)
>   File "/usr/local/lib/python3.6/site-packages/paddle/fluid/io.py", line 643, in load_vars
>     filename=filename)
>   File "/usr/local/lib/python3.6/site-packages/paddle/fluid/io.py", line 664, in load_vars
>     assert var_temp != None, "can't not find var: " + each_var.name
> AssertionError: can't not find var: conv2d_61.w_0
> ```
> 
> 用`ll /root/pyramidbox/models/PyramidBox_WiderFace | grep conv2d_61.w_0`查过是有这个文件的。刚使用paddle，而且在容器内也不好debug。没找到究竟是哪里有错。

建议您拉一下最近的latest镜像，目前latest-gpu-cuda10.0-cudnn7是最新的，可以使用命令：
docker pull paddlepaddle/paddle:latest-gpu-cuda10.0-cudnn7 
或者拉一下1.5.2版本的镜像。

**Comment by fengyuentau** [comment]
我拉了1.5.0-cuda9.0-cudnn7，这个镜像只有python2.7，这次没有报找不到模型文件的错，但是有
```shell
root@fe31a5b0b0bd:~/pyramidbox# python widerface_eval.py --model_dir=models/PyramidBox_WiderFace
-----------  Configuration Arguments -----------
confs_threshold: 0.15
data_dir: data/WIDER_val/images/
file_list: data/wider_face_split/wider_face_val_bbx_gt.txt
image_path:
infer: False
model_dir: models/PyramidBox_WiderFace
pred_dir: pred
use_gpu: True
use_pyramidbox: True
------------------------------------------------
W1016 11:56:06.097822    14 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 60, Driver API Version: 10.1, Runtime API Version: 9.0
W1016 11:56:06.101693    14 device_context.cc:267] device: 0, cuDNN Version: 7.4.
Traceback (most recent call last):
  File "widerface_eval.py", line 328, in <module>
    exe, args.model_dir, main_program=infer_program)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 742, in load_persistables
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 608, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 645, in load_vars
    executor.run(load_prog)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 650, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 748, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator load error.
Python Callstacks:
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 630, in load_vars
    'file_path': os.path.join(load_dirname, new_var.name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 608, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 742, in load_persistables
    filename=filename)
  File "widerface_eval.py", line 328, in <module>
    exe, args.model_dir, main_program=infer_program)
C++ Callstacks:
Enforce failed. Expected allocating <= available, but received allocating:14920696460 > available:13418495744.
Insufficient GPU memory to allocation. at [/paddle/paddle/fluid/platform/gpu_info.cc:262]
PaddlePaddle Call Stacks:
0       0x7f23f14bfbc8p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f23f14bff17p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f23f34d7996p paddle::platform::GpuMaxChunkSize() + 630
3       0x7f23f34abc8ap
4       0x7f24deb1ea99p
5       0x7f23f34ab32dp paddle::memory::legacy::GetGPUBuddyAllocator(int) + 109
6       0x7f23f34ac175p void* paddle::memory::legacy::Alloc<paddle::platform::CUDAPlace>(paddle::platform::CUDAPlace const&, unsigned long) + 37
7       0x7f23f34ac6b5p paddle::memory::allocation::LegacyAllocator::AllocateImpl(unsigned long) + 421
8       0x7f23f34a07d5p paddle::memory::allocation::AllocatorFacade::Alloc(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 181
9       0x7f23f34a095ap paddle::memory::allocation::AllocatorFacade::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 26
10      0x7f23f30adfccp paddle::memory::AllocShared(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 44
11      0x7f23f3473204p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, paddle::framework::proto::VarType_Type, unsigned long) + 148
12      0x7f23f34768a4p paddle::framework::TensorCopy(paddle::framework::Tensor const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::platform::DeviceContext const&, paddle::framework::Tensor*) + 452
13      0x7f23f347a49bp paddle::framework::TensorFromStream(std::istream&, paddle::framework::Tensor*, paddle::platform::DeviceContext const&) + 699
14      0x7f23f30698d0p paddle::framework::DeserializeFromStream(std::istream&, paddle::framework::LoDTensor*, paddle::platform::DeviceContext const&) + 576
15      0x7f23f1f72f99p paddle::operators::LoadOpKernel<paddle::platform::CUDADeviceContext, float>::LoadLodTensor(std::istream&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::Variable*, paddle::framework::ExecutionContext const&) const + 89
16      0x7f23f1f734c0p paddle::operators::LoadOpKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 432
17      0x7f23f1f73883p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CUDADeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CUDADeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CUDADeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
18      0x7f23f341c907p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
19      0x7f23f341cce1p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
20      0x7f23f341a2dcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
21      0x7f23f164b38ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 382
22      0x7f23f164e42fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
23      0x7f23f14b0b2dp
24      0x7f23f14f25c6p
25            0x4c5326p PyEval_EvalFrameEx + 37958
26            0x4b9b66p PyEval_EvalCodeEx + 774
27            0x4c1f56p PyEval_EvalFrameEx + 24694
28            0x4b9b66p PyEval_EvalCodeEx + 774
29            0x4c17c6p PyEval_EvalFrameEx + 22758
30            0x4b9b66p PyEval_EvalCodeEx + 774
31            0x4c17c6p PyEval_EvalFrameEx + 22758
32            0x4b9b66p PyEval_EvalCodeEx + 774
33            0x4c17c6p PyEval_EvalFrameEx + 22758
34            0x4b9b66p PyEval_EvalCodeEx + 774
35            0x4c17c6p PyEval_EvalFrameEx + 22758
36            0x4b9b66p PyEval_EvalCodeEx + 774
37            0x4eb69fp
38            0x4e58f2p PyRun_FileExFlags + 130
39            0x4e41a6p PyRun_SimpleFileExFlags + 390
40            0x4938cep Py_Main + 1358
41      0x7f24de766830p __libc_start_main + 240
42            0x493299p _start + 41

```
有个memory insufficient的错误，不过pyramidbox的readme也没写显存需求。

**Comment by fengyuentau** [comment]
现在用了4块GPU才能跑起来，每块显存16GB，只有第一块占用了将近15GB的显存，其他三块才占用了361MB...但是一到图片大的就又报显存不足的错了。考虑到pyramidbox是被eccv2018接收的，是不是paddle版本导致的问题？

**Comment by fengyuentau** [comment]
受限于docker版本的问题，我这边并不能使用cuda10的镜像。

**Comment by JepsonWong** [comment]
> 现在用了4块GPU才能跑起来，每块显存16GB，只有第一块占用了将近15GB的显存，其他三块才占用了361MB...但是一到图片大的就又报显存不足的错了。考虑到pyramidbox是被eccv2018接收的，是不是paddle版本导致的问题？

这个您重新提个PR贴上如上错误吧，会有人跟进的。这个应该不是paddle版本的问题。

**Comment by fengyuentau** [comment]
非常感谢您的帮助。我明天去PaddlePaddle/models下提个issue。
