### ISSUE TITLE
fluid.io.load_inference_model加载模型时报错paddle.fluid.core_avx.EnforceNotMet: Fail to parse program_desc from binary string

### ISSUE THREAD

**Issue by moming11** [PaddlePaddle/Paddle#20817]
Paddlepaddle 1.5，CPU环境，python3.5/2.7

python环境下使用fluid.io.load_inference_model加载模型时报错：
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    params_filename='./test_model/paras')
  File "/Users/houjiayun/miniconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/io.py", line 1188, in load_inference_model
    program = Program.parse_from_string(program_desc_str)
  File "/Users/houjiayun/miniconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 3290, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
paddle.fluid.core_avx.EnforceNotMet: Fail to parse program_desc from binary string. at [/home/teamcity/work/1ec40e2d88fa641/paddle/fluid/framework/program_desc.cc:95]
PaddlePaddle Call Stacks:
0          0x12326fd7cp void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 636
1          0x12326faabp paddle::platform::EnforceNotMet::EnforceNotMet(std::exception_ptr, char const*, int) + 139
2          0x1233e4a8ap paddle::framework::ProgramDesc::ProgramDesc(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 250
3          0x123315b9cp void pybind11::cpp_function::initialize<paddle::pybind::BindProgramDesc(pybind11::module*)::$_1, void, paddle::framework::ProgramDesc&, pybind11::bytes const&, pybind11::name, pybind11::is_method, pybind11::sibling>(paddle::pybind::BindProgramDesc(pybind11::module*)::$_1&&, void (*)(paddle::framework::ProgramDesc&, pybind11::bytes const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&) + 380
4          0x123236558p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 3400
5          0x1093cbe15p PyObject_Call + 101
6          0x1093db212p instancemethod_call + 162
7          0x1093cbe15p PyObject_Call + 101
8          0x10942efefp slot_tp_init + 175
9          0x10942aea9p type_call + 313
10         0x1093cbe15p PyObject_Call + 101
11         0x109478538p PyEval_EvalFrameEx + 22088
12         0x109472c94p PyEval_EvalCodeEx + 2164
13         0x10947cfedp fast_function + 109
14         0x109478359p PyEval_EvalFrameEx + 21609
15         0x109472c94p PyEval_EvalCodeEx + 2164
16         0x10947cfedp fast_function + 109
17         0x109478359p PyEval_EvalFrameEx + 21609
18         0x109472c94p PyEval_EvalCodeEx + 2164
19         0x109472412p PyEval_EvalCode + 34
20         0x10949feedp PyRun_FileExFlags + 157
21         0x10949fa30p PyRun_SimpleFileExFlags + 816
22         0x1094b6402p Py_Main + 3506
23      0x7fff69d01015p start + 1
```

**Comment by Superjomn** [comment]
看起来是模型格式有问题，解析 protobuf 的模型拓扑出错

**Comment by moming11** [comment]
> 看起来是模型格式有问题，解析 protobuf 的模型拓扑出错

跟环境配置有关系吗？另一个同学的机器环境上可以加载成功，我自己加载总是报同样的错误

**Comment by seiriosPlus** [comment]
确认一下版本：
1. 两边机器上paddle的版本是否一致
2. 两边机器上profobuf的版本是否一致

**Comment by moming11** [comment]
> 确认一下版本：
> 
> 1. 两边机器上paddle的版本是否一致
> 2. 两边机器上profobuf的版本是否一致

统一了protobuf版本以后试了一下还是相同的错误，还有什么其它的可能原因吗？

**Comment by seiriosPlus** [comment]
__model__这个文件有多大？

**Comment by moming11** [comment]
14KB

**Comment by moming11** [comment]
我这边找到原因了，是传模型的时候有点问题，我机器上的模型缺了什么信息导致加载不上。
