### ISSUE TITLE
centos 上安装paddle报错

### ISSUE THREAD

**Issue by liutaobit** [PaddlePaddle/Paddle#20872]
版本：paddlepaddle-1.5.1-cp27-cp27mu-linux_x86_64.whl
python 版本：2.7.3

[work@yq01-ps-dumi12a29106.yq01.baidu.com script]$ fluid
Python 2.7.13 (default, Mar 29 2018, 12:34:27) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
/home/work/liutao16/paddle/paddle_release_home/python/lib/python2.7/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py:38: UserWarning: [Errno 13] Permission denied.  joblib will operate in serial mode
  warnings.warn('%s.  joblib will operate in serial mode' % (e,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/liutao16/paddle/paddle_release_home/python/lib/python2.7/site-packages/paddle/__init__.py", line 25, in <module>
    import paddle.dataset
  File "/home/work/liutao16/paddle/paddle_release_home/python/lib/python2.7/site-packages/paddle/dataset/__init__.py", line 28, in <module>
    import paddle.dataset.mq2007
  File "/home/work/liutao16/paddle/paddle_release_home/python/lib/python2.7/site-packages/paddle/dataset/mq2007.py", line 30, in <module>
    import rarfile
  File "/home/work/liutao16/paddle/paddle_release_home/python/lib/python2.7/site-packages/rarfile.py", line 2950, in <module>
    _check_unrar_tool()
  File "/home/work/liutao16/paddle/paddle_release_home/python/lib/python2.7/site-packages/rarfile.py", line 2931, in _check_unrar_tool
    custom_check([ORIG_UNRAR_TOOL], True)
  File "/home/work/liutao16/paddle/paddle_release_home/python/lib/python2.7/site-packages/rarfile.py", line 2823, in custom_check
    p = custom_popen(cmd)
  File "/home/work/liutao16/paddle/paddle_release_home/python/lib/python2.7/site-packages/rarfile.py", line 2813, in custom_popen
    creationflags=creationflags)
  File "/home/work/liutao16/paddle/paddle_release_home/python/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/work/liutao16/paddle/paddle_release_home/python/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by wzzju** [comment]
建议您使用work身份登录且使用work身份安装paddle，您遇到的应该主要是权限问题。

**Comment by guoshengCS** [comment]
这个应该已经修复了 #23426 ，可以更新下Paddle版本，或者按照这里 https://github.com/PaddlePaddle/Paddle/pull/23426/files#diff-b825a6f1c45d4e9b28f233aa48a05777 先行自行修改下本地安装包中 paddle/dataset/mq2007.py 文件
