### ISSUE TITLE
压缩模型Compressor的train_optimizer参数是否需要设置？

### ISSUE THREAD

**Issue by yanyq1990** [PaddlePaddle/Paddle#20915]
如题，在对模型进行压缩时，train_optimizer参数是否需要设置，文档提到，train program如果带反向operators和优化更新相关的operators, train_optimizer需要设置为None，不是很明白这话的意思，是指的train program设置了优化器optimizer吗？参考示例代码的，哪怕是设置了optimizer，最后Compressor的参数train_optimizer也没有设置为None，并且如果在使用中设置为None，训练过程中的loss不下降，而设置train_optimizer不为None，会报错如下：

```
Traceback (most recent call last):
  File "pruning.py", line 119, in <module>
    compress()
  File "pruning.py", line 113, in compress
    com_pass.run()
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/contrib/slim/core/compressor.py", line 517, in run
    context.train_optimizer, context.place, context.scope)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/contrib/slim/graph/graph_wrapper.py", line 417, in get_optimize_graph
    optimizer.minimize(target, no_grad_set=no_grad_var_names)
  File "</usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-20>", line 2, in minimize
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/dygraph/base.py", line 87, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/optimizer.py", line 609, in minimize
    no_grad_set=no_grad_set)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/optimizer.py", line 494, in backward
    no_grad_set, callbacks)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/backward.py", line 706, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/backward.py", line 518, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
IndexError: _Map_base::at
```

**Comment by wanghaoshuang** [comment]
如果在定义train_porgram时，调用过`optimizer.minimize(loss)`这样的语句的话，在compressor中train_optimizer必须设置为None, 否则就会加两次反向op。

>哪怕是设置了optimizer，最后Compressor的参数train_optimizer也没有设置为None，并且如果在使用中设置为None，训练过程中的loss不下降
用的是什么压缩策略，把相关脚本贴出来我们看一下？

**Comment by yanyq1990** [comment]
配置文件

```yaml
version: 1.0
pruners:
  pruner_1:
    class: 'StructurePruner'
    pruning_axis:
      '*': 0
    criterions:
      '*': 'l1_norm'
strategies:
  uniform_pruning_strategy:
    class: 'UniformPruneStrategy'
    pruner: 'pruner_1'
    start_epoch: 0
    target_ratio: 0.5
    pruned_params: '.w*'
    metric_name: 'tmp_43'
compressor:
  epoch: 200
  checkpoint_path: './checkpoints/'
  strategies:
    - uniform_pruning_strategy
```

代码

```python
def compress():
    view_l = fluid.layers.data(name='view_l', shape=[3, 384, 768], dtype='float32')
    view_r = fluid.layers.data(name='view_r', shape=[3, 384, 768], dtype='float32')
    disp_l = fluid.layers.data(name='disp_l', shape=[1, 384, 768], dtype='float32')

    model = iResNet(args.max_disp)
    preds = model(view_l, view_r)
    loss = model_loss(preds[0], preds[1], preds[2], preds[3], disp_l, args.max_disp)

    print(loss)

    val_program = fluid.default_main_program().clone()

    opt = fluid.optimizer.Momentum(
        momentum=0.9,
        learning_rate=fluid.layers.piecewise_decay(
            boundaries=[5000 * 30, 5000 * 60, 5000 * 90],
            values=[0.1, 0.01, 0.001, 0.0001]),
        regularization=fluid.regularizer.L2Decay(4e-5))

    place = fluid.CUDAPlace(0) if args.use_gpu else fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())

    if args.init_model:
        def if_exist(var):
            return os.path.exists(os.path.join(args.init_model, var.name))

        fluid.io.load_vars(exe, args.init_model, predicate=if_exist)

    train_reader = reader.train(args.data_base, args.train_list, target_h=384, target_w=768,
                                batch_size=args.batch_size, shuffle=True)
    train_feed_list = [('view_l', view_l.name), ('view_r', view_r.name), ('disp_l', disp_l.name)]
    train_fetch_list = [('loss', loss.name)]

    val_reader = reader.test(args.data_base, args.valid_list, target_h=384, target_w=768, batch_size=args.batch_size)
    val_feed_list = [('view_l', view_l.name), ('view_r', view_r.name), ('disp_l', disp_l.name)]
    val_fetch_list = [('loss', loss.name)]

    com_pass = Compressor(
        place,
        fluid.global_scope(),
        fluid.default_main_program(),
        train_reader=train_reader,
        train_feed_list=train_feed_list,
        train_fetch_list=train_fetch_list,
        eval_program=val_program,
        eval_reader=val_reader,
        eval_feed_list=val_feed_list,
        eval_fetch_list=val_fetch_list,
        train_optimizer=None)
    com_pass.config(args.compress_config)
    com_pass.run()
```

这边的虽然我没有调用`optimizer.minimize(loss)`，但是最后train_optimizer也只能设置为`None`，不然就报错,设置为None的结果如下:

```shell
2019-10-31 05:36:37,651-INFO: epoch:2; batch_id:0; ['loss'] = [4.414]
2019-10-31 05:36:40,815-INFO: epoch:2; batch_id:20; ['loss'] = [2.611]
2019-10-31 05:36:43,766-INFO: epoch:2; batch_id:40; ['loss'] = [2.041]
2019-10-31 05:36:47,034-INFO: epoch:2; batch_id:60; ['loss'] = [8.3]
2019-10-31 05:36:50,280-INFO: epoch:2; batch_id:80; ['loss'] = [2.105]
2019-10-31 05:36:53,935-INFO: epoch:2; batch_id:100; ['loss'] = [0.71]
2019-10-31 05:36:56,729-INFO: epoch:2; batch_id:120; ['loss'] = [3.327]
2019-10-31 05:36:59,908-INFO: epoch:2; batch_id:140; ['loss'] = [6.429]
2019-10-31 05:37:03,076-INFO: epoch:2; batch_id:160; ['loss'] = [3.292]
2019-10-31 05:37:06,703-INFO: epoch:2; batch_id:180; ['loss'] = [4.985]
2019-10-31 05:37:09,693-INFO: epoch:2; batch_id:200; ['loss'] = [4.261]
2019-10-31 05:37:13,156-INFO: epoch:2; batch_id:220; ['loss'] = [2.802]
2019-10-31 05:37:16,517-INFO: epoch:2; batch_id:240; ['loss'] = [1.227]
2019-10-31 05:37:20,094-INFO: epoch:2; batch_id:260; ['loss'] = [2.45]
2019-10-31 05:37:23,792-INFO: epoch:2; batch_id:280; ['loss'] = [1.366]
2019-10-31 05:37:26,553-INFO: epoch:2; batch_id:300; ['loss'] = [0.709]
2019-10-31 05:37:29,783-INFO: epoch:2; batch_id:320; ['loss'] = [2.996]
2019-10-31 05:37:32,863-INFO: epoch:2; batch_id:340; ['loss'] = [2.894]
2019-10-31 05:37:35,963-INFO: epoch:2; batch_id:360; ['loss'] = [2.536]
2019-10-31 05:37:39,496-INFO: epoch:2; batch_id:380; ['loss'] = [2.883]
2019-10-31 05:37:42,940-INFO: epoch:2; batch_id:400; ['loss'] = [0.557]
2019-10-31 05:37:46,370-INFO: epoch:2; batch_id:420; ['loss'] = [2.339]
2019-10-31 05:37:49,928-INFO: epoch:2; batch_id:440; ['loss'] = [1.544]
2019-10-31 05:37:52,643-INFO: epoch:2; batch_id:460; ['loss'] = [2.827]
2019-10-31 05:37:55,960-INFO: epoch:2; batch_id:480; ['loss'] = [4.45]
2019-10-31 05:37:59,413-INFO: epoch:2; batch_id:500; ['loss'] = [1.817]
2019-10-31 05:38:02,911-INFO: epoch:2; batch_id:520; ['loss'] = [3.629]
2019-10-31 05:38:06,037-INFO: epoch:2; batch_id:540; ['loss'] = [0.849]
2019-10-31 05:38:09,584-INFO: epoch:2; batch_id:560; ['loss'] = [4.203]
2019-10-31 05:38:12,673-INFO: epoch:2; batch_id:580; ['loss'] = [2.71]
2019-10-31 05:38:16,345-INFO: epoch:2; batch_id:600; ['loss'] = [3.03]
2019-10-31 05:38:19,494-INFO: epoch:2; batch_id:620; ['loss'] = [6.387]
2019-10-31 05:38:22,529-INFO: epoch:2; batch_id:640; ['loss'] = [4.498]
2019-10-31 05:38:25,949-INFO: epoch:2; batch_id:660; ['loss'] = [6.837]
2019-10-31 05:38:29,452-INFO: epoch:2; batch_id:680; ['loss'] = [2.754]
2019-10-31 05:38:32,610-INFO: epoch:2; batch_id:700; ['loss'] = [2.535]
2019-10-31 05:38:36,242-INFO: epoch:2; batch_id:720; ['loss'] = [3.998]
2019-10-31 05:38:39,604-INFO: epoch:2; batch_id:740; ['loss'] = [0.603]
2019-10-31 05:38:42,700-INFO: epoch:2; batch_id:760; ['loss'] = [2.681]
2019-10-31 05:38:45,957-INFO: epoch:2; batch_id:780; ['loss'] = [2.532]
2019-10-31 05:38:49,252-INFO: epoch:2; batch_id:800; ['loss'] = [2.876]
2019-10-31 05:38:52,042-INFO: epoch:2; batch_id:820; ['loss'] = [2.453]
2019-10-31 05:38:55,643-INFO: epoch:2; batch_id:840; ['loss'] = [3.508]
2019-10-31 05:38:59,422-INFO: epoch:2; batch_id:860; ['loss'] = [4.081]
2019-10-31 05:39:02,652-INFO: epoch:2; batch_id:880; ['loss'] = [1.771]
2019-10-31 05:39:06,012-INFO: epoch:2; batch_id:900; ['loss'] = [2.363]
2019-10-31 05:39:08,869-INFO: epoch:2; batch_id:920; ['loss'] = [1.145]
2019-10-31 05:39:11,968-INFO: epoch:2; batch_id:940; ['loss'] = [5.089]
2019-10-31 05:39:15,573-INFO: epoch:2; batch_id:960; ['loss'] = [2.482]
2019-10-31 05:39:18,680-INFO: epoch:2; batch_id:980; ['loss'] = [3.975]
2019-10-31 05:39:21,935-INFO: epoch:2; batch_id:1000; ['loss'] = [4.902]
2019-10-31 05:39:25,311-INFO: epoch:2; batch_id:1020; ['loss'] = [5.28]
2019-10-31 05:39:28,133-INFO: epoch:2; batch_id:1040; ['loss'] = [4.501]
2019-10-31 05:39:31,838-INFO: epoch:2; batch_id:1060; ['loss'] = [3.223]
2019-10-31 05:39:35,424-INFO: epoch:2; batch_id:1080; ['loss'] = [0.908]
2019-10-31 05:39:38,188-INFO: epoch:2; batch_id:1100; ['loss'] = [2.546]
2019-10-31 05:39:41,507-INFO: epoch:2; batch_id:1120; ['loss'] = [1.669]
2019-10-31 05:39:44,522-INFO: epoch:2; batch_id:1140; ['loss'] = [9.283]
2019-10-31 05:39:47,320-INFO: epoch:2; batch_id:1160; ['loss'] = [2.493]
```

**Comment by wanghaoshuang** [comment]
调用optimizer.minimize(loss) + train_optimizer设置为None 也不收敛么？

**Comment by wanghaoshuang** [comment]
可以先用一张图片，剪裁前后都观察下是否能拟合。

**Comment by yanyq1990** [comment]
按照`optimizer.minimize(loss) + train_optimizer设置为None`，程序报了一个错，但是能继续执行下去。
```shell
File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/contrib/slim/prune/prune_strategy.py", line 384, in _forward_pruning_ralated_params
    for ci in range(concat_idx):
UnboundLocalError: local variable 'concat_idx' referenced before assignment
```

结果不收敛
```shell
2019-11-04 01:11:33,578-INFO: epoch:1; batch_id:0; ['loss'] = [2.442]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:0; ['loss'] = [2.442]
2019-11-04 01:11:53,024-INFO: epoch:1; batch_id:20; ['loss'] = [96.174]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:20; ['loss'] = [96.174]
2019-11-04 01:12:11,547-INFO: epoch:1; batch_id:40; ['loss'] = [81.352]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:40; ['loss'] = [81.352]
2019-11-04 01:12:30,165-INFO: epoch:1; batch_id:60; ['loss'] = [86.253]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:60; ['loss'] = [86.253]
2019-11-04 01:12:48,865-INFO: epoch:1; batch_id:80; ['loss'] = [93.174]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:80; ['loss'] = [93.174]
2019-11-04 01:13:07,810-INFO: epoch:1; batch_id:100; ['loss'] = [121.978]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:100; ['loss'] = [121.978]
2019-11-04 01:13:27,772-INFO: epoch:1; batch_id:120; ['loss'] = [96.45]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:120; ['loss'] = [96.45]
2019-11-04 01:13:46,720-INFO: epoch:1; batch_id:140; ['loss'] = [97.665]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:140; ['loss'] = [97.665]
2019-11-04 01:14:05,699-INFO: epoch:1; batch_id:160; ['loss'] = [121.789]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:160; ['loss'] = [121.789]
2019-11-04 01:14:24,277-INFO: epoch:1; batch_id:180; ['loss'] = [94.519]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:180; ['loss'] = [94.519]
2019-11-04 01:14:42,896-INFO: epoch:1; batch_id:200; ['loss'] = [120.019]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:200; ['loss'] = [120.019]
2019-11-04 01:15:01,959-INFO: epoch:1; batch_id:220; ['loss'] = [111.619]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:220; ['loss'] = [111.619]
2019-11-04 01:15:20,649-INFO: epoch:1; batch_id:240; ['loss'] = [109.281]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:240; ['loss'] = [109.281]
2019-11-04 01:15:39,447-INFO: epoch:1; batch_id:260; ['loss'] = [64.643]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:260; ['loss'] = [64.643]
2019-11-04 01:15:57,721-INFO: epoch:1; batch_id:280; ['loss'] = [68.765]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:280; ['loss'] = [68.765]
2019-11-04 01:16:16,709-INFO: epoch:1; batch_id:300; ['loss'] = [144.734]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:300; ['loss'] = [144.734]
2019-11-04 01:16:35,752-INFO: epoch:1; batch_id:320; ['loss'] = [71.214]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:320; ['loss'] = [71.214]
2019-11-04 01:16:54,750-INFO: epoch:1; batch_id:340; ['loss'] = [118.13]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:340; ['loss'] = [118.13]
2019-11-04 01:17:13,245-INFO: epoch:1; batch_id:360; ['loss'] = [61.143]
INFO:paddle.fluid.contrib.slim.core.compressor:epoch:1; batch_id:360; ['loss'] = [61.143]

```
