### ISSUE TITLE
win10运行yolov3报错，急！

### ISSUE THREAD

**Issue by shengyuqing** [PaddlePaddle/Paddle#20982]
首先是我的环境配置
1）PaddlePaddle版本：paddlepaddle-gpu，1.6.0.post107
2）使用GPU进行训练，CUDA10，cuDNN,7.3
3）系统环境：WIN10

跑官网下载的yolov3目标检测算法报错，报错信息：
WARNING:root:paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
Found 2 CUDA devices.
W1103 20:15:19.473218  8236 device_context.cc:235] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W1103 20:15:19.535706  8236 device_context.cc:243] device: 0, cuDNN Version: 7.3.
loading annotations into memory...
Done (t=0.11s)
creating index...
index created!
Load in 1 categories.
C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\executor.py:774: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "train.py", line 219, in <module>
    train(cfg)
  File "train.py", line 180, in train
    fetch_list=[v.name for v in fetch_list])
  File "C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 775, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\Admin\Anaconda3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 770, in run
    use_program_cache=use_program_cache)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 819, in _run_impl
    program._compile(scope, self.place)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\compiler.py", line 392, in _compile
    places=self._places)
  File "C:\Users\Admin\Anaconda3\lib\site-packages\paddle\fluid\compiler.py", line 355, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
paddle.fluid.core_avx.EnforceNotMet: Windows not support stack backtrace yet.PaddleCheckError: Windows can support Single GPU only. at [D:\1.6.0\paddle\paddle\fluid\framework\parallel_executor.cc:417]

试了多次都不行，求助！

**Comment by gavin1332** [comment]
你是跑的单卡GPU吗？

**Comment by iEatPickles** [comment]
+1
