### ISSUE TITLE
paddle的matmul计算报错

### ISSUE THREAD

**Issue by lxwzju** [PaddlePaddle/Paddle#20992]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU/GPU：如果您使用GPU训练，请提供GPU驱动版本、CUDA和cuDNN版本号
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
    4）Python版本号
    5）显存信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please provide us with the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/cuDNN version
-OS Platform and Distribution(eg.Mac OS 10.14)
-Python version 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by lxwzju** [comment]
代码：
print(enc_output,dec_input)
product1 = layers.matmul(x=dec_input, y=enc_output, transpose_y=True)
print(product1)


运行时提示以下问题：
```
(name: "layer_norm_12.tmp_2"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 100
      dims: 512
    }
    lod_level: 0
  }
}
persistable: false
, name: "dropout_25.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 1
      dims: 512
    }
    lod_level: 0
  }
}
persistable: false
)
name: "matmul_12.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 1
      dims: 100
    }
    lod_level: 0
  }
}

finish init model from params from ../models/trained_params/step_1500000
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    do_predict(args)
  File "/home/wangxiaohui05/liuxiwei/ett_model/transformer_colon/predict.py", line 179, in do_predict
    return_numpy=False)
  File "/home/wangxiaohui05/.local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 683, in run
    use_program_cache=False)
  File "/home/wangxiaohui05/.local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 748, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator matmul error.
Python Callstacks:
  File "/home/wangxiaohui05/.local/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/wangxiaohui05/.local/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/wangxiaohui05/.local/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 5218, in matmul
    'alpha': float(alpha),
  File "/home/wangxiaohui05/liuxiwei/ett_model/transformer_colon/transformer.py", line 726, in wrap_decoder
    product1 = layers.matmul(x=dec_input, y=enc_output, transpose_y=True)
  File "/home/wangxiaohui05/liuxiwei/ett_model/transformer_colon/transformer.py", line 910, in beam_search
    is_dump_attention=is_dump_attention)
  File "/home/wangxiaohui05/liuxiwei/ett_model/transformer_colon/transformer.py", line 965, in fast_decode
    finished_ids, finished_scores, pp = beam_search()
  File "/home/wangxiaohui05/liuxiwei/ett_model/transformer_colon/transformer.py", line 1013, in create_net
    is_dump_attention=args.is_dump_attention)
  File "/home/wangxiaohui05/liuxiwei/ett_model/transformer_colon/predict.py", line 137, in do_predict
    is_training=False, model_input=input_field, args=args)
  File "main.py", line 31, in <module>
    do_predict(args)
C++ Callstacks:
 at [/paddle/paddle/fluid/operators/matmul_op.cc:295]
PaddlePaddle Call Stacks:
0       0x7f94c99566a0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f94c9956a19p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f94c9d39835p paddle::operators::MatMulOp::InferShape(paddle::framework::InferShapeContext*) const + 1845
```

**Comment by Xreki** [comment]
请问使用的Paddle版本是？另外log是否贴全了啊，这个log里面看不出具体的错误信息啊。
我猜测可能是输入的dims不满足要求。可尝试插入layers.Print来打印运行时实际Tensor的dims。Print的文档见：https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/layers_cn/Print_cn.html#print
