### ISSUE TITLE
Import `paddle.v2` failed in Docker container

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#2112]
```bash
$ docker run --rm -it paddlepaddle/paddle python -c "import paddle.v2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/__init__.py", line 36, in <module>
    import image
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 7, in <module>
    from cv2 import resize
  File "/usr/local/lib/python2.7/dist-packages/cv2/__init__.py", line 7, in <module>
    from . import cv2
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by helinwang** [comment]
this should be fixed, since we run CI with docker.
