### ISSUE TITLE
visualDL官方教程例子跑不起来

### ISSUE THREAD

**Issue by jeromeJT** [PaddlePaddle/Paddle#21282]
- 版本、环境信息：
    1）PaddlePaddle版本：1.6
    2）CPU
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.15.1
    4）Python版本号: 2.7.15
- 复现信息：
安装完毕visualDL尝试跑例子：
https://www.paddlepaddle.org.cn/documentation/docs/zh/user_guides/howto/evaluation_and_debugging/debug/visualdl_usage.html#7
直接就报错了：
visualdl --logdir ./log --host 0.0.0.0 --port 8080 --model_pb paddle_lenet_5_model

[ERROR 2019-11-21 14:57:30,267 app.py:1761] Exception on /data/runs [GET]
Traceback (most recent call last):
  File "/Users/taotao/anaconda2/anaconda2/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/taotao/anaconda2/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/taotao/anaconda2/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/taotao/anaconda2/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/taotao/anaconda2/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/taotao/anaconda2/anaconda2/bin/visualdl", line 172, in runs
    data = cache_get('/data/runs', lib.get_modes, log_reader)
  File "/Users/taotao/anaconda2/anaconda2/lib/python2.7/site-packages/visualdl/server/lib.py", line 389, in _handler
    data = func(*args, **kwargs)
  File "/Users/taotao/anaconda2/anaconda2/lib/python2.7/site-packages/visualdl/server/lib.py", line 33, in get_modes
    return storage.modes()
  File "/Users/taotao/anaconda2/anaconda2/lib/python2.7/site-packages/visualdl/python/storage.py", line 83, in modes
    return self.reader.modes()
RuntimeError: [/work/VisualDL/visualdl/utils/filesystem.h:63] 
[INFO 2019-11-21 14:57:30,314 _internal.py:88] 127.0.0.1 - - [21/Nov/2019 14:57:30] "GET /data/runs HTTP/1.1" 500 -
[WARNING 2019-11-21 14:57:30,576 lib.py:388] update cache /data/plugin/scalars/tags
[ERROR 2019-11-21 14:57:30,576 lib.py:380] Unexpected error: <type 'exceptions.RuntimeError'>
[/work/VisualDL/visualdl/utils/filesystem.h:63] 
<traceback object at 0x115f29cb0>
[WARNING 2019-11-21 14:57:30,578 lib.py:388] update cache /data/plugin/histograms/tags
[ERROR 2019-11-21 14:57:30,578 lib.py:380] Unexpected error: <type 'exceptions.RuntimeError'>
[/work/VisualDL/visualdl/utils/filesystem.h:63]

**Comment by XiaoYangWu** [comment]
您好，我也遇到了同样的问题，请问这个后来是怎么解决的呢？
