### ISSUE TITLE
 Window 10  家庭版 conda安装 测试报错

### ISSUE THREAD

**Issue by tangbozhang** [PaddlePaddle/Paddle#21386]
Python 3.7.4 paddle 1.6.1 CPUi7-8750H GPU GeForce GTX 1050TI 4G CUDA 10.0 CUDNN 7.6.4  pip 19.3.1 Window 10 家庭版
>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ...
D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py:774: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\install_check.py", line 123, in run_check
    test_simple_exe()
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\install_check.py", line 119, in test_simple_exe
    exe0.run(startup_prog)
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 775, in run
    six.reraise(*sys.exc_info())
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\six.py", line 696, in reraise
    raise value
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 770, in run
    use_program_cache=use_program_cache)
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 817, in _run_impl
    use_program_cache=use_program_cache)
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 894, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2528, in _prepend_op
    attrs=kwargs.get("attrs", None))
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\initializer.py", line 189, in __call__
    stop_gradient=True)
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2410, in create_parameter
    initializer(param, self)
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\layer_helper_base.py", line 330, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 101, in create_parameter
    default_initializer)
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\nn.py", line 1058, in _build_once
    attr=self._bias_attr, shape=size, dtype=self._dtype, is_bias=True)
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 174, in __call__
    self._build_once(*inputs, **kwargs)
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\install_check.py", line 40, in forward
    x = self._fc1(inputs)
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 178, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "D:\softwareinstall\deeplearn\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\install_check.py", line 123, in run_check
    test_simple_exe()
  File "<stdin>", line 1, in <module>

----------------------
Error Message Summary:
----------------------
PaddleCheckError: cudaGetDeviceProperties failed in paddle::platform::GetCUDAComputeCapability, error code : 30, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038: unknown error at [D:\1.6.1\paddle\paddle\fluid\platform\gpu_info.cc:84]
  [operator < fill_constant > error]

**Comment by xyoungli** [comment]
您好，请检查一下安装的fluid cuda版本和安装的驱动版本.[17009](https://github.com/PaddlePaddle/Paddle/issues/17009)

**Comment by tangbozhang** [comment]
谢谢，重新安装显卡驱动好了
