### ISSUE TITLE
安装完成后导入paddle.fluid没问题,paddle.fluid.install_check.run_check()时报错

### ISSUE THREAD

**Issue by tzl1** [PaddlePaddle/Paddle#21495]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu                   1.6.1.post97
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：RTX 2060，CUDA9.0.176和CUDNN版本号
    4）系统环境：win7、旗舰版、anaconda虚拟环境python3.6.4
- 安装方式信息：
1）pip安装：pip install paddlepaddle-gpu==1.6.1.post97 -i https://pypi.tuna.tsinghua.edu.cn/simple
2）本地编译：请提供cmake命令，编译命令
3）docker编译：请提供docker镜像，编译命令            
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

Running Verify Fluid Program ...
W1203 10:27:30.216241  8364 device_context.cc:235] Please NOTE: device: 0, CUDA
Capability: 75, Driver API Version: 10.2, Runtime API Version: 9.0
W1203 10:27:30.238242  8364 device_context.cc:243] device: 0, cuDNN Version: 7.3
.
D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py:774: UserWarning: The fo
llowing exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\install_check.py", line 123,
 in run_check
    test_simple_exe()
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\install_check.py", line 121,
 in test_simple_exe
    fetch_list=[out0.name, param_grads[1].name])
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 775, in r
un
    six.reraise(*sys.exc_info())
  File "D:\Anaconda3\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 770, in r
un
    use_program_cache=use_program_cache)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 817, in _
run_impl
    use_program_cache=use_program_cache)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 894, in _
run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 2459, in
 append_op
    attrs=kwargs.get("attrs", None))
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layer_object_helper.
py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\dygraph\nn.py", line 1103, i
n forward
    "y_num_col_dims": 1
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 178
, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\install_check.py", line 40,
in forward
    x = self._fc1(inputs)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 178
, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\install_check.py", line 113,
 in test_simple_exe
    out0 = simple_layer0(inp0)
  File "D:\Anaconda3\lib\site-packages\paddle\fluid\install_check.py", line 123,
 in run_check
    test_simple_exe()
  File "<stdin>", line 1, in <module>

----------------------
Error Message Summary:
----------------------
PaddleCheckError: CUBLAS: execution failed,  at [D:/1.6.1/paddle\paddle/fluid/op
erators/math/blas_impl.cu.h:34]
  [operator < mul > error]

**Comment by tzl1** [comment]
已解决，报错原因可能是cuda，下载cuda9.0的补丁搞定！！！[点击此处下载补丁](https://developer.nvidia.com/cuda-90-download-archive?target_os=Windows&target_arch=x86_64&target_version=7&target_type=exelocal)

**Comment by huangyunhua** [comment]
感谢各位工程师的帮助，我在新环境下试了两次都是可以运行的，真是环境问题。太感谢啦
