### ISSUE TITLE
paddle 1.6.2多卡dygraph模式backward报错

### ISSUE THREAD

**Issue by sserdoubleh** [PaddlePaddle/Paddle#21768]
paddle版本1.6.2多卡报错，单卡无异常
paddle版本1.6.1，单卡多卡都没有异常
Edit: 不仅仅是Embedding，FC也一样报错，这应该是普遍存在的
复现代码如下
多卡运行脚本
```bash
export CUDA_VISIBLE_DEVICES=0,1
python \
    -m paddle.distributed.launch \
    test_embedding_multi_gpu.py \
    --data_distribute
```

模型训练脚本
```python
import argparse
import numpy as np

import paddle.fluid as fluid
import paddle.fluid.layers as layers
import paddle.fluid.dygraph as dygraph
import paddle.fluid.dygraph.parallel as parallel


def test_embedding(data_distributed=False):
    X = np.random.randint(0, 100, [100, 10, 1])
    Y = np.random.rand(100).astype("float32")

    if data_distributed:
        place = fluid.CUDAPlace(parallel.Env().dev_id)
    else:
        place = fluid.CUDAPlace(0)
    with dygraph.guard(place):
        embedding = dygraph.Embedding("test", [100, 10])
        if data_distributed:
            strategy = parallel.prepare_context()
            embedding = parallel.DataParallel(embedding, strategy)
        optimizer = fluid.optimizer.Adam()
        for i in range(0, 100, 10):
            x = X[i:i+10]
            y = Y[i:i+10]
            x = dygraph.to_variable(x)
            y = dygraph.to_variable(y)
            embed = embedding(x)
            out = layers.reduce_sum(embed, dim=1)
            out = layers.reduce_sum(out, dim=1)
            loss = layers.mse_loss(out, y)
            print(float(loss.numpy()))
            if data_distributed:
                embedding.scale_loss(loss)
            loss.backward()
            if data_distributed:
                embedding.apply_collective_grads()
            avg_loss = layers.reduce_mean(loss)
            optimizer.minimize(avg_loss)
            embedding.clear_gradients()


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--data_distributed", action="store_true")
    args = parser.parse_args()
    test_embedding(args.data_distributed)
```

报错信息
```
--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::AdamOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OperatorWithKernel::RuntimeInferShape(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext const&) const
4   paddle::imperative::PreparedOp::Run()
5   paddle::imperative::OpBase::Run(std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared
_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std:
:string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&)
6   paddle::imperative::Tracer::TraceOp(std::string const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > >, std::less<std::string>, std::allocator<std::pair<std::string const,
 std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::map<std::string, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarB
ase> > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::vector<std::shared_ptr<paddle::imperative::VarBase>, std::allocator<std::shared_ptr<paddle::imperative::VarBase> > > > > > const&, std::unordered_map<std::string, boost::variant<boost::blan
k, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, std::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle:
:framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, bo
ost::detail::variant::void_, boost::detail::variant::void_>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, boost::variant<boost::blank, int, float, std::string, std::vector<int, std::allocator<int> >, std::vector<float, st
d::allocator<float> >, std::vector<std::string, std::allocator<std::string> >, bool, std::vector<bool, std::allocator<bool> >, paddle::framework::BlockDesc*, long, std::vector<paddle::framework::BlockDesc*, std::allocator<paddle::framework::BlockDesc*> >, std::vector<long
, std::allocator<long> >, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > >, paddle::platform::Plac
e const&, bool)

----------------------
Error Message Summary:
----------------------
Error: Param and Grad input of AdamOp should have same dimension
  [Hint: Expected param_dims == ctx->GetInputDim("Grad"), but received param_dims:100, 10 != ctx->GetInputDim("Grad"):1000.] at (/paddle/paddle/fluid/operators/optimizers/adam_op.cc:88)
```

**Comment by chenwhql** [comment]
是个bug，已经在develop中修复了，见https://github.com/PaddlePaddle/Paddle/pull/21374

但是1.6.2已经发布了，这个没有cherry-pick到1.6.2里面，可以试下develop的包

**Comment by chenwhql** [comment]
Develop whl包链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/install/Tables.html#whl-dev

**Comment by sserdoubleh** [comment]
安装paddlepaddle_gpu-latest-cp37-cp37m-linux_x86_64.whl，出现
```bash
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/work/hehuang/local/python3.7/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/home/work/hehuang/local/python3.7/lib/python3.7/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/work/hehuang/local/python3.7/lib/python3.7/site-packages/paddle/fluid/core.py", line 189, in <module>
    raise e
  File "/home/work/hehuang/local/python3.7/lib/python3.7/site-packages/paddle/fluid/core.py", line 167, in <module>
    from .core_avx import *
ImportError: dlopen: cannot load any more object with static TLS
```

**Comment by JepsonWong** [comment]
您好，麻烦提供一下您的CUDA环境、Paddle环境、GCC环境。

**Comment by sserdoubleh** [comment]
CUDA: 10.0
Paddle: dev版本
Python: 3.7.3
GCC: 4.8.2
@JepsonWong

**Comment by JepsonWong** [comment]
> CUDA: 10.0
> Paddle: dev版本
> Python: 3.7.3
> GCC: 4.8.2
> @JepsonWong

操作系统版本是什么？是否升级过系统的一些库，比如glibc等？应该安装的paddle也是cuda10版本的吧？

**Comment by sserdoubleh** [comment]
操作系统是Cent-OS 6.3
paddle版本是cuda10版本的

**Comment by sserdoubleh** [comment]
可能是python的问题，我用anaconda安装的python没有问题

**Comment by JepsonWong** [comment]
> 操作系统是Cent-OS 6.3
> paddle版本是cuda10版本的

是否对系统库如glibc库进行过升级呢？然后输出glibc版本看看

**Comment by sserdoubleh** [comment]
是这个吗？
```
strings /lib64/libc.so.6  | grep GLIB
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_PRIVATE
```

**Comment by JepsonWong** [comment]
/lib64/libc.so.6 --version 看看

**Comment by sserdoubleh** [comment]
```
/lib64/libc.so.6 --version
GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.2 20140120 (Red Hat 4.8.2-16).
Compiled on a Linux 2.6.32 system on 2014-10-22.
Available extensions:
        The C stubs add-on version 2.1.2.
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
        RT using linux kernel aio
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```

**Comment by JepsonWong** [comment]
> ```
> /lib64/libc.so.6 --version
> GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
> Copyright (C) 2012 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.
> There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
> PARTICULAR PURPOSE.
> Compiled by GNU CC version 4.8.2 20140120 (Red Hat 4.8.2-16).
> Compiled on a Linux 2.6.32 system on 2014-10-22.
> Available extensions:
>         The C stubs add-on version 2.1.2.
>         crypt add-on version 2.1 by Michael Glad and others
>         GNU Libidn by Simon Josefsson
>         Native POSIX Threads Library by Ulrich Drepper et al
>         BIND-8.2.3-T5B
>         RT using linux kernel aio
> libc ABIs: UNIQUE IFUNC
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/libc/bugs.html>.
> ```

这个问题我记录一下，我复现一下。请您关注issue的回复。如果有docker的话考虑使用预装paddle的docker环境么？里面已经安装好了develop分支的paddle。
