### ISSUE TITLE
optimizer.minimize(loss) 报错

### ISSUE THREAD

**Issue by LexiHu** [PaddlePaddle/Paddle#22252]
#optimizer.minimize(loss) 报错
模型创建成功，到优化报错optimizer.minimize(loss) 显示，某变量未初始化
#报错信息
Traceback (most recent call last):
  File "run_classifier.py", line 365, in <module>
    main(args)
  File "run_classifier.py", line 129, in main
    decr_ratio=args.decr_ratio)
  File "/home/wxy/huzijuan/ERNIE/optimization.py", line 150, in optimization
    _, param_grads = optimizer.minimize(loss)
  File "</disk1/lx/conda/envs/pd/lib/python3.7/site-packages/decorator.py:decorator-gen-36>", line 2, in minimize
  File "/disk1/lx/conda/envs/pd/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/disk1/lx/conda/envs/pd/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 78, in __impl__
    return func(*args, **kwargs)
  File "/disk1/lx/conda/envs/pd/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 678, in minimize
    no_grad_set=no_grad_set)
  File "/disk1/lx/conda/envs/pd/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 551, in backward
    no_grad_set, callbacks)
  File "/disk1/lx/conda/envs/pd/lib/python3.7/site-packages/paddle/fluid/backward.py", line 1085, in append_backward
    _append_backward_vars_(root_block, fwd_op_num, grad_to_var, grad_info_map)
  File "/disk1/lx/conda/envs/pd/lib/python3.7/site-packages/paddle/fluid/backward.py", line 891, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::Reshape2GradOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/disk1/lx/conda/envs/pd/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/disk1/lx/conda/envs/pd/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/disk1/lx/conda/envs/pd/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 9022, in reshape
    "XShape": x_shape})
  File "/home/wxy/huzijuan/ERNIE/my_classifier.py", line 47, in gather_indexes
    flat_positions = layers.reshape(positions_offseted,[-1])
  File "/home/wxy/huzijuan/ERNIE/my_classifier.py", line 164, in create_model
    ntc_outputs=gather_indexes(seq_ernie_output, pos2)
  File "run_classifier.py", line 113, in main
    ernie_config=ernie_config)
  File "run_classifier.py", line 365, in <module>
    main(args)

----------------------
Error Message Summary:
----------------------
Error: Input(Out@GRAD) shouldn't be null.
  [Hint: Expected ctx->HasInput(framework::GradVarName("Out")) == true, but received ctx->HasInput(framework::GradVarName("Out")):0 != true:1.] at (/paddle/paddle/fluid/operators/reshape_op.cc:470)
  [operator < reshape2_grad > error]

**Comment by NHZlX** [comment]
看log是运行的Ernie 模型，有自己修改过什么地方么

**Comment by LexiHu** [comment]
> 看log是运行的Ernie 模型，有自己修改过什么地方么
我使用的ernie做编码层, 在创建模型部分with fluid.program_guard(train_program, startup_prog)下面没有报错，后边到optimizer.minimize(loss)报错

```
def gather_indexes(sequence_tensor, positions):
    """Gathers the vectors at the specific positions over a minibatch."""
    #sequence_tensor: [batch,seq_len,width]
    #positions: [batch, pos_len] 2d
    sequence_shape = sequence_tensor.shape
    batch_size= sequence_shape[0] 
    seq_length = sequence_shape[1]
    width = sequence_shape[-1]
    flat_sequence_tensor = layers.reshape(sequence_tensor,[-1, width])
    flat_offsets = layers.reshape(layers.range(0, batch_size, 1, dtype='int64')*seq_length,
                                  [-1,1])#[batch,1]
    **positions_offseted=positions+flat_offsets**
    flat_positions = layers.reshape(positions_offseted,[-1])
    output_tensor = layers.gather(flat_sequence_tensor,flat_positions)
    #[batch*pos_len,width]
    output_tensor = layers.reshape(output_tensor,
                                   [batch_size,-1,width],
                                   inplace=True)
    #[batch,pos_len,width]
    return output_tensor
ernie = ErnieModel(
        src_ids=token_ids,
        position_ids=position_ids,
        sentence_ids=text_type_ids,
        task_ids=task_ids,
        input_mask=input_mask,
        config=ernie_config,
        use_fp16=args.use_fp16)   
    seq_ernie_output=ernie.get_sequence_output()
    seq_ernie_output = fluid.layers.dropout(
        x=seq_ernie_output,
        dropout_prob=0.1,
        dropout_implementation="upscale_in_train")
    hidden_size=seq_ernie_output.shape[-1]
    MASK_outputs=gather_indexes(seq_ernie_output, pos1)
    #[B,mask_len,H]
    ntc_outputs=gather_indexes(seq_ernie_output, pos2)
    #[B,ntc_len,H]
#     print(seq_ernie_output.shape,MASK_outputs.shape,ntc_outputs.shape)
    '''quary: MASK_outputs,pos1_mask   
       key:   ntc_outputs,pos2_mask'''
    start_probs,end_probs=get_start_end_probs(MASK_outputs,pos1_mask,
                         ntc_outputs,pos2_mask,
                         hidden_size,
                         n_head=2)


```

**Comment by NHZlX** [comment]
可以把复现代码发我下么

**Comment by zzs95** [comment]
你好解决了么
