### ISSUE TITLE
Inference 加载模型报错：because it is missing required fields

### ISSUE THREAD

**Issue by AoZhang** [PaddlePaddle/Paddle#22416]
- 环境
   1）PaddlePaddle版本：1.6.2
   2）CPU：Intel(R) Xeon(R) CPU E5-2620 v2
   3）GPU：no
   4）系统环境：CentOS 6.3 ，Python版本 3.6.5

- 问题描述
看报错信息像是save model时漏了数据，但是看不出来缺少的什么，“cannot determine missing fields for lite message”。review过代码，所有训练阶段read的变量都在 save_inference_model 阶段保存（feeded_var_names）了，请问这种情况下如何排查问题？

详细错误日志如下：
```
[libprotobuf ERROR /paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/message_lite.cc:119] 
Can't parse message of type "paddle.framework.proto.ProgramDesc"
 because it is missing required fields:
 (cannot determine missing fields for lite message)
Traceback (most recent call last):
  File "script/text2sql_infer.py", line 67, in <module>
    predictor = Predictor(param_dict["predictor"], dataset, model)
  File "/xx/paddle_env/text2sql/textone/predict/predictor.py", line 30, in __init__
    self.init_env()
  File "/xxx/paddle_env/text2sql/textone/predict/predictor.py", line 43, in init_env
    self.predictor = create_paddle_predictor(config.to_native_config())
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::framework::ProgramDesc::ProgramDesc(std::string const&)
3   paddle::inference::Load(paddle::framework::Executor*, paddle::framework::Scope*, std::string const&, std::string const&)
4   paddle::NativePaddlePredictor::Init(std::shared_ptr<paddle::framework::Scope>)
5   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::NativeConfig, (paddle::PaddleEngineKind)0>(paddle::NativeConfig const&)
6   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::NativeConfig>(paddle::NativeConfig const&)

----------------------
Error Message Summary:
----------------------
Error: Fail to parse program_desc from binary string. at (/paddle/paddle/fluid/framework/program_desc.cc:103)
```

**Comment by jiweibo** [comment]
请问下能否提供下模型和参数文件，我先复现一下

**Comment by AoZhang** [comment]
> 请问下能否提供下模型和参数文件，我先复现一下

如下压缩包包括 model 和 params，这些是否ok？
[model.tar.gz](https://github.com/PaddlePaddle/Paddle/files/4147138/model.tar.gz)

**Comment by jiweibo** [comment]
> > 请问下能否提供下模型和参数文件，我先复现一下
> 
> 如下压缩包包括 model 和 params，这些是否ok？
> [model.tar.gz](https://github.com/PaddlePaddle/Paddle/files/4147138/model.tar.gz)

model的格式不对吧，我都不能直接可视化，可以先参考下官网保存模型部分代码修改下

**Comment by AoZhang** [comment]
> > > 请问下能否提供下模型和参数文件，我先复现一下
> > 
> > 
> > 如下压缩包包括 model 和 params，这些是否ok？
> > [model.tar.gz](https://github.com/PaddlePaddle/Paddle/files/4147138/model.tar.gz)
> 
> model的格式不对吧，我都不能直接可视化，可以先参考下官网保存模型部分代码修改下

这是我的代码，有啥问题？

```
fluid.io.save_inference_model(
    save_path,
    feeded_var_names,
    target_vars,
    exe,
    main_program=program,
    model_filename="model",
    params_filename="params")

```
我的模型train和inference代码不同，代码中的 target_vars 是 Inference 阶段最终结果的list（1个元素），program 是Inference 的 program。

**Comment by jiweibo** [comment]
> > > > 请问下能否提供下模型和参数文件，我先复现一下
> > > 
> > > 
> > > 如下压缩包包括 model 和 params，这些是否ok？
> > > [model.tar.gz](https://github.com/PaddlePaddle/Paddle/files/4147138/model.tar.gz)
> > 
> > 
> > model的格式不对吧，我都不能直接可视化，可以先参考下官网保存模型部分代码修改下
> 
> 这是我的代码，有啥问题？
> 
> ```
> fluid.io.save_inference_model(
>     save_path,
>     feeded_var_names,
>     target_vars,
>     exe,
>     main_program=program,
>     model_filename="model",
>     params_filename="params")
> ```
> 
> 我的模型train和inference代码不同，代码中的 target_vars 是 Inference 阶段最终结果的list（1个元素），program 是Inference 的 program。

可以用netron可视化文件，如果能正常可视化，才是正确的模型结构，你这里的模型查看不了。

此外，program经过save_inference_model之后才会得到预测的program，之前应该是训练后得到的program。

save_infernce_model参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#cn-api-fluid-io-save-inference-model

**Comment by AoZhang** [comment]
> 可以用netron可视化文件，如果能正常可视化，才是正确的模型结构

用 netron 查看只报了 `Error loading PaddlePaddle model. File format is not paddle.ProgramDesc (missing required 'data_type') in '__model__'.`
如何知道是哪里缺少了 data_type 呢？

**Comment by jiweibo** [comment]
> > 可以用netron可视化文件，如果能正常可视化，才是正确的模型结构
> 
> 用 netron 查看只报了 `Error loading PaddlePaddle model. File format is not paddle.ProgramDesc (missing required 'data_type') in '__model__'.`
> 如何知道是哪里缺少了 data_type 呢？

是用到了scatter_nd吗？把模型文件转为txt后发现scatted_nd没有dtype，人工加上dtype可视化发现好像没有用到scatter_nd op. 请确认下。
[model.txt](https://github.com/PaddlePaddle/Paddle/files/4151332/model.txt)

**Comment by AoZhang** [comment]
> > > 可以用netron可视化文件，如果能正常可视化，才是正确的模型结构
> > 
> > 
> > 用 netron 查看只报了 `Error loading PaddlePaddle model. File format is not paddle.ProgramDesc (missing required 'data_type') in '__model__'.`
> > 如何知道是哪里缺少了 data_type 呢？
> 
> 是用到了scatter_nd吗？把模型文件转为txt后发现scatted_nd没有dtype，人工加上dtype可视化发现好像没有用到scatter_nd op. 请确认下。
> [model.txt](https://github.com/PaddlePaddle/Paddle/files/4151332/model.txt)

用到 scatter_nd_add 了。
另外问下，模型文件如何转为明文txt的？

**Comment by jiweibo** [comment]
> > > > 可以用netron可视化文件，如果能正常可视化，才是正确的模型结构
> > > 
> > > 
> > > 用 netron 查看只报了 `Error loading PaddlePaddle model. File format is not paddle.ProgramDesc (missing required 'data_type') in '__model__'.`
> > > 如何知道是哪里缺少了 data_type 呢？
> > 
> > 
> > 是用到了scatter_nd吗？把模型文件转为txt后发现scatted_nd没有dtype，人工加上dtype可视化发现好像没有用到scatter_nd op. 请确认下。
> > [model.txt](https://github.com/PaddlePaddle/Paddle/files/4151332/model.txt)
> 
> 用到 scatter_nd_add 了。
> 另外问下，模型文件如何转为明文txt的？

步骤比较麻烦，如果是厂内用户可以hi我，Hi账号 JiWilber

**Comment by jiweibo** [comment]
已验证是scatter_nd_add的bug，关联issue https://github.com/PaddlePaddle/Paddle/issues/22000 已修复。

**Comment by qinhuangdaoStation** [comment]
> > > > > 请问下能否提供下模型和参数文件，我先复现一下
> > > > 
> > > > 
> > > > 如下压缩包包括 model 和 params，这些是否ok？
> > > > [model.tar.gz](https://github.com/PaddlePaddle/Paddle/files/4147138/model.tar.gz)
> > > 
> > > 
> > > model的格式不对吧，我都不能直接可视化，可以先参考下官网保存模型部分代码修改下
> > 
> > 
> > 这是我的代码，有啥问题？
> > ```
> > fluid.io.save_inference_model(
> >     save_path,
> >     feeded_var_names,
> >     target_vars,
> >     exe,
> >     main_program=program,
> >     model_filename="model",
> >     params_filename="params")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我的模型train和inference代码不同，代码中的 target_vars 是 Inference 阶段最终结果的list（1个元素），program 是Inference 的 program。
> 
> 可以用netron可视化文件，如果能正常可视化，才是正确的模型结构，你这里的模型查看不了。
> 
> 此外，program经过save_inference_model之后才会得到预测的program，之前应该是训练后得到的program。
> 
> save_infernce_model参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/io_cn/save_inference_model_cn.html#cn-api-fluid-io-save-inference-model

我这边使用netron可以正常可视化，但是还是报了类似上面的错误，请问是什么原因？要怎么解决呀？错误如下：

2024-08-06T09:17:59.747797530Z [libprotobuf ERROR /paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.framework.proto.ProgramDesc" because it is missing required fields: blocks[1].ops[16].attrs[13].type
2024-08-06T09:17:59.753752488Z [libprotobuf ERROR /paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.framework.proto.ProgramDesc" because it is missing required fields: blocks[1].ops[16].attrs[13].type
2024-08-06T09:17:59.757954750Z [2024-08-06 17:17:59 +0800] [17]: [ERROR] Exception in worker process
2024-08-06T09:17:59.757970633Z Traceback (most recent call last):
2024-08-06T09:17:59.757973948Z   File "/opt/huawei/miniconda/envs/python36/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2024-08-06T09:17:59.757977633Z     worker.init_process()
2024-08-06T09:17:59.757980358Z   File "/opt/huawei/miniconda/envs/python36/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 203, in init_process
2024-08-06T09:17:59.757983440Z     super(GeventWorker, self).init_process()
2024-08-06T09:17:59.757986138Z   File "/opt/huawei/miniconda/envs/python36/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
2024-08-06T09:17:59.757989005Z     self.load_wsgi()
2024-08-06T09:17:59.757991734Z   File "/opt/huawei/miniconda/envs/python36/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2024-08-06T09:17:59.757994576Z     self.wsgi = self.app.wsgi()
2024-08-06T09:17:59.758005712Z   File "/opt/huawei/miniconda/envs/python36/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-08-06T09:17:59.758008629Z     self.callable = self.load()
2024-08-06T09:17:59.758011237Z   File "/opt/huawei/miniconda/envs/python36/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
2024-08-06T09:17:59.758014039Z     return self.load_wsgiapp()
2024-08-06T09:17:59.758016690Z   File "/opt/huawei/miniconda/envs/python36/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2024-08-06T09:17:59.758019528Z     return util.import_app(self.app_uri)
2024-08-06T09:17:59.758022283Z   File "/opt/huawei/miniconda/envs/python36/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
2024-08-06T09:17:59.758025080Z     __import__(module)
2024-08-06T09:17:59.758027706Z   File "/opt/huawei/framework/service/appcontainer/app.py", line 39, in <module>
2024-08-06T09:17:59.758030834Z     process = customer_class()
2024-08-06T09:17:59.758033388Z   File "/model-data/component/process.py", line 25, in __init__
2024-08-06T09:17:59.758036135Z     self.app_intention_model = APPIntention(model_dir)
2024-08-06T09:17:59.758038863Z   File "/model-data/component/app_intention/app_intention.py", line 40, in __init__
2024-08-06T09:17:59.758041677Z     self.intent_service = AppIntentionModel(model_root_dir)
2024-08-06T09:17:59.758044324Z   File "/model-data/component/app_intention/app_intention_model.py", line 18, in __init__
2024-08-06T09:17:59.758047057Z     self.intention_model = IntentionModel(intention_model_dir)
2024-08-06T09:17:59.758049766Z   File "/model-data/component/intention_model/intention_model.py", line 21, in __init__
2024-08-06T09:17:59.758052482Z     self._construct_model()
2024-08-06T09:17:59.758055483Z   File "/model-data/component/intention_model/intention_model.py", line 47, in _construct_model
2024-08-06T09:17:59.758058298Z     self.predictor = paddle.inference.create_predictor(_config)
2024-08-06T09:17:59.758060958Z ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
2024-08-06T09:17:59.758063706Z   [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:103)
