### ISSUE TITLE
fluid.backward.append_backward出错If not, please set stop_gradient to True for its input and output variables using var.stop_gradient=True

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#22592]
可以直接在本地跑并且复现错误的代码：
```
import math
import numpy as np
import paddle
import paddle.fluid as fluid
import sys
import unittest

def kl_divergence(q_logits, p_logits, regression=False):
    if regression:
        q = fluid.layers.sigmoid(q_logits)
        kl = (fluid.layers.sigmoid_cross_entropy_with_logits(x=p_logits, label=q) \
            - fluid.layers.sigmoid_cross_entropy_with_logits(x=q_logits, label=q))
    else:
        q = fluid.layers.softmax(q_logits)
        p = fluid.layers.softmax(p_logits)
        kl = fluid.layers.reduce_sum(q * (fluid.layers.log(q) - fluid.layers.log(p)), -1)

    loss = fluid.layers.mean(x=kl)
    return loss


def scale_l2(x, norm_length):   
    alpha = fluid.layers.reduce_max(fluid.layers.abs(x), dim=1, keep_dim=True) + 1e-12
    l2_norm = alpha * fluid.layers.sqrt(
            fluid.layers.reduce_sum(fluid.layers.pow(x / alpha, factor=2), dim=1, keep_dim=True) + 1e-6) + 1e-12
    x_unit = x / l2_norm
    return norm_length * x_unit


def vatm(logits, 
         embedded, 
         logits_from_embedding_fn, 
         k_iteration=8, 
         small_constant_for_finite_diff=1e-5, 
         return_emb=False):

    program = fluid.default_main_program()

    d = fluid.layers.gaussian_random(embedded.shape)
    
    for _ in range(k_iteration):
        d = scale_l2(d, small_constant_for_finite_diff)
        d_logtis = logits_from_embedding_fn(embedded + d)
        kl = kl_divergence(logits, d_logtis)
        param_grads = fluid.backward.append_backward(kl, parameter_list=[d.name])
        
        gradient = list(filter(lambda p: p[0].name == d.name, param_grads))[0][1]
        gradient.stop_gradient = True
        d = gradient

    d = scale_l2(d, small_constant_for_finite_diff)
    d_logtis = logits_from_embedding_fn(embedded + d)
    kl = kl_divergence(logits, d_logtis)

    if return_emb == False:
        return kl
    else:
        return kl, embedded + d
    

def exe_run(mp, sp, feed, fetch_list):
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(sp)
    return exe.run(mp, 
            feed=feed,
            fetch_list=fetch_list)


class DummyTextModel(object):
    def __init__(self, nb_classes=10):
        self.ids = fluid.layers.data(name='ids', shape=[1], dtype='int64')
        self.emb = fluid.layers.embedding(
            input=self.ids,
            size=[10, 3],
            dtype="float32")
    
    def forward(self):
        mp, sp = fluid.Program(), fluid.Program()
        return self.forward_from_embedding(self.emb)

    def forward_from_embedding(self, emb):
        net = paddle.fluid.layers.reduce_mean(emb, dim=1)
        net = paddle.fluid.layers.flatten(net)
        net = paddle.fluid.layers.fc(net, 60)
        logits = paddle.fluid.layers.fc(net, 10)
        return paddle.fluid.layers.softmax(logits)
    
    
mp, sp = fluid.Program(), fluid.Program()

with fluid.program_guard(mp, sp):
    text_model = DummyTextModel()
    logits = text_model.forward()

    logits_from_embedding_fn = text_model.forward_from_embedding

    _, emb = vatm(logits,
                          text_model.emb,
                          logits_from_embedding_fn,
                          k_iteration=8, 
                          small_constant_for_finite_diff=1e-5, 
                          return_emb=True)


exe_run(mp, sp, feed={'ids':[[[1], [3]]]}, fetch_list=[])
```

**Comment by OleNet** [comment]
错误：
```
EnforceNotMet                             Traceback (most recent call last)
<ipython-input-7-3e5a93e41605> in <module>
    101                           k_iteration=8,
    102                           small_constant_for_finite_diff=1e-5,
--> 103                           return_emb=True)
    104 
    105 

<ipython-input-7-3e5a93e41605> in vatm(logits, embedded, logits_from_embedding_fn, k_iteration, small_constant_for_finite_diff, return_emb)
     43         d_logtis = logits_from_embedding_fn(embedded + d)
     44         kl = kl_divergence(logits, d_logtis)
---> 45         param_grads = fluid.backward.append_backward(kl, parameter_list=[d.name])
     46 
     47         gradient = list(filter(lambda p: p[0].name == d.name, param_grads))[0][1]

~/anaconda3/lib/python3.7/site-packages/paddle/fluid/backward.py in append_backward(loss, parameter_list, no_grad_set, callbacks, checkpoints)
   1076             grad_to_var,
   1077             callbacks,
-> 1078             input_grad_names_set=input_grad_names_set)
   1079 
   1080     # Because calc_gradient may be called multiple times,

~/anaconda3/lib/python3.7/site-packages/paddle/fluid/backward.py in _append_backward_ops_(block, ops, target_block, no_grad_dict, grad_to_var, callbacks, input_grad_names_set)
    796         # Getting op's corresponding grad_op
    797         grad_op_desc, op_grad_to_var = core.get_grad_op_desc(
--> 798             op.desc, cpt.to_text(no_grad_dict[block.idx]), grad_sub_block_list)
    799 
    800         # If input_grad_names_set is not None, extend grad_op_descs only when

EnforceNotMet: 0   std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > paddle::platform::GetTraceBackString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&&&, char const*, int)
1   paddle::framework::OpInfo::GradOpMaker() const
2   void pybind11::cpp_function::initialize<paddle::pybind::pybind11_init_core_avx(pybind11::module&)::$_64, std::__1::pair<std::__1::vector<paddle::framework::OpDesc*, std::__1::allocator<paddle::framework::OpDesc*> >, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > >, paddle::framework::OpDesc const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> > const&, pybind11::name, pybind11::scope, pybind11::sibling>(paddle::pybind::pybind11_init_core_avx(pybind11::module&)::$_64&&, std::__1::pair<std::__1::vector<paddle::framework::OpDesc*, std::__1::allocator<paddle::framework::OpDesc*> >, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > (*)(paddle::framework::OpDesc const&, std::__1::unordered_set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::vector<paddle::framework::BlockDesc*, std::__1::allocator<paddle::framework::BlockDesc*> > const&), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&)
3   pybind11::cpp_function::dispatcher(_object*, _object*, _object*)
PaddleCheckError: grad_op_maker_ should not be null
Operator unknown's GradOpMaker has not been registered.
Please check whether unknown_op has grad_op.
If not, please set stop_gradient to True for its input and output variables using var.stop_gradient=True. at [/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/framework/op_info.h:77]

```

**Comment by OleNet** [comment]
tensorflow 的 cleverhans 包就能跑的通：
https://github.com/tensorflow/cleverhans/blob/master/cleverhans/attacks/virtual_adversarial_method.py#L139

**Comment by zhupengyang** [comment]
我跑了下，显示
```
Traceback (most recent call last):
  File "test.py", line 103, in <module>
    return_emb=True)
  File "test.py", line 58, in vatm
    return kl, emb_hat
NameError: global name 'emb_hat' is not defined
```
看上去是```emb_hat```定义在后面，所以有问题

**Comment by OleNet** [comment]
这个问题fix了，可以复现了。
你再复现一下。
我的问题的本质是一个 op 不能在反向中被获得

**Comment by zhupengyang** [comment]
新的结果是
```
Traceback (most recent call last):
  File "test.py", line 106, in <module>
    emb_hat = exe_run(mp, sp, feed={text_model.ids:[[[1], [3]]]}, fetch_list=[emb])
  File "test.py", line 67, in exe_run
    fetch_list=fetch_list)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 900, in _run_program
    fetch_var_name=fetch_var_name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 549, in _add_feed_fetch_ops
    out = global_block.var(name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 2280, in var
    (type(name)))
TypeError: var require string as parameter, but get <class 'paddle.fluid.framework.Variable'> instead.
```
还是和你的不一样。。

看上去是```emb_hat = exe_run(mp, sp, feed={text_model.ids:[[[1], [3]]]}, fetch_list=[emb])```里面```emb```不是字符串

**Comment by OleNet** [comment]
我的python是2.7
paddle是1.6.0

**Comment by BladeSun** [comment]
> 这个问题fix了，可以复现了。
> 你再复现一下。
> 我的问题的本质是一个 op 不能在反向中被获得

请问这个问题具体是如何fix的呢？那个不能在反向中被获得的OP是如何找到的？
