### ISSUE TITLE
fluid.layers.gaussian_random(shape=shape)出错：ValueError: vector::reserve

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#22687]
运行如下代码的时候，程序会报错：
```
shape = paddle.fluid.layers.shape(embedded)
d = fluid.layers.gaussian_random(shape=shape)
```

```
Device count: 8
Num train examples: 50
Max train steps: 3
Num warmup steps: 0
2020-02-20 00:43:16,463-WARNING: paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
I0220 00:43:16.463838 71266 pybind.cc:967] init_lod_tensor_blocking_queue
Traceback (most recent call last):
  File "run_classifier.py", line 525, in <module>
    main(args)
  File "run_classifier.py", line 146, in main
    adv=args.adv)
  File "/ssd1//workfiles/representation_learning/ernie/ernie.albert.icode/baidu/nlp-ernie/ernie/ERNIE/finetune/classifier.py", line 198, in create_model
    return_d=True)
  File "./attacktext/attacktext/adv_vat.py", line 47, in vatm
    d = fluid.layers.gaussian_random(shape=shape)
  File "/ssd1//workfiles/representation_learning/ernie/ernie.albert.icode/baidu/nlp-ernie/ernie/ERNIE/package/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 9621, in gaussian_random
    'use_mkldnn': False
  File "/ssd1//workfiles/representation_learning/ernie/ernie.albert.icode/baidu/nlp-ernie/ernie/ERNIE/package/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/ssd1//workfiles/representation_learning/ernie/ernie.albert.icode/baidu/nlp-ernie/ernie/ERNIE/package/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2528, in append_op
    attrs=kwargs.get("attrs", None))
  File "/ssd1//workfiles/representation_learning/ernie/ernie.albert.icode/baidu/nlp-ernie/ernie/ERNIE/package/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 1878, in __init__
    self._update_desc_attr(attr_name, attr_val)
  File "/ssd1//workfiles/representation_learning/ernie/ernie.albert.icode/baidu/nlp-ernie/ernie/ERNIE/package/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2053, in _update_desc_attr
    self.desc._set_attr(name, val)
ValueError: vector::reserve
```

**Comment by OleNet** [comment]
```
def vatm(logits,
         embedded,
         logits_from_embedding_fn,
         k_iteration=8,
         perturb_norm_length=2.0,
         small_constant_for_finite_diff=1e-5,
         return_d=False):

    """ refer code from
    https://github.com/tensorflow/models/blob/master/research/adversarial_text/adversarial_losses.py#L145
    but we didn't use the vat loss for now
    """

    shape = paddle.fluid.layers.shape(embedded)
    d = fluid.layers.gaussian_random(shape=shape)
    #d = fluid.layers.gaussian_random_batch_size_like(embedded, shape=shape)

    for _ in range(k_iteration):
        d = scale_l2(d, small_constant_for_finite_diff)
        #import pdb
        #pdb.set_trace()
        emb_hat = embedded + d
        fluid.layers.Print(d)
        d_logtis = logits_from_embedding_fn(emb_hat)
        kl = kl_divergence(logits, d_logtis)
        param_grads = fluid.backward.append_backward(kl, parameter_list=[d.name])
        gradient = filter(lambda p: p[0].name == d.name, param_grads)[0][1]
        gradient.stop_gradient = True
        d = gradient

    d = scale_l2(d, perturb_norm_length)
    d_logtis = logits_from_embedding_fn(embedded + d)

    if return_d == False:
        return d_logtis
    else:
        return d_logtis, d

```

**Comment by gfwm2013** [comment]
@OleNet layers.shape返回是个Variable(Tensor)，但是layers.gaussian_random中shape要求是tuple或list，所以你这样直接使用会报错。
<img width="475" alt="a3596788d0611f52a8fb9673edc6c8d4" src="https://user-images.githubusercontent.com/52460041/75001954-db0ecb80-549d-11ea-9079-644dca40687f.png">
<img width="436" alt="9be0f6a11ab8bd5a1edfabd61be0d1b7" src="https://user-images.githubusercontent.com/52460041/75001966-e235d980-549d-11ea-9a2e-334576cc9c6a.png">
