### ISSUE TITLE
memory_usage_calc.py报错

### ISSUE THREAD

**Issue by yellmi** [PaddlePaddle/Paddle#22694]
- 版本、环境信息：
    1）PaddlePaddle版本：1.5.0
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，cudnn_v7.3， cuda 9.0， GPU v100
    4）系统环境：python 3.5.3
- 训练信息
    1）单机  单卡
    2）显存信息：32G
    3）Operator信息
在ernie v2版的基础上修改了classify模型
Traceback (most recent call last):
  File "./src/run_classifier.py", line 411, in <module>
    main(args)
  File "./src/run_classifier.py", line 135, in main
    program=train_program, batch_size=args.batch_size)
  File "xxxx/env/python3/lib/python3.5/site-packages/paddle/fluid/contrib/memory_usage_calc.py", line 95, in memory_usage
    % (var_name))
ValueError: Var matmul_0.tmp_0 has more than one negtive dim.

**Comment by DannyIsFunny** [comment]
看报错信息是某个op设置了一个以上的-1维度，但是不支持这种操作。

**Comment by DannyIsFunny** [comment]
请问有更全的报错log吗

**Comment by DannyIsFunny** [comment]
因为`memory_usage_calc.py`这个函数不支持两个维度都是-1，所以报错（可以将这个调用给去除）
