### ISSUE TITLE
PaddleSilm安装失败

### ISSUE THREAD

**Issue by CheungBH** [PaddlePaddle/Paddle#22704]
您好，我按照
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.3/beginners_guide/install/install_Ubuntu.html
的方法进行PaddleSilm的安装，发现会有ImportError。我的paddlepaddle版本是1.6.3

报错信息如下
root@hkuit164-GX501VIK:/opt/PaddleSlim# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    from paddleslim.version import slim_version
  File "/opt/PaddleSlim/paddleslim/__init__.py", line 21, in <module>
    from paddleslim import quant
  File "/opt/PaddleSlim/paddleslim/quant/__init__.py", line 15, in <module>
    from .quanter import quant_aware, quant_post, convert
  File "/opt/PaddleSlim/paddleslim/quant/quanter.py", line 25, in <module>
    from paddle.fluid.contrib.slim.quantization import PostTrainingQuantization
ImportError: cannot import name PostTrainingQuantization

版本信息如下
root@hkuit164-GX501VIK:/opt/PaddleSlim# paddle --version
/usr/local/bin/paddle: line 23: printf: post107: invalid number
: invalid numberaddle: line 23: printf: <html>
PaddlePaddle 1.6.3.post107, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON
root@hkuit164-GX501VIK:/opt/PaddleSlim# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    from paddleslim.version import slim_version
  File "/opt/PaddleSlim/paddleslim/__init__.py", line 21, in <module>
    from paddleslim import quant
  File "/opt/PaddleSlim/paddleslim/quant/__init__.py", line 15, in <module>
    from .quanter import quant_aware, quant_post, convert
  File "/opt/PaddleSlim/paddleslim/quant/quanter.py", line 25, in <module>
    from paddle.fluid.contrib.slim.quantization import PostTrainingQuantization
ImportError: cannot import name PostTrainingQuantization
root@hkuit164-GX501VIK:/opt/PaddleSlim#

**Comment by wanghaoshuang** [comment]
您好，PaddleSlim develop和PaddleSlim release1.0.0（未正式发布）分支都依赖paddlepaddle1.7（近日会发布安装包）。

在paddle1.6环境下，您可以执行以下命令安装PaddleSlim_v0.1.0:
```
pip install paddleslim==0.1.0 -i https://pypi.org/simple
```

PaddleSlim_v0.1.0去掉了对paddle1.7的依赖，除了离线量化功能，其它功能都可正常使用。

**Comment by wanghaoshuang** [comment]
如有使用问题，请提issue到：https://github.com/PaddlePaddle/PaddleSlim/issues
