### ISSUE TITLE
aistudio 训练后模型落地到本地机器报错：Shape not matching

### ISSUE THREAD

**Issue by lijingwei** [PaddlePaddle/Paddle#22783]
- 标题：“aistudio 训练后模型落地到本地机器报错：Shape not matching”
- ai studio 训练与预测 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle 1.4.1 
    2）Python：3.7
    3）GPU：v100 16G、CUDA 9.0 和CUDNN 7.0
ai studio 训练和预测都没有问题。

- 本机 训练与预测 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle 1.7.0 
    2）Python：3.7
    3）GPU：RTX 1070 TI 8G、CUDA 9.0 和CUDNN 7.6
图片等数据集、模型文件都是下载的ai studio

- 问题描述：
fork https://aistudio.baidu.com/aistudio/projectdetail/72574 这个项目。然后在ai studio训练了自己的数据集。并在aistudio成功测试。然后将数据集、训练后的模型文件下载到本地机器预测。也是和ai studio一样的代码。结果本地错误：
_Traceback (most recent call last):
  File "word.py", line 297, in <module>
    fluid.io.load_persistables(exe, save_freeze_dir, inference_program)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\paddle\fluid\io.py", line 917, in load_persistables
    filename=filename)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\paddle\fluid\io.py", line 742, in load_vars
    filename=filename)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\paddle\fluid\io.py", line 809, in load_vars
    format(orig_shape, each_var.name, new_shape))
**RuntimeError: Shape not matching:** the Program requires a parameter with a shape of ((38, 128)), while the loaded parameter (namely [ embedding_0.w_0 ]) has a shape of  ((65, 128)).
W0227 16:27:51.502305 11912 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 9.0
W0227 16:27:51.509286 11912 device_context.cc:245] device: 0, cuDNN Version: 7.6._

**Comment by JepsonWong** [comment]
看起来是导入参数和模型需要的参数shape不一致导致的，要不然输出模型embedding参数shape看看？
