### ISSUE TITLE
paddle 1.7-CPU版本 windows python3.6.6 安装后 import 出错

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/Paddle#22797]
paddle 1.7-CPU版本 windows python3.6.6 安装后 import 出错。使用的是 thinkpad，64位机器。采用 pip 命令安装。MKL数学库不确定是否有使用。pip安装提示安装成功，但是在使用的时候报错。错误提示说加载不到 DLL 动态链接库

Traceback (most recent call last):
  File "D:/python-code/paddle-1.7.0/src/network.py", line 1, in <module>
    import paddle.fluid as fluid
  File "D:\python\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "D:\python\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "D:\python\lib\site-packages\paddle\fluid\core.py", line 194, in <module>
    raise e
  File "D:\python\lib\site-packages\paddle\fluid\core.py", line 167, in <module>
    from .core_avx import *
ImportError: DLL load failed: 找不到指定的程序。

一开始我在虚拟环境中安装，也是报这个错误。然后我切换出来安装，依然这个错误。

**Comment by zhangting2020** [comment]
请参考下 #22732 这个issue

**Comment by xiangyubo** [comment]
我还要再反馈一下，就是我机器的环境，安装1.6.3非常顺利。但是切换到1.7，怎么都不能用。我甚至卸载了我的 python 环境安装都不行，都是在 import paddle.fluid 的时候报错

**Comment by zhwesky2010** [comment]
@xiangyubo 排查了Windows相关环境配置、环境变量、各种依赖。且用户1.6.3的paddle可用，1.7.0的paddle不可用，最终排查到mkldnn，初步判断用户机器对mkldnn的支持问题，1.7.0的mkldnn升级可能触发了这个问题。目前先通过1.7.0的openblas版本的paddle来解决需求，用户后面可以通过源码编译 cmake来检测机器是否支持mkl。

**Comment by xiangyubo** [comment]
> @xiangyubo 排查了Windows相关环境配置、环境变量、各种依赖。且用户1.6.3的paddle可用，1.7.0的paddle不可用，最终排查到mkldnn，初步认为1.7.0对mkldnn的升级可能是有影响的。目前先通过1.7.0的openblas版本的paddle来解决需求，用户后面可以通过源码编译 cmake来检测机器是否支持mkl。

感谢威神的协助，目前能跑了
