### ISSUE TITLE
生成任务多卡运行时fetch报错：exe.run(fetch_var_names)._move_to_list()

### ISSUE THREAD

**Issue by zhengxiao-yu** [PaddlePaddle/Paddle#22820]
1）PaddlePaddle版本：1.6.1
    2）gpu多机多卡

 运行平台：paddle cloud平台
日志链接：http://10.199.229.42:8388/v1/containers/be4b34bea1b8b2b24cec30e954dc4cff43984458e383b32d003776fe5591b1cb/backuplog

报错如下：

```shell
/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/executor.py:774: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
ERROR: 03-02 19:38:17: custom_trainer.py:109 * 140338501658368 traceback.format_exc():Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/textone/training/custom_trainer.py", line 62, in train_and_eval
    metrics_tensor_value = self.run(InstanceName.TRAINING, need_fetch=True)
  File "base_trainer.py", line 517, in base_trainer.BaseTrainer.run (/home/work/textone_pro/dabao/textone_pro/training/base_trainer.c:12475)
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/parallel_executor.py", line 311, in run
    return_numpy=return_numpy)
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/executor.py", line 775, in run
    six.reraise(*sys.exc_info())
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/executor.py", line 770, in run
    use_program_cache=use_program_cache)
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/executor.py", line 829, in _run_impl
    return_numpy=return_numpy)
  File "/opt/_internal/cpython-2.7.11-ucs4/lib/python2.7/site-packages/paddle/fluid/executor.py", line 669, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::LoDTensor::MergeLoDTensor(std::vector<paddle::framework::LoDTensor const*, std::allocator<paddle::framework::LoDTensor const*> > const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>)
3   paddle::framework::details::FetchOpHandle::WaitAndMergeCPUTensors() const
4   paddle::framework::details::FetchOpHandle::RunImpl()
5   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
6   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
7   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()(), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
8   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()()>&, bool&)
9   _ZZN10ThreadPoolC1EmENKUlvE_clEv

----------------------
Error Message Summary:
----------------------
PaddleCheckError: Expected framework::product(new_dim) / new_dim[0] == framework::product(t->dims()) / t->dims()[0], but received framework::product(new_dim) / new_dim[0]:51 != framework::product(t->dims()) / t->dims()[0]:55.
 at [/paddle/paddle/fluid/framework/lod_tensor.cc:363]


Traceback (most recent call last):
  File "run_with_json.py", line 91, in <module>
    trainer.train_and_eval()
  File "/root/paddlejob/workspace/env_run/textone/training/custom_trainer.py", line 111, in train_and_eval
    raise e
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::LoDTensor::MergeLoDTensor(std::vector<paddle::framework::LoDTensor const*, std::allocator<paddle::framework::LoDTensor const*> > const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>)
3   paddle::framework::details::FetchOpHandle::WaitAndMergeCPUTensors() const
4   paddle::framework::details::FetchOpHandle::RunImpl()
5   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
6   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
7   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()(), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
8   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()()>&, bool&)
9   _ZZN10ThreadPoolC1EmENKUlvE_clEv

----------------------
Error Message Summary:
----------------------
PaddleCheckError: Expected framework::product(new_dim) / new_dim[0] == framework::product(t->dims()) / t->dims()[0], but received framework::product(new_dim) / new_dim[0]:51 != framework::product(t->dims()) / t->dims()[0]:55.
 at [/paddle/paddle/fluid/framework/lod_tensor.cc:363]
```

**Comment by Melonzhou** [comment]
同样遇到这个问题，求解。

**Comment by mapingshuo** [comment]
从错误来看，你在尝试将两个LodTensor merge在一起，但是他俩一个是55维，一个是51维，导致了错误。

**Comment by mapingshuo** [comment]
python 这个脚本能共享一下吗：

```shell
  File "/root/paddlejob/workspace/env_run/textone/training/custom_trainer.py", line 111, in train_and_eval
```

**Comment by Melonzhou** [comment]
> python 这个脚本能共享一下吗：
> 
> ```shell
>   File "/root/paddlejob/workspace/env_run/textone/training/custom_trainer.py", line 111, in train_and_eval
> ```



> python 这个脚本能共享一下吗：
> 
> ```shell
>   File "/root/paddlejob/workspace/env_run/textone/training/custom_trainer.py", line 111, in train_and_eval
> ```

你方便登录到我的机器上看看么？

**Comment by mapingshuo** [comment]
目前看来是fetch的时候不同卡产生的LodTensor 维度不同（51 vs 55），merge时失败, @keaiyuzhu 你想一下组网中会不会有什么导致这个问题的原因；我这边也找专业同学来看一下。

**Comment by mapingshuo** [comment]
> 同样遇到这个问题，求解。

请问你也是1.6.1的版本，多机多卡GPU吗？你俩是一个任务吗？

**Comment by Melonzhou** [comment]
是的，同一个任务

**Comment by mapingshuo** [comment]
@keaiyuzhu 对51和55两个数字，你是否敏感，是否在组网时用到了这两个数字？

**Comment by mapingshuo** [comment]
请Hi上找我，我们详细了解一下为什么两张卡上的维度会有diff。

**Comment by mapingshuo** [comment]
这里有个类似的issue： https://github.com/PaddlePaddle/Paddle/issues/21860  ，生成任务中好像很常见这一问题

**Comment by Melonzhou** [comment]
21860的卡片是我年前提的，那种方式实现起来太麻烦了，没成功。出错的原因就是在merge 长度不同的tensor出错了。像序列标注、文本生成这种任务，预测值和标注值不可能是等长的。同一个batch中我可以padding到长度一样，但是多卡的时候就相当于是多个batch要merge到一起，我不知道其每张卡上的数据到底是啥呀。

**Comment by Melonzhou** [comment]
> 请Hi上找我，我们详细了解一下为什么两张卡上的维度会有diff。

hi名字是什么呀？我单hi你。

**Comment by mapingshuo** [comment]
> hi名字是什么呀？我单hi你。

和github一样的名字

**Comment by mapingshuo** [comment]
> 21860的卡片是我年前提的，那种方式实现起来太麻烦了，没成功。出错的原因就是在merge 长度不同的tensor出错了。像序列标注、文本生成这种任务，预测值和标注值不可能是等长的。同一个batch中我可以padding到长度一样，但是多卡的时候就相当于是多个batch要merge到一起，我不知道其每张卡上的数据到底是啥呀。

文本生成任务中的预测值和label确实很可能不同长度，它们的var的名字也应该不同，为什么会被merge在一起呢？

**Comment by Melonzhou** [comment]
不是说预测值和label被merge了，是多个batch的label被merge，多个batch的预测值被merge。

**Comment by Melonzhou** [comment]
https://github.com/PaddlePaddle/Paddle/pull/22635
