### ISSUE TITLE
Paddle gpu 1.7.0 安装 提示Error: Cannot load cudnn shared library

### ISSUE THREAD

**Issue by zengqi0730** [PaddlePaddle/Paddle#22996]
1）PaddlePaddle版本：paddlepaddle-gpu          1.7.0.post107
    2）CPU：Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    3）GPU：1080Ti
    4）系统环境：Ubuntu Kylin 18.04.3 LTS、Python3.6.10
- 安装方式信息：
1）pip安装：pip install paddlepaddle-gpu==1.7.0.post107 -i https://mirror.baidu.com/pypi/simple

- 复现信息：
- conda 已有环境
base                  *  /home/edu/anaconda3
paddle                   /home/edu/anaconda3/envs/paddle
py36                     /home/edu/anaconda3/envs/py36                     # 其中安装了pytorch1.4.0
tf1.12                   /home/edu/anaconda3/envs/tf1.12
edu@edu-Alienware-Aurora-R7:~/Desktop$ source activate paddle
(paddle) edu@edu-Alienware-Aurora-R7:~/Desktop$ conda list
# packages in environment at /home/edu/anaconda3/envs/paddle:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
_tflow_select             2.1.0                       gpu    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
absl-py                   0.9.0                    py36_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
astor                     0.8.0                    py36_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
blas                      1.0                         mkl    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
c-ares                    1.15.0            h7b6447c_1001    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
ca-certificates           2020.1.1                      0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
certifi                   2019.11.28               py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
chardet                   3.0.4                     <pip>
cudatoolkit               10.0.130                      0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudnn                     7.6.5                cuda10.0_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
cupti                     10.0.130                      0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
cycler                    0.10.0                    <pip>
decorator                 4.4.2                     <pip>
funcsigs                  1.0.2                     <pip>
gast                      0.3.3                      py_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
google-pasta              0.1.8                      py_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
graphviz                  0.13.2                    <pip>
grpcio                    1.27.2           py36hf8bcb03_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
h5py                      2.10.0           py36h7918eee_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
hdf5                      1.10.4               hb1b8bf9_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
idna                      2.9                       <pip>
intel-openmp              2020.0                      166    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
keras-applications        1.0.8                      py_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
keras-preprocessing       1.1.0                      py_1    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
kiwisolver                1.1.0                     <pip>
ld_impl_linux-64          2.33.1               h53a641e_7    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libedit                   3.1.20181209         hc058e9b_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libffi                    3.2.1                hd88cf55_4    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libgcc-ng                 9.1.0                hdf63c60_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
libgfortran-ng            7.3.0                hdf63c60_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
libprotobuf               3.11.4               hd408876_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
libstdcxx-ng              9.1.0                hdf63c60_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
markdown                  3.1.1                    py36_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
matplotlib                3.2.0                     <pip>
mkl                       2020.0                      166    http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.3.0            py36he904b0f_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl_fft                   1.0.15           py36ha843d7b_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
mkl_random                1.1.0            py36hd6b4f25_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
ncurses                   6.2                  he6710b0_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
nltk                      3.4.5                     <pip>
numpy                     1.18.1           py36h4f9e942_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
numpy                     1.18.1                    <pip>
numpy-base                1.18.1           py36hde5b4d6_1    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
objgraph                  3.4.1                     <pip>
opencv-python             4.2.0.32                  <pip>
openssl                   1.1.1d               h7b6447c_4    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
paddlepaddle-gpu          1.7.0.post107             <pip>
paddleslim                1.0.1                     <pip>
Pillow                    7.0.0                     <pip>
pip                       20.0.2                   py36_1    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
prettytable               0.7.2                     <pip>
protobuf                  3.11.4           py36he6710b0_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
protobuf                  3.11.3                    <pip>
pyparsing                 2.4.6                     <pip>
python                    3.6.10               h0371630_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.1                     <pip>
PyYAML                    5.3                       <pip>
rarfile                   3.1                       <pip>
readline                  7.0                  h7b6447c_5    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
requests                  2.23.0                    <pip>
scipy                     1.4.1            py36h0b6359f_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
scipy                     1.3.1                     <pip>
setuptools                46.0.0                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
six                       1.14.0                   py36_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
sqlite                    3.31.1               h7b6447c_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
tensorboard               1.14.0           py36hf484d3e_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
tensorflow                1.14.0          gpu_py36h57aa796_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
tensorflow-base           1.14.0          gpu_py36h8d69cac_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
tensorflow-estimator      1.14.0                     py_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
tensorflow-gpu            1.14.0               h0d30ee6_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
termcolor                 1.1.0                    py36_1    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
tk                        8.6.8                hbc83047_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
tqdm                      4.43.0                    <pip>
urllib3                   1.25.8                    <pip>
werkzeug                  1.0.0                      py_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
wheel                     0.34.2                   py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
wrapt                     1.11.2           py36h7b6447c_0    http://mirrors.ustc.edu.cn/anaconda/pkgs/main
xz                        5.2.4                h14c3975_4    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
zlib                      1.2.11               h7b6447c_3    https://mirrors.ustc.edu.cn/anaconda/pkgs/main
(paddle) edu@edu-Alienware-Aurora-R7:~/Desktop$ python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Paddle Program ... 
W0313 11:13:35.911985 11802 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.0
W0313 11:13:35.912094 11802 dynamic_loader.cc:120] Can not find library: libcudnn.so. The process maybe hang. Please try to add the lib path to LD_LIBRARY_PATH.
W0313 11:13:35.912115 11802 dynamic_loader.cc:179] Failed to find dynamic library: libcudnn.so ( libcudnn.so: cannot open shared object file: No such file or directory ) 
 Please specify its path correctly using following ways: 
 Method. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
 For instance, issue command: export LD_LIBRARY_PATH=... 
 Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled.
/home/edu/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/edu/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "/home/edu/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 120, in test_simple_exe
    exe0.run(startup_prog)
  File "/home/edu/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/home/edu/anaconda3/envs/paddle/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/edu/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/home/edu/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/edu/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/executor.py", line 905, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::dynload::EnforceCUDNNLoaded(char const*)
3   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
4   std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&)
5   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
6   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
7   std::__future_base::_Deferred_state<std::_Bind_simple<paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred()
8   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
9   paddle::framework::GarbageCollector::GarbageCollector(paddle::platform::Place const&, unsigned long)
10  paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long)
11  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
12  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

----------------------
Error Message Summary:
----------------------
Error: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion at (/paddle/paddle/fluid/platform/dynload/cudnn.cc:63)
>>>  import tensorflow as tf
 >>> print(tf.__version__)
1.14.0
 >>> tf.test.gpu_device_name()
2020-03-13 11:17:03.429640: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-03-13 11:17:03.460899: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3699850000 Hz
2020-03-13 11:17:03.461319: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562f07660ec0 executing computations on platform Host. Devices:
2020-03-13 11:17:03.461343: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2020-03-13 11:17:03.461449: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2020-03-13 11:17:03.461552: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-13 11:17:03.461941: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:01:00.0
2020-03-13 11:17:03.480250: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2020-03-13 11:17:03.654387: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2020-03-13 11:17:03.749657: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2020-03-13 11:17:03.781214: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2020-03-13 11:17:03.948525: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2020-03-13 11:17:04.061082: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2020-03-13 11:17:04.071400: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2020-03-13 11:17:04.071702: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-13 11:17:04.073268: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-13 11:17:04.074585: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2020-03-13 11:17:04.074718: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2020-03-13 11:17:04.097656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-03-13 11:17:04.097738: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2020-03-13 11:17:04.097764: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2020-03-13 11:17:04.098118: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-13 11:17:04.099641: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-13 11:17:04.101200: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-03-13 11:17:04.102656: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 10087 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2020-03-13 11:17:04.107436: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x562f07661600 executing computations on platform CUDA. Devices:
2020-03-13 11:17:04.107505: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
'/device:GPU:0'
>>> 

(paddle) edu@edu-Alienware-Aurora-R7:~/Downloads$  cat /usr/local/cuda/version.txt
CUDA Version 10.1.243
(paddle) edu@edu-Alienware-Aurora-R7:~/Downloads$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 6
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"

**Comment by LDOUBLEV** [comment]
麻烦提供下CUDNN的版本，或者尝试安装paddle 1.7.1

**Comment by zengqi0730** [comment]
CUDNN: /usr/local/cuda-10.1/lib64/libcudnn.so.7.6.5

**Comment by JepsonWong** [comment]
看你conda里面也装了cuda、cudnn：
cudatoolkit 10.0.130 0 http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cudnn 7.6.5 cuda10.0_0 http://mirrors.ustc.edu.cn/anaconda/pkgs/main

你用的cuda、cudnn是在哪个位置呢？

**Comment by zengqi0730** [comment]
再source /etc/profile 一下就行了
libcudnn.so的路径在这个文件里写了，只是搞不懂为啥我的tf和pytorch没事

**Comment by threefoldo** [comment]
The problem is probably caused by the libcudnn package, for example, this version libcudnn7_7.6.5.32-1+cuda9.2_amd64.deb doesn't install "libcudnn.so", only "libcudnn.so.7", and "libcudnn.so.7.6.5". So, if a program try to use "libcudnn.so", it will not find it correctly.
