### ISSUE TITLE
利用Executor的参数fetch list获取模型执行的中间结果时，出错

### ISSUE THREAD

**Issue by Akeepers** [PaddlePaddle/Paddle#22995]
paddle version: 1.6.3
python 2.7
错误信息：
```
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "run_seq2seq.py", line 236, in <module>
    main(args)
  File "run_seq2seq.py", line 207, in main
    train(args)
  File "run_seq2seq.py", line 106, in train
    preds_res, loss_val = exe.run(program=prog, feed=data, fetch_list=[preds_res, loss])
  File "/home/yangpan/anaconda3/envs/paddle-py2.7/lib/python2.7/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/home/yangpan/anaconda3/envs/paddle-py2.7/lib/python2.7/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/home/yangpan/anaconda3/envs/paddle-py2.7/lib/python2.7/site-packages/paddle/fluid/executor.py", line 834, in _run_impl
    return_numpy=return_numpy)  File "/home/yangpan/anaconda3/envs/paddle-py2.7/lib/python2.7/site-packages/paddle/fluid/executor.py", line 674, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::LoDTensor::MergeLoDTensor(std::vector<paddle::framework::LoDTensor const*, std::allocator<paddle::framework::LoDTensor const*> > const&, paddle::platform::Place)
3   paddle::framework::details::FetchOpHandle::WaitAndMergeCPUTensors() const
4   paddle::framework::details::FetchOpHandle::RunImpl()
5   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
6   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
7   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
8   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
9   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Paddle internal Check failed. (Please help us create a new issue, here we need to find the developer to add a user friendly error message)
  [Hint: Expected framework::product(new_dim) / new_dim[0] == framework::product(t->dims()) / t->dims()[0], but received framework::product(new_dim) / new_dim[0]:50 != framework::product(t->dims()) / t->dims()[0]:63.] at (/paddle/paddle/fluid/framework/lod_tensor.cc:363)

```

报错部分的paddle代码：
报错部分： preds_res, loss_val = exe.run(program=prog, feed=data, fetch_list=[preds_res, loss]) 
Note: 如果将fetch_list中的preds_res去除，代码运行正常
```
 for current_epoch in range(args.epoch):
        step = 0
        for data in loader():
            step += 1
            preds_res, loss_val = exe.run(program=prog, feed=data, fetch_list=[preds_res, loss])
            loss_val = np.mean(loss_val)
            np_preds_res = np.array(preds_res)

            current_example, current_epoch = reader.get_train_progress()
            print('epoch: %d, batch_id: %d/%d, loss: %f' %
                  (current_epoch, step, num_examples, loss_val))

            if step % args.save_steps == 0:
                save_path = os.path.join(args.checkpoints,
                                         "step_" + str(step))
                fluid.io.save_persistables(exe, save_path, train_prog)
                print("step: %d, save model in %s" % (step, save_path))
        # except fluid.core.EOFException:
        # save_path = os.path.join(args.checkpoints,
        #                          "step_" + str(step))
        # fluid.io.save_persistables(exe, save_path, train_prog)
        # print("step: %d, save model in %s" % (step, save_path))
        # loader.reset()
```
 program定义：
```
    train_prog = fluid.Program()
    startup_prog = fluid.Program()
    with fluid.program_guard(train_prog, startup_prog):
        with fluid.unique_name.guard():
            # For training:
            inputs, loader = data_func(args, is_train=True)
            logits = model_func(args, inputs, ernie_config, is_train=True)
            loss, preds_res = loss_func(logits, inputs[-1], inputs[-2])
            optimizer = optimizer_func()
            optimizer.minimize(loss)
```
loss func定义：
```
def loss_func(logits, label, trg_sequence_length):
    probs = layers.softmax(logits)
    res = layers.argmax(probs, axis=-1)
    loss = layers.cross_entropy(input=probs, label=label)
    trg_mask = layers.sequence_mask(
        trg_sequence_length, maxlen=layers.shape(logits)[1], dtype="float32")
    avg_cost = layers.reduce_sum(loss * trg_mask) / layers.reduce_sum(trg_mask)
    return avg_cost, res
```

**Comment by LDOUBLEV** [comment]
问题可能出在sequence_mask 这里，麻烦提供下trg_sequence_length的数据格式和shape

**Comment by Akeepers** [comment]
数据定义：
```
def data_func(args, is_train=True):
    """data inputs and data loader"""
    src_ids = fluid.layers.data(name='1', shape=[-1, args.max_seq_len, 1], dtype='int64')
    sent_ids = fluid.layers.data(name='2', shape=[-1, args.max_seq_len, 1], dtype='int64')
    pos_ids = fluid.layers.data(name='3', shape=[-1, args.max_seq_len, 1], dtype='int64')
    task_ids = fluid.layers.data(name='4', shape=[-1, args.max_seq_len, 1], dtype='int64')
    input_mask = fluid.layers.data(name='5', shape=[-1, args.max_seq_len, 1], dtype='float32')
    seq_lens = fluid.layers.data(name='6', shape=[-1], dtype='int64')

    inputs = [src_ids, sent_ids, pos_ids, task_ids, input_mask, seq_lens]
    if is_train:
        labels = fluid.layers.data(name='7', shape=[-1, args.max_seq_len, 1], dtype='int64')
        inputs += [labels]
    loader = fluid.io.DataLoader.from_generator(
        feed_list=inputs, capacity=70, iterable=True)
    return inputs, loader
```
reader里，在同一个batch 内进行了padding

**Comment by Akeepers** [comment]
[update]:
1. print(trg_sequence_length)的结果
![image](https://user-images.githubusercontent.com/22610351/76588076-0cb90680-6521-11ea-86e5-e5e80961a282.png)

2. 运行时layer.Print(trg_sequence_length)的结果：
![image](https://user-images.githubusercontent.com/22610351/76588113-22c6c700-6521-11ea-8e1e-fd27e5c0b78c.png)

**Comment by LDOUBLEV** [comment]
写了一个简单的单测，没能复现你的问题，麻烦和你的代码对比下，代码如下：
```
import paddle.fluid.layers as layers
import paddle.fluid as fluid

import numpy as np


def loss_func(logits, label, trg_sequence_length):
    probs = layers.softmax(logits)
    res = layers.argmax(probs, axis=-1)
    loss = layers.cross_entropy(input=probs, label=label)
    trg_mask = layers.sequence_mask(
        trg_sequence_length, maxlen=layers.shape(logits)[1], dtype="float32")
    #avg_cost = layers.reduce_sum(loss * trg_mask) / layers.reduce_sum(trg_mask)
    _loss_mask = layers.reduce_sum(loss * trg_mask)
    _mask = layers.reduce_sum(trg_mask)
    avg_cost = _loss_mask / _mask
    return avg_cost, res, _loss_mask


BS = 16
train_prog = fluid.Program()
startup_prog = fluid.Program()
with fluid.program_guard(train_prog, startup_prog):
    with fluid.unique_name.guard():

        logits = fluid.data('data', shape=[BS, 30])
        label = fluid.data('label', shape=[BS, 1], dtype='int64')

        seq_length = fluid.data('seq', shape=[16], dtype='int64')

        loss, preds_res, _loss_mask = loss_func(logits, label, seq_length)

        exe = fluid.Executor(place=fluid.CPUPlace())
        exe.run(program=fluid.default_startup_program())
        compiled_prog = fluid.compiler.CompiledProgram(train_prog)

        _inp = np.random.uniform(0, 1, [BS, 30]).astype(np.float32)
        _label = np.random.uniform(0, 10, [BS, 1]).astype(np.int64)
        _seq = np.random.uniform(0, 30, [16]).astype(np.int64)

        res = exe.run(compiled_prog, feed={'data':_inp, 'label':_label, 'seq':_seq},
                      fetch_list=[loss.name, preds_res.name, _loss_mask.name])

        print(res[0], res[1], res[-1])
```

调试时可以尝试，把loss_func里的trg_mask和avg_cost 逐个run出来看下，看是在哪里计算出错了。

**Comment by Akeepers** [comment]
好的，谢谢

有一个问题？引用“把loss_func里的trg_mask和avg_cost 逐个run出来看下，看是在哪里计算出错了。”这里的逐个run出来，我不没太明白是什么意思

**Comment by LDOUBLEV** [comment]
OK ， 是我没说明白，你可以先把trg_mask run出来，如果有结果没报错，说明sequence_mask 没问题，然后再检查是不是做除法的时候计算avg_cost出问题了。

**Comment by Akeepers** [comment]
好的，麻烦了

**Comment by Akeepers** [comment]
请问下，你用的什么paddle版本哇？你给出的单侧文件我看了下，没问题，但是跑这个单侧代码的时候，会报错：
仅修改代码中的print部分（我这边是python 2.7）
```
/home/yangpan/anaconda3/envs/paddle-py2.7/lib/python2.7/site-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    fetch_list=[loss.name, preds_res.name, _loss_mask.name])
  File "/home/yangpan/anaconda3/envs/paddle-py2.7/lib/python2.7/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/home/yangpan/anaconda3/envs/paddle-py2.7/lib/python2.7/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/home/yangpan/anaconda3/envs/paddle-py2.7/lib/python2.7/site-packages/paddle/fluid/executor.py", line 834, in _run_impl
    return_numpy=return_numpy)
  File "/home/yangpan/anaconda3/envs/paddle-py2.7/lib/python2.7/site-packages/paddle/fluid/executor.py", line 674, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------                                                                                                                                             [0/476]
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::get_mid_dims(paddle::framework::DDim const&, paddle::framework::DDim const&, int, int*, int*, int*, int*)
3   void paddle::operators::ElementwiseComputeEx<paddle::operators::MulFunctor<float, void>, paddle::platform::CPUDeviceContext, float, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, int, paddle::operators::MulFunctor<float, void>, paddle::framework::Tensor*)
4   void paddle::operators::default_elementwise_mul<paddle::platform::CPUDeviceContext, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, paddle::framework::Tensor*)
5   paddle::operators::ElementwiseMulKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
6   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::ElementwiseMulKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::ElementwiseMulKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::ElementwiseMulKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::ElementwiseMulKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
8   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
9   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
10  paddle::framework::details::OpHandleBase::RunAndRecordEvent(std::function<void ()> const&)
11  paddle::framework::details::ComputationOpHandle::RunImpl()
12  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
13  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
14  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
15  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
16  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/yangpan/anaconda3/envs/paddle-py2.7/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/yangpan/anaconda3/envs/paddle-py2.7/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 239, in __impl__
    attrs={'axis': axis})
  File "test.py", line 14, in loss_func
    _loss_mask = layers.reduce_sum(loss * trg_mask)
  File "test.py", line 30, in <module>
    loss, preds_res, _loss_mask = loss_func(logits, label, seq_length)

----------------------
Error Message Summary:
----------------------
Error: ShapeError: broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [16, 1] and the shape of Y = [16, 30]. Received [1] in X is not equal to [30] in Y
  [Hint: Expected y_dims[i] == 1, but received y_dims[i]:30 != 1:1.] at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:79)
  [operator < elementwise_mul > error]

```

**Comment by LDOUBLEV** [comment]
看报错是，loss和trg_mask的shape不一致，无法直接相乘
