### ISSUE TITLE
docker images paddle 0.10.0 import error

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#2300]
root:/home# python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.v2 as paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/__init__.py", line 36, in <module>
    import image
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 7, in <module>
    from cv2 import resize
  File "/usr/local/lib/python2.7/dist-packages/cv2/__init__.py", line 7, in <module>
    from . import cv2
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
>>>

**Comment by typhoonzero** [comment]
Can not reproduce this error with `paddlepaddle/paddle:0.10.0` image? Is it already fixed?

**Comment by Yancey1989** [comment]
I can not reproduce the error also, I will close this issue and feel free to reopen it, thanks!
