### ISSUE TITLE
Unit test test_v2_api, reader_tests, test_ploter failed on NVIDIA DRIVE PX 2.

### ISSUE THREAD

**Issue by Xreki** [PaddlePaddle/Paddle#2305]
When running python unit test, Paddle will deploy its own copy of python, and install all modules needed using `pip install`. When running those unit tests on NVIDIA DRIVE PX2, it failed to install `paddle-0.10.0-py2-none-any.whl` and caused those unit tests failed. Detailed information is listed as follows:

```bash
72: Processing /home/ubuntu/liuyiqun01/Paddle/build/python/dist/paddle-0.10.0-py2-none-any.whl
72: Collecting opencv-python (from paddle==0.10.0)
72:   Could not find a version that satisfies the requirement opencv-python (from paddle==0.10.0) (from versions: )
72: No matching distribution found for opencv-python (from paddle==0.10.0)
72: Collecting ipython==5.3
72:   Using cached ipython-5.3.0-py2-none-any.whl
72: Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython==5.3)
72:   Using cached prompt_toolkit-1.0.14-py2-none-any.whl
72: Requirement already satisfied: setuptools>=18.5 in ./.test_env/lib/python2.7/site-packages (from ipython==5.3)
72: Collecting pexpect; sys_platform != "win32" (from ipython==5.3)
72:   Using cached pexpect-4.2.1-py2.py3-none-any.whl
72: Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from ipython==5.3)
72:   Using cached backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
72: Collecting decorator (from ipython==5.3)
72:   Using cached decorator-4.0.11-py2.py3-none-any.whl
72: Collecting pygments (from ipython==5.3)
72:   Using cached Pygments-2.2.0-py2.py3-none-any.whl
72: Collecting pathlib2; python_version == "2.7" or python_version == "3.3" (from ipython==5.3)
72:   Using cached pathlib2-2.2.1-py2.py3-none-any.whl
72: Collecting traitlets>=4.2 (from ipython==5.3)
72:   Using cached traitlets-4.3.2-py2.py3-none-any.whl
72: Collecting simplegeneric>0.8 (from ipython==5.3)
72: Collecting pickleshare (from ipython==5.3)
72:   Using cached pickleshare-0.7.4-py2.py3-none-any.whl
72: Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython==5.3)
72:   Using cached wcwidth-0.1.7-py2.py3-none-any.whl
72: Requirement already satisfied: six>=1.9.0 in ./.test_env/lib/python2.7/site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython==5.3)
72: Requirement already satisfied: packaging>=16.8 in ./.test_env/lib/python2.7/site-packages (from setuptools>=18.5->ipython==5.3)
72: Requirement already satisfied: appdirs>=1.4.0 in ./.test_env/lib/python2.7/site-packages (from setuptools>=18.5->ipython==5.3)
72: Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython==5.3)
72:   Using cached ptyprocess-0.5.1-py2.py3-none-any.whl
72: Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython==5.3)
72: Collecting ipython-genutils (from traitlets>=4.2->ipython==5.3)
72:   Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl
72: Collecting enum34; python_version == "2.7" (from traitlets>=4.2->ipython==5.3)
72:   Using cached enum34-1.1.6-py2-none-any.whl
72: Requirement already satisfied: pyparsing in ./.test_env/lib/python2.7/site-packages (from packaging>=16.8->setuptools>=18.5->ipython==5.3)
72: Installing collected packages: wcwidth, prompt-toolkit, ptyprocess, pexpect, backports.shutil-get-terminal-size, decorator, pygments, scandir, pathlib2, ipython-genutils, enum34, traitlets, simplegeneric, pickleshare, ipython
72: Successfully installed backports.shutil-get-terminal-size-1.0.0 decorator-4.0.11 enum34-1.1.6 ipython-5.3.0 ipython-genutils-0.2.0 pathlib2-2.2.1 pexpect-4.2.1 pickleshare-0.7.4 prompt-toolkit-1.0.14 ptyprocess-0.5.1 pygments-2.2.0 scandir-1.5 simplegeneric-0.8.1 traitlets-4.3.2 wcwidth-0.1.7
72: test test_data_feeder.py
72: Traceback (most recent call last):
72:   File "test_data_feeder.py", line 17, in <module>
72:     import py_paddle.swig_paddle as api
72:   File "/home/ubuntu/liuyiqun01/Paddle/python/paddle/v2/tests/.test_env/local/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
72:     from util import DataProviderWrapperConverter
72:   File "/home/ubuntu/liuyiqun01/Paddle/python/paddle/v2/tests/.test_env/local/lib/python2.7/site-packages/py_paddle/util.py", line 20, in <module>
72:     import paddle.trainer.PyDataProviderWrapper
72: ImportError: No module named paddle.trainer.PyDataProviderWrapper
1/1 Test #72: test_v2_api ......................***Failed   28.47 sec
```

On NVIDIA DRIVE PX2, we can use `apt-get install python-opencv` instead of `pip install opencv-python` to install opencv.

**Comment by Xreki** [comment]
Cannot install paddle‘s python package because of the same problem.
```bash
$ pip install opt/paddle/share/wheels/paddle-0.10.0-py2-none-any.whl 
Processing ./opt/paddle/share/wheels/paddle-0.10.0-py2-none-any.whl
Collecting opencv-python (from paddle==0.10.0)
  Could not find a version that satisfies the requirement opencv-python (from paddle==0.10.0) (from versions: )
No matching distribution found for opencv-python (from paddle==0.10.0)
```
