### ISSUE TITLE
 Paddle 1.6 在 CPU 上运行 Bert 模型时 InferShape 报错

### ISSUE THREAD

**Issue by Karbit** [PaddlePaddle/Paddle#23065]
环境和模型信息：
PaddlePaddle 1.6, 使用 pip 安装
Paddle Models, 1.6, https://github.com/PaddlePaddle/models/blob/release/1.6/PaddleNLP/PaddleLARK/BERT/
复现：
将 train.sh 中的 use_cuda 改为 false, 然后执行 ./train.sh -local y.
报错信息：
```
------------------------------------------------
Traceback (most recent call last):
  File "./train.py", line 439, in <module>
    train(args)
  File "./train.py", line 232, in train
    bert_config=bert_config)
  File "./train.py", line 124, in create_model
    use_fp16=args.use_fp16)
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/bert.py", line 81, in __init__
    self._build_model(src_ids, position_ids, sentence_ids, input_mask)
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/bert.py", line 139, in _build_m
    name='encoder')
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 3
    name=name + '_layer_' + str(i))
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 2
    name=name + '_multi_head_att')
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 1
    dropout_rate)
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 1
    out = layers.matmul(weights, v)
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6974, in matmul
    'alpha': float(alpha),
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2426, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1809, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::MatMulOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2426, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6974, in matmul
    'alpha': float(alpha),
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 1
    out = layers.matmul(weights, v)
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 1
    dropout_rate)
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 2
    name=name + '_multi_head_att')
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 3
    name=name + '_layer_' + str(i))
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/bert.py", line 139, in _build_m
    name='encoder')
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/bert.py", line 81, in __init__
    self._build_model(src_ids, position_ids, sentence_ids, input_mask)
  File "./train.py", line 124, in create_model
    use_fp16=args.use_fp16)
  File "./train.py", line 232, in train
    bert_config=bert_config)
```

**Comment by Xreki** [comment]
从你贴的log来看，应该是在组网阶段就报错了，我拉取了models的release/1.6分支，pip安装1.6.0版本，无法复现你的错误。以下是我测试环境的详细信息：
- Paddle版本：
```
$ python -c "import paddle; print(paddle.__version__)"
1.6.0
```
- models代码commit
```
commit a95d49323ed504e5a9164586f171f408954fd43a
Author: sserdoubleh <sserdoubleh@gmail.com>
Date:   Thu Nov 14 18:01:56 2019 +0800

    Update Dialog-PLATO: Support paddlepaddle1.6. Release PLATO w/o latent. (#3931)

    * Upload mode: Dialogue-BLATO.

    * Update README.md.

    * Update Dialog-PLATO: Support APIs in paddlepaddle 1.6 and more features. Release PLATO w/o latent.
```

请你确认下你的Paddle版本和models版本。若仍然出现错误，请提供一下更详细的信息。

**Comment by Karbit** [comment]
请问你测试的时候是 GPU 还是 CPU，我这边仍然出现错误，复现方法如下：
拉下来 models/release1.6 分支之后，通过如下操作可以复现：
1. cd 到 Bert 模型的目录
2. 修改 train.sh, 将其中的 use_cuda 改为 false
3.  执行 ./train.sh -local y.

**Comment by Xreki** [comment]
> 请问你测试的时候是 GPU 还是 CPU

就是按照你说的来测试的。

你这个错误，看起来像是组网阶段报错，所以跟CPU、GPU应该无关。

你报错应该在[transformer_encoder.py#L127](https://github.com/PaddlePaddle/models/blob/a95d49323ed504e5a9164586f171f408954fd43a/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py#L127)，使用`print(weight)`和`print(v)`打印一下看看。

另外，你之前贴的log应该不全，没有贴出真正的错误信息。

**Comment by Karbit** [comment]
之前漏了最后的一小段 LOG，重贴一下：

```
Traceback (most recent call last):
  File "./train.py", line 439, in <module>
    train(args)
  File "./train.py", line 232, in train
    bert_config=bert_config)
  File "./train.py", line 124, in create_model
    use_fp16=args.use_fp16)
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/bert.py", line 81, in __init__
    self._build_model(src_ids, position_ids, sentence_ids, input_mask)
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/bert.py", line 139, in _build_m
    name='encoder')
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 3
    name=name + '_layer_' + str(i))
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 2
    name=name + '_multi_head_att')
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 1
    dropout_rate)
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 1
    out = layers.matmul(weights, v)
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6974, in matmul
    'alpha': float(alpha),
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2426, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1809, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::MatMulOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2426, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/liujiaqiang/.jumbo/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6974, in matmul
    'alpha': float(alpha),
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 1
    out = layers.matmul(weights, v)
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 1
    dropout_rate)
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 2
    name=name + '_multi_head_att')
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/transformer_encoder.py", line 3
    name=name + '_layer_' + str(i))
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/bert.py", line 139, in _build_m
    name='encoder')
  File "/home/liujiaqiang/workdir/paddle-models/models-release-1.6/PaddleNLP/PaddleLARK/BERT/model/bert.py", line 81, in __init__
    self._build_model(src_ids, position_ids, sentence_ids, input_mask)
  File "./train.py", line 124, in create_model
    use_fp16=args.use_fp16)
  File "./train.py", line 232, in train
    bert_config=bert_config)
  File "./train.py", line 439, in <module>
    train(args)

----------------------
:set nonumber
Error Message Summary:
----------------------
PaddleCheckError: Expected head_number <= mat_dim_x.width_, but received head_number:1 > mat_dim_x.width_:-1.
ShapeError: Unsatisfied mkl acceleration library requirements: The number of heads (1) must be equal to X's width. But received X'
  [operator < matmul > error]
```
按照你的建议，打印了 print(weight) 和 print(v), 结果如下：

```
name: "transpose_2.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 12
      dims: -1
      dims: 64
    }
  }
}
persistable: false

name: "dropout_1.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 12
      dims: -1
      dims: -1
    }
    lod_level: 0
  }
```

### 供 debug 参考

根据 C++ 调用栈，错误出在MatMulOp::InferShape 函数里，看了下代码（https://github.com/PaddlePaddle/Paddle/blob/release/1.6/paddle/fluid/operators/matmul_op.cc） 这其中有下面的一段：

```
#if defined(PADDLE_WITH_MKLML) && !defined(PADDLE_WITH_CUDA)
    int head_number = context->Attrs().Get<int>("head_number");
    bool split_vertical_y = (mat_dim_x.width_ != mat_dim_y.height_);
    if (context->IsRuntime()) {
      PADDLE_ENFORCE_LE(
          head_number, mat_dim_x.width_,
          "ShapeError: Unsatisfied mkl acceleration library requirements: "
          "The number of heads "
          "(%d) must be equal to X's width. But received X's shape: %s.",
          head_number, DumpMatrixShape(mat_dim_x).c_str());

      if (!split_vertical_y && head_number > 0) {
        dim_out_y = head_number * mat_dim_y.width_;
      }
    }
#else
    PADDLE_ENFORCE_EQ(
        mat_dim_x.width_, mat_dim_y.height_,
        "ShapeError: Input X's width should be equal to the Y's height, "
        "but received X's shape: %s,"
        "Y's shape: %s.",
        DumpMatrixShape(mat_dim_x).c_str(), DumpMatrixShape(mat_dim_y).c_str());
#endif
```
从上面的代码看，这里 CPU 和 GPU 的处理逻辑不同，所以我才强调用 CPU。

麻烦看下，还需要我提供哪些信息，辛苦，谢谢

**Comment by Xreki** [comment]
@Karbi 感谢你提供如此详细的debug信息。从出错的地方的源码来看，需要使用cpu-only的包，才能走到对应的分支。我安装1.6.0的cpu-only版本复现了该错误，并且发现1.6.1版本中已经修复了该问题，具体修复的PR是https://github.com/PaddlePaddle/Paddle/pull/20717 。
