### ISSUE TITLE
paddlehub的bert的sequence_out（variable,lod-tensor)如何转换为lod_level=1，以便后接dynamic_lstm??

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/Paddle#23210]
我考虑了layers的lod_append,但他并不能改变我的seq_output
考虑使用lod_reset:
他在一般的variable上可以用，但在sequence_output上用不了
set_lod也不管用
```
import paddle.fluid as fluid
seq_feature=fluid.layers.lod_reset(seq_output, target_lod=[1]*128)
print(seq_feature)
name: "@HUB_bert_chinese_L-12_H-768_A-12@@HUB_bert_chinese_L-12_H-768_A-12@layer_norm_24.tmp_2"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 768
    }
    lod_level: 0
  }
}
persistable: false
```

```
 
import paddle.fluid as fluid
x = fluid.layers.data(name='x1', shape=[128,768], lod_level=0)
print(x)
out = fluid.layers.lod_reset(x, target_lod=[128])
print(out)


name: "x1"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 768
    }
    lod_level: 0
  }
}
persistable: false

name: "lod_reset_1.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 768
    }
    lod_level: 1
  }
}
persistable: false
```
这是我想要实现的代码：
```
`import paddlehub as hub
max_seq_len=128
# dataset = MyDataset()
module = hub.Module(name="bert_chinese_L-12_H-768_A-12")
inputs, outputs, program = module.context(
trainable=True, max_seq_len=max_seq_len)
print(outputs)
# Use "pooled_output" for classification tasks on an entire sentence.
pooled_output = outputs["pooled_output"]
seq_output=outputs['sequence_output']
print(seq_output)
hidden_units=[128]
cls_feats = fluid.layers.dropout(
            x=seq_output,
            dropout_prob=0,
            dropout_implementation="upscale_in_train")
print(cls_feats)
if hidden_units is not None:
    for n_hidden in hidden_units:
        # cls_feats = fluid.layers.fc(
        #     input=cls_feats, size=n_hidden, act=None)
        # print(cls_feats)
        cls_feats = fluid.layers.fc(input=cls_feats, size=n_hidden,
                    act=None, bias_attr=None)
        print(cls_feats)
        lstm_h, c = fluid.layers.dynamic_lstm(
            input=cls_feats, size=n_hidden, is_reverse=False)
        print(lstm_h)
        # # 最大池化
        lstm_max = fluid.layers.sequence_pool(input=lstm_h, pool_type='max')
        print(lstm_max)
        # # 激活函数
        cls_feats = fluid.layers.tanh(lstm_max)
        print(cls_feats)

logits = fluid.layers.fc(
    input=cls_feats,
    size=3,
    param_attr=fluid.ParamAttr(
        name="cls_out_w",
        initializer=fluid.initializer.TruncatedNormal(scale=0.02)),
    bias_attr=fluid.ParamAttr(
        name="cls_out_b", initializer=fluid.initializer.Constant(0.)),
    act="softmax")

ret_infers = fluid.layers.reshape(
    x=fluid.layers.argmax(logits, axis=1), shape=[-1, 1])
----------------------
Error Message Summary:
----------------------
Error: Size of target LoD should be greater than 1.
  [Hint: Expected level0.size() > 1UL, but received level0.size():1 <= 1UL:1.] at (/paddle/paddle/fluid/operators/lod_reset_op.h:60)
  [operator < lod_reset > error]
```
`

**Comment by sneaxiy** [comment]
请问您是要在cls_feats上设置lod吗？能写下您所说的使用lod_reset不成功的代码吗？上面的代码里没看到lod_reset。

**Comment by wxl1351641822** [comment]
```
  def _build_net(self):
        self.feature = fluid.layers.lod_reset(self.feature, target_lod=[128])
        cls_feats = fluid.layers.dropout(
            x=self.feature,
            dropout_prob=0.1,
            dropout_implementation="upscale_in_train",
            seed=seed)

        if hidden_units is not None:
            for n_hidden in hidden_units:
                cls_feats=self._bilstm_layer(n_hidden)

        logits = fluid.layers.fc(
            input=cls_feats,
            size=self.num_classes,
            param_attr=fluid.ParamAttr(
                name="cls_out_w",
                initializer=fluid.initializer.TruncatedNormal(scale=0.02, seed=seed)),
            bias_attr=fluid.ParamAttr(
                name="cls_out_b", initializer=fluid.initializer.Constant(0.)),
            act="softmax")

        self.ret_infers = fluid.layers.reshape(
            x=fluid.layers.argmax(logits, axis=1), shape=[-1, 1])

        return [logits]
----------------------
Error Message Summary:
----------------------
Error: Size of target LoD should be greater than 1.
  [Hint: Expected level0.size() > 1UL, but received level0.size():1 <= 1UL:1.] at (/paddle/paddle/fluid/operators/lod_reset_op.h:60)
  [operator < lod_reset > error]
```
 self.feature = fluid.layers.lod_reset(self.feature, target_lod=[128])
这一行，加不加都会报上面的错误： [operator < lod_reset > error]

**Comment by sneaxiy** [comment]
> self.feature = fluid.layers.lod_reset(self.feature, target_lod=[128])
> 这一行，加不加都会报上面的错误： [operator < lod_reset > error]

目前看来应该不是这里的lod_reset报错吧，那其他地方的lod_reset是怎么设置的呢？另外，lod_reset这个API的target_lod要传入基于offset的lod，就是此处应该写target_lod=[0, 128]。

**Comment by wxl1351641822** [comment]
我的代码里没有其他的lod_reset了。但是dynamic_lstm这个是要求lod_level=1,然后从框架里拿出来，将paddlehub的bert的sequence_output送入lod_reset，就下面这行，输出却是个bool的值？？？
```
seq_feature=fluid.layers.lod_reset(seq_output, target_lod=[0,128])#换成0,128也没有用
[2020-03-26 12:40:30,459] [    INFO] - Installing bert_chinese_L-12_H-768_A-12 module
[2020-03-26 12:40:30,461] [    INFO] - Module bert_chinese_L-12_H-768_A-12 already installed in /home/aistudio/.paddlehub/modules/bert_chinese_L_12_H_768_A_12
[2020-03-26 12:40:32,821] [    INFO] - Load pretraining parameters from /home/aistudio/.paddlehub/modules/bert_chinese_L_12_H_768_A_12/assets/params.
name: "@HUB_bert_chinese_L-12_H-768_A-12@@HUB_bert_chinese_L-12_H-768_A-12@layer_norm_24.tmp_2"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 768
    }
    lod_level: 0
  }
}
persistable: false

name: "lod_reset_1.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: BOOL
      dims: 0
    }
    lod_level: 1
  }
}
persistable: false
```
然后如果自己初始化一个variable,用上面的这个代码，就没有任何问题

```
import paddle.fluid as fluid
x = fluid.layers.data(name='x1', shape=[128,768], lod_level=0)
print(x)
out = fluid.layers.lod_reset(x, target_lod=[128])
print(out)


name: "x1"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 768
    }
    lod_level: 0
  }
}
persistable: false

name: "lod_reset_1.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 768
    }
    lod_level: 1
  }
}
persistable: false
```

**Comment by wxl1351641822** [comment]
从dynamic_lstm换成lstm也不管用orz……求问这是什么情况？？？
不用lstm的时候就一切正常
```
    def _build_net(self):
        # self.feature = fluid.layers.lod_reset(self.feature, target_lod=[128])
        cls_feats = fluid.layers.dropout(
            x=self.feature,
            dropout_prob=0.1,
            dropout_implementation="upscale_in_train",
            seed=seed)

        # cls_feats=fluid.layers.lod_reset(self.feature, target_lod=[128])
        if hidden_units is not None:
            for n_hidden in hidden_units:
                num_layers=1
                init_h = fluid.layers.fill_constant([num_layers*2, batch_size,n_hidden], 'float32', 0.0)
                init_c = fluid.layers.fill_constant([num_layers*2, batch_size, n_hidden], 'float32', 0.0)
                cls_feats, last_h, last_c = fluid.layers.lstm(cls_feats, init_h, init_c, max_seq_len,n_hidden, num_layers,is_bidirec=True,seed=seed)
                print(cls_feats)

        logits = fluid.layers.fc(
                input=cls_feats,
                size=self.num_classes,
                param_attr=fluid.ParamAttr(
                    name="cls_out_w",
                    initializer=fluid.initializer.TruncatedNormal(scale=0.02, seed=seed)),
                bias_attr=fluid.ParamAttr(
                    name="cls_out_b", initializer=fluid.initializer.Constant(0.)),
                act="softmax")

        self.ret_infers = fluid.layers.reshape(
            x=fluid.layers.argmax(logits, axis=1), shape=[-1, 1])

        return [logits]
```

```
[2020-03-26 16:50:18,650] [    INFO] - Installing bert_chinese_L-12_H-768_A-12 module
[2020-03-26 16:50:18,653] [    INFO] - Module bert_chinese_L-12_H-768_A-12 already installed in /home/aistudio/.paddlehub/modules/bert_chinese_L_12_H_768_A_12
[2020-03-26 16:50:18,654] [    INFO] - Dataset label map = {'-1': 0, '0': 1, '1': 2}
[2020-03-26 16:50:18,682] [ WARNING] - Both noam_decay and linear_decay have been set, only noam_decay will take effect
[2020-03-26 16:50:18,682] [    INFO] - Checkpoint dir: ./work/model4
[2020-03-26 16:50:22,556] [    INFO] - Load pretraining parameters from /home/aistudio/.paddlehub/modules/bert_chinese_L_12_H_768_A_12/assets/params.
[2020-03-26 16:50:22,723] [    INFO] - Delete hook eval_end_event:default successfully
[2020-03-26 16:50:22,723] [    INFO] - Add hook eval_end_event:new_eval_end_event successfully
[2020-03-26 16:50:22,723] [    INFO] - Add hook log_interval_event:new_log_interval_event successfully
[2020-03-26 16:50:24,008] [    INFO] - Strategy with warmup, noam decay, slanted triangle learning rate, weight decay regularization, 
W0326 16:50:25.047698   474 device_context.cc:236] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0326 16:50:25.052628   474 device_context.cc:244] device: 0, cuDNN Version: 7.3.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:795: UserWarning: The current program is empty.
  warnings.warn(error_info)
[2020-03-26 16:50:26,302] [    INFO] - Try loading checkpoint from ./work/model4/ckpt.meta
[2020-03-26 16:50:26,303] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-03-26 16:50:26,357] [    INFO] - PaddleHub finetune start
I0326 16:50:26.698858   474 parallel_executor.cc:421] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I0326 16:50:26.823554   474 build_strategy.cc:363] SeqOnlyAllReduceOps:0, num_trainers:1
I0326 16:50:27.010787   474 parallel_executor.cc:285] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0326 16:50:27.115900   474 parallel_executor.cc:368] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:779: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
4
name: "dropout_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 768
    }
    lod_level: 0
  }
}
persistable: false

name: "cudnn_lstm_0.tmp_0"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 128
      dims: 32
    }
  }
}
persistable: false

Traceback (most recent call last):
  File "./work/change.py", line 766, in <module>
    run_states = cls_task.finetune_and_eval()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 863, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 884, in finetune
    run_states = self._run(do_eval=do_eval)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 1077, in _run
    return_numpy=self.return_numpy)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 834, in _run_impl
    return_numpy=return_numpy)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 674, in _run_parallel
    tensors = exe.run(fetch_var_names)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
2   paddle::operators::CudnnRNNCache::init(cudnnContext*, paddle::platform::Place const&, unsigned long, int, int, int, int, float, bool, int, int)
3   paddle::operators::CudnnLSTMGPUKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CudnnLSTMGPUKernel<float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::details::ComputationOpHandle::RunImpl()
9   paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync(paddle::framework::details::OpHandleBase*)
10  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp(paddle::framework::details::OpHandleBase*, std::shared_ptr<paddle::framework::BlockingQueue<unsigned long> > const&, unsigned long*)
11  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
12  std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
13  ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 1018, in lstm
    'seed': seed,
  File "./work/change.py", line 441, in _build_net
    cls_feats, last_h, last_c = fluid.layers.lstm(cls_feats, init_h, init_c, max_seq_len,n_hidden, num_layers,is_bidirec=True,seed=seed)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 401, in _build_env
    self.env.outputs = self._build_net()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 507, in main_program
    self._build_env()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 832, in load_checkpoint
    main_program=self.main_program)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 366, in init_if_necessary
    if not self.load_checkpoint():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 878, in finetune
    self.init_if_necessary()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 863, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "./work/change.py", line 766, in <module>
    run_states = cls_task.finetune_and_eval()

----------------------
Error Message Summary:
----------------------
Error: CUDNN_STATUS_EXECUTION_FAILED at (/paddle/paddle/fluid/operators/cudnn_rnn_cache.h:173)
  [operator < cudnn_lstm > error]
```
