### ISSUE TITLE
PaddleSeg预测报错

### ISSUE THREAD

**Issue by jbq123** [PaddlePaddle/Paddle#23278]
版本：Paddle1.7.0；PaddleSeg-release-v0.4.0
环境：Nvidia jetson TX2；ubuntu18.04
模型：Deeplabv3+Mobilenetv2（预训练）
问题描述：在运行pdseg/vis.py对下预训练模型进行推理时，出现如下错误：
`W0324 16:37:16.218273 8639 operator.cc:181] elementwise_add raises an exception thrust::system::system_error, parallel_for failed: too many resources requested for launch
/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
"The following exception is not an EOF exception.")
Traceback (most recent call last):
File "pdseg/vis.py", line 219, in
visualize(cfg, **args.dict)
File "pdseg/vis.py", line 134, in visualize
return_numpy=True)
File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 783, in run
six.reraise(*sys.exc_info())
File "/usr/local/lib/python3.6/dist-packages/six.py", line 696, in reraise
raise value
File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 778, in run
use_program_cache=use_program_cache)
File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 831, in _run_impl
use_program_cache=use_program_cache)
File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 905, in _run_program
fetch_var_name)
RuntimeError: parallel_for failed: too many resources requested for launch`
这个错误是程序执行到run这一步发生的，如图：
![image](https://user-images.githubusercontent.com/33571320/77744774-12503980-7055-11ea-9c2a-3cc9863faeec.png)
请问是什么原因造成的，该如何解决，谢谢！

**Comment by wzzju** [comment]
请问，您有改动哪些地方的代码吗？是直接运行原repo下的源码就报错吗？

**Comment by jbq123** [comment]
我只添加了几行打印执行时间的操作。同样的代码，在我自己电脑上是可以跑通的，放到TX2上就会产生这个错误。我又在TX2上测试了deploy/python/infer.py，还是会报相同的错误，这个推理代码在电脑上也是能够跑通的。

**Comment by wzzju** [comment]
从您的描述以及报错信息“parallel_for failed: too many resources requested for launch”可以看出应该是TX2上的硬件资源不足所致。

**Comment by jbq123** [comment]
是这样的，TX2的显卡计算能力应该是比我电脑GTX950M强的，处理器的核数也有六个，是不是我的代码没有充分地用到这些资源？我现在考虑用下inference C++API，tensorRT库。

**Comment by wzzju** [comment]
可以考虑使用inference C++API或者tensorRT库。我们的paddle代码ci上没有tx2机器，所以对于tx2可能不能完美适配。
