### ISSUE TITLE
赋值出错

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/Paddle#23324]
paddle版本：1.7.1
想对这个loc_t进行赋值，但是出现了错误，是否有办法进行赋值
代码部分：
```
    loc_t = fluid.layers.zeros([batch_size, num_priors, 4], 'float32')
    gt_box_t = []
    conf_t = []
    idx_t = []
    
    labels = []
    
    for idx in range(batch_size):
        num = gt_num[idx]
        truths = gt_box[idx, 0:num]
        labels.append(gt_class[idx, 0:num])
        
        crowd_boxes = None
        pos_threshold = 0.5
        neg_threshold = 0.4        
        loc, conf, best_truth_idx = match_tensor(pos_threshold, neg_threshold,
                  truths, priors, labels[idx], crowd_boxes,
                  loc_t, conf_t, idx_t, idx)  
                  
        loc_t[idx] = loc
```
错误如下
```
Traceback (most recent call last):
  File "tools/train.py", line 323, in <module>
    main()
  File "tools/train.py", line 116, in main
    train_fetches = model.train(feed_vars)
  File "/home/aistudio/work/PaddleDetection-release-0.2/ppdet/modeling/architectures/yolactplus.py", line 98, in train
    return self.build(feed_vars, 'train')
  File "/home/aistudio/work/PaddleDetection-release-0.2/ppdet/modeling/architectures/yolactplus.py", line 88, in build
    gt_box, gt_class, gt_segm, is_crowd, gt_num)
  File "/home/aistudio/work/PaddleDetection-release-0.2/ppdet/modeling/anchor_heads/yolact_head.py", line 683, in get_loss
    get_target_tensor(gt_box, priors, gt_class, is_crowd, gt_num, loc_data, batch_size, num_priors)
  File "/home/aistudio/work/PaddleDetection-release-0.2/ppdet/modeling/anchor_heads/yolact_head.py", line 1385, in get_target_tensor
    loc_t[idx] = loc
TypeError: 'Variable' object does not support item assignment
```

**Comment by luotao1** [comment]
loc_t是variable类型，不能直接取index来赋值，所以会报出`'Variable' object does not support item assignment`的错误。

可以用`get_tensor()`来获得loc_t对应的tensor，然后用`set`来赋值，参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/executor_cn/scope_guard_cn.html#scope-guard
```
fluid.global_scope().var(loc_t.name).get_tensor().set(xxx, fluid.CPUPlace())
```
具体来说，从scope中根据loc_t的名字，先找到variable再获得对应的tensor，最后用numpy值（xxx）进行赋值。

**Comment by zhengzhe97** [comment]
我把以上代码改成如下形式，但是loc_t并没有改变
`fluid.global_scope().var(loc_t[idx].name).get_tensor().set(fluid.global_scope().var(loc.name).get_tensor(), fluid.CUDAPlace(0)) `

**Comment by luotao1** [comment]
看下`loc.name`值是否发生了变化，可以用显示的numpy值先赋值来确认下。

**Comment by luotao1** [comment]
少加了一个np.array吧。
```
a = numpy.array(fluid.global_scope().var(loc.name).get_tensor())
fluid.global_scope().var(loc_t[idx].name).get_tensor().set(a, fluid.CUDAPlace(0))
```

**Comment by zhengzhe97** [comment]
改成上面的代码，loc_t的值还是没有改变
```
a = numpy.array(fluid.global_scope().var(loc.name).get_tensor())
fluid.global_scope().var(loc_t[idx].name).get_tensor().set(a, fluid.CUDAPlace(0))
```

**Comment by luotao1** [comment]
请问现在是有没有报错，还是值没有改变？
> loc_t[idx].name

loc_t是一个variable，还是一个variable的list呢？从最早`loc_t = fluid.layers.zeros([batch_size, num_priors, 4], 'float32')`看是一个variable，是不能用idx索引的。

**Comment by zhengzhe97** [comment]
没有报错，值也没改变

**Comment by luotao1** [comment]
请用显示的numpy值确认下。下面的demo中，loc对应的tensor是1维的。我先初始化一个值为1的一维矩阵，进行赋值，能看到打出来的data是1；然后初始化一个值为2的一维矩阵，进行赋值，能看到打出来的data是2
```
>>> loc = fluid.layers.zeros([1], 'float32')
>>> a=np.full((1),1)
>>> fluid.global_scope().var(loc.name).get_tensor().set(a, fluid.CPUPlace())
>>> print fluid.global_scope().var(loc.name).get_tensor()
	lod: {}
	dim: 1
	layout: NCHW
	dtype: int64_t
	data: [1]

>>> a=np.full((1),2)
>>> fluid.global_scope().var(loc.name).get_tensor().set(a, fluid.CPUPlace())
>>> print fluid.global_scope().var(loc.name).get_tensor()
	lod: {}
	dim: 1
	layout: NCHW
	dtype: int64_t
	data: [2]
```

**Comment by zhengzhe97** [comment]
显示的numpy是可以的，但是把一个variable的值取出来，再赋给另一个variable不可以
我试了下下面的代码，输出用py_func输出的，结果是0，loc的值没有赋给t
```
        loc, conf, best_truth_idx = match_tensor(pos_threshold, neg_threshold,
                  truths, priors, labels[idx], crowd_boxes,
                  loc_t, conf_t, idx_t, idx)  
                  
        a = np.array(fluid.global_scope().var(loc.name).get_tensor())
        t = fluid.layers.zeros([num_priors, 4], 'float32')
        fluid.global_scope().var(t.name).get_tensor().set(a, fluid.CUDAPlace(0))
        fluid.layers.py_func(func=debug_gt, x=t ,out=None)
```

**Comment by luotao1** [comment]
请一步步排查每个variable的值是否正确

我在上面的demo下补充了一个，loc3是一个新的variable，给它赋值3，然后将它的值取出来再赋值给loc，可以看到loc的值也变成3了。
```
>>> loc3 = fluid.layers.zeros([1], 'float32')
>>> b=np.full((1),3)
>>> fluid.global_scope().var(loc3.name).get_tensor().set(b, fluid.CPUPlace())
>>> print fluid.global_scope().var(loc3.name).get_tensor()
	lod: {}
	dim: 1
	layout: NCHW
	dtype: int64_t
	data: [3]
>>> c=np.array(fluid.global_scope().var(loc3.name).get_tensor())
>>> fluid.global_scope().var(loc.name).get_tensor().set(c, fluid.CPUPlace())
>>> print fluid.global_scope().var(loc.name).get_tensor()
	lod: {}
	dim: 1
	layout: NCHW
	dtype: int64_t
	data: [3]
```

**Comment by zhengzhe97** [comment]
用下面代码查看了loc是有值的，但是t还是0，对照了步骤和上面的是一样的
建图的时候，没有数据喂入，无法用print打印
```
        loc, conf, best_truth_idx = match_tensor(pos_threshold, neg_threshold,
                  truths, priors, labels[idx], crowd_boxes,
                  loc_t, conf_t, idx_t, idx)    
        fluid.layers.py_func(func=debug_gt, x=loc ,out=None)          
        a = np.array(fluid.global_scope().var(loc.name).get_tensor())
        t = fluid.layers.zeros([num_priors, 4], 'float32')
        fluid.global_scope().var(t.name).get_tensor().set(a, fluid.CPUPlace())
        fluid.layers.py_func(func=debug_gt, x=t ,out=None)
```
```
def debug_gt(x1):
    x = np.array(x1)
    print('debug',x.shape)
    print(np.sum(x))
    print(x)
```
打印结果：
```
debug (62190, 4)
0.0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
debug (62190, 4)
1456482.6
[[   9.674881      3.8183205   -11.3329935    -7.2566624 ]
 [  19.349762      1.9091603    -7.86726     -10.722397  ]
 [   4.837851      5.226562    -12.913971     -4.077633  ]
 ...
 [ -37.504845    -96.535286      0.21945505    4.2957883 ]
 [ -75.00969     -48.267643      3.6851904     0.83005303]
 [ -18.752422   -193.07057      -3.2462802     7.761524  ]]
```
