### ISSUE TITLE
conda验证环境成功，pycharm验证环境报错

### ISSUE THREAD

**Issue by yilawu** [PaddlePaddle/Paddle#23347]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu 1.7.1.
    2）CPU：i5-8265U
    3）GPU：mx150   CUDA9.0   cudnn7.3
    4）系统环境：win10

-安装方式：
conda 安装 py3.6

- 问题描述：
按照官方提示验证是否安装成功
在anaconda的环境下直接测试：
(paddle) C:\Users\xxxxxxxx>python
Python 3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 17:58:33) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid
>>> paddle.fluid.install_check.run_check()
Running Verify Paddle Program ...
W0331 17:43:25.698529  5136 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 9.0
W0331 17:43:25.752954  5136 device_context.cc:245] device: 0, cuDNN Version: 7.3.
Your Paddle works well on SINGLE GPU or CPU.
I0331 17:43:27.556147  5136 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
I0331 17:43:27.560168  5136 build_strategy.cc:365] SeqOnlyAllReduceOps:0, num_trainers:1
I0331 17:43:27.563160  5136 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I0331 17:43:27.563160  5136 parallel_executor.cc:322] Cross op memory reuse strategy is enabled, when build_strategy.memory_optimize = True or garbage collection strategy is disabled, which is not recommended
Your Paddle works well on MUTIPLE GPU or CPU.
Your Paddle is installed successfully! Let's start deep Learning with Paddle now

pycharm导入conda环境后测试：
import paddle.fluid
print(paddle.fluid.install_check.run_check())

Traceback (most recent call last):
  File "F:/pycharmPrograms/bd_day_7/day_1.py", line 1, in <module>
    import paddle.fluid
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\__init__.py", line 57, in <module>
    from . import contrib
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\contrib\__init__.py", line 27, in <module>
    from . import slim
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\contrib\slim\__init__.py", line 15, in <module>
    from .core import *
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\contrib\slim\core\__init__.py", line 15, in <module>
    from . import config
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\contrib\slim\core\config.py", line 19, in <module>
    from ..prune import *
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\contrib\slim\prune\__init__.py", line 17, in <module>
    from . import prune_strategy
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\contrib\slim\prune\prune_strategy.py", line 22, in <module>
    from scipy.optimize import leastsq
  File "D:\Anaconda3\envs\paddle\lib\site-packages\scipy\optimize\__init__.py", line 390, in <module>
    from ._minimize import *
  File "D:\Anaconda3\envs\paddle\lib\site-packages\scipy\optimize\_minimize.py", line 30, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "D:\Anaconda3\envs\paddle\lib\site-packages\scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "D:\Anaconda3\envs\paddle\lib\site-packages\scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 4, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "D:\Anaconda3\envs\paddle\lib\site-packages\scipy\sparse\linalg\__init__.py", line 116, in <module>
    from .eigen import *
  File "D:\Anaconda3\envs\paddle\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
    from .arpack import *
  File "D:\Anaconda3\envs\paddle\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
    from .arpack import *
  File "D:\Anaconda3\envs\paddle\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
    from . import _arpack
ImportError: DLL load failed: 找不到指定的程序。

**Comment by wangchaochaohu** [comment]
请问下这边环境安装过其他的pip 包吗？

**Comment by yilawu** [comment]
没有pip安装过其他的包，直接新建paddle环境，直接conda 安装paddle

**Comment by wangchaochaohu** [comment]
> 没有pip安装过其他的包，直接新建paddle环境，直接conda 安装paddle

目前情况是命令行能正常运行是吗？ 请问下Pycharm 有没有进行Anaconda的配置

**Comment by yilawu** [comment]
> > 没有pip安装过其他的包，直接新建paddle环境，直接conda 安装paddle
> 
> 目前情况是命令行能正常运行是吗？ 请问下Pycharm 有没有进行Anaconda的配置

就是导入conda的环境呀，没有别的配置

**Comment by wangchaochaohu** [comment]
我看网上有类似的教程 https://blog.csdn.net/m0_37518259/article/details/80650765 是这样操作的吗？

**Comment by yilawu** [comment]
> 我看网上有类似的教程 https://blog.csdn.net/m0_37518259/article/details/80650765 是这样操作的吗？

嗯嗯

**Comment by wangchaochaohu** [comment]
> > 我看网上有类似的教程 https://blog.csdn.net/m0_37518259/article/details/80650765 是这样操作的吗？
> 
> 嗯嗯

https://support.tibco.com/s/article/DLL-load-failed-error-when-importing-Miniconda-python-sklearn-library-from-Statistica-python-node
可以参考下这个 解决方案

**Comment by yilawu** [comment]
> > > 我看网上有类似的教程 https://blog.csdn.net/m0_37518259/article/details/80650765 是这样操作的吗？
> > 
> > 
> > 嗯嗯
> 
> https://support.tibco.com/s/article/DLL-load-failed-error-when-importing-Miniconda-python-sklearn-library-from-Statistica-python-node
> 可以参考下这个 解决方案

这好像说的是导入sklearn包的问题，跟我这个不大一样吧

**Comment by wangchaochaohu** [comment]
查阅了一些资料应该是Anaconda这个软件安装的问题 没有设置环境变量  https://bbs.pythontab.com/thread-37423-1-1.html 一些论坛里面也遇到和你相同的问题

https://www.jb51.net/article/170206.htm 这个是一个相似问题的解决方案

**Comment by yilawu** [comment]
> 查阅了一些资料应该是Anaconda这个软件安装的问题 没有设置环境变量 https://bbs.pythontab.com/thread-37423-1-1.html 一些论坛里面也遇到和你相同的问题
> 
> https://www.jb51.net/article/170206.htm 这个是一个相似问题的解决方案

嗯，pycharm的版本问题，我从2018.1换成2019.3就没有问题了，十分感谢
