### ISSUE TITLE
yolo-v3模型预训练，维度不匹配

### ISSUE THREAD

**Issue by tangbozhang** [PaddlePaddle/Paddle#23353]
aistduio 运行正常，下载本地后，进行预训练时报错，数据集是从官网下载的，没用aistudio上的数据，只用aistudio上的数据文件“label_list”、“train_list.txt”、“val_list.txt”；不加载预训练模型，直接重新训练，程序运行正常。
aistudio 网址：https://aistudio.baidu.com/aistudio/projectdetail/273746
本地运行报错内容：
2020-03-31 20:35:17,027 - train.py[line:418] - INFO: load param from pretrained model
Traceback (most recent call last):
  File "D:/codedevelop/tce/ai/paddle/ShuffleNetV2-YOLOv3/train.py", line 526, in <module>
    train()
  File "D:/codedevelop/tce/ai/paddle/ShuffleNetV2-YOLOv3/train.py", line 456, in train
    load_pretrained_params(exe, train_program)
  File "D:/codedevelop/tce/ai/paddle/ShuffleNetV2-YOLOv3/train.py", line 424, in load_pretrained_params
    predicate=if_exist)
  File "D:\softinstal\deeplearn\anaconda\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 682, in load_vars
    filename=filename)
  File "D:\softinstal\deeplearn\anaconda\envs\paddle\lib\site-packages\paddle\fluid\io.py", line 741, in load_vars
    format(orig_shape, each_var.name, new_shape))
RuntimeError: Shape not matching: the Program requires a parameter with a shape of ((78, 512, 1, 1)), while the loaded parameter (namely [ conv2d_61.w_0 ]) has a shape of  ((75, 512, 1, 1)).

**Comment by heavengate** [comment]
看着像是加载的voc数据集上的20类的数据的预训练权重，但是训练使用的是21类的数据集，请检查一下class_num设置的是否正确

**Comment by tangbozhang** [comment]
确实是由于加载类别个数不对引起的
