### ISSUE TITLE
TypeError: matmul(): incompatible function arguments. The following argument types are

### ISSUE THREAD

**Issue by Joejiong** [PaddlePaddle/Paddle#23939]
1）PaddlePaddle版本：1.7
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：Mac OS 10.14，Python版本3.7

![屏幕快照 2020-04-20 上午9 59 45](https://user-images.githubusercontent.com/18322401/79707073-dde73a80-82ed-11ea-88a8-408256ff7d97.png)

报错在return 那行进入decode那个地方，然后调用了这个dygraph.nn.Linear()
fc3 = self.fc3 = Linear(20, 400)

Traceback (most recent call last):
  File "train_vae_linear.py", line 124, in <module>
    train(model)
  File "train_vae_linear.py", line 74, in train
    sample = model.decode(sample)
  File "/Users/wujionghao/Documents/vae_paddle/paddle_vae_linear.py", line 47, in decode
    z1 = self.fc3(z)
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/nn.py", line 933, in forward
    outs = core.ops.matmul(inputs, attrs)
TypeError: matmul(): incompatible function arguments. The following argument types are supported:
    1. (ins: Dict[str, List[paddle::imperative::VarBase]], attrs: Dict[str, Variant]={}, outs: Dict[str, List[paddle::imperative::VarBase]]={}, out_nums: Dict[str, int]={}) -> Dict[str, List[paddle::imperative::VarBase]]

Invoked with: {'X': [array([[0.95415381],
       [0.2227887 ],
       [0.64918053],
       [0.49933275],
       [0.5487587 ],
       [0.33002875],
       [0.17807391],
       [0.08231865],

**Comment by bjjwwang** [comment]
方便给下 是如何用matmul这个op的呢

**Comment by zhiqiu** [comment]
hi，能发一下你的code吗？出错部分的code就可以。

**Comment by Joejiong** [comment]
谢谢拉是一下这个计算：
mu，和logvar是两个tensor一样大
def XXX(self, mu, logvar):      
        std = fluid.layers.exp(0.5*logvar)
        # eps = fluid.randn_like(std)
        eps = np.random.randn(*std.shape)
        eps = to_variable(eps)
        return mu + eps*std

**Comment by Joejiong** [comment]
现在报这个错拉。。。
File "/Users/wujionghao/Documents/vae_paddle/paddle_vae_linear.py", line 40, in reparameterize
    return mu + eps*std
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 164, in __impl__
    other_var = astype(other_var, lhs_dtype)
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 105, in astype
    "out_dtype": convert_np_dtype_to_dtype_(dtype)
  File "/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 502, in convert_np_dtype_to_dtype_
    dtype = np.dtype(np_dtype)
TypeError: data type not understood

**Comment by zhiqiu** [comment]
print(type(z))看下z是什么类型

**Comment by Joejiong** [comment]
应该搞定了，numpy转过来的时候需要指定astype('float32'),谢谢
