### ISSUE TITLE
unitest fails in CI due to not using the modified codes.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#2396]
- This RR https://github.com/PaddlePaddle/Paddle/pull/2384 does not pass the unitest in CI system. Here is the log: https://travis-ci.org/PaddlePaddle/Paddle/jobs/239968732

- 12 unitest fails, but they are all successfully executed in my local environment.
- This PR modifies the `config_parse.py`. However,  according to the following error information, the CI system uses the unmodified version of `config_parser.py`, leading to failures in unitest.

```text
Traceback (most recent call last):
  File "test_rnn_layer.py", line 159, in test_sequence_rnn_multi_input
    diff = difflib.unified_diff(parse_old_rnn().splitlines(1),
  File "test_rnn_layer.py", line 122, in parse_old_rnn
    return str(parse_network(test))
  File "/home/travis/build/PaddlePaddle/Paddle/python/paddle/v2/tests/.test_env/lib/python2.7/site-packages/paddle/trainer_config_helpers/config_parser_utils.py", line 35, in parse_network_config
    config = config_parser.parse_config(network_conf, config_arg_str)
  File "/home/travis/build/PaddlePaddle/Paddle/python/paddle/v2/tests/.test_env/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3567, in parse_config
    begin_parse(config_arg_str)
TypeError: begin_parse() takes no arguments (1 given)
```

**Comment by helinwang** [comment]
@lcy-seso In your PR, the
```python
def begin_parse():
```
does not have argument, and the error is complaining about begin_parse() takes no arguments. Did you forget to include the change of begin_parse into the PR?

**Comment by lcy-seso** [comment]
sorry, it is my mistake.
