### ISSUE TITLE
动态图能否提供一个类似pytorch dataset的数据加载方式

### ISSUE THREAD

**Issue by WenmuZhou** [PaddlePaddle/Paddle#24037]

**Comment by chenwhql** [comment]
嗯嗯，支持了，会随2.0发布，目前develop版本也可以用

**Comment by WenmuZhou** [comment]
我怎么安装develop可以试用一下

**Comment by chenwhql** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev

这里有每天最新编译的develop包，您可以选择合适的版本

但是，这个功能今天刚合入develop，最新版应该明天才会编译出来，你可以明天试试，您问的这个时机非常巧合

如果今天您一定要使用，只能自己编译了，可以参考文档试试，https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html#id1

**Comment by WenmuZhou** [comment]
好的，我明天试一下。还提个建议哈，
1. 动态图模式下print(net)希望能打印出网络结构

**Comment by chenwhql** [comment]
> 好的，我明天试一下。还提个建议哈，
> 
> 1. 动态图模式下print(net)希望能打印出网络结构

好的， 我反馈下这个需求

**Comment by WenmuZhou** [comment]
请问训练过程中如何获取学习率并打印

**Comment by WenmuZhou** [comment]
@chenwhql 有个问题，https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev
这里的我windows子系统的linux应该选择哪个呀

**Comment by WenmuZhou** [comment]
https://github.com/PaddlePaddle/Paddle/blob/80cf3c3c4d09cc77eb07c5c06a0d47d0bd55b989/python/paddle/fluid/dataloader/dataset.py
根据这个文件里的例子来，
```python
from paddle import io 
```

![image](https://user-images.githubusercontent.com/12406017/79947909-69ef9280-84a5-11ea-9d41-d222ff2f1ede.png)

**Comment by chenwhql** [comment]
确认了一下，这两天编译有点问题，安装包还是前两天develop的，可能会有1-2天延迟，您要着急的话还是编译下试试？

**Comment by WenmuZhou** [comment]
好的

**Comment by WenmuZhou** [comment]
我看今天的包已经可以了，我用下面的代码测试时，报错了
```python
#!/usr/bin/env python
# encoding: utf-8
'''
@author: zhoujun
@time: 2020/4/21 下午10:01
'''
import numpy as np
from paddle import fluid
from paddle.io import Dataset, DataLoader


class RandomDataset(Dataset):
    def __init__(self, IMAGE_SIZE=[1, 48, 512]):
        self.num_samples = 10000
        self.img_size = IMAGE_SIZE

    def __getitem__(self, idx):
        image = np.random.random(self.img_size).astype('float32')
        label = [1, 2, 3]
        return image, label

    def __len__(self):
        return self.num_samples


if __name__ == "__main__":
    place = fluid.CPUPlace()
    dataset = RandomDataset()
    dataloader = DataLoader(dataset, places=place, num_workers=6, batch_size=2, drop_last=True)
    for img, label in dataloader():
        print(img.shape, label)
        break
#!/usr/bin/env python
# encoding: utf-8
'''
@author: zhoujun
@time: 2020/4/21 下午10:01
'''
import numpy as np
from paddle import fluid
from paddle.io import Dataset, DataLoader


class RandomDataset(Dataset):
    def __init__(self, IMAGE_SIZE=[1, 48, 512]):
        self.num_samples = 10000
        self.img_size = IMAGE_SIZE

    def __getitem__(self, idx):
        image = np.random.random(self.img_size).astype('float32')
        label = [1, 2, 3]
        return image, label

    def __len__(self):
        return self.num_samples


if __name__ == "__main__":
    place = fluid.CPUPlace()
    dataset = RandomDataset()
    dataloader = DataLoader(dataset, places=place, num_workers=6, batch_size=2, drop_last=True)
    for img, label in dataloader():
        print(img.shape, label)
        break

```

![image](https://user-images.githubusercontent.com/12406017/80053229-fefa9600-854e-11ea-8e6a-0ce4fcad62d4.png)

**Comment by chenwhql** [comment]
您要在动态图模式下使用的话，加上fluid.dygraph.guard，参考这里的例子，https://github.com/PaddlePaddle/Paddle/blob/13b03e7ad6e9d555b972cca8e5e84ee0d4b61c99/python/paddle/fluid/reader.py#L100

没有guard的话，默认是静态图，需要传入feed_list

**Comment by chenwhql** [comment]
新上功能，官方文档还未公开，麻烦您耐心等待下，先参考code里面的文档

**Comment by WenmuZhou** [comment]
好了，谢谢

**Comment by WenmuZhou** [comment]
在aistudio里面运行的时候，num_workers好像不能设的超过6，会报错
```sh
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 443, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 397, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 454, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 3 workers exit unexpectedly, pids: 225, 226, 227

Traceback (most recent call last):
  File "dataset.py", line 33, in <module>
    for i,(img, label) in enumerate(dataloader()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 503, in __next__
    data = self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
```

测试代码
```python
#!/usr/bin/env python
# encoding: utf-8
'''
@author: zhoujun
@time: 2020/4/21 下午10:01
'''
import numpy as np
from paddle import fluid
from paddle.io import Dataset, DataLoader


class RandomDataset(Dataset):
    def __init__(self, IMAGE_SIZE=[1, 48, 512]):
        self.num_samples = 100000
        self.img_size = IMAGE_SIZE

    def __getitem__(self, idx):
        image = np.random.random(self.img_size).astype('float32')
        label = idx
        return image, label

    def __len__(self):
        return self.num_samples


if __name__ == "__main__":
    place = fluid.CPUPlace()
    with fluid.dygraph.guard(place):
        dataset = RandomDataset()
        dataloader = DataLoader(dataset, places=place, num_workers=3, batch_size=128, drop_last=True,shuffle=True)
        import time
        tic = time.time()
        for i,(img, label) in enumerate(dataloader()):
            if (i+1) % 100 == 0:
                print(time.time()-tic,len(img),i)
                tic = time.time()
```

**Comment by chenwhql** [comment]
感谢您的反馈，这可能也和studio平台有关，这个功能刚合入，接下来我们还会进行充分测试与调试

**Comment by heavengate** [comment]
本地试下了能跑通
![屏幕快照 2020-04-23 下午1 10 32](https://user-images.githubusercontent.com/12605721/80061441-dfba3380-8563-11ea-9af1-08b7cae5e9fd.png)
可以看下aistudio上共享内存多大，`df -h`看下`/dev/shm`下多大空间，感觉有可能是共享内存分配失败，或者可以`DataLoader(dataset, places=place, num_workers=3, batch_size=128, drop_last=True,shuffle=True, use_shared_memory=False)` 里设置`use_shared_memory=False`试下~

**Comment by WenmuZhou** [comment]
aistudio 给的是64M
![image](https://user-images.githubusercontent.com/12406017/80069021-32e7b280-8573-11ea-9a7a-ad29fc467c15.png)
设置为use_shared_memory=False之后，num_workers可以设大了，但是对速度并没有提升

**Comment by WenmuZhou** [comment]
dev包有windows的吗

**Comment by heavengate** [comment]
> aistudio 给的是64M
> ![image](https://user-images.githubusercontent.com/12406017/80069021-32e7b280-8573-11ea-9a7a-ad29fc467c15.png)
> 设置为use_shared_memory=False之后，num_workers可以设大了，但是对速度并没有提升

你的这个数据集是直接random的，并没有预处理，数据读取的计算量很小，多进程加速效果不明显，并不需要开启多进程，多进程DataLoader是针对数据读取和预处理比较复杂导致CPU瓶颈的场景，可以换个预处理复杂的数据集试下~

**Comment by WenmuZhou** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev
這個鏈接下的
cuda10-cudnn7-mkl　paddlepaddle_gpu-latest-cp37-cp37m-linux_x86_64.whl　　
之後，from paddle import io　這句話報錯了
```shTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zj/anaconda3/envs/zj/lib/python3.7/site-packages/paddle/__init__.py", line 37, in <module>
    import paddle.tensor
  File "/home/zj/anaconda3/envs/zj/lib/python3.7/site-packages/paddle/tensor/__init__.py", line 26, in <module>
    from .creation import eye  #DEFINE_ALIAS
  File "/home/zj/anaconda3/envs/zj/lib/python3.7/site-packages/paddle/tensor/creation.py", line 16, in <module>
    from ..fluid.framework import Variable, in_dygraph_mode
  File "/home/zj/anaconda3/envs/zj/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 52, in <module>
    from . import io
  File "/home/zj/anaconda3/envs/zj/lib/python3.7/site-packages/paddle/fluid/io.py", line 61, in <module>
    ] + reader.__all__ + paddle.reader.__all__
AttributeError: module 'paddle' has no attribute 'reader'

```
