### ISSUE TITLE
semantic_role_labeling demo中预测predict.sh无法跑通

### ISSUE THREAD

**Issue by April1010** [PaddlePaddle/Paddle#2404]
具体日志如下：
I0607 13:20:58.145887 32048 Util.cpp:155] commandline:  --use_gpu=0 
I0607 13:20:58.146003 32048 Util.cpp:130] Calling runInitFunctions
I0607 13:20:58.146319 32048 Util.cpp:143] Call runInitFunctions done.
[INFO 2017-06-07 13:20:58,247 networks.py:1282] The input order is [word_data, ctx_n2_data, ctx_n1_data, ctx_0_data, ctx_p1_data, ctx_p2_data, verb_data, mark_data]
[INFO 2017-06-07 13:20:58,247 networks.py:1289] The output order is [crf_dec_l]
I0607 13:20:58.289443 32048 GradientMachine.cpp:123] Loading parameters from output/pass-00001
Traceback (most recent call last):
  File "predict.py", line 193, in <module>
    main()
  File "predict.py", line 189, in main
    predict.predict(data_file, output_file)
  File "predict.py", line 107, in predict
    output = self.network.forwardTest(input)
  File "/home/disk2/lishuangjie/tools/paddle/paddle/python27-gcc482/lib/python2.7/site-packages/py_paddle/util.py", line 149, in forwardTest
    outArgs.getSlotNum())]
  File "/home/disk2/lishuangjie/tools/paddle/paddle/python27-gcc482/lib/python2.7/site-packages/py_paddle/util.py", line 89, in __arguments_to_numpy__
    if ids is not None:
UnboundLocalError: local variable 'ids' referenced before assignment

**Comment by lcy-seso** [comment]
你好~ 建议使用 paddle book 下 SRL 相关的代码。demo 目录下旧版本的 paddle 例子目前已经被移除。我在本地无法复这个错误。
