### ISSUE TITLE
AttributeError: module 'paddle.fluid.layers' has no attribute 'dynamic_decoder'

### ISSUE THREAD

**Issue by wxl1351641822** [PaddlePaddle/Paddle#24374]
```
Traceback (most recent call last):
  File "./work/seq2seq.py", line 393, in <module>
    train(opt)
  File "./work/seq2seq.py", line 322, in train
    predict(opt, opt.model_save_dir)
  File "./work/seq2seq.py", line 352, in predict
    predict_seqs = model_func(opt,inputs, is_train=False)
  File "./work/seq2seq.py", line 227, in model_func
    is_train=is_train)
  File "./work/seq2seq.py", line 185, in decoder
    decoder_output,_=layers.dynamic_decoder(
AttributeError: module 'paddle.fluid.layers' has no attribute 'dynamic_decoder'
```
paddle1.7.0,python3.7,我在另一个notebook里用是ok的，但在这个notebook里用就不行？？茫然

**Comment by wxl1351641822** [comment]
两者的区别在于一个是直接脚本运行没有函数，另一个则被我放入函数中？？？

**Comment by guoshengCS** [comment]
这个接口是`layers.dynamic_decode`，改下试下呢
