### ISSUE TITLE
Ernie INT8 test crash

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#24394]
Still updating...
Ernie INT8 Qat test crashed on develop on 6271.
The failure range:
Crashed commit id: newest develop
Crashed commit id: 9eedf05d2f30671da5332f2f8b50e2061d5a0758
Crashed commit id: 1fc6cc502ac7303c879460b050cb24d6fa3a6023
Crashed commit id: 50330c6c6d323446744ac65613ea45130e7714b7
Success commit id: 

Command:
```
OMP_NUM_THREADS=28 FLAGS_use_mkldnn=true python python/paddle/fluid/contrib/slim/tests/qat2_int8_nlp_comparison.py --qat_model=${qat_model_dir} --fp32_model=${fp32_model_dir} --infer_data=${dataset_dir}/1.8w.bs1 --labels=${dataset_dir}/label.xnli.dev --batch_size=50 --batch_num=0 --quantized_ops="fc,reshape2,transpose2,matmul" --acc_diff_threshold=0.01
```
Note if it is latest commit, change param `quantized_ops` to `ops_to_quantize`

**Comment by lidanqing-vv** [comment]
```
ERROR: test_graph_transformation (__main__.QatInt8NLPComparisonTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "python/paddle/fluid/contrib/slim/tests/qat2_int8_nlp_comparison.py", line 287, in test_graph
_transformation
    transform_to_int8=True)
  File "python/paddle/fluid/contrib/slim/tests/qat2_int8_nlp_comparison.py", line 189, in _predict
    fetch_list=fetch_targets)
  File "/home/danqing/repo/Paddle/build/python/paddle/fluid/executor.py", line 1073, in run
    six.reraise(*sys.exc_info())
  File "/home/danqing/repo/Paddle/build/python/paddle/fluid/executor.py", line 1068, in run
    return_merged=return_merged)
  File "/home/danqing/repo/Paddle/build/python/paddle/fluid/executor.py", line 1156, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/danqing/repo/Paddle/build/python/paddle/fluid/executor.py", line 1231, in _run_program
    fetch_var_name)
EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char co
nst*, int)

```

```
--------------------------------------------                                              [310/1879]
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char co
nst*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::memory::detail::MetadataCache::LoadDesc(paddle::memory::detail::MemoryBlock*)
3   paddle::memory::detail::BuddyAllocator::Free(void*)
4   void paddle::memory::legacy::Free<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&,
 void*, unsigned long)
5   paddle::memory::allocation::NaiveBestFitAllocator::FreeImpl(paddle::memory::allocation::Allocati
on*)
6   std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
7   paddle::framework::Variable::PlaceholderImpl<paddle::framework::LoDTensor>::~PlaceholderImpl()
8   paddle::framework::Scope::~Scope()
9   paddle::framework::Scope::DropKids()
10  paddle::framework::Scope::~Scope()
11  paddle::framework::ScopePool::DeleteScope(paddle::framework::Scope*)
12  paddle::framework::ScopePool::Clear()

----------------------
Error Message Summary:
----------------------
Error: Invalid CPU memory access
  [Hint: Expected desc->CheckGuards() == true, but received desc->CheckGuards():0 != true:1.] at (/h
ome/danqing/repo/Paddle/paddle/fluid/memory/detail/meta_cache.cc:35)

W0511 09:38:31.232573 87364 init.cc:219] Warning: PaddlePaddle catches a failure signal,

W0511 09:38:31.232573 87364 init.cc:219] Warning: PaddlePaddle catches a failure signal, it may not
work properly
W0511 09:38:31.232590 87364 init.cc:221] You could check whether you killed PaddlePaddle thread/proc
ess accidentally or report the case to PaddlePaddle
W0511 09:38:31.232597 87364 init.cc:224] The detail failure signal is:

W0511 09:38:31.232605 87364 init.cc:227] *** Aborted at 1589189911 (unix time) try "date -d @1589189
911" if you are using GNU date ***
W0511 09:38:31.233834 87364 init.cc:227] PC: @ 
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 2503, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 10379, in scale
    type='scale', inputs=inputs, outputs={'Out': out}, attrs=attrs)
  File "/work/ernie/model/ernie.py", line 149, in _build_model
    x=self_attn_mask, scale=10000.0, bias=-1.0, bias_after_scale=False)
  File "/work/ernie/model/ernie.py", line 99, in __init__
    input_mask)
  File "/work/ernie/xnli.py", line 74, in forward
    use_fp16=self.hparam['fp16']
  File "/work/paddle-estimator/propeller/paddle/train/trainer.py", line 79, in model_fn
    pred = model.forward(fea)
  File "/work/paddle-estimator/propeller/paddle/train/trainer.py", line 109, in build_net
    features=features, mode=mode, params=params, run_config=run_config)
  File "./quant_jc.py", line 140, in <module>
    RunMode.EVAL, params, run_config)

```

**Comment by lidanqing-vv** [comment]
@wojtuss  I saw this error before in some other model. It was key cache problem, that two ops used same key, but not sure how is this time

**Comment by wojtuss** [comment]
I have reproduced the error. It was caused by using mkldnn matmul primitives taken from cache instead of creating primitives from scratch when the batch size has changed for the last batch (the dataset has 2490 samples and if the batch size is set to 50, the last batch has only 40 samples).

A fix is submitted in the PR https://github.com/PaddlePaddle/Paddle/pull/24408.

**Comment by lidanqing-vv** [comment]
Solved.
