### ISSUE TITLE
paddle v2 api gpu can not use dropout_layer.

### ISSUE THREAD

**Issue by phonism** [PaddlePaddle/Paddle#2450]
here is my code
```
dropout_layer = paddle.networks.dropout_layer(input=concat_layer, dropout_rate=0.5)
# fc and output layer
output = paddle.layer.fc(input=dropout_layer, size=class_dim, act=paddle.activation.Sigmoid())
```
dropout_layer work for cpu, but gpu not. it will get the follow error.
```
Traceback (most recent call last):
  File "model.py", line 188, in <module>
    train_cnn_model(num_pass=num_pass)
  File "model.py", line 108, in train_cnn_model
    [cost, output, label] = convolution_net(dict_dim, class_dim=class_dim)
  File "model.py", line 42, in convolution_net
    dropout_layer = paddle.networks.dropout_layer(input=concat_layer, dropout_rate=0.5)
AttributeError: 'module' object has no attribute 'dropout_layer'
```

**Comment by lcy-seso** [comment]
This layer is moved from `paddle.network` into `paddle.layer`.

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L5572
http://www.paddlepaddle.org/develop/doc/api/v2/config/layer.html#dropout

**Comment by phonism** [comment]
@lcy-seso thank you.
