### ISSUE TITLE
AssertionError: Not compiled with CUDA

### ISSUE THREAD

**Issue by NULL-JC** [PaddlePaddle/Paddle#24581]
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle 1.7.1 paddleHub 1.6,2
    4）系统环境：win10 python3.7 
- 训练信息
    1）单机，单卡

Traceback (most recent call last):
  File "F:/学习资料/计算机/大二/下/人工智能/Text_Analysis/loadModule.py", line 70, in <module>
    metrics_choices=["f1"])
  File "E:\software\program\Python37\lib\site-packages\paddlehub\finetune\task\classifier_task.py", line 179, in __init__
    metrics_choices=metrics_choices)
  File "E:\software\program\Python37\lib\site-packages\paddlehub\finetune\task\classifier_task.py", line 49, in __init__
    metrics_choices=metrics_choices)
  File "E:\software\program\Python37\lib\site-packages\paddlehub\finetune\task\base_task.py", line 311, in __init__
    self.place = self.places[0]
  File "E:\software\program\Python37\lib\site-packages\paddlehub\finetune\task\base_task.py", line 450, in places
    _places = fluid.framework.cuda_places()
  File "E:\software\program\Python37\lib\site-packages\paddle\fluid\framework.py", line 314, in cuda_places
    "Not compiled with CUDA"
AssertionError: Not compiled with CUDA

**Comment by iclementine** [comment]
出现这个错误是因为所安装的 paddle 不支持 cuda.

可以参考
https://www.paddlepaddle.org.cn/install/quick
选择安装支持 gpu 的版本。
