### ISSUE TITLE
import paddlehub报错ImportError: /lib64/libXext.so.6: undefined symbol: _XGetRequest

### ISSUE THREAD

**Issue by AltenLi** [PaddlePaddle/Paddle#24640]
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：1.7.2 gpu
    2）CPU：
    3）GPU：P4，CUDA 9 和CUDNN 7.3
    4）系统环境：Python2.7.14和3.6.5
- 安装方式信息：
1）pip安装
- 复现信息：
安装了paddlepaddle和paddlehub后，import paddlehub报错
Traceback (most recent call last):
  File "run_ernie_sequence_labeling.py", line 35, in <module>
    import creator
  File "/home/work/liqian11/entity_tagging/model/creator.py", line 31, in <module>
    from models.representation.ernie import ernie_encoder, ernie_pyreader
  File "../shared_modules/models/representation/ernie.py", line 26, in <module>
    import paddlehub as hub
  File "/home/work/.pyenv/versions/lq2/lib/python2.7/site-packages/paddlehub/__init__.py", line 25, in <module>
    from . import module
  File "/home/work/.pyenv/versions/lq2/lib/python2.7/site-packages/paddlehub/module/__init__.py", line 16, in <module>
    from . import module
  File "/home/work/.pyenv/versions/lq2/lib/python2.7/site-packages/paddlehub/module/module.py", line 31, in <module>
    from paddlehub.common import utils
  File "/home/work/.pyenv/versions/lq2/lib/python2.7/site-packages/paddlehub/common/__init__.py", line 16, in <module>
    from . import utils
  File "/home/work/.pyenv/versions/lq2/lib/python2.7/site-packages/paddlehub/common/utils.py", line 30, in <module>
    import cv2
  File "/home/work/.pyenv/versions/lq2/lib/python2.7/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: /lib64/libXext.so.6: undefined symbol: _XGetRequest

**Comment by 1024er** [comment]
@nepeplwu 麻烦泽武看一下

**Comment by Steffy-zxf** [comment]
@AltenLi  你好！从错误提示来看：
>  /lib64/libXext.so.6: undefined symbol: _XGetRequest

应该是你的Linux环境有问题，可以参考下面的解答：https://community.cadence.com/cadence_technology_forums/f/pcb-design/37052/linux-spb17-0-startup-problem
