### ISSUE TITLE
aistudio训练报[operator < read > error]：Blocking queue is killed because the data reader raises an exception

### ISSUE THREAD

**Issue by KK-Jiang** [PaddlePaddle/Paddle#24739]
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.0
    2）系统环境｜GPU：aistudio上，v100
- 训练信息
    1）单卡
    2）16G
    3）[operator < read > error]

- 复现信息：使用官方PaddleDetection-release-0.3，配置文件cascade_mask_rcnn_dcnv2_se154_vd_fpn_gn_s1x.yml，修改了class_num, batch_size, 数据路径，lr策略等基础信息，然后直接训练模型，就出错。

- 问题描述：
err log如下，我做如下尝试都没有解决问题：我尝试了将work_num逐渐减小，非0的时候仍然报错，为0的时候，放十几个小时都显示正常log然后不动；将DataLoader.from_generator的capacity改小；use_double_buffer改为False；iterable改为True（默认False）；以上都无效:

> 2020-05-26 11:24:35,963-INFO: places would be ommited when DataLoader is not iterable
2020-05-26 11:24:39,118-WARNING: recv endsignal from outq with errmsg[consumer[consumer-c14-0] exits for reason[producer[producer-c14] failed with error: cannot reshape array of size 1 into shape (2)]]
2020-05-26 11:24:39,119-WARNING: recv endsignal from outq with errmsg[consumer[consumer-c14-1] exits for reason[consumer[consumer-c14-0] exits for reason[producer[producer-c14] failed with error: cannot reshape array of size 1 into shape (2)]]]
2020-05-26 11:24:39,119-WARNING: recv endsignal from outq with errmsg[consumer[consumer-c14-2] exits for reason[consumer[consumer-c14-1] exits for reason[consumer[consumer-c14-0] exits for reason[producer[producer-c14] failed with error: cannot reshape array of size 1 into shape (2)]]]]
2020-05-26 11:24:39,119-WARNING: recv endsignal from outq with errmsg[consumer[consumer-c14-3] exits for reason[consumer[consumer-c14-2] exits for reason[consumer[consumer-c14-1] exits for reason[consumer[consumer-c14-0] exits for reason[producer[producer-c14] failed with error: cannot reshape array of size 1 into shape (2)]]]]]
2020-05-26 11:24:39,119-WARNING: recv endsignal from outq with errmsg[consumer[consumer-c14-4] exits for reason[consumer[consumer-c14-3] exits for reason[consumer[consumer-c14-2] exits for reason[consumer[consumer-c14-1] exits for reason[consumer[consumer-c14-0] exits for reason[producer[producer-c14] failed with error: cannot reshape array of size 1 into shape (2)]]]]]]
2020-05-26 11:24:39,119-WARNING: recv endsignal from outq with errmsg[consumer[consumer-c14-5] exits for reason[consumer[consumer-c14-4] exits for reason[consumer[consumer-c14-3] exits for reason[consumer[consumer-c14-2] exits for reason[consumer[consumer-c14-1] exits for reason[consumer[consumer-c14-0] exits for reason[producer[producer-c14] failed with error: cannot reshape array of size 1 into shape (2)]]]]]]]
2020-05-26 11:24:39,119-WARNING: recv endsignal from outq with errmsg[consumer[consumer-c14-6] exits for reason[consumer[consumer-c14-5] exits for reason[consumer[consumer-c14-4] exits for reason[consumer[consumer-c14-3] exits for reason[consumer[consumer-c14-2] exits for reason[consumer[consumer-c14-1] exits for reason[consumer[consumer-c14-0] exits for reason[producer[producer-c14] failed with error: cannot reshape array of size 1 into shape (2)]]]]]]]]
2020-05-26 11:24:39,120-WARNING: recv endsignal from outq with errmsg[consumer[consumer-c14-7] exits for reason[consumer[consumer-c14-6] exits for reason[consumer[consumer-c14-5] exits for reason[consumer[consumer-c14-4] exits for reason[consumer[consumer-c14-3] exits for reason[consumer[consumer-c14-2] exits for reason[consumer[consumer-c14-1] exits for reason[consumer[consumer-c14-0] exits for reason[producer[producer-c14] failed with error: cannot reshape array of size 1 into shape (2)]]]]]]]]]
2020-05-26 11:24:39,120-WARNING: Your reader has raised an exception!
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1156, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1136, in __thread_main__
    for tensors in self._tensor_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1206, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 505, in __reader_creator__
    for item in reader():
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/data/reader.py", line 421, in _reader
    reader.reset()
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/data/parallel_map.py", line 259, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
loading annotations into memory...
Done (t=12.03s)
creating index...
index created!
Traceback (most recent call last):
  File "PaddleDetection-release-0.3/tools/train.py", line 366, in <module>
    main()
  File "PaddleDetection-release-0.3/tools/train.py", line 239, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1078, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 976, in __init__
    self._init_non_iterable()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 608, in from_generator
    iterable, return_list, drop_last)
  File "/home/aistudio/PaddleDetection-release-0.3/ppdet/modeling/architectures/cascade_mask_rcnn.py", line 426, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "PaddleDetection-release-0.3/tools/train.py", line 112, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "PaddleDetection-release-0.3/tools/train.py", line 366, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by jerrywgz** [comment]
从报错信息看是数据处理的地方出错：cannot reshape array of size 1 into shape (2)
可以发下配置文件吗，我们复现下，另外不建议修改dataloader相关配置，在检测库下是经过多个模型验证过的

**Comment by KK-Jiang** [comment]
architecture: CascadeMaskRCNN
max_iters: 300000
snapshot_iter: 10
use_gpu: true
log_iter: 20
log_smooth_window: 20
save_dir: output
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/SENet154_vd_caffe_pretrained.tar
weights: output/cascade_mask_rcnn_dcn_se154_vd_fpn_gn_s1x/model_final
metric: COCO
num_classes: 34

CascadeMaskRCNN:
  backbone: SENet
  fpn: FPN
  rpn_head: FPNRPNHead
  roi_extractor: FPNRoIAlign
  bbox_head: CascadeBBoxHead
  bbox_assigner: CascadeBBoxAssigner
  mask_assigner: MaskAssigner
  mask_head: MaskHead

SENet:
  depth: 152
  feature_maps: [2, 3, 4, 5]
  freeze_at: 2
  group_width: 4
  groups: 64
  norm_type: bn
  freeze_norm: True
  variant: d
  dcn_v2_stages: [3, 4, 5]
  std_senet: True

FPN:
  max_level: 6
  min_level: 2
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125, 0.25]
  freeze_norm: False
  norm_type: gn

FPNRPNHead:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  max_level: 6
  min_level: 2
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000

FPNRoIAlign:
  canconical_level: 4
  canonical_size: 224
  max_level: 5
  min_level: 2
  box_resolution: 7
  sampling_ratio: 2
  mask_resolution: 14

MaskHead:
  dilation: 1
  conv_dim: 256
  num_convs: 4
  resolution: 28
  norm_type: gn

CascadeBBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [10, 20, 30]
  bg_thresh_hi: [0.5, 0.6, 0.7]
  bg_thresh_lo: [0.0, 0.0, 0.0]
  fg_fraction: 0.25
  fg_thresh: [0.5, 0.6, 0.7]

MaskAssigner:
  resolution: 28

CascadeBBoxHead:
  head: CascadeXConvNormHead
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05

CascadeXConvNormHead:
  norm_type: gn

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [150000, 240000, 280000]
  - !LinearWarmup
    start_factor: 0.01
    steps: 2000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

TrainReader:
  batch_size: 2
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_mask']
  dataset:
    !COCODataSet
    dataset_dir: data/
    image_dir: train/image
    anno_path: train/train.json
    with_background: False
  sample_transforms:
  - !DecodeImage
    to_rgb: false
  - !RandomDistort
    is_order: False
  - !RandomFlipImage
    is_mask_flip: true
    is_normalized: false
    prob: 0.5
  - !NormalizeImage
    is_channel_first: false
    is_scale: False
    mean:
    - 125.95
    - 142.83
    - 156.08
    std:
    - 17.23
    - 15.18
    - 13.11
  - !ResizeImage
    interp: 1
    target_size:
    - 416
    - 448
    - 480
    - 512
    - 544
    - 576
    - 608
    - 640
    - 672
    - 704
    - 736
    - 768
    - 800
    - 832
    - 864
    - 896
    - 928
    - 960
    - 992
    - 1024
    max_size: 1200
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  worker_num: 8
  shuffle: true

EvalReader:
  batch_size: 2
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !COCODataSet
    dataset_dir: data/
    anno_path: train/valid.json
    image_dir: train/image
    with_background: False
  sample_transforms:
  - !DecodeImage
    to_rgb: False
  - !NormalizeImage
    is_channel_first: false
    is_scale: False
    mean:
    - 125.95
    - 142.83
    - 156.08
    std:
    - 17.23
    - 15.18
    - 13.11
  - !ResizeImage
    interp: 1
    target_size:
    - 800
    max_size: 1200
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  worker_num: 8
  drop_empty: false

TestReader:
  batch_size: 1
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: train/valid.json
    with_background: False
  sample_transforms:
  - !DecodeImage
    to_rgb: False
  - !NormalizeImage
    is_channel_first: false
    is_scale: False
    mean:
    - 125.95
    - 142.83
    - 156.08
    std:
    - 17.23
    - 15.18
    - 13.11
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
  worker_num: 1

**Comment by KK-Jiang** [comment]
> 从报错信息看是数据处理的地方出错：cannot reshape array of size 1 into shape (2)
> 可以发下配置文件吗，我们复现下，另外不建议修改dataloader相关配置，在检测库下是经过多个模型验证过的

配置已经发了，我也想过数据问题，但是同一个数据跑yolov3就没问题，所以很疑惑

**Comment by jerrywgz** [comment]
看到with_background: False 你使用的是rcnn系列模型，这里的with_background应该是为True同时类别数需要增加背景类

**Comment by KK-Jiang** [comment]
> 看到with_background: False 你使用的是rcnn系列模型，这里的with_background应该是为True同时类别数需要增加背景类

测了一下，还是报错。我查了以下数据，都是正常的jpg格式，数据大小1200*1200。郁闷中

**Comment by jerrywgz** [comment]
我在v100上测试了下这个模型会出现显存不足的情况，可以尝试使用一个较小的模型

**Comment by ZihuaZhao** [comment]
您好！我在使用ERNIE在GLUE dataset上训练时遇到了同样的问题。
我在8张GTX1080Ti上运行，每张卡内存10G，使用python3.6，CUDA10.0，torch1.2.0，paddle版本1.8.1。
我在git了项目并且下载预训练模型ernie2.0-en后，训练报错：
training: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "./demo/finetune_classifier_dygraph_distributed.py", line 113, in <module>
    for step, d in enumerate(tqdm(train_ds.start(place), desc='training')):
  File "/home/zhaozh/miniconda3/envs/learn/lib/python3.6/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/home/zhaozh/miniconda3/envs/learn/lib/python3.6/site-packages/paddle/fluid/reader.py", line 804, in __next__
    return self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
模型参数没有做改动，运行命令用的也是github上提供的：
python -m paddle.distributed.launch \
./demo/finetune_classifier_dygraph_distributed.py \
    --data_dir ./data/cola \
    --max_steps 10000 \
    --from_pretrained ernie2.0-en
只对路径做了修改。

**Comment by KK-Jiang** [comment]
> 我在v100上测试了下这个模型会出现显存不足的情况，可以尝试使用一个较小的模型

也就是你没有这个问题对吗？看官方介绍，这个模型指标很好，你有什么办法吗

**Comment by DammyZ** [comment]
@jerrywgz我也遇到相似的问题在使用yolo3时，看报错是样本标记框时候的错吗？可是之前用相同方式使用LableImg标记别的样本也没有遇到过这样的错，麻烦您帮忙看下
```
2020-06-02 17:24:54,327-INFO: fail to map op [RandomFlipImage_66565e] with error: RandomFlipImage_66565e: invalid box, x2 should be greater than x1 and stack:
Traceback (most recent call last):
  File "PaddleDetection/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "PaddleDetection/ppdet/data/transform/operators.py", line 428, in __call__
    raise BboxError(m)
ppdet.data.transform.operators.BboxError: RandomFlipImage_66565e: invalid box, x2 should be greater than x1

Traceback (most recent call last):
  File "PaddleDetection/ppdet/data/transform/operators.py", line 428, in __call__
    raise BboxError(m)

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
    data = f(data, ctx)
  File "PaddleDetection/ppdet/data/transform/operators.py", line 428, in __call__
    raise BboxError(m)
  File "PaddleDetection/ppdet/data/transform/operators.py", line 428, in __call__

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
2020-06-02 17:25:48,497-WARNING: Your reader has raised an exception!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    six.reraise(*sys.exc_info())
  File "venv_test/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
2020-06-02 17:25:48,497-WARNING: Your reader has raised an exception!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    six.reraise(*sys.exc_info())
  File "/home/jxrtest/venv_test/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
    for tensors in self._tensor_reader():
    for slots in paddle_reader():
    for item in reader():
  File "PaddleDetection/ppdet/data/parallel_map.py", line 259, in reset

  "The following exception is not an EOF exception.")
    six.reraise(*sys.exc_info())
  File "/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
    for tensors in self._tensor_reader():
    for slots in paddle_reader():
    for item in reader():
  File "PaddleDetection/ppdet/data/parallel_map.py", line 259, in reset

  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 334, in <module>
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
    return_merged=return_merged)
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------

    raise BboxError(m)
  File "PaddleDetection/ppdet/data/transform/operators.py", line 428, in __call__

libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
2020-06-02 17:25:48,497-WARNING: Your reader has raised an exception!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
    six.reraise(*sys.exc_info())
  File "/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
    for tensors in self._tensor_reader():
    for slots in paddle_reader():
    for item in reader():
  File "PaddleDetection/ppdet/data/parallel_map.py", line 259, in reset

  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 334, in <module>
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
    return_merged=return_merged)
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
    attrs={'drop_last': self._drop_last})
  File "/lib/python3.6/site-packages/paddle/fluid/reader.py", line 976, in __init__
    self._init_non_iterable()
  File "lib/python3.6/site-packages/paddle/fluid/reader.py", line 608, in from_generator
    iterable, return_list, drop_last)
  File "PaddleDetection/ppdet/modeling/architectures/yolov3.py", line 152, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 117, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 334, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]
```

**Comment by Ethan1999liu** [comment]
> 我在v100上测试了下这个模型会出现显存不足的情况，可以尝试使用一个较小的模型

我也存在这个问题，和mask-rcnn有关的模型都会这样，换成cascade-rcnn就好了，很奇怪
