### ISSUE TITLE
【有完整复现问题代码示例】PreconditionNotMetError: Maybe the Input variable Y(fc_0.w_0) has not been initialized

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#24832]
```
import numpy as np
from paddle import fluid


def get_sentence_reduce_vector(enc_out, mask):
    fp32_mask = fluid.layers.cast(mask, 'float32')
    fp32_mask_expand = fluid.layers.expand_as(fp32_mask, enc_out)
    text_vector = fp32_mask_expand * enc_out

    text_mean_vector = fluid.layers.reduce_sum(text_vector, dim=1) \
                            / fluid.layers.reduce_sum(fp32_mask_expand, dim=1)
    print(text_mean_vector)
    point = fluid.layers.fc(text_mean_vector, 1)
    return text_mean_vector


mp, sp = fluid.Program(), fluid.Program()
with fluid.program_guard(mp, sp):
    enc_out = fluid.layers.data("enc_out", shape=(-1,512, 2), dtype='float32')
    input_mask = fluid.layers.data("input_mask", shape=(-1,512, 1), dtype='int64')
    text_b_vector = get_sentence_reduce_vector(enc_out, input_mask)
    

place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(sp)

np_enc_out = np.random.randint(0, 10, [2, 6, 2]).astype('float32')

print(np_enc_out)

np_sentence_ids = np.array(
    [[0, 0, 0, 1, 1, 0],
     [0, 0, 1, 1, 1, 1]]
)

np_input_mask = np.array(
    [
        [1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1]
    ]
)


np_sentence_ids = np.expand_dims(np_sentence_ids, -1)
np_input_mask = np.expand_dims(np_input_mask, -1)

z_np = exe.run(mp, 
               feed={enc_out.name:np_enc_out,
                     sentence_ids.name: np_sentence_ids, 
                     input_mask.name: np_input_mask},
               fetch_list=[text_b_vector])
print(z_np)
```

```
name: "tmp_1"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: 0
      dims: 0
    }
    lod_level: 0
  }
}

---------------------------------------------------------------------------
EnforceNotMet                             Traceback (most recent call last)
<ipython-input-1-2576ceb37024> in <module>
     19     enc_out = fluid.layers.data("enc_out", shape=(-1,512, 2), dtype='float32')
     20     input_mask = fluid.layers.data("input_mask", shape=(-1,512, 1), dtype='int64')
---> 21     text_b_vector = get_sentence_reduce_vector(enc_out, input_mask)
     22 
     23 

<ipython-input-1-2576ceb37024> in get_sentence_reduce_vector(enc_out, mask)
     11                             / fluid.layers.reduce_sum(fp32_mask_expand, dim=1)
     12     print(text_mean_vector)
---> 13     point = fluid.layers.fc(text_mean_vector, 1)
     14     return text_mean_vector
     15 

~/anaconda3/lib/python3.7/site-packages/paddle/fluid/layers/nn.py in fc(input, size, num_flatten_dims, param_attr, bias_attr, act, name)
    382             outputs={"Out": tmp},
    383             attrs={"x_num_col_dims": num_flatten_dims,
--> 384                    "y_num_col_dims": 1})
    385         mul_results.append(tmp)
    386 

~/anaconda3/lib/python3.7/site-packages/paddle/fluid/layer_helper.py in append_op(self, *args, **kwargs)
     41 
     42     def append_op(self, *args, **kwargs):
---> 43         return self.main_program.current_block().append_op(*args, **kwargs)
     44 
     45     def multiple_input(self, input_param_name='input'):

~/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py in append_op(self, *args, **kwargs)
   2486                 inputs=kwargs.get("inputs", None),
   2487                 outputs=kwargs.get("outputs", None),
-> 2488                 attrs=kwargs.get("attrs", None))
   2489 
   2490             self.ops.append(op)

~/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py in __init__(***failed resolving arguments***)
   1869             if self._has_kernel(type):
   1870                 self.desc.infer_var_type(self.block.desc)
-> 1871                 self.desc.infer_shape(self.block.desc)
   1872 
   1873     def _has_kernel(self, op_type):

EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > paddle::platform::GetTraceBackString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int)
1   paddle::operators::MulOp::InferShape(paddle::framework::InferShapeContext*) const
2   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const
3   void pybind11::cpp_function::initialize<pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void&&, paddle::framework::OpDesc (*)(paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::operator()(pybind11::detail::function_call&) const
4   pybind11::cpp_function::dispatcher(_object*, _object*, _object*)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 384, in fc
    "y_num_col_dims": 1})
  File "<ipython-input-1-2576ceb37024>", line 13, in get_sentence_reduce_vector
    point = fluid.layers.fc(text_mean_vector, 1)
  File "<ipython-input-1-2576ceb37024>", line 21, in <module>
    text_b_vector = get_sentence_reduce_vector(enc_out, input_mask)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3248, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3057, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2880, in _run_cell
    return runner(coro)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2854, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 542, in execute_request
    user_expressions, allow_stdin,
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 787, in inner
    self.run()
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/liujiaxiang/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)

----------------------
Error Message Summary:
----------------------
PreconditionNotMetError: Maybe the Input variable Y(fc_0.w_0) has not been initialized. You may need to confirm if you put exe.run(startup_program) after optimizer.minimize function.
  [Hint: Expected framework::product(y_dims) != 0, but received framework::product(y_dims):0 == 0:0.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/mul_op.cc:56)
  [operator < mul > error]
```

**Comment by phlrain** [comment]
feed 的时候，多了一个组 sentence_ids.name: np_sentence_ids 参数，删除了能正确运行

**Comment by OleNet** [comment]
升级解决
