### ISSUE TITLE
raise NotImplementedError on dygraph.Sequential 

### ISSUE THREAD

**Issue by zhao181** [PaddlePaddle/Paddle#24885]
下面是我用dygraph实现的resnet网络,执行一个forward通不过。
有哪位能帮我解答一下吗?!

报错信息如下:
`C:\ProgramData\Anaconda3\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 39752 --file A:/semantic/furnace/dataAnalysis/netstem/resblock.py
pydev debugger: process 10948 is connecting

Connected to pydev debugger (build 191.6605.12)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "A:/semantic/furnace/dataAnalysis/netstem/resblock.py", line 113, in <module>
    output=model(input)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "A:/semantic/furnace/dataAnalysis/netstem/resblock.py", line 78, in forward
    output = self.layer1(output)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\container.py", line 87, in forward
    input = layer(input)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 304, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 316, in forward
    raise NotImplementedError
NotImplementedError
W0603 20:07:06.992059 18348 device_context.cc:237] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 9.0
W0603 20:07:06.992059 18348 device_context.cc:245] device: 0, cuDNN Version: 7.4.

Process finished with exit code 1
`

代码如下:
`
import numpy as np
from paddle import fluid
from paddle.fluid import dygraph
def conv_bn(inplanes,outplanes,act="relu",kernel_size=3,stride=1):
    conv_bn=dygraph.Sequential(
        dygraph.Conv2D(inplanes, outplanes, filter_size=kernel_size,
                       stride=stride,padding=kernel_size//2,bias_attr=False),
        dygraph.BatchNorm(outplanes, act=act), )
    return conv_bn

class BasicBlock_Paddle(dygraph.Layer):
    expansion=1
    def __init__(self,inplanes, planes, stride=1):
        super(BasicBlock_Paddle,self).__init__()
        self.downsample=None
        if(stride!=1 or inplanes!=planes):
            self.downsample=conv_bn(inplanes,planes,act=None,kernel_size=1,stride=stride)
        self.conv1_bn=conv_bn(inplanes,planes,act="relu",kernel_size=3,stride=stride)
        self.conv2_bn = conv_bn(planes, planes, act=None, kernel_size=3, stride=1)
    def foward(self,input):
        output=self.conv1_bn(input)
        output = self.conv2_bn(output)
        main_branch=input
        if(self.downsample is not None):
            main_branch=self.downsample(input)
        output=fluid.layers.relu(main_branch+output)
        return output

class Bottleneck_Paddle(dygraph.Layer):
    expansion = 4
    def __init__(self, inplanes, planes, stride=1):
        super(Bottleneck_Paddle, self).__init__()
        self.downsample = None
        outplanes=planes*Bottleneck_Paddle.expansion
        if (stride != 1 or inplanes != planes):
            self.downsample =conv_bn(inplanes,outplanes,kernel_size=1,stride=stride)
        self.conv1_bn = conv_bn(inplanes,outplanes,kernel_size=1,stride=1)
        self.conv2_bn= conv_bn(inplanes, outplanes, kernel_size=3, stride=stride)
        self.conv3_bn = conv_bn(inplanes, outplanes, act=None,kernel_size=1, stride=1)
    def forward(self,input):
        output=self.conv1_bn(input)
        output = self.conv2_bn(output)
        output = self.conv3_bn(output)
        main_branch=input
        if(self.downsample is not None):
            main_branch = self.downsample(input)
        return fluid.layers.relu(main_branch+output)

def _make_layer(block,inplanes, planes,nblocks,stride=1):
    outplane = planes *block.expansion
    inplaneList=[inplanes]+[outplane for idx in range(1,nblocks)]
    strideList=[stride]+[1 for idx in range(1,nblocks)]
    LayerList=[block(inplaneList[idx], planes, strideList[idx]) for idx in range(nblocks)]
    return dygraph.Sequential(*LayerList)

class ResNetStem(dygraph.Layer):
    def __init__(self, block, layers):
        super(ResNetStem, self).__init__()
        self.stem=conv_bn(3,64,act="relu",kernel_size=7,stride=2)
        self.maxpool = fluid.Pool2D(pool_size=3,pool_stride=2,pool_padding=1,)
        planes=[64,128,256,512]
        inplanes =[64]+ [block.expansion*planes[k] for k in range(1,4)]
        self.layer1= _make_layer(block,inplanes[0],planes[0], layers[0])
        self.layer2 = _make_layer(block,inplanes[1],planes[1], layers[1], stride=2)
        self.layer3 = _make_layer(block,inplanes[2],planes[2], layers[2], stride=2)
        self.layer4 = _make_layer(block,inplanes[3],planes[3], layers[3], stride=2)

    def forward(self, input):
        output=self.stem(input)
        output = self.maxpool(output)
        output = self.layer1(output)
        output = self.layer2(output)
        output = self.layer3(output)
        output = self.layer4(output)
        return output

def resnet18(num_classes, pretrained=False, **kwargs):
    model = ResNetStem(BasicBlock_Paddle, [2, 2, 2, 2], **kwargs)
    return model

def resnet34(num_classes, pretrained=False, **kwargs):
    model = ResNetStem(BasicBlock_Paddle, [3, 4, 6, 3], **kwargs)
    return model

def resnet50(num_classes, pretrained=False, **kwargs):
    model = ResNetStem( Bottleneck_Paddle, [3, 4, 6, 3], **kwargs)
    return model

def resnet101(num_classes, pretrained=False, **kwargs):
    model = ResNetStem(Bottleneck_Paddle, [3, 4, 23, 3], **kwargs)
    return model

def resnet152(num_classes, pretrained=False, **kwargs):
    model = ResNetStem(num_classes, Bottleneck_Paddle, [3, 8, 36, 3], **kwargs)
    return model

with fluid.dygraph.guard():
    model=resnet18(1000)
    input=np.random.uniform(-1.0,1.0,size=(2,3,224,224))
    input=dygraph.to_variable(input.astype(np.float32))
    output=model(input)
    print("==================")`

非常感谢  期待您的回复

**Comment by zhao181** [comment]
解决了  我把forward写错成foward了。
