### ISSUE TITLE
Training in multiprocessing.Process falied to run using tkinter EXE in 32-bit system

### ISSUE THREAD

**Issue by brianyu1986** [PaddlePaddle/Paddle#24919]
I try to write a Program using multiprocessing and tkinter(GUI), pack by pyinstaller for a 32-bit system.
However, it seems that doesn't work will.

Here is the code:

```
import os
import shutil
import time
import datetime
from tkinter import *
from tkinter.filedialog import askdirectory as adir
import multiprocessing as mp
from tkinter import messagebox



def copyfile():
    filename = "test.txt"
    src = "C:\\MCC\\" + filename
    dst = "C:\\MCC\\testfolder\\" + filename
    # print(src,",",dst)

    while True:
        shutil.copy(src, dst)
        time.sleep(60)


class UI():
    Q = mp.Queue()

    def main(self):
        UI = Tk()
        UI.title('Copy File')
        width = 500
        hight = 220
        ws = UI.winfo_screenwidth()
        hs = UI.winfo_screenheight()
        x = (ws / 2) - (width / 2)
        y = (hs / 2) - (hight / 2)
        UI.geometry('%dx%d+%d+%d' % (width, hight, x, y))

        default_SRCPath = 'C:/MCC/'
        default_DSTPath = 'Please Change...'

        path1 = StringVar()
        path1.set(default_SRCPath)
        path2 = StringVar()
        path2.set(default_DSTPath)

        Label(UI, text="MCC/KYE Source Path :").grid(row=0, column=0, padx=15, pady=15)
        Message(UI, textvariable=path1, bg="white", width=250).grid(row=0, column=1, padx=15, pady=15, sticky=W + E)
        Button(UI, text='Change Path', command=lambda: change_path(default_SRCPath, path1)).grid(row=0, column=2,
                                                                                                 padx=5,
                                                                                                 pady=5)

        Label(UI, text="MCC/KYE Target Path :").grid(row=1, column=0, padx=15, pady=15)
        Message(UI, textvariable=path2, bg="white", width=250).grid(row=1, column=1, padx=15, pady=15, sticky=W + E)
        Button(UI, text='Change Path', command=lambda: change_path(default_DSTPath, path2)).grid(row=1, column=2,
                                                                                                 padx=5,
                                                                                                 pady=5)

        var1 = IntVar()
        Checkbutton(UI, text="MCC", variable=var1).grid(row=2, column=0, padx=15, sticky=W + E)
        var2 = IntVar()
        Checkbutton(UI, text="KYE", variable=var2).grid(row=2, column=1, padx=15, sticky=W + E)

        self.startflag = 0
        self.startB = Button(UI, text='Start', command=lambda: self.start(var1, var2, path1, path2))
        self.startB.grid(row=3, column=0, padx=15, pady=15)
        Button(UI, text='Stop', command=lambda: self.stop()).grid(row=3, column=1, padx=15, pady=15)
        UI.mainloop()

    def start(self, var1, var2, path1, path2):
        mcc = var1.get()
        kye = var2.get()
        src = path1.get()
        dst = path2.get()
        self.startB.config(relief=SUNKEN)
        if dst == 'Please Change...':
            messagebox.showwarning('提示', 'Please select Target Folder!')
        else:
            if dst == src:
                messagebox.showwarning('提示', 'Source Folder and Target Folder could not be the Same!')
            else:
                if self.startflag == 0:
                    if mcc == kye:
                        messagebox.showwarning('提示', 'Please select only one option!')
                        self.startB.config(relief=RAISED)
                    else:
                        self.startflag = 1

                        if mcc == 1:
                            print("MCC mode!")
                            fileCopy = mp.Process(target=mccMode, args=[src, dst, self.Q])
                            fileCopy.start()
                        else:
                            print("KYE mode!")
                            fileCopy = mp.Process(target=kyeMode, args=[src, dst, self.Q])
                            fileCopy.start()

    def stop(self):
        self.Q.put("0")
        self.startB.config(relief=RAISED)
        self.startflag = 0
        pass


def mccMode(src, dst, Q):
    initDir = scan_folder(src)
    todoList = []
    while checkQueue(Q):
        tmp = scan_folder(src)
        for i in tmp:
            if i not in initDir:
                todoList.append([i, os.stat(src+i).st_size, 0])
                initDir.append(i)

        for i in range(len(todoList)):
            file = src+todoList[i][0]
            filenew = dst+todoList[i][0]
            shutil.copy(file, filenew)

        for i in range(len(todoList)):
            if todoList[i][1] == os.stat(src+todoList[i][0]).st_size:
                todoList[i][2] = todoList[i][2] + 1
                print(todoList[i][0],todoList[i][2])
                print(todoList)
            else:
                todoList[i][1] = os.stat(src + todoList[i][0]).st_size
                todoList[i][2] = 0
                print(todoList)

        for i in todoList:
            if i[2] > 5:
                todoList.remove(i)
        time.sleep(60)
    Q.get()
    print("Test end")


def kyeMode(src, dst, Q):
    src = src+str(getDate())+"/"
    dst = dst+str(getDate())+"/"
    if not os.path.exists(dst):
        os.mkdir(dst)
    initDir = scan_folder(src)
    todoList = []
    while checkQueue(Q):
        tmp = scan_folder(src)
        for i in tmp:
            if i not in initDir:
                todoList.append(i)
        for i in todoList:
            file = src+i
            filenew = dst+i
            shutil.copy(file, filenew)
            todoList.remove(i)
        time.sleep(60)
    Q.get()
    print("Test end")


def change_path(oldpath, pathx):
    tmp = adir()
    if tmp == '':
        pathx.set(oldpath)
    else:
        pathx.set(tmp + "/")


def checkQueue(queue):
    if queue.empty():
        return True
    else:
        return False

def getDate():
    current_time = datetime.datetime.now()
    format = re.compile("\d+.\d+.\d+")
    current_date = re.search(format, str(current_time)).group()
    print(current_date)
    return current_date

def scan_folder(path):
    res = os.listdir(path)
    return res

def main():
    test = UI()
    UI.main(test)


if __name__ == '__main__':
    if sys.platform.startswith('win'):
        # On Windows calling this function is necessary.
        mp.set_start_method("spawn",force=True)
        mp.freeze_support()
    main()
```

The error messages are as below:
```
Traceback (most recent call last):
  File "uploadLog32.py", line 194, in <module>
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 54, in _freeze_support
  File "multiprocessing\spawn.py", line 105, in spawn_main
  File "multiprocessing\spawn.py", line 114, in _main
  File "multiprocessing\spawn.py", line 220, in prepare
  File "multiprocessing\context.py", line 242, in set_start_method
RuntimeError: context has already been set
[1676] Failed to execute script uploadLog32
```

**Comment by brianyu1986** [comment]
seems that i posted in a wrong place, sorry
