### ISSUE TITLE
Warning: PaddlePaddle catches a failure signal, it may not work properly

### ISSUE THREAD

**Issue by 1170300201** [PaddlePaddle/Paddle#24930]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本
- 训练信息
    1）单机/多机，单卡/多卡
    2）显存信息
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by 1170300201** [comment]
2020-06-04 18:47:00,840-WARNING: consumer[9307] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,841-WARNING: consumer[9308] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,841-WARNING: consumer[9309] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,841-WARNING: consumer[9310] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,841-WARNING: consumer[9311] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,841-WARNING: consumer[9312] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,841-WARNING: consumer[9313] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,841-WARNING: consumer[9314] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,841-WARNING: 8 consumers have exited abnormally!!!
2020-06-04 18:47:00,842-WARNING: consumer[9307] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,842-WARNING: consumer[9308] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,842-WARNING: consumer[9309] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,842-WARNING: consumer[9310] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,842-WARNING: consumer[9311] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,842-WARNING: consumer[9312] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,842-WARNING: consumer[9313] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,842-WARNING: consumer[9314] exit abnormally with exitcode[-11]
2020-06-04 18:47:00,842-WARNING: 8 consumers have exited abnormally!!!
2020-06-04 18:47:00,843-WARNING: Your reader has raised an exception!
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1156, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1136, in __thread_main__
    for tensors in self._tensor_reader():
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1206, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 506, in __reader_creator__
    for item in reader():
  File "/Users/qingyang/PaddleDetection/ppdet/data/reader.py", line 421, in _reader
    reader.reset()
  File "/Users/qingyang/PaddleDetection/ppdet/data/parallel_map.py", line 267, in reset
    assert self._consumer_healthy(), "cannot start another pass of data" \
AssertionError: cannot start another pass of data for some consumers exited abnormally before!!!

/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 366, in <module>
    main()
  File "tools/train.py", line 239, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > paddle::platform::GetTraceBackString<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, char const*, int)
1   paddle::operators::reader::BlockingQueue<std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> > >::EnforceNotKilled()
2   paddle::operators::reader::BlockingQueue<std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> > >::Receive(std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::__1::vector<paddle::framework::LoDTensor, std::__1::allocator<paddle::framework::LoDTensor> >*)
4   std::__1::__packaged_task_func<std::__1::__bind<paddle::operators::reader::BufferedReader::ReadAsync(unsigned long)::$_0>, std::__1::allocator<std::__1::__bind<paddle::operators::reader::BufferedReader::ReadAsync(unsigned long)::$_0> >, unsigned long ()>::operator()()
5   std::__1::packaged_task<unsigned long ()>::operator()()
6   ThreadPool::ThreadPool(unsigned long)::'lambda'()::operator()() const
7   void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, ThreadPool::ThreadPool(unsigned long)::'lambda'()> >(void*)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1078, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 976, in __init__
    self._init_non_iterable()
  File "/Users/qingyang/opt/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 608, in from_generator
    iterable, return_list, drop_last)
  File "/Users/qingyang/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 152, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 112, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 366, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by 1170300201** [comment]
数据集是官方的，配置文件也是官方的，总是报这种错误，似乎是说进程被kill掉，有没有高人指点一下

**Comment by cuicaihao** [comment]
# paddle pgl deepwalk bug report

# environment

MacOS Big Sur 11.0.1
Intel core i5 / 8GB RAM
conda environment
python 3.7.8 64bit
paddlepaddle==1.8.5
pgl==1.2.1

# Passed CMD

```bash
# OK PASSED
python deepwalk.py --dataset ArXiv --save_path ./tmp/deepwalk_ArXiv --offline_learning --epoch 2 --batch_size 256 --processes 2 --walk_len 5 --hidden_size 5

python link_predict.py --ckpt_path ./tmp/deepwalk_Arxiv/paddle_model --epoch 50 --hidden_size 5
```

# Error CMD: change '--walk_len' from '5' to '10'

```bash
# BUG
(paddle) ➜  deepwalk git:(main) ✗ python deepwalk.py --dataset ArXiv --save_path ./tmp/deepwalk_ArXiv --offline_learning --epoch 2 --batch_size 256 --processes 2 --walk_len 10 --hidden_size 5

[INFO] 2020-11-24 17:07:15,233 [ deepwalk.py:  257]:    Namespace(batch_size=256, dataset='ArXiv', epoch=2, hidden_size=5, neg_num=20, offline_learning=True, processes=2, save_path='./tmp/deepwalk_ArXiv', use_cuda=False, walk_len=10, win_size=10)
[INFO] 2020-11-24 17:07:16,104 [ deepwalk.py:  172]:    Start random walk on disk...
/Users/caihaocui/opt/miniconda3/envs/paddle/lib/python3.7/site-packages/pgl/graph.py:65: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  self._sorted_v, self._indptr, index=u)
/Users/caihaocui/opt/miniconda3/envs/paddle/lib/python3.7/site-packages/pgl/graph.py:65: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  self._sorted_v, self._indptr, index=u)
[INFO] 2020-11-24 17:07:16,656 [ deepwalk.py:  182]:    Random walk on disk Done.
WARNING:root:paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
[INFO] 2020-11-24 17:07:16,912 [ deepwalk.py:  228]:    Step 1 Deepwalk Loss: 0.724056  0.069567 s/step.
[INFO] 2020-11-24 17:07:16,970 [ deepwalk.py:  228]:    Step 2 Deepwalk Loss: 0.722518  0.058299 s/step.
 ...
 ... # skip the logging
 ...
[INFO] 2020-11-24 17:07:25,379 [ deepwalk.py:  228]:    Step 145 Deepwalk Loss: 0.671779  0.054414 s/step.
[INFO] 2020-11-24 17:07:25,432 [ deepwalk.py:  228]:    Step 146 Deepwalk Loss: 0.674288  0.053607 s/step.
[INFO] 2020-11-24 17:07:25,468 [ deepwalk.py:  228]:    Step 147 Deepwalk Loss: 0.668711  0.035875 s/step. # here comes the issue.
W1124 17:07:25.638923 114757120 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1124 17:07:25.638980 114757120 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W1124 17:07:25.639286 114757120 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1124 17:07:25.639313 114757120 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W1124 17:07:25.639443 114757120 init.cc:231] The detail failure signal is:

W1124 17:07:25.639468 114757120 init.cc:231] The detail failure signal is:

W1124 17:07:25.639588 114757120 init.cc:234] *** Aborted at 1606198045 (unix time) try "date -d @1606198045" if you are using GNU date ***
W1124 17:07:25.639611 114757120 init.cc:234] *** Aborted at 1606198045 (unix time) try "date -d @1606198045" if you are using GNU date ***
W1124 17:07:25.641268 114757120 init.cc:234] PC: @                0x0 (unknown)
W1124 17:07:25.641322 114757120 init.cc:234] PC: @                0x0 (unknown)
W1124 17:07:25.641880 114757120 init.cc:234] *** SIGTERM (@0x1055a2061) received by PID 64078 (TID 0x106d70e00) stack trace: ***
W1124 17:07:25.641963 114757120 init.cc:234] *** SIGTERM (@0x10556b50d) received by PID 64077 (TID 0x106d70e00) stack trace: ***
W1124 17:07:25.642434 114757120 init.cc:234]     @     0x7fff2035fd7d _sigtramp
W1124 17:07:25.642457 114757120 init.cc:234]     @     0x7fff2035fd7d _sigtramp
W1124 17:07:25.645393 114757120 init.cc:234]     @        0x10556b50e PyDict_GetItem
W1124 17:07:25.645655 114757120 init.cc:234]     @        0x105588331 _PyObject_GetMethod
W1124 17:07:25.645689 114757120 init.cc:234]     @        0x1055a2062 _PyType_Lookup
W1124 17:07:25.645864 114757120 init.cc:234]     @        0x105654f25 _PyEval_EvalFrameDefault
W1124 17:07:25.645937 114757120 init.cc:234]     @        0x105587902 _PyObject_GenericGetAttrWithDict
W1124 17:07:25.646073 114757120 init.cc:234]     @        0x10552bc1b _PyFunction_FastCallKeywords
W1124 17:07:25.652050 114757120 init.cc:234]     @        0x10565cadc call_function
W1124 17:07:25.652259 114757120 init.cc:234]     @        0x105582e7c module_getattro
W1124 17:07:25.653404 114757120 init.cc:234]     @        0x105654835 _PyEval_EvalFrameDefault
W1124 17:07:25.653635 114757120 init.cc:234]     @        0x105588385 _PyObject_GetMethod
W1124 17:07:25.655256 114757120 init.cc:234]     @        0x105654f25 _PyEval_EvalFrameDefault
W1124 17:07:25.655256 114757120 init.cc:234]     @        0x10552bc1b _PyFunction_FastCallKeywords
W1124 17:07:25.656097 114757120 init.cc:234]     @        0x10552bc1b _PyFunction_FastCallKeywords
W1124 17:07:25.656096 114757120 init.cc:234]     @        0x10565cadc call_function
W1124 17:07:25.656625 114757120 init.cc:234]     @        0x10565cadc call_function
W1124 17:07:25.656621 114757120 init.cc:234]     @        0x1056547ac _PyEval_EvalFrameDefault
W1124 17:07:25.657299 114757120 init.cc:234]     @        0x10552bc1b _PyFunction_FastCallKeywords
W1124 17:07:25.657260 114757120 init.cc:234]     @        0x1056547ac _PyEval_EvalFrameDefault
W1124 17:07:25.657886 114757120 init.cc:234]     @        0x10565cadc call_function
W1124 17:07:25.657886 114757120 init.cc:234]     @        0x10552bc1b _PyFunction_FastCallKeywords
W1124 17:07:25.658340 114757120 init.cc:234]     @        0x1056547ac _PyEval_EvalFrameDefault
W1124 17:07:25.658428 114757120 init.cc:234]     @        0x10565cadc call_function
W1124 17:07:25.659114 114757120 init.cc:234]     @        0x1056547ac _PyEval_EvalFrameDefault
W1124 17:07:25.659209 114757120 init.cc:234]     @        0x10552a480 _PyFunction_FastCallDict
W1124 17:07:25.659982 114757120 init.cc:234]     @        0x1055a9ab5 slot_tp_init
W1124 17:07:25.660045 114757120 init.cc:234]     @        0x10552a480 _PyFunction_FastCallDict
W1124 17:07:25.660230 114757120 init.cc:234]     @        0x1055b40fb type_call
W1124 17:07:25.660385 114757120 init.cc:234]     @        0x1055a9ab5 slot_tp_init
W1124 17:07:25.660429 114757120 init.cc:234]     @        0x10552b723 _PyObject_FastCallKeywords
W1124 17:07:25.660624 114757120 init.cc:234]     @        0x10565cc23 call_function
W1124 17:07:25.660662 114757120 init.cc:234]     @        0x1055b40fb type_call
W1124 17:07:25.660809 114757120 init.cc:234]     @        0x105654ff2 _PyEval_EvalFrameDefault
W1124 17:07:25.660897 114757120 init.cc:234]     @        0x10552b723 _PyObject_FastCallKeywords
W1124 17:07:25.660989 114757120 init.cc:234]     @        0x10552bc1b _PyFunction_FastCallKeywords
W1124 17:07:25.661088 114757120 init.cc:234]     @        0x10565cc23 call_function
W1124 17:07:25.661175 114757120 init.cc:234]     @        0x10565cadc call_function
W1124 17:07:25.661275 114757120 init.cc:234]     @        0x105654ff2 _PyEval_EvalFrameDefault
W1124 17:07:25.661368 114757120 init.cc:234]     @        0x105654835 _PyEval_EvalFrameDefault
W1124 17:07:25.661461 114757120 init.cc:234]     @        0x10552bc1b _PyFunction_FastCallKeywords
W1124 17:07:25.661551 114757120 init.cc:234]     @        0x10552bc1b _PyFunction_FastCallKeywords
W1124 17:07:25.661641 114757120 init.cc:234]     @        0x10565cadc call_function
W1124 17:07:25.661731 114757120 init.cc:234]     @        0x10565cadc call_function
W1124 17:07:25.661818 114757120 init.cc:234]     @        0x105654835 _PyEval_EvalFrameDefault
W1124 17:07:25.661911 114757120 init.cc:234]     @        0x1056547ac _PyEval_EvalFrameDefault
W1124 17:07:25.661995 114757120 init.cc:234]     @        0x10552bc1b _PyFunction_FastCallKeywords
W1124 17:07:25.662092 114757120 init.cc:234]     @        0x10552bc1b _PyFunction_FastCallKeywords
W1124 17:07:25.675662 114757120 init.cc:234]     @        0x10565cadc call_function
W1124 17:07:25.675660 114757120 init.cc:234]     @        0x10565cadc call_function
W1124 17:07:25.675941 114757120 init.cc:234]     @        0x1056547ac _PyEval_EvalFrameDefault
W1124 17:07:25.675942 114757120 init.cc:234]     @        0x1056547ac _PyEval_EvalFrameDefault
W1124 17:07:25.676152 114757120 init.cc:234]     @        0x10552bc1b _PyFunction_FastCallKeywords
W1124 17:07:25.676152 114757120 init.cc:234]     @        0x10564e127 _PyEval_EvalCodeWithName
W1124 17:07:25.676367 114757120 init.cc:234]     @        0x10565cadc call_function
W1124 17:07:25.676367 114757120 init.cc:234]     @        0x10552a552 _PyFunction_FastCallDict
W1124 17:07:25.676569 114757120 init.cc:234]     @        0x1056547ac _PyEval_EvalFrameDefault
W1124 17:07:25.676569 114757120 init.cc:234]     @        0x1055a9ab5 slot_tp_init
W1124 17:07:25.676816 114757120 init.cc:234]     @        0x1055b40fb type_call
W1124 17:07:25.676816 114757120 init.cc:234]     @        0x10564e127 _PyEval_EvalCodeWithName
W1124 17:07:25.677101 114757120 init.cc:234]     @        0x10552a552 _PyFunction_FastCallDict
W1124 17:07:25.677403 114757120 init.cc:234]     @        0x1055a9ab5 slot_tp_init
W1124 17:07:25.677690 114757120 init.cc:234]     @        0x1055b40fb type_call
W1124 17:07:25.677896 114757120 init.cc:234]     @        0x10552b723 _PyObject_FastCallKeywords
(paddle) ➜  deepwalk git:(main) ✗

```

## Python Running Environment

```bash
# conda environment
(paddle) ➜  examples git:(main) ✗ conda list
# packages in environment at /Users/caihaocui/opt/miniconda3/envs/paddle:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.4                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
autopep8                  1.5.4              pyh9f0ad1d_0    conda-forge
babel                     2.9.0                    pypi_0    pypi
bce-python-sdk            0.8.49                   pypi_0    pypi
ca-certificates           2020.11.8            h033912b_0    conda-forge
certifi                   2020.11.8        py37hf985489_0    conda-forge
cfgv                      3.2.0                    pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.21                  pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
distlib                   0.3.1                    pypi_0    pypi
filelock                  3.0.12                   pypi_0    pypi
flake8                    3.8.4                    pypi_0    pypi
flask                     1.1.2                    pypi_0    pypi
flask-babel               2.0.0                    pypi_0    pypi
funcsigs                  1.0.2                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
identify                  1.5.9                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        2.0.0                    pypi_0    pypi
itsdangerous              1.1.0                    pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
joblib                    0.17.0                     py_0    conda-forge
kiwisolver                1.3.1                    pypi_0    pypi
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libcxx                    11.0.0               h439d374_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               5.0.0               h7cc5361_13    conda-forge
libgfortran5              9.3.0               h7cc5361_13    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.3                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
ncurses                   6.2                  h2e338ed_4    conda-forge
nltk                      3.5                      pypi_0    pypi
nodeenv                   1.5.0                    pypi_0    pypi
numpy                     1.19.4           py37h9ebeaaa_1    conda-forge
objgraph                  3.5.0                    pypi_0    pypi
opencv-python             4.2.0.32                 pypi_0    pypi
openssl                   1.1.1h               haf1e3a3_0    conda-forge
paddlepaddle              1.8.5                    pypi_0    pypi
pathlib                   1.0.1                    pypi_0    pypi
pgl                       1.2.1                    pypi_0    pypi
pillow                    8.0.1                    pypi_0    pypi
pip                       20.2.4                     py_0    conda-forge
pre-commit                2.9.0                    pypi_0    pypi
prettytable               2.0.0                    pypi_0    pypi
protobuf                  3.14.0                   pypi_0    pypi
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycryptodome              3.9.9                    pypi_0    pypi
pyflakes                  2.2.0                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.7.8           h837cb1c_2_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python-graphviz           0.15                     pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.4                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
rarfile                   4.0                      pypi_0    pypi
readline                  8.0                  h0678c8f_2    conda-forge
redis                     3.5.3                    pypi_0    pypi
redis-py-cluster          2.1.0                    pypi_0    pypi
regex                     2020.11.13               pypi_0    pypi
requests                  2.25.0                   pypi_0    pypi
scikit-learn              0.23.2           py37ha0250bc_3    conda-forge
scipy                     1.5.4                    pypi_0    pypi
setuptools                49.6.0           py37h2987424_2    conda-forge
six                       1.15.0                   pypi_0    pypi
sqlite                    3.33.0               h960bd1c_1    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tqdm                      4.53.0                   pypi_0    pypi
urllib3                   1.26.2                   pypi_0    pypi
virtualenv                20.2.0                   pypi_0    pypi
visualdl                  2.0.4                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11            h7795811_1010    conda-forge
(paddle) ➜  examples git:(main) ✗
```
