### ISSUE TITLE
visualDL官方教程例子跑不起来

### ISSUE THREAD

**Issue by XiaoYangWu** [PaddlePaddle/Paddle#25033]
- 版本、环境信息：
    1）PaddlePaddle版本：1.6.3
    2）CPU/GPU：CPU
    3）Python版本号: 3.6.10

- 复现信息:
   安装完毕visualDL尝试跑例子：    https://www.paddlepaddle.org.cn/documentation/docs/zh/1.6/user_guides/howto/evaluation_and_debugging/debug/visualdl_usage.html

    执行命令：visualdl --logdir ./log --host 10.95.130.185 --port 8684 --model_pb paddle_lenet_5_model
     
    报错信息：
    
[INFO 2020-06-12 15:17:59,350 visualdl:336]  port=8684
 * Serving Flask app "visualdl" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[INFO 2020-06-12 15:17:59,357 _internal.py:113]  * Running on http://10.95.130.185:8684/ (Press CTRL+C to quit)
[INFO 2020-06-12 15:18:10,057 _internal.py:113] 172.24.142.111 - - [12/Jun/2020 15:18:10] "GET / HTTP/1.1" 302 -
[INFO 2020-06-12 15:18:10,088 _internal.py:113] 172.24.142.111 - - [12/Jun/2020 15:18:10] "GET /static/index.html HTTP/1.1" 200 -
[INFO 2020-06-12 15:18:10,135 _internal.py:113] 172.24.142.111 - - [12/Jun/2020 15:18:10] "GET /static/index.55f888f6ce9bc7495353.js HTTP/1.1" 200 -
[INFO 2020-06-12 15:18:10,137 _internal.py:113] 172.24.142.111 - - [12/Jun/2020 15:18:10] "GET /static/vendor.b1c57cda17102ce039c3.js HTTP/1.1" 200 -
[INFO 2020-06-12 15:18:10,138 _internal.py:113] 172.24.142.111 - - [12/Jun/2020 15:18:10] "GET /static/manifest.55f888f6ce9bc7495353.js HTTP/1.1" 200 -
[INFO 2020-06-12 15:18:11,776 _internal.py:113] 172.24.142.111 - - [12/Jun/2020 15:18:11] "GET /data/language HTTP/1.1" 200 -
[WARNING 2020-06-12 15:18:11,778 lib.py:388] update cache /data/runs
[ERROR 2020-06-12 15:18:11,779 app.py:1892] Exception on /data/runs [GET]
Traceback (most recent call last):
  File "/home/xiaobang/anaconda2/envs/paddle/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/xiaobang/anaconda2/envs/paddle/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/xiaobang/anaconda2/envs/paddle/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/xiaobang/anaconda2/envs/paddle/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/xiaobang/anaconda2/envs/paddle/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/xiaobang/anaconda2/envs/paddle/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/xiaobang/anaconda2/envs/paddle/bin/visualdl", line 172, in runs
    data = cache_get('/data/runs', lib.get_modes, log_reader)
  File "/home/xiaobang/anaconda2/envs/paddle/lib/python3.6/site-packages/visualdl/server/lib.py", line 389, in _handler
    data = func(*args, **kwargs)
  File "/home/xiaobang/anaconda2/envs/paddle/lib/python3.6/site-packages/visualdl/server/lib.py", line 33, in get_modes
    return storage.modes()
  File "/home/xiaobang/anaconda2/envs/paddle/lib/python3.6/site-packages/visualdl/python/storage.py", line 83, in modes
    return self.reader.modes()
RuntimeError: [/work/VisualDL/visualdl/utils/filesystem.h:63]

**Comment by ceci3** [comment]
建议用户升级到新版本。用户使用旧版本，手动调整url的方法也解决了。
