### ISSUE TITLE
[Paddle-TRT] Can't do inference bert with tensorrt

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#25108]
-PaddlePaddle version: develop
-GPU: including CUDA 10.2.89/CUDNN 7.6
-OS Platform: Ubuntu16.04
-Python version: 3.7
-C++version: 7.3.0
-API information
To Reproduce
Hello, I try to modify the [infer_trt_ernie.py](https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/python/paddle_trt/infer_trt_ernie.py) to adapt the [BERT](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/pretrain_language_models/BERT) model.
```
$ cat infer_trt_bert.py
import numpy as np
import argparse
import cv2

from paddle.fluid.core import AnalysisConfig
from paddle.fluid.core import create_paddle_predictor

# this is a simple resnet block for dynamci test.
def create_predictor(args):
  config = AnalysisConfig(args.model_dir)
  config.switch_use_feed_fetch_ops(False)
  config.enable_memory_optim()
  config.enable_use_gpu(100, 0)

  # using dynamic shpae mode, the max_batch_size will be ignored.
  config.enable_tensorrt_engine(workspace_size = 1<<30,
          max_batch_size=1, min_subgraph_size=5,
                  precision_mode=AnalysisConfig.Precision.Float32,
                  use_static=False, use_calib_mode=False)

  head_number = 12
  # names = ["eval_placeholder_0", "eval_placeholder_1", "eval_placeholder_2", "stack_0.tmp_0"]
  names = ["src_ids", "pos_ids", "sent_ids", "stack_0.tmp_0",
           "embedding_0.tmp_0", "embedding_1.tmp_0", "embedding_2.tmp_0"]
  min_input_shape = [1, 1, 1]
  max_input_shape = [100, 128, 1]
  opt_input_shape = [16, 64, 1]
  min_emb_shape = [1, 1, 768]
  max_emb_shape = [100, 128, 768]
  opt_emb_shape = [16, 64, 768]

  config.set_trt_dynamic_shape_info(
    {names[0]:min_input_shape, names[1]:min_input_shape, names[2]:min_input_shape, names[3]:[1, head_number, 1, 1],
     names[4]:min_emb_shape, names[5]:min_emb_shape, names[6]:min_emb_shape},
    {names[0]:max_input_shape, names[1]:max_input_shape, names[2]:max_input_shape, names[3]:[100, head_number, 128, 128],
     names[4]:max_emb_shape, names[5]:max_emb_shape, names[6]:max_emb_shape},
    {names[0]:opt_input_shape, names[1]:opt_input_shape, names[2]:opt_input_shape, names[3]:[10, head_number, 60, 60],
     names[4]:opt_emb_shape, names[5]:opt_emb_shape, names[6]:opt_emb_shape})
  predictor = create_paddle_predictor(config)
  return predictor

def run(predictor, data):
  # copy data to input tensor
  input_names = predictor.get_input_names()
  for i,  name in enumerate(input_names):
    input_tensor = predictor.get_input_tensor(name)
    input_tensor.reshape(data[i].shape)
    input_tensor.copy_from_cpu(data[i].copy())

  # do the inference
  predictor.zero_copy_run()
  results = []
  # get out data from output tensor
  output_names = predictor.get_output_names()
  for i, name in enumerate(output_names):
    output_tensor = predictor.get_output_tensor(name)
    output_data = output_tensor.copy_to_cpu()
    results.append(output_data)

  return results

def parse_args():
  parser = argparse.ArgumentParser()
  parser.add_argument("--model_file", type=str, default="", help="Model filename, Specify this when your model is a combined model.")
  parser.add_argument("--params_file", type=str, default="", help="Parameter filename, Specify this when your model is a combined model.")
  parser.add_argument("--model_dir", type=str, default="", help="Model dir, If you load a non-combined model, specify the directory of the model.
")
  parser.add_argument("--use_gpu", type=int, default=0, help="Whether use gpu.")
  return parser.parse_args()

if __name__ == '__main__':
  args = parse_args()
  pred = create_predictor(args)
  in1 = np.ones((1, 128, 1)).astype(np.int64)
  in2 = np.ones((1, 128, 1)).astype(np.int64)
  in3 = np.ones((1, 128, 1)).astype(np.int64)
  in4 = np.ones((1, 128, 1)).astype(np.float32)
  result = run(pred, [in1, in2, in3, in4])
  print (result)
```
And I got the pretrained(XNLI) inference model follows [PaddlePaddle/model instruction](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/pretrain_language_models/BERT). But we meet the following error:
```
I0617 22:07:13.869216 12202 analysis_predictor.cc:138] Profiler is deactivated, and no profiling report will be generated.
I0617 22:07:13.881665 12202 analysis_predictor.cc:872] MODEL VERSION: 1.8.1
I0617 22:07:13.881688 12202 analysis_predictor.cc:874] PREDICTOR VERSION: 0.0.0
W0617 22:07:13.881749 12202 analysis_predictor.cc:887]  - Version incompatible (1) dropout
W0617 22:07:13.881759 12202 analysis_predictor.cc:887]  - Version incompatible (1) elementwise_add
W0617 22:07:13.881765 12202 analysis_predictor.cc:887]  - Version incompatible (1) feed
W0617 22:07:13.881772 12202 analysis_predictor.cc:887]  - Version incompatible (1) fetch
W0617 22:07:13.881778 12202 analysis_predictor.cc:887]  - Version incompatible (1) gelu
W0617 22:07:13.881783 12202 analysis_predictor.cc:887]  - Version incompatible (3) layer_norm
W0617 22:07:13.881790 12202 analysis_predictor.cc:887]  - Version incompatible (1) lookup_table_v2
W0617 22:07:13.881796 12202 analysis_predictor.cc:887]  - Version incompatible (2) matmul
W0617 22:07:13.881803 12202 analysis_predictor.cc:887]  - Version incompatible (2) mul
W0617 22:07:13.881808 12202 analysis_predictor.cc:887]  - Version incompatible (2) reshape2
W0617 22:07:13.881814 12202 analysis_predictor.cc:887]  - Version incompatible (1) scale
W0617 22:07:13.881820 12202 analysis_predictor.cc:887]  - Version incompatible (2) slice
W0617 22:07:13.881826 12202 analysis_predictor.cc:887]  - Version incompatible (1) softmax
W0617 22:07:13.881832 12202 analysis_predictor.cc:887]  - Version incompatible (1) stack
W0617 22:07:13.881839 12202 analysis_predictor.cc:887]  - Version incompatible (1) tanh
W0617 22:07:13.881844 12202 analysis_predictor.cc:887]  - Version incompatible (1) transpose2
W0617 22:07:13.881851 12202 analysis_predictor.cc:194] WARNING: Results may be DIFF! Please use the corresponding version of the model and predi$
tion library, and do not use the develop branch.
I0617 22:07:13.882042 12202 analysis_predictor.cc:432] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
I0617 22:07:14.247191 12202 graph_pattern_detector.cc:100] ---  detected 25 subgraphs
--- Running IR pass [multihead_matmul_fuse_pass_v2]
I0617 22:07:15.947032 12202 graph_pattern_detector.cc:100] ---  detected 12 subgraphs
--- Running IR pass [skip_layernorm_fuse_pass]
I0617 22:07:15.986004 12202 graph_pattern_detector.cc:100] ---  detected 25 subgraphs
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [fc_fuse_pass]
I0617 22:07:16.002060 12202 graph_pattern_detector.cc:100] ---  detected 38 subgraphs
--- Running IR pass [tensorrt_subgraph_pass]
I0617 22:07:16.018818 12202 tensorrt_subgraph_pass.cc:115] ---  detect a sub-graph with 92 nodes
W0617 22:07:16.022231 12202 tensorrt_subgraph_pass.cc:285] The Paddle lib links the 7011 version TensorRT, make sure the runtime TensorRT you are
 using is no less than this version, otherwise, there might be Segfault!
I0617 22:07:16.022267 12202 tensorrt_subgraph_pass.cc:321] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may
cost a lot of time.
Traceback (most recent call last):
  File "infer_trt_bert.py", line 74, in <module>
    pred = create_predictor(args)
  File "infer_trt_bert.py", line 40, in create_predictor
    predictor = create_paddle_predictor(config)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > paddle::platform::GetTraceBackString<std::__cxx11::basic_stri
ng<char, std::char_traits<char>, std::allocator<char> > const&>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > c
onst&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char c
onst*, int)
2   paddle::inference::tensorrt::plugin::SkipLayerNormPluginDynamic::getOutputDimensions(int, nvinfer1::DimsExprs const*, int, nvinfer1::IExprBui
lder&)
3   nvinfer1::PluginV2Layer::getOutputFormDynamicExt(int, std::vector<nvinfer1::TensorForm, std::allocator<nvinfer1::TensorForm> > const&, nvinfe
r1::IPluginV2DynamicExt&) const
4   nvinfer1::PluginV2Layer::getOutputForm(int, std::vector<nvinfer1::TensorForm, std::allocator<nvinfer1::TensorForm> > const&) const
5   nvinfer1::Network::updateTensor(nvinfer1::NetworkTensor const*) const
6   nvinfer1::NetworkTensor::getDimensions() const
7   nvinfer1::SoftMaxLayer::SoftMaxLayer(nvinfer1::Network*, std::string const&, nvinfer1::ITensor&, nvinfer1::ITensor&)
8   nvinfer1::Network::addSoftMax(nvinfer1::ITensor&)
9   paddle::inference::tensorrt::SoftMaxOpConverter::operator()(paddle::framework::proto::OpDesc const&, paddle::framework::Scope const&, bool)
10  paddle::inference::tensorrt::OpConverter::ConvertOp(paddle::framework::proto::OpDesc const&, std::unordered_set<std::__cxx11::basic_string<ch
ar, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >,
std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> > > > const&, paddle::framework::Scope const&, paddle::inference::tensorrt::TensorRTEngine*, bool)
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector
<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_trait
s<char>, std::allocator<char> > > > const&, std::unordered_set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, s
td::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::c
har_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > co
nst&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char
, std::char_traits<char>, std::allocator<char> > > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits
<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allo
cator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*) const
13  paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
14  paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
15  paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Gr
aph> >)
16  paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
17  paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
18  paddle::AnalysisPredictor::OptimizeInferenceProgram()
19  paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
20  paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
21  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig,
 (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
22  std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>
(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Input dim of the SkipLayernorm should be 5, but it's (3) now.
  [Hint: Expected inputs[0].nbDims == 5, but received inputs[0].nbDims:3 != 5:5.] at (/home/rewang/P61ec30f/paddle/fluid/inference/tensorrt/plugi
n/skip_layernorm_op_plugin.cu:54)
```
Can you point me out why I meet this error? Is this the bug of Paddle or the wrong setting of dynamic shape of my script? Thank you

**Comment by jeng1220** [comment]
looks like `SoftMaxOpConverter` is broken. @NHZlX, could you help this?

**Comment by NHZlX** [comment]
Can you provide a model download link？

**Comment by jeng1220** [comment]
@NHZlX, the [link](https://github.com/PaddlePaddle/models/tree/release/1.8/PaddleNLP/pretrain_language_models/BERT#%E5%8F%91%E5%B8%83%E8%A6%81%E7%82%B9), and the model is [BERT-Base, Uncased](https://bert-models.bj.bcebos.com/uncased_L-12_H-768_A-12.tar.gz).
