### ISSUE TITLE
读模型预估 operator < distributed_lookup_table > error

### ISSUE THREAD

**Issue by zhaocaibei123** [PaddlePaddle/Paddle#25139]
加载模型预估遇到以下问题，模型训练用1.6，模型预估1.7版本，是否和embedding版本有关？

/home/work/.jumbo/lib/python3.6/site-packages/paddle/fluid/executor.py:789: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "test.py", line 236, in <module>
    auc = valid_and_test(inference_program, test_feeder, test_reader, fetch_targets, label_set, qid_list, qs_list)
  File "test.py", line 105, in valid_and_test
    fetch_list=pred)
  File "/home/work/.jumbo/lib/python3.6/site-packages/paddle/fluid/executor.py", line 790, in run
    six.reraise(*sys.exc_info())
  File "/home/work/.jumbo/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/work/.jumbo/lib/python3.6/site-packages/paddle/fluid/executor.py", line 785, in run
    use_program_cache=use_program_cache)
  File "/home/work/.jumbo/lib/python3.6/site-packages/paddle/fluid/executor.py", line 838, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/work/.jumbo/lib/python3.6/site-packages/paddle/fluid/executor.py", line 912, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::DistributedLookupTableOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
6   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
7   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/disk1/normandy/maybach/app-user-20200616195431-1623/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2506, in _insert_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/home/disk1/normandy/maybach/app-user-20200616195431-1623/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 479, in _update_remote_sparse_update_op
    "trainer_id": self.trainer_id
  File "/home/disk1/normandy/maybach/app-user-20200616195431-1623/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/fluid/transpiler/distribute_transpiler.py", line 823, in transpile
    self._update_remote_sparse_update_op(program, need_sparse_update_params)
  File "train.py", line 370, in train
    t.transpile(trainer_id, pservers=pserver_endpoints, trainers=trainers)
  File "train.py", line 394, in main
    train(use_cuda, save_dirname, is_local)
  File "train.py", line 404, in <module>
    main(use_cuda, is_local)

----------------------
Error Message Summary:
----------------------
Error: The dimension of the 'Ids' tensor must be 2.
  [Hint: Expected ids_dim.size() == 2, but received ids_dim.size():1 != 2:2.] at (/paddle/paddle/fluid/operators/distributed_ops/distributed_lookup_table_op.cc:45)
  [operator < distributed_lookup_table > error]

部分代码如下：
[inference_program, feed_target_names, fetch_targets] = \
    fluid.io.load_inference_model(dirname=model_path, executor=exe)

        for data in batch_reader():
            print('data:', data)
            _pred = exe.run(program=program,
                         feed=feeder.feed(data),
                         fetch_list=pred)

**Comment by MrChengmo** [comment]
模型是用分布式训练过程中使用`save_inference_model`保存的吗？不建议这样做。

- 分布式训练使用`save_persistable`保存`模型参数`

- 相同组网使用单机训练保存`save_inference_model`会产出（`__model___`+ `模型参数`）

- 把这个 `__model__`拷贝到分布式保存的参数文件夹里去

- 使用这个文件夹正常做预测。
