### ISSUE TITLE
python API放到multiprocess_reader中预测报cuda错

### ISSUE THREAD

**Issue by wang-kangkang** [PaddlePaddle/Paddle#25185]
我的需求是在reader中使用inference_model进行预测，reader放在multiprocess_reader中。使用了两种实现方式都报错：Error: cudaSetDevice failed in paddle::platform::SetDeviced, error code : 3, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.htm    l#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038: initialization error at (/paddle/paddle/fluid/platform/gpu_info.cc:240)
第一种是：在reader中定义CUDAPlace和exe；第二种是在reader中使用python API预测。其中第二种方法在pool构造的多进程中没问题，在本场景的multiprocess_reader中有问题。
最小可复现代码：paddle1.7 post97
```
import os
os.environ["CUDA_VISIBLE_DEVICES"]="2"
import paddle
import paddle.fluid as fluid
from paddle.fluid.core import PaddleTensor
from paddle.fluid.core import AnalysisConfig
from paddle.fluid.core import create_paddle_predictor
def reader():
    landmark_config = AnalysisConfig('lmk_model/model','lmk_model/params')
    landmark_config.switch_use_feed_fetch_ops(False)
    #landmark_config.disable_gpu() 
    landmark_config.enable_use_gpu(100, 0)  
    landmark_predictor = create_paddle_predictor(landmark_config) 
    for i in range(10):
        yield i
if __name__=="__main__":
    place = fluid.CUDAPlace(0)
    exe = fluid.Executor(place)
    train_reader = paddle.reader.multiprocess_reader([reader, reader])
    for data in train_reader():
        print(data)
```

**Comment by chenwhql** [comment]
在这个例子中，不用multiprocess_reader装饰是可以正常工作的吗

**Comment by wang-kangkang** [comment]
> 在这个例子中，不用multiprocess_reader装饰是可以正常工作的吗

可以的，将for循环改成：for data in reader():  可以正常跑。

**Comment by chenwhql** [comment]
贴一下我这边的报错供分析：

```
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/paddle/reader/decorator.py", line 587, in _read_into_pipe
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/paddle/reader/decorator.py", line 578, in _read_into_pipe
    for sample in reader():
  File "reader_demo.py", line 13, in reader
    landmark_predictor = create_paddle_predictor(landmark_config)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::SetDeviceId(int)
3   paddle::AnalysisConfig::fraction_of_gpu_memory_for_pool() const
4   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
5   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig>(paddle::AnalysisConfig const&)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(3), initialization error.
  [Advise: Please search for the error code(3) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] at (/work/paddle/paddle/fluid/platform/gpu_info.cc:212)
```

**Comment by NHZlX** [comment]
create_paddle_predictor 非线程安全，可加锁试下

**Comment by wang-kangkang** [comment]
> create_paddle_predictor 非线程安全，可加锁试下

我改成：
    #place = fluid.CUDAPlace(0)
    #exe = fluid.Executor(place)
    train_reader = paddle.reader.multiprocess_reader([reader])
也报同样的错，看起来是multiprocess_reader导致的问题？

**Comment by NHZlX** [comment]
multiprocess reader我理解是多线程了吧，你在reader中使用了create_paddle_predictor ，但是这个接口非线程安全的。

**Comment by wang-kangkang** [comment]
> multiprocess reader我理解是多线程了吧，你在reader中使用了create_paddle_predictor ，但是这个接口非线程安全的。

文档里写的multiprocess_reader是多进程的。而且我上面改动后，仅剩一个reader在运行了，非线程安全也没影响吧

**Comment by chenwhql** [comment]
其实multiprocess_reader只是一个简单的多进程装饰器，没有实现进程间同步的安全机制，仅用在原先数据读取接口较慢的情况下，用户从磁盘读取数据这种简单场景，而且现在也不推荐使用

**Comment by chenwhql** [comment]
您上面说pool构造的多进程没有问题，是怎么实现的？不能满足您的需求吗

**Comment by chenwhql** [comment]
@NHZlX 从示例代码和报错能看出来，为什么这么写会报CUDA没初始化的错误吗

**Comment by chenwhql** [comment]
@wang-kangkang `第一种是：在reader中定义CUDAPlace和exe；`，请问第一种报什么错

**Comment by wang-kangkang** [comment]
> @wang-kangkang `第一种是：在reader中定义CUDAPlace和exe；`，请问第一种报什么错

类似，又不完全一样。
```
import os
os.environ["CUDA_VISIBLE_DEVICES"]="2"
import paddle
import paddle.fluid as fluid
def reader():
    place = fluid.CUDAPlace(0)
    exe = fluid.Executor(place)
    [program, feed, fetch] = fluid.io.load_inference_model('lmk_model', exe, 'model', 'params')
    for i in range(10):
        yield i
if __name__=="__main__":
    place = fluid.CUDAPlace(0)
    exe = fluid.Executor(place)
    train_reader = paddle.reader.multiprocess_reader([reader])
    for data in train_reader():
        print(data)
```
报错为：
```
/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "test1.py", line 15, in <module>
    for data in train_reader():
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/reader/decorator.py", line 614, in pipe_reader
    raise ValueError("multiprocess reader raises an exception")
ValueError: multiprocess reader raises an exception
Process Process-1:
Traceback (most recent call last):
  File "/ssd3/my/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/ssd3/my/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/reader/decorator.py", line 587, in _read_into_pipe
    six.reraise(*sys.exc_info())
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/reader/decorator.py", line 578, in _read_into_pipe
    for sample in reader():
  File "test1.py", line 8, in reader
    [program, feed, fetch] = fluid.io.load_inference_model('lmk_model', exe, 'model', 'params')
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 1377, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 917, in load_persistables
    filename=filename)
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 742, in load_vars
    filename=filename)
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/fluid/io.py", line 794, in load_vars
    executor.run(load_prog)
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "/ssd3/my/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py", line 905, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::platform::GetCurrentDeviceId()
3   paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace)
4   std::_Function_handler<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > (), std::reference_wrapper<std::_Bind_simple<void paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()> > >::_M_invoke(std::_Any_data const&)
5   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
6   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
7   std::__future_base::_Deferred_state<std::_Bind_simple<void paddle::platform::EmplaceDeviceContext<paddle::platform::CUDADeviceContext, paddle::platform::CUDAPlace>(std::map<paddle::platform::Place, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::less<paddle::platform::Place>, std::allocator<std::pair<paddle::platform::Place const, std::shared_future<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > > > >*, paddle::platform::Place)::{lambda()#1} ()>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >::_M_run_deferred()
8   paddle::platform::DeviceContextPool::Get(paddle::platform::Place const&)
9   paddle::framework::GarbageCollector::GarbageCollector(paddle::platform::Place const&, unsigned long)
10  paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long)
11  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
12  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

----------------------
Error Message Summary:
----------------------
Error: cudaGetDevice failed in paddle::platform::GetCurrentDeviceId, error code : 3, Please see detail in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038: initialization error at (/paddle/paddle/fluid/platform/gpu_info.cc:211)
```

**Comment by chenwhql** [comment]
这里多个进程不能都用一张GPU卡，这里是不是每个进程都用的是CUDAPlace(0)

**Comment by wang-kangkang** [comment]
> 这里多个进程不能都用一张GPU卡，这里是不是每个进程都用的是CUDAPlace(0)

什么原因呢？而且我的场景里就是需要在multiprocess_reader里的reader里进行预测，得把这个方案走通

**Comment by chenwhql** [comment]
稍等，我再排查一下

**Comment by chenwhql** [comment]
@wang-kangkang 我这边试了下，把exe塞到子进程里执行就会报这个错，还需要时间分析下
@NHZlX 说预测python API理论上支持这种第二种写法，麻烦等他回复下

**Comment by chenwhql** [comment]
@wang-kangkang 这里应该是因为，从框架层面来讲的话，import paddle的时候，会初始化的CUDADeviceContext，而一旦初始化之后，就不能共享给主进程创建的子进程使用，而要支持这种写法，涉及到的底层改动还是挺大的，后续反馈下要不要做，一时半会这种写法应该不行，单预测API的话等等 @NHZIX 回复

为什么一定要这么写？这个本质需求是预测的速度不够快吗？

**Comment by wang-kangkang** [comment]
> @wang-kangkang 这里应该是因为，从框架层面来讲的话，import paddle的时候，会初始化的CUDADeviceContext，而一旦初始化之后，就不能共享给主进程创建的子进程使用，而要支持这种写法，涉及到的底层改动还是挺大的，后续反馈下要不要做，一时半会这种写法应该不行，单预测API的话等等 @NHZIX 回复
> 
> 为什么一定要这么写？这个本质需求是预测的速度不够快吗？

需求场景是我在训练人脸检测模型的时候，想要在检测模型上再出另一个分支来输出人脸的模糊属性。由于检测的数据产生过程有data argument，其中会改变人脸模糊度和大小，所以模糊属性无法提前离线标注。当前的方法就是使用一个提前训练好的模糊分类小模型，在reader中的data argument之后进行inference，从而获得模糊度“标签”。
目前在reader中使用cpu预测十分慢，整体训练速度不到原先的40%

**Comment by NHZlX** [comment]
这个错误，具体的原因是，CUDA的context不能在多进程内共享。 

```
If you create a CUDA context before the fork(), 
you cannot use that within the child process. 
The cudaSetDevice(0); call attempts to share the CUDA context,
implicitly created in the parent process when you call cudaGetDeviceCount();
```

具体的解释可见：
https://stackoverflow.com/questions/22950047/cuda-initialization-error-after-fork


在调用 `paddle.reader.multiprocess_reader` 之后会fork出子进程，但是在这之前paddle会初始化cuda context，因此会有上述的问题。

https://github.com/PaddlePaddle/Paddle/blob/cb0472b05ab86dd7b51f663bc161841059a9d035/python/paddle/fluid/__init__.py#L221

https://github.com/PaddlePaddle/Paddle/blob/cb0472b05ab86dd7b51f663bc161841059a9d035/paddle/fluid/pybind/pybind.cc#L1533

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/init.cc#L139-L154


**因此在使用cuda期间避免fork多进程，建议使用多线程。**

**Comment by wang-kangkang** [comment]
> 这个错误，具体的原因是，CUDA的context不能在多进程内共享。
> 
> ```
> If you create a CUDA context before the fork(), 
> you cannot use that within the child process. 
> The cudaSetDevice(0); call attempts to share the CUDA context,
> implicitly created in the parent process when you call cudaGetDeviceCount();
> ```
> 
> 具体的解释可见：
> https://stackoverflow.com/questions/22950047/cuda-initialization-error-after-fork
> 
> 在调用 `paddle.reader.multiprocess_reader` 之后会fork出子进程，但是在这之前paddle会初始化cuda context，因此会有上述的问题。
> 
> https://github.com/PaddlePaddle/Paddle/blob/cb0472b05ab86dd7b51f663bc161841059a9d035/python/paddle/fluid/__init__.py#L221
> 
> https://github.com/PaddlePaddle/Paddle/blob/cb0472b05ab86dd7b51f663bc161841059a9d035/paddle/fluid/pybind/pybind.cc#L1533
> 
> https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/init.cc#L139-L154
> 
> **因此在使用cuda期间避免fork多进程，建议使用多线程。**

使用多线程会降低原有的训练速度。所以有没有办法能直面并解决当前问题

**Comment by NHZlX** [comment]
那在reader中去掉cuda相关（或者接口内部有调用cuda）的代码吧

**Comment by wang-kangkang** [comment]
> 也不可以）的代码

reader中使用place=fluid.CPUPlace()速度同样很慢，我期望的是起码能实用python API能在reader中调用cuda预测。

**Comment by NHZlX** [comment]
reader是否可以用多线程

**Comment by chenwhql** [comment]
@wang-kangkang import paddle的时候会在当前进程初始化cuda的环境，如果一定要用子进程的话，只能在子进程中import paddle了，这样倒不会报错，但应该也没法用了吧。。。

```
import os
import numpy as np
import multiprocessing

os.environ["CUDA_VISIBLE_DEVICES"]="0"

def _read_into_queue(reader, queue):
    try:
        for sample in reader():
            if sample is None:
                raise ValueError("sample has None")
            queue.put(sample)
        queue.put(None)
    except:
        queue.put("")
        six.reraise(*sys.exc_info())

def queue_reader(readers):
    queue = multiprocessing.Queue(10)
    for reader in readers:
        p = multiprocessing.Process(
            target=_read_into_queue, args=(reader, queue))
        p.start()

    reader_num = len(readers)
    finish_num = 0
    while finish_num < reader_num:
        sample = queue.get()
        if sample is None:
            finish_num += 1
        elif sample == "":
            raise ValueError("multiprocess reader raises an exception")
        else:
            yield sample

def reader():
    def __impl__():
      import paddle
      import paddle.fluid as fluid

      place = fluid.CUDAPlace(0)
      exe = fluid.Executor(place)
      
      [inference_program, feed_target_names, fetch_targets] = (
          fluid.io.load_inference_model(dirname="./save_load/fc.example.model", executor=exe))

      tensor_img = np.array(np.random.random((1, 784)), dtype=np.float32)
      results = exe.run(inference_program,
                        feed={feed_target_names[0]: tensor_img},
                        fetch_list=fetch_targets)
      yield results[0]

    return __impl__

if __name__=="__main__":
    train_reader = queue_reader([reader()])
    for data in train_reader:
        print(data)
```

**Comment by wang-kangkang** [comment]
> @wang-kangkang import paddle的时候会在当前进程初始化cuda的环境，如果一定要用子进程的话，只能在子进程中import paddle了，这样倒不会报错，但应该也没法用了吧。。。
> 
> ```
> import os
> import numpy as np
> import multiprocessing
> 
> os.environ["CUDA_VISIBLE_DEVICES"]="0"
> 
> def _read_into_queue(reader, queue):
>     try:
>         for sample in reader():
>             if sample is None:
>                 raise ValueError("sample has None")
>             queue.put(sample)
>         queue.put(None)
>     except:
>         queue.put("")
>         six.reraise(*sys.exc_info())
> 
> def queue_reader(readers):
>     queue = multiprocessing.Queue(10)
>     for reader in readers:
>         p = multiprocessing.Process(
>             target=_read_into_queue, args=(reader, queue))
>         p.start()
> 
>     reader_num = len(readers)
>     finish_num = 0
>     while finish_num < reader_num:
>         sample = queue.get()
>         if sample is None:
>             finish_num += 1
>         elif sample == "":
>             raise ValueError("multiprocess reader raises an exception")
>         else:
>             yield sample
> 
> def reader():
>     def __impl__():
>       import paddle
>       import paddle.fluid as fluid
> 
>       place = fluid.CUDAPlace(0)
>       exe = fluid.Executor(place)
>       
>       [inference_program, feed_target_names, fetch_targets] = (
>           fluid.io.load_inference_model(dirname="./save_load/fc.example.model", executor=exe))
> 
>       tensor_img = np.array(np.random.random((1, 784)), dtype=np.float32)
>       results = exe.run(inference_program,
>                         feed={feed_target_names[0]: tensor_img},
>                         fetch_list=fetch_targets)
>       yield results[0]
> 
>     return __impl__
> 
> if __name__=="__main__":
>     train_reader = queue_reader([reader()])
>     for data in train_reader:
>         print(data)
> ```

这种方法也不行，我的主进程里需要进行训练啊

**Comment by chenwhql** [comment]
嗯嗯，所以结论是目前想在主进程中创建子进程，在子进程中做inference这种思路在目前的paddle实现下是行不通的，这也不是一个bug修复的问题，而是架构层面的设计就不满足这样的写法，所以对于您这个需求，需要想别的办法，您看看reader多线程用GPU做inference能满足需求吗？

**Comment by wang-kangkang** [comment]
> 嗯嗯，所以结论是目前想在主进程中创建子进程，在子进程中做inference这种思路在目前的paddle实现下是行不通的，这也不是一个bug修复的问题，而是架构层面的设计就不满足这样的写法，所以对于您这个需求，需要想别的办法，您看看reader多线程用GPU做inference能满足需求吗？

好吧，我没想到这个问题这么复杂。我试试paddle server方法吧。
