### ISSUE TITLE
动态图转静态图后无法加载模型

### ISSUE THREAD

**Issue by wuxianshen** [PaddlePaddle/Paddle#25186]
按照文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/beginners_guide/basic_concept/dygraph/DyGraph.html#id11
提供的示例将mnist网络动态图模型转换为静态图模型，保存后再加载时报错ValueError：

/home/tao/.conda/envs/paddle/bin/python /home/tao/work/deep_learning/paddle-cpp/sample/dy_graph/dy_graph.py
W0624 11:20:11.270084 15827 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0624 11:20:11.273815 15827 device_context.cc:260] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "/home/tao/work/deep_learning/paddle-cpp/sample/dy_graph/dy_graph.py", line 22, in <module>
    program, feed_vars, fetch_vars = fluid.io.load_inference_model(save_dirname, exe)
  File "/home/tao/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/io.py", line 1396, in load_inference_model
    program = Program.parse_from_string(program_desc_str)
  File "/home/tao/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4357, in parse_from_string
    p._sync_with_cpp()
  File "/home/tao/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4557, in _sync_with_cpp
    block._sync_with_cpp()
  File "/home/tao/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2730, in _sync_with_cpp
    op = Operator(self, op_desc)
  File "/home/tao/.conda/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1832, in __init__
    "`type` to initialized an Operator can not be None.")
ValueError: `type` to initialized an Operator can not be None.

Process finished with exit code 1

Paddle version: paddlepaddle-gpu   1.8.1.post107 
Python version: 3.6.1
CUDA version: 10.1.243
cuDNN version: 7.6.5
Nvidia driver version: 418.87.00

dy_graph.py内容：

```
with fluid.dygraph.guard():
    # 定义MNIST类的对象
    mnist = mnist_net()
    in_np = np.random.random([10, 1, 28, 28]).astype('float32')
    # 将numpy的ndarray类型的数据转换为Variable类型
    input_var = fluid.dygraph.to_variable(in_np)
    # 通过 TracerLayer.trace 接口将动态图模型转换为静态图模型
    out_dygraph, static_layer = TracedLayer.trace(mnist, inputs=[input_var])
    save_dirname = './saved_infer_model'
    # 将转换后的模型保存
    static_layer.save_inference_model(save_dirname, feed=[0], fetch=[0])
    # 静态图中需要使用执行器执行之前已经定义好的网络
    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    program, feed_vars, fetch_vars = fluid.io.load_inference_model(save_dirname, exe)
    # 静态图中需要调用执行器的run方法执行计算过程
    fetch, = exe.run(program, feed={feed_vars[0]: in_np}, fetch_list=fetch_vars)
    print(fetch)

网络定义：
import paddle
import paddle.fluid as fluid

class simple_img_conv_pool(fluid.dygraph.Layer):
    def __init__(self,
                 num_channels,
                 num_filters,
                 filter_size,
                 pool_size,
                 pool_stride,
                 pool_padding=0,
                 pool_type='max',
                 global_pooling=False,
                 conv_stride=1,
                 conv_padding=0,
                 conv_dilation=1,
                 conv_groups=1,
                 act=None,
                 use_cudnn=False,
                 param_attr=None,
                 bias_attr=None):
        super(simple_img_conv_pool, self).__init__()
        self._conv2d = fluid.dygraph.Conv2D(
            num_channels=num_channels,
            num_filters=num_filters,
            filter_size=filter_size,
            stride=conv_stride,
            padding=conv_padding,
            dilation=conv_dilation,
            groups=conv_groups,
            param_attr=param_attr,
            bias_attr=bias_attr,
            use_cudnn=use_cudnn,
            act=act
        )
        self._pool2d = fluid.dygraph.Pool2D(
            pool_size=pool_size,
            pool_type=pool_type,
            pool_stride=pool_stride,
            pool_padding=pool_padding,
            global_pooling=global_pooling,
            use_cudnn=use_cudnn
        )

    def forward(self, inputs):
        x = self._conv2d(inputs)
        x = self._pool2d(x)
        return x

class mnist_net(fluid.dygraph.Layer):
    def __init__(self):
        super(mnist_net, self).__init__()

        self._simple_img_conv_pool_1 = simple_img_conv_pool(
            1, 20, 5, 2, 2, act='relu'
        )

        self._simple_img_conv_pool_2 = simple_img_conv_pool(
            20, 50, 5, 2, 2, act='relu'
        )

        # How to obtain the shape after pool_2?
        self.pool_2_shape = 50 * 4 * 4
        SIZE = 10
        scale = (2.0 / (self.pool_2_shape**2 * SIZE)) ** 0.5
        self._fc = fluid.dygraph.Linear(
            self.pool_2_shape,
            10,
            param_attr=fluid.param_attr.ParamAttr(
                initializer=fluid.initializer.NormalInitializer(
                    loc=0.0, scale=scale)),
            act='softmax'
        )

    def forward(self, inputs, label=None):
        x = self._simple_img_conv_pool_1(inputs)
        x = self._simple_img_conv_pool_2(x)
        x = fluid.layers.reshape(x, shape=[-1, self.pool_2_shape])
        x = self._fc(x)
        if label is not None:
            acc = fluid.layers.accuracy(input=x, label=label)
            return x, acc
        else:
            return x
```

**Comment by chenwhql** [comment]
把下面静态图的部分，退格，放到guard外面试试
```
with fluid.dygraph.guard():
    # 定义MNIST类的对象
    mnist = mnist_net()
    in_np = np.random.random([10, 1, 28, 28]).astype('float32')
    # 将numpy的ndarray类型的数据转换为Variable类型
    input_var = fluid.dygraph.to_variable(in_np)
    # 通过 TracerLayer.trace 接口将动态图模型转换为静态图模型
    out_dygraph, static_layer = TracedLayer.trace(mnist, inputs=[input_var])
    save_dirname = './saved_infer_model'
    # 将转换后的模型保存
    static_layer.save_inference_model(save_dirname, feed=[0], fetch=[0])

# 静态图中需要使用执行器执行之前已经定义好的网络
place = fluid.CPUPlace()
exe = fluid.Executor(place)
program, feed_vars, fetch_vars = fluid.io.load_inference_model(save_dirname, exe)
# 静态图中需要调用执行器的run方法执行计算过程
etch, = exe.run(program, feed={feed_vars[0]: in_np}, fetch_list=fetch_vars)
print(fetch)
```

**Comment by wuxianshen** [comment]
确实是这个问题，谢谢大佬！
