### ISSUE TITLE
Ubuntu 18.04 install_check  报错 CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by dkerjw1** [PaddlePaddle/Paddle#25255]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：请包含关键词“安装错误”/“编译错误”，例如“Mac编译错误”
- 版本、环境信息：
    1）PaddlePaddle版本：develop
    2）CPU：Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    3）GPU：RTX2080 CUDA10.1, CUDNN 7.6
    4）系统环境：Ubuntu 18.04 , python 3.5.2
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
1）编译安装
2）本地编译：cmake .. -DPY_VERSION=3.5.2 -DWITH_GPU=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DPYTHON_INCLUDE_DIR=/home/mengqingyue/anaconda3/include -DPYTHON_LIBRARY=/home/mengqingyue/anaconda3/lib/libpython3.5m.so
  特殊环境请注明：如离线安装等
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

安装之后，```import```没有问题，但```install_check```时报```CUBLAS_STATUS_EXECUTION_FAILED```， 具体如下：
=====================================================================================
```
(paddle-venv) mengqingyue@baidu-pc:~/work/Paddle/build/python/dist$ python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
>>> fluid.install_check.run_check()
Running Verify Fluid Program ... 
W0629 21:31:43.792838 21166 device_context.cc:265] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.1
W0629 21:31:43.795601 21166 device_context.cc:273] device: 0, cuDNN Version: 7.6.
/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/executor.py:1078: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 122, in test_simple_exe
    fetch_list=[out0.name, param_grads[1].name])
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/executor.py", line 1079, in run
    six.reraise(*sys.exc_info())
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/executor.py", line 1074, in run
    return_merged=return_merged)
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/executor.py", line 1162, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/executor.py", line 1237, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const
3   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, float, paddle::framework::Tensor*, float) const
4   paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/framework.py", line 2799, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/dygraph/nn.py", line 984, in forward
    type="matmul", inputs=inputs, outputs={"Out": tmp}, attrs=attrs)
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 466, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 41, in forward
    x = self._linear1(inputs)
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/dygraph/layers.py", line 466, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "/home/mengqingyue/.virtualenvs/paddle-venv/lib/python3.5/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "<stdin>", line 1, in <module>

----------------------
Error Message Summary:
----------------------
ExternalError:  Cublas error, CUBLAS_STATUS_EXECUTION_FAILED  at (/home/mengqingyue/work/Paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)
  [operator < matmul > error]

```

**Comment by dkerjw1** [comment]
重启电脑没问题了
