### ISSUE TITLE
安装完成后，import paddle报错

### ISSUE THREAD

**Issue by KrisZHH** [PaddlePaddle/Paddle#25396]
安装paddlepaddle-gpu-1.8.2-post97后，import paddle报错如下：

Python 3.6.11 (default, Jul  6 2020, 10:10:46)
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vis/zhenghonghui/env/python3.6/lib/python3.6/site-packages/paddle/__init__.py", line 37, in <module>
    import paddle.complex
  File "/home/vis/zhenghonghui/env/python3.6/lib/python3.6/site-packages/paddle/complex/__init__.py", line 15, in <module>
    from . import tensor
  File "/home/vis/zhenghonghui/env/python3.6/lib/python3.6/site-packages/paddle/complex/tensor/__init__.py", line 15, in <module>
    from . import math
  File "/home/vis/zhenghonghui/env/python3.6/lib/python3.6/site-packages/paddle/complex/tensor/math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "/home/vis/zhenghonghui/env/python3.6/lib/python3.6/site-packages/paddle/common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "/home/vis/zhenghonghui/env/python3.6/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/home/vis/zhenghonghui/env/python3.6/lib/python3.6/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/vis/zhenghonghui/env/python3.6/lib/python3.6/site-packages/paddle/fluid/core.py", line 197, in <module>
    raise e
  File "/home/vis/zhenghonghui/env/python3.6/lib/python3.6/site-packages/paddle/fluid/core.py", line 167, in <module>
    from .core_avx import *
ImportError: dlopen: cannot load any more object with static TLS

**Comment by FrostML** [comment]
请教了下 @zhiqiu ，这是一个已知的问题。具体的原因可以参照这个 [PR 25390](https://github.com/PaddlePaddle/Paddle/pull/25390)。
@zhiqiu 给出了一种解决方案可以先尝试下：
在 `/home/vis/zhenghonghui/env/python3.6/lib/python3.6/site-packages/paddle/fluid/` 下面找到`core_avx.so`
`ldd core_avx.so`之后
找到这么一行：
`libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1`
然后试下将`libgomp.so.1`的路径加入环境变量`LD_LIBRARY_PATH`，再
`export LD_PRELOAD=path_to_libgomp.so.1`

根据 25390：
![image](https://user-images.githubusercontent.com/7160927/86578517-81bbba80-bfae-11ea-867e-7838fae8349d.png)
