### ISSUE TITLE
PaddleServing faster rcnn demo 预测时报错

### ISSUE THREAD

**Issue by mcl-stone** [PaddlePaddle/Paddle#25489]
使用paddle1.8.2，paddleserving develop版本，部署起来预测时报错如下，因为看报错是paddle这边报的，所以发这边了。
```shell
[root@c99a526ec87f paddle]# python3.6 test_client2.py 
W0712 09:09:58.147349  1843 analysis_predictor.cc:133] Profiler is activated, which might affect the performance
I0712 09:09:58.785828  1843 analysis_predictor.cc:872] MODEL VERSION: 1.7.1
I0712 09:09:58.785851  1843 analysis_predictor.cc:874] PREDICTOR VERSION: 1.8.2
I0712 09:09:58.786041  1843 analysis_predictor.cc:471] ir_optim is turned off, no IR pass will be executed
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0712 09:09:58.998006  1843 ir_params_sync_among_devices_pass.cc:41] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I0712 09:09:59.093183  1843 analysis_predictor.cc:493] ======= optimize end =======
W0712 09:09:59.122561  1843 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W0712 09:09:59.126153  1843 device_context.cc:260] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "test_client2.py", line 38, in <module>
    fetch=["multiclass_nms"])
  File "/usr/local/lib/python3.6/site-packages/paddle_serving_app/local_predict.py", line 127, in predict
    outputs = self.predictor.run(inputs)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::ConvOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const
3   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::NaiveExecutor::Run()
8   paddle::AnalysisPredictor::Run(std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> > const&, std::vector<paddle::PaddleTensor, std::allocator<paddle::PaddleTensor> >*, int)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/lib64/python2.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/lib64/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/paddle/fluid/layers/nn.py", line 1405, in conv2d
    "data_format": data_format,
  File "/PaddleDetection/ppdet/modeling/backbones/resnet.py", line 162, in _conv_norm
    name=_name + '.conv2d.output.1')
  File "/PaddleDetection/ppdet/modeling/backbones/resnet.py", line 430, in c1_stage
    name=_name)
  File "/PaddleDetection/ppdet/modeling/backbones/resnet.py", line 451, in __call__
    res = self.c1_stage(res)
  File "/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 89, in build
    body_feats = self.backbone(im)
  File "/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 248, in test
    return self.build(feed_vars, 'test')
  File "tools/export_model.py", line 108, in main
    test_fetches = model.test(feed_vars)
  File "tools/export_model.py", line 125, in <module>
    main()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: input and filter data type should be consistent
  [Hint: Expected input_data_type == filter_data_type, but received input_data_type:2 != filter_data_type:5.] at (/paddle/paddle/fluid/operators/conv_op.cc:173)
  [operator < conv2d > error]
W0712 09:10:02.100517  1923 device_tracer.cc:53] Invalid timestamp occurred. Please try increasing the FLAGS_multiple_of_cupti_buffer_size.

------------------------->     Profiling Report     <-------------------------

Place: All
Time unit: ms
Sorted by total time in descending order in the same thread

Total time: 303.444
  Computation time       Total: 201.3       Ratio: 66.3387%
  Framework overhead     Total: 102.143     Ratio: 33.6613%

-------------------------     GpuMemCpy Summary     -------------------------

GpuMemcpy                Calls: 172         Total: 83.4565     Ratio: 27.5031%
  GpuMemcpyAsync         Calls: 3           Total: 3.2345      Ratio: 1.06593%
  GpuMemcpySync          Calls: 169         Total: 80.222      Ratio: 26.4372%

-------------------------       Event Summary       -------------------------

Event                                   Calls       Total       CPU Time (Ratio)        GPU Time (Ratio)        Min.        Max.        Ave.        Ratio.      
thread0::load                           169         202.819     202.819352 (1.000000)   0.000000 (0.000000)     0.017028    164.441     1.20011     0.668392    
thread0::GpuMemcpySync:CPU->GPU         169         80.222      40.694908 (0.507279)    39.527102 (0.492721)    0.011679    23.2058     0.474686    0.264372    
thread0::conv2d                         1           17.1275     17.127503 (1.000000)    0.000000 (0.000000)     17.1275     17.1275     17.1275     0.0564438   
thread0::GpuMemcpyAsync:CPU->GPU        3           3.2345      1.820567 (0.562860)     1.413929 (0.437140)     0.011064    3.19608     1.07817     0.0106593   
thread0::feed                           3           0.040244    0.040244 (1.000000)     0.000000 (0.000000)     0.006155    0.025493    0.0134147   0.000132624 
[root@c99a526ec87f paddle]# 
```

**Comment by mcl-stone** [comment]
test_client.py脚本内容如下：
```shell
from paddle_serving_app.local_predict import Debugger
from paddle_serving_client import Client
from paddle_serving_app.reader import *
import sys
import numpy as np

preprocess = Sequential([
File2Image(), BGR2RGB(), Div(255.0),
Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225], False),
Resize(640, 640), Transpose((2, 0, 1))
])

postprocess = RCNNPostprocess("label_list.txt", "output")
debugger = Debugger()

debugger.load_model_config("pddet_serving_model", gpu=True)

im = preprocess("000000570688.jpg")
fetch_map = debugger.predict(
feed={
"image": im,
"im_shape": np.array(list(im.shape[1:]) + [1.0]),
"im_info": np.array(list(im.shape[1:]) + [1.0])
},
fetch=["multiclass_nms"])
#fetch_map["image"] = sys.argv[3]
#postprocess(fetch_map)
```

**Comment by mapingshuo** [comment]
请问这个是NLP模型、图像模型，或者您自己组的网。如何快速复现您的问题？

**Comment by mapingshuo** [comment]
经查看，这个代码是Paddle Serving的demo之一: https://github.com/PaddlePaddle/Serving/tree/develop/python/examples/faster_rcnn_model
建议先在Serving库下提issue，如果仍解决不了问题，我们继续讨论。

**Comment by mcl-stone** [comment]
好的好的
