### ISSUE TITLE
TypeError: object of type 'paddle.fluid.core_avx.LoDTensor' has no len() 错误

### ISSUE THREAD

**Issue by dancingpipi** [PaddlePaddle/Paddle#25508]
![image](https://user-images.githubusercontent.com/20511825/87317026-0a130000-c559-11ea-893d-05a0fd02006f.png)
![image](https://user-images.githubusercontent.com/20511825/87317102-244cde00-c559-11ea-9103-e5f351ebd93a.png)

用的pyreader, 请问下这个报错是什么原因？

**Comment by frankwhzhang** [comment]
请问这个自己的Model还是models下面的模型 报错信息也完整发一下吧

**Comment by dancingpipi** [comment]
> 请问这个自己的Model还是models下面的模型 报错信息也完整发一下吧

```
2020-07-14 02:42:15,261-WARNING: Your decorated reader has raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.7_torch1.3_cuda10.0/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/py3.7_torch1.3_cuda10.0/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/py3.7_torch1.3_cuda10.0/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 491, in __provider_thread__
    six.reraise(*sys.exc_info())
  File "/root/miniconda3/envs/py3.7_torch1.3_cuda10.0/lib/python3.7/site-packages/six.py", line 696, in reraise
    raise value
  File "/root/miniconda3/envs/py3.7_torch1.3_cuda10.0/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 472, in __provider_thread__
    for tensors in func():
  File "/root/miniconda3/envs/py3.7_torch1.3_cuda10.0/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 523, in __tensor_provider__
    for slots in paddle_reader():
  File "/root/miniconda3/envs/py3.7_torch1.3_cuda10.0/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 489, in __reader_creator__
    yield self.feed(item)
  File "/root/miniconda3/envs/py3.7_torch1.3_cuda10.0/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 326, in feed
    each_converter.feed(each_slot)
  File "/root/miniconda3/envs/py3.7_torch1.3_cuda10.0/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 121, in feed
    self._feed_impl_(data, self.lod, self.lod_level)
  File "/root/miniconda3/envs/py3.7_torch1.3_cuda10.0/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 127, in _feed_impl_
    lod[0].append(len(data))
TypeError: object of type 'paddle.fluid.core_avx.LoDTensor' has no len()
```
是自己改写的DeepFM模型

**Comment by dancingpipi** [comment]
feat_key是一个lod tensor，其他的是非lod tensor。
不加feat_key没问题，加上feat_key以后就会报错

**Comment by dlkht** [comment]
是什么原因呢
