### ISSUE TITLE
如何在动态图模式下让子类调用父类的方法

### ISSUE THREAD

**Issue by liu0haha123** [PaddlePaddle/Paddle#25512]
飞桨版本1.7.2 python3.6 
使用ERINE做ErnieModelForTokenClassification 时需要获取中间的变量 的 pool，encoded
pooled, encoded = super(ErnieModelForTokenClassification, self).forward(*args, **kwargs)

我使用
sequence_output,encoded = self.erine_for_token.ErnieModel.forward(src_ids=batch_data,sents_id = None,input_mask=batch_masks)

报错信息：

```
Traceback (most recent call last):
  File "D:\Anaconda\envs\paddle\lib\site-packages\fire\core.py", line 468, in _Fire
    target=component.__name__)
  File "D:\Anaconda\envs\paddle\lib\site-packages\fire\core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "E:/Paddlesanyuanzuchouqu/main.py", line 119, in train
    tags = F.dygraph.to_variable(tags).astype("float32")
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 461, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\Paddlesanyuanzuchouqu\models\ERINE_MUL_CNN.py", line 123, in forward
    sequence_output,encoded = self.erine_for_token.ErnieModel.forward(src_ids=batch_data,sents_id = None,input_mask=batch_masks)
  File "D:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 533, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'ErnieModelForTokenClassification' object has no attribute 'ErnieModel'
```

如何调用ErnieModel的forward方法

**Comment by Meiyim** [comment]
让子类调用父类方法跟动态图没有关系，这个属于python问题。
任何时候在python子类函数中调用`super().method(...)`即可调用父类方法。

因此比较好的思路是继承`ErnieModelForTokenClassification` 并改写forward方法。

**Comment by liu0haha123** [comment]
```
class ErnieModelForTokenClassification_new(ErnieModelForTokenClassification):

    def __init__(self,cfg,name):
        super(ErnieModelForTokenClassification_new, self).__init__(cfg,name)

    def forward(self,*args,**kwargs):
        pooled, encoded = super(ErnieModelForTokenClassification, self).forward(*args,**kwargs)
        hidden = self.dropout(encoded)
        logits = self.classifier(hidden)

        return pooled,encoded,logits
```

解决方案 仅供参考
