### ISSUE TITLE
Blocking queue is killed because the data reader raises an exception，在使用ai studio训练时，报的这个错误  

### ISSUE THREAD

**Issue by a-zhui** [PaddlePaddle/Paddle#25569]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by baiyfbupt** [comment]
您好，现在的信息不足以定位问题，麻烦贴下出问题的aistudio链接，完整错误log

**Comment by a-zhui** [comment]
> 您好，现在的信息不足以定位问题，麻烦贴下出问题的aistudio链接，完整错误log

```bash
[2020-07-16 20:22:03,002] [    INFO] - Strategy with slanted triangle learning rate, L2 regularization, 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:804: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
[2020-07-16 20:22:05,381] [    INFO] - Try loading checkpoint from cv_finetune_turtorial_demo/ckpt.meta
[2020-07-16 20:22:05,382] [    INFO] - PaddleHub model checkpoint not found, start from scratch...
[2020-07-16 20:22:05,434] [    INFO] - PaddleHub finetune start
[2020-07-16 20:22:06,880] [   TRAIN] - step 10 / 1756: loss=2.26287 acc=0.22500 [step/sec: 7.92]
[2020-07-16 20:22:06,881] [    INFO] - Evaluation on dev dataset start
share_vars_from is set, scope is ignored.
2020-07-16 20:22:14,593-WARNING: Your reader has raised an exception!
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 805, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 785, in __thread_main__
    for tensors in self._tensor_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/reader/cv_reader.py", line 164, in _data_reader
    image = preprocess(image_path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/reader/cv_reader.py", line 113, in preprocess
    image = Image.open(image_path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/PIL/Image.py", line 2766, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: 'dog10/'

---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-10-035a73d4265a> in <module>
----> 1 run_states = task.finetune_and_eval()
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune_and_eval(self)
    861 
    862     def finetune_and_eval(self):
--> 863         return self.finetune(do_eval=True)
    864 
    865     def finetune(self, do_eval=False):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in finetune(self, do_eval)
    882                 while self.current_epoch <= self.config.num_epoch:
    883                     self.config.strategy.step()
--> 884                     run_states = self._run(do_eval=do_eval)
    885                     self.env.current_epoch += 1
    886 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
   1095 
   1096                     if do_eval and self.current_step % self.config.eval_interval == 0:
-> 1097                         self._eval_interval_event()
   1098 
   1099                 self._run_step_event(step_run_state)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in hook_function(self, *args)
    628             for name, func in self._hooks[hook_type].items():
    629                 if inspect.ismethod(func):
--> 630                     func(*args)
    631                 else:
    632                     partial(func, self)(*args)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _default_eval_interval_event(self)
    780 
    781     def _default_eval_interval_event(self):
--> 782         self.eval(phase="dev")
    783 
    784     def _default_run_step_event(self, run_state):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in eval(self, phase, load_best_model)
    919                 self.init_if_necessary()
    920             self._eval_start_event()
--> 921             run_states = self._run()
    922             self._eval_end_event(run_states)
    923             return run_states
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py in _run(self, do_eval)
   1066             period_run_states = []
   1067 
-> 1068             for run_step, batch in enumerate(data_reader(), start=1):
   1069                 step_run_state = RunState(len(self.fetch_list))
   1070                 step_run_state.run_step = 1
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py in __next__(self)
    755                 return self._reader.read_next_list()
    756             else:
--> 757                 return self._reader.read_next()
    758         except StopIteration:
    759             self._queue.close()
EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
```

**Comment by baiyfbupt** [comment]
> IsADirectoryError: [Errno 21] Is a directory: 'dog10/'

应该是这里引起的，数据集路径配置错误。
这个数据是你自行修改的吗？如果是请再检查下数据路径的配置是否正确。如果不是麻烦贴一下这个aistudio任务链接，我找相关同学修复下，谢谢~

**Comment by a-zhui** [comment]
我用的是AI Studio上的数据集，我检查了，但没有发现错误（这个任务是用resnet_v2_50_imagenet进行finetune）。https://aistudio.baidu.com/aistudio/projectdetail/633782 这是链接，那谢谢了

**Comment by baiyfbupt** [comment]
![image](https://user-images.githubusercontent.com/28884066/87750298-a2e19e00-c82d-11ea-9f1b-b5d04e7f48cc.png)
这个项目我看不到，你可以看到这个项目的创建人吗？我来联系下

**Comment by a-zhui** [comment]
创始人就是我，已经公开了，

**Comment by baiyfbupt** [comment]
那建议检查下数据集和数据路径的配置是否正确吧？重点看下报错信息中的这两个问题
OSError: cannot identify image file 'dog10/3/Niutougeng-123626392.html'
IsADirectoryError: [Errno 21] Is a directory: 'dog10/'

**Comment by a-zhui** [comment]
OSError: cannot identify image file 'dog10/3/Niutougeng-123626392.html'文件夹里的这个错误文件都删除了，但我想问一下IsADirectoryError: [Errno 21] Is a directory: 'dog10/'，这个问题怎么解决

**Comment by baiyfbupt** [comment]
image = Image.open(image_path) 在这一步时本应打开一个文件路径，但是传的参数是个目录导致报错，建议查下reader里面是否有用法错误的

**Comment by a-zhui** [comment]
好的，谢谢
