### ISSUE TITLE
batch_norm_grad error: No Output(X@GRAD) found for BatchNormGrad operator

### ISSUE THREAD

**Issue by flishwang** [PaddlePaddle/Paddle#25686]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】
无相似问题

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：batch_norm_grad error: No Output(X@GRAD) found for BatchNormGrad operator
- 版本、环境信息：
    1）PaddlePaddle版本：conda 1.8.3-gpu
    3）GPU：预测若用GPU，RTX 2080Ti, cuda 10.0 + cudnn 7.6
    4）系统环境：Ubuntu16.04, python3.7

- 训练信息
    1）单机，单卡
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段

使用PaddleDetection 1.8版本，更改ResNet部分代码如下：

            conv.stop_gradient=True
            out = fluid.layers.batch_norm(
                input=conv,
                act=act,
                name=bn_name + '.output.1',
                param_attr=pattr,
                bias_attr=battr,
                moving_mean_name=bn_name + '_mean',
                moving_variance_name=bn_name + '_variance',
                use_global_stats=True)
            scale = fluid.framework._get_var(pattr.name)
            bias = fluid.framework._get_var(battr.name)
            #out.stop_gradient = True

            out2 = fluid.layers.batch_norm(
                input=conv,
                act=act,
                name=bn_name+'.output.1c',
                param_attr=cpattr,
                bias_attr=cbattr,
                moving_mean_name=bn_name+'_c_mean',
                moving_variance_name=bn_name+'_c_variance',
                use_global_stats=False,
            )

            loss =fluid.layers.smooth_l1(x=out2,y=out,sigma=1.0)
            self.loss.append(loss)

使用tools/train.py进行训练，遇到如下错误：

2020-07-23 15:35:51,499-INFO: set base learning_rate to 0.001875
Traceback (most recent call last):
  File "tools/train.py", line 424, in <module>
    main()
  File "tools/train.py", line 176, in main
    optimizer.minimize(loss)
  File "<decorator-gen-66>", line 2, in minimize
  File "/home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 277, in __impl__
    return func(*args, **kwargs)
  File "/home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 835, in minimize
    no_grad_set=no_grad_set)
  File "/home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 678, in backward
    act_no_grad_set, callbacks)
  File "/home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/backward.py", line 1416, in append_backward
    grad_info_map)
  File "/home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/backward.py", line 1116, in _append_backward_vars_
    op_desc.infer_shape(block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::BatchNormGradOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/bwang/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 4207, in batch_norm
    type="batch_norm", inputs=inputs, outputs=outputs, attrs=attrs)
  File "/home/bwang/projects/sniper-paddle/ppdet/modeling/backbones/resnet_fixbn.py", line 274, in _conv_norm
    use_global_stats=False,
  File "/home/bwang/projects/sniper-paddle/ppdet/modeling/backbones/resnet_fixbn.py", line 377, in bottleneck
    gcb_name=gcb_name)
  File "/home/bwang/projects/sniper-paddle/ppdet/modeling/backbones/resnet_fixbn.py", line 464, in layer_warp
    gcb_name=gcb_name)
  File "/home/bwang/projects/sniper-paddle/ppdet/modeling/backbones/resnet_fixbn.py", line 533, in __call__
    res = self.layer_warp(res, i)
  File "/home/bwang/projects/sniper-paddle/ppdet/modeling/architectures/compare.py", line 100, in build
    body_feats,body_loss = self.backbone(im)
  File "/home/bwang/projects/sniper-paddle/ppdet/modeling/architectures/compare.py", line 347, in train
    return self.build(feed_vars, 'train')
  File "tools/train.py", line 166, in main
    train_fetches = model.train(feed_vars)
  File "tools/train.py", line 424, in <module>
    main()

----------------------
Error Message Summary:
----------------------
NotFoundError: No Output(X@GRAD) found for BatchNormGrad operator.
  [Hint: Expected ctx->HasOutput(framework::GradVarName("X")) == true, but received ctx->HasOutput(framework::GradVarName("X")):0 != true:1.] at (/paddle/paddle/fluid/operators/batch_norm_op.cc:466)
  [operator < batch_norm_grad > error]

**Comment by ceci3** [comment]
应该是bn的输入stop_gradient=True，导致的报错，网络这样改的目的是想更新bn的参数，但是梯度不继续回传吗？

**Comment by flishwang** [comment]
> 应该是bn的输入stop_gradient=True，导致的报错，网络这样改的目的是想更新bn的参数，但是梯度不继续回传吗？

感谢！应该是这里出的问题。对的，我是要固定整个网络，只更新bn的参数。

我把代码改成：
conv.stop_gradient=True
conv += 0.0
后，问题解决。

但这只是个workaround的方法。请问这是个bug吗？
