### ISSUE TITLE
报错：ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by 1830789843** [PaddlePaddle/Paddle#25700]
(初始版本：
python=2.7.14,
paddle=1.6.3)
版本升级后python=2.7.18、paddle=1.8.3发生如下错误：

/tools/python-paddle-dev/lib/python2.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "train.py", line 315, in <module>
    train(args)
  File "train.py", line 296, in train
    save_infer_params_filename = args.model_name+'.params', pair_key=args.pair_key)
  File "/home/disk2/wangxiaoxiao/imtxt-paddle/image_text_match_paddle/util/paddle_util.py", line 277, in train_with_pyreader_and_val
    train_outs = train_exe.run(train_prog, fetch_list=train_fetch_list, use_program_cache=True)
  File "/home/disk2/wangxiaoxiao/projects/tools/python-paddle-dev/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/disk2/wangxiaoxiao/projects/tools/python-paddle-dev/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/disk2/wangxiaoxiao/projects/tools/python-paddle-dev/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/disk2/wangxiaoxiao/projects/tools/python-paddle-dev/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1232, in _run_program
    False)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::BatchNormKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
8   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/disk2/wangxiaoxiao/projects/tools/python-paddle-dev/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/disk2/wangxiaoxiao/projects/tools/python-paddle-dev/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/disk2/wangxiaoxiao/projects/tools/python-paddle-dev/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 4207, in batch_norm
    type="batch_norm", inputs=inputs, outputs=outputs, attrs=attrs)
  File "/home/disk2/wangxiaoxiao/imtxt-paddle/image_text_match_paddle/models/modules/resnet_model.py", line 145, in conv_bn_layer
    moving_variance_name=bn_name + '_variance', )
  File "/home/disk2/wangxiaoxiao/imtxt-paddle/image_text_match_paddle/models/modules/resnet_model.py", line 61, in net
    name="conv1")
  File "/home/disk2/wangxiaoxiao/imtxt-paddle/image_text_match_paddle/models/image_text.py", line 73, in build_model
    self.image_emb = image_model.net(input=self.get_input("image"), name="image")
  File "train.py", line 78, in train
    train_model.build_model()
  File "train.py", line 315, in <module>
    train(args)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_BAD_PARAM  at (/paddle/paddle/fluid/operators/batch_norm_op.cu:319)
  [operator < batch_norm > error]
INFO 2020-07-24 15:23:11,283 utils.py:269] terminate all the procs
ERROR 2020-07-24 15:23:11,283 utils.py:413] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2020-07-24 15:23:14,286 utils.py:269] terminate all the procs

**Comment by qingqing01** [comment]
@1830789843  

> The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.0


你需要升级本地机器上的cuDNN版本至7.6。
