### ISSUE TITLE
目标检测框架下运行20000左右iter以后出现Error: Blocking queue is killed because the data reader raises an exception

### ISSUE THREAD

**Issue by Sephirothought** [PaddlePaddle/Paddle#25721]
我正在参加Paddle的目标检测比赛，尝试了几种CascadeRCNN和fasterRCNN方法，但令人崩溃的是调用这些yml 都会在一开始顺利运行，但在运行了20000iter左右以后出现报错情况，如下所示：
2020-07-25 13:24:32,980-INFO: iter: 16240, lr: 0.010000, 'loss_cls': '0.033885', 'loss_bbox': '0.046580', 'loss_rpn_cls': '0.002377', 'loss_rpn_bbox': '0.001451', 'loss': '0.077764', time: 0.413, eta: 1 day, 5:06:38
2020-07-25 13:24:41,208-INFO: iter: 16260, lr: 0.010000, 'loss_cls': '0.033792', 'loss_bbox': '0.043076', 'loss_rpn_cls': '0.002728', 'loss_rpn_bbox': '0.001324', 'loss': '0.077766', time: 0.412, eta: 1 day, 5:01:31
2020-07-25 13:24:42,049-INFO: fail to map op [AutoAugmentImage_6e507b] with error: tuple index out of range and stack:
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/reader.py", line 45, in __call__
    data = f(data, ctx)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/operators.py", line 498, in __call__
    self.autoaug_type)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 1588, in distort_image_with_autoaugment
    augmentation_hparams)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 1550, in build_and_apply_nas_policy
    tf_policies, image, bboxes)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 1498, in select_and_apply_random_policy
    image, bboxes = policy(image, bboxes)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 1542, in final_policy
    prob, bboxes_)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 1486, in _apply_func_with_prob
    augmented_image, augmented_bboxes = func(image, bboxes, *args)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 733, in shear_y_only_bboxes
    image, bboxes, prob, shear_y, func_changes_bbox, level, replace)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 708, in _apply_multi_bbox_augmentation_wrapper
    new_image, new_bboxes, prob, aug_func, func_changes_bbox, *args)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 689, in _apply_multi_bbox_augmentation
    idx, (image, new_bboxes) = body(idx, (image, new_bboxes))
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 687, in <lambda>
    _images_and_bboxes[1])]
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 657, in <lambda>
    wrapped_aug_func = lambda _image, bbox, _new_bboxes: _apply_bbox_augmentation_wrapper(_image, bbox, _new_bboxes, prob, aug_func, func_changes_bbox, *args)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 613, in _apply_bbox_augmentation_wrapper
    augmentation_func, *args)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 537, in _apply_bbox_augmentation
    augmented_bbox_content = augmentation_func(bbox_content, *args)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 959, in shear_y
    return unwrap(np.array(image), replace)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/transform/autoaugment_utils.py", line 1167, in unwrap
    flattened_image = np.reshape(image, [-1, image_shape[2]])
IndexError: tuple index out of range

2020-07-25 13:24:43,667-WARNING: recv endsignal from outq with errmsg[consumer[consumer-e8f-1] failed to map with error:[tuple index out of range]]
2020-07-25 13:24:45,319-WARNING: recv endsignal from outq with errmsg[consumer[consumer-e8f-0] exits for reason[consumer[consumer-e8f-1] failed to map with error:[tuple index out of range]]]
2020-07-25 13:24:45,320-WARNING: Your reader has raised an exception!
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1156, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1136, in __thread_main__
    for tensors in self._tensor_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1206, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 505, in __reader_creator__
    for item in reader():
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/reader.py", line 421, in _reader
    reader.reset()
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/data/parallel_map.py", line 259, in reset
    assert not self._exit, "cannot reset for already stopped dataset"
AssertionError: cannot reset for already stopped dataset

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 364, in <module>
    main()
  File "tools/train.py", line 237, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1078, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 976, in __init__
    self._init_non_iterable()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 608, in from_generator
    iterable, return_list, drop_last)
  File "/home/aistudio/work/PaddleDetection_traffic/ppdet/modeling/architectures/faster_rcnn.py", line 236, in build_inputs
    iterable=iterable) if use_dataloader else None
  File "tools/train.py", line 108, in main
    feed_vars, train_loader = model.build_inputs(**inputs_def)
  File "tools/train.py", line 364, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

#########################################分割线#################################################

我的yml配置文件之一：基于hanceRCNN下的yml,GPU是单卡V100

architecture: FasterRCNN
max_iters: 270000
snapshot_iter: 30000
use_gpu: true
log_smooth_window: 20
log_iter: 20
save_dir: output
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_ssld_pretrained.tar
weights: output/faster_rcnn_dcn_r50_vd_fpn_3x_server_side/model_final
metric: traffic
# If set `true`, for traffic output json
#save_prediction_only: true
save_prediction_only: false
num_classes: 20

FasterRCNN:
  backbone: ResNet
  fpn: FPN
  rpn_head: FPNRPNHead
  roi_extractor: FPNRoIAlign
  bbox_head: BBoxHead
  bbox_assigner: LibraBBoxAssigner

ResNet:
  depth: 50
  feature_maps: [2, 3, 4, 5]
  freeze_at: 2
  norm_type: bn
  variant: d
  dcn_v2_stages: [3, 4, 5]
  lr_mult_list: [0.05, 0.05, 0.1, 0.15]

FPN:
  max_level: 6
  min_level: 2
  num_chan: 64
  spatial_scale: [0.03125, 0.0625, 0.125, 0.25]

FPNRPNHead:
  anchor_generator:
    # anchor_sizes: [32, 64, 128, 256, 512]
    anchor_sizes: [16, 32, 64, 128, 256]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 8
  max_level: 6
  min_level: 2
  num_chan: 64
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    post_nms_top_n: 2000
    pre_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    post_nms_top_n: 1000
    pre_nms_top_n: 1000

FPNRoIAlign:
  canconical_level: 4
  canonical_size: 224
  max_level: 5
  min_level: 2
  box_resolution: 7
  sampling_ratio: 2

LibraBBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5

BBoxHead:
  head: TwoFCHead
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05
  bbox_loss: DiouLoss

DiouLoss:
  loss_weight: 10.0
  is_cls_agnostic: false
  use_complete_iou_loss: true

TwoFCHead:
  mlp_dim: 1024

LearningRate:
  # base_lr: 0.02
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [120000, 180000, 240000]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 2000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

TrainReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd']
  dataset:
    !TrafficDataSet
    image_dir: train/pic
    anno_path: tag/train/
    dataset_dir: ../../data/traffic_data/
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !RandomFlipImage
    prob: 0.5
  - !AutoAugmentImage
    autoaug_type: v1
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    target_size: [576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120]
    max_size: 1333
    interp: 1
    use_cv2: true
  - !Permute
    to_bgr: false
    channel_first: true
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: false
  batch_size: 4
  shuffle: true
  worker_num: 2
  use_process: false

TestReader:
  inputs_def:
    # for traffic output json
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: None
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: true
  batch_size: 1
  shuffle: false

EvalReader:
  inputs_def:
    # for traffic output json
    fields: ['image', 'im_info', 'im_id', 'im_shape']
    # for traffic calculate mAP
    # fields: ['image', 'im_info', 'im_id',  'im_shape', 'gt_bbox', 'gt_class']
  dataset:
    !TrafficDataSet
    # a. for traffic calculate mAP
    image_dir: valid/pic/
    # b. for traffic output json
    # image_dir: test/pic/
    # a. for traffic calculate mAP
    anno_path: tag/valid/
    # b. for traffic output json
    # anno_path: test/input/
    dataset_dir: ../../data/traffic_data
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    max_size: 1333
    target_size: 800
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: true
  batch_size: 1
  shuffle: false
  drop_empty: false
  worker_num: 2

我想死了找不到出问题的原因在哪里，希望可以得到一些来自大神的解答

**Comment by luotao1** [comment]
可以去 https://github.com/PaddlePaddle/Paddledetection 提问，会更有针对性

**Comment by luotao1** [comment]
duplication with https://github.com/PaddlePaddle/PaddleDetection/issues/1112
