### ISSUE TITLE
安装完成后，验证时时报错：ImportError: cannot import name '_imaging'

### ISSUE THREAD

**Issue by yuewuya20180928** [PaddlePaddle/Paddle#25722]
1）PaddlePaddle版本：1.8
    2）CPU：X86_64
    3）GPU：无
    4）系统环境：ubuntu20 python3.5
(paddle-venv) yuewuya@yuewuya-RedmiBook-14:~/Public/openSource/Paddle/build/python/dist$ python3.5
Python 3.5.9 (default, Apr 18 2020, 00:56:51) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuewuya/.local/lib/python3.5/site-packages/paddle/__init__.py", line 31, in <module>
    import paddle.dataset
  File "/home/yuewuya/.local/lib/python3.5/site-packages/paddle/dataset/__init__.py", line 30, in <module>
    import paddle.dataset.voc2012
  File "/home/yuewuya/.local/lib/python3.5/site-packages/paddle/dataset/voc2012.py", line 29, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 69, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging'
>>>

**Comment by yuxianhao-shu** [comment]
怎么解决的啊，我也遇到了这个问题
