### ISSUE TITLE
PaddleDetection安装后测试例子无法通过got an unexpected keyword argument 'scale_x_y'

### ISSUE THREAD

**Issue by wangleilei001** [PaddlePaddle/Paddle#25888]
安装后测试例子无法通过，报错如下

`
\[work@hostname PaddleDetection\]$ python3 ppdet/modeling/tests/test_architectures.py
ss........EE
======================================================================
ERROR: test_test (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/work/wangleilei01/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 57, in test_test
    test_fetches = model.eval(feed_vars)
  File "/home/work/wangleilei01/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 162, in eval
    return self.build(feed_vars, mode='test')
  File "/home/work/wangleilei01/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 93, in build
    body_feats, im_size, exclude_nms=exclude_nms)
  File "/home/work/wangleilei01/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 437, in get_prediction
    scale_x_y=scale_x_y)
TypeError: yolo_box() got an unexpected keyword argument 'scale_x_y'

======================================================================
ERROR: test_train (__main__.TestYolov3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/work/wangleilei01/PaddleDetection/ppdet/modeling/tests/decorator_helper.py", line 29, in __fn__
    fn(*args, **kwargs)
  File "ppdet/modeling/tests/test_architectures.py", line 49, in test_train
    train_fetches = model.train(feed_vars)
  File "/home/work/wangleilei01/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 159, in train
    return self.build(feed_vars, mode='train')
  File "/home/work/wangleilei01/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 85, in build
    gt_score, targets)
  File "/home/work/wangleilei01/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 401, in get_loss
    self.prefix_name)
  File "/home/work/wangleilei01/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 88, in __call__
    name=prefix_name + "yolo_loss" + str(i))
TypeError: yolov3_loss() got an unexpected keyword argument 'scale_x_y'

----------------------------------------------------------------------
Ran 12 tests in 5.219s
`

**Comment by qingqing01** [comment]
@cucuzg  

如果您使用的PaddleDetection release/0.4 or master版本，其中的YOLOv3需要使用 2.0.alpha版本或develop的每日版本，参考https://github.com/PaddlePaddle/PaddleDetection/issues/1103#issuecomment-663858241

如果是想使用pp-yolo模型: 需要使用develop的每日版本

其他模型使用release/1.8.1, release/1.8.2, release/1.8.3版本都可以。 

有问题，也可以到PaddleDetection的repo提问。

**Comment by wangleilei001** [comment]
@qingqing01 
感谢，已安装2.0.0a0。问题暂时看来已解决。

安装命令：pip install paddlepaddle==2.0.0a0

**Comment by heavengate** [comment]
感谢反馈，已修复，https://github.com/PaddlePaddle/PaddleDetection/pull/1147  可以pull一下最新代码~
