### ISSUE TITLE
cudnn使用报错

### ISSUE THREAD

**Issue by NameLacker** [PaddlePaddle/Paddle#25909]
W0803 15:56:39.833251 27062 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 11.0, Runtime API Version: 9.0
W0803 15:56:39.835793 27062 device_context.cc:260] device: 0, cuDNN Version: 7.6.
Begain training,times is: Mon Aug  3 15:56:40 2020
/home/lacker/anaconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "/home/lacker/anaconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/lacker/anaconda3/envs/paddle-gpu/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/lacker/anaconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/lacker/anaconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/lacker/anaconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::CUDNNConvOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvOpKernel<float>, paddle::operators::CUDNNConvOpKernel<double>, paddle::operators::CUDNNConvOpKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
8   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
9   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/lacker/anaconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/lacker/anaconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/lacker/anaconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 2938, in conv2d
    "data_format": data_format,
  File "/home/lacker/work/dectations/paddle_demo/classifer/mobilenet_v1.py", line 15, in conv_bn_layer
    bias_attr=bias_attr)
  File "/home/lacker/work/dectations/paddle_demo/classifer/mobilenet_v1.py", line 241, in net2
    padding=3)
  File "/home/lacker/work/dectations/paddle_demo/classifer/train.py", line 24, in train
    model = mobilenet_v1.net2(image, num)
  File "/home/lacker/work/dectations/paddle_demo/classifer/train.py", line 142, in train_classifcation
    return train(stop_train, num=num)
  File "/home/lacker/work/dectations/paddle_demo/classifer/demo.py", line 29, in train
    train_acc, train_cost, test_acc, test_cost, save_path = train_classifcation(stop_train = False, image_dir=image_dir)
  File "/home/lacker/work/dectations/paddle_demo/classifer/demo.py", line 91, in <module>
    train()
  File "/home/lacker/pycharm/pycharm-community-2020.1.4/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/lacker/pycharm/pycharm-community-2020.1.4/plugins/python-ce/helpers/pydev/pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/lacker/pycharm/pycharm-community-2020.1.4/plugins/python-ce/helpers/pydev/pydevd.py", line 1431, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/lacker/pycharm/pycharm-community-2020.1.4/plugins/python-ce/helpers/pydev/pydevd.py", line 2122, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/lacker/pycharm/pycharm-community-2020.1.4/plugins/python-ce/helpers/pydev/pydevd.py", line 2131, in <module>
    main()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  at (/paddle/paddle/fluid/operators/conv_cudnn_op.cu:300)
  [operator < conv2d > error]

**Comment by wzzju** [comment]
请附录代码、paddle版本信息以及硬件信息等。以上错误信息很难定位问题。

**Comment by wzzju** [comment]
您好！可以更新一下CUDNN版本，比如7.6版本。
