### ISSUE TITLE
[论文复现] 看不懂的异常消息

### ISSUE THREAD

**Issue by weiexcelpro** [PaddlePaddle/Paddle#26410]
复现时出现以下报错：看不懂，并且百度不到，望指教
Traceback (most recent call last):
  File "main.py", line 129, in <module>
    train_logger, train_batch_logger)
  File "/home/aistudio/train.py", line 32, in train_epoch
    outputs = model(inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 460, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/models/resnet.py", line 200, in forward
    x = self.conv1(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 460, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/nn.py", line 464, in forward
    'use_mkldnn': False
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2601, in append_op
    kwargs.get("stop_gradient", False))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    not stop_gradient)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Python object is not type of St10shared_ptrIN6paddle10imperative7VarBaseEE at (/paddle/paddle/fluid/pybind/imperative.cc:164)

源码

[737640.zip](https://github.com/PaddlePaddle/Paddle/files/5090597/737640.zip)

**Comment by xjhcassy** [comment]
同问，我也遇到这个问题

**Comment by bjjwwang** [comment]
好的 我马上复现下

**Comment by liu824** [comment]
我也遇到这个问题

**Comment by ymzlygw** [comment]
我也遇到这个问题，求解！不过我好像是因为数据类型不符造成这中异常错误，目前还不知道怎么将数据类numpy.ndarray转换为paddle.fluid.core_avx.VarBase类。你也有可能是数据类型不符造成的

**Comment by thunder95** [comment]
同问， 我也遇到了这个问题， 是在自定义算子时出现的， 哪位大佬能解答下？
