### ISSUE TITLE
模型还原训练问题，修改skpt.meta

### ISSUE THREAD

**Issue by ARDUJS** [PaddlePaddle/Paddle#26571]
### 环境
- AI Studio 
- paddle 1.7.2
- paddlehub 1.6
- python 3.7

### 意图
模型训练到了51000step，我想把模型还原到41000step，然后我修改了skpt.meta文件，修改后报错

![image](https://user-images.githubusercontent.com/20811685/90961416-5ac43400-e4db-11ea-9ab2-3dbe766ee4c1.png)

然后我还原skpt.meta文件，把其中41000更正为51000，依旧报错

### 报错内容
```
  File "/home/aistudio/work/R_3/Main.py", line 144, in <module>
    seq_label_task.finetune_and_eval()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 863, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 878, in finetune
    self.init_if_necessary()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 366, in init_if_necessary
    if not self.load_checkpoint():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 832, in load_checkpoint
    main_program=self.main_program)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/checkpoint.py", line 37, in load_checkpoint
    ckpt.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
```

**Comment by Steffy-zxf** [comment]
@ARDUJS 你好！请不要修改ckpt.meta文件。可以通过以下方式加载指定的参数：

```python
with seq_label_task.phase_guard('train'):
    seq_label_task.load_parameters('Path/to/Parameters')
```

**Comment by ARDUJS** [comment]
```
with seq_label_task.phase_guard('train'):
    seq_label_task.load_parameters('Path/to/Parameters')
```
> 报ckpt.meta的错误，有办法还原ckpt.meta吗
```
[2020-08-24 13:08:18,756] [    INFO] - Try loading checkpoint from models/relation_extraction_new_new_new_plus_rel_2_cnn/ckpt.meta
Traceback (most recent call last):
  File "submit.py", line 1, in <module>
    import Main
  File "/home/aistudio/work/R_3/Main.py", line 147, in <module>
    seq_label_task.finetune_and_eval()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 863, in finetune_and_eval
    return self.finetune(do_eval=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 878, in finetune
    self.init_if_necessary()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 366, in init_if_necessary
    if not self.load_checkpoint():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/task/base_task.py", line 832, in load_checkpoint
    main_program=self.main_program)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/finetune/checkpoint.py", line 37, in load_checkpoint
    ckpt.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
```

**Comment by Steffy-zxf** [comment]
meta文件有备份吗？有的话，可以恢复。没有的话，把meta文件删了，通过上述方式加载参数继续训练。

**Comment by ARDUJS** [comment]
好的谢谢，如果我想 只加载预训练部分的参数（比如bert层），不加载搭建在预训练后的网络参数，有办法吗？


 
---原始邮件---
发件人: "Steffy-zxf"<notifications@github.com&gt;
发送时间: 2020年8月25日 10:25:16
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"0_0_0_0__11000"<572915766@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 模型还原训练问题，修改skpt.meta (#26571)




 
meta文件有备份吗？有的话，可以恢复。没有的话，把meta文件删了，通过上述方式加载参数继续训练。

**Comment by Steffy-zxf** [comment]
为什么你只需要加载预训练（bert）参数，而不要预训练后的网络参数（比如分类任务的最后分类层参数）呢？

PaddleHub加载预训练模型，如`hub.Module(name='bert_uncased_L-12_H-768_A-12')`，就已经是已加载了原生的预训练参数值（不是Finetune之后的参数值）

**Comment by ARDUJS** [comment]
我想自己二次训练bert，
再套上分类的网络


 
---原始邮件---
发件人: "Steffy-zxf"<notifications@github.com&gt;
发送时间: 2020年8月25日 11:09:34
收件人: "PaddlePaddle/Paddle"<Paddle@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"0_0_0_0__11000"<572915766@qq.com&gt;;
主题: Re: [PaddlePaddle/Paddle] 模型还原训练问题，修改skpt.meta (#26571)




 
为什么你只需要加载预训练（bert）参数，而不要预训练后的网络参数（比如分类任务的最后分类层参数）呢？
 
PaddleHub加载预训练模型，如hub.Module(name='bert_uncased_L-12_H-768_A-12')，就已经是已加载了原生的预训练参数值（不是Finetune之后的参数值）

**Comment by Steffy-zxf** [comment]
> 二次训练bert，

二次训练bert的意思是指，你需要继续预训练bert吗？ 方便说说你的任务背景吗？

如果想要加载继续预训练的bert的参数，需要保证继续预训练后的bert所有参数名字和 hub的bert module，参数名字一致。之后使用`hub show bert_uncased_L-12_H-768_A-12`查看bert_uncased_L-12_H-768_A-12 module所在位置，替换其中参数文件assets/params。
