### ISSUE TITLE
【安装错误】conda安装环境，编译出现strip问题

### ISSUE THREAD

**Issue by yjmm10** [PaddlePaddle/Paddle#26680]
1）PaddlePaddle版本：paddle1.8.4
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：RTX2070 CUDA=9.0 CUDNN=7.3.1 (cuda、cudnn安装在conda上)
    4）系统环境：ubuntu19.10 python=3.7.7

- 安装方式信息：
1）conda
- 问题描述：按照官方安装教程，使用conda安装paddle,运行时出现
`>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tipray/Software/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/__init__.py", line 37, in <module>
    import paddle.complex
  File "/home/tipray/Software/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/complex/__init__.py", line 15, in <module>
    from . import tensor
  File "/home/tipray/Software/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/complex/tensor/__init__.py", line 15, in <module>
    from . import math
  File "/home/tipray/Software/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/complex/tensor/math.py", line 15, in <module>
    from paddle.common_ops_import import *
  File "/home/tipray/Software/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/common_ops_import.py", line 15, in <module>
    from paddle.fluid.layer_helper import LayerHelper
  File "/home/tipray/Software/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/home/tipray/Software/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/tipray/Software/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/core.py", line 226, in <module>
    if platform.system().lower() == 'linux' and less_than_ver(get_glibc_ver(),
  File "/home/tipray/Software/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/core.py", line 204, in get_glibc_ver
    return run_shell_command("ldd --version | awk '/ldd/{print $NF}'").strip()
AttributeError: 'NoneType' object has no attribute 'strip'
`
并且在Pycharm打开paddle的项目，同样会出现这个问题
系统环境变量已经设置conda 的paddle环境变量
`/home/tipray/Software/anaconda3/envs/paddle/bin:/home/tipray/Software/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-9.0/bin`

**Comment by zhiqiu** [comment]
hi，我提了一个PR修这个问题，你可以按[PR26693](https://github.com/PaddlePaddle/Paddle/pull/26693) 的方式修改下/home/tipray/Software/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/core.py文件试试。
