### ISSUE TITLE
Ubuntu18.04下安装paddle报错：Cublas error, CUBLAS_STATUS_EXECUTION_FAILED 

### ISSUE THREAD

**Issue by LiKangyuLKY** [PaddlePaddle/Paddle#26803]
- 标题：Ubuntu18.04下安装paddle报错：Cublas error, CUBLAS_STATUS_EXECUTION_FAILED 
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu==1.8.0.post107   paddlepaddle-gpu==1.8.4.post107  两个版本都试了
    2）GPU：CUDA和cudnn信息如下图：
![image](https://user-images.githubusercontent.com/42792466/91655129-222ae880-eae1-11ea-86c9-67442a669b77.png)
![image](https://user-images.githubusercontent.com/42792466/91655157-4ab2e280-eae1-11ea-8e3d-feffd4d4a16b.png)
![image](https://user-images.githubusercontent.com/42792466/91655167-5d2d1c00-eae1-11ea-91b3-c2fb4d564fcc.png)
    3）系统环境：Ubuntu18.04、Python3.6.9
- 安装方式信息：pip安装 
报错信息：
`>>> paddle.fluid.install_check.run_check()
Running Verify Fluid Program ...
W0830 16:41:39.113214  4532 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.2, Runtime API Version: 10.0
W0830 16:41:39.117029  4532 device_context.cc:260] device: 0, cuDNN Version: 7.6.
/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 122, in test_simple_exe
    fetch_list=[out0.name, param_grads[1].name])
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::GEMM<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) const
3   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, float, paddle::framework::Tensor*, float) const
4   paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
    stop_gradient=stop_gradient)
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/dygraph/nn.py", line 962, in forward
    type="matmul", inputs=inputs, outputs={"Out": tmp}, attrs=attrs)
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 460, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 41, in forward
    x = self._linear1(inputs)
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 460, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 113, in test_simple_exe
    out0 = simple_layer0(inp0)
  File "/home/ubuntu/NewDisk/liky/anaconda3/envs/pd/lib/python3.6/site-packages/paddle/fluid/install_check.py", line 124, in run_check
    test_simple_exe()
  File "<stdin>", line 1, in <module>

----------------------
Error Message Summary:
----------------------
ExternalError:  Cublas error, CUBLAS_STATUS_EXECUTION_FAILED  at (/paddle/paddle/fluid/operators/math/blas_impl.cu.h:34)
  [operator < matmul > error]
`
按照#24302的方式进行了测试，执行test，结果为：
![image](https://user-images.githubusercontent.com/42792466/91655267-ffe59a80-eae1-11ea-8ba3-b7f5c928cc2f.png)
输出PATH、LIBRARY_PATH 、LD_LIBRARY_PATH，结果为：
![image](https://user-images.githubusercontent.com/42792466/91655327-4f2bcb00-eae2-11ea-876a-36ce3d78e782.png)
使用cublas的测试代码进行测试，结果为：
![image](https://user-images.githubusercontent.com/42792466/91655353-89956800-eae2-11ea-8e73-d455df8ff150.png)

查了issue中的类似问题，还是没能解决

**Comment by jiweibo** [comment]
CUDA10.0版本好像是有BUG，linux环境下请尝试切换CUDA10.1版本

**Comment by LiKangyuLKY** [comment]
> CUDA10.0版本好像是有BUG，linux环境下请尝试切换CUDA10.1版本

是的，更换成CUDA10.1版本正常

**Comment by wumeng2** [comment]
> CUDA10.0版本好像是有BUG，linux环境下请尝试切换CUDA10.1版本
你好，请问支持cuda10.2吗？
