### ISSUE TITLE
使用AMD出现错误 paddle.fluid.core_avx.EnforceNotMet: Invoke operator matmul error.

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/Paddle#27012]
1）PaddlePaddle版本：paddlepaddle-gpu==1.5.1.post97
    2）CPU：AMD Ryzen 7 3700X 8-Core Processor × 16 
    3）GPU：Nvidia 2070 super ; CUDA=9.0 cuDnn = 7.6.5
    4）系统环境：Ubuntu 16.04 python = 3.7

报错信息：
```
I0904 09:06:13.223136  6845 parallel_executor.cc:329] The number of CUDAPlace, which is used in ParallelExecutor, is 1. And the Program will be copied 1 copies
I0904 09:06:13.228498  6845 build_strategy.cc:340] SeqOnlyAllReduceOps:0, num_trainers:1
[INFO] 2020-09-04 09:06:13,251 [ run_duie.py:  386]:	testing ./data/test.json, save to ./data/predict_dev.json
Traceback (most recent call last):
  File "./ernie/run_duie.py", line 406, in <module>
    main(args)
  File "./ernie/run_duie.py", line 316, in main
    prediction = predict_wrapper(reader, exe, test_prog, test_pyreader, graph_vars,'final', 'final')
  File "./ernie/run_duie.py", line 387, in predict_wrapper
    res = predict(args, examples, exe, test_prog, test_pyreader, graph_vars)
  File "/home/speedchina/Paddlepaddle/PaddleServing/DuIe_baseline/ernie/finetune/relation_extraction_multi_cls.py", line 444, in predict
    exe.run(program=test_program, fetch_list=fetch_list, return_numpy=False)
  File "/home/speedchina/anaconda3/envs/pp-1.5/lib/python3.7/site-packages/paddle/fluid/executor.py", line 651, in run
    use_program_cache=use_program_cache)
  File "/home/speedchina/anaconda3/envs/pp-1.5/lib/python3.7/site-packages/paddle/fluid/executor.py", line 749, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator matmul error.
Python Callstacks: 
  File "/home/speedchina/anaconda3/envs/pp-1.5/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1771, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/speedchina/anaconda3/envs/pp-1.5/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/speedchina/anaconda3/envs/pp-1.5/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 5255, in matmul
    'alpha': float(alpha),
  File "/home/speedchina/Paddlepaddle/PaddleServing/DuIe_baseline/ernie/model/ernie.py", line 144, in _build_model
    x=input_mask, y=input_mask, transpose_y=True)
  File "/home/speedchina/Paddlepaddle/PaddleServing/DuIe_baseline/ernie/model/ernie.py", line 97, in __init__
    input_mask)
  File "/home/speedchina/Paddlepaddle/PaddleServing/DuIe_baseline/ernie/finetune/relation_extraction_multi_cls.py", line 163, in create_model
    config=ernie_config)
  File "./ernie/run_duie.py", line 159, in main
    ernie_config=ernie_config)
  File "./ernie/run_duie.py", line 406, in <module>
    main(args)
C++ Callstacks: 
CUBLAS: execution failed,  at [/paddle/paddle/fluid/operators/math/blas_impl.cu.h:50]
PaddlePaddle Call Stacks: 
0       0x7f224f6da830p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f224f6daba9p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f224fabaa57p void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, float, paddle::framework::Tensor*, float) const + 1431
3       0x7f224fabafb9p paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 761
4       0x7f224fabb0c3p std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&) + 35
5       0x7f2251640f07p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 375
6       0x7f22516412e1p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 529
7       0x7f225163e8dcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
8       0x7f224f8656fep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 606
9       0x7f224f8686bfp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
10      0x7f224f6cbebdp
11      0x7f224f70d166p
12      0x55d5fa830c94p _PyMethodDef_RawFastCallKeywords + 612
13      0x55d5fa830db1p _PyCFunction_FastCallKeywords + 33
14      0x55d5fa89c9a1p _PyEval_EvalFrameDefault + 20945
15      0x55d5fa7e02b9p _PyEval_EvalCodeWithName + 761
16      0x55d5fa830497p _PyFunction_FastCallKeywords + 903
17      0x55d5fa898cbap _PyEval_EvalFrameDefault + 5354
18      0x55d5fa7e02b9p _PyEval_EvalCodeWithName + 761
19      0x55d5fa830497p _PyFunction_FastCallKeywords + 903
20      0x55d5fa898cbap _PyEval_EvalFrameDefault + 5354
21      0x55d5fa83020bp _PyFunction_FastCallKeywords + 251
22      0x55d5fa897be6p _PyEval_EvalFrameDefault + 1046
23      0x55d5fa83020bp _PyFunction_FastCallKeywords + 251
24      0x55d5fa897be6p _PyEval_EvalFrameDefault + 1046
25      0x55d5fa83020bp _PyFunction_FastCallKeywords + 251
26      0x55d5fa897be6p _PyEval_EvalFrameDefault + 1046
27      0x55d5fa7e02b9p _PyEval_EvalCodeWithName + 761
28      0x55d5fa7e11d4p PyEval_EvalCodeEx + 68
29      0x55d5fa7e11fcp PyEval_EvalCode + 28
30      0x55d5fa8f6f44p
31      0x55d5fa9012b1p PyRun_FileExFlags + 161
32      0x55d5fa9014a3p PyRun_SimpleFileExFlags + 451
33      0x55d5fa9025d5p
34      0x55d5fa9026fcp _Py_UnixMain + 60
35      0x7f229eb9e830p __libc_start_main + 240
36      0x55d5fa8a73c0p
```
在使用 Intel 的机器上程序可以正常运行;
除了更换CPU还有别的解决办法嘛？

**Comment by zhangting2020** [comment]
如果是旧版本的bug，在新版本中可能已解决。1.5版本比较低了，方便用1.8版本测试一下吗？

**Comment by iceriver97** [comment]
@zhangting2020 谢谢。但是我之前尝试过将环境升级到 1.8+的版本，有一个函数可能存在差异，我没能解决改写的问题；
函数：`fluid.layers.sequence_unpad`
代码：
```
pyreader = fluid.layers.py_reader(
        capacity=50,
        shapes=[[-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
                [-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1],
                [-1, args.max_seq_len, 1],
                [-1, args.max_seq_len, args.num_labels], [-1, 1], [-1, 1],
                [-1, args.max_seq_len, 1], [-1, args.max_seq_len, 1]],
        dtypes=[
            'int64', 'int64', 'int64', 'int64', 'float32', 'float32', 'int64',
            'int64', 'int64', 'int64'
        ],
        lod_levels=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        name=pyreader_name,
        use_double_buffer=True)
(src_ids, sent_ids, pos_ids, task_ids, input_mask, labels, seq_lens,
     example_index, tok_to_orig_start_index,
     tok_to_orig_end_index) = fluid.layers.read_file(pyreader)
 lod_labels = fluid.layers.sequence_unpad(labels, seq_lens)
```
在1.5的版本 labels 的维度(-1, 512, 112) -> (-1, 112)
我没能修改代码在1.8中达到相同的效果，我应该如何修改 shapes呢？您能帮我一下吗？非常感谢

**Comment by zhangting2020** [comment]
在1.8版本中，sequence_unpad接口的length参数说明为：存储每个样本实际长度信息的1D Tesnor，该Tensor维度的第0维必须与x维度的第0维一致。支持的数据类型：int64。
你的代码中，seq_lens的shape为[-1, 1]，是2D的。需要改为[-1]这样第0维才与labels的第0维相同

**Comment by iceriver97** [comment]
@zhangting2020  非常感谢，这种改法我尝试过，这会提示seq_lens依旧是2维的；报错信息如下：
```
Traceback (most recent call last):
  File "./ernie/run_duie.py", line 401, in <module>
    main(args)
  File "./ernie/run_duie.py", line 315, in main
    prediction = predict_wrapper(reader, exe, test_prog, test_pyreader, graph_vars,'final', 'final')
  File "./ernie/run_duie.py", line 385, in predict_wrapper
    res = predict(args, examples, exe, test_prog, test_pyreader, graph_vars)
  File "/home/aistudio/DuIe_baseline/ernie/finetune/relation_extraction_multi_cls.py", line 444, in predict
    exe.run(program=test_program, fetch_list=fetch_list, return_numpy=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::SequenceUnpadOp::InferShape(paddle::framework::InferShapeContext*) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
6   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
7   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
8   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/sequence_lod.py", line 1013, in sequence_unpad
    outputs={'Out': out})
  File "/home/aistudio/DuIe_baseline/ernie/finetune/relation_extraction_multi_cls.py", line 190, in create_model
    lod_labels = fluid.layers.sequence_unpad(labels, seq_lens)
  File "./ernie/run_duie.py", line 158, in main
    ernie_config=ernie_config)
  File "./ernie/run_duie.py", line 401, in <module>
    main(args)

----------------------
Error Message Summary:
----------------------
Error: The shape of Input(Length) should be [batch_size].
  [Hint: Expected len_dims.size() == 1, but received len_dims.size():2 != 1:1.] at (/paddle/paddle/fluid/operators/sequence_ops/sequence_unpad_op.cc:41)
  [operator < sequence_unpad > error]
```

**Comment by zhangting2020** [comment]
上面只是设置了seq_lens的shape，应该还需要检查一下seq_lens的数据维度，可能是2-D的

**Comment by iceriver97** [comment]
@zhangting2020 谢谢。但是我这里是使用py_reader异步读入数据的，我该如何检查数据维度呢？

**Comment by iceriver97** [comment]
@zhangting2020  非常感谢您的帮助;我在修改了reader的设置之后使用1.8的环境在AIStudio上可以正常运行了;
但是当我迁移到本地的时候，还是同样的最初的错误：
```
W0904 16:16:25.948801  4491 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.0
W0904 16:16:26.436219  4491 device_context.cc:260] device: 0, cuDNN Version: 7.6.
2020-09-04 16:16:42,069-INFO: Load model from ./checkpoints/step_10707/
[INFO] 2020-09-04 16:16:42,069 [     init.py:   64]:	Load model from ./checkpoints/step_10707/
2020-09-04 16:16:42,094-INFO: testing ./data/test.json, save to ./data/predict_dev.json
[INFO] 2020-09-04 16:16:42,094 [ run_duie.py:  386]:	testing ./data/test.json, save to ./data/predict_dev.json
/home/speedchina/anaconda3/envs/py36-pp/lib/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "./ernie/run_duie.py", line 406, in <module>
    main(args)
  File "./ernie/run_duie.py", line 316, in main
    prediction = predict_wrapper(reader, exe, test_prog, test_pyreader, graph_vars,'final', 'final')
  File "./ernie/run_duie.py", line 387, in predict_wrapper
    res = predict(args, examples, exe, test_prog, test_pyreader, graph_vars)
  File "/home/speedchina/Paddlepaddle/PaddleServing/DuIe_baseline/ernie/finetune/relation_extraction_multi_cls.py", line 444, in predict
    exe.run(program=test_program, fetch_list=fetch_list, return_numpy=False)
  File "/home/speedchina/anaconda3/envs/py36-pp/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/speedchina/anaconda3/envs/py36-pp/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/speedchina/anaconda3/envs/py36-pp/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/speedchina/anaconda3/envs/py36-pp/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/speedchina/anaconda3/envs/py36-pp/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   void paddle::operators::math::Blas<paddle::platform::CUDADeviceContext>::MatMul<float>(paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, paddle::framework::Tensor const&, paddle::operators::math::MatDescriptor const&, float, paddle::framework::Tensor*, float) const
3   paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, float>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, double>, paddle::operators::MatMulKernel<paddle::platform::CUDADeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
9   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
10  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/speedchina/anaconda3/envs/py36-pp/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/speedchina/anaconda3/envs/py36-pp/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/speedchina/anaconda3/envs/py36-pp/lib/python3.6/site-packages/paddle/fluid/layers/nn.py", line 6416, in matmul
    attrs=attrs)
  File "/home/speedchina/Paddlepaddle/PaddleServing/DuIe_baseline/ernie/model/ernie.py", line 145, in _build_model
    x=input_mask, y=input_mask, transpose_y=True)
  File "/home/speedchina/Paddlepaddle/PaddleServing/DuIe_baseline/ernie/model/ernie.py", line 98, in __init__
    input_mask)
  File "/home/speedchina/Paddlepaddle/PaddleServing/DuIe_baseline/ernie/finetune/relation_extraction_multi_cls.py", line 164, in create_model
    use_fp16=args.use_fp16)
  File "./ernie/run_duie.py", line 159, in main
    ernie_config=ernie_config)
  File "./ernie/run_duie.py", line 406, in <module>
    main(args)

----------------------
Error Message Summary:
----------------------
ExternalError:  Cublas error, CUBLAS_STATUS_EXECUTION_FAILED  at (/paddle/paddle/fluid/operators/math/blas_impl.cu.h:61)
  [operator < matmul > error]
```
paddle 版本 ：`paddlepaddle-gpu==1.8.3.post107`

**Comment by zhangting2020** [comment]
那这样看来，目前只能考虑换CPU了。我们这边会再看看这个问题如何修复

**Comment by iceriver97** [comment]
@zhangting2020  好的，谢谢。在输入数据较短时不会出错；数据很长时会报错：
`Intel MKL function load error: cpu specific dynamic library is not loaded.`希望这对你们有帮助，能够尽快修复，再次感谢！

**Comment by iceriver97** [comment]
@zhangting2020 在使用 Intel i7 8750h + PP1.8.4 时，一切正常；

**Comment by zhangting2020** [comment]
由于目前暂时不支持AMD CPU，因此只能通过换CPU解决，此issue关闭
