### ISSUE TITLE
paddle 训练报错 无显式提示信息

### ISSUE THREAD

**Issue by maosengshulei** [PaddlePaddle/Paddle#28066]
paddle 版本：1.8.1

```
2020-10-19 14:34:42,461-INFO: Steps: 1 Loss: [array([2.8835764], dtype=float32)]
/home/users/maoseng/listwise_pointer_network/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "listwise_pointer_network_dqn.py", line 392, in <module>
    local_run_train_episode(agent, msd_dataset)
  File "listwise_pointer_network_dqn.py", line 179, in local_run_train_episode
    loss = agent.learn(data)
  File "listwise_pointer_network_dqn.py", line 142, in learn
    self.learn_program, feed=data, fetch_list=[self.cost])
  File "/home/users/maoseng/listwise_pointer_network/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/users/maoseng/listwise_pointer_network/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/users/maoseng/listwise_pointer_network/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/users/maoseng/listwise_pointer_network/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::memory::detail::MemoryBlock::Split(paddle::memory::detail::MetadataCache*, unsigned long)
3   paddle::memory::detail::BuddyAllocator::SplitToAlloc(std::_Rb_tree_const_iterator<std::tuple<unsigned long, unsigned long, void*> >, unsigned long)
4   paddle::memory::detail::BuddyAllocator::Alloc(unsigned long)
5   void* paddle::memory::legacy::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, unsigned long)
6   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
7   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
8   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
9   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
10  paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
11  paddle::operators::MulGradKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
12  std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::MulGradKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::MulGradKernel<paddle::platform::CPUDeviceContext, double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
13  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
14  paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
15  paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
16  paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
17  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
18  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/users/maoseng/listwise_pointer_network/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/users/maoseng/listwise_pointer_network/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/users/maoseng/listwise_pointer_network/paddle_release_home/python/lib/python2.7/site-packages/paddle/fluid/layers/nn.py", line 1719, in fc
    "y_num_col_dims": 1})
  File "/home/users/maoseng/listwise_pointer_network_dqn/generator_network.py", line 119, in _build_encoder
    bias_attr=ParamAttr(name='Generator_{}_init_hidden_fc_0.b_0'.format(variable_field))) #(batch, hidden_size)
  File "/home/users/maoseng/listwise_pointer_network_dqn/generator_network.py", line 224, in forward
    self._build_encoder(inputs, target=target)
  File "listwise_pointer_network_dqn.py", line 57, in learn
    c_Q = self.generator_model.forward(inputs, output_type='c_Q')
  File "listwise_pointer_network_dqn.py", line 112, in _build_net
    self.cost = self.generator_trainer.learn(self.data_list)
  File "listwise_pointer_network_dqn.py", line 80, in __init__
    self._build_net()
  File "listwise_pointer_network_dqn.py", line 388, in <module>
    agent = GeneratorAgent(config, feat_list.features, args, msd_dataset)

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information
  [Hint: Expected desc->total_size >= size, but received desc->total_size:0 < size:69632.] at (/paddle/paddle/fluid/memory/detail/memory_block.cc:41)
  [operator < mul_grad > error]
```

**Comment by zhiqiu** [comment]
hi，可以先检查下机器的内存有多少，或者调小batchsize试试。

**Comment by maosengshulei** [comment]
经测试，batch_size设置为4，以及将fc的hidden_size降低可在本地训练。但是在mpi集群 分布式训练时 节点内存为150G，batch_size设置为4，fc的hidden_size提高一些 训练几个pass还是会报相同的错。网络结构本身不复杂，这么耗内存是为什么？

**Comment by zhiqiu** [comment]
> 经测试，batch_size设置为4，以及将fc的hidden_size降低可在本地训练。但是在mpi集群 分布式训练时 节点内存为150G，batch_size设置为4，fc的hidden_size提高一些 训练几个pass还是会报相同的错。网络结构本身不复杂，这么耗内存是为什么？

已线下沟通，经排查发现，模型中有一处concat的两个tensor的rank不一致，导致错误。
