### ISSUE TITLE
Building Paddle in Debug mode fails

### ISSUE THREAD

**Issue by wojtuss** [PaddlePaddle/Paddle#28248]
**System information**
-PaddlePaddle version: current develop branch
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-OS Platform and Distribution: Ubuntu 18.04
-Python version: 2.7.17

**To Reproduce**
Build Paddle with cmake command containing the option `-DCMAKE_BUILD_TYPE=Debug`, e.g.
```
cmake -DWITH_GPU=OFF -DWITH_DISTRIBUTE=OFF -DWITH_MKLDNN=ON -DWITH_PROFILER=ON -DON_INFER=ON -DCMAKE_BUILD_TYPE=Debug -DWITH_TESTING=ON -DWITH_INFERENCE_API_TEST=ON -DWITH_NCCL=OFF ..
```

When building Padle in debug mode the issue https://github.com/PaddlePaddle/Paddle/issues/25494 is present. However, even after commenting out the offending code in the `tinyformat.h` file the following building error occurs:
```
[100%] Built target check_symbol
Traceback (most recent call last):
  File "setup.py", line 506, in <module>
    'fleetrun = paddle.distributed.fleet.launch:launch'
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 266, in run
    wheel_name = archive_wheelfile(pseudoinstall_root, archive_root)
  File "/usr/lib/python2.7/dist-packages/wheel/archive.py", line 20, in archive_wheelfile
    return make_wheelfile_inner(base_name)
  File "/usr/lib/python2.7/dist-packages/wheel/archive.py", line 72, in make_wheelfile_inner
    writefile(path, date_time)
  File "/usr/lib/python2.7/dist-packages/wheel/archive.py", line 58, in writefile
    zip.writestr(zinfo, fp.read())
  File "/usr/lib/python2.7/zipfile.py", line 1257, in writestr
    self._writecheck(zinfo)
  File "/usr/lib/python2.7/zipfile.py", line 1137, in _writecheck
    " would require ZIP64 extensions")
zipfile.LargeZipFile: Filesize would require ZIP64 extensions
python/CMakeFiles/paddle_python.dir/build.make:1475: recipe for target 'python/build/.timestamp' failed
make[2]: *** [python/build/.timestamp] Error 1
CMakeFiles/Makefile2:128658: recipe for target 'python/CMakeFiles/paddle_python.dir/all' failed
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Built target inference_lib_dist
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

Both building issues are inhibitive when fixing issues and feature development.

**Comment by zhwesky2010** [comment]
@wojtuss Debug mode has a large C++ dynamic library, if the Filesize file is too large, python compress wheel package will raise error. It may need to modify setup.py.in.

**Comment by wojtuss** [comment]
> @wojtuss Debug mode has a large C++ dynamic library, if the Filesize file is too large, python compress wheel package will raise error. It may need to modify setup.py.in.

@zhouwei25 , Thank you. Can anything be done about it?

**Comment by codecookinging** [comment]
so,how to fix this problem in code?
