### ISSUE TITLE
分布环境下调用LAC时，报错：PermissionError: [Errno 13] Permission denied: ''

### ISSUE THREAD

**Issue by youngjt** [PaddlePaddle/Paddle#28333]
1）集群的每台机器单独调用LAC没有问题
2）通过mapreduce调用LAC时，出现一下错误信息：
Traceback (most recent call last):
File "lac_test.py", line 5, in <module>
from LAC import LAC
File "/opt/python3/lib/python3.7/site-packages/LAC/__init__.py", line 23, in <module>
from .lac import LAC
File "/opt/python3/lib/python3.7/site-packages/LAC/lac.py", line 28, in <module>
import paddle.fluid as fluid
File "/opt/python3/lib/python3.7/site-packages/paddle/__init__.py", line 31, in <module>
import paddle.dataset
File "/opt/python3/lib/python3.7/site-packages/paddle/dataset/__init__.py", line 29, in <module>
import paddle.dataset.flowers
File "/opt/python3/lib/python3.7/site-packages/paddle/dataset/flowers.py", line 39, in <module>
from paddle.dataset.image import *
File "/opt/python3/lib/python3.7/site-packages/paddle/dataset/image.py", line 45, in <module>
stderr=subprocess.PIPE)
File "/opt/python3/lib/python3.7/subprocess.py", line 800, in __init__
restore_signals, start_new_session)
File "/opt/python3/lib/python3.7/subprocess.py", line 1551, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''

**Comment by youngjt** [comment]
paddle/dataset/image.py，以下这段代码出错（系统为centos版本为：centos-release-7-6.1810.2.el7.centos.x86_64）

if six.PY3:
    import subprocess
    import sys
    **_import_cv2_proc = subprocess.Popen(
        [sys.executable, "-c", "import cv2"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE)
    out, err = import_cv2_proc.communicate()_**
    retcode = import_cv2_proc.poll()
    if retcode != 0:
        cv2 = None
    else:
        import cv2

**Comment by Heeenrrry** [comment]
您好，由于您的hadoop环境可能存在额外限制，不支持多线程库导致无法使用subprocess库，可考虑修改或更换环境。
