### ISSUE TITLE
cast raises an exception thrust::system::system_error, parallel_for failed

### ISSUE THREAD

**Issue by JingChunzhen** [PaddlePaddle/Paddle#28478]
```
W1109 11:20:13.749193 30271 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.1, Runtime API Version: 10.1
W1109 11:20:13.753401 30271 device_context.cc:260] device: 0, cuDNN Version: 7.5.
W1109 11:20:14.963344 30271 operator.cc:187] cast raises an exception thrust::system::system_error, parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument
```

有关cast的代码：
```
                node_zero_mask = fluid.layers.cast(current_layer_node, "bool")
                node_zero_mask = fluid.layers.cast(node_zero_mask, "float32")
                prob = fluid.layers.elementwise_mul(prob, node_zero_mask)

                # mask leaf node, leaf node not involved in topk 
  
                leaf_mask = fluid.layers.logical_not(leaf_mask)
                leaf_mask = fluid.layers.cast(leaf_mask, 'float32')
         
                UtilsWrapper.trace_var_detail(
                    leaf_mask, "[TDM]", "[leaf_mask_{}]".format(layer_idx), self.need_trace
                )       

                #prob = prob * leaf_mask
                prob = fluid.layers.elementwise_mul(prob, leaf_mask)

```
如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：paddle 1.8.3
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：Tesla p4
    4）系统环境：请您描述系统类型、版本（如Mac OS 10.14），Python版本
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

**Comment by JingChunzhen** [comment]
运行出core core信息如下：
```
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f970a4dc700 (LWP 2139))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f97142702d9 in __GI_abort () at abort.c:89
#2  0x00007f97145aa963 in ?? () from /opt/compiler/gcc-8.2/lib/libstdc++.so.6
#3  0x00007f97145b09a6 in ?? () from /opt/compiler/gcc-8.2/lib/libstdc++.so.6
#4  0x00007f97145b09e1 in std::terminate() () from /opt/compiler/gcc-8.2/lib/libstdc++.so.6
#5  0x00007f97145b099a in std::rethrow_exception(std::__exception_ptr::exception_ptr) () from /opt/compiler/gcc-8.2/lib/libstdc++.so.6
#6  0x00007f971db31b1e in paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&) [clone .cold.1229] ()
   from /home/surf/jingchunzhen/online_tdm_attention/beamsearch_test/bin/../lib/libpaddle_fluid.so
#7  0x00007f971df86a94 in paddle::framework::NaiveExecutor::Run() () from /home/surf/jingchunzhen/online_tdm_attention/beamsearch_test/bin/../lib/libpaddle_fluid.so
#8  0x00007f971ddad8cc in paddle::AnalysisPredictor::ZeroCopyRun() () from /home/surf/jingchunzhen/online_tdm_attention/beamsearch_test/bin/../lib/libpaddle_fluid.so
#9  0x0000000000407e72 in test_search(int, int)::{lambda()#1}::operator()() const ()
#10 0x00007f97145da16f in ?? () from /opt/compiler/gcc-8.2/lib/libstdc++.so.6
#11 0x00007f974dd9eda4 in start_thread (arg=<optimized out>) at pthread_create.c:333
#12 0x00007f971433b32d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

```

**Comment by lfchener** [comment]
@T8T9
