### ISSUE TITLE
Paddle2.0rc DataLoader自定义数据读取报错

### ISSUE THREAD

**Issue by iotctech** [PaddlePaddle/Paddle#28512]
## 问题描述
参考官方文档测试自定义数据集，paddle.io.DataLoader执行报错
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0-rc/guides/02_paddle2.0_develop/02_data_load_cn.html#id3

## 代码
```
import paddle
from paddle.io import Dataset

class MyDataset(Dataset):
    def __init__(self, mode='train'):
        super(MyDataset, self).__init__()

        if mode == 'train':
            self.data = [
                ['traindata1', 'label1'],
                ['traindata2', 'label2'],
                ['traindata3', 'label3'],
                ['traindata4', 'label4'],
            ]
        else:
            self.data = [
                ['testdata1', 'label1'],
                ['testdata2', 'label2'],
                ['testdata3', 'label3'],
                ['testdata4', 'label4'],
            ]

    def __getitem__(self, index):
        data = self.data[index][0]
        label = self.data[index][1]
        return data, label

    def __len__(self):
        return len(self.data)

train_dataset = MyDataset(mode='train')

train_loader = paddle.io.DataLoader(train_dataset, places=paddle.CPUPlace(), batch_size=64, shuffle=True)
for batch_id, data in enumerate(train_loader()):
    x_data = data[0]
    y_data = data[1]

    print(x_data.numpy().shape)
    print(y_data.numpy().shape)
```

## 错误日志
```
WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/simpleai/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 323, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/home/simpleai/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/simpleai/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 293, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/home/simpleai/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/fetcher.py", line 53, in fetch
    return self.collate_fn(data)
  File "/home/simpleai/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 94, in default_collate_fn
    raise RuntimeError("Unknown data type {}".format(type(slot[0])))
RuntimeError: Unknown data type <class 'str'>

---------------------------------------------------------------------------
EnforceNotMet                             Traceback (most recent call last)
<ipython-input-6-424de2e95c1c> in <module>
      2 
      3 train_loader = paddle.io.DataLoader(train_dataset, places=paddle.CPUPlace(), batch_size=64, shuffle=True)
----> 4 for batch_id, data in enumerate(train_loader()):
      5     x_data = data[0]
      6     y_data = data[1]

~/.local/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py in __next__(self)
    339         try:
    340             if in_dygraph_mode():
--> 341                 return self._reader.read_next_var_list()
    342             else:
    343                 if self._return_list:

EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)
```

## 运行环境
- 系统：ubuntu18.04
- driver: 450.51.06
- cuda：11.0.3
- cudnn: 8.0.3.33-1+cuda11.0
- python: 3.6.9

**Comment by iotctech** [comment]
#28385

**Comment by 123malin** [comment]
感谢使用Paddle。目前paddle不支持str格式的输入，换成数值类型就可以了。

**Comment by iotctech** [comment]
> 感谢使用Paddle。目前paddle不支持str格式的输入，换成数值类型就可以了。

感谢回复，换成数值型确实没有问题了，不过文档是不是需要做些提示，调试这些问题有点浪费时间。谢谢～

**Comment by chenjie04** [comment]
> > 感谢使用Paddle。目前paddle不支持str格式的输入，换成数值类型就可以了。
> 
> 感谢回复，换成数值型确实没有问题了，不过文档是不是需要做些提示，调试这些问题有点浪费时间。谢谢～

抱歉！能解释清楚一点吗？把什么换成数值型？
