### ISSUE TITLE
paddle2.0 develop版本动转静时若干bad case

### ISSUE THREAD

**Issue by Meiyim** [PaddlePaddle/Paddle#28754]
测试paddle版本: 2020.11.19 dev版本wheel包： https://paddle-wheel.bj.bcebos.com/0.0.0-gpu-cuda10-cudnn7-mkl/paddlepaddle_gpu-0.0.0-cp36-cp36m-linux_x86_64.whl

当被jit编译的forward函数用kwargs.pop方式处理入参时，没有考虑到pop的缺省参数。

测试代码:
```python
import paddle as p

class Net(p.nn.Layer):
    def __init__(self):
        super().__init__()
        self.fc=p.nn.Linear(3,3)
    @p.jit.to_static(input_spec=[
            p.static.InputSpec(shape=[None, None], name='ids', dtype='float32'),
        ])
    def forward(self, x, **kwargs):
        y = kwargs.pop('y', None)
        if y is not None:
            x += y
        x.mean()
        return x


x=p.zeros([2,3],dtype='float32')
net=Net()
y=net(x)
p.jit.save(x, 'f')
```

报错信息:
```
You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.W1119 19:45:18.281731 190706 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.0
W1119 19:45:18.285172 190706 device_context.cc:346] device: 0, cuDNN Version: 7.0.
W1119 19:45:19.824478 190706 device_context.h:207] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
Traceback (most recent call last):
  File "bug_to_static.py", line 20, in <module>
    y=net(x)
  File "/home/work/chenxuyi/dis/dyg/app/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 829, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/work/chenxuyi/dis/dyg/app/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 336, in __call__
    error_data.raise_new_exception()
  File "/home/work/chenxuyi/dis/dyg/app/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 181, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
KeyError: 'In user code:\n\n    File "/home/work/chenxuyi/.tmp/tmpe48_sbjl.py", line 5, in forward\n\tkwargs, \'y\')\n    File "/home/work/chenxuyi/dis/dyg/app/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/list_transformer.py", line 86, in convert_list_pop\n\tresult = target.pop(idx)\n    KeyError: \'y\''

```

**Comment by zhwesky2010** [comment]
@liym27 麻烦看看动转静这个问题

**Comment by liym27** [comment]
> @liym27 麻烦看看动转静这个问题

好的，问题正在排查中。将尽快给您@Meiyim 反馈及修复该bug

**Comment by Meiyim** [comment]
再贡献一个导致失效的badcase:
若被转换函数中调用了logging打日志， 则会莫名触发 `paddle.cond`. 导致编译失败，且日志晦涩难懂。
```
import paddle as p
import logging

class Net(p.nn.Layer):
    def __init__(self):
        super().__init__()
        self.fc=p.nn.Linear(3,3)
    @p.jit.to_static(input_spec=[
            p.static.InputSpec(shape=[None, None], name='ids', dtype='float32'),
        ])
    def forward(self, x, **kwargs):
        logging.info('good')
        x = self.fc(x)
        x.mean()
        return x


x=p.zeros([2,3],dtype='float32')
net=Net()
y=net(x)
```

错误输出:
```
W1123 17:22:51.270537     1 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.2, Runtime API Version: 10.2
W1123 17:22:51.288487     1 device_context.cc:346] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "bug.py", line 20, in <module>
    y=net(x)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 829, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 341, in __call__
    error_data.raise_new_exception()
  File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 186, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
KeyError: 'In transformed code:\n\n    File "bug.py", line 12, in forward (* user code *)\n\tlogging.info(\'good\')\n    File "/tmp/tmpkhey51lw.py", line 17, in info\n\tlen)(root.handlers) == 0, true_fn_0, false_fn_0, (), (), ())\n    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 171, in convert_ifelse\n\treturn _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)\n    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 197, in _run_py_ifelse\n\treturn true_fn(*true_args) if pred else false_fn(*false_args)\n    File "/usr/local/lib/python3.6/logging/__init__.py", line 1869, in info (* user code *)\n\tbasicConfig()\n    File "/tmp/tmpdb6t_3xr.py", line 196, in basicConfig\n\t(kwargs,), (), ())\n    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 171, in convert_ifelse\n\treturn _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)\n    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 197, in _run_py_ifelse\n\treturn true_fn(*true_args) if pred else false_fn(*false_args)\n    File "/tmp/tmpdb6t_3xr.py", line 58, in true_fn_10\n\tconvert_list_pop(kwargs, \'handlers\'))\n    File "/usr/local/lib/python3.6/site-packages/paddle/fluid/dygraph/dygraph_to_static/list_transformer.py", line 86, in convert_list_pop\n\tresult = target.pop(idx)\n    KeyError: \'handlers\''
```

**Comment by Meiyim** [comment]
```
>>> import logging as l
>>> l.__version__
'0.5.1.2'
```

**Comment by liym27** [comment]
问题已修复
修复PR:

1. https://github.com/PaddlePaddle/Paddle/pull/29023

2. https://github.com/PaddlePaddle/Paddle/pull/29098
