### ISSUE TITLE
AI Studio后台任务跑一半挂掉了

### ISSUE THREAD

**Issue by shaunhurryup** [PaddlePaddle/Paddle#29197]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.0rc
    4）系统环境：AI Studio后台任务

## 回溯
```python
Epoch 1/50
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return (isinstance(seq, collections.Sequence) and
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:637: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
step 619/619 [==============================] - loss: 7.3876 - 15s/step           
save checkpoint at /home/aistudio/work/output/0
Eval begin...
step 157/157 [==============================] - loss: 7.0366 - 15s/step           
Eval samples: 10000
Epoch 2/50
step 619/619 [==============================] - loss: 7.4104 - 15s/step           
save checkpoint at /home/aistudio/work/output/1
Eval begin...
step 157/157 [==============================] - loss: 7.1302 - 14s/step           
Eval samples: 10000
Epoch 3/50
step 619/619 [==============================] - loss: 7.0325 - 15s/step           
save checkpoint at /home/aistudio/work/output/2
Eval begin...
step 157/157 [==============================] - loss: 7.0113 - 14s/step           
Eval samples: 10000
Epoch 4/50
step 619/619 [==============================] - loss: 6.6897 - 15s/step           
save checkpoint at /home/aistudio/work/output/3
Eval begin...
step 157/157 [==============================] - loss: 7.0423 - 15s/step           
Eval samples: 10000
Epoch 5/50
step 619/619 [==============================] - loss: 6.4737 - 15s/step           
save checkpoint at /home/aistudio/work/output/4
Eval begin...
step 157/157 [==============================] - loss: 6.8552 - 14s/step           
Eval samples: 10000
Epoch 6/50
step 619/619 [==============================] - loss: 6.7646 - 17s/step           
save checkpoint at /home/aistudio/work/output/5
Eval begin...
step 157/157 [==============================] - loss: 7.1019 - 14s/step           
Eval samples: 10000
Epoch 7/50
step 619/619 [==============================] - loss: 6.8838 - 17s/step           
save checkpoint at /home/aistudio/work/output/6
Eval begin...
step 157/157 [==============================] - loss: 6.5195 - 15s/step           
Eval samples: 10000
Epoch 8/50
step 619/619 [==============================] - loss: 6.4819 - 14s/step           
save checkpoint at /home/aistudio/work/output/7
Eval begin...
step 157/157 [==============================] - loss: 6.7995 - 14s/step           
Eval samples: 10000
Epoch 9/50
step 619/619 [==============================] - loss: 6.8385 - 14s/step           
save checkpoint at /home/aistudio/work/output/8
Eval begin...
step 157/157 [==============================] - loss: 6.1501 - 14s/step           
Eval samples: 10000
Epoch 10/50
step 619/619 [==============================] - loss: 6.1990 - 16s/step           
save checkpoint at /home/aistudio/work/output/9
Eval begin...
step 157/157 [==============================] - loss: 6.4901 - 14s/step           
Eval samples: 10000
Epoch 11/50
step 619/619 [==============================] - loss: 5.9624 - 16s/step           
save checkpoint at /home/aistudio/work/output/10
Eval begin...
step 157/157 [==============================] - loss: 6.3731 - 14s/step           
Eval samples: 10000
Epoch 12/50
step 109/619 [====>.........................] - loss: 6.4915 - ETA: 1:58:36 - 14s/step
WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-26:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 323, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 293, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 52, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "<ipython-input-6-3c7598734fca>", line 45, in __getitem__
    for line in f:
OSError: [Errno 5] Input/output error

---------------------------------------------------------------------------EnforceNotMet                             Traceback (most recent call last)<ipython-input-10-810a3f976afe> in <module>
     42     save_freq=1,
     43     log_freq=1,
---> 44     verbose=1)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in fit(self, train_data, eval_data, batch_size, epochs, eval_freq, log_freq, save_dir, save_freq, verbose, drop_last, shuffle, num_workers, callbacks)
   1467 
   1468             cbks.on_epoch_begin(epoch)
-> 1469             logs = self._run_one_epoch(train_loader, cbks, 'train')
   1470             cbks.on_epoch_end(epoch, logs)
   1471 
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py in _run_one_epoch(self, data_loader, callbacks, mode, logs)
   1814     def _run_one_epoch(self, data_loader, callbacks, mode, logs={}):
   1815         outputs = []
-> 1816         for step, data in enumerate(data_loader):
   1817             # data might come from different types of data_loader and have
   1818             # different format, as following:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py in __next__(self)
    339         try:
    340             if in_dygraph_mode():
--> 341                 return self._reader.read_next_var_list()
    342             else:
    343                 if self._return_list:
EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)
```

**Comment by MissPenguin** [comment]
看着是数据读取的报错，可以单独测试一下data loader，看跑一段时间是否会挂，如果data loader没问题，那可能是aistudio不稳定，重启任务试试。
