### ISSUE TITLE
Fail to install PaddlePaddle CPU-version with pip on MacOS 10.15.6

### ISSUE THREAD

**Issue by chenjun082** [PaddlePaddle/Paddle#29237]
When installing PaddlePaddle CPU-version with pip on MacOS 10.15.6, I always get the following installation exception:

Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: ***sensitive***
       cwd: /private/var/folders/13/09f597jn53s3v4zgvncvh8x44c15rn/T/pip-install-uf13PE/opencv-python
  Complete output (22 lines):
  Traceback (most recent call last):
    File "/Users/***sensitive***/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/***sensitive***/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/***sensitive***/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/13/09f597jn53s3v4zgvncvh8x44c15rn/T/pip-build-env-x9gVG0/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/private/var/folders/13/09f597jn53s3v4zgvncvh8x44c15rn/T/pip-build-env-x9gVG0/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/13/09f597jn53s3v4zgvncvh8x44c15rn/T/pip-build-env-x9gVG0/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 243, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/private/var/folders/13/09f597jn53s3v4zgvncvh8x44c15rn/T/pip-build-env-x9gVG0/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 448, in <module>
      main()
    File "setup.py", line 99, in main
      % {"ext": re.escape(sysconfig.get_config_var("EXT_SUFFIX"))}
    File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 210, in escape
      s = list(pattern)
  TypeError: 'NoneType' object is not iterable
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/***sensitive***/Library/Python/2.7/lib/python/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/13/09f597jn53s3v4zgvncvh8x44c15rn/T/tmpIQD6Wc Check the logs for full command output.

My environment settings are:
MacOS: 10.15.6, 64bit 
Python2: 2.7.15
pip: 20.2.2

The following commands have been attempted, but all failed:
python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
python -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple

BTW, I am an engineer inside Baidu, but this makes me feel bad.

**Comment by ZHUI** [comment]
It seems you have trouble when install the opencv package. 

You can try `pip install opencv-python==4.2.0.32`, then  install the paddlepaddle package.
