### ISSUE TITLE
paddle2.0中tensor相等运算报错

### ISSUE THREAD

**Issue by qq345481843** [PaddlePaddle/Paddle#29625]
paddle2.0中tensor相等运算报错。

具体代码如下：
```
if __name__ == '__main__':
    x = paddle.to_tensor(np.random.randint(0, 5, 10))
    index = x == 1 
    print(index)
```
![image](https://user-images.githubusercontent.com/54829296/102188015-bf265b80-3eef-11eb-8a4e-8f7397cb8560.png)

报错信息如下：
```
Traceback (most recent call last):
  File "D:/Developer/Workplace/Python/project/maritime-situation-awareness-paddle/tools/reader.py", line 11, in <module>
    print(index)
  File "D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 247, in __str__
    return to_string(self)
  File "D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\tensor\to_string.py", line 204, in to_string
    data = _format_tensor(var, sumary, indent=indent)
  File "D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\tensor\to_string.py", line 147, in _format_tensor
    max_width = _get_max_width(_to_sumary(var))
  File "D:\Developer\Anaconda\envs\paddle2.0\lib\site-packages\paddle\tensor\to_string.py", line 104, in _to_sumary
    return paddle.concat([var[:edgeitems], var[-edgeitems:]])
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
NotFoundError: Operator slice does not have kernel for data_type[bool]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at D:\2.0.0-rc0\paddle\paddle\fluid\imperative\prepared_operator.cc:118)
  [operator < slice > error]
W1215 16:07:28.150907 13224 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 10.2, Runtime API Version: 10.2
W1215 16:07:28.160908 13224 device_context.cc:346] device: 0, cuDNN Version: 7.6.

Process finished with exit code 1
```
感谢！

**Comment by Xreki** [comment]
请问具体使用的是paddle哪个版本呢？建议更新到paddle2.0rc1试下。develop是可以支持该功能的。

**Comment by qq345481843** [comment]
我用的是rc0版本，我试着更新到rc1，能正常打印输出了。感谢！
