### ISSUE TITLE
"import paddle.fluid as fluid" 打包成.exe在其他机器运行报错

### ISSUE THREAD

**Issue by OrangeRanSX** [PaddlePaddle/Paddle#29660]
版本、环境信息：
 1）paddlepaddle1.8.5 CPU版本
 2)  系统环境：win10  家庭中文版 1903
 3）python 3.7.6（Anaconda3）
 
 predict_fun.py中第二行为"import paddle.fluid as fluid" ，用pyinstaller -D打包后无法运行，
 之后添加\Anaconda3\Lib\site-packages\paddle\libs下的5个dll后能在本机器运行，
 但是在别的电脑无法运行，报错信息如下
 
Traceback (most recent call last):
  File "mainWindows.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "predict_fun.py", line 2, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\__init__.py", line 37, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\tensor\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\tensor\math.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\common_ops_import.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\__init__.py", line 56, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\__init__.py", line 27, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\core\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\core\config.py", line 19, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\prune\__init__.py", line 17, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\prune\prune_strategy.py", line 22, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\optimize\__init__.py", line 390, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\optimize\_minimize.py", line 30, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\sparse\linalg\__init__.py", line 116, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
ImportError: DLL load failed: 找不到指定的程序。
[17824] Failed to execute script mainWindows

**Comment by OrangeRanSX** [comment]
问题补充：
       打包前为了解决打包的.exe一直生成相同的子进程问题，按照https://github.com/PaddlePaddle/Paddle/pull/26200/files
对paddle/dataset/image.py进行了修改

**Comment by Avin0323** [comment]
> predict_fun.py中第二行为"import paddle.fluid as fluid" ，用pyinstaller -D打包后无法运行，
> 之后添加\Anaconda3\Lib\site-packages\paddle\libs下的5个dll后能在本机器运行，
> 但是在别的电脑无法运行，报错信息如下
> ...

打包后无法运行报错与移植到其他机器报错信息一致吗？

**Comment by OrangeRanSX** [comment]
> > predict_fun.py中第二行为"import paddle.fluid as fluid" ，用pyinstaller -D打包后无法运行，
> > 之后添加\Anaconda3\Lib\site-packages\paddle\libs下的5个dll后能在本机器运行，
> > 但是在别的电脑无法运行，报错信息如下
> > ...
> 
> 打包后无法运行报错与移植到其他机器报错信息一致吗？

## 打包经历
### 1.添加site-package/paddle下的5个.dll前(本机):
Traceback (most recent call last):
  File "mainWindows.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "predict_fun.py", line 2, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\__init__.py", line 37, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\tensor\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\tensor\math.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\common_ops_import.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\__init__.py", line 35, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\framework.py", line 35, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\core.py", line 273, in <module>
  File "paddle\fluid\core.py", line 243, in <module>
ImportError: DLL load failed: 找不到指定的模块。


### 2.添加后：
生成的.exe不停生成同名子进程，无法运行


### 3.按照https://github.com/PaddlePaddle/Paddle/pull/26200/files
### 对paddle/dataset/image.py进行了修改后打包并添加paddle下.dll

Traceback (most recent call last):
  File "mainWindows.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "predict_fun.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\__init__.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\tensor\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\tensor\math.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\common_ops_import.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\__init__.py", line 56, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\core\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\core\config.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\prune\__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\prune\prune_strategy.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "prettytable\__init__.py", line 43, in <module>
  File "pkg_resources\__init__.py", line 482, in get_distribution
  File "pkg_resources\__init__.py", line 358, in get_provider
  File "pkg_resources\__init__.py", line 901, in require
  File "pkg_resources\__init__.py", line 787, in resolve
pkg_resources.DistributionNotFound: The 'prettytable' distribution was not found
 and is required by the application
[15612] Failed to execute script mainWindows


### 4.mainWindows.py（需要打包的.py文件）同目录下新增一个hook-ctypes.macholib.py,
#### 内容为：
  ```
from PyInstaller.utils.hooks import copy_metadata
  datas = copy_metadata('prettytable')
```
#### 重新打包
pyinstaller -D mainWindows.py --additional-hooks-dir=.
#### 并添加paddle下.dll后，本机能运行
#### 但别的机器（未安装paddlepaddle）
报错为：
Traceback (most recent call last):
  File "mainWindows.py", line 7, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "predict_fun.py", line 2, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\__init__.py", line 37, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\tensor\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\complex\tensor\math.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\common_ops_import.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\__init__.py", line 56, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\__init__.py", line 27, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\core\__init__.py", line 15, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\core\config.py", line 19, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\prune\__init__.py", line 17, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "paddle\fluid\contrib\slim\prune\prune_strategy.py", line 22, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\optimize\__init__.py", line 390, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\optimize\_minimize.py", line 30, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\optimize\_trustregion_constr\__init__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\optimize\_trustregion_constr\minimize_trustregion_constr.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\sparse\linalg\__init__.py", line 116, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\sparse\linalg\eigen\__init__.py", line 11, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\sparse\linalg\eigen\arpack\__init__.py", line 22, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 324, in exec_module
  File "scipy\sparse\linalg\eigen\arpack\arpack.py", line 45, in <module>
ImportError: DLL load failed: 找不到指定的程序。
[17824] Failed to execute script mainWindows


### 5. 单独写一个test.py测试了一下
```
import import paddle.fluid as fluid
if __name__ == '__main__':
    print("Hello.")
```
也有问题

**Comment by Avin0323** [comment]
> ### 5. 单独写一个test.py测试了一下
> ```
> import import paddle.fluid as fluid
> if __name__ == '__main__':
>     print("Hello.")
> ```
> 
> 也有问题

这部分是指在移植机器上执行失败是吗？

**Comment by Reatris** [comment]
@1771559253 感谢。打包这个实在是问题多多，之前那个多个同名线程的问题我是通过杀线程弄得
