### ISSUE TITLE
win/cuda10/paddle2.0.0b0/py3.7：cannot import name 'enum_type_wrapper' from 'google.protobuf.internal' (unknown location)

### ISSUE THREAD

**Issue by Wangyao1997-sdu** [PaddlePaddle/Paddle#29808]
标题： cannot import name 'enum_type_wrapper' from 'google.protobuf.internal' (unknown location)
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0b0
    2）GPU：CUDA版本10.0
    3）系统环境：python3.7、windows10

Traceback (most recent call last):
  File "E:/LearnPaddle2/wronglabel/cnncifar10_wronglabel.py", line 7, in <module>
    import paddle as paddle
  File "E:\python\install\envs\AIEnv\lib\site-packages\paddle\__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "E:\python\install\envs\AIEnv\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "E:\python\install\envs\AIEnv\lib\site-packages\paddle\fluid\framework.py", line 33, in <module>
    from .proto import framework_pb2
  File "E:\python\install\envs\AIEnv\lib\site-packages\paddle\fluid\proto\framework_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: cannot import name 'enum_type_wrapper' from 'google.protobuf.internal' (unknown location)

**Comment by ysh329** [comment]
是默认提供的代码嘛？这个错误是怎么触发的，环境是win/cuda10/paddle2.0.0b0/py3.7

**Comment by Wangyao1997-sdu** [comment]
> 是默认提供的代码嘛？这个错误是怎么触发的，环境是win/cuda10/paddle2.0.0b0/py3.7

import paddle as paddle的时候就直接报错了
尝试过重装1.8版本，还是一样

**Comment by ysh329** [comment]
这个应该是安装问题，paddle2.0rc1也有这个问题嘛

**Comment by Wangyao1997-sdu** [comment]
> 这个应该是安装问题，paddle2.0rc1也有这个问题嘛

我这边已经解决了：升级visualdl到1.14，matplotlib降级到2.2.3就好了

**Comment by ysh329** [comment]
Nice！

**Comment by ysh329** [comment]
这个原因看来是一些依赖库的版本问题，visaldl和matpotlib，之间有对google protobuf有依赖关系，在版本上有问题。
