### ISSUE TITLE
Paddle docker(paddlepaddle/paddle:latest) run models/image_classification/ failed

### ISSUE THREAD

**Issue by livc** [PaddlePaddle/Paddle#2990]
```
$ python train.py alexnet
I0720 07:18:59.060339   781 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1
[INFO 2017-07-20 07:18:59,074 layers.py:2428] output for __conv_0__: c = 96, h = 54, w = 54, size = 279936
[INFO 2017-07-20 07:18:59,077 layers.py:2553] output for __pool_0__: c = 96, h = 27, w = 27, size = 69984
[INFO 2017-07-20 07:18:59,080 layers.py:2428] output for __conv_1__: c = 256, h = 27, w = 27, size = 186624
[INFO 2017-07-20 07:18:59,086 layers.py:2553] output for __pool_1__: c = 256, h = 13, w = 13, size = 43264
[INFO 2017-07-20 07:18:59,089 layers.py:2428] output for __conv_2__: c = 384, h = 13, w = 13, size = 64896
[INFO 2017-07-20 07:18:59,091 layers.py:2428] output for __conv_3__: c = 384, h = 13, w = 13, size = 64896
[INFO 2017-07-20 07:18:59,093 layers.py:2428] output for __conv_4__: c = 256, h = 13, w = 13, size = 43264
[INFO 2017-07-20 07:18:59,094 layers.py:2553] output for __pool_2__: c = 256, h = 6, w = 6, size = 9216
I0720 07:19:05.273269   781 GradientMachine.cpp:85] Initing parameters..
I0720 07:19:07.668700   781 GradientMachine.cpp:92] Init parameters done.
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 271, in handle_worker
    r = mapper(sample)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/dataset/flowers.py", line 63, in default_mapper
    img = load_image_bytes(img)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 113, in load_image_bytes
    img = cv2.imdecode(file_bytes, flag)
AttributeError: 'NoneType' object has no attribute 'imdecode'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 271, in handle_worker
    r = mapper(sample)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/dataset/flowers.py", line 63, in default_mapper
    img = load_image_bytes(img)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 113, in load_image_bytes
    img = cv2.imdecode(file_bytes, flag)
AttributeError: 'NoneType' object has no attribute 'imdecode'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 271, in handle_worker
    r = mapper(sample)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/dataset/flowers.py", line 63, in default_mapper
    img = load_image_bytes(img)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 113, in load_image_bytes
    img = cv2.imdecode(file_bytes, flag)
AttributeError: 'NoneType' object has no attribute 'imdecode'


Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 271, in handle_worker
    r = mapper(sample)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/dataset/flowers.py", line 63, in default_mapper
    img = load_image_bytes(img)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 113, in load_image_bytes
    img = cv2.imdecode(file_bytes, flag)
AttributeError: 'NoneType' object has no attribute 'imdecode'
```

It works after I run `apt-get install libglib2.0-0`

**Comment by pkuyym** [comment]
Closed due to problem solved already. Please feel free to reopen it.
