### ISSUE TITLE
运行最新从icode下载的demo代码运行失败

### ISSUE THREAD

**Issue by jannet262** [PaddlePaddle/Paddle#3004]
我大约几个月前安装了一个paddle，然后以前的demo也能运行成功，今天我从icode拉取了一份最新的代码，里面的demo/quick_start执行会报错。

quick_start]$ sh -x ./preprocess.sh 
+ set -e
+ mkdir -p data/tmp
+ python preprocess.py -i data/reviews_Electronics_5.json.gz
Traceback (most recent call last):
  File "preprocess.py", line 40, in <module>
    parse_queue = Queue(maxsize=max_queue_size + num_tokenize)
  File "/home/map/paddle/install/python27-gcc482/lib/python2.7/multiprocessing/__init__.py", line 217, in Queue
    from multiprocessing.queues import Queue
  File "/home/map/paddle/install/python27-gcc482/lib/python2.7/multiprocessing/queues.py", line 48, in <module>
    from .synchronize import Lock, BoundedSemaphore, Semaphore, Condition
  File "/home/map/paddle/install/python27-gcc482/lib/python2.7/multiprocessing/synchronize.py", line 59, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

**Comment by gangliao** [comment]
你好，demo我们已经不在维护了，请尝试新的book https://github.com/PaddlePaddle/book
