### ISSUE TITLE
使用anchor_cluster.py得到自己数据集的anchor报错

### ISSUE THREAD

**Issue by xiaowanzizz** [PaddlePaddle/Paddle#30094]
Traceback (most recent call last):
  File "tools/anchor_cluster.py", line 362, in <module>
    main()
  File "tools/anchor_cluster.py", line 358, in main
    anchors = cluster()
  File "tools/anchor_cluster.py", line 95, in __call__
    self.get_whs()
  File "tools/anchor_cluster.py", line 71, in get_whs
    roidbs = self.dataset.get_roidb()
  File "/home/zzf/Desktop/PaddleDetection/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/home/zzf/Desktop/PaddleDetection/ppdet/data/source/coco.py", line 104, in load_roidb_and_cname2cid
    img_anno = coco.loadImgs(img_id)[0]
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/pycocotools/coco.py", line 230, in loadImgs
    return [self.imgs[id] for id in ids]
  File "/home/zzf/miniconda3/envs/torch1.7.0/lib/python3.7/site-packages/pycocotools/coco.py", line 230, in <listcomp>
    return [self.imgs[id] for id in ids]
KeyError: '0‘

**Comment by liym27** [comment]
您好，anchor_cluster.py 哪里提供的呢？数据集是什么？

**Comment by xiaowanzizz** [comment]
是paddle detection 里 tools 里的anchor cluster.py  数据集是德国交通标志数据集转化成coco style

**Comment by liym27** [comment]
好的。为了能更方便快捷处理该问题，建议您直接在 Paddle Detection repo 下提该issue，我们会有负责的同事跟进您的问题 
https://github.com/PaddlePaddle/PaddleDetection/issues/new

**Comment by xiaowanzizz** [comment]
已经将ISSUE 提交了

**Comment by liym27** [comment]
好的，已有 PaddleDetection 的同事跟进问题，当前 issue 将被关闭。感谢使用 Paddle。

**Comment by Petrichor686** [comment]
我也出现这个报错，能解决一下吗
