### ISSUE TITLE
集群上使用dataloader加载数据总是报错。

### ISSUE THREAD

**Issue by Green-li** [PaddlePaddle/Paddle#30133]
搜索过相关文档，修改`places=paddle.CPUPlace(),use_buffer_reader=False,use_shared_memory=False`等参数都不行。单机运行时可以加载数据，但是在超算平台运行的时候，就会报错。

## 相关配置
系统：Linux 3.10.0-514.21.1.el7.x86_64 Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
paddle：2.0.0-rc0
python: Python 3.7.7
GPU: 2080Ti
CUDA,10.1，cuDNN Version: 7.6
## 报错信息如下：
```
[2021-01-06 09:35:26,143] [    INFO] - Already cached /mnt/lustre02/jiangsu/aispeech/home/mll12/.paddlenlp/models/ernie-1.0/ernie_v1_chn_base.pdparams
W0106 09:35:26.144517 176367 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 75, Driver API Version: 10.1, Runtime API Version: 10.1
W0106 09:35:26.145131 176367 device_context.cc:346] device: 0, cuDNN Version: 7.6.
/mnt/lustre02/jiangsu/aispeech/home/mll12/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1175: UserWarning: Skip loading for classifier.weight. classifier.weight is not found in theprovided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/mnt/lustre02/jiangsu/aispeech/home/mll12/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1175: UserWarning: Skip loading for classifier.bias. classifier.bias is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
WARNING:root:DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    main()
  File "main.py", line 141, in main
    finetune(train_data_loader, dev_data_loader, label_list, tokenizer)
  File "main.py", line 112, in finetune
    for step, batch in enumerate(train_data_loader, start=1):
  File "/mnt/lustre02/jiangsu/aispeech/home/mll12/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 341, in __next__
    return self._reader.read_next_var_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::_Function_handler<void (), ThreadPool::enqueue<paddle::pybind::MultiDeviceFeedReader<paddle::operators::reader::LoDTensorBlockingQueue>::ReadAsync()::{lambda()#1}>(std::result_of&&, (paddle::pybind::MultiDeviceFeedReader<paddle::operators::reader::LoDTensorBlockingQueue>::ReadAsync()::{lambda()#1}&&)...)::{lambda()#1}>::_M_invoke(std::_Any_data const&)
2   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
3   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<paddle::pybind::MultiDeviceFeedReader<paddle::operators::reader::LoDTensorBlockingQueue>::Status>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::_Bind<paddle::pybind::MultiDeviceFeedReader<paddle::operators::reader::LoDTensorBlockingQueue>::ReadAsync()::{lambda()#1} ()>, std::allocator<int>, paddle::pybind::MultiDeviceFeedReader<paddle::operators::reader::LoDTensorBlockingQueue>::Status ()>::_M_run()::{lambda()#1}, paddle::pybind::MultiDeviceFeedReader<paddle::operators::reader::LoDTensorBlockingQueue>::Status> >::_M_invoke(std::_Any_data const&)
4   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
5   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
6   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)
```

代码：
```
from utils import convert_example, create_dataloader, evaluate

def read_from_tsv(file_path: str) -> list:
    data = []
    csv.register_dialect('tsv_dialect', delimiter='\t', quoting=csv.QUOTE_ALL)
    with open(file_path, "r") as wf:
        reader = csv.DictReader(wf, fieldnames=["desc", "dept"], dialect='tsv_dialect')
        for row in reader:
            item = dict(row)
            # yield item["desc"], item["dept"]
            data.append((item["desc"], item["dept"]))
    csv.unregister_dialect('tsv_dialect')
    return data

def create_dataloaders(tokenizer: ppnlp.transformers.ErnieTokenizer, label_list: List[str], batch_size: int = 32):
    batchify_fn = lambda samples, fn=Tuple(
        Pad(axis=0, pad_val=tokenizer.pad_token_id),  # input ids
        Pad(axis=0, pad_val=tokenizer.pad_token_id),  # segment ids
        Stack(dtype="int64")  # label
    ): [data for data in fn(samples)]

    label2idx = {
        label: idx
        for idx, label in enumerate(label_list)
    }

    trans_func = partial(
        convert_example,
        tokenizer=tokenizer,
        label2idx=label2idx,
        max_seq_length=256)

    train_path = "./data/dept_cls.train.tsv"
    train_ds = MapDatasetWrapper(read_from_tsv(train_path))
    train_data_loader = create_dataloader(
    train_ds,
    mode='train',
    batch_size=batch_size,
    batchify_fn=batchify_fn,
    trans_fn=trans_func)
```
`utils.py`来自项目“https://aistudio.baidu.com/aistudio/projectdetail/1428288”

**Comment by Green-li** [comment]
已解决，由于2.0.0-rc0代码不完善导致的。完成2.0.0-rc1就可以了。
