### ISSUE TITLE
Hapi 存在bug TypeError: forward() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#30320]
环境 paddle2.0rc1-gpu, cuda 10.2, ubuntu18.04, cudnn7.6.5

paddle2.0 rc1 使用高阶api model.fit（）接口训练 paddleseg 的部分模型，会报错，

W0112 10:11:30.308859 459358 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
W0112 10:11:30.310993 459358 device_context.cc:330] device: 0, cuDNN Version: 7.6.
2021-01-12 10:11:32 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
2021-01-12 10:11:32 [INFO]	There are 1525/1525 variables loaded into HRNet.
/home/w/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/distributed/parallel.py:118: UserWarning: Currently not a parallel execution environment, `paddle.distributed.init_parallel_env` will not do anything.
  warnings.warn(
The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/50
/home/w/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
Traceback (most recent call last):
  File "/home/w/python/ma/train.py", line 121, in <module>
    main(args)
  File "/home/w/python/ma/train.py", line 100, in main
    model.fit(train_ds,
  File "/home/w/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/hapi/model.py", line 1492, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/home/w/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/hapi/model.py", line 1798, in _run_one_epoch
    outs = getattr(self, mode + '_batch')(data[:len(self._inputs)],
  File "/home/w/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/hapi/model.py", line 940, in train_batch
    loss = self._adapter.train_batch(inputs, labels)
  File "/home/w/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/hapi/model.py", line 656, in train_batch
    losses = self.model._loss(*(to_list(outputs) + labels))
  File "/home/w/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
TypeError: forward() takes 3 positional arguments but 4 were given

运行过 paddleseg.model.FCN（backbone是hrnetw18） 没有问题，运行paddleseg.model.OCRNet, PSPNet等就出现上面这种报错，自行编写训练代码正常输出：
（下面是测试输出loss)
    for it, data in enumerate(train_loader):
        img = data[0]
        label = data[1]
        #print(img.shape)
        img = paddle.to_tensor(img)
        label = paddle.to_tensor(label)
        pred = net(img)
        #print(pred[0].shape)
        ls = loss(pred[0], label)
        print(np.mean(ls.numpy()))

W0112 10:03:25.436282 458257 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.2, Runtime API Version: 10.2
W0112 10:03:25.438438 458257 device_context.cc:330] device: 0, cuDNN Version: 7.6.
2021-01-12 10:03:27 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
2021-01-12 10:03:27 [INFO]	There are 1525/1525 variables loaded into HRNet.
0.6067874
0.624925
0.604115
0.6064513
0.6066702
0.60895455
0.605692
0.6115253
0.60572696
0.5984999
0.6046352
0.60126925
0.603066
0.6061119
0.6041645
0.6107049
0.6107404
0.60861415
0.6049708

Process finished with exit code 0

**Comment by michaelowenliu** [comment]
@Darki-luo Hi, Please refer to the issue: https://github.com/PaddlePaddle/PaddleSeg/issues/769
