### ISSUE TITLE
在使用GPU训练paddle的deepspeech的官方数据集时，graph加载报错

### ISSUE THREAD

**Issue by SullivanJia** [PaddlePaddle/Paddle#30379]
- 版本、环境信息：
    1）PaddlePaddle版本：2.00 rc1
    3）GPU：P4000，CUDA 10.1.243和CUDNN 7.6.0 nvdia driver :440.31 
    4）系统环境：linux ubuntu 16.04LTS，Python 2.7.18

- 模型信息
    使用tiny数据集在gpu下进行训练
- 复现信息：如为报错，请给出复现环境、复现步骤
- 执行 sh run_train.sh发生错误
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
- 

-----------  Configuration Arguments -----------
augment_conf_path: conf/augmentation.config
batch_size: 4
dev_manifest: data/tiny/manifest.tiny
init_from_pretrained_model: None
is_local: 1
learning_rate: 1e-05
max_duration: 27.0
mean_std_path: data/tiny/mean_std.npz
min_duration: 0.0
num_conv_layers: 2
num_epoch: 20
num_iter_print: 1
num_rnn_layers: 3
num_samples: 64
output_model_dir: ./checkpoints/tiny
rnn_layer_size: 2048
save_epoch: 1
share_rnn_weights: 1
shuffle_method: batch_shuffle_clipped
specgram_type: linear
test_off: 0
train_manifest: data/tiny/manifest.tiny
use_gpu: 1
use_gru: 0
use_sortagrad: 1
vocab_path: data/tiny/vocab.txt
------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    main()
  File "train.py", line 138, in main
    train()
  File "train.py", line 133, in train
    test_off=args.test_off)
  File "/workspace/DeepSpeech/model_utils/model.py", line 282, in train
    train_reader, log_probs, ctc_loss = self.create_network()
  File "/workspace/DeepSpeech/model_utils/model.py", line 106, in create_network
    for i in range(len(input_fields['names']))
  File "<decorator-gen-25>", line 2, in data
  File "/root/miniconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/framework.py", line 231, in __impl__
    ), "In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and '%s()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode." % func.__name__
AssertionError: In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and 'data()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode.
Thank you for contributing to PaddlePaddle.
按照提示修改后，发生如下错误
-----------  Configuration Arguments -----------
augment_conf_path: conf/augmentation.config
batch_size: 4
dev_manifest: data/tiny/manifest.tiny
init_from_pretrained_model: None
is_local: 1
learning_rate: 1e-05
max_duration: 27.0
mean_std_path: data/tiny/mean_std.npz
min_duration: 0.0
num_conv_layers: 2
num_epoch: 20
num_iter_print: 1
num_rnn_layers: 3
num_samples: 64
output_model_dir: ./checkpoints/tiny
rnn_layer_size: 2048
save_epoch: 1
share_rnn_weights: 1
shuffle_method: batch_shuffle_clipped
specgram_type: linear
test_off: 0
train_manifest: data/tiny/manifest.tiny
use_gpu: 1
use_gru: 0
use_sortagrad: 1
vocab_path: data/tiny/vocab.txt
------------------------------------------------
W0113 05:02:13.216773  5141 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0113 05:02:13.221822  5141 device_context.cc:330] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    main()
  File "train.py", line 138, in main
    train()
  File "train.py", line 133, in train
    test_off=args.test_off)
  File "/workspace/DeepSpeech/model_utils/model.py", line 337, in train
    return_numpy=False)
  File "/root/miniconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    six.reraise(*sys.exc_info())
  File "/root/miniconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1106, in run
    return_merged=return_merged)
  File "/root/miniconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1238, in _run_impl
    program._compile(scope, self.place)
  File "/root/miniconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/compiler.py", line 454, in _compile
    places=self._places)
  File "/root/miniconda3/envs/py27/lib/python2.7/site-packages/paddle/fluid/compiler.py", line 407, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
RuntimeError: (PreconditionNotMet) The graph doesn't have operators.
  [Hint: Expected op_deps_.size() > 0, but received op_deps_.size():0 <= 0:0.] (at /paddle/paddle/fluid/framework/details/fast_threaded_ssa_graph_executor.cc:55)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]

**Comment by lfchener** [comment]
目前 DeepSpeech 还暂不支持 Paddle 2.0，建议使用 Paddle 1.8 版本
