### ISSUE TITLE
AI STUDIO 中脚本任务环境没法用2.0是吗？

### ISSUE THREAD

**Issue by huochf** [PaddlePaddle/Paddle#30420]
我通过pip在脚本任务中安装2.0
但是运行时，import paddle出现了下面的错误！

Traceback (most recent call last):
  File "train.py", line 28, in <module>
    import paddle 
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/__init__.py", line 34, in <module>
    from .fluid import monkey_patch_variable
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/core.py", line 285, in <module>
    raise e
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/core.py", line 254, in <module>
    from .core_avx import *
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/core_avx.so)

**Comment by huochf** [comment]
你好，我刚才试了试pip 成功了！！！太开心了！
