### ISSUE TITLE
convert trainer_config.conf to binary_conf error

### ISSUE THREAD

**Issue by guozhizou** [PaddlePaddle/Paddle#3046]
when i try to convert a paddle trainer_config.conf to a binary conf, got this error:

```
Traceback (most recent call last):
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3113, in parse_config_and_serialize
    config = parse_config(config_file, config_arg_str)
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3089, in parse_config
    execfile(config_file, make_config_environment(config_file, config_args))
  File "trainer_config.conf", line 172, in <module>
    with mixed_layer() as mix:
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 45, in __wrapper__
    return func(*args, **kwargs)
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 45, in __wrapper__
    return func(*args, **kwargs)
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 45, in __wrapper__
    return func(*args, **kwargs)
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 219, in wrapper
    return method(*args, **kwargs)
TypeError: mixed_layer() takes at least 1 argument (2 given)
Traceback (most recent call last):
  File "convert_conf2binary.py", line 4, in <module>
    bin_str = paddle.trainer.config_parser.parse_config_and_serialize(sys.argv[1], "is_predict=1")
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3113, in parse_config_and_serialize
    config = parse_config(config_file, config_arg_str)
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3089, in parse_config
    execfile(config_file, make_config_environment(config_file, config_args))
  File "trainer_config.conf", line 172, in <module>
    with mixed_layer() as mix:
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 45, in __wrapper__
    return func(*args, **kwargs)
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 45, in __wrapper__
    return func(*args, **kwargs)
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 45, in __wrapper__
    return func(*args, **kwargs)
  File "/home/zc04/paddle/paddle_local_env/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 219, in wrapper
    return method(*args, **kwargs)
TypeError: mixed_layer() takes at least 1 argument (2 given)
```

trainer_config.conf error code:
```
164 for i, d in enumerate(view_input_dims):
165     view_dim = MLP(input=views['view_input%d' % (i+1)], size=d) \
166             .add(act='relu', size=views_hiddens[i][0], name='v%dh1' % (i+1), sparse_update=True) \
167             .add(act='relu', size=views_hiddens[i][1], name='v%dh2' % (i+1)) \
168             .add(act='tanh', size=dim, name='v%dh3' % (i+1)) \
169             .vec
170             #  .residual(batch_norm=False, name='vresidual1_%d' % (i+1)) \
171
172     with mixed_layer() as mix:
173         mix += dotmul_operator(a=view_dim, b=masks['mask%d' % (i+1)], scale=1)
174         view_dims.append(mix)
175
176 view_dim = addto_layer(input=view_dims, act=IdentityActivation())
177 predict = cos_sim(a=user_dim, b=view_dim, scale=1)
```

any suggestions?
thanks in advance.

**Comment by hedaoyuan** [comment]
`with mixed_layer() as mix:`这里有问题，应该至少有个size的值吧。

**Comment by guozhizou** [comment]
不用的，整个代码在MPI上训练都没问题，只是在做转化时出现里这个问题

**Comment by hedaoyuan** [comment]
你本地的环境是不是比较旧的？你看一下你本地`site-packages/paddle/trainer_config_helpers/layers.py`文件里面的mixed_layer函数参数定义，是size还是size=0？

**Comment by hedaoyuan** [comment]
@guozhizou 可以转换成功吗？

**Comment by guozhizou** [comment]
将网络结构修改下就可以转换了，但不同版本转化的bin貌似不兼容

**Comment by hedaoyuan** [comment]
> 但不同版本转化的bin貌似不兼容

这个具体是什么样想现象？config转换这部分代码好像一直都没有修改过。

**Comment by guozhizou** [comment]
不同版本转化的bin在sdk加载的时候会报错发自我的iPhone------------------ Original ------------------From: hedaoyuan  <notifications@github.com>Date: Wed,Jul 26,2017 3:26 PMTo: PaddlePaddle/Paddle <Paddle@noreply.github.com>Cc: guozhi zou <guozhizou@gmail.com>, Mention <mention@noreply.github.com>Subject: Re: [PaddlePaddle/Paddle] convert trainer_config.conf to binary_conferror (#3046)
但不同版本转化的bin貌似不兼容

这个具体是什么样想现象？config转换这部分代码好像一直都没有修改过。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PaddlePaddle/Paddle","title":"PaddlePaddle/Paddle","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PaddlePaddle/Paddle"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hedaoyuan in #3046: \u003e 但不同版本转化的bin貌似不兼容\r\n\r\n这个具体是什么样想现象？config转换这部分代码好像一直都没有修改过。"}],"action":{"name":"View Issue","url":"https://github.com/PaddlePaddle/Paddle/issues/3046#issuecomment-317971668"}}}

**Comment by hedaoyuan** [comment]
嗯，我想了解一下的是，哪个版本的bin到哪个版本运行报错了和报错的信息，这样方便定位问题。
