### ISSUE TITLE
编译最新dev分支，安装后找不到libpaddle_master.so，疑似编译选择变化未编译

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#3052]
- 编译最新dev分支，WITH_GOLANG=OFF，pip install 安装后出现如下错误：

```text
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    import paddle.v2 as paddle
  File "/home/caoying/.jumbo/lib/python2.7/site-packages/paddle/v2/__init__.py", line 36, in <module>
    import model
  File "/home/caoying/.jumbo/lib/python2.7/site-packages/paddle/v2/model.py", line 19, in <module>
    import paddle.v2.master
  File "/home/caoying/.jumbo/lib/python2.7/site-packages/paddle/v2/master/__init__.py", line 1, in <module>
    from client import *
  File "/home/caoying/.jumbo/lib/python2.7/site-packages/paddle/v2/master/client.py", line 5, in <module>
    lib = ctypes.cdll.LoadLibrary(path)
  File "/home/caoying/.jumbo/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/home/caoying/.jumbo/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/caoying/.jumbo/lib/python2.7/site-packages/paddle/v2/master/libpaddle_master.so: cannot open shared object file: No such file or directory
```

**Comment by typhoonzero** [comment]
This will fix https://github.com/PaddlePaddle/Paddle/pull/3045
