### ISSUE TITLE
DataLoader 中如何设置不对 collate_fn 的输出做检查和转换

### ISSUE THREAD

**Issue by AoZhang** [PaddlePaddle/Paddle#30713]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0-rc1
    2）CPU：-
    3）GPU：v100 cuda 10.1
    4）系统环境：CentOS 7.5
 
- 问题描述：开发 DataLoader 时自定义了 collate_fn 函数，返回的是一个 dict，包含 <name、data> 对。paddle 会对 collate_fn 的输出做检查和转换，发现不是标准 Tensor 就报错了。如何设置让 DataLoader 直接返回 collate_fn 的结果。

尝试了设置 batch_size = None, batch_sampler=None，依然不能解决问题。

- 报错信息如下

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/mnt/zhangao/miniconda3/envs/pp2/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/mnt/zhangao/miniconda3/envs/pp2/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/zhangao/miniconda3/envs/pp2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 338, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/mnt/zhangao/miniconda3/envs/pp2/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/mnt/zhangao/miniconda3/envs/pp2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 322, in _thread_loop
    tmp.set(slot, core.CPUPlace())
ValueError: (InvalidArgument) Input object type error or incompatible array data type. tensor.set() supports array with bool, float16, float32, float64, int8, int16, int32, int64, uint8 or uint16, please check your input or input array data type. (at /paddle/paddle/fluid/pybind/tensor_py.h:353)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]

```

- 可复现的代码
```
import paddle

def collate(batch):
    return {
            "key1": paddle.to_tensor(np.array([[1, 2, 3]] * len(batch))),
            "key2": paddle.to_tensor(np.array([[4, 5]] * len(batch))),
            "others": ['abc', 'def']
            }

dataset = xxx
loader = paddle.io.DataLoader(dataset, batch_size=2, collate_fn=collate)
for batch in loader():
    print(batch)

```

**Comment by Joejiong** [comment]
好的，收到正在查看

**Comment by Joejiong** [comment]
有简单复现的代码吗。可以贴一下

**Comment by AoZhang** [comment]
> 有简单复现的代码吗。可以贴一下

上边贴出来了。随便定义个 Dataset 即可。

**Comment by nku-shengzheliu** [comment]
楼主找到解决方法了吗

**Comment by CSQianDong** [comment]
+1

**Comment by thunder95** [comment]
+1

**Comment by suncheng-s** [comment]
有解决方法吗

**Comment by yjzhong89** [comment]
目前还存在这个问题，难道要直接修改源码？

**Comment by CSQianDong** [comment]
> 目前还存在这个问题，难道要直接修改源码？

直接改源码吧
