### ISSUE TITLE
2.0RC1版本 加载权重文件报错。

### ISSUE THREAD

**Issue by HXia-XXL** [PaddlePaddle/Paddle#30728]
使用AI Studio 2.0rc1版本，训练完成后，保存参数文件
`paddle.save(net.state_dict(), 'weight.pdparams')`
然后，在测试时候，使用`paddle.load() `导入参数文件：
```
 model_dict = paddle.load('weight.pdparams')
 net.set_state_dict(model_dict)
```
报错：
```
Traceback (most recent call last):
  File "work/proposed_method/test.py", line 133, in <module>
    model_dict = paddle.load('weight.pdparams')
  File "/opt/conda/envs/python35-paddle120-envb/python3.7/site-packages/paddle/framework/io.py", line 340, in load
    f, encoding='latin1')
_pickle.UnpicklingError: pickle data was truncated
```
参数文件正常大小300多M，前一次由于只保存到170M参数文件导致加载失败，这次的参数文件有300多M，与正常大小接近。
请问是加载方式有问题吗？？谢谢！

**Comment by chenwhql** [comment]
看起来没有问题，容易复现吗？能否给个case或者环境

**Comment by HXia-XXL** [comment]
在AI Studio又跑了遍后台任务，可以正常加载了。可能是后台任务保存权重不完整把。谢谢您
