### ISSUE TITLE
OSError: (External)  Cublas error, `CUSOLVER_STATUS_INTERNAL_ERROR`. An internal cuSolver ope     请问这种错误怎么解决

### ISSUE THREAD

**Issue by PotentialX** [PaddlePaddle/Paddle#30778]
今天跑飞桨官方mnist例程，构建网络部分报错如下：

W0129 18:26:32.738970 16225 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capabi                                                                                   lity: 8.6, Driver API Version: 11.1, Runtime API Version: 11.0
W0129 18:26:32.741225 16225 device_context.cc:372] device: 0, cuDNN Version: 8.0.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wyx/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/nn/layer/common.py                                                                                   ", line 124, in __init__
    self.weight = self.create_parameter(
  File "/home/wyx/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/laye                                                                                   rs.py", line 396, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/wyx/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/layer_helper                                                                                   _base.py", line 367, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/wyx/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py                                                                                   ", line 2979, in create_parameter
    initializer(param, self)
  File "/home/wyx/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/initializer.                                                                                   py", line 557, in __call__
    op = block._prepend_op(
  File "/home/wyx/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py                                                                                   ", line 3091, in _prepend_op
    _dygraph_tracer().trace_op(type,
  File "/home/wyx/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/trac                                                                                   er.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
OSError: (External)  Cublas error, `CUSOLVER_STATUS_INTERNAL_ERROR`. An internal cuSolver ope                                                                                   ration failed. This error is usually caused by a cudaMemcpyAsync() failure.  (at /paddle/padd                                                                                   le/fluid/platform/device_context.h:264)
  [operator < uniform_random > error]

**Comment by haozech** [comment]
你好，此错误可能是gpu显存不足造成的，建议检查gpu显存分配相关的代码
