### ISSUE TITLE
paddle infer的时候，出现如下错误

### ISSUE THREAD

**Issue by fanfannothing** [PaddlePaddle/Paddle#3111]
**场景**：使用cnn进行分类，model在paddlecloud上面训练生成。然后取model进行infer，出现错误（错误信息如下）。
**错误信息**：
Traceback (most recent call last):
  File "infer.py", line 93, in <module>
    batch_size=10)
  File "infer.py", line 57, in infer
    output_layer=prob_layer, parameters=parameters)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/inference.py", line 31, in __init__
    val.copyFromNumpyArray(parameters.get(name).flatten())
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 202, in get
    return self.__getitem__(key=parameter_name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 123, in __getitem__
    shape = self.get_shape(key)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 160, in get_shape
    raise ValueError("No such parameter %s" % key)
ValueError: No such parameter ___embedding_layer_0__.w0

**Comment by luotao1** [comment]
`No such parameter _embedding_layer_0.w0`，从结论看是生成的model中没有这个参数，因此无法加载。

**Comment by hedaoyuan** [comment]
Closed this issue, if there has any problem, feel free to reopen it.
