### ISSUE TITLE
创建了一个DataSet，但送入Model.fit在Linear的forward报错

### ISSUE THREAD

**Issue by wjy9** [PaddlePaddle/Paddle#31155]
paddle版本2.0-rc1
系统Centos7
python 3.6

按照文档中建立了一个RandomDataSet，
```
class RandomDataset(Dataset):
    def __init__(self, num_samples):
        self.num_samples = num_samples

    def __getitem__(self, idx):
        image = np.random.random([10, 181]).astype('float32')
        label = np.random.random([10, 1]).astype('float32')
        return image, label

    def __len__(self):
        return self.num_samples
```
送入Model.fit中训练（模型包括一个LSTM层和一个Linear层），

报错信息：
```
Traceback (most recent call last):
  File "paddle_lstm.py", line 41, in <module>
    verbose=1)
  File "/home/jywang/python_venv_tf1x/lib64/python3.6/site-packages/paddle/hapi/model.py", line 1493, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/home/jywang/python_venv_tf1x/lib64/python3.6/site-packages/paddle/hapi/model.py", line 1802, in _run_one_epoch
    data[len(self._inputs):])
  File "/home/jywang/python_venv_tf1x/lib64/python3.6/site-packages/paddle/hapi/model.py", line 941, in train_batch
    loss = self._adapter.train_batch(inputs, labels)
  File "/home/jywang/python_venv_tf1x/lib64/python3.6/site-packages/paddle/hapi/model.py", line 655, in train_batch
    * [to_variable(x) for x in inputs])
  File "/home/jywang/python_venv_tf1x/lib64/python3.6/site-packages/paddle/fluid/dygraph/container.py", line 86, in forward
    input = layer(input)
  File "/home/jywang/python_venv_tf1x/lib64/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/jywang/python_venv_tf1x/lib64/python3.6/site-packages/paddle/nn/layer/common.py", line 142, in forward
    x=input, weight=self.weight, bias=self.bias, name=self.name)
  File "/home/jywang/python_venv_tf1x/lib64/python3.6/site-packages/paddle/nn/functional/common.py", line 1469, in linear
    pre_bias = _varbase_creator(dtype=x.dtype)
AttributeError: 'tuple' object has no attribute 'dtype'
```
自己定位了一下，是在python/paddle/hapi/model.py#L654中，input在经过to_variable之后，从Tensor类型变成了一个(Tensor)的tuple，而在Linear的forward时由于tuple没有dtype成员报错。所以问题是to_variable之后为何会从一个Tensor类型变成了tuple，看了下to_variable代码，感觉不应该有问题，问题出在哪？

**Comment by bjjwwang** [comment]
您好 方便给个参考的文档链接吗，我复现下继续定位

**Comment by wjy9** [comment]
> 您好 方便给个参考的文档链接吗，我复现下继续定位

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/Dataset_cn.html#dataset
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/05_train_eval_predict_cn.html#model-fit

**Comment by wjy9** [comment]
这个问题有解决办法吗？
