### ISSUE TITLE
During word2vec trainig, save_inference_model report NoneType error

### ISSUE THREAD

**Issue by lidanqing-vv** [PaddlePaddle/Paddle#31184]
Hi, @luotao1 
During training word2vec model, save_inference_model report NoneType error
Build Paddle with following options
```
cmake ..  -DCMAKE_BUILD_TYPE=Release -DWITH_PYTHON=ON -DPY_VERSION=3.6 -DWITH_AVX=ON -DWITH_DISTRIBUTE=ON
```
Reproduction the training:
```
cd Fleet/2.0benchmark/ps/static/word2vec
python -u ../train.py -c benchmark.yaml
```
The output has following error
```
Epoch 0 Var LOSS        mean_0.tmp_0      - place: CPUPlace
  - shape: [1]
  - layout: NCHW
  - dtype: float
  - data: [2.74647]
2021-02-24 01:17:59,517 - INFO - Epoch: 0, using time 28.5967116355896 second, ips 36027.394097921366 word/sec.
Traceback (most recent call last):
  File "../train.py", line 245, in <module>
    benchmark_main.run()
  File "../train.py", line 65, in run
    self.run_worker()
  File "../train.py", line 125, in run_worker
    self.infer_target_var)
  File "/home/li/miniconda3/envs/myenv_python3.6/lib/python3.6/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 546, in save_inference_model
    self._runtime_handle._save_inference_model(
AttributeError: 'NoneType' object has no attribute '_save_inference_model'
```

**Comment by luotao1** [comment]
Please see  https://github.com/PaddlePaddle/Paddle/issues/30560#issuecomment-782529410
