### ISSUE TITLE
DataLoader使用多线程读取出错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#31259]
- PaddlePaddle 2.0.0
 - Ubuntu 18.04
 - Python 3.7

```python
from utils.model import PPASR
from paddle.io import DataLoader
from utils.data import PPASRDataset, collate_fn

dataset = PPASRDataset("dataset/manifest.train", "dataset/zh_vocab.json")
loader = DataLoader(dataset, batch_size=4, collate_fn=collate_fn, num_workers=4, shuffle=False)


model = PPASR(dataset.vocabulary)
for i, (inputs, labels, input_lens, label_lens) in enumerate(loader()):
    print(inputs.shape)
    print(labels.shape)
    print(input_lens.shape)
    print(label_lens.shape)
```

报错信息如下，如果num_workers设置为0就啥问题也没有
```
W0226 16:15:30.710134 13050 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W0226 16:15:30.711989 13050 device_context.cc:372] device: 0, cuDNN Version: 7.6.
ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    for i, (inputs, labels, input_lens, label_lens) in enumerate(loader()):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 788, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

```

**Comment by lyl120117** [comment]
我正好在分析Dataloader，PPASR应该是您自己的代码，我这边复现不了您的问题，根据经验，出现异常的代码应该是下面这段代码：
https://github.com/PaddlePaddle/Paddle/blob/e8d24b546a7def2efd00eabd8e36f9e9acb90df7/python/paddle/fluid/dataloader/dataloader_iter.py#L616-L621
您可以在621行后面增加下面的代码，看能不能看到具体是什么原因引起的异常。
```
                 elif isinstance(batch, Exception):
                     self._exit_thread_unexpectedly()
+                    six.reraise(type(batch), batch)
```

**Comment by yeyupiaoling** [comment]
@lyl120117 错误如下：

```
W0226 17:07:47.071539  8258 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W0226 17:07:47.073357  8258 device_context.cc:372] device: 0, cuDNN Version: 7.6.
ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    for i, (inputs, labels, input_lens, label_lens) in enumerate(loader()):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 789, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 631, in _thread_loop
    six.reraise(type(batch), batch)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:301)

```

**Comment by lyl120117** [comment]
@yeyupiaoling 方便提供一下您的代码吗？CUDA错误，我这边需要复现分析才行。

**Comment by yeyupiaoling** [comment]
```python
import paddle

from utils.model import PPASR
from paddle.io import DataLoader
from utils.data import PPASRDataset, collate_fn

# 使用 GPU训练
if paddle.is_compiled_with_cuda():
    paddle.set_device("gpu:0")

dataset = PPASRDataset("dataset/manifest.train", "dataset/zh_vocab.json")
loader = DataLoader(dataset, batch_size=4, collate_fn=collate_fn, num_workers=1, shuffle=False)

model = PPASR(dataset.vocabulary)
for i, (inputs, labels, input_lens, label_lens) in enumerate(loader()):
    print(inputs.shape)
    print(labels.shape)
    print(input_lens.shape)
    print(label_lens.shape)
```


```python
import wave
import librosa
import numpy as np
import paddle
from paddle.io import Dataset


# 加载二进制音频文件，转成numpy值
def load_audio(wav_path, normalize=True):
    with wave.open(wav_path) as wav:
        wav = np.frombuffer(wav.readframes(wav.getnframes()), dtype="int16")
        wav = wav.astype("float")
    if normalize:
        wav = (wav - wav.mean()) / wav.std()
    return wav


# 把音频数据执行短时傅里叶变换
def audio_to_stft(wav, normalize=True):
    D = librosa.stft(wav, n_fft=320, hop_length=160, win_length=320, window="hamming")
    spec, phase = librosa.magphase(D)
    spec = np.log1p(spec)
    spec = paddle.to_tensor(spec, dtype='float32')
    if normalize:
        spec = (spec - spec.mean()) / spec.std()
    return spec


# 音频数据加载器
class PPASRDataset(Dataset):
    def __init__(self, data_list, dict_path):
        super(PPASRDataset, self).__init__()
        # 获取数据列表
        with open(data_list) as f:
            idx = f.readlines()
        self.idx = [x.strip().split(",", 1) for x in idx]
        # 加载数据字典
        with open(dict_path) as f:
            labels = eval(f.read())
        self.vocabulary = dict([(labels[i], i) for i in range(len(labels))])

    def __getitem__(self, idx):
        # 分割音频路径和标签
        wav_path, transcript = self.idx[idx]
        # 读取音频并转换为短时傅里叶变换
        wav = load_audio(wav_path)
        stft = audio_to_stft(wav)
        # 将字符标签转换为int数据
        transcript = list(filter(None, [self.vocabulary.get(x) for x in transcript]))
        transcript = paddle.to_tensor(transcript, dtype='int32')
        return stft, transcript

    def __len__(self):
        return len(self.idx)


# 对一个batch的数据处理
def collate_fn(batch):
    # 找出音频长度最长的
    batch = sorted(batch, key=lambda sample: sample[0].shape[1], reverse=True)
    freq_size = batch[0][0].shape[0]
    max_audio_length = batch[0][0].shape[1]
    batch_size = len(batch)
    # 找出标签最长的
    batch_temp = sorted(batch, key=lambda sample: len(sample[1]), reverse=True)
    max_label_length = len(batch_temp[0][1])
    # 以最大的长度创建0张量
    inputs = paddle.zeros((batch_size, freq_size, max_audio_length), dtype='float32')
    labels = paddle.zeros((batch_size, max_label_length), dtype='int32')
    input_lens = []
    label_lens = []
    for x in range(batch_size):
        sample = batch[x]
        tensor = sample[0]
        target = sample[1]
        seq_length = tensor.shape[1]
        label_length = target.shape[0]
        # 将数据插入都0张量中，实现了padding
        inputs[x, :, :seq_length] = tensor[:, :]
        labels[x, :label_length] = target[:]
        input_lens.append(seq_length)
        label_lens.append(len(target))
    input_lens = paddle.to_tensor(input_lens, dtype='int64')
    label_lens = paddle.to_tensor(label_lens, dtype='int64')
    return inputs, labels, input_lens, label_lens

```

**Comment by lyl120117** [comment]
"dataset/manifest.train", "dataset/zh_vocab.json" 这两个文件也请帮忙提供一下，谢谢！

**Comment by yeyupiaoling** [comment]
@lyl120117 给你估计也 用不了，因为还有大量的音频文件，
你可以获取这个项目，执行这三个文件就可以得到这些文件：
```
https://github.com/yeyupiaoling/PPASR/blob/master/data/aishell.py
https://github.com/yeyupiaoling/PPASR/blob/master/create_manifest.py
https://github.com/yeyupiaoling/PPASR/blob/master/build_vocab.py
```

**Comment by lyl120117** [comment]
@yeyupiaoling 我这边定位到在collate_fn和PPASRDataset中将数据转成了Tensor，如果将num_workers设置为大于0的值，就会出现CUDA API errors，错误类型是cudaErrorInitializationError (error 3)，我将您的代码修改成了numpy可以正常运行，您可以参考一下，另外我这边测试num_workers=4比num_workers=0读数据会快很多，所以建议您使用num_workers=4或者更大的值，**代码如下：**
```

import wave
import librosa
import numpy as np
import paddle
from paddle.io import Dataset


# 加载二进制音频文件，转成numpy值
def load_audio(wav_path, normalize=True):
    with wave.open(wav_path) as wav:
        wav = np.frombuffer(wav.readframes(wav.getnframes()), dtype="int16")
        wav = wav.astype("float")
    if normalize:
        wav = (wav - wav.mean()) / wav.std()
    return wav


# 把音频数据执行短时傅里叶变换
def audio_to_stft(wav, normalize=True):
    D = librosa.stft(wav, n_fft=320, hop_length=160, win_length=320, window="hamming")
    spec, phase = librosa.magphase(D)
    spec = np.log1p(spec)
    # spec = paddle.to_tensor(spec, dtype='float32')
    if normalize:
        spec = (spec - spec.mean()) / spec.std()
    return spec


# 音频数据加载器
class PPASRDataset(Dataset):
    def __init__(self, data_list, dict_path):
        super(PPASRDataset, self).__init__()
        # 获取数据列表
        with open(data_list) as f:
            idx = f.readlines()
        self.idx = [x.strip().split(",", 1) for x in idx]
        # 加载数据字典
        with open(dict_path) as f:
            labels = eval(f.read())
        self.vocabulary = dict([(labels[i], i) for i in range(len(labels))])

    def __getitem__(self, idx):
        # 分割音频路径和标签
        wav_path, transcript = self.idx[idx]
        # 读取音频并转换为短时傅里叶变换
        wav = load_audio(wav_path)
        stft = audio_to_stft(wav)
        # 将字符标签转换为int数据
        transcript = list(filter(None, [self.vocabulary.get(x) for x in transcript]))
        transcript = np.array(transcript, dtype='int32')
        # transcript = paddle.to_tensor(transcript, dtype='int32')
        return stft, transcript

    def __len__(self):
        return len(self.idx)


# 对一个batch的数据处理
def collate_fn(batch):
    # 找出音频长度最长的
    batch = sorted(batch, key=lambda sample: sample[0].shape[1], reverse=True)
    freq_size = batch[0][0].shape[0]
    max_audio_length = batch[0][0].shape[1]
    batch_size = len(batch)
    # 找出标签最长的
    batch_temp = sorted(batch, key=lambda sample: len(sample[1]), reverse=True)
    max_label_length = len(batch_temp[0][1])
    # 以最大的长度创建0张量
    # inputs = paddle.zeros((batch_size, freq_size, max_audio_length), dtype='float32')
    # labels = paddle.zeros((batch_size, max_label_length), dtype='int32')
    inputs = np.zeros((batch_size, freq_size, max_audio_length), dtype='float32')
    labels = np.zeros((batch_size, max_label_length), dtype='int32')
    input_lens = []
    label_lens = []
    for x in range(batch_size):
        sample = batch[x]
        tensor = sample[0]
        target = sample[1]
        seq_length = tensor.shape[1]
        label_length = target.shape[0]
        # 将数据插入都0张量中，实现了padding
        inputs[x, :, :seq_length] = tensor[:, :]
        labels[x, :label_length] = target[:]
        input_lens.append(seq_length)
        label_lens.append(len(target))
    # input_lens = paddle.to_tensor(input_lens, dtype='int64')
    # label_lens = paddle.to_tensor(label_lens, dtype='int64')
    input_lens = np.array(input_lens, dtype='int64')
    label_lens = np.array(label_lens, dtype='int64')
    return inputs, labels, input_lens, label_lens
```

@yongqiangma 上述问题是由于在Datasets中使用了paddle.to_tensor这种API将数据转成Tensor引起的，从已有的DEBUG日志目前无法定位root case，后续我会继续跟进这个问题。

**Comment by yeyupiaoling** [comment]
@lyl120117 好的，谢谢，我可不可以理解为，使用多线程读取数据，预处理部分都不能包含Tensor

**Comment by lyl120117** [comment]
@yeyupiaoling 是的，在GPU环境多线程情况下预处理部分不能将数据转成Tensor，这应该是一个BUG，目前还没完全定位到root case，后续我会跟进这个问题，谢谢！

**Comment by yeyupiaoling** [comment]
@lyl120117 好的，谢谢。

**Comment by yeyupiaoling** [comment]
@lyl120117 又遇到了个新问题，在AIStudio环境，如果batch size设置大于4，就会报错。错误如下。如果把`num_workers`设置为0，batch size设置大也不会保存。这些问题只在AI Studio出现，本地不会出现这个问题。
```python
import paddle

from utils.model import PPASR
from paddle.io import DataLoader
from utils.data import PPASRDataset, collate_fn

# 使用 GPU训练
if paddle.is_compiled_with_cuda():
    paddle.set_device("gpu:0")

dataset = PPASRDataset("dataset/manifest.train", "dataset/zh_vocab.json")
loader = DataLoader(dataset, batch_size=64, collate_fn=collate_fn, num_workers=2, shuffle=False)

model = PPASR(dataset.vocabulary)
for i, (inputs, labels, input_lens, label_lens) in enumerate(loader()):
    print(inputs.shape)
    print(labels.shape)
    print(input_lens)
    print(label_lens)
    print('=============')
```

错误信息：
```
aistudio@jupyter-206-1597936:~/PPASR$ python test.py 
W0302 16:25:18.617630 31048 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0302 16:25:18.622676 31048 device_context.cc:372] device: 0, cuDNN Version: 7.6.
ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    for i, (inputs, labels, input_lens, label_lens) in enumerate(loader()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 789, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 694, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 625, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 710, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 2 workers exit unexpectedly, pids: 31108, 31109
```

**Comment by lyl120117** [comment]
@yeyupiaoling 试一下Dataloader不用共享内存use_shared_memory=False。

```
    loader = DataLoader(dataset, batch_size=64, collate_fn=collate_fn, use_shared_memory=False, num_workers=2, shuffle=False)
```

**Comment by yeyupiaoling** [comment]
@lyl120117 这样设置可以了，谢谢。这个API的文档参数默认值不对：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html#dataloader

**Comment by lyl120117** [comment]
> @lyl120117 这样设置可以了，谢谢。这个API的文档参数默认值不对：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html#dataloader

这个@谁去改一下...

**Comment by yeyupiaoling** [comment]
@GT-ZhangAcer

**Comment by GT-ZhangAcer** [comment]
> @GT-ZhangAcer

 太惨了，我不是RD，合个代码还得再找人，这可咋整啊。
不行不行，大佬都at我了，我得at文档小哥
@TCChenlong
