### ISSUE TITLE
Dataloader出现异常后，框架中的异常处理有BUG，不会抛出异常！

### ISSUE THREAD

**Issue by lyl120117** [PaddlePaddle/Paddle#31250]
- PaddlePaddle 2.0.0
- Ubuntu 18.04
- Python 3.7.7

**Dataloader经常会遇到下面的报错提示：**
> 2021-02-26 11:09:08,871 - ERROR - DataLoader reader thread raised an exception!
> Traceback (most recent call last):
>   File "test/test_datasets.py", line 90, in <module>
>     for i in loader:
>   File "/home/ps/anaconda3/envs/paddle_dev/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 779, in __next__
>     data = self._reader.read_next_var_list()
> SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
>   [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

上面的报错很不友好，影响定位问题的效率，通过分析Framework的代码：
https://github.com/PaddlePaddle/Paddle/blob/e8d24b546a7def2efd00eabd8e36f9e9acb90df7/python/paddle/fluid/dataloader/dataloader_iter.py#L342-L346
这是_DataLoaderIterSingleProcess中的异常处理，可以看到346行有通过six.reraise抛出异常，但是实际上这里并没有抛出任何异常！

**测试代码如下：**

```
class DefaultDataset(Dataset):
    def __init__(self):
        self.samples = np.arange(10).astype('float32')

    def __getitem__(self, index):
        fname = self.samples[index]
        return fname

    def __len__(self):
        return len(self.samples)

if __name__ == "__main__":
    dataset = DefaultDataset()
    loader = DataLoader(dataset, batch_size=2, collate_fn=None, num_workers=0, shuffle=False)
    for i in loader:
        print(i)
```

**Comment by heavengate** [comment]
我本地测试了一下你提供的代码，应该是有报错信息的
全量报错信息
```
WARNING:root:DataLoader reader thread raised an exception.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 347, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 317, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 65, in fetch
    data = self.collate_fn(data)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 81, in default_collate_fn
    for i, item in enumerate(items):
TypeError: 'numpy.float32' object is not iterable

Traceback (most recent call last):
  File "test.py", line 65, in <module>
    for i in loader:
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 365, in __next__
    return self._reader.read_next_var_list()
SystemError:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const
1   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
2   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
5   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
6   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/ssd3/git/Paddle/paddle/fluid/operators/reader/blocking_queue.h:158)
```

其中python端报错信息为
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 347, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 317, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 65, in fetch
    data = self.collate_fn(data)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 81, in default_collate_fn
    for i, item in enumerate(items):
TypeError: 'numpy.float32' object is not iterable
```

**Comment by lyl120117** [comment]
@heavengate 请问您的python版本是多少，我的是3.7.7

**Comment by heavengate** [comment]
> @heavengate 请问您的python版本是多少，我的是3.7.7

3.7.0

**Comment by lyl120117** [comment]
@heavengate 刚刚我用AIStudio试了，可以正常抛出异常，但是我这边的服务器更换了Python版本也不会抛出异常，看来也不是python版本的问题。

**Comment by lyl120117** [comment]
@heavengate 您好，我这边验证，注释掉self._thread.daemon = True 303这一行，可以正常抛出异常https://github.com/PaddlePaddle/Paddle/blob/c40b98e06857701137d54a20b6a0981560906b1f/python/paddle/fluid/dataloader/dataloader_iter.py#L301-L304
通过查看[Python官方文档](https://docs.python.org/zh-cn/3.7/library/threading.html#threading.Thread)，daemon这个参数会影响到主线程是否退出，请问您当时是出于什么目的将daemon设置为True？

**Comment by lyl120117** [comment]
@heavengate 您好，AIStudio上面用notebook测试可以正常抛出异常，用CMD命令行测试无法抛出异常。
