### ISSUE TITLE
@paddle.jit.to_static 动转静失败

### ISSUE THREAD

**Issue by supercyt** [PaddlePaddle/Paddle#31322]
**出错代码：**
```
@paddle.jit.to_static()
def forward(self, x):
    """ forward
    """
    # first order
    out = self._fm_first_order(x)
    out = nn.functional.sigmoid(out)
    return out   

def _fm_first_order(self, x):
    """ fm first order
    """
    first_order_emb = []

    for idx, feat in enumerate(self.attribute_size):
        first_order_emb_arr = getattr(self, "first_order_{}_embedding".format(feat))(x[:, idx])
        first_order_emb.append(first_order_emb_arr)

    first_order_emb = paddle.stack(first_order_emb, 1)
    first_order_out = paddle.sum(first_order_emb, 1)
    return first_order_out

paddle.jit.save(layer=model, path=train_config.model_params,
                input_spec=[static.InputSpec(shape=[None, len(train_config.attribute_size)], dtype='int64')])

self.attribute_size = {"user":105,"plan":376,"unit":636,"idea":1289,"wd":9,"hr":24}
```

**报错信息：**

> /home/caoyitong/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
W0301 15:45:13.527985 32599 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.0
W0301 15:45:13.530265 32599 device_context.cc:372] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "/home/caoyitong/Projects/PycharmProjects/secoo/train.py", line 102, in <module>
    main()
  File "/home/caoyitong/Projects/PycharmProjects/secoo/train.py", line 95, in main
    model.fit(loader_train, loader_val, criterion, optim, epochs=train_config.num_epoch, verbose=True)
  File "/home/caoyitong/Projects/PycharmProjects/secoo/model.py", line 52, in fit
    pred = self(x)
  File "/home/caoyitong/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/caoyitong/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 352, in __call__
    error_data.raise_new_exception()
  File "/home/caoyitong/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 189, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
KeyError: 'In transformed code:
    File "/home/caoyitong/Projects/PycharmProjects/secoo/model.py", line 120, in forward (* user code *)
        first_order_out = self._fm_first_order(x)
    File "/tmp/tmpm36jyr1j.py", line 27, in _fm_first_order
        for_loop_body_0, [__for_loop_var_index_0, idx, x, self])
    File "/home/caoyitong/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 44, in convert_while_loop
        loop_vars = _run_py_while(cond, body, loop_vars)
    File "/home/caoyitong/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 58, in _run_py_while
        loop_vars = body(*loop_vars)
    File "/home/caoyitong/Projects/PycharmProjects/secoo/model.py", line 133, in _fm_first_order (* user code *)
        for idx, feat in enumerate(self.attribute_size):
    KeyError: 0'

Process finished with exit code 1

**Comment by zhhsplendid** [comment]
当前log看不出什么，是否有更多信息？或者您在debug过程可以参考以下意见：

1. KeyError常出现于访问某容器类型时该key不存在。从代码报错可能是self.attribute_size在取为0的key时出错，检查一下self.attribute_size前后是否有什么错误。

2. 在没有用动转静时，单单动态图运行是否有错？请保证动态图运行没有问题

3. 如果在动态图运行无错情况下，参考这里的一些debug方式看看转静态图后是什么出问题：
https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/paddle/guides/04_dygraph_to_static/debugging_cn.md

**Comment by supercyt** [comment]
> 当前log看不出什么，是否有更多信息？或者您在debug过程可以参考以下意见：
> 
>     1. KeyError常出现于访问某容器类型时该key不存在。从代码报错可能是self.attribute_size在取为0的key时出错，检查一下self.attribute_size前后是否有什么错误。
> 
>     2. 在没有用动转静时，单单动态图运行是否有错？请保证动态图运行没有问题
> 
>     3. 如果在动态图运行无错情况下，参考这里的一些debug方式看看转静态图后是什么出问题：
>        https://github.com/PaddlePaddle/FluidDoc/blob/develop/doc/paddle/guides/04_dygraph_to_static/debugging_cn.md

2. 动态图没有问题。

目前定位出问题是，对于**dict类型的遍历**导致转换失败，dict改为list后，问题解决。
