### ISSUE TITLE
在训练过程中突然出现错误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#31410]
- PaddlePaddle
 - Ubuntu 18.04
 - Python3.7

```
------------------------------------------------
I0303 17:47:30.625275  9714 nccl_context.cc:189] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
I0303 17:47:30.625272  9715 nccl_context.cc:189] init nccl context nranks: 2 local rank: 1 gpu id: 1 ring id: 0
W0303 17:47:30.898056  9714 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W0303 17:47:30.898113  9715 device_context.cc:362] Please NOTE: device: 1, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.2
W0303 17:47:30.925174  9715 device_context.cc:372] device: 1, cuDNN Version: 7.6.
W0303 17:47:30.925184  9714 device_context.cc:372] device: 0, cuDNN Version: 7.6.
Epoch 0: ExponentialDecay set learning rate to 0.001.
Epoch 0: ExponentialDecay set learning rate to 0.001.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::BasicEngine::Execute()
1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&)
2   paddle::framework::TensorCopySync(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
3   void paddle::memory::Copy<paddle::platform::CUDAPlace, paddle::platform::CPUPlace>(paddle::platform::CUDAPlace, void*, paddle::platform::CPUPlace, void const*, unsigned long, CUstream_st*)
4   paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)
5   paddle::framework::SignalHandle(char const*, int)
6   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1614764975 (unix time) try "date -d @1614764975" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e8000025c5) received by PID 9715 (TID 0x7fc58782b740) from PID 9669 ***]

Traceback (most recent call last):
  File "train.py", line 140, in <module>
    dist.spawn(train, args=(args,))
  File "/home/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 449, in spawn
    while not context.join():
  File "/home/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 255, in join
    self._throw_exception(error_index)
  File "/home/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 263, in _throw_exception
    (error_index, name))
Exception: Process 0 terminated with signal SIGKILL.
```

**Comment by GaoWei8** [comment]
初步看起来是进行memory copy的时候发生的错误。使用的是什么样的代码呢

**Comment by yeyupiaoling** [comment]
@GaoWei8 这个：https://github.com/yeyupiaoling/PPASR/blob/master/train.py
这个错误有时出现，重启就不出现了。
