### ISSUE TITLE
建议paddle支持直接对布尔类型的tensor进行聚合运算

### ISSUE THREAD

**Issue by jesse01** [PaddlePaddle/Paddle#31615]
版本：2.0.1
举例：
pytorch:
a1 = torch.tensor([1,2,3,4,5])
a2 = torch.tensor([1,2,3,2,1])
torch.sum(a1==a2)
Out[22]: tensor(3)

paddle:
b1 = paddle.to_tensor([1,2,3,4,5])
b2 = paddle.to_tensor([1,2,3,2,1])
paddle.sum(b1==b2)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-09aa5a7698d2>", line 1, in <module>
    paddle.sum(b1==b2)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/tensor/math.py", line 757, in sum
    'reduce_all', reduce_all_flag)
RuntimeError: (NotFound) Operator reduce_sum does not have kernel for data_type[bool]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /home/teamcity/work/ef54dc8a5b211854/paddle/fluid/imperative/prepared_operator.cc:128)
  [operator < reduce_sum > error]

这样处理才可以：
paddle.sum(paddle.cast(b1==b2, dtype='int64'))
Out[25]: 
Tensor(shape=[1], dtype=int64, place=CPUPlace, stop_gradient=True,
       [3])

建议：不用cast，像pytorch，numpy一样直接可对布尔数组进行sum、mean等聚合运算

**Comment by ForFishes** [comment]
您好，这个问题其实普通api对数据类型提升（type promote）的支持。目前仅支持通用的加减乘除类api。您的问题，内部将进行反馈，后续进展将会及时告知您。
