### ISSUE TITLE
无法安装CUDA10.2的Develop (nightly build)版本

### ISSUE THREAD

**Issue by mikeshi80** [PaddlePaddle/Paddle#31690]
按照官网提示，选择 `Develop (nightly build)`，版本选择Linux， CUDA10.2，给出的安装指令

```shell
python -m pip install --pre paddlepaddle-gpu==2.1.0.dev0.post102 -f https://paddlepaddle.org.cn/whl/cu102/mkl/develop.html
Looking in links: https://paddlepaddle.org.cn/whl/cu102/mkl/develop.html
```

执行后会提示

```
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'paddlepaddle-gpu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 317, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 82, in from_requirement
    if not cands:
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in __bool__
    return any(self)
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 38, in _iter_built
    candidate = func()
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 169, in _make_candidate_from_link
    name=name, version=version,
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
    wheel_version = Version(wheel.version)
  File "/opt/PaddleOCR/venv/lib/python3.7/site-packages/pip/_vendor/packaging/version.py", line 298, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
pip._vendor.packaging.version.InvalidVersion: Invalid version: '2.1.0.dev0.post102'
```

**Comment by iclementine** [comment]
应该是pip版本号太高了, 可以先尝试pip==20.2.4

**Comment by mikeshi80** [comment]
OK，不过这个问题还是得解决，随着python的版本升高，自带的pip也会慢慢升上去的。

**Comment by iclementine** [comment]
好的，我们这边后面会兼容新的 pip 版本。
