### ISSUE TITLE
Cuda error(700), an illegal memory access was encountered.

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#31738]
Platform : AIStudio
Version: 2.0.1

地址：项目“retinafacce_v2”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/1664965/55c1200e3ddf4d358b5977be112bb1a4

当我使用`python train_v2.py --data_path ./widerface --batch 1 --save_path ./out`时，能够正常训练
```
9.04667854309082 6.236481189727783 0.6025031208992004 2.207693576812744

---- [Epoch 0/200, Batch 0/12880] ----
+----------------+--------------------+
| loss name      | value              |
+----------------+--------------------+
| total_loss     | 9.04667854309082   |
| classification | 6.236481189727783  |
| bbox           | 0.6025031208992004 |
| landmarks      | 2.207693576812744  |
+----------------+--------------------+
10.863420486450195 6.981016159057617 1.2865004539489746 2.5959033966064453

---- [Epoch 0/200, Batch 10/12880] ----
+----------------+--------------------+
| loss name      | value              |
+----------------+--------------------+
| total_loss     | 10.863420486450195 |
| classification | 6.981016159057617  |
| bbox           | 1.2865004539489746 |
| landmarks      | 2.5959033966064453 |
+----------------+--------------------+
10.308184623718262 6.715460777282715 1.3114498853683472 2.2812740802764893

---- [Epoch 0/200, Batch 20/12880] ----
+----------------+--------------------+
| loss name      | value              |
+----------------+--------------------+
| total_loss     | 10.308184623718262 |
| classification | 6.715460777282715  |
| bbox           | 1.3114498853683472 |
| landmarks      | 2.2812740802764893 |
+----------------+--------------------+
8.718461990356445 5.682147026062012 1.0791350603103638 1.9571796655654907
```
当我使用`python train_v2.py --data_path ./widerface --batch 2 --save_path ./out`时会出现以下错误
```
---- [Epoch 0/200, Batch 0/6440] ----
+----------------+--------------------+
| loss name      | value              |
+----------------+--------------------+
| total_loss     | 8.279301643371582  |
| classification | 5.27414608001709   |
| bbox           | 1.0533459186553955 |
| landmarks      | 1.9518101215362549 |
+----------------+--------------------+
Traceback (most recent call last):
  File "train_v2.py", line 160, in <module>
    main()
  File "train_v2.py", line 90, in main
    classification_loss, bbox_regression_loss,ldm_regression_loss = retinaface([data[0].cuda(), data[1].cuda()])
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/stream/cuda_stream.cc:65)
```
只有设置`batch=1`时才能正常运行，我感到很玄乎

**Comment by Aurelius84** [comment]
从报错来看，出现了非法内存访问。您可否帮忙用CPU训练下看是否正常，我们先看下是否是某个GPUKernel的问题。另外只有batch_size=2会触发么，其他bs是否也会触发这个问题？

**Comment by Aurelius84** [comment]
我这边clone了你的AI Studio上的代码，切换到CPU上来执行，发现batch_size = 2 时也会出错，日志如下：
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::BasicEngine::Execute()
1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&)
2   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
3   paddle::framework::SignalHandle(char const*, int)
4   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1616156303 (unix time) try "date -d @1616156303" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x18) received by PID 2621 (TID 0x7fc568c73700) from PID 24 ***]
```

请问可否确认下你的训练数据预处理逻辑是否在batch_size值不同时返回的batch_data是否符合预期？比如可能有 `//2` 到时空shape的情况。我这边也从框架层面排查下

**Comment by GuoQuanhao** [comment]
> 我这边clone了你的AI Studio上的代码，切换到CPU上来执行，发现batch_size = 2 时也会出错，日志如下：
> 
> ```
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   paddle::imperative::BasicEngine::Execute()
> 1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&)
> 2   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)
> 3   paddle::framework::SignalHandle(char const*, int)
> 4   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: `Segmentation fault` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1616156303 (unix time) try "date -d @1616156303" if you are using GNU date ***]
>   [SignalInfo: *** SIGSEGV (@0x18) received by PID 2621 (TID 0x7fc568c73700) from PID 24 ***]
> ```
> 
> 请问可否确认下你的训练数据预处理逻辑是否在batch_size值不同时返回的batch_data是否符合预期？比如可能有 `//2` 到时空shape的情况。我这边也从框架层面排查下

直接运行`dataloader_v2.py`可以返回正确的维度，我在`dataloader_v2.py`中有main测试代码，由于paddle的tensor切片比较局限，我在loss.py中来换切换tensor与numpy完成一些矩阵操作，我不知道是不是这个原因

**Comment by Aurelius84** [comment]
> 由于paddle的tensor切片比较局限，我在loss.py中来换切换tensor与numpy完成一些矩阵操作，我不知道是不是这个原因


在组网的中间将tensor转为numpy操作，可能存在一些潜在的不符合预期的情况，比如梯度的计算可能被截断导致参数更新偏离预期。想问下您这边对 tensor切片有什么特殊的功能需求。可否提供下想要支持功能的代码示例，我们这边也会进行支持。

**Comment by GuoQuanhao** [comment]
```python
import paddle
import numpy as np

x_numpy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
bool_numpy = x_numpy > 2
print(bool_numpy)
print(x_numpy[bool_numpy])

x_tensor = paddle.to_tensor(x_numpy)
bool_tensor = x_tensor > 2
print(bool_tensor)
print(x_tensor[bool_tensor])
```
```
[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[3 4 5 6 7 8 9]
Tensor(shape=[3, 3], dtype=bool, place=CPUPlace, stop_gradient=True,
       [[False, False, True ],
        [True , True , True ],
        [True , True , True ]])
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-26-c146294855f5> in <module>
     10 bool_tensor = x_tensor > 2
     11 print(bool_tensor)
---> 12 print(x_tensor[bool_tensor])
ValueError: (InvalidArgument) Currently, VarBase.__getitem__() only allows indexing by Integers, Slices, and tuples of these types, but received Tensor in 1th slice item
  [Hint: Expected PyCheckInteger(slice_item) || ((((PyObject*)(slice_item))->ob_type) == &PySlice_Type) == true, but received PyCheckInteger(slice_item) || ((((PyObject*)(slice_item))->ob_type) == &PySlice_Type):0 != true:1.] (at /paddle/paddle/fluid/pybind/imperative.cc:378)
```
我认为如果tensor能够支持numpy的操作习惯及其操作方法，这将对新手更友好

**Comment by Aurelius84** [comment]
非常感谢您的建议，我们会排期尽快支持这样的功能

**Comment by GuoQuanhao** [comment]
> 非常感谢您的建议，我们会排期尽快支持这样的功能

谢谢
