### ISSUE TITLE
OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`

### ISSUE THREAD

**Issue by jeffzhengye** [PaddlePaddle/Paddle#31777]
Since tensorflow is running very well on my machine, I assume the env is configured correctly.
What could be the problems and how I may fix it?
`
    results = self.detector.object_detection(images = [ori_img], use_gpu = self.use_gpu, score_thresh = self.threshold, visualization=False)
  File "/home/user/anaconda3/lib/python3.7/site-packages/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/home/user/.paddlehub/modules/yolov3_resnet50_vd_coco2017/module.py", line 211, in object_detection
    [image_tensor, im_size_tensor])
OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. An unsupported value or parameter was passed to the function (a negative vector size, for example).  (at /paddle/paddle/fluid/platform/cuda_helper.h:93)
`

**Comment by jeffzhengye** [comment]
这是paddlehub的问题应该。
result = predictor.object_detection(images=[cv2.imread('best-face-oil.png')], use_gpu=True)

AttributeError: 'YOLOv3ResNet50Coco2017' object has no attribute 'gpu_predictor'

不知道为什么不能使用gpu预测

**Comment by Bob-AFei** [comment]
> 您好，我们已经收到了您的问题，会安排技术人员尽快解答您的问题，请耐心等待。请您再次检查是否提供了清晰的问题描述、复现代码、环境&版本、报错信息等。同时，您也可以通过查看[官网API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)、[常见问题](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)、[历史Issue](https://github.com/PaddlePaddle/Paddle/issues)、[AI社区](https://ai.baidu.com/forum/topic/list/168)来寻求解答。祝您生活愉快～
> 
> Hi! We've received your issue and please be patient to get responded. We will arrange technicians to answer your questions as soon as possible. Please make sure that you have posted enough message to demo your request. You may also check out the [API](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/index_cn.html)，[FAQ](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/index_cn.html)，[Github Issue](https://github.com/PaddlePaddle/Paddle/issues) and [AI community](https://ai.baidu.com/forum/topic/list/168) to get the answer.Have a nice day!

Hi developer, I met the same issue today. Here is my Log. My paddle version is 2.0.1.post110


```2021-03-22 22:45:35,512 - INFO - unique_endpoints {''}
2021-03-22 22:45:35,513 - INFO - Found /home/bob/anaconda3/envs/dev/lib/python3.7/site-packages/ppgan/apps/photo2cartoon_genA2B_weight.pdparams
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-6da9bba74531> in <module>
----> 1 a = apps.Photo2CartoonPredictor()

~/anaconda3/envs/dev/lib/python3.7/site-packages/ppgan/apps/photo2cartoon_predictor.py in __init__(self, output_path, weight_path)
     41             weight_path = get_path_from_url(P2C_WEIGHT_URL, cur_path)
     42 
---> 43         self.genA2B = ResnetUGATITP2CGenerator()
     44         params = paddle.load(weight_path)
     45         self.genA2B.set_state_dict(params)

~/anaconda3/envs/dev/lib/python3.7/site-packages/ppgan/models/generators/resnet_ugatit_p2c.py in __init__(self, input_nc, output_nc, ngf, img_size, n_blocks, light)
     41         DownBlock += [
     42             nn.Pad2D([3, 3, 3, 3], 'reflect'),
---> 43             nn.Conv2D(input_nc, ngf, kernel_size=7, stride=1, bias_attr=False),
     44             nn.InstanceNorm2D(ngf, weight_attr=False, bias_attr=False),
     45             nn.ReLU()

~/anaconda3/envs/dev/lib/python3.7/site-packages/paddle/nn/layer/conv.py in __init__(self, in_channels, out_channels, kernel_size, stride, padding, dilation, groups, padding_mode, weight_attr, bias_attr, data_format)
    637             weight_attr=weight_attr,
    638             bias_attr=bias_attr,
--> 639             data_format=data_format)
    640 
    641     def forward(self, x):

~/anaconda3/envs/dev/lib/python3.7/site-packages/paddle/nn/layer/conv.py in __init__(self, in_channels, out_channels, kernel_size, transposed, dims, stride, padding, padding_mode, output_padding, dilation, groups, weight_attr, bias_attr, data_format)
    133             shape=filter_shape,
    134             attr=self._param_attr,
--> 135             default_initializer=_get_default_param_initializer())
    136         self.bias = self.create_parameter(
    137             attr=self._bias_attr, shape=[self._out_channels], is_bias=True)

~/anaconda3/envs/dev/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in create_parameter(self, shape, attr, dtype, is_bias, default_initializer)
    406             temp_attr = None
    407         return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
--> 408                                              default_initializer)
    409 
    410     @deprecated(

~/anaconda3/envs/dev/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py in create_parameter(self, attr, shape, dtype, is_bias, default_initializer, stop_gradient, type)
    370                 type=type,
    371                 stop_gradient=stop_gradient,
--> 372                 **attr._to_kwargs(with_initializer=True))
    373         else:
    374             self.startup_program.global_block().create_parameter(

~/anaconda3/envs/dev/lib/python3.7/site-packages/paddle/fluid/framework.py in create_parameter(self, *args, **kwargs)
   2982                 pass
   2983             else:
-> 2984                 initializer(param, self)
   2985         return param
   2986 

~/anaconda3/envs/dev/lib/python3.7/site-packages/paddle/fluid/initializer.py in __call__(self, var, block)
    362                 "use_mkldnn": False
    363             },
--> 364             stop_gradient=True)
    365 
    366         if var.dtype == VarDesc.VarType.FP16:

~/anaconda3/envs/dev/lib/python3.7/site-packages/paddle/fluid/framework.py in _prepend_op(self, *args, **kwargs)
   3098                                        kwargs.get("outputs", {}), attrs
   3099                                        if attrs else {},
-> 3100                                        kwargs.get("stop_gradient", False))
   3101         else:
   3102             op_desc = self.desc._prepend_op()

~/anaconda3/envs/dev/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py in trace_op(self, type, inputs, outputs, attrs, stop_gradient)
     43         self.trace(type, inputs, outputs, attrs,
     44                    framework._current_expected_place(), self._has_grad and
---> 45                    not stop_gradient)
     46 
     47     def train_mode(self):

OSError: (External)  Cublas error, `CUBLAS_STATUS_INVALID_VALUE`. An unsupported value or parameter was passed to the function (a negative vector size, for example).  (at /paddle/paddle/fluid/platform/cuda_helper.h:93)
  [operator < gaussian_random > error]`

```
