### ISSUE TITLE
B站强化学习 parl的quickstart例子跑不了

### ISSUE THREAD

**Issue by TronYY** [PaddlePaddle/Paddle#31827]
****************************************
Paddle version: None
Paddle With CUDA: None
OS: Windows 10
Python version: 3.8.5
CUDA version: 11.1.74
Build cuda_11.1.relgpu_drvr455TC455_06.29069683_0
cuDNN version: None
Nvidia driver version: 456.43

B站上科科老师的强化学习教程“世界冠军带你从零实践强化学习”第三节课，让我们安paddlepaddle 1.6.3的版本，可是压根没有这个版本了。安装最新版 但是parl的quickstart例子又跑不了，要求paddlepaddle版本小于2.0

在parl那边提了这个问题 但是那边解决不了 让我问这边  https://github.com/PaddlePaddle/PARL/issues/590

**Comment by vslyu** [comment]
cuda11只有paddle2.0以上的预编译包，建议你这边降低cuda的版本再安装paddle1.8或者1.7的低版本，或者在cuda11的环境下自行编译paddle版本。

**Comment by TronYY** [comment]
> cuda11只有paddle2.0以上的预编译包，建议你这边降低cuda的版本再安装paddle1.8或者1.7的低版本，或者在cuda11的环境下自行编译paddle版本。


那我把cuda卸载，只使用cpu



然后我按照parl那边的建议whl安装paddlepaddle 1.6.3的
```
(python37) E:\New folder>pip install paddlepaddle-1.6.3-cp37-cp37m-win_amd64.whl
Processing e:\new folder\paddlepaddle-1.6.3-cp37-cp37m-win_amd64.whl
Requirement already satisfied: graphviz in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (0.16)
Requirement already satisfied: matplotlib in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (3.3.4)
Requirement already satisfied: objgraph in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (3.5.0)
Requirement already satisfied: scipy in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (1.6.1)
Requirement already satisfied: pyyaml in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (5.4.1)
Requirement already satisfied: numpy>=1.12 in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (1.20.1)
Requirement already satisfied: Pillow in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (7.2.0)
Requirement already satisfied: opencv-python in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (4.5.1.48)
Requirement already satisfied: six in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (1.15.0)
Requirement already satisfied: decorator in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (4.4.2)
Requirement already satisfied: requests>=2.20.0 in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (2.25.1)
Requirement already satisfied: funcsigs in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (1.0.2)
Requirement already satisfied: nltk in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (3.5)
Requirement already satisfied: rarfile in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (4.0)
Requirement already satisfied: prettytable in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (2.1.0)
Requirement already satisfied: protobuf>=3.1.0 in d:\anaconda3\envs\python37\lib\site-packages (from paddlepaddle==1.6.3) (3.15.6)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\anaconda3\envs\python37\lib\site-packages (from requests>=2.20.0->paddlepaddle==1.6.3) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\envs\python37\lib\site-packages (from requests>=2.20.0->paddlepaddle==1.6.3) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in d:\anaconda3\envs\python37\lib\site-packages (from requests>=2.20.0->paddlepaddle==1.6.3) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in d:\anaconda3\envs\python37\lib\site-packages (from requests>=2.20.0->paddlepaddle==1.6.3) (4.0.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in d:\anaconda3\envs\python37\lib\site-packages (from matplotlib->paddlepaddle==1.6.3) (2.4.7)
Requirement already satisfied: cycler>=0.10 in d:\anaconda3\envs\python37\lib\site-packages (from matplotlib->paddlepaddle==1.6.3) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\anaconda3\envs\python37\lib\site-packages (from matplotlib->paddlepaddle==1.6.3) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in d:\anaconda3\envs\python37\lib\site-packages (from matplotlib->paddlepaddle==1.6.3) (2.8.1)
Requirement already satisfied: joblib in d:\anaconda3\envs\python37\lib\site-packages (from nltk->paddlepaddle==1.6.3) (1.0.1)
Requirement already satisfied: regex in d:\anaconda3\envs\python37\lib\site-packages (from nltk->paddlepaddle==1.6.3) (2021.3.17)
Requirement already satisfied: tqdm in d:\anaconda3\envs\python37\lib\site-packages (from nltk->paddlepaddle==1.6.3) (4.59.0)
Requirement already satisfied: click in d:\anaconda3\envs\python37\lib\site-packages (from nltk->paddlepaddle==1.6.3) (7.1.2)
Requirement already satisfied: wcwidth in d:\anaconda3\envs\python37\lib\site-packages (from prettytable->paddlepaddle==1.6.3) (0.2.5)
Requirement already satisfied: importlib-metadata in d:\anaconda3\envs\python37\lib\site-packages (from prettytable->paddlepaddle==1.6.3) (3.7.3)
Requirement already satisfied: typing-extensions>=3.6.4 in d:\anaconda3\envs\python37\lib\site-packages (from importlib-metadata->prettytable->paddlepaddle==1.6.3) (3.7.4.3)
Requirement already satisfied: zipp>=0.5 in d:\anaconda3\envs\python37\lib\site-packages (from importlib-metadata->prettytable->paddlepaddle==1.6.3) (3.4.1)
paddlepaddle is already installed with the same version as the provided wheel. Use --force-reinstall to force an installation of the wheel.
```
为啥显示paddle没有装上呢
****************************************
Paddle version: None
Paddle With CUDA: None
OS: Windows 10
Python version: 3.7.10
CUDA version: None
cuDNN version: None
Nvidia driver version: 456.43
****************************************

然后跑train.py
```
(python37) E:\PARL\examples\QuickStart>python train.py
[32m[03-24 13:34:26 MainThread @logger.py:224][0m Argv: train.py
[33m[03-24 13:34:27 MainThread @__init__.py:24][0m [5m[33mWRN[0m No deep learning framework was found, but it's ok for parallel computation.
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from cartpole_agent import CartpoleAgent
  File "E:\PARL\examples\QuickStart\cartpole_agent.py", line 16, in <module>
    import paddle.fluid as fluid
ModuleNotFoundError: No module named 'paddle.fluid'

(python37) E:\PARL\examples\QuickStart>
```

**Comment by vslyu** [comment]
你这边python train.py使用的python3.7的conda虚拟环境吧？建议你先在此环境下使用python -m pip list |grep paddle确认下paddlepaddle是否装上？～
