### ISSUE TITLE
eval时conv2d层报错，'Filter' (position 1) must be Tensor, but got Parameter

### ISSUE THREAD

**Issue by lu1kaifeng** [PaddlePaddle/Paddle#31842]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.1
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：cuda100
    4）系统环境：windows 10 python37
-预测信息
    1）C++预测：请您提供预测库安装包的版本信息，及其中的version.txt文件
    2）CMake包含路径的完整命令
    3）API信息（如调用请提供）
    4）预测库来源：官网下载/特殊环境（如BCLOUD编译）
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：eval时conv层报错
```
Traceback (most recent call last):
  File "E:\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\base.py", line 315, in _decorate_function
    return func(*args, **kwargs)
  File "E:\PyCharmProjects\pedDec\deep_sort\deepaddle\feature_extractor.py", line 46, in __call__
    features = self.net(im_batch)
  File "E:\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\PyCharmProjects\pedDec\deep_sort\deepaddle\model.py", line 84, in forward
    x = self.conv(x)
  File "E:\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\container.py", line 95, in forward
    input = layer(input)
  File "E:\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\envs\PaddleDetection\lib\site-packages\paddle\nn\layer\conv.py", line 660, in forward
    use_cudnn=self._use_cudnn)
  File "E:\envs\PaddleDetection\lib\site-packages\paddle\nn\functional\conv.py", line 119, in _conv_nd
    pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)
ValueError: (InvalidArgument) conv2d(): argument 'Filter' (position 1) must be Tensor, but got Parameter (at D:\v2.0.1\paddle\paddle/fluid/pybind/op_function.h:56)

python-BaseException
W0324 14:11:58.970736 10036 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.0
W0324 14:11:58.977742 10036 device_context.cc:372] device: 0, cuDNN Version: 7.6.

Process finished with exit code 1
```

模型类
```
class Net(nn.Layer):
    def __init__(self, num_classes=751, reid=False):
        super(Net, self).__init__()
        # 3 128 64
        self.conv = nn.Sequential(
            nn.Conv2D(3, 64, 3, stride=1, padding=1),
            nn.BatchNorm2D(64),
            nn.ReLU(),
            # nn.Conv2d(32,32,3,stride=1,padding=1),
            # nn.BatchNorm2d(32),
            # nn.ReLU(inplace=True),
            nn.MaxPool2D(3, 2, padding=1),
        )
        # 32 64 32
        self.layer1 = make_layers(64, 64, 2, False)
        # 32 64 32
        self.layer2 = make_layers(64, 128, 2, True)
        # 64 32 16
        self.layer3 = make_layers(128, 256, 2, True)
        # 128 16 8
        self.layer4 = make_layers(256, 512, 2, True)
        # 256 8 4
        self.avgpool = nn.AvgPool2D((8, 4), 1)
        # 256 1 1 
        self.reid = reid
        self.classifier = nn.Sequential(
            nn.Linear(512, 256),
            nn.BatchNorm1D(256),
            nn.ReLU(),
            nn.Dropout(),
            nn.Linear(256, num_classes),
        )

    def forward(self, x):
        x = self.conv(x)
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)
        x = self.avgpool(x)
        x = reshape(x,(x.shape[0],-1))#x.view(x.size(0), -1)
        # B x 128
        if self.reid:
            x = div(x, x.norm(p=2, dim=1, keepdim=True))
            return x
        # classifier
        x = self.classifier(x)
        return x

```
报错代码 pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)

**Comment by vslyu** [comment]
你的Filter 应该传入个tensor进去，而非Parameter

**Comment by lu1kaifeng** [comment]
> 你的Filter 应该传入个tensor进去，而非Parameter

传进去的，就是tensor，训练没有问题，一旦恢复ckpt之后传进去输入，就给我报这个

**Comment by vslyu** [comment]
你的paddle版本用的哪个版本？如果为2.0，
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/io/save_cn.html#save 建议使用新的save/load

**Comment by FrankWhh** [comment]
请问解决了吗？

**Comment by FrankWhh** [comment]
请问解决了吗？
