### ISSUE TITLE
怎么方便的从硬盘加载图像分类图片数据集，并且计算得到训练集的均值和方差？

### ISSUE THREAD

**Issue by JimXu1989** [PaddlePaddle/Paddle#31886]
你好，
可以提供从上述功能的示例程序吗？
我使用的是ubuntu20.04 ,paddle 2.0.0 我在计算的时候得到下列报错：
fail to perform transform [<paddle.vision.transforms.transforms.ToTensor object at 0x7f6f6f13f250>] with error: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:229)
 and stack:
Traceback (most recent call last):
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/vision/transforms/transforms.py", line 117, in __call__
    data = f(data)
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/vision/transforms/transforms.py", line 273, in __call__
    outputs.append(apply_func(inputs[i]))
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/vision/transforms/transforms.py", line 347, in _apply_image
    return F.to_tensor(img, self.data_format)
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/vision/transforms/functional.py", line 91, in to_tensor
    return F_pil.to_tensor(pic, data_format)
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py", line 75, in to_tensor
    img = paddle.to_tensor(np.array(pic, copy=False))
  File "<decorator-gen-118>", line 2, in to_tensor
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/tensor/creation.py", line 173, in to_tensor
    return paddle.Tensor(
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:229)

fail to perform transform [<paddle.vision.transforms.transforms.ToTensor object at 0x7f6f6f13f250>] with error: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:229)
 and stack:
Traceback (most recent call last):
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/vision/transforms/transforms.py", line 117, in __call__
    data = f(data)
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/vision/transforms/transforms.py", line 273, in __call__
    outputs.append(apply_func(inputs[i]))
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/vision/transforms/transforms.py", line 347, in _apply_image
    return F.to_tensor(img, self.data_format)
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/vision/transforms/functional.py", line 91, in to_tensor
    return F_pil.to_tensor(pic, data_format)
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/vision/transforms/functional_pil.py", line 75, in to_tensor
    img = paddle.to_tensor(np.array(pic, copy=False))
  File "<decorator-gen-118>", line 2, in to_tensor
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/home/jim/.local/lib/python3.8/site-packages/paddle/tensor/creation.py", line 173, in to_tensor
    return paddle.Tensor(
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:229)

**Comment by heavengate** [comment]
您好，当前paddle不支持在子进程里操作GPU Tensor，只支持子进程操作CPU Tensor，可以试下`paddle.set_device('cpu')`
