### ISSUE TITLE
paddle 1.8.2 save inference 是报错var read_file_0.tmp_5 not in this bloc

### ISSUE THREAD

**Issue by gromzhu** [PaddlePaddle/Paddle#31885]
paddle 1.8.2 
python3
save_inference_model时报错
Traceback (most recent call last):
  File "run_page_transformer_seq_label.py", line 421, in <module>
    main(args)
  File "run_page_transformer_seq_label.py", line 365, in main
    params_filename="__params__"
  File "/home/users/zhuzhenyu02/.local/lib/python3.6/site-packages/paddle/fluid/io.py", line 1246, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "/home/users/zhuzhenyu02/.local/lib/python3.6/site-packages/paddle/fluid/io.py", line 1042, in prepend_feed_ops
    out = global_block.var(name)
  File "/home/users/zhuzhenyu02/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2377, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var read_file_0.tmp_5 not in this block

**Comment by Shixiaowei02** [comment]
您好，请问 1.8.5 有问题，1.5 没问题；指的是完全相同的代码么？如果是这样，2.0 会有问题吗？

**Comment by Shixiaowei02** [comment]
> 请您再次检查是否提供了清晰的问题描述、复现代码、环境&版本、报错信息等。

您好，请问 1.8.5 有问题，1.5 没问题；指的是完全相同的代码么？如果是这样，2.0 会有问题吗；如果 1.5 没问题，而相同代码在 2.0 有问题；我们会在 2.0 上进行复现并修复。谢谢

**Comment by gromzhu** [comment]
> > 请您再次检查是否提供了清晰的问题描述、复现代码、环境&版本、报错信息等。
> 
> 您好，请问 1.8.5 有问题，1.5 没问题；指的是完全相同的代码么？如果是这样，2.0 会有问题吗；如果 1.5 没问题，而相同代码在 2.0 有问题；我们会在 2.0 上进行复现并修复。谢谢

代码完全相同，py3 1.8.2报错，py2 1.5保存成功

**Comment by Shixiaowei02** [comment]
> > > 请您再次检查是否提供了清晰的问题描述、复现代码、环境&版本、报错信息等。
> > 
> > 
> > 您好，请问 1.8.5 有问题，1.5 没问题；指的是完全相同的代码么？如果是这样，2.0 会有问题吗；如果 1.5 没问题，而相同代码在 2.0 有问题；我们会在 2.0 上进行复现并修复。谢谢
> 
> 代码完全相同，py3 1.8.2报错，py2 1.5保存成功

请使用最新的 2.0 版本试下，谢谢
