### ISSUE TITLE
OCR INT8 models raise mkldnn error

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#31928]
C++ API
Ubuntu 16.04
6148 CPU
MKLDNN
GCC 4.8.5

Contact danqing to download the demo.

Make and install paddle develop (commit id:`51eb29de18adcf8c20272218f105eb1c2135cc09`) or paddle release2.0 (commit id: `c7a6a1f9610a9ee018c19d89950d76b38f33aed1`).

Run `sh run.sh`  and then `./build/model_test --single_thread=true`  or `./build/model_test --single_thread=false`, get the error as follows.

```
(gdb) bt
#0  0x00007fc40b30fa5a in dnnl::impl::primitive_hashing::get_attr_hash(dnnl_primitive_attr const&) ()
   from /work/Paddle/build_gcc485/third_party/install/mkldnn/lib/libdnnl.so.2
#1  0x00007fc40b308954 in dnnl::impl::lru_primitive_cache_t::add(dnnl::impl::primitive_hashing::key_t const&, std::shared_future<dnnl::impl::primitive_cache_t::cache_value_t> const&) ()
   from /work/Paddle/build_gcc485/third_party/install/mkldnn/lib/libdnnl.so.2
#2  0x00007fc40b30928e in dnnl::impl::lru_primitive_cache_t::get_or_add(dnnl::impl::primitive_hashing::key_t const&, std::shared_future<dnnl::impl::primitive_cache_t::cache_value_t> const&) ()
   from /work/Paddle/build_gcc485/third_party/install/mkldnn/lib/libdnnl.so.2
#3  0x00007fc40b362bb5 in dnnl_status_t dnnl::impl::primitive_t::create_primitive_common<dnnl::impl::cpu::ncsp_batch_normalization_fwd_t<(dnnl_data_type_t)3>, dnnl::impl::cpu::ncsp_batch_normalization_fwd_t<(d$
nl_data_type_t)3>::pd_t>(std::pair<std::shared_ptr<dnnl::impl::primitive_t>, bool>&, dnnl::impl::cpu::ncsp_batch_normalization_fwd_t<(dnnl_data_type_t)3>::pd_t const*, dnnl_engine*, bool) ()
   from /work/Paddle/build_gcc485/third_party/install/mkldnn/lib/libdnnl.so.2
#4  0x00007fc40b30a0e0 in dnnl_primitive_desc::create_primitive_iface(std::pair<dnnl_primitive*, bool>&) const () from /work/Paddle/build_gcc485/third_party/install/mkldnn/lib/libdnnl.so.2
#5  0x00007fc40b2fd296 in dnnl::impl::primitive_create(dnnl_primitive**, dnnl_primitive_desc const*) ()
   from /work/Paddle/build_gcc485/third_party/install/mkldnn/lib/libdnnl.so.2
#6  0x00007fc4109b9bdc in paddle::platform::MKLDNNHandlerT<float, dnnl::batch_normalization_forward, dnnl::batch_normalization_backward>::AcquireForwardPrimitive() ()
   from /work/Paddle/build_gcc485/paddle_inference_install_dir/paddle/lib/libpaddle_inference.so
#7  0x00007fc4109c0069 in paddle::operators::BatchNormMKLDNNOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const ()
   from /work/Paddle/build_gcc485/paddle_inference_install_dir/paddle/lib/libpaddle_inference.so
#8  0x00007fc4109c12f3 in std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::BatchN$
rmMKLDNNOpKernel<float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
() from /work/Paddle/build_gcc485/paddle_inference_install_dir/paddle/lib/libpaddle_inference.so
#9  0x00007fc40f97729b in paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const ()
   from /work/Paddle/build_gcc485/paddle_inference_install_dir/paddle/lib/libpaddle_inference.so
#10 0x00007fc40f9778d3 in paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const ()
   from /work/Paddle/build_gcc485/paddle_inference_install_dir/paddle/lib/libpaddle_inference.so
#11 0x00007fc40f970a94 in paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&) ()
   from /work/Paddle/build_gcc485/paddle_inference_install_dir/paddle/lib/libpaddle_inference.so
#12 0x00007fc40f9b019f in paddle::framework::NaiveExecutor::Run() ()
   from /work/Paddle/build_gcc485/paddle_inference_install_dir/paddle/lib/libpaddle_inference.so
#13 0x00007fc40f65abf5 in paddle::AnalysisPredictor::ZeroCopyRun() ()
   from /work/Paddle/build_gcc485/paddle_inference_install_dir/paddle/lib/libpaddle_inference.so
#14 0x000000000041f652 in paddle_infer::BasePredictor::predictor (this=0x7fff6da806d0)
    at /work/autil/0328_vis_deploy/inference_2.0_api/mobilenet_test.cc:97
#15 0x000000000041d436 in paddle_infer::test_predictor (
    model_path="./roll_data/data/roll_data/det/cpu_models/fluid_model/models_merge",
    input_path="./roll_inout/image_text_detect_input_layer_0.txt", model_name="roll",
    use_mkldnn=false, threads=1, repeatss=1)
```

Run the next command to check whether the error is fixed or not.
```
./build/model_test --single_thread=true
./build/model_test --single_thread=false
```

**Comment by juncaipeng** [comment]
@lidanqing-intel @wojtuss  
The customers meet this bug, please take a look at it with the highest priority. Thank you.

**Comment by juncaipeng** [comment]
@wojtuss 

The customer wants to deploy several model on the same time. They create all predictors in the main thread, and then run predictors in the Child thread. Besides, all predictors use MKLDNN. Does this way cause problems?

**Comment by wojtuss** [comment]
@juncaipeng 
Using single thread I get the error every time. Using multiple threads, the error sometimes occurs and sometimes does not.
I am still looking into it.

**Comment by wojtuss** [comment]
To me it looks like a problem with oneDNN cache. I asked oneDNN team for help.

**Comment by lidanqing-vv** [comment]
I experienced with command
```
DNNL_PRIMITIVE_CACHE_CAPACITY=0 ./build/model_test --single_thread=true
```

and found the prediction passed successfully.

While following command
```
./build/model_test --single_thread=true
```
reported same error log as Uss, Wojciech showes. (oneDNN2.2 by default turn on oneDNN primitive cache, so it looks cache mechanism now)

oneDNN team is now investigating it.

**Comment by lidanqing-vv** [comment]
1. Customer give new fp32 or quant model (scales NAN)
2. oneDNN team will deal with NAN case
3. add DNNL_PRIMITIVE_CACHE_CAPACITY=0

**Comment by lidanqing-vv** [comment]
@juncaipeng  oneDNN made a fix dealing with the NAN case, now they are preparing a public oneDNN patch that contains this fix. It will be public in 1 or 2 days. We could use it after we receive it.
