### ISSUE TITLE
读取不同size图像数据读取器报错

### ISSUE THREAD

**Issue by Game-Li** [PaddlePaddle/Paddle#32106]
- 标题：读取不同size图像数据读取器报错
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.0
    2）CPU：
    3）GPU：CUDA 10  CUDNN 7.6.5
    4）系统环境：Python3.7

- 问题描述：使用paddle.io.DataLoader读取不同size图像数据读取器时报错如下，（是我操作的问题还是paddle数据读取器不支持变化的size图片数据呢？）：

WARNING:root:DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "G:\Pycharm\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "G:\Pycharm\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "*********/G_GAN.py", line 576, in <module>
    train()
  File "*********/G_GAN.py", line 524, in train
    for loader in trainloader:
  File "G:\Anaconda3\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 365, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at D:\v2.0.0\paddle\paddle/fluid/operators/reader/blocking_queue.h:158)
Exception in thread Thread-10:
Traceback (most recent call last):
  File "G:\Anaconda3\Anaconda3\envs\paddle_env\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "G:\Anaconda3\Anaconda3\envs\paddle_env\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Anaconda3\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 347, in _thread_loop
    six.reraise(*sys.exc_info())
  File "G:\Anaconda3\Anaconda3\envs\paddle_env\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "G:\Anaconda3\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 317, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "G:\Anaconda3\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 65, in fetch
    data = self.collate_fn(data)
  File "G:\Anaconda3\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 93, in default_collate_fn
    tmp = layers.stack(slot, axis=0)
  File "G:\Anaconda3\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\layers\nn.py", line 10069, in stack
    return core.ops.stack(x, 'axis', axis)
ValueError: (InvalidArgument) Dims of all Inputs(X) must be the same, but received input 1 dim is:339, 510, 3 not equal to input 0 dim:333, 510, 3.
  [Hint: Expected input_dims[i] == input_dims[0], but received input_dims[i]:339, 510, 3 != input_dims[0]:333, 510, 3.] (at D:\v2.0.0\paddle\paddle\fluid\operators\stack_op.cc:46)
  [operator < stack > error]

数据集__getitem__:
    def __getitem__(self, index):

        LR_data = np.array(cv2.imread(list(TRAIN_DATA_LIST[index].keys())[0], cv2.IMREAD_COLOR))
        HR_data = np.array(cv2.imread(list(TRAIN_DATA_LIST[index].values())[0], cv2.IMREAD_COLOR))

        LR_data = (LR_data / 127.5) - 1
        HR_data = (HR_data / 127.5) - 1

        print(LR_data.shape)
        print(LR_data)

        # LR_data = self.transforms(LR_data)
        print(LR_data)
        # HR_data = self.transforms(HR_data)

        LR_data = paddle.to_tensor(LR_data, dtype='float32')
        HR_data = paddle.to_tensor(HR_data, dtype='float32')

        return LR_data, HR_data

**Comment by MissPenguin** [comment]
训练时输入size需要固定的哈

**Comment by Game-Li** [comment]
我使用的是全卷积网络，请问怎么输入动态变化的size图像呢？有相应的API吗？

**Comment by MissPenguin** [comment]
确定是全卷积没有fc的话，batchsize=1应该就没问题。不支持batchsize>1时变长输入。

**Comment by Game-Li** [comment]
ok，懂了，谢谢啦
