### ISSUE TITLE
批量图片预测时operator < rnn > error 

### ISSUE THREAD

**Issue by aaferrero** [PaddlePaddle/Paddle#32172]
环境：python3.7 cuda10.0 nvidia geforce1080 8G，paddlepaddle-gpu 2,0,0 windows 10
批量图片预测时候，经常会报这个错误，这个有什么办法解决么，环境是paddle-paddle-gpu 2.0.0
报错信息：
Traceback (most recent call last):
File "E:/fanxi_wu/programs/wrapper_drink_ocr_v3/pp_ocr/tools/infer/classify_modules.py", line 2302, in
classify_modules.get_ksf_detect_areas(ori_img, image_name, module_name=module_name)
File "E:/fanxi_wu/programs/wrapper_drink_ocr_v3/pp_ocr/tools/infer/classify_modules.py", line 2112, in get_ksf_detect_areas
content_imgs, crop_imgs_dict, image_name=file_name)
File "E:/fanxi_wu/programs/wrapper_drink_ocr_v3/pp_ocr/tools/infer/classify_modules.py", line 1542, in get_content_result
rec_res, elapse = copy.deepcopy(self.text_recognizer(img_crop_list))
File "E:\fanxi_wu\programs\wrapper_drink_ocr_v3\pp_ocr_1\tools_2\infer\predict_rec.py", line 117, in call
self.predictor.run()
OSError: In user code:

File "tools/export_model.py", line 75, in <module>
  main()
File "tools/export_model.py", line 70, in main
  paddle.jit.save(model, save_path)
File "<decorator-gen-60>", line 2, in save
  
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
  return wrapped_func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
  return func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
  concrete_program = static_func.concrete_program
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 461, in concrete_program
  concrete_program, _ = self.get_concrete_program(*input_spec)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
  concrete_program, partial_program_layer = self._program_cache[cache_key]
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 684, in __getitem__
  self._caches[item] = self._build_once(item)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 675, in _build_once
  class_instance=cache_key.class_instance)
File "<decorator-gen-58>", line 2, in from_func_spec
  
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
  return wrapped_func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
  return func(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 625, in from_func_spec
  outputs = static_func(*inputs)
File "/tmp/tmpqk3xmm2v.py", line 22, in forward
  false_fn_1, (x,), (x,), (x,))
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
  return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
  return true_fn(*true_args) if pred else false_fn(*false_args)
File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/architectures/base_model.py", line 76, in forward
  x = self.neck(x)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
  outputs = self.forward(*inputs, **kwargs)
File "/tmp/tmpmf6_4ac7.py", line 14, in forward
  (x,), (x,))
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
  return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
  return true_fn(*true_args) if pred else false_fn(*false_args)
File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/necks/rnn.py", line 91, in forward
  x = self.encoder(x)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
  outputs = self.forward(*inputs, **kwargs)
File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/necks/rnn.py", line 45, in forward
  x, _ = self.lstm(x)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
  outputs = self.forward(*inputs, **kwargs)
File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1035, in forward
  return self._cudnn_impl(inputs, initial_states, sequence_length)
File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1012, in _cudnn_impl
  type="rnn", inputs=inputs, outputs=outputs, attrs=attrs)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
  stop_gradient=stop_gradient)
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2849, in append_op
  attrs=kwargs.get("attrs", None))
File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1934, in __init__
  for frame in traceback.extract_stack():

ExternalError:  Cudnn error, CUDNN_STATUS_INTERNAL_ERROR  (at D:\v2.0.0\paddle\paddle\fluid\operators\rnn_op.cu.cc:420)
  [operator < rnn > error]

**Comment by wawltor** [comment]
您好，上面的问题看起来是本地的cuda版本和paddle版本不适配的问题，您可以尝试用法conda的方式来安装paddlepaddle，因conda可以自动适配paddle版本和本地cuda版本，具体的安装方式可以看 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/windows-conda.html，谢谢！

**Comment by lacoboi** [comment]
> 环境：python3.7 cuda10.0 nvidia geforce1080 8G，paddlepaddle-gpu 2,0,0 windows 10
> 批量图片预测时候，经常会报这个错误，这个有什么办法解决么，环境是paddle-paddle-gpu 2.0.0
> 报错信息：
> Traceback (most recent call last):
> File "E:/fanxi_wu/programs/wrapper_drink_ocr_v3/pp_ocr/tools/infer/classify_modules.py", line 2302, in
> classify_modules.get_ksf_detect_areas(ori_img, image_name, module_name=module_name)
> File "E:/fanxi_wu/programs/wrapper_drink_ocr_v3/pp_ocr/tools/infer/classify_modules.py", line 2112, in get_ksf_detect_areas
> content_imgs, crop_imgs_dict, image_name=file_name)
> File "E:/fanxi_wu/programs/wrapper_drink_ocr_v3/pp_ocr/tools/infer/classify_modules.py", line 1542, in get_content_result
> rec_res, elapse = copy.deepcopy(self.text_recognizer(img_crop_list))
> File "E:\fanxi_wu\programs\wrapper_drink_ocr_v3\pp_ocr_1\tools_2\infer\predict_rec.py", line 117, in call
> self.predictor.run()
> OSError: In user code:
> 
> File "tools/export_model.py", line 75, in
> main()
> File "tools/export_model.py", line 70, in main
> paddle.jit.save(model, save_path)
> File "", line 2, in save
> 
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in **impl**
> return wrapped_func(*args, **kwargs)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in **impl**
> return func(*args, **kwargs)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
> concrete_program = static_func.concrete_program
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 461, in concrete_program
> concrete_program, _ = self.get_concrete_program(*input_spec)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
> concrete_program, partial_program_layer = self._program_cache[cache_key]
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 684, in **getitem**
> self._caches[item] = self._build_once(item)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 675, in _build_once
> class_instance=cache_key.class_instance)
> File "", line 2, in from_func_spec
> 
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in **impl**
> return wrapped_func(*args, **kwargs)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in **impl**
> return func(*args, **kwargs)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 625, in from_func_spec
> outputs = static_func(*inputs)
> File "/tmp/tmpqk3xmm2v.py", line 22, in forward
> false_fn_1, (x,), (x,), (x,))
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
> return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
> return true_fn(*true_args) if pred else false_fn(*false_args)
> File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/architectures/base_model.py", line 76, in forward
> x = self.neck(x)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in **call**
> outputs = self.forward(*inputs, **kwargs)
> File "/tmp/tmpmf6_4ac7.py", line 14, in forward
> (x,), (x,))
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
> return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
> return true_fn(*true_args) if pred else false_fn(*false_args)
> File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/necks/rnn.py", line 91, in forward
> x = self.encoder(x)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in **call**
> outputs = self.forward(*inputs, **kwargs)
> File "/paddle/code/gry/PaddleOCR_pub/ppocr/modeling/necks/rnn.py", line 45, in forward
> x, _ = self.lstm(x)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in **call**
> outputs = self.forward(*inputs, **kwargs)
> File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1035, in forward
> return self._cudnn_impl(inputs, initial_states, sequence_length)
> File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1012, in _cudnn_impl
> type="rnn", inputs=inputs, outputs=outputs, attrs=attrs)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layer_object_helper.py", line 52, in append_op
> stop_gradient=stop_gradient)
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2849, in append_op
> attrs=kwargs.get("attrs", None))
> File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1934, in **init**
> for frame in traceback.extract_stack():
> 
> ExternalError: Cudnn error, CUDNN_STATUS_INTERNAL_ERROR (at D:\v2.0.0\paddle\paddle\fluid\operators\rnn_op.cu.cc:420)
> [operator < rnn > error]

在 RTX2060 + win10 + paddle 2.0.2 + cuda10.0 + cuda7.6.5 上遇到同样的问题, 请问有解决方案么 ?
