### ISSUE TITLE
bug-打印空tensor报错

### ISSUE THREAD

**Issue by xmy0916** [PaddlePaddle/Paddle#32184]
```
import paddle
from paddle.fluid.layers import where
x = paddle.ones((10,10))
y = where(x==0)
print(y)
```
报错：
```
Traceback (most recent call last):
  File "/Users/xmy/Desktop/pycharm_project/PSENet/test.py", line 6, in <module>
    print(y)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 265, in __str__
    return to_string(self)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/tensor/to_string.py", line 214, in to_string
    max_width, signed = _get_max_width(_to_sumary(np_var))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/tensor/to_string.py", line 110, in _to_sumary
    return np.stack([_to_sumary(x) for x in var])
  File "<__array_function__ internals>", line 6, in stack
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
```

**Comment by joey12300** [comment]
> ```
> import paddle
> from paddle.fluid.layers import where
> x = paddle.ones((10,10))
> y = where(x==0)
> print(y)
> ```
> 
> 报错：
> 
> ```
> Traceback (most recent call last):
>   File "/Users/xmy/Desktop/pycharm_project/PSENet/test.py", line 6, in <module>
>     print(y)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 265, in __str__
>     return to_string(self)
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/tensor/to_string.py", line 214, in to_string
>     max_width, signed = _get_max_width(_to_sumary(np_var))
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/paddle/tensor/to_string.py", line 110, in _to_sumary
>     return np.stack([_to_sumary(x) for x in var])
>   File "<__array_function__ internals>", line 6, in stack
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/core/shape_base.py", line 423, in stack
>     raise ValueError('need at least one array to stack')
> ValueError: need at least one array to stack
> ```

您好，经测试确实存在无法打印空tensor的bug，感谢提供bug反馈 : )
