### ISSUE TITLE
Dropout 输入维度编号报错

### ISSUE THREAD

**Issue by JJYjackson** [PaddlePaddle/Paddle#32229]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

建立issue时，为快速解决问题，请您根据使用情况给出如下信息：
- 标题：简洁、精准描述您的问题，例如“ssd 模型前置lstm报错  ”
- 版本、环境信息：
   Paddle version: 2.0.1
Paddle With CUDA: True
OS: debian buster/sid
Python version: 3.7.10
CUDA version: 10.0.130
cuDNN version: 7.4.2
Nvidia driver version: 440.95.01

- 模型信息
    1）模型名称 ：cnn
![2021-04-13 12-48-23 的屏幕截图](https://user-images.githubusercontent.com/65533171/114498430-a720d780-9c56-11eb-960e-bfa55a90f0cb.png)

2）使用数据集名称
RADIOML 2016.04C      
  https://aistudio.baidu.com/aistudio/datasetdetail/80514
- 复现信息：如为报错，请给出复现环境、复现步骤
- 报错信息如下：
信噪比为: [-20, -18, -16, -14, -12, -10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
调制模式为: ['8PSK', 'AM-DSB', 'AM-SSB', 'BPSK', 'CPFSK', 'GFSK', 'PAM4', 'QAM16', 'QAM64', 'QPSK', 'WBFM']
(162060, 2, 128)
[('8PSK', -20), ('8PSK', -20), ('8PSK', -20), ('8PSK', -20), ('8PSK', -20)]
[-20 -20 -20 ... -10 -10 -10]
训练集的shape为：(113442, 2, 128, 1)
测试集的shape为：(48618, 2, 128, 1)
[6, 10, 9, 10, 0, 6, 4, 6, 5, 6] [4, 11, 14, 0, 10, 3, 4, 2, 2, 12]
[1, 2, 128]
6 () 113442
******************************************
[1, 2, 128]
0 48618
W0413 12:26:24.227283 10856 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.2, Runtime API Version: 10.0
W0413 12:26:24.230756 10856 device_context.cc:372] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "MR.py", line 157, in <module>
    model_CNN2.summary((None, 1, 2, 128))
  File "/home/titan-306/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1881, in summary
    return summary(self.network, _input_size, dtype)
  File "/home/titan-306/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/hapi/model_summary.py", line 149, in summary
    result, params_info = summary_string(net, _input_size, dtypes)
  File "<decorator-gen-218>", line 2, in summary_string
  File "/home/titan-306/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 315, in _decorate_function
    return func(*args, **kwargs)
  File "/home/titan-306/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/hapi/model_summary.py", line 276, in summary_string
    model(*x)
  File "/home/titan-306/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/titan-306/workspace/JJY/R2016C-MR_compare/cnn1_cnn2.py", line 30, in forward
    x = self.dropout(x)
  File "/home/titan-306/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/titan-306/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 727, in forward
    name=self.name)
  File "/home/titan-306/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 924, in dropout
    if seed is not None else 0, 'dropout_implementation', mode)
ValueError: (InvalidArgument) Input dimension number(num_col_dims) must be between 0 and 1, but received number is 1.
  [Hint: Expected (num_col_dims > 0 && num_col_dims < rank) == true, but received (num_col_dims > 0 && num_col_dims < rank):0 != true:1.] (at /paddle/paddle/fluid/framework/eigen.h:94)
  [operator < dropout > error]
![2021-04-13 12-53-20 的屏幕截图](https://user-images.githubusercontent.com/65533171/114498776-4940bf80-9c57-11eb-8f92-805765b7333f.png)
- 问题描述：MR.py中运行这几行代码时出现如上图所示的报错信息
![2021-04-13 12-55-26 的屏幕截图](https://user-images.githubusercontent.com/65533171/114498898-92910f00-9c57-11eb-8a2c-843ceddc8e6c.png)

**Comment by seiriosPlus** [comment]
我会在aistudio上验证后给您回复， 稍等.

**Comment by JJYjackson** [comment]
感谢感谢！










在 2021-04-15 22:02:33，"tangwei12" ***@***.***> 写道：

我会在aistudio上验证后给您回复， 稍等.

**Comment by JJYjackson** [comment]
> 我会在aistudio上验证后给您回复， 稍等.
您好，请问能分享下您在aisudio上的验证结果吗？因为我在aistudio上也是报同样的错

**Comment by seiriosPlus** [comment]
你好， 我暂时没复现此问题， 我正在切版本尝试.
