### ISSUE TITLE
飞腾麒麟V10 ImportError: skimage/restoration/_nl_means_denoising.cpython-37m-aarch64-linux-gnu.so: undefined symbol: fast_exp

### ISSUE THREAD

**Issue by yunchangxiaoguan** [PaddlePaddle/Paddle#32329]
python3 tools/infer/predict_system.py --image_dir="./doc/imgs/11.jpg" --det_model_dir="./inference/ch_ppocr_server_v1.1_det_infer/"  --rec_model_dir="./inference/ch_ppocr_server_v1.1_rec_infer_new/" --use_space_char=True
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/usr/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "tools/infer/predict_system.py", line 26, in <module>
    import tools.infer.predict_det as predict_det
  File "/root/PaddleOCR-develop/tools/infer/predict_det.py", line 35, in <module>
    from ppocr.data.det.db_process import DBProcessTest
  File "/root/PaddleOCR-develop/ppocr/data/det/db_process.py", line 23, in <module>
    from .data_augment import AugmentData
  File "/root/PaddleOCR-develop/ppocr/data/det/data_augment.py", line 13, in <module>
    import imgaug
  File "/usr/local/lib/python3.7/site-packages/imgaug/__init__.py", line 9, in <module>
    import imgaug.augmentables as augmentables
  File "/usr/local/lib/python3.7/site-packages/imgaug/augmentables/__init__.py", line 8, in <module>
    from imgaug.augmentables.segmaps import *
  File "/usr/local/lib/python3.7/site-packages/imgaug/augmentables/segmaps.py", line 12, in <module>
    from ..augmenters import blend as blendlib
  File "/usr/local/lib/python3.7/site-packages/imgaug/augmenters/__init__.py", line 21, in <module>
    from imgaug.augmenters.segmentation import *
  File "/usr/local/lib/python3.7/site-packages/imgaug/augmenters/segmentation.py", line 21, in <module>
    import skimage.segmentation
  File "/usr/local/lib64/python3.7/site-packages/skimage/segmentation/__init__.py", line 3, in <module>
    from .active_contour_model import active_contour
  File "/usr/local/lib64/python3.7/site-packages/skimage/segmentation/active_contour_model.py", line 4, in <module>
    from ..filters import sobel
  File "/usr/local/lib64/python3.7/site-packages/skimage/filters/__init__.py", line 4, in <module>
    from .edges import (sobel, sobel_h, sobel_v,
  File "/usr/local/lib64/python3.7/site-packages/skimage/filters/edges.py", line 18, in <module>
    from ..restoration.uft import laplacian
  File "/usr/local/lib64/python3.7/site-packages/skimage/restoration/__init__.py", line 10, in <module>
    from .non_local_means import denoise_nl_means
  File "/usr/local/lib64/python3.7/site-packages/skimage/restoration/non_local_means.py", line 4, in <module>
    from ._nl_means_denoising import (
ImportError: /usr/local/lib64/python3.7/site-packages/skimage/restoration/_nl_means_denoising.cpython-37m-aarch64-linux-gnu.so: undefined symbol: fast_exp

请问这个问题怎么解决，删了skimg重新装也没用

**Comment by jiweibo** [comment]
您好，目前国产化环境对Python的依赖包的安装不太友好，可以尝试源码安装的方式装skimg。

**Comment by yunchangxiaoguan** [comment]
> 您好，目前国产化环境对Python的依赖包的安装不太友好，可以尝试源码安装的方式装skimg。

好的谢谢，我把那个引用注释了就好了，没用到那块
