### ISSUE TITLE
反向传播出错

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#32331]
platform: AIStudio
version: 2.0.1
```
Traceback (most recent call last):
  File "train_v2.py", line 65, in <module>
    main()
  File "train_v2.py", line 59, in main
    loss.backward()
  File "</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-114>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 177, in backward
    self._run_backward(framework._dygraph_tracer(), retain_graph)
RuntimeError: (NotFound) Output(Scale@GRAD) and Output(Bias@GRAD) must be null or not be null at same time. But now, has Scale@Grad=[0], has Bias@GRAD=[1]
  [Hint: Expected (has_scale_grad == has_bias_grad) == true, but received (has_scale_grad == has_bias_grad):0 != true:1.] (at /paddle/paddle/fluid/operators/batch_norm_op.cc:477)
```

**Comment by hutuxian** [comment]
请确认一下网络中batch norm op里面的scale和bias是否同时存在或者同时不存在？

**Comment by GuoQuanhao** [comment]
已解决，问题在于复现代码时我设置了对weight不求梯度，只对bia求。这种操作目前paddle并不支持
