### ISSUE TITLE
使用 paddle2.0.2 trt 的推理功能预测通过 paddle1.8.5 训练模型报错

### ISSUE THREAD

**Issue by semal** [PaddlePaddle/Paddle#32333]
PaddlePaddle版本：paddlepaddle-gpu==2.0.2.post100 -f https://paddlepaddle.org.cn/whl/stable/tensorrt.html
GPU：GeForce RTX 2080ti cuda10.0 cudnn7.6
系统环境：centos7 Python3.6.0
预测库来源：https://paddlepaddle.org.cn/whl/stable/tensorrt.html
模型训练：paddlehub1.8.3 paddlepaddle-gpu==1.8.5.post107，利用 save_inference_model 接口输出的模型及参数文件到一个文件夹。
TensorRT: 版本为 6.0.1.5

## 代码
```
import numpy as np
import argparse
import cv2

from paddle.inference import Config
from paddle.inference import create_predictor
from paddle.inference import PrecisionType


# this is a simple resnet block for dynamic test.
def init_predictor(args):
    config = Config()
    config.enable_profile()
    config.set_model(args.model_dir)
    config.enable_memory_optim()
    config.enable_use_gpu(100, 0)
    # config.switch_specify_input_names(True)
    # config.switch_use_feed_fetch_ops(True)
    config.switch_ir_optim(True)
    # config.enable_tensorrt_oss()
    # using dynamic shape mode, the max_batch_size will be ignored.
    config.enable_tensorrt_engine(workspace_size=1 << 20,
                                  max_batch_size=5,
                                  min_subgraph_size=5,
                                  precision_mode=PrecisionType.Half,
                                  use_static=False,
                                  use_calib_mode=False)

    names = [
        "input_ids", "input_mask", "position_ids", "segment_ids", 'seq_len'
    ]
    min_input_shape = [1, 126, 1]
    max_input_shape = [10, 126, 1]
    opt_input_shape = [5, 126, 1]

    config.set_trt_dynamic_shape_info(
        {
            names[0]: min_input_shape,
            names[1]: min_input_shape,
            names[2]: min_input_shape,
            names[3]: min_input_shape,
            names[4]: [1, 1]
        }, {
            names[0]: max_input_shape,
            names[1]: max_input_shape,
            names[2]: max_input_shape,
            names[3]: max_input_shape,
            names[4]: [5, 1]
        }, {
            names[0]: opt_input_shape,
            names[1]: opt_input_shape,
            names[2]: opt_input_shape,
            names[3]: opt_input_shape,
            names[4]: [10, 1]
        })
    predictor = create_predictor(config)
    return predictor


def run(predictor, data):
    # copy data to input tensor
    input_names = [
        "input_ids", "input_mask", "position_ids", "segment_ids", 'seq_len'
    ]
    print('Got input names: %s' % str(input_names))
    for i, name in enumerate(input_names):
        input_tensor = predictor.get_input_handle(name)
        input_tensor.reshape(data[i].shape)
        input_tensor.copy_from_cpu(data[i].copy())
        print(input_tensor)

    # do the inference
    predictor.run()

    results = []
    # get out data from output tensor
    output_names = predictor.get_output_names()
    print('Got output names: %s' % str(output_names))
    for i, name in enumerate(output_names):
        output_tensor = predictor.get_output_handle(name)
        output_data = output_tensor.copy_to_cpu()
        results.append(output_data)

    return results


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model_file",
        type=str,
        default="",
        help="Model filename, Specify this when your model is a combined model."
    )
    parser.add_argument(
        "--params_file",
        type=str,
        default="",
        help=
        "Parameter filename, Specify this when your model is a combined model."
    )
    parser.add_argument(
        "--model_dir",
        type=str,
        default="",
        help=
        "Model dir, If you load a non-combined model, specify the directory of the model."
    )
    parser.add_argument("--use_gpu",
                        type=int,
                        default=0,
                        help="Whether use gpu.")
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()
    pred = init_predictor(args)
    in1 = np.ones((1, 126, 1)).astype(np.int64)
    in2 = np.ones((1, 126, 1)).astype(np.float32)
    in3 = np.ones((1, 126, 1)).astype(np.int64)
    in4 = np.ones((1, 126, 1)).astype(np.int64)
    in5 = np.array([126]).reshape([-1, 1]).astype(np.int64)
    result = run(pred, [in1, in2, in3, in4, in5])
    print(result)
```

## 报错信息
```
Traceback (most recent call last):
  File "test.py", line 118, in <module>
    pred = init_predictor(args)
  File "test.py", line 56, in init_predictor
    predictor = create_predictor(config)
SystemError: (Fatal) Build TensorRT cuda engine failed! Please recheck you configurations related to paddle-TensorRT.
  [Hint: infer_engine_ should not be null.] (at /paddle/paddle/fluid/inference/tensorrt/engine.cc:244)
```

**Comment by semal** [comment]
已解决，可以关闭..
