### ISSUE TITLE
OSError: 找不到指定的程序

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#32357]
运行错误：OSError: [WinError 127] 找不到指定的程序。: 'D:\\miniconda3\\envs\\paddle\\lib\\site-packages\\paddle\\fluid\\..\\libs'

- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle2.0.2cpu
    2）CPU：Xeon X5670
    4）系统环境：win2008 server、 Python3.8.5
1）pip安装/docker安装 miniconda4.9.2

Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\miniconda3\envs\paddle\lib\site-packages\paddle\__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "D:\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\__init__.py", line 35, in <module>
    from . import framework
  File "D:\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 36, in <module>
    from . import core
  File "D:\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\core.py", line 65, in <module>
    raise e
  File "D:\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\core.py", line 46, in <module>
    os.add_dll_directory(third_lib_path)
  File "D:\miniconda3\envs\paddle\lib\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)
OSError: [WinError 127] 找不到指定的程序。: 'D:\\miniconda3\\envs\\paddle\\lib\\site-packages\\paddle\\fluid\\..\\libs'

**Comment by ClassmateXiaoyu** [comment]
遇到同样的问题，请问这个问题解决了吗？

**Comment by Darki-luo** [comment]
> 遇到同样的问题，请问这个问题解决了吗？

没有

**Comment by zhwesky2010** [comment]
@Darki-luo @ClassmateXiaoyu 您好，目前没有复现这个问题，安装的miniconda：
```
conda create -n paddle_env python=3.8
conda install paddlepaddle --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
```
import paddle时显示是正常的

![infoflow 2021-08-06 18-50-21](https://user-images.githubusercontent.com/52485244/128499775-78484e0a-b8f3-4d92-9987-da628d427de9.png)
