### ISSUE TITLE
反向传播出错

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#32509]
platform: AIStudio
Version: 2.0.2
在程序中我是用`logits.backward(grad)`出错，其中`logits`的`stop_gradient=False`, `grad`的`stop_gradient=True`，即`logits`有梯度信息，`grad`没有，我想知道这个报错信息代表什么意思
```
W0424 14:49:52.979720  9582 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0424 14:49:52.984573  9582 device_context.cc:372] device: 0, cuDNN Version: 7.6.
softmax weight init successfully!
softmax weight mom init successfully!
Epoch 0: LambdaDecay set learning rate to 0.0125.
Epoch 0: LambdaDecay set learning rate to 0.0125.
2021-04-24 14:50:08,572 - INFO - Total Step is: 1455663
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:143: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py:89: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if isinstance(slot[0], (np.ndarray, np.bool, numbers.Number)):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:648: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
VarType.FP32
Traceback (most recent call last):
  File "train_single.py", line 100, in <module>
    main(args_)
  File "train_single.py", line 69, in main
    x_grad, loss_v = module_partial_fc.forward_backward(label, features, opt_pfc)
  File "/home/aistudio/partial_fc.py", line 148, in forward_backward
    logits.backward(grad)
  File "</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-114>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 177, in backward
    self._run_backward(framework._dygraph_tracer(), retain_graph)
TypeError: _run_backward(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core_avx.VarBase, arg0: paddle::imperative::Tracer, arg1: bool) -> None

Invoked with: Tensor(shape=[64, 85742], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[-30.68324471, -0.00000280 , -0.00000280 , ..., -0.00000280 , -0.00000280 , -0.00000280 ],
        [-30.68324471, -0.00000280 , -0.00000280 , ..., -0.00000280 , -0.00000280 , -0.00000280 ],
        [-30.68324471, -0.00000280 , -0.00000280 , ..., -0.00000280 , -0.00000280 , -0.00000280 ],
        ...,
        [-30.68324471, -0.00000280 , -0.00000280 , ..., -0.00000280 , -0.00000280 , -0.00000280 ],
        [-30.68324471, -0.00000280 , -0.00000280 , ..., -0.00000280 , -0.00000280 , -0.00000280 ],
        [-30.68324471, -0.00000280 , -0.00000280 , ..., -0.00000280 , -0.00000280 , -0.00000280 ]]), <paddle.fluid.dygraph.tracer.Tracer object at 0x7f1eb0d865f0>, Tensor(shape=[64, 85742], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [[-0.01562500,  0.00000018,  0.00000018, ...,  0.00000018,  0.00000018,  0.00000018],
        [-0.01562500,  0.00000018,  0.00000018, ...,  0.00000018,  0.00000018,  0.00000018],
        [-0.01562500,  0.00000018,  0.00000018, ...,  0.00000018,  0.00000018,  0.00000018],
        ...,
        [-0.01562500,  0.00000018,  0.00000018, ...,  0.00000018,  0.00000018,  0.00000018],
        [-0.01562500,  0.00000018,  0.00000018, ...,  0.00000018,  0.00000018,  0.00000018],
        [-0.01562500,  0.00000018,  0.00000018, ...,  0.00000018,  0.00000018,  0.00000018]])
terminate called without an active exception


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1619247010 (unix time) try "date -d @1619247010" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e80000256e) received by PID 9582 (TID 0x7f1dc4ffd700) from PID 9582 ***]

Aborted (core dumped)
```

**Comment by GuoQuanhao** [comment]
在torch中这样运行没有错误
```
A = torch.tensor([1.0, 2, 3], requires_grad=True)
with torch.no_grad():
    B = 2 * A
A.backward(B)
```
但在paddle中，我收到以下错误
```
A = paddle.to_tensor([1.0, 2, 3], stop_gradient=False)
with paddle.no_grad():
    B = 2 * A
A.backward(B)
```
```
---------------------------------------------------------------------------TypeError                                 Traceback (most recent call last)<ipython-input-33-f311e01ab013> in <module>
----> 1 A.backward(B)
</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-238> in backward(self, retain_graph)
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    223         assert in_dygraph_mode(
    224         ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
--> 225         return func(*args, **kwargs)
    226 
    227     return __impl__
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py in backward(self, retain_graph)
    175                                           retain_graph)
    176             else:
--> 177                 self._run_backward(framework._dygraph_tracer(), retain_graph)
    178         else:
    179             raise ValueError(
TypeError: _run_backward(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.core_avx.VarBase, arg0: paddle::imperative::Tracer, arg1: bool) -> None

Invoked with: Tensor(shape=[3], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [1., 2., 3.]), <paddle.fluid.dygraph.tracer.Tracer object at 0x7fb5451bd1d0>, Tensor(shape=[3], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [2., 4., 6.])
```
我想知道paddle如何实现torch这样的机制？这对我很重要

**Comment by GuoQuanhao** [comment]
已解决，利用multiply可以获得相同的结果
