### ISSUE TITLE
【aistudio】GPU环境下conda安装RDkit报错，CPU环境无报错

### ISSUE THREAD

**Issue by chfhf** [PaddlePaddle/Paddle#32733]
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/conda/gateways/connection/session.py", line 60, in __call__
        return cls._thread_local.session
    AttributeError: '_thread._local' object has no attribute 'session'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/opt/conda/lib/python3.6/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/conda/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/solve.py", line 1021, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/index.py", line 289, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 140, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
        yield fs.pop().result()
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 432, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 133, in <lambda>
        package_ref_or_match_spec))
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 145, in query
        self.load()
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 209, in load
        _internal_state = self._load()
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 375, in _load
        repodata_fn=self.repodata_fn)
      File "/opt/conda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 680, in fetch_repodata_remote_request
        session = CondaSession()
      File "/opt/conda/lib/python3.6/site-packages/conda/gateways/connection/session.py", line 62, in __call__
        session = cls._thread_local.session = super(CondaSessionType, cls).__call__()
      File "/opt/conda/lib/python3.6/site-packages/conda/gateways/connection/session.py", line 88, in __init__
        raise_on_status=False)
    TypeError: __init__() got an unexpected keyword argument 'raise_on_status'

`$ /opt/conda/bin/conda update conda`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/opt/conda
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64
                     PATH=/opt/conda/envs/python35-paddle120-env/bin:/opt/conda/envs/python27-pa
                          ddle120-env/bin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/b
                          in:/usr/local/sbin:/usr/sbin:/sbin:/home/aistudio/bin:/home/aistudio/.
                          local/bin:/usr/local/bin:/usr/bin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/aistudio/.condarc
 populated config files : /home/aistudio/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.6.8.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.23=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/aistudio/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/aistudio/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.22.0 CPython/3.6.8 Linux/4.4.0-150-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by juncaipeng** [comment]
我理解rdkit不是paddle提供的，估计是环境问题，建议联系aistudio （aistudio@baidu.com）。
