### ISSUE TITLE
多卡训练中随机出现疑似显存不足？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#32796]
- PaddlePaddle 2.0.2
 - Ubuntu 18.04
 - Python 3.7
 - CUDA 10.2

在训练过程中，已经训练了好几轮了，突然就出现这个。我的显存是11G，一开始我的显存只占用3.8G，很明显是够用的。不知道为啥这样。
```
[2021-05-07 23:20:27.405148] Train epoch 5, batch_id: 1900, loss: 0.610733
[2021-05-07 23:20:35.769312] Train epoch 5, batch_id: 2000, loss: 0.622740
[2021-05-07 23:20:44.189663] Train epoch 5, batch_id: 2100, loss: 0.574676
[2021-05-07 23:20:52.561204] Train epoch 5, batch_id: 2200, loss: 0.654894


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::_Sp_counted_ptr<paddle::imperative::VarBase*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
1   std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
2   paddle::framework::SignalHandle(char const*, int)
3   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1620400853 (unix time) try "date -d @1620400853" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e800007b77) received by PID 31620 (TID 0x7f631d3d2740) from PID 31607 ***]

Traceback (most recent call last):
  File "train.py", line 149, in <module>
    dist.spawn(train, args=(args,))
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 449, in spawn
    while not context.join():
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 255, in join
    self._throw_exception(error_index)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 263, in _throw_exception
    (error_index, name))
Exception: Process 1 terminated with signal SIGKILL.
```

**Comment by ForFishes** [comment]
您好，这个不一定是显存出现的问题，可以提供简单复现的代码吗？还有这个是动态图吗？以及单卡跑会有问题吗？

**Comment by yeyupiaoling** [comment]
@ForFishes 代码这这里：https://github.com/yeyupiaoling/PaddlePaddle-MobileFaceNets/blob/master/train.py
是动态图的。单卡好像也会出现问题。出现是时间是随机的，有时候训练到70多个epoch才出现

**Comment by ForFishes** [comment]
提供一下有数据的可复现的代码？这里看报错，不是显存的问题，可能是数据访问越界了。如果你尝试用fake数据训练呢，看看是否出现同样的问题。

**Comment by yeyupiaoling** [comment]
@ForFishes 数据访问越界？出现这种情况的原因是什么？为啥前面好几个epoch都没有问题？
项目文档中有提供数据集了：
https://github.com/yeyupiaoling/PaddlePaddle-MobileFaceNets

**Comment by ForFishes** [comment]
嗯嗯，好的。我这边复现一下，你这边可以先用fake的数据+ 单卡测试一下。这个报错信息非常少，难以判断问题。

**Comment by yeyupiaoling** [comment]
@ForFishes 我在AI Studio单卡好像没有问题，训练了一个晚上也没有出现这个问题。
