### ISSUE TITLE
dilation显存泄露

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#32898]
evaluate或训练时有显存泄露， 然后就OOM了, 定位到dilation=2时出现
AIstudio上， paddle 2.0

**Comment by LDOUBLEV** [comment]
提供下具体信息方便定位问题，
- 训练的什么算法，
- 项目链接
- 具体报错信息
- dilation=2的 上下文代码

**Comment by thunder95** [comment]
> 提供下具体信息方便定位问题，
> 
>     * 训练的什么算法，
> 
>     * 项目链接
> 
>     * 具体报错信息
> 
>     * dilation=2的 上下文代码

可能不是dilation的问题，我搭建了一个resnet50+dc5， evaluate的时候无论如何显存都会一直上涨，然后就OOM.
特别是make_layer那里是明显增长，稳步增长显存，每运行一个batch， 并没有把显存降下来
训练是显存占用时候也有3，4个G的波动
放在本地也是这样的。 代码如下， 请帮忙看看 @LDOUBLEV 


[resnet_bk.txt](https://github.com/PaddlePaddle/Paddle/files/6476502/resnet_bk.txt)

**Comment by LDOUBLEV** [comment]
make_layer这里在搭建网络，肯定会增加显存占用，eval的时候加上这个环境变量试试：export FLAGS_allocator_strategy='auto_growth'

训练没有显存溢出的话，eval一般也没问题，可以再检查下代码，或者贴一下具体报错信息？

**Comment by thunder95** [comment]
@LDOUBLEV 设置上面的环境变量没有任何帮助， 在torch上尝试同样的模型，显存非常稳定，而且占用显存远小于paddle， 应该是我哪里没弄对，琢磨了好久都没想明白，batch_size已经是最小的1了， 每次batch推理玩似乎显存没有回收，而且AIStudio是32G的显存。 错误信息如下：

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py:687: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:238: UserWarning: The dtype of left and right variables are not the same, left dtype is VarType.FP32, but right dtype is VarType.INT64, the right dtype will convert to VarType.FP32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
Traceback (most recent call last):
  File "train_val.py", line 127, in <module>
    evaluate() #只是验证
  File "train_val.py", line 111, in evaluate
    outputs = model(image)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/my_detr/model.py", line 185, in forward
    hs = self.transformer(self.input_proj(src), mask, self.query_embed.weight, pos[-1])[0]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/my_detr/transformer.py", line 73, in forward
    memory = self.encoder(src, src_mask=mask, pos=pos_embed) # [bs, h * w, c]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/my_detr/transformer.py", line 117, in forward
    output = layer(output, src_mask=src_mask, pos=pos)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/my_detr/transformer.py", line 237, in forward
    return self.forward_post(src, src_mask, pos)
  File "/home/aistudio/my_detr/transformer.py", line 213, in forward_post
    src2 = self.self_attn(q, k, src, src_mask)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/transformer.py", line 385, in forward
    mode="upscale_in_train")
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 924, in dropout
    if seed is not None else 0, 'dropout_implementation', mode)
SystemError: (Fatal) Operator dropout raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 488.281494MB memory on GPU 0, available memory is only 396.500000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:69)
. (at /paddle/paddle/fluid/imperative/tracer.cc:172)

**Comment by LDOUBLEV** [comment]
是否是你每次评估的时候重新定义模型了，评估的代码发一下？

**Comment by thunder95** [comment]
@LDOUBLEV 没有的哈，大概代码是这样的, 就是很普通的评估

```
@paddle.no_grad()
def evaluate():
    model.eval()
    coco_evaluator = CocoEvaluator(dataset_val.coco)
    for batch_id, (image, label)  in enumerate(val_loader()):
        outputs = model(image)
        orig_target_sizes = paddle.stack([t["orig_size"] for t in label], axis=0)
        results = postprocesser(outputs, orig_target_sizes)
        res = {target['im_id'].numpy()[0]: output for target, output in zip(label, results)}
        coco_evaluator.update(res)
    coco_evaluator.synchronize_between_processes()
    coco_evaluator.accumulate()
    return coco_evaluator.summarize() 
```

**Comment by LDOUBLEV** [comment]
你的项目方便公开不，没有你的环境不好确定问题，

你先把程序kill掉，让显存清空，不训练只评估也会显存不够用吗？

**Comment by thunder95** [comment]
重启项目之后莫名的变好了， 虽然显存仍然占用较大，但至少没报错了 @LDOUBLEV
