### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'

### ISSUE THREAD

**Issue by htw2012** [PaddlePaddle/Paddle#32925]
mac机器：
执行 python -c "import paddle; print(paddle.__version__)"
输出 2.0.0

执行
python infers/infer.py -c configs/blazeface_1000e.yml  -o weights=weights/blazeface_1000e.pdparams  --infer_img=test/16pic_8594349_b.jpg --save_txt=True

Traceback (most recent call last):
  File "infers/infer.py", line 29, in <module>
    from ppdet.core.workspace import load_config, merge_config
  File "/Users/towan/envs/py3/envs/py36/lib/python3.6/site-packages/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/Users/towan/envs/py3/envs/py36/lib/python3.6/site-packages/ppdet/data/__init__.py", line 17, in <module>
    from . import reader
  File "/Users/towan/envs/py3/envs/py36/lib/python3.6/site-packages/ppdet/data/reader.py", line 28, in <module>
    from paddle.fluid.dataloader.collate import default_collate_fn
ModuleNotFoundError: No module named 'paddle.fluid.dataloader.collate'

麻烦知道原因的帮忙看一下？

**Comment by wangxicoding** [comment]
看了下源码，需要升级一下Paddle，使用2.1版本的paddle，或者用最新的develop版本
