### ISSUE TITLE
算子split存在安全问题/bug

### ISSUE THREAD

**Issue by 360AIVul** [PaddlePaddle/Paddle#32942]
- 标题：算子split存在安全问题/bug
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.2
    2）CPU/GPU：CPU
    3）系统环境: ubuntu 20.04
    4）Python版本号: 3.8.5

```
import paddle.fluid as fluid
import paddle

x = fluid.layers.ones(shape=[1], dtype='int64')
y = paddle.rand(shape=[1, 1, 1, 1], dtype='float32', name = "LambdaX")

#for dim in range(-0x100, 0x100):
#    try:
#        ans = fluid.layers.split(x, num_or_sections = 1, dim = dim)
#        print(dim, ans)
#    except:
#        continue
```

问题一：可能存在double free or corruption (out)
fluid.layers.split(x, num_or_sections = 1, dim = -2)

```log
[Detaching after fork from child process 38626]
double free or corruption (out)

Thread 1 "python3" received signal SIGABRT, Aborted.
0x00007ffff7e1618b in raise () from /lib/x86_64-linux-gnu/libc.so.6
[ Legend: Modified register | Code | Heap | Stack | String ]
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── registers ────
$rax   : 0x0
$rbx   : 0x00007ffff7c04740  →  0x00007ffff7c04740  →  [loop detected]
$rcx   : 0x00007ffff7e1618b  →  <raise+203> mov rax, QWORD PTR [rsp+0x108]
$rdx   : 0x0
$rsp   : 0x00007fffffffc9e0  →  0x0000000000000000
$rbp   : 0x00007fffffffcd30  →  0x00007ffff7fbbb80  →  0x0000000000000001
$rsi   : 0x00007fffffffc9e0  →  0x0000000000000000
$rdi   : 0x2
$rip   : 0x00007ffff7e1618b  →  <raise+203> mov rax, QWORD PTR [rsp+0x108]
$r8    : 0x0
$r9    : 0x00007fffffffc9e0  →  0x0000000000000000
$r10   : 0x8
$r11   : 0x246
$r12   : 0x00007fffffffcc50  →  0x00007fffffffcc80  →  0x00007ffff7f8c670  →  "double free or corruption (out)"
$r13   : 0x10
$r14   : 0x00007ffff7ffb000  →  0x62756f6400001000
$r15   : 0x1
$eflags: [ZERO carry PARITY adjust sign trap INTERRUPT direction overflow resume virtualx86 identification]
$cs: 0x0033 $ss: 0x002b $ds: 0x0000 $es: 0x0000 $fs: 0x0000 $gs: 0x0000
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── stack ────
0x00007fffffffc9e0│+0x0000: 0x0000000000000000   ← $rsp, $rsi, $r9
0x00007fffffffc9e8│+0x0008: 0x00007ffea26527c0  →  "/root/Paddle/paddle/fluid/framework/operator.h"
0x00007fffffffc9f0│+0x0010: 0x00007ffea265400f  →  "GetAttr(name)"
0x00007fffffffc9f8│+0x0018: 0x00000000009a2508  →  0x00007fff00000004  →  0x0000000000000000
0x00007fffffffca00│+0x0020: 0x00000000009a24e0  →  0x00000000009a2400  →  0x00000000009a2470  →  0x0000000000000000
0x00007fffffffca08│+0x0028: 0x0000000000000000
0x00007fffffffca10│+0x0030: 0x0000000000000000
0x00007fffffffca18│+0x0038: 0x00000000009a2510  →  0x0000000000000000
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── code:x86:64 ────
   0x7ffff7e1617f <raise+191>      mov    edi, 0x2
   0x7ffff7e16184 <raise+196>      mov    eax, 0xe
   0x7ffff7e16189 <raise+201>      syscall
 → 0x7ffff7e1618b <raise+203>      mov    rax, QWORD PTR [rsp+0x108]
   0x7ffff7e16193 <raise+211>      xor    rax, QWORD PTR fs:0x28
   0x7ffff7e1619c <raise+220>      jne    0x7ffff7e161c4 <raise+260>
   0x7ffff7e1619e <raise+222>      mov    eax, r8d
   0x7ffff7e161a1 <raise+225>      add    rsp, 0x118
   0x7ffff7e161a8 <raise+232>      ret
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── threads ────
[#0] Id 1, Name: "python3", stopped 0x7ffff7e1618b in raise (), reason: SIGABRT
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── trace ────
[#0] 0x7ffff7e1618b → raise()
[#1] 0x7ffff7df5859 → abort()
[#2] 0x7ffff7e603ee → xchg ax, ax
[#3] 0x7ffff7e6847c → nop DWORD PTR [rax+0x0]
[#4] 0x7ffff7e6a120 → lea rdi, [rip+0x122569]        # 0x7ffff7f8c690
[#5] 0x7ffe9de754f6 → __gnu_cxx::new_allocator<paddle::framework::DDim>::deallocate(this=0x7fffffffcf20, __p=0x1ed95f0)
[#6] 0x7ffe9de6d8be → std::allocator_traits<std::allocator<paddle::framework::DDim> >::deallocate(__a=@0x7fffffffcf20, __p=0x1ed95f0, __n=0x1)
[#7] 0x7ffe9de65226 → std::_Vector_base<paddle::framework::DDim, std::allocator<paddle::framework::DDim> >::_M_deallocate(this=0x7fffffffcf20, __p=0x1ed95f0, __n=0x1)
[#8] 0x7ffe9de5dfdd → std::_Vector_base<paddle::framework::DDim, std::allocator<paddle::framework::DDim> >::~_Vector_base(this=0x7fffffffcf20, __in_chrg=<optimized out>)
[#9] 0x7ffe9de572e7 → std::vector<paddle::framework::DDim, std::allocator<paddle::framework::DDim> >::~vector(this=0x7fffffffcf20, __in_chrg=<optimized out>)
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Python Exception <class 'UnicodeEncodeError'> 'ascii' codec can't encode character '\u27a4' in position 12: ordinal not in range(128):
(gdb) bt
#0  0x00007ffff7e1618b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff7df5859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff7e603ee in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff7e6847c in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff7e6a120 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007ffe9de754f6 in __gnu_cxx::new_allocator<paddle::framework::DDim>::deallocate (this=0x7fffffffcf20, __p=0x1ed95f0) at /usr/include/c++/8/ext/new_allocator.h:125
#6  0x00007ffe9de6d8be in std::allocator_traits<std::allocator<paddle::framework::DDim> >::deallocate (__a=..., __p=0x1ed95f0, __n=0x1) at /usr/include/c++/8/bits/alloc_traits.h:462
#7  0x00007ffe9de65226 in std::_Vector_base<paddle::framework::DDim, std::allocator<paddle::framework::DDim> >::_M_deallocate (this=0x7fffffffcf20, __p=0x1ed95f0, __n=0x1) at /usr/include/c++/8/bits/stl_vector.h:304
#8  0x00007ffe9de5dfdd in std::_Vector_base<paddle::framework::DDim, std::allocator<paddle::framework::DDim> >::~_Vector_base (this=0x7fffffffcf20, __in_chrg=<optimized out>) at /usr/include/c++/8/bits/stl_vector.h:285
#9  0x00007ffe9de572e7 in std::vector<paddle::framework::DDim, std::allocator<paddle::framework::DDim> >::~vector (this=0x7fffffffcf20, __in_chrg=<optimized out>) at /usr/include/c++/8/bits/stl_vector.h:570
#10 0x00007ffe9eaec346 in paddle::operators::SplitOp::InferShape (this=0x1d91760, ctx=0x7fffffffd150) at /root/Paddle/paddle/fluid/operators/split_op.cc:63
#11 0x00007ffea2124140 in paddle::imperative::PreparedOpRunImpl<paddle::imperative::VarBase> (op=..., ctx=..., kernel_type=..., func=..., dev_ctx=0x1cb0180, ins=std::map with 1 element = {...}, outs=std::map with 1 element = {...}, attrs=std::unordered_map with 3 elements = {...}) at /root/Paddle/paddle/fluid/imperative/prepared_operator.cc:165
```

问题二：可能存在越界读
fluid.layers.split(x, num_or_sections = 1, dim = 0x1337)

```log
#0  0x00007ffe9dacb11a in paddle::framework::DDim::operator[] (this=0x7fffffffcda0, idx=0x1337) at /root/Paddle/paddle/fluid/framework/ddim.h:97
#1  0x00007ffe9eaea59d in paddle::operators::UpdateOutsDims (is_runtime=0x1, each_section_is_known=0x0, in_dims=..., num=0x1, sections=std::vector of length 0, capacity 0, axis=0x1337, outs_number=0x1) at /root/Paddle/paddle/fluid/operators/split_op.h:33
#2  0x00007ffe9eaec1b4 in paddle::operators::SplitOp::InferShape (this=0x1d917e0, ctx=0x7fffffffced0) at /root/Paddle/paddle/fluid/operators/split_op.cc:63
#3  0x00007ffea2124140 in paddle::imperative::PreparedOpRunImpl<paddle::imperative::VarBase> (op=..., ctx=..., kernel_type=..., func=..., dev_ctx=0x1cb0200, ins=std::map with 1 element = {...}, outs=std::map with 1 element = {...}, attrs=std::unordered_map with 3 elements = {...}) at /root/Paddle/paddle/fluid/imperative/prepared_operator.cc:165
```
获取[axis](https://github.com/PaddlePaddle/Paddle/blob/69d8027471f82d9f73234a7df9a9396dec982ad5/paddle/fluid/operators/split_op.cc#L35)数据后，进入UpdateOutsDims函数，https://github.com/PaddlePaddle/Paddle/blob/69d8027471f82d9f73234a7df9a9396dec982ad5/paddle/fluid/operators/split_op.h#L33 

```C
int64_t input_axis_dim = in_dims[axis];
```

对axis没有检测，直接越界读取数据

问题三：可能存在浮点数异常
paddle.split(x, num_or_sections = [True, True], axis = 2)
```
#0  0x00007ffea1a61510 in paddle::operators::math::SplitFunctor<paddle::platform::CPUDeviceContext, long>::operator() (this=0x7fffffffcf00, context=..., input=..., ref_inputs=std::vector of length 1, capacity 1 = {...}, axis=0x2, outputs=0x7fffffffce80) at /root/Paddle/paddle/fluid/operators/math/concat_and_split.cc:99
#1  0x00007ffe9eaf2a63 in paddle::operators::SplitOpKernel<paddle::platform::CPUDeviceContext, long>::Compute (this=0x7fffffffd040, ctx=...) at /root/Paddle/paddle/fluid/operators/split_op.h:159
#2  0x00007ffe9eaf177b in paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 2ul, paddle::operators::SplitOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::SplitOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::SplitOpKernel<paddle::platform::CPUDeviceContext, long>, paddle::operators::SplitOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::SplitOpKernel<paddle::platform::CPUDeviceContext, bool>, paddle::operators::SplitOpKernel<paddle::platform::CPUDeviceContext, paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}::operator()(paddle::framework::ExecutionContext const&) const (this=0x7fffffffd448, ctx=...) at /root/Paddle/paddle/fluid/framework/op_registry.h:166
```

```c
     94
     95      int input_cols = 0;
     96
     97      std::vector<int64_t> output_cols(outputs->size());
     98      for (size_t i = 0; i < num; ++i) {
               // t_cols=-0x61ab555d, input_rows=0x0
 →   99        int t_cols = ref_inputs[i]->numel() / input_rows;
    100        input_cols += t_cols;
    101        output_cols[i] = t_cols;
    102      }
    103      auto cpu_place = BOOST_GET_CONST(platform::CPUPlace, context.GetPlace());
    104
```

split 的dim/axis参数可以使用以上注释的循环代码测试

**Comment by vslyu** [comment]
收到，反馈的问题确实存在，已请op负责人帮忙跟进。
