### ISSUE TITLE
AI Studio在线部署预测

### ISSUE THREAD

**Issue by a794133319** [PaddlePaddle/Paddle#33115]
为使您的问题得到快速解决，在建立Issue前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准描述您的问题，例如“最新预测库的API文档在哪儿 ”
- 版本、环境信息：
    1）PaddlePaddle版本：1.8.4
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
    4）系统环境：Ai Studio Notebook任务

在线部署目标检测模型，使用Paddlex进行训练，然后导出部署模型，使用AIstudio 进行在线部署，然后预测的时候报错

![image](https://user-images.githubusercontent.com/55074811/119500312-3c58d500-bd9a-11eb-95da-ec0ced77b6fa.png)
![image](https://user-images.githubusercontent.com/55074811/119500331-41b61f80-bd9a-11eb-9f1c-60e31b581d89.png)
![image](https://user-images.githubusercontent.com/55074811/119500346-467ad380-bd9a-11eb-9d36-e1c682b105c1.png)
自定义参数器使用的是默认的目标检测示例代码：
```python

# -*- coding: utf-8 -*-
"""
Hook
"""
import os
import sys

sys.path.append("..")
from PIL import Image

import numpy as np
import paddle.fluid as fluid

from home.utility import base64_to_image


def reader_infer(data_args):
    """
    reader_inter
    示例为目标检测数据预处理
    :param data_args: 接口传入的数据，以k-v形式
    :return [[]], feeder
    """

    def reader():
        """
        reader
        :return:
        """
        image_shape = [3, 300, 300]
        image = fluid.layers.data(name='image', shape=image_shape, dtype='float32')
        feeder = fluid.DataFeeder(place=fluid.CPUPlace(), feed_list=[image])
        img = base64_to_image(data_args["image"])
        if img.mode == 'L':
            img = img.convert('RGB')
        img = img.resize((300, 300), Image.ANTIALIAS)
        im_width, im_height = img.size
        img = np.array(img)
        if len(img.shape) == 3:
            img = np.swapaxes(img, 1, 2)
            img = np.swapaxes(img, 1, 0)
        img = img[[2, 1, 0], :, :]
        img = img.astype('float32')
        img -= 127.5
        img = img * 0.007843
        return [[img]], feeder

    return reader



```

输出参数代码：
```python

# -*- coding: utf-8 -*-
"""
Hook
"""
def output(results, data_args):
    """
    示例为目标检测的输出hook
    将模型预测的结果，转换为直线坐标
    :param results 模型预测结果
    :param data_args: 接口传入的数据，以k-v形式
    :return array 需要能被json_encode的数据格式
    """
    im_height = 300
    im_width = 300
    lines = []
    for dt in results:
        category_id, score, xmin, ymin, xmax, ymax = dt.tolist()
        if score < 0.05:
            continue
        bbox = dt[2:]
        xmin, ymin, xmax, ymax = bbox
        (left, right, top, bottom) = (xmin * im_width, xmax * im_width,
                                      ymin * im_height, ymax * im_height)
        # lines.append({"left": left, "right": right, "top": top, "bottom": bottom})
        lines.append({"p1": [left, top], "p2": [left, bottom],
                      "p3": [right, bottom], "p4": [right, top]})
        # lines.append({"x1": left, "y1": top, "x2": right, "y2": bottom})
    return lines


```

![image](https://user-images.githubusercontent.com/55074811/119500715-b12c0f00-bd9a-11eb-9be5-9d3a3b2afc79.png)
请求日志：
```python

start deploy...
get file url from evn
http://bj.bcebos.com/v1/ai-studio-serving-build-online/6168/11319.zip?authorization=bce-auth-v1%2F0ef6765c1e494918bc0d4c3ca3e5c6d1%2F2021-05-25T12%3A36%3A34Z%2F-1%2F%2F90d009df915e907a31c6ba4d9c6cd8c1eb87bc6ce5cc3e09fb41f7e1887613ad
downloading...
extracting...
unzip is /usr/bin/unzip
unzip available
start server...
[2021-05-25 20:*:*,374.374] server_conf.py [line:*] INFO current config section cpu
/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py:*: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "app_server.py", line 162, in <module>
    from utils.consumer import InferConsumer
  File "/home/work/paddle-predictor/src/utils/consumer.py", line 6, in <module>
    import business_service
  File "/home/work/paddle-predictor/src/business_service.py", line 21, in <module>
    from infer_service import infer_with_executor_by_dict
  File "/home/work/paddle-predictor/src/infer_service.py", line 21, in <module>
    from predict.executor_manager import executor_manager
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 150, in <module>
    executor_manager = ExecutorManager()
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 51, in __init__
    self._load_model(model_dir[model_name], model_name)
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 135, in _load_model
    executor=exe)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 1328, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 849, in load_persistables
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 682, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 726, in load_vars
    executor.run(load_prog)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 822, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 899, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
8   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 711, in load_vars
    'file_path': os.path.join(load_dirname, new_var.name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 682, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 849, in load_persistables
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 1328, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 135, in _load_model
    executor=exe)
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 51, in __init__
    self._load_model(model_dir[model_name], model_name)
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 150, in <module>
    executor_manager = ExecutorManager()
  File "/home/work/paddle-predictor/src/infer_service.py", line 21, in <module>
    from predict.executor_manager import executor_manager
  File "/home/work/paddle-predictor/src/business_service.py", line 21, in <module>
    from infer_service import infer_with_executor_by_dict
  File "/home/work/paddle-predictor/src/utils/consumer.py", line 6, in <module>
    import business_service
  File "app_server.py", line 162, in <module>
    from utils.consumer import InferConsumer

----------------------
Error Message Summary:
----------------------
Error: Cannot open file /home/work/paddle-predictor/resources/model/yolo_block.1.1.0.bn.mean for load op at (/paddle/paddle/fluid/operators/load_op.h:*)
  [operator < load > error]
start success

```

**Comment by a794133319** [comment]
![image](https://user-images.githubusercontent.com/55074811/119500715-b12c0f00-bd9a-11eb-9be5-9d3a3b2afc79.png)
请求日志：
```python

start deploy...
get file url from evn
http://bj.bcebos.com/v1/ai-studio-serving-build-online/6168/11319.zip?authorization=bce-auth-v1%2F0ef6765c1e494918bc0d4c3ca3e5c6d1%2F2021-05-25T12%3A36%3A34Z%2F-1%2F%2F90d009df915e907a31c6ba4d9c6cd8c1eb87bc6ce5cc3e09fb41f7e1887613ad
downloading...
extracting...
unzip is /usr/bin/unzip
unzip available
start server...
[2021-05-25 20:*:*,374.374] server_conf.py [line:*] INFO current config section cpu
/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py:*: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "app_server.py", line 162, in <module>
    from utils.consumer import InferConsumer
  File "/home/work/paddle-predictor/src/utils/consumer.py", line 6, in <module>
    import business_service
  File "/home/work/paddle-predictor/src/business_service.py", line 21, in <module>
    from infer_service import infer_with_executor_by_dict
  File "/home/work/paddle-predictor/src/infer_service.py", line 21, in <module>
    from predict.executor_manager import executor_manager
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 150, in <module>
    executor_manager = ExecutorManager()
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 51, in __init__
    self._load_model(model_dir[model_name], model_name)
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 135, in _load_model
    executor=exe)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 1328, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 849, in load_persistables
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 682, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 726, in load_vars
    executor.run(load_prog)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 780, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 775, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 822, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 899, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
2   paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
3   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, signed char>, paddle::operators::LoadOpKernel<paddle::platform::CPUDeviceContext, long> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
7   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
8   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 2488, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 711, in load_vars
    'file_path': os.path.join(load_dirname, new_var.name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 682, in load_vars
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 849, in load_persistables
    filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 1328, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 135, in _load_model
    executor=exe)
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 51, in __init__
    self._load_model(model_dir[model_name], model_name)
  File "/home/work/paddle-predictor/src/predict/executor_manager.py", line 150, in <module>
    executor_manager = ExecutorManager()
  File "/home/work/paddle-predictor/src/infer_service.py", line 21, in <module>
    from predict.executor_manager import executor_manager
  File "/home/work/paddle-predictor/src/business_service.py", line 21, in <module>
    from infer_service import infer_with_executor_by_dict
  File "/home/work/paddle-predictor/src/utils/consumer.py", line 6, in <module>
    import business_service
  File "app_server.py", line 162, in <module>
    from utils.consumer import InferConsumer

----------------------
Error Message Summary:
----------------------
Error: Cannot open file /home/work/paddle-predictor/resources/model/yolo_block.1.1.0.bn.mean for load op at (/paddle/paddle/fluid/operators/load_op.h:*)
  [operator < load > error]
start success

```

**Comment by a794133319** [comment]
请求：
![Uploading image.png…]()

**Comment by a794133319** [comment]
![image](https://user-images.githubusercontent.com/55074811/119501763-c05f8c80-bd9b-11eb-95d3-5f654317a1e0.png)
请求

**Comment by qili93** [comment]
`self._load_model(model_dir[model_name], model_name)`这里load_model的API使用不对，你的模型输出是压缩模型，就是参数是存在`__params__`里面的，需要参考这里combined模型的加载方式来加载，你当前代码是“非combine”模型的加载方式
https://paddle-inference.readthedocs.io/en/latest/api_reference/python_api_doc/Config/ModelConfig.html#id2

**Comment by a794133319** [comment]
> `self._load_model(model_dir[model_name], model_name)`这里load_model的API使用不对，你的模型输出是压缩模型，就是参数是存在`__params__`里面的，需要参考这里combined模型的加载方式来加载，你当前代码是“非combine”模型的加载方式
> https://paddle-inference.readthedocs.io/en/latest/api_reference/python_api_doc/Config/ModelConfig.html#id2

AI studio在线部署的话，那在哪里改为 combined模型的加载方式来加载 啊？这里不是只有参数的输入输出的代码可以更改吗？

**Comment by qili93** [comment]
这里的代码`self._load_model(model_dir[model_name], model_name)`是AIStudio自动生成的，不是你自己写的对不？这个需要咨询一下AIStudio负责些自动化模型部署脚本的同学，看看他们那边有没有提供"combined模型"的部署选项和相应的脚本。

**Comment by a794133319** [comment]
> 这里的代码`self._load_model(model_dir[model_name], model_name)`是AIStudio自动生成的，不是你自己写的对不？这个需要咨询一下AIStudio负责些自动化模型部署脚本的同学，看看他们那边有没有提供"combined模型"的部署选项和相应的脚本。
好的谢谢
