### ISSUE TITLE
SystemError: (Fatal) Operator equal raises an thrust::system::system_error exception. The exception content is :parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument. (at /paddle/paddle/fluid/imperative/tracer.cc:192)

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/Paddle#33111]
aistudio@jupyter-325350-1988508:~$ python summary_env.py
****************************************
Paddle version: 2.1.0
Paddle With CUDA: True
OS: Ubuntu 16.04
Python version: 3.7.4
CUDA version: 10.1.243
cuDNN version: 7.3.1
Nvidia driver version: 418.67
****************************************
aistudio 环境 用paddleDetection套件：
backbone是swinTransform模型

*************************************************
[05/25 18:39:40] ppdet.engine INFO: Epoch: [0] [     0/117266] learning_rate: 0.000010 loss_rpn_cls: 0.655590 loss_rpn_reg: 0.018746 loss_bbox_cls_stage0: 1.439264 loss_bbox_reg_stage0: 0.000121 loss_bbox_cls_stage1: 1.405969 loss_bbox_reg_stage1: 0.000326 loss_bbox_cls_stage2: 1.497029 loss_bbox_reg_stage2: 0.000547 loss_mask: 1.044970 loss: 6.062562 eta: 18 days, 14:04:52 batch_cost: 1.1412 data_cost: 0.0007 ips: 0.8763 images/s
[05/25 18:40:00] ppdet.engine INFO: Epoch: [0] [    20/117266] learning_rate: 0.000210 loss_rpn_cls: 0.534252 loss_rpn_reg: 0.055952 loss_bbox_cls_stage0: 1.198074 loss_bbox_reg_stage0: 0.012510 loss_bbox_cls_stage1: 1.130215 loss_bbox_reg_stage1: 0.011061 loss_bbox_cls_stage2: 1.186514 loss_bbox_reg_stage2: 0.001061 loss_mask: 1.193377 loss: 5.443953 eta: 16 days, 18:17:16 batch_cost: 1.0236 data_cost: 0.0012 ips: 0.9770 images/s
[05/25 18:40:22] ppdet.engine INFO: Epoch: [0] [    40/117266] learning_rate: 0.000410 loss_rpn_cls: 0.254133 loss_rpn_reg: 0.116567 loss_bbox_cls_stage0: 0.219815 loss_bbox_reg_stage0: 0.058110 loss_bbox_cls_stage1: 0.190359 loss_bbox_reg_stage1: 0.027457 loss_bbox_cls_stage2: 0.170063 loss_bbox_reg_stage2: 0.010385 loss_mask: 1.218292 loss: 2.421215 eta: 17 days, 9:10:04 batch_cost: 1.1073 data_cost: 0.0011 ips: 0.9031 images/s
[05/25 18:40:45] ppdet.engine INFO: Epoch: [0] [    60/117266] learning_rate: 0.000609 loss_rpn_cls: 0.309539 loss_rpn_reg: 0.109913 loss_bbox_cls_stage0: 0.090543 loss_bbox_reg_stage0: 0.024873 loss_bbox_cls_stage1: 0.063418 loss_bbox_reg_stage1: 0.011244 loss_bbox_cls_stage2: 0.039009 loss_bbox_reg_stage2: 0.005669 loss_mask: 0.918403 loss: 1.712931 eta: 17 days, 15:05:34 batch_cost: 1.1135 data_cost: 0.0016 ips: 0.8980 images/s
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/data/PaddleDetection/ppdet/engine/trainer.py", line 307, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/data/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 27, in forward
    out = self.get_loss()
  File "/home/aistudio/data/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 125, in get_loss
    rpn_loss, bbox_loss, mask_loss = self._forward()
  File "/home/aistudio/data/PaddleDetection/ppdet/modeling/architectures/cascade_rcnn.py", line 87, in _forward
    body_feats = self.backbone(self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/data/PaddleDetection/ppdet/modeling/backbones/swin.py", line 666, in forward
    x_out, H, W, x, Wh, Ww = layer(x, Wh, Ww)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/data/PaddleDetection/ppdet/modeling/backbones/swin.py", line 466, in forward
    x = blk(x, attn_mask)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/data/PaddleDetection/ppdet/modeling/backbones/swin.py", line 335, in forward
    x = shortcut + self.drop_path(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/data/PaddleDetection/ppdet/modeling/backbones/swin.py", line 46, in forward
    return drop_path(x, self.drop_prob, self.training)
  File "/home/aistudio/data/PaddleDetection/ppdet/modeling/backbones/swin.py", line 28, in drop_path
    if drop_prob == 0. or not training:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 250, in __impl__
    return math_op(self, other_var, 'axis', axis)
SystemError: (Fatal) Operator equal raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument. (at /paddle/paddle/fluid/imperative/tracer.cc:192)
****************************************************************************************
看起来是drop_path那里出现问题

**Comment by qili93** [comment]
这个问题为已知问题，目前正在修复中，具体见 PaddlePaddle/PaddleClas#685 已有icafe卡片跟进这个问题，需要等待修复。
