### ISSUE TITLE
Accuracy issue of fc_lstm_fuse_pass under cpu

### ISSUE THREAD

**Issue by jakpiase** [PaddlePaddle/Paddle#33168]
Hi,

I have been informed that our oneDNN LSTM kernel is not being used in ch_ppocr_mobile_v1.1_rec inference model. After investigation I have found that fc_lstm_fuse_pass was temporarily disabled in https://github.com/PaddlePaddle/Paddle/pull/27377) So I have a question, when can we expect that pass to be enabled?

Best Regards,
Jakub

**Comment by jiweibo** [comment]
hi, fc_lstm_fuse_pass has accuracy problems under cpu. If the calculation result of fusion_lstm under oneDNNL is correct, you can add fc_lstm_fuse_pass to the pass opened by mkldnn
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/paddle_pass_builder.cc#L221

I will try to fix the accuracy of fusion_lstm under cpu, but it may take some time

**Comment by juncaipeng** [comment]
@jakpiase  @lidanqing-intel  

We find the next unit test will fail when the fc_lstm_fuse_pass is enabled. So, once the problem of unit test is fixed, we can enbale the pass.

![image](https://user-images.githubusercontent.com/52520497/120286148-8721a200-c2f0-11eb-86ac-c0494464a971.png)

**Comment by Aganlengzi** [comment]
@baoachun

**Comment by yaomichael** [comment]
@lidanqing-intel is looking into this.

**Comment by lidanqing-vv** [comment]
@yaomichael  I try to reproduce the accuracy issue in UT but I can't. Unit test passed after I enable fc_lstm_fuse_pass in both paddle_pass_builder.cc and test_fc_lstm_fuse_pass.py. It looks no issue or Baidu may comment more.

- What I changed
```
+++ b/paddle/fluid/inference/api/paddle_pass_builder.cc
@@ -248,7 +248,7 @@ CpuPassStrategy::CpuPassStrategy() : PassStrategy({}) {
                   "seqpool_cvm_concat_fuse_pass",  //
                   // "embedding_fc_lstm_fuse_pass", //
                   // TODO(wilber): fix correctness problem.
-                  // "fc_lstm_fuse_pass",                    //
+                  "fc_lstm_fuse_pass",                    //
                   "mul_lstm_fuse_pass",                      //
                   "fc_gru_fuse_pass",                        //
                   "mul_gru_fuse_pass",                       //
```
```
+++ b/python/paddle/fluid/tests/unittests/ir/inference/test_fc_lstm_fuse_pass.py
@@ -45,7 +45,8 @@ class MulLstmFusePassTest(InferencePassTest):
     def test_check_output(self):
         use_gpu = False
         self.check_output_with_option(use_gpu)
-        self.assertTrue(PassVersionChecker.IsCompatible('mul_lstm_fuse_pass'))
+        print("WARNING! This is to check the output")
+        self.assertTrue(PassVersionChecker.IsCompatible('fc_lstm_fuse_pass'))
```
- The unit test results I received
```
W0530 03:26:34.026981 47967 analysis_predictor.cc:1725] Deprecated. Please use CreatePredictor instead.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
I0530 03:26:34.030793 47967 fuse_pass_base.cc:57] ---  detected 1 subgraphs
--- Running IR pass [fc_gru_fuse_pass]
---    fused 0 pairs of fc gru patterns
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [matmul_v2_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
--- Running IR pass [matmul_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I0530 03:26:34.032506 47967 analysis_predictor.cc:1024] ======= optimize end =======
I0530 03:26:34.032532 47967 naive_executor.cc:102] ---  skip [feed], feed -> data
I0530 03:26:34.032588 47967 naive_executor.cc:102] ---  skip [lstm_0.tmp_0], fetch -> fetch
I0530 03:26:34.032590 47967 naive_executor.cc:102] ---  skip [lstm_0.tmp_1], fetch -> fetch
WARNING! This is to check the output
.
----------------------------------------------------------------------
Ran 1 test in 0.183s
```

**Comment by lidanqing-vv** [comment]
PR enabling the fc_lstm_fuse_pass and the UT https://github.com/PaddlePaddle/Paddle/pull/43430

**Comment by yaomichael** [comment]
@jakpiase can you close this ticket?
@jiangjiajun @lidanqing-intel

**Comment by lidanqing-vv** [comment]
Releate to #44416. 
Hi, @jakpiase Enabling fc_lstm_fuse_pass cause accuracy test failure. So I suggest closing this issue for now
And ch_ppocr_mobile_v1.1_rec is not high priority model. What do you think?

**Comment by jakpiase** [comment]
@lidanqing-intel you are right, it is really low priority for now, I'll close that issue

**Comment by lidanqing-vv** [comment]
Enabling fc_lstm_fuse_pass with #44416 cause other models failure. I think for now let's not enable it. Only when high priority model need this pass, we can enable it.
```
[1m[35m--- Running analysis [ir_graph_to_program_pass][0m
I0718 11:47:54.931946 43288 analysis_predictor.cc:1266] ======= optimize end =======
I0718 11:47:54.939473 43288 onednn_context.cc:79] oneDNN v2.6.0
W0718 11:47:55.049451 43288 operator.cc:283] top_k raises an exception dnnl::error, could not create a primitive descriptor for a reorder primitive
/usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "model_test.py", line 164, in <module>
    test_lstm_model()
  File "model_test.py", line 153, in test_lstm_model
    (hx_acc, ctc_acc, fps) = run_program(model_path, data_path)
  File "model_test.py", line 116, in run_program
    hz_out, ctc_out = predictor.run([inputs[i]])
RuntimeError: could not create a primitive descriptor for a reorder primitive
```

```
          APPLICATION: TEST_LSTM_MODEL                                                            
| PASSED  | test_lstm_fp32_inference                      | batch: 1    | HX_ACC: 93.31%            |
| FAILED  | test_lstm_ptq_int8_inference                  | batch: 1    | Pattern not found.        |
+---------------------------------------------------------------------------------------------------+
          APPLICATION: TEST_LSTM_QAT_MODEL                                                        
| FAILED  | test_lstm_qat_int8_inference                  | batch: 1    | Pattern not found.        |
+---------------------------------------------------------------------------------------------------+
+=========+===============================================+=============+===========================+
```
