### ISSUE TITLE
MKLDNN error for blazeface model

### ISSUE THREAD

**Issue by juncaipeng** [PaddlePaddle/Paddle#33282]
Install PaddlePaddle 2.1

Install PaddleDetection 2.1
```
git clone https://github.com/PaddlePaddle/PaddleDetection.git
cd PaddleDetection
git checkout -b release/2.1 origin/release/2.1
python setup.py install
python -m pip install -r requirments.txt
```

Download and unzip the blazeface model(Link:https://dubox.com/s/15iC3J0dXT3H5mfImnQt57g Password:k2a2) .

```
cd PaddleDetection
# Disable MKLDNN,  the test is ok.
python deploy/python/infer.py --model_dir models_fp32/blazeface_ori --image_file ./demo/road554.png --use_gpu False --enable_mkldnn False

# Enable MKLDNN, the test raises error 
python deploy/python/infer.py --model_dir models_fp32/blazeface_ori --image_file ./demo/road554.png --use_gpu False --enable_mkldnn True 
```

```
I0602 06:18:09.606899 26233 analysis_config.cc:424] use_dlnne_:0
I0602 06:18:09.606976 26233 analysis_config.cc:424] use_dlnne_:0
I0602 06:18:09.607010 26233 analysis_config.cc:424] use_dlnne_:0
I0602 06:18:09.607040 26233 analysis_config.cc:424] use_dlnne_:0
I0602 06:18:09.607089 26233 analysis_config.cc:424] use_dlnne_:0
I0602 06:18:09.607120 26233 analysis_config.cc:424] use_dlnne_:0
---    Fused 0 subgraphs into layer_norm op.
---    fused 0 scale with matmul
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with transpose's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape
---    Fused 0 ReshapeTransposeMatmulMkldnn patterns with reshape's xshape with transpose's xshape
---    Fused 0 MatmulTransposeReshape patterns
---    fused 0 batch norm with relu activation
Traceback (most recent call last):
  File "deploy/python/infer.py", line 641, in <module>
    main()
  File "deploy/python/infer.py", line 608, in main
    predict_image(detector, img_list, FLAGS.batch_size)
  File "deploy/python/infer.py", line 520, in predict_image
    results = detector.predict(batch_image_list, FLAGS.threshold)
  File "deploy/python/infer.py", line 160, in predict
    self.predictor.run()
RuntimeError: could not create a descriptor for a binary operation primitive
```

**Hope to fix the problem in Paddle 2.1.1**

**Comment by lidanqing-vv** [comment]
@juncaipeng  I reproduced and it looks the graph has some problem, there is one elementwise_add, one of its input is one dimension array and another input of this elementwise_add is two dimension array.

**Comment by lidanqing-vv** [comment]
broadcast X(1 dimension ) Y(2 dimensions) mkldnn version will be supported before 16th June.

**Comment by lidanqing-vv** [comment]
Hi, @juncaipeng  @jczaja 

Jacek's PR #33549 fixed the issue. I tested **newest develop(b1355444a91747a27cb10f2d0087d7fd5e704d55) + this PR** on my i9 machine results are as follows:

mkldnn False
```
li@c3gpo:~/repo/PaddleDetection$ python deploy/python/infer.py --model_dir /home/li/issue_33282/blaz
eface_ori --image_file ./demo/road554.png --use_gpu False --enable_mkldnn False

save result to: output/road554.png
------------------ Inference Time Info ----------------------
total_time(ms): 183.60000000000002, img_num: 1
average latency time(ms): 183.60, QPS: 5.446623
preprocess_time(ms): 15.30, inference_time(ms): 168.30, postprocess_time(ms): 0.00
```

mkldnn True
```
li@c3gpo:~/repo/PaddleDetection$ python deploy/python/infer.py --model_dir /home/li/issue_33282/blaz
eface_ori --image_file ./demo/road554.png --use_gpu False --enable_mkldnn True

save result to: output/road554.png
------------------ Inference Time Info ----------------------
total_time(ms): 93.5, img_num: 1
average latency time(ms): 93.50, QPS: 10.695187
preprocess_time(ms): 8.60, inference_time(ms): 84.90, postprocess_time(ms): 0.0
```

@juncaipeng  Maybe you could ask Baidu QA to verify it?

**Comment by lidanqing-vv** [comment]
@juncaipeng @OliverLPH  Could you please verify if this error is solved and I will close this issue.

**Comment by OliverLPH** [comment]
@lidanqing-intel @jczaja 
thanks for your effort~
we have verified this issue has been solved by https://github.com/PaddlePaddle/Paddle/pull/33845, and won't cause this error https://github.com/PaddlePaddle/Paddle/issues/33918. 
@juncaipeng please help merge https://github.com/PaddlePaddle/Paddle/pull/33845 into release/2.1

**Comment by kkHAIKE** [comment]
this commit make this again... https://github.com/PaddlePaddle/Paddle/issues/29506
