### ISSUE TITLE
训练的过程中突然出现PermissionDenied

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#33403]
- PaddlePaddle 2.1.0
 - Ubuntu 18.04

在训练的过程中，突然出现下面错误，前面已经训练几千个batch了。
```
Traceback (most recent call last):
  File "train.py", line 213, in <module>
    train(args)
  File "train.py", line 167, in train
    out, out_lens = model(inputs, input_lens)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/psdz/yeyupiaoling/PPASR/model_utils/deepspeech2.py", line 50, in forward
    x, x_lens = self.conv(x, audio_len)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/tmp/tmp9zjbiiht.py", line 8, in forward
    x, x_len = paddle.jit.dy2static.convert_call(self.conv_in)(x, x_len)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/tmp/tmpk01sm8xk.py", line 12, in forward
    x = paddle.jit.dy2static.convert_call(self.mask)(x, x_len)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/tmp/tmpewer9tzr.py", line 28, in forward
    for_loop_condition_1, for_loop_body_1, [x, i, masks, lengths])
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 42, in convert_while_loop
    loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 52, in _run_paddle_while_loop
    loop_vars = control_flow.while_loop(cond, body, loop_vars)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/layers/control_flow.py", line 1207, in while_loop
    map_structure(assign_skip_lod_tensor_array, output_vars, loop_vars)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/layers/utils.py", line 195, in map_structure
    return pack_sequence_as(structure[0], [func(*x) for x in entries])
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/layers/utils.py", line 195, in <listcomp>
    return pack_sequence_as(structure[0], [func(*x) for x in entries])
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/layers/control_flow.py", line 1112, in assign_skip_lod_tensor_array
    assign(input, output)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/layers/tensor.py", line 592, in assign
    type='assign', inputs={'X': [input]}, outputs={'Out': [output]})
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3223, in append_op
    kwargs.get("stop_gradient", False))
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
RuntimeError: (PermissionDenied) Cannot set gradient op twice unless using Inplace Strategy.
  [Hint: Expected shared_node == nullptr, but received shared_node != nullptr.] (at /paddle/paddle/fluid/imperative/variable_wrapper.h:282)
  [operator < assign > error]
```

唯一提示的就只有这个代码，没有提升哪一行。
https://github.com/yeyupiaoling/PPASR/blob/%E8%BF%9B%E9%98%B6%E7%BA%A7/model_utils/conv.py

**Comment by yeyupiaoling** [comment]
刚才调试了一下，主要是出现在保存模型之后出现的问题，如果不保存静态模型，就不会出现上面的错误，这种情况怎么解决？

```
    infer_model_path = os.path.join(args.save_model, 'infer')
    if not os.path.exists(infer_model_path):
        os.makedirs(infer_model_path)
    paddle.jit.save(layer=model,
                    path=os.path.join(infer_model_path, 'model'),
                    input_spec=[InputSpec(shape=(-1, feature_dim, -1), dtype=paddle.float32),
                                InputSpec(shape=(-1, ), dtype=paddle.int64)])
```

**Comment by zhhsplendid** [comment]
暂时没看出什么错，但是从报错信息上：
RuntimeError: (PermissionDenied) Cannot set gradient op twice unless using Inplace Strategy.
gradient op是反向时进行梯度计算的op，这里报错貌似是说不能计算反向两次。请检查一下是否有什么地方进行了两次反向梯度计算？

**Comment by yeyupiaoling** [comment]
@zhhsplendid 这些代码都是很常规的做法：https://github.com/yeyupiaoling/PPASR/blob/%E8%BF%9B%E9%98%B6%E7%BA%A7/model_utils/conv.py

没有没有什么特别的。

**Comment by zhhsplendid** [comment]
上面是模型代码，怎么训练，怎么存储的代码能发给我看看吗？

**Comment by yeyupiaoling** [comment]
https://github.com/yeyupiaoling/PPASR/blob/%E8%BF%9B%E9%98%B6%E7%BA%A7/train.py

**Comment by zhhsplendid** [comment]
说实话，这个报错我也不知道是什么错。但是python报错栈我大概知道是哪。我不是十分确定原因，你可以看看这里：

https://github.com/yeyupiaoling/PPASR/blob/bd79cf9bbfe5b2a48e9581612e7b1b7fc88dfc3e/model_utils/conv.py#L18
```
masks = paddle.full(shape=(x.shape[0], x.shape[-1]), fill_value=0, dtype=x.dtype)  # [B, T] 
for i in range(x.shape[0]):            
           length = lengths[i]            
           masks[i, :length] = 1        
masks = masks.unsqueeze(1).unsqueeze(1)  # [B, 1, 1, T]
```
我不确定是否是这里循环控制流里加`masks[i, :length] = 1`这种索引方式paddle还支持得不是很好。请问x.shape[0]是相对固定的数吗，或者可否从MaskConv的forward传进去？可否试试`for i in range(某个数)`，因为`for i in range(x.shape[0])`会被动态图转静态图转化为paddle控制流接口。不在控制流里的`masks[i, :length] = 1`索引方式可能可以。你可以试一下是不是这个原因。

**Comment by yeyupiaoling** [comment]
@zhhsplendid  x.shape[0]就是batch size，我试着改一下。

**Comment by yeyupiaoling** [comment]
@zhhsplendid 我想不出还有什么方法改适合PaddlePaddle了，您能指点一下吗？
其功能是按照`length`指定的长度，把`masks`每一行都填1，
