### ISSUE TITLE
paddle.vision.models.resnet34()出错

### ISSUE THREAD

**Issue by yangkerrr** [PaddlePaddle/Paddle#33458]
1）PaddlePaddle2.1
2）AiStudio运行环境
训练时使用resnet预训练模型突然出错，运行文档中代码中也出现了一样的错误，错误信息如下：

>>> import paddle
>>> from paddle.vision.models import resnet34
>>> model = resnet34()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/models/resnet.py", line 309, in resnet34
    return _resnet('resnet34', BasicBlock, 34, pretrained, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/models/resnet.py", line 259, in _resnet
    model = ResNet(Block, depth, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/models/resnet.py", line 197, in __init__
    bias_attr=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 646, in __init__
    data_format=data_format)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 412, in create_parameter
    default_initializer)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 374, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3193, in create_parameter
    initializer(param, self)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 364, in __call__
    stop_gradient=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3223, in append_op
    kwargs.get("stop_gradient", False))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError:   [operator < gaussian_random > error]

**Comment by sandyhouse** [comment]
请描述具体的环境信息，我本地无法复现上述错误。

**Comment by yangkerrr** [comment]
> 请描述具体的环境信息，我本地无法复现上述错误。

重启项目两次之后又可以正常运行了，很奇怪的错误。。。
