### ISSUE TITLE
使用paddleocr基于自己的数据集训练识别模型 模型使用的是MobileNetV3_large_x0_5_pretrained 但是在训练到159次中止训练

### ISSUE THREAD

**Issue by QIANXUNZDL123** [PaddlePaddle/Paddle#33493]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle-GPU 2.1.0.post
    2）CPU：
    3）GPU：Tesla V100  CUDA:11.2   CuDNN8.1
    4）系统环境：python:3.8   CentOS Linux release 7.9.2009 (Core)
- 训练信息
    1）单机，单卡
    2）16G
    3）Operator信息
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
训练指令：nohup python tools/train.py -c configs/det/det_mv3_db_zdl.yml &

错误信息：
[2021/06/10 12:46:54] root INFO: epoch: [159/1200], iter: 7590, lr: 0.001000, loss: 0.997759, loss_shrink_maps: 0.558870, loss_threshold_maps: 0.356539, loss_binary_maps: 0.111850, reader_cost: 0.31695 s, batch_cost: 0.43888 s, samples: 28, ips: 6.37992
[2021/06/10 12:46:59] root INFO: epoch: [159/1200], iter: 7600, lr: 0.001000, loss: 1.031973, loss_shrink_maps: 0.560523, loss_threshold_maps: 0.352846, loss_binary_maps: 0.112455, reader_cost: 0.34167 s, batch_cost: 0.48562 s, samples: 40, ips: 8.23681

eval model::   0%|          | 0/11 [00:00<?, ?it/s]Traceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 100, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "/home/zhangdaoliang/PaddleOCR/tools/program.py", line 262, in train
    cur_metric = eval(
  File "/home/zhangdaoliang/PaddleOCR/tools/program.py", line 338, in eval
    for idx, batch in enumerate(valid_dataloader):
  File "/home/zhangdaoliang/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/reader.py", line 426, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/zhangdaoliang/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
    self._init_workers()
  File "/home/zhangdaoliang/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 327, in _init_workers
    worker.start()
  File "/home/zhangdaoliang/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/zhangdaoliang/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/zhangdaoliang/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/zhangdaoliang/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/zhangdaoliang/anaconda3/envs/paddle_env/lib/python3.8/multiprocessing/popen_fork.py", line 69, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f22938e7790>
Traceback (most recent call last):
  File "/home/zhangdaoliang/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/zhangdaoliang/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
**AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'**

eval model::   0%|          | 0/11 [00:03<?, **?it/s]**

**Comment by LDOUBLEV** [comment]
看报错是模型评估的是后数据加载报错了
- 可以先检查下eval数据的格式是否符合paddleocr的数据格式；
- 把eval.loader的[num_works](https://github.com/PaddlePaddle/PaddleOCR/blob/7ca246f4f3b20b78fb96ecfd2e179c1067e55a6c/configs/rec/rec_icdar15_train.yml#L99)设置为0，执行tools/eval.py试试
