### ISSUE TITLE
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

### ISSUE THREAD

**Issue by 1058239242** [PaddlePaddle/Paddle#33516]
raceback (most recent call last):
  File "tools/train.py", line 125, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 102, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/xutao/work/PaddleOCR/tools/program.py", line 204, in train
W0611 08:10:16.251390 273098 default_variables.cpp:78] Fail to open /proc/self/stat: Too many open files [24]
W0611 08:10:16.393468 273098 default_variables.cpp:331] Fail to open /proc/self/fd: Too many open files [24]
W0611 08:10:16.393501 273098 default_variables.cpp:209] Fail to open /proc/self/statm: Too many open files [24]
W0611 08:10:16.393524 273098 default_variables.cpp:276] Fail to open /proc/loadavg: Too many open files [24]
W0611 08:10:16.393543 273098 default_variables.cpp:429] Fail to open /proc/self/io: Too many open files [24]
    for idx, batch in enumerate(train_dataloader):
  File "/home/xutao/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 426, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/xutao/anaconda3/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
    self._init_workers()
  File "/home/xutao/anaconda3/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 327, in _init_workers
    worker.start()
  File "/home/xutao/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/xutao/anaconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/xutao/anaconda3/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/xutao/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/xutao/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 65, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
Exception ignored in: <bound method _DataLoaderIterMultiProcess.__del__ of <paddle.fluid.dataloader.dataloader_iter._DataLoaderIterMultiProcess object at 0x7f0b09ddc5c0>>
Traceback (most recent call last):
  File "/home/xutao/anaconda3/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/xutao/anaconda3/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

**Comment by Shixiaowei02** [comment]
您好，现在需要确认最终的报错是否和
`OSError: [Errno 24] Too many open files`
相关。请尝试输入 `ulimit -n 10000` 改变 linux 文件打开数量限制，然后看问题是否消失。谢谢
