### ISSUE TITLE
Error in save_quant_model.py

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#33541]
After PR: b2afc8dfd2151c1646bd2dc639620df8b8858578
an error appears:
```
+ python python/paddle/fluid/contrib/slim/tests/save_quant_model.py --quant_model_path=/data/PaddlePaddle/trained_models/ERNIE/Ernie_qat/float --int8_model_save_path=/data/PaddlePaddle/trained_models/ERNIE/ernie_int8 --ops_to_quantize=fc,reshape2,transpose2
/usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "python/paddle/fluid/contrib/slim/tests/save_quant_model.py", line 24, in <module>
    import paddle
  File "/usr/local/lib/python3.6/dist-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/__init__.py", line 58, in <module>
    from . import contrib
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/contrib/__init__.py", line 35, in <module>
    from . import optimizer
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/contrib/optimizer.py", line 14, in <module>
    from paddle.fluid.optimizer import Optimizer
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/optimizer.py", line 25, in <module>
    import paddle.fluid as fluid
AttributeError: module 'paddle' has no attribute 'fluid'
```
**CMake flags used while PaddlePaddle build:**
```
CMAKE_FLAGS='-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6'
```

**Comment by Shixiaowei02** [comment]
We have received your problem but cannot reproduce it locally, are you sure that this submission caused the problem?

**Comment by OliverLPH** [comment]
@Shixiaowei02 this problem only occurred in python3.6, and it has been revert by https://github.com/PaddlePaddle/Paddle/pull/33538

**Comment by pmajchrzak** [comment]
seems to me that issue is solved so can be closed
