### ISSUE TITLE
paddle2.0,cuda10.0 运行报错：OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.

### ISSUE THREAD

**Issue by weichen12345** [PaddlePaddle/Paddle#33619]
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    model = ErnieSeg()
  File "/home/tc/code/chinese-casual-extraction/ErnieSEG.py", line 13, in __init__
    self.erniemodel = ErnieModel.from_pretrained('ernie-1.0').train()
  File "/home/tc/anaconda3/lib/python3.7/site-packages/ernie/modeling_ernie.py", line 283, in from_pretrained
    model = cls(cfg_dict, name=name_prefix)
  File "/home/tc/anaconda3/lib/python3.7/site-packages/ernie/modeling_ernie.py", line 326, in __init__
    self.ln = _build_ln(d_model, name=append_name(name, 'pre_encoder'))
  File "/home/tc/anaconda3/lib/python3.7/site-packages/ernie/modeling_ernie.py", line 88, in _build_ln
    initializer=nn.initializer.Constant(0.)), )
  File "/home/tc/anaconda3/lib/python3.7/site-packages/paddle/nn/layer/norm.py", line 532, in __init__
    default_initializer=Constant(1.0))
  File "/home/tc/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 408, in create_parameter
    default_initializer)
  File "/home/tc/anaconda3/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 372, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/tc/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2984, in create_parameter
    initializer(param, self)
  File "/home/tc/anaconda3/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 165, in __call__
    stop_gradient=True)
  File "/home/tc/anaconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3100, in _prepend_op
    kwargs.get("stop_gradient", False))
  File "/home/tc/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External)  Cuda error(35), CUDA driver version is insufficient for CUDA runtime version.
  [Advise: This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration.Users should install an updated NVIDIA display driver to allow the application to run.] (at /paddle/paddle/fluid/platform/gpu_info.cc:78)
  [operator < fill_constant > error]

**Comment by DannyIsFunny** [comment]
你好从报错信息看是因为环境问题：gpu    驱动版本过低
![image](https://user-images.githubusercontent.com/45189361/122361639-06b69e80-cf8a-11eb-8087-7bb9fc651036.png)
cuda10.0需要410以上
