### ISSUE TITLE
Paddle-TensorRT使用中的问题

### ISSUE THREAD

**Issue by JianJingGao** [PaddlePaddle/Paddle#33716]
Paddle version: 2.1.0
Paddle With CUDA: True

OS: Windows 10
Python version: 3.7.10

CUDA version: 10.2.89
cuDNN version: 7.6.5
Nvidia driver version: 462.30
————————————————————————————————————————————————————————
1.开启dynamic_shape之后，参数为fp16，启动速度贼慢，需要五到十分钟的样子
2.关闭dynamic_shape启动程序会报错，输入图像为固定尺寸的视频帧，错误如下：
![Uploading image.png…]()

**Comment by JianJingGao** [comment]
![image](https://user-images.githubusercontent.com/51236891/122862093-2fa4ae00-d353-11eb-94a1-4cbc9ef52471.png)

**Comment by JianJingGao** [comment]
运行dynamic之后报错 

 `--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: TRT runtime input shape of image is invalid. Expect runtime input shape to be within min/max input shape configured in SetTRTDynamicShapeInfo(),but got runtime input shape = [1, 3, 704, 1344], min input shape = [1, 3, 1, 1], max input shape = [1, 3, 1280, 1280].
  [Hint: Expected is_input_shape_valid(runtime_input_shape, min_input_shape, max_input_shape) == true, but received is_input_shape_valid(runtime_input_shape, min_input_shape, max_input_shape):0 != true:1.] (at D:\work\Paddle\paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:124)
`

**Comment by JianJingGao** [comment]
E0622 12:34:19.013554 17588 helper.h:84] Parameter check failed at: engine.cpp::nvinfer1::rt::ExecutionContext::setBindingDimensions::948, condition: profileMaxDims.d[i] >= dimensions.d[i]
E0622 12:34:19.013554 17588 helper.h:84] Parameter check failed at: engine.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)
E0622 12:34:19.013554 17588 helper.h:84] Parameter check failed at: engine.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)
E0622 12:34:19.013554 17588 helper.h:84] Parameter check failed at: engine.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)
E0622 12:34:19.013554 17588 helper.h:84] Parameter check failed at: engine.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)
E0622 12:34:19.013554 17588 helper.h:84] Parameter check failed at: engine.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)
E0622 12:34:19.013554 17588 helper.h:84] Parameter check failed at: engine.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)
E0622 12:34:19.013554 17588 helper.h:84] Parameter check failed at: engine.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::1092, condition: allInputDimensionsSpecified(routine)

Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:/work/Python/PaddleDetection/deploy/python/infer.py", line 1052, in thread_network_video_dispose
    results = detector.predict([pre_im], FLAGS.threshold)
  File "D:/work/Python/PaddleDetection/deploy/python/infer.py", line 277, in predict
    self.predictor.run()
NotImplementedError: 

  Compile Traceback (most recent call last):
    File "tools/export_model.py", line 105, in <module>
      main()
    File "tools/export_model.py", line 101, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 69, in run
      trainer.export(FLAGS.output_dir)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\ppdet\engine\trainer.py", line 507, in export
      input_spec, static_model.forward.main_program,
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 488, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 702, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-65>", line 2, in from_func_spec
      
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\ppdet\modeling\architectures\meta_arch.py", line 24, in forward
      self.model_arch()
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\ppdet\modeling\architectures\solov2.py", line 69, in model_arch
      body_feats = self.neck(body_feats)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "C:\Users\GAOTIA~1\AppData\Local\Temp\tmpmf1m0adz.py", line 31, in forward
      for_loop_condition_4, for_loop_body_4, [num_levels, laterals, i])
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 44, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 58, in _run_py_while
      loop_vars = body(*loop_vars)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\ppdet\modeling\necks\fpn.py", line 198, in forward
      mode='nearest', )
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\nn\functional\common.py", line 470, in interpolate
      attrs=attrs)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\framework.py", line 3232, in append_op
      attrs=kwargs.get("attrs", None))
    File "C:\Users\Gaotiantian\anaconda3\envs\pp-gpu\lib\site-packages\paddle\fluid\framework.py", line 2312, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
UnimplementedError: Input(X) dimension must be 3, 4 or 5, but got dimension = 0 . (at D:/work/Paddle/paddle/fluid/operators/interpolate_v2_op.cc:348)
  [operator < nearest_interp_v2 > error]


Process finished with exit code -1

**Comment by juncaipeng** [comment]
> 运行dynamic之后报错
> 
> ## `--------------------------------------
> C++ Traceback (most recent call last):
> Not support stack backtrace yet.
> 
> ## Error Message Summary:
> InvalidArgumentError: TRT runtime input shape of image is invalid. Expect runtime input shape to be within min/max input shape configured in SetTRTDynamicShapeInfo(),but got runtime input shape = [1, 3, 704, 1344], min input shape = [1, 3, 1, 1], max input shape = [1, 3, 1280, 1280].
> [Hint: Expected is_input_shape_valid(runtime_input_shape, min_input_shape, max_input_shape) == true, but received is_input_shape_valid(runtime_input_shape, min_input_shape, max_input_shape):0 != true:1.] (at D:\work\Paddle\paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:124)
> `

从log可以看出，实际执行的input shape大于设置的max input shape，你需要改一下设置最大的shape

**Comment by JianJingGao** [comment]
我输入的图像应该是1024*540的

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年6月22日 19:52
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [PaddlePaddle/Paddle] Paddle-TensorRT使用中的问题 (#33716)


运行dynamic之后报错

`--------------------------------------

C++ Traceback (most recent call last):
Not support stack backtrace yet.

Error Message Summary:

InvalidArgumentError: TRT runtime input shape of image is invalid. Expect runtime input shape to be within min/max input shape configured in SetTRTDynamicShapeInfo(),but got runtime input shape = [1, 3, 704, 1344], min input shape = [1, 3, 1, 1], max input shape = [1, 3, 1280, 1280].
[Hint: Expected is_input_shape_valid(runtime_input_shape, min_input_shape, max_input_shape) == true, but received is_input_shape_valid(runtime_input_shape, min_input_shape, max_input_shape):0 != true:1.] (at D:\work\Paddle\paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:124)
`

从log可以看出，实际执行的input shape大于设置的max input shape

―

**Comment by juncaipeng** [comment]
那基于log看不出来具体问题，你可以提供复现的单侧（模型、数据、代码、说明文档），我们来调试。
