### ISSUE TITLE
在训练过程中突然出现未知错误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#33772]
- PaddlePaddle 2.1.0
 - Python 3.7
 - Ubuntu 18.04
 - 双卡 2080ti

错误信息如下：
```
[2021-06-25 04:42:10.712613] Train epoch 2, batch: 20000/45490, loss: 47.108596, accuracy: 0.000005, eta: 5 days, 19:32:32
[2021-06-25 04:42:33.908209] Train epoch 2, batch: 20100/45490, loss: 46.775913, accuracy: 0.000005, eta: 5 days, 20:04:23

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle::memory::Copy<paddle::platform::CPUPlace, paddle::platform::CUDAPlace>(paddle::platform::CPUPlace, void*, paddle::platform::CUDAPlace, void const*, unsigned long, CUstream_st*)
1   paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)
2   paddle::framework::SignalHandle(char const*, int)
3   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1624575567 (unix time) try "date -d @1624575567" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e800003393) received by PID 13245 (TID 0x7fd531a3e740) from PID 13203 ***]

Traceback (most recent call last):
  File "train.py", line 188, in <module>
    dist.spawn(train, args=(args,), gpus=args.gpus)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 496, in spawn
    while not context.join():
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 296, in join
    self._throw_exception(error_index)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 304, in _throw_exception
    (error_index, name))
Exception: Process 0 terminated with signal SIGKILL.
```

 没挂掉之前的显卡使用情况：
![image](https://user-images.githubusercontent.com/26297768/123361174-2a3ca300-d5a1-11eb-8b4a-b0184e304a7c.png)

**Comment by ForFishes** [comment]
您好，请问这个是静态图还是动态图呢？还有这里能看到其他卡的日志。

**Comment by yeyupiaoling** [comment]
看不到，这个是动态图。
就只有这些日志

**Comment by ForFishes** [comment]
这里可能是数据读取出了问题，要具体分析，需要提供最小可复现的代码。报错信息有限呢。

**Comment by yeyupiaoling** [comment]
小的代码没有，是这个项目：https://github.com/yeyupiaoling/VoiceprintRecognition-PaddlePaddle

如果是读取数据的问题，那么前面也成功训练了好几个epoch呢。

**Comment by ForFishes** [comment]
您好，这里先把 find_unused_parameters=True，然后再训练看看是否还是报错？

**Comment by yeyupiaoling** [comment]
@ForFishes 请问find_unused_parameters=True这个参数在哪里设置呢？

**Comment by wyuzyf** [comment]
你好，请问解决了么，我的环境
paddlepaddle-gpu       2.1.0.post101
Python 3.6
Ubuntu 18.04
双卡 2080ti

**Comment by yeyupiaoling** [comment]
@wyuzyf 没有。不过这个问题没有出现了，我也不知道改了啥。可能偶尔出现吧。
