### ISSUE TITLE
数据集读取API傻傻搞不清

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#33988]
```python
sampler = RandomSampler(train_dataset)
batch_sampler = BatchSampler(sampler=sampler, batch_size=100)
train_loader = DataLoader(dataset=train_dataset, batch_sampler=batch_sampler, num_workers=cfg.DATASET.WORKERS, batch_size=cfg.TRAIN.BATCH_SIZE)
```
```
Traceback (most recent call last):
  File "Test.py", line 68, in <module>
    train_loader = DataLoader(dataset=train_dataset, batch_sampler=batch_sampler, num_workers=cfg.DATASET.WORKERS, batch_size=cfg.TRAIN.BATCH_SIZE)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 338, in __init__
    "dataset should be subclass instance of paddle.io.Dataset"
AssertionError: dataset should be subclass instance of paddle.io.Dataset
```
其中train_dataset是Paddle.io.Dataset，前两行都能正确运行，且可以从中所以数据，第三行就报错了，我难以从文档中的信息获取如何组合使用这几个API

**Comment by TeslaZhao** [comment]
您好，RandomSampler中未对train_dataset类型做强制检查，而DataLoader中做了强制检查。因此，建议您需要check一下train_dataset类型和名称是否正确（为None也会报错）

**Comment by GuoQuanhao** [comment]
train_dataset里面的每个数据都是一个三元元组，分别包含图像，标签和图像名，是图像名这个str类型造成的吗

**Comment by TeslaZhao** [comment]
有可能

**Comment by GuoQuanhao** [comment]
已解决，不是str类型造成的，是我自己从object继承一个类，再从这个类继承出一个子类来用getitem获取数据，把object改成Dataset就好了
