### ISSUE TITLE
Error on  trying to verify installation 

### ISSUE THREAD

**Issue by harsh-curl** [PaddlePaddle/Paddle#34164]
**System information**
- PaddlePaddle 2.1.0
- CPU: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz(6 cores)
- Redhat Distro
- Python 3.7
- Install method: pip install
- GCC version 8.3

**To Reproduce**

**import paddle.fluid** in a python interpreter

**Describe your current behavior**

It throws the following error:

**Error: Can not import avx core while this file exists: /home/ec2-user/.local/share/virtualenvs/ec2-user-zzkNbF-x/lib/python3.7/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/share/virtualenvs/ec2-user-zzkNbF-x/lib/python3.7/site-packages/paddle/__init__.py", line 26, in <module>
    from .fluid import monkey_patch_variable
  File "/home/ec2-user/.local/share/virtualenvs/ec2-user-zzkNbF-x/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/ec2-user/.local/share/virtualenvs/ec2-user-zzkNbF-x/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/ec2-user/.local/share/virtualenvs/ec2-user-zzkNbF-x/lib/python3.7/site-packages/paddle/fluid/core.py", line 297, in <module>
    raise e
  File "/home/ec2-user/.local/share/virtualenvs/ec2-user-zzkNbF-x/lib/python3.7/site-packages/paddle/fluid/core.py", line 257, in <module>
    from .core_avx import *
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/ec2-user/.local/share/virtualenvs/ec2-user-zzkNbF-x/lib/python3.7/site-packages/paddle/fluid/core_avx.so)**

**Comment by MissPenguin** [comment]
看着是GCC版本过低导致的，建议升级GCC版本到8.4

**Comment by harsh-curl** [comment]
Hi @MissPenguin, is it okay if we try with gcc 9?

**Comment by harsh-curl** [comment]
@MissPenguin  even after updating the gcc version to 9.2.0. I am getting the same error.

**Comment by MissPenguin** [comment]
This kind of error message is an environmental problem. If it is not feasible to try different versions of GCC, you can try to solve it in the following ways:

Check whether libstdc++.so.6 is installed in the current directory by command "strings /usr/lib64/libstdc++.so.6|grep CXXABI".  If yes, migrate the relevant so to the current directory. More details：https://blog.csdn.net/zerow__/article/details/88845192; if no, please download the so file first and relink. For more details, refer to: https://blog.csdn.net/u012811841/article/details/77854581
