### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 24 were given

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/Paddle#34226]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题
- 版本、环境信息：
    1）PaddlePaddle版本：paddle 2.0
    2）CPU/GPU：cpu
    3）系统环境：Mac OS 10.14
    4）Python版本号
    5）显存信息
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 复现信息：如为报错，请给出复现环境、复现步骤
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
代码，我就添加了一个summary代码，想看看模型的结构，源代码地址为：https://github.com/PaddlePaddle/PaddleRec/blob/release/2.1.0/models/multitask/esmm/dygraph_model.py
：
```
esmm_model = net.ESMMLayer(sparse_feature_number, sparse_feature_dim,
                                   num_field, ctr_fc_sizes, cvr_fc_sizes)
        inputs=[(2,3) for i in range(23)]
        info=paddle.summary(esmm_model,input_size=inputs,dtypes=int)
        print(info)
```
错误信息
```
2021-07-18 16:43:36,270 - INFO - **************common.configs**********
2021-07-18 16:43:36,270 - INFO - use_gpu: False, use_xpu: False, use_visual: False, train_batch_size: 2, train_data_dir: data/train, epochs: 3, print_interval: 2, model_save_path: output_model_esmm
2021-07-18 16:43:36,270 - INFO - **************common.configs**********
Traceback (most recent call last):
  File "../../../tools/trainer.py", line 210, in <module>
    main(args)
  File "../../../tools/trainer.py", line 89, in main
    dy_model = dy_model_class.create_model(config)
  File "/Users/wugaosheng/Documents/pythonFiles/PaddleRec/models/multitask/esmm/dygraph_model.py", line 40, in create_model
    info=paddle.summary(esmm_model,input_size=inputs,dtypes=int)
  File "/Users/wugaosheng/anaconda3/lib/python3.7/site-packages/paddle/hapi/model_summary.py", line 149, in summary
    result, params_info = summary_string(net, _input_size, dtypes)
  File "<decorator-gen-245>", line 2, in summary_string
  File "/Users/wugaosheng/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 316, in _decorate_function
    return func(*args, **kwargs)
  File "/Users/wugaosheng/anaconda3/lib/python3.7/site-packages/paddle/hapi/model_summary.py", line 276, in summary_string
    model(*x)
  File "/Users/wugaosheng/anaconda3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
TypeError: forward() takes 2 positional arguments but 24 were given
```

Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please provide us with the following details :
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/cuDNN version
-OS Platform and Distribution(eg.Mac OS 10.14)
-Python version 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by joey12300** [comment]
您好，paddle.summary目前不支持输入是个list的参数。https://github.com/PaddlePaddle/PaddleRec/blob/release/2.1.0/models/multitask/esmm/net.py#L79 我理解inputs是个list，装着多个shape一致的tensor。可以尝试把inputs中所有tensor concat起来，使得inputs是个tensor。
