### ISSUE TITLE
centos7 armV8 源码编译成功,import paddle报错ImportError: /root/paddle/build/python/paddle/fluid/core_noavx.so: ELF load command alignment not page-aligned(使用源码编译的patchelf可成功编译并安装)

### ISSUE THREAD

**Issue by Duanexiao** [PaddlePaddle/Paddle#34223]
源码编译paddle后pip install 编译生成的paddle whl文件，在校验是否安装成功的时候报错
Can not import noavx core while this file exists: /root/paddle/build/python/paddle/fluid/core_noavx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/paddle/build/python/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/root/paddle/build/python/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/root/paddle/build/python/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/root/paddle/build/python/paddle/fluid/core.py", line 362, in <module>
    raise e
  File "/root/paddle/build/python/paddle/fluid/core.py", line 312, in <module>
    from .core_noavx import *
ImportError: /root/paddle/build/python/paddle/fluid/core_noavx.so: ELF load command alignment not page-aligned

paddlepaddle版本: release/2.21
cpu: 鲲鹏麒麟 armv8
无gpu环境
编译操作步骤是按照文档操作的

**Comment by Duanexiao** [comment]
搞定了，不能使用系统yum install 的patchelf,我直接源码编译的patchelf，然后按照源码编译paddle就ok了
