### ISSUE TITLE
增量学习在MPI上的设置

### ISSUE THREAD

**Issue by Jarlonyan** [PaddlePaddle/Paddle#3423]
![machi 2017-08-11 21-10-19](https://user-images.githubusercontent.com/19587684/29214354-983ac24c-7ed9-11e7-904e-7ab9ef0cf0d6.png)

请问，在MPI上做增量学习，这个init_model_path可以是本地文件吗？？
另外，为什么init_model_path不存在的时候，也不报错，而会执行呢？？

原始代码：
```
 13  paddle.init(use_gpu=False,
 14         trainer_count=int(os.getenv("PADDLE_TRAINER_COUNT", "1")),
 15         port=int(os.getenv("PADDLE_PORT", "7164")),
 16         ports_num=int(os.getenv("PADDLE_PORTS_NUM", "1")),
 17         num_gradient_servers=int(os.getenv("PADDLE_NUM_GRADIENT_SERVERS", "1")),
 18         trainer_id=int(os.getenv("PADDLE_TRAINER_ID", "0")),
 19         ports_num_for_sparse=int(os.getenv("PADDLE_PORTS_NUM_FOR_SPARSE", "1")),
 20         pservers=os.getenv("PADDLE_PSERVERS", "127.0.0.1"),
 21         init_model_path="./dnn_params_pass12345678.tar.gz"
 22         )
```

**Comment by typhoonzero** [comment]
> 请问，在MPI上做增量学习，这个init_model_path可以是本地文件吗？？

`init_model_path`这个参数目前仅适用于V1 API，在使用V2 API定义网络时，要加载V2训练输出的模型，需要调用`parameter.from_tar()`。在MPI集群训练时，`parameter.from_tar()`由于是每个节点执行的，需要提前将tar文件下载到每个节点才可以。

> 另外，为什么init_model_path不存在的时候，也不报错，而会执行呢？？

同上，此参数仅适用于V1 API。

同时，的确需要一些文档来描述V1和V2 API command-line参数和init()参数中的一些区别。

**Comment by Jarlonyan** [comment]
现在有两个问题：

1. 我是这样调用的：
```
parameters = paddle.parameters.from_tar("dnn_params_pass7.tar.gz")
```
结果报错：
```
Traceback (most recent call last):
  File "dnn_experiment_cpu_full_slot_1_changeB_D_2_newdata.py", line 935, in <module>
    incrementLearning(num_pass=num_pass)
  File "dnn_experiment_cpu_full_slot_1_changeB_D_2_newdata.py", line 882, in incrementLearning
    parameters = paddle.parameters.from_tar("dnn_params_pass7.tar.gz")
AttributeError: 'module' object has no attribute 'from_tar'
```
2. tar文件如何下载到每个节点？？

**Comment by wanghaoshuang** [comment]
@Jarlonyan 关于第一个错误，你这样试下?
```
parameters = paddle.parameters.create(cost)
if args.init_model is not None:
          assert os.path.isfile(args.init_model), "Init model can't be found!"
          print("init parameters from %s..."%args.init_model)
          parameters.init_from_tar(open(args.init_model))
```

**Comment by typhoonzero** [comment]
1. 
```python
with open("dnn_params_pass7.tar.gz") as f:
    parameters = paddle.Parameters.from_tar(f)
```

2. 使用任意方法都行，比如从HDFS下载，或者放在FTP可访问的位置然后wget下来都行。在python程序执行开始的位置使用比如`os.system("/hadoop/client/path/hadoop -get xxx")`或者`os.system("wget xxx")`下载即可。

**Comment by Jarlonyan** [comment]
```
# load parameters
793     os.system("hadoop fs -get /app/ns/tieba/recommend/yanzhenglong/mpi_dnn_experiment/paramfile/dnn_params_pass7.tar.gz ./"    )
794     parameters = paddle.parameters.Parameters.from_tar( gzip.open("dnn_params_pass7.tar.gz"))
```
这样写，还是找不到参数文件

**Comment by wanghaoshuang** [comment]
>@typhoonzero:  
os.system("hadoop fs -get /***/dnn_params_pass7.tar.gz ./"    )应该是这句执行没成功，hadoop命令在workspace下应该是放在一个目录里的，比如./hadoop_client/bin/hadoop之类的

我们尽量在这里交流吧，以后方便其他人搜索到。

**Comment by Jarlonyan** [comment]
配置了环境变量，直接用hadoop应该可以的啊

**Comment by typhoonzero** [comment]
如果是没有下载成功，可以用`os.system("hadoop fs -get /***/dnn_params_pass7.tar.gz ./ &> log/hadoop_fetch.log" )`输出日志看下下载失败的原因。

**Comment by Jarlonyan** [comment]
```
Bad connection to FS. command aborted. exception is : java.io.IOException: Incomplete HDFS URI, no host: hdfs://namenode:port
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:219)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2198)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:64)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2210)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:177)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:150)
	at org.apache.hadoop.fs.FsShell.init(FsShell.java:103)
	at org.apache.hadoop.fs.FsShell.run(FsShell.java:2166)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:79)
	at org.apache.hadoop.fs.FsShell.main(FsShell.java:2340)
```

**Comment by Jarlonyan** [comment]
报错，说用户没有权限。我改成：
```
hadoop fs -get hdfs机器及文件路径 -u  username -p password ./  
```
请问，命令格式是怎样的？？

**Comment by wanghaoshuang** [comment]
hadoop 命令格式: 
`hadoop fs -Dfs.default.name=hdfs://server:54310 -Dhadoop.job.ugi=username,password`

**Comment by cszhou** [comment]
@Jarlonyan 
```Python
hdfs_dict = "${HADOOP_HOME}/bin/hadoop fs -Dfs.default.name=hdfs://xxxxx:54310 -Dhadoop.job.ugi=name,pwd -getmerge filepath ."
(status, output) = commands.getstatusoutput(hdfs_dict)
```
