### ISSUE TITLE
使用jit.save报错：paddleValueError: No valid transformed program for function: forward(input,label), input_spec: None

### ISSUE THREAD

**Issue by Reatris** [PaddlePaddle/Paddle#34345]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.0.post101 
    2）CPU：None
    3）GPU：V100
    4）系统环境：AIStudio
- 训练信息
    1）单机
    2）显存信息
    3）paddle.jit.save
- 问题描述：自组网后训练，（动态图）保存模型op保存，以下为报错信息

```python
paddle.jit.save(BACKBONE, os.path.join(os.path.join(os.getcwd(), MODEL_ROOT),
                                                "Backbone"),input_spec=[inputs])
```

如上是我保存模型的方法，inputs 是我输入网络的数据

```python

**for iters, data in tqdm(enumerate(train_loader())):
            inputs, labels = data[0], data[1] 
            features = BACKBONE(inputs)
            outputs = HEAD(features, labels)
            loss = LOSS(outputs, labels)**

```

报错：

```
ValueError: No valid transformed program for function: forward(input,label), input_spec: None.
	    Please specific `input_spec` in `@paddle.jit.to_static` or feed input tensor to call the decorated function at once.
```

完整报错：

```bash

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return (isinstance(seq, collections.Sequence) and
Traceback (most recent call last):
  File "train.py", line 228, in <module>
    "Head"))
  File "<decorator-gen-67>", line 2, in save
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 729, in save
    concrete_program = static_forward.concrete_program
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 493, in concrete_program_specify_input_spec
    format(self._function_spec))
ValueError: No valid transformed program for function: forward(input,label), input_spec: None.
	    Please specific `input_spec` in `@paddle.jit.to_static` or feed input tensor to call the decorated function at once.

```

**Comment by ceci3** [comment]
这个保存接口是保存成静态图模型，保存动态图参数的话可以直接调用paddle.save接口，保存成静态图模型的话，需要先调用paddle.jit.to_static接口转成静态图模型，再调用paddle.jit.save保存

**Comment by Reatris** [comment]
@ceci3 我是想保存推理模型的，paddle.save是可以正常保存的，
我正在尝试的是文档里  **3.1.1.2 动态图训练 + 模型&参数保存**
我想的是保存推理模型，但是用了文档里的方法不能保存[https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/08_model_save_load_cn.html](url)

**Comment by ceci3** [comment]
@Reatris   哦哦，我看文档里面模型的forward函数上面有  @paddle.jit.to_static 这个上下文管理，你的模型里面加了嘛？

**Comment by Reatris** [comment]
@ceci3 您仔细看了3.1.1.2 动态图训练 + 模型&参数保存 后面的注意点，特别说明了  `相比动转静训练，Layer对象的forward方法不需要额外装饰，保持原实现即可`

**Comment by Reatris** [comment]
@ceci3 再给你贴下文档链接[3.1.1.2 动态图训练 + 模型&参数保存](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/02_paddle2.0_develop/08_model_save_load_cn.html)

**Comment by Aurelius84** [comment]
> ```python
> paddle.jit.save(BACKBONE, os.path.join(os.path.join(os.getcwd(), MODEL_ROOT),
>                                                 "Backbone"),input_spec=[inputs])
> ```

这里的BACKBONE 是类，还是类实例？

**Comment by Reatris** [comment]
@Aurelius84  BACKBONE是paddle.nn.Layer的类实例

**Comment by Aurelius84** [comment]
> ```python
> input_spec=[inputs])
> ```

这里的 inputs 是 `paddle.static.InputSpec` 类型么

**Comment by Reatris** [comment]
不是，这是Tensor类，paddle.static.InputSpec照文档里的写依然报错，刚才我通过另一种保存方法保存了
https://github.com/PaddlePaddle/Paddle/issues/31222#issuecomment-785816448

**Comment by Aurelius84** [comment]
可否简化下逻辑，提供一下这段paddle.jit.save调用时的核心代码，我们复现下这个问题。另外请问下你这里的 inputs 是 list[Tensor] 还是？

**Comment by Reatris** [comment]
好的，那我去简化一下

**Comment by Reatris** [comment]
@Aurelius84 您可以帮我看看这个吗 https://github.com/PaddlePaddle/Paddle/issues/34391#issue-952720312

**Comment by Reatris** [comment]
> 可否简化下逻辑，提供一下这段paddle.jit.save调用时的核心代码，我们复现下这个问题。另外请问下你这里的 inputs 是 list[Tensor] 还是？

我把inputs放list里面了报错如下

```python

File "train.py", line 221, in <module>
    "Backbone"),input_spec=[[inputs]])
  File "<decorator-gen-67>", line 2, in save
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 729, in save
    concrete_program = static_forward.concrete_program
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
TypeError: In transformed code:

    File "/home/aistudio/face_evoLVe/paddle/backbone/resnet_pp.py", line 563, in forward (* user code *)
	conv1 = self.conv1(x)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 97, in forward
	input = layer(input)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/home/aistudio/face_evoLVe/paddle/backbone/resnet_pp.py", line 108, in forward
	out = self.conv(inputs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 667, in forward
	use_cudnn=self._use_cudnn)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 133, in _conv_nd
	op_type)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 81, in check_variable_and_dtype
	check_type(input, input_name, Variable, op_name, extra_message)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 114, in check_type
	(input_name, op_name, expected_type, type(input), extra_message))
    TypeError: The type of 'x' in conv2d must be (<class 'paddle.fluid.framework.Variable'>, <class 'paddle.Tensor'>), but received <class 'list'>. 

```

**Comment by hhxdestiny** [comment]
@Reatris 请教这个问题是怎么解决的？
