### ISSUE TITLE
动态图转静态图保存op报错TypeError: The data type of 'x' in sum must be ['float32', 'float64', 'int32', 'int64'], but received bool. 

### ISSUE THREAD

**Issue by Reatris** [PaddlePaddle/Paddle#34391]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.0.post101 
    2）CPU：None
    3）GPU：V100
    4）系统环境：AIStudio
- 训练信息
    1）单机
    2）显存信息
    3）paddle.jit.save
- 问题描述：自组网后训练，（动态图转静态图）保存模型op保存，以下为报错信息

```python

File "/home/aistudio/face_evoLVe/paddle/head/metrics.py", line 61, in forward (* user code *)
	paddle.sum(paddle.square(weight), axis=0, keepdim=True))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/math.py", line 745, in sum
	x, 'x', ['float32', 'float64', 'int32', 'int64'], 'sum')
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 82, in check_variable_and_dtype
	check_dtype(input.dtype, input_name, expected_dtype, op_name, extra_message)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 139, in check_dtype
	extra_message))
    TypeError: The data type of 'x' in sum must be ['float32', 'float64', 'int32', 'int64'], but received bool. 

```

有关于这个op在Layer里面的写法是这样的
```python

def forward(self, input, label):
        # norm input
        input_norm = paddle.sqrt(
            paddle.sum(paddle.square(input), axis=1, keepdim=True))
        input = paddle.divide(input, input_norm)  # support broadcast
        # norm weight
        weight = self.fc0.weight
         ###########################
        weight_norm = paddle.sqrt(
            paddle.sum(paddle.square(weight), axis=0, keepdim=True))
        #####################################
        weight = paddle.divide(weight, weight_norm)
        # get cos(sita)
        cos = paddle.matmul(input, weight)
        sin = paddle.sqrt(1.0 - paddle.square(cos) + 1e-6)
        cos_m = math.cos(self.margin)
        sin_m = math.sin(self.margin)
        phi = cos * cos_m - sin * sin_m
        # if use easy_margin
        th = math.cos(self.margin) * (-1)
        mm = math.sin(self.margin) * self.margin
        if self.easy_margin:
            phi = self._paddle_where_more_than(cos, 0, phi, cos)
        else:
            phi = self._paddle_where_more_than(cos, th, phi, cos - mm)
        # use label
        one_hot = paddle.nn.functional.one_hot(label, self.class_dim)
        one_hot = paddle.squeeze(one_hot, axis=[1])
        output = paddle.multiply(one_hot, phi) + paddle.multiply(
            (1.0 - one_hot), cos)
        output = output * self.scale
        return output

```

如下是我保存模型的方法

```python

save_backbone = paddle.jit.to_static(
        BACKBONE,
        input_spec=[InputSpec(shape = [None,3,112,112],dtype = 'float32')]
    )
    paddle.jit.save(save_backbone, os.path.join(os.path.join(os.getcwd(), MODEL_ROOT),
                                                "Backbone"))
    save_head = paddle.jit.to_static(
        HEAD,
        input_spec=[InputSpec(shape = [None,512],dtype = 'float32'),InputSpec(shape = [None,1],dtype = 'int64')]
    )
    paddle.jit.save(save_head, os.path.join(os.path.join(os.getcwd(), MODEL_ROOT),
                                            "Head"))


```

完整报错：

```bash

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  return (isinstance(seq, collections.Sequence) and
Traceback (most recent call last):
  File "train.py", line 244, in <module>
    "Head"))
  File "<decorator-gen-67>", line 2, in save
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 719, in save
    inner_input_spec)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
TypeError: In transformed code:

    File "/home/aistudio/face_evoLVe/paddle/head/metrics.py", line 61, in forward (* user code *)
	paddle.sum(paddle.square(weight), axis=0, keepdim=True))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/math.py", line 745, in sum
	x, 'x', ['float32', 'float64', 'int32', 'int64'], 'sum')
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 82, in check_variable_and_dtype
	check_dtype(input.dtype, input_name, expected_dtype, op_name, extra_message)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 139, in check_dtype
	extra_message))
    TypeError: The data type of 'x' in sum must be ['float32', 'float64', 'int32', 'int64'], but received bool. 

```

**Comment by Reatris** [comment]
我把API换成paddle.fluid.layers.reduce_sum 还是这样

```python

File "/home/aistudio/face_evoLVe/paddle/head/metrics.py", line 62, in forward (* user code *)
	w_sum = paddle.fluid.layers.reduce_sum(w_square,dim = 0,keep_dim=True)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 4409, in reduce_sum
	input, 'input', ['float32', 'float64', 'int32', 'int64'], 'reduce_sum')
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 82, in check_variable_and_dtype
	check_dtype(input.dtype, input_name, expected_dtype, op_name, extra_message)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 139, in check_dtype
	extra_message))
    TypeError: The data type of 'input' in reduce_sum must be ['float32', 'float64', 'int32', 'int64'], but received bool. 

```
