### ISSUE TITLE
use_shared_memory=False报错

### ISSUE THREAD

**Issue by Stave604671** [PaddlePaddle/Paddle#34451]
1）PaddlePaddle版本：Paddle2.1.0
    2）CPU：AIStudio
    3）GPU：AIStudio提供的V100
    4）Python：3.7
    1）单机，单卡
```
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects
```

**Comment by bjjwwang** [comment]
方便分享一下AIStudio的notebook吗

**Comment by Stave604671** [comment]
这个是训练的部分和dataset对象的部分，模型用的paddlehub的efficientnet，数据集是普通的分类数据集，这个代码在本地windows的paddle2.1GPU版可以跑，就是在云端不行。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月28日(星期三) 晚上6:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] use_shared_memory=False报错 (#34451)





 
方便分享一下AIStudio的notebook吗

**Comment by Stave604671** [comment]
> 方便分享一下AIStudio的notebook吗

https://aistudio.baidu.com/aistudio/projectdetail/2136219?shared=1
就是这个项目，然后跑第一个cell解压数据集，然后启动train_one.py开始出现了以下问题,希望帮忙把这个问题解决一下

当batchsize为32时报错shm溢出
然后我设置use_shared_memory=False以后的报错是这个：
2021-07-29 15:13:56,626 INFO     ('epoch:', 1, 'begin_train')
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: can't pickle Tensor objects

然后我同时设置use_shared_memory=False，和num_worker=0，报错是这个
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_Impl<std::_Bind_simple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1} ()> >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::framework::SignalHandle(char const*, int)
3   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1627543076 (unix time) try "date -d @1627543076" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x20) received by PID 1304 (TID 0x7f662f4b2700) from PID 32 ***]

Segmentation fault (core dumped)
然后我不设置use_shared_memory，设置num_worker=0,报错和上面一样
然后我工程项目在windows本地和Ubuntu本地的paddle2.1GPU环境都可以跑，就在aistudio不行。我骨干网络是efficientnetb0。

**Comment by Stave604671** [comment]
问题已经解决，好家伙，paddle2.x禁用了paddle.fluid，这个禁用在电脑本地没生效，在aistudio生效了。
然后paddle.io.dataloader调用了paddle.fluid，换成自定义的dataloader就能在aistudio跑了。

**Comment by zhijiejia** [comment]
AIStudio上paddle的数据加载是真的难用，服了

**Comment by Stave604671** [comment]
> AIStudio上paddle的数据加载是真的难用，服了

后来查清了，也不是版本的错，paddle.io没有考虑数据集未经过清洗的情况，数据集中有空值的时候就会报这个错。
