### ISSUE TITLE
飞浆AIstudio上使用GPU至尊环境跑paddleOCR出错

### ISSUE THREAD

**Issue by LinXin04** [PaddlePaddle/Paddle#34527]
飞浆AIstudio上使用GPU至尊环境跑paddleOCR出错，batch设置到了15，num_work设置为0还是报下面的错，迭代到20几次的时候会报错

ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 126, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 103, in main
    eval_class, pre_best_model_dict, logger, vdl_writer)
  File "/home/aistudio/paddleOCR/tools/program.py", line 203, in train
Exception in thread Thread-31:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 482, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 498, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 3927
    for idx, batch in enumerate(train_dataloader):

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by weiexcelpro** [comment]
首先是 飞桨 哈. 
请问这个报错的项目有公开网址吗?

**Comment by Xreki** [comment]
这个错误是因为AIStudio容器shared memory只有64M，无法设置成更大的。可以将DataLoader的use_shared_memory设置成False试下。
