### ISSUE TITLE
DYGRAPH + OneDNN runtime error

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#34544]
#### CMAKE flags
```
CMAKE_FLAGS='-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=ON -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6
```

#### Run command line
```
OMP_NUM_THREADS=28 FLAGS_use_mkldnn=True  /usr/bin/time -v python /root/models/paddle_models_github/dygraph/resnet/train.py --use_gpu=False --ce --max_iter=200  -b=32
```

#### ERROR message
```
Traceback (most recent call last):
  File "/root/models/paddle_models_github/dygraph/resnet/train.py", line 527, in <module>
    train_resnet()
  File "/root/models/paddle_models_github/dygraph/resnet/train.py", line 463, in train_resnet
    out = resnet(img)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 907, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/models/paddle_models_github/dygraph/resnet/train.py", line 324, in forward
    y = self.conv(inputs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 907, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/models/paddle_models_github/dygraph/resnet/train.py", line 216, in forward
    y = self._conv(inputs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/layers.py", line 907, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/nn.py", line 239, in forward
    out = core.ops.conv2d(input, self.weight, *attrs)
RuntimeError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   std::shared_ptr<paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type> paddle::imperative::PrepareData<paddle::imperative::VarBase>(paddle::framework::OperatorWithKernel const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::OpKernelType const&)
3   paddle::operators::ConvOp::GetKernelTypeForVar(std::string const&, paddle::framework::Tensor const&, paddle::framework::OpKernelType const&) const
4   std::string const& paddle::framework::AttrReader::Get<std::string >(std::string const&) const
5   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
6   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
NotFoundError: Attribute (data_format) should be in AttributeMap.
  [Hint: Expected found == true, but received found:0 != true:1.] (at /repos/paddle_paddle/paddle/fluid/framework/attribute.h:229)
  [operator < conv2d > error]
```

**Comment by wanghuancoder** [comment]
thx！
We will fix it in https://github.com/PaddlePaddle/Paddle/pull/34567
