### ISSUE TITLE
在训练过程中随机出现错误：RuntimeError: DataLoader 1 workers exit unexpectedly

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#34677]
- PaddlePaddle 2.1.2
 - Ubuntu 18.04
 - 2080ti CUDA 10.2

错误如下，设置1线程，2线程读取数据都会出错，2张显卡训练。
```
ERROR:root:DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    main()
  File "train.py", line 98, in main
    run(FLAGS, cfg)
  File "train.py", line 71, in run
    trainer.train(FLAGS.eval)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/ppdet/engine/trainer.py", line 339, in train
    for step_id, data in enumerate(self.loader):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 565, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 462, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
INFO 2021-08-06 18:10:23,310 launch_utils.py:327] terminate all the procs
ERROR 2021-08-06 18:10:23,325 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-08-06 18:10:26,326 launch_utils.py:327] terminate all the procs
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 391, in _thread_loop
    batch = self._get_data()
  File "/home/psdz/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 478, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 20968

```

**Comment by juncaipeng** [comment]
可以将数据的代码贴出来吗？没遇到类似问题。

**Comment by yeyupiaoling** [comment]
我用的是这个代码：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/tools/train.py

**Comment by juncaipeng** [comment]
使用PaddleDetection遇到的问题，请在PaddleDetection repo中提交相关issue，详细描述复现步骤，对应同学会更加熟悉一些如何解决。谢谢。
PaddleDetection提交issue的链接：https://github.com/PaddlePaddle/PaddleDetection/issues
