### ISSUE TITLE
jetson nano成功安装paddlepaddle gpu版本调用时报错

### ISSUE THREAD

**Issue by wyh669** [PaddlePaddle/Paddle#34709]
下载nv_jetson-cuda10.2-trt7-maxwell对应版本的paddlepaddle安装包，成功安装
但在运行命令import paddle时报如下错
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rvs/.local/lib/python3.6/site-packages/paddle/__init__.py", line 45, in <module>
    import paddle.distributed  # noqa: F401
  File "/home/rvs/.local/lib/python3.6/site-packages/paddle/distributed/__init__.py", line 15, in <module>
    from .spawn import spawn  # noqa: F401
  File "/home/rvs/.local/lib/python3.6/site-packages/paddle/distributed/spawn.py", line 28, in <module>
    from paddle.distributed.fleet.cloud_utils import use_paddlecloud
  File "/home/rvs/.local/lib/python3.6/site-packages/paddle/distributed/fleet/__init__.py", line 20, in <module>
    from .base.fleet_base import Fleet  # noqa: F401
  File "/home/rvs/.local/lib/python3.6/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 32, in <module>
    from ..meta_parallel import TensorParallel, model_parallel_random_seed
  File "/home/rvs/.local/lib/python3.6/site-packages/paddle/distributed/fleet/meta_parallel/__init__.py", line 15, in <module>
    from .parallel_layers import VocabParallelEmbedding  # noqa: F401
  File "/home/rvs/.local/lib/python3.6/site-packages/paddle/distributed/fleet/meta_parallel/parallel_layers/__init__.py", line 15, in <module>
    from .mp_layers import VocabParallelEmbedding  # noqa: F401
  File "/home/rvs/.local/lib/python3.6/site-packages/paddle/distributed/fleet/meta_parallel/parallel_layers/mp_layers.py", line 18, in <module>
    from paddle.nn import functional as F
  File "/home/rvs/.local/lib/python3.6/site-packages/paddle/nn/__init__.py", line 23, in <module>
    from .layer.activation import ELU  # noqa: F401
  File "/home/rvs/.local/lib/python3.6/site-packages/paddle/nn/layer/__init__.py", line 19, in <module>
    from . import container  # noqa: F401
  File "/home/rvs/.local/lib/python3.6/site-packages/paddle/nn/layer/container.py", line 17, in <module>
    from six.moves import collections_abc
ImportError: cannot import name 'collections_abc'

**Comment by wyh669** [comment]
已解决

**Comment by lixinweijy** [comment]
请问大佬是怎么解决的哈？
