### ISSUE TITLE
RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero.

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#34849]
platform centos 8x2080ti
version: 2.1.2
在aistudio上时能正确训练，在本地服务器使用dist.spawn(train, nprocs=2, gpus='0,1')，发现只占用0号卡，并且训练过程中，不定时的会报错如下：
```
Epoch:1/100 || Epochiter: 539/6440 || Iter: 539/644000 || Loc: 1.2577 Cla: 2.5154 Landm: 4.9627 || LR: 0.00100000 || Batchtime: 0.7507 s || ETA: 5 days, 14:10:51
Epoch:1/100 || Epochiter: 540/6440 || Iter: 540/644000 || Loc: 2.3884 Cla: 2.9396 Landm: 4.1411 || LR: 0.00100000 || Batchtime: 0.8593 s || ETA: 6 days, 9:35:54


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::BasicEngine::Execute()
1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&)
2   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvGradOpKernel<float>, paddle::operators::CUDNNConvGradOpKernel<double>, paddle::operators::CUDNNConvGradOpKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
3   paddle::operators::CUDNNConvGradOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
4   cudnnConvolutionBwdDataAlgo_t paddle::operators::SearchAlgorithm<cudnnConvolutionBwdDataAlgoPerf_t>::Find<float>(paddle::operators::ConvArgs const&, bool, bool, paddle::framework::ExecutionContext const&)
5   paddle::framework::SignalHandle(char const*, int)
6   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1628751952 (unix time) try "date -d @1628751952" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3ed0000a04b) received by PID 45210 (TID 0x7fc0dbd2c740) from PID 41035 ***]

Traceback (most recent call last):
  File "multi_train.py", line 149, in <module>
    dist.spawn(train, nprocs=2, gpus='0,1')
  File "/home/wql/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 501, in spawn
    while not context.join():
  File "/home/wql/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 312, in join
    self._throw_exception(error_index)
  File "/home/wql/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 330, in _throw_exception
    raise Exception(msg)
Exception: 

----------------------------------------------
Process 1 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File "/home/wql/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 261, in _func_wrapper
    result = func(*args)
  File "/home/wql/RetinaFace/Retinaface/multi_train.py", line 120, in train
    loss_l, loss_c, loss_landm = criterion(out, priors, [anno for anno in labels])
  File "/home/wql/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/wql/RetinaFace/Retinaface/layers/modules/multibox_loss.py", line 79, in forward
    landm_p = landm_data.masked_select(pos_idx1).reshape([-1, 10])
  File "/home/wql/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 1582, in reshape
    return paddle.fluid.layers.reshape(x=x, shape=shape, name=name)
  File "/home/wql/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 6142, in reshape
    out, _ = core.ops.reshape2(x, None, 'shape', shape)
RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1, 10] now
  [Hint: Expected numel() >= 0, but received numel():-10 < 0:0.] (at /paddle/paddle/fluid/framework/tensor.cc:59)
  [operator < reshape2 > error]
```

**Comment by GuoQuanhao** [comment]
`dist.init_parallel_env()`位置没放对，显存在一张卡的问题解决了，但是RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1, 10] now还是没解决

**Comment by iclementine** [comment]
谢谢反馈。看起来的原因是形状中的 -1 处理发生了错误。
但是我单独测试 reshape 的时候并未能够复现这个问题。

<img width="784" alt="图片" src="https://user-images.githubusercontent.com/16222986/129511321-0b96479f-0af7-447c-8784-780485fc11a2.png">

有可能是其他的原因导致的。你可以试试把 reshape 前的形状也打印出来，看看出现这个问题的时候，是否 reshape 之前的形状就有什么问题呢?

**Comment by GuoQuanhao** [comment]
找到问题了，我的tensor存在空值，因此出现了此问题
