### ISSUE TITLE
使用cascade_rcnn模型预测同一环境的图片，有时正常有时报错，elementwise_div参数不匹配

### ISSUE THREAD

**Issue by liuhuaguang** [PaddlePaddle/Paddle#34852]
1）PaddlePaddle版本：2.1
    2）GPU：1080 ti， cuda 10.2，cudnn 7.6.5
    3）系统环境：Windows 10 专业版19042.1165， python 3.9
    我使用PaddleDetection中的cascade_rcnn训练了一个模型，数据集的数量在400张，数据集的类型为coco，预测好并导出到本地后，通过“python D:\PaddleDetection\deploy\python\infer.py --model_dir=D:\PaddleDetection\inference_model\cascade_rcnn_r50_fpn_1x_coco --image_file=D:\PaddleDetection\demo\4.png --use_gpu=True”（其中，D:\PaddleDetection为我存PaddleDetection的路径），发现预测时大部分图片都是可以正常执行的，但少数图片会出现报错，所有的图片都是在同一个环境下拍的，可以保证各属性应该是相同的，报错信息如下：
Traceback (most recent call last):
  File "D:\PaddleDetection\deploy\python\infer.py", line 622, in <module>
    main()
  File "D:\PaddleDetection\deploy\python\infer.py", line 590, in main
    predict_image(detector, img_list, FLAGS.batch_size)
  File "D:\PaddleDetection\deploy\python\infer.py", line 502, in predict_image
    results = detector.predict(batch_image_list, FLAGS.threshold)
  File "D:\PaddleDetection\deploy\python\infer.py", line 151, in predict
    self.predictor.run()
RuntimeError: In user code:

    File "D:\PaddleDetection\tools\export_model.py", line 108, in <module>
      main()
    File "D:\PaddleDetection\tools\export_model.py", line 104, in main
      run(FLAGS, cfg)
    File "D:\PaddleDetection\tools\export_model.py", line 72, in run
      trainer.export(FLAGS.output_dir)
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\ppdet\engine\trainer.py", line 507, in export
      input_spec, static_model.forward.main_program,
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 487, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 698, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "<decorator-gen-65>", line 2, in from_func_spec

    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "C:\Users\HUAOPT\AppData\Local\Temp\tmpkmolxce2.py", line 26, in forward
      out = paddle.jit.dy2static.convert_ifelse(self.training, true_fn_1,
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\ppdet\modeling\architectures\meta_arch.py", line 29, in forward
      out = self.get_pred()
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\ppdet\modeling\architectures\cascade_rcnn.py", line 136, in get_pred
      bbox_pred, bbox_num, mask_pred = self._forward()
    File "C:\Users\HUAOPT\AppData\Local\Temp\tmpwh1cqohe.py", line 112, in _forward
      __return_value_0, rois, rois_num = paddle.jit.dy2static.convert_ifelse(self
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\ppdet\modeling\architectures\cascade_rcnn.py", line 114, in _forward
      bbox_pred = self.bbox_post_process.get_pred(bbox, bbox_num,
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\ppdet\modeling\post_process.py", line 120, in get_pred
      scaled_bbox = pred_bbox / scale_factor_list
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\layers\math_op_patch.py", line 300, in __impl__
      current_block(self).append_op(
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\framework.py", line 2899, in append_op
      op = Operator(
    File "C:\Users\HUAOPT\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\framework.py", line 1977, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1, 4] now
      [Hint: Expected numel() >= 0, but received numel():-4 < 0:0.] (at C:\home\workspace\Paddle_release4\paddle\fluid\framework\tensor.cc:59)
      [operator < elementwise_div > error]

**Comment by iclementine** [comment]
这个看起来是形状推导发生了错误。

更详细的信息，可以到 paddledetection 的 repo 里提个 issue.
https://github.com/PaddlePaddle/PaddleDetection

**Comment by liuhuaguang** [comment]
好的，多谢
