### ISSUE TITLE
【论文复现】在稳定训练中，显存逐渐占满

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#34885]
platform: AIStudio
version:2.1.2
在稳定训练中，显存占用如下
```
Every 1.0s: nvidia-smi                                                                                                                                 Fri Aug 13 13:58:54 2021

Fri Aug 13 13:58:54 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
| N/A   60C    P0   250W / 300W |  19069MiB / 32480MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
但是随着训练的推进，显存占用会缓慢增长，这导致训练几十个epoch之后，显存爆炸。如果有必要可以邮件提供我的aistudio地址

**Comment by TCChenlong** [comment]
可以提供下复现代么？初步判断可能是需要加 `no_grad`

**Comment by zhiqiu** [comment]
hi，看了下你在aistudio的code。显存泄漏的原因是，你在使用dataloader的时候，没有直接for循环迭代，而是用了iter()和next()；并且，下一个epoch你会创建一个新的dataloader，这样的话，上一个dataloader并不会自动停止，那么它占用的显存也不会释放。
修改方法：需要手动stop一下。具体可以参考如下改动：
![image](https://user-images.githubusercontent.com/6888866/130038749-26f440a4-48cb-4fbe-8b24-529422af4df7.png)

**另外，我们建议对于dataloader还是直接用for循环迭代，不要手动iter()和next()。**

**Comment by GuoQuanhao** [comment]
我将试试这种方案，这应该时train.py中的代码，我之前已经排查这种iter会报错，所以我在ttrain.py更新的数据读取方式。但仍然出现这个显存堆积

**Comment by GuoQuanhao** [comment]
仍然出现显存缓慢增长的情况，这个现象有时后在一个epoch内出现，有时需要几个epoch才出现

**Comment by GuoQuanhao** [comment]
![image](https://user-images.githubusercontent.com/49911294/130169845-3b02ee17-07fe-4785-900b-e44fb6e140e3.png)
我发现我在multibox_loss.py文件中使用print(conf_t.max())会出现cuda错误

**Comment by GuoQuanhao** [comment]
```
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    train()
  File "train.py", line 114, in train
    loss_l, loss_c, loss_landm = criterion(out, priors, [anno for anno in labels])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/Retinaface/layers/modules/multibox_loss.py", line 65, in forward
    print(conf_t.max())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 473, in __str__
    return to_string(self)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/to_string.py", line 205, in to_string
    np_var = var.numpy()
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)
```

**Comment by GuoQuanhao** [comment]
问题已解决，我将新开一个issue，更详述整个解决方案
