### ISSUE TITLE
cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. 

### ISSUE THREAD

**Issue by bhchiang** [PaddlePaddle/Paddle#35008]
Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in Github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is an installation issue including the following details:
**System information**
-PaddlePaddle version（eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: RTX 3090 CUDA 11.4
-OS Platform (eg. Mac OS 10.14)  Ubuntu 20.04
-Python version: Python 3.8.5
- Install method: pip install paddlepaddle-gpu
- Other special cases that you think may be related to this problem, eg. offline install, special internet condition 
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py).   

**To Reproduce**
I'm running this file (https://github.com/wzmsltw/PaintTransformer/blob/main/inference/inference.py).

**Describe your current behavior**
Running into this error:
```
W0818 20:19:31.132983 607266 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W0818 20:19:31.135051 607266 device_context.cc:372] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "inference.py", line 65, in <module>
    main(input_path='input/chicago.jpg',
  File "inference.py", line 33, in main
    net_g = network.Painter(5, stroke_num, 256, 8, 3, 3)
  File "/home/bryan/work/PaintTransformer/inference/network.py", line 13, in __init__
    nn.Conv2D(3, 32, 3, 1),
  File "/home/bryan/miniconda3/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 626, in __init__
    super(Conv2D, self).__init__(
  File "/home/bryan/miniconda3/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 132, in __init__
    self.weight = self.create_parameter(
  File "/home/bryan/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 407, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/bryan/miniconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 367, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/bryan/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2988, in create_parameter
    initializer(param, self)
  File "/home/bryan/miniconda3/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 353, in __call__
    op = block._prepend_op(
  File "/home/bryan/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3100, in _prepend_op
    _dygraph_tracer().trace_op(type,
  File "/home/bryan/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
SystemError: (Fatal) Operator gaussian_random raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at /paddle/paddle/fluid/imperative/tracer.cc:172)
```
**Code to reproduce the issue**
**Other info / logs**

**Comment by wanghuancoder** [comment]
您能否多提供一些信息，包括Paddle的版本，CUDA版本等

**Comment by SNeugber** [comment]
Same issue, running under:
* OS: Ubuntu 20.04
* GPU: RTX3060
* Paddle: paddlepaddle-gpu==2.1.2

```
launch proc_id:13962 idx:0
2021-08-20 14:44:20.164193: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
W0820 14:44:27.044440 13962 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W0820 14:44:27.058020 13962 device_context.cc:422] device: 0, cuDNN Version: 8.1.
2021-08-20 14:44:35.408394: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11

...

SystemError: (Fatal) Operator gaussian_random raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at /paddle/paddle/fluid/imperative/tracer.cc:192)
```

**Comment by bhchiang** [comment]
> 您能否多提供一些信息，包括Paddle的版本，CUDA版本等

@wanghuancoder 

- Ubuntu 20.04, RTX 3090, CUDA 11.4, Driver 470.42.01, paddlepaddle-gpu==2.1.2, cuDNN 8.2

**Comment by wanghuancoder** [comment]
> > 您能否多提供一些信息，包括Paddle的版本，CUDA版本等
> 
> @wanghuancoder
> 
> * Ubuntu 20.04, RTX 3090, CUDA 11.4, Driver 470.42.01, paddlepaddle-gpu==2.1.2, cuDNN 8.2

你好，Paddle目前只支持到cuda11.2
