### ISSUE TITLE
OSError: (External)  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at /paddle/paddle/fluid/operators/conv_cudnn_op.cu:731)

### ISSUE THREAD

**Issue by CuberrChen** [PaddlePaddle/Paddle#35039]
- 标题：Cudnn error, CUDNN_STATUS_EXECUTION_FAILED 
- 版本、环境信息：
    1）PaddlePaddle版本：PaddlePaddle 2.1.2
    3）GPU：device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 10.1, cuDNN Version: 7.6.
    4）系统环境：ubuntu/python 3.7
- 训练信息
    1）单机单卡
    2）16G
    3）loss.backward()
- 复现信息：AIStduio上训练时，自定义loss backward时报以下错误
- 问题描述：
-   File "train.py", line 189, in <module>
    main(args)
  File "train.py", line 184, in main
    fp16=args.fp16)
  File "/home/aistudio/paddlesegmodel-develop-local/paddleseg/core/train.py", line 188, in train
    loss.backward()
  File "<decorator-gen-122>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 239, in backward
    framework._dygraph_tracer())
OSError: (External)  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at /paddle/paddle/fluid/operators/conv_cudnn_op.cu:731)

terminate called without an active exception

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1629431839 (unix time) try "date -d @1629431839" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800001702) received by PID 5890 (TID 0x7f0b977fe700) from PID 5890 ***]

**Comment by CuberrChen** [comment]
已经解决。是除0错误。十分感谢
