### ISSUE TITLE
【论文复现】显存逐增问题排查与解决方案，共排查出三个bug

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#35043]
platform: AIStudio
Version: 2.1.2

在复现retinaface时出现训练阶段显存逐增问题，这个问题有时在一个epoch内出现，有时需要训练几个epoch才出现。导致最终显存爆炸，参见[这个issue](https://github.com/PaddlePaddle/Paddle/issues/34752)解决方案，我共修改两处

### 第一处
参见[这里](https://github.com/PaddlePaddle/Paddle/issues/34885)和[这里](https://github.com/PaddlePaddle/Paddle/issues/34774)数据读取，`iter`这个bug是坐实了，后来我通过如下代码段
```
class IterationBasedBatchSampler(BatchSampler):
    """
    Wraps a BatchSampler, resampling from it until
    a specified number of iterations have been sampled
    """

    def __init__(self, batch_sampler, num_iterations, start_iter=0):
        self.batch_sampler = batch_sampler
        self.num_iterations = num_iterations
        self.start_iter = start_iter

    def __iter__(self):
        iteration = self.start_iter
        while iteration <= self.num_iterations:
            # if the underlying sampler has a set_epoch method, like
            # DistributedSampler, used for making each process see
            # a different split of the dataset, then set it
            if hasattr(self.batch_sampler.sampler, "set_epoch"):
                self.batch_sampler.sampler.set_epoch(iteration)
            for batch in self.batch_sampler:
                iteration += 1
                if iteration > self.num_iterations:
                    break
                yield batch

    def __len__(self):
        return self.num_iterations
```
自定义了可迭代的数据读取方式，仍存在显存递增，我认为是collate_fn中有tensor的原因(因为之前paddle技术人员建议在传入DataLoader之前尽量全部用numpy)，后面我修改collate_fn，使里面没有任何tensor出现，全是numpy array。但显存bug仍在

### 第二处
在自定义损失函数`multibox_loss`的`forward`阶段，我具有如下代码段，并发现使用`print(conf_t.max())`会报错如下
```python
def forward(self, predictions, priors, targets):
    """Multibox Loss
    Args:
        predictions (tuple): A tuple containing loc preds, conf preds,
        and prior boxes from SSD net.
            conf shape: paddle.shape(batch_size,num_priors,num_classes)
            loc shape: paddle.shape(batch_size,num_priors,4)
            priors shape: paddle.shape(num_priors,4)

        ground_truth (tensor): Ground truth boxes and labels for a batch,
            shape: [batch_size,num_objs,5] (last idx is the label).
    """

    loc_data, conf_data, landm_data = predictions
    priors = priors
    num = loc_data.shape[0]
    num_priors = (priors.shape[0])

    # match priors (default boxes) and ground truth boxes
    loc_t = paddle.randn([num, num_priors, 4])
    landm_t = paddle.randn([num, num_priors, 10])
    conf_t = paddle.zeros([num, num_priors], dtype='int64')
    print(conf_t.max())
```
```
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    train()
  File "train.py", line 114, in train
    loss_l, loss_c, loss_landm = criterion(out, priors, [anno for anno in labels])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/Retinaface/layers/modules/multibox_loss.py", line 65, in forward
    print(conf_t.max())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 473, in __str__
    return to_string(self)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/to_string.py", line 205, in to_string
    np_var = var.numpy()
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)
```
所以我断定是`conf_t `出现问题，当我使用`conf_t = paddle.zeros([num, num_priors], dtype='int32')`而不是`int64`数据类型时，能正常打印输出，但是在执行`F.cross_entropy`需要`int64`类型，因此在`F.cross_entropy`内用了`astype('int64')`回转数据格式，这能正常运行。

我先认为只要是forward内创建`int64`都会造成这个错误（这个想法明显是荒诞的，但我还是尝试了一下），我使用如下代码
```python
import paddle
import paddle.nn.functional as F
class LeNet(paddle.nn.Layer):
    def __init__(self):
        super(LeNet, self).__init__()
        self.conv1 = paddle.nn.Conv2D(in_channels=1, out_channels=6, kernel_size=5, stride=1, padding=2)
        self.max_pool1 = paddle.nn.MaxPool2D(kernel_size=2,  stride=2)
        self.conv2 = paddle.nn.Conv2D(in_channels=6, out_channels=16, kernel_size=5, stride=1)
        self.max_pool2 = paddle.nn.MaxPool2D(kernel_size=2, stride=2)
        self.linear1 = paddle.nn.Linear(in_features=16*5*5, out_features=120)
        self.linear2 = paddle.nn.Linear(in_features=120, out_features=84)
        self.linear3 = paddle.nn.Linear(in_features=84, out_features=10)

    def forward(self, x):
        conf_t = paddle.zeros([5, 5], dtype='int64')
        print(conf_t.max())
        x = self.conv1(x)
        x = F.relu(x)
        x = self.max_pool1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = self.max_pool2(x)
        x = paddle.flatten(x, start_axis=1,stop_axis=-1)
        x = self.linear1(x)
        x = F.relu(x)
        x = self.linear2(x)
        x = F.relu(x)
        x = self.linear3(x)
        return x

from paddle.vision.transforms import Compose, Normalize

transform = Compose([Normalize(mean=[127.5],
                               std=[127.5],
                               data_format='CHW')])
# 使用transform对数据集做归一化
print('download training data and load training data')
train_dataset = paddle.vision.datasets.MNIST(mode='train', transform=transform)
test_dataset = paddle.vision.datasets.MNIST(mode='test', transform=transform)
print('load finished')

import paddle.nn.functional as F
train_loader = paddle.io.DataLoader(train_dataset, batch_size=64, shuffle=True)
# 加载训练集 batch_size 设为 64
def train(model):
    model.train()
    epochs = 2
    optim = paddle.optimizer.Adam(learning_rate=0.001, parameters=model.parameters())
    # 用Adam作为优化函数
    for epoch in range(epochs):
        for batch_id, data in enumerate(train_loader()):
            x_data = data[0]
            y_data = data[1]
            predicts = model(x_data)
            loss = F.cross_entropy(predicts, y_data)
            # 计算损失
            acc = paddle.metric.accuracy(predicts, y_data)
            loss.backward()
            if batch_id % 300 == 0:
                print("epoch: {}, batch_id: {}, loss is: {}, acc is: {}".format(epoch, batch_id, loss.numpy(), acc.numpy()))
            optim.step()
            optim.clear_grad()
model = LeNet()
train(model)

```
```
该条输出内容超过1000行，保存时将被截断
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [0])
epoch: 0, batch_id: 0, loss is: [2.7694225], acc is: [0.171875]
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [0])
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [0])
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [0])
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [0])
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [0])
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [0])
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [0])
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [0])
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [0])
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [0])
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
```
这能正常输出。至此，我认为可能在自定义Loss函数(通过nn.Layer)时，forward内使用`int64`会报错

### 第三处
第三处bug类型是paddle的bool切片，如下所示

直接bool切片，现有的paddle是不支持的
```python
import paddle
A = paddle.zeros([3, 12], dtype='int64')
B = paddle.randn([3, 12]) > 0
print(A, '\n', B)
A[B]
```
```
Tensor(shape=[3, 12], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]) 
 Tensor(shape=[3, 12], dtype=bool, place=CUDAPlace(0), stop_gradient=True,
       [[True , False, False, False, False, True , False, False, False, True , True , True ],
        [True , True , True , False, True , True , True , False, True , False, False, False],
        [True , True , False, True , True , False, True , True , True , True , False, False]])
---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)<ipython-input-9-67735a2f8efc> in <module>
      3 B = paddle.randn([3, 12]) > 0
      4 print(A, '\n', B)
----> 5 A[B]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py in __getitem__(self, item)
    563             # 1. Call _getitem_impl_ when item contains tensor.
    564             # Why not call a c++ function ? Because item can't be parsed when it contains tensor.
--> 565             return _getitem_impl_(self, item)
    566 
    567         else:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/variable_index.py in _getitem_impl_(var, item)
    180 
    181             from ..tensor import index_select
--> 182             return index_select(var, index=slice_item, axis=0)
    183 
    184         else:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/search.py in index_select(x, index, axis, name)
    303 
    304     if in_dygraph_mode():
--> 305         return core.ops.index_select(x, index, 'dim', axis)
    306 
    307     helper = LayerHelper("index_select", **locals())
ValueError: (InvalidArgument) The 'shape' of Input(Index) must be 1-D tensor. But received: the 'shape' of Input(Index) is [3, 12], the dimension of Input(Index) is [2].
  [Hint: Expected index_dim.size() == 1 || (index_dim.size() == 2 && index_dim[1] == 1) == true, but received index_dim.size() == 1 || (index_dim.size() == 2 && index_dim[1] == 1):0 != true:1.] (at /paddle/paddle/fluid/operators/index_select_op.cc:55)
  [operator < index_select > error]
```
但是同时赋值是可行的
```python
import paddle
A = paddle.zeros([3, 12], dtype='int64')
B = paddle.randn([3, 12]) > 0
print(A, '\n', B)
A[B] = 1
print(A)
```
```
Tensor(shape=[3, 12], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]) 
 Tensor(shape=[3, 12], dtype=bool, place=CUDAPlace(0), stop_gradient=True,
       [[False, True , False, False, True , True , True , False, False, False, True , False],
        [False, False, False, True , True , True , True , False, False, True , True , False],
        [False, False, True , True , False, False, False, False, True , True , True , False]])
Tensor(shape=[3, 12], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [[0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0],
        [0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0],
        [0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0]])
```
我的代码中有两处用到了这种操作，我均用矩阵运算的方式进行替换，这个bug与[这个issue](https://github.com/PaddlePaddle/Paddle/issues/34752)应是同一类型。通过几小时的训练，利用`watch -n 1 nvidia-smi`进行监视，显存占用稳定不变，训练正常
```
Every 1.0s: nvidia-smi                                                                                                                                 Fri Aug 20 13:13:43 2021

Fri Aug 20 13:13:43 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:0C.0 Off |                    0 |
| N/A   52C    P0    71W / 300W |  18925MiB / 32480MiB |     68%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
```


至此，一共发现了三个存在的bug，一个是iter操作会导致显存叠加，这在torch中不会出现此问题；第二是自定义Loss函数forward中`int64`问题（未采用其他方式复现）；第三是bool切片赋值导致左值问题。比赛结束后会公开源码

**Comment by TeslaZhao** [comment]
您好，感谢您指出Bug。第①、③问题我们会内部讨论；第②个问题需要有复现code，再分析C++栈。
