### ISSUE TITLE
2.1.2单机多卡报错paddle.distributed.launch

### ISSUE THREAD

**Issue by johnyanccer** [PaddlePaddle/Paddle#35054]
paddle.__version__ 2.1.2
paddle.__git_commit__  e04b66f2d272d68f77dcd94cb2956938475411d8
项目地址：https://aistudio.baidu.com/aistudio/projectdetail/1222066
运行代码：
%%writefile hapitrain.py 
import warnings
warnings.filterwarnings("ignore")
import paddle 
from paddle.vision.transforms import ToTensor

train_dataset = paddle.vision.datasets.MNIST(mode='train', transform=ToTensor())
test_dataset = paddle.vision.datasets.MNIST(mode='test', transform=ToTensor())
lenet = paddle.vision.models.LeNet()
model = paddle.Model(lenet)
model.prepare(
    paddle.optimizer.Adam(learning_rate=0.001, parameters=model.parameters()),
    paddle.nn.CrossEntropyLoss(),
    paddle.metric.Accuracy(topk=(1, 2))
    )
model.fit(train_dataset, epochs=1, batch_size=64, log_freq=400)
model.evaluate(test_dataset, log_freq=100, batch_size=64)

#单机单卡正常运行，加入python -m paddle.distributed.launch 之后中止报错：
W0823 10:09:43.540493  2451 gen_comm_id_helper.cc:120] connect addr=127.0.0.1:47731 failed 1 times with reason: Connection refused retry after 0.5 seconds
W0823 10:09:44.041168  2451 gen_comm_id_helper.cc:120] connect addr=127.0.0.1:47731 failed 2 times with reason: Connection refused retry after 1 seconds
INFO 2021-08-23 10:09:47,950 launch_utils.py:327] terminate all the procs
ERROR 2021-08-23 10:09:47,951 launch_utils.py:582] ABORT!!! Out of all 2 trainers, the trainer process with rank=[1] was aborted. Please check its log.
INFO 2021-08-23 10:09:50,954 launch_utils.py:327] terminate all the procs

以下是log信息
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1629547344 (unix time) try "date -d @1629547344" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e8000009e3) received by PID 2604 (TID 0x7f9673bb8340) from PID 2531 ***]

W0823 10:09:42.278770  2451 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0823 10:09:42.280050  2451 device_context.cc:422] device: 0, cuDNN Version: 8.1.
W0823 10:09:43.540493  2451 gen_comm_id_helper.cc:120] connect addr=127.0.0.1:47731 failed 1 times with reason: Connection refused retry after 0.5 seconds
W0823 10:09:44.041168  2451 gen_comm_id_helper.cc:120] connect addr=127.0.0.1:47731 failed 2 times with reason: Connection refused retry after 1 seconds

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::NCCLParallelContext::Init()
1   paddle::imperative::NCCLParallelContext::BcastNCCLId(std::vector<ncclUniqueId, std::allocator<ncclUniqueId> >&, int, int)
2   void paddle::platform::SendBroadCastCommID<ncclUniqueId>(std::vector<std::string, std::allocator<std::string > >, std::vector<ncclUniqueId, std::allocator<ncclUniqueId> >*)
3   paddle::framework::SignalHandle(char const*, int)
4   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1629684584 (unix time) try "date -d @1629684584" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e80000094a) received by PID 2451 (TID 0x7fdd1b3a9340) from PID 2378 ***]

**Comment by zhwesky2010** [comment]
@johnyanccer 您好，请问这个问题能反复复现吗？

**Comment by johnyanccer** [comment]
> @johnyanccer 您好，请问这个问题能反复复现吗？

我这边一直没成功运行过paddle的单机多卡，不知道还有没有别的示例代码。能正常跑tensorflow的并行代码

**Comment by zhwesky2010** [comment]
@johnyanccer 这个代码是官方提供的还是自己写的呢？

**Comment by johnyanccer** [comment]
> @johnyanccer 这个代码是官方提供的还是自己写的呢？

paddle这边没有提供示例代码，只是写了“当调用paddle.Model高层API来实现训练时，想要启动单机多卡训练非常简单，代码不需要做任何修改，只需要在启动时增加一下参数-m paddle.distributed.launch。

# 单机单卡启动，默认使用第0号卡
$ python train.py

# 单机多卡启动，默认使用当前可见的所有卡
$ python -m paddle.distributed.launch train.py

# 单机多卡启动，设置当前使用的第0号和第1号卡
$ python -m paddle.distributed.launch --gpus='0,1' train.py

# 单机多卡启动，设置当前使用第0号和第1号卡
$ export CUDA_VISIBLE_DEVICES=0,1
$ python -m paddle.distributed.launch train.py

**Comment by zhwesky2010** [comment]
@johnyanccer 1号卡挂了，得检查一下一号卡的log  
<img width="825" alt="9963f253f137f00625fd085ccd8674b8" src="https://user-images.githubusercontent.com/52485244/130423589-0a32bc8c-2123-43af-81fe-13d41893de73.png">
麻烦看下 log/workerlog.1。另外好像没有看到初始化多卡环境的代码

**Comment by johnyanccer** [comment]
[2021-08-21 19:29:52,708] [    INFO] - Found /home/johnyan/.paddlenlp/models/ernie-gram-zh/vocab.txt
[2021-08-21 19:29:52,714] [    INFO] - Already cached /home/johnyan/.paddlenlp/models/ernie-gram-zh/ernie_gram_zh.pdparams
Traceback (most recent call last):
  File "class2.py", line 116, in <module>
    pretrained_model = paddlenlp.transformers.ErnieGramModel.from_pretrained('ernie-gram-zh')
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 274, in from_pretrained
    model = cls(*base_args, **base_kwargs)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 83, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/ernie_gram/modeling.py", line 201, in __init__
    self.embeddings = ErnieGramEmbeddings(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/ernie_gram/modeling.py", line 45, in __init__
    self.word_embeddings = nn.Embedding(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 1343, in __init__
    self.weight = self.create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 561, in __call__
    op = block.append_op(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2921, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)
  [operator < uniform_random > error]
[2021-08-21 20:02:23,016] [    INFO] - Found /home/johnyan/.paddlenlp/models/ernie-gram-zh/vocab.txt
[2021-08-21 20:02:23,022] [    INFO] - Already cached /home/johnyan/.paddlenlp/models/ernie-gram-zh/ernie_gram_zh.pdparams
Traceback (most recent call last):
  File "class2.py", line 117, in <module>
    pretrained_model = paddlenlp.transformers.ErnieGramModel.from_pretrained('ernie-gram-zh')
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 274, in from_pretrained
    model = cls(*base_args, **base_kwargs)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 83, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/ernie_gram/modeling.py", line 201, in __init__
    self.embeddings = ErnieGramEmbeddings(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/ernie_gram/modeling.py", line 45, in __init__
    self.word_embeddings = nn.Embedding(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 1343, in __init__
    self.weight = self.create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 561, in __call__
    op = block.append_op(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2921, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)
  [operator < uniform_random > error]
Traceback (most recent call last):
  File "class2-1.py", line 6, in <module>
    lenet = paddle.vision.models.LeNet()
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/vision/models/lenet.py", line 41, in __init__
    nn.Conv2D(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 633, in __init__
    super(Conv2D, self).__init__(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 132, in __init__
    self.weight = self.create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 355, in __call__
    op = block.append_op(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2921, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)
  [operator < gaussian_random > error]
Traceback (most recent call last):
  File "class2-1.py", line 6, in <module>
    lenet = paddle.vision.models.LeNet()
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/vision/models/lenet.py", line 41, in __init__
    nn.Conv2D(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 633, in __init__
    super(Conv2D, self).__init__(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 132, in __init__
    self.weight = self.create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 355, in __call__
    op = block.append_op(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2921, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)
  [operator < gaussian_random > error]

**Comment by johnyanccer** [comment]
[2021-08-21 19:29:52,708] [    INFO] - Found /home/johnyan/.paddlenlp/models/ernie-gram-zh/vocab.txt
[2021-08-21 19:29:52,714] [    INFO] - Already cached /home/johnyan/.paddlenlp/models/ernie-gram-zh/ernie_gram_zh.pdparams
Traceback (most recent call last):
  File "class2.py", line 116, in <module>
    pretrained_model = paddlenlp.transformers.ErnieGramModel.from_pretrained('ernie-gram-zh')
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 274, in from_pretrained
    model = cls(*base_args, **base_kwargs)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 83, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/ernie_gram/modeling.py", line 201, in __init__
    self.embeddings = ErnieGramEmbeddings(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/ernie_gram/modeling.py", line 45, in __init__
    self.word_embeddings = nn.Embedding(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 1343, in __init__
    self.weight = self.create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 561, in __call__
    op = block.append_op(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2921, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)
  [operator < uniform_random > error]
[2021-08-21 20:02:23,016] [    INFO] - Found /home/johnyan/.paddlenlp/models/ernie-gram-zh/vocab.txt
[2021-08-21 20:02:23,022] [    INFO] - Already cached /home/johnyan/.paddlenlp/models/ernie-gram-zh/ernie_gram_zh.pdparams
Traceback (most recent call last):
  File "class2.py", line 117, in <module>
    pretrained_model = paddlenlp.transformers.ErnieGramModel.from_pretrained('ernie-gram-zh')
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 274, in from_pretrained
    model = cls(*base_args, **base_kwargs)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/utils.py", line 83, in __impl__
    init_func(self, *args, **kwargs)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/ernie_gram/modeling.py", line 201, in __init__
    self.embeddings = ErnieGramEmbeddings(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddlenlp/transformers/ernie_gram/modeling.py", line 45, in __init__
    self.word_embeddings = nn.Embedding(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 1343, in __init__
    self.weight = self.create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 561, in __call__
    op = block.append_op(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2921, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)
  [operator < uniform_random > error]
Traceback (most recent call last):
  File "class2-1.py", line 6, in <module>
    lenet = paddle.vision.models.LeNet()
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/vision/models/lenet.py", line 41, in __init__
    nn.Conv2D(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 633, in __init__
    super(Conv2D, self).__init__(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 132, in __init__
    self.weight = self.create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 355, in __call__
    op = block.append_op(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2921, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)
  [operator < gaussian_random > error]
Traceback (most recent call last):
  File "class2-1.py", line 6, in <module>
    lenet = paddle.vision.models.LeNet()
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/vision/models/lenet.py", line 41, in __init__
    nn.Conv2D(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 633, in __init__
    super(Conv2D, self).__init__(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 132, in __init__
    self.weight = self.create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 411, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 369, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 355, in __call__
    op = block.append_op(
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2921, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/johnyan/anaconda3/envs/rtx_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)
  [operator < gaussian_random > error]

**Comment by johnyanccer** [comment]
> @johnyanccer 1号卡挂了，得检查一下一号卡的log
> <img alt="9963f253f137f00625fd085ccd8674b8" width="825" src="https://user-images.githubusercontent.com/52485244/130423589-0a32bc8c-2123-43af-81fe-13d41893de73.png">
> 麻烦看下 log/workerlog.1。另外好像没有看到初始化多卡环境的代码

workerlog.1提示paddle版本问题。。之前在代码段里直接指定使用GPU0或者GPU1就能正常跑单卡，跑多卡就报错，

**Comment by zhwesky2010** [comment]
@johnyanccer 您好，请问是否使用的同一个Python，现在的问题就是装的Paddle不支持CUDA

**Comment by johnyanccer** [comment]
> @johnyanccer 您好，请问是否使用的同一个Python，现在的问题就是装的Paddle不支持CUDA

python hapitrain.py 是正常支持CUDA的
python -m paddle.distributed.launch hapitrain.py 就报错不支持了

**Comment by gentelyang** [comment]
试了一下，设置一下device就可以了 paddle.device.set_device("gpu")

**Comment by johnyanccer** [comment]
> 试了一下，设置一下device就可以了 paddle.device.set_device("gpu")
修改后同样报错
2329 gen_comm_id_helper.cc:120] connect addr=127.0.0.1:43135 failed 1 times with reason: Connection refused retry after 0.5 seconds
并且怀疑仍然只在一个GPU上跑的

**Comment by gentelyang** [comment]
首先unset 一下cuda_visible_devices ，然后paddle.distribtuted.launch --gpus 0,1 train.py

**Comment by johnyanccer** [comment]
> 首先unset 一下cuda_visible_devices ，然后paddle.distribtuted.launch --gpus 0,1 train.py

代码加入paddle.device.set_device("gpu")，再运行paddle.distribtuted.launch --gpus 0,1 train.py，目前没有报错了，两个GPU都有显存占用，batch数减半，应该运行成功了，十分感谢！！

**Comment by Guangjun-A** [comment]
paddle.device.set_device("gpu") 正解！！！
