### ISSUE TITLE
nuitka 打包报错

### ISSUE THREAD

**Issue by sticktoFE** [PaddlePaddle/Paddle#35058]
使用最新版 paddlepaddle 2.1.2 在使用 nuitka打包后，需要把paddle拷到程序目录，但运行时
File "D:\rpa\rpa.dist\tools\infer\predict_system.py", line 30, in <module>
    import tools.infer.utility as utility
  File "D:\rpa\rpa.dist\tools\infer\utility.py", line 23, in <module>
    from paddle import inference
  File "D:\rpa\rpa.dist\paddle\__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "D:\rpa\rpa.dist\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "D:\rpa\rpa.dist\paddle\fluid\framework.py", line 37, in <module>
    from . import core
  File "D:\rpa\rpa.dist\paddle\fluid\core.py", line 381, in <module>
    set_paddle_lib_path()
  File "D:\rpa\rpa.dist\paddle\fluid\core.py", line 376, in set_paddle_lib_path
    lib_dir = os.path.sep.join([site.USER_SITE, 'paddle', 'libs'])
TypeError: sequence item 0: expected str instance, NoneType found

**Comment by zhwesky2010** [comment]
@sticktoFE 您好，麻烦跑下 ``import site; site. USER_SITE `` 是否是None，看起来是挂在这个地方了

**Comment by monkeycc** [comment]
paddlepaddle-gpu==2.3.2

nuitka 打包报错
我也遇到这个问题
lib_dir = os.path.sep.join([site.USER_SITE, 'paddle', 'libs'])
TypeError: sequence item 0: expected str instance, NoneType found

site.USER_SITE
这个地方改为paddle的目录才可以
@zhouwei25

**Comment by aceyw** [comment]
@monkeycc 您好
我也遇到了这个问题，
paddle的安装路径、打包后的运行路径是不一样的，exe打包后在win10上的运行时路径也是随机的，
请问，paddle的目录是哪个、你是怎么写的呢
谢谢~

**Comment by monkeycc** [comment]
所有第三方模块放 根目录
不要编译
特别是paddle

paddle哪里报错就注释哪里
注释一堆之后
正常 

反正就是一堆坑 @aceyw

**Comment by vision1v1** [comment]
我也遇见了相同错误：报错如下
`Traceback (most recent call last):
  File "/tmp/onefile_3440012_1702381817_524957/http_server.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/onefile_3440012_1702381817_524957/paddleocr/__init__.py", line 14, in <module paddleocr>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/onefile_3440012_1702381817_524957/paddleocr/paddleocr.py", line 21, in <module paddleocr.paddleocr>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/onefile_3440012_1702381817_524957/paddle/__init__.py", line 31, in <module paddle>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/onefile_3440012_1702381817_524957/paddle/framework/__init__.py", line 17, in <module paddle.framework>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/onefile_3440012_1702381817_524957/paddle/framework/random.py", line 17, in <module paddle.framework.random>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/onefile_3440012_1702381817_524957/paddle/fluid/__init__.py", line 36, in <module paddle.fluid>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/onefile_3440012_1702381817_524957/paddle/fluid/framework.py", line 35, in <module paddle.fluid.framework>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/tmp/onefile_3440012_1702381817_524957/paddle/fluid/core.py", line 394, in <module paddle.fluid.core>
  File "/tmp/onefile_3440012_1702381817_524957/paddle/fluid/core.py", line 386, in set_paddle_lib_path
TypeError: sequence item 0: expected str instance, NoneType found`

**Comment by Suvoo** [comment]
> 使用最新版 paddlepaddle 2.1.2 在使用 nuitka打包后，需要把paddle拷到程序目录，但运行时 File "D:\rpa\rpa.dist\tools\infer\predict_system.py", line 30, in import tools.infer.utility as utility File "D:\rpa\rpa.dist\tools\infer\utility.py", line 23, in from paddle import inference File "D:\rpa\rpa.dist\paddle__init__.py", line 25, in from .fluid import monkey_patch_variable File "D:\rpa\rpa.dist\paddle\fluid__init__.py", line 36, in from . import framework File "D:\rpa\rpa.dist\paddle\fluid\framework.py", line 37, in from . import core File "D:\rpa\rpa.dist\paddle\fluid\core.py", line 381, in set_paddle_lib_path() File "D:\rpa\rpa.dist\paddle\fluid\core.py", line 376, in set_paddle_lib_path lib_dir = os.path.sep.join([site.USER_SITE, 'paddle', 'libs']) TypeError: sequence item 0: expected str instance, NoneType found

https://github.com/PaddlePaddle/Paddle/issues/62128
