### ISSUE TITLE
window2008 服务器安装报错

### ISSUE THREAD

**Issue by songsh** [PaddlePaddle/Paddle#35136]
- 安装方式信息：
1）pip安装/docker安装

**System information**
-PaddlePaddle version   2.0.2
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform  window 2008 server
-Python version:2.7

Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\_internal\cli\base_command.py", line 1
78, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\_internal\commands\install.py", line 4
58, in run
    wheel_cache.cleanup()
  File "c:\python27\lib\site-packages\pip\_internal\utils\temp_dir.py", line 60,
 in __exit__
    self.cleanup()
  File "c:\python27\lib\site-packages\pip\_internal\utils\temp_dir.py", line 83,
 in cleanup
    rmtree(self.path)
  File "c:\python27\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrap
ped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\python27\lib\site-packages\pip\_vendor\retrying.py", line 212, in cal

**Comment by qili93** [comment]
@songsh 请问是根据这个文档按步骤安装的吗？

https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/install/pip/windows-pip.html

能给一下完整的错误LOG不，从pip isntall开始的。谢谢！
