### ISSUE TITLE
book 08.machine_translation 运行失败：TypeError: __init__() got an unexpected keyword argument 'error_clipping_threshold'

### ISSUE THREAD

**Issue by zongming256** [PaddlePaddle/Paddle#3517]
错误信息如下：
```text
Traceback (most recent call last):
  File "train.py", line 234, in <module>
    main()
  File "train.py", line 152, in main
    cost = seq_to_seq_net(source_dict_dim, target_dict_dim, is_generating)
  File "train.py", line 102, in seq_to_seq_net
    input=group_inputs)
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 3475, in recurrent_group
    layer_outs = step(*in_args)
  File "train.py", line 65, in gru_decoder_with_attention
    error_clipping_threshold=100.0))
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 350, in wrapper
    return method(*args, **kwargs)
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 961, in fc_layer
    **ExtraLayerAttribute.to_kwargs(layer_attr))
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3136, in Layer
    return layer_func(name, **xargs)
  File "/home/img/zongming/paddle_env2/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 1575, in __init__
    super(FCLayer, self).__init__(name, 'fc', size, inputs=inputs, **xargs)
TypeError: __init__() got an unexpected keyword argument 'error_clipping_threshold'
```

**Comment by zongming256** [comment]
补充下：
paddle环境是用内网的一键安装：

curl -s http://gitlab.baidu.com/yuyang18/PaddleInstall/raw/master/install_paddle.sh \| bash -s GPU .
--

**Comment by hedaoyuan** [comment]
@zongming256 估计是paddle版本的问题。develop分支下的paddle编译出来应该是没有问题的。

**Comment by jzh1992** [comment]
确实是版本问题，集群上的paddle版本如何手动更新或者手动指定python啊
