### ISSUE TITLE
【论文复现】训练一定轮次后出现错误 Cuda error(719), unspecified launch failure.

### ISSUE THREAD

**Issue by thunder95** [PaddlePaddle/Paddle#35188]
在aistudio的脚本任务上基于PaddleDetection套件进行多卡训练，训练到epoch序号接近6时， 出现下面的cuda错误，请帮忙分析下问题 可能出在哪里？

```
expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
INFO 2021-08-27 03:39:38,961 launch_utils.py:327] terminate all the procs
ERROR 2021-08-27 03:39:38,961 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 3] was aborted. Please check its log.
INFO 2021-08-27 03:39:41,964 launch_utils.py:327] terminate all the procs
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
```

```
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "/root/paddlejob/workspace/code/ppdet/engine/trainer.py", line 335, in train
    outputs = model(data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 578, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/meta_arch.py", line 26, in forward
    out = self.get_loss()
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox.py", line 86, in get_loss
    return self._forward()
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox.py", line 52, in _forward
    fpn_outs, targets, input_img
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox_utils/yolo_head.py", line 171, in forward
    dtype=xin[0].dtype,
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox_utils/yolo_head.py", line 334, in get_losses
    imgs,
  File "<decorator-gen-278>", line 2, in get_assignments
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox_utils/yolo_head.py", line 567, in get_assignments
    ) = self.dynamic_k_matching(cost, pair_wise_ious, gt_classes, num_gt, fg_mask)
  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox_utils/yolo_head.py", line 688, in dynamic_k_matching
    cost[gt_idx], k=dynamic_ks[gt_idx].item(), largest=False
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 432, in item
    return self._getitem_from_offset(*args).item()
OSError: (External)  Cuda error(719), unspecified launch failure.
  [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)
```

中途打印了很多bce的error，各个worker.log也几乎同一时间出现bce错误， 然后中途多卡训练时就abort了。  不清楚这个错误来自nn.BCEWithLogitsLoss，还是来自代码实现逻辑出现的问题， 请各位专家能给一些提示和建议。

**Comment by jerrywgz** [comment]
实际上是bce的输入值为nan了，在bce里会对输入检查所以报错，应该还是和模型训练训飞有关，可以打印下bce之前的输入

**Comment by thunder95** [comment]
> 实际上是bce的输入值为nan了，在bce里会对输入检查所以报错，应该还是和模型训练训飞有关，可以打印下bce之前的输入

@jerrywgz 
我也想过打印以下， 这个打印可能有点多， 主要是不确定什么时候会出现， 我也是训练了很多时间才出现这个，而且里面有两处用到了bce loss。 有什么好的打印策略吗， cuda报错里面直接是assert又不能try catch进行捕获。

**Comment by jerrywgz** [comment]
如果在算子里加debug代码需要自己编译安装paddle，可以试试用export FLAGS_check_nan_inf=1 看看

**Comment by yinhaofeng** [comment]
1.可以添加paddle.seed()来固定随机量，使用确定的初始化方式以及FLAGS_cudnn_deterministic，这样每次训练时从数据到loss和反传都是确定的，方便检测是从哪里开始出现问题

**Comment by yinhaofeng** [comment]
2.检查nan可以使用check nan inf工具：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/flags/check_nan_inf_cn.html#check-nan-inf
或者使用paddle.isnan（）：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.0/api/paddle/tensor/math/isnan_cn.html#fanhui

**Comment by thunder95** [comment]
@jerrywgz @yinhaofeng 谢谢两位专家回复， 按照给的提示，仍旧debug不出来哪里有问题， 也没有任何打印，感觉设置了下面的参数用途不大，只是报错的地方不一样了。要复现这个问题时间也比较长， 4卡大概4小时。我在每个bce_loss前都做了isnan判断，但是没有任何输出。 

```
Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.

Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.

INFO 2021-08-27 14:13:14,007 launch_utils.py:327] terminate all the procs

ERROR 2021-08-27 14:13:14,007 launch_utils.py:584] ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 2, 3] was aborted. Please check its log.

INFO 2021-08-27 14:13:17,011 launch_utils.py:327] terminate all the procs

Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.

Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.

Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.

Error: /paddle/paddle/fluid/operators/bce_loss_op.cu:38 Assertion `(x >= static_cast<T>(0)) && (x <= one)` failed. Input is expected to be within the interval [0, 1], but recieved nan.

Traceback (most recent call last):

  File "tools/train.py", line 140, in <module>

    main()

  File "tools/train.py", line 136, in main

    run(FLAGS, cfg)

  File "tools/train.py", line 110, in run

    trainer.train(FLAGS.eval)

  File "/root/paddlejob/workspace/code/ppdet/engine/trainer.py", line 336, in train

    outputs = model(data)

  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__

    outputs = self.forward(*inputs, **kwargs)

  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 578, in forward

    outputs = self._layers(*inputs, **kwargs)

  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__

    outputs = self.forward(*inputs, **kwargs)

  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/meta_arch.py", line 26, in forward

    out = self.get_loss()

  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox.py", line 86, in get_loss

    return self._forward()

  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox.py", line 52, in _forward

    fpn_outs, targets, input_img

  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__

    outputs = self.forward(*inputs, **kwargs)

  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox_utils/yolo_head.py", line 171, in forward

    dtype=xin[0].dtype,

  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox_utils/yolo_head.py", line 334, in get_losses

    imgs,

  File "<decorator-gen-278>", line 2, in get_assignments

  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 331, in _decorate_function

    return func(*args, **kwargs)

  File "/root/paddlejob/workspace/code/ppdet/modeling/architectures/yolox_utils/yolo_head.py", line 551, in get_assignments

    paddle.ones_like(is_in_boxes_and_center))

  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12257, in logical_xor

    op_name="logical_xor", x=x, y=y, name=name, out=out, binary_op=True)

  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 12118, in _logical_op

    return op(x, y)

SystemError: (Fatal) Operator logical_xor raises an thrust::system::system_error exception.

The exception content is

:transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure. (at /paddle/paddle/fluid/imperative/tracer.cc:192)

```

```

export PYTHONPATH=$PYTHONPATH:./
export FLAGS_cudnn_deterministic=1
export FLAGS_check_nan_inf=1
export CUDA_VISIBLE_DEVICES=0,1,2,3 && python -m paddle.distributed.launch --log_dir /root/paddlejob/workspace/output/ --gpus 0,1,2,3  tools/train.py -c yolox_train.yml --eval

```


```
        if np.isnan(obj_preds.numpy()).any():
            print(obj_preds)
```

```
 if np.isnan(tmp_input.numpy()).any():
            print(tmp_input)
```

**Comment by thunder95** [comment]
有么有可能是其他地方引发了错误，才导致bce_loss的assert失败？

**Comment by thunder95** [comment]
补充: 我将训练过程中**每个批次**bce**所有**的输入保存下来，单独使用BCEWithLogitsLoss运行了一遍，没有任何问题。

**Comment by hlr7999** [comment]
我也遇到了同样的问题，训练PPYOLOE的时候，第一次训练了300轮没报错，之后每次训练到100轮报错，错误信息也是bce non。。。。。

**Comment by ChenjieXu** [comment]
我也遇到了了，5个epoch之后，报错
