### ISSUE TITLE
无法训练

### ISSUE THREAD

**Issue by zmdcs** [PaddlePaddle/Paddle#35721]
就普通训练个yolo3都报错
Traceback (most recent call last):
  File "tools/train.py", line 412, in <module>
    main()
  File "tools/train.py", line 180, in main
    eval_reader = create_reader(cfg.EvalReader, devices_num=1)
  File "/home/aistudio/PaddleDetection/static/ppdet/data/reader.py", line 442, in create_reader
    reader = Reader(**cfg)()
  File "/home/aistudio/PaddleDetection/static/ppdet/data/reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/home/aistudio/PaddleDetection/static/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/home/aistudio/PaddleDetection/static/ppdet/data/source/voc.py", line 154, in load_roidb_and_cname2cid
    gt_class.append([cname2cid[cname]])
KeyError: 'fire'
为什么呢？我按之前的操作一模一样的来的，除了数据集不一样

**Comment by danleifeng** [comment]
看着像是解析数据有问题，请检查下数据格式和数据解析逻辑
