### ISSUE TITLE
ltr/ranknet  demo模型训练报错

### ISSUE THREAD

**Issue by jcqu** [PaddlePaddle/Paddle#3588]
在开发机上尝试使用Paddle v2 中的ranknet模型，运行demo脚本,  按说明执行命令
`bash ./run_ranknet.sh`
运行出错，应该是数据格式不匹配导致的错误。报错信息：
```python
Traceback (most recent call last):
  File "ranknet.py", line 140, in <module>
    train_ranknet(args.num_passes)
  File "ranknet.py", line 92, in train_ranknet
    num_passes=num_passes)
  File "/root/paddle/python27/lib/python2.7/site-packages/paddle/v2/trainer.py", line 153, in train
    in_args = feeder(data_batch)
  File "/root/paddle/python27/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 279, in __call__
    return self.convert(dat, argument)
  File "/root/paddle/python27/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 134, in convert
    return DataProviderConverter.convert(self, reorder_data(dat), argument)
  File "/root/paddle/python27/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 264, in convert
    scanner.pre_scan(each_step)
  File "/root/paddle/python27/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 113, in pre_scan
    self.__dim__ = reduce(lambda x, y: x * y, self.__shape__)
TypeError: reduce() of empty sequence with no initial value
```
查看数据下载目录，正确下载了MQ2007数据集，正确解压。
在本地调试reader函数并未发现明显错误，希望能得到解决，谢谢。

**Comment by luotao1** [comment]
我和 @NHZlX 本地跑，使用最新的develop分支，出现以下问题：
```
Traceback (most recent call last):
  File "ranknet.py", line 143, in <module>
    train_ranknet(args.num_passes)
  File "ranknet.py", line 95, in train_ranknet
    num_passes=num_passes)
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/v2/trainer.py", line 154, in train
    for batch_id, data_batch in enumerate(reader()):
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/v2/minibatch.py", line 33, in batch_reader
    for instance in r:
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 67, in data_reader
    for e in reader():
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/v2/dataset/mq2007.py", line 311, in __reader__
    filepath, shuffle=shuffle, fill_missing=fill_missing))
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/v2/dataset/mq2007.py", line 275, in load_from_text
    fn = __initialize_meta_info__()
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/v2/dataset/mq2007.py", line 45, in __initialize_meta_info__
    rar.extractall(path=dirpath)
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/rarfile.py", line 820, in extractall
    self._extract(fnlist, path, pwd)
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/rarfile.py", line 885, in _extract
    p = custom_popen(cmd)
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/rarfile.py", line 2816, in custom_popen
    raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL)
rarfile.RarCannotExec: Unrar not installed? (rarfile.UNRAR_TOOL='unrar')
```
@dzhwinter 请问数据能弄成tar或者tar.gz格式的么

**Comment by luotao1** [comment]
安装unrar后，可以正常运行。

**Comment by NHZlX** [comment]
确保models 以及paddle代码是否是最新版本

**Comment by jcqu** [comment]
问题初步解决 paddle/v2/dataset/mq2007.py 中处理数据集格式时，label字段并未放入列表，维度检查时不通过导致后续错误。
```python
yield label, pair[0], pair[1]
```
将line 227 的label字段改为[label]即可正常执行。
查看git当前版本：
```python
yield np.array(label), pair[0], pair[1]
```
依然没有修正该问题，可能在其它地方做了数据处理，大家可以注意版本的一致性。
done
