### ISSUE TITLE
 version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#3601]
在开发机环境下，使用`pip install paddlepaddle`后，在python下运行`import py_paddle`出现：
```
>>> import py_paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: /home/luotao02/.jumbo/opt/gcc48/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/luotao02/.jumbo/lib/python2.7/site-packages/py_paddle/_swig_paddle.so)
>>> 
```
使用`strings /home/luotao02/.jumbo/opt/gcc48/lib64/libstdc++.so.6 | grep GLIBC`，出现
```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH
```
没有GLIBC_3.4.20。

但在docker的环境下，一切都正常。应该是提供的paddlepaddle包太新了。

**Comment by typhoonzero** [comment]
目前是在docker环境下编译pypi的whl包的，可能导致依赖版本太高，我用docker里自带的gcc 4.8编译下吧，默认用4.8看起来会适配更多的运行时环境。
