### ISSUE TITLE
单机多卡启动时报错ABORT!!! Out of all 4 trainers, the trainer process with rank=[1, 2, 3] was aborted. Please check its log.

### ISSUE THREAD

**Issue by Beichen-Ma** [PaddlePaddle/Paddle#36104]
这是log：
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    p.apply_async(globals()[Job[config["group"]][0]](config))
  File "/home/mabeichen/MJFL-Simulation/core/Job.py", line 144, in Image_CnnEm
    model = CnnNIID()
  File "/home/mabeichen/MJFL-Simulation/core/model.py", line 120, in __init__
    Conv2D(in_channels=1, out_channels=32, kernel_size=3),
  File "/home/mabeichen/.local/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 646, in __init__
    data_format=data_format)
  File "/home/mabeichen/.local/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "/home/mabeichen/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 412, in cre
ate_parameter
    default_initializer)
  File "/home/mabeichen/.local/lib/python3.6/site-packages/paddle/fluid/layer_helper_base.py", line 374, in 
create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/mabeichen/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2920, in create_
parameter
    initializer(param, self)
  File "/home/mabeichen/.local/lib/python3.6/site-packages/paddle/fluid/initializer.py", line 366, in __call
__
    stop_gradient=True)
  File "/home/mabeichen/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2950, in append_
op
    kwargs.get("stop_gradient", False))
  File "/home/mabeichen/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trac
e_op
    not stop_gradient)
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle comp
iles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct devic
e id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:88)

**Comment by zhwesky2010** [comment]
@bizzzzzy 您好，这个问题是由于你使用的不是CUDA版本的Paddle，麻烦执行下 `paddle.is_compiled_with_cuda` 和 `nvidia-smi` 看看。

**Comment by bizzzzzy** [comment]
@zhouwei25 
![image](https://user-images.githubusercontent.com/90386322/134804878-1d2fe179-93e5-41c5-b097-59580ea4ab56.png)
![image](https://user-images.githubusercontent.com/90386322/134804907-d05417e1-2e0d-4943-90d0-d6db32fde882.png)

**Comment by Beichen-Ma** [comment]
> @bizzzzzy 您好，这个问题是由于你使用的不是CUDA版本的Paddle，麻烦执行下 `paddle.is_compiled_with_cuda` 和 `nvidia-smi` 看看。
![image](https://user-images.githubusercontent.com/90386322/134804939-c6b70a87-856b-4eff-8642-c6c746b14ab1.png)


![image](https://user-images.githubusercontent.com/90386322/134804941-8d83af9f-1bf3-4acc-a11e-a0a2d4a6c1fe.png)

**Comment by Beichen-Ma** [comment]
> @bizzzzzy 您好，这个问题是由于你使用的不是CUDA版本的Paddle，麻烦执行下 `paddle.is_compiled_with_cuda` 和 `nvidia-smi` 看看。

是cuda版本的Paddle应该
单独使用0号卡可以启动 多卡不能启动 单独使用1/2/3号卡也不能启动

**Comment by zhwesky2010** [comment]
@bizzzzzy 跑一下 `paddle.is_compiled_with_cuda()` ，另外这个代码多吗，代码能给我先复现一下吗

**Comment by Beichen-Ma** [comment]
> @bizzzzzy 跑一下 `paddle.is_compiled_with_cuda()` ，另外这个代码多吗，代码能给我先复现一下吗

![image](https://user-images.githubusercontent.com/90386322/134840700-cfd88564-1041-45e1-95f1-cfed564a76cd.png)
还挺多的 可以

**Comment by zhwesky2010** [comment]
@bizzzzzy 代码可以发邮箱 zhouwei25@baidu.com吗，还有复现方式

**Comment by zhwesky2010** [comment]
@bizzzzzy 请问是安装的paddle还是自行编译的paddle呢，什么操作系统

**Comment by Beichen-Ma** [comment]
> @bizzzzzy 请问是安装的paddle还是自行编译的paddle呢，什么操作系统

安装的paddle， Centos7

**Comment by zhwesky2010** [comment]
@bizzzzzy 经排查 用户代码在高层API中未添加 `paddle.set_device('gpu')` ，不加的话 执行器place默认成0号，执行OP时去找0号，但是--selected_gpus='1'初始化时指定只初始化1号，因此会报找不到place 0号的错误。
