### ISSUE TITLE
在使用ProgramTranslator进行动态转静态时OSError: could not get source code报错

### ISSUE THREAD

**Issue by docoter** [PaddlePaddle/Paddle#36184]
使用的是官方文档的案例：
### 以下是代码：
```
import numpy as np
import paddle
class SimpleFcLayer(paddle.nn.Layer):
    def __init__(self, batch_size, feature_size, fc_size):
        super(SimpleFcLayer, self).__init__()
        self._linear = paddle.nn.Linear(feature_size, fc_size)
        self._offset = paddle.to_tensor(
            np.random.random((batch_size, fc_size)).astype('float32'))
    @paddle.jit.to_static
    def forward(self, x):
        fc = self._linear(x)
        return fc + self._offset
    
fc_layer = SimpleFcLayer(3, 4, 2)
in_np = np.random.random([3, 4]).astype('float32')
input_var = paddle.to_tensor(in_np)
out = fc_layer(input_var)
```

### 以下是报错信息：
W0928 15:34:39.342442 32433 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0928 15:34:39.344497 32433 device_context.cc:422] device: 0, cuDNN Version: 8.1.
/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  return (isinstance(seq, collections.Sequence) and 2021-09-28 15:34:41,675 Dynamic-to-Static WARNING: Please file an issue at 'https://github.com/PaddlePaddle/Paddle/issues' if you can't handle this <class 'OSError'> yourself.
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 356, in __call__
    raise e
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 333, in __call__
    concrete_program, partial_program_layer = self.get_concrete_program(
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 701, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/home/cr/miniconda3/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 623, in from_func_spec
    static_func = convert_to_static(dygraph_function)
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 140, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 77, in convert_with_cache
    static_func = self._convert(func)
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 104, in _convert
    source_code = func_to_source_code(func)
  File "/home/cr/miniconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 559, in func_to_source_code
    source_code = inspect.getsource(function)
  File "/home/cr/miniconda3/lib/python3.9/inspect.py", line 1024, in getsource
    lines, lnum = getsourcelines(object)
  File "/home/cr/miniconda3/lib/python3.9/inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "/home/cr/miniconda3/lib/python3.9/inspect.py", line 835, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

### 以下是环境和版本信息：
操作系统：ubuntu18.04
python：3.9.5
PaddlePaddle：2.1.2
GPU：RTX3080
显卡驱动：470.57.02
CUDA：11.2.152
CUDNN：v8.1.1
NCCL：2.8.4

### 以下是训练信息：
单机单卡

因为百度了以后大概率推测是什么关联包的版本问题，所以贴出包的信息
### 以下是包的信息：
Package                           Version
--------------------------------- -------------------
astor                             0.8.1
Babel                             2.9.1
backports.entry-points-selectable 1.1.0
bce-python-sdk                    0.8.62
brotlipy                          0.7.0
certifi                           2021.5.30
cffi                              1.14.6
cfgv                              3.3.1
chardet                           4.0.0
click                             8.0.1
conda                             4.10.3
conda-package-handling            1.7.3
cryptography                      3.4.7
cycler                            0.10.0
decorator                         5.0.9
distlib                           0.3.2
distro                            1.6.0
filelock                          3.0.12
flake8                            3.9.2
Flask                             2.0.1
Flask-Babel                       2.0.0
fonttools                         4.26.2
future                            0.18.2
gast                              0.4.0
h5py                              3.4.0
identify                          2.2.13
idna                              2.10
itsdangerous                      2.0.1
Jinja2                            3.0.1
kiwisolver                        1.3.2
MarkupSafe                        2.0.1
matplotlib                        3.5.0b1
mccabe                            0.6.1
nodeenv                           1.6.0
numexpr                           2.7.3
numpy                             1.21.2
packaging                         21.0
paddlepaddle-gpu                  2.1.2.post112
pandas                            1.3.2
Pillow                            8.3.2
pip                               21.1.3
platformdirs                      2.3.0
pre-commit                        2.15.0
protobuf                          3.17.3
pycodestyle                       2.7.0
pycosat                           0.6.3
pycparser                         2.20
pycryptodome                      3.10.1
pyflakes                          2.3.1
pyOpenSSL                         20.0.1
pyparsing                         3.0.0b3
PySocks                           1.7.1
python-dateutil                   2.8.2
pytz                              2021.1
PyYAML                            5.4.1
requests                          2.25.1
ruamel-yaml-conda                 0.15.100
setuptools                        52.0.0.post20210125
setuptools-scm                    6.3.1
shellcheck-py                     0.7.2.1
six                               1.16.0
tables                            3.6.1
toml                              0.10.2
tomli                             1.2.1
tqdm                              4.61.2
urllib3                           1.26.6
virtualenv                        20.7.2
visualdl                          2.2.1
Werkzeug                          2.0.1
wheel                             0.36.2

**Comment by qili93** [comment]
@docoter 首先建议您这里使用Paddle官方的镜像环境来跑可以避免很多环境问题 paddlepaddle/paddle:latest-dev-cuda11.2-cudnn8-gcc82。

同时您这里的代码貌似和官网稍有区别，可以用这个最新代码试一下 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/04_dygraph_to_static/input_spec_cn.html#to-static

如果以上方法都不适用，帮忙确认下你安装的Paddle的whl包的链接或者你安装paddle的命令行，谢谢！

**Comment by docoter** [comment]
> @docoter首先建议这里使用Paddle官方的镜像环境来跑可以避免很多环境问题paddlepaddle/paddle:latest-dev-cuda11.2-cudnn8-gcc82。
> 
> 同时你这里的代码假装和官网稍有区别，可以用这个最新的代码来一下https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/04_dygraph_to_static/input_spec_cn.html#to-static
> 
> 如果以上方法不适用，请帮忙确认下你安装的桨的whl包的链接或者你安装桨的命令行，谢谢！

现在行了，不知道为什么。。。
