### ISSUE TITLE
自行训练的 PPYOLOV2-ResNet50_vd_dcn的模型，执行预测时报错，Server崩溃了，什么原因？

### ISSUE THREAD

**Issue by sdl415** [PaddlePaddle/Paddle#36195]
- 版本、环境信息：
    1）PaddlePaddle版本：2.1.3
    2）CPU：
    3）GPU：GTX TITAN X（4块卡） cuda 10.2 cudnn 8.2 
    4）系统环境：ubuntu 18.04
    5）python 3.7

用paddleX训练模型，
模型选择：PPYOLOV2
Backbone选择:ResNet50_vd_dcn
其它参数全部是paddleX默认
训练完成后，在paddlex中评估预测的效果不错，发布后开始用命令开启server
python -m paddle_serving_server.serve --model serving_server --port 9494 --gpu_ids 1
启动信息如下，之后执行预测程序如下：

`
from paddle_serving_client import Client
from paddle_serving_app.reader import *
import sys
import numpy as np

preprocess = Sequential([
    File2Image(), BGR2RGB(), Div(255.0),
    Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225], False),
    Resize(640, 640), Transpose((2, 0, 1))
])

postprocess = RCNNPostprocess("label_list.txt", "output")
client = Client()

client.load_client_config("serving_client/serving_client_conf.prototxt")
client.connect(['127.0.0.1:9494'])

im = preprocess(sys.argv[1])
fetch_map = client.predict(
    feed={
        "image": im,
        "im_shape": np.array(list(im.shape[1:])).reshape(-1),
        "scale_factor": np.array([1.0,1.0]).reshape(-1),
    },
    fetch=["save_infer_model/scale_0.tmp_1"],
    batch=False)
print(fetch_map)
fetch_map["image"] = sys.argv[1]
postprocess(fetch_map)

`
执行 后就报错，同时server崩溃。

客户端报错信息如下：
Traceback (most recent call last):
  File "test_client_9898.py", line 42, in <module>
    fetch_map["image"] = sys.argv[1]
TypeError: 'NoneType' object does not support item assignment

server端启动信息及报错如下：

λ gpu /home/testP20006 python -m paddle_serving_server.serve --model serving_server --port 9494 --gpu_ids 1
/usr/local/lib/python3.7/runpy.py:125: RuntimeWarning: 'paddle_serving_server.serve' found in sys.modules after import of package 'paddle_serving_server', but prior to execution of 'paddle_serving_server.serve'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
set brpc port here: 9494
Going to Run Comand
/usr/local/lib/python3.7/site-packages/paddle_serving_server/serving-gpu-102-0.6.3/serving -enable_model_toolkit -inferservice_path workdir_1 -inferservice_file infer_service.prototxt -max_concurrency 0 -num_threads 2 -port 9494 -precision fp32 -use_calib False -reload_interval_s 10 -resource_path workdir_1 -resource_file resource.prototxt -workflow_path workdir_1 -workflow_file workflow.prototxt -bthread_concurrency 2 -gpuid 1 -max_body_size 536870912 
I0100 00:00:00.000000  2423 op_repository.h:68] RAW: Succ regist op: GeneralCopyOp
I0100 00:00:00.000000  2423 op_repository.h:68] RAW: Succ regist op: GeneralDistKVInferOp
I0100 00:00:00.000000  2423 op_repository.h:68] RAW: Succ regist op: GeneralDistKVQuantInferOp
I0100 00:00:00.000000  2423 op_repository.h:68] RAW: Succ regist op: GeneralInferOp
I0100 00:00:00.000000  2423 op_repository.h:68] RAW: Succ regist op: GeneralReaderOp
I0100 00:00:00.000000  2423 op_repository.h:68] RAW: Succ regist op: GeneralResponseOp
I0100 00:00:00.000000  2423 op_repository.h:68] RAW: Succ regist op: GeneralTextReaderOp
I0100 00:00:00.000000  2423 op_repository.h:68] RAW: Succ regist op: GeneralTextResponseOp
I0100 00:00:00.000000  2423 service_manager.h:79] RAW: Service[LoadGeneralModelService] insert successfully!
I0100 00:00:00.000000  2423 load_general_model_service.pb.h:333] RAW: Success regist service[LoadGeneralModelService][PN5baidu14paddle_serving9predictor26load_general_model_service27LoadGeneralModelServiceImplE]
I0100 00:00:00.000000  2423 service_manager.h:79] RAW: Service[GeneralModelService] insert successfully!
I0100 00:00:00.000000  2423 general_model_service.pb.h:1507] RAW: Success regist service[GeneralModelService][PN5baidu14paddle_serving9predictor13general_model23GeneralModelServiceImplE]
I0100 00:00:00.000000  2423 factory.h:155] RAW: Succ insert one factory, tag: PADDLE_INFER, base type N5baidu14paddle_serving9predictor11InferEngineE
W0100 00:00:00.000000  2423 paddle_engine.cpp:29] RAW: Succ regist factory: ::baidu::paddle_serving::predictor::FluidInferEngine<PaddleInferenceEngine>->::baidu::paddle_serving::predictor::InferEngine, tag: PADDLE_INFER in macro!
You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
I0928 19:57:59.338238  2423 analysis_config.cc:424] use_dlnne_:0
I0928 19:57:59.338270  2423 analysis_predictor.cc:155] Profiler is deactivated, and no profiling report will be generated.
I0928 19:57:59.396523  2423 analysis_predictor.cc:571] ir_optim is turned off, no IR pass will be executed
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I0928 19:57:59.670655  2423 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0928 19:57:59.775223  2423 memory_optimize_pass.cc:199] Cluster name : im_shape  size: 8
I0928 19:57:59.775250  2423 memory_optimize_pass.cc:199] Cluster name : tmp_4  size: 819200
I0928 19:57:59.775254  2423 memory_optimize_pass.cc:199] Cluster name : tmp_8  size: 1638400
I0928 19:57:59.775257  2423 memory_optimize_pass.cc:199] Cluster name : conv2d_2.tmp_0  size: 26214400
I0928 19:57:59.775260  2423 memory_optimize_pass.cc:199] Cluster name : batch_norm_2.tmp_3  size: 26214400
I0928 19:57:59.775264  2423 memory_optimize_pass.cc:199] Cluster name : elementwise_add_0  size: 23040000
I0928 19:57:59.775266  2423 memory_optimize_pass.cc:199] Cluster name : elementwise_add_4  size: 13107200
I0928 19:57:59.775270  2423 memory_optimize_pass.cc:199] Cluster name : scale_factor  size: 8
I0928 19:57:59.775272  2423 memory_optimize_pass.cc:199] Cluster name : tmp_18  size: 3276800
I0928 19:57:59.775275  2423 memory_optimize_pass.cc:199] Cluster name : image  size: 4915200
I0928 19:57:59.775279  2423 memory_optimize_pass.cc:199] Cluster name : elementwise_add_12  size: 6553600
--- Running analysis [ir_graph_to_program_pass]
I0928 19:58:00.017562  2423 analysis_predictor.cc:595] ======= optimize end =======
I0928 19:58:00.017827  2423 naive_executor.cc:98] ---  skip [feed], feed -> scale_factor
I0928 19:58:00.017861  2423 naive_executor.cc:98] ---  skip [feed], feed -> image
I0928 19:58:00.017870  2423 naive_executor.cc:98] ---  skip [feed], feed -> im_shape
I0928 19:58:00.028211  2423 naive_executor.cc:98] ---  skip [conv2d_2.tmp_0], fetch -> fetch
I0928 19:58:00.028239  2423 naive_executor.cc:98] ---  skip [batch_norm_2.tmp_3], fetch -> fetch
W0928 19:58:00.028380  2423 infer.h:307] Succ load common model[0x463fb5f0], path[serving_server].
W0928 19:58:00.028403  2423 infer.cpp:42] Succ load model:serving_server
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

  Compile Traceback (most recent call last):
    File "PaddleX.py", line 18, in <module>
      
    File "PaddleXCore.py", line 50, in main
      
    File "main/utils.py", line 193, in init_app_resource
      
    File "pms/core.py", line 1837, in run_pms
      
    File "multiprocessing/process.py", line 112, in start
      
    File "multiprocessing/context.py", line 223, in _Popen
      
    File "multiprocessing/context.py", line 277, in _Popen
      
    File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 81, in __init__
      
    File "multiprocessing/popen_fork.py", line 20, in __init__
      
    File "multiprocessing/popen_fork.py", line 74, in _launch
      
    File "multiprocessing/process.py", line 297, in _bootstrap
      
    File "multiprocessing/process.py", line 99, in run
      
    File "pms/core.py", line 1810, in run_core
      
    File "pms/core.py", line 1795, in clock
      
    File "pms/core.py", line 1773, in execute
      
    File "pms/core.py", line 1219, in export_infer_model
      
    File "pms/model_tasks/tasks.py", line 349, in export_infer_model
      
    File "multiprocessing/process.py", line 112, in start
      
    File "multiprocessing/context.py", line 223, in _Popen
      
    File "multiprocessing/context.py", line 277, in _Popen
      
    File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 81, in __init__
      
    File "multiprocessing/popen_fork.py", line 20, in __init__
      
    File "multiprocessing/popen_fork.py", line 74, in _launch
      
    File "multiprocessing/process.py", line 297, in _bootstrap
      
    File "multiprocessing/process.py", line 99, in run
      
    File "pms/model_tasks/tasks.py", line 252, in _call_paddlex_export_infer
      
    File "/home/PaddleX/paddlex/cv/models/base.py", line 602, in _export_inference_model
      paddle.jit.save(static_net, osp.join(save_dir, 'model'))
    File "<decorator-gen-66>", line 2, in save
      
    File "/home/PaddleX/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/PaddleX/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/PaddleX/paddle/fluid/dygraph/jit.py", line 726, in save
      inner_input_spec)
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 491, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 705, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-64>", line 2, in from_func_spec
      
    File "/home/PaddleX/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/PaddleX/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 655, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpfdsgthkc.py", line 29, in forward
      false_fn_1, (), (), (out,))
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/PaddleX/paddlex/ppdet/modeling/architectures/meta_arch.py", line 28, in forward
      out = self.get_pred()
    File "/home/PaddleX/paddlex/ppdet/modeling/architectures/yolo.py", line 124, in get_pred
      return self._forward()
    File "/home/PaddleX/paddlex/ppdet/modeling/architectures/yolo.py", line 80, in _forward
      neck_feats = self.neck(body_feats, self.for_mot)
    File "/home/PaddleX/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpwsgw8paj.py", line 89, in forward
      for_loop_body_2, [__for_loop_var_index_3, tip, i, route, blocks])
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 44, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 58, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/tmp/tmpwsgw8paj.py", line 59, in for_loop_body_2
      (__for_loop_iter_var_2,), (__for_loop_iter_var_2,))
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmpwsgw8paj.py", line 52, in true_fn_15
      route), (__for_loop_iter_var_2,))
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/PaddleX/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/PaddleX/paddlex/ppdet/modeling/necks/yolo_fpn.py", line 949, in forward
      block = paddle.concat([route, block], axis=1)
    File "/home/PaddleX/paddle/tensor/manipulation.py", line 121, in concat
      return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
    File "/home/PaddleX/paddle/fluid/layers/tensor.py", line 356, in concat
      type='concat', inputs=inputs, outputs={'Out': [out]}, attrs=attrs)
    File "/home/PaddleX/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/PaddleX/paddle/fluid/framework.py", line 2942, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/PaddleX/paddle/fluid/framework.py", line 2014, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 512, 28, 40], input[1]'s shape = [1, 1024, 27, 40].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:28 != inputs_dims[i][j]:27.] (at /paddle/paddle/fluid/operators/concat_op.h:63)
  [operator < concat >
  
  
  我在同一台服务器上运行 paddle带的例子ppyolo_r50vd_dcn_1x_coco 是可以正常运行的，
  整个操作过程中，我基本没有自己写代码，可为什么一执行预测就会这样呢？烦请指点一二，谢谢！

**Comment by TeslaZhao** [comment]
您好，从报错信息上看是concat op计算过程中输入参数input[0]和input[1]参数不符合concat的计算条件。我猜测input[0]中512和 input[1]中1024已经是batch维度了，最前面的增加了额外的1维导致的。因此我判断是在client请求参数predict函数中的batch参数需要修改：

原代码：
fetch_map = client.predict(
feed={
"image": im,
"im_shape": np.array(list(im.shape[1:])).reshape(-1),
"scale_factor": np.array([1.0,1.0]).reshape(-1),
},
fetch=["save_infer_model/scale_0.tmp_1"],
batch=False)

修改为：
fetch_map = client.predict(
feed={
"image": im,
"im_shape": np.array(list(im.shape[1:])).reshape(-1),
"scale_factor": np.array([1.0,1.0]).reshape(-1),
},
fetch=["save_infer_model/scale_0.tmp_1"],
batch=True)

**Comment by ZhangYulongg** [comment]
把Resize(640, 640)改为Resize((640, 640))试试？
https://github.com/PaddlePaddle/Serving/blob/v0.6.3/python/paddle_serving_app/reader/image_reader.py#L706
Resize(640, 640)是指定了int类型size=640，max_size=640，如果要将图片Resize为640x640，应指定size=(640, 640)
如果还是不对，应该是im_shape和模型规定的shape没有对上？需要Resize为规定的shape

**Comment by LightSun** [comment]
遇到了类似的错误。求助
```
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  

  Compile Traceback (most recent call last):
    File "tools/export_model.py", line 111, in <module>
      main()
    File "tools/export_model.py", line 107, in main
      run(FLAGS, cfg)
    File "tools/export_model.py", line 73, in run
      trainer.export(FLAGS.output_dir)
    File "/home/ai998/coding/detection/PaddleDetection/ppdet/engine/trainer.py", line 775, in export
      save_dir)
    File "/home/ai998/coding/detection/PaddleDetection/ppdet/engine/trainer.py", line 752, in _get_infer_cfg_and_input_spec
      input_spec, static_model.forward.main_program,
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in main_program
      concrete_program = self.concrete_program
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
      *desired_input_spec, with_hook=with_hook)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
      **cache_key.kwargs)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmprnurp1s6.py", line 101, in forward
      false_fn_5, (), (inputs, self), (out,))
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/tmp/tmprnurp1s6.py", line 84, in false_fn_5
      for_loop_body_0, [__for_loop_var_index_0, inputs_list])
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/tmp/tmprnurp1s6.py", line 79, in for_loop_body_0
      dy2static.convert_call(self.get_pred)())
    File "/home/ai998/coding/detection/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 128, in get_pred
      return self._forward()
    File "/home/ai998/coding/detection/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 80, in _forward
      neck_feats = self.neck(body_feats, self.for_mot)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmppc8qhx5d.py", line 51, in forward
      for_loop_body_2, [route, i, blocks, __for_loop_var_index_3])
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/tmp/tmppc8qhx5d.py", line 30, in for_loop_body_2
      __for_loop_iter_var_2,), (__for_loop_iter_var_2,))
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/ai998/coding/detection/PaddleDetection/ppdet/modeling/necks/custom_pan.py", line 199, in forward
      block = paddle.concat([route, block], axis=1)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 331, in concat
      return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/layers/tensor.py", line 393, in concat
      type='concat', inputs=inputs, outputs={'Out': [out]}, attrs=attrs)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/ai998/.conda/envs/ppcv/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::InferShapeContext*), paddle::framework::details::OpInfoFiller<ConcatInferShapeFunctor, (paddle::framework::details::OpInfoFillType)4>::operator()(char const*, paddle::framework::OpInfo*) const::{lambda(paddle::framework::InferShapeContext*)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::InferShapeContext*&&)
6   ConcatInferShapeFunctor::operator()(paddle::framework::InferShapeContext*) const
7   phi::ConcatInferMeta(std::vector<phi::MetaTensor const*, std::allocator<phi::MetaTensor const*> > const&, paddle::experimental::ScalarBase<phi::DenseTensor> const&, phi::MetaTensor*, phi::MetaConfig)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 192, 4, 12], input[1]'s shape = [1, 256, 3, 12].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:4 != inputs_dims[i][j]:3.] (at /home/heaven7/heaven7/libs/paddle/Paddle/paddle/phi/kernels/funcs/concat_funcs.h:83)
  [operator < concat > error]
Aborted (core dumped)

```

paddle version: 2.3
paddle ocr: 2.5

**Comment by LightSun** [comment]
最后找到原因是 同事给的AI模型三paddle detection的 不能直接替换掉OCR的 分类模型使用，要用 paddle detection cpp的处理
