### ISSUE TITLE
【论文复现】ECANet正常打印网络结构，但训练时报错

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/Paddle#36269]
1）PaddlePaddle版本：2.1.2
    2）系统环境：aistudio GPU：V100

- 模型信息
    1）模型名称   ECANET
    2）使用数据集名称 10 animals
    3）使用算法名称  ECANet 注意力机制
    4）模型链接 https://aistudio.baidu.com/aistudio/projectdetail/1545743
code/eca_module.py
- 复现信息：报错代码如下所示

```
import paddle
from paddle.fluid.layers.nn import transpose
import paddle.nn as nn
import math
import paddle.nn.functional as F

class h_sigmoid(nn.Layer):
    def __init__(self):
        super(h_sigmoid, self).__init__()
        self.relu = nn.ReLU6()

    def forward(self, x):
        return self.relu(x + 3) / 6

class h_swish(nn.Layer):
    def __init__(self):
        super(h_swish, self).__init__()
        self.sigmoid = h_sigmoid()

    def forward(self, x):
        return x * self.sigmoid(x)

class sa_layer(nn.Layer):
    def __init__(self, channel, outchannel, groups=32):
        super(sa_layer, self).__init__()
        self.AvgPool = nn.AdaptiveAvgPool2D(1)
        self.sigmoid = nn.Sigmoid()
        self.groups = groups
        self.Conv1D = nn.Conv1D(1, 1, kernel_size=3, padding=1, bias_attr=False) 
        self.Conv2D = nn.Conv2D(channel, outchannel, kernel_size=1, stride=1, padding=0)
        self.bn1 = nn.BatchNorm2D(channel)
        self.act = h_swish()
        self.conv = nn.Sequential(
            nn.Conv2D(channel, channel, kernel_size=1, groups=channel),
            # ch_input = ch_out = groups
            # GDC=global depth-wise convolution 类似于全局平局池化，但参数是可学习的
            nn.BatchNorm2D(channel) )
        
        self.gn = nn.GroupNorm(channel // (2 * groups), channel // (2 * groups))
        self.sweight = self.create_parameter(shape=[1, channel // (2 * groups), 1, 1],
                                            default_initializer=paddle.nn.initializer.Assign(
                                                paddle.zeros([1, channel // (2 * groups), 1, 1])))
        self.sbias = self.create_parameter(shape=[1, channel // (2 * groups), 1, 1],
                                            default_initializer=paddle.nn.initializer.Assign(
                                                paddle.ones([1, channel // (2 * groups), 1, 1])))       
    def forward(self, x):
        identity = x
        n,c,h,w = x.shape

        y = self.AvgPool(x)   #  b,c,1,1
        y = paddle.squeeze(y, axis=-1) # b,c,1
        y = paddle.transpose(y, perm=[0, 2, 1]) # b,1,c

        y = self.Conv1D(y)

        y = paddle.transpose(y, perm=[0, 2, 1]) # b,c,1
        paddle.unsqueeze_(y, axis=-1) # b,c,1,1
        y = self.sigmoid(y) # nchw*nc11
        y = paddle.expand_as(y, x)
        
        out = x * y
        return out



def BasicConv2d(in_channels, out_channels, kernel, stride=1, padding=0):
    layer = paddle.nn.Sequential(
                paddle.nn.Conv2D(in_channels, out_channels, kernel, stride, padding), 
                paddle.nn.BatchNorm2D(out_channels, epsilon=1e-3),
                paddle.nn.ReLU())
    return layer

class Net(paddle.nn.Layer):
    def __init__(self, in_channel, num_classes):
        super(Net, self).__init__()
        self.b1 = paddle.nn.Sequential(
                    BasicConv2d(in_channel, out_channels=64, kernel=3, stride=2, padding=1),
                    #sa_layer(64)
                    )
        self.b2 = paddle.nn.Sequential(
                    BasicConv2d(64, 128, kernel=3, stride=2, padding=1),
                    #sa_layer(128,128)
                    )
        self.b3 = paddle.nn.Sequential(
                    BasicConv2d(128, 256, kernel=3,stride=2,  padding=1),
                    sa_layer(256,256)
                    )
        self.b4 = paddle.nn.Sequential(
                    BasicConv2d(256, 512, kernel=3, stride=2, padding=1),
                    #sa_layer(512)
                    )
        self.AvgPool2D=paddle.nn.AdaptiveAvgPool2D(1)
        self.flatten=paddle.nn.Flatten()
        self.b6 = paddle.nn.Linear(512, num_classes)


    def forward(self, x):
        x = self.b1(x)
        x = self.b2(x)
        x = self.b3(x)
        x = self.b4(x)
        x = self.AvgPool2D(x)
        x = self.flatten(x)
        x = self.b6(x)
        return x

model = paddle.Model(Net(3, config_parameters['class_dim']))
model.summary((-1, 3, 256, 256))
```

- 问题描述：训练后开始报错，报错内容如下
```
The loss value printed in the log is the current step, and the metric is the average value of previous step.
Epoch 1/50
Traceback (most recent call last):
  File "code/train.py", line 120, in <module>
    verbose=1)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1495, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1802, in _run_one_epoch
    data[len(self._inputs):])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 941, in train_batch
    loss = self._adapter.train_batch(inputs, labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 661, in train_batch
    final_loss.backward()
  File "<decorator-gen-114>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 177, in backward
    self._run_backward(framework._dygraph_tracer(), retain_graph)
ValueError: (InvalidArgument)  shape should have the save dim with perm, but received shape size is:4, perm size is:3.
  [Hint: Expected shape.size() == perm.size(), but received shape.size():4 != perm.size():3.] (at /paddle/paddle/fluid/operators/transpose_op.cu:565)
```

**Comment by nemonameless** [comment]
您好，从报错信息上看，错误可能是由于loss计算过程维度不匹配，建议检查此过程的输入输出tensor等的维度，例如batch size维度。如未能解决还请继续反馈。

**Comment by gaorui999** [comment]
您好，我通过逐项print计算tensor维度，检查过程无异常，但训练仍提示相同错误

**Comment by nemonameless** [comment]
> 您好，我通过逐项print计算tensor维度，检查过程无异常，但训练仍提示相同错误

您好，报错信息需要复现代码，请提供代码和环境信息，我们复现后会尽快回复您。把您的ai studio项目分享下，或者把你所有的改动点全部体现下谢谢。

**Comment by gaorui999** [comment]
https://aistudio.baidu.com/aistudio/projectdetail/1545743

**Comment by gaorui999** [comment]
code/eca_module.py

**Comment by xuechenxing** [comment]
我好像和他遇到一样的问题了，请问解决没，在cnn中加入eca模块就报这个错，去掉后可正常训练

File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in call
return self._dygraph_call_func(*inputs, **kwargs)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
outputs = self.forward(*inputs, **kwargs)
File "/home/aistudio/work/eca_module.py", line 34, in forward
y = paddle.expand_as(y, x)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 1884, in expand_as
outputs={'Out': out})
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
return self.main_program.current_block().append_op(*args, **kwargs)
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
attrs=kwargs.get("attrs", None))
File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in init
for frame in traceback.extract_stack():

InvalidArgumentError: The value (100) of the non-singleton dimension does not match the corresponding value (16) in shape for expand_as_v2 op.
  [Hint: Expected vec_in_dims[i] == target_shape[i], but received vec_in_dims[i]:100 != target_shape[i]:16.] (at /paddle/paddle/phi/kernels/impl/expand_as_kernel_impl.h:60)
  [operator &#60; expand_as_v2 &#62; error]  [operator &#60; run_program &#62; error]
