### ISSUE TITLE
张量经过squeeze和unsqueeze_操作后打印模型没问题，训练时报错

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/Paddle#36343]
- 版本、环境信息：
    1）PaddlePaddle版本：2.0.2
    2）CPU：aistudio平台
    3）GPU：aistudio平台  V100
    4）系统环境：aistudio平台，Python.37

- 报错信息：
张量经过以下操作后打印结构没问题，但一训练就会提示以下报错信息。全部代码在最下方，复现项目链接为：https://aistudio.baidu.com/aistudio/projectdetail/1545743

        y = paddle.squeeze(y, axis=-1)
        y = paddle.unsqueeze_(y, axis=-1)

```
Traceback (most recent call last):
  File "code/train.py", line 120, in <module>
    verbose=1)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1495, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1802, in _run_one_epoch
    data[len(self._inputs):])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 941, in train_batch
    loss = self._adapter.train_batch(inputs, labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 661, in train_batch
    final_loss.backward()
  File "<decorator-gen-114>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 177, in backward
    self._run_backward(framework._dygraph_tracer(), retain_graph)
ValueError: (InvalidArgument)  shape should have the save dim with perm, but received shape size is:4, perm size is:3.
  [Hint: Expected shape.size() == perm.size(), but received shape.size():4 != perm.size():3.] (at /paddle/paddle/fluid/operators/transpose_op.cu:565)
```
- 问题描述：
- 可复现的代码片段

```
import paddle
from paddle import nn


class eca_layer(nn.Layer):
    """Constructs a ECA module.
    Args:
        channel: Number of channels of the input feature map
        k_size: Adaptive selection of kernel size
    """
    def __init__(self, channel, k_size=3):
        super(eca_layer, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool2D(1)
        self.conv = nn.Conv1D(1, 1, kernel_size=k_size, padding=(k_size - 1) // 2, bias_attr=False) 
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # x: input features with shape [b, c, h, w]
        b, c, h, w = x.shape
        # feature descriptor on the global spatial information
        y = self.avg_pool(x)

        y = paddle.squeeze(y, axis=3)
        y = paddle.transpose(y, perm=[0, 2, 1])
        y = paddle.transpose(y, perm=[0, 2, 1])
        y = paddle.unsqueeze_(y, axis=-1)

        return y
```

**Comment by lyuwenyu** [comment]
建议安装下边试一下
```
y = paddle.unsqueeze_(y, axis=-1)
```
改成
```
y = paddle.unsqueeze(y, axis=-1)
```

**Comment by gaorui999** [comment]
已解决
