### ISSUE TITLE
There is a flaw in Paddle Tensor Indexing

### ISSUE THREAD

**Issue by crj1998** [PaddlePaddle/Paddle#36359]
Indexing is a  common operation in practice. but i found that the boolean indexing in paddle is blurry.
Firstly, I wan to show how pytorch works. I have a vector `x` and a boolean flag `y`, and use `y` as index for 'x'. The operation in pytorch is simple and nature.
```
>>> import torch
>>> x = torch.tensor([1., 2., 3., 4.])
>>> y = torch.tensor([True, False, True, False])
>>> x[y]
tensor([1., 3.])
>>> x[y] = 0
>>> x
tensor([0., 2., 0., 4.])
```
However, for paddle, it is stupid. When i use boolean index to get value, it is error. But if i use boolean index to set value, it works. This logic is ridiculous. I think the indexing operation in paddle need re-do.
```
>>> import paddle
>>> x = paddle.to_tensor([1., 2., 3., 4.])
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
>>> y = paddle.to_tensor([True, False, True, False])
>>> x[y]
W1012 13:21:54.634701  4072 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 10.1
W1012 13:21:54.640252  4072 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 565, in __getitem__
    return _getitem_impl_(self, item)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/variable_index.py", line 182, in _getitem_impl_
    return index_select(var, index=slice_item, axis=0)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/search.py", line 305, in index_select
    return core.ops.index_select(x, index, 'dim', axis)
ValueError: (InvalidArgument) Input(Index) holds the wrong type, it holds bool, but desires to be int or int64_t
  [Hint: Expected index_type_match == true, but received index_type_match:0 != true:1.] (at /paddle/paddle/fluid/operators/index_select_op.cu:94)
  [operator < index_select > error]
>>> x[y]=0
>>> x
Tensor(shape=[4], dtype=float32, place=CUDAPlace(0), stop_gradient=True,
       [0., 2., 0., 4.])
```

**Comment by lzzyzlbb** [comment]
您好，这边复现啦您的问题，已交由内部工程师进行修改，希望您多多提问，祝您生活愉快！
