### ISSUE TITLE
gpu 运行会卡住

### ISSUE THREAD

**Issue by chereyk** [PaddlePaddle/Paddle#36364]
cuda版本是10.2，cudnn版本是7.6.5，系统是windows10专业版，显卡是3060，paddlepaddle是2.1.3，来源于官网pip安装，python是3.8（也在3.7上尝试过），pip是21.0.1
现象是在运行paddle.fluid.install_check.run_check()时会卡住很久，最后崩溃退出，在训练模型时，会卡住半个小时左右然后开始正常训练
我以为是版本适配问题，所以尝试过10.1，10.0，11.0，11.2，最后发现都有这个问题，重装系统还是有这个问题。在paddlepaddle官方论坛和其他地方查了很久发现也有其他同学遇到这个问题，但都没有解决办法，所以只能麻烦官方大佬可以查看一下。

**Comment by lzzyzlbb** [comment]
您好，请问有具体的日志吗？可以使用： GLOG_v=10 python 命令， 看看c++的日志，具体卡在哪里了

**Comment by chereyk** [comment]
非常感谢您的回复！我不太明白该在哪输入这条命令
刚刚把cpu版的卸载重装了一下gpu版的，卡了十分钟左右出现了报错信息，出现了与这位同学https://github.com/PaddlePaddle/Paddle/issues/35028     一样的错误，根据下面同学的回复，设置了path = cublas64_10.dll,可能是因为我cuda中没有cublas64_102.dll，所以没有设置这个的路径，所以还是出现了与没有设置一模一样的错误
错误信息如下：
Running Verify Fluid Program ... 
W1012 16:24:43.127553  3024 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W1012 16:24:43.136505  3024 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "F:/project/paddleocr/PaddleOCR/test.py", line 2, in <module>
    paddle.fluid.install_check.run_check()
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\install_check.py", line 140, in run_check
    test_simple_exe()
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\install_check.py", line 136, in test_simple_exe
    exe0.run(startup_prog)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "D:\ProgramData\Anaconda3\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1098, in run
    return self._run_impl(
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1231, in _run_impl
    return self._run_program(
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\executor.py", line 1328, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cublas64_102.dll;cublas64_10.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release\paddle\fluid\platform\dynload\dynamic_loader.cc:265)


Process finished with exit code 1

**Comment by betterpig** [comment]
您好，安装检测失败的原因为没有找到需要的动态库。请您进行以下操作：

1. 确保CUDA的动态库文件夹中存在 cublas64_10.dll 与 cublasLt64_10.dll 文件，它们一般位于 `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin`（CUDA10.2）。
2. 检查Python的获取渠道，若是从Microsoft store安装的Python，则会出现该问题（已本地验证）。请尝试从[官网](https://www.python.org/)安装Python，再通过pip安装paddle。
3. 若仍出现该问题，将cublas64_10.dll 与 cublasLt64_10.dll 文件复制到 `C:\Windows\System32` 中，再运行 `paddle.utils.run_check()`

**Comment by chereyk** [comment]
> 您好，安装检测失败的原因为没有找到需要的动态库。请您进行以下操作：
> 
> 1. 确保CUDA的动态库文件夹中存在 cublas64_10.dll 与 cublasLt64_10.dll 文件，它们一般位于 `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin`（CUDA10.2）。
> 2. 检查Python的获取渠道，若是从Microsoft store安装的Python，则会出现该问题（已本地验证）。请尝试从[官网](https://www.python.org/)安装Python，再通过pip安装paddle。
> 3. 若仍出现该问题，将cublas64_10.dll 与 cublasLt64_10.dll 文件复制到 `C:\Windows\System32` 中，再运行 `paddle.utils.run_check()`

您好，将cublas64_10.dll 与 cublasLt64_10.dll 文件复制到 C:\Windows\System32 中，再运行 paddle.utils.run_check()后又出现了原来的问题，即在运行paddle.fluid.install_check.run_check()时会卡住很久，最后崩溃退出，如下
D:\ProgramData\Anaconda3\python.exe F:/project/paddleocr/test.py
D:\ProgramData\Anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
Running verify PaddlePaddle program ...
W1021 09:42:44.184212 15824 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W1021 09:42:44.204190 15824 device_context.cc:422] device: 0, cuDNN Version: 7.6.

Process finished with exit code -1073741818 (0xC0000006)

**Comment by betterpig** [comment]
> > 您好，安装检测失败的原因为没有找到需要的动态库。请您进行以下操作：
> > 
> > 1. 确保CUDA的动态库文件夹中存在 cublas64_10.dll 与 cublasLt64_10.dll 文件，它们一般位于 `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin`（CUDA10.2）。
> > 2. 检查Python的获取渠道，若是从Microsoft store安装的Python，则会出现该问题（已本地验证）。请尝试从[官网](https://www.python.org/)安装Python，再通过pip安装paddle。
> > 3. 若仍出现该问题，将cublas64_10.dll 与 cublasLt64_10.dll 文件复制到 `C:\Windows\System32` 中，再运行 `paddle.utils.run_check()`
> 
> 您好，将cublas64_10.dll 与 cublasLt64_10.dll 文件复制到 C:\Windows\System32 中，再运行 paddle.utils.run_check()后又出现了原来的问题，即在运行paddle.fluid.install_check.run_check()时会卡住很久，最后崩溃退出，如下 D:\ProgramData\Anaconda3\python.exe F:/project/paddleocr/test.py D:\ProgramData\Anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses import imp, sys, os Running verify PaddlePaddle program ... W1021 09:42:44.184212 15824 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2 W1021 09:42:44.204190 15824 device_context.cc:422] device: 0, cuDNN Version: 7.6.
> 
> Process finished with exit code -1073741818 (0xC0000006)

您好，3060显卡需要安装CUDA11.x。建议安装CUDA11.0 + cudnn8.0.2 for CUDA 11.0 。

**Comment by chereyk** [comment]
您好，安装完CUDA11.0 + cudnn8.0.2 for CUDA 11.0 之后依然报错。如下：

RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_8.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release\paddle\fluid\platform\dynload\dynamic_loader.cc:265)


随后我将cudnn64_8.dll复制到C:\Windows\System32中，报错如下：


D:\ProgramData\Anaconda3\python.exe F:/project/paddleocr/test.py
D:\ProgramData\Anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
Running verify PaddlePaddle program ... 
W1022 16:39:07.616294 19420 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.0

Process finished with exit code -1073740791 (0xC0000409)




程序运行出错的地方在executor.py 1327行
        if not use_program_cache:
            self._default_executor.run(program.desc, scope,0, True, True,[fetch_var_name])


重启之后出现了新的报错，报错如下：
OSError: (External)  Cublas error, `CUSOLVER_STATUS_INTERNAL_ERROR`. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.  (at C:\home\workspace\Paddle_release\paddle/fluid/platform/device_context.h:382)

**Comment by betterpig** [comment]
在解压cudnn后，需要将bin、include、lib文件夹内的文件分别复制到CUDA安装路径对应文件夹下，如bin中文件复制到`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin`。

**Comment by chereyk** [comment]
> 在解压cudnn后，需要将bin、include、lib文件夹内的文件分别复制到CUDA安装路径对应文件夹下，如bin中文件复制到`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin`。

已经是复制了的呢

**Comment by betterpig** [comment]
> > 在解压cudnn后，需要将bin、include、lib文件夹内的文件分别复制到CUDA安装路径对应文件夹下，如bin中文件复制到`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin`。
> 
> 已经是复制了的呢

请set GLOG_v=10，截图错误的地方，方便分析失败原因。

**Comment by chereyk** [comment]
> > > 在解压cudnn后，需要将bin、include、lib文件夹内的文件分别复制到CUDA安装路径对应文件夹下，如bin中文件复制到`C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin`。
> > 
> > 
> > 已经是复制了的呢
> 
> 请set GLOG_v=10，截图错误的地方，方便分析失败原因。

I1025 15:33:10.178448  6668 op_call_stack.cc:61] ExternalError:  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at C:/home/workspace/Paddle_release/paddle/fluid/operators/fused/conv_fusion_op.cu:306)
Traceback (most recent call last):
  File "predict_system.py", line 193, in <module>
    main(args)
  File "predict_system.py", line 126, in main
    res = text_sys(img)
  File "predict_system.py", line 60, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "F:\project\paddleocr\PaddleOCR\tools\infer\predict_det.py", line 195, in __call__
    self.predictor.run()
OSError: In user code:

    File "tools/export_model.py", line 75, in <module>
      main()
    File "tools/export_model.py", line 70, in main
      paddle.jit.save(model, save_path)
    File "<decorator-gen-60>", line 2, in save

    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 680, in save
      concrete_program = static_func.concrete_program
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 461, in concrete_program
      concrete_program, _ = self.get_concrete_program(*input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 684, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 675, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-58>", line 2, in from_func_spec

    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 38, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 625, in from_func_spec
      outputs = static_func(*inputs)
    File "/paddle/eval_DB/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 74, in forward
      x = self.backbone(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpfjz7mcq2.py", line 22, in forward
      for_loop_condition_0, for_loop_body_0, [__for_loop_var_index_0, y])
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 44, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 58, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/paddle/eval_DB/PaddleOCR/ppocr/modeling/backbones/det_resnet_vd.py", line 278, in forward
      y = block(y)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 86, in forward
      input = layer(input)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/eval_DB/PaddleOCR/ppocr/modeling/backbones/det_resnet_vd.py", line 163, in forward
      y = self.conv0(inputs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/eval_DB/PaddleOCR/ppocr/modeling/backbones/det_resnet_vd.py", line 67, in forward
      y = self._conv(inputs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 884, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 644, in forward
      use_cudnn=self._use_cudnn)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 144, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2846, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1931, in __init__
      for frame in traceback.extract_stack():

    ExternalError:  Cudnn error, CUDNN_STATUS_EXECUTION_FAILED  (at C:/home/workspace/Paddle_release/paddle/fluid/operators/fused/conv_fusion_op.cu:306)
      [operator < conv2d_fusion > error]
输出的东西太多了，是要这个吗

**Comment by chereyk** [comment]
非常感谢您的帮助，在使用cuda11.2+cudnn8.1.0之后可以正常训练了

**Comment by betterpig** [comment]
> 非常感谢您的帮助，在使用cuda11.2+cudnn8.1.0之后可以正常训练了

不客气。环境适配是比较麻烦。
