### ISSUE TITLE
增加batch_normalization报错

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/Paddle#36395]
paddle 2.1 python 3.7
预测任务，都是全连接层，在原来的model上加上batchnormalization报错如下：
Epoch 0/8000
step 0[==============================] - loss: 1177250955264.0 - 0.18ms/step 
Traceback (most recent call last):
  File "/Users/sunyingbin/Documents/workspace/loadforecast/task.py", line 228, in <module>
    high_base(trainer_dataset, EPOCH_NUM, BATCH_SIZE, learning_rate, vdl_writer, inference_path, True)
  File "/Users/sunyingbin/Documents/workspace/loadforecast/dnn.py", line 104, in high_base
    optim.step()
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 1032, in step
    loss=None, startup_program=None, params_grads=params_grads)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 796, in _apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 615, in _create_optimization_pass
    [p[0] for p in parameters_and_grads if not p[0].stop_gradient])
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/optimizer/adagrad.py", line 114, in _create_accumulators
    fill_value=self.initial_accumulator_value)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 533, in _add_accumulator
    "Optimizer set error, {} should in state dict".format( var_name )
AssertionError: Optimizer set error, batch_norm_1.w_0_moment_0 should in state dict

Process finished with exit code 1

**Comment by zh794390558** [comment]
AssertionError: Optimizer set error, batch_norm_1.w_0_moment_0 should in state dict

上面是报错讯息，麻烦确认下。model是否在eval模式下做推理。

**Comment by Sunyingbin** [comment]
> AssertionError: Optimizer set error, batch_norm_1.w_0_moment_0 should in state dict
> 
> 上面是报错讯息，麻烦确认下。model是否在eval模式下做推理。

我知道了，是我之前保存了best.opt和param然后现在是load原来的model训练，但是model我已经修改了，所以会有问题，对吧，我不load之前训练的model之后就好了

**Comment by zh794390558** [comment]
是的，如果没有问题了，麻烦close下，谢谢。

**Comment by Sunyingbin** [comment]
> 是的，如果没有问题了，麻烦close下，谢谢。

我这里还有一个问题，当我自己手动实现bn时候
def batch_norm(X, gamma, beta, moving_mean, moving_var, eps, momentum, is_training=True):
    print('X.shape--->>>>', X.shape)
    # 训练模式还与预测模式的BN处理不同
    if not is_training:
        # 如果是在预测模式下，直接使用传入的移动平均所得的均值和方差
        X_hat = (X - moving_mean) / (moving_var + eps) ** 0.5
    else:
        # assert len(X.shape) in (2, 4)
        if len(X.shape) == 2:
            # 使用全连接层的情况， 计算特征维上的均值和方差
            mean = paddle.mean(X)
            var = paddle.mean((X - mean) ** 2)
        else:
            # 使用二维卷积层的情况， 计算通道维上(axis=1)的均值和方差。这里我们需要保持
            # X的形状以便后面可以做广播运算
            mean = paddle.mean(X, axis=(0, 2, 3), keepdim=True)
            var = paddle.mean((X - mean) ** 2, axis=(0, 2, 3), keepdim=True)
        # 训练模式下用当前的均值和方差做标准化
        X_hat = (X - mean) / (var + eps) ** 0.5
        # 更新移动平均的均值和方差
        moving_mean = momentum * moving_mean + (1.0 - momentum) * mean
        moving_var = momentum * moving_var + (1.0 - momentum) * var
    Y = gamma * X_hat + beta  # 拉伸和平移
    return Y, moving_mean, moving_var

 if len(X.shape) == 2:这个部分，写一个条件语句就会报错，如下：
Traceback (most recent call last):
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 79, in param_guard
    yield
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 351, in __call__
    error_data.raise_new_exception()
  File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "/Users/sunyingbin/Documents/workspace/loadforecast/models.py", line 23, in forward (* user code *)
	x = self.bn1(x)
    File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/Users/sunyingbin/Documents/workspace/loadforecast/models.py", line 74, in forward (* user code *)
	eps=1e-5, momentum=0.9, is_training=self.training)
    File "/var/folders/w1/cjkr4hz941j40gyy2mvlff4r0000gn/T/tmpe_veharj.py", line 41, in batch_norm
	moving_mean, moving_var), (X_hat, moving_mean, moving_var))
    File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
	return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
	return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/var/folders/w1/cjkr4hz941j40gyy2mvlff4r0000gn/T/tmpe_veharj.py", line 33, in false_fn_1
	false_fn_0, (X,), (X,), (mean, var))
    File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 208, in convert_ifelse
	return_vars)
    File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 231, in _run_paddle_cond
	lambda: false_fn(*false_args))
    File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/layers/control_flow.py", line 2415, in cond
	origin_false_output = false_fn()
    File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 231, in <lambda>
	lambda: false_fn(*false_args))
    File "/Users/sunyingbin/Documents/workspace/loadforecast/batch_norm.py", line 24, in batch_norm (* user code *)
	mean = paddle.mean(X, axis=(0, 2, 3), keepdim=True)
    File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/tensor/stat.py", line 105, in mean
	type='reduce_mean', inputs={'X': x}, outputs={'Out': out}, attrs=attrs)
    File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
	return self.main_program.current_block().append_op(*args, **kwargs)
    File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2942, in append_op
	attrs=kwargs.get("attrs", None))
    File "/opt/anaconda3/envs/paddleocr/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2129, in __init__
	self.desc.infer_shape(self.block.desc)
    ValueError: (InvalidArgument) The reduce dim index 1 should be in the range [-dimension(X), dimension(X)] which dimesion = 2. But received dim index = 2.
  [Hint: Expected dims[i] < x_rank, but received dims[i]:2 >= x_rank:2.] (at /home/Paddle/paddle/fluid/operators/reduce_ops/reduce_op.h:448)
  [operator < reduce_mean > error]


如果不写条件语句直接写
mean = paddle.mean(X)
var = paddle.mean((X - mean) ** 2)
就没问题了，这是为啥

**Comment by zh794390558** [comment]
```
ValueError: (InvalidArgument) The reduce dim index 1 should be in the range [-dimension(X), dimension(X)] which dimesion = 2. But received dim index = 2.
```
查下readuce_mean的调用吧
