### ISSUE TITLE
从Categorical中采样时报错

### ISSUE THREAD

**Issue by destroy314** [PaddlePaddle/Paddle#36401]
使用AIStudio的至尊版GPU环境：
PaddlePaddle版本：2.1.2，GPU：V100，cuDNN Version: 7.6

从神经网络输出的Tensor在转化为类别分布后采样：
```python
import paddle
with paddle.no_grad():
    actor=paddle.nn.Sequential(paddle.nn.Linear(20, 2800))
    logits=actor(paddle.rand([20]))
    cat=paddle.distribution.Categorical(logits.exp())
    print(cat.sample([1]))
```
此时报错： 
```python
Error: /paddle/paddle/fluid/operators/multinomial_op.cu:42 Assertion `in_data[id] >= 0.0` failed. The input of multinomial distribution should be >= 0, but got -0.038249.
（省略类似错误）
Error: /paddle/paddle/fluid/operators/multinomial_op.cu:42 Assertion `in_data[id] >= 0.0` failed. The input of multinomial distribution should be >= 0, but got -0.044257.
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    print(cat.sample([1]))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distribution.py", line 771, in sample
    sample_index = multinomial(logits, num_samples, True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/random.py", line 133, in multinomial
    'replacement', replacement)
SystemError: (Fatal) Operator multinomial raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure. (at /paddle/paddle/fluid/imperative/tracer.cc:192)
```
网络输出尺寸取其它值，如100，1000，3000，5000时不会出现这一错误

**Comment by zh794390558** [comment]
```
Error: /paddle/paddle/fluid/operators/multinomial_op.cu:42 Assertion `in_data[id] >= 0.0` failed. The input of multinomial distribution should be >= 0, but got -0.038249.
（省略类似错误）
Error: /paddle/paddle/fluid/operators/multinomial_op.cu:42 Assertion `in_data[id] >= 0.0` failed. The input of multinomial distribution should be >= 0, but got -0.044257
```

输入数据有负数

**Comment by destroy314** [comment]
> ```
> Error: /paddle/paddle/fluid/operators/multinomial_op.cu:42 Assertion `in_data[id] >= 0.0` failed. The input of multinomial distribution should be >= 0, but got -0.038249.
> （省略类似错误）
> Error: /paddle/paddle/fluid/operators/multinomial_op.cu:42 Assertion `in_data[id] >= 0.0` failed. The input of multinomial distribution should be >= 0, but got -0.044257
> ```
> 
> 输入数据有负数

输入是取指数后的结果logits.exp()，而且调用它的.min()方法得到的也是正数

**Comment by zh794390558** [comment]
已确认是底层cuda kernel计算时显存访问问题，已经排期修复。
