### ISSUE TITLE
训练时出现cudaErrorIllegalAddress

### ISSUE THREAD

**Issue by destroy314** [PaddlePaddle/Paddle#36403]
使用AIStudio的至尊版GPU环境：
PaddlePaddle版本：2.1.2，GPU：V100，cuDNN Version: 7.6

见此项目：[强化学习兵棋游戏](https://aistudio.baidu.com/aistudio/projectdetail/2408931)
项目使用PPO算法训练强化学习智能体，environment.py是类似[将军棋](https://generals.io/)的小游戏环境，运行`python com.py`进行训练。
训练几个epoch后报错：
```python
Traceback (most recent call last):
  File "com.py", line 272, in <module>
    main()
  File "com.py", line 240, in main
    pg_loss = paddle.maximum(pg_loss1, pg_loss2).mean()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/math.py", line 570, in maximum
    x, y, axis=axis, act=act, op_name=op_type)
  File "<decorator-gen-135>", line 2, in _elementwise_op_in_dygraph
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/math.py", line 179, in _elementwise_op_in_dygraph
    out = op(x, y, 'axis', axis, 'use_mkldnn', use_mkldnn)
SystemError: (Fatal) Operator elementwise_max raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered. (at /paddle/paddle/fluid/imperative/tracer.cc:192)
```

**Comment by zh794390558** [comment]
需要打开 export CUDA_LAUNCH_BLOCKING=1 这个标志，这个拦截在elementwise这里主要是thrust库的拦截的问题，但是不一定真正的错误在这块 . export FLAGS_benchmak=1 后再测试下具体位置。

**Comment by zh794390558** [comment]
可以试下develop最新版本，看是否有此问题。
