### ISSUE TITLE
RNN Module Cudnn Error CUDNN_STATUS_VERSION_MISMATCH

### ISSUE THREAD

**Issue by ZHANG-GuiGui** [PaddlePaddle/Paddle#36411]
- 版本、环境信息：
Paddle version: 2.1.2
Paddle With CUDA: True
OS: Ubuntu 18.04
Python version: 3.8.11
CUDA version: 11.1.74
Build cuda_11.1.TC455_06.29069683_0
cuDNN version: None.None.None
Nvidia driver version: 465.31

- 问题描述：
```
Traceback (most recent call last):
  File "../run_gen_pos.py", line 248, in <module>
    run(args)
  File "../run_gen_pos.py", line 151, in run
    logits = model(*inputs[:-1])
  File "/home/zxf/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zxf/paddleAbstract/pos_unimomodel.py", line 59, in forward
    gru_out, _ = self.gru(highway_out)  # Batch_size x Sequence_length x 1536
  File "/home/zxf/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zxf/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/nn/layer/rnn.py", line 1049, in forward
    return self._cudnn_impl(inputs, initial_states, sequence_length)
  File "/home/zxf/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/nn/layer/rnn.py", line 984, in _cudnn_impl
    _, _, out, state = framework.core.ops.rnn(
OSError: (External)  Cudnn error, CUDNN_STATUS_VERSION_MISMATCH  (at /paddle/paddle/fluid/operators/rnn_op.cu.cc:464)
  [operator < rnn > error]
```
在调用rnn的时候提示cudnn version mismatch，但是没有指明错误的版本和正确的版本。通过（summary_env.py）得到的版本信息中cudnn为None，而通过`conda list`和`paddle.utils.run_check()`得到的cudnn版本均为8.1。并且`paddle.utils.run_check()`没有报错。

类似问题找到#33208
但是好像没有给出解决办法。

请问如何解决？

**Comment by zh794390558** [comment]
CUDA 工具包10.1/10.2配合cuDNN v7.6+(如需多卡支持，需配合NCCL2.7及更高)

CUDA 工具包11.2配合cuDNN v8.1.1(如需多卡支持，需配合NCCL2.7及更高)

应该是cudnn的版本过高了，7.6 应该是可以的。

**Comment by ZHANG-GuiGui** [comment]
请问如何更改cudnn版本呢？它引用的应该是conda虚拟环境中的cudnn，而不是/usr/local中的cudnn。是需要conda重新install一下指定版本的cudnn吗？ @zh794390558 
不过这个cudnn版本应该是install的时候它自动安装的匹配的版本吧，为什么会出错呢？

**Comment by zh794390558** [comment]
确认 CUDA version: 11.1.74版本吧，官方说的是CUDA 工具包11.2配合cuDNN v8.1.1。具体conda的环境安装还请baidu下。
![image](https://user-images.githubusercontent.com/3038472/137241620-f3fdd706-c426-4c78-9a4c-300b49c9084c.png)
建议尝试使用对应的docker image

**Comment by ZHANG-GuiGui** [comment]
通过更新CUDA为11.2版本解决
