### ISSUE TITLE
Matting(MODNet模型)导出报错: 'Valid index accept int or slice or ellipsis, but received img. '

### ISSUE THREAD

**Issue by hhxdestiny** [PaddlePaddle/Paddle#36458]
- 版本、环境信息：
1）Platform: AI Studio 
2）PaddlePaddle版本：2.1.1
3）GPU：32G
- 模型信息
1）模型名称: MODNet
2）模型链接: [MODNet](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.3/contrib/Matting/model/modnet.py)
- 复现信息：
1）拷贝[exprot.py](PaddleSeg/export.py)到PaddleSeg/contrib/Matting下
2）修改line:141
    ```python
    if __name__ == '__main__':
    from paddleseg.cvlibs import manager
    from model import MODNet
    manager.MODELS.add_component(MODNet)
    from dataset import MattingDataset
    manager.DATASETS.add_component(MattingDataset)
    args = parse_args()
    main(args)
    ```
3)  执行
   ```bash
   python export.py --config configs/modnet/modnet.yml --model_path output/best_model/model.pdparams --save_dir output
   ```
- 问题描述：
```shell
   Traceback (most recent call last):
  File "export.py", line 148, in <module>
    main(args)
  File "export.py", line 122, in main
    paddle.jit.save(new_net, save_path)
  File "<decorator-gen-66>", line 2, in save
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 726, in save
    inner_input_spec)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 491, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 401, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 705, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-64>", line 2, in from_func_spec
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 661, in from_func_spec
    error_data.raise_new_exception()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
IndexError: In transformed code:
    File "export.py", line 74, in forward (* user code *)
        outs = self.net(x)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
        outputs = self.forward(*inputs, **kwargs)
    File "/home/aistudio/work/PaddleSeg/contrib/Matting/model/modnet.py", line 56, in forward (* user code *)
        x = inputs['img']
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1658, in __getitem__
        return _getitem_impl_(self, item)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/variable_index.py", line 187, in _getitem_impl_
        format(slice_item))
    IndexError: Valid index accept int or slice or ellipsis, but received img.
```

**Comment by wuyefeilin** [comment]
@hhxdestiny 你好，matting里模型的输入是个字典，跟paddleseg里模型略有不同，你可以在模型的forward的函数里改一下暂时先进行导出。我们后续会跟进导出这一块的功能。

有相关问题可以提到https://github.com/PaddlePaddle/PaddleSeg里，方便我们进行回答哈
