### ISSUE TITLE
AssertionError: When Variable is used as the condition of if/while , Variable can only contain one element.

### ISSUE THREAD

**Issue by anliyuan** [PaddlePaddle/Paddle#36533]
救命
self.double_conv = nn.Sequential(
            nn.Conv2D(in_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2D(out_channels),
            nn.ReLU(),
            nn.Conv2D(out_channels, out_channels, kernel_size=3, padding=1),
            nn.BatchNorm2D(out_channels),
            nn.ReLU()
        )

Traceback (most recent call last):
  File "model.py", line 99, in <module>
    out = Net(img)
  File "model.py", line 67, in __init__
    self.inc = DoubleConv(self.n_channels, ch[0])
  File "model.py", line 11, in __init__
    nn.Conv2D(in_channels=in_channels, out_channels=out_channels, kernel_size=3, padding=1),
  File "/home/yidian/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 633, in __init__
    super(Conv2D, self).__init__(
  File "/home/yidian/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 110, in __init__
    if in_channels % groups != 0:
  File "/home/yidian/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 515, in __bool__
    return self.__nonzero__()
  File "/home/yidian/anaconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 509, in __nonzero__
    assert numel == 1, "When Variable is used as the condition of if/while , Variable can only contain one element."
AssertionError: When Variable is used as the condition of if/while , Variable can only contain one element.

**Comment by wangxinxin08** [comment]
您好，可以先检查下`DoubleConv(self.n_channels, ch[0])`这里的self.n_channels和ch[0]是否是一个数值

**Comment by anliyuan** [comment]
> 您好，可以先检查下`DoubleConv(self.n_channels, ch[0])`这里的self.n_channels和ch[0]是否是一个数值

检查了一下，self.n_channels 和ch[0]都是是整型的数值，但是当我把self.n_channels直接改成一个数的时候就不会报这个错了

**Comment by wangxinxin08** [comment]
> > 您好，可以先检查下`DoubleConv(self.n_channels, ch[0])`这里的self.n_channels和ch[0]是否是一个数值
> 
> 检查了一下，self.n_channels 和ch[0]都是是整型的数值，但是当我把self.n_channels直接改成一个数的时候就不会报这个错了

您可以参考Conv2D的API，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Conv2D_cn.html#conv2d, in_channels和out_channels 都需要是一个整数

**Comment by wangxinxin08** [comment]
您好，由于你长时间未回复，我们关闭了该issue，如果你还有问题，可以重新打开
