### ISSUE TITLE
PaddlePaddle/2.1 源码编译安装时paddle.tensor问题

### ISSUE THREAD

**Issue by lansehuo** [PaddlePaddle/Paddle#36606]
平台：FT
Paddle版本：release/2.1

>>> import paddle.tensor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kylin/.local/lib/python3.5/site-packages/paddle/__init__.py", line 27, in <module>
    monkey_patch_variable()
  File "/home/kylin/.local/lib/python3.5/site-packages/paddle/fluid/layers/math_op_patch.py", line 401, in monkey_patch_variable
    variabel_methods = paddle.tensor.tensor_method_func
AttributeError: module 'paddle' has no attribute 'tensor'

**Comment by wenming2014** [comment]
您好，看问题应该没正确编译源码。我这边没有复现问题。pip安装方式
python3 -m pip install paddlepaddle==2.1.3 -i https://mirror.baidu.com/pypi/simple
源码编译参考https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html#congyuanmabianyi
