### ISSUE TITLE
打开 MKLDNN 后预测报错

### ISSUE THREAD

**Issue by LoveNingBo** [PaddlePaddle/Paddle#36738]
## 版本、环境信息：
```python
Paddle version: 2.0.0
Paddle With CUDA: True
OS: CentOS Linux 7
Python version: 3.6.13
CUDA version: 9.0.176
cuDNN version: 7.6.0
Nvidia driver version: 465.19.01
```

## 报错信息
```python
I1026 14:48:36.103977 19929 device_context.cc:515] oneDNN v1.6.0
W1026 14:48:36.137215 19929 operator.cc:206] elementwise_mul raises an exception dnnl::error, could not create a descriptor for a binary operation primitive
[2021-10-26 14:48:36,137] ERROR in app: Exception on /test/req [POST]
Traceback (most recent call last):
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/huiyanfei/conda_env/hyf_py3/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 164, in req
    res = predictor.predict(request_dict)
  File "server.py", line 101, in predict
    self.predictor.run()
RuntimeError: could not create a descriptor for a binary operation primitive
```

## 相关代码
```python
'''
@Author: your name
@Date: 2021-10-26 11:54:30
@LastEditTime: 2021-10-26 14:48:24
@LastEditors: Please set LastEditors
@Description: In User Settings Edit
@FilePath: /huiyanfei/work/Chinese-QANet-Paddle/paddle_inference/server.py
'''

'''
@Author: your name
@Date: 2021-07-06 20:27:52
@LastEditTime: 2021-10-22 18:50:37
@LastEditors: Please set LastEditors
@Description: In User Settings Edit
@FilePath: /huiyanfei/work/QANet-Paddle-master/predict.py
''' 
import os
import paddle
# paddle.set_device('cpu')
import shutil
import time
import paddle.nn as nn
import paddle.nn.functional as F 
from datetime import datetime
# from trainer.metric import convert_tokens, evaluate_by_dict 
import numpy as np
from flask import Flask
from flask import request
from flask import jsonify
import threading 
from tqdm import tqdm
from paddle.io import Dataset,DataLoader 
import sys
sys.path.append("..")
from util.file_utils import pickle_load_large_file 
from data_loader.DDQA import word2wid,char2cid
import argparse
import numpy as np
# from paddle.fluid.core import AnalysisConfig
# from paddle.fluid.core import create_paddle_predictor 
import paddle.inference as paddle_infer
paddle.set_device("cpu")

###
app = Flask(__name__) 


def convert_tokens(context, left_idx, right_idx): 
    return "".join(context.split()[left_idx:right_idx+1])

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--model_file", type=str, default = "./inference_model_new/qanet.pdmodel",help="model filename")
    parser.add_argument("--params_file", type=str, default = "./inference_model_new/qanet.pdiparams",help="parameter filename")
    parser.add_argument("--batch_size", type=int, default=1, help="batch size")
    return parser.parse_args()
 

class Predictor:
    def __init__(self):
        self.use_ema = True 
        
        args = parse_args()
        config = paddle_infer.Config(args.model_file, args.params_file)
        config.disable_gpu()
        config.switch_use_feed_fetch_ops(False)
        config.switch_specify_input_names(True) 
        config.disable_gpu()
        config.enable_mkldnn() 
        print(config.mkldnn_enabled())
        config.set_cpu_math_library_num_threads(5)
        # self.predictor = create_paddle_predictor(config)
        self.predictor = paddle_infer.create_predictor(config)

        
    def predict(self, data):
        """
        Evaluate model over development dataset.
        Return the metrics: em, f1.
        """ 
        start = time.time() 
        for batch_idx, batch in enumerate(data): 
            (context_wids, 
            question_wids) = batch   
            input_names = self.predictor.get_input_names()
            input_tensor1 = self.predictor.get_input_handle(input_names[0])
            input_tensor2 = self.predictor.get_input_handle(input_names[1])

            # 设置输入
            # fake_input1= [[13   , 1    , 20825, 14   , 16   , 49   , 4631 , 7    , 5854 , 7    , 2918 , 626  , 164  , 2813 , 71   , 4790 , 362  , 1223 , 61   , 5    , 2505 , 4    , 63789, 10084, 87617, 7491 , 7    , 517  , 24   , 2695 , 20   , 1204 , 541  , 67   , 1558 , 580  , 17   , 7    , 1    , 25   , 1    , 20   , 175  , 1    , 7535 , 5415 , 28435, 17   , 7    , 12261, 56   , 2076 , 2695 , 20   , 1204 , 1    , 21   , 31   , 43   , 109562, 23   , 256  , 7    , 25   , 4922 , 1223 , 504  , 166  , 5    , 660  , 884  , 6    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    , 0    ]]
            # fake_input2= [[9338, 24  , 4211, 211 , 1223, 1139, 0   , 0   , 0   , 0   , 0   , 0   , 0   , 0   , 0   ]+[0]*85]
            fake_input2 = question_wids
            fake_input1 = context_wids 
            print(len(fake_input1[0]))
            print(len(fake_input2[0]))
            input_tensor1.copy_from_cpu(fake_input1)
            input_tensor2.copy_from_cpu(fake_input2)

            # 运行predictor
            self.predictor.run()

            # 获取输出
            output_names = self.predictor.get_output_names()
            output_tensor = self.predictor.get_output_handle(output_names[2])
            y1 = output_tensor.copy_to_cpu().tolist() # numpy.ndarray类型
            output_tensor2 = self.predictor.get_output_handle(output_names[3])
            y2 = output_tensor2.copy_to_cpu().tolist()  # numpy.ndarray类型
  
        return y1,y2
 
def word_tokenize(sent): 
    return sent.split()
    
word_dictionary = '../datasets/processed/DDQA/word_dict.pkl'
char_dictionary = '../datasets/processed/DDQA/char_dict.pkl'

word2idx_dict = pickle_load_large_file(word_dictionary)
char2idx_dict = pickle_load_large_file(char_dictionary)

def process(request_dict):
    para_limit = 100
    ques_limit = 100
    ans_limit = 10
    num_head = 8
    d_model = 128 
    
    request_dict['ques_tokens'] = word_tokenize(request_dict['query'])
    question_wids = np.ones([1,ques_limit], dtype=np.int32) * \
            word2idx_dict["<PAD>"]
    for i, token in enumerate(request_dict["ques_tokens"]):
        if i>=ques_limit:break
        question_wids[0][i] = word2wid(token, word2idx_dict)
            
    paras = request_dict["paras"]
    examples_with_features = []
    for para in paras: 
        example = {"ques_tokens":request_dict['ques_tokens']}
        context_wids = np.ones(
            [1,para_limit], dtype=np.int32) * \
            word2idx_dict["<PAD>"] 
        example["context_tokens"] = word_tokenize(para) 
        for i, token in enumerate(example["context_tokens"]):
            if i>= para_limit:break
            context_wids[0][i] = word2wid(token, word2idx_dict)
        example["context_wids"] = context_wids.tolist()  
        example["question_wids"] = question_wids.tolist()  

        examples_with_features.append((example["context_wids"],example["question_wids"]))
 
    return examples_with_features 
 
# 全局预测器
predictor = Predictor()
@app.route('/test/req', methods=['POST','GET'])
def req():
    start =time.time()
    request_dict = request.get_json(force=True) 
    # print("request:%s"%str(request_dict))
    context_list = request_dict["paras"]
    request_dict = process(request_dict)
    # test_dataloader = get_loader(request_dict, 10, shuffle=False)
    start = time.time()
    res = predictor.predict(request_dict)
    response_dict = {"res":res} 
    # print("time:%s res:%s"%(time.time()-start,res))
    return jsonify(response_dict)

def print_heart_beat(interval):
    """
    print heart_beat log
    """
    log_cnt = 0
    while True:
        log_cnt += 1
        if log_cnt == (interval * 10):
            print("Say something ... kind of boring ... | file cut trigger")
            log_cnt = 0
        time.sleep(0.1)   

if __name__ == '__main__':
 
    extra_dict ={}
    port = 8098
    t = threading.Thread(target=print_heart_beat, args=(60,))
    t.setDaemon(True)
    t.start()
    app.run(host='0.0.0.0', debug=False, port=int(port), threaded=False)
    print ("server start finish!")

```

**Comment by baoachun** [comment]
请问有尝试最新版本的paddle吗？

**Comment by LoveNingBo** [comment]
初始环境paddle.2.0.0(对应oneDNN v1.6.0)会报错，按照paddle同学的提示升级paddle.2.1.2(对应oneDNN v2.2.1)后使用mkldnn可以得到结果，十分感谢！
