### ISSUE TITLE
【菁英计划】训练后报库文件错误，一直刷屏，没有抛出异常终止

### ISSUE THREAD

**Issue by ttjygbtj** [PaddlePaddle/Paddle#36819]
训练后一直报错如下，都是库文件的错误，没显示源文件的错误，不知道要改什么，并且一直刷屏，没有抛出异常终止
```shell
Traceback (most recent call last):
  File "/home/lc/anaconda3/envs/paddle/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/lc/anaconda3/envs/paddle/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle 'Tensor' object
```

**Comment by huangjun12** [comment]
num_works设为0之后，可以查看具体报错信息
