### ISSUE TITLE
安装最新版paddlepaddle-gpu2.1.3报错：module 'paddle' has no attribute 'enable_static'

### ISSUE THREAD

**Issue by wupaopao123** [PaddlePaddle/Paddle#36828]
安装的paddle版本：addlepaddle-gpu2.1.3
服务器： NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4
安装命令：python -m pip install paddlepaddle-gpu==2.1.3.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**最开始报错：**

Traceback (most recent call last):
  File "/raid/ly2/programming/project1/02_bilstm_crf/process_data.py", line 79, in <module>
    _test_jieba_dl_cut()
  File "/raid/ly2/programming/project1/02_bilstm_crf/process_data.py", line 17, in _test_jieba_dl_cut
    jieba.enable_paddle()
  File "/home/ly/miniconda3/envs/pytorch/lib/python3.8/site-packages/jieba/_compat.py", line 46, in enable_paddle
    import jieba.lac_small.predict as predict
  File "/home/ly/miniconda3/envs/pytorch/lib/python3.8/site-packages/jieba/lac_small/predict.py", line 43, in <module>
    infer_ret = creator.create_model(dataset.vocab_size, dataset.num_labels, mode='infer')
  File "/home/ly/miniconda3/envs/pytorch/lib/python3.8/site-packages/jieba/lac_small/creator.py", line 32, in create_model
    words = fluid.data(name='words', shape=[-1, 1], dtype='int64', lod_level=1)
  File "/home/ly/miniconda3/envs/pytorch/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ly/miniconda3/envs/pytorch/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/ly/miniconda3/envs/pytorch/lib/python3.8/site-packages/paddle/fluid/framework.py", line 242, in __impl__
    assert not in_dygraph_mode(
AssertionError: In PaddlePaddle 2.x, we turn on dynamic graph mode by default, and 'data()' is only supported in static graph mode. So if you want to use this api, please call 'paddle.enable_static()' before this api to enter static graph mode.

**之后修改**：

`import contextlib
from .wrapped_decorator import signature_safe_contextmanager, wrap_decorator
import os
import re
import traceback
import six
import copy
from types import MethodType, FunctionType

import numpy as np
import subprocess
import multiprocessing
import sys
import logging
from .. import compat as cpt
from .proto import framework_pb2

import paddle      # 添加第一行

from . import core
from . import unique_name
import paddle.version as fluid_version
import warnings
import functools
from .variable_index import _getitem_impl_, _setitem_impl_

paddle.enable_static()`    # 添加第二行

**现在报错：**

Traceback (most recent call last):
  File "/raid/ly2/programming/project1/02_bilstm_crf/process_data.py", line 79, in <module>
    _test_jieba_dl_cut()
  File "/raid/ly2/programming/project1/02_bilstm_crf/process_data.py", line 17, in _test_jieba_dl_cut
    jieba.enable_paddle()
  File "/home/ly/miniconda3/envs/pytorch/lib/python3.8/site-packages/jieba/_compat.py", line 29, in enable_paddle
    import paddle
  File "/home/ly/miniconda3/envs/pytorch/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/home/ly/miniconda3/envs/pytorch/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/ly/miniconda3/envs/pytorch/lib/python3.8/site-packages/paddle/fluid/framework.py", line 48, in <module>
    paddle.enable_static()
AttributeError: partially initialized module 'paddle' has no attribute 'enable_static' (most likely due to a circular import)

**请问该怎么办呀？**

**Comment by WorgenZhang** [comment]
您好，尝试将paddle.enable_static()放在import paddle的下面，而不是最下面
