### ISSUE TITLE
【菁英计划】AI Studio 能否选择 python3.8 及以上版本

### ISSUE THREAD

**Issue by S-HuaBomb** [PaddlePaddle/Paddle#36824]
- 标题：论文复现第 11 篇，COOT: Cooperative Hierarchical Transformer for Video-Text Representation Learning
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.0rc
    4）Python版本号：3.7

- 复现信息：在 AI Studio 上运行 paddle 版代码：[https://github.com/ImportPaddle/coot-vieotext-paddle](https://github.com/ImportPaddle/coot-vieotext-paddle)
- 问题描述：需要 python 3.8 及以上，但是 AI Studio 只能选择 python 3.7，会出现语法错误如下：

```
/home/aistudio/coot-vieotext-paddle/pd-coot/nntrainer/typext.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
Traceback (most recent call last):
  File "coot-vieotext-paddle/pd-coot/train_retrieval.py", line 6, in <module>
    from coot.configs_retrieval import ExperimentTypesConst, RetrievalConfig as Config
  File "/home/aistudio/coot-vieotext-paddle/pd-coot/coot/configs_retrieval.py", line 10, in <module>
    from nntrainer import lr_scheduler, models, optimization, trainer_configs, typext, utils
  File "/home/aistudio/coot-vieotext-paddle/pd-coot/nntrainer/models/__init__.py", line 10, in <module>
    from nntrainer.models.transformer_legacy import (
  File "/home/aistudio/coot-vieotext-paddle/pd-coot/nntrainer/models/transformer_legacy.py", line 451
    return self.layer_normalization(x), *sublayer_return[1:]
                                        ^
SyntaxError: invalid syntax
```

**Comment by huangjun12** [comment]
将个别语法转成Python3.7的写法即可
