### ISSUE TITLE
【菁英计划】paddle2.2.0rc 版的优化器 Adam optimizer 如何使用 param_groups

### ISSUE THREAD

**Issue by S-HuaBomb** [PaddlePaddle/Paddle#36874]
- 标题：第 11 篇 COOT: Cooperative Hierarchical Transformer for Video-Text Representation Learning
- 版本、环境信息：
    1）PaddlePaddle版本：paddle2.2rc

- 训练信息
    1）notebook 单机

- 复现信息：repo：https://github.com/ImportPaddle/coot-vieotext-paddle
- 问题描述：查看paddle optimizer源码，似乎可以调用 `optimizer._param_groups`  来设置 param_groups 优化方案，相应的优化器初始化的parameters参数也可以接收 [dict,...] 类型的模型参数，但是parameters参数报错了：

  - 报错paddle 代码位置： [optimization.py](https://github.com/ImportPaddle/coot-vieotext-paddle/blob/0c8211825b4d1812ab6ddd8cd593e0f7a87d0668/pd-coot/nntrainer/optimization.py#L45)
  - 引用位置：[trainer_retrieval.py](https://github.com/ImportPaddle/coot-vieotext-paddle/blob/0c8211825b4d1812ab6ddd8cd593e0f7a87d0668/pd-coot/coot/trainer_retrieval.py#L116)
  - param_group构建位置：[model_manager_base.py](https://github.com/ImportPaddle/coot-vieotext-paddle/blob/0c8211825b4d1812ab6ddd8cd593e0f7a87d0668/pd-coot/nntrainer/models/model_manager_base.py#L125)

parameters参数：

```
params: [{'params': Parameter containing:
Tensor(shape=[512, 384], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[ 0.00066618,  0.00605299,  0.00268659, ..., -0.01784501,
         -0.00613993,  0.00458619],
        [ 0.00930437, -0.00098383, -0.00171733, ..., -0.00319585,
         -0.00336399,  0.00676588],
        [-0.00253591, -0.00111721, -0.01043748, ..., -0.00683398,
          0.00531353, -0.00037463],
        ...,
        [ 0.00695124, -0.00701262, -0.01098010, ..., -0.00168518,
         -0.01033223,  0.00713493],
        [-0.01084980, -0.00181245, -0.00365885, ...,  0.00596036,
          0.00146857,  0.00420018],
        [ 0.01045176,  0.01130659,  0.00483452, ..., -0.00460148,
         -0.00946456,  0.00369506]]), 'decay_mult': 1.0}, Parameter containing:
Tensor(shape=[512, 384], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [[ 0.00066618,  0.00605299,  0.00268659, ..., -0.01784501,
```

报错信息：

```
/home/aistudio/coot-vieotext-paddle/pd-coot/nntrainer/typext.py:16: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
Source config: coot-vieotext-paddle/pd-coot/config/retrieval/paper2020/yc2_100m_coot.yaml
Results path:  experiments/retrieval/default/yc2_100m_coot
    Change config: Set use_multi_gpu to False.
Built metadata for train: 1333 datapoints, 10337 segments. Expanded 0 segments.
Built metadata for val: 457 datapoints, 3492 segments. Expanded 0 segments.
---------- Setup done!
W1030 11:47:39.479156 10182 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W1030 11:47:39.483664 10182 device_context.cc:465] device: 0, cuDNN Version: 7.6.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Logger: 'trainlog' to experiments/retrieval/default/yc2_100m_coot_run1/logs/run_2021_10_30_11_47_52.log
 INFO Running on cuda: False, multi-gpu: False, gpus found: gpu:0, fp16 amp: False.
INFO:trainlog:Running on cuda: False, multi-gpu: False, gpus found: gpu:0, fp16 amp: False.
 INFO Random seed: None
INFO:trainlog:Random seed: None
Traceback (most recent call last):
  File "coot-vieotext-paddle/pd-coot/train_retrieval.py", line 97, in <module>
    main()
  File "coot-vieotext-paddle/pd-coot/train_retrieval.py", line 80, in main
    load_epoch=args.load_epoch, load_model=args.load_model, inference_only=args.validate)
  File "/home/aistudio/coot-vieotext-paddle/pd-coot/coot/trainer_retrieval.py", line 118, in __init__
    params)
  File "/home/aistudio/coot-vieotext-paddle/pd-coot/nntrainer/optimization.py", line 73, in make_optimizer
    weight_decay=float(cfg_optim.weight_decay))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adamw.py", line 188, in __init__
    multi_precision=multi_precision)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 197, in __init__
    name=name)
  File "<decorator-gen-213>", line 2, in __init__
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 189, in __init__
    assert 'params' in param_group, \
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 233, in __impl__
    value=other_var, dtype=lhs_dtype)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 79, in create_scalar
    return create_tensor(value, dtype, shape=[1])
  File "<decorator-gen-132>", line 2, in create_tensor
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 74, in create_tensor
    value, 'force_cpu', False)
ValueError: (InvalidArgument) fill_constant(): argument (position 6) must be float, but got str (at /paddle/paddle/fluid/pybind/op_function.h:305)
```

**Comment by huangjun12** [comment]
https://github.com/ImportPaddle/coot-vieotext-paddle/blob/0c8211825b4d1812ab6ddd8cd593e0f7a87d0668/pd-coot/nntrainer/models/model_manager_base.py#L154  这一行看起来多余了，上一行已经传入value值了。

param_groups的用法可以参考这里 https://github.com/PaddlePaddle/Paddle/blob/9516108a852dcc0f14fe787045cf0eb388f41b80/python/paddle/optimizer/optimizer.py#L107
