### ISSUE TITLE
使用matmul()引发segment fault

### ISSUE THREAD

**Issue by limited-sky-3Q3q** [PaddlePaddle/Paddle#36889]
- 版本、环境信息：
    Paddle version: 2.0.2
    Paddle With CUDA: True
    OS: Ubuntu 18.04
    Python version: 3.6.9
    CUDA version: 0.2.1221(nvidia-smi cuda: 11.4)
    cuDNN version: None.None.None
    Nvidia driver version: 470.63.01

运行paddle.matmul()文档中的演示代码，发现tensor维度变化时可能会引发segment fault，测试时发现，当两个tensor维度都大于2的情况下会发生错误。

报错代码：
```
import paddle
import numpy as np

# vector * vector
# 不报错
x_data = np.random.random([10]).astype(np.float32)
y_data = np.random.random([10]).astype(np.float32)
x = paddle.to_tensor(x_data)
y = paddle.to_tensor(y_data)
z = paddle.matmul(x, y)
print(z.numpy().shape)
# [1]

# matrix * vector
# 不报错
x_data = np.random.random([10, 5]).astype(np.float32)
y_data = np.random.random([5]).astype(np.float32)
x = paddle.to_tensor(x_data)
y = paddle.to_tensor(y_data)
z = paddle.matmul(x, y)
print(z.numpy().shape)
# [10]

# batched matrix * broadcasted vector
# 不报错
x_data = np.random.random([10, 5, 2]).astype(np.float32)
y_data = np.random.random([2]).astype(np.float32)
x = paddle.to_tensor(x_data)
y = paddle.to_tensor(y_data)
z = paddle.matmul(x, y)
print(z.numpy().shape)
# [10, 5]

# batched matrix * batched matrix
#! 报错
x_data = np.random.random([10, 5, 2]).astype(np.float32)
y_data = np.random.random([10, 2, 5]).astype(np.float32)
x = paddle.to_tensor(x_data)
y = paddle.to_tensor(y_data)
z = paddle.matmul(x, y)
print(z.numpy().shape)
# [10, 5, 5]

# batched matrix * broadcasted matrix
#! 报错
x_data = np.random.random([10, 1, 5, 2]).astype(np.float32)
y_data = np.random.random([1, 3, 2, 5]).astype(np.float32)
x = paddle.to_tensor(x_data)
y = paddle.to_tensor(y_data)
z = paddle.matmul(x, y)
print(z.numpy().shape)
```

输出和报错信息：
```
W1101 10:44:24.661501  5039 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 10.0
W1101 10:44:24.665783  5039 device_context.cc:372] device: 0, cuDNN Version: 7.6.
(1,)
(10,)
(10, 5)


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1635734665 (unix time) try "date -d @1635734665" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 5039 (TID 0x7fcef22df740) from PID 0 ***]

Segmentation fault (core dumped)
```

**Comment by sljlp** [comment]
请更新到最新版paddle，这个问题在新版paddle应该已经解决

**Comment by limited-sky-3Q3q** [comment]
> 请更新到最新版paddle，这个问题在新版paddle应该已经解决

更新到最新版paddle后问题依然存在，之后再检查发现是cuda版本过低，更新cuda后即可正常使用

**Comment by skywalk163** [comment]
我这边也碰到类似的错误，是矩池云的双卡环境， 低版本不行，换到cuda 11.2版本正常。（目前2080，P100和T4都测试正常，但是P80有报错，估计是矩池云的问题的几率大。）
以下为低版本报错信息：
```
W0215 07:55:11.650157  1014 device_context.cc:465] device: 0, cuDNN Version: 7.6.
W0215 07:55:11.650208  1015 device_context.cc:465] device: 1, cuDNN Version: 7.6.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::platform::NCCLCommContext::ReleaseNCCLComms()
1   paddle::platform::NCCLCommImpl::~NCCLCommImpl()
2   paddle::platform::CUDADeviceContext::~CUDADeviceContext()
3   paddle::platform::CUDADeviceContext::~CUDADeviceContext()
4   std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
5   std::_Sp_counted_ptr<paddle::platform::CUDAContext*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
6   paddle::platform::CUDAContext::~CUDAContext()
7   cublasDestroy_v2

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1644911714 (unix time) try "date -d @1644911714" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x75) received by PID 1015 (TID 0x7fa5b3b19740) from PID 117 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::platform::NCCLCommContext::ReleaseNCCLComms()
1   paddle::platform::NCCLCommImpl::~NCCLCommImpl()
2   paddle::platform::CUDADeviceContext::~CUDADeviceContext()
3   paddle::platform::CUDADeviceContext::~CUDADeviceContext()
4   std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()
5   std::_Sp_counted_ptr<paddle::platform::CUDAContext*, (__gnu_cxx::_Lock_policy)2>::_M_dispose()
6   paddle::platform::CUDAContext::~CUDAContext()
7   cublasDestroy_v2

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1644911714 (unix time) try "date -d @1644911714" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x65) received by PID 1014 (TID 0x7f239b3cb740) from PID 101 ***]

Traceback (most recent call last):
  File "handbooksample.py", line 47, in <module>
    dist.spawn(train)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 564, in spawn
    while not context.join():
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 373, in join
    self._throw_exception(error_index)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 380, in _throw_exception
    raise Exception("Process %d terminated with signal %s." %
Exception: Process 1 terminated with signal SIGSEGV.
```
