### ISSUE TITLE
【菁英计划】单机多卡训练时backward出错

### ISSUE THREAD

**Issue by WangChen0902** [PaddlePaddle/Paddle#36895]
在进行多卡训练的时候，出现如下问题：

Traceback (most recent call last):
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/distributed/spawn.py", line 261, in _func_wrapper
    result = func(*args)
  File "/root/paddlejob/workspace/code/code/main.py", line 73, in mul_train
    algo.train(dataloader, cfg.STAGE)
  File "/mnt/code_20211101090203/code/trainer.py", line 186, in train
    errD.backward()
  File "<decorator-gen-122>", line 2, in backward
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 239, in backward
    framework._dygraph_tracer())
RuntimeError: (PreconditionNotMet) Error happened, when parameter[28][conv2d_28.b_0@GRAD] has been ready before. Please set find_unused_parameters=True to traverse backward graph in each step to prepare reduce in advance. If you have set, there may be several reasons for this error: 1) In multiple reentrant backward phase, some parameters are reused.2) Using model parameters outside of forward function. Please make sure that model parameters are not shared in concurrent forward-backward passes.
  [Hint: Expected has_marked_unused_vars_ == false, but received has_marked_unused_vars_:1 != false:0.] (at /paddle/paddle/fluid/imperative/reducer.cc:645)

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/22705546/139619667-3dad1d59-113a-433f-a234-df3aa14ac9d6.png">

**Comment by WangChen0902** [comment]
经过排查，有变量有时会参与反向传播，有时不会参与反向传播，这种情况下需要设置DataParallel的find_unused_parameters = True，问题解决

**Comment by WangChen0902** [comment]
论文号68，设置find_unused_parameters = True后，又复现了这个问题，问题还没有解决

**Comment by wangna11BD** [comment]
建议对模型内的子网络循环设置find_unused_parameters = True

**Comment by CuberrChen** [comment]
> 

遇到了类似问题，我用一个模型封装了两个子网络，不同条件下forward调用不同子网络。多卡会出现上述类似问题。
请问如何解决！急～

**Comment by sherwin-silin-chen** [comment]
> > 
> 
> 遇到了类似问题，我用一个模型封装了两个子网络，不同条件下forward调用不同子网络。多卡会出现上述类似问题。 请问如何解决！急～

同样的问题 forward时根据epoch来前向传播不同的子网络，DDP会报错，单卡可以训练
