### ISSUE TITLE
【菁英计划】lmdbDataset.__getitem__报错：Blocking queue is killed because the data reader raises an exception.

### ISSUE THREAD

**Issue by ttjygbtj** [PaddlePaddle/Paddle#36939]
报错如下：
```shell
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1635847912 (unix time) try "date -d @1635847912" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3ee000068c3) received by PID 26819 (TID 0x7f7cb3dcf700) from PID 26819 ***]

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/lc/anaconda3/envs/pd22/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 583, in _get_data
    Traceback (most recent call last):
data = self._data_queue.get(timeout=self._timeout)  File "/app/wht/lc/VisionLAN/paddle_VisionLAN/train_LA.py", line 129, in <module>

  File "/home/lc/anaconda3/envs/pd22/lib/python3.8/multiprocessing/queues.py", line 108, in get
        for batch_idx, sample_batched in enumerate(train_loader):raise Empty

  File "/home/lc/anaconda3/envs/pd22/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in __next__
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
      File "/home/lc/anaconda3/envs/pd22/lib/python3.8/threading.py", line 932, in _bootstrap_inner
data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

    self.run()
  File "/home/lc/anaconda3/envs/pd22/lib/python3.8/threading.py", line 870, in run

Process finished with exit code 1
```
源代码：
```python
# coding:utf-8
import random
from paddle.io import Dataset
import paddle.vision.transforms as transforms
import lmdb
import six
import sys
from PIL import Image
import numpy as np
import cv2

from api import ToPILImage
from .transforms import CVColorJitter, CVDeterioration, CVGeometry
import re
from random import sample

def des_orderlabel(imput_lable):
    '''
    generate the label for WCL
    '''
    if True:
        len_str = len(imput_lable)
        change_num = 1
        order = list(range(len_str))
        change_id = sample(order, change_num)[0]
        label_sub =imput_lable[change_id]
        if change_id == (len_str - 1):
            imput_lable = imput_lable[:change_id]
        else:
            imput_lable = imput_lable[:change_id] + imput_lable[change_id + 1:]
    return imput_lable, label_sub, change_id
class lmdbDataset(Dataset):
    def __init__(self, roots=None, ratio=None, img_height = 32, img_width = 128,
        transform=None, global_state='Test'):
        self.envs = []
        self.nSamples = 0
        self.lengths = []
        self.ratio = []
        self.global_state = global_state
        for i in range(0,len(roots)):
            env = lmdb.open(
                roots[i],
                max_readers=1,
                readonly=True,
                lock=False,
                readahead=False,
                meminit=False)
            if not env:
                print('cannot creat lmdb from %s' % (root))
                sys.exit(0)
            with env.begin(write=False) as txn:
                nSamples = int(txn.get('num-samples'.encode()))
                self.nSamples += nSamples
            self.lengths.append(nSamples)
            self.envs.append(env)

        if ratio != None:
            assert len(roots) == len(ratio) ,'length of ratio must equal to length of roots!'
            for i in range(0,len(roots)):
                self.ratio.append(ratio[i] / float(sum(ratio)))
        else:
            for i in range(0,len(roots)):
                self.ratio.append(self.lengths[i] / float(self.nSamples))
        self.transform = transform
        self.maxlen = max(self.lengths)
        self.img_height = img_height
        self.img_width = img_width
        self.target_ratio = img_width / float(img_width)
        self.min_size = (img_width * 0.5, img_width * 0.75, img_width)

        self.augment_tfs = transforms.Compose([
            CVGeometry(degrees=45, translate=(0.0, 0.0), scale=(0.5, 2.), shear=(45, 15), distortion=0.5, p=0.5),
            CVDeterioration(var=20, degrees=6, factor=4, p=0.25),
            CVColorJitter(brightness=0.5, contrast=0.5, saturation=0.5, hue=0.1, p=0.25)
        ])
    def __fromwhich__(self ):
        rd = random.random()
        total = 0
        for i in range(0,len(self.ratio)):
            total += self.ratio[i]
            if rd <= total:
                return i
    def keepratio_resize(self, img, is_train):
        if is_train == 'Train':
            img = self.augment_tfs(img)
        img = cv2.resize(np.array(img), (self.img_width, self.img_height))
        img = ToPILImage(transforms)(img)
        return img

    def __len__(self):
        return self.nSamples

    def __getitem__(self, index):
        fromwhich = self.__fromwhich__()
        if self.global_state == 'Train':
            index = random.randint(0,self.maxlen - 1)
        index = index % self.lengths[fromwhich]
        assert index <= len(self), 'index range error'
        index += 1
        with self.envs[fromwhich].begin(write=False) as txn:
            img_key = 'image-%09d' % index
            try:
                imgbuf = txn.get(img_key.encode())
                buf = six.BytesIO()
                buf.write(imgbuf)
                buf.seek(0)
                img = Image.open(buf).convert('RGB')
            except:
                print('Corrupted image for %d' % index)
                return self[index + 1]
            label_key = 'label-%09d' % index
            label = str(txn.get(label_key.encode()))
            # if python3
            # label = str(txn.get(label_key.encode()), 'utf-8')
            label = re.sub('[^0-9a-zA-Z]+', '', label)
            
            if (len(label) > 25 or len(label) <= 0) and self.global_state == 'Train':
                print('sample too long')
                return self[index + 1]
            try:
                img = self.keepratio_resize(img, self.global_state)
            except:
                print('Size error for %d' % index)
                return self[index + 1]
            if self.transform:
                img = self.transform(img)
            # generate masked_id masked_character remain_string
            label_res, label_sub, label_id =  des_orderlabel(label)
            sample = {'image': img, 'label': label, 'label_res': label_res, 'label_sub': label_sub, 'label_id': label_id}
            return sample
```

**Comment by WenmuZhou** [comment]
你好，我这边在aistudio上面测试了没问题，你那边可以再确认一下哈
