### ISSUE TITLE
长度为 1 的 Tensor 无法用 bool 取值

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#36940]
```bash
>>> import paddle
>>> y = paddle.to_tensor([1,2])
>>> temp = paddle.to_tensor([True,False])
>>> y[temp]
Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [1])
>>> y = paddle.to_tensor([1])
>>> temp = paddle.to_tensor([True])
>>> y[temp]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuantian01/yt_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 594, in __getitem__
    return _getitem_impl_(self, item)
  File "/home/yuantian01/yt_py37/lib/python3.7/site-packages/paddle/fluid/variable_index.py", line 463, in _getitem_impl_
    attrs=attrs)
  File "/home/yuantian01/yt_py37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3249, in append_op
    kwargs.get("stop_gradient", False))
  File "/home/yuantian01/yt_py37/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) The dtype of Tensor in list must be int32 or int64, but received: 0 (at /paddle/paddle/fluid/operators/utils.h:85)
  [operator < slice > error]
```

**Comment by FeixLiu** [comment]
对于temp的shape为[1]的时候，框架认为该variable是int/scalar，走了与shape不为1时不同的代码逻辑。是否会更新该逻辑使之支持您列出的问题，我们内部会安排评估，未来有计划尽快回复。

**Comment by CuberrChen** [comment]
@FeixLiu 
 请问这个问题有没有暂时的解决办法？我也遇到了相同的问题

**Comment by FeixLiu** [comment]
感谢您的反馈~这里的问题我们在最新的develop代码分支里已经支持https://github.com/PaddlePaddle/Paddle/pull/37761 预计在后续的正式版本中发布。
如果赶时间的话可以直接拉取最新的develop分支代码编译进行使用，编译流程可以参考这里https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html
