### ISSUE TITLE
【菁英计划】#80 paddle2.2 python3.8 import reprod_log报错Can not import avx core while this file exists

### ISSUE THREAD

**Issue by ttjygbtj** [PaddlePaddle/Paddle#36955]
```shell 报错
ssh://lc@211.81.55.150:20036/home/lc/anaconda3/envs/pt22/bin/python3 -u /app/wht/lc/VisionLAN/check/check.py
Error: Can not import avx core while this file exists: /home/lc/anaconda3/envs/pt22/lib/python3.8/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "/app/wht/lc/VisionLAN/check/check.py", line 5, in <module>
    from reprod_log import ReprodDiffHelper
  File "/home/lc/anaconda3/envs/pt22/lib/python3.8/site-packages/reprod_log/__init__.py", line 16, in <module>
    from .ReprodDiffHelper import ReprodDiffHelper
  File "/home/lc/anaconda3/envs/pt22/lib/python3.8/site-packages/reprod_log/ReprodDiffHelper.py", line 19, in <module>
    from .utils import init_logger, check_print_diff
  File "/home/lc/anaconda3/envs/pt22/lib/python3.8/site-packages/reprod_log/utils.py", line 19, in <module>
    import paddle
  File "/home/lc/anaconda3/envs/pt22/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/home/lc/anaconda3/envs/pt22/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/lc/anaconda3/envs/pt22/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/lc/anaconda3/envs/pt22/lib/python3.8/site-packages/paddle/fluid/core.py", line 294, in <module>
    raise e
  File "/home/lc/anaconda3/envs/pt22/lib/python3.8/site-packages/paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/lc/anaconda3/envs/pt22/lib/python3.8/site-packages/paddle/fluid/core_avx.so)

Process finished with exit code 1
```
```Python 代码
import os
import pickle

import numpy as np
from reprod_log import ReprodDiffHelper
from reprod_log import ReprodLogger

print(__file__)
SEED = 100
import paddle

paddle.seed(SEED)
np.random.seed(SEED)


def torchRes():
    result = {}
    from torch import nn
    import torch
    import pytorch_VisionLAN.cfgs.cfgs_LF_2 as cfgs
    from pytorch_VisionLAN.train_LA import load_network
    from pytorch_VisionLAN.train_LA import generate_optimizer
    from pytorch_VisionLAN.train_LA import Train_or_Eval, flatten_label, _flatten, Zero_Grad, test
    from pytorch_VisionLAN.utils import Attention_AR_counter, cha_encdec
    torch.manual_seed(SEED)
    model = load_network()
    optimizer, optimizer_scheduler = generate_optimizer(model)
    criterion_CE = nn.CrossEntropyLoss().cuda()
    L1_loss = nn.L1Loss().cuda()
    # tools prepare
    train_acc_counter = Attention_AR_counter('train accuracy: ', cfgs.dataset_cfgs['dict_dir'],
                                             cfgs.dataset_cfgs['case_sensitive'])
    train_acc_counter_rem = Attention_AR_counter('train accuracy: ', cfgs.dataset_cfgs['dict_dir'],
                                                 cfgs.dataset_cfgs['case_sensitive'])
    train_acc_counter_sub = Attention_AR_counter('train accuracy: ', cfgs.dataset_cfgs['dict_dir'],
                                                 cfgs.dataset_cfgs['case_sensitive'])
    encdec = cha_encdec(cfgs.dataset_cfgs['dict_dir'], cfgs.dataset_cfgs['case_sensitive'])
    # train
    loss_show = 0
    ratio_res = 0.5
    ratio_sub = 0.5
    best_acc = 0
    loss_ori_show = 0
    loss_mas_show = 0
    for iter, params in enumerate(params_):
        # data_prepare
        data = params['data']
        label = params['label']  # original string
        label_res = params['label_res']  # remaining string
        label_sub = params['label_sub']  # occluded character
        label_id = params['label_id']  # character index

        target = encdec.encode(label)
        target_res = encdec.encode(label_res)
        target_sub = encdec.encode(label_sub)
        Train_or_Eval(model, 'Train')
        data = data.cuda()
        label_flatten, length = flatten_label(target)
        label_flatten_res, length_res = flatten_label(target_res)
        label_flatten_sub, length_sub = flatten_label(target_sub)
        target, label_flatten, target_res, target_sub, label_flatten_res = target.cuda(), label_flatten.cuda(), target_res.cuda(), target_sub.cuda(), label_flatten_res.cuda()
        label_flatten_sub, label_id = label_flatten_sub.cuda(), label_id.cuda()
        # prediction
        text_pre, text_rem, text_mas, att_mask_sub = model(data, label_id, cfgs.global_cfgs['step'])
        if iter == 0:
            result['forword'] = [text_pre, text_rem, text_mas, att_mask_sub]
        if iter == 1:
            result['backword'] = [text_pre, text_rem, text_mas, att_mask_sub]
            return result
        # loss_calculation
        if cfgs.global_cfgs['step'] == 'LF_1':
            pre_ori, label_ori = train_acc_counter.add_iter(**params['train_acc_counter'])
            loss_ori = criterion_CE(**params['loss_ori'])
            loss = loss_ori
        else:
            pre_ori, label_ori = train_acc_counter.add_iter(**params['train_acc_counter'])
            pre_rem, label_rem = train_acc_counter_rem.add_iter(**params['train_acc_counter_rem'])
            pre_sub, label_sub = train_acc_counter_sub.add_iter(**params['train_acc_counter_sub'])

            loss_ori = criterion_CE(**params['loss_ori'])
            loss_res = criterion_CE(**params['loss_res'])
            loss_mas = criterion_CE(**params['loss_mas'])
            loss = loss_ori + loss_res * ratio_res + loss_mas * ratio_sub
            loss_ori_show += loss_res
            loss_mas_show += loss_mas
        # loss for display
        loss_show += loss
        if iter == 0:
            result['loss'] = loss
        # optimize
        Zero_Grad(model)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 20, 2)
        optimizer.step()
        best_train_acc, _ = train_acc_counter.show_test(best_acc)
        best_train_acc_rem, _ = train_acc_counter_rem.show_test(best_acc)
        best_train_acc_sub, _ = train_acc_counter_sub.show_test(best_acc)
        result['acc'] = [best_train_acc, best_train_acc_rem, best_train_acc_sub]
        optimizer_scheduler.step()


def paddleRes():
    result = {}
    import paddle
    from paddle import nn
    import paddle_VisionLAN.cfgs.cfgs_LF_2 as cfgs
    from paddle_VisionLAN.train_LA import load_network
    from paddle_VisionLAN.train_LA import generate_optimizer
    from paddle_VisionLAN.train_LA import Train_or_Eval, flatten_label, _flatten, Zero_Grad, test
    from paddle_VisionLAN.utils import Attention_AR_counter, cha_encdec
    from paddle_VisionLAN.api import clip_grad_norm_
    paddle.seed(SEED)
    model = load_network()
    optimizer, optimizer_scheduler = generate_optimizer(model)
    criterion_CE = nn.CrossEntropyLoss()
    L1_loss = nn.L1Loss()
    # tools prepare
    train_acc_counter = Attention_AR_counter('train accuracy: ', cfgs.dataset_cfgs['dict_dir'],
                                             cfgs.dataset_cfgs['case_sensitive'])
    train_acc_counter_rem = Attention_AR_counter('train accuracy: ', cfgs.dataset_cfgs['dict_dir'],
                                                 cfgs.dataset_cfgs['case_sensitive'])
    train_acc_counter_sub = Attention_AR_counter('train accuracy: ', cfgs.dataset_cfgs['dict_dir'],
                                                 cfgs.dataset_cfgs['case_sensitive'])
    encdec = cha_encdec(cfgs.dataset_cfgs['dict_dir'], cfgs.dataset_cfgs['case_sensitive'])
    # train
    loss_show = 0
    ratio_res = 0.5
    ratio_sub = 0.5
    best_acc = 0
    loss_ori_show = 0
    loss_mas_show = 0
    for iter, params in enumerate(params_):
        # data_prepare
        data = params['data']
        label = params['label']  # original string
        label_res = params['label_res']  # remaining string
        label_sub = params['label_sub']  # occluded character
        label_id = params['label_id']  # character index

        target = encdec.encode(label)
        target_res = encdec.encode(label_res)
        target_sub = encdec.encode(label_sub)
        Train_or_Eval(model, 'Train')
        data = data
        label_flatten, length = flatten_label(target)
        label_flatten_res, length_res = flatten_label(target_res)
        label_flatten_sub, length_sub = flatten_label(target_sub)
        target, label_flatten, target_res, target_sub, label_flatten_res = target, label_flatten, target_res, target_sub, label_flatten_res
        label_flatten_sub, label_id = label_flatten_sub, label_id
        # prediction
        text_pre, text_rem, text_mas, att_mask_sub = model(data, label_id, cfgs.global_cfgs['step'])
        if iter == 0:
            result['forword'] = [text_pre, text_rem, text_mas, att_mask_sub]
        if iter == 1:
            result['backword'] = [text_pre, text_rem, text_mas, att_mask_sub]
            return result
        # loss_calculation
        if cfgs.global_cfgs['step'] == 'LF_1':
            pre_ori, label_ori = train_acc_counter.add_iter(**params['train_acc_counter'])
            loss_ori = criterion_CE(**params['loss_ori'])
            loss = loss_ori
        else:
            pre_ori, label_ori = train_acc_counter.add_iter(**params['train_acc_counter'])
            pre_rem, label_rem = train_acc_counter_rem.add_iter(**params['train_acc_counter_rem'])
            pre_sub, label_sub = train_acc_counter_sub.add_iter(**params['train_acc_counter_sub'])

            loss_ori = criterion_CE(**params['loss_ori'])
            loss_res = criterion_CE(**params['loss_res'])
            loss_mas = criterion_CE(**params['loss_mas'])
            loss = loss_ori + loss_res * ratio_res + loss_mas * ratio_sub
            loss_ori_show += loss_res
            loss_mas_show += loss_mas
        # loss for display
        loss_show += loss
        if iter == 0:
            result['loss'] = loss
        # optimize
        Zero_Grad(model)
        loss.backward()
        clip_grad_norm_(model.parameters(), 20, 2)
        optimizer.step()
        best_train_acc, _ = train_acc_counter.show_test(best_acc)
        best_train_acc_rem, _ = train_acc_counter_rem.show_test(best_acc)
        best_train_acc_sub, _ = train_acc_counter_sub.show_test(best_acc)
        result['acc'] = [best_train_acc, best_train_acc_rem, best_train_acc_sub]
        optimizer_scheduler.step()


def main():
    reprod_log_1 = ReprodLogger()
    reprod_log_2 = ReprodLogger()

    pytorch_res = torchRes()
    paddle_res = paddleRes()

    for k in pytorch_res:
        print(type(pytorch_res[k]))
        reprod_log_1.add(k, pytorch_res[k])
        reprod_log_1.save(f"{k}_torch.npy")

        print(type(paddle_res[k]))
        reprod_log_2.add(k, paddle_res[k])
        reprod_log_2.save(f"{k}_paddle.npy")
        check(k)


def check(k):
    diff_helper = ReprodDiffHelper()
    info1 = diff_helper.load_info(f"{k}/{k}_torch.npy")
    info2 = diff_helper.load_info(f"{k}/{k}_paddle.npy")
    diff_helper.compare_info(info1, info2)
    diff_helper.report(
        diff_method="mean", diff_threshold=1e-6, path=f"{f}/diff-{k}.txt")


if __name__ == "__main__":
    with open('../params.pkl', 'rb') as f:
        params_ = pickle.load(f)
    main()
```

**Comment by WenmuZhou** [comment]
https://blog.csdn.net/qq_30653631/article/details/107620137  看一下这篇博客
