### ISSUE TITLE
同样的代码win10可以运行（GPU版），AIstudio运行报错

### ISSUE THREAD

**Issue by henryccl** [PaddlePaddle/Paddle#36963]
我在根据
https://aistudio.baidu.com/aistudio/projectdetail/1938423
![image](https://user-images.githubusercontent.com/44051761/140023513-6a5d85e8-8a83-49cf-8946-4cf470f1696f.png)
里面的流程，在不同的平台上调用swin transformer出了错。
一开始我在自己的win10笔记本上写好代码微调ppdet文件后运行，发现可以运行没有问题。
![image](https://user-images.githubusercontent.com/44051761/140023880-31da95e3-64f4-4ded-aca1-021363ca8d19.png)

随后我要把写好的代码放到AIstudio上运行时，却报出了如下的错误
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:143: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W1103 15:27:54.706117   465 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W1103 15:27:54.711261   465 device_context.cc:372] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    out = net(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/backbones/swin_transformer.py", line 663, in forward
    x = x['image']
ValueError: (InvalidArgument) Currently, VarBase.__getitem__() only allows indexing by Integers, Slices, and tuples of these types, but received str in 1th slice item
  [Hint: Expected PyCheckInteger(slice_item) || ((((PyObject*)(slice_item))->ob_type) == &PySlice_Type) == true, but received PyCheckInteger(slice_item) || ((((PyObject*)(slice_item))->ob_type) == &PySlice_Type):0 != true:1.] (at /paddle/paddle/fluid/pybind/imperative.cc:378)

**Comment by henryccl** [comment]
在这个问题中，我只是调用了ppdet中的SwinTranformer模型，然后使用一个tensor测试前向传播。在win10中可以运行，但是AIstudio不行，怎么会这样，我该怎么解决呢？
from ppdet.modeling.backbones import SwinTransformer

在官方发布的PaddleDetection中的ppdet模块中是没有这个swin transformer的backbone的实现的，该模块是aistudio中的一个用户写的， 但是调用该模块的目标检测项目是可以直接运行的（亲测可用，win10和aistudio都能运行，代码应该没问题）。

当我想把swin迁移到其他项目（语义分割）上时，这样写报错了，是我调用的姿势不对吗？？？
![image](https://user-images.githubusercontent.com/44051761/140025315-681c0c2d-6490-42a2-b970-b2c87cde229b.png)

**Comment by henryccl** [comment]
emmm   应该是我自己搞错了  在win10上有修改源码jiang将swin transformer中的forward中的x = x["image"]注释掉即可
![image](https://user-images.githubusercontent.com/44051761/140026481-e4a55266-5bb1-4c94-adb2-6e2803628750.png)
