### ISSUE TITLE
Tensor形参传递，出现Cuda Error

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#37092]
Platform: AIStudio
Version: 2.1.2

仓库https://aistudio.baidu.com/aistudio/projectdetail/2580805

运行前执行如下命令
```
pip install gputil
mkdir /home/aistudio/.config/Ultralytics/
cp /home/aistudio/Arial.ttf /home/aistudio/.config/Ultralytics/
```

运行命令
```
cd YOLOv5-Paddle
python train.py --data ./data/guangshan.yaml --cfg yolov5s.yaml --batch-size 1 --device 0 --epochs 100 --weights None
```

发现`train.py`332行计算损失传入pred在`utils/loss.py中183行出现显存泄露
```
Traceback (most recent call last):
  File "train.py", line 645, in <module>
    main(opt)
  File "train.py", line 542, in main
    train(opt.hyp, opt, device, callbacks)
  File "train.py", line 332, in train
    loss, loss_items = compute_loss(pred, targets)  # loss scaled by batch_size
  File "/home/aistudio/YOLOv5-Paddle/utils/loss.py", line 120, in __call__
    tcls, tbox, indices, anchors = self.build_targets(p, targets)  # targets
  File "/home/aistudio/YOLOv5-Paddle/utils/loss.py", line 189, in build_targets
    gain[2:6] = paddle.to_tensor(p[i].shape).index_select(paddle.to_tensor([3, 2, 3, 2])).astype('float32')
  File "<decorator-gen-127>", line 2, in to_tensor
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py", line 160, in to_tensor
    stop_gradient=stop_gradient)
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)

terminate called without an active exception
      0/99 3.91e-07G    0.1258   0.05493         0         5       640:  50%|██████████████████████████████████                                  | 2/4 [00:03<00:03,  1.78s/it]


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1636530830 (unix time) try "date -d @1636530830" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e8000029d6) received by PID 10710 (TID 0x7f35effff700) from PID 10710 ***]

Aborted (core dumped)
```

**Comment by GuoQuanhao** [comment]
这个issue迟迟无回应，由于build_targets没有梯度，我将build_targets全被改为numpy运算，这算是解决了我的问题
