### ISSUE TITLE
运行 PaddleSpeech 报错，cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device.

### ISSUE THREAD

**Issue by ZZHHogan** [PaddlePaddle/Paddle#37134]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu                  2.2.0
    2）CPU：请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库的使用情况
    3）GPU：3090显卡，cuda版本cuda11.1
    4）系统环境：centos、Python版本：3.8.1
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 安装方式信息：
按照 https://www.paddlepaddle.org.cn/documentation/docs/zh/1.5/beginners_guide/install/install_CentOS.html
按照并测试，没有问题。
- 复现信息：按照PaddleSpeech的readme的指令运行后报错 
- 指令为 FLAGS_allocator_strategy=naive_best_fit FLAGS_fraction_of_gpu_memory_to_use=0.01 python3 ${BIN_DIR}/synthesize_e2e.py --fastspeech2-config=fastspeech2_nosil_baker_ckpt_0.4/default.yaml --fastspeech2-checkpoint=fastspeech2_nosil_baker_ckpt_0.4/snapshot_iter_76000.pdz --fastspeech2-stat=fastspeech2_nosil_baker_ckpt_0.4/speech_stats.npy --pwg-config=pwg_baker_ckpt_0.4/pwg_default.yaml --pwg-checkpoint=pwg_baker_ckpt_0.4/pwg_snapshot_iter_400000.pdz --pwg-stat=pwg_baker_ckpt_0.4/pwg_stats.npy --text=${BIN_DIR}/../sentences.txt --output-dir=exp/default/test_e2e --inference-dir=exp/default/inference --phones-dict=fastspeech2_nosil_baker_ckpt_0.4/phone_id_map.txt
应该和readme上的一致

报错信息：
Traceback (most recent call last):
File "/usr/local/notebook_dir/图像/TTS/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/synthesize_e2e.py", line 185, in
main()
File "/usr/local/notebook_dir/图像/TTS/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/synthesize_e2e.py", line 181, in main
evaluate(args, fastspeech2_config, pwg_config)
File "/usr/local/notebook_dir/图像/TTS/PaddleSpeech/paddlespeech/t2s/exps/fastspeech2/synthesize_e2e.py", line 51, in evaluate
model = FastSpeech2(
File "/usr/local/notebook_dir/图像/TTS/PaddleSpeech/paddlespeech/t2s/models/fastspeech2/fastspeech2.py", line 166, in init
encoder_input_layer = nn.Embedding(
File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 1386, in init
self.weight = self.create_parameter(
File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 423, in create_parameter
return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 373, in create_parameter
return self.main_program.global_block().create_parameter(
File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3137, in create_parameter
initializer(param, self)
File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 561, in call
op = block.append_op(
File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3163, in append_op
_dygraph_tracer().trace_op(type,
File "/root/.jupyter/Paddlepaddle-2.0.0/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
self.trace(type, inputs, outputs, attrs,
SystemError: (Fatal) Operator uniform_random raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at /paddle/paddle/fluid/imperative/tracer.cc:221)
- 运行以上指令报错：cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device.可是安装完paddle后执行fluid.install_check.run_check()没有问题

之前提的issue
https://github.com/PaddlePaddle/PaddleSpeech/issues/991

**Comment by zhangbo9674** [comment]
您好，我了解到paddle2.2版本刚刚发布，确定安装的是2.2版本的paddle么？

**Comment by yt605155624** [comment]
> 您好，我了解到paddle2.2版本刚刚发布，确定安装的是2.2版本的paddle么？

看报错信息是 2.0.0

**Comment by zhangbo9674** [comment]
你好，2.0.0应该还不支持CUDA11.1。
