### ISSUE TITLE
梯度回传报错

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/Paddle#37209]
代码如下所示：
start_logits, end_logits = model.forward_interpret(*args)
start_logit = start_logits[:, start_index].sum()
start_logit.backward(retain_graph=False)
embedded_start_grad = embedded.grad
model.clear_gradients()

start_logits, end_logits = model.forward_interpret(*args)
end_logit = end_logits[:, end_index].sum()
end_logit.backward(retain_graph=False)
embedded_end_grad = embedded.grad
model.clear_gradients()

model.forward_interpret(*args)必须调用两遍。仅调用一遍时，第二次backward会报如下错误：

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<decorator-gen-128>", line 2, in backward
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zs_py38/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zs_py38/lib/python3.8/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/home/work/zhangao/ZoooSP/python/miniconda3/envs/zs_py38/lib/python3.8/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 248, in backward
    core.dygraph_run_backward([self], [grad_tensor], retain_graph,
RuntimeError: (AlreadyExists) Accumulators are not empty before preparing it for backward network execution.
  [Hint: Expected accumulators_.empty() == true, but received accumulators_.empty():0 != true:1.] (at /paddle/paddle/fluid/imperative/basic_engine.cc:55)`

**Comment by thisjiang** [comment]
您好，可以尝试修改`start_logit.backward(retain_graph=False)` --> `start_logit.backward(retain_graph=True)`，请参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/autograd/backward_cn.html#backward 实现，谢谢

**Comment by zhangyimi** [comment]
感谢，十分高效！
