### ISSUE TITLE
调用GPU进行模型推理时，报了如下的错误，求帮忙解答一下。环境：paddlepaddle-gpu：2.1.3 ，python3.8，cuda10.2，cudnn7.6.5

### ISSUE THREAD

**Issue by Easonshow** [PaddlePaddle/Paddle#37364]
Traceback (most recent call last):
  File "angle_rectify_sample_gpu.py", line 265, in <module>
    Angle.RotationRepair(black_border, save_path)
  File "angle_rectify_sample_gpu.py", line 225, in RotationRepair
    angle_list, roate_state = self.text_sys(image_temp)
  File "/HDD/xcd/angle_rectify/tools/infer/predict_system.py", line 113, in __call__
    img_crop_list, angle_list, elapse = self.text_classifier(
  File "/HDD/xcd/angle_rectify/tools/infer/predict_cls.py", line 100, in __call__
    self.predictor.run()
OSError: (External)  Cublas error, `CUBLAS_STATUS_EXECUTION_FAILED`. The GPU program failed to execute. This is often caused by a launch failure of the kernel on the GPU, which can be caused by multiple reasons.  (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:35)
  [operator < fc > error]

**Comment by huangxu96** [comment]
您好，请问方便提供代码和环境信息吗，我们复现后会尽快回复您～
