### ISSUE TITLE
grid_sampler 算子丢失 shape 信息

### ISSUE THREAD

**Issue by Latalio** [PaddlePaddle/Paddle#37436]
- 版本、环境信息：
    1）PaddlePaddle版本：2.2
    2）CPU环境
    3）系统环境：Windows 10 , Python 3.9

- 问题：**grid_sampler 或 affine_grid 算子的输出 shape 在编译器应该就可以确定，为何会丢失 H, W 维度的 shape 信息**
- 代码目的：连续对图像进行空间变换（spatial transform）
- 可复现片段
```import paddle
import paddle.fluid as fluid
import numpy as np

paddle.enable_static()

def stn(image, theta):

    grid = fluid.layers.affine_grid(theta, image.shape)

    out = fluid.layers.grid_sampler(x=image, grid=grid)

    return out

image = fluid.data('image', [1, 3, 32, 32], dtype='float32')
theta = fluid.data('theta', [1, 2, 3], dtype='float32')

out = image
for i in range(3):
    out = stn(out, theta)
    print(out.shape)

device = fluid.CPUPlace()
exe = fluid.Executor(device)

exe.run(fluid.default_startup_program())

data = {}
data['image'] = np.array(np.random.rand(1, 3, 32, 32), dtype='float32')
data['theta'] = np.array(np.random.rand(1, 2, 3), dtype='float32')

exe.run(program=fluid.default_main_program(),
        feed=data)
```

- 报错信息
```
C:\Users\miniconda3\envs\paddle\python.exe D:/Projects/imagefusion_test/tools/test2.py
(1, 3, -1, -1)
(1, 3, -1, -1)
(1, 3, -1, -1)
C:\Users\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py:1279: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
Traceback (most recent call last):
  File "D:\Projects\imagefusion_test\tools\test2.py", line 35, in <module>
    exe.run(program=fluid.default_main_program(),
  File "C:\Users\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1246, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\miniconda3\envs\paddle\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1234, in run
    return self._run_impl(
  File "C:\Users\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1366, in _run_impl
    return self._run_program(
  File "C:\Users\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\executor.py", line 1463, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
RuntimeError: In user code:

    File "D:\Projects\imagefusion_test\tools\test2.py", line 23, in <module>
      out = stn(out, theta)
    File "D:\Projects\imagefusion_test\tools\test2.py", line 11, in stn
      grid = fluid.layers.affine_grid(theta, image.shape)
    File "C:\Users\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\layers\nn.py", line 9351, in affine_grid
      helper.append_op(
    File "C:\Users\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "C:\Users\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 3178, in append_op
      op = Operator(
    File "C:\Users\miniconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1] now
      [Hint: Expected numel() >= 0, but received numel():-1 < 0:0.] (at C:\home\workspace\Paddle_release\paddle\fluid\framework\tensor.cc:59)
      [operator < affine_grid > error]

Process finished with exit code 1
```

**Comment by Latalio** [comment]
一种解决方案是使用 paddle.reshape 指明输出 tensor 的 shape

```
def stn(image, theta):

    grid = fluid.layers.affine_grid(theta, image.shape)

    out = fluid.layers.grid_sampler(x=image, grid=grid)

    out = paddle.reshape(out, image.shape)

    return out
```

**Comment by Ligoml** [comment]
推荐使用paddle最新版本中的`paddle.nn.functional.grid_sample `
