### ISSUE TITLE
Tensor not initialized yet when Tensor::place() is called

### ISSUE THREAD

**Issue by ppy-hellowd** [PaddlePaddle/Paddle#37582]
Paddle-fluid 1.5.0 / py3.6.4

    def test_train_dygraph(params=Params):

      with D.guard():
          # input
          data_reader = MyDataReader(FLIST)
          # layers defined
          c_embed = StateEmbedding(params, name_scope="c_state_emb")
          actor = Actor(params)
          actor_op = OP.AdagradOptimizer(learning_rate=params['actor_learning_rate'])
          limit = min(3, params["max_steps"])
          for i in range(limit):
              S1, A1, R1, S2 = data_reader.next_batch()
              s1, a1, r1, s2 = Get_variable(S1, A1, R1, S2)
              label_a1 = base.to_variable(A1)
              # get loss
              c_state_embed = c_embed(s1[0], s1[1], s1[2], s1[3], s1[4], s1[5], s1[6], s1[7])
              action_pred = actor(c_state_embed) # predict action
              print("action pred by actor: ", action_pred)
              aloss = L.cross_entropy(input=action_pred, label=label_a1)
              print("actor loss vector: ", aloss)
              aloss_mean = L.reduce_mean(aloss)
              print("actor loss mean: ", aloss_mean)
              actor_op.minimize(aloss_mean)
              c_embed.clear_gradients()
              actor.clear_gradients()
              print("finish step {}".format(i))
    if __name__ == "__main__":
        #train()
        test_train_dygraph()

执行结果：
action pred by actor:  name tmp_31, dtype: VarType.FP32 shape: [10, 4] 	lod: {}
	dim: 10, 4
	layout: NCHW
	dtype: float
	data: [0.53004 0.0619888 0.0149845 0.392986 0.392579 0.549193 0.0243641 0.0338636 0.388597 0.1491 0.323565 0.138737 0.00885332 0.68479 0.174379 0.131978 0.0972298 0.363435 0.0379183 0.501417 0.194809 0.490121 0.0711259 0.243944 0.120558 0.520827 0.333216 0.025399 0.225029 0.664208 0.0566911 0.0540724 0.787723 0.102603 0.0549177 0.0547568 0.351577 0.444836 0.0779248 0.125662]

actor loss vector:  name tmp_32, dtype: VarType.FP32 shape: [10, 1] 	lod: {}
	dim: 10, 1
	layout: NCHW
	dtype: float
	data: [0.933981 3.38542 1.90314 2.02512 1.01216 0.713103 3.67304 2.91743 2.90485 2.07416]

actor loss mean:  name tmp_35, dtype: VarType.FP32 shape: [1] 	lod: {}
	dim: 1
	layout: NCHW
	dtype: float
	data: [2.15424]

Traceback (most recent call last):
  File "main.py", line 216, in <module>
    test_train_dygraph()
  File "main.py", line 206, in test_train_dygraph
    actor_op.minimize(aloss_mean)
  File "<decorator-gen-20>", line 2, in minimize
  File "/ssd2/pengpeiyan/tools/python36/lib/python3.6/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/ssd2/pengpeiyan/tools/python36/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 88, in __impl__
    return func(*args, **kwargs)
  File "/ssd2/pengpeiyan/tools/python36/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 600, in minimize
    loss, startup_program=startup_program, params_grads=params_grads)
  File "/ssd2/pengpeiyan/tools/python36/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 557, in apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/ssd2/pengpeiyan/tools/python36/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 376, in _create_optimization_pass
    param_and_grad)
  File "/ssd2/pengpeiyan/tools/python36/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 1228, in _append_optimize_op
    stop_gradient=True)
  File "/ssd2/pengpeiyan/tools/python36/lib/python3.6/site-packages/paddle/fluid/framework.py", line 1739, in append_op
    kwargs.get("stop_gradient", False))
  File "/ssd2/pengpeiyan/tools/python36/lib/python3.6/site-packages/paddle/fluid/dygraph/tracer.py", line 59, in trace_op
    framework._current_expected_place(), stop_gradient)
paddle.fluid.core_avx.EnforceNotMet: holder_ should not be null
Tensor not initialized yet when Tensor::place() is called. at [/paddle/paddle/fluid/framework/tensor.h:133]
PaddlePaddle Call Stacks: 
0       0x7f676c7a7b88p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f676c7a7ed7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f676c9881c9p paddle::imperative::GetExpectedPlace(boost::variant<paddle::platform::CUDAPlace,

**Comment by zhangting2020** [comment]
您使用的是1.5版本的Paddle，看报错怀疑是旧版本AdagradOptimizer的bug，我们在后来的版本中曾修复过 `Tensor not initialized yet when Tensor::place() is called`这样的问题。建议您使用新版本。
