### ISSUE TITLE
loss.backward()计算得到反向梯度，opt.step()更新参数报错

### ISSUE THREAD

**Issue by txx-899** [PaddlePaddle/Paddle#37736]
将PaddleDetection里的ppyotiny模型复现出来训练时，loss.backward()能计算出反向梯度，但opt.step()报如下错误：
ValueError: (InvalidArgument) Cannot get attribute (value) by type float, its type is class std::vector<int,class std::allocator<int> >. (at C:\home\workspace\Paddle_release\paddle/fluid/framework/attribute.h:164)
具体如下：
Traceback (most recent call last):
  File "E:/Users/Administrator/PycharmProjects/my_ppyolo/mytrain/train.py", line 54, in <module>
    opt.step()
  File "<decorator-gen-198>", line 2, in step
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-196>", line 2, in step
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\framework.py", line 227, in __impl__
    return func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\optimizer\adam.py", line 365, in step
    optimize_ops = self._apply_optimize(
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\optimizer\optimizer.py", line 796, in _apply_optimize
    optimize_ops = self._create_optimization_pass(params_grads)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\optimizer\optimizer.py", line 623, in _create_optimization_pass
    self._append_optimize_op(target_block, param_and_grad)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\optimizer\adam.py", line 266, in _append_optimize_op
    lr = self._create_param_lr(param_and_grad)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\optimizer\optimizer.py", line 458, in _create_param_lr
    return self._global_learning_rate() * param_lr
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 219, in __impl__
    other_var = create_scalar(value=other_var, dtype=lhs_dtype)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 79, in create_scalar
    return create_tensor(value, dtype, shape=[1])
  File "<decorator-gen-126>", line 2, in create_tensor
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 73, in create_tensor
    out = core.ops.fill_constant(out, 'dtype', dtype, 'shape', shape,
ValueError: (InvalidArgument) Cannot get attribute (value) by type float, its type is class std::vector<int,class std::allocator<int> >. (at C:\home\workspace\Paddle_release\paddle/fluid/framework/attribute.h:164)

请教大家，该如何解决或从哪排查

**Comment by txx-899** [comment]
采用了最简单的优化器 opt = paddle.optimizer.Adam(learning_rate=0.1,parameters=model.parameters())
用源码的优化器也报同样的错误

**Comment by yaoxuefeng6** [comment]
看报错像是某个op的输入类型有问题

**Comment by txx-899** [comment]
> 看报错像是某个op的输入类型有问题

请问一下，若是输入类型问题，为什么前向计算和梯度计算不受影响呢？谢谢
