### ISSUE TITLE
论文复现：多机多卡训练报错

### ISSUE THREAD

**Issue by jordan2013** [PaddlePaddle/Paddle#37797]
- 标题：论文复现：多机多卡训练报错
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.0
    2）CPU：未使用
    3）GPU：请提供GPU型号:Nvidia A100、CUDA版本号:11.1.74 CUDNN版本号:8.1
    4）系统环境：Ubuntu 20.04，Python版本:3.8.12
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）多机，多卡
    2）显存信息：40M
    3）Operator信息：root
- 复现信息：1.单机多卡训练正常
                     2.多机多卡训练出错
python3 -m paddle.distributed.launch --ips="192.168.1.2,192.168.1.3" --gpus 0,1  main_multi_gpu_pretrain.py -cfg='./configs/mae_base_patch16_224.yaml' -dataset='imagenet2012' -batch_size=256 -data_path='/root/datasets/ILSVRC2012/'

- 问题描述：
INFO:local_logger:----- world_size = 1, local_rank = 0
INFO:master_logger:----- world_size = 1, local_rank = 0
Traceback (most recent call last):
  File "main_multi_gpu_pretrain.py", line 517, in <module>
    main()
  File "main_multi_gpu_pretrain.py", line 513, in main
    dist.spawn(main_worker, args=(config, dataset_train, dataset_val, ), nprocs=config.NGPUS)
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 564, in spawn
    while not context.join():
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 373, in join
    self._throw_exception(error_index)
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 391, in _throw_exception
    raise Exception(msg)
Exception: 

----------------------------------------------
Process 0 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 322, in _func_wrapper
    result = func(*args)
  File "/root/MAE/MAE/main_multi_gpu_pretrain.py", line 308, in main_worker
    model = build_model(config)
  File "/root/MAE/MAE/mae.py", line 232, in build_mae
    model = MAE(img_size=config.DATA.IMAGE_SIZE,
  File "/root/MAE/MAE/mae.py", line 141, in __init__
    self.encoder = MAEEncoder(
  File "/root/MAE/MAE/mae.py", line 21, in __init__
    self.patch_embedding = PatchEmbedding(img_size,
  File "/root/MAE/MAE/transformer.py", line 71, in __init__
    self.patch_embedding = nn.Conv2D(in_channels=in_channels,
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 643, in __init__
    super(Conv2D, self).__init__(
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 132, in __init__
    self.weight = self.create_parameter(
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 423, in create_parameter
    return self._helper.create_parameter(temp_attr, shape, dtype, is_bias,
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 373, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 355, in __call__
    op = block.append_op(
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3163, in append_op
    _dygraph_tracer().trace_op(type,
  File "/root/miniconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 43, in trace_op
    self.trace(type, inputs, outputs, attrs,
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:101)
  [operator < gaussian_random > error]

**Comment by huangjun12** [comment]
```txt
NotImplementedError: (Unimplemented) Place CUDAPlace(0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU or WITH_ASCEND_CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:101)
```
报错提示使用的paadle不是gpu版本。使用多机多卡，请chekc下使用的是gpu版本的paddle，同时编译的时候加了`--WITH_DISTRIBUTE`参数，表示编译带有分布式版本的paddle
