### ISSUE TITLE
paddle 动态图转静态图报错

### ISSUE THREAD

**Issue by Fujiaoji** [PaddlePaddle/Paddle#37820]
- 版本、环境信息：
    1）
                  Paddle version: 2.1.1
                  Paddle With CUDA: True
                  Python version: 3.7.10
                  CUDA version: 9.0.176
                  cuDNN version: None.None.None-->这个在下面报错那里有版本信息，这个用的注释执行出来的结果
                  Nvidia driver version: 418.39

 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。

---错误详情：动态图转静态图，动态图可以运行，paddle.jit.save不可以保存模型；本地动态图与静态图都可以；

+ /home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/bin/python -u run.py --mode=train --use_cuda --feat=none --preprocess --model_files=model_files/baidu/model --train_data_path=data/ceshi0.txt --valid_data_path=data/ceshi0.txt --test_data_path=data/ceshi0.txt --encoding_model=ernie-1.0 --batch_size=1 --max_len=30
INFO:root:Preprocess the data
INFO:ddparser0.ernie.tokenizing_ernie:pretrain dir ./ernie/ not in {'ernie-1.0': 'https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz', 'ernie-lstm': 'https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz', 'ernie-2.0-en': 'https://ernie-github.cdn.bcebos.com/model-ernie2.0-en.1.tar.gz', 'ernie-2.0-large-en': 'https://ernie-github.cdn.bcebos.com/model-ernie2.0-large-en.1.tar.gz', 'ernie-tiny': 'https://ernie-github.cdn.bcebos.com/model-ernie_tiny.1.tar.gz', 'ernie-gen-base-en': 'https://ernie-github.cdn.bcebos.com/model-ernie-gen-base-en.1.tar.gz', 'ernie-gen-large-en': 'https://ernie-github.cdn.bcebos.com/model-ernie-gen-large-en.1.tar.gz'}, read from local
INFO:root:dumping fileds to disk.
INFO:root:Override the default configs
--------------------------+--------------------------
Param                     |           Value          
--------------------------+--------------------------
n_embed                   |            300           
embed_dropout             |           0.33           
n_mlp_arc                 |            500           
n_mlp_rel                 |            100           
mlp_dropout               |           0.33           
n_feat_embed              |            60            
n_char_embed              |            50            
n_lstm_feat_embed         |            100           
n_lstm_hidden             |            300           
n_tran_hidden             |            300           
n_lstm_layers             |             3            
lstm_dropout              |           0.33           
n_tran_feat_embed         |            120           
n_tran_feat_head          |            12            
n_tran_feat_layer         |             2            
n_tran_word_head          |            12            
n_tran_word_layer         |             3            
warmup_proportion         |            0.1           
weight_decay              |           0.01           
lstm_by_wp_embed_size     |            200           
lstm_lr                   |           0.002          
ernie_lr                  |           5e-05          
mu                        |            0.9           
nu                        |            0.9           
epsilon                   |           1e-12          
decay                     |           0.75           
decay_steps               |           5000           
epochs                    |             2            
patience                  |             1            
min_freq                  |             1            
fix_len                   |             5            
clip                      |            1.0           
mode                      |           train          
config_path               |        config.ini        
model_files               |  model_files/baidu/model 
train_data_path           |      data/ceshi0.txt     
valid_data_path           |      data/ceshi0.txt     
test_data_path            |      data/ceshi0.txt     
pred_data_path            |      data/ceshi0.txt     
infer_data_path           |      data/result.txt     
batch_size                |             1            
max_len                   |            30            
log_path                  |         ./log/log        
log_level                 |           INFO           
infer_result_path         |       infer_result       
use_cuda                  |           True           
preprocess                |           True           
use_data_parallel         |           False          
seed                      |             1            
threads                   |            16            
tree                      |           False          
prob                      |           False          
feat                      |           none           
encoding_model            |         ernie-1.0        
pretrain_model_dir        |         ./ernie/         
buckets                   |           None           
punct                     |           False          
None                      |           False          
nranks                    |             1            
local_rank                |             0            
fields_path               | model_files/baidu/model/fields
model_path                | model_files/baidu/model/model
ernie_vocabs_size         |           17964          
n_words                   |           17964          
n_feats                   |           None           
n_rels                    |             5            
pad_index                 |             0            
unk_index                 |           17963          
bos_index                 |             1            
eos_index                 |             2            
feat_pad_index            |           None           
--------------------------+--------------------------

INFO:root:(word): ErnieField(pad=[PAD], unk=[UNK], bos=[CLS], eos=[SEP])
None
(head): Field(bos=<bos>, eos=<eos>, use_vocab=False)
(deprel): Field(bos=<bos>, eos=<eos>)
INFO:root:Set the max num of threads to 16
INFO:root:Set the seed for generating random numbers to 1
INFO:root:Run the subcommand in mode train
INFO:root:loading data.
INFO:root:init dataset.
INFO:root:set the data loaders.
INFO:root:train:     1 sentences,   1 batches,   1 batch_size, 
INFO:root:dev:       1 sentences,   1 batches, 
INFO:root:test:      1 sentences,   1 batches, 
INFO:root:Create the model
INFO:ddparser0.ernie.modeling_ernie:pretrain dir ./ernie/ not in {'ernie-1.0': 'https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz', 'ernie-lstm': 'https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz', 'ernie-2.0-en': 'https://ernie-github.cdn.bcebos.com/model-ernie2.0-en.1.tar.gz', 'ernie-2.0-large-en': 'https://ernie-github.cdn.bcebos.com/model-ernie2.0-large-en.1.tar.gz', 'ernie-tiny': 'https://ernie-github.cdn.bcebos.com/model-ernie_tiny.1.tar.gz'}, read from local
W1203 11:57:23.169701 192569 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.1, Runtime API Version: 10.1
W1203 11:57:23.174546 192569 device_context.cc:422] device: 0, cuDNN Version: 7.4.
W1203 11:57:25.825425 192569 device_context.h:361] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.4, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
INFO:ddparser0.ernie.modeling_ernie:loading pretrained model from ./ernie/
INFO:root:start training.
INFO:root:Epoch 1 / 2:
/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:239: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.bool, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:239: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int32, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
INFO:root:epoch: 1, batch: 1/1, batch_size: 1, loss: 6.0781
/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
w1
Traceback (most recent call last):
  File "run.py", line 710, in <module>
    train(env)
  File "run.py", line 173, in train
    save(args.model_path, args, model, optimizer)
  File "/home/qu/rd/sunyibo/intern/jifujiao/ddparser_ernie/ddparser0/parser0/model.py", line 516, in save
    path=path)
  File "<decorator-gen-67>", line 2, in save
  File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 719, in save
    inner_input_spec)
  File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AttributeError: In transformed code:

    File "/home/qu/rd/sunyibo/intern/jifujiao/ddparser_ernie/ddparser0/parser0/model.py", line 93, in forward (* user code *)
        _, x = self.ernie(words)
    File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 228, in convert_call
        forward_func = convert_to_static(forward_func)
    File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 141, in convert_to_static
        static_func = _FUNCTION_CACHE.convert_with_cache(function)
    File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 78, in convert_with_cache
        static_func = self._convert(func)
    File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 122, in _convert
        create_and_update_origin_info_map(root_wrapper.node, static_func)
    File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/origin_info.py", line 163, in create_and_update_origin_info_map
        for t_node, s_node in ast_walk(transformed_node, static_node):
    File "/home/map/tools/paddle_release_home/paddle_gpu211_py37_gcc82/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/origin_info.py", line 241, in ast_walk
        t_node_child = getattr(t_node, field)
    AttributeError: 'Assign' object has no attribute 'type_comment'

**Comment by Fujiaoji** [comment]
动态图训练，仅保存静态图参数用于推理

**Comment by LDOUBLEV** [comment]
1.  可以安装最新的paddle2.2版本再次运行动转静；
2. 如果完成步骤1后仍报错，请提供您报错的模型组网代码，方便问题定位；（如果能提供最小模型复现函数最好）

**Comment by Fujiaoji** [comment]
> * 可以安装最新的paddle2.2版本再次运行动转静；
> * 如果完成步骤1后仍报错，请提供您报错的模型组网代码，方便问题定位；（如果能提供最小模型复现函数最好）

好的，谢谢，我先试试版本，不行再来

**Comment by Fujiaoji** [comment]
可以了，换了个版本就可以了，谢谢
