### ISSUE TITLE
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'eager'

### ISSUE THREAD

**Issue by wozna** [PaddlePaddle/Paddle#37986]
On recent develop: commit aff7397bbf2290c8cdff2e2b2202cbb286d3ae93
I get the following error while importing paddle or paddle.fluid.core
```
Traceback (most recent call last):
  File "save_quant_model.py", line 19, in <module>
    import paddle
  File "/usr/local/lib/python3.6/dist-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/__init__.py", line 217, in <module>
    monkey_patch_eagertensor()
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/eager/eager_tensor_patch_methods.py", line 23, in monkey_patch_eagertensor
    setattr(core.eager.EagerTensor, "__str__", __str__)
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'eager'
```

Build flags: 
```
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6
```

**Comment by haozech** [comment]
您好，问题已收到，会转给相关同学

**Comment by Ligoml** [comment]
用户你好，develop分支为开发分支，不稳定，可能会遇到bug并修复bug。建议编译时使用稳定分支~
