### ISSUE TITLE
在jetson nano 上使用trt为 tinypose_128x96 模型做推理 ，加载模型时出错

### ISSUE THREAD

**Issue by Reatris** [PaddlePaddle/Paddle#38159]
1）官方提供的 linux-cuda10.2-cudnn8.1-trt7-gcc8.2 安装包
2）paddlepaddle-gpu (2.1.1)
3）系统环境：Python3.6

我安装了这个包在jetson nano 上使用trt为 tinypose_128x96 模型做推理， 在加载模型的时候报错了
保存信息如下：
```
I1215 15:19:17.817080 10085 graph_pattern_detector.cc:91] ---  detected 172 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
I1215 15:19:18.639354 10085 graph_pattern_detector.cc:91] ---  detected 173 subgraphs
--- Running IR pass [tensorrt_subgraph_pass]
I1215 15:19:20.456756 10085 tensorrt_subgraph_pass.cc:137] ---  detect a sub-graph with 136 nodes
I1215 15:19:20.530040 10085 tensorrt_subgraph_pass.cc:377] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
E1215 15:19:20.637236 10085 helper.h:84] ../builder/cudnnBuilderGraphOptimizer.cpp (3121) - Assertion Error in mergeDAG: 0 (d1Inputs.size() == n1.inputs.size())
Traceback (most recent call last):
  File "mian.py", line 16, in <module>
    action_master = ActionMaster()
  File "mian.py", line 8, in __init__
    self.tiny_pose = TinyPose()
  File "/home/xshl/nanoserve/Model_api/TinyPose.py", line 19, in __init__
    'model/tinypose_128x96/',use_trt=True)
  File "/home/xshl/nanoserve/Model_api/TinyPose.py", line 58, in init_predictor
    predictor = inference.create_predictor(config)
SystemError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::inference::tensorrt::TensorRTEngine::FreezeNetwork()
13  paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
14  paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Build TensorRT cuda engine failed! Please recheck you configurations related to paddle-TensorRT.
  [Hint: infer_engine_ should not be null.] (at /home/paddle/data/wangye19/Paddle/paddle/fluid/inference/tensorrt/engine.cc:242)
```

**Comment by Reatris** [comment]
这是我加载模型的部分
```
model_file = model_dir + 'model.pdmodel'
        params_file = model_dir + 'model.pdiparams'
        print('loading model from {} ...'.format(model_dir))
        # model_file = model_dir + '__model__'
        # params_file = model_dir + '__params__'
        config = inference.Config()
        config.set_prog_file(model_file)
        config.set_params_file(params_file)
        if use_trt:
            # 启用 TensorRT 进行预测加速 - FP16 Nano 上不支持 Int8 预测
            config.enable_use_gpu(100, 0)  # use free
            config.enable_tensorrt_engine(workspace_size=1 << 30,
                                          max_batch_size=5,
                                          min_subgraph_size=3,
                                          precision_mode=inference.PrecisionType.Half,
                                          use_static=True, use_calib_mode=False)
            # 通过 API 获取 TensorRT 启用结果 - true
            print("Enable TensorRT is: {}".format(config.tensorrt_engine_enabled()))
        else:
            config.use_gpu()
```

**Comment by thunder95** [comment]
大佬用起来咋样， 我使用这个模型时感觉效果不太好

**Comment by Reatris** [comment]
> 大佬用起来咋样， 我使用这个模型时感觉效果不太好

正在尝试提高推理速度，我的速度只有130ms  trt加速也只有47ms

**Comment by jiangjiajun** [comment]
@Reatris 当前已解决TRT加速问题了吗

**Comment by Reatris** [comment]
> @Reatris 当前已解决TRT加速问题了吗

更换了Jetpack4.6 TRT加速出现错误
使用的paddlepaddle-gpu 版本为官方的版本paddlepaddle_gpu-2.2.1-cp36-cp36m-linux_aarch64.whl

报错信息如下

```
/usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
loading model from ../model/picodet_s_192_pedestrian/ ...
W1216 16:54:28.416855  8330 analysis_predictor.cc:798] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1216 16:54:29.418275  8330 fuse_pass_base.cc:57] ---  detected 68 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
--- Running IR pass [map_matmul_v2_to_matmul_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [fc_elementwise_layernorm_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I1216 16:54:29.987197  8330 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I1216 16:54:30.879029  8330 analysis_predictor.cc:717] ======= optimize end =======
I1216 16:54:30.926586  8330 naive_executor.cc:98] ---  skip [feed], feed -> image
I1216 16:54:30.955647  8330 naive_executor.cc:98] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
I1216 16:54:30.955729  8330 naive_executor.cc:98] ---  skip [save_infer_model/scale_1.tmp_1], fetch -> fetch
I1216 16:54:30.955746  8330 naive_executor.cc:98] ---  skip [save_infer_model/scale_2.tmp_1], fetch -> fetch
I1216 16:54:30.955762  8330 naive_executor.cc:98] ---  skip [save_infer_model/scale_3.tmp_1], fetch -> fetch
I1216 16:54:30.955778  8330 naive_executor.cc:98] ---  skip [save_infer_model/scale_4.tmp_1], fetch -> fetch
I1216 16:54:30.955792  8330 naive_executor.cc:98] ---  skip [save_infer_model/scale_5.tmp_1], fetch -> fetch
I1216 16:54:30.955826  8330 naive_executor.cc:98] ---  skip [save_infer_model/scale_6.tmp_1], fetch -> fetch
I1216 16:54:30.955848  8330 naive_executor.cc:98] ---  skip [save_infer_model/scale_7.tmp_1], fetch -> fetch
model ../model/picodet_s_192_pedestrian/ has 1 inputs tensor 8 outputs tensor
W1216 16:54:31.022316  8330 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 5.3, Driver API Version: 10.2, Runtime API Version: 10.2
W1216 16:54:31.163849  8330 device_context.cc:465] device: 0, cuDNN Version: 8.2.
^CTraceback (most recent call last):
  File "Picodet.py", line 101, in <module>
    tp.infer([image])
  File "Picodet.py", line 82, in infer
    self.picodet.run()
KeyboardInterrupt
xshl@xshl-desktop:~/nanoserve/Model_api$ rz -b
rz waiting to receive.**xshl@xshl-desktop:~/nanoserve/Model_api$ python3 Picodet.py 
/usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
loading model from ../model/picodet_s_192_pedestrian/ ...
Enable TensorRT is: True
W1216 16:55:35.297677  8717 analysis_predictor.cc:798] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I1216 16:55:35.513557  8717 analysis_predictor.cc:579] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
I1216 16:55:35.917910  8717 fuse_pass_base.cc:57] ---  detected 13 subgraphs
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
W1216 16:55:35.973495  8717 shuffle_channel_detect_pass.cc:126] There is fluid.layers.shuffle_channel API already, maybe you can use it instead of (reshape + transpose + reshape)
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1216 16:55:36.495867  8717 fuse_pass_base.cc:57] ---  detected 68 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
--- Running IR pass [map_matmul_v2_to_matmul_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I1216 16:55:36.925348  8717 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 240 nodes
I1216 16:55:37.163525  8717 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1216 16:55:40.864883  8717 engine.cc:84] Run Paddle-TRT FP16 mode
W1216 16:55:47.214929  8717 helper.h:107] Detected invalid timing cache, setup a local cache instead
E1216 16:57:26.352558  8717 helper.h:111] 10: [optimizer.cpp::computeCosts::1855] Error Code 10: Internal Error (Could not find any implementation for node 2-layer MLP: conv2d (Output: conv2d_138.tmp_183) + relu (Output: relu_0.tmp_085) -> conv2d (Output: conv2d_139.tmp_191).)
E1216 16:57:26.352972  8717 helper.h:111] 2: [builder.cpp::buildSerializedNetwork::417] Error Code 2: Internal Error (Assertion enginePtr != nullptr failed.)


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::inference::analysis::TensorRtSubgraphPass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::inference::analysis::TensorRtSubgraphPass::CreateTensorRTOp(paddle::framework::ir::Node*, paddle::framework::ir::Graph*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > >*) const
11  paddle::inference::tensorrt::OpConverter::ConvertBlockToTRTEngine(paddle::framework::BlockDesc*, paddle::framework::Scope const&, std::vector<std::string, std::allocator<std::string > > const&, std::unordered_set<std::string, std::hash<std::string >, std::equal_to<std::string >, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&, paddle::inference::tensorrt::TensorRTEngine*)
12  paddle::inference::tensorrt::TensorRTEngine::FreezeNetwork()

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1639645046 (unix time) try "date -d @1639645046" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x8) received by PID 8717 (TID 0x7fb4d7c010) from PID 8 ***]

Segmentation fault (core dumped)
```

**Comment by jiangjiajun** [comment]
@Reatris 你好，这个问题已经解决了吗，看你close掉了这个issue

**Comment by Reatris** [comment]
> @Reatris 你好，这个问题已经解决了吗，看你close掉了这个issue

并没有，我在使用trt加载模型的时候，第一个模型能加载，保存模型序列化也正常，但是第二个模型加载的时候就不能序列化保存，每次都需要转化

**Comment by Reatris** [comment]
> @Reatris 你好，这个问题已经解决了吗，看你close掉了这个issue

错误信息如下

```
/usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
loading model from model/picodet_s_192_pedestrian/ ...
Enable TensorRT is: True
W1217 10:37:39.165199 20834 analysis_predictor.cc:798] The one-time configuration of analysis predictor failed, which may be due to native predictor called first and its configurations taken effect.
I1217 10:37:39.378808 20834 analysis_predictor.cc:579] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
I1217 10:37:39.788355 20834 fuse_pass_base.cc:57] ---  detected 13 subgraphs
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
W1217 10:37:39.850471 20834 shuffle_channel_detect_pass.cc:126] There is fluid.layers.shuffle_channel API already, maybe you can use it instead of (reshape + transpose + reshape)
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1217 10:37:40.420258 20834 fuse_pass_base.cc:57] ---  detected 68 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
--- Running IR pass [map_matmul_v2_to_matmul_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I1217 10:37:40.870415 20834 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 240 nodes
I1217 10:37:51.217907 20834 tensorrt_subgraph_pass.cc:385] Load TRT Optimized Info from model/picodet_s_192_pedestrian/_opt_cache//trt_serialized_11774546365011309457
I1217 10:37:51.260113 20834 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 15 nodes
I1217 10:37:51.323359 20834 tensorrt_subgraph_pass.cc:385] Load TRT Optimized Info from model/picodet_s_192_pedestrian/_opt_cache//trt_serialized_1419903167609048086
I1217 10:37:51.329583 20834 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 137 nodes
I1217 10:37:51.601054 20834 tensorrt_subgraph_pass.cc:385] Load TRT Optimized Info from model/picodet_s_192_pedestrian/_opt_cache//trt_serialized_10097047475177779212
--- Running IR pass [conv_bn_fuse_pass]
--- Running IR pass [conv_elementwise_add_act_fuse_pass]
--- Running IR pass [conv_elementwise_add2_act_fuse_pass]
--- Running IR pass [transpose_flatten_concat_fuse_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
I1217 10:37:51.751818 20834 ir_params_sync_among_devices_pass.cc:45] Sync params from CPU to GPU
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I1217 10:37:52.537331 20834 analysis_predictor.cc:717] ======= optimize end =======
I1217 10:37:52.584563 20834 naive_executor.cc:98] ---  skip [feed], feed -> image
I1217 10:37:52.587783 20834 naive_executor.cc:98] ---  skip [save_infer_model/scale_0.tmp_1], fetch -> fetch
I1217 10:37:52.587859 20834 naive_executor.cc:98] ---  skip [save_infer_model/scale_1.tmp_1], fetch -> fetch
I1217 10:37:52.587877 20834 naive_executor.cc:98] ---  skip [save_infer_model/scale_2.tmp_1], fetch -> fetch
I1217 10:37:52.587893 20834 naive_executor.cc:98] ---  skip [save_infer_model/scale_3.tmp_1], fetch -> fetch
I1217 10:37:52.587909 20834 naive_executor.cc:98] ---  skip [save_infer_model/scale_4.tmp_1], fetch -> fetch
I1217 10:37:52.587935 20834 naive_executor.cc:98] ---  skip [save_infer_model/scale_5.tmp_1], fetch -> fetch
I1217 10:37:52.587998 20834 naive_executor.cc:98] ---  skip [save_infer_model/scale_6.tmp_1], fetch -> fetch
I1217 10:37:52.588017 20834 naive_executor.cc:98] ---  skip [save_infer_model/scale_7.tmp_1], fetch -> fetch
model model/picodet_s_192_pedestrian/ has 1 inputs tensor 8 outputs tensor
loading model from model/tinypose_128x96/ ...
Enable TensorRT is: True
I1217 10:37:53.099571 20834 analysis_predictor.cc:579] TensorRT subgraph engine is enabled
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [conv_affine_channel_fuse_pass]
--- Running IR pass [adaptive_pool2d_convert_global_pass]
--- Running IR pass [conv_eltwiseadd_affine_channel_fuse_pass]
--- Running IR pass [shuffle_channel_detect_pass]
--- Running IR pass [quant_conv2d_dequant_fuse_pass]
--- Running IR pass [delete_quant_dequant_op_pass]
--- Running IR pass [delete_quant_dequant_filter_op_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [embedding_eltwise_layernorm_fuse_pass]
--- Running IR pass [multihead_matmul_fuse_pass_v2]
--- Running IR pass [multihead_matmul_fuse_pass_v3]
--- Running IR pass [skip_layernorm_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I1217 10:37:58.579047 20834 fuse_pass_base.cc:57] ---  detected 172 subgraphs
--- Running IR pass [unsqueeze2_eltwise_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_v2_to_mul_pass]
--- Running IR pass [map_matmul_v2_to_matmul_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [conv_elementwise_add_fuse_pass]
--- Running IR pass [tensorrt_subgraph_pass]
I1217 10:38:00.222807 20834 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 82 nodes
I1217 10:38:00.268771 20834 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1217 10:38:00.323668 20834 engine.cc:84] Run Paddle-TRT FP16 mode
W1217 10:38:00.368896 20834 helper.h:107] Detected invalid timing cache, setup a local cache instead
I1217 10:40:51.028406 20834 tensorrt_subgraph_pass.cc:416] Save TRT Optimized Info to model/tinypose_128x96/_opt_cache//trt_serialized_1124554245862683585
I1217 10:40:51.053553 20834 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 5 nodes
I1217 10:40:51.073618 20834 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1217 10:40:52.324230 20834 engine.cc:84] Run Paddle-TRT FP16 mode
W1217 10:40:52.341272 20834 helper.h:107] Detected invalid timing cache, setup a local cache instead
I1217 10:40:56.251981 20834 tensorrt_subgraph_pass.cc:416] Save TRT Optimized Info to model/tinypose_128x96/_opt_cache//trt_serialized_10080599998167725833
I1217 10:40:56.261128 20834 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 73 nodes
I1217 10:40:56.300571 20834 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1217 10:40:56.344997 20834 engine.cc:84] Run Paddle-TRT FP16 mode
W1217 10:40:56.377036 20834 helper.h:107] Detected invalid timing cache, setup a local cache instead
I1217 10:41:54.027459 20834 tensorrt_subgraph_pass.cc:416] Save TRT Optimized Info to model/tinypose_128x96/_opt_cache//trt_serialized_7993196703248762131
I1217 10:41:54.059257 20834 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 82 nodes
I1217 10:41:54.104527 20834 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1217 10:41:54.154747 20834 engine.cc:84] Run Paddle-TRT FP16 mode
W1217 10:41:54.191932 20834 helper.h:107] Detected invalid timing cache, setup a local cache instead
I1217 10:42:10.031926 20834 tensorrt_subgraph_pass.cc:416] Save TRT Optimized Info to model/tinypose_128x96/_opt_cache//trt_serialized_7998963703947932761
I1217 10:42:10.063655 20834 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 61 nodes
I1217 10:42:10.097442 20834 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1217 10:42:10.131402 20834 engine.cc:84] Run Paddle-TRT FP16 mode
W1217 10:42:10.171836 20834 helper.h:107] Detected invalid timing cache, setup a local cache instead
I1217 10:42:22.586680 20834 tensorrt_subgraph_pass.cc:416] Save TRT Optimized Info to model/tinypose_128x96/_opt_cache//trt_serialized_13649998049063354483
I1217 10:42:22.611065 20834 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 117 nodes
I1217 10:42:22.676146 20834 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1217 10:42:22.753453 20834 engine.cc:84] Run Paddle-TRT FP16 mode
W1217 10:42:22.799280 20834 helper.h:107] Detected invalid timing cache, setup a local cache instead
I1217 10:42:48.184006 20834 tensorrt_subgraph_pass.cc:416] Save TRT Optimized Info to model/tinypose_128x96/_opt_cache//trt_serialized_913936399857672150
I1217 10:42:48.237613 20834 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 44 nodes
I1217 10:42:48.268055 20834 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1217 10:42:48.295974 20834 engine.cc:84] Run Paddle-TRT FP16 mode
W1217 10:42:48.318909 20834 helper.h:107] Detected invalid timing cache, setup a local cache instead
```

**Comment by jiangjiajun** [comment]
上面这里没看到错误信息，是最后出错了吗，出错的日志是什么呢？

**Comment by Reatris** [comment]
> 上面这里没看到错误信息，是最后出错了吗，出错的日志是什么呢？

并不是报错，而是运行异常
```
I1217 10:38:00.222807 20834 tensorrt_subgraph_pass.cc:138] ---  detect a sub-graph with 82 nodes
I1217 10:38:00.268771 20834 tensorrt_subgraph_pass.cc:395] Prepare TRT engine (Optimize model structure, Select OP kernel etc). This process may cost a lot of time.
I1217 10:38:00.323668 20834 engine.cc:84] Run Paddle-TRT FP16 mode
W1217 10:38:00.368896 20834 helper.h:107] Detected invalid timing cache, setup a local cache instead
```
这里本来是应该读取保存的 cache的，然而它还是在做转换

**Comment by jiangjiajun** [comment]
你可以将`use_static`设为True，这样会在下次加载时读取cache

**Comment by Reatris** [comment]
> 你可以将`use_static`设为True，这样会在下次加载时读取cache
设置了。我加载了两个模型，一个有效，一个无效，总是后面 那个模型无效

**Comment by Reatris** [comment]
我又来了，这个问题又出现了，现在我用的TRT7，又出现这个问题了，上次是换TRT8 解决的 @jiangjiajun 
这次没法换trt8了
