### ISSUE TITLE
【论文复现 工程落地复现赛】模型动转静时出现错误

### ISSUE THREAD

**Issue by FL77N** [PaddlePaddle/Paddle#38196]
能正常 train、eval 动转静时报错，paddle 版本 2.2.1 错误如下：

```
# 发生错误代码段
def _process_single_level_pred(self, box_lvl, score_lvl, anchors, scale_factor_wh, img_wh):    
        score_lvl = paddle.transpose(score_lvl, [0, 2, 1])
        score_lvl = F.sigmoid(score_lvl)

        batch_lvl = []
        for i in range(len(img_wh)):
            box_lvl_i = delta2bbox(box_lvl[i], 
                                   anchors, 
                                   self.bbox_reg_weights).reshape(anchors.shape)
            
            box_lvl_i[:, 0::2] = paddle.clip(
                box_lvl_i[:, 0::2], min=0, max=img_wh[i][0]
            ) / scale_factor_wh[i][0]
            box_lvl_i[:, 1::2] =  paddle.clip(
                box_lvl_i[:, 1::2], min=0, max=img_wh[i][1]
            ) / scale_factor_wh[i][1]

            batch_lvl.append(box_lvl_i)

        box_lvl = paddle.stack(batch_lvl, axis=0)

        return box_lvl, score_lvl



File "/home/aistudio/ppdet/modeling/post_process.py", line 695, in _process_single_level_pred
            batch_lvl.append(box_lvl_i)

        box_lvl = paddle.stack(batch_lvl, axis=0)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

        return box_lvl, score_lvl

  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 798, in stack
return layers.stack(x, axis, name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 10203, in stack
attrs={'axis': axis})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2344, in __init__
self.desc.infer_shape(self.block.desc)

  RuntimeError: (NotFound) Variable reshape2_45.tmp_0 is not found.
[Hint: var should not be null.] (at /paddle/paddle/fluid/framework/op_desc.cc:286)
[operator < stack > error]

**Comment by joey12300** [comment]
`batch_lvl`这个列表有可能为空，导致动转静出错~

**Comment by FL77N** [comment]
> `batch_lvl`这个列表有可能为空，导致动转静出错~

谢谢你~已经解决了
但又有另外一个错误了，在动态图下 nms 出来的 pred_boxes.shape 是 [N, 6] 但静态图就变为了 [N, 1] 导致报错

```
 bbox_pred, bbox_num, _ = self.nms(pred_boxes, pred_scores)

if bbox_pred.shape[0] == 0:
    pred_result =  paddle.to_tensor(np.array([[-1, 0.0, 0.0, 0.0, 0.0, 0.0]], dtype='float32'))
    bbox_num = paddle.to_tensor(np.array([1], dtype='int32'))

    return pred_result, bbox_num

print("bbox_pred", bbox_pred.shape)

pred_label = bbox_pred[:, 0:1]
pred_score = bbox_pred[:, 1:2]
pred_bbox = bbox_pred[:, 2:]
keep_mask = nonempty_bbox(pred_bbox, return_mask=True)
keep_mask = paddle.unsqueeze(keep_mask, [1])
pred_label = paddle.where(keep_mask, pred_label,
                          paddle.ones_like(pred_label) * -1)
                          
pred_result = paddle.concat([pred_label, pred_score, pred_bbox], axis=1)

return pred_result, bbox_num
# 部分打印如下
bbox_pred
(-1, 1)
Traceback (most recent call last):
  File "tools/export_model.py", line 114, in <module>
    main()
  File "tools/export_model.py", line 110, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 78, in run
.....
    File "/home/aistudio/ppdet/modeling/architectures/meta_arch.py", line 28, in forward
	out = self.get_pred()
    File "/home/aistudio/ppdet/modeling/architectures/retinanet.py", line 84, in get_pred
	bbox_pred, bbox_num = self._forward()
    File "/home/aistudio/ppdet/modeling/architectures/retinanet.py", line 66, in _forward
	self.inputs
    File "/home/aistudio/ppdet/modeling/post_process.py", line 769, in __call__
        pred_label = bbox_pred[:, 0:1]
        pred_score = bbox_pred[:, 1:2]
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        pred_bbox = bbox_pred[:, 2:]
        keep_mask = nonempty_bbox(pred_bbox, return_mask=True)

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1783, in __getitem__
	return _getitem_impl_(self, item)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/variable_index.py", line 463, in _getitem_impl_
	attrs=attrs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
	attrs=kwargs.get("attrs", None))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2344, in __init__
	self.desc.infer_shape(self.block.desc)

    ValueError: (InvalidArgument) When step > 0, end should be greater than start, but received end = 1, start = 1.
  [Hint: Expected end > start, but received end:1 <= start:1.] (at /paddle/paddle/fluid/operators/slice_utils.h:59)
  [operator < slice > error]

**Comment by joey12300** [comment]
@FL77N 您在做动转静的时候，输入的input_spec是否固定了shape呢？
