### ISSUE TITLE
 Cannot find gradient of variable generated_tensor_15@GRAD

### ISSUE THREAD

**Issue by d2623587501** [PaddlePaddle/Paddle#38226]
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.1
    2）CPU：aistudio平台
    3）GPU：aistudio平台
    4）系统环境：aistudio平台
- 报错
    Traceback (most recent call last):
  File "train.py", line 366, in <module>
    main()
  File "train.py", line 339, in main
    p=p)#encoder_optimizer=encoder_optimizer,
  File "train.py", line 90, in train
    loss.backward()
  File "<decorator-gen-128>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 249, in backward
    framework._dygraph_tracer())
RuntimeError: (NotFound) Cannot find gradient of variable generated_tensor_15@GRAD
  [Hint: Expected iter != accumulators_.end() == true, but received iter != accumulators_.end():0 != true:1.] (at /paddle/paddle/fluid/imperative/basic_engine.cc:445)

**Comment by d2623587501** [comment]
loss.backward(retain_graph=True)
尝试这么设置也不行

**Comment by joey12300** [comment]
你好，可以提供最小可复现代码吗？

**Comment by d2623587501** [comment]
aistudio项目链接
项目“公式ocr”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/3148713/9047f107545f4becba86c8fa50456e70

**Comment by joey12300** [comment]
你好，我看了你的代码，你应该是希望encoder和decoder以不同的学习率更新参数，而使用两个optimizer分别更新梯度。你试试先只用一个optimizer更新参数，看看会不会报错。至于针对不同参数使用不同的学习率，可以通过在构造网络时传入weight_attr指定学习率。指定的lr会乘以外面定义的lr，得到该参数实际lr值，如：

```
self.conv = nn.Conv2D(1,64,3,stride=1,padding=1, weight_attr=paddle.ParamAttr(learning_rate=lr))
```

**Comment by d2623587501** [comment]
encoder和decoder使用同一个optimizer也没能解决，参考这个issue
[使用d_loss_cov.backward()时报错](https://github.com/PaddlePaddle/Paddle/issues/37265)
我将版本2.2.1->2.1.2，代码可以跑通

**Comment by joey12300** [comment]
@d2623587501 你好，可以试试2.2.2，看看代码还能否跑通，我这边测试了2.2.2是不会报这个反向的bug的
