### ISSUE TITLE
在paddle cloud上训练PaddleSeg-releasev2.0中的模型时出现ModuleNotFoundError类的错误

### ISSUE THREAD

**Issue by xinliyangguang** [PaddlePaddle/Paddle#38364]
我在paddle cloud中使用集群训练PaddleSeg-releasev2.0的模型，数据放在了afs集群上，代码放在了开发机上，提交作业之后报错如下：

/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/cvlibs/param_init.py:89: DeprecationWarning: invalid escape sequence \s
  """
Traceback (most recent call last):
  File "zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/train.py", line 21, in <module>
    from paddleseg.cvlibs import manager, Config
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/__init__.py", line 15, in <module>
    from . import models, datasets, transforms
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/models/__init__.py", line 15, in <module>
    from .backbones import *
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/models/backbones/__init__.py", line 16, in <module>
    from .resnet_vd import *
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/models/backbones/resnet_vd.py", line 21, in <module>
    from paddleseg.utils import utils
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/utils/__init__.py", line 18, in <module>
    from .env import seg_env, get_sys_env
ModuleNotFoundError: No module named 'paddleseg.utils.env'

**Comment by lyuwenyu** [comment]
请把问题在seg里也提一下吧 https://github.com/PaddlePaddle/PaddleSeg/issues
