### ISSUE TITLE
ValueError: Target(Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,        [102])) is out of class_dimension's upper bound(12)

### ISSUE THREAD

**Issue by Acoli98** [PaddlePaddle/Paddle#38403]
ValueError: Target(Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [102])) is out of class_dimension's upper bound(12)

**Comment by Acoli98** [comment]
Traceback (most recent call last):
  File "E:\Python_file\PaddlePaddle\paddle3.py", line 539, in <module>
    step_loss = loss(pred, label)
  File "F:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "F:\Anaconda\envs\paddle\lib\site-packages\paddle\nn\layer\loss.py", line 397, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "F:\Anaconda\envs\paddle\lib\site-packages\paddle\nn\functional\loss.py", line 1669, in cross_entropy
    raise ValueError(
ValueError: Target(Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [102])) is out of class_dimension's upper bound(12)

**Comment by lzzyzlbb** [comment]
看着像是class的维度超了，请问能贴一下源码吗

**Comment by Acoli98** [comment]
loss = paddle.nn.CrossEntropyLoss(axis=1) 
   for batch_id, (img, label) in enumerate(train_loader):
        optimizer.clear_grad()
        pred = model(img)
        print('label={}'.format(label.numpy().shape))
        print('pred={}'.format(pred.numpy().shape))
        step_loss = loss(pred, label)

错误信息：
label=(1, 600, 400)
pred=(1, 13, 600, 400)
Traceback (most recent call last):
  File "E:\Python_file\PaddlePaddle\paddle2.py", line 277, in <module>
    step_loss = loss(pred, label)
  File "F:\Anaconda\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "F:\Anaconda\envs\paddle\lib\site-packages\paddle\nn\layer\loss.py", line 397, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "F:\Anaconda\envs\paddle\lib\site-packages\paddle\nn\functional\loss.py", line 1669, in cross_entropy
    raise ValueError(
ValueError: Target(Tensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [255])) is out of class_dimension's upper bound(12)

**Comment by lzzyzlbb** [comment]
这个应该是说，你的pre只有13dim，然后你的label应该不超过12，但是label有出现值为255，是个异常值，可以检查一下
