### ISSUE TITLE
图像分类时报错OSError: (External) CUDA error(719), unspecified launch failure.    

### ISSUE THREAD

**Issue by Zero-Tang** [PaddlePaddle/Paddle#38549]
为使您的问题得到快速解决，在建立Issues前，请您先通过如下方式搜索是否有相似问题:【搜索issue关键字】【使用labels筛选】【官方文档】

如果您没有查询到相似问题，为快速解决您的提问，建立issue时请提供如下细节信息：
- 标题：简洁、精准概括您的问题，例如“Insufficient Memory xxx" ”
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
我使用的版本是2.2.1
    2）CPU：预测若用CPU，请提供CPU型号，MKL/OpenBlas/MKLDNN/等数学库使用情况
    3）GPU：预测若用GPU，请提供GPU型号、CUDA和CUDNN版本号
GPU是Nvidia GeForce RTX2060 with Max-Q Design
CUDA版本为10.2
CUDNN版本为7.6
    4）系统环境：请您描述系统类型、版本，例如Mac OS 10.14，Python版本、
Windows 10 x64 LTSC 2021，Python 3.9.7（随Visual Studio 2019安装的）
 注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。
- 训练信息
    1）单机/多机，单卡/多卡
单机单卡
    2）显存信息
6G显存
    3）Operator信息
```
****************************************
Paddle version: 2.2.1
Paddle With CUDA: True

OS: Windows 10
Python version: 3.9.7

CUDA version: 10.2.89
cuDNN version: 7.6.5
Nvidia driver version: 496.13
**************************************** 
```
- 复现信息：如为报错，请给出复现环境、复现步骤
使用的图源来自image-net的"downsampled image data", 8x8（就是227MB+9MB的那套）
在调用train.py时仅添加了`--data-dir`参数指定图源路径
运行至"pass 0, train batch 150"时会报错
另外，我写了一个python脚本用于从image-net的图源包里提取图片：
```Python
import pickle
import math
import os
from PIL import Image

def unpickle(file):
    with open(file,'rb') as fo:
        pickled_dict=pickle.load(fo)
    return pickled_dict

def transcript(file,prefix,size,output_dir=''):
    pickle_dict=unpickle(file)
    data=pickle_dict["data"]
    labels=pickle_dict["labels"]
    assert len(data)==len(labels)
    nlen=math.ceil(math.log(len(data),10))
    batch_list=""
    for i in range(len(data)):
        fx,fy=size
        assert fx*fy*3==len(data[i])
        file_path=os.path.join(output_dir,prefix+str(i).zfill(nlen)+'.jpg')
        with Image.new('RGB',(fx,fy)) as temp_img:
            for x in range(fx):
                for y in range(fy):
                    index=x*fx+y
                    r=data[i][index]
                    g=data[i][index+fx*fy]
                    b=data[i][index+fx*fy*2]
                    temp_img.putpixel((x,y),(r,g,b))
        temp_img.save(file_path,'jpeg')
        batch_list+=file_path+" "+str(labels[i])+"\n"
    return batch_list

train_list=open("train_list.txt","w")
for i in range(1,10):
    try:
        os.mkdir("batch_n"+str(i))
    except OSError:
        pass
    print("Extracting training data batch "+str(i)+"...")
    listing=transcript('train_data_batch_'+str(i),'batch_n'+str(i),(8,8),'batch_n'+str(i))
    train_list.write(listing)
train_list.close()
val_list=open("val_list.txt","w")
try:
    os.mkdir("val")
except OSError:
    pass
print("Extracting validation data batch...")
listing=transcript('val_data','val',(8,8),'val')
val_list.write(listing)
val_list.close()
print("Extraction completed...")
```
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段
总而言之就是训练了没几秒就报错了。
以下贴出运行输出：
```
INFO:utils.utility:-------------  Configuration Arguments -------------
INFO:utils.utility:               batch_size : 8
INFO:utils.utility:               checkpoint : None                                                                     
INFO:utils.utility:                class_dim : 1000                                                                     
INFO:utils.utility:                 data_dir : .\sample_data                                                            
INFO:utils.utility:              data_format : NCHW                                                                     
INFO:utils.utility:             decay_epochs : 2.4                                                                      
INFO:utils.utility:               decay_rate : 0.97                                                                     
INFO:utils.utility:        drop_connect_rate : 0.2                                                                      
INFO:utils.utility:                ema_decay : 0.9999                                                                   
INFO:utils.utility:             enable_addto : False                                                                    
INFO:utils.utility:                enable_ce : False                                                                    
INFO:utils.utility:finetune_exclude_pretrained_params : None                                                            
INFO:utils.utility:          fuse_bn_act_ops : False                                                                    
INFO:utils.utility:      fuse_bn_add_act_ops : True                                                                     
INFO:utils.utility: fuse_elewise_add_act_ops : False                                                                    
INFO:utils.utility:               image_mean : [0.485, 0.456, 0.406]                                                   
INFO:utils.utility:              image_shape : [3, 224, 224]                                                            
INFO:utils.utility:                image_std : [0.229, 0.224, 0.225]                                                    
INFO:utils.utility:            interpolation : None                                                                     
INFO:utils.utility:              is_profiler : False                                                                    
INFO:utils.utility:                 l2_decay : 0.0001                                                                   
INFO:utils.utility:  label_smoothing_epsilon : 0.1                                                                      
INFO:utils.utility:              lower_ratio : 0.75                                                                     
INFO:utils.utility:              lower_scale : 0.08                                                                     
INFO:utils.utility:                       lr : 0.1                                                                      
INFO:utils.utility:              lr_strategy : piecewise_decay                                                          
INFO:utils.utility:                 max_iter : 0                                                                        
INFO:utils.utility:              mixup_alpha : 0.2                                                                      
INFO:utils.utility:                    model : ResNet50                                                                 
INFO:utils.utility:           model_save_dir : ./output                                                                 
INFO:utils.utility:            momentum_rate : 0.9                                                                      
INFO:utils.utility:               num_epochs : 120                                                                      
INFO:utils.utility:             padding_type : SAME                                                                     
INFO:utils.utility:         pretrained_model : None                                                                     
INFO:utils.utility:               print_step : 10                                                                       
INFO:utils.utility:            profiler_path : ./profilier_files                                                        
INFO:utils.utility:              random_seed : None                                                                     
INFO:utils.utility:          reader_buf_size : 8                                                                        
INFO:utils.utility:            reader_thread : 8                                                                        
INFO:utils.utility:        resize_short_size : 256                                                                      
INFO:utils.utility:                same_feed : 0                                                                        
INFO:utils.utility:                save_step : 1                                                                        
INFO:utils.utility:               scale_loss : 1.0                                                                      
INFO:utils.utility:              step_epochs : [30, 60, 90]                                                             
INFO:utils.utility:          test_batch_size : 8                                                                        
INFO:utils.utility:             total_images : 1281167                                                                  
INFO:utils.utility:              upper_ratio : 1.3333333333333333                                                       
INFO:utils.utility:                   use_aa : False                                                                    
INFO:utils.utility:                  use_amp : False                                                                    
INFO:utils.utility:                 use_dali : False                                                                    
INFO:utils.utility: use_dynamic_loss_scaling : True                                                                     
INFO:utils.utility:                  use_ema : False                                                                    
INFO:utils.utility:                  use_gpu : True                                                                     
INFO:utils.utility:      use_label_smoothing : False                                                                    
INFO:utils.utility:                use_mixup : False                                                                    
INFO:utils.utility:            use_pure_fp16 : False                                                                    
INFO:utils.utility:                   use_se : True                                                                     
INFO:utils.utility:                 validate : True                                                                     
INFO:utils.utility:           warm_up_epochs : 5.0                                                                      
INFO:utils.utility:----------------------------------------------------                                                 
W1228 21:01:43.614042  2676 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.5, Runtime API Version: 10.2
W1228 21:01:43.622045  2676 device_context.cc:465] device: 0, cuDNN Version: 7.6.                                       
INFO:utils.utility:[Pass 0, train batch 0]      loss 7.19254, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.97350 sec, reader_cost 0.50653 sec, ips 8.21775 images/sec
INFO:utils.utility:[Pass 0, train batch 10]     loss 14.91554, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.10789 sec, reader_cost 0.00020 sec, ips 74.14785 images/sec
INFO:utils.utility:[Pass 0, train batch 20]     loss 8.63187, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09762 sec, reader_cost 0.00010 sec, ips 81.94887 images/sec
INFO:utils.utility:[Pass 0, train batch 30]     loss 6.47855, acc1 0.00000, acc5 0.12500, lr 0.10000, batch_cost 0.09762 sec, ips 81.94699 images/sec
INFO:utils.utility:[Pass 0, train batch 40]     loss 6.98920, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09800 sec, ips 81.63470 images/sec
INFO:utils.utility:[Pass 0, train batch 50]     loss 6.90599, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09783 sec, ips 81.77468 images/sec
INFO:utils.utility:[Pass 0, train batch 60]     loss 6.93639, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09798 sec, ips 81.65196 images/sec
INFO:utils.utility:[Pass 0, train batch 70]     loss 6.95135, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09824 sec, ips 81.43724 images/sec
INFO:utils.utility:[Pass 0, train batch 80]     loss 6.92151, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09819 sec, ips 81.47333 images/sec
INFO:utils.utility:[Pass 0, train batch 90]     loss 6.92293, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09838 sec, reader_cost 0.00010 sec, ips 81.32101 images/sec
INFO:utils.utility:[Pass 0, train batch 100]    loss 6.92285, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09874 sec, ips 81.02080 images/sec
INFO:utils.utility:[Pass 0, train batch 110]    loss 6.88460, acc1 0.00000, acc5 0.12500, lr 0.10000, batch_cost 0.09882 sec, ips 80.95854 images/sec
INFO:utils.utility:[Pass 0, train batch 120]    loss 7.03168, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09896 sec, ips 80.84349 images/sec
INFO:utils.utility:[Pass 0, train batch 130]    loss 6.92974, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09861 sec, ips 81.13123 images/sec
INFO:utils.utility:[Pass 0, train batch 140]    loss 6.92922, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09827 sec, ips 81.41239 images/sec
INFO:utils.utility:[Pass 0, train batch 150]    loss 6.92885, acc1 0.00000, acc5 0.00000, lr 0.10000, batch_cost 0.09834 sec, ips 81.35195 images/sec
Traceback (most recent call last):                                                                                        
File "D:\imagenet8-train\models-develop\PaddleCV\image_classification\train.py", line 357, in <module>
    main()
File "D:\imagenet8-train\models-develop\PaddleCV\image_classification\train.py", line 351, in main
    train(args)
File "D:\imagenet8-train\models-develop\PaddleCV\image_classification\train.py", line 283, in train
    train_batch_metrics = exe.run(compiled_train_prog,
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\paddle\fluid\executor.py", line 1262, in run
    six.reraise(*sys.exc_info())
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\six.py", line 719, in reraise
    raise value
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\paddle\fluid\executor.py", line 1250, in run
    return self._run_impl(
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\paddle\fluid\executor.py", line 1408, in _run_impl
    return self._run_parallel(
File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\paddle\fluid\executor.py", line 1065, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
OSError: (External) CUDA error(719), unspecified launch failure.
[Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\fluid\platform\stream\cuda_stream.cc:92)
Error: ../paddle/fluid/operators/cross_entropy_op.h:175 Assertion `label >= 0 && label < feature_size_` failed. Variable value (label) of OP(fluid.layers.cross_entropy) expected >= 0 and < 1000, but got 0. Please check label value. 
```
Thank you for contributing to PaddlePaddle.
Before submitting the issue, you could search issue in the github in case that there was a similar issue submitted or resolved before.
If there is no solution,please make sure that this is a training issue including the following details:
**System information**
-PaddlePaddle version （eg.1.1）or CommitID
-CPU: including CPUMKL/OpenBlas/MKLDNN version
-GPU: including CUDA/CUDNN version
-OS Platform (eg.Mac OS 10.14)
-Other imformation: Distriuted training/informantion of operator/
Graphics card storage
Note: You can get most of the information by running [summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py). 
**To Reproduce**
Steps to reproduce the behavior
**Describe your current behavior**
**Code to reproduce the issue**
**Other info / logs**

**Comment by smallv0221** [comment]
您好，报错信息需要复现代码，请提供最小可复现代码，我们复现后会尽快回复您～

**Comment by Zero-Tang** [comment]
我用上面给出的python代码提取了图像之后并且生成了对应的`train_list.txt`和`val_list.txt`后，调用[这里的](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification)的`train.py`进行训练的时候报错了。
所以说，最小可复现代码已经给了。。。
训练用的图像来自https://image-net.org
![Capture](https://user-images.githubusercontent.com/37060901/147654452-23dbe9a0-5582-4af3-96b6-9258873b43b3.PNG)

**Comment by HydrogenSulfate** [comment]
> 我用上面给出的python代码提取了图像之后并且生成了对应的`train_list.txt`和`val_list.txt`后，调用[这里的](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification)的`train.py`进行训练的时候报错了。 所以说，最小可复现代码已经给了。。。 训练用的图像来自https://image-net.org ![Capture](https://user-images.githubusercontent.com/37060901/147654452-23dbe9a0-5582-4af3-96b6-9258873b43b3.PNG)

您好，看起来是输入中的labels范围超出了[0,1000)这一区间范围，可以检查一下labels确认一下。

**Comment by Zero-Tang** [comment]
确实是labels超了，谢谢。

**Comment by CassieFeng** [comment]
@Zero-Tang @HydrogenSulfate 您好，我也遇到了相同的问题，麻烦问一下labels超具体是指label长度？还是label个数？还是其他的，谢谢~

**Comment by HydrogenSulfate** [comment]
> @Zero-Tang @HydrogenSulfate 您好，我也遇到了相同的问题，麻烦问一下labels超具体是指label长度？还是label个数？还是其他的，谢谢~

如果有N个label，那么label在构造成数据时，由于从0开始，范围应该在[0, N-1]，检查一下labels里是否有>=N-1的值

**Comment by CassieFeng** [comment]
> > @Zero-Tang @HydrogenSulfate 您好，我也遇到了相同的问题，麻烦问一下labels超具体是指label长度？还是label个数？还是其他的，谢谢~
> 
> 如果有N个label，那么label在构造成数据时，由于从0开始，范围应该在[0, N-1]，检查一下labels里是否有>=N-1的值

收到，感谢[抱拳]
