### ISSUE TITLE
【论文复现】aistudio上训练vit类模型报多进程的错

### ISSUE THREAD

**Issue by renmada** [PaddlePaddle/Paddle#38551]
训练到一半报错，训练2次都出现这个问题
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 232, in _get_code_from_file
    code = read_code(f)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/pkgutil.py", line 45, in read_code
    magic = stream.read(4)
OSError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 232, in _get_code_from_file
    code = read_code(f)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/pkgutil.py", line 45, in read_code
    magic = stream.read(4)
OSError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 232, in _get_code_from_file
    code = read_code(f)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/pkgutil.py", line 45, in read_code
    magic = stream.read(4)
OSError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 232, in _get_code_from_file
    code = read_code(f)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/pkgutil.py", line 45, in read_code
    magic = stream.read(4)
OSError: [Errno 5] Input/output error
```

**Comment by renmada** [comment]
每次epoch结束都会报warning，不知道是不是有关系
```
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
1228 07:42:17 PM ----- Epoch[040/400], Train Loss: 3.5191, Train Acc: 0.2799, time: 2937.14
1228 07:42:17 PM Now training epoch 41. LR=0.000993
1228 07:42:17 PM ----- Epoch[040/400], Train Loss: 3.5003, Train Acc: 0.2781, time: 2936.96
1228 07:42:17 PM ----- Epoch[040/400], Train Loss: 3.5113, Train Acc: 0.2808, time: 2936.96
1228 07:42:17 PM Now training epoch 41. LR=0.000993
1228 07:42:17 PM Now training epoch 41. LR=0.000993
1228 07:42:17 PM ----- Epoch[040/400], Train Loss: 3.5139, Train Acc: 0.2818, time: 2937.15


```

**Comment by weisy11** [comment]
可以提供一下最小的可复现代码么？从报错信息看不出什么问题。或者可以试试PaddleClas

**Comment by renmada** [comment]
> 可以提供一下最小的可复现代码么？从报错信息看不出什么问题。或者可以试试PaddleClas
https://gitee.com/imxly2/paddle-vi-t/tree/PVTv2/image_classification/PVTv2

这是我在用的代码，run.sh修改相应的路径

**Comment by weisy11** [comment]
> > 可以提供一下最小的可复现代码么？从报错信息看不出什么问题。或者可以试试PaddleClas
> > https://gitee.com/imxly2/paddle-vi-t/tree/PVTv2/image_classification/PVTv2
> 
> 这是我在用的代码，run.sh修改相应的路径

不好意思漏了消息。这个项目的代码太多了，能不能麻烦你提供一个最小可复现的代码？
