### ISSUE TITLE
脚本任务训练数据读取错误【论文复现】

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#38606]
使用多卡训练(spwan机制)会出现如下警告，最终大概训练1.5天报数据输入输出错误
```
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 232, in _get_code_from_file
    code = read_code(f)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/pkgutil.py", line 45, in read_code
    magic = stream.read(4)
OSError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 232, in _get_code_from_file
    code = read_code(f)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/pkgutil.py", line 45, in read_code
    magic = stream.read(4)
OSError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 232, in _get_code_from_file
    code = read_code(f)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/pkgutil.py", line 45, in read_code
    magic = stream.read(4)
OSError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 261, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/runpy.py", line 232, in _get_code_from_file
    code = read_code(f)
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/pkgutil.py", line 45, in read_code
    magic = stream.read(4)
OSError: [Errno 5] 
```

**Comment by wangxinxin08** [comment]
你好，感谢您的反馈，我们正在定位问题中
