### ISSUE TITLE
安装后版本显示0.0.0

### ISSUE THREAD

**Issue by dockiHan** [PaddlePaddle/Paddle#3869]
最近将代码由本机容器迁移到物理机时发现一些问题：

1. 物理机的环境搭建使用的二进制安装方式，安装之后paddlepaddle版本显示0.0.0。物理机运行paddle version如下：
```text
PaddlePaddle 0.0.0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF
```
2. 我的代码中定义有两个网络（一个lstm时间序列的预测模型，一个分类器模型），两个网络的定义分别封装在两个python类中，相关的网络参数都以成员变量的方式存储。使用时两个模型是需要同时存在的，不过训练和预测是有顺序关系的（串行关系），代码在本机的容器中（paddlepaddle版本为0.10.0）可以正常运行，但在物理机中（paddlepaddle版本为0.0.0）却无法运行，刚开始报命名冲突的错误，如下：

```text
I0905 11:03:26.478267 16376 Util.cpp:166] commandline:  --log_error_clipping=True --use_gpu=False 
I0905 11:03:26.504140 16376 GradientMachine.cpp:85] Initing parameters..
I0905 11:03:26.535382 16376 GradientMachine.cpp:92] Init parameters done.
[CRITICAL 2017-09-05 11:03:26,577 layers.py:854] Duplicated layer name: X
Traceback (most recent call last):
  File "twitter_dataset_test_case.py", line 179, in <module>
    init_networks()
  File "twitter_dataset_test_case.py", line 95, in init_networks
    ad.network_construct()
  File "/home/paddle/anomaly-detection/anomaly_detection.py", line 103, in network_construct
    classifier.classify_network()
  File "/home/paddle/anomaly-detection/classifier_model.py", line 45, in classify_network
    X = paddle.layer.data(name="X", type = paddle.data_type.dense_vector(dim=self.input_dim))
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/paddle/v2/layer.py", line 88, in __data_layer__
    l = v1_layers.data_layer(name, type.dim, **kwargs)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 350, in wrapper
    return method(*args, **kwargs)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 854, in data_layer
    **ExtraLayerAttribute.to_kwargs(layer_attr))
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3136, in Layer
    return layer_func(name, **xargs)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 1681, in __init__
    name, 'data', size, inputs=[], device=device)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 1363, in __init__
    'Duplicated layer name: %s' % name)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 156, in config_assert
    logger.fatal(msg)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3482, in my_fatal
    raise Exception()
Exception
```
---

（先声明一下，layer X是模型的输入，两个模型确实都是X，但是定义的地方分别在两个类里面，应该不会有交集吧，而且我的代码在本机容器可以正常运行，我觉得这应该不是问题的本质。为了尝试解决问题，我还是根据bug提示修改了变量命名）
修改过命名冲突的问题后又出现了疑似reader的错误，报错如下：

```text
I0905 11:09:46.388175  5056 Util.cpp:166] commandline:  --log_error_clipping=True --use_gpu=False 
I0905 11:09:46.413916  5056 GradientMachine.cpp:85] Initing parameters..
I0905 11:09:46.445041  5056 GradientMachine.cpp:92] Init parameters done.
I0905 11:09:46.451920  5056 GradientMachine.cpp:85] Initing parameters..
I0905 11:09:46.453236  5056 GradientMachine.cpp:92] Init parameters done.
Traceback (most recent call last):
  File "twitter_dataset_test_case.py", line 187, in <module>
    lstm_model_train(lstm_model_path=lstm_model_path, lstm_train_x=lstm_train_x, lstm_train_y=lstm_train_y)
  File "twitter_dataset_test_case.py", line 109, in lstm_model_train
    ad.lstm_train()
  File "/home/paddle/anomaly-detection/anomaly_detection.py", line 107, in lstm_train
    lstm.lstm_train()
  File "/home/paddle/anomaly-detection/lstm_model.py", line 123, in lstm_train
    self.trainer.train(reader=paddle.minibatch.batch(paddle.reader.shuffle(data_reader(), buf_size=self.train_set_num), batch_size=self.batch_size), feeding=feeding, event_handler=event_handler, num_passes=self.train_pass_num)    
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/paddle/v2/trainer.py", line 153, in train
    in_args = feeder(data_batch)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 278, in __call__
    return self.convert(dat, argument)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 134, in convert
    return DataProviderConverter.convert(self, reorder_data(dat), argument)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 263, in convert
    scanner.pre_scan(each_step)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 221, in pre_scan
    self.__inner_scanner__.pre_scan(each)
  File "/home/paddle/paddlepaddle/python27/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 112, in pre_scan
    self.__dim__ = reduce(lambda x, y: x * y, self.__shape__)
TypeError: reduce() of empty sequence with no initial value
```

**Comment by lcy-seso** [comment]
1. 第一个 paddle version = 0.0.0 的问题，我需要再看一下，暂时不确定是什么原因引起的。
2. 从报错信息中看到有这样一句：
    ```python
    X = paddle.layer.data(name="X", type = paddle.data_type.dense_vector(dim=self.input_dim))
    ```
    在 Paddle 中， 一个训练任务中的每个 layer 都需要有唯一的名字，这一行将 X 的名字写死了。即使他们出现在不同的类中也会出现名字冲突。在容器中为什么没有错，没有具体的代码，我不确定。

3. 最后一个是读数据引起的错误，能不能提供读数据相关的代码。

**Comment by dockiHan** [comment]
@lcy-seso  
lstm模型的reader：
```
def lstm_train(self):
        def data_reader():
            def reader():
                for i in xrange(len(self.train_x)):
                    yield self.train_x[i], self.train_y[i]
            return reader
```
可以确定train_x和train_y不为空（加print测试过），两者都是list，格式也相同都是（train_set_size, time_step），假设time_step为4、train_set_size为2: [[1,2,3,4], [5,6,7,8]]
本机容器与物理机是同一份代码，容器中可以正常运行，感觉还是有些问题的，包括上面的命名冲突问题（确实定义layer时name相同会造成冲突，但是容器竟然没有报错而且可以正常运行。）

**Comment by lcy-seso** [comment]
Paddle 经历过历次版本更新，对一些细节的处理会有变化。容器是什么时候的版本呢？

**Comment by lcy-seso** [comment]
这个reader 返回的数据给分别给了两个data layer，从现在提供的格式来看。如果这个两个data layer 的type不是 interge_value_sequence ，返回的数据格式会是错误的。请问data layer对应的type是什么。

**Comment by dockiHan** [comment]
@lcy-seso 
我感觉这个reader的返回类型应该是`dense_vector_sequence`呀。train_x, train_y的结构是类似这个样子的：[[1,2,3,4], [5,6,7,8]]， 那么yield train_x[i] 就应该是[1,2,3,4]这样子的呀
________________________________________________
1.以下是对应train_x和train_y的data layer:
```
X = paddle.layer.data(name="lstm_X", type=paddle.data_type.dense_vector_sequence(dim=self.input_dim))
Y = paddle.layer.data(name="lstm_Y", type=paddle.data_type.dense_vector_sequence(dim=self.output_dim))
```
input_dim 和 output_dim 都是1

2.本机容器的镜像：
`docker.paddlepaddle.org/paddle   0.10.0              efb209ef9426        3 months ago        749MB`

**Comment by lcy-seso** [comment]
现在返回的这个格式不是 `dense_vector_sequence`。
下面这样的一条数据：

```python
[[1.0 1.0 1.0] [2.0 2.0 2.0]]
```
是一个含有2个时间步的 `dense_vector_sequence`。

[1, 2, 3, 4] 这种格式是含有4个时间步的`integer_value_sequence`。

**Comment by dockiHan** [comment]
@lcy-seso
抱歉，我还是没太理解您的意思。现在我的需求是这样的：使用前N个时间步的数据作为特征值（即1 * N的向量，假设时间步1-N）输入到LSTM模型进行预测，LSTM模型的输出也应该是对应的N个时间步（根据LSTM模型按时间步展开每一步都会有一个输出，所以输出也应该是个1 * N的向量, 即时间步2 - N+1的值），然后我只需要取最后一个值使用，也就是第N+1时间步的值。所以按照我的理解，我的输入和输出都应该是一个vector而非value

-------------------
以下是train_x的前5条数据
```
[array([ 1.19733989,  0.94989866,  0.71905422,  0.8589946 ,  1.13472557,
        0.96159172,  1.15396249,  0.93896019,  0.50518352,  1.29578841,
        0.67228156,  0.57685071,  0.65078163,  0.59269297,  0.93858266,
        0.90840733,  0.75224775,  0.57006145,  0.57647371,  0.57043844,
        0.56478041,  0.3754276 ,  0.3890067 ,  0.33393598,  1.11096203,
        0.69981736,  0.40673503,  0.41012967,  0.34751508,  0.49198139,
        0.18418865,  0.20003086], dtype=float32), array([ 0.94989866,  0.71905422,  0.8589946 ,  1.13472557,  0.96159172,
        1.15396249,  0.93896019,  0.50518352,  1.29578841,  0.67228156,
        0.57685071,  0.65078163,  0.59269297,  0.93858266,  0.90840733,
        0.75224775,  0.57006145,  0.57647371,  0.57043844,  0.56478041,
        0.3754276 ,  0.3890067 ,  0.33393598,  1.11096203,  0.69981736,
        0.40673503,  0.41012967,  0.34751508,  0.49198139,  0.18418865,
        0.20003086,  0.04009936], dtype=float32), array([ 0.71905422,  0.8589946 ,  1.13472557,  0.96159172,  1.15396249,
        0.93896019,  0.50518352,  1.29578841,  0.67228156,  0.57685071,
        0.65078163,  0.59269297,  0.93858266,  0.90840733,  0.75224775,
        0.57006145,  0.57647371,  0.57043844,  0.56478041,  0.3754276 ,
        0.3890067 ,  0.33393598,  1.11096203,  0.69981736,  0.40673503,
        0.41012967,  0.34751508,  0.49198139,  0.18418865,  0.20003086,
        0.04009936,  0.08121371], dtype=float32), array([ 0.8589946 ,  1.13472557,  0.96159172,  1.15396249,  0.93896019,
        0.50518352,  1.29578841,  0.67228156,  0.57685071,  0.65078163,
        0.59269297,  0.93858266,  0.90840733,  0.75224775,  0.57006145,
        0.57647371,  0.57043844,  0.56478041,  0.3754276 ,  0.3890067 ,
        0.33393598,  1.11096203,  0.69981736,  0.40673503,  0.41012967,
        0.34751508,  0.49198139,  0.18418865,  0.20003086,  0.04009936,
        0.08121371,  0.23963667], dtype=float32), array([ 1.13472557,  0.96159172,  1.15396249,  0.93896019,  0.50518352,
        1.29578841,  0.67228156,  0.57685071,  0.65078163,  0.59269297,
        0.93858266,  0.90840733,  0.75224775,  0.57006145,  0.57647371,
        0.57043844,  0.56478041,  0.3754276 ,  0.3890067 ,  0.33393598,
        1.11096203,  0.69981736,  0.40673503,  0.41012967,  0.34751508,
        0.49198139,  0.18418865,  0.20003086,  0.04009936,  0.08121371,
        0.23963667, -0.06664751], dtype=float32)]
```
----------------------------------

我按照你的建议将data layer 改为`integer_value_sequence`后，容器和物理机都会报同样的错误：
Traceback (most recent call last):
  File "twitter_dataset_test_case.py", line 187, in <module>
    lstm_model_train(lstm_model_path=lstm_model_path, lstm_train_x=lstm_train_x, lstm_train_y=lstm_train_y)
  File "twitter_dataset_test_case.py", line 109, in lstm_model_train
    ad.lstm_train()
  File "/paddlepaddle/anomaly-detection/anomaly_detection.py", line 107, in lstm_train
    lstm.lstm_train()
  File "/paddlepaddle/anomaly-detection/lstm_model.py", line 123, in lstm_train
    self.trainer.train(reader=paddle.minibatch.batch(paddle.reader.shuffle(data_reader(), buf_size=self.train_set_num), batch_size=self.batch_size), feeding=feeding, event_handler=event_handler, num_passes=self.train_pass_num)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/trainer.py", line 114, in train
    feeder(data_batch), out_args, pass_type)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 249, in __call__
    return self.convert(dat, argument)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/data_feeder.py", line 134, in convert
    return DataProviderConverter.convert(self, reorder_data(dat), argument)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 244, in convert
    scanner.finish_scan(argument)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 205, in finish_scan
    self.__inner_scanner__.finish_scan(argument)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 178, in finish_scan
    ids = swig_paddle.IVector.create(self.__ids__, self.data_in_gpu)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 881, in create
    return _swig_paddle.IVector_create(*args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'IVector_create'.
  Possible C/C++ prototypes are:
    IVector::create(std::vector< int,std::allocator< int > > const &,bool)
    IVector::create(std::vector< int,std::allocator< int > > const &)

-------------------------------------------------------------------------
我个人觉得data layer 改为`integer_value_sequence`是有问题的，`integer_value_sequence`定义时需要的参数value_range我也是无法确定的，因为我把时间序列normalize之后我也不知道它的范围是多少（Z-score的normalize方法）。此外，我的输入和输出也不是integer呀。

**Comment by lcy-seso** [comment]
我的意思不是说建议改成 `integer_value_sequence` ，而是说现在reader 返回的是 `integer_value_sequence`，请你确定这是你需要的数据类型。

**Comment by lcy-seso** [comment]
先不要管需要的模型是什么样的。现在这个错误是读数据的问题，和你描述的这些LSTM层都没有关系。

>使用前N个时间步的数据作为特征值（即1 * N的向量，假设时间步1-N）输入到LSTM模型进行预测，LSTM模型的输出也应该是对应的N个时间步（根据LSTM模型按时间步展开每一步都会有一个输出，所以输出也应该是个1 * N的向量, 即时间步2 - N+1的值），然后我只需要取最后一个值使用，也就是第N+1时间步的值。所以按照我的理解，我的输入和输出都应该是一个vector而非value 

只取决于现在你的 data_layer 定义时候指定了什么type，而你在reader 里面返回的数据格式并对应那种type。

**Comment by dockiHan** [comment]
@lcy-seso
非常感谢您的耐心指导！现在已经可以跑通了，确实是数据的格式没有符合data layer定义的类型。但是本机容器中无论数据格式修改之前还是修改之后包括存在命名冲突时都可以正常运行，关于这一点我还不太理解，如果你们有时间可以check一下容器中的paddlepaddle版本。
此外关于二进制安装paddle version 显示0.0.0的问题，如果有时间也希望你们能够check一下，如果仅仅是显示错误就好了，希望不会对paddlepaddle的使用有较大影响。
再次感谢您的耐心指导， 谢谢！

**Comment by lcy-seso** [comment]
呃。。不客气。

这个容器版本是三个月之前的，可能之前也存在一些bug。我们会再看一下~
