### ISSUE TITLE
sparse_embedding的注释说明是否有错误

### ISSUE THREAD

**Issue by Li-Jiajie** [PaddlePaddle/Paddle#38829]
paddle.static.nn.sparse_embedding中的注释是上图，但是C++中OP的操作又校验了最后一维是否等于1，这里的注释是否有误？
我实际运行起来，传入一个[-1, 100]的tensor至sparse_embedding也会报错
版本2.2.1-CPU
![image](https://user-images.githubusercontent.com/35255760/148714320-e2c06bc9-ed65-4d43-b0ff-2dd9d777bd34.png)
![image](https://user-images.githubusercontent.com/35255760/148714346-f861a3e3-e7ec-4d2e-8f2e-9b6f7d25efb9.png)

**Comment by Li-Jiajie** [comment]
代码（按照注释里，是可以传入shpae=[3,2]的tensor的）：
import paddle
paddle.enable_static()
input = paddle.static.data(name='ins', shape=[3, 2], dtype='int64')
emb = paddle.static.nn.sparse_embedding(input=input, size=[1024, 64])

报错：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/contrib/layers/nn.py", line 1130, in sparse_embedding
    'table_class': table_class
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/framework.py", line 3184, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib64/python3.6/site-packages/paddle/fluid/framework.py", line 2344, in __init__
    self.desc.infer_shape(self.block.desc)
ValueError: (InvalidArgument) ShapeError: The last dimensions of the 'Ids' tensor must be 1. But received Ids's last dimensions = 2, Ids's shape = [3, 2].
  [Hint: Expected ids_dims[ids_rank - 1] == 1, but received ids_dims[ids_rank - 1]:2 != 1:1.] (at /paddle/paddle/fluid/operators/lookup_table_op.cc:52)
  [operator < lookup_table > error]

**Comment by Li-Jiajie** [comment]
@kuizhiqing @paddle-bot

**Comment by Yanxing-Shi** [comment]
@Li-Jiajie sparse_embedding文档部分有误，embedding Op中check最后一维是否为1
