### ISSUE TITLE
paddle.utils.run_check()的runtime api version和bvcc --version不一样

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/Paddle#39090]
环境：
ubuntu18.04
RTX3090
cuda11.1+cudnn8.2.1
我在终端输入
nvcc --version显示：

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0

安装paddlpaddle-gpu==2.2.1或者2.2.0均有下面错误，仔细对比发现paddle.utils.run_check()的Runtime API Version: 10.2不知道是什么问题呢

>>> import paddle
pa>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0120 19:29:14.875797 20703 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 10.2
W0120 19:29:14.891688 20703 device_context.cc:465] device: 0, cuDNN Version: 8.2.
W0120 19:29:18.099985 20703 operator.cc:248] uniform_random raises an exception thrust::system::system_error, parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/howso/Anaconda/envs/paddle/lib/python3.8/site-packages/paddle/utils/install_check.py", line 196, in run_check
    _run_static_single(use_cuda)
  File "/home/howso/Anaconda/envs/paddle/lib/python3.8/site-packages/paddle/utils/install_check.py", line 124, in _run_static_single
    exe.run(startup_prog)
  File "/home/howso/Anaconda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1246, in run
    six.reraise(*sys.exc_info())
  File "/home/howso/Anaconda/envs/paddle/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/howso/Anaconda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1234, in run
    return self._run_impl(
  File "/home/howso/Anaconda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1366, in _run_impl
    return self._run_program(
  File "/home/howso/Anaconda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1463, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
RuntimeError: parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

**Comment by tongxin** [comment]
你好，你的本地环境可能安装了多个版本的 Cuda，可以看下 nvidia-smi 的输出。
另外稍加澄清两点：
1，同一台机器安装的 Cuda driver 和 Cuda runtime 版本号不同是正常的，无须多虑，nvidia-smi 命令显示的是 driver version。
2，nvcc 的 version 是 nvcc 识别的 Cuda version，是构建 nvcc 的时候就确定的，所以本地安装的时候要注意安装合适的 Cuda toolkit。
针对你的情况，可以考虑按官方说明重新安装 Cuda toolkit
