### ISSUE TITLE
單測 random seed 未固定導致單測不穩定

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#39382]
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID: develop
    2）CPU/GPU：如果您使用GPU训练，请提供GPU驱动版本、CUDA和cuDNN版本号: 
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
    4）Python版本号
    5）显存信息
```
****************************************
Paddle version: 0.0.0
Paddle With CUDA: True

OS: Ubuntu 20.04
Python version: 3.8.10

CUDA version: 11.6.55
cuDNN version: None.None.None
Nvidia driver version: 460.32.03
****************************************
```
問題描述:
``test_linalg_cond``, ``test_custom_conj``, ``test_linalg_pinv_op`` 這幾個單測生成測試輸入的 random seed(or reg) 沒有固定, 導致單測會隨機錯誤

**Comment by ForFishes** [comment]
您好，这个几个单侧会随机挂吗？有些单测的随机性是不需要固定的，这个几个单侧在ci也没有出现随机挂的情形。

**Comment by zhwesky2010** [comment]
@zlsh80826 您好，目前在V100显卡未复现问题，方便看下三个单测分别的报错信息截图吗

**Comment by jeng1220** [comment]
The following log shows random failure of `test_linalg_pinv_op`. It fails the second test but passes the other time. The `test_linalg_cond` and `test_custom_conj` have the similar issue. These issues can be reproduced with both V100 and A100


```
Test project /workspace/Paddle-sanitizer/Paddle/build
    Start  852: test_linalg_cond
1/3 Test  #852: test_linalg_cond .................   Passed    4.93 sec
    Start  854: test_linalg_pinv_op
2/3 Test  #854: test_linalg_pinv_op ..............   Passed    5.74 sec
    Start 1437: test_custom_conj
3/3 Test #1437: test_custom_conj .................   Passed    2.53 sec

100% tests passed, 0 tests failed out of 3

Total Test time (real) =  13.41 sec


Test project /workspace/Paddle-sanitizer/Paddle/build
    Start  852: test_linalg_cond
1/3 Test  #852: test_linalg_cond .................   Passed    4.80 sec
    Start  854: test_linalg_pinv_op
2/3 Test  #854: test_linalg_pinv_op ..............***Failed    5.90 sec
W0214 13:44:52.539511 14141 init.cc:236] AVX is available, Please re-compile on local machine
W0214 13:44:52.944250 14141 device_context.cc:509] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0214 13:44:52.946528 14141 device_context.cc:527] device: 0, cuDNN Version: 8.1.
Hint: Your machine support AVX, but the installed paddlepaddle doesn't have avx core. Hence, no-avx core with worse preformance will be imported.
If you like, you could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' to get better performance.
The original error is: No module named 'paddle.fluid.core_avx'
/workspace/Paddle-sanitizer/Paddle/build/python/paddle/fluid/dygraph/varbase_patch_methods.py:501: UserWarning: [93m
Warning:
tensor.grad will return the tensor value of the gradient. This is an incompatible upgrade for tensor.grad API.  It's return type changes from numpy.ndarray in version 2.0 to paddle.Tensor in version 2.1.0.  If you want to get the numpy value of the gradient, you can use :code:`x.grad.numpy()` [0m
  warnings.warn(warning_msg)
/workspace/Paddle-sanitizer/Paddle/build/python/paddle/fluid/framework.py:933: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
test_linalg_pinv_op failed
 ............................................E...
======================================================================
ERROR: test_static (test_linalg_pinv_op.LinalgPinvTestCaseHermitianFP32)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/Paddle-sanitizer/Paddle/build/python/paddle/fluid/tests/unittests/test_linalg_pinv_op.py", line 86, in test_static
    raise RuntimeError("Check PINV static Failed")
RuntimeError: Check PINV static Failed

----------------------------------------------------------------------
Ran 48 tests in 3.401s

FAILED (errors=1)

EXPECTED: 
 [[[ -1.3659471   -0.7847442    1.3236785   -1.8204367    2.3604732 ]
  [ -0.78474426  -1.6915888    1.4065591   -1.935105     2.6942034 ]
  [  1.3236785    1.406559    -1.3540677    3.3701332   -3.6552954 ]
  [ -1.8204368   -1.935105     3.3701332   -6.928256     5.8804035 ]
  [  2.3604732    2.6942034   -3.6552954    5.8804035   -5.7669687 ]]

 [[ -0.22908202  -0.72432786  -0.27039152   1.7335304   -0.1928434 ]
  [ -0.72432786   2.208218     0.5342427   -3.0191803    0.77261525]
  [ -0.2703915    0.5342427    0.73744315  -1.9313303    0.9123824 ]
  [  1.7335304   -3.0191803   -1.9313304    5.244094    -1.346119  ]
  [ -0.1928434    0.7726153    0.9123824   -1.346119     0.06573456]]

 [[-10.314561     9.052603   -12.2133      -0.9642844   17.25126   ]
  [  9.052603    -7.8826313    9.46537      0.8519637  -13.467516  ]
  [-12.2133       9.465369   -11.406977     0.05519036  17.346346  ]
  [ -0.9642845    0.8519637    0.05519033  -1.4286668    1.6619059 ]
  [ 17.25126    -13.467516    17.346346     1.6619059  -26.784708  ]]]
GOT     : 
 [[[ -1.3659412   -0.7847379    1.3236694   -1.8204201    2.3604577 ]
  [ -0.7847379   -1.6915816    1.4065491   -1.9350871    2.6941864 ]
  [  1.3236694    1.4065491   -1.3540535    3.370107    -3.6552713 ]
  [ -1.8204201   -1.9350871    3.370107    -6.928207     5.8803596 ]
  [  2.3604577    2.6941864   -3.6552713    5.8803596   -5.7669287 ]]

 [[ -0.22908393  -0.72432387  -0.27038878   1.7335232   -0.19284143]
  [ -0.72432387   2.2082095    0.53423715  -3.0191648    0.7726113 ]
  [ -0.2703888    0.53423727   0.7374389   -1.9313196    0.91237944]
  [  1.7335232   -3.0191648   -1.9313195    5.2440653   -1.3461114 ]
  [ -0.19284149   0.7726113    0.91237944  -1.3461114    0.06573247]]

 [[-10.314606     9.052645   -12.213361    -0.9642914   17.251345  ]
  [  9.052645    -7.8826704    9.465426     0.85197    -13.467591  ]
  [-12.213361     9.465426   -11.40706      0.05518186  17.346457  ]
  [ -0.9642915    0.8519701    0.05518184  -1.4286681    1.661918  ]
  [ 17.251345   -13.467591    17.346457     1.661918   -26.784853  ]]]

    Start 1437: test_custom_conj
3/3 Test #1437: test_custom_conj .................   Passed    2.51 sec

67% tests passed, 1 tests failed out of 3

Total Test time (real) =  13.36 sec

The following tests FAILED:
	854 - test_linalg_pinv_op (Failed)
Errors while running CTest


Test project /workspace/Paddle-sanitizer/Paddle/build
    Start  852: test_linalg_cond
1/3 Test  #852: test_linalg_cond .................   Passed    5.13 sec
    Start  854: test_linalg_pinv_op
2/3 Test  #854: test_linalg_pinv_op ..............   Passed    5.88 sec
    Start 1437: test_custom_conj
3/3 Test #1437: test_custom_conj .................   Passed    2.53 sec

100% tests passed, 0 tests failed out of 3

Total Test time (real) =  13.61 sec


Test project /workspace/Paddle-sanitizer/Paddle/build
    Start  852: test_linalg_cond
1/3 Test  #852: test_linalg_cond .................***Failed    4.77 sec
W0214 13:53:28.742112 38405 init.cc:236] AVX is available, Please re-compile on local machine
W0214 13:53:30.071043 38405 device_context.cc:509] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0214 13:53:30.074376 38405 device_context.cc:527] device: 0, cuDNN Version: 8.1.
Hint: Your machine support AVX, but the installed paddlepaddle doesn't have avx core. Hence, no-avx core with worse preformance will be imported.
If you like, you could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' to get better performance.
The original error is: No module named 'paddle.fluid.core_avx'
test_linalg_cond failed
 F.....
======================================================================
FAIL: test_out (test_linalg_cond.API_TestDygraphCond)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/Paddle-sanitizer/Paddle/build/python/paddle/fluid/tests/unittests/test_linalg_cond.py", line 95, in test_out
    test_dygraph_assert_true(self, x_list_n_n, p_list_n_n + p_list_m_n)
  File "/workspace/Paddle-sanitizer/Paddle/build/python/paddle/fluid/tests/unittests/test_linalg_cond.py", line 46, in test_dygraph_assert_true
    output.numpy(), expected_output, rtol=5e-5)
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 1531, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python3.7/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=5e-05, atol=0

Mismatched elements: 1 / 8 (12.5%)
Max absolute difference: 3.1757812
Max relative difference: 0.00014203
 x: array([[2.236384e+04, 1.326666e+02, 2.964268e+01, 2.528470e+01],
       [7.030324e+00, 7.617666e+00, 2.453774e+01, 1.225458e+01]],
      dtype=float32)
 y: array([[2.236067e+04, 1.326664e+02, 2.964268e+01, 2.528471e+01],
       [7.030324e+00, 7.617667e+00, 2.453774e+01, 1.225458e+01]],
      dtype=float32)

----------------------------------------------------------------------
Ran 6 tests in 2.382s

FAILED (failures=1)

    Start  854: test_linalg_pinv_op
2/3 Test  #854: test_linalg_pinv_op ..............   Passed    5.87 sec
    Start 1437: test_custom_conj
3/3 Test #1437: test_custom_conj .................   Passed    2.51 sec

67% tests passed, 1 tests failed out of 3

Total Test time (real) =  13.36 sec

The following tests FAILED:
	852 - test_linalg_cond (Failed)
Errors while running CTest
```

**Comment by zhwesky2010** [comment]
@zlsh80826 目前已经固定了种子，麻烦再测一下

**Comment by zlsh80826** [comment]
@zhouwei25 請問是哪個 PR 呢? 我這邊 cherry-pick 過來測試一下

**Comment by zlsh80826** [comment]
Issue has been fixed by https://github.com/PaddlePaddle/Paddle/pull/39566 and https://github.com/PaddlePaddle/Paddle/pull/39574.
