### ISSUE TITLE
InvalidArgumentError: Invalid CPU memory access

### ISSUE THREAD

**Issue by gongchenting** [PaddlePaddle/Paddle#39466]
训练前期正常，后面会突然报错InvalidArgumentError: Invalid CPU memory access

- 版本、环境信息：
    1）CPU：Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
    2）GPU：K40、CUDA10、cudnn_v7.6
- 训练信息
    1）单机多卡
    2）每卡11441MiB
- 问题描述：

Traceback (most recent call last):
  File "/home/vis/jiangminyue/v2x/his_quant/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/vis/jiangminyue/v2x/his_quant/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vis/jiangminyue/v2x/his_quant/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1146, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/vis/jiangminyue/v2x/his_quant/anaconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/vis/jiangminyue/v2x/his_quant/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1126, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/vis/jiangminyue/v2x/his_quant/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1196, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/home/vis/jiangminyue/v2x/his_quant/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 524, in __reader_creator__
    yield self.feed(item)
  File "/home/vis/jiangminyue/v2x/his_quant/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 365, in feed
    ret_dict[each_name] = each_converter.done()
  File "/home/vis/jiangminyue/v2x/his_quant/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 182, in done
    t.set(arr, self.place)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::memory::detail::MetadataCache::LoadDesc(paddle::memory::detail::MemoryBlock*)
2   paddle::memory::detail::BuddyAllocator::SplitToAlloc(std::_Rb_tree_const_iterator<std::tuple<unsigned long, unsigned long, void*> >, unsigned long)
3   paddle::memory::detail::BuddyAllocator::Alloc(unsigned long)
4   void* paddle::memory::legacy::Alloc<paddle::platform::CPUPlace>(paddle::platform::CPUPlace const&, unsigned long)
5   paddle::memory::allocation::NaiveBestFitAllocator::AllocateImpl(unsigned long)
6   paddle::memory::allocation::AllocatorFacade::Alloc(paddle::platform::Place const&, unsigned long)
7   paddle::memory::allocation::AllocatorFacade::AllocShared(paddle::platform::Place const&, unsigned long)
8   paddle::memory::AllocShared(paddle::platform::Place const&, unsigned long)
9   paddle::framework::Tensor::mutable_data(paddle::platform::Place const&, paddle::framework::proto::VarType_Type, unsigned long)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Invalid CPU memory access
  [Hint: Expected desc->CheckGuards() == true, but received desc->CheckGuards():0 != true:1.] at (/ssd3/Paddle/paddle/fluid/memory/detail/meta_cache.cc:41)

**Comment by iclementine** [comment]
可以先把 export GLOG_v=10 运行看看更多的信息。

看起来就是分配内存失败
