### ISSUE TITLE
paddlepaddle验证安装无法定位到mklml.dll文件动态链上

### ISSUE THREAD

**Issue by yufangbo** [PaddlePaddle/Paddle#39493]
版本、环境信息
1）PaddlePaddle版本：paddlepaddle：2.2.2
2）CPU：AMD Ryzen 7 5800H with Radeon Graphics
3）操作系统：Windows 10 家庭中文版 + Python 3.6.15

安装方式信息
python -m pip install paddlepaddle==2.2.2 -i https://mirror.baidu.com/pypi/simple

复现信息：命令行下import paddle成功但paddle.utils.run_check()验证安装失败

问题描述
(paddleocr) C:\Users\yufangbo>python
Python 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.fluid as fluid
>>> fluid.install_check.run_check()
Running Verify Fluid Program ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\install_check.py", line 140, in run_check
    test_simple_exe()
  File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\install_check.py", line 138, in test_simple_exe
    fetch_list=[out0.name, param_grads[1].name])
  File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\executor.py", line 1262, in run
    six.reraise(*sys.exc_info())
  File "D:\anaconda\download\envs\paddleocr\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\executor.py", line 1260, in run
    return_merged=return_merged)
  File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\executor.py", line 1402, in _run_impl
    use_program_cache=use_program_cache)
  File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\executor.py", line 1492, in _run_program
    [fetch_var_name])
RuntimeError: In user code:

    File "<stdin>", line 1, in <module>

    File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\install_check.py", line 140, in run_check
      test_simple_exe()
    File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\install_check.py", line 129, in test_simple_exe
      out0 = simple_layer0(inp0)
    File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\install_check.py", line 42, in forward
      x = self._linear1(inputs)
    File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\nn.py", line 1008, in forward
      type="matmul", inputs=inputs, outputs={"Out": tmp}, attrs=attrs)
    File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\dygraph\layer_object_helper.py", line 52, in append_op
      stop_gradient=stop_gradient)
    File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "D:\anaconda\download\envs\paddleocr\lib\site-packages\paddle\fluid\framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: The third-party dynamic library (mklml.dll) that Paddle depends on is not configured correctly. (error code is 182)
      Suggestions:
      1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
      2. Configure third-party dynamic library environment variables as follows:
      - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
      - Windows: set PATH by `set PATH=XXX; (at C:\home\workspace\Paddle_release\paddle\fluid\platform\dynload\dynamic_loader.cc:285)
      [operator < matmul > error]

**Comment by DDDivano** [comment]
amd cpu 试试noavx的版本

**Comment by LDOUBLEV** [comment]
mklml是mkldnn依赖的模块，amd上不支持mkldnn加速；

noavx的paddle版本安装： 
python -m pip download paddlepaddle==2.2.2 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps

python -m pip download paddlepaddle==2.2.2 -f https://www.paddlepaddle.org.cn/whl/windows/openblas/noavx/stable.html --no-index --no-deps

参考文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/windows-pip.html#genjubanbenjinxinganzhuang

**Comment by yufangbo** [comment]
> mklml是mkldnn依赖的模块，amd上不支持mkldnn加速；
> 
> noavx的paddle版本安装： python -m pip download paddlepaddle==2.2.2 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/noavx/stable.html --no-index --no-deps
> 
> python -m pip download paddlepaddle==2.2.2 -f https://www.paddlepaddle.org.cn/whl/windows/openblas/noavx/stable.html --no-index --no-deps
> 
> 参考文档： https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/windows-pip.html#genjubanbenjinxinganzhuang

我下载了noavx的版本验证的时候说我的机器支持avx，我看了paddle的官方文档 [paddle好像不支持家庭版的windows10系统

**Comment by zhwesky2010** [comment]
@yufangbo 支持Windows10家庭版，麻烦装下openblas版本试试 `python -m pip download paddlepaddle==2.2.2 -f https://www.paddlepaddle.org.cn/whl/windows/openblas/avx/stable.html --no-index --no-deps`

**Comment by yufangbo** [comment]
> @yufangbo 支持Windows10家庭版，麻烦装下openblas版本试试 `python -m pip download paddlepaddle==2.2.2 -f https://www.paddlepaddle.org.cn/whl/windows/openblas/avx/stable.html --no-index --no-deps`

谢谢大佬 问题已经解决了

**Comment by love-plus** [comment]
@yufangbo 请问是怎么解决的，安装mkldnn依赖的模块就可以了吗

**Comment by yufangbo** [comment]
> @yufangbo 请问是怎么解决的，安装mkldnn依赖的模块就可以了吗
python -m pip download paddlepaddle==2.2.2 -f https://www.paddlepaddle.org.cn/whl/windows/openblas/avx/stable.html --no-index --no-deps 你用这个命令安装试试
