### ISSUE TITLE
训练transformer encoder的过程中，输入超过2K的序列长度导致的训练过程异常和报错问题

### ISSUE THREAD

**Issue by wuwusky** [PaddlePaddle/Paddle#39786]
- 版本、环境信息：
    1）PaddlePaddle版本：2.2.2 gpu版本
    3）GPU：Tesla V100 PCIE 32 G，cuda：10.1，cudnn：7.6.5
    4）系统环境： Linux, python=3.7

- 训练信息
    1）单卡和单机多卡都存在问题
    2）32G显存，没有显存泄露情况，内存也正常
- 问题描述：参考 paddleHelix中的tape预训练模型，对序列数据进行训练，当最长序列设置为1024~2048的时候训练一切正常；然后增加最长序列长度限制后问题出现：
- ① 设置为3000，发现计算的loss在经过一定轮数后变为 nan
- ② 设置为4096，发现无法训练，报错提示非法内存访问，错误信息出现位置不一定，偶然会先训练几轮后抛出错误，偶尔会直接抛出错误，错误信息如下：
- 
W0221 18:31:56.758687 28071 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0221 18:31:56.769076 28071 device_context.cc:465] device: 0, cuDNN Version: 7.6.
/home/zhouhao/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:253: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.bool, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
epoch:1, step:1/163376, Loss:2.86357
epoch:1, step:2/163376, Loss:2.26879
epoch:1, step:3/163376, Loss:2.03603
epoch:1, step:4/163376, Loss:1.92704
epoch:1, step:5/163376, Loss:1.96022
epoch:1, step:6/163376, Loss:1.70171
epoch:1, step:7/163376, Loss:1.69766
epoch:1, step:8/163376, Loss:1.61913
epoch:1, step:9/163376, Loss:1.66900
epoch:1, step:10/163376, Loss:1.73385
(External) CUDA error(700), an illegal memory access was encountered.
  [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:441)

Traceback (most recent call last):
  File "train.py", line 127, in <module>
    main(args)
  File "train.py", line 100, in main
    pred = model(text, pos)
  File "/home/zhouhao/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/zhouhao/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhouhao/mRNA/pretrain/rna_sequence_model.py", line 118, in forward
    output = self.model(input, pos)
  File "/home/zhouhao/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/zhouhao/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhouhao/mRNA/pretrain/rna_sequence_model.py", line 102, in forward
    encoder_out = self.encoder_module(input, pos)
  File "/home/zhouhao/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/zhouhao/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhouhao/mRNA/pretrain/rna_sequence_model.py", line 84, in forward
    encoder_output = self.encoder_model(input, pos)
  File "/home/zhouhao/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/zhouhao/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhouhao/mRNA/pretrain/rna_sequence_model.py", line 38, in forward
    (pos == self.padding_idx).astype('float32')*1e-9, axis=[1,2]
  File "/home/zhouhao/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 264, in __impl__
    return math_op(self, other_var, 'axis', axis)
OSError: (External) CUDA error(700), an illegal memory access was encountered.
  [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:441)
  [operator < equal > error]

**Comment by yinhaofeng** [comment]
感谢您的问题反馈，同时也建议您前往paddleHelix的套件中同步提下issue吧。

**Comment by wuwusky** [comment]
> 感谢您的问题反馈，同时也建议您前往paddleHelix的套件中同步提下issue吧。

已经在那边提交issue了，但是这个问题不知道怎么解决？很奇怪的问题，回顾历史的issue中同样的错误抛出但是跟我的情况不一样，同时也根据issue中的内容尝试进行修改也没有解决问题。

**Comment by yinhaofeng** [comment]
不知道您这边方不方便提供一下复现代码和环境？我们这边尝试复现您的错误，然后进行分析或者解决？

**Comment by wuwusky** [comment]
> 不知道您这边方不方便提供一下复现代码和环境？我们这边尝试复现您的错误，然后进行分析或者解决？

我的问题，我又仔细检查了一遍流程，发现问题在transformer在定义pos embedding的时候固定写了最大是3000，所以超过3000就有问题了，这里改成跟数据设置长度一致后就没问题了，问题找到并解决，是我自己的问题！
