### ISSUE TITLE
test_jit_save_load unit test random failure

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#39818]
版本、环境信息：
   1）PaddlePaddle版本：v2.2.2, develop branch
   2）CPU/GPU：CPU
   3）系统环境： [paddlepaddle/paddle:2.2.2](https://hub.docker.com/layers/paddlepaddle/paddle/2.2.2/images/sha256-8b08aec5a3898c1478bcfd3c30fdbdb118eb53d75b7f585fc910d5173dca9c50?context=explore)
   4）Python版本号: 無
   5）显存信息

```
$ python3.7 tools/summary_env.py
****************************************
Paddle version: 2.2.2
Paddle With CUDA: False

OS: Ubuntu 18.04
Python version: 3.7.12

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************
```

复现信息：如为报错，请给出复现环境、复现步骤: 提供以下 Dockerfile

```
FROM paddlepaddle/paddle:2.2.2

RUN git clone https://github.com/PaddlePaddle/Paddle.git -b v2.2.2

RUN apt install python3-pip libasan5 -y

RUN pip install --upgrade pip && \
    pip install -r Paddle/python/requirements.txt

RUN cd Paddle && \
    mkdir -p build && \
    cd build && \
    cmake .. \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_GPU=OFF \
    -DWITH_MKL=OFF \
    -DWITH_AVX=OFF \
    -DWITH_PYTHON=ON \
    -DPY_VERSION=3.7 \
    -DWITH_TESTING=ON

RUN cd Paddle/build && make -j`nproc`
```
接著照以下指令复现

```
docker build -t paddle .
docker run --rm paddle bash -c 'cd Paddle/build && for i in `seq 1 100`; do ctest -R ^test_jit_save_load$ --output-on-failure; done' 2>&1 | tee log
```
即有可能看到隨機錯誤的訊息, 以下為錯誤的 log
```
Test project /home/Paddle/build
    Start 630: test_jit_save_load
1/1 Test #630: test_jit_save_load ...............***Failed    4.02 sec
W0222 11:13:44.114696 39686 init.cc:202] AVX is available, Please re-compile on local machine
Hint: Your machine support AVX, but the installed paddlepaddle doesn't have avx core. Hence, no-avx core with worse preformance will be imported.
If you like, you could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' to get better performance.
The original error is: No module named 'paddle.fluid.core_avx'
/home/Paddle/build/python/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
/home/Paddle/build/python/paddle/fluid/io.py:382: UserWarning: no variable in your model, please ensure there are any variables in your model to save
  "no variable in your model, please ensure there are any variables in your model to save"
/home/Paddle/build/python/paddle/fluid/dygraph/jit.py:434: UserWarning: The InputSpec(shape=(8, 8), dtype=paddle.float32, name=None)'s name is None. When using jit.save, please set InputSepc's name in to_static(input_spec=[]) and jit.save(input_spec=[]) and make sure they are consistent.
  warnings.warn(name_none_error % spec)
/home/Paddle/build/python/paddle/fluid/dygraph/jit.py:434: UserWarning: The InputSpec(shape=(8, -1), dtype=paddle.float64, name=None)'s name is None. When using jit.save, please set InputSepc's name in to_static(input_spec=[]) and jit.save(input_spec=[]) and make sure they are consistent.
  warnings.warn(name_none_error % spec)
/home/Paddle/build/python/paddle/fluid/reader.py:843: UserWarning: Please NOTE: DygraphGeneratorLoader supports returning as list only. Change to return as list.
  "Please NOTE: DygraphGeneratorLoader supports returning as list only. Change to return as list."
/home/Paddle/build/python/paddle/fluid/reader.py:136: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if arr.dtype == np.object:
/home/Paddle/build/python/paddle/fluid/dygraph/parallel.py:596: UserWarning: The program will return to single-card operation. Please check 1, whether you use spawn or fleetrun to start the program. 2, Whether it is a multi-card program. 3, Is the current environment multi-card.
  warnings.warn("The program will return to single-card operation. "
/home/Paddle/build/python/paddle/fluid/framework.py:744: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
Tue Feb 22 11:13:45 Dynamic-to-Static WARNING: Current function: forward(x), input_spec: None has more than one cached programs: 3, the last traced progam will be return by default.
/home/Paddle/build/python/paddle/fluid/dygraph/jit.py:678: UserWarning: What you save is a function, and `jit.save` will generate the name of the model file according to `path` you specify. When loading these files with `jit.load`, you get a `TranslatedLayer` whose inference result is the same as the inference result of the function you saved.
  'What you save is a function, and `jit.save` will generate the name of the model file according to `path` you specify. When loading these files with `jit.load`, you get a `TranslatedLayer` whose inference result is the same as the inference result of the function you saved.'
/home/Paddle/build/python/paddle/fluid/dygraph/jit.py:778: UserWarning: `jit.save` will only save the `Program`, not the parameters. If you have to save the parameters, please make sure that <function TestJitSaveLoadFunctionCase3.test_jit_save_load_function_function.<locals>.fun at 0x7f031b9e4710> is a member function of `paddle.nn.Layer` and the saved parameters are in `state_dict`
  format(layer))
/home/Paddle/build/python/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmpwdcdpo9r.py:13
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/Paddle/build/python/paddle/fluid/dygraph/jit.py:434: UserWarning: The InputSpec(shape=(-1, 784), dtype=paddle.float32, name=None)'s name is None. When using jit.save, please set InputSepc's name in to_static(input_spec=[]) and jit.save(input_spec=[]) and make sure they are consistent.
  warnings.warn(name_none_error % spec)
/home/Paddle/build/python/paddle/fluid/dygraph/jit.py:436: UserWarning: The tensor `feed_input` does not exists. Please make sure the name of InputSpec or example Tensor in input_spec is the same as the name of InputSpec in `to_static` decorated on the Layer.forward method.
  warnings.warn(name_no_exists_error % spec.name)
/home/Paddle/build/python/paddle/fluid/dygraph/jit.py:471: UserWarning: The tensor `generated_tensor_250` does not exists. Please make sure the name of example Tensor in configs.output_spec is the output tensor of Layer.forward method.
  warnings.warn(name_no_exists_error % var.name)
Tue Feb 22 11:13:46 Dynamic-to-Static WARNING:

You have specified `input_spec` both in function definition (higher priority) and `paddle.jit.save` (will be ignored.)

         Using: (InputSpec(shape=(-1, 784), dtype=paddle.float32, name=image), InputSpec(shape=(-1, 1), dtype=paddle.int64, name=label))

         Ignore: [InputSpec(shape=(-1, 784), dtype=paddle.float32, name=image)]

Tue Feb 22 11:13:46 Dynamic-to-Static WARNING:

You have specified `input_spec` both in function definition (higher priority) and `paddle.jit.save` (will be ignored.)

         Using: (InputSpec(shape=(-1, 784), dtype=paddle.float32, name=image), InputSpec(shape=(-1, 1), dtype=paddle.int64, name=label))

         Ignore: [InputSpec(shape=(-1, 784), dtype=paddle.float32, name=image)]

/home/Paddle/build/python/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmpn29zvec7.py:7
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/Paddle/build/python/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmpz7e12ydz.py:8
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/home/Paddle/build/python/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmpck1wbwd2.py:8
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
Tue Feb 22 11:13:47 Dynamic-to-Static WARNING: `LinearNetWithNestOut.forward` has already been decorated somewhere. It will be redecorated to replace previous one.
/home/Paddle/build/python/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmp4v22i04t.py:8
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
test_jit_save_load failed
 ........................................E......
======================================================================
ERROR: test_prune_useless_input_to_static_no_train (test_jit_save_load.TestJitSaveMultiCases)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_jit_save_load.py", line 882, in test_prune_useless_input_to_static_no_train
    self.verify_inference_correctness(layer, model_path, with_label=True)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_jit_save_load.py", line 759, in verify_inference_correctness
    loaded_pred = loaded_layer(x).numpy()
  File "/home/Paddle/build/python/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/Paddle/build/python/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/Paddle/build/python/paddle/fluid/dygraph/io.py", line 1279, in __i_m_p_l__
    return _run_dygraph(self, input, program_holder)
  File "/home/Paddle/build/python/paddle/fluid/dygraph/io.py", line 829, in _run_dygraph
    'program_id': _hash_with_id(trace_program)
  File "/home/Paddle/build/python/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) Input X's width should be equal to the Y's height, but received X's shape: [1, 784], Y's shape: [0].
  [Hint: Expected mat_dim_x.width_ == mat_dim_y.height_, but received mat_dim_x.width_:784 != mat_dim_y.height_:0.] (at /home/Paddle/paddle/fluid/operators/matmul_op.cc:638)
  [operator < matmul > error]  [operator < run_program > error]

----------------------------------------------------------------------
Ran 47 tests in 2.854s

FAILED (errors=1)



0% tests passed, 1 tests failed out of 1

Total Test time (real) =   4.07 sec

The following tests FAILED:
        630 - test_jit_save_load (Failed)
Errors while running CTest
```

**Comment by zlsh80826** [comment]
The problem has been fixed.
