### ISSUE TITLE
训练swin-transformer时，随机崩溃出现CUDA error(700), an illegal memory access was encountered

### ISSUE THREAD

**Issue by TinyQi** [PaddlePaddle/Paddle#39866]
- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu  2.2.0rc0.post101
    3）GPU：GPU  T4
    4）系统环境：CenterOS7

- 训练信息
    1） 单卡T4、单卡V100都试过
- 复现信息：基本上每次都会崩溃
- 问题描述：训练swin-transfomer模型时，改了几个必要的参数，其余基本上就没动了，都是沿用原始的配置，然后一开始训练，有时候1个epoch没满就崩溃，有时候几个epoch再崩溃。每次崩溃时，打印的日志都是下面这一段

- 
- 下面是崩溃时的日志
[02/22 14:11:00] ppdet.data.source.voc WARNING: Found an invalid bbox in annotations: xml_file: /share/disk2/data/02.detection/01.pfw/pfw/has_obj/./Annotations/c1003c8389fc6baecc56fe5c886e4cc7.xml, x1: 0, y1: 0, x2: 0.0, y2: 0.0.
[02/22 14:11:00] ppdet.data.source.voc WARNING: Found an invalid bbox in annotations: xml_file: /share/disk2/data/02.detection/01.pfw/pfw/has_obj/./Annotations/c13a2920f43a0c5fe6c1066026d943a9.xml, x1: 0, y1: 0, x2: 0.0, y2: 0.0.
W0222 14:11:00.176617 26525 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 10.1, Runtime API Version: 10.1
W0222 14:11:00.181706 26525 device_context.cc:465] device: 0, cuDNN Version: 7.5.
W0222 14:11:00.958298 26525 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 7.6, but CUDNN version in your machine is 7.5, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
[02/22 14:11:04] ppdet.engine INFO: Epoch: [0] [   0/1481] learning_rate: 0.000010 loss_rpn_cls: 0.698239 loss_rpn_reg: 0.341781 loss_bbox_cls: 1.299142 loss_bbox_reg: 0.005312 loss: 2.344474 eta: 4:05:04 batch_cost: 0.8274 data_cost: 0.0003 ips: 2.4172 images/s
[02/22 14:11:24] ppdet.engine INFO: Epoch: [0] [  20/1481] learning_rate: 0.000012 loss_rpn_cls: 0.675141 loss_rpn_reg: 0.321593 loss_bbox_cls: 0.285954 loss_bbox_reg: 0.019696 loss: 1.437952 eta: 4:50:31 batch_cost: 0.9897 data_cost: 0.0002 ips: 2.0208 images/s
Traceback (most recent call last):
  File "tools/train.py", line 171, in <module>
    main()
  File "tools/train.py", line 167, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/share/disk1/training_tools/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 398, in train
    outputs = model(data)
  File "/root/anaconda3/envs/paddle_2.2.0_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/share/disk1/training_tools/PaddleDetection-release-2.3/ppdet/modeling/architectures/meta_arch.py", line 54, in forward
    out = self.get_loss()
  File "/share/disk1/training_tools/PaddleDetection-release-2.3/ppdet/modeling/architectures/faster_rcnn.py", line 95, in get_loss
    rpn_loss, bbox_loss = self._forward()
  File "/share/disk1/training_tools/PaddleDetection-release-2.3/ppdet/modeling/architectures/faster_rcnn.py", line 77, in _forward
    bbox_loss, _ = self.bbox_head(body_feats, rois, rois_num,
  File "/root/anaconda3/envs/paddle_2.2.0_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/share/disk1/training_tools/PaddleDetection-release-2.3/ppdet/modeling/heads/bbox_head.py", line 237, in forward
    rois, rois_num, targets = self.bbox_assigner(rois, rois_num, inputs)
  File "/share/disk1/training_tools/PaddleDetection-release-2.3/ppdet/modeling/proposal_generator/target_layer.py", line 165, in __call__
    outs = generate_proposal_target(
  File "/share/disk1/training_tools/PaddleDetection-release-2.3/ppdet/modeling/proposal_generator/target.py", line 215, in generate_proposal_target
    sampled_inds, sampled_gt_classes = sample_bbox(
  File "/share/disk1/training_tools/PaddleDetection-release-2.3/ppdet/modeling/proposal_generator/target.py", line 268, in sample_bbox
    fg_inds, bg_inds = subsample_labels(gt_classes, rois_per_image, fg_fraction,
  File "/share/disk1/training_tools/PaddleDetection-release-2.3/ppdet/modeling/proposal_generator/target.py", line 137, in subsample_labels
    positive = paddle.nonzero(
  File "/root/anaconda3/envs/paddle_2.2.0_gpu/lib/python3.8/site-packages/paddle/tensor/search.py", line 382, in nonzero
    outs = _C_ops.where_index(x)
OSError: (External) CUDA error(700), an illegal memory access was encountered.
  [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:428)

**Comment by TinyQi** [comment]
补充一下，并且基本上每次训练都会伴随nan的出现，我将学习率降低为原来的一半也会出现问题

**Comment by windstamp** [comment]
请问 swin-transformer 也是使用的 Paddle 的模型套件吗，请提供一下复现代码。

另外，你是采用动态图还是静态图模式训练的。有尝试过减少 batch size 试试吗？

**Comment by TinyQi** [comment]
> 请问 swin-transformer 也是使用的 Paddle 的模型套件吗，请提供一下复现代码。
> 
> 另外，你是采用动态图还是静态图模式训练的。有尝试过减少 batch size 试试吗？

1. 训练套件使用的是PaddleDetection2.3训练套件，没改过代码，只改过一些必要配置文件的惨呼
2. 应该是采用默认的动态图的训练模型
3. 默认的batchsize就是2，我尝试过增加到3和4，上述问题仍会出现
4. 我还尝试将学习率减半，上述问题仍会出现

**Comment by windstamp** [comment]
我本地基于 PaddleDetection2.3 先复现看看，有进展及时反馈给你。

我测试的配置文件是 configs/faster_rcnn/faster_rcnn_swin_tiny_fpn_1x_coco.yml
```
python tools/train.py \
    --eval \
    -c configs/faster_rcnn/faster_rcnn_swin_tiny_fpn_1x_coco.yml \
    -o norm_type=bn use_gpu=True use_npu=False
```

<img width="1384" alt="5e5e99f66eb022acd0818d49c4a2e126" src="https://user-images.githubusercontent.com/34057289/155646978-a19e0484-953c-4639-8a28-89ce98424eeb.png">

另外，请问你测试环境的 GPU 显存是多少的。

同时，建议 cuda-memcheck 工具本地先查一下看看，  cuda-memcheck  python xxx.py

**Comment by TinyQi** [comment]
> 我本地基于 PaddleDetection2.3 先复现看看，有进展及时反馈给你。
> 
> 我测试的配置文件是 configs/faster_rcnn/faster_rcnn_swin_tiny_fpn_1x_coco.yml
> 
> ```
> python tools/train.py \
>     --eval \
>     -c configs/faster_rcnn/faster_rcnn_swin_tiny_fpn_1x_coco.yml \
>     -o norm_type=bn use_gpu=True use_npu=False
> ```
> 
> <img alt="5e5e99f66eb022acd0818d49c4a2e126" width="1384" src="https://user-images.githubusercontent.com/34057289/155646978-a19e0484-953c-4639-8a28-89ce98424eeb.png">
> 
> 另外，请问你测试环境的 GPU 显存是多少的。
> 
> 同时，建议 cuda-memcheck 工具本地先查一下看看， cuda-memcheck python xxx.py

我没有指定norm_type=bn
另外我主要尝试的显卡是T4（16G显存）

**Comment by windstamp** [comment]
目前复测到 Epoch 5，没有出现任何问题。

我复测的环境是 V100 16GB 显存， paddle 是基于最新 develop 分支编译的，CUDA 10.2 + cudnn 7，你也可以采用官方提供的 Daily wheel。
```
python -m pip install paddlepaddle-gpu==0.0.0.post102 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
```

安装文档参考 https://www.paddlepaddle.org.cn/

模型训练到命令是，数据集是默认的 coco 2017。
```
python tools/train.py \
    --eval \
    -c configs/faster_rcnn/faster_rcnn_swin_tiny_fpn_1x_coco.yml \
    -o norm_type=bn use_gpu=True use_npu=False
```

使用的是 docker 环境 https://hub.docker.com/layers/paddlepaddle/paddle/latest-gpu-cuda10.2-cudnn7-dev/images/sha256-5faf0c6d603e301e9d7e5d0ffbfb30be32ae7dc2006ab3215259f743f52932c2?context=explore
```
docker pull paddlepaddle/paddle:latest-gpu-cuda10.2-cudnn7-dev
```

建议先这样试试，看看是否还会出现问题。


附：
1. 利用 cuda-memcheck 工具，本地先查一下看看是什么问题， cuda-memcheck python xxx.py
2. 我这边的训练日志 链接: https://pan.baidu.com/s/175yBuALhOL-chQch-Pkg3Q 提取码: n22o
