### ISSUE TITLE
Paddle运行出错C++ Traceback (most recent call last)错误

### ISSUE THREAD

**Issue by AbbottKilig** [PaddlePaddle/Paddle#39929]
Paddle版本2.2.2
错误信息如下：

-

--------------------------------------
--
C++ Traceback (most recent call last):
--------------------------------------
0 paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1 paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2 paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
3 std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, double> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
4 paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
5 paddle::operators::math::Im2ColFunctor<(paddle::operators::math::ColFormat)0, paddle::platform::CPUDeviceContext, float>::operator()(paddle::platform::CPUDeviceContext const&, paddle::framework::Tensor const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, paddle::framework::Tensor*, paddle::framework::DataLayout)
 
----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
[TimeInfo: *** Aborted at 1645699668 (unix time) try "date -d @1645699668" if you are using GNU date ***]
[SignalInfo: *** SIGSEGV (@0x7f34dcf02080) received by PID 1495 (TID 0x7f3dce4f3740) from PID 18446744073121308800 ***]
 
2022-02-24 18:53:46,159 - traitlets - ERROR - Kernel died while waiting for execute reply.
Traceback (most recent call last):
File "/root/miniconda3/lib/python3.6/site-packages/nbclient/client.py", line 838, in async_execute_cell
exec_reply = await self.task_poll_for_reply
File "/root/miniconda3/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
future.result()
concurrent.futures._base.CancelledError
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
File "/root/miniconda3/bin/jupyter-nbconvert", line 8, in <module>
sys.exit(main())
File "/root/miniconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 254, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "/root/miniconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
app.start()
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
self.convert_notebooks()
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
self.convert_single_notebook(notebook_filename)
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
return self.from_file(f, resources=resources, **kw)
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/html.py", line 119, in from_notebook_node
return super().from_notebook_node(nb, resources, **kw)
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 369, in from_notebook_node
nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
nb_copy, resources = self._preprocess(nb_copy, resources)
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
nbc, resc = preprocessor(nbc, resc)
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
return self.preprocess(nb, resources)
File "/root/miniconda3/lib/python3.6/site-packages/aistudio_notebook/public/executor.py", line 43, in preprocess
return self.preprocessor.preprocess(nb, resources)
File "/root/miniconda3/lib/python3.6/site-packages/aistudio_notebook/public/pai_preprocessor_v2.py", line 44, in preprocess
return super(PaiPreprocessorV2, self).preprocess(nb, resources)
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
self.execute()
File "/root/miniconda3/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
return just_run(coro(*args, **kwargs))
File "/root/miniconda3/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
return loop.run_until_complete(coro)
File "/root/miniconda3/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
return future.result()
File "/root/miniconda3/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
cell, index, execution_count=self.code_cells_executed + 1
File "/root/miniconda3/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
File "/root/miniconda3/lib/python3.6/site-packages/aistudio_notebook/public/pai_preprocessor_v2.py", line 57, in preprocess_cell
cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
File "/root/miniconda3/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
return just_run(coro(*args, **kwargs))
File "/root/miniconda3/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
return loop.run_until_complete(coro)
File "/root/miniconda3/lib/python3.6/site-packages/nest_asyncio.py", line 81, in run_until_complete
return f.result()
File "/root/miniconda3/lib/python3.6/asyncio/tasks.py", line 182, in _step
result = coro.throw(exc)
File "/root/miniconda3/lib/python3.6/site-packages/nbclient/client.py", line 842, in async_execute_cell
raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died

**Comment by ZHUI** [comment]
请问这个是在运行什么代码时候出现的问题？

**Comment by AbbottKilig** [comment]
运行paddlespecch语音识别的时候，出现这个错误

**Comment by ZHUI** [comment]
可否提供相关代码？
