### ISSUE TITLE
PaddleSlim非结构化稀疏转inference模型报错.

### ISSUE THREAD

**Issue by Water2style** [PaddlePaddle/Paddle#39974]
Hello 您好，
我按照官网的demo训练完后，准备将其用paddle-inference在nvgpu上部署,结果在 jit.save时报错.（错误报告后面贴出）

并且想请教如下问题：
1.非结构化稀疏后的模型，是否更适合在CPU上预测，或者GPU也行？CPU的话, X86和Arm是否都支持？
2.官方文档里没有看到让转inference相关的教程，难道非结构化稀疏后的模型是使用PaddleLite套件吗~?
谢谢！

jit.save的错误报告如下：

Traceback (most recent call last):
  File "un_sparse.py", line 470, in <module>
    main()
  File "un_sparse.py", line 466, in main
    compress(args)
  File "un_sparse.py", line 448, in compress
    export_to_inference(args,net)
  File "un_sparse.py", line 140, in export_to_inference
    paddle.jit.save(infer_net, inference_save_path)
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 743, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 495, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 406, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 709, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 668, in from_func_spec
    error_data.raise_new_exception()
  File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "../PaddleClas/ppcls/arch/backbone/legendary_models/mobilenet_v1.py", line 164, in forward
        x = self.conv(x)
    File "../PaddleClas/ppcls/arch/backbone/legendary_models/mobilenet_v1.py", line 67, in forward
        def forward(self, x):
            x = self.conv(x)
            ~~~~~~~~~~~~~~~~ <--- HERE
            x = self.bn(x)
            x = self.relu(x)

    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 894, in __call__
        hook_result = forward_pre_hook(self, inputs)
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddleslim/dygraph/prune/unstructured_pruner.py", line 166, in _forward_pre_hook
        self.mask_parameters(param, mask)
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddleslim/dygraph/prune/unstructured_pruner.py", line 69, in mask_parameters
        param_tmp = param * mask
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py", line 313, in __impl__
        other_var = create_scalar(
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py", line 98, in create_scalar
        return create_tensor(block, value, dtype, shape=[1])
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py", line 82, in create_tensor
        value = float(value)
    File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 116, in _float_
        assert numel == 1, "only one element variable can be converted to float."

    AssertionError: only one element variable can be converted to float.

**Comment by minghaoBD** [comment]
> Hello 您好， 我按照官网的demo训练完后，准备将其用paddle-inference在nvgpu上部署,结果在 jit.save时报错.（错误报告后面贴出）
> 
> 并且想请教如下问题： 1.非结构化稀疏后的模型，是否更适合在CPU上预测，或者GPU也行？CPU的话, X86和Arm是否都支持？ 2.官方文档里没有看到让转inference相关的教程，难道非结构化稀疏后的模型是使用PaddleLite套件吗~? 谢谢！
> 
> jit.save的错误报告如下：
> 
> Traceback (most recent call last): File "un_sparse.py", line 470, in main() File "un_sparse.py", line 466, in main compress(args) File "un_sparse.py", line 448, in compress export_to_inference(args,net) File "un_sparse.py", line 140, in export_to_inference paddle.jit.save(infer_net, inference_save_path) File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in **impl** return wrapped_func(*args, **kwargs) File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in **impl** return func(*args, **kwargs) File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 743, in save concrete_program = static_func.concrete_program_specify_input_spec( File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 495, in concrete_program_specify_input_spec concrete_program, _ = self.get_concrete_program( File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 406, in get_concrete_program concrete_program, partial_program_layer = self._program_cache[cache_key] File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in **getitem** self._caches[item] = self._build_once(item) File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 709, in _build_once concrete_program = ConcreteProgram.from_func_spec( File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in **impl** return wrapped_func(*args, **kwargs) File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 40, in **impl** return func(*args, **kwargs) File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 668, in from_func_spec error_data.raise_new_exception() File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception six.exec_("raise new_exception from None") File "", line 1, in AssertionError: In transformed code:
> 
> ```
> File "../PaddleClas/ppcls/arch/backbone/legendary_models/mobilenet_v1.py", line 164, in forward
>     x = self.conv(x)
> File "../PaddleClas/ppcls/arch/backbone/legendary_models/mobilenet_v1.py", line 67, in forward
>     def forward(self, x):
>         x = self.conv(x)
>         ~~~~~~~~~~~~~~~~ <--- HERE
>         x = self.bn(x)
>         x = self.relu(x)
> 
> File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 894, in __call__
>     hook_result = forward_pre_hook(self, inputs)
> File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddleslim/dygraph/prune/unstructured_pruner.py", line 166, in _forward_pre_hook
>     self.mask_parameters(param, mask)
> File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddleslim/dygraph/prune/unstructured_pruner.py", line 69, in mask_parameters
>     param_tmp = param * mask
> File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py", line 313, in __impl__
>     other_var = create_scalar(
> File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py", line 98, in create_scalar
>     return create_tensor(block, value, dtype, shape=[1])
> File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py", line 82, in create_tensor
>     value = float(value)
> File "/home/xieyunyao/miniconda3/envs/PP22/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 116, in _float_
>     assert numel == 1, "only one element variable can be converted to float."
> 
> AssertionError: only one element variable can be converted to float.
> ```

您好，

1. 关于报错，我猜测跟export_model时声明了pruner有关。如果是这么做的，建议在export推理模型时，不加pruner声明，只是导入模型参数即可。如果不是，麻烦提供下复现代码，我具体看一下。
2. 关于使用设备，目前只基于PaddleLite支持arm CPU设备。paddle-inference的话，还没有加速效果。
