### ISSUE TITLE
paddle v2训练出错 有时候能全部训练完成(50轮)，有时候只能跑20轮出错

### ISSUE THREAD

**Issue by xieshufu** [PaddlePaddle/Paddle#3998]
网络结构如下：

```python
import paddle.v2 as paddle
from paddle.v2.layer import parse_network

__all__ = ['ocr_4conv_net']


def ocr_4conv_net(input, classdim):
    def conv_block(ipt, num_filters_, num_channels=None):
        conv_layer_attr = paddle.attr.ParamAttr(momentum=0.9, 
            initial_mean=0.0,
            initial_std=0.0005)
        conv_bias_attr = paddle.attr.ParamAttr(momentum=0.9,
            initial_mean=0,
            initial_std=0.0)
        return paddle.networks.simple_img_conv_pool(
            input=ipt,
            filter_size=3,
            num_filters=num_filters_,
            conv_stride=1,
            conv_padding=1,
            param_attr=conv_layer_attr,
            bias_attr=conv_bias_attr,
            num_channel=num_channels,
            groups=1,
            pool_size=2, 
            pool_type=paddle.pooling.Max(),
            pool_stride=2,
            pool_padding=0)
    def gru_layer(input, size, reverse):
        gru_layer_attr = paddle.attr.Param(learning_rate=0.001,
            momentum=0.9,
            initial_mean=0.0,
            initial_std=0.02)
        gru_bias_attr = paddle.attr.Param(learning_rate=0.001,
            momentum=0.9,
            initial_mean=0.0,
            initial_std=0.02)
        return paddle.networks.simple_gru2(input=input,
            size=size,
            name=None,
            reverse=reverse,
            mixed_param_attr=None,
            mixed_bias_attr=None,
            gru_param_attr=gru_layer_attr,
            gru_bias_attr=gru_bias_attr,
            act=paddle.activation.Relu(),
            gate_act=paddle.activation.Sigmoid(),
            mixed_layer_attr=None,
            gru_cell_attr=None)

    conv1_1 = conv_block(input, 16, 1)
    conv2_1 = conv_block(conv1_1, 32, 16)
    conv3_1 = conv_block(conv2_1, 64, 32)
    conv4_1 = conv_block(conv3_1, 128, 64)
    block5 = paddle.layer.block_expand(input=conv4_1,
        num_channels=128,
        stride_x=1,
        stride_y=1,
        padding_x=0,
        padding_y=0,
        block_x=1,
        block_y=3)
    gated1 = gru_layer(block5, 200, False)
    gated2 = gru_layer(block5, 200, True)
    fc_bias_attr = paddle.attr.Param(learning_rate=0.001,
        momentum=0.9,
        initial_mean=0,
        initial_std=0.0)
    output = paddle.layer.fc(input=[gated1, gated2], 
        size=classdim,
        act=paddle.activation.Linear(),
        bias_attr=fc_bias_attr)
    return output
if __name__ == "__main__":
    #print(parse_network(ocr_4conv_net("data")))
    a = [1, 2, 3, 4, 5, 6]
    print a[0:3]
```
训练程序如下：
```python
import gzip
import sys
import time
import paddle.v2 as paddle
from ocr_8conv import ocr_8conv_net
from ocr_4conv import ocr_4conv_net
#from ocr_reader import train_reader, test_reader
from ocr_data import DataGenerator

def main():
    datadim = 48 * 48 * 1
    classdim = 21501

    # PaddlePaddle init
    paddle.init(use_gpu=True, trainer_count=1)

    image = paddle.layer.data(
        name="image", type=paddle.data_type.dense_vector(datadim))

    # Add neural network config
    # option 1. resnet
    # net = resnet_cifar10(image, depth=32)
    # option 2. vgg
    output = ocr_4conv_net(image, classdim+1)

    lbl = paddle.layer.data(
        name="label", type=paddle.data_type.integer_value_sequence(classdim))
    cost = paddle.layer.warp_ctc(input=output, 
        label=lbl, 
        size=classdim+1,
        blank=classdim,
        norm_by_times=True)
    ctc_eval = paddle.evaluator.ctc_error(input=output, label=lbl)

    # Create parameters
    model_path = "" #"./result/1.tar"
    if model_path == "":
        parameters = paddle.parameters.create(cost)
    else:
        model_file = open(model_path, 'r')
        parameters = paddle.parameters.Parameters.from_tar(model_file)
        print "load paramters from ", model_path

    train_list_path = "/home/vis/xieshufu/PADDLE/Data/Cigerette/train_set/train_3W.list"
    test_list_path = "/home/vis/xieshufu/PADDLE/Data/Cigerette/test_set/test_image.list"
    train_generator = DataGenerator(file_list_path=train_list_path)
    test_generator = DataGenerator(file_list_path=test_list_path)
    train_batch_reader = train_generator.batch_train_reader_creator(batch_size=32)
    test_batch_reader = test_generator.batch_test_reader_creator(batch_size=1)

    # Create optimizer
    momentum_optimizer = paddle.optimizer.Momentum(
        momentum=0.9,
        learning_rate=0.001)

    # End batch and end pass event handler
    def event_handler(event):
        global start_time
        if isinstance(event, paddle.event.EndIteration):
            if (event.batch_id+1) % 312 == 0:
                print "\n", time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())
                print "Pass %d, Batch %d, Cost %f, %s" %   (event.pass_id, event.batch_id, event.cost, event.metrics)
            else:
                sys.stdout.write('.')
                sys.stdout.flush()
            
            if (event.batch_id+1) % 1000 == 0:
                result = trainer.test(
                    reader=test_batch_reader,
                    feeding={'image': 0,
                             'label': 1})
                print "\n", time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),
                print "Test with Pass %d_%d, %s" % (event.pass_id, event.batch_id, result.metrics)
        if isinstance(event, paddle.event.BeginPass):
            start_time = time.time()
        if isinstance(event, paddle.event.EndPass):
            # save parameters
            with open('./result/params_pass_%d.tar' % event.pass_id, 'w') as f:
                parameters.to_tar(f)

            result = trainer.test(
                reader=test_batch_reader,
                feeding={'image': 0,
                         'label': 1})
            print "\n", time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()), "Test with Pass %d, %s" % (event.pass_id, result.metrics)

    # Create trainer
    trainer = paddle.trainer.SGD(
        cost=cost, 
        parameters=parameters, 
        update_equation=momentum_optimizer,
        extra_layers=ctc_eval)
    trainer.train(
        reader=train_batch_reader,
        num_passes=50,
        event_handler=event_handler,
        feeding={'image': 0,'label': 1})

if __name__ == '__main__':
    main()
```
有时候能全部训练完成(50轮)，有时候只能跑20轮出错
错误信息如下： 

```text
326 .Traceback (most recent call last):
327   File "ocr_train.py", line 114, in <module>
328     main()
329   File "ocr_train.py", line 111, in main
330     feeding={'image': 0,'label': 1})
331   File "/home/vis/.jumbo/lib/python2.7/site-packages/paddle/v2/trainer.py", line 178, in train
332     self.__parameter_updater__.finishBatch(cost)
333   File "/home/vis/.jumbo/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 1531, in finishBatch
334     return _swig_paddle.ParameterUpdater_finishBatch(self, *args)
335 OverflowError: in method 'ParameterUpdater_finishBatch', argument 2 of type 'float'
336 Exception in thread Thread-339 (most likely raised during interpreter shutdown):
337 Traceback (most recent call last):
338   File "/home/vis/.jumbo/lib/python2.7/threading.py", line 551, in __bootstrap_inner
339   File "/home/vis/.jumbo/lib/python2.7/threading.py", line 504, in run
340   File "/home/vis/.jumbo/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 281, in order_handle_worker
341 <type 'exceptions.TypeError'>: isinstance() arg 2 must be a class, type, or tuple of classes and types
342 Exception in thread Thread-337 (most likely raised during interpreter shutdown):
343 Traceback (most recent call last):
344   File "/home/vis/.jumbo/lib/python2.7/threading.py", line 551, in __bootstrap_inner
345   File "/home/vis/.jumbo/lib/python2.7/threading.py", line 504, in run
346   File "/home/vis/.jumbo/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 262, in order_read_worker
347   File "/home/vis/.jumbo/lib/python2.7/Queue.py", line 126, in put
348   File "/home/vis/.jumbo/lib/python2.7/threading.py", line 237, in wait
```

**Comment by hedaoyuan** [comment]
```
335 OverflowError: in method 'ParameterUpdater_finishBatch', argument 2 of type 'float'
```
看起来像是finishBatch（梯度更新）的时候浮点溢出了。调节一下`learning_rate`或者用 [`Adam`](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/optimizer.py#L25https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/optimizer.py#L25)等其他算法试一下？

**Comment by xieshufu** [comment]
好的，我试试看

**Comment by chengduoZH** [comment]
该issue长期没有更新，暂时先关闭了，如果需继续讨论再打开
