### ISSUE TITLE
ERROR while assign topk in paddle.metric.Accuracy

### ISSUE THREAD

**Issue by hermitgreen** [PaddlePaddle/Paddle#40110]
2.2.2.post112 Python3.8 CentOS7

sample:
```python
import paddle
metric = paddle.metric.Accuracy(topk=1)
```

got

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yangbo25/software/conda/envs/paddle/lib/python3.8/site-packages/paddle/metric/metrics.py", line 240, in __init__
    self.maxk = max(topk)
TypeError: 'int' object is not iterable
```

**Comment by hermitgreen** [comment]
In source code I found
```
topk (int|list[int]|tuple[int]) – Number of top elements to look at for computing accuracy. Default is (1,).
```

It seems int is unwork

```
self.maxk = max(topk) # topk is int
```

**Comment by minghaoBD** [comment]
You may consider this API for instant fix on your side: paddle.metric.accuracy() https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/metric/accuracy_cn.html#accuracy

btw, as for Accuracy(), it seems inconsistent for the documentation and source code. We will dig into it.
