### ISSUE TITLE
提交集群预测任务失败

### ISSUE THREAD

**Issue by jcqu** [PaddlePaddle/Paddle#4020]
1、尝试提交一个集群预测任务失败了，报错信息：
```bash
usage: paddle [--help] [<args>]
These are common paddle commands used in various situations:
    train             Start a paddle_trainer
    merge_model       Start a paddle_merge_model
    pserver           Start a paddle_pserver_main
    version           Print paddle version
    dump_config       Dump the trainer config as proto string
    make_diagram      Make Diagram using Graphviz

'paddle train --help' 'paddle merge_model --help', 'paddle pserver --help', list more detailed usage of each command
ltr_infer_online.sh: line 39: --test_data_path: command not found
```

配置如下：
```bash
 18 key=`date -d "0 hour" +%Y%m%d%H%M%S`
 19 test_data_path="*/daily/${now_day}/testdata"
 20 model_path="*/model_file/infer_params.tar.gz"
 21 output_path="*/daily/${now_day}/output"
 22 hadoop fs -rmr $output_path
 23 hadoop fs -mkdir $output_path
 24
 25 paddle cluster_train \
 26   --config ltr_infer_online.py \
 27   --use_remote_sparse 0 \
 28   --use_gpu cpu \
 29   --port 8306 \
 30   --ports_num 8 \
 31   --time_limit 512:00:00 \
 32   --submitter qujinchun \
 33   --config_args is_predict=1 \
 34   --num_nodes 20 \
 35   --job_priority normal \
 36   --fs_name *** \
 37   --fs_ugi *** \
 38   --init_model_path ${model_path} \
 39   --test_data_path ${test_data_path} \
 40   --output_path ${output_path} \
 41   --where *** \
 42   --job_name paddle_cluster_ranknet_$key
```

重装客户端后，运行报错：
```bash
Reason: [Errno 111] Connection refused
connect to receiver:  *:8888
finished to pack request
starting to submit to server
Traceback (most recent call last):
  File "/home/forum/qujinchun/paddle_client/output/submit.py", line 303, in <module>
    no_prefix_train_args_dict, ).run()
  File "/home/forum/qujinchun/paddle_client/output/submit.py", line 77, in run
    self._do_poster_request()
  File "/home/forum/qujinchun/paddle_client/output/submit.py", line 168, in _do_poster_request
    connection = urllib2.urlopen(request)
  File "/home/forum/lhl/paddle/python27/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/forum/lhl/paddle/python27/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/forum/lhl/paddle/python27/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/forum/lhl/paddle/python27/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/forum/lhl/paddle/python27/lib/python2.7/site-packages/poster/streaminghttp.py", line 142, in http_open
    return self.do_open(StreamingHTTPConnection, req)
  File "/home/forum/lhl/paddle/python27/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
```
可能是网络原因，重新运行后成功。

**Comment by Yancey1989** [comment]
请按内网Wiki中的步骤安装paddle集群客户端。

**Comment by jcqu** [comment]
@Yancey1989 请问有具体链接嘛？各版本问题太乱了，不知道哪个为准

**Comment by jcqu** [comment]
@Yancey1989 我成功提交任务了，但是运行失败退出。
[FATAL]: mpirun download_init_model.sh failed'
我该如何定位问题出处，或者如何修改呢？谢谢

**Comment by lxk1990727** [comment]
同样问题，求指导。
