### ISSUE TITLE
【Conda Install paddlepaddle-gpu Error】ImportError: paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by Irvingao** [PaddlePaddle/Paddle#40215]
- 版本、环境信息：

    1）PaddlePaddle版本：
`paddlepaddle-gpu==2.2.2  cudatoolkit=11.2`

    2）CPU：
```
(paddle) pc@pc-Irvingao:~$ cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
     16  11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
```
    3）GPU：
```
(paddle) pc@pc-Irvingao:~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
(paddle) pc@pc-Irvingao:~$ dpkg -l | grep cudnn
ii  libcudnn8                                  8.2.1.32-1+cuda11.3                             amd64        cuDNN runtime libraries
ii  libcudnn8-dev                              8.2.1.32-1+cuda11.3                             amd64        cuDNN development libraries and headers
ii  libcudnn8-samples                          8.2.1.32-1+cuda11.3                             amd64        cuDNN documents and samples
```
The cudnn which I installed supports cuda version 11.1, 11.2 and 11.3.
    4）系统环境：
```
(paddle) pc@pc-Irvingao:~$ cat /etc/issue
Ubuntu 18.04.6 LTS \n \l
(paddle) pc@pc-Irvingao:~$ uname -a
Linux pc-Irvingao 5.4.0-84-generic #94~18.04.1-Ubuntu SMP Thu Aug 26 23:17:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

- 安装方式信息：
1）Using conda to install: `conda install paddlepaddle-gpu==2.2.2 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`

```
(paddle) pc@pc-Irvingao:~$ python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import avx core while this file exists: /home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/core.py", line 294, in <module>
    raise e
  File "/home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
>>> 
```

**Comment by Irvingao** [comment]
I got the same error when I install paddlepaddle cpu version. As a consequence, are there some related dependences lost or missing?

- Download cpu version: 

`
conda install paddlepaddle==2.2.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/`

- Error report: 
```
(paddle) pc@pc-Irvingao:~$ python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import avx core while this file exists: /home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/core.py", line 294, in <module>
    raise e
  File "/home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /home/pc/anaconda3/envs/paddle/lib/python3.6/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
```

**Comment by Irvingao** [comment]
I have installed gcc-5 a few days ago, the version info as follow: 
```
(paddle) pc@pc-Irvingao:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.5.0-12ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-12ubuntu1) 
```

**Comment by zhiboniu** [comment]
Paddle is tested in gcc8 and gcc5 is not well supported, maybe you can try gcc8 it should work well.

**Comment by mmdbhs** [comment]
i have tried gcc8, it did't work

**Comment by jack-lijing** [comment]
gcc 11 did't work.

**Comment by holdengreen** [comment]
I have the same error.
Although I'm using CPU and my GCC is recent.

**Comment by chiyuki0325** [comment]
gcc 12 didn't work

**Comment by mnansary** [comment]
same error
