### ISSUE TITLE
更新工具链及依赖，提供Python 3.10以及VS 2019+的支持

### ISSUE THREAD

**Issue by liudonghua123** [PaddlePaddle/Paddle#40212]
欢迎您对PaddlePaddle提出建议，非常感谢您对PaddlePaddle的贡献！
在留下您的建议时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddlePaddle版本：2.2.2
2）CPU/GPU：CPU
3）系统环境：Windows 11
注：您可以通过执行[summary_env.py](https://github.com/PaddlePaddle/Paddle/blob/develop/tools/summary_env.py)获取以上信息。

```shell
D:\code\python\Paddle>python tools\summary_env.py
****************************************
Paddle version: None
Paddle With CUDA: None

OS: Windows 10
Python version: 3.10.2

CUDA version: None
cuDNN version: None
Nvidia driver version: 456.71
****************************************

D:\code\python\Paddle>
```
希望可以提供Python3.10的支持，Python 3.10已经发布很长一段时间了，社区里的很多包都已经支持了，我也尝试很多方式都不行，本地根据 https://www.paddlepaddle.org.cn/documentation/docs/en/install/compile/windows-compile_en.html#compile_from_host 编译，因为没有vs2017，使用了vs2019也报了很多其他错误。

```shell
D:\code\python\Paddle\build>ninja all
[6/1779] Performing configure step for 'extern_protobuf'
FAILED: third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-configure D:/code/python/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-configure
cmd.exe /C "cd /D D:\code\python\Paddle\build\third_party\protobuf\src\extern_protobuf-build && "C:\Program Files\CMake\bin\cmake.exe" -P D:/code/python/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-configure-Release.cmake && "C:\Program Files\CMake\bin\cmake.exe" -E touch D:/code/python/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-configure"
CMake Error at D:/code/python/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-configure-ReleCMake Error at D:/code/python/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-configure-Release.cmake:49 (message):
  Command failed: 1

   'C:/Program Files/CMake/bin/cmake.exe' 'D:/code/python/Paddle/build/third_party/protobuf/src/extern_protobuf/cmake' '-DCMAKE_CXX_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe' '-DCMAKE_C_COMPILER=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe' '-DCMAKE_C_FLAGS=/DWIN32 /D_WINDOWS  /W0  /w /wd4068 /wd4129 /wd4244 /wd4267 /wd4297 /wd4530 /wd4577 /wd4819 /wd4838' '-DCMAKE_C_FLAGS_DEBUG=/MTd /Zi /Ob0 /Od /RTC1 /bigobj /Zc:inline' '-DCMAKE_C_FLAGS_RELEASE=/MT /O2 /Ob2 /DNDEBUG /bigobj /Zc:inline' '-DCMAKE_CXX_FLAGS=/DWIN32 /D_WINDOWS  /W0  /GR /EHsc /w /wd4068 /wd4129 /wd4244 /wd4267 /wd4297 /wd4530 /wd4577 /wd4819 /wd4838' '-DCMAKE_CXX_FLAGS_RELEASE=/MT /O2 /Ob2 /DNDEBUG /bigobj /Zc:inline' '-DCMAKE_CXX_FLAGS_DEBUG=/MTd /Zi /Ob0 /Od /RTC1 /bigobj /Zc:inline' '-Dprotobuf_WITH_ZLIB=ON' '-DZLIB_ROOT:FILEPATH=D:/code/python/Paddle/build/third_party/install/zlib' '-DCMAKE_GENERATOR=Ninja' '-DCMAKE_GENERATOR_PLATFORM=' '-Dprotobuf_MSVC_STATIC_RUNTIME=ON' '-Dprotobuf_BUILD_TESTS=OFF' '-DCMAKE_SKIP_RPATH=ON' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_BUILD_TYPE=Release' '-DCMAKE_INSTALL_PREFIX=D:/code/python/Paddle/build/third_party/install/protobuf' '-DCMAKE_INSTALL_LIBDIR=lib' '-DBUILD_SHARED_LIBS=OFF'

  See also

    D:/code/python/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-configure-*.log


[9/1779] Performing build step for 'extern_mkldnn'
ninja: no work to do.
[15/1779] Performing configure step for 'extern_cryptopp'
ninja: build stopped: subcommand failed.

D:\code\python\Paddle\build>
```

建议更新一下工具链及依赖库，支持 vs 2019+， 例如 https://github.com/PaddlePaddle/Paddle/blob/v2.2.2/python/requirements.txt#L3 这里还限制 windows平台的numpy不能高于1.19.3。

**Comment by yuwoyizhan** [comment]
同求,支持最新版本的python和各种包,比如numpy等.支持VS2022.

**Comment by zhiboniu** [comment]
非常感谢您的宝贵意见，我们会认真考虑该功能。版本的拓展是一个持续的过程，请耐心保持关注。

**Comment by liudonghua123** [comment]
理论上，Python 3.x 是向下兼容的，所以 python 代码部分应该基本不用改动或变动很少，涉及到 C/C++ 相关 extension module 
或 第三方依赖 可能需要更新一下 toolchain 的相关配置，然后重新编译发布。当然这是我个人非深入了解的猜想，可能没有我想的那么简单。
之前我在 python 3.10 上安装 PyQt5/6 PyQt5/6-tools 的时候也遇到过相关问题，当时是 修改 whl 文件名，然后安装就可用的，详细可参考 https://github.com/altendky/pyqt-tools/issues/98#issuecomment-1058964595 .

**Comment by zhiboniu** [comment]
好的，感谢您的经验分享，我们会注意您的这些经验，如果有需要后续会有同学联系您，非常感谢，希望继续支持Paddle.

**Comment by liudonghua123** [comment]
经过自己摸索，我终于在python 3.10上成功运行了 https://mp.weixin.qq.com/s/mlNDdfArr33ayE_nVyyu2A 这里面提到的一个使用 paddle 抠图的程序。

```shell
D:\code\python\paddle_matting_example>python -V
Python 3.10.2

D:\code\python\paddle_matting_example>cat matting.py
import os, paddlehub as hub
print(f"loading module deeplabv3p_xception65_humanseg")
humanseg = hub.Module(name='deeplabv3p_xception65_humanseg')
path = r'D:/Pictures/test/'
files = [path + i for i in os.listdir(path)]
print(f"processing files: {files}")
# https://aistudio.baidu.com/paddle/forum/topic/show/960654
results = humanseg.segmentation(data={'image':files}, visualization=True)
D:\code\python\paddle_matting_example>
D:\code\python\paddle_matting_example>pip show paddlehub
Name: paddlehub
Version: 2.2.0
Summary: A toolkit for managing pretrained models of PaddlePaddle and helping user getting started with transfer learning more efficiently.
Home-page: https://github.com/PaddlePaddle/PaddleHub
Author: PaddlePaddle Author
Author-email: UNKNOWN
License: Apache 2.0
Location: c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages
Requires: colorama, colorlog, easydict, filelock, flask, matplotlib, numpy, opencv-python, packaging, paddle2onnx, paddlenlp, Pillow, pyyaml, pyzmq, rarfile, tqdm, visualdl
Required-by:

D:\code\python\paddle_matting_example>pip show paddlepaddle
Name: paddlepaddle
Version: 2.2.2
Summary: Parallel Distributed Deep Learning
Home-page: UNKNOWN
Author:
Author-email: Paddle-better@baidu.com
License: Apache Software License
Location: c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages
Requires: astor, decorator, numpy, Pillow, protobuf, requests, six
Required-by:

D:\code\python\paddle_matting_example>pip show onnx
Name: onnx
Version: 1.11.0
Summary: Open Neural Network Exchange
Home-page: https://github.com/onnx/onnx
Author: ONNX
Author-email: onnx-technical-discuss@lists.lfai.foundation
License: Apache License v2.0
Location: c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages
Requires: numpy, protobuf, typing-extensions
Required-by: paddle2onnx

D:\code\python\paddle_matting_example>
```

记录一下自己的编译过程

**编译 paddle** ，参考 https://www.paddlepaddle.org.cn/documentation/docs/en/install/compile/windows-compile_en.html
其中需要修改以下几处，编译时间比较长，这块是不停的编译-错误-修改-编译-错误-修改-... 直到最后编译成功。

1. Paddle\build\third_party\protobuf\src\extern_protobuf\src\google\protobuf\compiler\java\java_file.cc 修改

```diff
68c68
<   bool operator ()(const FieldDescriptor* f1, const FieldDescriptor* f2) {
---
>   bool operator ()(const FieldDescriptor* f1, const FieldDescriptor* f2) const {
```

2. Paddle\paddle\fluid\operators\matmul_v2_op.cc 修改

```diff
80c80
<        new_dims.push_back(std::max(dims_x[i], dims_y[i]));
---
>        new_dims.push_back(std::max<int64_t>(dims_x[i], dims_y[i]));
```

3. Paddle\build\third_party\pybind\src\extern_pybind\include\pybind11\numpy.h 和 Paddle\paddle\fluid\pybind\op_function.h 中添加以下代码，可参考 https://github.com/ycm-core/YouCompleteMe/issues/3949, https://groups.google.com/g/snappy-compression/c/xzKxBNeAREc, https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types

```diff
27a28,32
> #include <BaseTsd.h>
> typedef SSIZE_T ssize_t;
> #endif
> 
> #if defined(_MSC_VER)
```

4. Paddle\python\requirements.txt 中修改 numpy 的依赖，修改后如下

```txt
requests>=2.20.0
numpy>=1.13
protobuf>=3.1.0
Pillow
six
decorator
astor
```

这样就可以成功使用vs2019编译出 Paddle\build\python\dist\paddlepaddle-2.2.2-cp310-cp310-win_amd64.whl ，然后使用 pip 安装

```shell
d:\code\python\Paddle\build>pip install -U python\dist\paddlepaddle-2.2.2-cp310-cp310-win_amd64.whl
Processing d:\code\python\paddle\build\python\dist\paddlepaddle-2.2.2-cp310-cp310-win_amd64.whl
Requirement already satisfied: Pillow in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlepaddle==2.2.2) (9.0.1)
Requirement already satisfied: protobuf>=3.1.0 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlepaddle==2.2.2) (3.19.4)
Requirement already satisfied: astor in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlepaddle==2.2.2) (0.8.1)
Requirement already satisfied: requests>=2.20.0 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlepaddle==2.2.2) (2.27.1)
Requirement already satisfied: decorator in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlepaddle==2.2.2) (5.1.1)
Requirement already satisfied: six in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlepaddle==2.2.2) (1.16.0)
Requirement already satisfied: numpy>=1.13 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlepaddle==2.2.2) (1.22.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.20.0->paddlepaddle==2.2.2) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.20.0->paddlepaddle==2.2.2) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.20.0->paddlepaddle==2.2.2) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.20.0->paddlepaddle==2.2.2) (2.0.12)
Installing collected packages: paddlepaddle
Successfully installed paddlepaddle-2.2.2

d:\code\python\Paddle\build>
```

**安装 onnx** 

我是直接安装使用最新的 `onnx==1.11.0`，当然在 `pip install onnx` 的时候会提示 `protobuf` 相关的依赖，这个安装比较麻烦，我是自己摸索的安装配置，我是使用 `vcpkg install protobuf protobuf:x64-windows` ( https://github.com/protocolbuffers/protobuf/blob/master/src/README.md#c-installation---windows )安装，然后把 `<vspkg>\packages\protobuf_x64-windows\tools\protobuf\protoc.exe` 复制到 `<vspkg>\packages\protobuf_x64-windows\bin\protoc.exe`，然后 `set PATH=<vspkg>\packages\protobuf_x64-windows\bin;%PATH%`，之后就可以成功执行 `pip install onnx` ，但是 `python -c "import onnx"` 会有错误提示 `ImportError: DLL load failed while importing onnx_cpp2py_export: The specified module could not be found.`， 使用 `DependenciesGui.exe` 查看 "%LOCALAPPDATA%\Local\Programs\Python\Python310\Lib\site-packages\onnx\onnx_cpp2py_export.cp310-win_amd64.pyd" 会提示缺少 `libprotobuf.dll` ，所以把 `<vspkg>\packages\protobuf_x64-windows\bin\libprotoc.dll` 复制到 "%LOCALAPPDATA%\Local\Programs\Python\Python310\Lib\site-packages\onnx\" 即可，其实我没看 https://github.com/onnx/onnx#windows 的编译过程，目前 `onnx` 仅支持 `protobuf` 的静态链接，不支持动态链接，使用这里的方式就不需要 `libprotobuf.dll`。

**安装 `paddlehub`** 
安装 `paddlehub` 的时候由于 依赖 `paddle2onnx` 依赖 `onnx<=1.9.0`， 所以我就直接使用 `pip install paddlehub --no-deps` 来解决 `paddlehub` 依赖 `onnx` 的问题。

```shell
d:\code\python\Paddle\build>pip install paddlehub
Requirement already satisfied: paddlehub in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (2.2.0)
Requirement already satisfied: flask>=1.1.0 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (2.0.3)
Requirement already satisfied: opencv-python in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (4.5.5.62)
Requirement already satisfied: tqdm in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (4.63.0)
Requirement already satisfied: easydict in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (1.9)
Requirement already satisfied: rarfile in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (4.0)
Requirement already satisfied: colorlog in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (6.6.0)
Requirement already satisfied: paddle2onnx>=0.5.1 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (0.9.1)
Requirement already satisfied: packaging in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (21.3)
Requirement already satisfied: numpy in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (1.22.2)
Requirement already satisfied: paddlenlp>=2.0.0 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (2.2.4)
Requirement already satisfied: visualdl>=2.0.0 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (2.2.3)
Requirement already satisfied: matplotlib in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (3.5.1)
Requirement already satisfied: colorama in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (0.4.4)
Requirement already satisfied: pyyaml in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (6.0)
Requirement already satisfied: filelock in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (3.6.0)
Requirement already satisfied: Pillow in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (9.0.1)
Requirement already satisfied: pyzmq in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddlehub) (22.3.0)
Requirement already satisfied: Jinja2>=3.0 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from flask>=1.1.0->paddlehub) (3.0.3)
Requirement already satisfied: click>=7.1.2 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from flask>=1.1.0->paddlehub) (8.0.4)
Requirement already satisfied: itsdangerous>=2.0 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from flask>=1.1.0->paddlehub) (2.1.0)
Requirement already satisfied: Werkzeug>=2.0 in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from flask>=1.1.0->paddlehub) (2.0.3)
Requirement already satisfied: six in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddle2onnx>=0.5.1->paddlehub) (1.16.0)
Requirement already satisfied: protobuf in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (from paddle2onnx>=0.5.1->paddlehub) (3.19.4)
Collecting onnx<=1.9.0
  Using cached onnx-1.9.0.tar.gz (9.8 MB)
  Installing build dependencies ... canceled
ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\Scripts\pip.exe\__main__.py", line 7, in <module>
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\main.py", line 70, in main
    return command.main(cmd_args)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 100, in main
    with self.main_context():
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\command_context.py", line 19, in main_context
    with self._main_context:
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 576, in __exit__
    raise exc_details[1]
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\utils\temp_dir.py", line 70, in tempdir_registry
    yield _tempdir_registry
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 561, in __exit__
    if cb(*exc_details):
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\utils\temp_dir.py", line 31, in global_tempdir_manager
    with ExitStack() as stack:
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 576, in __exit__
    raise exc_details[1]
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 561, in __exit__
    if cb(*exc_details):
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\utils\temp_dir.py", line 156, in __exit__
    self.cleanup()
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
    rmtree(self._path)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 326, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 406, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 351, in iter
    return fut.result()
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 409, in __call__
    result = fn(*args, **kwargs)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\utils\misc.py", line 124, in rmtree
    shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 739, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 612, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 4 more times]
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    os.unlink(fullname)
KeyboardInterrupt
^C
d:\code\python\Paddle\build>pip install paddlehub --no-deps
Requirement already satisfied: paddlehub in c:\users\liu.d.h\appdata\local\programs\python\python310\lib\site-packages (2.2.0)

d:\code\python\Paddle\build>
```

最后运行的时候还是会报错 `ImportError: cannot import name 'Iterable' from 'collections' `， 还需要修改一下 `%LOCALAPPDATA%\Programs\Python\Python310\lib\site-packages\paddlenlp` 中两处 `from collections import Iterable`，修改为 `from collections.abc import Iterable` (Python 3.10 这块变了)

如果需要我编译好的protobuf_x64-windows、paddlepaddle-2.2.2-cp310-cp310-win_amd64.whl，可以下载以下三个zip文件，重命名为packages.zip.001类似，之后解压（github限制上传文件大小25M，后缀不能是001）即可。

[packages.001.zip](https://github.com/PaddlePaddle/Paddle/files/8203771/packages.001.zip)

[packages.002.zip](https://github.com/PaddlePaddle/Paddle/files/8203772/packages.002.zip)

[packages.003.zip](https://github.com/PaddlePaddle/Paddle/files/8203770/packages.003.zip)

**Comment by liudonghua123** [comment]
我参考 https://github.com/onnx/onnx#windows 编译了静态链接 protobuf 的 onnx，使用也是正常的，注意这里不能使用 master 分支或者更新一点的如 3.19.4 的 protobuf，否则会出现 `ImportError: cannot import name 'builder' from 'google.protobuf.internal'`.

更新：测试过 protobuf 如果静态链接，使用 3.18.2， 3.16.0 都是可以的，如果是 > 3.18.2 例如 3.19.4 安装 onnx 会出现 `libprotobuf.lib(coded_stream.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in cpp2py_export.obj [C:\Users\Liu.D.H\AppData\Local\Temp\pip-install-c9r4wmfa\onnx_9889e9551ce741f2a6f34f8b9e805a88\.setuptools-cmake-build\onnx_cpp2py_export.vcxproj]` 错误。如果是动态链接的，之前即使使用 master 分支的 protobuf 也都是可以的，只是需要配置 libprotoc.dll .

```shell
D:\code\python\paddle_matting_example>python -c "import onnx"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\onnx\__init__.py", line 11, in <module>
    from onnx.external_data_helper import load_external_data_for_model, write_external_data_tensors, convert_model_to_external_data
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\onnx\external_data_helper.py", line 14, in <module>
    from .onnx_pb import TensorProto, ModelProto
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\onnx\onnx_pb.py", line 8, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\onnx\onnx_ml_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python310\lib\site-packages\google\protobuf\internal\__init__.py)

D:\code\python\paddle_matting_example>
```

[onnx-1.11.0-cp310-cp310-win_amd64-wheel-static-and-shared-linked-protobuf.zip](https://github.com/PaddlePaddle/Paddle/files/8205970/onnx-1.11.0-cp310-cp310-win_amd64-wheel-static-and-shared-linked-protobuf.zip)

[paddle2onnx-0.9.1-py3-none-any-modified.zip](https://github.com/PaddlePaddle/Paddle/files/8207095/paddle2onnx-0.9.1-py3-none-any-modified.zip)

为了在 Python 3.10 环境下成功安装 paddlepaddle, paddlehub，需要按依赖顺序安装 onnx（本地编译） -> paddle2onnx（本地修改 paddle2onnx-0.9.1-py3-none-any.whl/paddle2onnx-0.9.1.dist-info/METADATA 中的 onnx 依赖） -> paddlehub -> paddlepaddle（本地编译） 。

**Comment by zhwesky2010** [comment]
@liudonghua123 你好，目前已经支持了VS2019编译，可以用develop分支编译，或者等2.3发版后切换2.3分支编译，预计发版时间是4月中

**Comment by dingjiaweiww** [comment]
@liudonghua123 感谢您的测试，我们已收到，我们正在对集成python3.10 进行技术验证，如果顺利将会在2.3 正式版中发布支持python3.10 的安装包，时间大概在今年5月份，敬请期待！

**Comment by yuwoyizhan** [comment]
@[zhouwei25](https://github.com/zhouwei25)@[dingjiaweiww](https://github.com/dingjiaweiww)支持VS2022最新版本吗?还有一点疑问,我原来以为飞桨是python写的,后来才知道底层等需要高性能的代码都是C++写的,我不知道使用的是什么IDE和编译器,我想问问,编译飞桨的话,支持C++17,C++20这些标准吗?该不会只支持多年前的标准吧?提了几个问题,希望您都回答下,谢谢大佬.

**Comment by zhwesky2010** [comment]
> @[zhouwei25](https://github.com/zhouwei25)@[dingjiaweiww](https://github.com/dingjiaweiww)支持VS2022最新版本吗?还有一点疑问,我原来以为飞桨是python写的,后来才知道底层等需要高性能的代码都是C++写的,我不知道使用的是什么IDE和编译器,我想问问,编译飞桨的话,支持C++17,C++20这些标准吗?该不会只支持多年前的标准吧?提了几个问题,希望您都回答下,谢谢大佬.

参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/windows-compile.html 进行编译
