### ISSUE TITLE
test_model unit test failed

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#40230]
- 版本、环境信息：
    1）PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2）CPU/GPU：如果您使用GPU训练，请提供GPU驱动版本、CUDA和cuDNN版本号
    3）系统环境：请您描述系统类型、版本，例如Mac OS 10.14
    4）Python版本号
    5）显存信息
```
****************************************
Paddle version: 2.2.2
Paddle With CUDA: True

OS: Ubuntu 18.04
Python version: 3.6.9

CUDA version: 11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
cuDNN version: None.None.None
Nvidia driver version: 460.32.03
****************************************
```

- 复现信息：如为报错，请给出复现环境、复现步骤
```
$ cat Dockerfile
FROM nvcr.io/nvidia/cuda:11.5.1-cudnn8-devel-ubuntu18.04

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && apt install python3 python3-pip libasan5 patchelf sudo cmake libssl-dev git gcc-8 g++-8 wget -y

RUN git clone https://github.com/PaddlePaddle/Paddle.git -b v2.2.2 && \
    sed -i 's/BRPC_DEPS brpc/BRPC_DEPS brpc ssl crypto/g' Paddle/paddle/fluid/framework/CMakeLists.txt

RUN pip3 install --upgrade pip && \
    pip3 install -r Paddle/python/requirements.txt

ENV PYVER=3.6

RUN cd Paddle && \
    mkdir -p build && \
    cd build && \
    cmake .. \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_C_COMPILER=`which gcc-8` \
    -DCMAKE_CXX_COMPILER=`which g++-8` \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_FLAGS="-t0" \
    -DCUDA_ARCH_NAME=Manual \
    -DCUDA_ARCH_BIN="70" \
    -DWITH_INCREMENTAL_COVERAGE=OFF \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DWITH_DISTRIBUTE=OFF \
    -DWITH_COVERAGE=OFF \
    -DWITH_TENSORRT=OFF \
    -DWITH_TESTING=ON \
    -DWITH_CONTRIB=OFF \
    -DWITH_ROCM=OFF \
    -DWITH_RCCL=OFF \
    -DWITH_STRIP=OFF \
    -DWITH_MKL=OFF \
    -DWITH_AVX=OFF \
    -DWITH_GPU=ON \
    -DWITH_PYTHON=ON \
    -DPY_VERSION=$PYVER

RUN cd Paddle/build && make -j`nproc`

RUN pip install Paddle/build/python/dist/*.whl
```
新增 `Dockerfile` 後照以下步驟執行
```
$ docker build -t test_model .
$ docker run -it --rm test_model bash -c 'cd Paddle/build && ctest -R test_model$ -V'
```
- 问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
```
206: ======================================================================
206: FAIL: test_export_deploy_model (__main__.TestModelFunction)
206: ----------------------------------------------------------------------
206: Traceback (most recent call last):
206:   File "test_model.py", line 755, in test_export_deploy_model
206:     results, ori_results, rtol=1e-5, atol=1e-7)
206:   File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 1528, in assert_allclose
206:     verbose=verbose, header=header, equal_nan=equal_nan)
206:   File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 840, in assert_array_compare
206:     raise AssertionError(msg)
206: AssertionError:
206: Not equal to tolerance rtol=1e-05, atol=1e-07
206:
206: Mismatched elements: 1 / 10 (10%)
206: Max absolute difference: 1.15484e-06
206: Max relative difference: 1.2361224e-05
206:  x: array([[[-3.567702, -1.809304,  1.734027,  1.016512,  0.398602,
206:          -0.246758,  0.981044,  0.093423, -3.17874 ,  2.768389]]],
206:       dtype=float32)
206:  y: array([[[-3.567703, -1.809303,  1.734027,  1.016513,  0.398603,
206:          -0.246758,  0.981045,  0.093424, -3.17874 ,  2.768389]]],
206:       dtype=float32)
206:
206: ----------------------------------------------------------------------
206: Ran 39 tests in 78.291s
206:
206: FAILED (failures=1)
```

**Comment by zhiboniu** [comment]
看起来Max relative difference: 1.2361224e-05 只比阈值rtol=1e-05 稍微大出了一些，我们会关注该问题。请问您的具体应用是什么，这个精度误差应该实际影响比较小的

**Comment by LielinJiang** [comment]
![image](https://user-images.githubusercontent.com/50691816/161885506-a0a294e4-7d3b-4bc9-a16f-b03b5b34424a.png)
您好，我使用您提供的方式在v100机器上无法复现。

**Comment by zlsh80826** [comment]
@LielinJiang Did you use the exactly same image I provided?

**Comment by zlsh80826** [comment]
Fixed by https://github.com/PaddlePaddle/Paddle/pull/42230, close.
