### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'distributed'

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#40405]
Changes made by commit https://github.com/PaddlePaddle/Paddle/commit/f40ed5f421d64028c9781c2b77aeb2958327b090 causes a runtime error in the module /paddle_paddle/python/paddle/fluid/contrib/slim/tests/save_quant_model.py

### Application run command:
```
python python/paddle/fluid/contrib/slim/tests/save_quant_model.py --quant_model_path=/data/PaddlePaddle/trained_models/ERNIE/Ernie_qat/float --int8_model_save_path=/data/PaddlePaddle/trained_models/ERNIE/ernie_int8 --ops_to_quantize=fc,reshape2,transpose2
```
### ERROR:
```
Traceback (most recent call last):
  File "python/paddle/fluid/contrib/slim/tests/save_quant_model.py", line 19, in <module>
    import paddle
  File "/usr/local/lib/python3.6/dist-packages/paddle/__init__.py", line 54, in <module>
    import paddle.distributed  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/paddle/distributed/__init__.py", line 58, in <module>
    from .sharding import *  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/paddle/distributed/sharding/__init__.py", line 15, in <module>
    from .group_sharded import group_sharded_parallel, save_group_sharded_model  # noqa: F401
  File "/usr/local/lib/python3.6/dist-packages/paddle/distributed/sharding/group_sharded.py", line 23, in <module>
    from paddle.distributed.fleet.meta_optimizers.dygraph_optimizer.sharding_optimizer_stage2 import ShardingOptimizerStage2
  File "/usr/local/lib/python3.6/dist-packages/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/sharding_optimizer_stage2.py", line 28, in <module>
    import paddle.distributed as dist
AttributeError: module 'paddle' has no attribute 'distributed'
```
### PaddlePaddle CMAKE parameters:
```
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6
```

**Comment by lidanqing-vv** [comment]
@piotrekobi Please investigate on this initially

**Comment by lidanqing-vv** [comment]
Hi since this issue is fixed, I will close it

**Comment by pmajchrzak** [comment]
fixed by commit: https://github.com/PaddlePaddle/Paddle/commit/bd2d4fd080fb2e72cbba57bc9862a5c10cb69077
