### ISSUE TITLE
[Linux编译错误] Linux编译Paddle import paddle失败

### ISSUE THREAD

**Issue by MARD1NO** [PaddlePaddle/Paddle#40467]
按照官方文档从源码进行编译：

环境信息：
```
Paddle version: None
Paddle With CUDA: None

OS: Ubuntu 20.04
Python version: 3.7.10

CUDA version: 11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
cuDNN version: None.None.None
Nvidia driver version: 495.44
```

- 安装方式信息：
本地编译：请提供cmake命令，编译命令
```shell
# cmake 命令：
cmake .. \
    -DPYTHON_EXECUTABLE:FILEPATH=/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/bin/python \
    -DPYTHON_INCLUDE_DIR:PATH=/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/include/python3.7m \
    -DPYTHON_LIBRARY:FILEPATH=/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/lib/libpython3.so \
    -DCUDNN_INCLUDE_DIR=/usr/local/cudnn-11.2-linux-x64-v8.1.1.33/cuda/include \
    -DCUDNN_LIBRARY=/usr/local/cudnn-11.2-linux-x64-v8.1.1.33/cuda//lib64/libcudnn.so.8 \
    -DWITH_GPU=ON -DCMAKE_CUDA_ARCHITECTURES=75 -DWITH_TESTING=OFF -DWITH_MKL=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_NCCL=OFF 

```

`import paddle`报错如下：
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 52, in <module>
    from . import io
  File "/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/site-packages/paddle/fluid/io.py", line 31, in <module>
    from paddle.fluid import layers
  File "/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/site-packages/paddle/fluid/layers/__init__.py", line 17, in <module>
    from . import ops
  File "/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/site-packages/paddle/fluid/layers/ops.py", line 81, in <module>
    globals()['_scale'] = generate_layer_fn('scale')
  File "/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/site-packages/paddle/fluid/layers/layer_function_generator.py", line 148, in generate_layer_fn
    op_proto = OpProtoHolder.instance().get_op_proto(op_type)
  File "/home/zzk/miniconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2395, in get_op_proto
    raise ValueError("Operator \"%s\" has not been registered." % type)
ValueError: Operator "scale" has not been registered.
```

**Comment by RainFrost1** [comment]
pip install 安装对应的版本，能使用吗

**Comment by RainFrost1** [comment]
建议使用官方docker环境，如develp版本进行编译, ubuntu 20.04 gcc版本为9+，可能存在问题

**Comment by yang131313** [comment]
你好，现在Paddle已经有编译好的安装包了，请问你在什么任务场景下需要编译Paddle呀？比如是需要新增算子、还是需要修改飞桨源代码，或者有什么其他的用途呢？
