### ISSUE TITLE
Paddle do not fit PEP 513 `manylinux1` standard

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#4050]
Currently, we rename Paddle's wheel package into `manylinux1`. It is not good because our binary does not fit `manylinux1` standard.

In [`manylinux1`](https://www.python.org/dev/peps/pep-0513/) standard, the dependencies are:

```
GLIBC <= 2.5
CXXABI <= 3.4.8
GLIBCXX <= 3.4.9
GCC <= 4.2.0
```
And we should build our wheel package in `CentOS 5`.

But we are using C++ 11, which depends on higher `GLIBCXX`. The current depends is `GLIBCXX==3.4.21`.

The pypa give a docker image to build `manylinux1` standard wheel package in [here](https://github.com/pypa/manylinux/blob/master/docker/Dockerfile-x86_64). We should use that docker image to build our wheel package.

**Comment by typhoonzero** [comment]
Indeed, supporting `manylinux1` is reaaaally needed, but I doubt that we should make a lot of changes to our build system. I'll give it a try.

**Comment by typhoonzero** [comment]
Found some [work](https://github.com/numenta/manylinux) which port `manylinux1` to centos6.

Using centos 5 may introduce too many problems, including CUDA installation or third-party libraries. Will try this on CentOS6.

By the way, [auditwheel](https://pypi.python.org/pypi/auditwheel) is a good tool to test whether the `whl` package is sufficient for the dependencies.

**Comment by typhoonzero** [comment]
Updated using `quay.io/numenta/manylinux1_x86_64_centos6:0.1.2`, this images seems have only `cp27-cp27mu` python included. Adding `cp27-cp27m` support is also needed, build image from `https://github.com/numenta/manylinux` seems not passing.

**Comment by typhoonzero** [comment]
Update using above docker generated `whl`, `auditwheel` says:

```
LD_LIBRARY_PATH=/opt/_internal/cpython-3.5.1/lib:$LD_LIBRARY_PATH auditwheel show python/dist/paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl
Traceback (most recent call last):
  File "/usr/local/bin/auditwheel", line 11, in <module>
    sys.exit(main())
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/auditwheel/main.py", line 49, in main
    rval = args.func(args, p)
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/auditwheel/main_show.py", line 28, in execute
    winfo = analyze_wheel_abi(args.WHEEL_FILE)
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/auditwheel/wheel_abi.py", line 73, in analyze_wheel_abi
    get_wheel_elfdata(wheel_fn)
  File "/opt/_internal/cpython-3.5.1/lib/python3.5/site-packages/auditwheel/wheel_abi.py", line 42, in get_wheel_elfdata
    so_path_split[-1])
RuntimeError: Invalid binary wheel, found shared library "core.so" in purelib folder.
The wheel has to be platlib compliant in order to be repaired by auditwheel.
```

**Comment by typhoonzero** [comment]
After https://github.com/PaddlePaddle/Paddle/pull/5396 merged, build under above image will generate a `whl` package results:

```
auditwheel show paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl

paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl is consistent with
the following platform tag: "linux_x86_64".

The wheel references external versioned symbols in these system-
provided shared libraries: libm.so.6 with versions {'GLIBC_2.2.5'},
libstdc++.so.6 with versions {'GLIBCXX_3.4.11', 'GLIBCXX_3.4.10',
'GLIBCXX_3.4.9', 'CXXABI_1.3.3', 'CXXABI_1.3', 'GLIBCXX_3.4.13',
'GLIBCXX_3.4'}, libdl.so.2 with versions {'GLIBC_2.2.5'},
libgcc_s.so.1 with versions {'GCC_3.3', 'GCC_3.0'}, libc.so.6 with
versions {'GLIBC_2.3.4', 'GLIBC_2.2.5', 'GLIBC_2.3.2', 'GLIBC_2.7',
'GLIBC_2.6'}, libpthread.so.0 with versions {'GLIBC_2.2.5',
'GLIBC_2.3.2'}

This constrains the platform tag to "linux_x86_64". In order to
achieve a more compatible tag, you would to recompile a new wheel from
source on a system with earlier versions of these libraries, such as
CentOS 5.
```

Install this whl on a pure `centos 6` works fine. This tool chain can support most of our cases. Will refine the build images/scripts and put it on CI.

**Comment by typhoonzero** [comment]
Update: I added a new repo https://github.com/PaddlePaddle/buildtools containing scripts to build development docker images of different version.

**Comment by wangkuiyi** [comment]
@typhoonzero How are you going to keep the relationship between versions of Paddle and buildtools?  We are facing such a challenge to keep versions of models/book up to date with Paddle.  The current solution is that we need a git submodule link in the models/book repo pointing to a certain version (recently released) of PaddlePaddle.  We are not yet sure if this solution is perfect.

**Comment by typhoonzero** [comment]
@wangkuiyi No. `buildtools` contains only `Dockerfiles` that can build `manylinux1` sufficient building environment, and it should be static since `manylinux1` defined dependencies are static. `buildtools` repo is not going to update until a new `PEP` definition came out.

**Comment by wangkuiyi** [comment]
Sounds reasonable. According to my experience adding the default Dockerfile, it is static. And it seems that Dockerfile.android is also static. Let's go for your proposal for a while. If it runs all good, we can switch completely to it.

**Comment by Yancey1989** [comment]
I reopen this issue, because we also need to add some project on teamCity:
- [ ] Build different version whl package with manlinux standard

| feature gate | option switch |
| ------------ | -------------- |
| GPU ON + CUDA/CUDNN version | cuda7.5_cudnn5, cuda8.0_cudnn5, cuda8.0_cudnn7 |
| GPU OFF + AVX | AVX ON/OFF (Only use default ON) |
| GPU OFF + cblas | MKL/OpenBlas (Only use one as default) |
| android | build for androind |
- [ ] All PR should pass unit test with manlinux develop Docker image.
- [ ] Production Docker image should be built from manlinux Python package.
- [ ] C-API should be built on manlinux develop Docker image.

**Comment by luotao1** [comment]
How much time of TeamCity if we add all above projects? 
And should we enhance the TeamCity agent at first? Currently, we only have 3 agents. @helinwang 
https://www.jetbrains.com/teamcity/buy/#license-type=new-license

**Comment by Yancey1989** [comment]
Hi @luotao1 
If we don't enought agents on TeamCity, maybe we can make all project except PR Test building on midnight. But I think enhance the TeamCity agent is very important, there are often more than 10 tasks waitting in the Queue.

**Comment by luotao1** [comment]
However, our midnight is the daytime of American colleagues. If we make all project building on midnight, do they wait a lot of time?

**Comment by Yancey1989** [comment]
Yep, I miss this question, how about disperse the builting time, make sure all project to run once a day?

**Comment by luotao1** [comment]
> how about disperse the builting time, make sure all project to run once a day?

I agree with you!

**Comment by Yancey1989** [comment]
Update:
1. Use schedule trigger instead of CSV trigger in all project except PR CI.
1. Build different version whl Python package on TeamCity https://paddleci.ngrok.io/project.html?projectId=Manylinux1&tab=projectOverview.

**Comment by helinwang** [comment]
How many extra projects are we planning to build at midnight Beijing time? If there are within 6 projects, and each one takes 30min, it only takes an hour on three machines, it's probably fine.

**Comment by Yancey1989** [comment]
@helinwang There are 15 configurations for totally except the PR CI, I have already configured them as schedule trigger at different time.

**Comment by Yancey1989** [comment]
Update:
limiting the number of different version of whl package, because the community edition of TeamCity limits the number of congurations.

TeamCity Configuration | WITH_AVX| WITH_GPU|WITH_MKL |  Docker Image | cp27-cp27mu | cp27-cp27m  
--- | --- | --- | --- | --- | --- | ---
cpu_avx_mkl | ON | OFF | ON | paddle:latest | [download](http://guest:@paddleci.ngrok.io/repository/download/Manylinux1_CpuAvxCp27cp27mu/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl) | [download](http://guest:@paddleci.ngrok.io/repository/download/Manylinux1_CpuAvxCp27cp27mu/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27m-linux_x86_64.whl)
cpu_avx_openblas|ON | OFF | ON | paddle:latest-openblas | [download](http://guest:@paddleci.ngrok.io/repository/download/Manylinux1_CpuAvxOpenblas/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl) | [download](http://guest:@paddleci.ngrok.io/repository/download/Manylinux1_CpuAvxOpenblas/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27m-linux_x86_64.whl)
cuda7.5_cudnn5_avx_mkl| ON | ON | ON|None | [download](http://guest:@paddleci.ngrok.io/repository/download/Manylinux1_Cuda75cudnn5cp27cp27mu/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl) | [download](http://guest:@paddleci.ngrok.io/repository/download/Manylinux1_Cuda75cudnn5cp27cp27mu/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27m-linux_x86_64.whl)
cuda8.0_cudnn5_avx_mkl|ON | ON | ON |None | [download](http://guest:@paddleci.ngrok.io/repository/download/Manylinux1_Cuda80cudnn5cp27cp27mu/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl) | [download](http://guest:@paddleci.ngrok.io/repository/download/Manylinux1_Cuda80cudnn5cp27cp27mu/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27m-linux_x86_64.whl)
cuda8.0_cudnn7_avx_mkl|ON | ON | ON |paddle:latest-gpu | [download](http://guest:@paddleci.ngrok.io/repository/download/Manylinux1_Cuda8cudnn7cp27cp27mu/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl) | [download](http://guest:@paddleci.ngrok.io/repository/download/Manylinux1_Cuda8cudnn7cp27cp27mu/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27m-linux_x86_64.whl)

**Comment by typhoonzero** [comment]
Also add corresponding capi links?

**Comment by Yancey1989** [comment]
@typhoonzero will do that :)

**Comment by Yancey1989** [comment]
@typhoonzero Add C-API links.
