### ISSUE TITLE
paddle.take_along_axis 与torch.gather运行结果不一致

### ISSUE THREAD

**Issue by Meiyim** [PaddlePaddle/Paddle#40566]
paddle 采用nightlybuild(2022.3.15)
测试代码:
```python
import paddle as p
L = 200 
idx = p.arange(L).unsqueeze(0).unsqueeze(0).expand([10,L,L])
arr = p.randn([10,L,L])
ret =p.take_along_axis(arr,idx,2)
print(ret)
```
若将`L` 设置为3，运行正常，当`L==200`时，有如下报错(cuda11.0)：
```shell
W0315 15:33:20.281211 15204 gpu_context.cc:244] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.2, Runtime API Version: 11.0
W0315 15:33:20.286876 15204 gpu_context.cc:272] device: 0, cuDNN Version: 8.0.
Traceback (most recent call last):
  File "t.py", line 6, in <module>
    print(ret)
  File "/root/paddlejob/workspace/env_run/ernie-se/python37/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 600, in __str__
    return to_string(self)
  File "/root/paddlejob/workspace/env_run/ernie-se/python37/lib/python3.7/site-packages/paddle/tensor/to_string.py", line 238, in to_string
    np_var = var.numpy()
OSError: (External) CUDA error(700), an illegal memory access was encountered. 
  [Hint: 'cudaErrorIllegalAddress'. The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:258)
```

以下torch代码可以成功运行
```python
import torch as t
L = 200 
idx = t.arange(L).unsqueeze(0).unsqueeze(0).expand([10,L,L])
arr = t.randn([10,L,L])
ret =t.gather(arr,2,idx)
print(ret)
print(ret==arr)
```

**Comment by LiuChiachi** [comment]
感谢关注～
是否可以请 @huangxu96 同学帮忙看一下这个问题，十分感谢～

**Comment by Meiyim** [comment]
any update?
