### ISSUE TITLE
paddle.jit.save的模型中如果包含带有break语句的for循环会报错

### ISSUE THREAD

**Issue by daidaiershidi** [PaddlePaddle/Paddle#40645]
- 标题：paddle.jit.save的模型中如果包含带有break语句的for循环会报错

- 版本、环境信息：
    1）PaddlePaddle版本：paddlepaddle-gpu 2.2.2
    2）CPU/GPU（GPU驱动、CUDA、cuDNN版本）：NVIDIA-SMI 440.64.00 Driver Version: 440.64.00 CUDA Version: 10.2
    3）操作系统版本：Linux version 3.10.0-1062.18.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) )
    4）Python版本：3.7.11
    5）显存信息：Tesla V100-SXM2 16G

- 训练信息

- 复现信息：
测试
```
# example 1: save layer
import numpy as np
import paddle
import paddle.nn as nn
import paddle.optimizer as opt

BATCH_SIZE = 16
BATCH_NUM = 4
EPOCH_NUM = 4

IMAGE_SIZE = 784
CLASS_NUM = 10

# define a random dataset
class RandomDataset(paddle.io.Dataset):
    def __init__(self, num_samples):
        self.num_samples = num_samples

    def __getitem__(self, idx):
        image = np.random.random([IMAGE_SIZE]).astype('float32')
        label = np.random.randint(0, CLASS_NUM - 1, (1, )).astype('int64')
        return image, label

    def __len__(self):
        return self.num_samples

class LinearNet(nn.Layer):
    def __init__(self):
        super(LinearNet, self).__init__()
        self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)

    @paddle.jit.to_static
    def forward(self, x):

        #########################        
        # 加入带break的for循环会报错
        for i in range(3):
            if i == 2:
                break
        #########################      

        return self._linear(x)

def train(layer, loader, loss_fn, opt):
    for epoch_id in range(EPOCH_NUM):
        for batch_id, (image, label) in enumerate(loader()):
            out = layer(image)
            loss = loss_fn(out, label)
            loss.backward()
            opt.step()
            opt.clear_grad()
            print("Epoch {} batch {}: loss = {}".format(
                epoch_id, batch_id, np.mean(loss.numpy())))

# 1. train & save model.

# create network
layer = LinearNet()
loss_fn = nn.CrossEntropyLoss()
adam = opt.Adam(learning_rate=0.001, parameters=layer.parameters())

# create data loader
dataset = RandomDataset(BATCH_NUM * BATCH_SIZE)
loader = paddle.io.DataLoader(dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    drop_last=True,
    num_workers=2)

# train
train(layer, loader, loss_fn, adam)

# save
path = "example_model/linear"
paddle.jit.save(layer, path)

# example 2: save function
import paddle
from paddle.static import InputSpec


def save_function():
    @paddle.jit.to_static
    def fun(inputs):
        return paddle.tanh(inputs)

    path = 'test_jit_save_load_function_1/func'
    inps = paddle.rand([3, 6])
    origin = fun(inps)

    paddle.jit.save(fun, path)
    load_func = paddle.jit.load(path)

    load_result = load_func(inps)
    print((load_result - origin).abs().max() < 1e-10)

save_function()

```
结果：
```
Traceback (most recent call last):
  File "/workspace/liukaiyuan/mytools/1.py", line 66, in <module>
    train(layer, loader, loss_fn, adam)
  File "/workspace/liukaiyuan/mytools/1.py", line 42, in train
    out = layer(image)
  File "/root/miniconda3/envs/python3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/python3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 376, in __call__
    error_data.raise_new_exception()
  File "/root/miniconda3/envs/python3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
TypeError: In transformed code:


    File "/tmp/tmp1prtcj8s.py", line 16, in forward
        while_body_0, [i])
    File "/root/miniconda3/envs/python3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
        loop_vars = _run_py_while(cond, body, loop_vars)
    File "/root/miniconda3/envs/python3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 58, in _run_py_while
        while cond(*loop_vars):

    TypeError: while_condition_0() argument after * must be an iterable, not int
```

- 问题描述：好像是因为for在动转静变成了while，在while的condition里会进行lambad依次比较。虽然__for_loop_var_index_0初始化是0，但是和__break_0进经过paddle.jit.dy2static.convert_logical_and逻辑与之后，__for_loop_var_index_0就从int变成了和__break_0一样的paddle.fluid.layers.fill_constant

<img width="1282" alt="图片" src="https://user-images.githubusercontent.com/48178838/158716934-3d6438b2-fb85-4090-8234-1336e175712e.png">
<img width="547" alt="图片" src="https://user-images.githubusercontent.com/48178838/158716945-4c8924ab-5bfe-4947-8ed3-55abec9ee301.png">

**Comment by Aurelius84** [comment]
非常感谢您的反馈，我们已经复现此问题，修复PR见：https://github.com/PaddlePaddle/Paddle/pull/40683
