### ISSUE TITLE
为OP添加bool类型属性的问题

### ISSUE THREAD

**Issue by guoshengCS** [PaddlePaddle/Paddle#4068]
在写reduce_op的过程中，需要为其添加`keep_dim`这样一个`bool`类型的属性，代码如下：

```
    AddAttr<bool>("keep_dim",
                  "(bool, default fasle) "
                  "If true, retain the reduced dimension with length 1.")
```

在编译过程中，MAC上CXX编译器无法编译通过，报如下的编译错误（内容较多，还请见谅）：

```
In file included from /usr/local/include/boost/variant.hpp:22:
/usr/local/include/boost/variant/get.hpp:220:5: error: static_assert failed "boost::variant does not contain specified type U, call to boost::get<U>(boost::variant<T...>&) will always throw boost::bad_get exception"
    BOOST_STATIC_ASSERT_MSG(
    ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/static_assert.hpp:31:45: note: expanded from macro 'BOOST_STATIC_ASSERT_MSG'
#     define BOOST_STATIC_ASSERT_MSG( ... ) static_assert(__VA_ARGS__)
                                            ^             ~~~~~~~~~~~
/usr/local/include/boost/variant/get.hpp:292:12: note: in instantiation of function template specialization 'boost::strict_get<bool, boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > >' requested here
    return strict_get<U>(operand);
           ^
/Users/baidu/Documents/codeRep/paddle-master/Paddle/paddle/framework/attribute.h:161:28: note: in instantiation of function template specialization 'boost::get<bool, boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > >' requested here
    T& attr_value = boost::get<T>(attr);
                           ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__functional_base:416:12: note: in instantiation of member function 'paddle::framework::TypedAttrChecker<bool>::operator()' requested here
    return _VSTD::forward<_Fp>(__f)(_VSTD::forward<_Args>(__args)...);
           ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__config:401:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_NAMESPACE
              ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/__functional_base:468:9: note: in instantiation of function template specialization 'std::__1::__invoke<paddle::framework::TypedAttrChecker<bool> &, std::__1::unordered_map<std::__1::basic_string<char>, boost::variant<boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > >, std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, boost::variant<boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > > > > > &>' requested here
        __invoke(_VSTD::forward<_Args>(__args)...);
        ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:1437:22: note: in instantiation of function template specialization 'std::__1::__invoke_void_return_wrapper<void>::__call<paddle::framework::TypedAttrChecker<bool> &, std::__1::unordered_map<std::__1::basic_string<char>, boost::variant<boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > >, std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, boost::variant<boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > > > > > &>' requested here
    return _Invoker::__call(__f_.first(), _VSTD::forward<_ArgTypes>(__arg)...);
                     ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:1366:14: note: in instantiation of member function 'std::__1::__function::__func<paddle::framework::TypedAttrChecker<bool>, std::__1::allocator<paddle::framework::TypedAttrChecker<bool> >, void (std::__1::unordered_map<std::__1::basic_string<char>, boost::variant<boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > >, std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, boost::variant<boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > > > > > &)>::operator()' requested here
    explicit __func(_Fp&& __f)
             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:1663:26: note: in instantiation of member function 'std::__1::__function::__func<paddle::framework::TypedAttrChecker<bool>, std::__1::allocator<paddle::framework::TypedAttrChecker<bool> >, void (std::__1::unordered_map<std::__1::basic_string<char>, boost::variant<boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > >, std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, boost::variant<boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > > > > > &)>::__func' requested here
            ::new (__f_) _FF(_VSTD::move(__f));
                         ^
/Users/baidu/Documents/codeRep/paddle-master/Paddle/paddle/framework/attribute.h:180:30: note: in instantiation of function template specialization 'std::__1::function<void (std::__1::unordered_map<std::__1::basic_string<char>, boost::variant<boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > >, std::__1::hash<std::__1::basic_string<char> >, std::__1::equal_to<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, boost::variant<boost::blank, int, float, std::__1::basic_string<char>, std::__1::vector<int, std::__1::allocator<int> >, std::__1::vector<float, std::__1::allocator<float> >, std::__1::vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >, std::__1::vector<std::__1::pair<int, int>, std::__1::allocator<std::__1::pair<int, int> > > > > > > &)>::function<paddle::framework::TypedAttrChecker<bool> >' requested here
    attr_checkers_.push_back(TypedAttrChecker<T>(attr_name));
                             ^
/Users/baidu/Documents/codeRep/paddle-master/Paddle/paddle/framework/operator.h:215:25: note: in instantiation of function template specialization 'paddle::framework::OpAttrChecker::AddAttrChecker<bool>' requested here
    return op_checker_->AddAttrChecker<T>(name);
                        ^
/Users/baidu/Documents/codeRep/paddle-master/Paddle/paddle/operators/reduce_op.cc:89:5: note: in instantiation of function template specialization 'paddle::framework::OpProtoAndCheckerMaker::AddAttr<bool>' requested here
    AddAttr<bool>("keep_dim",
    ^
1 error generated.
make[2]: *** [paddle/operators/CMakeFiles/reduce_op.dir/reduce_op.cc.o] Error 1
```

移植到Linux使用gcc48编译可以编译成功，但在运行Python单测时报undefinedsymbol，Python单测代码如下：

```
class TestKeepDimReduce(OpTest):
    def setUp(self):
        self.op_type = "reduce_sum"
        self.inputs = {'X': np.random.random((5, 6, 10)).astype("float32")}
        self.attrs = {'dim': 2}
        self.outputs = {'Out': self.inputs['X'].sum(axis=self.attrs['dim'], keepdims=True)}
```

报错如下，貌似也是因为`AttrType<bool>`的原因：

```
130: Test command: /bin/env "PYTHONPATH=/home/work/guosheng/paddle-dev/Paddle/build/python/build/lib-python" "python2" "test_reduce_op.py"
130: Test timeout computed to be: 9.99988e+06
130: Traceback (most recent call last):
130:   File "test_reduce_op.py", line 3, in <module>
130:     from op_test import OpTest
130:   File "/home/work/guosheng/paddle-dev/Paddle/python/paddle/v2/framework/tests/op_test.py", line 4, in <module>
130:     import paddle.v2.framework.core as core
130: ImportError: /home/work/guosheng/paddle-dev/Paddle/build/python/build/lib-python/paddle/v2/framework/core.so: undefined symbol: _ZN6paddle9framework10AttrTypeIDIbEENS0_8AttrTypeEv
1/1 Test #130: test_reduce_op ...................***Failed    0.85 sec
```

请问有没有相应的解决办法~

**Comment by lcy-seso** [comment]
这个 undefined symbol 类的错误我也遇到过，但是情形不太一样。之前是因为模板没有特化引起的。

**Comment by typhoonzero** [comment]
之前遇到的一个`undefined symbol`问题原因是写新的op之前make过一次，然后在`make copy_paddle_pybind`，只编译所有的op，但是ctest找的目录是在`build/python/build/lib-python`，所以得手动执行
```
cp ../python/paddle/v2/framework/core.so /paddle/build/python/build/lib-python/paddle/v2/framework/
```

**Comment by Yancey1989** [comment]
是否在 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/attribute.cc 和  https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/attribute.h#L30 添加对应的Attribute类型了呢？不加的化貌似`boost::variant`会报找不到对应类型。

**Comment by guoshengCS** [comment]
多谢各位，应该是没有添加对应的Attribute类型，`undefined symbol`问题可能确实是之前make过的原因。
