### ISSUE TITLE
paddle.Model如何包装继承自nn.Layer的自定义模型

### ISSUE THREAD

**Issue by SuperMaskv** [PaddlePaddle/Paddle#40764]
请问哪里可以找到继承自nn.Layer的自定义模型使用paddle.Model.fit进行训练的示例。
我尝试着写了一个ernie-tiny-crf的模型，但是在使用Model.fit进行训练的时候出现了Broadcast dimension mismatch的错误, 我尝试过将batch_size调整到1，但是仍然报错。
```python
def forward(self,
            input_ids,
            token_type_ids=None,
            position_ids=None,
            attention_mask=None,
            lengths=None,
            labels=None):
    logits = self.ernie(input_ids, token_type_ids=token_type_ids, attention_mask=attention_mask,
                        position_ids=position_ids)

    if labels is not None:
        return self.crf_loss(logits, lengths, labels)
    else:
        return self.viterbi_decoder(logits, lengths)
```
```bash
Traceback (most recent call last):
  File "D:/code-stuff/amberdata/abnlp/src/train/ernie_tiny_crf_training.py", line 41, in <module>
    model.fit(
  File "D:\Anaconda3\envs\abdatatip\lib\site-packages\paddle\hapi\model.py", line 1732, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "D:\Anaconda3\envs\abdatatip\lib\site-packages\paddle\hapi\model.py", line 2062, in _run_one_epoch
    outs = getattr(self, mode + '_batch')(*_inputs)
  File "D:\Anaconda3\envs\abdatatip\lib\site-packages\paddle\hapi\model.py", line 1061, in train_batch
    loss = self._adapter.train_batch(inputs, labels, update)
  File "D:\Anaconda3\envs\abdatatip\lib\site-packages\paddle\hapi\model.py", line 713, in train_batch
    outputs = self.model.network.forward(
  File "D:\code-stuff\amberdata\abnlp\src\model\ernie_tiny_with_crf_model.py", line 99, in forward
    logits = self.ernie(input_ids, token_type_ids=token_type_ids, attention_mask=attention_mask,
  File "D:\Anaconda3\envs\abdatatip\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\envs\abdatatip\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 588, in forward
    sequence_output, _ = self.ernie(
  File "D:\Anaconda3\envs\abdatatip\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\envs\abdatatip\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 373, in forward
    embedding_output = self.embeddings(
  File "D:\Anaconda3\envs\abdatatip\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\envs\abdatatip\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 70, in forward
    embeddings = input_embedings + position_embeddings + token_type_embeddings
  File "D:\Anaconda3\envs\abdatatip\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 264, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [32, 130, 1024] and the shape of Y = [32, 1024]. Received [130] in X is not equal to [32] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error]
```

**Comment by zhaocaibei123** [comment]
embeddings = input_embedings + position_embeddings + token_type_embeddings
请检查下各个embedding的维度，报错显式这几个embedding的shape不一样

**Comment by SuperMaskv** [comment]
@zhaocaibei123 感谢帮助，确实是position_ids少了个维度。再请教一个问题，Model.fit是通过什么方式将dataloader中的数据和模型的入参对应起来的呢

**Comment by SuperMaskv** [comment]
> @zhaocaibei123 感谢帮助，确实是position_ids少了个维度。再请教一个问题，Model.fit是通过什么方式将dataloader中的数据和模型的入参对应起来的呢

补充一下，比如说在我的模型的入参中有一个名为lengths的参数，那么应该如何通过Model.fit传递这个参数呢

**Comment by zhaocaibei123** [comment]
不太清楚你的Model.fix是什么，是Paddle套件吗，dataloader可以通过feed_list指定输入数据

**Comment by SuperMaskv** [comment]
paddle.Model.fit
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Model_cn.html#fit-train-data-none-eval-data-none-batch-size-1-epochs-1-eval-freq-1-log-freq-10-save-dir-none-save-freq-1-verbose-2-drop-last-false-shuffle-true-num-workers-0-callbacks-none

**Comment by zhaocaibei123** [comment]
确保dataloader出来的数据和Model input参数的定义一一对应就可以了，dataloader文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html#dataloader

**Comment by SuperMaskv** [comment]
请问有相关的示例吗，我尝试了很多次，实在是试不出来

**Comment by SuperMaskv** [comment]
我看了一下源码，在paddle.Model.fit中，给loss和metric传参的方法都是Model output + labels，但是我现在用的`LinearChainCrfLoss.forward(self, inputs, lengths, labels, old_version_labels=None):` 和 `ChunkEvaluator.compute(self, lengths, predictions, labels, dummy=None):` 他们在参数的顺序上是冲突的，请问有什么解决方法吗

**Comment by zhaocaibei123** [comment]
可dataloader文档里的示例，如果还不够明确，可以参考单测里dataloader的用法，例如：python/paddle/fluid/tests/unittests/test_translated_layer.py 
python里参数顺序没关系，使用关键字参数来确定传入的参数值，例如 LinearChainCrfLoss.forward(inputs=XXX, labels=XXX...)

**Comment by SuperMaskv** [comment]
是paddle.Model.fit的内部按照顺序传参，我干预不了

**Comment by SuperMaskv** [comment]
我继承paddlenlp.metrics.ChunkEvaluator，魔改了一下解决了
