### ISSUE TITLE
paddle训练报错

### ISSUE THREAD

**Issue by Winniesea** [PaddlePaddle/Paddle#41150]
希望大佬们给予解答！谢谢！
- 版本、环境信息：

     ****************************************
Paddle version: 2.2.2
Paddle With CUDA: True

OS: Windows 10
Python version: 3.8.12

CUDA version: 10.2.89
cuDNN version: 7.6.5
Nvidia driver version: 511.79
**************************************** 

- 训练信息
    1）单机
    2）显存信息
         
<img width="490" alt="1" src="https://user-images.githubusercontent.com/94028979/160794120-06f3748a-b421-4aaf-ae28-ab7ff938fc29.png">

    3）Operator信息
- 复现信息：（以下为输入训练指令之后出现的报错代码）
(paddle21) C:\Users\Winnie\Desktop\PaddleDetection-develop>python tools/train.py -c configs/dota/s2anet_1x_dota.yml  -o use_gpu=true --use_vdl=True
C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
W0330 17:03:17.908252  4860 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W0330 17:03:17.923878  4860 device_context.cc:465] device: 0, cuDNN Version: 7.6.
C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\bbox_utils.py:441: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float(pt4[1] - pt1[1]), np.float(pt4[0] - pt1[0]))
C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\bbox_utils.py:448: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x_ctr = np.float(pt1[0] + pt3[0]) / 2
C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\bbox_utils.py:449: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_ctr = np.float(pt1[1] + pt3[1]) / 2
C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\bbox_utils.py:438: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.float(pt2[1] - pt1[1]), np.float(pt2[0] - pt1[0]))
[03/30 17:03:19] ppdet.utils.checkpoint INFO: Finish loading model weights: ResNet50_cos_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 139, in <module>
    main()
  File "tools/train.py", line 135, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 110, in run
    trainer.train(FLAGS.eval)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\engine\trainer.py", line 356, in train
    outputs = model(data)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\meta_arch.py", line 26, in forward
    out = self.get_loss()
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\s2anet.py", line 97, in get_loss
    loss = self._forward()
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\s2anet.py", line 70, in _forward
    body_feats = self.backbone(self.inputs)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\backbones\resnet.py", line 586, in forward
    x = stage(x)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\backbones\resnet.py", line 427, in forward
    block_out = block(block_out)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\backbones\resnet.py", line 376, in forward
    out = paddle.add(x=out, y=short)
  File "C:\Users\Winnie\anaconda3\envs\paddle21\lib\site-packages\paddle\tensor\math.py", line 240, in add
    return _C_ops.elementwise_add(x, y)
SystemError: (Fatal) Operator elementwise_add raises an struct paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 16.000244MB memory on GPU 0, 1.999756GB memory has been allocated and available memory is only 0.000000B.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:79)
. (at ..\paddle\fluid\imperative\tracer.cc:221)

**Comment by GuoxiaWang** [comment]
@Winniesea 显存不够导致的

**Comment by Winniesea** [comment]
> @Winniesea 显存不够导致的

感谢解答！请问您说的“显存不够导致的“与我的nvidia-smi显示No running processes found是没有必然关系的是嘛？那就是说，我的电脑配置无法跑这个算法，需要换成服务器？

**Comment by GuoxiaWang** [comment]
@Winniesea 

> Out of memory error on GPU 0. Cannot allocate 16.000244MB memory on GPU 0, 1.999756GB memory has been allocated and available memory is only 0.000000B.

显存已经分配完了， 你这个显存只有2G，这个算法可能需要更多的显存。

**Comment by Winniesea** [comment]
好的。感谢您！我明天换成服务器试试 ：D

**Comment by Winniesea** [comment]
> @Winniesea
> 
> > Out of memory error on GPU 0. Cannot allocate 16.000244MB memory on GPU 0, 1.999756GB memory has been allocated and available memory is only 0.000000B.
> 
> 显存已经分配完了， 你这个显存只有2G，这个算法可能需要更多的显存。

好的。感谢您！我明天换成服务器试试 ：D
