### ISSUE TITLE
test_squared_l2_distance_op failed in CI

### ISSUE THREAD

**Issue by Xreki** [PaddlePaddle/Paddle#4118]
```
[10:11:22]	151/161 Test #154: test_squared_l2_distance_op .........***Failed 1.69 sec
[10:11:22]	....F.
[10:11:22]	======================================================================
[10:11:22]	FAIL: test_check_grad (__main__.TestSquaredL2DistanceOp_f2)
[10:11:22]	----------------------------------------------------------------------
[10:11:22]	Traceback (most recent call last):
[10:11:22]	File "test_squared_l2_distance_op.py", line 67, in test_check_grad
[10:11:22]	self.check_grad(['X', 'Y'], 'Out')
[10:11:22]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 268, in check_grad
[10:11:22]	"Gradient Check On %s" % str(cpu_place))
[10:11:22]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 227, in __assert_is_close
[10:11:22]	self.assertLessEqual(max_diff, max_relative_error, err_msg())
[10:11:22]	AssertionError: Gradient Check On CPUPlace Variable X@GRAD max gradient diff 0.007579 over limit 0.005000, the first error element is 8
[10:11:22]	
[10:11:22]	----------------------------------------------------------------------
[10:11:22]	Ran 6 tests in 0.403s
[10:11:22]	
[10:11:22]	FAILED (failures=1)
```

**Comment by lcy-seso** [comment]
I think our current gradient check may meet with computation accuracy problem.

I run the gradient check for an op I implemented for multiple times, it may occasionally fail https://github.com/PaddlePaddle/Paddle/issues/4134. To make sure the gradient check always succeed,  you have to carefully choose a relatively large `max_relative_error`.

**Comment by lcy-seso** [comment]
I think this issue is the same problem. The error information are as follows:

```text
[19:58:13]	FAIL: test_check_grad_ingore_x (__main__.TestCosSimOp)
[19:58:13]	----------------------------------------------------------------------
[19:58:13]	Traceback (most recent call last):
[19:58:13]	File "test_cos_sim_op.py", line 31, in test_check_grad_ingore_x
[19:58:13]	['Y'], 'Out', max_relative_error=0.05, no_grad_set=set('X'))
[19:58:13]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 262, in check_grad
[19:58:13]	"Gradient Check On %s" % str(cpu_place))
[19:58:13]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 224, in __assert_is_close
[19:58:13]	self.assertLessEqual(max_diff, max_relative_error, err_msg())
[19:58:13]	AssertionError: Gradient Check On CPUPlace Variable Y@GRAD max gradient diff 0.050586 over limit 0.050000, the first error element is 47
```
