### ISSUE TITLE
pip install paddle

### ISSUE THREAD

**Issue by Han-YLun** [PaddlePaddle/Paddle#41213]
```
pip install paddle
Collecting paddle
  Using cached paddle-1.0.2.tar.gz (579 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/arvinyl/.local/share/virtualenvs/dataengine-etl-pXi36jQF/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_698f0bf13cda44d290ed4ef5e90ee145/setup.py'"'"'; __file__='"'"'/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_698f0bf13cda44d290ed4ef5e90ee145/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-pip-egg-info-a_n7297v
       cwd: /private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_698f0bf13cda44d290ed4ef5e90ee145/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_698f0bf13cda44d290ed4ef5e90ee145/setup.py", line 3, in <module>
      import paddle
    File "/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_698f0bf13cda44d290ed4ef5e90ee145/paddle/__init__.py", line 5, in <module>
      import common, dual, tight, data, prox
  ModuleNotFoundError: No module named 'common'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/55/cf/e4b6b9a54d2f072e4491e34317bf5f5fea260da8a3072e641832dc9ce770/paddle-1.0.2.tar.gz#sha256=aeb13606880a932f97eb1a810bc8820c7e80f943abcdb56f272b1375964ef117 (from https://pypi.org/simple/paddle/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached paddle-1.0.1.tar.gz (539 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/arvinyl/.local/share/virtualenvs/dataengine-etl-pXi36jQF/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_4a2849ae978642b6a069797f70ae066e/setup.py'"'"'; __file__='"'"'/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_4a2849ae978642b6a069797f70ae066e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-pip-egg-info-fxltzhlc
       cwd: /private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_4a2849ae978642b6a069797f70ae066e/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_4a2849ae978642b6a069797f70ae066e/setup.py", line 3, in <module>
      import paddle
    File "/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_4a2849ae978642b6a069797f70ae066e/paddle/__init__.py", line 5, in <module>
      import common, dual, tight
  ModuleNotFoundError: No module named 'common'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/93/cc/5d3b4eb9c5ea536ddaf10e4d7ec2019e1bde9d0b4207f314f7cf8a1af0d7/paddle-1.0.1.tar.gz#sha256=e4468cfb5be7a2f3373bd93c31541da758027bbd6ffe75f83008a88e70e2eae7 (from https://pypi.org/simple/paddle/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached paddle-1.0.0.tar.gz (539 kB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/arvinyl/.local/share/virtualenvs/dataengine-etl-pXi36jQF/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_d7764eff66c042709ea3e9ff504fb87d/setup.py'"'"'; __file__='"'"'/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_d7764eff66c042709ea3e9ff504fb87d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-pip-egg-info-y_btigd0
       cwd: /private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_d7764eff66c042709ea3e9ff504fb87d/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_d7764eff66c042709ea3e9ff504fb87d/setup.py", line 3, in <module>
      import paddle
    File "/private/var/folders/7r/ft0xjpg95fv_x7fp16n7d7mw0000gn/T/pip-install-pn9lbdnv/paddle_d7764eff66c042709ea3e9ff504fb87d/paddle/__init__.py", line 5, in <module>
      import common, dual, tight
  ModuleNotFoundError: No module named 'common'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a9/c2/10db468c6a588b208ad22506c0f390059c5fa7a399e2085baefba3dcc24e/paddle-1.0.0.tar.gz#sha256=64abc6b5574da69ea02ca058fbd0677fc0a19473b45c34cf0c4d23aeaf6738e1 (from https://pypi.org/simple/paddle/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement paddle (from versions: 1.0.0, 1.0.1, 1.0.2)
ERROR: No matching distribution found for paddle
```

**Comment by Han-YLun** [comment]
i use mac,python version 3.8.9,pip version 21.3.1

**Comment by liutiexing** [comment]
按照您的需求，请走这个安装方式
python -m pip install paddlepaddle==2.2.2 -i https://mirror.baidu.com/pypi/simple

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/74819124/161051362-3ff773e6-d0ff-400d-95c9-b4e295617ff0.png">

**Comment by liutiexing** [comment]
mac上不支持gpu训练

**Comment by Han-YLun** [comment]
[2022/04/02 16:24:36] root INFO: dt_boxes num : 41, elapse : 1.985137939453125
W0402 16:24:36.930294   261 analysis_predictor.cc:1353] Deprecated. Please use CreatePredictor instead.
[2022/04/02 16:24:37] root INFO: cls num  : 41, elapse : 0.5929715633392334
100%|██████████| 99.3k/99.3k [00:00<00:00, 3.25MiB/s][2022-04-02 16:24:38 +0800] [37] [INFO] Booting worker with pid: 37
W0402 16:24:40.035571    37 analysis_predictor.cc:1353] Deprecated. Please use CreatePredictor instead.


这样就不往下面走了，本地可以，云服务docker不行，这是为啥

**Comment by Han-YLun** [comment]
报错之后停止运行，后面的内容也不会执行

**Comment by Han-YLun** [comment]
> [2022/04/02 16:24:36] root INFO: dt_boxes num : 41, elapse : 1.985137939453125 W0402 16:24:36.930294 261 analysis_predictor.cc:1353] Deprecated. Please use CreatePredictor instead. [2022/04/02 16:24:37] root INFO: cls num : 41, elapse : 0.5929715633392334 100%|██████████| 99.3k/99.3k [00:00<00:00, 3.25MiB/s][2022-04-02 16:24:38 +0800] [37] [INFO] Booting worker with pid: 37 W0402 16:24:40.035571 37 analysis_predictor.cc:1353] Deprecated. Please use CreatePredictor instead.
> 
> 这样就不往下面走了，本地可以，云服务docker不行，这是为啥

**Comment by 0xkevin** [comment]
请问怎么安装uapi？
