### ISSUE TITLE
Python tests has stopped working with Python3.6

### ISSUE THREAD

**Issue by wozna** [PaddlePaddle/Paddle#41283]
From commit https://github.com/PaddlePaddle/Paddle/commit/c15e3823346e323d2d84f1fc7c174ae09790ccec all python tests don't work if Python is lower than 3.7. I checked python 3.7 and 3.9 and it works fine. 
Here is the error that appears for the test `test_conv2d_op` and the same error appears in all other tests. 
```
    Start 518: test_conv2d_op

518: Test command: /usr/local/bin/cmake "-E" "env" "PYTHONPATH=/home/wozna/Paddle/Paddle/build/python" "/usr/bin/python3.6" "/home/wozna/Paddle/Paddle/tools/test_runner.py" "test_conv2d_op"
518: Test timeout computed to be: 120
518: /usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
518:   import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
518: Traceback (most recent call last):
518:   File "/home/wozna/Paddle/Paddle/tools/test_runner.py", line 20, in <module>
518:     import paddle
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/__init__.py", line 25, in <module>
518:     from .framework import monkey_patch_variable
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/framework/__init__.py", line 17, in <module>
518:     from . import random  # noqa: F401
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/framework/random.py", line 16, in <module>
518:     import paddle.fluid as fluid
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/fluid/__init__.py", line 52, in <module>
518:     from . import io
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/fluid/io.py", line 31, in <module>
518:     from paddle.fluid import layers
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/fluid/layers/__init__.py", line 37, in <module>
518:     from .learning_rate_scheduler import *
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/fluid/layers/learning_rate_scheduler.py", line 35, in <module>
518:     from ..dygraph import learning_rate_scheduler as imperate_lr
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/fluid/dygraph/__init__.py", line 20, in <module>
518:     from . import layers
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/fluid/dygraph/layers.py", line 28, in <module>
518:     import paddle.profiler as profiler
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/profiler/__init__.py", line 15, in <module>
518:     from .profiler import ProfilerState, ProfilerTarget
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/profiler/profiler.py", line 26, in <module>
518:     from .utils import RecordEvent, wrap_optimizers
518:   File "/home/wozna/Paddle/Paddle/build/python/paddle/profiler/utils.py", line 21, in <module>
518:     import paddle.fluid.core as core
518: AttributeError: module 'paddle' has no attribute 'fluid'
1/2 Test #518: test_conv2d_op ...................***Failed    0.70 sec
```
python - 3.6.9 
cmake -  3.16.5
gcc -  7.5.0
build flags 
```
cmake .. -DPY_VERSION=3.6 -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DON_INFER=ON -DWITH_PYTHON=ON -DWITH_MKL=ON -DWITH_AVX=ON -DWITH_TESTING=ON -DWITH_INFERENCE_API_TEST=ON
```

**Comment by wozna** [comment]
I found that this commit fixed this problem https://github.com/PaddlePaddle/Paddle/commit/6ed6f9fed74d0815b36b82336440d8906c4830e7
