### ISSUE TITLE
训练程序异常终止，dataloader抛出异常。

### ISSUE THREAD

**Issue by muzixihust** [PaddlePaddle/Paddle#41508]
### 请提出你的问题 Please ask your question

http://paddlecloud.baidu-int.com/paddle/job/detail?jobId=job-0bb624d050611748
程序在本地单机服务器训练时正常，但提交至PaddleCloud进行训练时出错。DataLoader异常终止。报错如下：

ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 482, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/local/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 498, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 3348

**Comment by heavengate** [comment]
看着是有进程退出了，可能是Cloud上资源不够，如num_workers是不是设置得过大，还有/dev/shm下空间不大导致共享内存不够之类的，可以调小num_workers或者把use_shared_memory设置成False试下

**Comment by muzixihust** [comment]
请教下paddle的dataloader的num_workers生成的子进程怎么自动清理呢？发现在训练过程中每过一遍dataloader子进程就会增加一遍，逐渐累积，越来越多，最终导致程序崩溃
