### ISSUE TITLE
用静态图定义函数运算报错：(InvalidArgument) The tensor Input (Input) of Slice op is not initialized.

### ISSUE THREAD

**Issue by Patrick-Star125** [PaddlePaddle/Paddle#41609]
### 请提出你的问题 Please ask your question

我想用paddle静态图实现自定义函数运算，用fluid.layers实现的各种API组合，但是总是报同样的错误，错误信息如下
```
E:\MiniConda\envs\pytorch1.7\lib\site-packages\paddle\fluid\executor.py:1344: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
E:\MiniConda\envs\pytorch1.7\lib\site-packages\paddle\fluid\executor.py:986: UserWarning: The variable input1 is not found in program. It is not declared or is pruned.
  % feed_name)
E:\MiniConda\envs\pytorch1.7\lib\site-packages\paddle\fluid\executor.py:986: UserWarning: The variable input2 is not found in program. It is not declared or is pruned.
  % feed_name)
Traceback (most recent call last):
  File "C:/Users/NetPunk/Desktop/PaddleAPI/test.py", line 143, in <module>
    run_static()
  File "C:/Users/NetPunk/Desktop/PaddleAPI/test.py", line 135, in run_static
    fetch_list=[result0, result1, result2])
  File "E:\MiniConda\envs\pytorch1.7\lib\site-packages\paddle\fluid\executor.py", line 1293, in run
    six.reraise(*sys.exc_info())
  File "E:\MiniConda\envs\pytorch1.7\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "E:\MiniConda\envs\pytorch1.7\lib\site-packages\paddle\fluid\executor.py", line 1289, in run
    return_merged=return_merged)
  File "E:\MiniConda\envs\pytorch1.7\lib\site-packages\paddle\fluid\executor.py", line 1458, in _run_impl
    return new_exe.run(list(feed.keys()), fetch_list, return_numpy)
  File "E:\MiniConda\envs\pytorch1.7\lib\site-packages\paddle\fluid\executor.py", line 541, in run
    tensors = self._new_exe.run(feed_names, fetch_list)._move_to_list()
ValueError: (InvalidArgument) The tensor Input (Input) of Slice op is not initialized.
  [Hint: Expected in_tensor.IsInitialized() == true, but received in_tensor.IsInitialized():0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/slice_op.cc:133)


Process finished with exit code 1
```
自定义函数的调用方法如下
```
if __name__ == "__main__":
    paddle.enable_static()

    with fluid.program_guard(Program(), Program()):
        run_static()

def run_static():
    input1_np = np.random.random(size=(2, 3)).astype(np.float32)
    input2_np = np.random.random(size=(2, 3)).astype(np.float32)
    label_np = np.random.randint(low=0, high=2, size=2)

    input1 = paddle.fluid.data(name='input', shape=[2, 3], dtype='float32')
    input2 = paddle.fluid.data(name='input', shape=[2, 3], dtype='float32')
    label = paddle.fluid.data(name='label', shape=[2], dtype='int32')
    result0 = cosine_embedding_loss(input1, input2, label, margin=0.5, reduction='none')
    result1 = cosine_embedding_loss(input1, input2, label, margin=0.5, reduction='sum')
    result2 = cosine_embedding_loss(input1, input2, label, margin=0.5, reduction='mean')

    place = fluid.CPUPlace()
    exe = fluid.Executor(place)
    exe.run(fluid.default_startup_program())
    static_result = exe.run(
        feed={"input1": input1_np,
              "input2": input2_np,
              "label": label_np},
        fetch_list=[result0, result1, result2])
```
自定义函数的构建方法如下
```
def cosine_embedding_loss(input1, input2, label, margin=0, reduction='mean'):
    batch_size, hidden_size = input1.shape
    scores = paddle.zeros([batch_size])
    for i in range(batch_size):
        z = fluid.layers.matmul(fluid.layers.slice(input1, axes=[0, 1], starts=[i, 0], ends=[i + 1, 3]),
                                fluid.layers.slice(input2, axes=[0, 1], starts=[i, 0], ends=[i + 1, 3]),
                                transpose_x=True)
        elem1 = fluid.layers.reduce_sum(
            fluid.layers.pow(fluid.layers.slice(input1, axes=[0, 1], starts=[i, 0], ends=[i + 1, 3]), factor=2.0))
        elem2 = fluid.layers.reduce_sum(
            fluid.layers.pow(fluid.layers.slice(input1, axes=[0, 1], starts=[i, 0], ends=[i + 1, 3]), factor=2.0))
        denom = fluid.layers.sqrt(elem1) * fluid.layers.sqrt(elem2)
        score = z / denom
        if label == 1:
            scores[i] = 1 - score
        elif label == 0:
            scores[i] = max(0, score - margin)

    if reduction == 'none':
        return scores
    if reduction == 'mean':
        return paddle.mean(scores)
    elif reduction == 'sum':
        return paddle.sum(scores)
```
关于提示的Slice op错误我将函数内各种索引操作都去除过，但是没有用

**Comment by sandyhouse** [comment]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/6737864/162659119-18f77821-b64e-4303-ad82-3edfdef9eee4.png">
这个地方name应该分别为'input1'和‘input2’

**Comment by Patrick-Star125** [comment]
> <img alt="image" width="593" src="https://user-images.githubusercontent.com/6737864/162659119-18f77821-b64e-4303-ad82-3edfdef9eee4.png">
> 
> 这个地方name应该分别为'input1'和‘input2’

非常感谢！问题解决了，不过我还有一个疑问，在静态图中实现条件判断似乎有些困难，在上面的代码中有这样一段
```
        if label[i] == 1:
            scores[i] = 1 - score
        elif label[i] == 0:
            scores[i] = max(0, score - margin)
```
要根据label的实际值来选用不同的公式，其中label的输入数据是只包含0和1的一维numpy数组

实际运行过程中`label[i] == 1`一直成立，我尝试过调用获取Variable变量实际值的函数get_value()，但是会在构建静态图的阶段报错。
```
ValueError: Can not find Variable 'label_slice_0' in the Scope.
```

**Comment by sandyhouse** [comment]
静态图里面无法直接使用这种分支判断。静态图里面做分支判断比较麻烦，可以参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/static/nn/switch_case_cn.html
