### ISSUE TITLE
dataloader里面 del self._task_infos[idx]     KeyError

### ISSUE THREAD

**Issue by youlingforever0328** [PaddlePaddle/Paddle#41635]
### bug描述 Describe the Bug

有时候在dataloader里面会报错KeyError:，同样的代码，有时候能跑完没事，但是偶尔会在 ```del self._task_infos[idx]``` 处出现KeyError:

paddlepaddle-gpu==2.2.2 cudatoolkit=11.2
环境Linux 
nvcc: NVIDIA (R) Cuda compiler driver
Cuda compilation tools, release 11.1, V11.1.74

```Exception in thread Thread-43:
Traceback (most recent call last):
  File "/home/xxx/.conda/envs/mylab/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/xxx/.conda/envs/mylab/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/.conda/envs/mylab/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
    batch = self._get_data()
  File "/home/xxx/.conda/envs/mylab/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 637, in _get_data
    del self._task_infos[idx]
KeyError: 1005

### 其他补充信息 Additional Supplementary Information

_No response_

**Comment by sandyhouse** [comment]
请提供个最小可复现代码，谢谢。

**Comment by youlingforever0328** [comment]
> 请提供个最小可复现代码，谢谢。

这个是一个项目里的数据读取部分，最小可复现代码可能没办法整理拿出来😰，这个错误偶尔会发生，大部分时候能完整地跑完都没问题，偶尔会报上面的错误，同一份代码同一个数据集。

大致就是我准备好了数据然后生成了下面三个DataLoader:     文件Mydataset.py部分代码
``` 
train_loader = DataLoader(train_dataset,
                              batch_size=batch_size,
                              shuffle=False,
                              num_workers=4)

valid_loader = DataLoader(valid_dataset,
                              batch_size=batch_size,
                              shuffle=False,
                              num_workers=4)

test_loader = DataLoader(test_dataset,
                             batch_size=batch_size,
                             shuffle=True,
                             num_workers=4)
```

然后在训练时如下: 文件train.py部分代码
```
for batch_id, data in enumerate(train_loader):
      inputs, labels = data
      outputs = Net(inputs)
      .......
```
然后挂到后台训练，偶尔就会报那个错误:
```
Traceback (most recent call last):
  File "/home/xxx/.conda/envs/mylab/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/xxx/.conda/envs/mylab/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xxx/.conda/envs/mylab/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
    batch = self._get_data()
  File "/home/xxx/.conda/envs/mylab/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 637, in _get_data
    del self._task_infos[idx]
KeyError: 1005
```

**Comment by youlingforever0328** [comment]
> 请提供个最小可复现代码，谢谢。

我看了下报错的dataloader_iter.py文件报错的定位，貌似跟num_workers，开了多进程读取数据有关，但是偶尔会报错，有时候又不会报错，不知道有什么解决的办法吗？

**Comment by sandyhouse** [comment]
仅仅从描述上看其实无法准确判断出错原因，一种可能的原因是dataloader在开启多进程是存在bug。我们本地也试一下，也希望能够提供个复现代码帮助我们分析定位问题原因哈。

**Comment by youlingforever0328** [comment]
> 仅仅从描述上看其实无法准确判断出错原因，一种可能的原因是dataloader在开启多进程是存在bug。我们本地也试一下，也希望能够提供个复现代码帮助我们分析定位问题原因哈。

没有数据集可能没办法复现，我只能提供我的dataset.py和train.py了，其实这个问题也不是每次都出现，偶尔出现，之前出现我都是重跑，然后也没事，都能跑完。最近要跑的实验epoch多，batchsize小，时间长了就相对频繁会出现这个报错，就得重跑，感觉有点麻烦，目前还没试过num_work=0,一直都用的num_work=4.

**而且还注意到，每当发生这个KeyError的时候，GPU上的该父进程及其对应的四个子进程（num_work=4）都没有退出，一直占用着GPU的内存，得手动kill**

Mydataset.py
```
import os
import numpy as np
import random
from paddle.io import Dataset, DataLoader

from sklearn import preprocessing
from mne.io import read_raw_edf
import mne


annotation_2_class = {'Sleep stage W': 0,
                      'Sleep stage 1': 1,
                      'Sleep stage 2': 2,
                      'Sleep stage 3': 3,
                      'Sleep stage 4': 4,
                      'Sleep stage R': 5,
                      'Movement time': 6,
                      'Sleep stage ?': 7}


def get_all_data2(data_path, channels):
    all_data = []
    with open('sleep_edf_39.list') as f:
        L = f.readlines()
        for idx in range(int(len(L) / 4)):
            raw1 = read_raw_edf(os.path.join(data_path, L[idx * 4 + 0][:-1]))
            label1 = mne.read_annotations(os.path.join(data_path, L[idx * 4 + 1][:-1]))
            raw2 = read_raw_edf(os.path.join(data_path, L[idx * 4 + 2][:-1]))
            label2 = mne.read_annotations(os.path.join(data_path, L[idx * 4 + 3][:-1]))

            Raw_data = Get_person_RawM_data2(raw1, label1, raw2, label2, channels)
            all_data.append(Raw_data)

    return all_data



def Get_person_RawM_data2(raw1, label1, raw2, label2, channels):
    Raw_data = []

    label_data1 = []
    for item in label1[:-1]:
        duration = int(item['duration'] / 30)
        for _ in range(duration):
            label_data1.append(annotation_2_class[item['description']])

    label_data2 = []
    for item in label2[:-1]:
        duration = int(item['duration'] / 30)
        for _ in range(duration):
            label_data2.append(annotation_2_class[item['description']])

    ptr = 0
    while (ptr < len(label_data1)):
        span = 0
        label3 = []
        EEGdata3 = []
        while (span < 3):
            if ptr >= len(label_data1):
                break
            temp = label_data1[ptr]
            if temp != 6 and temp != 7:
                label3.append(temp)
                EEGdata, times = raw1[channels, 3000 * ptr: 3000 * (ptr + 1)]
                EEGdata3.append(EEGdata)
                span += 1
            ptr += 1
        if span < 3:
            break
        EEGdata = np.concatenate(EEGdata3, axis=-1)
        label3 = np.array(label3)
        Raw_data.append((EEGdata, label3))

    ptr = 0
    while (ptr < len(label_data2)):
        span = 0
        label3 = []
        EEGdata3 = []
        while (span < 3):
            if ptr >= len(label_data2):
                break
            temp = label_data2[ptr]
            if temp != 6 and temp != 7:
                label3.append(temp)
                EEGdata, times = raw2[channels, 3000 * ptr: 3000 * (ptr + 1)]
                EEGdata3.append(EEGdata)
                span += 1
            ptr += 1
        if span < 3:
            break
        EEGdata = np.concatenate(EEGdata3, axis=-1)
        label3 = np.array(label3)
        Raw_data.append((EEGdata, label3))

    return Raw_data



# 标签转换
def label_change(num_class,origon_data,change_box):
    label_num = [0] * num_class
    label = origon_data['label']
    EEG = origon_data['EEG']

    changed_label = np.zeros_like(label)

    for k,v in change_box.items():
        temp = (label == k)
        changed_label += temp * v
        label_num[v] += np.sum(temp)

    weight = [max(label_num) / i for i in label_num]
    return (EEG, changed_label), weight


# 通道标准化
def channle_Z_score(train_EEG,valid_EEG,test_EEG):
    for i in range(train_EEG.shape[1]):
        mean = train_EEG[:, i, :].mean()
        std = train_EEG[:, i, :].std()
        train_EEG[:, i, :] = (train_EEG[:, i, :] - mean) / std
        valid_EEG[:, i, :] = (valid_EEG[:, i, :] - mean) / std
        test_EEG[:, i, :]  = (test_EEG[:, i, :] - mean) / std
    return train_EEG,valid_EEG,test_EEG



class PSD_Dataset(Dataset):
    def __init__(self, data):
        super().__init__()
        self.EEG = data[0]
        self.label = data[1]

    def __getitem__(self, idx):
        eeg, label = self.EEG[idx], self.label[idx]
        eeg = eeg.astype('float32')
        label = label.astype('int64')
        return eeg, label

    def __len__(self):
        return self.label.shape[0]


#根据subject_test分别生成训练集、验证集、测试集的data_loader
def get_data_loader(num_class, all_data, change_box, subject_test, batch_size):
    test_single_data = all_data[subject_test]
    test_num = len(test_single_data)
    print('test_num: ', test_num)

    # split train and valid set
    subject_list = [i for i in range(19)]
    leave_list = subject_list[0:subject_test] + subject_list[subject_test + 1:]
    print('subject_test: ', subject_test)
    print('leave_list: ', leave_list)
    leave_EEG = []
    leave_label = []
    for idx, item in enumerate(leave_list):
        for (EEG, label) in all_data[item]:
            leave_EEG.append(EEG)
            leave_label.append(label)

    leave_EEG = np.array(leave_EEG)  # merge all leave subject EEG
    leave_label = np.array(leave_label)  # merge all leave subject label

    print('leave_EEG.shape: ', leave_EEG.shape)
    print('leave_label.shape: ', leave_label.shape)

    leave_index = np.arange(leave_EEG.shape[0])
    np.random.shuffle(leave_index)  # 打乱，然后取一部分当验证集
    train_index = leave_index[test_num:]
    valid_index = leave_index[:test_num]

    train_EEG = leave_EEG[train_index]
    train_label = leave_label[train_index]

    valid_EEG = leave_EEG[valid_index]
    valid_label = leave_label[valid_index]

    test_EEG = []
    test_label = []
    for (EEG, label) in test_single_data:
        test_EEG.append(EEG)
        test_label.append(label)

    test_EEG = np.array(test_EEG)  # merge all leave subject EEG
    test_label = np.array(test_label)  # merge all leave subject label

    print('train shape ', train_EEG.shape)
    print('valid shape ', valid_EEG.shape)
    print('test shape ', test_EEG.shape)

    train_EEG,valid_EEG,test_EEG = channle_Z_score(train_EEG,valid_EEG,test_EEG)
    

    # 生成三个data_loader
    train_data = {'EEG': train_EEG,'label': train_label}
    train_data, weight = label_change(num_class, train_data, change_box)
    train_dataset = PSD_Dataset(train_data)
    train_loader = DataLoader(train_dataset,
                              batch_size=batch_size,
                              shuffle=False,
                              num_workers=4)

    valid_data = {'EEG': valid_EEG, 'label': valid_label}
    valid_data, _ = label_change(num_class, valid_data, change_box)
    valid_dataset = PSD_Dataset(valid_data)
    valid_loader = DataLoader(valid_dataset,
                              batch_size=batch_size,
                              shuffle=False,
                              num_workers=4)

    test_data  = {'EEG': test_EEG, 'label': test_label}
    test_data, _ = label_change(num_class, test_data, change_box)
    test_dataset = PSD_Dataset(test_data)
    test_loader = DataLoader(test_dataset,
                             batch_size=batch_size,
                             shuffle=True,
                             num_workers=4)

    print('train set length: ', len(train_dataset))
    print('valid set length: ', len(valid_dataset))
    print('test set length:  ', len(test_dataset))

    return train_loader, valid_loader, test_loader, weight


if __name__ == '__main__':
    change_box = {0: 0,
                  1: 1,
                  2: 2,
                  3: 3,
                  4: 3,
                  5: 4}
    data_path = '/mnt/ssd2/hywu/SLEEP_data/sleep-edf-database-expanded-1.0.0/sleep-cassette/'
    all_data = get_all_data2(data_path=data_path, channels=[0, 2])

    train_loader, valid_loader, test_loader, weight = get_data_loader(
        num_class=5,
        all_data=all_data,
        change_box=change_box,
        subject_test=0,
        batch_size=128
    )

    for batch_id, data in enumerate(train_loader):
        inputs, labels = data  # inputs:[128, 2, 9000], labels:[128, 3] 统一规定网络输入
        print('input shape: ',inputs.shape, labels.shape)    
        break
    pass
```


train.py
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
os.environ["FLAGS_cudnn_deterministic"] = "True"

from Mydataset import get_all_data2, get_data_loader
from eval import data_loader_evaluate
from util import log_print

import paddle
import paddle.nn as nn
import logging
import numpy as np
import random
import pickle as pkl
from sklearn.metrics import accuracy_score
from DeepSleepNet import TinySleepNet


paddle.set_device('gpu')
seed = 1815789
paddle.seed(1815789) #设置全局随机种子
random.seed(seed)
np.random.seed(seed)


import argparse

parser = argparse.ArgumentParser()
parser.add_argument("-i", "--info", type=str, default='...', help="exp info")
args = parser.parse_args()

root = '/mnt/ssd2/stzheng/ModelSave/'
model_type = 'M_baseline/'
data_path = '/mnt/ssd2/hywu/SLEEP_data/sleep-edf-database-expanded-1.0.0/sleep-cassette/'
exp_info = 'TinySleepNet2_1e_4'
exp_instruction = 'TinySleepNet EEG+EOG+EMG with 3 label in [with dataset method2] with FLAGS_cudnn_deterministic=True and batchsize=20 lr=1e-4 no early stop and epoch=200 select best in valid set'


save_path = root + model_type + exp_info + '/model'
result_path = root + model_type + exp_info + '/result'
log_path = './' + model_type+'/log'

if not os.path.exists(save_path):
    os.makedirs(save_path)
if not os.path.exists(result_path):
    os.makedirs(result_path)
if not os.path.exists(log_path):
    os.makedirs(log_path)

class_num = 5
change_box = {0:0,
                1:1,
                2:2,
                3:3,
                4:3,
                5:4}
class_label = [0, 1, 2, 3, 4]

num_epochs = 200
early_stop_epoch = 0
learning_rate = 1e-4


# load data
all_data = get_all_data2(data_path=data_path, channels=[0, 2])
print('load ok')


logging.basicConfig(level=logging.DEBUG,
                    filename=log_path + '/record_'+exp_info+'.log',
                    filemode='a',
                    format='%(asctime)s- %(levelname)s:-%(message)s')
log_print('Start logging *****************************')
log_print(exp_instruction)




def train_single_subject(subject_test):
    train_loader, valid_loader, \
    test_loader, weight = get_data_loader(num_class=5,
                                          all_data=all_data,
                                          change_box=change_box,
                                          subject_test=subject_test,
                                          batch_size=20)

    # number
    ACC_times = []
    BCA_times = []
    Fones_macro_times = []
    # array
    Fones_times = []
    Recall_times = []
    confusion_matrix_times = []

    log_print('Start single exp, test subject is : {} >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
              .format(subject_test))
    log_print('subject: {} start exp ----------------------------------'.format(subject_test))


    best_acc = 0.0
    best_bca = 0.0
    best_bca_acc = 0.0
    best_acc_bca = 0.0

    last_best_epoch = 5

    Net = TinySleepNet(inC=2)
    weight_tensor = paddle.to_tensor(weight)

    optim = paddle.optimizer.Adam(parameters=Net.parameters(),learning_rate=learning_rate,weight_decay=0.001)
    loss_func = nn.CrossEntropyLoss(weight=weight_tensor)
    for epoch in range(num_epochs):
        loss_epoch = []
        train_pred = []
        train_true = []
        for batch_id, data in enumerate(train_loader):
            inputs, labels = data
            outputs = Net(inputs) #[128, 3, 5]

            # for train_acc
            result = paddle.argmax(outputs, axis=-1,keepdim=True).numpy()
            result = np.reshape(result, newshape=-1)
            train_pred.append(result)
            train_true.append(np.reshape(labels,newshape=-1))

            loss = loss_func(outputs, labels)
            loss_save = loss.numpy()
            # loss_l.append(loss_save)
            loss_epoch.append(loss_save)

            loss.backward()

            # 更新参数
            optim.step()
            #梯度清0
            optim.clear_grad()

        # train acc
        predict = np.concatenate(train_pred, axis=0)
        groundtruth = np.concatenate(train_true, axis=0)
        train_acc = accuracy_score(groundtruth, predict)

        # evaluate in valid set
        Net.eval()
        acc, bca, F1_score_macro, _, _, _ = data_loader_evaluate(Net, valid_loader, class_label)
        Net.train()


        epoch_average_error = sum(loss_epoch) / len(loss_epoch)
        if acc > best_acc:
            best_acc = acc
            best_acc_bca = bca
            paddle.save(Net.state_dict(),os.path.join(save_path, 'SleepNet_'+str(subject_test)+'.pdparams'))
            last_best_epoch = epoch

        if bca > best_bca:
            best_bca = bca
            best_bca_acc = acc
        

        log_print(
            "epoch:{}, train_acc:{:.5f} loss:{:.5f}, valid_acc:{:.5f}, best_acc:{:.5f}, BCA:{:.5f}, F1:{:.5f}"
            .format(epoch, train_acc, epoch_average_error[0], acc, best_acc, bca, F1_score_macro))

        if early_stop_epoch > 0: # early_stopping
            if epoch - last_best_epoch > early_stop_epoch:
                log_print('early_stopping! curr epoch: {} last_best_epoch: {}'
                            .format(epoch, last_best_epoch))
                break
    # train end
    log_print('——————————————————————————————————————————————————————————————————————————————————————')
    log_print('best acc: {}'.format(best_acc))
    log_print('best_acc_bca: {}'.format(best_acc_bca))
    log_print('best_bca: {}'.format(best_bca))
    log_print('best_bca_acc: {}'.format(best_bca_acc))

    # start test
    log_print('Start test !!!!!!!!!!!!')
    model_path = os.path.join(save_path, 'SleepNet_'+str(subject_test)+'.pdparams')
    Net.load_dict(paddle.load(model_path))
    Net.eval()
    test_acc, test_bca, test_F1_score_macro, \
    test_recall, test_F1_score, cm = data_loader_evaluate(Net, test_loader, class_label)
    Net.train()

    log_print('test ACC: {}'.format(test_acc))
    log_print('test BAC: {}'.format(test_bca))
    log_print('test test_F1_score_macro: {}'.format(test_F1_score_macro))
    log_print('test test_recall: {}'.format(test_recall))
    log_print('test test_F1_score: {}'.format(test_F1_score))
    log_print('——————————————————————————————————————————————————————————————————————————————————————')
    log_print('subject: {} end exp ----------------------------------'.format(subject_test))

    # number metrics
    ACC_times.append(test_acc)
    BCA_times.append(test_bca)
    Fones_macro_times.append(test_F1_score_macro)
    # array metrics
    Recall_times.append(test_recall)
    Fones_times.append(test_F1_score)
    confusion_matrix_times.append(cm)

    del Net

    average_test_acc = np.mean(np.array(ACC_times))
    average_test_bca = np.mean(np.array(BCA_times))
    average_test_f1_macro = np.mean(np.array(Fones_macro_times))

    
    person_test = {'final_test': (ACC_times, BCA_times, Fones_macro_times,Recall_times, Fones_times, confusion_matrix_times)}

    with open(os.path.join(result_path, 'result_subject_'+str(subject_test)+'.pkl'), "wb") as f:
        pkl.dump(person_test, f)

    log_print('average test ACC：{}'.format(average_test_acc))
    log_print('average test BCA：{}'.format(average_test_bca))
    log_print('average test f1-score：{}'.format(average_test_f1_macro))


# 19折交叉验证
if __name__ == '__main__':
    for i in range(0,19):
        print('subject id :**********************',i)
        train_single_subject(subject_test=i)
```

**Comment by HydrogenSulfate** [comment]
同样的问题

**Comment by HydrogenSulfate** [comment]
你好，我这个PR里尝试了修复 #54498 , 我用两个训练时间为五六天的模型进行了自测，训练全程没有再出现 KeyError 的问题，你现在可以重新安装最新版 develop 来解决这个问题
