### ISSUE TITLE
MPI集群任务错误

### ISSUE THREAD

**Issue by alanse7en** [PaddlePaddle/Paddle#4180]
```
ue Sep 19 11:01:08 2017[1,70]<stderr>:Traceback (most recent call last):
Tue Sep 19 11:01:08 2017[1,70]<stderr>:  File "conf/trainer_config.conf", line 7, in <module>
Tue Sep 19 11:01:08 2017[1,70]<stderr>:    import paddle.v2 as paddle
Tue Sep 19 11:01:08 2017[1,70]<stderr>:  File "/home/disk1/normandy/maybach/35337/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/__init__.py", line 26, in <module>
Tue Sep 19 11:01:08 2017[1,70]<stderr>:    from . import dataset
Tue Sep 19 11:01:08 2017[1,70]<stderr>:  File "/home/disk1/normandy/maybach/35337/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/dataset/__init__.py", line 27, in <module>
Tue Sep 19 11:01:08 2017[1,70]<stderr>:    import mq2007
Tue Sep 19 11:01:08 2017[1,70]<stderr>:  File "/home/disk1/normandy/maybach/35337/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/dataset/mq2007.py", line 29, in <module>
Tue Sep 19 11:01:08 2017[1,70]<stderr>:    import rarfile
Tue Sep 19 11:01:08 2017[1,70]<stderr>:  File "/home/disk1/normandy/maybach/35337/workspace/python27-gcc482/lib/python2.7/site-packages/rarfile.py", line 2950, in <module>
Tue Sep 19 11:01:08 2017[1,70]<stderr>:    _check_unrar_tool()
Tue Sep 19 11:01:08 2017[1,70]<stderr>:  File "/home/disk1/normandy/maybach/35337/workspace/python27-gcc482/lib/python2.7/site-packages/rarfile.py", line 2931, in _check_unrar_tool
Tue Sep 19 11:01:08 2017[1,70]<stderr>:    custom_check([ORIG_UNRAR_TOOL], True)
Tue Sep 19 11:01:08 2017[1,70]<stderr>:  File "/home/disk1/normandy/maybach/35337/workspace/python27-gcc482/lib/python2.7/site-packages/rarfile.py", line 2823, in custom_check
Tue Sep 19 11:01:08 2017[1,70]<stderr>:    p = custom_popen(cmd)
Tue Sep 19 11:01:08 2017[1,70]<stderr>:  File "/home/disk1/normandy/maybach/35337/workspace/python27-gcc482/lib/python2.7/site-packages/rarfile.py", line 2813, in custom_popen
Tue Sep 19 11:01:08 2017[1,70]<stderr>:    creationflags=creationflags)
Tue Sep 19 11:01:08 2017[1,70]<stderr>:  File "/home/disk1/normandy/maybach/35337/workspace/python27-gcc482/lib/python2.7/subprocess.py", line 710, in __init__
Tue Sep 19 11:01:08 2017[1,70]<stderr>:    errread, errwrite)
Tue Sep 19 11:01:08 2017[1,70]<stderr>:  File "/home/disk1/normandy/maybach/35337/workspace/python27-gcc482/lib/python2.7/subprocess.py", line 1335, in _execute_child
Tue Sep 19 11:01:08 2017[1,70]<stderr>:    raise child_exception
Tue Sep 19 11:01:08 2017[1,70]<stderr>:OSError: [Errno 13] Permission denied
```
错误日志如上，麻烦看一下是什么原因导致的，多谢。

**Comment by Xreki** [comment]
从这个log来看，好像是权限问题`[Errno 13] Permission denied`

**Comment by alanse7en** [comment]
@Xreki 这个是需要什么的权限？

**Comment by Xreki** [comment]
@alanse7en 从这个出错来看，初步怀疑可能是python问题，这个python版本在`import rarfile`需要什么权限。
你的log里面，已经有训练输出的log了，所以是在什么地方出的这个错呢？可以贴下配置吗？

**Comment by alanse7en** [comment]
@Xreki 不是所有的节点都出了这个问题，没出问题的节点还在继续训练，这也是我认为比较奇怪的地方，集群的任务，不是应该有失败的地方整个任务就失败掉吗？
`import rarfile`不是我的代码啊，应该是paddle某个地方用了这个吧。

**Comment by Yancey1989** [comment]
可能和SELinux的设置有关，`import rarfile`会调用机器上的`unrar`命令做一次check， 相关issue： https://github.com/markokr/rarfile/issues/38, 可以联系OP帮忙排查一下吗？

**Comment by Yancey1989** [comment]
Close the inactivate issue.
