### ISSUE TITLE
Error setting gradient_merge_step>1 with grad_clip for Lamb and Adamw optimizer

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#41858]
### bug描述 Describe the Bug

System information
-PaddlePaddle version: v2.2.2
-GPU: A100 CUDA11.4
-OS Platform: Ubuntu 20.04

Use paddle release v2.2 and [paddlenlp/bert/static](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/bert/static) to reproduce this bug.

1. Prepare a container with `paddle v2.2.2` and `paddlenlp` environment, and a simple hdf5 dataset for BERT pretraining.

2. Add `grad_clip` to optimizer here ([run_pretrain.py#L327](https://github.com/PaddlePaddle/PaddleNLP/blob/519f5527304ddfe2584e143f07b838efb55e1e07/examples/language_model/bert/static/run_pretrain.py#L327))
```python
clip = paddle.nn.ClipGradByGlobalNorm(clip_norm=1.0)
optimizer = paddle.optimizer.AdamW(
    learning_rate=lr_scheduler,
    epsilon=args.adam_epsilon,
    parameters=model.parameters(),
    weight_decay=args.weight_decay,
    apply_decay_param_fun=lambda x: x in decay_params,
    grad_clip=clip,                                       # add grad_clip
    multi_precision=args.use_pure_fp16)
```
Lamb optimizer also encountered the same issue:
```python
clip = paddle.nn.ClipGradByGlobalNorm(clip_norm=1.0)
optimizer = paddle.optimizer.Lamb(
    learning_rate=lr_scheduler,
    lamb_weight_decay=args.weight_decay,
    epsilon=args.adam_epsilon,
    grad_clip=clip)
```
3. Then run bert pretraining with `gradient_merge_steps`=2 (or any number > 1):
```shell
unset CUDA_VISIBLE_DEVICES
python -m paddle.distributed.launch --gpus "0" run_pretrain.py \
    --model_type bert \
    --model_name_or_path bert-base-uncased \
    --max_predictions_per_seq 20 \
    --batch_size 32   \
    --learning_rate 1e-4 \
    --weight_decay 1e-2 \
    --adam_epsilon 1e-6 \
    --warmup_steps 10 \
    --input_dir data/ \
    --output_dir pretrained_models/ \
    --logging_steps 1 \
    --save_steps 100 \
    --max_steps 100 \
    --device gpu \
    --gradient_merge_steps 2\
    --use_amp True
```

The error looks like:
```shell
Traceback (most recent call last):
  File "run_pretrain.py", line 441, in <module>
    do_train(args)
  File "run_pretrain.py", line 339, in do_train
    optimizer.minimize(loss)
  File "/usr/local/lib/python3.8/dist-packages/paddle/distributed/fleet/base/fleet_base.py", line 1500, in minimize
    optimize_ops, params_grads = meta_optimizer.minimize(
  File "/usr/local/lib/python3.8/dist-packages/paddle/distributed/fleet/meta_optimizers/meta_optimizer_base.py", line 94, in minimize
    optimize_ops, params_grads = self.minimize_impl(
  File "/usr/local/lib/python3.8/dist-packages/paddle/distributed/fleet/meta_optimizers/gradient_merge_optimizer.py", line 70, in minimize_impl
    self.wrapped_opt.minimize(loss, startup_program,
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/optimizer.py", line 7095, in minimize
    optimize_ops = self.apply_optimize(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/optimizer.py", line 6868, in apply_optimize
    optimize_ops = self.apply_gradients(params_grads)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/optimizer.py", line 7078, in apply_gradients
    layers.cond(cond, true_fn=true_apply_gradient, false_fn=None)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layers/control_flow.py", line 2466, in cond
    origin_true_output = true_fn()
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/optimizer.py", line 7064, in true_apply_gradient
    self._optimize_ops = self.inner_optimizer.apply_gradients(
  File "/usr/local/lib/python3.8/dist-packages/paddle/distributed/fleet/meta_optimizers/amp_optimizer.py", line 103, in apply_gradients
    return self.wrapped_opt.apply_gradients(params_grads=params_grads)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 414, in apply_gradients
    optimize_ops = self._optimizer.apply_gradients(params_grads)
  File "/usr/local/lib/python3.8/dist-packages/paddle/optimizer/optimizer.py", line 851, in apply_gradients
    params_grads = self._grad_clip(params_grads)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/clip.py", line 171, in __call__
    return self._static_clip(params_grads)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/clip.py", line 550, in _static_clip
    p.block.append_op(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 3178, in append_op
    op = Operator(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 2344, in __init__
    self.desc.infer_shape(self.block.desc)
RuntimeError: (NotFound) No Input(Y) found for ElementwiseOp operator.
  [Hint: Expected ctx->HasInput("Y") == true, but received ctx->HasInput("Y"):0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op.h:45)
  [operator < elementwise_mul > error]
INFO 2022-04-15 02:55:31,830 launch_utils.py:341] terminate all the procs
ERROR 2022-04-15 02:55:31,830 launch_utils.py:602] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-04-15 02:55:35,834 launch_utils.py:341] terminate all the procs
INFO 2022-04-15 02:55:35,834 launch.py:311] Local processes completed.
```

### 其他补充信息 Additional Supplementary Information

We need to pre-train BERT-large from scratch with large batch size (65536, 32768). And `grad_clip` can avoid gradient explosion. So setting `gradient_merge_steps`>1 and `grad_clip` simultaneously for `Lamb` optimizer is necessary. This issue may also occur using other optimizers except `AdamW` and `Lamb` but I haven't tested.

The bug seems to have been solved between release 2.2.2 and develop branch. Because I didn't see any error when using `paddle-nightly-build` to train BERT with the same parameters.

Please help to figure out which commits have fixed this issue.

**Comment by zhangting2020** [comment]
A solution will be given after the bug is reproduced.

**Comment by ZHUI** [comment]
您好，可以尝试一下最新develop版本的paddle看看。Maybe you can try the develop version of paddlepaddle-gpu，this problem may be sloved.

**Comment by zhangting2020** [comment]
It is not easy for us to find which commits  fixed this issue, because there are many changes since the release 2.2.2.

**Comment by ZHUI** [comment]
It is  the problem of `clip`, and we reimplement the `clip`, so this problem is sloved.
