### ISSUE TITLE
test_cumsum_op failure on P100

### ISSUE THREAD

**Issue by leo0519** [PaddlePaddle/Paddle#41932]
### bug描述 Describe the Bug

- 版本、环境信息：
    1. PaddlePaddle版本：请提供您的PaddlePaddle版本号，例如1.1或CommitID
    2. CPU/GPU：Tesla-P100
    3. 系统环境：请您描述系统类型、版本，例如Mac OS 10.14
    4. Python版本号
    5. 显存信息

```bash
$ python3.7 tools/summary_env.py
****************************************
Paddle version: 2.2.2
Paddle With CUDA: True

OS: Ubuntu 18.04
Python version: 3.7.12

CUDA version: 11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
cuDNN version: None.None.None
Nvidia driver version: 470.57.02
****************************************
```

- 复现步骤

```bash
$ echo "
FROM paddlepaddle/paddle:2.2.2-gpu-cuda11.2-cudnn8

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && apt install python3 python3-pip -y

RUN git clone https://github.com/PaddlePaddle/Paddle.git -b v2.2.2 && \
    sed -i 's/BRPC_DEPS brpc/BRPC_DEPS brpc ssl crypto/g' Paddle/paddle/fluid/framework/CMakeLists.txt

RUN pip install --upgrade pip && \
    pip install -r Paddle/python/requirements.txt

RUN cd Paddle && \
    mkdir -p build && \
    cd build && \
    cmake .. \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_FLAGS="-t0" \
    -DCUDA_ARCH_NAME=Manual \
    -DCUDA_ARCH_BIN="60" \
    -DWITH_INCREMENTAL_COVERAGE=OFF \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DWITH_DISTRIBUTE=OFF \
    -DWITH_COVERAGE=OFF \
    -DWITH_TENSORRT=OFF \
    -DWITH_TESTING=ON \
    -DWITH_CONTRIB=OFF \
    -DWITH_ROCM=OFF \
    -DWITH_RCCL=OFF \
    -DWITH_STRIP=ON \
    -DWITH_MKL=OFF \
    -DWITH_AVX=OFF \
    -DWITH_GPU=ON \
    -DWITH_PYTHON=ON \
    -DPY_VERSION=3.7

RUN cd Paddle/build && make -j`nproc`
" > Dockerfile
$ docker build -t paddle .
$ docker run -it --rm --gpus all paddle bash -c 'set -xe; cd Paddle/build; ctest -R test_cumsum_op --output-on-failure'
```

-问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
`test_run_program_op` failed on tesla-P100. The error log is following

```bash
+ ctest -R test_cumsum_op --output-on-failure
Test project /home/Paddle/build
    Start 424: test_cumsum_op
1/1 Test #424: test_cumsum_op ...................***Failed    8.46 sec
W0418 07:48:24.086153     9 init.cc:202] AVX is available, Please re-compile on local machine
W0418 07:48:26.644606     9 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 11.4, Runtime API Version: 11.2
W0418 07:48:26.649191     9 device_context.cc:465] device: 0, cuDNN Version: 8.1.
Hint: Your machine support AVX, but the installed paddlepaddle doesn't have avx core. Hence, no-avx core with worse preformance will be imported.
If you like, you could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' to get better performance.
The original error is: No module named 'paddle.fluid.core_avx'
/home/Paddle/build/python/paddle/nn/functional/loss.py:1281: DeprecationWarning: invalid escape sequence \s
  """
/home/Paddle/build/python/paddle/nn/functional/pooling.py:740: DeprecationWarning: invalid escape sequence \_
  """
/home/Paddle/build/python/paddle/nn/layer/pooling.py:1187: DeprecationWarning: invalid escape sequence \_
  """
/home/Paddle/build/python/paddle/incubate/nn/functional/fused_transformer.py:111: DeprecationWarning: invalid escape sequence \_
  """
/home/Paddle/build/python/paddle/incubate/nn/functional/fused_transformer.py:339: DeprecationWarning: invalid escape sequence \_
  """
/home/Paddle/build/python/paddle/vision/ops.py:952: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (len(x.shape) == 4,
/home/Paddle/build/python/paddle/signal.py:307: DeprecationWarning: invalid escape sequence \o
  """
/home/Paddle/build/python/paddle/signal.py:472: DeprecationWarning: invalid escape sequence \s
  """
/home/Paddle/build/python/paddle/fluid/data_feeder.py:51: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool, np.float16, np.uint16, np.float32, np.float64, np.int8,
/home/Paddle/build/python/paddle/fluid/executor.py:1307: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py:407: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.dtype(np.bool)
test_cumsum_op failed
 ....F.FFF.F.F........F
======================================================================
FAIL: test_check_grad (test_cumsum_op.TestSumOp1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_cumsum_op.py", line 118, in test_check_grad
    self.check_grad(['X'], 'Out')
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1436, in check_grad
    user_defined_grads, user_defined_grad_outputs, check_dygraph)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1545, in check_grad_with_place
    "Gradient Check On %s" % str(place))
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1411, in _assert_is_close
    self.assertLessEqual(max_diff, max_relative_error, err_msg())
AssertionError: 1.0 not less than or equal to 1e-07 : Operator cumsum error, Gradient Check On CUDAPlace(0) variable X (shape: (5, 6, 10), dtype: float64) max gradient diff 1.000000e+00 over limit 1.000000e-07, the first error element is 0, expected 3.333333e-02, but got 0.000000e+00.

======================================================================
FAIL: test_check_grad (test_cumsum_op.TestSumOp2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_cumsum_op.py", line 136, in test_check_grad
    self.check_grad(['X'], 'Out')
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1436, in check_grad
    user_defined_grads, user_defined_grad_outputs, check_dygraph)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1545, in check_grad_with_place
    "Gradient Check On %s" % str(place))
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1411, in _assert_is_close
    self.assertLessEqual(max_diff, max_relative_error, err_msg())
AssertionError: 33.333333333333336 not less than or equal to 1e-07 : Operator cumsum error, Gradient Check On CUDAPlace(0) variable X (shape: (5, 6, 10), dtype: float64) max gradient diff 3.333333e+01 over limit 1.000000e-07, the first error element is 0, expected 0.000000e+00, but got 3.333333e-03.

======================================================================
FAIL: test_check_output (test_cumsum_op.TestSumOp2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_cumsum_op.py", line 133, in test_check_output
    self.check_output()
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1357, in check_output
    inplace_atol)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1222, in check_output_with_place
    str(actual_t) + " in class " + self.__class__.__name__)
AssertionError: False is not true : Output (Out) has diff at CUDAPlace(0)
Expect [[[3.62786241e+00 3.61146993e+00 2.89028556e+00 2.88254805e+00
   2.79772577e+00 2.57222736e+00 1.69710283e+00 1.33352651e+00
   7.93566574e-01 2.25463360e-01]
  [5.92775270e+00 5.35560593e+00 4.69465413e+00 4.39640874e+00
   3.97778188e+00 3.52469296e+00 2.59234229e+00 2.00484855e+00
   1.05659617e+00 5.00561421e-01]
  [4.24542185e+00 4.24188964e+00 3.76100060e+00 2.83354560e+00
   2.63517991e+00 2.58308878e+00 2.17630988e+00 1.80391340e+00
   9.46760345e-01 9.20149230e-01]
  [5.44590377e+00 4.76500077e+00 3.86077478e+00 3.25324571e+00
   2.44129239e+00 2.10574852e+00 1.75618229e+00 1.36630806e+00
   6.11510981e-01 2.42219806e-01]
  [5.67709150e+00 4.73942315e+00 3.83141206e+00 3.48261475e+00
   2.84797668e+00 2.57413447e+00 2.36801934e+00 2.03167981e+00
   1.70457992e+00 8.22303815e-01]
  [3.95956612e+00 3.24994289e+00 2.29059766e+00 1.86805431e+00
   1.62302127e+00 1.50562284e+00 1.20456948e+00 1.05930574e+00
   9.67119646e-01 3.64187450e-01]]

 [[4.79964918e+00 4.23507884e+00 4.04374312e+00 3.36683726e+00
   3.15133181e+00 2.87330822e+00 2.13154779e+00 1.57180990e+00
   1.23697349e+00 6.93984703e-01]
  [5.75315363e+00 4.84102151e+00 4.26030830e+00 4.02762192e+00
   3.28092429e+00 2.50315527e+00 2.30275396e+00 1.48217974e+00
   1.01724488e+00 2.37478220e-01]
  [5.57036439e+00 5.23778412e+00 4.28408700e+00 3.62627193e+00
   2.85339409e+00 2.16501975e+00 1.96071563e+00 1.49002689e+00
   6.81063013e-01 6.02788565e-03]
  [4.19599910e+00 4.10859136e+00 3.76179664e+00 2.81743110e+00
   2.32624062e+00 2.05606435e+00 1.69564063e+00 1.48498800e+00
   1.06378795e+00 8.45752507e-01]
  [4.60799688e+00 4.15172628e+00 3.87192426e+00 2.93903261e+00
   2.62468126e+00 1.71496660e+00 1.67154850e+00 9.64433445e-01
   4.80544406e-01 3.63233444e-02]
  [4.51543680e+00 4.47475361e+00 4.14199999e+00 3.19488045e+00
   2.57722048e+00 2.20834564e+00 1.59636860e+00 1.39023706e+00
   1.22517062e+00 8.63353352e-01]]

 [[6.32518068e+00 5.81577895e+00 5.51887744e+00 4.56862581e+00
   3.75265972e+00 3.42968578e+00 2.45758753e+00 1.47023644e+00
   1.06157630e+00 4.05653198e-01]
  [3.58222030e+00 3.32487220e+00 3.24221952e+00 2.97860917e+00
   2.70712932e+00 2.30849024e+00 2.12360421e+00 1.16978581e+00
   1.06690592e+00 4.41697388e-01]
  [4.65693251e+00 4.23341446e+00 3.86142268e+00 2.99310797e+00
   2.71263099e+00 2.69205483e+00 1.77395781e+00 9.09477536e-01
   6.32575746e-01 1.09088197e-01]
  [4.86245240e+00 4.76902533e+00 3.93155922e+00 3.52129350e+00
   2.85957696e+00 1.91637641e+00 1.67124581e+00 1.65808598e+00
   1.63393758e+00 9.24551885e-01]
  [4.81678641e+00 4.34945614e+00 3.97434699e+00 3.43148656e+00
   2.57256973e+00 1.92041585e+00 1.68743596e+00 9.12855751e-01
   7.78242254e-01 6.12682283e-01]
  [4.28486129e+00 4.04607789e+00 3.34129934e+00 2.99178081e+00
   2.71435685e+00 1.71543845e+00 1.67482232e+00 1.02899980e+00
   9.90300215e-01 2.30089957e-01]]

 [[4.17500620e+00 4.08517433e+00 3.43672462e+00 2.70412340e+00
   2.02602809e+00 1.97412714e+00 1.67982020e+00 1.22873185e+00
   9.41628561e-01 1.31115105e-01]
  [6.66809160e+00 6.05591224e+00 5.06769729e+00 4.16514076e+00
   3.94298369e+00 3.94290181e+00 2.96230446e+00 2.07959148e+00
   1.16011901e+00 7.44615462e-01]
  [5.14088348e+00 4.92805198e+00 4.53574791e+00 3.68419985e+00
   3.55658763e+00 2.66272226e+00 2.16621429e+00 1.74011863e+00
   1.43447225e+00 5.17623461e-01]
  [6.07183474e+00 5.26780837e+00 4.41015659e+00 3.48777423e+00
   3.18439350e+00 2.84458264e+00 2.24950877e+00 1.80818463e+00
   8.75342100e-01 4.77778048e-01]
  [4.39059312e+00 3.77340703e+00 3.36866754e+00 2.37618911e+00
   2.27733782e+00 2.05673450e+00 1.73407937e+00 1.58635653e+00
   1.30213729e+00 5.22892001e-01]
  [4.82860476e+00 4.79465113e+00 3.81202854e+00 3.19602207e+00
   3.13708259e+00 2.47591382e+00 2.09754444e+00 1.96187115e+00
   1.39820655e+00 6.71126604e-01]]

 [[5.25909070e+00 5.01157755e+00 4.48671133e+00 3.94904788e+00
   3.23224452e+00 2.87237717e+00 2.07464457e+00 1.44672272e+00
   1.40839112e+00 8.61912095e-01]
  [4.27385429e+00 3.70628013e+00 3.53045187e+00 3.02007550e+00
   2.26312966e+00 2.15302446e+00 1.33592538e+00 1.16844374e+00
   6.34367250e-01 2.48623768e-01]
  [4.83451537e+00 4.18708286e+00 4.14969075e+00 3.38964494e+00
   2.86270431e+00 1.98693309e+00 1.46621477e+00 1.43118161e+00
   1.28758064e+00 4.91976049e-01]
  [6.64307427e+00 6.20119500e+00 5.88276022e+00 5.59821102e+00
   4.63232471e+00 4.19935537e+00 3.31535234e+00 2.66718922e+00
   1.80876157e+00 9.56312028e-01]
  [5.86743062e+00 5.16948839e+00 4.36409145e+00 3.63096356e+00
   3.02573672e+00 2.30838259e+00 1.59263218e+00 1.55172438e+00
   1.03561355e+00 2.42962187e-01]
  [3.66898703e+00 3.20383905e+00 2.76885334e+00 2.36606617e+00
   2.24422664e+00 1.71851510e+00 1.27226673e+00 6.08873976e-01
   5.94609173e-02 3.19179876e-02]]]
But Got[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]] in class TestSumOp2

======================================================================
FAIL: test_check_grad (test_cumsum_op.TestSumOp3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_cumsum_op.py", line 150, in test_check_grad
    self.check_grad(['X'], 'Out')
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1436, in check_grad
    user_defined_grads, user_defined_grad_outputs, check_dygraph)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1545, in check_grad_with_place
    "Gradient Check On %s" % str(place))
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1411, in _assert_is_close
    self.assertLessEqual(max_diff, max_relative_error, err_msg())
AssertionError: 1.0 not less than or equal to 1e-07 : Operator cumsum error, Gradient Check On CUDAPlace(0) variable X (shape: (5, 6, 10), dtype: float64) max gradient diff 1.000000e+00 over limit 1.000000e-07, the first error element is 0, expected 2.000000e-02, but got 0.000000e+00.

======================================================================
FAIL: test_check_grad (test_cumsum_op.TestSumOp4)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_cumsum_op.py", line 164, in test_check_grad
    self.check_grad(['X'], 'Out')
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1436, in check_grad
    user_defined_grads, user_defined_grad_outputs, check_dygraph)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1545, in check_grad_with_place
    "Gradient Check On %s" % str(place))
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1411, in _assert_is_close
    self.assertLessEqual(max_diff, max_relative_error, err_msg())
AssertionError: 1.0 not less than or equal to 1e-07 : Operator cumsum error, Gradient Check On CUDAPlace(0) variable X (shape: (5, 6, 10), dtype: float64) max gradient diff 1.000000e+00 over limit 1.000000e-07, the first error element is 0, expected 1.666667e-02, but got 0.000000e+00.

======================================================================
FAIL: test_check_grad (test_cumsum_op.TestSumOp5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_cumsum_op.py", line 177, in test_check_grad
    self.check_grad(['X'], 'Out')
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1436, in check_grad
    user_defined_grads, user_defined_grad_outputs, check_dygraph)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1545, in check_grad_with_place
    "Gradient Check On %s" % str(place))
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1411, in _assert_is_close
    self.assertLessEqual(max_diff, max_relative_error, err_msg())
AssertionError: 1.0 not less than or equal to 1e-07 : Operator cumsum error, Gradient Check On CUDAPlace(0) variable X (shape: (5, 20), dtype: float64) max gradient diff 1.000000e+00 over limit 1.000000e-07, the first error element is 0, expected 2.000000e-01, but got 0.000000e+00.

======================================================================
FAIL: test_check_output (test_cumsum_op.TestSumOpReverseExclusive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_cumsum_op.py", line 294, in test_check_output
    self.check_output()
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1357, in check_output
    inplace_atol)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1222, in check_output_with_place
    str(actual_t) + " in class " + self.__class__.__name__)
AssertionError: False is not true : Output (Out) has diff at CUDAPlace(0)
Expect [[[2.20688099 1.92074165 1.6938902  1.14257543 0.42310646 0.        ]
  [2.63010688 1.94527714 1.46434524 1.07222772 0.72904971 0.        ]
  [1.55366104 1.49398315 1.09593889 0.35794349 0.17545176 0.        ]
  [3.35113918 2.81931159 2.18491063 1.33547884 0.61102351 0.        ]
  [1.83770097 1.51474206 1.1529534  0.92469017 0.63097612 0.        ]]

 [[2.09634055 1.66263937 1.23177661 0.73809151 0.31226122 0.        ]
  [3.0789572  2.18556804 1.24140802 0.73957135 0.1156184  0.        ]
  [3.00018479 2.58535857 1.71904942 1.46859405 0.98555979 0.        ]
  [2.70799213 2.0950976  1.97446894 1.14812813 0.54506801 0.        ]
  [2.78832295 2.48420216 2.06717995 1.38587918 0.51042234 0.        ]]

 [[2.81106653 2.22512998 1.60022648 0.92553743 0.08319499 0.        ]
  [1.99138564 1.74771926 1.5534963  0.98103934 0.88532683 0.        ]
  [2.04972228 1.32630592 1.31017672 0.71574484 0.15895964 0.        ]
  [2.64960007 1.95407055 1.63530412 0.94333382 0.38895057 0.        ]
  [1.94561278 1.10394279 0.74654522 0.70295376 0.39818568 0.        ]]

 [[3.39869988 2.40334139 2.04742653 1.28487872 0.6917018  0.        ]
  [2.16294091 1.76406462 1.52320872 1.1797527  0.66662455 0.        ]
  [2.51420346 2.38330851 2.06132791 1.39976357 0.55325734 0.        ]
  [2.05608485 1.67124704 1.35445914 1.00019446 0.82911263 0.        ]
  [2.64348809 2.09111801 1.51256654 0.99103348 0.98834542 0.        ]]]
But Got[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]] in class TestSumOpReverseExclusive

----------------------------------------------------------------------
Ran 22 tests in 4.664s

FAILED (failures=7)



0% tests passed, 1 tests failed out of 1
```

**Comment by zlsh80826** [comment]
Fixed by https://github.com/PaddlePaddle/Paddle/pull/42205
