### ISSUE TITLE
【论文复现】TIPC动转静的时候paddle.autograd.PyLayer的apply()报错不支持，如何解决？

### ISSUE THREAD

**Issue by hatimwen** [PaddlePaddle/Paddle#41982]
### 请提出你的问题 Please ask your question

运行环境：

- Python 3.7.11

- paddlepaddle-gpu    2.2.2.post111

模型由动态图模式转为静态图的时候，报如下的错：

```bash
AssertionError: We only support 'apply()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.
```

下面是一段复现此报错的动态图转静态图代码：

```python
import os
import paddle
import paddle.nn as nn
from paddle.static import InputSpec

class Hash(paddle.autograd.PyLayer):
    @staticmethod
    def forward(ctx, input):
        return input.sign()

    @staticmethod
    def backward(ctx, grad_output):
        return grad_output

class Net(nn.Layer):
    def __init__(self) -> None:
        super().__init__()
    def forward(self, x):
        code = Hash.apply(x)
        return code

if __name__ == "__main__":
    save_inference_dir = "./tipc_output"
    model = Net()
    model = paddle.jit.to_static(
        model,
        input_spec=[
            InputSpec(
                shape=[None, 10], dtype='float32')
        ])
    # save inference model
    paddle.jit.save(model, os.path.join(save_inference_dir, "inference"))
    print(f"inference model is saved in {save_inference_dir}")
```

具体报错如下：

```bash
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    paddle.jit.save(model, os.path.join(save_inference_dir, "inference"))
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save
    inner_input_spec)
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
    **cache_key.kwargs)
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 668, in from_func_spec
    error_data.raise_new_exception()
  File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "test.py", line 19, in forward
            super().__init__()
        def forward(self, x):
            code = Hash.apply(x)
            ~~~~~~~~~~~~~~~~~~~~ <--- HERE
            return code

    File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/decorator.py", line 232, in fun
        return caller(func, *(extras + args), **kw)
    File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
        return wrapped_func(*args, **kwargs)
    File "/home/super/anaconda3/envs/paddle_222/lib/python3.7/site-packages/paddle/fluid/framework.py", line 228, in __impl__
        ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__

    AssertionError: We only support 'apply()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.
```

**Comment by yaoxuefeng6** [comment]
PyLayer 机制目前还没有支持，后续会评估一下支持方案

**Comment by littletomatodonkey** [comment]
你好，可以把Net这个类的代码实现如下

```python
class Net(nn.Layer):
    def __init__(self) -> None:
        super().__init__()
    def forward(self, x):
        if self.training:
            code = Hash.apply(x)
        else:
            code = x.sign()
        return code
```

然后导出之前，需要做一下model.eval()，切换到eval模式哈

**Comment by hatimwen** [comment]
> 你好，可以把Net这个类的代码实现如下
> 
> ```python
> class Net(nn.Layer):
>     def __init__(self) -> None:
>         super().__init__()
>     def forward(self, x):
>         if self.training:
>             code = Hash.apply(x)
>         else:
>             code = x.sign()
>         return code
> ```
> 
> 然后导出之前，需要做一下model.eval()，切换到eval模式哈

可以导出静态模型了，谢谢老师！
