### ISSUE TITLE
GPU单机多卡训练报错 ’cannot pickle paddle.fluid.core.avx.Place‘

### ISSUE THREAD

**Issue by ganyixian** [PaddlePaddle/Paddle#42150]
### bug描述 Describe the Bug

使用单机多卡GPU进行训练的时候启动报错，完整报错信息如下
```
Traceback (most recent call last):
  File "/var/lib/condor/execute/slot1/dir_62117/AdvBox/hello.py", line 43, in <module>
    dist.spawn(train, args=(train_loader, test_loader, ))
  File "/var/lib/condor/execute/slot1/dir_62117/perce11/lib/python3.9/site-packages/paddle/distributed/spawn.py", line 554, in spawn
    process.start()
  File "/var/lib/condor/execute/slot1/dir_62117/perce11/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/var/lib/condor/execute/slot1/dir_62117/perce11/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/var/lib/condor/execute/slot1/dir_62117/perce11/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/var/lib/condor/execute/slot1/dir_62117/perce11/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/var/lib/condor/execute/slot1/dir_62117/perce11/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/var/lib/condor/execute/slot1/dir_62117/perce11/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'paddle.fluid.core_avx.Place' object

```
运行环境为paddlepaddle-gpu 2.2, Cuda 11.2, CuDNN 8.1, nccl 2.12
训练代码:
```python
import os
import sys
sys.path.append("../..")

import paddle
import paddle.distributed as dist

USE_GPU = paddle.get_device()
if USE_GPU.startswith('gpu'):
    paddle.set_device("gpu")
else:
    paddle.set_device("cpu")
paddle.seed(2021)


def train(train_loader=None, test_loader=None):
    dist.init_parallel.env()
    m = paddle.vision.models.resnet34(pretrained=False, num_classes=10)
    model = paddle.DataParallel(m)
    # model = paddle.Model(m)
    opt = paddle.optimizer.Adam(learning_rate=0.001, parameters=model.parameters()),
    loss = paddle.nn.CrossEntropyLoss()

    model.train()
    for x, y in train_loader:
        out = model(x)
        l = loss(out, y)
        l.backward()
        opt.step()
        opt.clear_grad()
    paddle.save(model.state_dict(), os.path.realpath(__file__+'../')+'test.pdparams')

if __name__ == '__main__':
    train_dataset = paddle.vision.datasets.MNIST(mode='train')
    test_dataset = paddle.vision.datasets.MNIST(mode='test')
    train_loader = paddle.io.DataLoader(train_dataset, batch_size=64, shuffle=True)
    test_loader = paddle.io.DataLoader(test_dataset, batch_size=64, shuffle=True)

    dist.spawn(train, args=(train_loader, test_loader, ))
```
通过指令```python train.py```运行后报上述错误

**Comment by wangxicoding** [comment]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/10208305/164909610-0f289d6d-8864-47e9-b225-121e4d9774de.png">
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/spawn_cn.html#spawn
应该是Place没法pickled。把set_device和data_loader都放进目标函数里吧

**Comment by ganyixian** [comment]
那请问在目标函数里调用内部子函数或者类方法可以吗？现在训练可以正常启动，但是好像进程没办法中止可能是由于什么原因呢？

**Comment by wangxicoding** [comment]
可以调用。进程中止，是指ctrl+c这种，还是训练完后自动退出？

**Comment by ganyixian** [comment]
训练完成后不会自动退出

**Comment by wangxicoding** [comment]
可以用nvidia-smi看下是否还有卡在运行，可能是由于各个卡数据量不一致导致step不一致，然后某张卡一直在同步等待别的卡

**Comment by ganyixian** [comment]
好的，请问多卡训练默认是如何进行数据切分的？我在训练中发现使用单卡和使用4卡每一轮中的迭代次数是相同的，请问这是符合预期的吗？

**Comment by wangxicoding** [comment]
多卡一般需要将数据切分一下，每轮相同随机种子shuffle一下，然后根据卡号取各自数据。
比如有[0, 1, 2, 3, 4, 5, 6, 7]样本，2张卡，那么不同epoch可以：
0 epoch：0卡[0, 1, 2, 3], 1卡[4, 5 ,6, 7]
1 epoch：0卡[0, 3, 6, 7]，1卡[1, 2, 4, 5]
...
这种数据切分方式可以使用DistributedBatchSampler_cn来切分，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DistributedBatchSampler_cn.html

当然也可以每张卡不切分数据，设置不同的随机种子，确保shuffle后顺序不一致，然后读入数据。比如上面的数据，
shuffle后可能，0卡[0, 1, 2, 3, 4, 5, 6, 7] 1卡[3, 5, 7, 2, 0 ,1, 4, 6]，然后读入训练。不过这个时候需要注意这时一个epoch的数据量是切分后的两倍，总训练epoch数需要减半。或者保证相同bsz下，总step相同即可。

**Comment by ganyixian** [comment]
在每一次迭代中对不同GPU上的损失梯度求平均的操作是在优化器的step()函数里完成的吗？有没有办法能让不同GPU在这一步时先不计算平均梯度，之后再手动计算？

**Comment by ForFishes** [comment]
1、不是在step中完成，是在backward()中完成，和反向计算一起overlap执行。2、可以调用no_sync接口，屏蔽backward阶段的梯度同步，然后在backward()结束后，再手动调用通信算子实现梯度同步。
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/DataParallel_cn.html#dataparallel
