### ISSUE TITLE
网络结构搜索官方教程代码执行报错

### ISSUE THREAD

**Issue by moneypi** [PaddlePaddle/Paddle#42308]
### 文档链接&描述 Document Links & Description

链接： https://paddleslim.readthedocs.io/zh_CN/latest/quick_start/static/nas_tutorial.html
直接执行此代码，会报如下错误：
```
Traceback (most recent call last):
  File "/home/luke/paddle/NAS/nas_study.py", line 83, in <module>
    start_train(train_program, train_loader)
  File "/home/luke/paddle/NAS/nas_study.py", line 61, in start_train
    batch_reward = exe.run(program, feed=data, fetch_list = outputs)
  File "/home/luke/miniconda3/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1262, in run
    six.reraise(*sys.exc_info())
  File "/home/luke/miniconda3/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/luke/miniconda3/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1250, in run
    return self._run_impl(
  File "/home/luke/miniconda3/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1394, in _run_impl
    return self._run_program(
  File "/home/luke/miniconda3/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1491, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
ValueError: In user code:

    File "/home/luke/paddle/NAS/nas_study.py", line 79, in <module>
      exe, train_program, eval_program, (image, label), avg_cost, acc_top1, acc_top5 = build_program(archs)
    File "/home/luke/paddle/NAS/nas_study.py", line 22, in build_program
      cost = F.cross_entropy(softmax_out, label=label)
    File "/home/luke/miniconda3/lib/python3.9/site-packages/paddle/nn/functional/loss.py", line 1777, in cross_entropy
      helper.append_op(
    File "/home/luke/miniconda3/lib/python3.9/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/luke/miniconda3/lib/python3.9/site-packages/paddle/fluid/framework.py", line 3178, in append_op
      op = Operator(
    File "/home/luke/miniconda3/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: If Attr(soft_label) == false, the axis dimension of Input(Label) should be 1.
      [Hint: Expected labels_dims[axis] == 1UL, but received labels_dims[axis]:94587512244880 != 1UL:1.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:192)
      [operator < softmax_with_cross_entropy > error]
```
运行环境：
Ubuntu 20.04
paddlepaddle:2.2.2

**Comment by zhwesky2010** [comment]
@moneypi 感谢提出问题，我们后续会修复该文档的bug

**Comment by zhwesky2010** [comment]
@ceci3 你好，麻烦看下这里的文档问题，另外 发现这里input_data少了个输入，也是跑不了的
![infoflow 2022-04-28 11-36-14](https://user-images.githubusercontent.com/52485244/165671325-7eb30600-0a23-447d-ad3f-15bb77f3d61e.png)

**Comment by moneypi** [comment]
我已解决此问题，链接 https://github.com/PaddlePaddle/PaddleSlim/blob/develop/docs/zh_cn/quick_start/static/nas_tutorial.md
是正确的。
请更新教程文档

**Comment by luotao1** [comment]
教程已更新，感谢您的建议！
