### ISSUE TITLE
安装旧版本1.8.5，无论pip还是conda最后由于pathlib模块报错无法完成安装

### ISSUE THREAD

**Issue by vxfla** [PaddlePaddle/Paddle#42432]
### 问题描述 Issue Description

无法安装，报错信息部分截取如下
2b/pathlib-0.3.tar.gz (27 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/work/anaconda3/envs/rocketqa/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qeuuz8km/pathlib_934e806ad6c34c9586b5f988a485f639/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qeuuz8km/pathlib_934e806ad6c34c9586b5f988a485f639/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cxa_vaw8
         cwd: /tmp/pip-install-qeuuz8km/pathlib_934e806ad6c34c9586b5f988a485f639/
    Complete output (21 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qeuuz8km/pathlib_934e806ad6c34c9586b5f988a485f639/setup.py", line 28, in <module>
        url='http://readthedocs.org/docs/pathlib/',
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 109, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/dist.py", line 460, in __init__
        for ep in metadata.entry_points(group='distutils.setup_keywords'):
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
        return SelectableGroups.load(eps).select(**params)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
        ordered = sorted(eps, key=by_group)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 997, in <genexpr>
        dist.entry_points for dist in unique(distributions())
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 609, in entry_points
        return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 917, in read_text
        return self._path.joinpath(filename).read_text(encoding='utf-8')
      File "/tmp/pip-install-qeuuz8km/pathlib_934e806ad6c34c9586b5f988a485f639/pathlib.py", line 927, in __getattr__
        return super().__getattribute__(name)
    AttributeError: 'PosixPath' object has no attribute 'joinpath'
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/94/6b/2239738ba4f46b917cabdbd1d8bdc7c443a9498a6fa83dad388a785a872b/pathlib-0.3.tar.gz#sha256=fbf7a43ab854391202845ce8f6c4acbfc3dd5fd1b4bc689f3b5433c8d9231c32 (from https://pypi.tuna.tsinghua.edu.cn/simple/pathlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/81/4b/23433a0aa0273ee3ac511d58d4a8c6815554b84a71caab02dc3f0cd79b17/pathlib-0.2.tar.gz (27 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/work/anaconda3/envs/rocketqa/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qeuuz8km/pathlib_3025df3a86144e0e8524841165c3cc15/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qeuuz8km/pathlib_3025df3a86144e0e8524841165c3cc15/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-f714wgqc
         cwd: /tmp/pip-install-qeuuz8km/pathlib_3025df3a86144e0e8524841165c3cc15/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qeuuz8km/pathlib_3025df3a86144e0e8524841165c3cc15/setup.py", line 28, in <module>
        url='http://readthedocs.org/docs/pathlib/',
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 109, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/dist.py", line 460, in __init__
        for ep in metadata.entry_points(group='distutils.setup_keywords'):
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
        return SelectableGroups.load(eps).select(**params)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
        ordered = sorted(eps, key=by_group)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 997, in <genexpr>
        dist.entry_points for dist in unique(distributions())
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 609, in entry_points
        return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 917, in read_text
        return self._path.joinpath(filename).read_text(encoding='utf-8')
    AttributeError: 'PosixPath' object has no attribute 'joinpath'
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/81/4b/23433a0aa0273ee3ac511d58d4a8c6815554b84a71caab02dc3f0cd79b17/pathlib-0.2.tar.gz#sha256=21de0e7c7eeab7b88bd92e11cad0f58c8370382d8ca39169331f6ae135b26b91 (from https://pypi.tuna.tsinghua.edu.cn/simple/pathlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3c/a7/573e6c37775848cd2f9d0fcdf9dd168739f6534e6624573a968f3838d436/pathlib-0.1.tar.gz (26 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/work/anaconda3/envs/rocketqa/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qeuuz8km/pathlib_0ae8e31fe52f4e07a6c24ea8c4529125/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qeuuz8km/pathlib_0ae8e31fe52f4e07a6c24ea8c4529125/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ro4c02dc
         cwd: /tmp/pip-install-qeuuz8km/pathlib_0ae8e31fe52f4e07a6c24ea8c4529125/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qeuuz8km/pathlib_0ae8e31fe52f4e07a6c24ea8c4529125/setup.py", line 28, in <module>
        url='http://readthedocs.org/docs/pathlib/',
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 109, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/dist.py", line 460, in __init__
        for ep in metadata.entry_points(group='distutils.setup_keywords'):
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 999, in entry_points
        return SelectableGroups.load(eps).select(**params)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 449, in load
        ordered = sorted(eps, key=by_group)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 997, in <genexpr>
        dist.entry_points for dist in unique(distributions())
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 609, in entry_points
        return EntryPoints._from_text_for(self.read_text('entry_points.txt'), self)
      File "/home/work/anaconda3/envs/rocketqa/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 917, in read_text
        return self._path.joinpath(filename).read_text(encoding='utf-8')
    AttributeError: 'PosixPath' object has no attribute 'joinpath'
    ----------------------------------------
WARNING: Discarding https://pypi.tuna.tsinghua.edu.cn/packages/3c/a7/573e6c37775848cd2f9d0fcdf9dd168739f6534e6624573a968f3838d436/pathlib-0.1.tar.gz#sha256=d09e494964125084d67132c42b9e61fa4b428fa0dd8ae7aa2fb25925eeabc3e0 (from https://pypi.tuna.tsinghua.edu.cn/simple/pathlib/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pathlib (from paddlepaddle-gpu) (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.97, 1.0, 1.0.1)
ERROR: No matching distribution found for pathlib

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: None
Paddle With CUDA: None

OS: Ubuntu 16.04
Python version: 3.7.13

CUDA version: 10.1.105
cuDNN version: 7.6.0
Nvidia driver version: 418.67
****************************************

**Comment by littletomatodonkey** [comment]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/14270174/166214774-20d3709e-e94d-42b3-894f-5fcf4b7f1728.png">

你好，根据上面的报错，是pathlib库安装问题导致的，建议在这里先安装下pathlib，再安装paddle试下

**Comment by vxfla** [comment]
> <img alt="image" width="832" src="https://user-images.githubusercontent.com/14270174/166214774-20d3709e-e94d-42b3-894f-5fcf4b7f1728.png">
> 
> 你好，根据上面的报错，是pathlib库安装问题导致的，建议在这里先安装下pathlib，再安装paddle试下

安装paddle前，我已经安装pathlib了，是1.0.1版本的

**Comment by littletomatodonkey** [comment]
使用`pip install --no-deps paddlepaddle-gpu==1.8.5`试下哈，然后缺什么包，再单独安装即可

**Comment by littletomatodonkey** [comment]
你好，我在安装pathlib之后，再安装1.8.5的paddle，没有出现你所说的报错，想问下按照上面的操作有做不？

![image](https://user-images.githubusercontent.com/14270174/167288817-f0cd6617-cf13-4569-9306-3ae5d5a85d50.png)

**Comment by vxfla** [comment]
嗯嗯 问题解决了
