### ISSUE TITLE
[Docker]Should using opencv-python-headless instead with opencv-python

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#42562]
### bug描述 Describe the Bug

While running paddle inside docker, it will lead error like this:

```
Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 234, in locate_app
    __import__(module_name)
  File "/ldasum/app.py", line 6, in <module>
    import paddlehub as hub
  File "/usr/local/lib/python3.8/site-packages/paddlehub/__init__.py", line 31, in <module>
    from paddlehub import datasets
  File "/usr/local/lib/python3.8/site-packages/paddlehub/datasets/__init__.py", line 15, in <module>
    from paddlehub.datasets.canvas import Canvas
  File "/usr/local/lib/python3.8/site-packages/paddlehub/datasets/canvas.py", line 23, in <module>
    from paddlehub.vision.utils import get_img_file
  File "/usr/local/lib/python3.8/site-packages/paddlehub/vision/utils.py", line 18, in <module>
    import cv2
  File "/usr/local/lib/python3.8/site-packages/cv2/__init__.py", line 8, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

### 其他补充信息 Additional Supplementary Information

by the opencv document
```
Packages for server (headless) environments (such as Docker, cloud environments etc.), no GUI library dependencies

These packages are smaller than the two other packages above because they do not contain any GUI functionality (not compiled with Qt / other GUI components). This means that the packages avoid a heavy dependency chain to X11 libraries and you will have for example smaller Docker images as a result. You should always use these packages if you do not use cv2.imshow et al. or you are using some other package (such as PyQt) than OpenCV to create your GUI.

Option 3 - Headless main modules package: pip install opencv-python-headless
Option 4 - Headless full package (contains both main modules and contrib/extra modules): pip install opencv-contrib-python-headless (check contrib/extra modules listing from [OpenCV documentation](https://docs.opencv.org/master/))
```

see: https://pypi.org/project/opencv-python-headless/

**Comment by nemonameless** [comment]
Both of these are OK. Please make sure that ```import cv2``` can run ok first, which is only related to your machine environment.
