### ISSUE TITLE
DeepSpeech2 raise error when training

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#4268]
```
root@ef135375cad3:/baidu/models/deep_speech_2/examples/librispeech# bash run_train.sh > rec.txt
I0917 00:38:07.764762   826 Util.cpp:166] commandline:  --use_gpu=1 --trainer_count=8 
[INFO 2017-09-17 00:38:11,339 layers.py:2188] output for __img_conv_layer_0__: c = 32, h = 81, w = 54, size = 139968
[WARNING 2017-09-17 00:38:11,340 layers.py:2547] brelu is not recommend for batch normalization's activation, maybe the relu is better
[INFO 2017-09-17 00:38:11,341 layers.py:2188] output for __img_conv_layer_1__: c = 32, h = 41, w = 54, size = 70848
[WARNING 2017-09-17 00:38:11,342 layers.py:2547] brelu is not recommend for batch normalization's activation, maybe the relu is better
[WARNING 2017-09-17 00:38:11,344 layers.py:2547]  is not recommend for batch normalization's activation, maybe the relu is better
[CRITICAL 2017-09-17 00:38:11,345 layers.py:2571] Input layer __fc_layer_0__: Incorrect input image size 54 * 41 for input image pixels 1
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    main()
  File "train.py", line 120, in main
    train()
  File "train.py", line 104, in train
    share_rnn_weights=args.share_rnn_weights)
  File "/baidu/models/deep_speech_2/model_utils/model.py", line 42, in __init__
    self._create_parameters(pretrained_model_path)
  File "/baidu/models/deep_speech_2/model_utils/model.py", line 228, in _create_parameters
    self._parameters = paddle.parameters.create(self._loss)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 19, in create
    topology = Topology(layers)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/topology.py", line 69, in __init__
    layers, extra_layers=extra_layers)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/layer.py", line 96, in parse_network
    return __parse__(__real_func__)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/config_parser_utils.py", line 32, in parse_network_config
    config = config_parser.parse_config(network_conf, config_arg_str)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3597, in parse_config
    trainer_config()
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/layer.py", line 89, in __real_func__
    real_output = [each.to_proto(context=context) for each in output_layers]
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
    context=context)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto                                       [40/1870]
    context=context)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
    context=context)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 112, in to_proto
    self.__parent_layers__[layer_name])
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 111, in <lambda>
    v1_layer = map(lambda x: x.to_proto(context=context),
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
    context=context)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
    context=context)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
    context=context)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 112, in to_proto
    self.__parent_layers__[layer_name])
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 111, in <lambda>
    v1_layer = map(lambda x: x.to_proto(context=context),
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
    context=context)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
    context=context)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
    context=context)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 112, in to_proto
    self.__parent_layers__[layer_name])
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 111, in <lambda>
    v1_layer = map(lambda x: x.to_proto(context=context),
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 109, in to_proto
    context=context)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 116, in to_proto
    ret_val = self.to_proto_impl(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 212, in to_proto_impl
    return getattr(conf_helps, method_name)(**args)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 329, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 2571, in batch_norm_layer
    **ExtraLayerAttribute.to_kwargs(layer_attr))
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3180, in Layer
    return layer_func(name, **xargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 2012, in __init__
    parse_image(self.inputs[0].image, input_layer.name, image_conf)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 1218, in parse_image
    get_img_size(input_layer_name, image_conf.channels)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 1165, in get_img_size
    % (input_layer_name, img_size, img_size_y, img_pixels))
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 163, in config_assert
    logger.fatal(msg)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3517, in my_fatal
    raise Exception()
Exception
```

**Comment by jacquesqiao** [comment]
```
To be thorough, we found that we needed to run `apt-get update wget libsndfile1-dev` before `sh setup.sh`. We then ran `models/librispeech/download_model.sh`, `deep_speech_2/models/lm/download_lm_en.sh`, and `deep_speech_2/data/librispeech/librispeech.py` with the modified `default='/baidu/paddle/dataset/speech/libri'`.

Thus, the data should not be customized at all.
```

**Comment by jacquesqiao** [comment]
OK. I just change
```parser.add_argument(
     "--target_dir",
-    default='~/.cache/paddle/dataset/speech/libri',
+    default='/ds2/dataset/speech/libri',
```
and copy the data from `~/.cache/paddle/dataset` to `/ds2/dataset/`
