### ISSUE TITLE
INT32 Failed on paddle.metric.accuracy

### ISSUE THREAD

**Issue by mingxu1067** [PaddlePaddle/Paddle#42845]
### bug描述 Describe the Bug

`paddle.metric.accuracy` fails when `dtype` of `label` is `int32`, even [documents](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/metric/accuracy_cn.html) said it is allowed to be.

Reproduce Python Script:
```python
import paddle

predictions = paddle.to_tensor([[0.2, 0.1, 0.4, 0.1, 0.1], [0.2, 0.3, 0.1, 0.15, 0.25]], dtype='float32')

print("Run with Label INT64")
label_int64 = paddle.to_tensor([[2], [0]], dtype="int64")
result = paddle.metric.accuracy(input=predictions, label=label_int64, k=1)
print(result)
print("INT64 Test Done\n")

print("Run with Label INT32")
label_int32 = paddle.to_tensor([[2], [0]], dtype="int32")
result = paddle.metric.accuracy(input=predictions, label=label_int32, k=1)
print(result)
print("INT32 Test Done\n")
```

Error Message:
* v2.3.0
> * Docker image: paddlepaddle/paddle:2.3.0
> * log
```shell
Run with Label INT64
Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [0.50000000])
INT64 Test Done

Run with Label INT32
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    result = paddle.metric.accuracy(input=predictions, label=label_int32, k=1)
  File "/usr/local/lib/python3.7/dist-packages/paddle/metric/metrics.py", line 802, in accuracy
    total)
ValueError: (InvalidArgument) The type of data we are trying to retrieve does not match the type of data currently contained in the container.
  [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():5 != paddle::experimental::CppTypeToDataType<T>::Type():7.] (at /paddle/paddle/phi/core/dense_tensor.cc:137)
  [operator < accuracy > error]
```

* v2.2.2
> * Docker image: paddlepaddle/paddle:2.2.2
> * log
```shell
Run with Label INT64
Tensor(shape=[1], dtype=float32, place=CPUPlace, stop_gradient=True,
       [0.50000000])
INT64 Test Done

Run with Label INT32
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    result = paddle.metric.accuracy(input=predictions, label=label_int32, k=1)
  File "/usr/local/lib/python3.7/dist-packages/paddle/metric/metrics.py", line 802, in accuracy
    total)
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int, but desires to be int64_t.
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at /paddle/paddle/fluid/framework/tensor_impl.h:33)
  [operator < accuracy > error]
```

**Comment by wangxinxin08** [comment]
目前该API只支持INT64的输入，感谢您的反馈，我们评估下是否需要支持INT32的输入

**Comment by mingxu1067** [comment]
那官方的[文件](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/metric/accuracy_cn.html)可以考慮先移除INT32的相關訊息，這樣使用者比較不易混淆
> label (Tensor)-数据类型为int64，**int32**。输入为数据集的标签。shape为 [sample_number, 1] 。

**Comment by wangxinxin08** [comment]
收到，感谢反馈
