### ISSUE TITLE
高阶微分

### ISSUE THREAD

**Issue by tianshao1992** [PaddlePaddle/Paddle#42867]
### bug描述 Describe the Bug

import paddle
import numpy as np
from paddle.autograd import jacobian, hessian
from paddle.fluid.dygraph import grad

x = paddle.ones(shape=[1], dtype='float32') * 2 * np.pi
x.stop_gradient = False

y = paddle.sin(x)
dydx = grad(y, x, create_graph=True, retain_graph=True)[0]
print(dydx)
dy2dx2 = grad(dydx, x, create_graph=False, retain_graph=True)[0]
print(dy2dx2)

报错如下：
'''Traceback (most recent call last):
File "F:\pycharm\Physics-AI\PINN_InverseDesign_paddle\run_paddle_grad.py", line 13, in
dydx = grad(y, x, create_graph=True, retain_graph=True)[0]
File "", line 2, in grad
File "D:\Programs\Anaconda\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in impl
return wrapped_func(*args, **kwargs)
File "D:\Programs\Anaconda\lib\site-packages\paddle\fluid\framework.py", line 434, in impl
return func(*args, **kwargs)
File "D:\Programs\Anaconda\lib\site-packages\paddle\fluid\dygraph\base.py", line 661, in grad
return core.dygraph_partial_grad(
RuntimeError: (NotFound) The Op sin_grad doesn't have any grad op. If you don't intend calculating higher order derivatives, please set create_graph to False.
[Hint: double_grad_node should not be null.] (at ..\paddle\fluid\imperative\partial_grad_engine.cc:923)'''

### 其他补充信息 Additional Supplementary Information

在本次论文复现挑战赛中，由于需要使用paddle实现高阶梯度计算，具体而言在构造的损失函数中，包括对sin() cos() exp()等算子的高阶梯度计算（需要设置create_graph=True会报错，代码如下），能否帮忙尽快实现下对**上述三种算子的高阶梯度支持**：

import paddle
import numpy as np
from paddle.autograd import jacobian, hessian
from paddle.fluid.dygraph import grad

x = paddle.ones(shape=[1], dtype='float32') * 2 * np.pi
x.stop_gradient = False

y = paddle.sin(x)
dydx = grad(y, x, create_graph=True, retain_graph=True)[0]
print(dydx)
dy2dx2 = grad(dydx, x, create_graph=False, retain_graph=True)[0]
print(dy2dx2)

报错如下：

Traceback (most recent call last):
File "F:\pycharm\Physics-AI\PINN_InverseDesign_paddle\run_paddle_grad.py", line 13, in
dydx = grad(y, x, create_graph=True, retain_graph=True)[0]
File "", line 2, in grad
File "D:\Programs\Anaconda\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in impl
return wrapped_func(*args, **kwargs)
File "D:\Programs\Anaconda\lib\site-packages\paddle\fluid\framework.py", line 434, in impl
return func(*args, **kwargs)
File "D:\Programs\Anaconda\lib\site-packages\paddle\fluid\dygraph\base.py", line 661, in grad
return core.dygraph_partial_grad(
RuntimeError: (NotFound) The Op sin_grad doesn't have any grad op. If you don't intend calculating higher order derivatives, please set create_graph to False.
[Hint: double_grad_node should not be null.] (at ..\paddle\fluid\imperative\partial_grad_engine.cc:923)

**Comment by WenmuZhou** [comment]
您好，我们内部会安排评估一下, 可以先试一下能不能绕过去
