### ISSUE TITLE
使用CPU训练模型时无法超过八线程

### ISSUE THREAD

**Issue by Zero-Tang** [PaddlePaddle/Paddle#42869]
### bug描述 Describe the Bug

我在使用飞桨训练图像分类的时候发现指定超过八个线程时就会报错，内容如下:
```
/home/zerotang/.local/lib/python3.9/site-packages/paddle/fluid/framework.py:1104: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations                 elif dtype == np.bool:
/home/zerotang/.local/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.                    return _methods._mean(a, axis=axis, dtype=dtype,
/home/zerotang/.local/lib/python3.9/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last): 
File "/mnt/h/AI/models-develop/PaddleCV/image_classification/train.py", line 357, in <module>
main()
File "/mnt/h/AI/models-develop/PaddleCV/image_classification/train.py", line 351, in main                                                 train(args)
File "/mnt/h/AI/models-develop/PaddleCV/image_classification/train.py", line 335, in train
validate(args, test_iter, exe, test_prog, test_fetch_list, pass_id, 
File "/mnt/h/AI/models-develop/PaddleCV/image_classification/train.py", line 163, in validate
list(train_epoch_metrics_avg) + list(test_epoch_metrics_avg),
TypeError: 'numpy.float64' object is not iterable 
```
我使用的训练脚本来自[PaddleCV](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/image_classification)的`train.py`文件，调用参数如下：
```shell
export CPU_NUM=10
python3 train.py --data_dir sample --class_dim 1001 --num_epochs 1 --print_step 1 --use_gpu False
```
其中sample是存放图像的目录。
若将`CPU_NUM`环境变量调整到8或者更小，则不会报错。
在Windows上调整`CPU_NUM`环境变量时，应当用如下命令：
```Cmd
set CPU_NUM=10
```
训练图像源来自[Image-Net](https://image-net.org/)的"downsampled image data", 8x8的图像训练集。
![](https://user-images.githubusercontent.com/37060901/147654452-23dbe9a0-5582-4af3-96b6-9258873b43b3.PNG)
可以用以下python脚本提取图像：
```Python
import pickle
import math
import os
from PIL import Image

def unpickle(file):
    with open(file,'rb') as fo:
        pickled_dict=pickle.load(fo)
    return pickled_dict

def transcript(file,prefix,size,output_dir=''):
    pickle_dict=unpickle(file)
    data=pickle_dict["data"]
    labels=pickle_dict["labels"]
    assert len(data)==len(labels)
    nlen=math.ceil(math.log(len(data),10))
    batch_list=""
    for i in range(len(data)):
        fx,fy=size
        assert fx*fy*3==len(data[i])
        file_path=os.path.join(output_dir,prefix+str(i).zfill(nlen)+'.jpg')
        with Image.new('RGB',(fx,fy)) as temp_img:
            for x in range(fx):
                for y in range(fy):
                    index=x*fx+y
                    r=data[i][index]
                    g=data[i][index+fx*fy]
                    b=data[i][index+fx*fy*2]
                    temp_img.putpixel((x,y),(r,g,b))
        temp_img.save(file_path,'jpeg')
        batch_list+=file_path+" "+str(labels[i])+"\n"
    return batch_list

train_list=open("train_list.txt","w")
for i in range(1,10):
    try:
        os.mkdir("batch_n"+str(i))
    except OSError:
        pass
    print("Extracting training data batch "+str(i)+"...")
    listing=transcript('train_data_batch_'+str(i),'batch_n'+str(i),(8,8),'batch_n'+str(i))
    train_list.write(listing)
train_list.close()
val_list=open("val_list.txt","w")
try:
    os.mkdir("val")
except OSError:
    pass
print("Extracting validation data batch...")
listing=transcript('val_data','val',(8,8),'val')
val_list.write(listing)
val_list.close()
print("Extraction completed...")
```

### 其他补充信息 Additional Supplementary Information

在以下平台上均复现该错误：
- Debian 11 (Bullseye) on Windows Subsystem for Linux 1, Windows 10 Enterprise LTSC 2021。Python版本为3.9.2。
- CentOS Stream 8，在docker里使用Paddle。
- Windows 7 x64 Enterprise SP1。Python版本为3.8.10。

所用的Paddle版本为2.3.0

**Comment by WenmuZhou** [comment]
你好，看起来是那边代码的问题，在这里提问会有对应的同学解答的 https://github.com/PaddlePaddle/models/issues 。另外，分类任务，现在建议使用PaddleClas进行
