### ISSUE TITLE
安装后第一次跑报AttributeError: 'WindowsPath' object has no attribute 'tell'

### ISSUE THREAD

**Issue by Daminan0919** [PaddlePaddle/Paddle#42888]
### bug描述 Describe the Bug

应该是执行：model = ErnieModel.from_pretrained('ernie-1.0')时报如下错，windows中的pycharm里跑的，版本2.3.0

[INFO] 2022-05-20 14:36:48,313 [modeling_ernie.py: 267]: get pretrain dir from https://ernie-github.cdn.bcebos.com/model-ernie1.0.1.tar.gz
[INFO] 2022-05-20 14:36:54,157 [modeling_ernie.py: 285]: loading pretrained model from C:\Users\xwhmajun.paddle-ernie-cache\466eabcffd6d6a83ae9cb97dd1a167bd
Traceback (most recent call last):
File "D:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3457, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "", line 1, in
runfile('E:/telecom/telework/python/geekbangpython-master/geekbangpython-master/chinese_match/paddle_baidu.py', wdir='E:/telecom/telework/python/geekbangpython-master/geekbangpython-master/chinese_match')
File "D:\Program Files\PyCharm 2020.1\plugins\python\helpers\pydev_pydev_bundle\pydev_umd.py", line 197, in runfile
pydev_imports.execfile(filename, global_vars, local_vars) # execute the script
File "D:\Program Files\PyCharm 2020.1\plugins\python\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
exec(compile(contents+"\n", file, 'exec'), glob, loc)
File "E:/telecom/telework/python/geekbangpython-master/geekbangpython-master/chinese_match/paddle_baidu.py", line 18, in
model = ErnieModel.from_pretrained('ernie-1.0')
File "D:\anaconda3\lib\site-packages\ernie\ernie\modeling_ernie.py", line 293, in from_pretrained
m = P.load(state_dict_path)
File "C:\Users\xwhmajun\AppData\Roaming\Python\Python39\site-packages\paddle\framework\io.py", line 947, in load
with _open_file_buffer(path, 'rb') as f:
File "C:\Users\xwhmajun\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\io.py", line 111, in _open_file_buffer
return _buffer_reader(path_or_buffer)
File "C:\Users\xwhmajun\AppData\Roaming\Python\Python39\site-packages\paddle\fluid\io.py", line 86, in init
self.initial_tell = self.buffer.tell()
AttributeError: 'WindowsPath' object has no attribute 'tell'

**Comment by wenming2014** [comment]
您好，看下paddle.utils.run_check()能不能跑通，看下是否是安装问题

**Comment by Daminan0919** [comment]
这个早试过了，可以跑通



***@***.***
 
发件人： wangone
发送时间： 2022-05-23 14:40
收件人： PaddlePaddle/Paddle
抄送： Daminan0919; Author
主题： Re: [PaddlePaddle/Paddle] 安装后第一次跑报AttributeError: 'WindowsPath' object has no attribute 'tell' (Issue #42888)
您好，看下paddle.utils.run_check()能不能跑通，看下是否是安装问题

**Comment by Daminan0919** [comment]
跑出来有报：
PaddlePaddle works well on 2 CPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

这个早试过了



***@***.***
 
发件人： wangone
发送时间： 2022-05-23 14:40
收件人： PaddlePaddle/Paddle
抄送： Daminan0919; Author
主题： Re: [PaddlePaddle/Paddle] 安装后第一次跑报AttributeError: 'WindowsPath' object has no attribute 'tell' (Issue #42888)
您好，看下paddle.utils.run_check()能不能跑通，看下是否是安装问题
