### ISSUE TITLE
在ubuntu上paddle不支持gcc-9,gcc-10,gcc-11

### ISSUE THREAD

**Issue by DreamJokerMJ** [PaddlePaddle/Paddle#42891]
bug描述 Describe the Bug
----------------------------------------------------------
#paddlepaddle = 2.3.0(cpu) python=3.8
#gcc=9.4.0，10.3.0，11.2.0
import paddle #这里报错
----------------------------------------------------------
Error: Can not import avx core while this file exists: /usr/local/lib/python3.8/dist-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
File "", line 1, in
File "/usr/local/lib/python3.8/dist-packages/paddle/init.py", line 25, in
from .framework import monkey_patch_variable
File "/usr/local/lib/python3.8/dist-packages/paddle/framework/init.py", line 17, in
from . import random # noqa: F401
File "/usr/local/lib/python3.8/dist-packages/paddle/framework/random.py", line 16, in
import paddle.fluid as fluid
File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/init.py", line 36, in
from . import framework
File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 37, in
from . import core
File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/core.py", line 298, in
raise e
File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/core.py", line 256, in
from . import core_avx
ImportError: /usr/local/lib/python3.8/dist-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
----------------------------------------------------------------
其他补充信息 Additional Supplementary Information
我使用的VMware中的ubuntu22.04 LSTM，在其中使用docker，根据官方文档使用docker镜像部署paddleOCR是可以的，docker镜像环境为：Linux 6e4f888db950 5.15.0-27-generic #28-Ubuntu gcc version 10.2.1 20210110 (Debian 10.2.1-6) python3.9

**Comment by wenming2014** [comment]
您好，应该是linux版本的问题，相同问题见https://github.com/PaddlePaddle/Paddle/issues/36801

**Comment by jzhang533** [comment]
初步定位，当运行时的环境，是glibc 2.34时，该问题会出现。
@pangyoki @XieYunshen is working on this.

**Comment by spike-xiong** [comment]
glibc  2.35 有同样报错

> 初步定位，当运行时的环境，是glibc 2.34时，该问题会出现。 @pangyoki @XieYunshen is working on this.
