### ISSUE TITLE
transpose_op also have a gradient test problem

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/Paddle#4290]
```
[06:19:29][Step 1/1] 161/178 Test #161: test_transpose_op ...................***Failed    2.45 sec
[06:19:29][Step 1/1] ......F.....
[06:19:29][Step 1/1] ======================================================================
[06:19:29][Step 1/1] FAIL: test_check_grad (__main__.TestCase3)
[06:19:29][Step 1/1] ----------------------------------------------------------------------
[06:19:29][Step 1/1] Traceback (most recent call last):
[06:19:29][Step 1/1]   File "test_transpose_op.py", line 18, in test_check_grad
[06:19:29][Step 1/1]     self.check_grad(['X'], 'Out')
[06:19:29][Step 1/1]   File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 284, in check_grad
[06:19:29][Step 1/1]     "Gradient Check On %s" % str(cpu_place))
[06:19:29][Step 1/1]   File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 242, in __assert_is_close
[06:19:29][Step 1/1]     self.assertLessEqual(max_diff, max_relative_error, err_msg())
[06:19:29][Step 1/1] AssertionError: Gradient Check On CPUPlace Variable X@GRAD max gradient diff 0.005153 over limit 0.005000, the first error element is 1
[06:19:29][Step 1/1] 
[06:19:29][Step 1/1] ----------------------------------------------------------------------
[06:19:29][Step 1/1] Ran 12 tests in 1.476s
```

**Comment by chengduoZH** [comment]
There's no problem now. Can I close this issue?

**Comment by hedaoyuan** [comment]
Yes, it can be closed.
