### ISSUE TITLE
使用 exe.run(fetch_var_name) 提取期望层的计算输出一直报错

### ISSUE THREAD

**Issue by xiangyubo** [PaddlePaddle/Paddle#42990]
### 请提出你的问题 Please ask your question

我想使用预训练好的图像分类模型来作为图片特征的抽取器。以 InceptionV3为例子。我下载了官网上的预训练模型。但是现在模型运行输出直接是1000分类，而不是2048维度的特征。我看 executor.run 这个API有个参数是 fetch_var_name。字面理解应该是就是把参数的名字传入，返回推理时候这个参数的值。但我写了个简单的代码测试报错。
我用的是 Paddle 2.0.2
以下是我的测试代码

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import paddle
import numpy as np

paddle.enable_static()

# 构建模型
startup_prog = paddle.static.default_startup_program()
exe = paddle.static.Executor(paddle.CPUPlace())
exe.run(startup_prog)

# 保存预测模型
path_prefix = "./inceptionv3-model/inference"

[inference_program, feed_target_names, fetch_targets] = (
    paddle.static.load_inference_model(path_prefix, exe))
print(feed_target_names)
print(fetch_targets[0].name)

tensor_img = np.array(np.random.random((1, 3, 299, 299)), dtype=np.float32)
results = exe.run(inference_program,
              feed={feed_target_names[0]: tensor_img},
              fetch_var_name=fetch_targets[0].name)
print(results)
```

**Comment by tianxin1860** [comment]
具体报了什么错呢？另外 `fetch_targets[0].name` 这个变脸打印出来是什么？

**Comment by xiangyubo** [comment]
> 

打印出来的变量名看着很正常，是 softmax_1.tmp_0
下面是报错，我就有点懵了
```
Traceback (most recent call last):
  File "D:/python-code/baidu/aipe/iocr-training/tests/paddle_infer.py", line 25, in <module>
    fetch_var_name=fetch_targets[0].name)
  File "D:\python36\lib\site-packages\paddle\fluid\executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "D:\python36\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\python36\lib\site-packages\paddle\fluid\executor.py", line 1108, in run
    return_merged=return_merged)
  File "D:\python36\lib\site-packages\paddle\fluid\executor.py", line 1238, in _run_impl
    use_program_cache=use_program_cache)
  File "D:\python36\lib\site-packages\paddle\fluid\executor.py", line 1313, in _run_program
    fetch_var_name=fetch_var_name)
  File "D:\python36\lib\site-packages\paddle\fluid\executor.py", line 638, in _add_feed_fetch_ops
    if not has_fetch_operators(global_block, fetch_list, fetch_var_name):
  File "D:\python36\lib\site-packages\paddle\fluid\executor.py", line 314, in has_fetch_operators
    assert op.desc.output('Out')[0] == fetch_holder_name
AssertionError

Process finished with exit code 1

```

**Comment by tianxin1860** [comment]
试试别的变量名呢？都无法正常 fetch 出来？

**Comment by xiangyubo** [comment]
> 

这就是最后一个变量的名字，如果使用 fetch_var_list 的方式就能正常出结果。别的变量我也试过一个，也不行

**Comment by tianxin1860** [comment]
那就先使用 fetch_var_list 可以满足需求么？

**Comment by xiangyubo** [comment]
> 那就先使用 fetch_var_list 可以满足需求么？

我没找到合适的用法，因为我想获取倒数第二三层，而这个变量不知道怎么从加载的模型里获取，load_inference_model 返回的 fetch_targets 没有包含倒数第二三层的结果。这个预训练模型我是直接从 github 上下载的

**Comment by xiangyubo** [comment]
> 那就先使用 fetch_var_list 可以满足需求么？

再者，fetch_var_name 不就是应该输入变量名字的字符串，然后返回变量值么。。

**Comment by xiangyubo** [comment]
> 那就先使用 fetch_var_list 可以满足需求么？

我刚刚又测试了一下，用下面的代码可以获取到变量
```
dropout = inference_program.global_block().var('dropout_1.tmp_0')
print(dropout.name)
```
但是，我通过 fetch_var_list 来获取 dropout 的结果还是会报错

**Comment by xiangyubo** [comment]
> 那就先使用 fetch_var_list 可以满足需求么？

另外一种方式，我找到模型结构的源文件，加载参数，修改输出为导数第二层计算结果，再保存。但是现在的预训练参数名字和动态图网络结构里的参数名字又对不上。

**Comment by tianxin1860** [comment]
保存的 inference_program.global_block().var('dropout_1.tmp_0') 按理说应该是没有 dropout op 的，因为 inference 的时候会裁剪掉无用的 op, 确定你的 inference_program 有 dropout_1.tmp_0 这个参数么？

**Comment by xiangyubo** [comment]
这个是模型地址
https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/inference/InceptionV3_infer.tar
从 github 的 [paddle 模型库](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/algorithm_introduction/ImageNet_models.md)里下载的。

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import paddle
import numpy as np
import time

paddle.enable_static()

# 构建模型
startup_prog = paddle.static.default_startup_program()
exe = paddle.static.Executor(paddle.CPUPlace())
exe.run(startup_prog)

# 保存预测模型
path_prefix = "./inceptionv3-model/inference"

[inference_program, feed_target_names, fetch_targets] = (
    paddle.static.load_inference_model(path_prefix, exe))
print(feed_target_names)
print(fetch_targets[0].name)
# 想使用 pool 之后的输出，作为图片提取的特征
dropout = inference_program.global_block().var('pool2d_13.tmp_0')
print(dropout.name)

tensor_img = np.array(np.random.random((1, 3, 299, 299)), dtype=np.float32)
t0 = time.time()
results = exe.run(inference_program,
              feed={feed_target_names[0]: tensor_img},
              fetch_var_name=dropout.name)     # 这里会报错
# 但是，我换成 fetch_list=[dropout] 也还是报错
# 甚至我用 fetch_var_name=fetch_targets[0].name 都报错...
print("cost:{}".format(time.time() - t0))
```

**Comment by tianxin1860** [comment]
改成这样就好了，采用 fetch_list 取回中间输出结果:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/6829601/170644485-68e144c0-2e08-4e1c-b574-c3bbc540d6ca.png">
