### ISSUE TITLE
feed data格式错误

### ISSUE THREAD

**Issue by ckarying** [PaddlePaddle/Paddle#4301]
```python
def train():
    def train_reader():
        train_x = [[1, 2], [1, 4], [3, 4], [5,4]]
        train_y = [[1,2], [2,3], [4,5], [8,9]]
        train_z = [1, 0, 0, 0, 1]
        def reader():
            for i in xrange(4):
                yield train_x[i],train_z[i]
        return reader

    tmp = train_reader()
    for i in tmp():
        print i 
   paddle.init(use_gpu=with_gpu, trainer_count=3)
    ## query part
    query_id = paddle.layer.data(
        name='query_id',
        type=paddle.data_type.integer_value_sequence(13))
    query_emb = paddle.layer.embedding(input=query_id, size=12)
    ## label part
    click = paddle.layer.data(name='label',
                              type=paddle.data_type.integer_value(2))
    ## label
    inference = paddle.layer.fc(input=query_emb, size=2, act=paddle.activation.Softmax())
    ## cost
    cost = paddle.layer.classification_cost(
        input=inference, label=click)
    params = paddle.parameters.create(cost)
    optimizer = paddle.optimizer.AdaGrad()
    trainer = paddle.trainer.SGD(
        cost=cost, parameters=params, update_equation=optimizer)

    def __event_handler__(event):
        if isinstance(event, paddle.event.EndIteration):
            pass

    feeding_index = {'query_id':0, 'label':1}

    print feeding_index

    trainer.train(reader=train_reader(),
                  feeding=feeding_index,
                  event_handler=__event_handler__,
                  num_passes=1)
train()

```
照着demo改的，但是run一直出错
```text
([1, 2], 1)
([1, 4], 0)
([3, 4], 0)
([5, 4], 0)
I0921 17:29:05.504608 29439 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=3
I0921 17:29:05.512742 29439 GradientMachine.cpp:85] Initing parameters..
I0921 17:29:05.512795 29439 GradientMachine.cpp:92] Init parameters done.
{'query_id': 0, 'label': 1}
Traceback (most recent call last):
  File "train.py", line 64, in <module>
    train()
  File "train.py", line 62, in train
    num_passes=1)
  File "/home/work/wangdong/paddlev2/python27/lib/python2.7/site-packages/paddle/v2/trainer.py", line 153, in train
    in_args = feeder(data_batch)
  File "/home/work/wangdong/paddlev2/python27/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 278, in __call__
    return self.convert(dat, argument)
  File "/home/work/wangdong/paddlev2/python27/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 134, in convert
    return DataProviderConverter.convert(self, reorder_data(dat), argument)
  File "/home/work/wangdong/paddlev2/python27/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 130, in reorder_data
    reorder.append(each[self.feeding[name]])
TypeError: 'int' object has no attribute '__getitem__'
```

**Comment by lcy-seso** [comment]
请先参考此文档了解一下数据的格式：
http://doc.paddlepaddle.org/develop/doc_cn/getstarted/concepts/use_concepts_cn.html

**Comment by ckarying** [comment]
看了demo，但还是没有找到问题，demo是
对于分类问题，能不能也写一个简单的demo，我感觉是feed的data格式有问题，但是一直找不到

**Comment by lcy-seso** [comment]
https://github.com/PaddlePaddle/models/tree/develop/text_classification models下有各种例子。请先参考。

**Comment by daiwk** [comment]
看了下，两个修改点

- embedding出来的是一个sequence，需要变成非sequence
```python
    seq_pool = paddle.layer.pooling(
        input=query_emb, pooling_type=paddle.pooling.Max())
    ## label part
    click = paddle.layer.data(name='label',
                              type=paddle.data_type.integer_value(2))
    ## label
    inference = paddle.layer.fc(input=seq_pool, size=2, act=paddle.activation.Softmax())
```
- 把train_reader外面套一个batch..(我也不太清楚为啥一定要这样)
```python
    tmp_2 = paddle.batch(
                paddle.reader.shuffle(
                        train_reader(), buf_size=500),
                        batch_size=5)
    trainer.train(reader=tmp_2,
                  feeding=feeding_index,
                  event_handler=__event_handler__,
                  num_passes=1)
```

**Comment by chengduoZH** [comment]
> (我也不太清楚为啥一定要这样)
模型训练过程中，数据是以batch（比如这里的 5 个样本为一个batch）的是方式喂给模型的
