### ISSUE TITLE
pip安装成功后，import paddle报错：Downgrade the protobuf package to 3.20.x or lower

### ISSUE THREAD

**Issue by holyseven** [PaddlePaddle/Paddle#43033]
### bug描述 Describe the Bug

```bash

conda create -n sandbox python=3.7

pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
# GPU版本好像也会同样问题。
# python -m pip install paddlepaddle-gpu==2.3.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

python
```

然后import paddle时报错：
```
>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/sandbox/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/opt/conda/envs/sandbox/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/opt/conda/envs/sandbox/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/opt/conda/envs/sandbox/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/opt/conda/envs/sandbox/lib/python3.7/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from .proto import framework_pb2
  File "/opt/conda/envs/sandbox/lib/python3.7/site-packages/paddle/fluid/proto/framework_pb2.py", line 36, in <module>
    type=None),
  File "/opt/conda/envs/sandbox/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```

`pip list`结果：
```
Package            Version
------------------ -----------
astor              0.8.1
certifi            2022.5.18.1
charset-normalizer 2.0.12
decorator          5.1.1
idna               3.3
numpy              1.21.6
opt-einsum         3.3.0
paddle-bfloat      0.1.2
paddlepaddle       2.3.0
Pillow             9.1.1
pip                21.2.2
protobuf           4.21.0
requests           2.27.1
setuptools         61.2.0
six                1.16.0
urllib3            1.26.9
wheel              0.37.1

```

**Comment by yt605155624** [comment]
参考 https://github.com/PaddlePaddle/PaddleSpeech/issues/1970

**Comment by Ligoml** [comment]
这个问题已在develop分支上修复，会随2.3.1版本发布，PR https://github.com/PaddlePaddle/Paddle/pull/43009
详细信息可见https://github.com/PaddlePaddle/Paddle/issues/43052

**Comment by danielbraun89** [comment]
this is high priority
