### ISSUE TITLE
使用paddlex 可视化端 目标检测任务训练模型时报错

### ISSUE THREAD

**Issue by TPF0628** [PaddlePaddle/Paddle#43046]
### 请提出你的问题 Please ask your question

使用paddlex 可视化端 目标检测任务训练模型时报错
This log file path is D:\paddlex_workplace\projects\P0006\T0011\err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
D:\PaddleX_GUI_2.1.0_win10\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "D:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dataloader\dataloader_iter.py", line 213, in _thread_loop
    self._thread_done_event)
  File "D:\PaddleX_GUI_2.1.0_win10\paddle\fluid\dataloader\fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "D:\PaddleX_GUI_2.1.0_win10\paddlex\cv\datasets\voc.py", line 322, in __getitem__
    Decode(to_rgb=False)(sample), Decode(to_rgb=False)(sample_mix)
  File "D:\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 82, in __call__
    sample = self.apply(sample)
  File "D:\PaddleX_GUI_2.1.0_win10\paddlex\cv\transforms\operators.py", line 198, in apply
    sample['image'].shape[:2], dtype=np.float32)
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by zhaocaibei123** [comment]
从错误上看是 sample 是 None，请先检查下脚本
