### ISSUE TITLE
关于安装paddle 2.3.0 版本遇到protobuf 的报错问题

### ISSUE THREAD

**Issue by dingjiaweiww** [PaddlePaddle/Paddle#43050]
### 问题描述 Please describe your issue

问题原因：
protobuf 于 2022.05.26 发布了 4.21 版本，如果您环境中没有 protobuf 的话，默认安装 paddle 时会自动下载最高版本的protobuf 4.21，paddle能安装成功但是 import paddle 会报错，这是由于protobuf 4.21 为不兼容升级，目前 develop 版本的 paddle 已经修复了这个问题（ see https://github.com/PaddlePaddle/Paddle/pull/43009 ），但是发行版依由于已经编包发布所以仍存在这个问题，飞桨会在下个版本2.3.1中解决。
参考:
[Streamlit run with protocbuf error](https://discuss.streamlit.io/t/streamlit-run-with-protocbuf-error/25632)
[TypeError: Descriptors cannot not be created directly](https://discuss.streamlit.io/t/typeerror-descriptors-cannot-not-be-created-directly/25639)

解决办法：

手动降低 protobuf 为 3.x
pip install protobuf==3.20.1

完整报错:
![image](https://user-images.githubusercontent.com/23093488/170646504-445ec0a8-42ea-48ab-bbce-ba2aa4db9247.png)

(py39) C:\Users\Admin>hub install ge2e_fastspeech2_pwgan==1.0.0
Traceback (most recent call last):
  File "f:\anaconda3\envs\py39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "f:\anaconda3\envs\py39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "f:\anaconda3\envs\py39\Scripts\hub.exe\__main__.py", line 4, in <module>
  File "f:\anaconda3\envs\py39\lib\site-packages\paddlehub\__init__.py", line 18, in <module>
    import paddle
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from .proto import framework_pb2
  File "f:\anaconda3\envs\py39\lib\site-packages\paddle\fluid\proto\framework_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "f:\anaconda3\envs\py39\lib\site-packages\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 4. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by dingjiaweiww** [comment]
重复发送，已关
