### ISSUE TITLE
Parl框架AttributeError: 'Agent' object has no attribute 'pred_program'

### ISSUE THREAD

**Issue by HarryUP-rhy** [PaddlePaddle/Paddle#43070]
### bug描述 Describe the Bug

https://gist.github.com/RenHyz/5b6b841545a5cc825a360fb6da78db33
代码如上，在调用Agent时报错没有预测程序
具体报错信息如下：
E:\RhyAnaconda\envs\paddle2.2\python.exe E:/LearnPad/learn_pad_pycharm/test_trading/tst_3_parl.py
[05-29 10:40:27 MainThread @logger.py:242] Argv: E:/LearnPad/learn_pad_pycharm/test_trading/tst_3_parl.py
[05-29 10:40:28 MainThread @utils.py:73] paddlepaddle version: 2.2.2.
Traceback (most recent call last):
  File "E:/LearnPad/learn_pad_pycharm/test_trading/tst_3_parl.py", line 160, in <module>
    action = agent.sample(obs)
  File "E:/LearnPad/learn_pad_pycharm/test_trading/tst_3_parl.py", line 72, in sample
    self.pred_program,
AttributeError: 'Agent' object has no attribute 'pred_program'
[05-29 10:40:29 MainThread @tst_3_parl.py:152] obs_dim10, act_dim2

进程已结束，退出代码为 1

版本信息：
paddle2.2
parl2.0.3
python3.7

**Comment by MingMingShangTian** [comment]
你好，该问题参考  https://github.com/PaddlePaddle/PARL/issues/867
