### ISSUE TITLE
【打包后出问题】 OSError: could not get source code

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/Paddle#43092]
### bug描述 Describe the Bug

环境：
```
win10
paddlepaddle-gpu          2.2.2
```

示例代码 (这是Paddle官方在解释[paddle.jit.save](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/jit/save_cn.html#daimashili)时给出的示例代码)`demo.py`：
```python
# example 1: save layer
import numpy as np
import paddle
import paddle.nn as nn
import paddle.optimizer as opt

BATCH_SIZE = 16
BATCH_NUM = 4
EPOCH_NUM = 4

IMAGE_SIZE = 784
CLASS_NUM = 10

# define a random dataset
class RandomDataset(paddle.io.Dataset):
    def __init__(self, num_samples):
        self.num_samples = num_samples

    def __getitem__(self, idx):
        image = np.random.random([IMAGE_SIZE]).astype('float32')
        label = np.random.randint(0, CLASS_NUM - 1, (1, )).astype('int64')
        return image, label

    def __len__(self):
        return self.num_samples

class LinearNet(nn.Layer):
    def __init__(self):
        super(LinearNet, self).__init__()
        self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)

    @paddle.jit.to_static
    def forward(self, x):
        return self._linear(x)

def train(layer, loader, loss_fn, opt):
    for epoch_id in range(EPOCH_NUM):
        for batch_id, (image, label) in enumerate(loader()):
            out = layer(image)
            loss = loss_fn(out, label)
            loss.backward()
            opt.step()
            opt.clear_grad()
            print("Epoch {} batch {}: loss = {}".format(
                epoch_id, batch_id, np.mean(loss.numpy())))

# 1. train & save model.

# create network
layer = LinearNet()
loss_fn = nn.CrossEntropyLoss()
adam = opt.Adam(learning_rate=0.001, parameters=layer.parameters())

# create data loader
dataset = RandomDataset(BATCH_NUM * BATCH_SIZE)
loader = paddle.io.DataLoader(dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    drop_last=True,
    num_workers=2)

# train
train(layer, loader, loss_fn, adam)

# save
path = "example_model/linear"
paddle.jit.save(layer, path)

# example 2: save function
import paddle
from paddle.static import InputSpec


def save_function():
    @paddle.jit.to_static
    def fun(inputs):
        return paddle.tanh(inputs)

    path = 'test_jit_save_load_function_1/func'
    inps = paddle.rand([3, 6])
    origin = fun(inps)

    paddle.jit.save(fun, path)
    load_func = paddle.jit.load(path)

    load_result = load_func(inps)
    print((load_result - origin).abs().max() < 1e-10)

save_function()

```

在VSCode终端运行`demo.py`是没有问题的。

利用`PyInstaller -D demo.py --distpath=./out`打包成`demo.exe`，然后在cmd运行`demo.exe`，会报如下的错：
```
Traceback (most recent call last):
  File "demo.py", line 63, in <module>
  File "demo.py", line 39, in train
  File "paddle\fluid\dygraph\layers.py", line 917, in __call__
    hook_result = forward_post_hook(self, inputs, outputs)
  File "paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    if parallel_helper._is_data_parallel_mode(
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 381, in __call__
    raise e
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 357, in __call__
    *args, **kwargs)
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 427, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 723, in __getitem__
    Wrapper class for the program functions defined by dygraph function.
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 714, in _build_once
    params = list(get_parameters(class_instance).values())
  File "decorator.py", line 232, in fun
  File "paddle\fluid\wrapped_decorator.py", line 25, in __impl__
  File "paddle\fluid\dygraph\base.py", line 51, in __impl__
    if tracer:
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 629, in from_func_spec
    self.startup_program = startup_program
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 140, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 77, in convert_with_cache
    static_func = self._convert(func)
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 104, in _convert
    source_code = func_to_source_code(func)
  File "paddle\fluid\dygraph\dygraph_to_static\utils.py", line 549, in func_to_source_code
    source_code = inspect.getsource(function)
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code
[24812] Failed to execute script 'demo' due to unhandled exception!
```
将`paddlepaddle-gpu 2.2.2`换成`paddlepaddle-gpu 2.3.0`，依然有问题。

请问该如何解决呢？谢谢！

**Comment by geoexploring** [comment]
是Pyinstaller打包软件的问题。

**Comment by geoexploring** [comment]
是`paddle.jit.save`和`paddle.jit.to_static`导致的，

打包PyTorch也会出现类似问题，具体可参考[pytorch #1899](https://github.com/pytorch/vision/issues/1899)和[pyinstaller #5673](https://github.com/pyinstaller/pyinstaller/issues/5673)，

但仍没有找到解决方案，可能需要重写`paddle.jit.save`和`paddle.jit.to_static`，特来请教

**Comment by geoexploring** [comment]
已解决，请参考[pyinstaller #6865](https://github.com/pyinstaller/pyinstaller/issues/6865)

**Comment by Yaman-yagiz** [comment]
It took a long time to solve this error for me, and i tried various solutions on the Internet, and finally found a way to solve the problem, as follows:

Just add a bit of code to the import torch. The module I reported the error is the main file, and the package is also the main file, so I directly added the code to the import torch of the main. My other modules also use import torch, but they don't need to do this. 

`
### 
def script_method(fn, _rcb=None):
    return fn

def script(obj, optimize=True, _frames_up=0, _rcb=None):
    return obj

import torch.jit
script_method1 = torch.jit.script_method
script1 = torch.jit.script_if_tracing
torch.jit.script_method = script_method
torch.jit.script = script
####
`

**Comment by Yaman-yagiz** [comment]
It took a long time to solve this error for me, and i tried various solutions on the Internet, and finally found a way to solve the problem, as follows:

Just add a bit of code to the import torch. The module I reported the error is the main file, and the package is also the main file, so I directly added the code to the import torch of the main. My other modules also use import torch, but they don't need to do this. 

```
def script_method(fn, _rcb=None):
    return fn

def script(obj, optimize=True, _frames_up=0, _rcb=None):
    return obj

import torch.jit
script_method1 = torch.jit.script_method
script1 = torch.jit.script_if_tracing
torch.jit.script_method = script_method
torch.jit.script = script
```

**Comment by wangyexiang** [comment]
> 已解决，请参考[pyinstaller #6865](https://github.com/pyinstaller/pyinstaller/issues/6865)
请问是怎么解决的，没看懂链接的方法
