### ISSUE TITLE
3090运行nn.Conv2D(3, 16, 3)报错

### ISSUE THREAD

**Issue by wuqi930907** [PaddlePaddle/Paddle#43152]
### 问题描述 Issue Description

代码:
import paddle.nn as nn

nn.Conv2D(3, 16, 3)

log:
W0601 15:46:55.629635 21509 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.2
W0601 15:46:55.633584 21509 device_context.cc:465] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "111.py", line 3, in <module>
    nn.Conv2D(3, 16, 3)
  File "/opt/python3.7/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 656, in __init__
    data_format=data_format)
  File "/opt/python3.7/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "/opt/python3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 422, in create_parameter
    default_initializer)
  File "/opt/python3.7/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/opt/python3.7/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "/opt/python3.7/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 362, in __call__
    stop_gradient=True)
  File "/opt/python3.7/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "/opt/python3.7/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External) CUBLAS error(7).
  [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/fluid/platform/cuda_helper.h:107)

### 版本&环境信息 Version & Environment Information

Paddle version: 2.2.2
Paddle With CUDA: True
OS: Ubuntu 16.04
Python version: 3.7.1
CUDA version: 11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0
cuDNN version: 7.6.5
Nvidia driver version: 460.84

显卡使用的3090，CUDA也曾实验过CUDA11.1，python也用过python3.8，都会报错

**Comment by TingquanGao** [comment]
你好！初步判断是版本过低导致的，建议试下：CUDA 11.2; cuDNN 8.2.1; 驱动 471.41。

另外，也可以尝试运行以下代码，检查一下paddle安装问题：

```python
import paddle
paddle.utils.install_check.run_check()
```

**Comment by wuqi930907** [comment]
@TingquanGao 十分感谢，需要将CUDNN更新到8就可以了
