### ISSUE TITLE
M1 mac安装paddle后import时报错

### ISSUE THREAD

**Issue by xiehuanyi** [PaddlePaddle/Paddle#43188]
### 问题描述 Issue Description

Traceback (most recent call last):
  File "/Volumes/Samsung_T5/PycharmProjects/Sign-GPT/test.py", line 1, in <module>
    import paddle
  File "/Volumes/Samsung_T5/Resume-master/Sign-GPT/lib/python3.9/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/Volumes/Samsung_T5/Resume-master/Sign-GPT/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/Volumes/Samsung_T5/Resume-master/Sign-GPT/lib/python3.9/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/Volumes/Samsung_T5/Resume-master/Sign-GPT/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/Volumes/Samsung_T5/Resume-master/Sign-GPT/lib/python3.9/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from .proto import framework_pb2
  File "/Volumes/Samsung_T5/Resume-master/Sign-GPT/lib/python3.9/site-packages/paddle/fluid/proto/framework_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/Volumes/Samsung_T5/Resume-master/Sign-GPT/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: None
Paddle With CUDA: None

OS: macOs 12.4
Python version: 3.9.2

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

**Comment by xiehuanyi** [comment]
官网上说安装unrar，但是我没法安装
Warning: No available formula with the name "unrar". Did you mean unar?
==> Searching for similarly named formulae...
This similarly named formula was found:
unar
To install it, run:
  brew install unar
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by SigureMo** [comment]
见 #43052

另外报错信息也很清楚了

> Downgrade the protobuf package to 3.20.x or lower.

降级到 3.20 及以下即可

``` bash
pip install protobuf==3.20.1
```

**Comment by SigureMo** [comment]
> 官网上说安装unrar，但是我没法安装

我怎么记得自行编译才需要安装这个，如果一定要安装的话，现在 Homebrew 可以通过安装 rar 一并安装 rar 和 unrar

``` bash
brew install rar
```
