### ISSUE TITLE
CUDA 10.2  Paddle depends on is not configured correctly

### ISSUE THREAD

**Issue by JamesYuCN** [PaddlePaddle/Paddle#43197]
### 问题描述 Issue Description

paddle: 2.3 和 develope
cuda： 10.2 

 **按照安装说明、网上找各种攻略折腾，运行paddle.utils.run_check() 都报错：** 

    return self._run_program(
  File "C:\Users\Zheng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\paddle\fluid\executor.py", line 1612, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cublas64_102.dll;cublas64_10.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:303)

 **怎么折腾都没有用，但是我后来安装了PyTorch,先Import torch,竟然正常了，但是不Import ,还是继续上面的错误，求助。。。** 
torch                 1.8.2+cu102
torchaudio            0.8.2
torchvision           0.9.2+cu102

Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0604 20:29:07.488788  8088 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 10.2
W0604 20:29:07.488788  8088 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**直接Import paddle 继续报错**
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0604 20:54:30.067052   468 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 10.2
W0604 20:54:30.067052   468 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Zheng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\paddle\utils\install_check.py", line 266, in run_check

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 0.0.0 (2.3 也测试过，不行）
Paddle With CUDA: True

CPU:Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
GPU: NVIDIA GeForce GTX 1060 6GB NVIDIA-SMI 512.96       Driver Version: 512.96       CUDA Version: 11.6
deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.6, CUDA Runtime Version = 10.2, NumDevs = 1, Device0 = NVIDIA GeForce GTX 1060 6GB
Result = PASS

OS: Windows 10
Python version: 3.9.13

CUDA version: 10.2.89
cuDNN version: 7.6.5
Nvidia driver version: 512.96
****************************************

**Comment by JamesYuCN** [comment]
I copy  Python39\site-packages\torch\lib to pddle\libs  , It's OK!

Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0604 22:46:25.457581  5436 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 10.2
W0604 22:46:25.660684  5436 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
