### ISSUE TITLE
paddle.nn.LSTM 调用to函数报错

### ISSUE THREAD

**Issue by x54-729** [PaddlePaddle/Paddle#43192]
### bug描述 Describe the Bug

您好，我在使用paddle时遇到一个问题，就是LSTM模型调用to函数会报错，代码如下：
```python
import paddle
model = paddle.nn.LSTM(16, 32)
model.to("cpu") # 无论是 cpu 还是 gpu 都会报错
```
报错信息为：
```bash
W0604 05:53:31.999567  4012 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 11.2
W0604 05:53:32.014454  4012 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    model.to("cpu")
  File "/remote-home/shxing/anaconda3/envs/fnlp-paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1567, in to
    include_sublayers=True)
  File "/remote-home/shxing/anaconda3/envs/fnlp-paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1687, in _to_impl
    self._apply(transform, device, dtype, blocking, include_sublayers)
  File "/remote-home/shxing/anaconda3/envs/fnlp-paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1585, in _apply
    self._buffers[key] = func(buf, device, dtype, blocking)
  File "/remote-home/shxing/anaconda3/envs/fnlp-paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1681, in transform
    dst_tensor._share_data_with(src_tensor)
RuntimeError: (PreconditionNotMet) Tensor holds no memory. Call Tensor::mutable_data firstly.
  [Hint: holder_ should not be null.] (at /paddle/paddle/phi/core/dense_tensor_impl.cc:46)
```
在Linear等模型上没有这个问题，或者如果先传入张量前向传播后也不会出现报错。请问这个问题是由于什么引起的呢？还是我的环境及版本存在某些问题？我安装的为最新2.3版本的paddle，cuda11.2，显卡设备为1080ti。
非常感谢！

**Comment by joey12300** [comment]
你好，感谢提供报错信息~这里已经提了一个修复的PR：https://github.com/PaddlePaddle/Paddle/pull/43277

**Comment by x54-729** [comment]
> 你好，感谢提供报错信息~这里已经提了一个修复的PR：#43277

十分感谢，辛苦了！
