### ISSUE TITLE
test_poisson_op UT failure

### ISSUE THREAD

**Issue by leo0519** [PaddlePaddle/Paddle#43208]
### bug描述 Describe the Bug

- 版本、环境信息：
    1. PaddlePaddle版本：2.3.0
    2. CPU/GPU：A100
    3. Docker：paddlepaddle/paddle:2.3.0-gpu-cuda11.2-cudnn8
    4. Python版本号：3.7
    5. 显存信息

```bash
$ python3.7 tools/summary_env.py
****************************************
Paddle version: 2.3.0
Paddle With CUDA: True

OS: Ubuntu 18.04
Python version: 3.7.12

CUDA version: 11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
cuDNN version: None.None.None
Nvidia driver version: 470.57.02
****************************************
```

- 复现步骤

```bash
$ echo "
FROM paddlepaddle/paddle:2.3.0-gpu-cuda11.2-cudnn8

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && apt install python3 python3-pip -y

RUN git clone https://github.com/PaddlePaddle/Paddle.git -b v2.3.0 && \
    sed -i 's/BRPC_DEPS brpc/BRPC_DEPS brpc ssl crypto/g' Paddle/paddle/fluid/framework/CMakeLists.txt

RUN pip install --upgrade pip && \
    pip install -r Paddle/python/requirements.txt

RUN cd Paddle && \
    mkdir -p build && \
    cd build && \
    cmake .. \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_FLAGS="-t0" \
    -DCUDA_ARCH_NAME=Manual \
    -DCUDA_ARCH_BIN="80" \
    -DWITH_INCREMENTAL_COVERAGE=OFF \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DWITH_DISTRIBUTE=OFF \
    -DWITH_COVERAGE=OFF \
    -DWITH_TENSORRT=OFF \
    -DWITH_TESTING=ON \
    -DWITH_CONTRIB=OFF \
    -DWITH_ROCM=OFF \
    -DWITH_RCCL=OFF \
    -DWITH_STRIP=ON \
    -DWITH_MKL=OFF \
    -DWITH_AVX=OFF \
    -DWITH_GPU=ON \
    -DWITH_PYTHON=ON \
    -DPY_VERSION=3.7

RUN cd Paddle/build && make -j`nproc`
" > Dockerfile
$ docker build -t paddle .
$ docker run -it --rm --gpus all paddle bash -c 'set -xe; cd Paddle/build; ctest -R test_poisson_op --output-on-failure'
```

-问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
`test_poisson_op` failed on A100 (also failed on V100). The error log is as follow

```bash
+ cd Paddle/build
+ ctest -R test_poisson_op --output-on-failure
Test project /home/Paddle/build
    Start 1059: test_poisson_op
1/1 Test #1059: test_poisson_op ..................***Failed    6.94 sec
W0605 05:08:49.972330     9 init.cc:285] AVX is available, Please re-compile on local machine
W0605 05:08:50.630681     9 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.2
W0605 05:08:50.632890     9 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.
Hint: Your machine support AVX, but the installed paddlepaddle doesn't have avx core. Hence, no-avx core with worse preformance will be imported.
If you like, you could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' to get better performance.
The original error is: cannot import name 'core_avx' from 'paddle.fluid' (/home/Paddle/build/python/paddle/fluid/__init__.py)
/home/Paddle/build/python/paddle/profiler/profiler_statistic.py:1321: DeprecationWarning: invalid escape sequence \(
  kernel_name_pattern = re.compile('(.+?)(<.*>)(\(.*\))')
/home/Paddle/build/python/paddle/tensor/manipulation.py:1769: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (repeat_times.ndim == 1,
/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py:442: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.dtype(np.bool)
test_poisson_op failed
 ....F..
======================================================================
FAIL: test_check_output (test_poisson_op.TestPoissonOp1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_poisson_op.py", line 64, in test_check_output
    self.check_output_customized(self.verify_output)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1762, in check_output_customized
    checker(outs)
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_poisson_op.py", line 61, in verify_output
    "actual: {}, expected: {}".format(hist, prob))
AssertionError: False is not true : actual: [0.03761482 0.06311131 0.09003544 0.11246204 0.12530518 0.12517738
 0.11393547 0.09486961 0.07269478 0.05177879 0.03515244], expected: [0.03783327480207071, 0.06305545800345118, 0.09007922571921599, 0.11259903214901998, 0.1251100357211333, 0.1251100357211333, 0.11373639611012118, 0.09478033009176766, 0.07290794622443666, 0.05207710444602619, 0.03471806963068413]

----------------------------------------------------------------------
Ran 7 tests in 4.405s

FAILED (failures=1)



0% tests passed, 1 tests failed out of 1

Total Test time (real) =   7.00 sec

The following tests FAILED:
        1059 - test_poisson_op (Failed)
Errors while running CTest
```

**Comment by zhwesky2010** [comment]
@leo0519 你好，已提PR修复，预计 https://github.com/PaddlePaddle/Paddle/pull/43315

**Comment by leo0519** [comment]
@zhouwei25 謝謝，另外想請問，為何 Paddle-CI poisson UT 會通過，但在 local (Paddle docker) 上跑卻無法通過呢？
poisson OP 底層是透過 curand_poisson 生成資料，但我實驗過 CUDA=11.2/10.2 皆會失敗 (2.3.0 無 CUDA 10.1 版本的 docker)。
能否提供 Paddle-CI 使用的 docker 讓我做驗證呢？

**Comment by zhwesky2010** [comment]
> @zhouwei25 謝謝，另外想請問，為何 Paddle-CI poisson UT 會通過，但在 local (Paddle docker) 上跑卻無法通過呢？ poisson OP 底層是透過 curand_poisson 生成資料，但我實驗過 CUDA=11.2/10.2 皆會失敗 (2.3.0 無 CUDA 10.1 版本的 docker)。 能否提供 Paddle-CI 使用的 docker 讓我做驗證呢？

https://hub.docker.com/r/paddlepaddle/paddle/tags

**Comment by leo0519** [comment]
修復的 PR 已合併至 develop
