### ISSUE TITLE
test_elementwise_div_op failed on A100

### ISSUE THREAD

**Issue by leo0519** [PaddlePaddle/Paddle#43262]
### bug描述 Describe the Bug

- 版本、环境信息：
    1. PaddlePaddle版本：2.3.0
    2. CPU/GPU：A100
    3. Docker：paddlepaddle/paddle:2.3.0-gpu-cuda11.2-cudnn8
    4. Python版本号：3.7
    5. 显存信息

```bash
$ python3.7 tools/summary_env.py
****************************************
Paddle version: 2.3.0
Paddle With CUDA: True

OS: Ubuntu 18.04
Python version: 3.7.12

CUDA version: 11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
cuDNN version: None.None.None
Nvidia driver version: 470.57.02
****************************************
```

- 复现步骤

```bash
$ echo "
FROM paddlepaddle/paddle:2.3.0-gpu-cuda11.2-cudnn8

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && apt install python3 python3-pip -y

RUN git clone https://github.com/PaddlePaddle/Paddle.git -b v2.3.0 && \
    sed -i 's/BRPC_DEPS brpc/BRPC_DEPS brpc ssl crypto/g' Paddle/paddle/fluid/framework/CMakeLists.txt

RUN pip install --upgrade pip && \
    pip install -r Paddle/python/requirements.txt

RUN cd Paddle && \
    mkdir -p build && \
    cd build && \
    cmake .. \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_FLAGS="-t0" \
    -DCUDA_ARCH_NAME=Manual \
    -DCUDA_ARCH_BIN="80" \
    -DWITH_INCREMENTAL_COVERAGE=OFF \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DWITH_DISTRIBUTE=OFF \
    -DWITH_COVERAGE=OFF \
    -DWITH_TENSORRT=OFF \
    -DWITH_TESTING=ON \
    -DWITH_CONTRIB=OFF \
    -DWITH_ROCM=OFF \
    -DWITH_RCCL=OFF \
    -DWITH_STRIP=ON \
    -DWITH_MKL=OFF \
    -DWITH_AVX=OFF \
    -DWITH_GPU=ON \
    -DWITH_PYTHON=ON \
    -DPY_VERSION=3.7

RUN cd Paddle/build && make -j`nproc`
" > Dockerfile
$ docker build -t paddle .
$ docker run -it --rm --gpus all paddle bash -c 'set -xe; cd Paddle/build; ctest -R test_elementwise_div_op --output-on-failure'
```

-问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段
`test_elementwise_div_op` failed on A100. The error log is as follow.

In elementwise_div_op UT, the BF16 test should have max_relative_error=1.0 (same as FP16 test).
However, such large rtol is irrational, and the reason is the different ways to compute gradient between Paddle and validation.
- The gradients calculated by Paddle follows the math derivative.
- The validation gradients are calculated by f(x+delta) - f(x-delta) / delta / 2, which is inaccurate.

There are two solutions
1. Set the max_relative_error=1.0 for BF16
2. Provide user defined gradients for each test

We need to discuss which one is more acceptable.

```bash
+ cd Paddle/build
+ ctest -R test_elementwise_div_op --output-on-failure
Test project /home/Paddle/build
    Start 629: test_elementwise_div_op
1/1 Test #629: test_elementwise_div_op ..........***Failed   14.97 sec
W0606 10:21:47.579907     9 init.cc:285] AVX is available, Please re-compile on local machine
W0606 10:21:49.228252     9 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.2
W0606 10:21:49.230831     9 gpu_context.cc:306] device: 0, cuDNN Version: 8.1.
Hint: Your machine support AVX, but the installed paddlepaddle doesn't have avx core. Hence, no-avx core with worse preformance will be imported.
If you like, you could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' to get better performance.
The original error is: cannot import name 'core_avx' from 'paddle.fluid' (/home/Paddle/build/python/paddle/fluid/__init__.py)
/home/Paddle/build/python/paddle/profiler/profiler_statistic.py:1321: DeprecationWarning: invalid escape sequence \(
  kernel_name_pattern = re.compile('(.+?)(<.*>)(\(.*\))')
/home/Paddle/build/python/paddle/tensor/manipulation.py:1769: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (repeat_times.ndim == 1,
/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py:442: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.dtype(np.bool)
/home/Paddle/build/python/paddle/fluid/framework.py:1104: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py:1798: ComplexWarning: Casting complex values to real discards the imaginary part
  offset, a.flatten()[offset], b.flatten()[offset])
/home/Paddle/build/python/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /home/Paddle/build/python/paddle/fluid/tests/unittests/test_elementwise_div_op.py:290
The behavior of expression A /= B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A /= B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
test_elementwise_div_op failed
 ...........FFF......................................................
======================================================================
FAIL: test_check_grad_ingore_x (test_elementwise_div_op.TestElementwiseDivOpBF16)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_elementwise_div_op.py", line 93, in test_check_grad_ingore_x
    self.check_grad_with_place(place, ['Y'], 'Out', no_grad_set=set("X"))
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1943, in check_grad_with_place
    "Gradient Check On %s" % str(place))
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1800, in _assert_is_close
    self.assertLessEqual(max_diff, max_relative_error, err_msg())
AssertionError: 0.33406305 not less than or equal to 0.04 : Operator elementwise_div error, Gradient Check On Place(gpu:0) variable Y (shape: (12, 13), dtype: <class 'numpy.uint16'>) max gradient diff 3.340631e-01 over limit 4.000000e-02, the first error element is 6, expected -2.002716e-02, but got -1.708984e-02.

======================================================================
FAIL: test_check_grad_ingore_y (test_elementwise_div_op.TestElementwiseDivOpBF16)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_elementwise_div_op.py", line 97, in test_check_grad_ingore_y
    self.check_grad_with_place(place, ['X'], 'Out', no_grad_set=set('Y'))
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1943, in check_grad_with_place
    "Gradient Check On %s" % str(place))
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1800, in _assert_is_close
    self.assertLessEqual(max_diff, max_relative_error, err_msg())
AssertionError: 0.4384762 not less than or equal to 0.04 : Operator elementwise_div error, Gradient Check On Place(gpu:0) variable X (shape: (12, 13), dtype: <class 'numpy.uint16'>) max gradient diff 4.384762e-01 over limit 4.000000e-02, the first error element is 3, expected 1.002550e-02, but got 8.789062e-03.

======================================================================
FAIL: test_check_grad_normal (test_elementwise_div_op.TestElementwiseDivOpBF16)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/test_elementwise_div_op.py", line 89, in test_check_grad_normal
    self.check_grad_with_place(place, ['X', 'Y'], 'Out')
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1943, in check_grad_with_place
    "Gradient Check On %s" % str(place))
  File "/home/Paddle/build/python/paddle/fluid/tests/unittests/op_test.py", line 1800, in _assert_is_close
    self.assertLessEqual(max_diff, max_relative_error, err_msg())
AssertionError: 0.5847619 not less than or equal to 0.04 : Operator elementwise_div error, Gradient Check On Place(gpu:0) variable X (shape: (12, 13), dtype: <class 'numpy.uint16'>) max gradient diff 5.847619e-01 over limit 4.000000e-02, the first error element is 0, expected 1.001358e-02, but got 7.080078e-03.

----------------------------------------------------------------------
Ran 68 tests in 11.017s

FAILED (failures=3)



0% tests passed, 1 tests failed out of 1

Total Test time (real) =  15.02 sec

The following tests FAILED:
        629 - test_elementwise_div_op (Failed)
Errors while running CTest
```

**Comment by zlsh80826** [comment]
Besides, why we use [a very large relative error](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_elementwise_div_op.py#L289-L302) for FP16? Will it be better to use `user_defined_grads` here?

**Comment by zhiqiu** [comment]
> Besides, why we use [a very large relative error](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_elementwise_div_op.py#L289-L302) for FP16? Will it be better to use `user_defined_grads` here?

I think the problem is that, for BF16 computing, it is not easy to get the `expected result`? It there some good practice in Nvidia?

**Comment by leo0519** [comment]
@zhiqiu 
If using derivative (expected) to compute gradient, the BP16 result has relative error less than 0.01 in comparison to FP32 result.
Hence, the reason to set a large relative error is because of the inaccurate [validation gradients](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/op_test.py#L126-L243).

**Comment by leo0519** [comment]
@zhiqiu 
Paddle computes gradient of elementwise_div operator by the following formula [(reference)](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/funcs/elementwise_functor.h#L109-L121).

- dx = dout / y
- dy = -dout * out / y

where out = x / y

The BF16 result of Paddle has relative error less than 0.005 in comparison to FP32 result of numpy with the above formula,

but the UT use another approach to compute validation gradient [(reference)](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/op_test.py#L126-L243), which is inaccurate and need max_relative_error to be 1.0 to pass.

**Comment by zhiqiu** [comment]
> @zhiqiu Paddle computes gradient of elementwise_div operator by the following formula [(reference)](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/funcs/elementwise_functor.h#L109-L121).
> 
> * dx = dout / y
> * dy = -dout * out / y
> 
> where out = x / y
> 
> The BF16 result of Paddle has relative error less than 0.005 in comparison to FP32 result of numpy with the above formula,
> 
> but the UT use another approach to compute validation gradient [(reference)](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/op_test.py#L126-L243), which is inaccurate and need max_relative_error to be 1.0 to pass.

Thanks, the UT uses `numeric method`, and the above formula is `analytic method`. We will discuss if we need to use `analytic method` for low precision UT. The problem is that if we use `analytic method`, we need to calculate the gradient by ourself when writing UT.

**Comment by jeng1220** [comment]
@zhiqiu ,
Please take a look at PR #43536.
@leo0519  has fixed this bug.

**Comment by leo0519** [comment]
The PR is already merged.
Close the issue.
