### ISSUE TITLE
单机多卡时不允许存在forward外的变量，否则backward报错

### ISSUE THREAD

**Issue by jesiws** [PaddlePaddle/Paddle#43362]
### 问题描述 Please describe your issue

目前基本定位到问题为报错信息中提示的Using model parameters outside of forward function，但是在单机单卡的时候使用forward外的变量是可以训练的，单机多卡报以下错误信息，这是bug还是有特殊的考虑呢？
## 报错信息
```
Traceback (most recent call last):
  File "train.py", line 811, in <module>
    train(args)
  File "train.py", line 380, in train
    train_loss.backward()
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 249, in backward
    framework._dygraph_tracer())
RuntimeError: (PreconditionNotMet) Error happened, when parameter[204][linear_73.b_0@GRAD] has been ready before. Please set find_unused_parameters=True to traverse backward graph in each step to prepare reduce in advance. If you have set, there may be several reasons for this error: 1) In multiple reentrant backward phase, some parameters are reused.2) Using model parameters outside of forward function. Please make sure that model parameters are not shared in concurrent forward-backward passes.
  [Hint: Expected has_marked_unused_vars_ == false, but received has_marked_unused_vars_:1 != false:0.] (at /paddle/paddle/fluid/imperative/reducer.cc:669)
```
## python
代码基本逻辑如下：
```
class Model(Layer):
     def __init__(self):
           self.layer1 = XX
           self.layer2 = XX
     def forward(self, input):
           return self.layer1(input)
     def other_function(self, input, idx):
           return self.layer2(input, idx)

def train():
     dist.init_parallel_env()
     model = Model()
     model = paddle.DataParallel(model)
     inner_output = model(input)
     loss = 0
     for i in range(10):
          loss += criterion(model.other_function(inner_output, i), label)
     loss.backward()
```

## shell
python -m paddle.distributed.launch  train.py

**Comment by firestonelib** [comment]
多卡训练有梯度规约操作，因此模型参数的所有正向输出必须参与loss的计算以及后续的梯度计算，建议把other 变量放在forward 函数内，用分支做判断。
