### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by Sampson1107** [PaddlePaddle/Paddle#4358]
你好，在运行示例的过程中出现如下错误：
[root@dl3 image_classification]# python train.py alexnet 4 64                          sys.version_info(major=2, minor=7, micro=5, releaselevel='final', serial=0)
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    main()
  File "train.py", line 34, in main
    paddle.init(use_gpu=True, trainer_count=1)
  File "/usr/lib/python2.7/site-packages/paddle/v2/__init__.py", line 66, in init
    import py_paddle.swig_paddle as api
  File "/usr/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/usr/lib/python2.7/site-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/usr/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 27, in <module>
    _swig_paddle = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 23, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: dlopen: cannot load any more object with static TLS
我查看了一下py_paddle下的_swig_paddle.so文件的大小为171M
是否遇到过这个问题呢？期待您的回复

**Comment by 930083287** [comment]
你好，请问这个问题怎么解决的？
