### ISSUE TITLE
import paddle时出现这个错误怎么解决呢TypeError: Couldn't build proto file into descriptor pool: duplicate file name (framework.proto)

### ISSUE THREAD

**Issue by Mrc-2020** [PaddlePaddle/Paddle#43604]
### 请提出你的问题 Please ask your question

>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from .proto import framework_pb2
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\proto\framework_pb2.py", line 19, in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
  File "D:\Anaconda3\envs\paddle\lib\site-packages\google\protobuf\descriptor.py", line 1028, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool: duplicate file name (framework.proto)

**Comment by yt605155624** [comment]
你好，可以参考这个链接的解决办法：
https://stackoverflow.com/questions/68952308/tensorflow-couldnt-build-proto-file-into-descriptor-pool
```bash
pip uninstall protobuf
pip install --no-binary protobuf protobuf
```
另外注意 protobuf 的版本

参考: https://github.com/PaddlePaddle/Paddle/issues/43052
