### ISSUE TITLE
提交集群任务失败

### ISSUE THREAD

**Issue by alanse7en** [PaddlePaddle/Paddle#4367]
```
Traceback (most recent call last):
  File "/home/forum/yishijie/paddlepaddle/output/submit.py", line 288, in <module>
    no_prefix_train_args_dict, ).run()
  File "/home/forum/yishijie/paddlepaddle/output/submit.py", line 73, in run
    self._do_poster_request()
  File "/home/forum/yishijie/paddlepaddle/output/submit.py", line 162, in _do_poster_request
    print urllib2.urlopen(request).read()
  File "/home/forum/.jumbo/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/home/forum/.jumbo/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/home/forum/.jumbo/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/home/forum/.jumbo/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "build/bdist.linux-x86_64/egg/poster/streaminghttp.py", line 142, in http_open
  File "/home/forum/.jumbo/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/home/forum/.jumbo/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/home/forum/.jumbo/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/home/forum/.jumbo/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```
v2版本通过receiver提交mpi集群任务，报错信息如上。

**Comment by typhoonzero** [comment]
Closing. This was an error of "receiver" side, should be fixed now.
