### ISSUE TITLE
RuntimeError for paddle.nn.functional.paddle when dtype=bool

### ISSUE THREAD

**Issue by minogame** [PaddlePaddle/Paddle#43802]
### bug描述 Describe the Bug

```python
import numpy as np
import paddle
import paddle.nn.functional as F

# example 1
x_shape = (1, 1, 3)
x = paddle.arange(np.prod(x_shape), dtype="float32").reshape(x_shape) + 1
y = F.pad(x, [0, 0, 0, 0, 2, 3], value=1, mode='constant', data_format="NCL")
print(y.shape)

# example 2
x_shape = (1, 1, 3)
x = paddle.arange(np.prod(x_shape), dtype="float32").reshape(x_shape) + 1
z = x!=2.0
print(z.shape)
y = F.pad(z, [0, 0, 0, 0, 2, 3], value=True, mode='constant', data_format="NCL") #RuntimeError
```

### 其他补充信息 Additional Supplementary Information

```
[1, 1, 8]
[1, 1, 3]
Traceback (most recent call last):
  File "test_sb_paddle_pad.py", line 16, in <module>
    y = F.pad(z, [0, 0, 0, 0, 2, 3], value=True, mode='constant', data_format="NCL") #RuntimeError
  File "/home/sunzhun/.local/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 1298, in pad
    return layers.pad(x, pad, pad_value=value)
  File "/home/sunzhun/.local/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 6939, in pad
    helper.append_op(
  File "/home/sunzhun/.local/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/home/sunzhun/.local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3599, in append_op
    _dygraph_tracer().trace_op(type,
  File "/home/sunzhun/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 307, in trace_op
    self.trace(type, inputs, outputs, attrs,
RuntimeError: (NotFound) There are no kernels which are registered in the pad operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:327)
  [operator < pad > error]
```

**Comment by zhaoyinglia** [comment]
你好，根据官方文档，该api的参数x不支持 dtype=bool 的数据类型。

**Comment by zhaoyinglia** [comment]
你好，根据官方文档，该api不支持 dtype=bool 的数据类型。https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/pad_cn.html#canshu
