### ISSUE TITLE
core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by qijigaici** [PaddlePaddle/Paddle#43908]
### 请提出你的问题 Please ask your question

安装命令：python3 -m pip install paddlepaddle==2.3.0 -i https://mirror.baidu.com/pypi/simple
运行： paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav
错误提示：
Error: Can not import avx core while this file exists: /home/ctb/tools/venv/lib/python3.7/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "/home/ctb/tools/venv/bin/paddlespeech", line 5, in <module>
    from paddlespeech.cli.entry import _execute
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddlespeech/cli/__init__.py", line 16, in <module>
    from .base_commands import BaseCommand
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddlespeech/cli/base_commands.py", line 19, in <module>
    from ..resource import CommonTaskResource
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddlespeech/resource/__init__.py", line 14, in <module>
    from .resource import CommonTaskResource
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddlespeech/resource/resource.py", line 20, in <module>
    from ..cli.utils import download_and_decompress
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddlespeech/cli/utils.py", line 26, in <module>
    import paddle
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/home/ctb/tools/venv/lib/python3.7/site-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /home/ctb/tools/venv/lib/python3.7/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

**Comment by qijigaici** [comment]
(/home/ctb/tools/venv) ctb@ctb-virtual-machine:~$ cat /proc/cpuinfo |grep -i avx
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsaveavx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xsaves arat md_clear flush_l1d arch_capabilities

**Comment by qijigaici** [comment]
(/home/ctb/tools/venv) ctb@ctb-virtual-machine:~$ python -m pip install paddlepaddle-2.3.0-cp38-cp38-linux_x86_64.whl 
ERROR: paddlepaddle-2.3.0-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform


python -m pip install paddlepaddle-2.3.0rc0-cp38-cp38-linux_x86_64.whl
ERROR: paddlepaddle-2.3.0rc0-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by shiyutang** [comment]
你好，你的问题已经收到，可以参考 https://github.com/PaddlePaddle/Paddle/issues/36801 目前你的系统似乎是 paddle 不支持的系统版本

**Comment by qijigaici** [comment]
目前ubuntu只支持18.04及以下？

**Comment by shiyutang** [comment]
可以参考noavx的panddle版本安装：https://github.com/PaddlePaddle/Paddle/issues/42225

**Comment by Microslargh** [comment]
Today I want to explain that Ubuntu20.04 can use paddle anyway, but I don't know if Ubuntu21.10 can support it? Please just give us an answer.

**Comment by arzakmiftakhul** [comment]
I got same error on Ubuntu 22.04 LTS.

**Comment by jalenchan** [comment]
me too.

**Comment by wgq18** [comment]
Yes, Ubuntu 22.04 can not support paddle2.3.1

**Comment by gamegrd** [comment]
same issues on 5.15.60-1-MANJARO #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022 x86_64 GNU/Linux

**Comment by april211** [comment]
> Yes, Ubuntu 22.04 can not support paddle2.3.1

2.3.2 too

**Comment by saaavsaaa** [comment]
Waiting for support for ubuntu 22

**Comment by devopsmi** [comment]
各位大佬们，不要一个问题，多次出现嘛，想说爱你不容易啊

**Comment by AntonOfTheWoods** [comment]
Does anyone know what Linux distros *are* supported?
