### ISSUE TITLE
静态图 all_gather 随机报错 ncclInvalidUsage

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/Paddle#44102]
### bug描述 Describe the Bug

使用all_gather 获取多卡loss损失，但是随机出现 nccl 报错

paddle版本：99b3727d5bd37ae18ef63407dc4bd6ab75fb76fc

代码: 
```python
343 def all_gather(v):
344     if fleet.worker_num() <= 1:
345         return v
346  
347     ret = []
348     dist.all_gather(ret, v)
349     concat = paddle.concat(ret, axis=0)
350     concat.stop_gradients=True
351     paddle.static.Print(concat)
352     return concat.mean()
```

报错：
```python
[2022-07-05 17:16:17,060] [    INFO] - global step 250, loss: 6.391261, speed: 3.97 steps/s, ips: 126.93 seqs/s, learning rate: 9.99864e-05, loss_scaling: 32768.0, num_good_steps: 250, num_bad_steps: 0
Variable: concat_0.tmp_0
  - lod: {}
  - place: Place(gpu:5)
  - shape: [2]
  - layout: NCHW
  - dtype: float
  - data: [6.33632 6.34206]
Traceback (most recent call last):
  File "run_pretrain_static.py", line 789, in <module>
    do_train(args)
  File "run_pretrain_static.py", line 640, in do_train
    ret = exe.run(main_program,
  File "/ssd1/zhonghui03/miniconda3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1303, in run
    six.reraise(*sys.exc_info())
  File "/ssd1/zhonghui03/miniconda3/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/ssd1/zhonghui03/miniconda3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1290, in run
    res = self._run_impl(program=program,
  File "/ssd1/zhonghui03/miniconda3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1510, in _run_impl
    return self._run_parallel(program._graph,
  File "/ssd1/zhonghui03/miniconda3/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1105, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
OSError: (External) NCCL error(5), invalid usage.
  [Hint: 'ncclInvalidUsage'. The call to NCCL is incorrect. This is usually reflecting a programming error.] (at /paddle/paddle/fluid/framework/details/nccl_op_handle.h:153)

```

### 其他补充信息 Additional Supplementary Information

复现：
```
git clone -b enhance_ernie_tokenizer https://github.com/ZHUI/PaddleNLP.git
cd PaddleNLP/model_zoo/ernie-1.0
bash -x run_test.sh
```

```shell
# run_test.sh
set -x
unset CUDA_VISIBLE_DEVICES

rm -rf core.*

# dp8 for 8 worker of data parallel
# gb512 for the global batch size is 512 = 64 * 8
# s1m for max steps is 1 million
task_name="ernie-1.0-dp8-gb512"
rm -rf output/$task_name/log

python -u  -m paddle.distributed.launch \
    --gpus "5,6" \
    --log_dir "output/$task_name/log" \
    run_pretrain_static.py \
    --model_type "ernie" \
    --model_name_or_path "ernie-3.0-base-zh" \
    --tokenizer_name_or_path "./final_vocab/" \
    --masked_lm_prob 0.15 \
    --binary_head false \
    --dp_degree 2\
    --input_dir "./data" \
    --output_dir "output/$task_name" \
    --split 949,50,1 \
    --max_seq_len 512 \
    --micro_batch_size 16 \
    --use_amp true \
    --use_recompute false \
    --max_lr 0.0001 \
    --min_lr 0.00001 \
    --max_steps 10000 \
    --save_steps 50000 \
    --checkpoint_steps 5000 \
    --decay_steps 990000 \
    --weight_decay 0.01 \
    --warmup_rate 0.01 \
    --grad_clip 1.0 \
    --logging_freq 10\
    --num_workers 0 \
    --eval_freq 100 \
    --device "gpu"\
```

**Comment by GuoxiaWang** [comment]
用高层 API 封装，使用了 Parallel Executor (PE)，这模式下底层会做一些通信 API的优化，导致用户再自己调用通信 API 时引起冲突
