### ISSUE TITLE
单卡单机训练报错

### ISSUE THREAD

**Issue by William-Jianyuan** [PaddlePaddle/Paddle#44110]
### 问题描述 Please describe your issue

单卡单机训练 时报错 2.3.0,  cuda10.2
celery.app.trace - ERROR - Task model_lib.ocr.train.train[ac1ae09cfccb11ec8f7b024202cdb4fb] raised unexpected: OSError("(External) CUDA error(3), initialization error. \n  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:243)\n  [operator < gaussian_random > error]")
Traceback (most recent call last):
  File "/home/qic/env/anaconda3/envs/qic/lib/python3.7/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/qic/env/anaconda3/envs/qic/lib/python3.7/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/qic/yjy/make_qic_struct_better/model_lib/ocr/train.py", line 98, in train
    model = build_model(config['Architecture'])
  File "/home/qic/yjy/make_qic_struct_better/model_lib/ocr/ppocr/modeling/architectures/__init__.py", line 27, in build_model
    arch = BaseModel(config)
  File "/home/qic/yjy/make_qic_struct_better/model_lib/ocr/ppocr/modeling/architectures/base_model.py", line 50, in __init__
    self.backbone = build_backbone(config["Backbone"], model_type)
  File "/home/qic/yjy/make_qic_struct_better/model_lib/ocr/ppocr/modeling/backbones/__init__.py", line 47, in build_backbone
    module_class = eval(module_name)(**config)
  File "/home/qic/yjy/make_qic_struct_better/model_lib/ocr/ppocr/modeling/backbones/det_resnet_vd.py", line 205, in __init__
    name="conv1_1")
  File "/home/qic/yjy/make_qic_struct_better/model_lib/ocr/ppocr/modeling/backbones/det_resnet_vd.py", line 51, in __init__
    bias_attr=False)
  File "/home/qic/env/anaconda3/envs/qic/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 657, in __init__
    data_format=data_format)
  File "/home/qic/env/anaconda3/envs/qic/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 136, in __init__
    default_initializer=_get_default_param_initializer())
  File "/home/qic/env/anaconda3/envs/qic/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 424, in create_parameter
    default_initializer)
  File "/home/qic/env/anaconda3/envs/qic/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/qic/env/anaconda3/envs/qic/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "/home/qic/env/anaconda3/envs/qic/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 367, in __call__
    'std', self._std_dev, 'seed', self._seed, 'use_mkldnn', False)
OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:243)
  [operator < gaussian_random > error]

**Comment by YuanRisheng** [comment]
您好，可以先检查一下paddle是否正确安装，
使用如下命令先检查一下paddle安装是否正确：

import paddle
paddle.utils.run_check()

**Comment by William-Jianyuan** [comment]
您好, 检查出来是这样
机器上有4个gpu
Running verify PaddlePaddle program ... 
W0706 11:28:58.431027 17882 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 10.2
W0706 11:28:58.432694 17882 gpu_context.cc:306] device: 0, cuDNN Version: 8.3.
PaddlePaddle works well on 1 GPU.
W0706 11:29:06.859215 17882 dynamic_loader.cc:276] You may need to install 'nccl2' from NVIDIA official website: https://developer.nvidia.com/nccl/nccl-downloadbefore install PaddlePaddle.
WARNING:root:PaddlePaddle meets some problem with 4 GPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests 
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
WARNING:root:
 Original Error is: (PreconditionNotMet) The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. (error code is libnccl.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:303)

PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.

**Comment by YuanRisheng** [comment]
您好，您的paddle安装有问题，从上述提示看出应该是您环境有些问题，可以尝试按照上述的提示尝试进行修复，如若未解决，推进使用paddle官方的docker安装方式重新安装paddle : https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

**Comment by YuanRisheng** [comment]
您好，从上述提示看出应该是您环境有些问题，只能使用单GPU进行训练，可以尝试按照上述的提示尝试进行修复，另外您的cuda版本(10.2)和您的driver版本(11.4)是不匹配的，这个也会是个影响因素，推荐使用cuda11.x，如若未解决，推荐使用paddle官方的docker安装方式重新安装paddle : https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

**Comment by William-Jianyuan** [comment]
如果我用单卡就够了, 现在的还是要重装吗

**Comment by YuanRisheng** [comment]
可以先试试单卡训练，不行再重装

**Comment by William-Jianyuan** [comment]
现在就是单机单卡报的错 不启动分布式,
用的是 这样的脚本
# 单机单卡训练 mv3_db 模型
python3 tools/train.py -c configs/det/det_mv3_db.yml \
     -o Global.pretrain_weights=./pretrain_models/MobileNetV3_large_x0_5_pretrained

**Comment by YuanRisheng** [comment]
可以使用export CUDA_VISIBLE_DEVICES=卡号，指定一张空闲的GPU卡再试试，如果还不行，建议更新cuda版本到11.2，再不行需要重装了

**Comment by William-Jianyuan** [comment]
好的, 感谢, 有问题再找您
