### ISSUE TITLE
notebook上使用dist.spawn 失败

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/Paddle#44261]
### bug描述 Describe the Bug

以下是从官网复制的示例代码：

```
from __future__ import print_function

import paddle
import paddle.nn as nn
import paddle.optimizer as opt
import paddle.distributed as dist

class LinearNet(nn.Layer):
    def __init__(self):
        super(LinearNet, self).__init__()
        self._linear1 = nn.Linear(10, 10)
        self._linear2 = nn.Linear(10, 1)

    def forward(self, x):
        return self._linear2(self._linear1(x))

def train(print_result=False):
    # 1. initialize parallel environment
    dist.init_parallel_env()

    # 2. create data parallel layer & optimizer
    layer = LinearNet()
    dp_layer = paddle.DataParallel(layer)

    loss_fn = nn.MSELoss()
    adam = opt.Adam(
        learning_rate=0.001, parameters=dp_layer.parameters())

    # 3. run layer
    inputs = paddle.randn([10, 10], 'float32')
    outputs = dp_layer(inputs)
    labels = paddle.randn([10, 1], 'float32')
    loss = loss_fn(outputs, labels)

    if print_result is True:
        print("loss:", loss.numpy())

    loss.backward()

    adam.step()
    adam.clear_grad()

if __name__ == '__main__':
    dist.spawn(train, args=(True,))
```
运行结果为：

```
INFO 2022-07-12 14:58:53,951 cloud_utils.py:122] get cluster from args:job_server:None pods:['rank:0 id:None addr:127.0.0.1 port:None visible_gpu:[] trainers:["gpu:[\'0\'] endpoint:127.0.0.1:56004 rank:0", "gpu:[\'1\'] endpoint:127.0.0.1:35754 rank:1", "gpu:[\'2\'] endpoint:127.0.0.1:35179 rank:2", "gpu:[\'3\'] endpoint:127.0.0.1:51884 rank:3", "gpu:[\'4\'] endpoint:127.0.0.1:51789 rank:4", "gpu:[\'5\'] endpoint:127.0.0.1:39826 rank:5", "gpu:[\'6\'] endpoint:127.0.0.1:54294 rank:6", "gpu:[\'7\'] endpoint:127.0.0.1:33243 rank:7"]'] job_stage_flag:None hdfs:None
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'train' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'train' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'train' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'train' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'train' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'train' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'train' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/root/anaconda3/envs/d2l/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'train' on <module '__main__' (built-in)>


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1657609135 (unix time) try "date -d @1657609135" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x289d) received by PID 10426 (TID 0x7fc35544d700) from PID 10397 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1657609136 (unix time) try "date -d @1657609136" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x289d) received by PID 10427 (TID 0x7ff46ba10700) from PID 10397 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1657609136 (unix time) try "date -d @1657609136" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x289d) received by PID 10428 (TID 0x7fd939eec700) from PID 10397 ***]

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Input In [3], in <cell line: 1>()
      1 if __name__ == '__main__':
----> 2     dist.spawn(train, args=(True,))

File ~/anaconda3/envs/d2l/lib/python3.8/site-packages/paddle/distributed/spawn.py:565, in spawn(func, args, nprocs, join, daemon, **options)
    562     return context
    564 # loop until all process end
--> 565 while not context.join():
    566     pass
    568 # finally return context

File ~/anaconda3/envs/d2l/lib/python3.8/site-packages/paddle/distributed/spawn.py:373, in MultiprocessContext.join(self, timeout)
    370         process.terminate()
    371     process.join()
--> 373 self._throw_exception(error_index)

File ~/anaconda3/envs/d2l/lib/python3.8/site-packages/paddle/distributed/spawn.py:383, in MultiprocessContext._throw_exception(self, error_index)
    380         raise Exception("Process %d terminated with signal %s." %
    381                         (error_index, name))
    382     else:
--> 383         raise Exception("Process %d terminated with exit code %d." %
    384                         (error_index, exitcode))
    386 original_trace = self.error_queues[error_index].get()
    387 msg = "\n\n----------------------------------------------\n" \
    388       "Process %d terminated with the following error:\n" \
    389       "----------------------------------------------\n\n" % error_index

Exception: Process 0 terminated with exit code 1.
```

环境是ubuntu， python3.8， paddle 2.3.1版本

**Comment by seemingwang** [comment]
官网提供的whl包编译的时候没有打开          -DWITH_DISTRIBUTE=ON  选项，所以使用不了这个功能，
若需要使用这个功能需要手动编译，并在cmake时候加上           -DWITH_DISTRIBUTE=ON 选项。
可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html
