### ISSUE TITLE
multiclass_nms3 op无法单独序列化

### ISSUE THREAD

**Issue by Kevin-XiongC** [PaddlePaddle/Paddle#44349]
### bug描述 Describe the Bug

# Bug描述
其他无参数op都能通过jit单独序列化，但是multiclass_nms3不行,无论是通过动态图的jit还是静态图的save_inference_model

## 静态图
``` python

import numpy as np
import paddle
import paddle.fluid as fluid
from paddle.fluid import core

from paddle.static import InputSpec
from collections import OrderedDict
import warnings
from paddle.jit import to_static

exe = paddle.static.Executor(paddle.CPUPlace())

def f(BOX_SIZE, N, M, C, background_label, nms_threshold, nms_top_k, keep_top_k, score_threshold):

    paddle.enable_static()
    bbox = paddle.static.data(shape=(N, M, BOX_SIZE), name='bbox')
    score = paddle.static.data(shape=(N, C, M), name='score')
    attrs = ('background_label', background_label, 'score_threshold',
             score_threshold, 'nms_top_k', nms_top_k, 'nms_threshold',
             nms_threshold, 'keep_top_k', keep_top_k, 'nms_eta', 1,
             'normalized', True)

    output, _, nms_rois_num = core.ops.multiclass_nms3(bbox, score,
                                                       None, *attrs)
    exe.run(paddle.static.default_startup_program())
    paddle.static.save_inference_model("xxxxxx", [bbox,score], [output,nms_rois_num], exe)

f(N=1, M=1200,
               C=21,
               BOX_SIZE=4,
               background_label=3,
               nms_threshold=0.3,
               nms_top_k=400,
               keep_top_k=200,
               score_threshold=0.1
               )

```

## 动态图

``` Python

class Test(paddle.nn.Layer):
    """" Temporary Class to create a DAG"""

    def __init__(self, attrs):
        super(Test, self).__init__()
        self.attrs = attrs

    def forward(self, bboxes,
                scores, rois_num=None
                ):
        """"forward"""
        output, _, nms_rois_num = core.ops.multiclass_nms3(bboxes, scores,
                                                           rois_num, *self.attrs)
        return output, nms_rois_num

def f(BOX_SIZE, N, M, C, background_label, nms_threshold, nms_top_k, keep_top_k, score_threshold):
   attrs = ('background_label', background_label, 'score_threshold',
                 score_threshold, 'nms_top_k', nms_top_k, 'nms_threshold',
                 nms_threshold, 'keep_top_k', keep_top_k, 'nms_eta', 1,
                 'normalized', True)
    obj = Test(attrs)
    bbox_spec = InputSpec(shape=(N, M, BOX_SIZE), name='bbox')
    score_spec = InputSpec(shape=(N, C, M), name='scores')
    paddle.jit.save(obj, path=paddle_path,input_spec = [bbox_spec,score_spec])


f(N=1, M=1200,
       C=21,
       BOX_SIZE=4,
       background_label=3,
       nms_threshold=0.3,
       nms_top_k=400,
       keep_top_k=200,
       score_threshold=0.1
                       )
```

# 报错信息

``` shell
Traceback (most recent call last):
  File "test_multiclass_nms3.py", line 124, in test_Nms_2
    test_nms_entry(test_case, N=1,
  File "test_multiclass_nms3.py", line 60, in test_nms_entry
    paddle.jit.save(obj, path=paddle_path,input_spec = [bbox_spec,score_spec])
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 629, in wrapper
    func(layer, path, input_spec, **configs)
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 856, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/Users/xxxx/pyenv/versions/3.8.13/lib/python3.8/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "test_multiclass_nms3.py", line 40, in forward
                ):
        """"forward"""
        output, _, nms_rois_num = core.ops.multiclass_nms3(bboxes, scores,
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                                           rois_num, *self.attrs)
        return output, nms_rois_num


    ValueError: (InvalidArgument) multiclass_nms3(): argument 'BBoxes' (position 0) must be Tensor, but got Variable (at /Users/paddle/xly/workspace/e5273a57-82b5-470b-98d2-ae1990b2308c/Paddle/paddle/fluid/pybind/op_function_common.cc:737)

```
静态图没有报错的trace，但最后的error信息是一样的

### 其他补充信息 Additional Supplementary Information

mac m1
paddle 2.3.1

**Comment by RichardWooSJTU** [comment]
请问您是在哪里看到core.ops.multiclass_nms3的用法呢？core的调用仅限动态图模式，不支持inference model的导出，paddle 提供的API [multiclass_nms](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/layers/multiclass_nms_cn.html)是否可以满足开发需求呢？如果必须使用multiclass_nms3的话也可以参考这里自己实现静态图APIhttps://github.com/PaddlePaddle/Paddle/blob/94271bc2250b4eba155b72269430c3dafc5ae10d/python/paddle/fluid/layers/detection.py#L3397

**Comment by Kevin-XiongC** [comment]
你好，我是在适配paddledet的ssd模型时看到multiclass_nms3这个op, 所以理论上 所有序列化进protobuf的op，都可以通过helper进行单独导出吗？
