### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'desc'

### ISSUE THREAD

**Issue by xyhcc** [PaddlePaddle/Paddle#44410]
### 请提出你的问题 Please ask your question

环境：win10，pycharm2022社区版上，Python3.10，paddle2.3.1

在运行下面代码时报错，错误如下，希望能帮忙解决一下
`F:\文档\Pycharm_Project\paddle_Project\venv\Scripts\python.exe F:/文档/Pycharm_Project/paddle_Project/test_paddle.py
WARNING: OMP_NUM_THREADS set to 12, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
PLEASE USE OMP_NUM_THREADS WISELY.
F:\文档\Pycharm_Project\paddle_Project\venv\lib\site-packages\paddle\fluid\executor.py:1350: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
Traceback (most recent call last):
  File "F:\文档\Pycharm_Project\paddle_Project\test_paddle.py", line 15, in 
    result=exe.run(program=fluid.default_main_program(), fetch_list=[y1])
  File "F:\文档\Pycharm_Project\paddle_Project\venv\lib\site-packages\paddle\fluid\executor.py", line 1299, in run
    six.reraise(*sys.exc_info())
  File "F:\文档\Pycharm_Project\paddle_Project\venv\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "F:\文档\Pycharm_Project\paddle_Project\venv\lib\site-packages\paddle\fluid\executor.py", line 1285, in run
    res = self._run_impl(
  File "F:\文档\Pycharm_Project\paddle_Project\venv\lib\site-packages\paddle\fluid\executor.py", line 1425, in _run_impl
    key = _get_strong_program_cache_key(inner_program, feed,
  File "F:\文档\Pycharm_Project\paddle_Project\venv\lib\site-packages\paddle\fluid\executor.py", line 439, in _get_strong_program_cache_key
    program)) + _get_program_cache_key(feed, fetch_list)
  File "F:\文档\Pycharm_Project\paddle_Project\venv\lib\site-packages\paddle\fluid\executor.py", line 449, in _get_program_cache_key
    fetch_var_names = list(map(_to_name_str, fetch_list))
  File "F:\文档\Pycharm_Project\paddle_Project\venv\lib\site-packages\paddle\fluid\executor.py", line 389, in _to_name_str
    return _to_str(var)
  File "F:\文档\Pycharm_Project\paddle_Project\venv\lib\site-packages\paddle\fluid\executor.py", line 371, in _to_str
    return var.desc.name()
AttributeError: 'Tensor' object has no attribute 'desc'`

`import paddle.fluid as fluid
x1=fluid.layers.fill_constant(shape=[2,2],value=1,dtype='int64')

x2=fluid.layers.fill_constant(shape=[2,2],value=1,dtype='int64')

y1=fluid.layers.sum(x=[x1,x2])

# 创建使用CPU的解析器
place=fluid.CPUPlace()
exe=fluid.executor.Executor(place)

# 参数初始化
exe.run(fluid.default_startup_program())

result=exe.run(program=fluid.default_main_program(), fetch_list=[y1])
print(result)`

**Comment by firestonelib** [comment]
Thanks for reporting this case.

1. check if there is `paddle.enable_static()` in your code, try this :
```
import paddle
import paddle.fluid as fluid
paddle.enable_static()
x1=fluid.layers.fill_constant(shape=[2,2],value=1,dtype='int64')

x2=fluid.layers.fill_constant(shape=[2,2],value=1,dtype='int64')

y1=fluid.layers.sum(x=[x1,x2])

place=fluid.CPUPlace()
exe=fluid.executor.Executor(place)

exe.run(fluid.default_startup_program())

result=exe.run(program=fluid.default_main_program(), fetch_list=[y1])
print(result)
```

**Comment by xyhcc** [comment]
Thank you for your answer. The problem has been solved
