### ISSUE TITLE
在使用ctc_loss 计算的时候报错：[operator < warpctc > error]

### ISSUE THREAD

**Issue by SoulSubmerge** [PaddlePaddle/Paddle#44489]
### 请提出你的问题 Please ask your question

  warnings.warn(
Traceback (most recent call last):
  File "d:/code/Deep_Learning/PaddlePaddle/OCR_PP/tools/trainCRNN.py", line 37, in <module>
    loss = paddle.nn.functional.ctc_loss(pre, labelInput, pre_length, labelLength, blank=12)
  File "E:\Apps\development_tool\python3.8\lib\site-packages\paddle\nn\functional\loss.py", line 1129, in ctc_loss
    loss_out = fluid.layers.warpctc(log_probs, labels, blank, norm_by_times,
  File "E:\Apps\development_tool\python3.8\lib\site-packages\paddle\fluid\layers\loss.py", line 605, in warpctc
    grad, loss_out = _C_ops.warpctc(
ValueError: (InvalidArgument) The value of Attr(blank) should be in interval [0, 12), but received
  [Hint: Expected blank < sequence_width, but received blank:12 >= sequence_width:11.] (at C:\home\workspace\Paddle_release\paddle\phi\infermeta\multiary.cc:1868)
  [operator < warpctc > error]

**Comment by zhangbo9674** [comment]
您好，根据报错提示， fluid.layers.warpctc的blank参数的有效范围为[0, 12)，当前的值为12，建议复查一下代码

**Comment by SoulSubmerge** [comment]
> 您好，根据报错提示， fluid.layers.warpctc的blank参数的有效范围为[0, 12)，当前的值为12，建议复查一下代码

谢谢！我解决了，感谢感谢！
