### ISSUE TITLE
paddle官网的异步读取数据的范例代码中，无法使用save_inference保存模型

### ISSUE THREAD

**Issue by tianrenheyi09** [PaddlePaddle/Paddle#44553]
### bug描述 Describe the Bug

https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/advanced_guide/data_preparing/static_mode/use_py_reader.html
paddle官网的异步读取数据的范例代码中，无法使用save_inference保存模型
在以上实例代码中，每个epoch加上保存模型的代码，报错
 fluid.io.save_inference_model(dirname="./modelm", feeded_var_names=['image'], target_vars=[train_loss], executor=exe)

**Comment by ronny1996** [comment]
请问使用什么版本的Paddle和环境？有详细的错误信息吗？

**Comment by tianrenheyi09** [comment]
paddle1.8，提示变量不存在

**Comment by tianrenheyi09** [comment]
INFO 2022-07-22 17:57:43,665 dataloader_auto_checkpoint.py:157] end dataloader epoch_no:0                                                                  
Traceback (most recent call last):                                                                                                                         
  File "test5.py", line 135, in <module>                                                                                                                   
    fluid.io.save_inference_model(dirname="./modelm", feeded_var_names=['image'], target_vars=[train_loss], executor=exe)                                  
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/io.py", line 1250, in save_inference_model                                   
    prepend_feed_ops(main_program, feeded_var_names)                                                                                                       
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/io.py", line 1046, in prepend_feed_ops                                       
    out = global_block.var(name)                                                                                                                           
  File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2392, in var                                             
    raise ValueError("var %s not in this block" % name)                                                                                                    
ValueError: var image not in this block

**Comment by tianrenheyi09** [comment]
import paddle.fluid as fluid
import numpy as np

# sample级reader
def fake_sample_reader():
    for _ in range(100):
        sample_image = np.random.random(size=(784, )).astype('float32')
        sample_label = np.random.random_integers(size=(1, ), low=0, high=9).astype('int64')
        yield sample_image, sample_label


# batch级reader
def fake_batch_reader():
    batch_size = 32
    for _ in range(100):
        batch_image = np.random.random(size=(batch_size, 784)).astype('float32')
        batch_label = np.random.random_integers(size=(batch_size, 1), low=0, high=9).astype('int64')
        yield batch_image, batch_label

image1 = fluid.data(name='image1', dtype='float32', shape=[None, 784])
label1 = fluid.data(name='label1', dtype='int64', shape=[None, 1])

image2 = fluid.data(name='image2', dtype='float32', shape=[None, 784])
label2 = fluid.data(name='label2', dtype='int64', shape=[None, 1])

image3 = fluid.data(name='image3', dtype='float32', shape=[None, 784])
label3 = fluid.data(name='label3', dtype='int64', shape=[None, 1])

import paddle
import paddle.fluid as fluid

ITERABLE = True
USE_CUDA = True
USE_DATA_PARALLEL = True

if ITERABLE:
    # 若DataLoader可迭代，则必须设置places参数
    if USE_DATA_PARALLEL:
        # 若进行多GPU卡训练，则取所有的CUDAPlace
        # 若进行多CPU核训练，则取多个CPUPlace，本例中取了8个CPUPlace
        places = fluid.cuda_places() if USE_CUDA else fluid.cpu_places(8)
    else:
        # 若进行单GPU卡训练，则取单个CUDAPlace，本例中0代表0号GPU卡
        # 若进行单CPU核训练，则取单个CPUPlace，本例中1代表1个CPUPlace
        places = fluid.cuda_places(0) if USE_CUDA else fluid.cpu_places(1)
else:
    # 若DataLoader不可迭代，则不需要设置places参数
    places = None

# 使用sample级的reader作为DataLoader的数据源
data_loader1 = fluid.io.DataLoader.from_generator(feed_list=[image1, label1], capacity=10, iterable=ITERABLE)
data_loader1.set_sample_generator(fake_sample_reader, batch_size=32, places=places)

# 使用sample级的reader + fluid.io.batch设置DataLoader的数据源
data_loader2 = fluid.io.DataLoader.from_generator(feed_list=[image2, label2], capacity=10, iterable=ITERABLE)
sample_list_reader = fluid.io.batch(fake_sample_reader, batch_size=32)
sample_list_reader = fluid.io.shuffle(sample_list_reader, buf_size=64) # 还可以进行适当的shuffle
data_loader2.set_sample_list_generator(sample_list_reader, places=places)

# 使用batch级的reader作为DataLoader的数据源
data_loader3 = fluid.io.DataLoader.from_generator(feed_list=[image3, label3], capacity=10, iterable=ITERABLE)
data_loader3.set_batch_generator(fake_batch_reader, places=places)

import paddle
import paddle.fluid as fluid
import paddle.dataset.mnist as mnist
import six

ITERABLE = True

def network():
    # 创建数据层对象
    image = fluid.data(name='image', dtype='float32', shape=[None, 784])
    label = fluid.data(name='label', dtype='int64', shape=[None, 1])

    # 创建DataLoader对象
    reader = fluid.io.DataLoader.from_generator(feed_list=[image, label], capacity=64, iterable=ITERABLE)

    # Definition of models
    fc = fluid.layers.fc(image, size=10)
    xe = fluid.layers.softmax_with_cross_entropy(fc, label)
    loss = fluid.layers.reduce_mean(xe)
    return loss , reader

# 创建训练的main_program和startup_program
train_prog = fluid.Program()
train_startup = fluid.Program()

# 定义训练网络
with fluid.program_guard(train_prog, train_startup):
    # fluid.unique_name.guard() to share parameters with test network
    with fluid.unique_name.guard():
        train_loss, train_loader = network()
        adam = fluid.optimizer.Adam(learning_rate=0.01)
        adam.minimize(train_loss)

# 创建预测的main_program和startup_program
test_prog = fluid.Program()
test_startup = fluid.Program()

# 定义预测网络
with fluid.program_guard(test_prog, test_startup):
    # Use fluid.unique_name.guard() to share parameters with train network
    with fluid.unique_name.guard():
        test_loss, test_loader = network()

place = fluid.CUDAPlace(0)
exe = fluid.Executor(place)

# 运行startup_program进行初始化
exe.run(train_startup)
exe.run(test_startup)

# Compile programs
train_prog = fluid.CompiledProgram(train_prog).with_data_parallel(loss_name=train_loss.name)
test_prog = fluid.CompiledProgram(test_prog).with_data_parallel(share_vars_from=train_prog)

# 设置DataLoader的数据源
places = fluid.cuda_places() if ITERABLE else None

train_loader.set_sample_list_generator(
    fluid.io.shuffle(fluid.io.batch(mnist.train(), 512), buf_size=1024), places=places)

test_loader.set_sample_list_generator(fluid.io.batch(mnist.test(), 512), places=places)


def run_iterable(program, exe, loss, data_loader):
    for data in data_loader():
        loss_value = exe.run(program=program, feed=data, fetch_list=[loss])
        print('loss is {}'.format(loss_value))

for epoch_id in six.moves.range(1):
    run_iterable(train_prog, exe, train_loss, train_loader)
    # run_iterable(test_prog, exe, test_loss, test_loader)
    fluid.io.save_inference_model(dirname="./modelm", feeded_var_names=['image'], target_vars=[train_loss], executor=exe)

**Comment by tianrenheyi09** [comment]
`import paddle.fluid as fluid
import numpy as np

# sample级reader
def fake_sample_reader():
    for _ in range(100):
        sample_image = np.random.random(size=(784, )).astype('float32')
        sample_label = np.random.random_integers(size=(1, ), low=0, high=9).astype('int64')
        yield sample_image, sample_label


# batch级reader
def fake_batch_reader():
    batch_size = 32
    for _ in range(100):
        batch_image = np.random.random(size=(batch_size, 784)).astype('float32')
        batch_label = np.random.random_integers(size=(batch_size, 1), low=0, high=9).astype('int64')
        yield batch_image, batch_label

image1 = fluid.data(name='image1', dtype='float32', shape=[None, 784])
label1 = fluid.data(name='label1', dtype='int64', shape=[None, 1])

image2 = fluid.data(name='image2', dtype='float32', shape=[None, 784])
label2 = fluid.data(name='label2', dtype='int64', shape=[None, 1])

image3 = fluid.data(name='image3', dtype='float32', shape=[None, 784])
label3 = fluid.data(name='label3', dtype='int64', shape=[None, 1])

import paddle
import paddle.fluid as fluid

ITERABLE = True
USE_CUDA = True
USE_DATA_PARALLEL = True

if ITERABLE:
    # 若DataLoader可迭代，则必须设置places参数
    if USE_DATA_PARALLEL:
        # 若进行多GPU卡训练，则取所有的CUDAPlace
        # 若进行多CPU核训练，则取多个CPUPlace，本例中取了8个CPUPlace
        places = fluid.cuda_places() if USE_CUDA else fluid.cpu_places(8)
    else:
        # 若进行单GPU卡训练，则取单个CUDAPlace，本例中0代表0号GPU卡
        # 若进行单CPU核训练，则取单个CPUPlace，本例中1代表1个CPUPlace
        places = fluid.cuda_places(0) if USE_CUDA else fluid.cpu_places(1)
else:
    # 若DataLoader不可迭代，则不需要设置places参数
    places = None

# 使用sample级的reader作为DataLoader的数据源
data_loader1 = fluid.io.DataLoader.from_generator(feed_list=[image1, label1], capacity=10, iterable=ITERABLE)
data_loader1.set_sample_generator(fake_sample_reader, batch_size=32, places=places)

# 使用sample级的reader + fluid.io.batch设置DataLoader的数据源
data_loader2 = fluid.io.DataLoader.from_generator(feed_list=[image2, label2], capacity=10, iterable=ITERABLE)
sample_list_reader = fluid.io.batch(fake_sample_reader, batch_size=32)
sample_list_reader = fluid.io.shuffle(sample_list_reader, buf_size=64) # 还可以进行适当的shuffle
data_loader2.set_sample_list_generator(sample_list_reader, places=places)

# 使用batch级的reader作为DataLoader的数据源
data_loader3 = fluid.io.DataLoader.from_generator(feed_list=[image3, label3], capacity=10, iterable=ITERABLE)
data_loader3.set_batch_generator(fake_batch_reader, places=places)

import paddle
import paddle.fluid as fluid
import paddle.dataset.mnist as mnist
import six

ITERABLE = True

def network():
    # 创建数据层对象
    image = fluid.data(name='image', dtype='float32', shape=[None, 784])
    label = fluid.data(name='label', dtype='int64', shape=[None, 1])

    # 创建DataLoader对象
    reader = fluid.io.DataLoader.from_generator(feed_list=[image, label], capacity=64, iterable=ITERABLE)

    # Definition of models
    fc = fluid.layers.fc(image, size=10)
    xe = fluid.layers.softmax_with_cross_entropy(fc, label)
    loss = fluid.layers.reduce_mean(xe)
    return loss , reader

# 创建训练的main_program和startup_program
train_prog = fluid.Program()
train_startup = fluid.Program()

# 定义训练网络
with fluid.program_guard(train_prog, train_startup):
    # fluid.unique_name.guard() to share parameters with test network
    with fluid.unique_name.guard():
        train_loss, train_loader = network()
        adam = fluid.optimizer.Adam(learning_rate=0.01)
        adam.minimize(train_loss)

# 创建预测的main_program和startup_program
test_prog = fluid.Program()
test_startup = fluid.Program()

# 定义预测网络
with fluid.program_guard(test_prog, test_startup):
    # Use fluid.unique_name.guard() to share parameters with train network
    with fluid.unique_name.guard():
        test_loss, test_loader = network()

place = fluid.CUDAPlace(0)
exe = fluid.Executor(place)

# 运行startup_program进行初始化
exe.run(train_startup)
exe.run(test_startup)

# Compile programs
train_prog = fluid.CompiledProgram(train_prog).with_data_parallel(loss_name=train_loss.name)
test_prog = fluid.CompiledProgram(test_prog).with_data_parallel(share_vars_from=train_prog)

# 设置DataLoader的数据源
places = fluid.cuda_places() if ITERABLE else None

train_loader.set_sample_list_generator(
    fluid.io.shuffle(fluid.io.batch(mnist.train(), 512), buf_size=1024), places=places)

test_loader.set_sample_list_generator(fluid.io.batch(mnist.test(), 512), places=places)


def run_iterable(program, exe, loss, data_loader):
    for data in data_loader():
        loss_value = exe.run(program=program, feed=data, fetch_list=[loss])
        print('loss is {}'.format(loss_value))

for epoch_id in six.moves.range(1):
    run_iterable(train_prog, exe, train_loss, train_loader)
    # run_iterable(test_prog, exe, test_loss, test_loader)
    fluid.io.save_inference_model(dirname="./modelm", feeded_var_names=['image'], target_vars=[train_loss], executor=exe)`

**Comment by tianrenheyi09** [comment]
for epoch_id in six.moves.range(1):
    run_iterable(train_prog, exe, train_loss, train_loader)
    # run_iterable(test_prog, exe, test_loss, test_loader)
    fluid.io.save_inference_model(dirname="./modelm", feeded_var_names=['image'], target_vars=[train_loss], executor=exe)

**Comment by ronny1996** [comment]
你好，能贴一段可复现的代码吗？

**Comment by ronny1996** [comment]
你好，请设置一下save_inference_model的main_program参数

**Comment by tianrenheyi09** [comment]
多谢，添加main_program参数后，可以正常保存
