### ISSUE TITLE
core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by phoenixes94** [PaddlePaddle/Paddle#44571]
### bug描述 Describe the Bug

Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```python
import paddle
Error: Can not import avx core while this file exists: /work/csg/shzhou/anaconda3/envs/Paddle/lib/python3.8/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
File "", line 1, in
File "/work/csg/shzhou/anaconda3/envs/Paddle/lib/python3.8/site-packages/paddle/init.py", line 25, in
from .framework import monkey_patch_variable
File "/work/csg/shzhou/anaconda3/envs/Paddle/lib/python3.8/site-packages/paddle/framework/init.py", line 17, in
from . import random # noqa: F401
File "/work/csg/shzhou/anaconda3/envs/Paddle/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in
import paddle.fluid as fluid
File "/work/csg/shzhou/anaconda3/envs/Paddle/lib/python3.8/site-packages/paddle/fluid/init.py", line 36, in
from . import framework
File "/work/csg/shzhou/anaconda3/envs/Paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in
from . import core
File "/work/csg/shzhou/anaconda3/envs/Paddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 298, in
raise e
File "/work/csg/shzhou/anaconda3/envs/Paddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 256, in
from . import core_avx
ImportError: /work/csg/shzhou/anaconda3/envs/Paddle/lib/python3.8/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
```

**Comment by phoenixes94** [comment]
I have one machine of gcc9.4.0，it run normally。but other two linux of gcc9.4.0 can not . It seems that having nothing to do with the GCC version.

**Comment by ZzSean** [comment]
> I have one machine of gcc9.4.0，it run normally。but other two linux of gcc9.4.0 can not . It seems that having nothing to do with the GCC version.

Hi, please check the Linux version, PaddlePaddle may not currently support versions above Ubuntu 20.04

**Comment by ZzSean** [comment]
Same problem with https://github.com/PaddlePaddle/Paddle/issues/36801

**Comment by phoenixes94** [comment]
My two machine’s Linux version is red hat 9 which can not be supported，another red hat 8 can run paddle normally. How can I sovle this issue？


发自我的iPhone

------------------ Original ------------------
From: Zhang Zheng ***@***.***&gt;
Date: 周一,7月 25,2022 11:19 上午
To: PaddlePaddle/Paddle ***@***.***&gt;
Cc: phoenixes94 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [PaddlePaddle/Paddle] core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE (Issue #44571)





  
I have one machine of gcc9.4.0，it run normally。but other two linux of gcc9.4.0 can not . It seems that having nothing to do with the GCC version.
  
Hi, please check the Linux version, PaddlePaddle may not currently support versions above Ubuntu 20.04

**Comment by jzhang533** [comment]
glibc >= 2.34 时会有这个问题，Paddle团队正在解决。
@Thunderbrook

**Comment by amitabduls15** [comment]
Hi i have same problem like this. When i run paddle in bash 
`python -m paddle.distributed.launch --gpus 0 tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.yml --eval`

produce error:

> `Error: Can not import avx core while this file exists: /run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/core.py", line 294, in <module>
    raise e
  File "/run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
05:07:57 (venvlnx) amitabduls@omen PaddleDetection ±||→ python -c 'import paddle;paddle.utils.run_check()'
Error: Can not import avx core while this file exists: /run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/core.py", line 294, in <module>
    raise e
  File "/run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /run/media/amitabduls/data/PROJECT/ICU/PYTHON/FishMoonProject/Image Recognition/PaddleDetection/venvlnx/lib/python3.7/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE`

This my system are used:
- Arch Linux kernel -> `Linux omen 5.14.1-xanmod1-cacule-1 #1 SMP PREEMPT Mon, 06 Sep 2021 20:31:59 +0000 x86_64 GNU/Linux`
- CUDA 11.7
- python 3.7.9
- paddlepaddle-gpu   2.2.0.post101

i have tried to install gomp and this error always show when i import paddle.

**Comment by haohetao** [comment]
I have same problem on Ubuntu 22.04.
>ImportError: /tmp/_MEI35wT82/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

**Comment by jzhang533** [comment]
fixed in develop branch by PR #45351
nightly build available at : https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html

duplicate: #36801

**Comment by yechong316** [comment]
Error: Can not import avx core while this file exists: /home/govid/miniconda3/lib/python3.9/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "/home/govid/miniconda3/bin/x2paddle", line 5, in <module>
    from x2paddle.convert import main
  File "/home/govid/miniconda3/lib/python3.9/site-packages/x2paddle/__init__.py", line 3, in <module>
    from .core.program import PaddleGraph
  File "/home/govid/miniconda3/lib/python3.9/site-packages/x2paddle/core/program.py", line 18, in <module>
    import paddle
  File "/home/govid/miniconda3/lib/python3.9/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/govid/miniconda3/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/govid/miniconda3/lib/python3.9/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/govid/miniconda3/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/govid/miniconda3/lib/python3.9/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/govid/miniconda3/lib/python3.9/site-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/home/govid/miniconda3/lib/python3.9/site-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /home/govid/miniconda3/lib/python3.9/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE


麻烦尽快解决，谢谢

**Comment by nabilragab** [comment]
PaddlePaddle supports GCC version 8

https://blog.csdn.net/zhqh100/article/details/124410399?spm=1001.2101.3001.6661.1&utm_medium=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-124410399-blog-122741583.t5_download_comparev1&depth_1-utm_source=distribute.pc_relevant_t0.none-task-blog-2%7Edefault%7ECTRLIST%7ERate-1-124410399-blog-122741583.t5_download_comparev1&utm_relevant_index=1

**Comment by jithinsankar** [comment]
My issue got resolved by installing v2.4 rc!!!

pip install paddlepaddle==2.4.0rc0

**Comment by yinlu6** [comment]
paddle is so hard to install, I may quit it

**Comment by angel-yi** [comment]
metoo

**Comment by Maioy97** [comment]
I also have this issue,  I recently upgraded to Ubuntu 22.04 and I'm using Conda environments

**Comment by Maioy97** [comment]
I tried reinstalling paddle using a new version like mentioned in 
https://github.com/urbanogilson/SICAR/issues/10#issuecomment-1352048407
and it works now

**Comment by renoyuan** [comment]
遇到一样的问题

**Comment by yiakwy-xpu-ml-framework-team** [comment]
> My issue got resolved by installing v2.4 rc!!!
> 
> pip install paddlepaddle==2.4.0rc0

You are installing CPU version paddle not gpu version.

**Comment by QianYing-LYG** [comment]
> My issue got resolved by installing v2.4 rc!!!
> 
> pip install paddlepaddle==2.4.0rc0

Very good, my ubuntu version is 22.04 and paddle version is 2.2, and it was resolved

**Comment by TheQYQ** [comment]
> My issue got resolved by installing v2.4 rc!!!
> 
> pip install paddlepaddle==2.4.0rc0

这个运行后就变味cpu版本了

**Comment by PeterPanWF** [comment]
With old versions solved.
Fedora 39, python3.8, paddleocr 2.7.0.3, paddlepaddle 2.4.0,
cpu version test ok.
