### ISSUE TITLE
安装官方文档安装报错  python -m pip install paddlepaddle-gpu==2.3.1.post111 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

### ISSUE THREAD

**Issue by yucaifuyoyo** [PaddlePaddle/Paddle#44707]
### 问题描述 Issue Description

![KMQ_Q5A4TTZ51FEP`UMEVGY](https://user-images.githubusercontent.com/34351511/181488187-324c6510-8c89-41b6-8af7-4cb148c25552.png)
![ZANQU5X S3YRB{%0T@SYEV](https://user-images.githubusercontent.com/34351511/181488217-bce90bec-2197-454e-8bbc-62701824e9e9.png)

### 版本&环境信息 Version & Environment Information

C:\Users\cf.yu>python -m pip install paddlepaddle-gpu==2.3.1.post111 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Looking in links: https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
ERROR: Exception:
Traceback (most recent call last):
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\commands\install.py", line 369, in run
    requirement_set = resolver.resolve(
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 44, in _iter_built
    for version, func in infos:
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 279, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\index\package_finder.py", line 889, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\index\package_finder.py", line 830, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\index\sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\index\package_finder.py", line 794, in process_project_url
    page_links = list(parse_links(index_response))
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\index\collector.py", line 313, in wrapper_wrapper
    return wrapper(CacheablePageContent(page))
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\index\collector.py", line 308, in wrapper
    return list(fn(cacheable_page.page))
  File "C:\02-software_python\01-python3.8\lib\site-packages\pip\_internal\index\collector.py", line 327, in parse_links
    data = json.loads(page.content)
  File "C:\02-software_python\01-python3.8\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\02-software_python\01-python3.8\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\02-software_python\01-python3.8\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by thsno02** [comment]
@yucaifuyoyo 我遇到这个问题后局部解决了。

OS：WSL 下的 Ubuntu 20.04
python：python 3.9
包管理：Anaconda

在非 root 用户下，base 环境里的安装时不会报错的；在自定义环境，比如 ocr 中安装，会持续报该错误。
在 root 用户下，无论 base 还是自定义的环境，都不会报错。

**Comment by bertrandpa** [comment]
Hi @yucaifuyoyo

I ran into the same error and it seems to be related to pip update 22.2 and especially this commit regarding PEP 691 implementation :
https://github.com/pypa/pip/commit/6f167b55a9293b423244318f1ae77fe576f2ee43#diff-6a334a312dbfe5998b0e0826594f38bc2cc4fc69e7d285580fd323b3a9d69e1cR143

To fix this while waiting for pip to change this you can downgrade pip with : python -m pip install --upgrade pip==22.1.2

**Comment by jzhang533** [comment]
该问题已经通过更新 https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html 页面得到了修复。
发现的pip的bug也已经反馈给了pip社区。
