### ISSUE TITLE
paddle训练时，出现了数据的大小不一样问题，是什么原因导致的？

### ISSUE THREAD

**Issue by joseph-chan** [PaddlePaddle/Paddle#4477]
Thu Sep 28 20:02:49 2017[1,0]<stderr>:Traceback (most recent call last):
Thu Sep 28 20:02:49 2017[1,0]<stderr>:  File "conf/trainer_config.conf", line 299, in <module>
Thu Sep 28 20:02:49 2017[1,0]<stderr>:    train(num_passes)
Thu Sep 28 20:02:49 2017[1,0]<stderr>:  File "conf/trainer_config.conf", line 287, in train
Thu Sep 28 20:02:49 2017[1,0]<stderr>:    num_passes= num_passes)
Thu Sep 28 20:02:49 2017[1,0]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20170928195731-1536/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/trainer.py", line 161, in train
Thu Sep 28 20:02:49 2017[1,0]<stderr>:    in_args = feeder(data_batch)
Thu Sep 28 20:02:49 2017[1,0]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20170928195731-1536/workspace/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 282, in __call__
Thu Sep 28 20:02:49 2017[1,0]<stderr>:    return self.convert(dat, argument)
Thu Sep 28 20:02:49 2017[1,0]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20170928195731-1536/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/data_feeder.py", line 133, in convert
Thu Sep 28 20:02:49 2017[1,0]<stderr>:    return DataProviderConverter.convert(self, reorder_data(dat), argument)
Thu Sep 28 20:02:49 2017[1,0]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20170928195731-1536/workspace/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 267, in convert
Thu Sep 28 20:02:49 2017[1,0]<stderr>:    scanner.pre_scan(each_step)
Thu Sep 28 20:02:49 2017[1,0]<stderr>:  File "/home/disk1/normandy/maybach/app-user-20170928195731-1536/workspace/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 119, in pre_scan
Thu Sep 28 20:02:49 2017[1,0]<stderr>:    "The data size must be equal to it in data layer.")
Thu Sep 28 20:02:49 2017[1,0]<stderr>:ValueError: 
Thu Sep 28 20:02:49 2017[1,0]<stderr>:The data size must be equal to it in data layer.

**Comment by joseph-chan** [comment]
这个问题在于我输入的dense_vector定义的维度
`·
self.aeinput = paddle.layer.data(                                                           
                name='ae_input',                                                                    
               type=paddle.data_type.dense_vector(self.input_layer_dim)) 
`
input_layer_dim为100000，而我的输入为一个不定维度的输入
