### ISSUE TITLE
windows pip安装paddle==1.0.2报错

### ISSUE THREAD

**Issue by liuxiaohui1221** [PaddlePaddle/Paddle#44939]
### 问题描述 Issue Description

安装命令：pip install paddle==1.0.2 --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple
错误信息如下：

`
(ctc) PS E:\pycharm_workspace\syntactic-experts\model\escspell\apex> pip install paddle==1.0.2 --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://pypi.ngc.nvidia.com
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.ngc.nvidia.com', port=443): Read timed out. (read timeout=15)")': /paddle/
Collecting paddle==1.0.2
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/55/cf/e4b6b9a54d2f072e4491e34317bf5f5fea260da8a3072e641832dc9ce770/paddle-1.0.2.tar.gz (579 kB)
     ---------------------------------------- 579.0/579.0 kB 2.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\18198\AppData\Local\Temp\pip-install-nh45w4ym\paddle_f03894c7bc67487abaca98dd5c8cccbd\setup.py", line 3, in <module>
          import paddle
        File "C:\Users\18198\AppData\Local\Temp\pip-install-nh45w4ym\paddle_f03894c7bc67487abaca98dd5c8cccbd\paddle\__init__.py", line 5, in <module>
          import common, dual, tight, data, prox
      ModuleNotFoundError: No module named 'common'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

### 版本&环境信息 Version & Environment Information

Paddle版本：1.0.2

GPU:  cuda11.6

Python: 3.8

**Comment by liuxiaohui1221** [comment]
运行代码错误：
Traceback (most recent call last):
  File "E:/work/ECSpell/Code/evaluate.py", line 5, in <module>
    from pipeline import tagger
  File "E:\work\ECSpell\Code\pipeline.py", line 2, in <module>
    from processor import VocabProcessor
  File "E:\work\ECSpell\Code\processor.py", line 4, in <module>
    import paddle
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\__init__.py", line 45, in <module>
    import paddle.distributed  # noqa: F401
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\distributed\__init__.py", line 15, in <module>
    from .spawn import spawn  # noqa: F401
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\distributed\spawn.py", line 28, in <module>
    from paddle.distributed.fleet.cloud_utils import use_paddlecloud
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\distributed\fleet\__init__.py", line 20, in <module>
    from .base.fleet_base import Fleet  # noqa: F401
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\distributed\fleet\base\fleet_base.py", line 32, in <module>
    from ..meta_parallel import TensorParallel, model_parallel_random_seed
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\distributed\fleet\meta_parallel\__init__.py", line 15, in <module>
    from .parallel_layers import VocabParallelEmbedding  # noqa: F401
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\distributed\fleet\meta_parallel\parallel_layers\__init__.py", line 15, in <module>
    from .mp_layers import VocabParallelEmbedding  # noqa: F401
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\distributed\fleet\meta_parallel\parallel_layers\mp_layers.py", line 18, in <module>
    from paddle.nn import functional as F
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\nn\__init__.py", line 23, in <module>
    from .layer.activation import ELU  # noqa: F401
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\nn\layer\__init__.py", line 17, in <module>
    from . import rnn  # noqa: F401
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\nn\layer\rnn.py", line 28, in <module>
    from paddle.device import get_device, get_cudnn_version
  File "C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\device\__init__.py", line 21, in <module>
    from paddle.fluid.framework import is_compiled_with_cinn  # noqa: F401
ImportError: cannot import name 'is_compiled_with_cinn' from 'paddle.fluid.framework' (C:\ProgramData\Anaconda3\envs\ctc\lib\site-packages\paddle\fluid\framework.py)

Process finished with exit code 1

**Comment by iclementine** [comment]
此 paddle 非彼 paddle.

paddlepaddle 的包名叫做 paddlepaddle 或者 paddelpaddle-gpu.
