### ISSUE TITLE
动态图多机多卡卡在not ready endpoints:['192.168.4.7:6070']

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#44966]
### 请提出你的问题 Please ask your question

 - PaddlePaddle 2.3.1
 - Ubuntu 18.04

第一台服务器命令：
```
python -m paddle.distributed.launch --ips="192.168.4.17,192.168.4.7" --gpus=0,1 train_fleet_dygraph.py
```

输出：
```
not ready endpoints:['192.168.4.7:6070', '192.168.4.7:6071']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.7:6070', '192.168.4.7:6071']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.7:6070', '192.168.4.7:6071']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.7:6070', '192.168.4.7:6071']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.7:6070']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.7:6070']
```

第二台服务器命令：
```
python -m paddle.distributed.launch --ips="192.168.4.7,192.168.4.17" --gpus=0,1 train_fleet_dygraph.py
```

输出：
```
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.7:6071', '192.168.4.17:6070']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.17:6070']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.17:6070']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.17:6070']
```

防火墙是关闭的，一直卡在这里。
参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/cluster_quick_start_cn.html

**Comment by JZ-LIANG** [comment]
命令使用是正确的，但是默认端口 6070 被占用 （其他进程）， 请确认节点上其他进程端口占用情况, 或使用 FLAGS_START_PORT flag 设置另外的空闲端口。

**Comment by yeyupiaoling** [comment]
请问FLAGS_START_PORT flag 怎麽使用，文档没有搜索到这个命令，
https://www.paddlepaddle.org.cn/searchall?q=FLAGS_START_PORT&language=zh&version=2.3

**Comment by yeyupiaoling** [comment]
@JZ-LIANG 请问FLAGS_START_PORT flag 怎麽使用，文档没有搜索到这个命令

**Comment by yeyupiaoling** [comment]
@JZ-LIANG 我知道怎么使用了，但是没有效果，不管怎么设置，开始的端口就是连接不了。
```
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.17:6074', '192.168.4.17:6075']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.17:6074', '192.168.4.17:6075']
server not ready, wait 3 sec to retry...
not ready endpoints:['192.168.4.17:6074']
server not ready, wait 3 sec to retry...
```
<br/><br/>

是不是我的命令有问题，我的命令`--ips`指定的IP，第一个是机器本身的IP地址。第二个才是另一台服务器
```shell
python -m paddle.distributed.launch --ips="192.168.4.17,192.168.4.7" --gpus=0,1 train_fleet_dygraph.py
```
```shell
python -m paddle.distributed.launch --ips="192.168.4.7,192.168.4.17" --gpus=0,1 train_fleet_dygraph.py
```

<br/><br/>

如果`--ips`只指定的另一台服务器的IP，如下命令，则会发生错误。这个程序是官方的例子，分别单机多卡训练是正常的。
```shell
python -m paddle.distributed.launch --ips="192.168.4.7" --gpus=0,1 train_fleet_dygraph.py
```
```shell
python -m paddle.distributed.launch --ips="192.168.4.17" --gpus=0,1 train_fleet_dygraph.py
```

错误如下。
```
    fleet.init(is_collective=True)
  File "/home/fgwj2/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 314, in init
    paddle.distributed.init_parallel_env()
  File "/home/fgwj2/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/distributed/parallel.py", line 317, in init_parallel_env
    parallel_helper._init_parallel_ctx()
  File "/home/fgwj2/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
    __parallel_ctx__clz__.init()
OSError: (External) NCCL error(5), invalid usage. 
  [Hint: 'ncclInvalidUsage'. The call to NCCL is incorrect. This is usually reflecting a programming error.] (at /paddle/paddle/fluid/platform/collective_helper.cc:100)
```

**Comment by yeyupiaoling** [comment]
哦哦，我知道了，两台机器的ips顺序要一样的。
```
python -m paddle.distributed.launch --ips="192.168.4.17,192.168.4.7" --gpus=0,1 train_fleet_dygraph.py
```

但是有一台机器的会报错，错误如下：
```
I0811 11:17:15.062717 24732 gen_comm_id_helper.cc:205] Server listening on: 192.168.4.17:6075 successful.
I0811 11:17:46.529448 24732 nccl_context.cc:83] init nccl context nranks: 4 local rank: 3 gpu id: 1 ring id: 0
Traceback (most recent call last):
  File "train_fleet_dygraph.py", line 86, in <module>
    train_resnet()
  File "train_fleet_dygraph.py", line 41, in train_resnet
    fleet.init(is_collective=True)
  File "/home/fgwj2/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 314, in init
    paddle.distributed.init_parallel_env()
  File "/home/fgwj2/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/distributed/parallel.py", line 317, in init_parallel_env
    parallel_helper._init_parallel_ctx()
  File "/home/fgwj2/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
    __parallel_ctx__clz__.init()
OSError: (External) NCCL error(2), unhandled system error. 
  [Hint: 'ncclSystemError'. A call to the system failed.] (at /paddle/paddle/fluid/platform/collective_helper.cc:100)
```

**Comment by yeyupiaoling** [comment]
是NCCL版本文问题，统一升级为2.8.4版本就可以了。
