### ISSUE TITLE
lgb使用脚本任务，调用GPU进行训练时，可以运行成功但是不进行训练。

### ISSUE THREAD

**Issue by super-tian** [PaddlePaddle/Paddle#45010]
### bug描述 Describe the Bug

环境配置：单机四卡

import lightgbm as lgb

notebook 上可以正常使用CPU训练

lgb 参数配置：
    params = {
............
        "device":"gpu",
        "gpu_platform_id":-1
        }

运行命令：
python -m paddle.distributed.launch --gpus="0,1,2,3" run001.py

报错信息：
'''
aunch train in GPU mode!
launch proc_id:491 idx:0
launch proc_id:494 idx:1
launch proc_id:499 idx:2
launch proc_id:504 idx:3
Traceback (most recent call last):
  File "run.py", line 57, in <module>
    import pandas as pd
  File "/usr/local/lib/python3.7/dist-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/groupby.py", line 46, in <module>
    from pandas.core.index import (Index, MultiIndex,
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/index.py", line 2, in <module>
    from pandas.core.indexes.api import *
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/api.py", line 4, in <module>
    from pandas.core.indexes.base import (Index,
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 53, in <module>
    from pandas.core import ops
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/ops/__init__.py", line 32, in <module>
    from pandas.core.ops.array_ops import (  # noqa:F401
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/ops/array_ops.py", line 19, in <module>
    from pandas._libs.tslibs import BaseOffset
ImportError: cannot import name 'BaseOffset' from 'pandas._libs.tslibs' (/usr/local/lib/python3.7/dist-packages/pandas/_libs/tslibs/__init__.py)
/mnt'''

**Comment by pangyoki** [comment]
你好，看报错是pandas的问题，可以看下单独使用pandas库是不是本来就有问题。
