### ISSUE TITLE
If combination op has several same input, it will fail at check_grad

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#4502]
I am porting interpolation_op #4500 
The formula is : 
```
Out.row[i] = W[i] * X.row[i] + (1 - W[i]) * Y.row[i]
                 = (X.row[i] - Y.row[i]) * W[i] + Y.row[i]
```
I combine it with three ops:
- MinusOut = X - Y
- MulOut = MinusOut * W = (X - Y) * W
- Out = MulOut + Y = (X - Y) * W + Y = X * W + Y * (1 - W)

Thus, `Input(Y)` has been used twice. 
When I use `LOG(INFO) << DebugString()` in `operator.cc`, I can find two `Y@GRAD[Y@GRAD]`:
```
operator.cc:142] Op(elementwise_add_grad), inputs:{Out[Out], Out@GRAD[Out@GRAD], X[MulOut], Y[Y]}, outputs:{X@GRAD[MulOut@GRAD], Y@GRAD[Y@GRAD]}.
operator.cc:142] Op(elementwise_sub_grad), inputs:{Out[MinusOut], Out@GRAD[MinusOut@GRAD], X[X], Y[Y]}, outputs:{X@GRAD[X@GRAD], Y@GRAD[Y@GRAD]}.
```

The forward test of #4500 is successful. But the backward test fails:
```
163: Traceback (most recent call last):
163:   File "test_interp_op.py", line 25, in test_check_grad_normal
163:     self.check_grad(['X', 'Y'], 'Out')
163:   File "/home/luotao02/Paddle/python/paddle/v2/framework/tests/op_test.py", line 295, in check_grad
163:     for grad_name in grad_names
163:   File "/home/luotao02/Paddle/python/paddle/v2/framework/tests/op_test.py", line 185, in get_gradient
163:     backward_op = get_backward_op(scope, op, no_grad_set)
163:   File "/home/luotao02/Paddle/python/paddle/v2/framework/tests/op_test.py", line 164, in get_backward_op
163:     backward_op = core.Operator.backward(op, no_grad_set)
163: EnforceNotMet: Type add's input Y is not set at [/home/luotao02/Paddle/paddle/framework/operator.cc:185]
```
You can pull my code and test it.

**Comment by luotao1** [comment]
Though there are `TEST(Backward, net_shared_weight)` in [backward_test.cc](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/backward_test.cc#L274), it seems no effect on Interpolation Op.
