### ISSUE TITLE
安装paddle报json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by zhangCollab** [PaddlePaddle/Paddle#45257]
### 问题描述 Issue Description

ubuntu18,4下，python版本3.7.13安装，CUDA为11.6 ，CUDNN为8.4.0，安装pddle命令一直报错，也不知道怎么回事
       #######命令：
python -m pip install paddlepaddle-gpu==2.3.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

ERROR: Exception:
Traceback (most recent call last):
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 370, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 93, in resolve
    collected.requirements, max_rounds=try_to_avoid_resolution_too_deep
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 44, in _iter_built
    for version, func in infos:
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 282, in iter_index_candidate_infos
    hashes=hashes,
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 889, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 830, in find_all_candidates
    page_candidates = list(page_candidates_it)
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/index/sources.py", line 134, in page_candidates
    yield from self._candidates_from_page(self._link)
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 794, in process_project_url
    page_links = list(parse_links(index_response))
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 313, in wrapper_wrapper
    return wrapper(CacheablePageContent(page))
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 308, in wrapper
    return list(fn(cacheable_page.page))
  File "/root/tutorial-env/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 327, in parse_links
    data = json.loads(page.content)
  File "/root/python3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/root/python3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/python3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from  None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### 版本&环境信息 Version & Environment Information

 ubuntu18,4下，python版本3.7.13安装，CUDA为11.6 ，CUDNN为8.4.0，安装pddle命令一直报错，也不知道怎么回事
       #######命令：
python -m pip install paddlepaddle-gpu==2.3.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by nemonameless** [comment]
您好，我这可以正常下载安装，显示下载链接是这个 https://paddle-wheel.bj.bcebos.com/2.3.1/linux/linux-gpu-cuda11.6-cudnn8.4.0-mkl-gcc8.2-avx/paddlepaddle_gpu-2.3.1.post116-cp37-cp37m-linux_x86_64.whl ，你可以wget下载下来再pip安装。
或者去 https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html 页面找你需要的版本的下载链接下载。

**Comment by zhangCollab** [comment]
我把pip降下到20.2.2版本就找到了

**Comment by haobibo** [comment]
疑似pip在请求https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html时得到的content type为`application/vnd.pypi.simple.v1+json;charset=UTF-8`导致pip去解析上述网页中的HTML代码。

但是torch的源就不会：` pip install --pre -U torch -f "https://download.pytorch.org/whl/cu116/torch_stable.html"`。

请 @nemonameless  @paddle-bot 排查下网页返回的header中的content type。
