### ISSUE TITLE
通过paddlex_restful新建检测训练任务或执行单张图像预测时，出现'cudaErrorInitializationError'偶发性错误。

### ISSUE THREAD

**Issue by tsing-luo** [PaddlePaddle/Paddle#45299]
### 请提出你的问题 Please ask your question

问题描述：使用paddlex_restful网页客户端新建检测训练任务时，可能会出现'cudaErrorInitializationError'错误，该错误为偶发性错误，新建训练任务几十次才可能出现一次。同时，在使用训练好的模型进行单张图片预测时也会出现该类型错误（同为偶发性），且报错信息位置一致，位于`path/to/site-packages/paddle/fluid/initializer.py`文件中。

环境信息：
```bash
appdirs            1.4.4 
astor              0.8.1
Babel              2.10.3
bce-python-sdk     0.8.74
certifi            2022.6.15
chardet            5.0.0
charset-normalizer 2.1.0
click              8.1.3
colorama           0.4.5
cycler             0.11.0
decorator          5.1.1
et-xmlfile         1.1.0
filelock           3.7.1
Flask              2.1.3
Flask-Babel        2.0.0
Flask-Cors         3.0.10
fonttools          4.34.4
future             0.18.2
idna               3.3
importlib-metadata 4.12.0
itsdangerous       2.1.2
Jinja2             3.1.2
joblib             1.1.0
kiwisolver         1.4.4
lap                0.4.0
Mako               1.2.1
MarkupSafe         2.1.1
matplotlib         3.5.2
motmetrics         1.2.5
numpy              1.23.1
onnx               1.9.0
opencv-python      4.6.0.66
openpyxl           3.0.10
opt-einsum         3.3.0
packaging          21.3
paddle-bfloat      0.1.7
paddle2onnx        0.9.8
paddlepaddle-gpu   2.3.1.post112
paddleslim         2.2.1
paddlex            2.1.0
pandas             1.4.3
Pillow             9.2.0
pip                22.0.4
platformdirs       2.5.2
protobuf           3.20.0
psutil             5.9.1
pycocotools        2.0.4
pycryptodome       3.15.0
pycuda             2021.1
pynvml             11.4.1
pyparsing          3.0.9
python-dateutil    2.8.2
pytools            2022.1.12
pytz               2022.1
PyYAML             6.0
pyzmq              23.2.0
requests           2.28.1
scikit-learn       0.23.2
scipy              1.9.0
setuptools         56.0.0
Shapely            1.8.2
six                1.16.0
tensorrt           8.0.1.6
threadpoolctl      3.1.0
tqdm               4.64.0
typing_extensions  4.3.0
urllib3            1.26.11
visualdl           2.3.0
Werkzeug           2.0.3
xlwt               1.3.0
xmltodict          0.13.0
zipp               3.8.1
```

PaddleDetection组件版本：v2.4，commit id：38f695ebdc09cdfeebc2870105442908b42f062a

python3.8.13, cuda：11.2.2，cudnn：8.1.1.33， nvidia driver：470.141.03，RTX 3070 8G

系统信息：Ubuntu20.04 LTS
```python
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0822 06:35:43.854761 775802 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0822 06:35:43.883822 775802 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

错误日志：
```log
This log file path is pdx_test_wxz/projects/P0054/T0103/err.log
注意：标志为WARNING/INFO类的仅为警告或提示类信息，非错误信息
Process Process-11:
Traceback (most recent call last):
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddlex_restful/restful/project/operate.py", line 284, in _call_paddlex_train
    train(task_path, dataset_path, params['train'])
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddlex_restful/restful/project/train/detection.py", line 224, in train
    model = detector(num_classes=num_classes, backbone=params.backbone)
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddlex/cv/models/detector.py", line 1186, in __init__
    backbone = self._get_backbone('DarkNet', norm_type=norm_type)
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddlex/cv/models/detector.py", line 114, in _get_backbone
    backbone = getattr(ppdet.modeling, backbone_name)(**params)
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddlex/ppdet/modeling/backbones/darknet.py", line 284, in __init__
    data_format=data_format)
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddlex/ppdet/modeling/backbones/darknet.py", line 66, in __init__
    bias_attr=False)
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 657, in __init__
    data_format=data_format)
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 136, in __init__
    default_initializer=_get_default_param_initializer())
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 424, in create_parameter
    default_initializer)
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "/home/imagexx/anaconda3/envs/paddlex_api/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 367, in __call__
    'std', self._std_dev, 'seed', self._seed, 'use_mkldnn', False)
OSError: (External) CUDA error(3), initialization error. 
  [Hint: 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:243)
  [operator < gaussian_random > error]
```
通过分析报错信息发现，为调用`_C_ops.gaussian_random`时出错，查询paddle更新历史发现，`_C_ops.gaussian_random`为v2.3.0版本后新加入的，尚不清楚是何作用，以及为何会出现此类偶发性错误，望解答，谢谢！

**Comment by minghaoBD** [comment]
> 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized.

您好。看到是通过paddlex的 multiprocessing方式启动的，可以尝试单进程启动吗？

**Comment by tsing-luo** [comment]
> > 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized.
> 
> 您好。看到是通过paddlex的 multiprocessing方式启动的，可以尝试单进程启动吗？

目前使用单进程是可以启动的，但由于是偶发性的，不知道会不会继续出现错误，请问以multiprocessing方式启动为什么会报这个错误呢？

**Comment by minghaoBD** [comment]
> > > 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized.
> > 
> > 
> > 您好。看到是通过paddlex的 multiprocessing方式启动的，可以尝试单进程启动吗？
> 
> 目前使用单进程是可以启动的，但由于是偶发性的，不知道会不会继续出现错误，请问以multiprocessing方式启动为什么会报这个错误呢？

也没有什么确信的依据，只是提出一个debug成本较低的猜测。可以整理一个复现脚本吗？我这边测试下。

**Comment by tsing-luo** [comment]
> > > > 'cudaErrorInitializationError'. The API call failed because the CUDA driver and runtime could not be initialized.
> > > 
> > > 
> > > 您好。看到是通过paddlex的 multiprocessing方式启动的，可以尝试单进程启动吗？
> > 
> > 
> > 目前使用单进程是可以启动的，但由于是偶发性的，不知道会不会继续出现错误，请问以multiprocessing方式启动为什么会报这个错误呢？
> 
> 也没有什么确信的依据，只是提出一个debug成本较低的猜测。可以整理一个复现脚本吗？我这边测试下。

我也没办法立刻复现bug，而且涉及到内部开发的一些代码，所以代码暂不方便贴出，目前先改为单进程启动吧，后续有问题我再想办法解决。非常感谢您的解答！

**Comment by HustleOoo** [comment]
这个bug现在解决了吗？我遇到了相同的问题，mp启动多进程调取paddle初始化函数报错
