### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ZhangzrJerry** [PaddlePaddle/Paddle#45307]
### bug描述 Describe the Bug

```python
# main.ipynb
!python -m pip install paddlepaddle==2.3.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
import paddle
```
I run the program in Jupyter but throw an error out
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
d:\项目\让我们荡起飞桨\飞桨_个贷违约\main.ipynb Cell 3 in <cell line: 2>()
...
--> 421     for method_name in paddle.tensor.tensor_method_func:
    422         if hasattr(Variable, method_name): continue
    423         method_impl = getattr(paddle.tensor, method_name, None)

AttributeError: partially initialized module 'paddle' has no attribute 'tensor' (most likely due to a circular import)
```
I have no idea about it

**Comment by minghaoBD** [comment]
![image](https://user-images.githubusercontent.com/79566150/185904779-231c7870-6dc2-4f95-a761-0bca9bbf1634.png)

I didn't reproduce your errors. You might want to check if you import something else also as 'paddle'

**Comment by ZhangzrJerry** [comment]
well, actually I can run successfully in terminal
![image](https://user-images.githubusercontent.com/87751816/185933506-fd81c357-3c84-43bb-9a11-2ff1f4a39f1e.png)
however I don't know what goes wrong in Jupyter
![image](https://user-images.githubusercontent.com/87751816/185934136-e5888ec8-8969-410c-b260-702db9e2a62d.png)

**Comment by ZhangzrJerry** [comment]
yep it can run in python, but couldn't in Jupyter on my computer
![image](https://user-images.githubusercontent.com/87751816/185935190-e2893902-5095-4dcc-bcfe-5373a5d998c1.png)

**Comment by minghaoBD** [comment]
Are you sure you are using exact the same python/paddle? It seems the environments differ somewhere. Could you double-check your environment in Jupyter?

**Comment by ZhangzrJerry** [comment]
I couldn't find out the reason of the issue. Maybe just something wrong with my Jupyter

**Comment by minghaoBD** [comment]
Yep, some similar issues can be found in jupyter's repo. You might get some insights there.

https://github.com/jupyter/notebook/issues/5543

**Comment by ViokingTung** [comment]
i have a same issue ,when install paddlepaddle with conda ,it work well,but when use paddlepaddle with docker ,it comes errors,dockerfile like this:
```
    FROM python:3.9
    ENV PYTHONUNBUFFERED=1
    
    RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
    RUN sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list
    
    RUN apt-get clean && apt-get update && apt-get -y install vim libgl1-mesa-dev nginx
    
    RUN pip config set global.index-url https://mirrors.bfsu.edu.cn/pypi/web/simple \
        && pip config set install.trusted-host mirrors.bfsu.edu.cn \
        && python -m pip install --upgrade pip \
        && pip install -r requirements.txt
    
    ...
```
requirements.txt include:
```
paddle-bfloat           0.1.7
paddle2onnx             1.0.0
paddleocr               2.6.0.1
paddlepaddle            2.3.2

```
errors:
```
   File "/usr/local/lib/python3.9/site-packages/paddleocr/__init__.py", line 14, in <module>

     from .paddleocr import *

   File "/usr/local/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 21, in <module>

     import paddle

   File "/usr/local/lib/python3.9/site-packages/paddle/__init__.py", line 27, in <module>

     monkey_patch_variable()

   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/layers/math_op_patch.py", line 421, in monkey_patch_variable

     for method_name in paddle.tensor.tensor_method_func:

 AttributeError: partially initialized module 'paddle' has no attribute 'tensor' (most likely due to a circular import)
```
check paddle:
```
# which python
/usr/local/bin/python
# python
Python 3.9.9 (main, Dec 21 2021, 10:03:34)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.__version__
'2.3.2'
>>> paddle.tensor.tensor_method_func
['matmul', 'dot', 'cov', 'norm', 'cond', 'transpose', 'lstsq', 'dist', 't', 'cross', 'cholesky', 'bmm', 'histogram', 'bincount', 'mv', 'matrix_power', 'qr', 'eigvals', 'eigvalsh', 'abs', 'acos', 'all', 'any', 'asin', 'atan', 'ceil', 'ceil_', 'cos', 'cosh', 'cumsum', 'cumprod', 'logit', 'exp', 'exp_', 'floor', 'floor_', 'increment', 'log', 'log2', 'log10', 'logsumexp', 'multiplex', 'pow', 'prod', 'reciprocal', 'reciprocal_', 'round', 'round_', 'rsqrt','rsqrt_', 'scale', 'scale_', 'sign', 'sin', 'sinh', 'sqrt', 'sqrt_', 'square', 'stanh', 'sum', 'nansum', 'nanmean', 'tanh', 'tanh_', 'add_n', 'max', 'amax', 'maximum', 'min', 'amin', 'minimum', 'fmax', 'fmin', 'mm', 'inner', 'outer', 'divide', 'floor_divide', 'remainder', 'mod', 'floor_mod', 'multiply', 'add', 'add_', 'subtract', 'subtract_', 'atan', 'logsumexp', 'inverse', 'log1p', 'erf', 'addmm', 'clip', 'clip_', 'trace', 'kron', 'kthvalue', 'isfinite', 'isinf', 'isnan', 'broadcast_shape', 'conj', 'neg', 'lgamma', 'equal', 'equal_all', 'greater_equal', 'greater_than', 'is_empty', 'less_equal', 'less_than', 'logical_and', 'logical_not', 'logical_or', 'logical_xor', 'not_equal', 'allclose', 'isclose', 'is_tensor', 'cast', 'concat', 'expand', 'broadcast_to', 'expand_as', 'flatten', 'flatten_', 'gather', 'gather_nd', 'reshape', 'reshape_', 'reverse', 'scatter', 'scatter_', 'scatter_nd_add', 'scatter_nd', 'shard_index', 'slice', 'split', 'chunk', 'tensordot', 'squeeze', 'squeeze_', 'stack', 'strided_slice', 'transpose', 'unique', 'unique_consecutive', 'unsqueeze', 'unsqueeze_', 'unstack', 'flip', 'rot90', 'unbind', 'roll', 'tile', 'argmax', 'argmin', 'argsort', 'masked_select', 'topk', 'where', 'index_select', 'nonzero', 'sort', 'index_sample', 'mean', 'std', 'var', 'numel', 'median', 'quantile', 'is_complex', 'is_integer', 'rank', 'shape', 'real','imag', 'is_floating_point', 'digamma', 'diagonal', 'trunc', 'bitwise_and', 'bitwise_or', 'bitwise_xor', 'bitwise_not', 'broadcast_tensors', 'eig', 'uniform_', 'multi_dot', 'solve', 'cholesky_solve', 'triangular_solve', 'asinh', 'atanh', 'acosh', 'lu', 'lu_unpack', 'as_complex', 'as_real', 'rad2deg', 'deg2rad', 'gcd', 'lcm', 'diff', 'mode', 'lerp', 'lerp_', 'erfinv', 'erfinv_', 'angle', 'moveaxis', 'repeat_interleave', 'take_along_axis', 'put_along_axis', 'put_along_axis_', 'exponential_']
>>>
```
