### ISSUE TITLE
GPU推理环境，多线程加载卸载模型必现程序崩溃(模型绑定同一张GPU卡)

### ISSUE THREAD

**Issue by paperHZ** [PaddlePaddle/Paddle#45437]
### 问题描述：
GPU推理环境，多线程加载卸载模型必现程序崩溃(模型绑定同一张GPU卡)
### 复现环境：
    1、基础镜像：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html   registry.baidubce.com/paddlepaddle/paddle:2.3.1-gpu-cuda11.2-cudnn8
    2、GPU推理库:  https://paddle-inference-lib.bj.bcebos.com/2.3.1/cxx_c/Linux/GPU/x86-64_gcc8.2_avx_mkl_cuda11.2_cudnn8.2.1_trt8.0.3.4/paddle_inference.tgz 
    3、显卡信息：NVIDIA-SMI 418.126.02   Driver Version: 418.126.02   CUDA Version: 10.1 
    4、CPU信息：1、Architecture: x86_64   2、Model name:  Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
### 代码
```
#include "paddle_analysis_config.h"
#include "paddle_api.h"
#include "paddle_inference_api.h"
#include "paddleTensorLoader.hpp"
#include <thread>

void runPaddleInfer(int arg) {
 for (int j = 0; j < 1000; ++j) {
  paddle_infer::Config config;
  config.SetModel("../dnn_plugin/__model__", "../dnn_plugin/params");
  config.DisableGlogInfo();
  config.EnableUseGpu(500, 1);  // 注：如果每个线程分别绑定不同的显卡，则不会有问题，当每个线程绑定相同的显卡则有问题
  config.SwitchIrOptim(true);
  config.EnableMKLDNN();
  config.SetCpuMathLibraryNumThreads(10);

  std::shared_ptr<paddle_infer::Predictor> predictor =
      paddle_infer::CreatePredictor(config);

  std::vector<std::string> inputVarNames = predictor->GetInputNames();
  std::map<std::string, std::shared_ptr<paddle_infer::Tensor>> varNameTensorMap;
  for (auto varName : inputVarNames) {
    std::shared_ptr<paddle_infer::Tensor> lodTensor;
    lodTensor = predictor->GetInputHandle(varName);
    if (varNameTensorMap.find(varName) != varNameTensorMap.end()) {
      continue;
    }
    varNameTensorMap[varName] = lodTensor;
  }

  //填充数据
  paddle::restore(varNameTensorMap);
  predictor->Run();
  
  std::vector<std::string> outputName = predictor->GetOutputNames();
  auto outputTensor = predictor->GetOutputHandle(outputName[0]);
  std::vector<int> outputShape = outputTensor->shape();
  int outNum = std::accumulate(outputShape.begin(), outputShape.end(), 1,
						   std::multiplies<int>());
  std::vector<float> out;
  out.resize(outNum);
  outputTensor->CopyToCpu(out.data());
 }
}

int main()
{
  unsigned int n = 4;
  std::vector<std::thread*> thread_pool;

  for (unsigned int i = 0; i < n; i++) {
    thread_pool.push_back(new std::thread(runPaddleInfer, i));
  }

  for (unsigned int i = 0; i < n; i++) {
    thread_pool[i]->join();
  }
  std::cout << "********out" << std::endl;
  return 0;
}
```
### 报错堆栈信息
```
Thread 2 "a.out" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff94b86700 (LWP 126135)]
std::__detail::_List_node_base::_M_unhook (this=0x7fff8816ab60) at ../../../../../gcc-8.2.0/libstdc++-v3/src/c++98/list.cc:141
141	../../../../../gcc-8.2.0/libstdc++-v3/src/c++98/list.cc: No such file or directory.
(gdb) bt
#0  std::__detail::_List_node_base::_M_unhook (this=0x7fff8816ab60) at ../../../../../gcc-8.2.0/libstdc++-v3/src/c++98/list.cc:141
#1  0x00007fffa1c6c9b3 in paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeImpl(phi::Allocation*) () from /usr/local/lib/libpaddle_inference.so
#2  0x00007fffa1c4b8e6 in paddle::memory::allocation::StreamSafeCUDAAllocation::~StreamSafeCUDAAllocation() () from /usr/local/lib/libpaddle_inference.so
#3  0x00007fffa1c4aa3c in paddle::memory::allocation::StreamSafeCUDAAllocator::FreeImpl(phi::Allocation*) () from /usr/local/lib/libpaddle_inference.so
#4  0x00007fffa1c6af72 in paddle::memory::allocation::RetryAllocator::FreeImpl(phi::Allocation*) () from /usr/local/lib/libpaddle_inference.so
#5  0x00007fffa1c2a5fd in paddle::memory::allocation::StatAllocator::FreeImpl(phi::Allocation*) () from /usr/local/lib/libpaddle_inference.so
#6  0x00007fff9cfa3be5 in std::_Sp_counted_deleter<phi::Allocation*, std::function<void (phi::Allocation*)>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() ()
   from /usr/local/lib/libpaddle_inference.so
#7  0x00007fff9c6fb327 in ?? () from /usr/local/lib/libpaddle_inference.so
#8  0x00007fff9c6fb750 in paddle::framework::Variable::PlaceholderImpl<phi::DenseTensor>::~PlaceholderImpl() () from /usr/local/lib/libpaddle_inference.so
#9  0x00007fff9c6fb327 in ?? () from /usr/local/lib/libpaddle_inference.so
#10 0x00007fff9cade74f in paddle::framework::Scope::~Scope() () from /usr/local/lib/libpaddle_inference.so
#11 0x00007fff9cae0d6a in paddle::framework::Scope::DeleteScope(paddle::framework::Scope*) const () from /usr/local/lib/libpaddle_inference.so
#12 0x00007fff9c7266ed in paddle::AnalysisPredictor::~AnalysisPredictor() () from /usr/local/lib/libpaddle_inference.so
#13 0x00007fff9c739434 in std::_Sp_counted_ptr<paddle_infer::Predictor*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() () from /usr/local/lib/libpaddle_inference.so
#14 0x0000000000410e52 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() ()
#15 0x000000000040cbcd in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() ()
#16 0x000000000040ab5a in std::__shared_ptr<paddle_infer::Predictor, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() ()
#17 0x000000000040ab76 in std::shared_ptr<paddle_infer::Predictor>::~shared_ptr() ()
#18 0x0000000000407266 in runPaddleInfer(int) ()
#19 0x00000000004147dc in void std::__invoke_impl<void, void (*)(int), unsigned int>(std::__invoke_other, void (*&&)(int), unsigned int&&) ()
#20 0x000000000040e045 in std::__invoke_result<void (*)(int), unsigned int>::type std::__invoke<void (*)(int), unsigned int>(void (*&&)(int), unsigned int&&) ()
#21 0x00000000004403c5 in decltype (__invoke((_S_declval<0ul>)(), (_S_declval<1ul>)())) std::thread::_Invoker<std::tuple<void (*)(int), unsigned int> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) ()
#22 0x00000000004402f0 in std::thread::_Invoker<std::tuple<void (*)(int), unsigned int> >::operator()() ()
#23 0x0000000000440160 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(int), unsigned int> > >::_M_run() ()
#24 0x00007fff99c7fecf in execute_native_thread_routine () at ../../../../../gcc-8.2.0/libstdc++-v3/src/c++11/thread.cc:80
#25 0x00007fff99f4c6db in start_thread (arg=0x7fff94b86700) at pthread_create.c:463
#26 0x00007fff9933761f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

### 其他补充信息 Additional Supplementary Information

**只有当模型都绑定到同一张卡上才会出现崩溃问题。**

**Comment by carryyu** [comment]
问题已解决，在最新develop分支上，更换内存分配策略为naive_best_fit后验证无误。待后续合入～

**Comment by yjbdsky** [comment]
@carryyu 请问怎么处理的(如何更换)，，我用的最新的2.5现在还有这个问题，，，
https://github.com/PaddlePaddle/Paddle/issues/58810
