### ISSUE TITLE
ExternalError: CUDA error(719), unspecified launch failure.

### ISSUE THREAD

**Issue by Cppowboy** [PaddlePaddle/Paddle#45472]
### bug描述 Describe the Bug

训练过程中报错，训练进行一段时间后报错，训练开始阶段正常

```shell
numel:162240000 idx:52096 value:0.000889
numel:162240000 idx:52097 value:0.001961
numel:162240000 idx:52098 value:-0.001101
numel:162240000 idx:137939836 value:inf
In block 50, there has 0,1,1267711 nan,inf,num
Error: /paddle/paddle/fluid/framework/details/nan_inf_utils_detail.cu:94 Assertion `false` failed. ===ERROR: in [op=matmul_grad] [tensor=softmax_34.tmp_0.cast_fp16@GRAD] find nan or inf===
Fri 26 Aug 2022 16:36:08 generation_finetune.py ERROR traceback.format_exc():Traceback (most recent call last):
  File "./generation_finetune.py", line 332, in train
    exe.run(fetch_list=[], program=train_program, use_program_cache=True)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1262, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1260, in run
    return_merged=return_merged)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1402, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1495, in _run_program
    False)
OSError: In user code:

    File "./generation_finetune.py", line 370, in <module>
      train(args)
    File "./generation_finetune.py", line 301, in train
      use_infcheck_adam=args.use_infcheck_adam)
    File "/root/paddlejob/workspace/env_run/utils/optimization.py", line 195, in optimization
      optimizer.minimize(loss)
    File "/usr/local/lib/python3.7/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 1501, in minimize
      loss, startup_program, parameter_list, no_grad_set=no_grad_set)
    File "/usr/local/lib/python3.7/site-packages/paddle/distributed/fleet/meta_optimizers/meta_optimizer_base.py", line 95, in minimize
      loss, startup_program, parameter_list, no_grad_set)
    File "/usr/local/lib/python3.7/site-packages/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py", line 516, in minimize_impl
      self._apply_sharding_pass(params_grads)
    File "/usr/local/lib/python3.7/site-packages/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py", line 298, in _apply_sharding_pass
      self._add_broadcast_allreduce(main_block)
    File "/usr/local/lib/python3.7/site-packages/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py", line 1098, in _add_broadcast_allreduce
      [calc_dep_vars[-1]])
    File "/usr/local/lib/python3.7/site-packages/paddle/distributed/fleet/meta_optimizers/sharding/utils.py", line 254, in insert_sync_calc_op
      attrs={OP_ROLE_KEY: op_role})
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3215, in _insert_op_without_sync
      op = Operator(block=self, desc=op_desc, *args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDA error(719), unspecified launch failure. 
      [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at /paddle/paddle/fluid/operators/collective/c_sync_calc_stream_op.cc:61)
      [operator < c_sync_calc_stream > error]

terminate called without an active exception


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1661502969 (unix time) try "date -d @1661502969" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x824) received by PID 2084 (TID 0x7fdab8bfd700) from PID 2084 ***]
```

### 其他补充信息 Additional Supplementary Information

paddle 2.2.2
cuda 10.2
ubuntu 16.04

**Comment by Cppowboy** [comment]
是sharding或amp导致的nan/inf还是index访问越界？

**Comment by weisy11** [comment]
报错信息确实提示为显存访问越界，可以提供下复现代码吗？
