### ISSUE TITLE
Categorical.probs(value)中建议添加对value的类别检查

### ISSUE THREAD

**Issue by yuxiaooye** [PaddlePaddle/Paddle#45558]
### bug描述 Describe the Bug

paddle版本：2.3.1 
IDE：BML CodeLab

```python
import paddle
from paddle.distribution import Categorical

logits = paddle.to_tensor([
    [0.8, 0.2],
    [0.4, 0.6]]
    )
value = paddle.to_tensor([
    [1.],
    [0.]]
    )
dist = Categorical(logits)
prob = dist.prob(value)
print(prob)  # 希望为[[0.2], [0.4]], 实际为第一次运行时为[[0.0], [0.0]]，之后运行为[[0.8], [0.2]]
```

当value为float类型tensor时，prob的结果不符合预期，且结果不可复现。另外当value为float类型且数值不是整数时（例如[[0.5], [1.2]]），代码仍可以正常运行，给出无意义的prob值。实际代码中value很可能是数值为整数的float类型tensor，导致不符合程序预期的结果。因此建议增加对value的类型检查，当value不为int型时产生报错中断程序。

参考torch的报错提示：
```python
import torch
from torch.distributions import Categorical

logits = torch.tensor([
    [0.8, 0.2],
    [0.4, 0.6]])
value = torch.tensor([
    [0.5],
    [1.2]])
dist = Categorical(logits)
prob = dist.log_prob(value)  # value不为int型，报错
print(prob)
```

```shell
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\JetBrains\PyCharm2021.1\scratches\scratch_43.py", line 9, in <module>
    prob1 = dist.log_prob(value)
  File "D:\program_files\Miniconda\envs\111\lib\site-packages\torch\distributions\categorical.py", line 117, in log_prob
    self._validate_sample(value)
  File "D:\program_files\Miniconda\envs\111\lib\site-packages\torch\distributions\distribution.py", line 277, in _validate_sample
    raise ValueError('The value argument must be within the support')
ValueError: The value argument must be within the support
```

**Comment by luotao1** [comment]
@Insomnia-y 欢迎提一个PR来修复！
