### ISSUE TITLE
解決了都依然會發生錯誤

### ISSUE THREAD

**Issue by youkeith** [PaddlePaddle/Paddle#45715]
### 请提出你的问题 Please ask your question

`Running verify PaddlePaddle program ...
W0903 19:42:39.613351 18536 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.7, Runtime API Version: 10.2
W0903 19:42:39.697345 18536 dynamic_loader.cc:276] Note: [Recommend] copy cudnn into CUDA installation directory.
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\utils\install_check.py", line 266, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\utils\install_check.py", line 170, in _run_static_single
    exe.run(startup_prog)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\executor.py", line 1299, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\executor.py", line 1285, in run
    res = self._run_impl(
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\executor.py", line 1510, in _run_impl
    return self._run_program(
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python39\lib\site-packages\paddle\fluid\executor.py", line 1607, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:303)`

這個如何解決,因為重新安裝所有軟件了,一直有問題...

**Comment by esythan** [comment]
Paddle依赖的cudnn库没有正确配置，请按照log中的建议进行配置：
1、确认cuda和cudnn正确安装，并且安装版本与Paddle对应
2、windows下请将cudnn的动态链接库地址配置到环境变量PATH中

**Comment by youkeith** [comment]
> Paddle依賴的cudnn庫沒有配置，按照log中的建議進行配置： 1、確認cuda和cudnn正確安裝，並安裝正確的版本與Paddle 2、windows下cudnn的動態鏈接地址庫配置到環境變量PATH中
cuda和cudnn檢查了沒有問題,與Paddle要求一模一樣

設置是不是這樣(set PATH= C:\Users\Owner\AppData\Local\Programs\Python\Python39\Lib\site-packages\ paddle\dynload\
dynamic_loader.cc:303)

**Comment by youkeith** [comment]
解決了,缺乏文件(cudnn64_7.dll)
