### ISSUE TITLE
run_check报CUBLAS错误

### ISSUE THREAD

**Issue by hakaboom** [PaddlePaddle/Paddle#45723]
### bug描述 Describe the Bug

```python
import paddle
paddle.utils.run_check()
```

报错信息：
```
Running verify PaddlePaddle program ... 
W0904 21:24:46.885578  1308 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.6
W0904 21:24:46.888571  1308 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Traceback (most recent call last):
  File "D:\python\rpg_error_train\main.py", line 2, in <module>
    paddle.utils.run_check()
  File "D:\python\rpg_error_train\venv\lib\site-packages\paddle\utils\install_check.py", line 266, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "D:\python\rpg_error_train\venv\lib\site-packages\paddle\utils\install_check.py", line 171, in _run_static_single
    exe.run(train_prog,
  File "D:\python\rpg_error_train\venv\lib\site-packages\paddle\fluid\executor.py", line 1299, in run
    six.reraise(*sys.exc_info())
  File "D:\python\rpg_error_train\venv\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "D:\python\rpg_error_train\venv\lib\site-packages\paddle\fluid\executor.py", line 1285, in run
    res = self._run_impl(
  File "D:\python\rpg_error_train\venv\lib\site-packages\paddle\fluid\executor.py", line 1464, in _run_impl
    return new_exe.run(list(feed.keys()), fetch_list, return_numpy)
  File "D:\python\rpg_error_train\venv\lib\site-packages\paddle\fluid\executor.py", line 547, in run
    tensors = self._new_exe.run(feed_names, fetch_list)._move_to_list()
OSError: (External) CUBLAS error(15). 
  [Hint: 'CUBLAS_STATUS_NOT_SUPPORTED'.  The functionality requested is not supported ] (at ../paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
```
nvcc
![image](https://user-images.githubusercontent.com/43911741/188315979-a74cbd28-c2ac-4ecb-9552-8e43dabf6020.png)

**Comment by zhaocaibei123** [comment]
请问装的哪个cuda版本的paddle

**Comment by zhaocaibei123** [comment]
请问装的哪个cuda版本的paddle

**Comment by hakaboom** [comment]
> 请询问装的哪个cuda版本的paddle

装的是11.6 用的链接是python -m pip install paddlepaddle-gpu==2.3.2.post116 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
