### ISSUE TITLE
单机多卡训练出现 _pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by 15554710621** [PaddlePaddle/Paddle#45798]
### 请提出你的问题 Please ask your question
```python
def eval_one_epoch(net, eval_loader, epoch, eval_dataset_len, eval_dataset_fall_len):
    with paddle.no_grad():
        net.eval()
        accuracy_sum = 0
        accuracy_fall_sum = 0
        labels_mat = paddle.to_tensor([])
        soft_out_mat = paddle.to_tensor([])
        for i,j in enumerate(eval_loader):
            values, labels = j
            labels_mat = paddle.concat([labels_mat, labels], axis=0)
            outputs = net(values)
            predicts = paddle.argmax(outputs, axis=1)
            soft_out_mat = paddle.concat([soft_out_mat, paddle.nn.functional.softmax(outputs)], axis=0)
            eq = paddle.equal(predicts, labels)
            accuracy_sum += eq.sum().item()
            labels_bool = paddle.cast(labels, dtype='bool')
            # eq = eq & (labels_bool ^ paddle.to_tensor(eval_dataset.class_to_idx['fall']==0))
            eq = eq & labels_bool
            accuracy_fall_sum += eq.sum().item()
        TP = accuracy_fall_sum
        FN = eval_dataset_fall_len - accuracy_fall_sum
        FP = eval_dataset_len - (eval_dataset_fall_len + accuracy_sum - accuracy_fall_sum)
        TN = accuracy_sum - accuracy_fall_sum
        scores_mat = soft_out_mat[:,1]
        accuracy = accuracy_sum / eval_dataset_len
        sensitivity = accuracy_fall_sum / eval_dataset_fall_len
        print(f'epoch:{epoch}, accuracy:{accuracy}, sensitivity:{sensitivity}')
        return (TP,FN,FP,TN,labels_mat.numpy(),scores_mat.numpy(),accuracy,sensitivity)

import pickle
def dictpk_appendb(file_path, key=None, value=None):
    try:
        with open(file_path, 'rb') as f:
            pass
    except FileNotFoundError:
        with open(file_path, 'wb') as f:
            pass
    if key is not None:
        with open(file_path, 'rb') as f:
            try:
                p = pickle.load(f)
            except EOFError:
                p = {}
        with open(file_path + '_备份', 'wb') as f: 
            pickle.dump(p, f)       
        with open(file_path, 'wb') as f:
            p[key] = value
            pickle.dump(p, f)



中途31分钟报错


LAUNCH INFO 2022-08-09 00:31:13,689 Pod failed
LAUNCH ERROR 2022-08-09 00:31:13,689 Container failed !!!
Container rank 3 status failed cmd ['/root/paddlejob/workspace/external-libraries/bin/python', '-u', '/root/paddlejob/workspace/code/run.py'] code 1 log /root/paddlejob/workspace/log/trainer-0/default.bsbigo.3.log 
env {'CODE_BOS_OBJECT': '4414021/161414/codeURI/', 'CUDNN_VERSION': '8.1.1.33', 'LC_ALL': 'en_US.UTF-8', 'LD_LIBRARY_PATH': '/opt/_internal/cpython-3.7.0/lib:/usr/local/python2.7.15/lib:/usr/local/openmpi-3.1.0/lib:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib/:/usr/lib64:/usr/local/cuda-11.2/targets/x86_64-linux/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64', 'PADDLE_LOG_DIR': '/root/paddlejob/workspace/log/trainer-0', 'PUBLIC_BOS_URL': 'ai-studio-cluster-infinite-task.bj.bcebos.com/public_dependency/distributelog', 'PADDLE_TRAINERS_NUM': '4', 'VK_TASK_INDEX': '0', 'LANG': 'en_US.UTF-8', 'TZ': 'Asia/Shanghai', 'PF_JOB_CLUSTER_ID': 'cluster-4577b7ec', 'HOSTNAME': 'jobpf-4414021-161414-20220809001240', 'OLDPWD': '/root/paddlejob/workspace/passl', 'LOG_BOS_SK': 'ea40003b343544edb4d376dc5f06ebd5', 'MOUNT_RECORD': 'train_data,code', 'APP_ID': 'aistudio', 'OPENMPI_HOME': '/usr/local/openmpi-3.1.0', 'WITH_GPU': 'ON', 'OUTPUT_MODEL_MOUNT_PATH': '/root/paddlejob/workspace/output', 'HOME_WORK_DIR': '/root/ppoc', 'PF_JOB_NAMESPACE': 'default', 'LOG_BOS_HOST': 'http://bj.bcebos.com', 'NVIDIA_VISIBLE_DEVICES': 'GPU-e04ad4a8-311c-015e-c397-7e8283b8c139,GPU-00d18ea3-8aba-52be-d6e6-15609c755c38,GPU-459468ec-656c-bbdb-f169-b8a1fd0dacf7,GPU-ab6cc71a-2057-9c72-33e5-01903151881a', 'VIRTUAL_ENV': '/root/paddlejob/workspace/external-libraries', 'OUTPUT_MODEL_BOS_OBJECT': '4414021/161414/output/ppoc_4414021_161414/', 'PADDLE_USE_CUDA': '1', 'KUBERNETES_PORT_443_TCP_PROTO': 'tcp', 'PF_JOB_PRIORITY': 'NORMAL', 'KUBERNETES_PORT_443_TCP_ADDR': '10.157.0.1', 'LOCAL_SYNC_PATH': '/mnt/ppoc_output_log', 'OUTPUT_PATH': '/root/paddlejob/workspace/output', 'LOG_BOS_AK': 'ed8ca96f173411ed92ddf586ef548fff', 'PADDLE_IS_LOCAL': '1', 'NCCL_VERSION': '2.8.4', 'GOPATH': '/root/gopath', 'KUBERNETES_PORT': 'tcp://10.157.0.1:443', 'WORKSPACE': '/mnt', 'PWD': '/root/paddlejob/workspace/passl', 'HOME': '/root', 'GOROOT': '/usr/local/go', 'LOG_STS_TOKEN': 'ZjkyZmQ2YmQxZTQ3NDcyNjk0ZTg1ZjYyYjlkZjNjODB8AAAAAGoFAACc+t+ACl8pT8cChBQD17PnQCBt9gNpDHZlTX9YuPSgs0DORcfPBuyAJE5nF+tCCSa6nWr+UEI6czCTSP5NFeg32xlnxcUQzu/MRMD4vp7ggeJZWGc5O0K3M9AojVrkJx2zlLpK383WiqEvsGmRVa8N40WANd+VZ5HtbQVvAT++glvLtI8d7+J8g1Ac11akDu6eZbRFFo1KokmJpqLZpQGUxzVSMZFuqrTGv0P7fuQcx+rr4UGRW/VAmwdlYr7wn4EIdu/YBSWXyr4SyrXSiH4GNSsfPriPLG85MyYJrMJneISWq5EiVlnZkC0Y2GQ3ASb1TvpH9/9NU2pRIYVOlWL66p8ckoET6q4pd+6XL4uqSUrFqAZOuqGIzpMv27K8UN0QUaz/Wj7hyH97ng38mBQ9U2H55X4i83yBVhS5RZ2+DmWdPl9dqI0jTARX4Xn7saSF7mPljD0xRsUR7eIwbMPqKZVRanC0qYwozL0m1ykD0jOZ6wuInQOnSCzO4AY8qoN5ZWD6xbwBS5jgx+j/28lPshnRbhyjGU3Dn2UZ0IyHtvJSz1X9u4W1ulb4vJo0TAmGgB461nCnpn6YpNyvWAFM/wHhS3sEEAovL4GnKBug8Q==', 'PADDLE_TRAINER_ID': '3', '_STDBUF_O': 'L', 'KUBERNETES_SERVICE_PORT_HTTPS': '443', 'OUTPUT_MODEL_BOS_BUCKET': 'ai-studio-cluster-infinite-task', 'DEBIAN_FRONTEND': 'noninteractive', 'KUBERNETES_PORT_443_TCP_PORT': '443', 'OUTPUT_MODEL_BOS_AK': 'ed8ca96f173411ed92ddf586ef548fff', 'TRAINING_ROLE': 'TRAINER', 'PUBLIC_BOS_SK': '365c4163791d4da48b6eedcef31a222d', 'LOCAL_LOG_PATH': '/root/paddlejob/workspace/log', 'LOG_BOS_BUCKET': 'ai-studio-cluster-infinite-task', 'OUTPUT_MODEL_STS_TOKEN': 'ZjkyZmQ2YmQxZTQ3NDcyNjk0ZTg1ZjYyYjlkZjNjODB8AAAAAGoFAACc+t+ACl8pT8cChBQD17PnQCBt9gNpDHZlTX9YuPSgs0DORcfPBuyAJE5nF+tCCSa6nWr+UEI6czCTSP5NFeg32xlnxcUQzu/MRMD4vp7ggeJZWGc5O0K3M9AojVrkJx2zlLpK383WiqEvsGmRVa8N40WANd+VZ5HtbQVvAT++glvLtI8d7+J8g1Ac11akDu6eZbRFFo1KokmJpqLZpQGUxzVSMZFuqrTGv0P7fuQcx+rr4UGRW/VAmwdlYr7wn4EIdu/YBSWXyr4SyrXSiH4GNSsfPriPLG85MyYJrMJneISWq5EiVlnZkC0Y2GQ3ASb1TvpH9/9NU2pRIYVOlWL66p8ckoET6q4pd+6XL4uqSUrFqAZOuqGIzpMv27K8UN0QUaz/Wj7hyH97ng38mBQ9U2H55X4i83yBVhS5RZ2+DmWdPl9dqI0jTARX4Xn7saSF7mPljD0xRsUR7eIwbMPqKZVRanC0qYwozL0m1ykD0jOZ6wuInQOnSCzO4AY8qoN5ZWD6xbwBS5jgx+j/28lPshnRbhyjGU3Dn2UZ0IyHtvJSz1X9u4W1ulb4vJo0TAmGgB461nCnpn6YpNyvWAFM/wHhS3sEEAovL4GnKBug8Q==', 'CODE_BOS_BUCKET': 'ai-studio-cluster-infinite-task', 'CODE_BOS_SK': 'ea40003b343544edb4d376dc5f06ebd5', 'LIBRARY_PATH': '/usr/local/cuda/lib64/stubs', 'CODE_STS_TOKEN': 'ZjkyZmQ2YmQxZTQ3NDcyNjk0ZTg1ZjYyYjlkZjNjODB8AAAAAGoFAACc+t+ACl8pT8cChBQD17PnQCBt9gNpDHZlTX9YuPSgs0DORcfPBuyAJE5nF+tCCSa6nWr+UEI6czCTSP5NFeg32xlnxcUQzu/MRMD4vp7ggeJZWGc5O0K3M9AojVrkJx2zlLpK383WiqEvsGmRVa8N40WANd+VZ5HtbQVvAT++glvLtI8d7+J8g1Ac11akDu6eZbRFFo1KokmJpqLZpQGUxzVSMZFuqrTGv0P7fuQcx+rr4UGRW/VAmwdlYr7wn4EIdu/YBSWXyr4SyrXSiH4GNSsfPriPLG85MyYJrMJneISWq5EiVlnZkC0Y2GQ3ASb1TvpH9/9NU2pRIYVOlWL66p8ckoET6q4pd+6XL4uqSUrFqAZOuqGIzpMv27K8UN0QUaz/Wj7hyH97ng38mBQ9U2H55X4i83yBVhS5RZ2+DmWdPl9dqI0jTARX4Xn7saSF7mPljD0xRsUR7eIwbMPqKZVRanC0qYwozL0m1ykD0jOZ6wuInQOnSCzO4AY8qoN5ZWD6xbwBS5jgx+j/28lPshnRbhyjGU3Dn2UZ0IyHtvJSz1X9u4W1ulb4vJo0TAmGgB461nCnpn6YpNyvWAFM/wHhS3sEEAovL4GnKBug8Q==', 'PADDLE_GPU_NUM': '4', 'KUBERNETES_PORT_443_TCP': 'tcp://10.157.0.1:443', 'PUBLIC_BOS_AK': 'ed9de6b9173411ed9a42752a49e63402', 'OUTPUT_MODEL_BOS_HOST': 'http://bj.bcebos.com', 'LOCAL_MOUNT_PATH': '/mnt/bos_mount', 'UPLOAD_RECORD': 'log,output_model', 'PADDLE_JOB_NAME': 'jobpf-4414021-161414-20220809001240', 'PUBLIC_STS_TOKEN': 'ZjkyZmQ2YmQxZTQ3NDcyNjk0ZTg1ZjYyYjlkZjNjODB8AAAAAKsDAAB+EQoMUhEi2FNqvMl8yPQVIMqO/9DCEc3k0vvw9Hx1SKCDJK3+vKp3ngURlgtJTkQ4ZGyAiaTUSH/AtEErMeOyeTsY8Zqa8B3NdENsPu35e/ZOCdX/mj39+eC4qVZfwch93LPEN5/wMMU2n7pUC00Qg3Fswd82bTdSstKiFZKe3HFSdBcHjRYSP4/aRjT1pXBVOvQqUf2fNai9RMCeQhqgo/M7nYZ8w39Pf2uVX67BfWm1Uu6UTg9DtD/Haj6rotbonEN5NPUd8gQ+4TnRyzpQJ2Gok3QH+u9gGdMjauf8beQktYxrcMl7QZ/puELwCH/xH49EKWfoxuH7nYLEq4+/Laann83j0GV3Nfc+nBQIjlboyOLHtzkQ4L0DiOkt4SZ23I3fHZQRUWYWQKXUHxjtZjoneFKxvCXRBG7mNJfuxseR7XX1mEMGFYzDd66DQnFGIUKa9DcNuNKdlXHYo6OWFqi9mKsUu1e4U0ji6dvFuaK42np8ukMaOPNhLiciajOQL/oV51xSkqwJUVHevxGKJ4gHUxr9jF+qPeVfYP5DwA==', 'VC_TASK_INDEX': '0', 'IS_MULTI_BOS': '1', 'WITH_AVX': 'ON', 'PF_JOB_QUEUE_NAME': 'task4card', 'OUTPUT_MODEL_BOS_SK': 'ea40003b343544edb4d376dc5f06ebd5', 'CUDA_VERSION': '11.2.1', 'JOB_ID': 'jobpf-4414021-161414-20220809001240', 'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility', 'DEPENDENCY_NAME': 'public_dependency.tar.gz', 'SHLVL': '5', 'LANGUAGE': 'en_US.UTF-8', 'START_CMD': 'sh run.sh', 'NVIDIA_REQUIRE_CUDA': 'cuda>=11.2 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450,driver<451', 'KUBERNETES_SERVICE_PORT': '443', 'LOG_MOUNT_PATH': '/root/paddlejob/workspace/log', 'MOUNT_NAME_LIST': 'code,log,output_model', 'CODE_BOS_HOST': 'http://bj.bcebos.com', 'CODE_MOUNT_PATH': '/root/paddlejob/workspace/code', 'PATH': '/root/paddlejob/workspace/external-libraries/bin:/opt/_internal/cpython-3.7.0/bin:/usr/local/openmpi-3.1.0/bin:/home/cmake-3.16.0-Linux-x86_64/bin::/usr/local/gcc-8.2/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/your_dir/usr/bin/', 'IS_STS_UPDATE': '1', 'PS1': '\\[\\e[36;1m\\]\\u\\[\\e[33;1m\\]@\\[\\e[33;1m\\]\\H \\[\\e[32;1m\\]\\W \\[\\e[31;1m\\]$ \\[\\e[0m\\]', 'CODE_BOS_AK': 'ed8ca96f173411ed92ddf586ef548fff', 'NCCL_SOCKET_IFNAME': '', 'LD_PRELOAD': '/usr/lib/x86_64-linux-gnu/coreutils/libstdbuf.so', 'KUBERNETES_SERVICE_HOST': '10.157.0.1', 'PADDLE_PORT': '12345', 'LOG_BOS_OBJECT': '4414021/161414/.schedule/ppoc_4414021_161414/log/', '_': '/root/paddlejob/workspace/external-libraries/bin/python', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'PADDLE_MASTER': '10.156.20.31:55635', 'PADDLE_GLOBAL_SIZE': '4', 'PADDLE_LOCAL_SIZE': '4', 'PADDLE_GLOBAL_RANK': '3', 'PADDLE_LOCAL_RANK': '3', 'PADDLE_TRAINER_ENDPOINTS': '10.156.20.31:48925,10.156.20.31:56675,10.156.20.31:56927,10.156.20.31:52945', 'PADDLE_CURRENT_ENDPOINT': '10.156.20.31:52945', 'PADDLE_RANK_IN_NODE': '3', 'FLAGS_selected_gpus': '3'}
LAUNCH INFO 2022-08-09 00:31:15,293 Exit code -15



Traceback (most recent call last):
  File "/root/paddlejob/workspace/code/run.py", line 152, in <module>
    main(lr,bs,train_dataset_path,eval_dataset_path,net,fold_number,test_dataset_path,pretrain_weights_path,log_path)
  File "/root/paddlejob/workspace/code/run.py", line 111, in main
    dictpk_appendb(results_path,str(lr)+'_'+str(bs),results)
  File "/mnt/code_20220809001248/dictpk_appendb.py", line 13, in dictpk_appendb
    p = pickle.load(f)
_pickle.UnpicklingError: pickle data was truncated
```

将验证结果用pickle保存出错

单卡训练不报错
多卡的时候需要怎么样通信才能将结果保存下来呢

**Comment by LemonNoel** [comment]
单机训练的时候在`paddle.distributed.get_rank()==0`的卡上保存即可。

**Comment by 15554710621** [comment]
但是不同卡取的不是不同的数据吗，我理解的是不同卡上模型相同但输出的结果不同？

**Comment by LemonNoel** [comment]
哦哦，上边说的是模型保存。保存结果的话，可以将file_path用卡号`paddle.distributed.get_rank()`来区分，避免同时写入同个文件。

**Comment by 15554710621** [comment]
可不可以每个epoch里将数据整合，然后epochs结束后一起输出呢？

**Comment by 15554710621** [comment]
我感觉要用all_gather和barrier，但是没成功。。。

**Comment by ZHUI** [comment]
可以参考这里的写法:
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/utils/helper.py#L57-L74

不太会用的话，还是自己用一些flag，一张卡上合并结果，在输出。

**Comment by ZHUI** [comment]
这里也有 all_gather的简单例子：
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/ernie-1.0/run_pretrain.py#L183-L189

**Comment by 15554710621** [comment]
好的，谢谢，我试试
