### ISSUE TITLE
paddle 如何实现多维索引切片

### ISSUE THREAD

**Issue by GreatV** [PaddlePaddle/Paddle#46213]
### 请提出你的问题 Please ask your question

paddle 如何实现如下操作：

```Python
>>> import numpy as np 
>>> a = np.random.randn(4, 4)
>>> a
array([[-0.53817856,  0.26886933,  0.23166897, -0.14635637],
       [ 1.26851834,  1.17730071,  0.02772879, -1.00755722],
       [ 0.49338692,  1.58899974, -1.31532924, -1.25873109],
       [-0.66151256, -1.15239274,  0.52636298, -0.36722689]])
>>> idx = np.array([1, 3])
>>> a[0, idx]
array([ 0.26886933, -0.14635637])
>>> a[1, idx]
array([ 1.17730071, -1.00755722])
>>> import paddle
>>> b = paddle.to_tensor(a)
>>> c = paddle.to_tensor(idx)
>>> b[1, c]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wangxin/repos/PaddleOCR/venv/lib/python3.10/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 736, in __getitem__
    return _getitem_impl_(self, item)
  File "/Users/wangxin/repos/PaddleOCR/venv/lib/python3.10/site-packages/paddle/fluid/variable_index.py", line 455, in _getitem_impl_
    raise IndexError(
IndexError: Valid index accept int or slice or ellipsis or list, but received [1, Tensor(shape=[2], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1, 3])].
```

关联问题： #35243

**Comment by an1018** [comment]
分隔切片参数，start:stop:step 来进行切片操作，其中 start、stop、step 都可缺省，对应上面的修改为b[1, 1:4:2]

更详细的切片操作可以参考[官方文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/tensor_cn.html#suoyinheqiepian)

**Comment by GreatV** [comment]
> 分隔切片参数，start:stop:step 来进行切片操作，其中 start、stop、step 都可缺省，对应上面的修改为b[1, 1:4:2]
> 
> 更详细的切片操作可以参考[官方文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/tensor_cn.html#suoyinheqiepian)

对于无规律的索引应该如何操作呢，例如，取`[0, 1, 3]`。

**Comment by GreatV** [comment]
```Python
>>> b[1][c]
Tensor(shape=[2], dtype=float64, place=Place(cpu), stop_gradient=True,
       [ 1.17730071, -1.00755722])
```
