### ISSUE TITLE
[OSError]   paddle::platform::GpuMemcpySync

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#46469]
## The paddlepaddle is compiled from develop branch source code in  a  CI test on Github when I try to merge a PR to the develop branch of PaddlePaddle.  You can refer  to  https://github.com/PaddlePaddle/Paddle/pull/46333#issuecomment-1256836470
```python
import paddle  

# just create a dense tensor on gpu
x = paddle.to_tensor([2],  place=paddle.CUDAPlace(0))
x.numpy()  # this line reports an error
```

## The error message is as follows:  
```shell
2022-09-24 09:05:53 Traceback (most recent call last):
2022-09-24 09:05:53   File "/mnt/paddle/build/python/paddle/fluid/tests/unittests/test_sparse_reshape_op.py", line 112, in test_reshape_2d
2022-09-24 09:05:53     self.check_result([2, 5], [10,], 'coo')
2022-09-24 09:05:53   File "/mnt/paddle/build/python/paddle/fluid/tests/unittests/test_sparse_reshape_op.py", line 92, in check_result
2022-09-24 09:05:53     print("dense_out.numpy():", dense_out.numpy())
2022-09-24 09:05:53 OSError: 
2022-09-24 09:05:53 
2022-09-24 09:05:53 --------------------------------------
2022-09-24 09:05:53 C++ Traceback (most recent call last):
2022-09-24 09:05:53 --------------------------------------
2022-09-24 09:05:53 0   paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)
2022-09-24 09:05:53 1   phi::backends::gpu::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)
2022-09-24 09:05:53 2   phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
2022-09-24 09:05:53 3   phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)
2022-09-24 09:05:53 
2022-09-24 09:05:53 ----------------------
2022-09-24 09:05:53 Error Message Summary:
2022-09-24 09:05:53 ----------------------
2022-09-24 09:05:53 ExternalError: CUDA error(700), an illegal memory access was encountered. 
2022-09-24 09:05:53   [Hint: Please search for the error code(700) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:259)
```

### 其他补充信息 Additional Supplementary Information

# It seems that numpy() method of a cuda dense tensor reports the error

**Comment by OccupyMars2030** [comment]
# It is my cuda kernel of sparse reshape that causes the error. It has nothing to do with PaddlePaddle framework.
