### ISSUE TITLE
【论文复现】模型动转静以后保存静态模型报错：TypeError: float() argument must be a string or a number, not 'tuple'

### ISSUE THREAD

**Issue by vax521** [PaddlePaddle/Paddle#46498]
### bug描述 Describe the Bug

调用 paddle.jit.save保存转换后的静态图模型报错
堆栈报错信息
```shell 
Traceback (most recent call last):
  File "Step6Export.py", line 71, in <module>
    export(args)
  File "Step6Export.py", line 65, in export
    paddle.jit.save(model, os.path.join(args.save_inference_dir, "inference"))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
    func(layer, path, input_spec, **configs)
  File "<decorator-gen-106>", line 2, in save
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 861, in save
    inner_input_spec, with_hook=with_hook)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
    *desired_input_spec, with_hook=with_hook)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
    **cache_key.kwargs)
  File "<decorator-gen-104>", line 2, in from_func_spec
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
TypeError: In transformed code:

    File "/home/aistudio/PaddleVisionLAN/VisionLAN.py", line 182, in forward
        def forward(self, input, label_pos="", training_stp="", Train_in=True):
            # extract feature
            features = self.backbone(input)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            # MLM + VRM
            if Train_in:

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
        return self._dygraph_call_func(*inputs, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
        outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpnsjjrilg.py", line 32, in forward
        globals())), true_fn_1, false_fn_1, (out_features, tmp_shape, x), (
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 314, in __impl__
        current_block(self), value=other_var, dtype=lhs_dtype)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 98, in create_scalar
        return create_tensor(block, value, dtype, shape=[1])
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 82, in create_tensor
        value = float(value)

    TypeError: float() argument must be a string or a number, not 'tuple'
```
bug复现的代码地址： 我发现了一篇高质量的实训项目，使用免费算力即可一键运行，还能额外获取8小时免费GPU运行时长，快来Fork一下体验吧。
【论文复现】反向对齐paddle模型梯度异常梯度无法正常打印 #46368：https://aistudio.baidu.com/aistudio/projectdetail/4580735?contributionType=1&sUid=48323&shared=1&ts=1664180113770
复现步骤  
```shell
cd PaddleVisionLAN/
pip install -r requirements.txt
python Step6Export.py 
```

**Comment by XYZ-916** [comment]
你好，在你提供的复现代码中并没有找到Step6Export.py 文件，请确认是否上传。

**Comment by vax521** [comment]
> 你好，在你提供的复现代码中并没有找到Step6Export.py 文件，请确认是否上传。

重新生成了版本，麻烦再看一下

**Comment by XYZ-916** [comment]
请根据该调试文档确认下是哪一行模型代码导致的错误：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/jit/debugging_cn.html
