### ISSUE TITLE
visualdl 出现错误

### ISSUE THREAD

**Issue by hitbuyi** [PaddlePaddle/Paddle#46503]
### 请提出你的问题 Please ask your question

使用  visualdl --model deploy/inference.pdmodel  inference.为产生的模型，出现了如下错误： 

(pddl) hitbuyi@hitbuyi-Dell-G15-5511:~/PycharmProjects/padlepadle|_project/SMOKE$ visualdl --model ./deploy/inference.pdmodel
VisualDL 2.4.0
Traceback (most recent call last):
  File "/home/hitbuyi/.conda/envs/pddl/bin/visualdl", line 8, in <module>
    sys.exit(main())
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/server/app.py", line 198, in main
    _run(args)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/server/app.py", line 179, in _run
    app = create_app(args)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/server/app.py", line 70, in create_app
    profiler_api_call = create_profiler_api_call(args.logdir)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_server.py", line 302, in create_profiler_api_call
    api = ProfilerApi(logdir)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_server.py", line 24, in __init__
    self._reader = ProfilerReader(logdir)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_reader.py", line 66, in __init__
    self.runs()
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_reader.py", line 111, in runs
    self.profile_runs(update=update)
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_reader.py", line 97, in profile_runs
    flush_walks = self.get_all_walk()
  File "/home/hitbuyi/.conda/envs/pddl/lib/python3.7/site-packages/visualdl/component/profiler/profiler_reader.py", line 75, in get_all_walk
    for dir in self.dir:
TypeError: 'NoneType' object is not iterable

**Comment by XYZ-916** [comment]
你好，能否提供下复现的模型和代码。

**Comment by hitbuyi** [comment]
> 你好，能否提供下复现的模型和代码。

模型为
链接: https://pan.baidu.com/s/1dZXfu6X3tuw0asxRNrL5ZQ 提取码: 8n22
代码:
>> visualdl --model ./deploy/smoke_kitti.pdmodel
paddlepaddle 2.3.2
visualdl: 2.4.0, （2.4.1也试过，错误提示码类似）
conda: 4.13.0

**Comment by XYZ-916** [comment]
你的logdir参数没有指定，默认是空，所以会报错。请尝试设置该参数。

**Comment by hitbuyi** [comment]
> 你的logdir参数没有指定，默认是空，所以会报错。请尝试设置该参数。

我只想看模型结构，不看其它信息，这个指令也是你们给出的官方指令，见[这里](https://github.com/PaddlePaddle/models/tree/develop/PaddleCV/3d_vision/SMOKE)
