### ISSUE TITLE
AttributeError: 'ParallelEnv' object has no attribute '_device_id'

### ISSUE THREAD

**Issue by moonriseny** [PaddlePaddle/Paddle#46748]
### bug描述 Describe the Bug

Hi there,

I am trying to run the example on page https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/kie/README.md

# just predict using SER trained model
python3 tools/infer_kie_token_ser.py \
  -c configs/kie/vi_layoutxlm/ser_vi_layoutxlm_xfund_zh.yml \
  -o Architecture.Backbone.checkpoints=./pretrained_model/ser_vi_layoutxlm_xfund_pretrained/best_accuracy \
  Global.infer_img=./ppstructure/docs/kie/input/zh_val_42.jpg

Got following error:
Traceback (most recent call last):
  File "tools/infer_kie_token_ser.py", line 116, in <module>
    config, device, logger, vdl_writer = program.preprocess()
  File "/home/sheng/PaddleOCR/tools/program.py", line 651, in preprocess
    device = 'gpu:{}'.format(dist.ParallelEnv()
  File "/home/sheng/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 200, in device_id
    return self._device_id
AttributeError: 'ParallelEnv' object has no attribute '_device_id'

I have paddlepaddle-gpu installed, when I checked GPU in Python, it looked fine to me 

>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 CPU.
W1004 13:31:41.203050 31028 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 CPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

Any idea of what's going wrong?

Thanks

Sheng Li

**Comment by moonriseny** [comment]
Hi there,
Found the solution, I need to specify the version and CUDA version in my system when installing paddlepaddle-gpu, here is my command
conda install paddlepaddle-gpu==2.3.2 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
Now everything works. You can close this case.
Thanks.
Sheng
