### ISSUE TITLE
[需求] 请求 index_sample op 支持 fp16 kernel

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/Paddle#46899]
### 需求描述 Feature Description

请求，index_sample op 支持 fp16 kernel
```python
Traceback (most recent call last):
  File "run_glue_trainer.py", line 402, in <module>
    main()
  File "run_glue_trainer.py", line 388, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/ssd2/zhonghui03/Datasets/PaddleNLP/paddlenlp/trainer/trainer_base.py", line 697, in train
    ignore_keys_for_eval)
  File "/ssd2/zhonghui03/Datasets/PaddleNLP/paddlenlp/trainer/trainer_base.py", line 825, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/ssd2/zhonghui03/Datasets/PaddleNLP/paddlenlp/trainer/trainer_base.py", line 1522, in evaluate
    metric_key_prefix=metric_key_prefix,
  File "/ssd2/zhonghui03/Datasets/PaddleNLP/paddlenlp/trainer/trainer_base.py", line 1621, in evaluation_loop
    ignore_keys=ignore_keys)
  File "run_glue_trainer.py", line 258, in prediction_step
    max_length=5,
  File "/ssd2/zhonghui03/anaconda3/envs/py37/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/ssd2/zhonghui03/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 356, in _decorate_function
    return func(*args, **kwargs)
  File "/ssd2/zhonghui03/Datasets/PaddleNLP/paddlenlp/transformers/generation_utils.py", line 889, in generate
    **model_kwargs)
  File "/ssd2/zhonghui03/Datasets/PaddleNLP/paddlenlp/transformers/generation_utils.py", line 975, in greedy_search
    next_scores = paddle.index_sample(probs, next_tokens)
  File "/ssd2/zhonghui03/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/tensor/search.py", line 757, in index_sample
    return _C_ops.index_sample(x, index)
RuntimeError: (NotFound) The kernel with key (GPU, NCHW, float16) of kernel `index_sample` is not registered and fail to fallback to CPU one.
  [Hint: Expected kernel_iter != iter->second.end(), but received kernel_iter == iter->second.end().] (at /paddle/paddle/phi/core/kernel_factory.cc:152)

```

**Comment by wuyefeilin** [comment]
已收到请求，我们将会尽快进行评估实现
