### ISSUE TITLE
 from paddlenlp import Taskflow DLL

### ISSUE THREAD

**Issue by ordin9** [PaddlePaddle/Paddle#46988]
### 请提出你的问题 Please ask your question

Traceback (most recent call last):
  File "G:/Py4e/知识图谱/uie_test.py", line 2, in <module>
    from paddlenlp import Taskflow
  File "G:\anaconda3\lib\site-packages\paddlenlp\__init__.py", line 24, in <module>
    from . import data
  File "G:\anaconda3\lib\site-packages\paddlenlp\data\__init__.py", line 16, in <module>
    from .data_collator import *
  File "G:\anaconda3\lib\site-packages\paddlenlp\data\data_collator.py", line 23, in <module>
    from ..transformers.tokenizer_utils_base import BatchEncoding, PretrainedTokenizerBase, PaddingStrategy
  File "G:\anaconda3\lib\site-packages\paddlenlp\transformers\__init__.py", line 104, in <module>
    from .ernie_vil.modeling import *
  File "G:\anaconda3\lib\site-packages\paddlenlp\transformers\ernie_vil\modeling.py", line 26, in <module>
    from ..clip.modeling import VisionTransformer, clip_loss
  File "G:\anaconda3\lib\site-packages\paddlenlp\transformers\clip\modeling.py", line 25, in <module>
    from ..stable_diffusion_utils import StableDiffusionMixin, AutoencoderKL, PNDMScheduler, LMSDiscreteScheduler, DDIMScheduler, UNet2DConditionModel
  File "G:\anaconda3\lib\site-packages\paddlenlp\transformers\stable_diffusion_utils\__init__.py", line 3, in <module>
    from .schedulers import (LMSDiscreteScheduler, PNDMScheduler, DDIMScheduler,
  File "G:\anaconda3\lib\site-packages\paddlenlp\transformers\stable_diffusion_utils\schedulers.py", line 20, in <module>
    from scipy import integrate
  File "G:\anaconda3\lib\site-packages\scipy\integrate\__init__.py", line 90, in <module>
    from ._quadrature import *
  File "G:\anaconda3\lib\site-packages\scipy\integrate\_quadrature.py", line 12, in <module>
    from scipy.special import roots_legendre
  File "G:\anaconda3\lib\site-packages\scipy\special\__init__.py", line 646, in <module>
    from . import _basic
  File "G:\anaconda3\lib\site-packages\scipy\special\_basic.py", line 16, in <module>
    from . import orthogonal
  File "G:\anaconda3\lib\site-packages\scipy\special\orthogonal.py", line 81, in <module>
    from scipy import linalg
  File "G:\anaconda3\lib\site-packages\scipy\linalg\__init__.py", line 195, in <module>
    from .misc import *
  File "G:\anaconda3\lib\site-packages\scipy\linalg\misc.py", line 4, in <module>
    from .lapack import get_lapack_funcs
  File "G:\anaconda3\lib\site-packages\scipy\linalg\lapack.py", line 818, in <module>
    from scipy.linalg import _flapack
ImportError: DLL load failed: 找不到指定的程序。

**Comment by kuizhiqing** [comment]
看报错在
`from scipy.linalg import _flapack` 
请先确保 scipy 安装配置正确。
如果还有问题，请提供更多信息。
