### ISSUE TITLE
分布式训练，在脚本里设置了IP和端口信息，但是日志里显示得IP是127.0.1.1

### ISSUE THREAD

**Issue by Eddie-zhg** [PaddlePaddle/Paddle#47130]
### 请提出你的问题 Please ask your question

采用两台机子本地部署分布式训练，两台机子使用网线连接起来的，是通的。运行的示例是wide_and_deep_dataset里的文件。
在train.py脚本里，进行下图所示的IP和端口设置：
![2022-10-19 10-38-24屏幕截图](https://user-images.githubusercontent.com/82798516/196587984-795132a4-db79-498a-a097-3a08a3dbd321.png)

日志里显示的如下图所示，endpoint：127.0.1.1：
![Inked2022-10-19 10-39-15屏幕截图](https://user-images.githubusercontent.com/82798516/196588257-fd986722-b9a0-4cac-814e-46d0131eff2c.jpg)

有两个问题：
1、我的IP和端口设置的是否正确 
2、日志里显示的仍是127.0.1.1需要如何解决

**Comment by wangzhen38** [comment]
IP端口设置，可以参考下，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/launch_cn.html
另外，新版本不用设端口号，自动检测的

**Comment by Eddie-zhg** [comment]
参看后更改了启动命令，出下面的问题了，这个是哪里出错了？
$ python -m paddle.distributed.launch --servers="169.254.60.61:36011" --workers="169.254.94.75:36011" train.py --lr=0.01
LAUNCH INFO 2022-10-19 15:12:10,743 -----------  Configuration  ----------------------
LAUNCH INFO 2022-10-19 15:12:10,744 devices: None
LAUNCH INFO 2022-10-19 15:12:10,744 elastic_level: -1
LAUNCH INFO 2022-10-19 15:12:10,744 elastic_timeout: 30
LAUNCH INFO 2022-10-19 15:12:10,744 gloo_port: 6767
LAUNCH INFO 2022-10-19 15:12:10,744 host: None
LAUNCH INFO 2022-10-19 15:12:10,744 job_id: default
LAUNCH INFO 2022-10-19 15:12:10,744 legacy: False
LAUNCH INFO 2022-10-19 15:12:10,744 log_dir: log
LAUNCH INFO 2022-10-19 15:12:10,744 log_level: INFO
LAUNCH INFO 2022-10-19 15:12:10,744 master: None
LAUNCH INFO 2022-10-19 15:12:10,744 max_restart: 3
LAUNCH INFO 2022-10-19 15:12:10,744 nnodes: 1
LAUNCH INFO 2022-10-19 15:12:10,744 nproc_per_node: None
LAUNCH INFO 2022-10-19 15:12:10,744 rank: -1
LAUNCH INFO 2022-10-19 15:12:10,744 run_mode: collective
LAUNCH INFO 2022-10-19 15:12:10,744 server_num: None
LAUNCH INFO 2022-10-19 15:12:10,744 servers: 169.254.60.61:36011
LAUNCH INFO 2022-10-19 15:12:10,744 trainer_num: None
LAUNCH INFO 2022-10-19 15:12:10,744 trainers:
LAUNCH INFO 2022-10-19 15:12:10,744 training_script: train.py
LAUNCH INFO 2022-10-19 15:12:10,744 training_script_args: ['--lr=0.01']
LAUNCH INFO 2022-10-19 15:12:10,744 with_gloo: 0
LAUNCH INFO 2022-10-19 15:12:10,744 --------------------------------------------------
LAUNCH WARNING 2022-10-19 15:12:10,744 Compatible mode enable with args ['--workers=169.254.94.75:36011']
-----------  Configuration Arguments -----------
backend: auto
cluster_topo_path: None
elastic_pre_hook: None
elastic_server: None
enable_auto_mapping: False
force: False
heter_devices:
heter_worker_num: None
heter_workers:
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
rank_mapping_path: None
run_mode: None
scale: 0
server_num: None
servers: 169.254.60.61:36011
training_script: train.py
training_script_args: ['--lr=0.01']
worker_num: None
workers: 169.254.94.75:36011
------------------------------------------------
INFO 2022-10-19 15:12:10,745 launch.py:494] Run parameter-sever mode. pserver arguments:['--servers', '--workers'], accelerators count:0
INFO 2022-10-19 15:12:10,745 launch.py:494] Run parameter-sever mode. pserver arguments:['--servers', '--workers'], accelerators count:0
WARNING 2022-10-19 15:12:10,745 launch.py:714] launch start with CPUONLY mode
WARNING 2022-10-19 15:12:10,745 launch.py:714] launch start with CPUONLY mode
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/launch/__main__.py", line 17, in <module>
    launch()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/launch/main.py", line 241, in launch
    launch.launch()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/fleet/launch.py", line 726, in launch
    launch_ps(args, distribute_mode)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/fleet/launch.py", line 430, in launch_ps
    ps_launcher = ParameterServerLauncher(args, distribute_mode)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/fleet/launch_utils.py", line 1184, in __init__
    self.get_role_endpoints(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/fleet/launch_utils.py", line 1421, in get_role_endpoints
    assert self.current_node_ip in self.node_ips, "Can't find your local ip {%s} in args.servers and args.workers ips: {%s}" \
AssertionError: Can't find your local ip {127.0.1.1} in args.servers and args.workers ips: {['169.254.60.61', '169.254.94.75']}

**Comment by Eddie-zhg** [comment]
目前的情况是，本地部署两台机子，一台当server，一台当worker，进行PS分布式训练。

**Comment by wangzhen38** [comment]
可以参考下这个[ISSUE](https://github.com/PaddlePaddle/Paddle/issues/34533) ～

**Comment by Eddie-zhg** [comment]
你好，参考了试了一下。
![屏幕截图 2022-10-19 164751](https://user-images.githubusercontent.com/82798516/196643142-802a0355-916a-460e-8403-a79d7536994f.png)
按照图中1方案来运行，结果还是报一样的错。
按照2来，export POD_IP=169.254.60.61 （这个是我server的ip），server端能正常运行，一直卡在下图步骤，ctrl+c结束。
![2022-10-19 16-53-08屏幕截图](https://user-images.githubusercontent.com/82798516/196645063-3c189740-737d-4392-9460-bb1b1a169eec.png)
在worker端类似的进行，export POD_IP=169.254.94.75，见下图
![2022-10-19 16-58-20屏幕截图](https://user-images.githubusercontent.com/82798516/196646637-18f09ce9-ce86-445c-9d54-c735e523dada.png)
![2022-10-19 16-58-46屏幕截图](https://user-images.githubusercontent.com/82798516/196646650-05180676-7928-4122-85eb-cf10cdeb37dd.png)
worker端出现问题了。请问该如何解决。

**Comment by Eddie-zhg** [comment]
补充一张图，是server端卡住按ctrl+c结束后的反馈内容
![2022-10-19 17-09-39屏幕截图](https://user-images.githubusercontent.com/82798516/196649535-0e307144-e9f3-4620-a461-279f0aad0024.png)
有一个疑问，这个是server处于在等待worker的状态吗？

**Comment by kuizhiqing** [comment]
试试这个，

server 端
```
export POD_IP=169.254.60.61
fleetrun --master=169.254.60.61:8090 --nnodes=2 --server_num=1 train.py --lr=0.01
```
worker 端
```
export POD_IP=169.254.94.75
fleetrun --master=169.254.60.61:8090 --nnodes=2 --trainer_num =1 train.py --lr=0.01
```

**Comment by Eddie-zhg** [comment]
尝试了。还是有错误。
**server端：**
![2022-10-24 11-05-36屏幕截图](https://user-images.githubusercontent.com/82798516/197440957-c657ee2a-cfbc-492f-ab62-49203f953daa.png)
![2022-10-24 11-05-50屏幕截图](https://user-images.githubusercontent.com/82798516/197440965-7bb52b4f-91e0-4a88-945f-6b0f85f5e0d9.png)
**worker端：**
![2022-10-24 11-04-52屏幕截图](https://user-images.githubusercontent.com/82798516/197441034-b6133cc8-d64a-4394-af7b-0e28c06a0689.png)
![2022-10-24 11-05-11屏幕截图](https://user-images.githubusercontent.com/82798516/197441039-8c501df3-04fd-4467-89a8-641c4383c831.png)

**Comment by kuizhiqing** [comment]
这里的启动过程已经正常，报错是程序错误导致异常退出。请检查程序代码是否正常或者从官网的例子开始使用。

**Comment by Eddie-zhg** [comment]
[您好，我是使用[官网例子。](https://github.com/PaddlePaddle/PaddleFleetX/tree/old_develop/examples/wide_and_deep_dataset)

下面是train.py的代码。参照别人“文档体验评估”而修改的train.py，检查了一下和别人的是一样的，应该是没什么问题的。
import paddle.distributed.fleet as fleet
import os
from model import WideDeepModel
import paddle
paddle.enable_static()

fleet.init(is_collective=False)

model = WideDeepModel()
model.net(is_train=True)

dataset = paddle.distributed.QueueDataset()
thread_num = 1
batch_size = 1
train_data_path = "./data/"
dataset.init(use_var=model.inputs,
             pipe_command="python reader.py",
             batch_size=batch_size,
             thread_num=thread_num)

train_files_list = [os.path.join(train_data_path, x)
                      for x in os.listdir(train_data_path)]
dataset.set_filelist(train_files_list)

strategy = fleet.DistributedStrategy()
strategy.a_sync = True

optimizer = paddle.optimizer.SGD(learning_rate=0.0001)
optimizer = fleet.distributed_optimizer(optimizer, strategy)
optimizer.minimize(model.loss)


if fleet.is_server():
    fleet.init_server()
    fleet.run_server()

if fleet.is_worker():
    place = paddle.CPUPlace()
    exe = paddle.static.Executor(place)
    exe.run(paddle.static.default_startup_program())

    fleet.init_worker()

    for epoch_id in range(1):
        exe.train_from_dataset(paddle.static.default_main_program(),
                               dataset,
                               paddle.static.global_scope(),
                               debug=False,
                               fetch_list=[model.loss],
                               fetch_info=["loss"],
                               print_period=1)

    fleet.stop_worker()

**Comment by Eddie-zhg** [comment]
运行的时候，会卡在标红位置，按ctrl+c终止的。
![111](https://user-images.githubusercontent.com/82798516/197455923-1e91b5eb-5776-4d1c-af84-1c9dc3560447.jpg)
