### ISSUE TITLE
标签图维度出错

### ISSUE THREAD

**Issue by zjliu-cs** [PaddlePaddle/Paddle#47182]
### 请提出你的问题 Please ask your question

标签图是灰度图，输出的numpy数组也只是个二维数组。

错误信息
```
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Traceback (most recent call last):
  File "./utils/main.py", line 52, in <module>
    save_dir='./output/unet1')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1767, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 2097, in _run_one_epoch
    outs = getattr(self, mode + '_batch')(*_inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1093, in train_batch
    loss = self._adapter.train_batch(inputs, labels, update)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 730, in train_batch
    losses = self.model._loss(*(to_list(outputs) + labels))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/loss.py", line 406, in forward
    name=self.name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 1738, in cross_entropy
    'use_softmax', use_softmax)
ValueError: (InvalidArgument) If Attr(soft_label) == false, the axis dimension of Input(Label) should be 1.
  [Hint: Expected labels_dims[axis] == 1UL, but received labels_dims[axis]:3 != 1UL:1.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:193)
  [operator < softmax_with_cross_entropy > error]
```

```
from paddle.io import Dataset
from PIL import Image
import numpy as np
import cv2
from paddle.vision.transforms import ToTensor


class MyDataset(Dataset):
    # 初始化
    def __init__(self, mode, train_path=None, val_path=None, test_path=None, separator=' ', 
                img_color_mode='RGB', label_color_mode='L', image_transforms=None, label_transforms=None):
        super().__init__()
        self._mode = mode
        self._train_path = train_path
        self._val_path = val_path
        self._test_path = test_path
        self._img_color_mode = img_color_mode
        self._label_color_mode = label_color_mode
        self._separator = separator
        self._image_transforms = image_transforms
        self._label_transforms = label_transforms

        self._path = ''
        self._images = []
        self._label_images = []

        # 断言语句，判断输入参数是否正确
        assert self._mode in ['train', 'val', 'test'], \
            "mode should be 'train' or 'val' or 'test', but got {}".format(self._mode)
        if __debug__:
            if self._mode == 'train':
                if self._train_path is None:
                    print('train_path must have value if mode is train')
                    raise AssertionError
                else:
                    self._path = self._train_path
            elif self._mode == 'val':
                if self._val_path is None:
                    print('val_path must have value if mode is val')
                else:
                    self._path = self._val_path
            else:
                if self._test_path is None:
                    print('test_path must have value if mode is test')
                else:
                    self._path = self._test_path
        # 初始化文件
        print(self._path)
        with open(self._path, 'r') as f:
            if self._mode == 'test':
                for l in f.readlines():
                    self._images.append(l)
            else:
                for l in f.readlines():
                    image, label = l.strip().split(self._separator)
                    self._images.append(image)
                    self._label_images.append(label)

    def __getitem__(self, index):
        img_path = self._images[index]
        label_path = self._label_images[index]
        #image = Image.open(img_path)
        image = cv2.imread(img_path)[..., ::-1]
        if self._image_transforms is not None:
            image = self._image_transforms(image)
            
        if self._mode in ['train', 'val']:
            label = cv2.imread(label_path, flags=0)[..., ::-1]  #读取灰度图
            print('label.shape:',label.shape)
            if self._label_transforms is not None:
                label = self._label_transforms(label)
            return image, label
        return image


    def __len__(self):
        return len(self._images)
```

**Comment by GuoxiaWang** [comment]
是不是 loss 函数没按照要求输入？

**Comment by zjliu-cs** [comment]
是的，我错误的设置了`loss=paddle.nn.CrossEntropyLoss(axis=1)`，但是我把axis属性删除或设为2，还是报错
```
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:2 != labels_dims[i]:3.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:164)
```

**Comment by zjliu-cs** [comment]
我使用的是Unet网络，似乎是标签维度和模型输出不同导致，但我现在不知道怎么调整模型输出
```
import paddle
from Encoder import Encoder
from Decoder import Decoder
class Net(paddle.nn.Layer):
    def __init__(self, num_classes):
        super(Net, self).__init__()
        self.conv_1 = paddle.nn.Conv2D(3, 32, kernel_size=3, stride=2, padding='same')
        self.bn = paddle.nn.BatchNorm2D(32)
        self.relu = paddle.nn.ReLU()

        in_channels = 32
        self.encoders = []
        self.encoder_list = [64, 128, 256]
        self.decoder_list = [256, 128, 64, 32]

        for out_channels in self.encoder_list:
            block = self.add_sublayer('encoder_{}'.format(out_channels),Encoder(in_channels, out_channels))
            self.encoders.append(block)
            in_channels = out_channels
        
        self.decoders = []

        for out_channels in self.decoder_list:
            block = self.add_sublayer('decoder_{}'.format(out_channels), Decoder(in_channels, out_channels))
            self.decoders.append(block)
            in_channels = out_channels
        
        self.output_conv = paddle.nn.Conv2D(in_channels, num_classes, kernel_size=3, padding='same')
    
    def forward(self, inputs):
        y = self.conv_1(inputs)
        y = self.bn(y)
        y = self.relu(y)

        for encoder in self.encoders:
            y = encoder(y)
        
        for decoder in self.decoders:
            y = decoder(y)
        
        y = self.output_conv(y)
        return y


from paddle.nn import functional as F
import numpy as np 
import paddle

class SeparableConv2D(paddle.nn.Layer):
    def __init__(self, 
                in_channels,
                out_channels, 
                kernel_size, 
                stride=1, 
                padding=0, 
                dilation=1, 
                groups=None, 
                weight_attr=None, 
                bias_attr=None, 
                data_format='NCHW'):
        super(SeparableConv2D, self).__init__()
        self._padding = padding
        self._stride = stride
        self._dilation = dilation
        self._in_channels = in_channels
        self._data_format = data_format

        #第一次卷积参数，没有偏置参数
        filter_shape = [in_channels, 1] + self.convert_to_list(kernel_size, 2, 'kernel_size')
        self.weight_conv = self.create_parameter(shape=filter_shape, attr=weight_attr)
        
        #第二次卷积参数
        filter_shape = [out_channels, in_channels] + self.convert_to_list(1, 2, 'kernel_size')
        self.weight_pointwise = self.create_parameter(shape=filter_shape,attr=weight_attr)
        self.bias_pointwise = self.create_parameter(shape=[out_channels], attr=bias_attr,is_bias=True)
    
    def convert_to_list(self, value, n, name, dtype=np.int):
        if isinstance(value, dtype):
            return [value, ] * n
        else:
            try:
                value_list = list(value)
            except TypeError:
                raise ValueError("The " + name +"'s type must be list or tuple. Received: " + str(value))
            if len(value_list) != n:
                raise ValueError("The " + name + "'s length must be " + str(n) +". Received: " + str(value))
            for single_value in value_list:
                try:
                    dtype(single_value)
                except (ValueError, TypeError):
                    raise ValueError("The " + name + "'s type must be a list or tuple of" + str(n) + " " + str(dtype) + ". Received: " + \
                    str(value) + " including element " + str(single_value) + " of type " + str(type(single_value)))
        return value_list

    def forward(self, inputs):
        conv_out = F.conv2d(inputs, self.weight_conv, padding=self._padding,
                            stride=self._stride, dilation=self._dilation, 
                            groups=self._in_channels, data_format=self._data_format)
        out = F.conv2d(conv_out, self.weight_pointwise, bias=self.bias_pointwise,
                    padding=0,stride=1,dilation=1,groups=1,data_format=self._data_format)
        return out


import paddle
from SeparableConv2D import SeparableConv2D

class Encoder(paddle.nn.Layer):
    def __init__(self, in_channels, out_channels):
        super(Encoder, self).__init__()

        self.relus = paddle.nn.LayerList([paddle.nn.ReLU() for i in range(2)])
        self.separable_conv_01 = SeparableConv2D(in_channels, out_channels, kernel_size=3,padding='same')
        self.bns = paddle.nn.LayerList([paddle.nn.BatchNorm2D(out_channels) for i in range(2)])
        self.separable_conv_02 = SeparableConv2D(out_channels, out_channels, kernel_size=3, padding='same')
        self.pool = paddle.nn.MaxPool2D(kernel_size=3,stride=2, padding=1)
        self.residual_conv = paddle.nn.Conv2D(in_channels, out_channels, kernel_size=1, stride=2,
                                            padding='same')
    
    def forward(self, inputs):
        previous_block_activation = inputs
        y = self.relus[0](inputs)
        y = self.separable_conv_01(y)
        y = self.bns[0](y)
        y = self.relus[1](y)
        y = self.separable_conv_02(y)
        y = self.bns[1](y)
        y = self.pool(y)

        residual = self.residual_conv(previous_block_activation)
        y = paddle.add(y, residual)
        return y



import paddle
class Decoder(paddle.nn.Layer):
    def __init__(self, in_channels, out_channels):
        super(Decoder, self).__init__()

        self.relus = paddle.nn.LayerList([paddle.nn.ReLU() for i in range(2)])

        self.conv_transpose_01 = paddle.nn.Conv2DTranspose(in_channels, out_channels, kernel_size=3, padding=1)
        self.conv_transpose_02 = paddle.nn.Conv2DTranspose(out_channels, out_channels, 
                                                            kernel_size=3, padding=1)
        self.bns = paddle.nn.LayerList([paddle.nn.BatchNorm2D(out_channels) for i in range(2)])
        self.upsamples = paddle.nn.LayerList([paddle.nn.Upsample(scale_factor=2.0) for i in range(2)])
        self.residual_conv = paddle.nn.Conv2D(in_channels, out_channels, kernel_size=1, padding='same')

    def forward(self, inputs):
        previous_block_activation = inputs

        y = self.relus[0](inputs)
        y = self.conv_transpose_01(y)
        y = self.bns[0](y)
        y = self.relus[1](y)
        y = self.conv_transpose_02(y)
        y = self.bns[1](y)
        y = self.upsamples[0](y)

        residual = self.upsamples[1](previous_block_activation)
        residual = self.residual_conv(residual)

        y = paddle.add(y, residual)
        return y
```

**Comment by zjliu-cs** [comment]
已解决。本来使用PIL读取图片 ，然后transforms.transpose转为CHW，后来改为cv直接读取CHW，没改过来
