### ISSUE TITLE
CrossEntropyLoss中Label的维度为什么是1

### ISSUE THREAD

**Issue by zjliu-cs** [PaddlePaddle/Paddle#47202]
### 请提出你的问题 Please ask your question

使用的是CrossEntropyLoss()，报错。后续设置参数为axis=2，同样的错
```
Epoch 1/10000
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Traceback (most recent call last):
  File "./utils/main.py", line 51, in <module>
    save_dir='./output/unet1')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1767, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 2097, in _run_one_epoch
    outs = getattr(self, mode + '_batch')(*_inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1093, in train_batch
    loss = self._adapter.train_batch(inputs, labels, update)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 730, in train_batch
    losses = self.model._loss(*(to_list(outputs) + labels))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/loss.py", line 406, in forward
    name=self.name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 1738, in cross_entropy
    'use_softmax', use_softmax)
ValueError: (InvalidArgument) If Attr(soft_label) == true,  the axis dimension of Input(X) and Input(Label) should be equal.
  [Hint: Expected logits_dims[axis] == labels_dims[axis], but received logits_dims[axis]:2 != labels_dims[axis]:1.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:185)
  [operator < softmax_with_cross_entropy > error]
```

```
def __getitem__(self, index):
        img_path = self._images[index]
        label_path = self._label_images[index]
        image = Image.open(img_path)
        if self._image_transforms is not None:
            image = self._image_transforms(image)
        if self._mode in ['train', 'val']:
            label = Image.open(label_path).convert('L')
            if self._label_transforms is not None:
                label = self._label_transforms(label).astype('float32') / 255
            return image, label
        return image
```

**Comment by zjliu-cs** [comment]
axis=1

**Comment by zhangbo9674** [comment]
你好，报错信息上看，是输入x与label的维度不一致，请检查并确保一致
1. If soft_label=False, the shape is
:math:`[N_1, N_2, ..., N_k]` or :math:`[N_1, N_2, ..., N_k, 1]`, k >= 1.
the data type is int32, int64, float32, float64, where each value is [0, C-1].

2. If soft_label=True, the shape and data type should be same with ``input`` ,
and the sum of the labels for each sample should be 1.

**Comment by zjliu-cs** [comment]
我添加了新的参数soft_label=True，报错消失了。但是在损失函数中又出现了新的错误
```
Traceback (most recent call last):
  File "./utils/main.py", line 51, in <module>
    save_dir='./output/unet1')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1767, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 2097, in _run_one_epoch
    outs = getattr(self, mode + '_batch')(*_inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1093, in train_batch
    loss = self._adapter.train_batch(inputs, labels, update)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 730, in train_batch
    losses = self.model._loss(*(to_list(outputs) + labels))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/loss.py", line 406, in forward
    name=self.name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 1715, in cross_entropy
    label != ignore_index, dtype=label.dtype) * label
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (NotFound) There are no kernels which are registered in the not_equal operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:341)
  [operator < not_equal > error]
```
这里是动态图模式中类型不匹配，于是我将label转为float32.`label = self._label_transforms(label).astype(np.float32)`
继续报错
```
Traceback (most recent call last):
  File "./utils/main.py", line 51, in <module>
    save_dir='./output/unet1')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1767, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 2097, in _run_one_epoch
    outs = getattr(self, mode + '_batch')(*_inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 1093, in train_batch
    loss = self._adapter.train_batch(inputs, labels, update)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/model.py", line 730, in train_batch
    losses = self.model._loss(*(to_list(outputs) + labels))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/loss.py", line 406, in forward
    name=self.name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 1738, in cross_entropy
    'use_softmax', use_softmax)
SystemError: (Fatal) Operator softmax_with_cross_entropy raises an paddle::PD_Exception exception.
The exception content is
:function "CrossEntropyWithSoftmaxCUDAKernel" is not implemented for data type `float32`
  [/paddle/paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1544]. (at /paddle/paddle/fluid/imperative/tracer.cc:307)
```
报的PD_Exception应该是权限限制异常，内核并不支持float32，这是不是与前一个错误相互冲突呢？

**Comment by zhangbo9674** [comment]
你好，CrossEntropyWithSoftmaxCUDAKernel目前应该是支持float32的，麻烦提供一下使用的paddle版本和最小复现case，我来定位一下问题

**Comment by zjliu-cs** [comment]
paddle2.3.2post112
```
import paddle
from SeparableConv2D import SeparableConv2D
from paddle.io import Dataset
from PIL import Image
import numpy as np
from paddle.nn import functional as F
from paddle.vision.transforms import Resize, RandomHorizontalFlip, RandomVerticalFlip, \
    ColorJitter, RandomRotation, Normalize, \
    Compose, Transpose


class MyDataset(Dataset):
    def __init__(self, mode, train_path=None, val_path=None, test_path=None, separator=' ',
                 image_transforms=None, label_transforms=None):
        super().__init__()
        self._mode = mode
        self._separator = separator
        self._image_transforms = image_transforms
        self._label_transforms = label_transforms

        self._path = ''
        self._images = []
        self._label_images = []

        if self._mode == 'train':
            self._path = train_path
        elif self._mode == 'val':
            self._path = val_path
        else:
            self._path = test_path

        with open(self._path, 'r') as f:
            if self._mode == 'test':
                for l in f.readlines():
                    self._images.append(l)
            else:
                for l in f.readlines():
                    image, label = l.strip().split(self._separator)
                    self._images.append(image)
                    self._label_images.append(label)

    def __getitem__(self, index):
        img_path = self._images[index]
        label_path = self._label_images[index]
        image = Image.open(img_path)
        if self._image_transforms is not None:
            image = self._image_transforms(image)
        if self._mode in ['train', 'val']:
            label = Image.open(label_path).convert('L')
            if self._label_transforms is not None:
                label = self._label_transforms(label).astype(np.float32)
            return image, label
        return image

    def __len__(self):
        return len(self._images)


class Net(paddle.nn.Layer):
    def __init__(self, num_classes):
        super(Net, self).__init__()
        self.conv_1 = paddle.nn.Conv2D(3, 32, kernel_size=3, stride=2, padding='same')
        self.bn = paddle.nn.BatchNorm2D(32)
        self.relu = paddle.nn.ReLU()

        in_channels = 32
        self.encoders = []
        self.encoder_list = [64, 128, 256]
        self.decoder_list = [256, 128, 64, 32]

        for out_channels in self.encoder_list:
            block = self.add_sublayer('encoder_{}'.format(out_channels), Encoder(in_channels, out_channels))
            self.encoders.append(block)
            in_channels = out_channels

        self.decoders = []

        for out_channels in self.decoder_list:
            block = self.add_sublayer('decoder_{}'.format(out_channels), Decoder(in_channels, out_channels))
            self.decoders.append(block)
            in_channels = out_channels

        self.output_conv = paddle.nn.Conv2D(in_channels, num_classes, kernel_size=3, padding='same')

    def forward(self, inputs):
        y = self.conv_1(inputs)
        y = self.bn(y)
        y = self.relu(y)

        for encoder in self.encoders:
            y = encoder(y)

        for decoder in self.decoders:
            y = decoder(y)

        y = self.output_conv(y)
        return y


class SeparableConv2D(paddle.nn.Layer):
    def __init__(self,
                 in_channels,
                 out_channels,
                 kernel_size,
                 stride=1,
                 padding=0,
                 dilation=1,
                 groups=None,
                 weight_attr=None,
                 bias_attr=None,
                 data_format='NCHW'):
        super(SeparableConv2D, self).__init__()
        self._padding = padding
        self._stride = stride
        self._dilation = dilation
        self._in_channels = in_channels
        self._data_format = data_format

        filter_shape = [in_channels, 1] + self.convert_to_list(kernel_size, 2, 'kernel_size')
        self.weight_conv = self.create_parameter(shape=filter_shape, attr=weight_attr)

        filter_shape = [out_channels, in_channels] + self.convert_to_list(1, 2, 'kernel_size')
        self.weight_pointwise = self.create_parameter(shape=filter_shape, attr=weight_attr)
        self.bias_pointwise = self.create_parameter(shape=[out_channels], attr=bias_attr, is_bias=True)

    def convert_to_list(self, value, n, name, dtype=np.intp):
        if isinstance(value, dtype):
            return [value, ] * n
        else:
            try:
                value_list = [value] * n
            except TypeError:
                raise ValueError("The " + name +
                                 "'s type must be list or tuple. Received: " + str(
                    value))
            if len(value_list) != n:
                raise ValueError("The " + name + "'s length must be " + str(n) +
                                 ". Received: " + str(value))
            for single_value in value_list:
                try:
                    dtype(single_value)
                except (ValueError, TypeError):
                    raise ValueError(
                        "The " + name + "'s type must be a list or tuple of " + str(
                            n) + " " + str(dtype) + " . Received: " + str(
                            value) + " "
                                     "including element " + str(single_value) + " of type" + " "
                        + str(type(single_value)))
            return value_list

    def forward(self, inputs):
        conv_out = F.conv2d(inputs, self.weight_conv, padding=self._padding,
                            stride=self._stride, dilation=self._dilation,
                            groups=self._in_channels, data_format=self._data_format)
        out = F.conv2d(conv_out, self.weight_pointwise, bias=self.bias_pointwise,
                       padding=0, stride=1, dilation=1, groups=1, data_format=self._data_format)
        return out


class Encoder(paddle.nn.Layer):
    def __init__(self, in_channels, out_channels):
        super(Encoder, self).__init__()

        self.relus = paddle.nn.LayerList([paddle.nn.ReLU() for i in range(2)])
        self.separable_conv_01 = SeparableConv2D(in_channels, out_channels, kernel_size=3, padding='same')
        self.bns = paddle.nn.LayerList([paddle.nn.BatchNorm2D(out_channels) for i in range(2)])
        self.separable_conv_02 = SeparableConv2D(out_channels, out_channels, kernel_size=3, padding='same')
        self.pool = paddle.nn.MaxPool2D(kernel_size=3, stride=2, padding=1)
        self.residual_conv = paddle.nn.Conv2D(in_channels, out_channels, kernel_size=1, stride=2,
                                              padding='same')

    def forward(self, inputs):
        previous_block_activation = inputs
        y = self.relus[0](inputs)
        y = self.separable_conv_01(y)
        y = self.bns[0](y)
        y = self.relus[1](y)
        y = self.separable_conv_02(y)
        y = self.bns[1](y)
        y = self.pool(y)

        residual = self.residual_conv(previous_block_activation)
        y = paddle.add(y, residual)
        return y


class Decoder(paddle.nn.Layer):
    def __init__(self, in_channels, out_channels):
        super(Decoder, self).__init__()
        self.relus = paddle.nn.LayerList([paddle.nn.ReLU() for i in range(2)])
        self.conv_transpose_01 = paddle.nn.Conv2DTranspose(in_channels, out_channels, kernel_size=3, padding=1)
        self.conv_transpose_02 = paddle.nn.Conv2DTranspose(out_channels, out_channels,
                                                           kernel_size=3, padding=1)
        self.bns = paddle.nn.LayerList([paddle.nn.BatchNorm2D(out_channels) for i in range(2)])
        self.upsamples = paddle.nn.LayerList([paddle.nn.Upsample(scale_factor=2.0) for i in range(2)])
        self.residual_conv = paddle.nn.Conv2D(in_channels, out_channels, kernel_size=1, padding='same')

    def forward(self, inputs):
        previous_block_activation = inputs

        y = self.relus[0](inputs)
        y = self.conv_transpose_01(y)
        y = self.bns[0](y)
        y = self.relus[1](y)
        y = self.conv_transpose_02(y)
        y = self.bns[1](y)
        y = self.upsamples[0](y)
        residual = self.upsamples[1](previous_block_activation)
        residual = self.residual_conv(residual)
        y = paddle.add(y, residual)
        return y


if __name__ == '__main__':

    IMAGE_SIZE = (1024, 1024)

    image_transforms = Compose([
        Resize(size=IMAGE_SIZE),
        RandomRotation(30),
        RandomHorizontalFlip(0.3),
        RandomVerticalFlip(0.3),
        ColorJitter(brightness=0.5, contrast=0.5, saturation=0.5, hue=0.5),
        Transpose(),
        Normalize()])

    label_transforms = Compose([
        Resize(size=IMAGE_SIZE),
        Transpose()])

    train_dataset = MyDataset(mode='train', train_path='./PaddleSeg/dataset/train.txt',
                              image_transforms=image_transforms,
                              label_transforms=label_transforms)
    val_dataset = MyDataset(mode='val', val_path='./PaddleSeg/dataset/val.txt',
                            image_transforms=image_transforms,
                            label_transforms=label_transforms)
    model = paddle.Model(Net(2))
    optimizer = paddle.optimizer.SGD(learning_rate=0.001, parameters=model.parameters(), weight_decay=4.0e-5)

    model.prepare(optimizer=optimizer, loss=paddle.nn.CrossEntropyLoss(axis=1, soft_label=False))
    model.fit(train_data=train_dataset, eval_data=val_dataset, batch_size=4, epochs=10000,
              save_dir='./output/unet1')
```
谢谢

**Comment by zhangbo9674** [comment]
麻烦提供一下数据集：
train_dataset = MyDataset(mode='train', train_path='./PaddleSeg/dataset/train.txt',
                              image_transforms=image_transforms,
                              label_transforms=label_transforms)
val_dataset = MyDataset(mode='val', val_path='./PaddleSeg/dataset/val.txt',
                        image_transforms=image_transforms,
                        label_transforms=label_transforms)

**Comment by zjliu-cs** [comment]
https://github.com/jaycola99/dataset
上传到GitHub了

**Comment by jaycola99** [comment]
3

**Comment by zjliu-cs** [comment]
请问这边代码是有什么问题吗？

**Comment by zhangbo9674** [comment]
https://github.com/PaddlePaddle/Paddle/issues/47202#issuecomment-1285093610
你好，dataset数据集链接404，无法下载

**Comment by zjliu-cs** [comment]
上传到托管平台了
https://send.ioiox.com/download/c3b2c8ec6a35f54d/#YSs7Ugb91IIyCjESpbiNzA

**Comment by zhangbo9674** [comment]
你好，收到了数据集，我会尽快复现问题并答复。

**Comment by zhangbo9674** [comment]
您好，由于您的代码中设置了paddle.nn.CrossEntropyLoss的soft_label参数为False，在改参数为False的情况下label即val_dataset需要设置为int数据类型，您可以在Dataset的__getitem__中配置label的数据类型：
```
def __getitem__(self, index):
        img_path = self._images[index]
        label_path = self._label_images[index]
        image = Image.open(img_path)
        if self._image_transforms is not None:
            image = self._image_transforms(image)
        if self._mode in ['train', 'val']:
            label = Image.open(label_path).convert('L')
            if self._label_transforms is not None:
                label = self._label_transforms(label).astype(np.int64)
            return image, label
        return image

```
cross_entropy的api文档可见如下链接
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/nn/functional/cross_entropy_cn.html#cross-entropy
