### ISSUE TITLE
.HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch/current_repodata.json

### ISSUE THREAD

**Issue by xiaopei-sd** [PaddlePaddle/Paddle#47286]
### 问题描述 Issue Description

```
安装过程中使用代码
`conda install paddlepaddle-gpu==2.3.2 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/`
报错信息
`Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 531, in fetch_repodata_remote_request
        resp.raise_for_status()
      File "D:\Anaconda\lib\site-packages\requests\models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch/current_repodata.json`
```

### 版本&环境信息 Version & Environment Information

显卡 RTX2060
GPU 未安装  最高支持cuda 11.1
PaddlePaddle（2.3.2）
win 10
python 3.8

**Comment by xiaopei-sd** [comment]
已收到非常感谢！

**Comment by ZzSean** [comment]
你好，从报错信息上看应该是连接超时，建议尝试使用代理

**Comment by xiaopei-sd** [comment]
使用 vpn么？

**Comment by ZzSean** [comment]
> 使用 vpn么？

对的

**Comment by xiaopei-sd** [comment]
报错信息
```
(paddle_env) C:\Users\54165>conda install paddlepaddle-gpu==2.3.2 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
Collecting package metadata (current_repodata.json): failed

ProxyError: Conda cannot proceed due to an error in your proxy configuration.
Check for typos and other configuration errors in any '.netrc' file in your home directory,
any environment variables ending in '_PROXY', and any other system-wide proxy
configuration settings.

```
我之前是使用的清华镜像，我重新描述一下之前的报错，现在不理解current_repodata.json 为何报错
```
conda install paddlepaddle-gpu==2.3.2 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 531, in fetch_repodata_remote_request
        resp.raise_for_status()
      File "D:\Anaconda\lib\site-packages\requests\models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch/current_repodata.json
```

**Comment by ZzSean** [comment]
`ProxyError: Conda cannot proceed due to an error in your proxy configuration.`
这句报错就是代理问题吧，应该是window下conda安装的问题，可以看看这里https://blog.csdn.net/qq_41159191/article/details/126077080

**Comment by xiaopei-sd** [comment]
尝试您提到的方法，但是失败。
我分别尝试了 使用国内网直接下载 和使用您提到的博客进行解决。
使用内网，报错结果为：
```
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 531, in fetch_repodata_remote_request
        resp.raise_for_status()
      File "D:\Anaconda\lib\site-packages\requests\models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch/current_repodata.json

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\requests\models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "D:\Anaconda\lib\site-packages\simplejson\__init__.py", line 525, in loads
        return _default_decoder.decode(s)
      File "D:\Anaconda\lib\site-packages\simplejson\decoder.py", line 370, in decode
        obj, end = self.raw_decode(s)
      File "D:\Anaconda\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "D:\Anaconda\lib\site-packages\conda\cli\main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "D:\Anaconda\lib\site-packages\conda\cli\conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "D:\Anaconda\lib\site-packages\conda\notices\core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "D:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 22, in execute
        install(args, parser, 'install')
      File "D:\Anaconda\lib\site-packages\conda\cli\install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 156, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 199, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 304, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "D:\Anaconda\lib\site-packages\conda\common\io.py", line 86, in decorated
        return f(*args, **kwds)
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 467, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 1061, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "D:\Anaconda\lib\site-packages\conda\core\index.py", line 301, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 137, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "D:\Anaconda\lib\concurrent\futures\_base.py", line 611, in result_iterator
        yield fs.pop().result()
      File "D:\Anaconda\lib\concurrent\futures\_base.py", line 439, in result
        return self.__get_result()
      File "D:\Anaconda\lib\concurrent\futures\_base.py", line 388, in __get_result
        raise self._exception
      File "D:\Anaconda\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 129, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 142, in query
        self.load()
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 207, in load
        _internal_state = self._load()
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 277, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 587, in fetch_repodata_remote_request
        raise UnavailableInvalidChannel(
      File "D:\Anaconda\lib\site-packages\conda\exceptions.py", line 464, in __init__
        body = response.json()
      File "D:\Anaconda\lib\site-packages\requests\models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ D:\Anaconda\Scripts\conda-script.py install paddlepaddle-gpu==2.3.2 cudatoolkit=10.1 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=D:\LINGO64_18\Lingo18.jar
        CONDA_DEFAULT_ENV=paddle_env
                CONDA_EXE=D:\Anaconda\condabin\..\Scripts\conda.exe
               CONDA_EXES="D:\Anaconda\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=D:\Anaconda\envs\paddle_env
           CONDA_PREFIX_1=D:\Anaconda
    CONDA_PROMPT_MODIFIER=(paddle_env)
         CONDA_PYTHON_EXE=D:\Anaconda\python.exe
               CONDA_ROOT=D:\Anaconda
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\54165
                     PATH=D:\Anaconda\envs\paddle_env;D:\Anaconda\envs\paddle_env\Library\mingw-
                          w64\bin;D:\Anaconda\envs\paddle_env\Library\usr\bin;D:\Anaconda\envs\p
                          addle_env\Library\bin;D:\Anaconda\envs\paddle_env\Scripts;D:\Anaconda\
                          envs\paddle_env\bin;D:\Anaconda\condabin;C:\Program Files (x86)\Common
                          Files\Oracle\Java\javapath;F:\gurobi950\win64\bin;C:\Windows\system32;
                          C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerSh
                          ell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;D:\ArcGIS 10.4.1\Desktop10.4\bin;D:\ArcGIS
                          10.4.1\Desktop10.4\arcpy;D:\ArcGIS 10.4.1\Desktop10.4\ArcToolbox\Scrip
                          ts;D:\Anaconda\envs\arcgis;D:\Anaconda\envs\arcgis\Scripts;D:\Anaconda
                          \envs\arcgis\Library\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Sys
                          tem32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\Syste
                          m32\OpenSSH;D:\Anaconda;D:\Anaconda\Scripts;D:\Anaconda\Library\bin;F:
                          \Matlab_2020a\runtime\win64;F:\Matlab_2020a\bin;F:\Matlab_2020a\polysp
                          ace\bin;D:\LINGO64_18;C:\Program Files\MySQL\MySQL Server
                          8.0\bin;.;C:\Program Files (x86)\IDM Computer
                          Solutions\UltraEdit;D:\PDFtk Server\bin;C:\Program Files\IDM Computer
                          Solutions\UltraEdit;C:\Users\54165\AppData\Local\Microsoft\WindowsApps
                          ;D:\Microsoft VS Code\bin;D:\latex\texlive\2020\bin\win32;C:\Program
                          Files\Google\Chrome\Application\driver.exe;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : paddle_env
    active env location : D:\Anaconda\envs\paddle_env
            shell level : 2
       user config file : C:\Users\54165\.condarc
 populated config files :
          conda version : 22.9.0
    conda-build version : 3.20.2
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : D:\Anaconda  (writable)
      conda av data dir : D:\Anaconda\etc\conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda\pkgs
                          C:\Users\54165\.conda\pkgs
                          C:\Users\54165\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda\envs
                          C:\Users\54165\.conda\envs
                          C:\Users\54165\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

```

如果使用外网，报错结果为：
```
Collecting package metadata (current_repodata.json): failed

ProxyError: Conda cannot proceed due to an error in your proxy configuration.
Check for typos and other configuration errors in any '.netrc' file in your home directory,
any environment variables ending in '_PROXY', and any other system-wide proxy
configuration settings.
```

我这里都是用的 清华镜像网站，输入代码为：
`conda install paddlepaddle-gpu==2.3.2 cudatoolkit=10.1 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/`

**Comment by xiaopei-sd** [comment]
使用外网后，也和内网报错一致
```
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 531, in fetch_repodata_remote_request
        resp.raise_for_status()
      File "D:\Anaconda\lib\site-packages\requests\models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch/current_repodata.json

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
```

**Comment by ZzSean** [comment]
使用官方源试试呢？

**Comment by xiaopei-sd** [comment]
先 进行删除channels？ `conda config --remove-key channels `
需要添加默认官方源么？
感觉镜像网站 好像少文件了

**Comment by xiaopei-sd** [comment]
我使用 remove..后，产生下列代码，这个报错有什么影响么？
```
usage: conda-script.py config [-h] [--json] [-v] [-q] [--system | --env | --file FILE] [--show [SHOW [SHOW ...]] |
                              --show-sources | --validate | --describe [DESCRIBE [DESCRIBE ...]] | --write-default]
                              [--get [KEY [KEY ...]] | --append KEY VALUE | --prepend KEY VALUE | --set KEY VALUE |
                              --remove KEY VALUE | --remove-key KEY | --stdin]
conda-script.py config: error: argument --remove: expected 2 arguments
```

**Comment by xiaopei-sd** [comment]
未解决...
```
(paddle_env) C:\Users\54165>conda config --show channels
channels:
  - defaults

(paddle_env) C:\Users\54165>conda install paddlepaddle-gpu==2.3.2 cudatoolkit=10.1 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 531, in fetch_repodata_remote_request
        resp.raise_for_status()
      File "D:\Anaconda\lib\site-packages\requests\models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch/current_repodata.json

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\requests\models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "D:\Anaconda\lib\site-packages\simplejson\__init__.py", line 525, in loads
        return _default_decoder.decode(s)
      File "D:\Anaconda\lib\site-packages\simplejson\decoder.py", line 370, in decode
        obj, end = self.raw_decode(s)
      File "D:\Anaconda\lib\site-packages\simplejson\decoder.py", line 400, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "D:\Anaconda\lib\site-packages\conda\cli\main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "D:\Anaconda\lib\site-packages\conda\cli\conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "D:\Anaconda\lib\site-packages\conda\notices\core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "D:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 22, in execute
        install(args, parser, 'install')
      File "D:\Anaconda\lib\site-packages\conda\cli\install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 156, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 199, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 304, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "D:\Anaconda\lib\site-packages\conda\common\io.py", line 86, in decorated
        return f(*args, **kwds)
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 467, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 1061, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "D:\Anaconda\lib\site-packages\conda\core\index.py", line 301, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 137, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "D:\Anaconda\lib\concurrent\futures\_base.py", line 611, in result_iterator
        yield fs.pop().result()
      File "D:\Anaconda\lib\concurrent\futures\_base.py", line 432, in result
        return self.__get_result()
      File "D:\Anaconda\lib\concurrent\futures\_base.py", line 388, in __get_result
        raise self._exception
      File "D:\Anaconda\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 129, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 142, in query
        self.load()
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 207, in load
        _internal_state = self._load()
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 277, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 587, in fetch_repodata_remote_request
        raise UnavailableInvalidChannel(
      File "D:\Anaconda\lib\site-packages\conda\exceptions.py", line 464, in __init__
        body = response.json()
      File "D:\Anaconda\lib\site-packages\requests\models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ D:\Anaconda\Scripts\conda-script.py install paddlepaddle-gpu==2.3.2 cudatoolkit=10.1 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=D:\LINGO64_18\Lingo18.jar
        CONDA_DEFAULT_ENV=paddle_env
                CONDA_EXE=D:\Anaconda\condabin\..\Scripts\conda.exe
               CONDA_EXES="D:\Anaconda\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=D:\Anaconda\envs\paddle_env
           CONDA_PREFIX_1=D:\Anaconda
    CONDA_PROMPT_MODIFIER=(paddle_env)
         CONDA_PYTHON_EXE=D:\Anaconda\python.exe
               CONDA_ROOT=D:\Anaconda
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\54165
                     PATH=D:\Anaconda\envs\paddle_env;D:\Anaconda\envs\paddle_env\Library\mingw-
                          w64\bin;D:\Anaconda\envs\paddle_env\Library\usr\bin;D:\Anaconda\envs\p
                          addle_env\Library\bin;D:\Anaconda\envs\paddle_env\Scripts;D:\Anaconda\
                          envs\paddle_env\bin;D:\Anaconda\condabin;C:\Program Files (x86)\Common
                          Files\Oracle\Java\javapath;F:\gurobi950\win64\bin;C:\Windows\system32;
                          C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerSh
                          ell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;D:\ArcGIS 10.4.1\Desktop10.4\bin;D:\ArcGIS
                          10.4.1\Desktop10.4\arcpy;D:\ArcGIS 10.4.1\Desktop10.4\ArcToolbox\Scrip
                          ts;D:\Anaconda\envs\arcgis;D:\Anaconda\envs\arcgis\Scripts;D:\Anaconda
                          \envs\arcgis\Library\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Sys
                          tem32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\Syste
                          m32\OpenSSH;D:\Anaconda;D:\Anaconda\Scripts;D:\Anaconda\Library\bin;F:
                          \Matlab_2020a\runtime\win64;F:\Matlab_2020a\bin;F:\Matlab_2020a\polysp
                          ace\bin;D:\LINGO64_18;C:\Program Files\MySQL\MySQL Server
                          8.0\bin;.;C:\Program Files (x86)\IDM Computer
                          Solutions\UltraEdit;D:\PDFtk Server\bin;C:\Program Files\IDM Computer
                          Solutions\UltraEdit;C:\Users\54165\AppData\Local\Microsoft\WindowsApps
                          ;D:\Microsoft VS Code\bin;D:\latex\texlive\2020\bin\win32;C:\Program
                          Files\Google\Chrome\Application\driver.exe;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : paddle_env
    active env location : D:\Anaconda\envs\paddle_env
            shell level : 2
       user config file : C:\Users\54165\.condarc
 populated config files :
          conda version : 22.9.0
    conda-build version : 3.20.2
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : D:\Anaconda  (writable)
      conda av data dir : D:\Anaconda\etc\conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda\pkgs
                          C:\Users\54165\.conda\pkgs
                          C:\Users\54165\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda\envs
                          C:\Users\54165\.conda\envs
                          C:\Users\54165\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

**Comment by xiaopei-sd** [comment]
官方源 中只有2.4.0版本。 没有2.3.2版本。
![image](https://user-images.githubusercontent.com/65117285/197473742-40d13237-79e3-445c-854b-8d70f2ab524c.png)
而且无法安装
![image](https://user-images.githubusercontent.com/65117285/197474092-04b480a9-d709-4e5f-b6b8-7df7688f6dc9.png)

**Comment by ZzSean** [comment]
可以尝试将安装文件下载到本地安装
地址：https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/win-64/
指令：`conda install -c local xxx.tar.bz2; conda install -c local paddlepaddle-gpu`

**Comment by xiaopei-sd** [comment]
与前述报错一致。
`HTTPError: 404 Client Error: Not Found for url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch/current_repodata.json`

**Comment by ZzSean** [comment]
https://github.com/tuna/issues/issues/1518

**Comment by xiaopei-sd** [comment]
非常感谢~
问题解决
解决办法：重新安装。
这个问题可能是conda内部问题。没有找到根源问题。
