### ISSUE TITLE
paddle2.X对不同结构但是同name的模型怎么隔离训练

### ISSUE THREAD

**Issue by junman** [PaddlePaddle/Paddle#47568]
### 请提出你的问题 Please ask your question

想同时训练两个不同结构，但是同名字的（比如预训练加载同一个ernie）的模型，训练时怎么做隔离？
paddle1.7使用score_guard，paddle2.X的动态图怎么写？有demo嘛？

```python
import paddle
paddle.set_default_dtype("float64")

class UCIHousing(paddle.nn.Layer):
    def __init__(self):
        super(UCIHousing, self).__init__()
        weight_attr = paddle.ParamAttr(
                name="weight",
                initializer=paddle.nn.initializer.Constant(value=0.5))
        bias_attr = paddle.ParamAttr(
                name="bias",
                initializer=paddle.nn.initializer.Constant(value=1.0))
        self.fc = paddle.nn.Linear(10, 5, weight_attr=weight_attr, bias_attr=bias_attr, name = "x_fc")

    def forward(self, input):
        pred = self.fc(input)
        return pred

model_1st = UCIHousing()
print(model_1st.parameters())

# 报错:
model_2nd = UCIHousing()
print(model_2nd.parameters())
```

报错信息：
```
[Parameter containing:
Tensor(shape=[10, 5], dtype=float64, place=CPUPlace, stop_gradient=False,
       [[0.50000000, 0.50000000, 0.50000000, 0.50000000, 0.50000000],
        [0.50000000, 0.50000000, 0.50000000, 0.50000000, 0.50000000],
        [0.50000000, 0.50000000, 0.50000000, 0.50000000, 0.50000000],
        [0.50000000, 0.50000000, 0.50000000, 0.50000000, 0.50000000],
        [0.50000000, 0.50000000, 0.50000000, 0.50000000, 0.50000000],
        [0.50000000, 0.50000000, 0.50000000, 0.50000000, 0.50000000],
        [0.50000000, 0.50000000, 0.50000000, 0.50000000, 0.50000000],
        [0.50000000, 0.50000000, 0.50000000, 0.50000000, 0.50000000],
        [0.50000000, 0.50000000, 0.50000000, 0.50000000, 0.50000000],
        [0.50000000, 0.50000000, 0.50000000, 0.50000000, 0.50000000]]), Parameter containing:
Tensor(shape=[5], dtype=float64, place=CPUPlace, stop_gradient=False,
       [1., 1., 1., 1., 1.])]
Traceback (most recent call last):
  File "demo_parameters_3.py", line 23, in <module>
    model_2nd = UCIHousing()
  File "demo_parameters_3.py", line 13, in __init__
    self.fc = paddle.nn.Linear(10, 5, weight_attr=weight_attr, bias_attr=bias_attr, name = "x_fc")
  File "/home/disk6/majunman/.deck/1.0/python/3.7.6/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 162, in __init__
    is_bias=False)
  File "/home/disk6/majunman/.deck/1.0/python/3.7.6/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 422, in create_parameter
    default_initializer)
  File "/home/disk6/majunman/.deck/1.0/python/3.7.6/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 372, in create_parameter
    "constructor of dygraph Layers".format(attr.name))
ValueError: parameter name [weight] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers
```

**Comment by ForFishes** [comment]
您好，如果你创建了2个model，本身就是两份参数（这个和静态图不同），本身就是各自训练各自的，天然的隔离训练。

**Comment by junman** [comment]
请教下，如果天然的隔离，为什么这里创建第二个对象时报错呢，自己理解是不同的对象是不同的内存：

```
model_1st = UCIHousing()
print(model_1st.parameters())

# 报错: ValueError: parameter name [weight] have be been used. In dygraph mode, the name of parameter can't be same.Please check the parameter attr value passed to self.create_parameter or constructor of dygraph Layers

model_2nd = UCIHousing()            # 和model_1st是不同的对象
print(model_2nd.parameters())
```

**Comment by ForFishes** [comment]
您好，原因是你这里给参数设置了名字。导致创建两个model的时候，参数名字相同。这里建议：
1、不特意给参数设置名字，交由框架自动命名。
```python
import paddle
paddle.set_default_dtype("float64")

class UCIHousing(paddle.nn.Layer):
    def __init__(self):
        super(UCIHousing, self).__init__()
        weight_attr = paddle.ParamAttr(
    #            name="weight",
                initializer=paddle.nn.initializer.Constant(value=0.5))
        bias_attr = paddle.ParamAttr(
     #           name="bias",
                initializer=paddle.nn.initializer.Constant(value=1.0))
        self.fc = paddle.nn.Linear(10, 5, weight_attr=weight_attr, bias_attr=bias_attr, name = "x_fc")

    def forward(self, input):
        pred = self.fc(input)
        return pred

model_1st = UCIHousing()
print(model_1st.parameters())

model_2nd = UCIHousing()
```
2、构建两个model的时候，每个model的参数的名字不同。
