### ISSUE TITLE
F.interpolate 挡mode='area'的时候不支持shape为tensor类型。

### ISSUE THREAD

**Issue by wuyefeilin** [PaddlePaddle/Paddle#47565]
### bug描述 Describe the Bug

paddle.nn.functional.interpolate在参数mode='area'的时候不支持shape为tensor类型

复现代码
```python
import paddle
import paddle.nn.functional as F
a = paddle.rand((1, 3,16,16))
shape = paddle.shape(a) // 2
F.interpolate(a, shape[-2:], mode='area')
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 312, in interpolate
    return paddle.nn.functional.adaptive_avg_pool2d(x, size)
  File "anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/functional/pooling.py", line 1395, in adaptive_avg_pool2d
    if output_size[0] == None:
  File "anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 258, in __impl__
    value=other_var, dtype=lhs_dtype)
  File "anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 90, in create_scalar
    return create_tensor(value, dtype, shape=[1])
  File "<decorator-gen-152>", line 2, in create_tensor
  File "anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 85, in create_tensor
    value, 'force_cpu', False)
ValueError: (InvalidArgument) fill_constant(): argument (position 6) must be float, but got NoneType (at /paddle/paddle/fluid/pybind/op_function_common.cc:189)
```

**Comment by ForFishes** [comment]
您好，可以使用tensor.tolist()，将tensor转换成 list

**Comment by wuyefeilin** [comment]
> 您好，可以使用tensor.tolist()，将tensor转换成 list

使用list影响模型的导出部署。 而且bilinear等其它模式支持，就这个'area'不支持

**Comment by Genlk** [comment]
@wuyefeilin 
你这边插值可以正常使用么？在gpu环境下需要额外设置什么嘛？我这边的插值和torch相比不一样
#47797 ，插值之后全部结果为0.

**Comment by wuyefeilin** [comment]
> @wuyefeilin 你这边插值可以正常使用么？在gpu环境下需要额外设置什么嘛？我这边的插值和torch相比不一样 #47797 ，插值之后全部结果为0.

除了'area'模式其它可以正常使用
