### ISSUE TITLE
fail to submit job with receiver

### ISSUE THREAD

**Issue by RuijieHou** [PaddlePaddle/Paddle#4757]
connect to receiver:  xxxx:8090
compressing thirdparty files
finished to pack request
starting to submit to server:  xxxx:8090
Traceback (most recent call last):
  File "/home/project/title_correlation/paddle-dnn/mpi/output/submit.py", line 303, in <module>
    no_prefix_train_args_dict, ).run()
  File "/home/project/title_correlation/paddle-dnn/mpi/output/submit.py", line 77, in run
    self._do_poster_request()
  File "/home/project/title_correlation/paddle-dnn/mpi/output/submit.py", line 167, in _do_poster_request
    connection = urllib2.urlopen(request)
  File "/home/project/title_correlation/paddle-dnn/python27/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/project/title_correlation/paddle-dnn/python27/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/home/project/title_correlation/paddle-dnn/python27/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/home/project/title_correlation/paddle-dnn/python27/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "build/bdist.linux-x86_64/egg/poster/streaminghttp.py", line 142, in http_open
  File "/home/project/title_correlation/paddle-dnn/python27/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/home/project/title_correlation/paddle-dnn/python27/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/home/project/title_correlation/paddle-dnn/python27/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/home/project/title_correlation/paddle-dnn/python27/lib/python2.7/httplib.py", line 402, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

提交失败，可能是receiver的问题，请问如何解决或者查看其他可用的receive？

**Comment by typhoonzero** [comment]
receiver的问题，提交过程中Ctrl+C可能引发。

**Comment by RuijieHou** [comment]
@typhoonzero 我按官网配的receiver，最近好像不是很稳定，时不时会出现上面的问题，现在又出现了 “urllib2.URLError: <urlopen error [Errno 111] Connection refused>”，请问有其他可用的receiver么？

**Comment by typhoonzero** [comment]
receiver 目前是仅维护状态。有问题在群里反馈即可。
