### ISSUE TITLE
Paddle关于exe.run中的 fetch_list=target_var问题

### ISSUE THREAD

**Issue by PunchOvO** [PaddlePaddle/Paddle#48067]
### bug描述 Describe the Bug

本人在复现一个文本分类，目前卡在最后一步
'''
D:\conda\lib\site-packages\socks.py:58: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Callable
C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\executor.py:1520: UserWarning: There are no operators in the program to be executed. If you pass Program manually, please use fluid.program_guard to ensure the current Program is being used.
  warnings.warn(error_info)
Traceback (most recent call last):
  File "D:\dk\drrec-main\models\contentunderstanding\tag\infer.py", line 56, in <module>
    fetch_list=target_var)  #
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\executor.py", line 1459, in run
    return_merged=return_merged)
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\executor.py", line 1662, in _run_impl
    return_numpy)
  File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\executor.py", line 632, in run
    fetch_list)._move_to_list()
ValueError: In user code:

    File "D:\dk\drrec-main\models\contentunderstanding\tag\train.py", line 23, in <module>
      model = bilstm_net.bilstm_net(words, dict_dim, 15)  #
    File "D:\dk\drrec-main\models\contentunderstanding\tag\bilstm_net.py", line 8, in bilstm_net
      param_attr=fluid.ParamAttr(learning_rate=emb_lr))  #
    File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\layers\nn.py", line 557, in embedding
      'padding_idx': padding_idx
    File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\framework.py", line 3828, in append_op
      attrs=kwargs.get("attrs", None))
    File "C:\Users\xxx\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\framework.py", line 2736, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The type of data we are trying to retrieve does not match the type of data currently contained in the container.
      [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():7 != paddle::experimental::CppTypeToDataType<T>::Type():9.] (at ..\paddle\phi\core\dense_tensor.cc:143)
      [operator < lookup_table > error]
'''
代码链接：https://github.com/yeyupiaoling/LearnPaddle2/tree/master/note12
请大家指导

**Comment by joey12300** [comment]
您好，这个应该是输入的数据类型有问题，将输入数据转为int64即可。

针对文本分类任务，可以参考这个示例：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/text_classification

**Comment by PunchOvO** [comment]
>这个应该是输入的数据类型有问题，将输入数据转为int64即可。

# 定义输入数据， lod_level不为0指定输入数据为序列数据
words = fluid.layers.data(name='words', shape=[1], dtype='int64', lod_level=1)
label = fluid.layers.data(name='label', shape=[1], dtype='int64') 
 这里训练 输入数据都是 int64 呀

**Comment by joey12300** [comment]
> > 这个应该是输入的数据类型有问题，将输入数据转为int64即可。
> 
> # 定义输入数据， lod_level不为0指定输入数据为序列数据
> words = fluid.layers.data(name='words', shape=[1], dtype='int64', lod_level=1) label = fluid.layers.data(name='label', shape=[1], dtype='int64') 这里训练 输入数据都是 int64 呀

是的，但这是定义输入数据，在喂入数据的时候也要保证数据是int64的。比如红框部分，需要确保data也是int64
![image](https://user-images.githubusercontent.com/10826371/202604490-9844aa9f-4a01-4c7b-a10b-c96084ac2dc8.png)
