### ISSUE TITLE
TRT-paddleinference whl 包安装后paddle自查失败

### ISSUE THREAD

**Issue by hsdjkfnsfc** [PaddlePaddle/Paddle#48143]
### 问题描述 Please describe your issue

cuda11.2,cudnn8.2,trt8,gcc8.4
安装python trt 推理库
https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html#python
在python自查的时候报错，显卡为4090

RUN:
paddle.fluid.install_check.run_check()

报错
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ps/miniconda3/envs/paddle-trt/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 140, in run_check
    test_simple_exe()
  File "/home/ps/miniconda3/envs/paddle-trt/lib/python3.7/site-packages/paddle/fluid/install_check.py", line 136, in test_simple_exe
    exe0.run(startup_prog)
  File "/home/ps/miniconda3/envs/paddle-trt/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1262, in run
    six.reraise(*sys.exc_info())
  File "/home/ps/miniconda3/envs/paddle-trt/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/ps/miniconda3/envs/paddle-trt/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1260, in run
    return_merged=return_merged)
  File "/home/ps/miniconda3/envs/paddle-trt/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1402, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/ps/miniconda3/envs/paddle-trt/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1492, in _run_program
    [fetch_var_name])
OSError: (External) CUSOLVER error(7). 
  [Hint: 'CUSOLVER_STATUS_INTERNAL_ERROR'. An internal cuSolver operation failed. This error is usually caused by a cudaMemcpyAsync() failure.To correct: check that the hardware, an appropriate version of the driver, and the cuSolver library are correctly installed. Also, check that the memory passed as a parameter to the routine is not being deallocated prior to the routine’s completion.] (at /paddle/paddle/fluid/platform/device_context.h:418)

**Comment by ghostxsl** [comment]
看报错信息，可能是你的环境有问题，检查一下自己的驱动CUDA版本之类的，如果实在不行，可以尝试源码编译安装

**Comment by hsdjkfnsfc** [comment]
事实上，编译也会存在问题,但是刚才尝试了3.9的whl包，问题解决了，编译的时候会提示:
target extern_mkldnn recipe for target 'all' failed
