### ISSUE TITLE
CUBLAS_STATUS_INVALID_VALUE

### ISSUE THREAD

**Issue by jack-gits** [PaddlePaddle/Paddle#48171]
### bug描述 Describe the Bug

**在服务启动的时候paddle.utils.run_check()报错，下面是报错信息**

**但登陆到docker镜像用命令行再运行paddle.utils.run_check()，确check成功了。**

**_1. 启动是的错误信息_**
```
2022-11-20T07:04:51,097 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG - Running verify PaddlePaddle program ... 
2022-11-20T07:04:51,110 [WARN ] W-9000-neuron-ocr_release-2022-11-19-stderr MODEL_LOG - W1120 07:04:51.109781    49 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 11.1
2022-11-20T07:04:51,112 [WARN ] W-9000-neuron-ocr_release-2022-11-19-stderr MODEL_LOG - W1120 07:04:51.112783    49 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
2022-11-20T07:04:53,311 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG - Backend worker process died.
2022-11-20T07:04:53,311 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG - Traceback (most recent call last):
2022-11-20T07:04:53,311 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/ts/model_service_worker.py", line 221, in <module>
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     worker.run_server()
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/ts/model_service_worker.py", line 189, in run_server
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/ts/model_service_worker.py", line 154, in handle_connection
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/ts/model_service_worker.py", line 118, in load_model
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     service = model_loader.load(
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/ts/model_loader.py", line 135, in load
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     entry_point, initialize_fn = self._get_class_entry_point(module)
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/ts/model_loader.py", line 193, in _get_class_entry_point
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     model_service = model_class()
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/model-server/tmp/models/b69c3d3e0c6e477093ca1c3534aade3d/inference-handler.py", line 32, in __init__
**2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     paddle.utils.run_check()
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddle/utils/install_check.py", line 266, in run_check**
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     _run_static_single(use_cuda, use_xpu, use_npu)
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddle/utils/install_check.py", line 171, in _run_static_single
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     exe.run(train_prog,
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1299, in run
2022-11-20T07:04:53,312 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     six.reraise(*sys.exc_info())
2022-11-20T07:04:53,313 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/six.py", line 719, in reraise
2022-11-20T07:04:53,313 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     raise value
2022-11-20T07:04:53,313 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1285, in run
2022-11-20T07:04:53,313 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     res = self._run_impl(
2022-11-20T07:04:53,313 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1464, in _run_impl
2022-11-20T07:04:53,313 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     return new_exe.run(list(feed.keys()), fetch_list, return_numpy)
2022-11-20T07:04:53,313 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   File "/home/venv/lib/python3.8/site-packages/paddle/fluid/executor.py", line 547, in run
2022-11-20T07:04:53,313 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -     tensors = self._new_exe.run(feed_names, fetch_list)._move_to_list()
2022-11-20T07:04:53,313 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG - OSError: (External) CUBLAS error(7). 
2022-11-20T07:04:53,313 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2022-11-20T07:04:53,313 [INFO ] W-9000-neuron-ocr_release-2022-11-19-stdout MODEL_LOG -   [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
```

**_2，命令行check成功_**

```
root@e539e7a3f615:/home/venv/lib/python3.8/site-packages/paddle/utils# python
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
********************************************************
W1120 07:14:00.049743   689 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 11.1
W1120 07:14:00.057123   689 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

**Comment by jack-gits** [comment]
paddlepaddle_gpu=2.3.2.post111

**Comment by jack-gits** [comment]
paddlepaddle-gpu==2.3.2.post116 也同样问题

**Comment by RainFrost1** [comment]
可以使用`nvcc --version`看看机器运行的cuda版本，安装对应版本的paddle试一下。或者直接使用paddle官方提供的docker镜像试一下，详见[官网](https://www.paddlepaddle.org.cn/)

**Comment by jack-gits** [comment]
要看机器的cuda版本还是 docker里的cuda版本？

**Comment by RainFrost1** [comment]
在docker里安装的话，就看docker的cuda版本。建议使用官方的docker环境，环境问题有时候比较难以定位

**Comment by jack-gits** [comment]
![image](https://user-images.githubusercontent.com/30545972/203010812-99327175-20c4-4f44-b15c-3e38f4b21fe7.png)

这个是docker里的版本

**Comment by RainFrost1** [comment]
用nvidia-smi的方式是不准的，运行时的cuda版本用nvcc --version查看

**Comment by jack-gits** [comment]
torch.version.cuda 11.6

**Comment by RainFrost1** [comment]
这个是torch支持的cuda版本，不是运行安装的cuda版本。建议还是使用官网的docker镜像吧
