### ISSUE TITLE
NCCL Error -- paddle training bug！

### ISSUE THREAD

**Issue by 2050airobert** [PaddlePaddle/Paddle#48181]
### bug描述 Describe the Bug

hi，
     训练模型的时候出现了异常，猜测是环境问题，具体log如下，麻烦大佬看下具体哪里问题，该如何简单的修复这个bug呢？ 
```  root@fd9af94f4692:/app_lcl/paddle_test/PaddleDetection# python3 -m paddle.distributed.launch tools/train.py -c configs/keypoint/tiny_pose/tinypose_256x192_wholebody-v2-0921-1021-1108-1121.yml --eval
LAUNCH INFO 2022-11-21 02:35:46,339 -----------  Configuration  ----------------------
LAUNCH INFO 2022-11-21 02:35:46,339 devices: None
LAUNCH INFO 2022-11-21 02:35:46,339 elastic_level: -1
LAUNCH INFO 2022-11-21 02:35:46,339 elastic_timeout: 30
LAUNCH INFO 2022-11-21 02:35:46,339 gloo_port: 6767
LAUNCH INFO 2022-11-21 02:35:46,339 host: None
LAUNCH INFO 2022-11-21 02:35:46,339 ips: None
LAUNCH INFO 2022-11-21 02:35:46,339 job_id: default
LAUNCH INFO 2022-11-21 02:35:46,339 legacy: False
LAUNCH INFO 2022-11-21 02:35:46,339 log_dir: log
LAUNCH INFO 2022-11-21 02:35:46,339 log_level: INFO
LAUNCH INFO 2022-11-21 02:35:46,339 master: None
LAUNCH INFO 2022-11-21 02:35:46,339 max_restart: 3
LAUNCH INFO 2022-11-21 02:35:46,339 nnodes: 1
LAUNCH INFO 2022-11-21 02:35:46,339 nproc_per_node: None
LAUNCH INFO 2022-11-21 02:35:46,339 rank: -1
LAUNCH INFO 2022-11-21 02:35:46,339 run_mode: collective
LAUNCH INFO 2022-11-21 02:35:46,339 server_num: None
LAUNCH INFO 2022-11-21 02:35:46,339 servers:
LAUNCH INFO 2022-11-21 02:35:46,339 start_port: 6070
LAUNCH INFO 2022-11-21 02:35:46,339 trainer_num: None
LAUNCH INFO 2022-11-21 02:35:46,339 trainers:
LAUNCH INFO 2022-11-21 02:35:46,340 training_script: tools/train.py
LAUNCH INFO 2022-11-21 02:35:46,340 training_script_args: ['-c', 'configs/keypoint/tiny_pose/tinypose_256x192_wholebody-v2-0921-1021-1108-1121.yml', '--eval']
LAUNCH INFO 2022-11-21 02:35:46,340 with_gloo: 1
LAUNCH INFO 2022-11-21 02:35:46,340 --------------------------------------------------
LAUNCH INFO 2022-11-21 02:35:46,340 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2022-11-21 02:35:46,347 Run Pod: qvawgl, replicas 2, status ready
LAUNCH INFO 2022-11-21 02:35:46,374 Watching Pod: qvawgl, replicas 2, status running
I1121 02:35:50.375497 3004620 tcp_utils.cc:181] The server starts to listen on IP_ANY:47948
I1121 02:35:50.375732 3004620 tcp_utils.cc:130] Successfully connected to 172.18.0.4:47948
W1121 02:35:52.835877 3004620 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.7
W1121 02:35:52.838711 3004620 gpu_resources.cc:91] device: 0, cuDNN Version: 8.0.
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 112, in run
    init_parallel_env()
  File "/app_lcl/paddle_test/PaddleDetection/ppdet/engine/env.py", line 44, in init_parallel_env
    paddle.distributed.init_parallel_env()
  File "/usr/local/lib/python3.8/dist-packages/paddle/distributed/parallel.py", line 272, in init_parallel_env
    paddle.distributed.barrier(group=group)
  File "/usr/local/lib/python3.8/dist-packages/paddle/distributed/collective.py", line 328, in barrier
    task = group.process_group.barrier()
OSError: (External) NCCL error(2), unhandled system error.
  [Hint: Please search for the error code(2) on website (https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html#ncclresult-t) to get Nvidia's official solution and advice about NCCL Error.] (at /paddle/paddle/fluid/distributed/collective/ProcessGroupNCCL.cc:236)

I1121 02:35:53.560647 3004662 tcp_store.cc:257] receive shutdown event and so quit from MasterDaemon run loop
LAUNCH INFO 2022-11-21 02:35:54,384 Pod failed
LAUNCH ERROR 2022-11-21 02:35:54,385 Container failed !!!
Container rank 0 status failed cmd ['/usr/bin/python3', '-u', 'tools/train.py', '-c', 'configs/keypoint/tiny_pose/tinypose_256x192_wholebody-v2-0921-1021-1108-1121.yml', '--eval'] code 1 log log/workerlog.0
env {'NV_LIBCUBLAS_VERSION': '11.3.0.106-1', 'NVIDIA_VISIBLE_DEVICES': 'all', 'NV_NVML_DEV_VERSION': '11.1.74-1', 'NV_CUDNN_PACKAGE_NAME': 'libcudnn8', 'NV_LIBNCCL_DEV_PACKAGE': 'libnccl-dev=2.8.4-1+cuda11.1', 'NV_LIBNCCL_DEV_PACKAGE_VERSION': '2.8.4-1', 'HOSTNAME': 'fd9af94f4692', 'NVIDIA_REQUIRE_CUDA': 'cuda>=11.1 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450', 'NV_LIBCUBLAS_DEV_PACKAGE': 'libcublas-dev-11-1=11.3.0.106-1', 'NV_NVTX_VERSION': '11.1.74-1', 'NV_ML_REPO_ENABLED': '1', 'NV_CUDA_CUDART_DEV_VERSION': '11.1.74-1', 'NV_LIBCUSPARSE_VERSION': '11.3.0.10-1', 'NV_LIBNPP_VERSION': '11.1.2.301-1', 'NCCL_VERSION': '2.8.4-1', 'PWD': '/app_lcl/paddle_test/PaddleDetection', 'NV_CUDNN_PACKAGE': 'libcudnn8=8.0.5.39-1+cuda11.1', 'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility', 'NV_LIBNCCL_DEV_PACKAGE_NAME': 'libnccl-dev', 'NV_LIBCUBLAS_DEV_VERSION': '11.3.0.106-1', 'NV_LIBCUBLAS_DEV_PACKAGE_NAME': 'libcublas-dev-11-1', 'NV_CUDA_CUDART_VERSION': '11.1.74-1', 'HOME': '/root', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'CUDA_VERSION': '11.1.1', 'NV_LIBCUBLAS_PACKAGE': 'libcublas-11-1=11.3.0.106-1', 'NV_LIBCUBLAS_PACKAGE_NAME': 'libcublas-11-1', 'NV_LIBNPP_DEV_VERSION': '11.1.2.301-1', 'TERM': 'xterm', 'NV_LIBCUSPARSE_DEV_VERSION': '11.3.0.10-1', 'NV_ML_REPO_URL': 'https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64', 'LIBRARY_PATH': '/usr/local/cuda/lib64/stubs', 'NV_CUDNN_VERSION': '8.0.5.39', 'DISPLAY': '172.17.2.11:0.0', 'SHLVL': '1', 'NV_CUDA_LIB_VERSION': '11.1.1-1', 'NVARCH': 'x86_64', 'HTTPS_PROXY': 'http://172.17.101.23:1080', 'HTTP_PROXY': 'http://172.17.101.23:1080', 'NV_CUDNN_PACKAGE_DEV': 'libcudnn8-dev=8.0.5.39-1+cuda11.1', 'NV_CUDA_COMPAT_PACKAGE': 'cuda-compat-11-1', 'NV_LIBNCCL_PACKAGE': 'libnccl2=2.8.4-1+cuda11.1', 'LD_LIBRARY_PATH': '/usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64', 'PATH': '/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'NV_LIBNCCL_PACKAGE_NAME': 'libnccl2', 'NV_LIBNCCL_PACKAGE_VERSION': '2.8.4-1', 'DEBIAN_FRONTEND': 'noninteractive', 'OLDPWD': '/', '_': '/usr/bin/python3', 'LC_CTYPE': 'C.UTF-8', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/usr/local/lib/python3.8/dist-packages/cv2/qt/plugins', 'QT_QPA_FONTDIR': '/usr/local/lib/python3.8/dist-packages/cv2/qt/fonts', 'POD_NAME': 'qvawgl', 'PADDLE_MASTER': '172.18.0.4:47948', 'PADDLE_GLOBAL_SIZE': '2', 'PADDLE_LOCAL_SIZE': '2', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '172.18.0.4:47949,172.18.0.4:47950', 'PADDLE_CURRENT_ENDPOINT': '172.18.0.4:47949', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '2', 'PADDLE_RANK_IN_NODE': '0', 'FLAGS_selected_gpus': '0'}
LAUNCH INFO 2022-11-21 02:35:54,385 ------------------------- ERROR LOG DETAIL -------------------------
I1121 02:35:50.375497 3004620 tcp_utils.cc:181] The server starts to listen on IP_ANY:47948
I1121 02:35:50.375732 3004620 tcp_utils.cc:130] Successfully connected to 172.18.0.4:47948
W1121 02:35:52.835877 3004620 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.7
W1121 02:35:52.838711 3004620 gpu_resources.cc:91] device: 0, cuDNN Version: 8.0.
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 112, in run
    init_parallel_env()
  File "/app_lcl/paddle_test/PaddleDetection/ppdet/engine/env.py", line 44, in init_parallel_env
    paddle.distributed.init_parallel_env()
  File "/usr/local/lib/python3.8/dist-packages/paddle/distributed/parallel.py", line 272, in init_parallel_env
    paddle.distributed.barrier(group=group)
  File "/usr/local/lib/python3.8/dist-packages/paddle/distributed/collective.py", line 328, in barrier
    task = group.process_group.barrier()
OSError: (External) NCCL error(2), unhandled system error.
  [Hint: Please search for the error code(2) on website (https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/api/types.html#ncclresult-t) to get Nvidia's official solution and advice about NCCL Error.] (at /paddle/paddle/fluid/distributed/collective/ProcessGroupNCCL.cc:236)

I1121 02:35:53.560647 3004662 tcp_store.cc:257] receive shutdown event and so quit from MasterDaemon run loop
LAUNCH INFO 2022-11-21 02:35:54,386 Exit code 1 ```

     多谢     
   
BR 

### 其他补充信息 Additional Supplementary Information

_No response_

**Comment by gongel** [comment]
你好，可参考这里解决该问题：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/faq/train_cn.html#nvidia-paddle-nccl-error
如果还不行，可以考虑Docker搭建环境：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

**Comment by kehuo** [comment]
@gongel 你好，请问paddle docker镜像默认安装了NCCL吗？文档没有提到诶

**Comment by dyh** [comment]
遇到同样问题。

**Comment by dyh** [comment]
export NCCL_DEBUG=info
输出一下详细的错误信息。

**Comment by TerryBryant** [comment]
> 你好，可参考这里解决该问题：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/faq/train_cn.html#nvidia-paddle-nccl-error 如果还不行，可以考虑Docker搭建环境：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

以上链接已失效，可参考[新的网址](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/train_cn.html#nvidia-paddle-nccl-error)
