### ISSUE TITLE
Can not import paddle core while this file exists: /path/to/libpaddle.so

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/Paddle#48243]
### 问题描述 Issue Description

在 python3.8/3.7环境下安装完paddlepaddle==2.4.0之后，不能导入libpaddle.so文件。

可是我从 pypi server 上面下载了对应版本的whl包解压之后发现里面还是有对应的libpaddle.so文件，就感觉到很奇怪。

我在paddlenlp 的一个 pr 里面尝试解决此问题：https://github.com/PaddlePaddle/PaddleNLP/pull/3859。

详细的编译信息请看：https://readthedocs.org/api/v2/build/18703479.txt

### 版本&环境信息 Version & Environment Information

具体环境请看：
PaddlePaddle == 2.4.0
python 3.7
centos

由于程序是运行在readthedocs 服务器上，更相信的环境信息这边是没办法拿到，你们可以通过日志查看更多详细信息。

**Comment by minghaoBD** [comment]
可以暂时使用2.3.x版本。我这边测试2.4尚不稳定，正在联系相关同学确定问题。

**Comment by wj-Mcat** [comment]
好的，感谢回复。

**Comment by yt605155624** [comment]
赞，刚好遇到了这个问题

**Comment by linnnn1** [comment]
请问您是怎么解决这个问题的呢？

**Comment by www516717402** [comment]
@linnnn1 直接回退使用2.3.*版本就行了，搞不懂这paddle团队发布新版本都不进行大量测试的吗？

**Comment by hjing100** [comment]
docker环境部署
python3.7
请问，安装2.3.2还是显示Error: Can not import avx core while this file exists: /usr/local/lib/python3.7/site-packages/paddle/fluid/core_avx.so

**Comment by quelle1** [comment]
CPU：ft1500, 
system: kylin v4,
paddlepaddle：v2.4.1，v2.4.2,v2.4.3  自己下载的代码进行编译，都会出现下面的问题

Python 3.7.16 (default, Apr 12 2023, 12:22:04)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: /usr/local/lib/python3.7/site-packages/paddle/fluid/libpaddle.so: undefined symbol: shm_unlink

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 300, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined
>>>

**Comment by Veteran-ChengQin** [comment]
@linnnn1 > 发

你好，建议你根据这个链接：
https://blog.csdn.net/weixin_43021830/article/details/128243800
先将缺失的文件cp到/usr/lib,
然后可能会出现
ImportError: /home/veteran/anaconda3/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/veteran/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/libpaddle.so)
关于这个问题，可以根据这个链接解决
https://blog.csdn.net/bohrium/article/details/126546521

**Comment by Zomun** [comment]
(ser) root@ps:/home/SER-multitask-main2# python infer_batch.py 
Error: Can not import paddle core while this file exists: /root/anaconda3/envs/ser/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "infer_batch.py", line 6, in <module>
    import paddle
  File "/root/anaconda3/envs/ser/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/root/anaconda3/envs/ser/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/root/anaconda3/envs/ser/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/root/anaconda3/envs/ser/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/root/anaconda3/envs/ser/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/root/anaconda3/envs/ser/lib/python3.8/site-packages/paddle/fluid/core.py", line 338, in <module>
    raise e
  File "/root/anaconda3/envs/ser/lib/python3.8/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by AsifMehmood97** [comment]
> CPU：ft1500, system: kylin v4, paddlepaddle：v2.4.1，v2.4.2,v2.4.3 自己下载的代码进行编译，都会出现下面的问题
> 
> Python 3.7.16 (default, Apr 12 2023, 12:22:04) [GCC 10.2.1 20210110] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import paddle
> > > > Error: Can not import paddle core while this file exists: /usr/local/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
> > > > Traceback (most recent call last):
> > > > File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 249, in 
> > > > from . import libpaddle
> > > > ImportError: /usr/local/lib/python3.7/site-packages/paddle/fluid/libpaddle.so: undefined symbol: shm_unlink
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "", line 1, in File "/usr/local/lib/python3.7/site-packages/paddle/**init**.py", line 25, in from .framework import monkey_patch_variable File "/usr/local/lib/python3.7/site-packages/paddle/framework/**init**.py", line 17, in from . import random # noqa: F401 File "/usr/local/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in import paddle.fluid as fluid File "/usr/local/lib/python3.7/site-packages/paddle/fluid/**init**.py", line 36, in from . import framework File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in from . import core File "/usr/local/lib/python3.7/site-packages/paddle/fluid/core.py", line 300, in if not avx_supported() and libpaddle.is_compiled_with_avx(): NameError: name 'libpaddle' is not defined
> 
> > > >

@quelle1 This is because the Paddle is not able to load the libpaddle.so file. I had the same problem, it turned out to be libpaddle.so is not compatible with the architecture **arm64**.  I can see your CPU is also **arm64**, I tried with **x86_64** and it worked perfectly fine.

**Comment by AsifMehmood97** [comment]
> ### 问题描述 Issue Description
> 在 python3.8/3.7环境下安装完paddlepaddle==2.4.0之后，不能导入libpaddle.so文件。
> 
> 可是我从 pypi server 上面下载了对应版本的whl包解压之后发现里面还是有对应的libpaddle.so文件，就感觉到很奇怪。
> 
> 我在paddlenlp 的一个 pr 里面尝试解决此问题：[https://github.com/PaddlePaddle/PaddleNLP/pull/3859。](https://github.com/PaddlePaddle/PaddleNLP/pull/3859%E3%80%82)
> 
> 详细的编译信息请看：https://readthedocs.org/api/v2/build/18703479.txt
> 
> ### 版本&环境信息 Version & Environment Information
> 具体环境请看： PaddlePaddle == 2.4.0 python 3.7 centos
> 
> 由于程序是运行在readthedocs 服务器上，更相信的环境信息这边是没办法拿到，你们可以通过日志查看更多详细信息。

Check with your CPU architecture, its **arm64** based then it doesn't support the libpaddle.so. I had to create a docker with **x86_64** architecture and deployed in **x86_64** architecture of lambda and it worked.
