### ISSUE TITLE
Exception not handled

### ISSUE THREAD

**Issue by emilygong-zhuying** [PaddlePaddle/Paddle#48302]
### bug描述 Describe the Bug

[My Jupyter Notebook](https://github.com/emilygong-zhuying/Weibo-Network-Analysis/blob/main/paddle_training.ipynb) 

可以进入上面的链接Ctrl + F “mytest(model, metric, actual_test_data_loader)” 查看报错的cell。我用同样的mytest function evaluate过我的dev data，是没有问题的。parameters也都有对应换过，所以照理来说不应该有问题。。。我看了我的dataloader，感觉是正常的，每一个tensor也都在max_length之下。

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/home/emilygong/miniconda3/envs/paddle_env/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/emilygong/miniconda3/envs/paddle_env/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/emilygong/miniconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/home/emilygong/miniconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/home/emilygong/miniconda3/envs/paddle_env/lib/python3.9/site-packages/paddlenlp/datasets/dataset.py", line 276, in __getitem__
    self.new_data[idx]
IndexError: list index out of range
```

### 其他补充信息 Additional Supplementary Information

在第一个iteration之后，这个Exception就会出来，但是loop还是会一直跑到底（可以看我的notebook cell output）。不太理解为什么不会直接停下来

**Comment by zh794390558** [comment]
`IndexError: list index out of range` check下吧。还有num workers 设置成0试试。

**Comment by emilygong-zhuying** [comment]
> `IndexError: list index out of range` check下吧。还有num workers 设置成0试试。

在DataLoader里面把num_workers=0之后出现一个不同的error，
<img width="1038" alt="Screen Shot 2022-11-30 at 7 28 24 AM" src="https://user-images.githubusercontent.com/74880355/204839439-d369e1f5-6872-45da-93a6-1d0e05e25001.png">

**Comment by emilygong-zhuying** [comment]
找到问题了，是我自己设置test_batch_sampler时设置错了
