### ISSUE TITLE
OSError: (External) CUDA error(716), misaligned address. 

### ISSUE THREAD

**Issue by Fordacre** [PaddlePaddle/Paddle#48442]
### 请提出你的问题 Please ask your question

使用paddle程序运行时报错OSError: (External) CUDA error(716), misaligned address. 使用paddle版本2.2.2。找不到解决问题的头绪。麻烦帮忙看一下。
![image](https://user-images.githubusercontent.com/12699033/204219020-e77484cb-efa9-43ef-85c1-66d4431c11d0.png)

**Comment by yghstill** [comment]
@Fordacre 可能是CUDA环境的问题，请问是使用Paddle框架还是Paddle Inference预测呢？如果是Paddle，那运行`paddle.utils.run_check()`看下是否运行正常呢？

**Comment by Fordacre** [comment]
@yghstill 看起来不太像，因为在Inference过程中有些程序能运行成功，有些不能（主要在于输入数据区别）。是否是因为paddle在处理一些特殊字符的时候产生了越界问题呢？而且比较奇怪的是将batch size调整为1，便没有报错了。
下图为`paddle.utils.run_check()`命令运行结果，看起来是正常的。
![image](https://user-images.githubusercontent.com/12699033/204264856-40bd554c-8a72-4a9b-a92d-96c8a1c003ed.png)

**Comment by Fordacre** [comment]
初步定位是paddle.text.ViterbiDecoder的问题。因为在此op之前的数据可以打印，之后的便无法打印了。

**Comment by Fordacre** [comment]
@yghstill 请问这个问题有什么解决方案嘛。

**Comment by yghstill** [comment]
@Fordacre 有最小单测吗？我们复现并解决下这个问题

**Comment by Fordacre** [comment]
@yghstill 不好意思，最近没有看notifications。现在生成了3个存储数据的npy文件，请问这个要怎么提供给你那边呢。此外，include_bos_eos_tag设置为False。

**Comment by eric-gitta-moore** [comment]
同样问题

https://aistudio.baidu.com/aistudio/projectdetail/6545272

使用这个项目，在 docker 里面运行 `docker run --rm --gpus all --ipc=host -v .:/app -it nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04 /bin/bash`

```shell
LPD-project on  master [!] is 󰏗 v0.1.0 via  v3.12.3 (lpd-project) took 11m6s at 13:29:50 
❯ docker run --rm --gpus all --ipc=host -v .:/app -it nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04 /bin/bash

LPD-project on  master [!] is 󰏗 v0.1.0 via  v3.12.3 (lpd-project) at 13:29:52 
❯ nvidia-smi 
Sat May  3 13:30:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.51.02              Driver Version: 576.02         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1060        On  |   00000000:01:00.0 Off |                  N/A |
| N/A   65C    P2             25W /   78W |    1084MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A               1      C   /python3.8                            N/A      |
+-----------------------------------------------------------------------------------------+

LPD-project on  master [!] is 󰏗 v0.1.0 via  v3.12.3 (lpd-project) at 13:30:13 
❯ cat /etc/os-release                
PRETTY_NAME="Ubuntu 24.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.2 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

LPD-project on  master [!] is 󰏗 v0.1.0 via  v3.12.3 (lpd-project) at 13:30:20 
❯ usname -a
zsh: command not found: usname

LPD-project on  master [!] is 󰏗 v0.1.0 via  v3.12.3 (lpd-project) at 13:30:22 
❯ uname -a 
Linux DESKTOP-SURJD4A 5.15.167.4-microsoft-standard-WSL2 #1 SMP Tue Nov 5 00:21:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

LPD-project on  master [!] is 󰏗 v0.1.0 via  v3.12.3 (lpd-project) at 13:30:19 
❯ 
```

project.toml
```toml
[project]
name = "lpd-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "albumentations>=1.0.3",
    "gitpython>=3.1.30",
    "jupyterlab>=4.4.1",
    "matplotlib>=3.2.2",
    "numpy>=1.18.5",
    "opencv-python>=4.1.1",
    "pandas>=1.1.4",
    "pillow>=7.1.2",
    "pip>=25.1",
    "psutil>=7.0.0",
    "pyyaml>=5.3.1",
    "requests>=2.23.0",
    "scipy>=1.4.1",
    "seaborn>=0.11.0",
    "setuptools>=65.5.1",
    "tqdm>=4.64.0",
    "paddlepaddle-gpu==2.6.*",
    # "torch==2.0.0+cu118",
]

[tool.uv.pip]
index-strategy = "unsafe-best-match"

[tool.uv.sources]
torch = [{ index = "torch" }]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true

[[tool.uv.index]]
name = "torch"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

```

错误信息
```log
/home/linux/workspace/LPD-project/.venv/lib/python3.9/site-packages/albumentations/__init__.py:24: UserWarning: A new version of Albumentations is available: 2.0.6 (you have 0.0.19). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
[34m[1mval: [0mdata=/home/linux/workspace/LPD-project/YOLOv5-LPD-Keypoint/yolov5-Paddle/data/plate.yaml, weights=['runs/train/exp3/weights/best.pdparams'], cfg=, batch_size=32, imgsz=640, conf_thres=0.5, iou_thres=0.3, max_det=300, task=val, device=, workers=8, single_cls=False, augment=False, verbose=False, save_txt=False, save_hybrid=False, save_conf=False, save_json=False, project=runs/val, name=exp, exist_ok=False, half=False, dnn=False
WARNING ⚠️ confidence threshold 0.5 > 0.001 produces invalid results
YOLOv5 🚀 2025-5-1 Python-3.9.22 paddle-2.6.2 CUDA:0 (NVIDIA GeForce GTX 1060, 6144MiB)

W0503 12:17:48.006968 755260 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.9, Runtime API Version: 11.8
W0503 12:17:48.008131 755260 gpu_resources.cc:164] device: 0, cuDNN Version: 9.8.
Fusing layers... 
Model summary: 156 layers, 1771342 parameters, 18942 gradients, 4.2 GFLOPs
[34m[1mval: [0mScanning /home/linux/workspace/LPD-project/YOLOv5-LPD-Keypoint/datasets/val[0m
                 Class     Images  Instances          P          R      mAP50   
Traceback (most recent call last):
  File "/home/linux/workspace/LPD-project/YOLOv5-LPD-Keypoint/yolov5-Paddle/val.py", line 216, in run
    preds = non_max_suppression(preds,
  File "/home/linux/workspace/LPD-project/YOLOv5-LPD-Keypoint/yolov5-Paddle/utils/general.py", line 979, in non_max_suppression
    x = x[xc[xi]]  # confidence
  File "/home/linux/workspace/LPD-project/.venv/lib/python3.9/site-packages/paddle/base/dygraph/tensor_patch_methods.py", line 897, in __getitem__
    return self._getitem_dygraph(item)
OSError: (External) CUDA error(716), misaligned address. 
  [Hint: 'cudaErrorMisalignedAddress'. The device encountered a load or store instruction on a memory address which is not aligned. This leaves the process in aninconsistent state and any further CUDA work will return the same error. To continue using CUDA, the process must be terminatedand relaunched.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:265)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linux/workspace/LPD-project/YOLOv5-LPD-Keypoint/yolov5-Paddle/val.py", line 411, in <module>
    main(opt)
  File "/home/linux/workspace/LPD-project/YOLOv5-LPD-Keypoint/yolov5-Paddle/val.py", line 382, in main
    run(**vars(opt))
  File "/home/linux/workspace/LPD-project/.venv/lib/python3.9/site-packages/decorator.py", line 235, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/linux/workspace/LPD-project/.venv/lib/python3.9/site-packages/paddle/base/dygraph/base.py", line 352, in _decorate_function
    return func(*args, **kwargs)
  File "/home/linux/workspace/LPD-project/YOLOv5-LPD-Keypoint/yolov5-Paddle/val.py", line 216, in run
    preds = non_max_suppression(preds,
  File "/home/linux/workspace/LPD-project/YOLOv5-LPD-Keypoint/yolov5-Paddle/utils/general.py", line 181, in __exit__
    self.dt = self.time() - self.start  # delta-time
  File "/home/linux/workspace/LPD-project/YOLOv5-LPD-Keypoint/yolov5-Paddle/utils/general.py", line 186, in time
    paddle.device.cuda.synchronize()
  File "/home/linux/workspace/LPD-project/.venv/lib/python3.9/site-packages/paddle/device/cuda/__init__.py", line 125, in synchronize
    return core._device_synchronize(device_id)
OSError: (External) CUDA error(716), misaligned address. 
  [Hint: 'cudaErrorMisalignedAddress'. The device encountered a load or store instruction on a memory address which is not aligned. This leaves the process in aninconsistent state and any further CUDA work will return the same error. To continue using CUDA, the process must be terminatedand relaunched.] (at /paddle/paddle/fluid/pybind/cuda_streams_py.cc:88)
```

**Comment by eric-gitta-moore** [comment]
更新 1
可能这个情况是 gpu 环境和 paddle 的一个兼容性问题，即便是使用官方 docker 
`ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle:2.6.2-gpu-cuda12.0-cudnn8.9-trt8.6` 也会出现一模一样的问题

我放弃了 1060，换到 V100 之后没有任何问题

**Comment by eric-gitta-moore** [comment]
update 2

找到问题了，我在 aistudio 仔细对了一下 paddle 版本号是 paddlepaddle-gpu==2.4.1.post112 （挺抽象，用 2.4.2 都会报 cuda 716）
然后找官方文档重新安装 whl `find-links = ["https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html"]`

不过我的驱动是 cuda12，得再手动补一个 cuda 11 的 runtime，不然会缺少 `libcudart11.0.so`

> 参考官方文档 https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#pip-wheels
>
> pip/conda/deb/local/runfile 安装都可以

```sh
pip install nvidia-cuda-runtime-cu11
 (lpd-project) worker@LPD-project# find .venv -name 'libcudart.so*'
.venv/lib/python3.9/site-packages/nvidia/cuda_runtime/lib/libcudart.so.11.0
export LD_LIBRARY_PATH=$HOME/.venv/lib/python3.9/site-packages/nvidia/cuda_runtime/lib:$LD_LIBRARY_PATH
```
