### ISSUE TITLE
2.4.0版本的缺少 libpython3.8.so.1.0 

### ISSUE THREAD

**Issue by turkeymz** [PaddlePaddle/Paddle#48445]
### bug描述 Describe the Bug

BUG描述
更新Paddle 2.4.0后版本在import paddle时缺少 libpython3.8.so.1.0。参考BUG[48428](https://github.com/PaddlePaddle/Paddle/issues/48428)，全局搜索了一下该文件，也没有找到。

环境
PaddlePaddle 2.4.0
CentOS
Python 3.8

```python
>>> import paddle
Error: Can not import paddle core while this file exists: /usr/local/python3/lib/python3.8/site-packages/padd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/usr/local/python3/lib/python3.8/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
>>> exit()
[root@k8s-master-134 qy_addr_element]# find / -name libpython3.8.so.1.0

```

**Comment by turkeymz** [comment]
进一步的，我跟着paddlenlp关于Triton Server部署文档来做
发现官方triton容器也会出现同样的问题

**Comment by zh794390558** [comment]
参考 https://github.com/PaddlePaddle/Paddle/issues/48428 的解决方法试试。

**Comment by turkeymz** [comment]
> 参考 #48428 的解决方法试试。

这个方案不能满足。主要原因是服务器以及paddle推荐的Triton Server安装是官方python，不是anaconda。
我全盘搜索过，系统本身就缺少这些文件

**Comment by phlrain** [comment]
> > 参考 #48428 的解决方法试试。
> 
> 这个方案不能满足。主要原因是服务器以及paddle推荐的Triton Server安装是官方python，不是anaconda。 我全盘搜索过，系统本身就缺少这些文件

如果系统本身没有这个so文件，是怎么运行起来的呢

**Comment by turkeymz** [comment]
> ```python
> libpython3.8.so.1.0
> ```

不知道，可以根据官方提供Triton方案尝试一下。容器中安装2.4以后去import paddle根本不起来

**Comment by turkeymz** [comment]
> > > 参考 #48428 的解决方法试试。
> > 
> > 
> > 这个方案不能满足。主要原因是服务器以及paddle推荐的Triton Server安装是官方python，不是anaconda。 我全盘搜索过，系统本身就缺少这些文件
> 
> 如果系统本身没有这个so文件，是怎么运行起来的呢

不知道，可以根据官方提供Triton方案尝试一下。容器中安装2.4以后去import paddle根本不起来

**Comment by tong-zeng** [comment]
从报错信息上看，并不是说找不到 libpython3.8.so.1.0 ，而是 libpython3.8.so.1.0 抛出了错误消息，错误是 from . import libpaddle 引起的，也就是说 libpaddle import 不了，请检查下 PaddlePaddle 是否安装成功，例如 import paddle 试试。

**Comment by tong-zeng** [comment]
试试把 libpython3.9.so.1.0 这个文件复制到 /usr/lib
libpython3.9.so.1.0 这个文件在 /your/anaconda_home/envs/your_environment_name/lib 目录下
#48667

**Comment by turkeymz** [comment]
> 试试把 libpython3.9.so.1.0 这个文件复制到 /usr/lib libpython3.9.so.1.0 这个文件在 /your/anaconda_home/envs/your_environment_name/lib 目录下 #48667
