### ISSUE TITLE
linux安装addlepaddle-gpu.2.4.0.post112 出错

### ISSUE THREAD

**Issue by wchuan163** [PaddlePaddle/Paddle#48628]
### 问题描述 Issue Description

python -m pip install paddlepaddle-gpu==2.4.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

运行python,
import paddle 报错

Error: Can not import paddle core while this file exists: /home/omnisky/.local/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/omnisky/.local/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/omnisky/.local/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/omnisky/.local/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/omnisky/.local/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/omnisky/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/omnisky/.local/lib/python3.7/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/home/omnisky/.local/lib/python3.7/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

装回2.3.2版本又可以
pip install paddlepaddle-gpu==2.3.2 -i https://pypi.tuna.tsinghua.edu.cn/simple

这个大概是什么问题

### 版本&环境信息 Version & Environment Information

summary_env.py:52: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  plat = distro.linux_distribution()[0]
summary_env.py:53: DeprecationWarning: distro.linux_distribution() is deprecated. It should only be used as a compatibility shim with Python's platform.linux_distribution(). Please use distro.id(), distro.version() and distro.name() instead.
  ver = distro.linux_distribution()[1]
****************************************
Paddle version: 2.3.2
Paddle With CUDA: True

OS: Ubuntu 20.04
Python version: 3.7.6

CUDA version: 11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
cuDNN version: None.None.None
Nvidia driver version: 460.106.00
****************************************

**Comment by wchuan163** [comment]
参考
https://blog.csdn.net/w5688414/article/details/128070172
 已解决

**Comment by aiXia121** [comment]
> https://blog.csdn.net/w5688414/article/details/128070172

redhat 无法解决；
sudo cp /data//miniconda3/pkgs/python-3.7.16-h7a1cb2a_0/lib/libpython3.7m.so.1.0  /usr/lib/x86_64-redhat-linux6E/
