### ISSUE TITLE
Win10+RTX3090+Cuda11.7+Paddle2.4安装paddlepaddle报错

### ISSUE THREAD

**Issue by xuxiaoye212** [PaddlePaddle/Paddle#48622]
### 问题描述 Issue Description

Windows10系统，使用Anaconda新建了paddle的环境，安装了paddlepaddle之后，执行 paddle.utils.run_check()，报错
如下所示：
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W1201 16:48:11.781360  7152 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
W1201 16:48:11.843880  7152 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rovision\anaconda3\envs\paddle\lib\site-packages\paddle\utils\install_check.py", line 270, in run_check
    _run_dygraph_single(use_cuda, use_xpu, use_npu)
  File "C:\Users\rovision\anaconda3\envs\paddle\lib\site-packages\paddle\utils\install_check.py", line 136, in _run_dygraph_single
    linear_out = linear(input_tensor)
  File "C:\Users\rovision\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\rovision\anaconda3\envs\paddle\lib\site-packages\paddle\nn\layer\common.py", line 175, in forward
    out = F.linear(
  File "C:\Users\rovision\anaconda3\envs\paddle\lib\site-packages\paddle\nn\functional\common.py", line 1882, in linear
    return _C_ops.linear(x, weight, bias)
OSError: Invalid enum backend type `63`.
  [..\paddle/phi/common/backend.h:140]

****************************************
Paddle version: 2.4.0
Paddle With CUDA: True

OS: Windows 10
Python version: 3.9.15

CUDA version: 11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
cuDNN version: None.None.None
Nvidia driver version: 526.98
****************************************
![Uploading baocuo.png…]()

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.4.0
Paddle With CUDA: True

OS: Windows 10
Python version: 3.9.15

CUDA version: 11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
cuDNN version: None.None.None
Nvidia driver version: 526.98
****************************************

**Comment by zhwesky2010** [comment]
@xuxiaoye212 这个问题比较奇怪，试试随便调一个其他API会不会挂，比如`paddle.to_tensor(1.)` ，另外试一试非anaconda会出这个问题吗？

**Comment by pigwing** [comment]
@zhouwei25 我的issues也是这个问题,不过是type 64
https://github.com/PaddlePaddle/Paddle/issues/49133
