### ISSUE TITLE
Bug while Running the tools/train.py on cpu machine

### ISSUE THREAD

**Issue by rahulvish2144** [PaddlePaddle/Paddle#48661]
I'm facing this issue while running the training pipeline on CPU machine, can anyone help me out here?

Traceback (most recent call last):
  File "C:\Projects\elevance\jupyter-notebooks\paddle-ocr\PaddleOCR-release-2.6\PaddleOCR-release-2.6\tools\train.py", line 205, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "C:\Projects\elevance\jupyter-notebooks\paddle-ocr\PaddleOCR-release-2.6\PaddleOCR-release-2.6\tools\program.py", line 657, in preprocess
    .dev_id) if use_gpu else 'cpu'
  File "c:\Projects\virtual-environment\elevance-venv\lib\site-packages\paddle\fluid\dygraph\parallel.py", line 208, in device_id
    return self._device_id
AttributeError: 'ParallelEnv' object has no attribute '_device_id'. Did you mean: 'device_id'?

Also, I checked running the below code snippet:
`import paddle
paddle.utils.run_check()`

Output:
Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 CPU.
PaddlePaddle works well on 2 CPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by MissPenguin** [comment]
The GPU is used by default for training. If you want to train on CPU, you need to set the parameter "use_gpu" to false in the configuration file. But model training on CPU is not recommended.
