### ISSUE TITLE
Paddle 2.4.0 版本 fluid/core.py 文件 import libpaddle 出错

### ISSUE THREAD

**Issue by tong-zeng** [PaddlePaddle/Paddle#48667]
### bug描述 Describe the Bug

Ubuntu 20.04 安装 PaddlePaddle 使用命令： `conda install paddlepaddle-gpu==2.4.0 cudatoolkit=11.6 -c  Paddle -c conda-forge` 
新建的 Conda 环境，安装脚本执行成功，但 import paddle 时报错：

```
>>> import paddle
Error: Can not import paddle core while this file exists: /cpfs/user/zhaochenxu1/software/anaconda3/envs/zengtong_paddle/lib/python3.9/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cpfs/user/zhaochenxu1/software/anaconda3/envs/zengtong_paddle/lib/python3.9/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/cpfs/user/zhaochenxu1/software/anaconda3/envs/zengtong_paddle/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/cpfs/user/zhaochenxu1/software/anaconda3/envs/zengtong_paddle/lib/python3.9/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/cpfs/user/zhaochenxu1/software/anaconda3/envs/zengtong_paddle/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/cpfs/user/zhaochenxu1/software/anaconda3/envs/zengtong_paddle/lib/python3.9/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/cpfs/user/zhaochenxu1/software/anaconda3/envs/zengtong_paddle/lib/python3.9/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/cpfs/user/zhaochenxu1/software/anaconda3/envs/zengtong_paddle/lib/python3.9/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libpython3.9.so.1.0: cannot open shared object file: No such file or directory
```

测试了 Python 3.9, Python 3.10 版本，都会出现类似错误。

nvcc 版本：
```
Cuda compilation tools, release 11.6, V11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0
```

Pytorch 安装 cudatoolkit=11.6 版本可以正常运行。

**Comment by tong-zeng** [comment]
可以通过把 libpython3.9.so.1.0 这个文件复制到  /usr/lib 目录临时解决
libpython3.9.so.1.0 这个文件在 /your/anaconda_home/envs/your_environment_name/lib 目录下
`cp /your/anaconda_home/envs/your_environment_name/lib/libpython3.9.so.1.0 /usr/lib`

**Comment by yongshangli** [comment]
I got the same error. 
Exactly the same.

**Comment by Freshield** [comment]
Get same error in Python3.9 both conda install and pip install

**Comment by icedream2linxi** [comment]
这个问题在 2.4.2 下依然存在。
我猜测原因大概率是 libpaddle.so 的 RPATH 设置不对，缺少 $ORIGIN/../lib/。
https://docs.conda.io/projects/conda-build/en/stable/resources/use-shared-libraries.html
