### ISSUE TITLE
AttributeError: module 'paddle' has no attribute 'float16'

### ISSUE THREAD

**Issue by BaiMeiyingxue** [PaddlePaddle/Paddle#48743]
### 请提出你的问题 Please ask your question

when i download the Knover and run python Knover/knover/scripts/train.py
the error AttributeError: module 'paddle' has no attribute 'float16' occured:

Traceback (most recent call last):
  File "Knover/knover/scripts/train.py", line 319, in <module>
    train(args)
  File "Knover/knover/scripts/train.py", line 95, in train
    model = models.create_model(args, place)
  File "/home/aistudio/Knover/knover/models/__init__.py", line 46, in create_model
    return MODEL_REGISTRY[args.model](args, place)
  File "/home/aistudio/Knover/knover/models/unified_transformer.py", line 99, in __init__
    super(UnifiedTransformer, self).__init__(args, place)
  File "/home/aistudio/Knover/knover/core/model.py", line 155, in __init__
    self._build_programs()
  File "/home/aistudio/Knover/knover/core/model.py", line 255, in _build_programs
    outputs = self.forward(inputs)
  File "/home/aistudio/Knover/knover/models/unified_transformer.py", line 433, in forward
    gather_idx=inputs.get("parent_idx", None)
  File "/home/aistudio/Knover/knover/models/unified_transformer.py", line 273, in _generation_network
    name="encoder" if name == "" else name)
  File "/home/aistudio/Knover/knover/models/unified_transformer.py", line 315, in _encode
    topo=self.topo
  File "/home/aistudio/Knover/knover/modules/transformer_block.py", line 501, in encoder
    topo=topo)
  File "/home/aistudio/Knover/knover/modules/transformer_block.py", line 388, in encoder_layer
    name=name + "_pre_att"),
  File "/home/aistudio/Knover/knover/modules/transformer_block.py", line 326, in pre_post_process_layer
    if out_dtype == paddle.float16:
AttributeError: module 'paddle' has no attribute 'float16'

the version of the packages are
paddlehub                      2.0.4
paddlenlp                      2.0.7
paddlepaddle-gpu               2.0.2.post101

could you give me some guidances? thank you!

**Comment by haoyuying** [comment]
we recomment you to upgrade the paddle with the latest version v2.4, for more details for  installation: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html
