### ISSUE TITLE
IterableDataset+DataLoader训练一段时间报错

### ISSUE THREAD

**Issue by yzhw9981** [PaddlePaddle/Paddle#48752]
### bug描述 Describe the Bug

IterableDataset+DataLoader
模型训练一段时间后报dataloader错误（trace栈没有报在我写的逻辑里）
——————————————————————————————————————————————————
Train step 24331...
Train step 24332...
Train step 24333...Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 530, in _thread_loop
    batch = self._get_data()
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 667, in _get_data
    batch.reraise()
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
TypeError: function takes exactly 5 arguments (1 given)

Train step 24334...

——————————————————————————————————————————————————————
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    main()
  File "train.py", line 114, in main
    for data in train_reader():
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 762, in __next__
    data = self._reader.read_next()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

模型代码&报错信息见pdc训练日志
http://10.127.43.140:8388/v1/containers/52ba1bc0fde671777d3602d486e71bf7769f843d8c6125ee4bfc2235c12f2763/backuplog

### 其他补充信息 Additional Supplementary Information

pd2.3.0
场内pdc标准镜像

**Comment by yzhw9981** [comment]
日志文件
env_run/nohup.out

**Comment by yzhw9981** [comment]
另，在pd1.8环境里，相同reader代码，使用fluid.io.DataLoader.from_generator无此问题，可以顺利训练1+ epoch

**Comment by haoyuying** [comment]
请检查数据集中是否有非法数据或者一些隐藏文件等

**Comment by Shixiaowei02** [comment]
您好，这个页面打开是空白的，请问能提供一个复现环境吗，谢谢
http://10.127.43.140:8388/v1/containers/52ba1bc0fde671777d3602d486e71bf7769f843d8c6125ee4bfc2235c12f2763/backuplog

**Comment by yzhw9981** [comment]
@haoyuying 问题已解决，多谢。py3对于非utf8编码兼容性没有py2好，导致了我们reader在pd1.8+py2环境没问题，在pd2.3+py3环境就出错
不过也请看一下，paddle如何在reader有问题时输出下reader的报错栈，这样用户也容易定位一些。
