### ISSUE TITLE
Permission denied: '/.paddleocr'

### ISSUE THREAD

**Issue by Jinzhou511** [PaddlePaddle/Paddle#48873]
## Background
I am building a container that uses PaddleOCR to extract words in the image. repo link: https://github.com/Jinzhou511/pl-ocr-tool
## How to reproduce
git clone this repo and docker build the image, use command

``docker run --rm -u $(id -u)                                             -v $(pwd)/in:/incoming -v $(pwd)/out:/outgoing                      YOUR_DOCKERHUB_NAME/pl-ocr_tool ocr_tool                                        /incoming /outgoing``

## Environment
Ubuntu 22.04, python 3.10.6
## Description
I can successfully docker build the image with paddleocr and paddlepaddle module imported. But when I run the image, it reports following error:

walt@waltubuntu:~/pl-ocr-tool$ ``docker run --rm -u $(id -u)                                             -v $(pwd)/in:/incoming -v $(pwd)/out:/outgoing                      walterzhao511/pl-ocr_tool ocr_tool                                        /incoming /outgoing``

Version: 0.1
Converting images in '/incoming' to text in '/outgoing'
Will use spa as language for OCR
Converting '/incoming/test3_german.jpg' to '/outgoing/test3_german.txt'
download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar to /.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer/ch_PP-OCRv3_det_infer.tar
Traceback (most recent call last):
  File "/usr/local/bin/ocr_tool", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/ocr_tool/__main__.py", line 6, in main
    chris_app.launch()
  File "/usr/local/lib/python3.9/site-packages/chrisapp/base.py", line 457, in launch
    self.run(self.options)
  File "/usr/local/lib/python3.9/site-packages/ocr_tool/ocr_tool.py", line 191, in run
    ocr = PaddleOCR(use_angle_cls=True, lang="ch")
  File "/usr/local/lib/python3.9/site-packages/paddleocr/paddleocr.py", line 485, in __init__
    maybe_download(params.det_model_dir, det_url)
  File "/usr/local/lib/python3.9/site-packages/paddleocr/ppocr/utils/network.py", line 52, in maybe_download
    os.makedirs(model_storage_directory, exist_ok=True)
  File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/local/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.paddleocr'

**Comment by jennydaman** [comment]
This issue has less to do with Paddle and more to do how Docker works, and its assumptions.

You are using the command `docker run` with the option  `-u $(id -u)` which manually sets a user ID (UID). The specified UID `$(id -u)` does not exist inside the container, so the container will not have a valid `$HOME` directory. As a fallback, `/` is treated as your `$HOME` directory, however the container user does not have write access to `/`.

The Paddle program wants to create a file called `$HOME/.paddleocr` and it is unable to do so.

The best workaround would be to disable the creation or use of the `.paddleocr` file. Please consult Paddle's documentation for how to do this.

A less ideal solution would be to do a "blackbox" approach: manually set the environment variable `HOME=/tmp`. You can do this by passing the option `-e HOME=/tmp` to `docker run`. If that works, you can make the change permanent by adding the line `ENV HOME=/tmp` to `Dockerfile`.

**Comment by Jinzhou511** [comment]
> This issue has less to do with Paddle and more to do how Docker works, and its assumptions.
> 
> You are using the command `docker run` with the option `-u $(id -u)` which manually sets a user ID (UID). The specified UID `$(id -u)` does not exist inside the container, so the container will not have a valid `$HOME` directory. As a fallback, `/` is treated as your `$HOME` directory, however the container user does not have write access to `/`.
> 
> The Paddle program wants to create a file called `$HOME/.paddleocr` and it is unable to do so.
> 
> The best workaround would be to disable the creation or use of the `.paddleocr` file. Please consult Paddle's documentation for how to do this.
> 
> A less ideal solution would be to do a "blackbox" approach: manually set the environment variable `HOME=/tmp`. You can do this by passing the option `-e HOME=/tmp` to `docker run`. If that works, you can make the change permanent by adding the line `ENV HOME=/tmp` to `Dockerfile`.

Thanks! The second approach "blackbox" actually makes the whole application work, but that brings another issue:

Every time I run this application, it would download some ``.tar`` file to the folders under the ``/tmp`` I created, it doesn't affect the function, but it is not that efficient. 

The log:

``download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar to /tmp/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer/ch_PP-OCRv3_det_infer.tar``
``100%|██████████| 3.83M/3.83M [00:21<00:00, 182kiB/s]``
``download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar to /tmp/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer/ch_PP-OCRv3_rec_infer.tar``
``100%|██████████| 11.9M/11.9M [00:13<00:00, 867kiB/s] ``
``download https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar to /tmp/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer.tar``
``100%|██████████| 2.19M/2.19M [00:11<00:00, 187kiB/s] ``
