### ISSUE TITLE
使用t2s模型进行stage 3时，即文本生成语音时，报ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int64_t, but desires to be int

### ISSUE THREAD

**Issue by Anonymoussubmitter123** [PaddlePaddle/Paddle#48971]
### bug描述 Describe the Bug

def evaluate(args):
                for i in range(len(phone_ids)):
                    part_phone_ids = phone_ids[i]
                    # acoustic model
                    if am_name == 'fastspeech2':
                        # multi speaker
                        if am_dataset in {"aishell3", "vctk", "mix"}:
                            spk_id = paddle.to_tensor(args.spk_id)
                            mel = am_inference(part_phone_ids, spk_id)
                        else:
                            mel = am_inference(part_phone_ids)
                    elif am_name == 'speedyspeech':
                        part_tone_ids = frontend_dict['tone_ids'][i]
                        if am_dataset in {"aishell3", "vctk", "mix"}:
                            spk_id = paddle.to_tensor(args.spk_id)
                            mel = am_inference(part_phone_ids, part_tone_ids,
                                               spk_id)
                        else:
                            mel = am_inference(part_phone_ids, part_tone_ids)  # 这句报错

### 其他补充信息 Additional Supplementary Information

Traceback (most recent call last):
  File "/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 267, in <module>
    main()
  File "/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 263, in main
    evaluate(args)
  File "/PaddleSpeech-develop/paddlespeech/t2s/exps/fastspeech2/../synthesize_e2e.py", line 129, in evaluate
    mel = am_inference(part_phone_ids)
  File "/root/anaconda3/envs/PaddleSpeech/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/PaddleSpeech/lib/python3.7/site-packages/paddle/fluid/dygraph/io.py", line 1274, in __i_m_p_l__
    return _run_dygraph(self, input, program_holder)
  File "/root/anaconda3/envs/PaddleSpeech/lib/python3.7/site-packages/paddle/fluid/dygraph/io.py", line 829, in _run_dygraph
    'program_id': _hash_with_id(trace_program)
  File "/root/anaconda3/envs/PaddleSpeech/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int64_t, but desires to be int
  [Hint: Expected valid == true, but received valid:0 != true:1.] (at /paddle/paddle/fluid/framework/tensor_impl.h:51)
  [operator < reshape2 > error]  [operator < run_program > error]

**Comment by zh794390558** [comment]
`ValueError: (InvalidArgument) Tensor holds the wrong type, it holds int64_t, but desires to be int`
请检查数据类型。
