### ISSUE TITLE
在使用OCR时有个bug, pickle.dump(saved_obj, f, protocol=protocol) MemoryError ,也就是pickle.dump()把大量数据写入文件发生MemoryError解决方法

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/Paddle#48984]
### bug描述 Describe the Bug

详细报错： https://github.com/PaddlePaddle/PaddleOCR/issues/8456 

也就是pickle.dump()把大量数据写入文件发生MemoryError解决方法
![图片](https://user-images.githubusercontent.com/6648329/206823349-806cdd70-9fd1-4948-8f3a-f214ea6ad3f3.png)

官方是不是要改成:  joblib

**Comment by zoooo0820** [comment]
你好，请问在这个case里，保存的数据对象的大小是多少呢

**Comment by gg22mm** [comment]
> 对象的大小是多少呢

具体是多少我不知道了，

报错代码路径：C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\paddle\framework\io.py

![图片](https://user-images.githubusercontent.com/6648329/206825099-d6199012-fbc3-4731-b50e-8d8f36ba0ee3.png)
---------------------------------------------------------------------------


![图片](https://user-images.githubusercontent.com/6648329/206825119-0faaff74-92c2-415c-9832-ae78c8a88a76.png)

这是官方的代码：翻译过来是： 当dict的值大于4GB时，“MAC python3”上出现错误，  官方已经发现这个问题了，但是没有解决


-------------------------------------------------------------------------
现在我在训练已经成功生成的如下：
![图片](https://user-images.githubusercontent.com/6648329/206825206-e0797db0-3cd5-4c6f-8512-e2c9e91a39d0.png)


但是训练到10多轮时就会报上面的错

**Comment by gg22mm** [comment]
我试了用 aistudio 运行没有问题

**Comment by foolfish1** [comment]
请问这个问题解决了吗？或者有有效解决方案么？

**Comment by zoooo0820** [comment]
@foolfish1 
短期可以参考这个issue描述中的内容，修改对应位置的代码，通过joblib的方式进行存储。长期看，因为这个修改涉及到第三方库的引入，目前我们还需要评估一下支持这个case的解决方案。

**Comment by PureWerZ** [comment]
请问不改变paddle源码，这个问题解决了吗

**Comment by gg22mm** [comment]
解决了。 如果报错就改上面的。如果还报错，上linux

**Comment by zhongmy20230403** [comment]
我改成joblib之后，又报这个问题，大佬知道啥情况不？
![image](https://github.com/PaddlePaddle/Paddle/assets/129714430/08271d4a-2861-4134-ad3b-d46592e46fb7)

[2024/06/25 13:29:50] ppocr INFO: train dataloader has 3 iters
[2024/06/25 13:29:50] ppocr INFO: valid dataloader has 1 iters
[2024/06/25 13:29:50] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 19 iterations
1649
Traceback (most recent call last):
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\joblib\numpy_pickle.py", line 553, in dump
    NumpyPickler(f, protocol=protocol).dump(value)
  File "D:\anaconda3\envs\paddle_env\lib\pickle.py", line 487, in dump
    self.save(obj)
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\joblib\numpy_pickle.py", line 355, in save
    return Pickler.save(self, obj)
  File "D:\anaconda3\envs\paddle_env\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "D:\anaconda3\envs\paddle_env\lib\pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "D:\anaconda3\envs\paddle_env\lib\pickle.py", line 997, in _batch_setitems
    save(v)
  File "D:\anaconda3\envs\paddle_env\lib\site-packages\joblib\numpy_pickle.py", line 355, in save
    return Pickler.save(self, obj)
  File "D:\anaconda3\envs\paddle_env\lib\pickle.py", line 578, in save
    rv = reduce(self.proto)
TypeError: cannot pickle 'Tensor' object
python-BaseException

Process finished with exit code 1
