### ISSUE TITLE
设置分层学习率报错

### ISSUE THREAD

**Issue by fengyunzaidushi** [PaddlePaddle/Paddle#49041]
```
param_group = [
                {'params': self.ernie_model.parameters()},
                {'params': self.fc_prediction_start.parameters(), 'learning_rate': 1e-2},
                {'params': self.fc_prediction_end.parameters(), 'learning_rate': 1e-2},
                {'params': self.fc_cls.parameters(), 'learning_rate': 1e-2}]

self.optimizer = paddle.optimizer.AdamW(learning_rate=self.lr_scheduler,
                                                    parameters=param_group,
                                                    weight_decay=weight_decay,
                                                    apply_decay_param_fun=lambda
                                                        n: not param_name_to_exclue_from_weight_decay.match(n),
                                                    epsilon=epsilon,
                                                    grad_clip=g_clip)
```

报错信息：
```
Traceback (most recent call last):
  File "D:\2020exe\Anaconda3\envs\paddle\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 6854, in program_guard
    yield
  File "I:\a2211daima\ernie_dqa_task1\erniekit\controller\static_trainer.py", line 349, in init_static_train_net
    self.optimizer.minimize(loss)
  File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\paddle\optimizer\optimizer.py", line 1176, in minimize
    no_grad_set=no_grad_set)
  File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\paddle\optimizer\optimizer.py", line 884, in backward
    act_no_grad_set, callbacks)
  File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\framework.py", line 443, in __impl__
    return func(*args, **kwargs)
  File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\backward.py", line 1672, in append_backward
    'fluid.backward.append_backward')
  File "D:\2020exe\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\data_feeder.py", line 124, in check_type
    (input_name, op_name, expected_type, type(input), extra_message))
TypeError: The type of 'parameter_list[0]' in fluid.backward.append_backward must be
 (<class 'paddle.fluid.framework.Variable'>, (<class 'str'>,)),
 but received <class 'dict'>. 
```

**Comment by ZhangHandi** [comment]
parameters参数支持传入list，不支持传入dict，paddle.optimizer.AdamW api的使用方法可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/AdamW_cn.html#adamw

**Comment by fengyunzaidushi** [comment]
> parameters参数支持传入list，不支持传入dict，paddle.optimizer.AdamW api的使用方法可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/AdamW_cn.html#adamw

大神，我就是按照这个文档写的。 就是为了设置线性层的学习率大一点，
```
adam = paddle.optimizer.AdamW(
    learning_rate=0.1,
    parameters=[{
        'params': linear_1.parameters()
    }, {
        'params': linear_2.parameters(),
        'weight_decay': 0.001,
        'learning_rate': 0.1,
        'beta1': 0.8
    }],
    weight_decay=0.01,
    beta1=0.9)
```

**Comment by fengyunzaidushi** [comment]
> parameters参数支持传入list，不支持传入dict，paddle.optimizer.AdamW api的使用方法可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/AdamW_cn.html#adamw

大神，我就是按照这个文档写的。 就是为了设置线性层的学习率大一点，
```
adam = paddle.optimizer.AdamW(
    learning_rate=0.1,
    parameters=[{
        'params': linear_1.parameters()
    }, {
        'params': linear_2.parameters(),
        'weight_decay': 0.001,
        'learning_rate': 0.1,
        'beta1': 0.8
    }],
    weight_decay=0.01,
    beta1=0.9)
```

**Comment by fengyunzaidushi** [comment]
```
param_group = [
                {'params': self.ernie_model.parameters()},
                {'params': self.fc_prediction_start.parameters(), 'learning_rate': 1e-2},
                {'params': self.fc_prediction_end.parameters(), 'learning_rate': 1e-2},
                {'params': self.fc_cls.parameters(), 'learning_rate': 1e-2}]
```
我这里参数是list，内在元素是dict，因为要同时设置学习率，和ernie3.0整体的学习率2e-5不一样。

**Comment by ZhangHandi** [comment]
在self.optimizer.minimize(loss)这里，设置下parameters参数，传入一个只包含参数的list，否则会默认使用前面传入的dict导致报错
