### ISSUE TITLE
安装paddle出现问题

### ISSUE THREAD

**Issue by dfcs008** [PaddlePaddle/Paddle#49106]
重新安装了pytorch 11.7 cuda版本。  显示torch.cuda.isavailable 为True  cudnn也有。 然后安装了paddle  
conda install paddlepaddle-gpu==2.4.1 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge

运行import paddle  没出现问题
运行paddle.utils.run_check() 出现如下问题

paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W1215 14:25:46.643707 14556 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.7, Runtime API Version: 11.7
W1215 14:25:46.644002 14556 dynamic_loader.cc:307] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/utils/install_check.py", line 173, in _run_static_single
    exe.run(startup_prog)
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1450, in run
    res = self._run_impl(program=program,
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1661, in _run_impl
    return new_exe.run(scope, list(feed.keys()), fetch_list,
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/executor.py", line 631, in run
    tensors = self._new_exe.run(scope, feed_names,
RuntimeError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/utils/install_check.py", line 159, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/utils/install_check.py", line 33, in _simple_network
      weight = paddle.create_parameter(
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/layers/tensor.py", line 152, in create_parameter
      return helper.create_parameter(attr, shape, convert_dtype(dtype), is_bias,
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
      self.startup_program.global_block().create_parameter(
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/framework.py", line 3965, in create_parameter
      initializer(param, self)
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/initializer.py", line 56, in __call__
      return self.forward(param, block)
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/initializer.py", line 184, in forward
      op = block.append_op(type="fill_constant",
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/framework.py", line 4017, in append_op
      op = Operator(
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2858, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
      [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:60)
      [operator < fill_constant > error]

而后我所搜了一下，找到了这篇：
https://blog.csdn.net/weixin_41255438/article/details/124144722
运行了   find / -name 'cudnn' 
并找到并运行了类似的命令， export LD_LIBRARY_PATH='/usr/local/anaconda3/envs/rasa-gpu/lib/' 
后再运行import paddle  没出现问题
运行paddle.utils.run_check() 出现如下问题
paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W1215 14:42:27.344878 14576 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.7, Runtime API Version: 11.7
W1215 14:42:27.351974 14576 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/utils/install_check.py", line 173, in _run_static_single
    exe.run(startup_prog)
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1450, in run
    res = self._run_impl(program=program,
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1661, in _run_impl
    return new_exe.run(scope, list(feed.keys()), fetch_list,
  File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/executor.py", line 631, in run
    tensors = self._new_exe.run(scope, feed_names,
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/utils/install_check.py", line 159, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/utils/install_check.py", line 33, in _simple_network
      weight = paddle.create_parameter(
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/layers/tensor.py", line 152, in create_parameter
      return helper.create_parameter(attr, shape, convert_dtype(dtype), is_bias,
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
      self.startup_program.global_block().create_parameter(
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/framework.py", line 3965, in create_parameter
      initializer(param, self)
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/initializer.py", line 56, in __call__
      return self.forward(param, block)
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/initializer.py", line 184, in forward
      op = block.append_op(type="fill_constant",
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/framework.py", line 4017, in append_op
      op = Operator(
    File "/home/bdhxx/miniconda3/envs/flc-HRnet/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2858, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDA error(214), uncorrectable ECC error encountered. 
      [Hint: Please search for the error code(214) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/core/cuda_stream.h:73)
      [operator < fill_constant > error]

**Comment by dfcs008** [comment]
本GPU服务器已经安装了pytorch， 并成功运行了很多程序。

**Comment by yt605155624** [comment]
Hint: Please search for the error code(214) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.

**Comment by dfcs008** [comment]
> Hint: Please search for the error code(214) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.

why did pytorch work when I just pip install ?

**Comment by dfcs008** [comment]
> Hint: Please search for the error code(214) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.

so how can I solve the problem? I could not find the answer

**Comment by ghost** [comment]
看来不是我一个人有这个问题，本来想支持一波国产框架，发现我不配，🦀🦀，安装都装不上

**Comment by zxjt2012** [comment]
我是用anaconda安装的，也出现这个问题，输入下面命令，暂时解决。
export LD_LIBRARY_PATH='/home/{用户名}/anaconda3/envs/{虚拟环境名}/lib/'

pa>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0124 22:52:18.063221 126315 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
W0124 22:52:18.068292 126315 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
>>>

**Comment by ghost** [comment]
我用的miniconda，然后挂代理，从国外访问下载，才成功了。可能是conda访问网络有问题。

**Comment by hushuguo** [comment]
> 
我发现还是不行
