### ISSUE TITLE
张量索引

### ISSUE THREAD

**Issue by zkyseu** [PaddlePaddle/Paddle#49101]
### 需求描述 Feature Description

paddle和torch的索引有些差异，该怎么实现
>>> import torch
>>> a = torch.rand(8,128,23,48)
>>> b = torch.arange(23)
>>> c = a[...,b,:]
>>> import paddle
>>> d = paddle.rand((8,128,23,48))
>>> e = paddle.arange(23)
>>> f = d[...,e,:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fyj/anaconda3/envs/zky/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 736, in __getitem__
    return _getitem_impl_(self, item)
  File "/home/fyj/anaconda3/envs/zky/lib/python3.7/site-packages/paddle/fluid/variable_index.py", line 341, in _getitem_impl_
    item = replace_ellipsis(var, item)
  File "/home/fyj/anaconda3/envs/zky/lib/python3.7/site-packages/paddle/fluid/variable_index.py", line 222, in replace_ellipsis
    len(var.shape) - len(item) + item.count(None) + 1)
  File "/home/fyj/anaconda3/envs/zky/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 258, in __impl__
    value=other_var, dtype=lhs_dtype)
  File "/home/fyj/anaconda3/envs/zky/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 90, in create_scalar
    return create_tensor(value, dtype, shape=[1])
  File "/home/fyj/anaconda3/envs/zky/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/fyj/anaconda3/envs/zky/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 299, in __impl__
    return func(*args, **kwargs)
  File "/home/fyj/anaconda3/envs/zky/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 85, in create_tensor
    value, 'force_cpu', False)
ValueError: (InvalidArgument) fill_constant(): argument (position 6) must be float, but got NoneType (at /paddle/paddle/fluid/pybind/op_function_common.cc:189)

**Comment by yt605155624** [comment]
参考文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/tensor_cn.html#suoyinheqiepian

**Comment by zkyseu** [comment]
> 参考文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/tensor_cn.html#suoyinheqiepian

您好，我看文档里面没有提供我这个问题的解决方法，您可否看一下我的问题，然后帮我解决一下，谢谢

**Comment by yt605155624** [comment]
@zkyseu paddle 不支持 f = d[...,e,:] 这种切片方式，请按照文档中的方式进行切片
