### ISSUE TITLE
Cython编译后运行时报错：【AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.】

### ISSUE THREAD

**Issue by U019TT** [PaddlePaddle/Paddle#49169]
【paddle版本】
paddlepaddle-gpu       2.3.2.post112

【问题描述】
一个paddle模型单测程序，原始状态可以正常运行。 通过cython 将 py 脚本编译成 so 文件之后，运行会报错：

```
Traceback (most recent call last):
  File "tools/predict_rec_platform.py", line 204, in <module>
    main()
  File "tools/predict_rec_platform.py", line 92, in main
    paddle.jit.save(model, config['Global']['pretrained_model'] + "2")
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
    func(layer, path, input_spec, **configs)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/jit.py", line 861, in save
    inner_input_spec, with_hook=with_hook)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
    *desired_input_spec, with_hook=with_hook)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
    **cache_key.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "/home/xmind/train_platform/tools_emy/MaskOCR_eval_enc_emy/MaskOCR_src/ppocr/modeling/architectures/base_model.py", line 79, in forward
        """ forward """
        y = dict()
        x = self.backbone(x)
        ~~~~~~~~~~~~~~~~~~~~ <--- HERE
        y["backbone_out"] = x
        if self.use_neck:

    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "mm_vit_backbone.pyx", line 220, in mm_vit_backbone.MMVITBackbone.forward

    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "rec_vit.pyx", line 362, in rec_vit.Block.forward

    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "rec_vit.pyx", line 156, in rec_vit.DropPath.forward

    File "rec_vit.pyx", line 26, in rec_vit.drop_path

    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
	return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
	return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 433, in __impl__
	), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__

    AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

LAUNCH INFO 2022-12-19 08:24:48,945 Pod failed
LAUNCH ERROR 2022-12-19 08:24:48,945 Container failed !!!
Container rank 0 status failed cmd ['/usr/bin/python3.7', '-u', 'tools/predict_rec_platform.py'] code 1 log ./debug/default.ebsnad.0.log
env {'LIBRARY_PATH': '/usr/local/cuda/lib64/stubs', 'LANGUAGE': 'en_US.UTF-8', 'HOSTNAME': 'yq01-sys-hic-k8s-v100-box-a225-0005.yq01.baidu.com', 'GREP_COLOR': '1;31', 'LD_LIBRARY_PATH': '/usr/local/lib/python3.7/dist-packages/cv2/../../lib64:/usr/local/python2.7.15/lib:/opt/_internal/cpython-2.7.11-ucs4/lib:/opt/_internal/cpython-2.7.15-ucs4/lib:/opt/conda/envs/py27/lib:/opt/_internal/cpython-3.7.0/lib:/opt/conda/envs/py27/lib:/usr/local/cuda/lib64:/usr/local/cuda/targets/x86_64-linux/lib/:/usr/lib64:/usr/local/lib:/nccl/lib:/usr/lib64/mlnx_ofed/valgrind:/usr/local/lib/python2.7/site-packages/paddle/libs:/usr/local/cuda-11.2/targets/x86_64-linux/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64', 'SHLVL': '1', 'HOME': '/root', 'OLDPWD': '/home/xmind/train_platform/tools_emy/MaskOCR_eval_enc_emy', 'PS1': '\\[\\033[1;33m\\]λ \\[\\033[1;37m\\]\\h \\[\\033[1;32m\\]\\w \\[\\033[0m\\]', 'WITH_GPU': 'ON', 'GOROOT': '/usr/local/go', 'CUDA_VERSION': '11.2.1', 'WITH_AVX': 'ON', 'CUDA_VISIBLE_DEVICES': '6', 'NVIDIA_REQUIRE_CUDA': 'cuda>=11.2 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450,driver<451', '_': '/bin/sh', 'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility', 'TERM': 'xterm', 'PATH': '/opt/_internal/cpython-2.7.11-ucs4/bin:/opt/_internal/cpython-2.7.15-ucs4/bin:/opt/conda/envs/py27/bin:/root/paddlejob/hadoop-client/hadoop/bin:/usr/local/openmpi-3.1.0/bin:/root/paddlejob/hadoop-client/hadoop/bin:/opt/rh/devtoolset-2/root/usr/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/cmake-3.16.0-Linux-x86_64/bin:/usr/local/gcc-8.2/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/gopath/bin', 'GREP_OPTIONS': '--color=auto', 'LANG': 'en_US.UTF-8', 'CUDNN_VERSION': '8.1.1.33', 'DEBIAN_FRONTEND': 'noninteractive', 'GOPATH': '/root/gopath', 'LC_ALL': 'en_US.UTF-8', 'PWD': '/home/xmind/train_platform/tools_emy/MaskOCR_eval_enc_emy/MaskOCR_src', 'CLICOLOR': '1', 'NVIDIA_VISIBLE_DEVICES': 'all', 'NCCL_VERSION': '2.8.4', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'PADDLE_MASTER': '10.255.140.23:11460', 'PADDLE_GLOBAL_SIZE': '1', 'PADDLE_LOCAL_SIZE': '1', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_TRAINER_ENDPOINTS': '10.255.140.23:23201', 'PADDLE_CURRENT_ENDPOINT': '10.255.140.23:23201', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '1', 'PADDLE_RANK_IN_NODE': '0', 'FLAGS_selected_gpus': '0'}
args)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "/home/xmind/train_platform/tools_emy/MaskOCR_eval_enc_emy/MaskOCR_src/ppocr/modeling/architectures/base_model.py", line 79, in forward
        """ forward """
        y = dict()
        x = self.backbone(x)
        ~~~~~~~~~~~~~~~~~~~~ <--- HERE
        y["backbone_out"] = x
        if self.use_neck:

    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "mm_vit_backbone.pyx", line 220, in mm_vit_backbone.MMVITBackbone.forward

    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "rec_vit.pyx", line 362, in rec_vit.Block.forward

    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "rec_vit.pyx", line 156, in rec_vit.DropPath.forward

    File "rec_vit.pyx", line 26, in rec_vit.drop_path

    File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
	return caller(func, *(extras + args), **kw)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
	return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 433, in __impl__
	), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__

    AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

LAUNCH INFO 2022-12-19 08:24:48,946 Exit code 1
```

【问题】
看报错，大概是因为发现不是在动态图模式中，可是为啥原始状态就可以正常运行呢？

**Comment by haohongxiang** [comment]
@enmengyi paddle.to_tensor在2.3.2以及之前的paddle版本中，只支持在动态图模式下使用；2.4新版本增加了动转静对paddle.to_tensor的支持，所以您升级paddle版本为2.4后应该就能解决这个问题。
