### ISSUE TITLE
单机多卡环境中，x.clone() 报错 NotImplementedError

### ISSUE THREAD

**Issue by LemonNoel** [PaddlePaddle/Paddle#49215]
### bug描述 Describe the Bug

复现环境：

- paddlepaddle-gpu=develop (CUDA=11.2, CUDNN=8.1)
- paddlenlp=develop
- 代码路径：https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/ernie-health
- 执行脚本：
```shell
unset CUDA_VISIBLE_DEVICES
python -m paddle.distributed.launch --gpus "0,1" run_pretrain.py \
    --input_dir ./data \
    --output_dir ./output \
    --learning_rate 1e-7 \
    --batch_size 10 \
    --adam_epsilon 1e-8 \
    --weight_decay 1e-2 \
    --warmup_steps 10000 \
    --max_steps 1000000 \
    --save_steps 10000 \
    --logging_steps 1 \
    --seed 1000 \
    --use_amp
```
- 报错信息 log/workerlog.1
```shell
25939 ------------------------------------------------
25940 I1221 11:53:31.671428 19119 tcp_utils.cc:130] Successfully connected to 10.21.226.184:44296
25941 W1221 11:53:34.340793 19119 gpu_resources.cc:61] Please NOTE: device: 1, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
25942 W1221 11:53:34.344606 19119 gpu_resources.cc:91] device: 1, cuDNN Version: 8.1.
25943 ^[[32m[2022-12-21 11:53:34,583] [    INFO]^[[0m - Already cached /ssd2/.paddlenlp/models/ernie-health-chinese/vocab.txt^[[0m
25944 ^[[32m[2022-12-21 11:53:34,598] [    INFO]^[[0m - tokenizer config file saved in /ssd2/.paddlenlp/models/ernie-health-chinese/tokenizer_config.json^[[0m
25945 ^[[32m[2022-12-21 11:53:34,598] [    INFO]^[[0m - Special tokens file saved in /ssd2/.paddlenlp/models/ernie-health-chinese/special_tokens_map.json^[[0m
25946 ^[[32m[2022-12-21 11:53:35,996] [    INFO]^[[0m - start load data : 2022-12-21 11:53:35^[[0m
25947 ^[[32m[2022-12-21 11:53:36,017] [    INFO]^[[0m - load data done, total : 0.021075010299682617 s^[[0m
25948 ^[[32m[2022-12-21 11:53:36,031] [    INFO]^[[0m - start train : 2022-12-21 11:53:36^[[0m
25949 I1221 11:53:36.031898 19119 reader_py.cc:406] init_lod_tensor_blocking_queue
25950 I1221 11:53:36.032111 19119 buffered_reader.cc:50] BufferedReader
25951 Exception in thread Thread-1:
25952 Traceback (most recent call last):
25953   File "/ssd2/anaconda3/envs/black/lib/python3.8/threading.py", line 932, in _bootstrap_inner
25954     self.run()
25955   File "/ssd2/anaconda3/envs/black/lib/python3.8/threading.py", line 870, in run
25956     self._target(*self._args, **self._kwargs)
25957   File "/ssd2/anaconda3/envs/black/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 247, in _thread_loop
25958     batch = self._dataset_fetcher.fetch(
25959   File "/ssd2/anaconda3/envs/black/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 139, in fetch
25960     data = self.collate_fn(data)
25961   File "/ssd2/prompt/PaddleNLP/model_zoo/ernie-health/dataset.py", line 102, in __call__
25962     masked_input_ids_a, input_ids_a, labels_a = self.mask_tokens(data)
25963   File "/ssd2/prompt/PaddleNLP/model_zoo/ernie-health/dataset.py", line 123, in mask_tokens
25964     masked_token_ids = paddle.clone(token_ids)
25965   File "/ssd2/anaconda3/envs/black/lib/python3.8/site-packages/paddle/tensor/creation.py", line 2123, in clone
25966     return x.clone()
25967 NotImplementedError: (Unimplemented) Place Place(gpu:0) is not supported. Please check that your paddle compiles with WITH_GPU, WITH_XPU, WITH_IPU, WITH_MLU or WITH_ASCEND_      CL option or check that your train process set the correct device id if you use Executor. (at /paddle/paddle/fluid/platform/device_context.cc:122)
```

**Comment by zhaoyinglia** [comment]
你好。请问编译 paddle 的时候是否开启了 DWITH_GPU 选项

**Comment by LemonNoel** [comment]
你好，是直接从官网拉取的whl包
