### ISSUE TITLE
Can't import new package in PR-CI-Py3

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#49216]
### 背景
在PR https://github.com/PaddlePaddle/Paddle/pull/48000 中新增了package `paddle.quantization`，并修改了setup.py.in文件。
本地测试，在python3环境下安装paddle后，可以正常import paddle.quantization.

### 问题

在单测paddle/tests/quantization/test_quantization.py中引用了`paddle.quantization`
- [PR-CI-Coverage](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/7433065/job/21176202)可以正常执行以上单测
- [PR-CI-Py3](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/7437418/job/21182990)报错如下：

```
2022-12-16 16:59:37     Test #323: test_quant .......................***Failed    2.30 sec
2022-12-16 16:59:37 Hint: Your machine support AVX, but the installed paddlepaddle doesn't have avx core. Hence, no-avx core with worse preformance will be imported.
2022-12-16 16:59:37 If you like, you could reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version]' to get better performance.
2022-12-16 16:59:37 Traceback (most recent call last):
2022-12-16 16:59:37   File "test_quant.py", line 17, in <module>
2022-12-16 16:59:37     import paddle
2022-12-16 16:59:37   File "/opt/_internal/cpython-3.7.0/lib/python3.7/site-packages/paddle/__init__.py", line 88, in <module>
2022-12-16 16:59:37     import paddle.quantization  # noqa: F401
2022-12-16 16:59:37 ModuleNotFoundError: No module named 'paddle.quantization'
```

**Comment by wanghaoshuang** [comment]
需要修改[setup.py](https://github.com/PaddlePaddle/Paddle/blob/develop/setup.py#L1251)文件，添加新增的package
