### ISSUE TITLE
评估报错 ‘numpy.float64’ object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/Paddle#49292]
### bug描述 Describe the Bug

---------------------------------------------------------------------------------------------------------------------
1. 边训练边评估在评估的时候会报错，只训练不评估不报错。
---------------------------------------------------------------------------------------------------------------------
python tools/train.py -c configs/smalldet/ppyoloe_crn_l_80e_sliced_visdrone_640_025.yml --use_vdl=True --vdl_log_dir=./sliced_visdrone/ --eval

D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
'nearest': Image.NEAREST,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
'bilinear': Image.BILINEAR,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
'bicubic': Image.BICUBIC,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
'box': Image.BOX,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
'lanczos': Image.LANCZOS,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
'hamming': Image.HAMMING
W1222 17:18:04.070852 28056 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 11.2
W1222 17:18:04.075852 28056 device_context.cc:465] device: 0, cuDNN Version: 8.1.
W1222 17:18:05.134035 28056 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Traceback (most recent call last):
File "tools/eval.py", line 193, in
main()
File "tools/eval.py", line 189, in main
run(FLAGS, cfg)
File "tools/eval.py", line 143, in run
trainer.load_weights(cfg.weights)
File "D:\pkg\PaddleDetection\ppdet\engine\trainer.py", line 375, in load_weights
load_pretrain_weight(self.model, weights)
File "D:\pkg\PaddleDetection\ppdet\utils\checkpoint.py", line 209, in load_pretrain_weight
"config file.".format(path))
ValueError: Model pretrain path output/faster_rcnn_r50_vd_fpn_ssld_1x_rice/best_model does not exists. If you don't want to load pretrain model, please delete pretrain_weights field in config file.

(paddle) D:\pkg\PaddleDetection>python tools/eval.py -c configs/faster_rcnn/faster_rcnn_r50_vd_fpn_ssld_1x_rice.yml -o weights=output/faster_rcnn_r50_vd_fpn_ssld_1x_rice/model_final.pdparams
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
'nearest': Image.NEAREST,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
'bilinear': Image.BILINEAR,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
'bicubic': Image.BICUBIC,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
'box': Image.BOX,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
'lanczos': Image.LANCZOS,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
'hamming': Image.HAMMING
W1222 17:19:54.703459 37624 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 11.2
W1222 17:19:54.707639 37624 device_context.cc:465] device: 0, cuDNN Version: 8.1.
W1222 17:19:55.760320 37624 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[12/22 17:19:57] ppdet.utils.checkpoint INFO: Finish loading model weights: output/faster_rcnn_r50_vd_fpn_ssld_1x_rice/model_final.pdparams
[12/22 17:19:59] ppdet.engine INFO: Eval iter: 0
[12/22 17:20:00] ppdet.metrics.metrics INFO: The bbox result is saved to bbox.json.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[12/22 17:20:00] ppdet.metrics.coco_utils INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
Traceback (most recent call last):
File "tools/eval.py", line 193, in
main()
File "tools/eval.py", line 189, in main
run(FLAGS, cfg)
File "tools/eval.py", line 154, in run
trainer.evaluate()
File "D:\pkg\PaddleDetection\ppdet\engine\trainer.py", line 621, in evaluate
self._eval_with_loader(self.loader)
File "D:\pkg\PaddleDetection\ppdet\engine\trainer.py", line 613, in _eval_with_loader
metric.accumulate()
File "D:\pkg\PaddleDetection\ppdet\metrics\metrics.py", line 142, in accumulate
classwise=self.classwise)
File "D:\pkg\PaddleDetection\ppdet\metrics\coco_utils.py", line 111, in cocoapi_eval
coco_eval = COCOeval(coco_gt, coco_dt, style)
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\pycocotools-2.0-py3.7-win-amd64.egg\pycocotools\cocoeval.py", line 76, in init
self.params = Params(iouType=iouType) # parameters
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\pycocotools-2.0-py3.7-win-amd64.egg\pycocotools\cocoeval.py", line 527, in init
self.setDetParams()
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\pycocotools-2.0-py3.7-win-amd64.egg\pycocotools\cocoeval.py", line 507, in setDetParams
self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
File "<array_function internals>", line 6, in linspace
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\numpy\core\function_base.py", line 120, in linspace
num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

(paddle) D:\pkg\PaddleDetection>python tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_vd_fpn_ssld_1x_rice.yml -o LearningRate.base_lr=0.00125 worker_num=1 --eval
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
'nearest': Image.NEAREST,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
'bilinear': Image.BILINEAR,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
'bicubic': Image.BICUBIC,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
'box': Image.BOX,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
'lanczos': Image.LANCZOS,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
'hamming': Image.HAMMING
loading annotations into memory...
Done (t=0.05s)
creating index...
index created!
W1222 17:22:24.654457 42104 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 11.2
W1222 17:22:24.659533 42104 device_context.cc:465] device: 0, cuDNN Version: 8.1.
W1222 17:22:25.917392 42104 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
[12/22 17:22:28] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\NINGMEI/.cache/paddle/weights\ResNet50_vd_ssld_v2_pretrained.pdparams
[12/22 17:22:30] ppdet.engine INFO: Epoch: [0] [ 0/260] learning_rate: 0.000125 loss_rpn_cls: 0.693904 loss_rpn_reg: 0.356441 loss_bbox_cls: 0.673198 loss_bbox_reg: 0.035566 loss: 1.759109 eta: 1:33:46 batch_cost: 1.8035 data_cost: 0.0000 ips: 0.5545 images/s
[12/22 17:22:32] ppdet.engine INFO: Epoch: [0] [ 20/260] learning_rate: 0.000148 loss_rpn_cls: 0.691607 loss_rpn_reg: 0.224547 loss_bbox_cls: 0.403094 loss_bbox_reg: 0.030676 loss: 1.416234 eta: 0:09:23 batch_cost: 0.1006 data_cost: 0.0000 ips: 9.9356 images/s
[12/22 17:22:34] ppdet.engine INFO: Epoch: [0] [ 40/260] learning_rate: 0.000170 loss_rpn_cls: 0.687207 loss_rpn_reg: 0.209526 loss_bbox_cls: 0.203862 loss_bbox_reg: 0.114515 loss: 1.216542 eta: 0:07:14 batch_cost: 0.0987 data_cost: 0.0000 ips: 10.1364 images/s
[12/22 17:22:36] ppdet.engine INFO: Epoch: [0] [ 60/260] learning_rate: 0.000192 loss_rpn_cls: 0.679385 loss_rpn_reg: 0.185349 loss_bbox_cls: 0.402787 loss_bbox_reg: 0.423124 loss: 1.684347 eta: 0:06:32 batch_cost: 0.1019 data_cost: 0.0000 ips: 9.8099 images/s
[12/22 17:22:38] ppdet.engine INFO: Epoch: [0] [ 80/260] learning_rate: 0.000215 loss_rpn_cls: 0.672719 loss_rpn_reg: 0.274452 loss_bbox_cls: 0.485732 loss_bbox_reg: 0.582607 loss: 2.093315 eta: 0:06:12 batch_cost: 0.1045 data_cost: 0.0001 ips: 9.5707 images/s
[12/22 17:22:40] ppdet.engine INFO: Epoch: [0] [100/260] learning_rate: 0.000237 loss_rpn_cls: 0.661841 loss_rpn_reg: 0.209330 loss_bbox_cls: 0.563600 loss_bbox_reg: 0.706078 loss: 2.147810 eta: 0:06:03 batch_cost: 0.1123 data_cost: 0.0000 ips: 8.9028 images/s
[12/22 17:22:44] ppdet.engine INFO: Epoch: [0] [120/260] learning_rate: 0.000260 loss_rpn_cls: 0.649042 loss_rpn_reg: 0.179652 loss_bbox_cls: 0.570783 loss_bbox_reg: 0.846109 loss: 2.308572 eta: 0:06:29 batch_cost: 0.1774 data_cost: 0.0000 ips: 5.6361 images/s
[12/22 17:22:48] ppdet.engine INFO: Epoch: [0] [140/260] learning_rate: 0.000283 loss_rpn_cls: 0.635163 loss_rpn_reg: 0.215484 loss_bbox_cls: 0.536656 loss_bbox_reg: 0.742632 loss: 2.144272 eta: 0:06:48 batch_cost: 0.1800 data_cost: 0.0001 ips: 5.5565 images/s
[12/22 17:22:51] ppdet.engine INFO: Epoch: [0] [160/260] learning_rate: 0.000305 loss_rpn_cls: 0.606619 loss_rpn_reg: 0.228886 loss_bbox_cls: 0.533526 loss_bbox_reg: 0.813776 loss: 2.179272 eta: 0:07:01 batch_cost: 0.1798 data_cost: 0.0002 ips: 5.5624 images/s
[12/22 17:22:55] ppdet.engine INFO: Epoch: [0] [180/260] learning_rate: 0.000328 loss_rpn_cls: 0.561313 loss_rpn_reg: 0.223344 loss_bbox_cls: 0.518211 loss_bbox_reg: 0.821883 loss: 2.143983 eta: 0:07:10 batch_cost: 0.1804 data_cost: 0.0001 ips: 5.5439 images/s
[12/22 17:22:59] ppdet.engine INFO: Epoch: [0] [200/260] learning_rate: 0.000350 loss_rpn_cls: 0.489461 loss_rpn_reg: 0.193966 loss_bbox_cls: 0.485476 loss_bbox_reg: 0.845269 loss: 2.011831 eta: 0:07:18 batch_cost: 0.1828 data_cost: 0.0002 ips: 5.4692 images/s
[12/22 17:23:02] ppdet.engine INFO: Epoch: [0] [220/260] learning_rate: 0.000373 loss_rpn_cls: 0.368714 loss_rpn_reg: 0.166986 loss_bbox_cls: 0.440583 loss_bbox_reg: 0.811506 loss: 1.813768 eta: 0:07:26 batch_cost: 0.1910 data_cost: 0.0001 ips: 5.2352 images/s
[12/22 17:23:06] ppdet.engine INFO: Epoch: [0] [240/260] learning_rate: 0.000395 loss_rpn_cls: 0.278925 loss_rpn_reg: 0.162571 loss_bbox_cls: 0.395618 loss_bbox_reg: 0.815755 loss: 1.685229 eta: 0:07:30 batch_cost: 0.1868 data_cost: 0.0002 ips: 5.3538 images/s
[12/22 17:23:10] ppdet.utils.checkpoint INFO: Save checkpoint: output\faster_rcnn_r50_vd_fpn_ssld_1x_rice
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[12/22 17:23:10] ppdet.engine INFO: Eval iter: 0
[12/22 17:23:13] ppdet.metrics.metrics INFO: The bbox result is saved to bbox.json.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[12/22 17:23:13] ppdet.metrics.coco_utils INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.02s)
creating index...
index created!
Traceback (most recent call last):
File "tools/train.py", line 172, in
main()
File "tools/train.py", line 168, in main
run(FLAGS, cfg)
File "tools/train.py", line 132, in run
trainer.train(FLAGS.eval)
File "D:\pkg\PaddleDetection\ppdet\engine\trainer.py", line 564, in train
self._eval_with_loader(self._eval_loader)
File "D:\pkg\PaddleDetection\ppdet\engine\trainer.py", line 613, in _eval_with_loader
metric.accumulate()
File "D:\pkg\PaddleDetection\ppdet\metrics\metrics.py", line 142, in accumulate
classwise=self.classwise)
File "D:\pkg\PaddleDetection\ppdet\metrics\coco_utils.py", line 111, in cocoapi_eval
coco_eval = COCOeval(coco_gt, coco_dt, style)
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\pycocotools-2.0-py3.7-win-amd64.egg\pycocotools\cocoeval.py", line 76, in init
self.params = Params(iouType=iouType) # parameters
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\pycocotools-2.0-py3.7-win-amd64.egg\pycocotools\cocoeval.py", line 527, in init
self.setDetParams()
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\pycocotools-2.0-py3.7-win-amd64.egg\pycocotools\cocoeval.py", line 507, in setDetParams
self.iouThrs = np.linspace(.5, 0.95, np.round((0.95 - .5) / .05) + 1, endpoint=True)
File "<array_function internals>", line 6, in linspace
File "D:\soft\anaconda3\envs\paddle\lib\site-packages\numpy\core\function_base.py", line 120, in linspace
num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

------------------------------------------------------------------------------------------------------------------------------
2。bboxjson文件
-------------------------------------------------------------------------------------------------------------------------------
[{"image_id": 4, "category_id": 1, "bbox": [275.2439880371094, 138.0215301513672, 97.75216674804688, 105.435546875], "score": 0.1600416749715805}, {"image_id": 4, "category_id": 1, "bbox": [395.4527282714844, 403.98883056640625, 97.97509765625, 97.94207763671875], "score": 0.16338315606117249}, {"image_id": 4, "category_id": 1, "bbox": [500.4181213378906, 350.83905029296875, 113.09176635742188, 103.125244140625], "score": 0.5210153460502625}, {"image_id": 4, "category_id": 1, "bbox": [512.1255493164062, 18.448816299438477, 102.44287109375, 102.96307182312012], "score": 0.15462179481983185}, {"image_id": 4, "category_id": 1, "bbox": [1.078302025794983, 372.0433654785156, 92.93096005916595, 96.88739013671875], "score": 0.24322748184204102},
.......,
{"image_id": 287, "category_id": 1, "bbox": [586.73779296875, 534.8777465820312, 53.26220703125, 32.52642822265625], "score": 0.32499566674232483}]

---------------------------------------------------------------------------------------------------------------------------------
3. numpy版本 
---------------------------------------------------------------------------------------------------------------------------------
我有个11.2版本的cuda，paddle2.2.2, 配了1.21.5的numpy, 会报以上错误；我换10.2cuda, 就配不了这个版本的numpy了，都会自动升级1.21.6，并且不可卸载numpy重新安装，因为卸载会连带paddle一起卸载了。1.21.6 评价也是报numpy的错误。

----------------------------------------------------------------------------------------------------------------------------------
4. cudnn版本
----------------------------------------------------------------------------------------------------------------------------------
根据以下提示，我下载了cudnn8.2.1,然后粘贴到对应的文件夹里，重启，新建环境，重新安装paddle, 仍然报这个错误。
WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug.

**Comment by Caozhou1995** [comment]
建议先检查模型组网是否有问题，把operator.index(num)的num变量前后打印一下数据类型，看是否与你预期的一致。另外你重新安装cudnn8.2.1，可能安装方式不对，建议参考官方安装文档：https://docs.nvidia.com/deeplearning/cudnn/install-guide/，以及paddle官方安装文档：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html  进行环境重装。

**Comment by cunjing56** [comment]
> 建议先检查模型组网是否有问题，把operator.index(num)的num变量前后打印一下数据类型，看是否与你预期的一致。另外你重新安装cudnn8.2.1，可能安装方式不对，建议参考官方安装文档：[https://docs.nvidia.com/deeplearning/cudnn/install-guide/，以及paddle官方安装文档：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html](https://docs.nvidia.com/deeplearning/cudnn/install-guide/%EF%BC%8C%E4%BB%A5%E5%8F%8Apaddle%E5%AE%98%E6%96%B9%E5%AE%89%E8%A3%85%E6%96%87%E6%A1%A3%EF%BC%9Ahttps://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html) 进行环境重装。
感谢回复。
第一个模型组网问题不太明白，我都是跑的aistudio上的案例搬到本地，数据模型都没有修改，只要评估就报错numpy。
您说的operator这个在哪里能打印呢？
第二个安装cudnn, 官方的cudnn8.2.1是给cuda11.3配的，飞桨给配的cuda11.2, cudnn8.2.1就挺奇怪的。安装方式，我看了下window的安装方式，感觉有点古早，因为没有cudnn的文件夹，都是在cuda的文件夹里对应粘贴上文件。我反复检查了，系统里cuda文件夹里的cudnn的文件都是8.2.1的（参考文件日期）

**Comment by cunjing56** [comment]
> 感谢回复。
> 第一个模型组网问题不太明白，我都是跑的aistudio上的案例搬到本地，数据模型都没有修改，只要评估就报错numpy。
> 您说的operator这个在哪里能打印呢？
> 第二个安装cudnn, 官方的cudnn8.2.1是给cuda11.3配的，飞桨给配的cuda11.2, cudnn8.2.1就挺奇怪的。安装方式，我看了下window的安装方式，感觉有点古早，因为没有cudnn的文件夹，都是在cuda的文件夹里对应粘贴上文件。我反复检查了，系统里cuda文件夹里的cudnn的文件都是8.2.1的（参考文件日期）

感谢回复。
第一个模型组网问题不太明白，我都是跑的aistudio上的案例搬到本地，数据模型都没有修改，只要评估就报错numpy。
您说的operator这个在哪里能打印呢？
第二个安装cudnn, 官方的cudnn8.2.1是给cuda11.3配的，飞桨给配的cuda11.2, cudnn8.2.1就挺奇怪的。安装方式，我看了下window的安装方式，感觉有点古早，因为没有cudnn的文件夹，都是在cuda的文件夹里对应粘贴上文件。我反复检查了，系统里cuda文件夹里的cudnn的文件都是8.2.1的（参考文件日期）

**Comment by cunjing56** [comment]
> 建议先检查模型组网是否有问题，把operator.index(num)的num变量前后打印一下数据类型，看是否与你预期的一致。另外你重新安装cudnn8.2.1，可能安装方式不对，建议参考官方安装文档：[https://docs.nvidia.com/deeplearning/cudnn/install-guide/，以及paddle官方安装文档：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html](https://docs.nvidia.com/deeplearning/cudnn/install-guide/%EF%BC%8C%E4%BB%A5%E5%8F%8Apaddle%E5%AE%98%E6%96%B9%E5%AE%89%E8%A3%85%E6%96%87%E6%A1%A3%EF%BC%9Ahttps://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html) 进行环境重装。

感谢回复。
第一个模型组网问题不太明白，我都是跑的aistudio上的案例搬到本地，数据模型都没有修改，只要评估就报错numpy。
您说的operator这个在哪里能打印呢？
第二个安装cudnn, 官方的cudnn8.2.1是给cuda11.3配的，飞桨给配的cuda11.2, cudnn8.2.1就挺奇怪的。安装方式，我看了下window的安装方式，感觉有点古早，因为没有cudnn的文件夹，都是在cuda的文件夹里对应粘贴上文件。我反复检查了，系统里cuda文件夹里的cudnn的文件都是8.2.1的（参考文件日期）

**Comment by cunjing56** [comment]
> 建议先检查模型组网是否有问题，把operator.index(num)的num变量前后打印一下数据类型，看是否与你预期的一致。另外你重新安装cudnn8.2.1，可能安装方式不对，建议参考官方安装文档：[https://docs.nvidia.com/deeplearning/cudnn/install-guide/，以及paddle官方安装文档：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html](https://docs.nvidia.com/deeplearning/cudnn/install-guide/%EF%BC%8C%E4%BB%A5%E5%8F%8Apaddle%E5%AE%98%E6%96%B9%E5%AE%89%E8%A3%85%E6%96%87%E6%A1%A3%EF%BC%9Ahttps://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html) 进行环境重装。

您好，我打印了num,
    print('before:',type(num),num)
    num = operator.index(num)
    print('after:',type(num),num)
 都是int,请问这说明什么问题呢？
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 11
after: <class 'int'> 11
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 11
after: <class 'int'> 11
before: <class 'int'> 11
after: <class 'int'> 11
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 11
after: <class 'int'> 11
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 11
after: <class 'int'> 11
before: <class 'int'> 11
after: <class 'int'> 11
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 11
after: <class 'int'> 11
before: <class 'int'> 11
after: <class 'int'> 11
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 11
after: <class 'int'> 11
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 9
after: <class 'int'> 9
before: <class 'int'> 3
after: <class 'int'> 3
before: <class 'int'> 3
after: <class 'int'> 3
before: <class 'int'> 5
after: <class 'int'> 5

**Comment by cunjing56** [comment]
> 建议先检查模型组网是否有问题，把operator.index(num)的num变量前后打印一下数据类型，看是否与你预期的一致。另外你重新安装cudnn8.2.1，可能安装方式不对，建议参考官方安装文档：[https://docs.nvidia.com/deeplearning/cudnn/install-guide/，以及paddle官方安装文档：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html](https://docs.nvidia.com/deeplearning/cudnn/install-guide/%EF%BC%8C%E4%BB%A5%E5%8F%8Apaddle%E5%AE%98%E6%96%B9%E5%AE%89%E8%A3%85%E6%96%87%E6%A1%A3%EF%BC%9Ahttps://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html) 进行环境重装。

hi~能看到吗？

**Comment by cunjing56** [comment]
问题已经解决，是pycocotools版本的问题，安装pycocotoolswindows就可以了。
