### ISSUE TITLE
paddle.incubate.optimizer.functional.minimize_lbfgs 报错问题

### ISSUE THREAD

**Issue by cloud2009** [PaddlePaddle/Paddle#49296]
### 请提出你的问题 Please ask your question

希望用lbfgs对网络参数进行优化 

代码
      w_all = self.net.parameters()
      w = w_all[1][0]
      print('before lbfgs:',w)
      w_update = paddle.incubate.optimizer.functional.minimize_lbfgs(self.loss_e, w)[2]
      print('after lbfgs:',w_update)

显示
before lbfgs: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [-0.13723874])
Traceback (most recent call last):
  File "/home/aistudio/work/PaddleScience_CubeDomain/refactor_PaddleScience_0430/Module/CFD/pinn_solver.py", line 270, in fwd_computing_loss_2d
    w_update = paddle.incubate.optimizer.functional.minimize_lbfgs(self.loss_e, w)[2]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/incubate/optimizer/functional/lbfgs.py", line 118, in minimize_lbfgs
    value, g1 = _value_and_gradient(objective_func, xk)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/incubate/optimizer/functional/utils.py", line 91, in _value_and_gradient
    value = f(x)
TypeError: 'Tensor' object is not callable

self.loss_e如果用Adam的优化器，是没有问题的，不知道为什么lbfgs无法正确使用。

**Comment by cxxly** [comment]
lbfgs目前处于实验特性，和Adam用法不太一样，参考示例代码中用法及注意事项https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/incubate/optimizer/functional/minimize_lbfgs_cn.html

**Comment by cloud2009** [comment]
> lbfgs目前处于实验特性，和Adam用法不太一样，参考示例代码中用法及注意事项https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/incubate/optimizer/functional/minimize_lbfgs_cn.html

我按照这个API说明链接来写代码了，首先从网络了提取了一个weight，是一维tensor，然后用带有动态图的loss对这个提取的tensor进行了lbfgs优化。我也不知道为啥不行，是要等lbfgs后续完善了才能用吗？

**Comment by cloud2009** [comment]
我补充一个信息，我试了用 loss对提取出来的weight进行了autograd运算，也是报错，
代码：
print('autograd:',paddle.grad(self.loss_e, w, retain_graph=True, create_graph=True)[0])

错误如下：

Traceback (most recent call last):
  File "examples/cylinder/2d_unsteady_cylinder_train.py", line 84, in <module>
    train(net_params=net_params)
  File "examples/cylinder/2d_unsteady_cylinder_train.py", line 73, in train
    PINN.train(num_epoch=4, optimizer=opt, scheduler=scheduler,checkpoint_freq=1000, checkpoint_path='/home/aistudio/')
  File "/home/aistudio/work/PaddleScience_CubeDomain/refactor_PaddleScience_0430/Module/CFD/pinn_solver.py", line 406, in train
    return self.solve_Opt(self.fwd_computing_loss_2d, num_epoch, scheduler, batch_size, checkpoint_freq, checkpoint_path=checkpoint_path)
  File "/home/aistudio/work/PaddleScience_CubeDomain/refactor_PaddleScience_0430/Module/CFD/pinn_solver.py", line 421, in solve_Opt
    loss, losses = loss_func()
  File "/home/aistudio/work/PaddleScience_CubeDomain/refactor_PaddleScience_0430/Module/CFD/pinn_solver.py", line 270, in fwd_computing_loss_2d
    print('autograd:',paddle.grad(self.loss_e, w,retain_graph=True, create_graph=True)[0])
  File "<decorator-gen-49>", line 2, in grad
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 663, in grad
    retain_graph, allow_unused, only_inputs)
ValueError: (InvalidArgument) The 0-th input does not appear in the backward graph. Please check the input variable or set allow_unused=True to get None result.
  [Hint: Expected allow_unused_ == true, but received allow_unused_:0 != true:1.] (at /paddle/paddle/fluid/imperative/partial_grad_engine.cc:1041)

看起来是这么提取的weight没法用在autograd里，所以bfgs和lbfgs就肯定也不行了。那么需要怎么做才能提取网络的weight和bias参数，让算的loss可以对参数进行自动微分和bfgs/lbfgs呢？

**Comment by cxxly** [comment]
这个报错意思是elf.loss_e和w之间没有梯度关系，一般是前向计算函数出现问题；另外，对于lbfgs，你仔细看下文档，`w_update = paddle.incubate.optimizer.functional.minimize_lbfgs(self.loss_e, w)[2]` 这种用法不对，lbfgs优化器要求第一个参数是func，第二个参数是参数初始位置

**Comment by cloud2009** [comment]
> 

好的 感谢 我再试一试

**Comment by cloud2009** [comment]
已经解决了 谢谢
