### ISSUE TITLE
安装成功，import报错

### ISSUE THREAD

**Issue by rap8** [PaddlePaddle/Paddle#49565]
### bug描述 Describe the Bug

服务器是UOS系统，鲲鹏920处理器，按照paddle官网步骤源码编译，生产whl包，安装成功，但是import paddle验证时报错，依赖包什么的都有安装，试过把libpaddle.so加入系统变量，但还是报一样的错误。请问有什么好方法解决吗？

(wxy3.7) root@yuanfeng-PC:/tmp/yfenty/Paddle/build# python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:22:24) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /root/anaconda3/envs/wxy3.7/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/root/anaconda3/envs/wxy3.7/lib/python3.7/site-packages/paddle/fluid/core.py", line 268, in <module>
    from . import libpaddle
ImportError: /root/anaconda3/envs/wxy3.7/lib/python3.7/site-packages/paddle/fluid/libpaddle.so: ELF load command alignment not page-aligned

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/wxy3.7/lib/python3.7/site-packages/paddle/__init__.py", line 27, in <module>
    from .framework import monkey_patch_variable
  File "/root/anaconda3/envs/wxy3.7/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/root/anaconda3/envs/wxy3.7/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/root/anaconda3/envs/wxy3.7/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/root/anaconda3/envs/wxy3.7/lib/python3.7/site-packages/paddle/fluid/framework.py", line 33, in <module>
    from . import core
  File "/root/anaconda3/envs/wxy3.7/lib/python3.7/site-packages/paddle/fluid/core.py", line 328, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined

**Comment by kuizhiqing** [comment]
你好，请问是按照https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html 这里的说明进行编译安装的吗？

另外请确保目录 ` /root/anaconda3/envs/wxy3.7/lib/python3.7/site-packages/paddle/` 的 paddle 是你编译产生的版本。

**Comment by rap8** [comment]
> 

您好，谢谢你的回复
我是按照您这个地址链接编译安装的。目录确实是编译产生的版本，下面这个图片是具体编译产生的文件
![01646a0de8706f5f4400b194c8b88ae](https://user-images.githubusercontent.com/110172520/210714120-1f7c26cd-1e74-4317-867f-4de225fa707f.png)

**Comment by rap8** [comment]
问题解决了，UOS源码编译必须要开个VPN，开完vpn源码编译成功

**Comment by hitzhu** [comment]
> 问题解决了，UOS源码编译必须要开个VPN，开完vpn源码编译成功
什么意思？不是一开始就编译成功了，是在安装后import的时候报错？

**Comment by rap8** [comment]
> > 问题解决了，UOS源码编译必须要开个VPN，开完vpn源码编译成功
> > 什么意思？不是一开始就编译成功了，是在安装后import的时候报错？

编译成功了，但是import paddle 报错

**Comment by tjubjy** [comment]
> > > 问题解决了，UOS源码编译必须要开个VPN，开完vpn源码编译成功
> > > 什么意思？不是一开始就编译成功了，是在安装后import的时候报错？
> 
> 编译成功了，但是import paddle 报错

请问最后import paddle的报错解决了吗？我也是编译完，import的时候报错：NameError: name 'libpaddle' is not defined @rap8

**Comment by tjubjy** [comment]
我也遇到同样的问题，最后python换成3.7、gcc、g++换成7.5.0可以解决。
