### ISSUE TITLE
x2paddle onnx转torch 失败

### ISSUE THREAD

**Issue by kollobn** [PaddlePaddle/Paddle#49563]
### bug描述 Describe the Bug

使用x2paddle命令将onnx转成torch时出现报错，命令如下：
x2paddle --framework onnx --model onnx/audio_classification_asmr_static.onnx  --save_dir pd/

报错：
NFO:root:paddle.__version__ = 2.3.0
INFO:root:Now translating model from onnx to paddle.
model ir_version: 6, op version: 11
shape inferencing ...
shape inferenced.
/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py:89: DeprecationWarning: `mapping.TENSOR_TYPE_TO_NP_TYPE` is now deprecated and will be removed in the next release or so.To silence this warning, please use `helper.{self._future_function}` instead.
  dtype = np.dtype(TENSOR_TYPE_TO_NP_TYPE[attr.t.data_type])
/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py:390: DeprecationWarning: `mapping.TENSOR_TYPE_TO_NP_TYPE` is now deprecated and will be removed in the next release or so.To silence this warning, please use `helper.{self._future_function}` instead.
  TENSOR_TYPE_TO_NP_TYPE[item.type.tensor_type.elem_type],
Now, onnx2paddle support convert onnx model opset_verison [7, 8, 9, 10, 11, 12, 13, 14, 15], opset_verison of your onnx model is 11.
Total nodes: 70
Nodes converting ...
Converting node 1 ...     /home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py:169: DeprecationWarning: `mapping.TENSOR_TYPE_TO_NP_TYPE` is now deprecated and will be removed in the next release or so.To silence this warning, please use `helper.{self._future_function}` instead.
  return TENSOR_TYPE_TO_NP_TYPE[dtype]
Converting node 2 ...     /home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/decoder/onnx_decoder.py:172: DeprecationWarning: `mapping.TENSOR_TYPE_TO_NP_TYPE` is now deprecated and will be removed in the next release or so.To silence this warning, please use `helper.{self._future_function}` instead.
  return TENSOR_TYPE_TO_NP_TYPE[dtype]
Converting node 64 ...     /home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/opset_legacy.py:1511: DeprecationWarning: `mapping.TENSOR_TYPE_TO_NP_TYPE` is now deprecated and will be removed in the next release or so.To silence this warning, please use `helper.{self._future_function}` instead.
  dtype = TENSOR_TYPE_TO_NP_TYPE[dtype]
Converting node 65 ...     Traceback (most recent call last):
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/opset_legacy.py", line 110, in run_mapping
    res = func(*args, **kwargs)
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/opset_legacy.py", line 732, in Pad
    raise Exception("The padding value is wrong!")
Exception: The padding value is wrong!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zjr/anaconda3/envs/panns/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/convert.py", line 488, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/convert.py", line 296, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 52, in __init__
    func(node)
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/opset_legacy.py", line 113, in run_mapping
    node.name[9:], node.layer_type))
Exception: convert failed node:110, op_type is Pad

**Comment by kollobn** [comment]
直接将pytorch 模型转化成paddle，同样报错。
代码如下：
    pytorch2paddle(module=model,
               save_dir=output_path,
               jit_type="trace",
               input_examples=[waveform])

报错：
/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/torch/tensor.py:590: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
Traceback (most recent call last):
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zjr/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/zjr/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/zjr/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zjr/audioCode/classify/baidu/netdisk/moderation-audio/codes/PytorchVersion/traincodes/pytorch/torch2paddle.py", line 65, in <module>
    ToPaddle(ori_path, out_path)
  File "/home/zjr/audioCode/classify/baidu/netdisk/moderation-audio/codes/PytorchVersion/traincodes/pytorch/torch2paddle.py", line 60, in ToPaddle
    input_examples=[waveform])
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/convert.py", line 372, in pytorch2paddle
    mapper = PyTorchOpMapper(model)
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 42, in __init__
    self.paddle_graph, _ = self.traverse(decoder.graph)
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/op_mapper/pytorch2paddle/pytorch_op_mapper.py", line 121, in traverse
    inputs, outputs = func(self, graph, node)
  File "/home/zjr/anaconda3/envs/panns/lib/python3.7/site-packages/x2paddle/op_mapper/pytorch2paddle/aten.py", line 3694, in aten_max
    return current_inputs, current_outputs
UnboundLocalError: local variable 'current_inputs' referenced before assignment
