### ISSUE TITLE
Conda方式安装CUDA11.6验证paddle.utils.run_check() 反馈 ExternalError: CUBLAS error(7).[operator < matmul_v2 > error]

### ISSUE THREAD

**Issue by Luna2199** [PaddlePaddle/Paddle#49602]
### 请提出你的问题 Please ask your question

`nvidia-smi` :
![1672988296456](https://user-images.githubusercontent.com/21285692/210947529-adebd84c-4d09-458a-b654-f8325d209383.png)
===
`nvcc -V` : 
![1672988351364](https://user-images.githubusercontent.com/21285692/210947680-d6df50b2-1e3b-42a8-afdb-8c21efec53ef.png)
===
`/usr/local/cuda` : 
![image](https://user-images.githubusercontent.com/21285692/210948044-cf8ff039-0f6b-4d64-8b8a-4a16042d6549.png)
===
`$HOME/.bashrc` : 
![image](https://user-images.githubusercontent.com/21285692/210948252-3e47e542-871d-47a6-9cc8-8647c8dbc313.png)
===
**通过conda方式安装** ：
```
conda install paddlepaddle-gpu==2.4.1 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
```

`NCCL : 2.12.7-1+cuda11.6`
===============================================================================
安装完成，执行验证 `paddle.utils.run_check()` 报错如下：
```
Running verify PaddlePaddle program ... 
W0106 14:51:05.131494 11817 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.6, Runtime API Version: 11.6
W0106 14:51:05.187563 11817 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 269, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 174, in _run_static_single
    exe.run(train_prog,
  File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1450, in run
    res = self._run_impl(program=program,
  File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1661, in _run_impl
    return new_exe.run(scope, list(feed.keys()), fetch_list,
  File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/executor.py", line 631, in run
    tensors = self._new_exe.run(scope, feed_names,
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 159, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 38, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 1907, in linear
      helper.append_op(
    File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 4017, in append_op
      op = Operator(
    File "/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2858, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUBLAS error(7). 
      [Hint: Please search for the error code(7) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
      [operator < matmul_v2 > error]
```
==================================================================================
**注 : 相同环境，基于pytorch官方CUDA11.6的安装指导，可以通过验证。**

**Comment by Luna2199** [comment]
**通过pip方式安装**：
```
python -m pip install paddlepaddle-gpu==2.4.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```
**可以验证通过**
```
Running verify PaddlePaddle program ... 
W0106 15:28:34.048610 15377 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.6, Runtime API Version: 11.6
W0106 15:28:34.086305 15377 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
/home/rabbit/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/executor.py:1583: UserWarning: Standalone executor is not used for data parallel
  warnings.warn(
W0106 15:28:40.636234 15377 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 4 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

**Comment by sljlp** [comment]
可能是因为conda环境有一些库与适配的版本冲突了，建议使用一个干净的conda试下

**Comment by Luna2199** [comment]
反复删除重建过conda虚拟环境，按照文档安装，始终无法成功。

**Comment by xinj7** [comment]
> 
后来解决了吗？
