### ISSUE TITLE
代码训练中断

### ISSUE THREAD

**Issue by zh-hike** [PaddlePaddle/Paddle#49634]
### 问题描述 Please describe your issue

Traceback (most recent call last):
  File "/root/autodl-tmp/zh/ppsr/tools/train.py", line 25, in <module>
  File "/root/autodl-tmp/zh/ppsr/engine/engine.py", line 90, in train
  File "/root/autodl-tmp/zh/ppsr/engine/trainer/common.py", line 13, in train_epoch_common
  File "/home/zh/.local/lib/python3.10/site-packages/paddle/fluid/reader.py", line 566, in __iter__
  File "/home/zh/.local/lib/python3.10/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 379, in __init__
  File "/home/zh/.local/lib/python3.10/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 413, in _init_workers
  File "/home/zh/miniconda3/lib/python3.10/multiprocessing/process.py", line 121, in start
  File "/home/zh/miniconda3/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
  File "/home/zh/miniconda3/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
  File "/home/zh/miniconda3/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
  File "/home/zh/miniconda3/lib/python3.10/multiprocessing/popen_fork.py", line 65, in _launch
OSError: [Errno 24] Too many open files
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f1f98558f70>
Traceback (most recent call last):
  File "/home/zh/.local/lib/python3.10/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 712, in __del__
    self._try_shutdown_all()
  File "/home/zh/.local/lib/python3.10/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 503, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'

**Comment by wuhuachaocoding** [comment]
您好，从报错信息来看，是数据加载部分有问题，请重点从reader部分排查问题，可尝试使用单线程加载数据看看。 @zh-hike
