### ISSUE TITLE
`infer_onnx_trt.py` raises error in PaddleSeg

### ISSUE THREAD

**Issue by zlin-monarch** [PaddlePaddle/Paddle#49683]
### bug描述 Describe the Bug

I tried to convert model into onnx, it raise "AssertionError: We only support 'value()' in dynamic graph mode, please call 'paddle.disable_static()' . 

Model I used: `configs/pp_liteseg/pp_liteseg_stdc1_cityscapes_1024x512_scale1.0_160k.yml`
```
python3 deploy/python/infer_onnx_trt.py \
    --config configs/pp_liteseg/pp_liteseg_stdc1_cityscapes_1024x512_scale1.0_160k.yml \
    --width 1024 \
    --height 1024 \
    --save_dir models/20220109_1024_1024
```
Error: 
```
Traceback (most recent call last):
  File "deploy/python/infer_onnx_trt.py", line 494, in <module>
    export_load_infer(args)
  File "deploy/python/infer_onnx_trt.py", line 436, in export_load_infer
    model, onnx_model_path, input_spec=[input_spec], opset_version=11)
  File "/usr/local/lib/python3.6/dist-packages/paddle/onnx/export.py", line 105, in export
    **configs
  File "/home/cv/.local/lib/python3.6/site-packages/paddle2onnx/convert.py", line 183, in dygraph2onnx
    output_spec)
  File "/home/cv/.local/lib/python3.6/site-packages/paddle2onnx/graph/paddle_graph.py", line 272, in build_from_dygraph
    layer, input_spec, output_spec)
  File "<decorator-gen-510>", line 2, in get_program
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
    return func(*args, **kwargs)
  File "/home/cv/.local/lib/python3.6/site-packages/paddle2onnx/graph/dygraph_helper.py", line 244, in get_program
    src_tensor = state_var_dict[param_or_buffer.name].value(
  File "<decorator-gen-164>", line 2, in value
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 532, in __impl__
    % func.__name__
AssertionError: We only support 'value()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.
```

Trials:
1. I added this following codes on `infer_onnx_trt.py`. but it does not solve this bug
```
paddle.disable_static()
print('paddle.dynamic_mode: ', paddle.in_dynamic_mode())  # True, Now we are in dynamic mode
```
2. I looked into code of dynamic graph converting into static graph, which the bug comes from. But still don't know how to do it.

![](https://files.slack.com/files-pri/TPHAL3U92-F04J5FPJ2LS/image.png)

### Version Information
Jetpack Xavier NX: 4.6.1
tensorrt: 8.2.1.8
Cuda: 10.2
Cudnn: 8.2.1.32
PaddlePaddle: 2.4.1

### Pip Package
numpy==1.19.5
onnx==1.9.0
onnxruntime==1.10.0
opencv-python==4.7.0.68
paddle-bfloat==0.1.7
paddle2onnx==0.9.2
paddlepaddle-gpu==2.4.1
paddleseg==2.7.0

**Comment by juncaipeng** [comment]
I am trying to solve the problem.
