### ISSUE TITLE
paddle.nn.functional.pad使用动态padding时，在导出jit模型报错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#49786]
### 请提出你的问题 Please ask your question

 - PaddlePaddle 2.4.1

paddle.nn.functional.pad使用动态padding时，在导出jit模型报错，请问如何修改才可以正确导出模型。

代码片段如下：
```python
    def pad4group(self, Q, K, V, P, mask, group_size: int = 3):
        """
        q: (#batch, time1, size) -> (#batch, head, time1, size/head)
        k,v: (#batch, time2, size) -> (#batch, head, time2, size/head)
        p: (#batch, time2, size)
        """
        # Compute Overflows
        overflow_Q = Q.shape[2] % group_size
        overflow_KV = K.shape[2] % group_size

        padding_Q = (group_size - overflow_Q) * int(overflow_Q // (overflow_Q + 0.00000000000000001))
        padding_KV = (group_size - overflow_KV) * int(overflow_KV // (overflow_KV + 0.00000000000000001))

        batch_size, _, seq_len_KV, _ = K.shape

        # Input Padding (B, T, D) -> (B, T + P, D)
        Q = F.pad(Q, (0, 0, 0, padding_Q), mode='constant', value=0.0)
        K = F.pad(K, (0, 0, 0, padding_KV), mode='constant', value=0.0)
        V = F.pad(V, (0, 0, 0, padding_KV), mode='constant', value=0.0)

        if mask is not None and mask.shape[2] > 0:  # time2 > 0:
            mask = mask[:, ::group_size, ::group_size]

        Q = Q.transpose([0, 2, 1, 3]).reshape([batch_size, -1, self.h, self.d_k * group_size]).transpose([0, 2, 1, 3])
        K = K.transpose([0, 2, 1, 3]).reshape([batch_size, -1, self.h, self.d_k * group_size]).transpose([0, 2, 1, 3])
        V = V.transpose([0, 2, 1, 3]).reshape([batch_size, -1, self.h, self.d_k * group_size]).transpose([0, 2, 1, 3])

        # process pos_emb
        P_batch_size = P.shape[0]
        overflow_P = P.shape[1] % group_size
        padding_P = group_size - overflow_P if overflow_P else 0
        P = F.pad(P, (0, 0, 0, padding_P, 0, 0), mode='constant', value=0.0, data_format='NLC')
        P = P.reshape([P_batch_size, -1, self.h, self.d_k * group_size]).transpose([0, 2, 1, 3])

        return Q, K, V, P, mask, padding_Q
```

报错信息如下：
```
   File "E:\PyCharm\PPASR\ppasr\model_utils\efficient_conformer\encoder.py", line 341, in forward_chunk
	for i, layer in enumerate(self.encoders):
    File "E:\PyCharm\PPASR\ppasr\model_utils\efficient_conformer\encoder.py", line 347, in forward_chunk
	xs, _, new_att_cache, new_cnn_cache = layer(
    File "E:\PyCharm\PPASR\ppasr\model_utils\conformer\encoder.py", line 394, in forward
	x_att, new_att_cache = self.self_attn(x, x, x, mask, pos_emb, cache=att_cache)
    File "E:\PyCharm\PPASR\ppasr\model_utils\efficient_conformer\attention.py", line 176, in forward
	q, k, v, p, mask, padding_q = self.pad4group(q, k, v, p, mask, self.group_size)
    File "E:\PyCharm\PPASR\ppasr\model_utils\efficient_conformer\attention.py", line 59, in pad4group
        # Input Padding (B, T, D) -> (B, T + P, D)
        print(Q.shape)
        Q = F.pad(Q, (0, 0, 0, padding_Q), mode='constant', value=0.0)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        K = F.pad(K, (0, 0, 0, padding_KV), mode='constant', value=0.0)
        V = F.pad(V, (0, 0, 0, padding_KV), mode='constant', value=0.0)

    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\nn\functional\common.py", line 1724, in pad
	helper.append_op(
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\layer_helper.py", line 45, in append_op
	return self.main_program.current_block().append_op(*args, **kwargs)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\framework.py", line 4017, in append_op
	op = Operator(
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\framework.py", line 2991, in __init__
	self._update_desc_attr(attr_name, attr_val)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\framework.py", line 3339, in _update_desc_attr
	self._update_desc_plain_attr(name, val)
    File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\paddle\fluid\framework.py", line 3363, in _update_desc_plain_attr
	desc._set_int32s_attr(name, val)

    TypeError: _set_int32s_attr(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.libpaddle.OpDesc, arg0: str, arg1: List[int]) -> None

Invoked with: <paddle.fluid.libpaddle.OpDesc object at 0x0000028BC900D7B0>, 'paddings', [0, 0, 0, var tmp_36 : LOD_TENSOR.shape(1,).dtype(int32).stop_gradient(False), 0, 0]
```

**Comment by ronny1996** [comment]
你好，能给一份完整的复现代码吗？错误提示好像是pad输入参数的类型有问题

**Comment by yeyupiaoling** [comment]
@ronny1996 

```shell
git clone https://github.com/yeyupiaoling/PPASR.git
cd PPASR
```

下载这个解压放到项目根目录
[dataset.zip](https://github.com/PaddlePaddle/Paddle/files/10350642/dataset.zip)

注释掉加载模型的代码：
https://github.com/yeyupiaoling/PPASR/blob/28f8035cdf3ec1154061689c4028665a4acf7639/ppasr/trainer.py#L589-L595

最后执行：
```shell
python export_model.py --configs=configs/efficient_conformer_online_zh.yml
```

**Comment by yeyupiaoling** [comment]
@ronny1996 报错的那个位置，例如padding_Q这值是动态计算得到的。

**Comment by yeyupiaoling** [comment]
@ronny1996 您好，能解答一下吗？

**Comment by yeyupiaoling** [comment]
@ronny1996 初步找到是因为在导出的时候，`Q.shape[2]`是Variable类型的，导致padding_Q也是也是Variable类型，就导出模型失败
这个如果转换呢？

**Comment by yeyupiaoling** [comment]
应该是这样原因：https://github.com/PaddlePaddle/Paddle/issues/49715#issuecomment-1378194474

**Comment by yeyupiaoling** [comment]
这样解决了

```python

    def pad4group(self, Q, K, V, P, mask, group_size: int = 3):
        """
        q: (#batch, time1, size) -> (#batch, head, time1, size/head)
        k,v: (#batch, time2, size) -> (#batch, head, time2, size/head)
        p: (#batch, time2, size)
        """
        # Compute Overflows
        overflow_Q = Q.shape[2] % group_size
        overflow_KV = K.shape[2] % group_size

        padding_Q = (group_size - overflow_Q) * int(overflow_Q // (overflow_Q + 1e-17))
        padding_KV = (group_size - overflow_KV) * int(overflow_KV // (overflow_KV + 1e-17))

        batch_size, _, seq_len_KV, _ = K.shape

        # Input Padding (B, T, D) -> (B, T + P, D)
        padding_Q1 = paddle.to_tensor([0, 0, 0, padding_Q], dtype=paddle.int32)
        padding_KV1 = paddle.to_tensor([0, 0, 0, padding_KV], dtype=paddle.int32)
        Q = F.pad(Q, padding_Q1, mode='constant', value=0.0)
        K = F.pad(K, padding_KV1, mode='constant', value=0.0)
        V = F.pad(V, padding_KV1, mode='constant', value=0.0)

        if mask is not None and mask.shape[2] > 0:  # time2 > 0:
            mask = mask[:, ::group_size, ::group_size]

        Q = Q.transpose([0, 2, 1, 3]).reshape([batch_size, -1, self.h, self.d_k * group_size]).transpose([0, 2, 1, 3])
        K = K.transpose([0, 2, 1, 3]).reshape([batch_size, -1, self.h, self.d_k * group_size]).transpose([0, 2, 1, 3])
        V = V.transpose([0, 2, 1, 3]).reshape([batch_size, -1, self.h, self.d_k * group_size]).transpose([0, 2, 1, 3])

        # process pos_emb
        P_batch_size = P.shape[0]
        overflow_P = P.shape[1] % group_size
        padding_P = group_size - overflow_P if overflow_P else 0
        padding_P1 = paddle.to_tensor([0, padding_P], dtype=paddle.int32)
        P = F.pad(P, padding_P1, mode='constant', value=0.0, data_format='NLC')
        P = P.reshape([P_batch_size, -1, self.h, self.d_k * group_size]).transpose([0, 2, 1, 3])

        return Q, K, V, P, mask, padding_Q
```

**Comment by yeyupiaoling** [comment]
这样做不对。这样做的话，导致那个值已经被固定了，在预测的时候就会出错。

错误如下：
```python
Traceback (most recent call last):
  File "E:\PyCharm\PPASR\infer_path.py", line 24, in <module>
    predictor = PPASRPredictor(configs=args.configs,
  File "E:\PyCharm\PPASR\ppasr\predict.py", line 90, in __init__
    self.predict(audio_data=warmup_audio, is_itn=False)
  File "E:\PyCharm\PPASR\ppasr\predict.py", line 170, in predict
    output_data = self.predictor.predict(input_data, audio_len)[0]
  File "E:\PyCharm\PPASR\ppasr\infer_utils\inference_predictor.py", line 140, in predict
    self.predictor.run()
ValueError: (InvalidArgument) Shape of Input(Paddings) should be equal to [6], but received [4].
  [Hint: Expected paddings.size() == 6, but received paddings.size():4 != 6:6.] (at ..\paddle\phi\infermeta\unary.cc:2215)
  [operator < pad3d > error]
```

**Comment by yeyupiaoling** [comment]
#52392
