### ISSUE TITLE
NameError: name 'libpaddle' is not defined

### ISSUE THREAD

**Issue by yatshunlee** [PaddlePaddle/Paddle#49800]
### 问题描述 Issue Description

I followed the guide `https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/zh/install/compile/arm-compile.html` here. After the installation, when I was trying to import paddle, there is an error message:

```
Error: Can not import paddle core while this file exists: /home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: /home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/libpaddle.so: undefined symbol: shm_unlink

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/core.py", line 333, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined
```

### 版本&环境信息 Version & Environment Information

Paddle version: 2.4
OS: Linux aarch64
using Horizon X3 pi to install
Python: 3.8

### Method tried
According to `https://github.com/PaddlePaddle/Paddle/issues/48681`:
tried `export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/sunrise/miniforge3/envs/paddle_env/lib`

**Comment by ronny1996** [comment]
<img width="694" alt="image" src="https://user-images.githubusercontent.com/25691046/212255716-3a58ccad-2d14-4201-8b60-231769617853.png">

Please use `ldd /home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/libpaddle.so` to confirm the library that cannot be found

**Comment by yatshunlee** [comment]
> <img alt="image" width="694" src="https://user-images.githubusercontent.com/25691046/212255716-3a58ccad-2d14-4201-8b60-231769617853.png">
> 
> Please use `ldd /home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/libpaddle.so` to confirm the library that cannot be found

```
$ ldd /home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
        linux-vdso.so.1 (0x0000007f96a63000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f8e034000)
        libstdc++.so.6 => /home/sunrise/miniforge3/envs/paddle_env/lib/libstdc++.so.6 (0x0000007f8de6d000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f8ddc2000)
        libgcc_s.so.1 => /home/sunrise/miniforge3/envs/paddle_env/lib/libgcc_s.so.1 (0x0000007f8dd91000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f8dc1e000)
        /lib/ld-linux-aarch64.so.1 (0x0000007f96a33000)
```

I can locate the file. But somehow, it has the error mentioned above
```
sunrise@RbbX3Pi:~/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid$ find . -name "libpaddle.so"
./libpaddle.so
```

When I execute `python` in the directory `/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid` and import the libpaddle directly, the error message shows as what you showed.
```
import libpaddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/sunrise/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/libpaddle.so: undefined symbol: shm_unlink
```

**Comment by yatshunlee** [comment]
I followed the approach here:
`https://blog.csdn.net/u012505617/article/details/119248870`
and seems like there are some new error messages...

```
(paddle_env) sunrise@RbbX3Pi:~/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid$ file libpaddle.so
libpaddle.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=312ec15e82b85cb9f575cd16c6b8d98aa170fa1e, not stripped
(paddle_env) sunrise@RbbX3Pi:~/miniforge3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid$ ldd -r libpaddle.so
        linux-vdso.so.1 (0x0000007f9d830000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f94e01000)
        libstdc++.so.6 => /home/sunrise/miniforge3/envs/paddle_env/lib/libstdc++.so.6 (0x0000007f94c3a000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f94b8f000)
        libgcc_s.so.1 => /home/sunrise/miniforge3/envs/paddle_env/lib/libgcc_s.so.1 (0x0000007f94b5e000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f949eb000)
        /lib/ld-linux-aarch64.so.1 (0x0000007f9d800000)
undefined symbol: PyInstanceMethod_Type (./libpaddle.so)
undefined symbol: PyExc_NotImplementedError     (./libpaddle.so)
undefined symbol: PyExc_RuntimeError    (./libpaddle.so)
undefined symbol: PyExc_MemoryError     (./libpaddle.so)
undefined symbol: PyBaseObject_Type     (./libpaddle.so)
undefined symbol: PySlice_Type  (./libpaddle.so)
undefined symbol: PyModule_Type (./libpaddle.so)
undefined symbol: PyExc_TypeError       (./libpaddle.so)
undefined symbol: PyBool_Type   (./libpaddle.so)
undefined symbol: PyCFunction_Type      (./libpaddle.so)
undefined symbol: PyMethod_Type (./libpaddle.so)
undefined symbol: PyExc_ImportError     (./libpaddle.so)
undefined symbol: PyExc_ValueError      (./libpaddle.so)
undefined symbol: _Py_FalseStruct       (./libpaddle.so)
undefined symbol: PyDict_Type   (./libpaddle.so)
undefined symbol: PyExc_BufferError     (./libpaddle.so)
undefined symbol: PyType_Type   (./libpaddle.so)
undefined symbol: PyProperty_Type       (./libpaddle.so)
undefined symbol: PySet_Type    (./libpaddle.so)
undefined symbol: _Py_NoneStruct        (./libpaddle.so)
undefined symbol: _Py_NotImplementedStruct      (./libpaddle.so)
undefined symbol: PyExc_SystemError     (./libpaddle.so)
undefined symbol: PyCapsule_Type        (./libpaddle.so)
undefined symbol: PyExc_Exception       (./libpaddle.so)
undefined symbol: _Py_TrueStruct        (./libpaddle.so)
undefined symbol: PyFloat_Type  (./libpaddle.so)
undefined symbol: PyExc_IndexError      (./libpaddle.so)
undefined symbol: PyExc_StopIteration   (./libpaddle.so)
undefined symbol: _Py_EllipsisObject    (./libpaddle.so)
undefined symbol: PyExc_OSError (./libpaddle.so)
undefined symbol: PyStaticMethod_Type   (./libpaddle.so)
undefined symbol: PyDict_DelItemString  (./libpaddle.so)
undefined symbol: _Py_Dealloc   (./libpaddle.so)
undefined symbol: PyLong_FromLong       (./libpaddle.so)
undefined symbol: PyModule_Create2      (./libpaddle.so)
undefined symbol: PyLong_FromSsize_t    (./libpaddle.so)
undefined symbol: PyObject_SetAttrString        (./libpaddle.so)
undefined symbol: PyType_IsSubtype      (./libpaddle.so)
undefined symbol: PyModule_AddFunctions (./libpaddle.so)
undefined symbol: PyErr_Fetch   (./libpaddle.so)
undefined symbol: PyException_SetTraceback      (./libpaddle.so)
undefined symbol: PyDict_Copy   (./libpaddle.so)
undefined symbol: _PyThreadState_UncheckedGet   (./libpaddle.so)
undefined symbol: PyEval_RestoreThread  (./libpaddle.so)
undefined symbol: PyDict_Size   (./libpaddle.so)
undefined symbol: PyStaticMethod_New    (./libpaddle.so)
undefined symbol: PyUnicode_DecodeUTF8  (./libpaddle.so)
undefined symbol: PyUnicode_FromString  (./libpaddle.so)
undefined symbol: PyBytes_FromString    (./libpaddle.so)
undefined symbol: shm_unlink    (./libpaddle.so)
undefined symbol: PyNumber_Check        (./libpaddle.so)
undefined symbol: PyThread_tss_create   (./libpaddle.so)
undefined symbol: PyObject_HasAttrString        (./libpaddle.so)
undefined symbol: PyObject_GetBuffer    (./libpaddle.so)
undefined symbol: PyTuple_Pack  (./libpaddle.so)
undefined symbol: PyBytes_AsString      (./libpaddle.so)
undefined symbol: PyCapsule_GetContext  (./libpaddle.so)
undefined symbol: PyList_SetItem        (./libpaddle.so)
undefined symbol: _PyType_Lookup        (./libpaddle.so)
undefined symbol: PyThreadState_Clear   (./libpaddle.so)
undefined symbol: PyErr_Clear   (./libpaddle.so)
undefined symbol: PyArg_ParseTupleAndKeywords   (./libpaddle.so)
undefined symbol: PyCallable_Check      (./libpaddle.so)
undefined symbol: PyNumber_Xor  (./libpaddle.so)
undefined symbol: PyCapsule_New (./libpaddle.so)
undefined symbol: PyMem_Calloc  (./libpaddle.so)
undefined symbol: PyErr_ExceptionMatches        (./libpaddle.so)
undefined symbol: PyBuffer_Release      (./libpaddle.so)
undefined symbol: PyBytes_Size  (./libpaddle.so)
undefined symbol: PyNumber_Or   (./libpaddle.so)
undefined symbol: PySequence_Size       (./libpaddle.so)
undefined symbol: PyLong_AsUnsignedLong (./libpaddle.so)
undefined symbol: PyEval_InitThreads    (./libpaddle.so)
undefined symbol: PyNumber_Long (./libpaddle.so)
undefined symbol: PyType_Ready  (./libpaddle.so)
undefined symbol: PyFloat_FromDouble    (./libpaddle.so)
undefined symbol: PySet_New     (./libpaddle.so)
undefined symbol: PyTuple_GetItem       (./libpaddle.so)
undefined symbol: PyList_AsTuple        (./libpaddle.so)
undefined symbol: shm_open      (./libpaddle.so)
undefined symbol: _PyObject_GetDictPtr  (./libpaddle.so)
undefined symbol: PyObject_Size (./libpaddle.so)
undefined symbol: PyObject_Malloc       (./libpaddle.so)
undefined symbol: PyLong_AsLongLong     (./libpaddle.so)
undefined symbol: PyTuple_SetItem       (./libpaddle.so)
undefined symbol: PyThread_tss_get      (./libpaddle.so)
undefined symbol: PyErr_Restore (./libpaddle.so)
undefined symbol: PyCapsule_SetName     (./libpaddle.so)
undefined symbol: PyObject_Call (./libpaddle.so)
undefined symbol: PyThread_tss_alloc    (./libpaddle.so)
undefined symbol: PySequence_List       (./libpaddle.so)
undefined symbol: PyLong_FromSize_t     (./libpaddle.so)
undefined symbol: PyList_Size   (./libpaddle.so)
undefined symbol: PyObject_GetIter      (./libpaddle.so)
undefined symbol: PyGILState_GetThisThreadState (./libpaddle.so)
undefined symbol: PyDict_GetItem        (./libpaddle.so)
undefined symbol: PyBytes_AsStringAndSize       (./libpaddle.so)
undefined symbol: PyUnicode_AsEncodedString     (./libpaddle.so)
undefined symbol: PyTuple_New   (./libpaddle.so)
undefined symbol: PyImport_AddModule    (./libpaddle.so)
undefined symbol: PyObject_CallFunctionObjArgs  (./libpaddle.so)
undefined symbol: PySlice_Unpack        (./libpaddle.so)
undefined symbol: PyErr_Occurred        (./libpaddle.so)
undefined symbol: PyThreadState_DeleteCurrent   (./libpaddle.so)
undefined symbol: PySequence_Tuple      (./libpaddle.so)
undefined symbol: PyWeakref_NewRef      (./libpaddle.so)
undefined symbol: PyUnicode_AsUTF8String        (./libpaddle.so)
undefined symbol: PyEval_GetBuiltins    (./libpaddle.so)
undefined symbol: PyBytes_FromStringAndSize     (./libpaddle.so)
undefined symbol: PyDict_SetItem        (./libpaddle.so)
undefined symbol: PyUnicode_FromFormat  (./libpaddle.so)
undefined symbol: PyNumber_And  (./libpaddle.so)
undefined symbol: PyCapsule_GetName     (./libpaddle.so)
undefined symbol: PyImport_ImportModule (./libpaddle.so)
undefined symbol: dlclose       (./libpaddle.so)
undefined symbol: PySlice_AdjustIndices (./libpaddle.so)
undefined symbol: PyGILState_Ensure     (./libpaddle.so)
undefined symbol: PyEval_AcquireThread  (./libpaddle.so)
undefined symbol: PyErr_SetString       (./libpaddle.so)
undefined symbol: PyObject_CallObject   (./libpaddle.so)
undefined symbol: PyThread_tss_set      (./libpaddle.so)
undefined symbol: PyUnicode_FromWideChar        (./libpaddle.so)
undefined symbol: dlsym (./libpaddle.so)
undefined symbol: PyList_GetItem        (./libpaddle.so)
undefined symbol: PyObject_IsInstance   (./libpaddle.so)
undefined symbol: PyList_Append (./libpaddle.so)
undefined symbol: PyMem_Free    (./libpaddle.so)
undefined symbol: PyThreadState_Get     (./libpaddle.so)
undefined symbol: PyNumber_Invert       (./libpaddle.so)
undefined symbol: PyUnicode_FromStringAndSize   (./libpaddle.so)
undefined symbol: PyLong_FromDouble     (./libpaddle.so)
undefined symbol: PyThreadState_New     (./libpaddle.so)
undefined symbol: PyLong_AsSize_t       (./libpaddle.so)
undefined symbol: PyObject_Repr (./libpaddle.so)
undefined symbol: PyFrame_GetLineNumber (./libpaddle.so)
undefined symbol: PyErr_NormalizeException      (./libpaddle.so)
undefined symbol: PyDict_Values (./libpaddle.so)
undefined symbol: PyObject_ClearWeakRefs        (./libpaddle.so)
undefined symbol: PyDict_Next   (./libpaddle.so)
undefined symbol: PyCapsule_GetPointer  (./libpaddle.so)
undefined symbol: PyInstanceMethod_New  (./libpaddle.so)
undefined symbol: dlopen        (./libpaddle.so)
undefined symbol: PyDict_New    (./libpaddle.so)
undefined symbol: PyObject_RichCompareBool      (./libpaddle.so)
undefined symbol: PyGILState_Release    (./libpaddle.so)
undefined symbol: PyErr_NewException    (./libpaddle.so)
undefined symbol: PySet_Add     (./libpaddle.so)
undefined symbol: PyModule_AddObject    (./libpaddle.so)
undefined symbol: PySequence_GetItem    (./libpaddle.so)
undefined symbol: PyObject_GetItem      (./libpaddle.so)
undefined symbol: PyFrame_FastToLocals  (./libpaddle.so)
undefined symbol: PyObject_SetItem      (./libpaddle.so)
undefined symbol: PyDict_Contains       (./libpaddle.so)
undefined symbol: PyDict_GetItemString  (./libpaddle.so)
undefined symbol: PyNumber_Float        (./libpaddle.so)
undefined symbol: PyLong_AsLong (./libpaddle.so)
undefined symbol: dlerror       (./libpaddle.so)
undefined symbol: PyFloat_AsDouble      (./libpaddle.so)
undefined symbol: PyLong_FromLongLong   (./libpaddle.so)
undefined symbol: PyIter_Next   (./libpaddle.so)
undefined symbol: PyEval_SaveThread     (./libpaddle.so)
undefined symbol: PyCapsule_SetContext  (./libpaddle.so)
undefined symbol: Py_GetVersion (./libpaddle.so)
undefined symbol: PySequence_Check      (./libpaddle.so)
undefined symbol: PyUnicode_DecodeUTF32 (./libpaddle.so)
undefined symbol: PyCapsule_Import      (./libpaddle.so)
undefined symbol: PyObject_GetAttrString        (./libpaddle.so)
undefined symbol: PyList_New    (./libpaddle.so)
undefined symbol: PyModule_GetName      (./libpaddle.so)
undefined symbol: PyObject_Str  (./libpaddle.so)
undefined symbol: PyErr_Format  (./libpaddle.so)
undefined symbol: PyObject_SetAttr      (./libpaddle.so)
undefined symbol: PyCFunction_NewEx     (./libpaddle.so)
undefined symbol: PyLong_FromUnsignedLong       (./libpaddle.so)
undefined symbol: PyUnicode_AsUTF8AndSize       (./libpaddle.so)
undefined symbol: PyTuple_Size  (./libpaddle.so)
undefined symbol: dladdr        (./libpaddle.so)
```

**Comment by caifafa** [comment]
After the installation, when I was trying to import paddleocr , i have the same error

  File "C:\Users\youkh\Desktop\tools_all\pages\process_page.py", line 24, in <module>
    from paddleocr import PaddleOCR
  File "C:\Users\youkh\.conda\envs\pig\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "C:\Users\youkh\.conda\envs\pig\lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
  File "C:\Users\youkh\AppData\Roaming\Python\Python37\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "C:\Users\youkh\AppData\Roaming\Python\Python37\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "C:\Users\youkh\AppData\Roaming\Python\Python37\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "C:\Users\youkh\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "C:\Users\youkh\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\framework.py", line 37, in <module>
    from . import core
  File "C:\Users\youkh\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\core.py", line 300, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined

Paddle version: 2.4
os: arm-win11

**Comment by ronny1996** [comment]
Please install paddlepaddle from source code, or compile with docker. @yatshunlee

**Comment by sankalpie** [comment]
### SOMEBODY please give a direct and cut-to-cut answer on how to solve this problem. 

If anyone is still wondering,  I am following this tutorial
[https://www.youtube.com/watch?v=0OA9RdW2saE](https://www.youtube.com/watch?v=0OA9RdW2saE)
and I get this error

Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-8-bf945e5b2106>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from paddleocr import PaddleOCR,draw_ocr
      2 
      3 ocr=PaddleOCR(use_angle_cls=True,lan="en")

8 frames
[/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py](https://localhost:8080/#) in <module>
    267 
    268 try:
--> 269     from . import libpaddle
    270 
    271     if avx_supported() and not libpaddle.is_compiled_with_avx():

ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory


**When I opened the directory that it told me to open Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so ........I could not even find the file that the error is pointing at. **
I thought I would delete the file and it would work fine. But, I CANNOT DELETE ANYTHING IF THERE IS NOTHING TO DELETE.

Then I looked at "/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py" because maybe the error is in this file. And I thought that it was not able to import libpaddle. So I asked chatGPT, how to install libpaddle. chatGPT asked me to install 
"pip install paddlepaddle" 

_Even after doing all this random troubleshooting, looking at stackoverflow articles and GOD KNOWS WHAT NOT. I still cannot find a precise answer. And how on Earth can the answer be different for everybody?? I am using GOOGLE COLAB and the person in the tutorial is using Google Colab. It is not my personal computer that the path for some libraries would be different. Is this not what Colab is for? It provides the same development environment for everyone!!_

### Please just fix the issue and if you can, just post a video documenting and proving that it works. And if PaddlePaddle, the people who created this OCR thing cannot resolve this issue then they should clearly reply on this comment the "We do not know how to solve your issue" .

**Comment by hoangmt** [comment]
frustrated!

**Comment by heavi824** [comment]
frustrated!

**Comment by tjubjy** [comment]
i compiled and installed paddlepaddle from source code, i have the same error

> Please install paddlepaddle from source code, or compile with docker. @yatshunlee

**Comment by tjubjy** [comment]
python换成3.7、gcc、g++换成7.5.0可以解决。

**Comment by yatshunlee** [comment]
At last, I found out that it did not work in my edge device named `horizon x3pi` so I instead used a window pc to host the service.

**Comment by userHarpreet** [comment]
How to resolve this issue? As the issue has been closed, I am still struggling to find the correct resolution.

**Comment by Midoudji-prime** [comment]
> How to resolve this issue? As the issue has been closed, I am still struggling to find the correct resolution.

is there any solution now ? I have been struggling for 2 days now
