### ISSUE TITLE
Conda 安装 Paddle 出现 CUBLAS error(7) 错误，使用 pip 在相同环境相同版本安装 Paddle 能成功

### ISSUE THREAD

**Issue by tong-zeng** [PaddlePaddle/Paddle#49891]
### 问题描述 Issue Description

Conda 安装 Paddle 出现 CUBLAS error(7) 错误，使用 pip 在相同环境相同版本安装 Paddle 能成功

1. 下载、安装 Anaconda3-2022.10-Linux-x86_64 版本
2. 在完全新建的环境，使用 conda 安装 Paddle，命令：
``` conda install paddlepaddle-gpu==2.4.1 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge ```
3. 安装过程没有报错，成功安装后，运行 paddle.utils.run_check( ) 时，返回如下错误：
``` 
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0117 15:52:01.605340  7118 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.6, Runtime API Version            : 11.6
W0117 15:52:01.612543  7118 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/utils/install_check.py", line 269, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/utils/install_check.py", line 174, in _run_static_single
    exe.run(train_prog,
  File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1450, in run
    res = self._run_impl(program=program,
  File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1661, in _run_impl
    return new_exe.run(scope, list(feed.keys()), fetch_list,
  File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/fluid/executor.py", line 631, in run
    tensors = self._new_exe.run(scope, feed_names,
OSError: In user code:

    File "<stdin>", line 1, in <module>

    File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/utils/install_check.py", line 159, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/utils/install_check.py", line 38, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 1907, in linear
      helper.append_op(
    File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/fluid/framework.py", line 4017, in append_op
      op = Operator(
    File "/home/xxx/anaconda3/envs/paddle_m/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2858, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUBLAS error(7).
      [Hint: Please search for the error code(7) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's officia            l solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
      [operator < matmul_v2 > error]
```
4. 新建另外一个 conda 环境，使用 pip 安装 Paddle，` paddle.utils.run_check()` 显示成功 PaddlePaddle is installed successfully!
```python -m pip install paddlepaddle-gpu==2.4.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html```

具体环境信息请见下文。

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.4.1
Paddle With CUDA: True

OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: N/A
Libc version: glibc 2.31
Python version: 3.8.15

CUDA version: 11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
cuDNN version: 8.4.0
Nvidia driver version: 470.57.02
Nvidia driver List:
GPU 0: NVIDIA A100-SXM-80GB
GPU 1: NVIDIA A100-SXM-80GB

****************************************

**Comment by thisjiang** [comment]
可能是因为conda环境有一些库与适配的版本冲突了，后续我们再测试修复下，建议先用pip安装环境

**Comment by dsfcdsfdg** [comment]
我也是这个问题。但是我不能使用pip 安装，显示WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='paddle-wheel.bj.bcebos.com', port=443): Read timed out. (read timeout=15)")': /2.4.1/linux/linux-gpu-cuda11.7-cudnn8.4.1-mkl-gcc8.2-avx/paddlepaddle_gpu-2.4.1.post117-cp38-cp38-linux_x86_64.whl

ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='paddle-wheel.bj.bcebos.com', port=443): Max retries exceeded with url: /2.4.1/linux/linux-gpu-cuda11.7-cudnn8.4.1-mkl-gcc8.2-avx/paddlepaddle_gpu-2.4.1.post117-cp38-cp38-linux_x86_64.whl (Caused by ReadTimeoutError("HTTPSConnectionPool(host='paddle-wheel.bj.bcebos.com', port=443): Read timed out. (read timeout=15)"))

**Comment by thisjiang** [comment]
> 我也是这个问题。但是我不能使用pip 安装，显示WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='paddle-wheel.bj.bcebos.com', port=443): Read timed out. (read timeout=15)")': /2.4.1/linux/linux-gpu-cuda11.7-cudnn8.4.1-mkl-gcc8.2-avx/paddlepaddle_gpu-2.4.1.post117-cp38-cp38-linux_x86_64.whl
> 
> ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='paddle-wheel.bj.bcebos.com', port=443): Max retries exceeded with url: /2.4.1/linux/linux-gpu-cuda11.7-cudnn8.4.1-mkl-gcc8.2-avx/paddlepaddle_gpu-2.4.1.post117-cp38-cp38-linux_x86_64.whl (Caused by ReadTimeoutError("HTTPSConnectionPool(host='paddle-wheel.bj.bcebos.com', port=443): Read timed out. (read timeout=15)"))

这是网络问题吧？试试把代理关了？

**Comment by dsfcdsfdg** [comment]
> 



> 

学校服务器，我只有使用权限，没有关代理的权限。系统管理员说学校的服务器都是ip v6。我之前下载模型也有问题，只能用ip V4下载。安装只能用 conda安装

**Comment by thisjiang** [comment]
请问2.3.0版本paddle conda安装会有问题么？

**Comment by VANDJACKY** [comment]
我也遇到了CUBLAS error(7) 相同的错误，环境如下：

------------------------------------------------------------------------------------------
飞桨版本 2.4.0
安装参考页面
https://www.paddlepaddle.org.cn/documentation/docs/zh/release_note_cn.html
```
驱动版本 : NVIDIA-Linux-x86_64-510.60.02.run (dis @ 2022-03-22)
https://www.nvidia.cn/download/driverResults.aspx/187168/cn/

```
```
Toolkit版本 : cuda_11.6.2_510.47.03_linux.run (dis @ dis-2022-03)
https://developer.download.nvidia.com/compute/cuda/11.6.2/local_installers/cuda_11.6.2_510.47.03_linux.run

```
```
cudnn版本 : cudnn-linux-x86_64-8.4.0.27_cuda11.6-archive.tar.xz
https://developer.nvidia.com/compute/cudnn/secure/8.4.0/local_installers/11.6/cudnn-linux-x86_64-8.4.0.27_cuda11.6-archive.tar.xz
```
------------------------------------------------------------------------------------------

**nvidia-smi**
```
(pip_paddle_env) root@asus:/home/tangxi# nvidia-smi
Mon Feb 13 06:50:18 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+

其他内容省略...
```

**nvcc -V**
```
(pip_paddle_env) root@asus:/home/tangxi# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```

**conda -V**
`conda 22.9.0`

**python -V**
`Python 3.9.16`

**python3 -c "import platform;print(platform.architecture()[0]);print(platform.machine())"**
```
64bit
x86_64
```
**CONDA安装指令**
`conda install paddlepaddle-gpu==2.4.1 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`

------------------------------------------------------------------------------------------

**paddle.utils.run_check()错误如下**
------------------------------------------------------------------------------------------
```
Python 3.9.16 (main, Jan 11 2023, 16:05:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0213 06:28:19.034085 11077 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W0213 06:28:19.038161 11077 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/utils/install_check.py", line 174, in _run_static_single
    exe.run(train_prog,
  File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1450, in run
    res = self._run_impl(program=program,
  File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1661, in _run_impl
    return new_exe.run(scope, list(feed.keys()), fetch_list,
  File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/fluid/executor.py", line 631, in run
    tensors = self._new_exe.run(scope, feed_names,
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/utils/install_check.py", line 159, in _run_static_single
      input, out, weight = _simple_network()
    File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/utils/install_check.py", line 38, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/nn/functional/common.py", line 1907, in linear
      helper.append_op(
    File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/fluid/framework.py", line 4017, in append_op
      op = Operator(
    File "/root/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2858, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUBLAS error(7). 
      [Hint: Please search for the error code(7) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
      [operator < matmul_v2 > error]
>>> exit()
```

使用 conda 重新创建环境后使用 PIP 安装重新检查，一切正常
解决过程：
创建一个新环境
`conda create -n pip_paddle_env python=3.9`
**使用PIP安装paddlepaddle**
`python3 -m pip install paddlepaddle-gpu==2.4.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
`
------------------------------------------------------------------------------------------

**Comment by dianxin556** [comment]
me too，但是是pip 安装也是报这个错

**Comment by firekeepers** [comment]
> 

请问解决了吗，我也遇到这个错误，是使用pip在docker内部的base环境直接安装的
