### ISSUE TITLE
Python IndexError

### ISSUE THREAD

**Issue by Ligoml** [PaddlePaddle/Paddle#49923]
## Case1: paddle.linalg.lstsq

Reproduced Case：

```python
import paddle
import numpy as np
array = np.array([], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [0]), dtype='float32')
y = paddle.to_tensor(np.reshape(array, [0, 0]), dtype='float32')
paddle.linalg.lstsq(x, y, driver='gelsy')
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "test_lstsq.py", line 7, in <module>
    paddle.linalg.lstsq(x, y, driver='gelsy')
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/tensor/linalg.py", line 3418, in lstsq
    rcond = 1e-7 * max(x.shape[-2], x.shape[-1])
IndexError: list index out of range
```

**Comment by Ligoml** [comment]
## Case2: paddle.incubate.nn.FusedMultiHeadAttention

Reproduced Case：

```python
import paddle
import numpy as np
layer = paddle.incubate.nn.FusedMultiHeadAttention(embed_dim=1, num_heads=1)
array = np.array([1.9], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [1]), dtype='float32')
layer(x)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "test_FusedMultiHeadAttention.py", line 7, in <module>
    layer(x)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1004, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/incubate/nn/layer/fused_transformer.py", line 419, in forward
    out = incubate_f.fused_multi_head_attention(
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/incubate/nn/functional/fused_transformer.py", line 625, in fused_multi_head_attention
    qkv_weight.shape[3] == x.shape[2]
IndexError: list index out of range
```

**Comment by Ligoml** [comment]
## Case3: paddle.incubate.nn.FusedTransformerEncoderLayer

Reproduced Case：

```python
import paddle
import numpy as np
layer = paddle.incubate.nn.FusedTransformerEncoderLayer(108, 108, 108, 0.0, 'relu')
array = np.array([], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [0]), dtype='int32')
layer(x)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "test_FusedTransformerEncoderLayer.py", line 7, in <module>
    layer(x)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1004, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/incubate/nn/layer/fused_transformer.py", line 868, in forward
    attn_out = self.fused_attn(src, attn_mask=src_mask)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1004, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/incubate/nn/layer/fused_transformer.py", line 419, in forward
    out = incubate_f.fused_multi_head_attention(
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/incubate/nn/functional/fused_transformer.py", line 625, in fused_multi_head_attention
    qkv_weight.shape[3] == x.shape[2]
IndexError: list index out of range
```

**Comment by Ligoml** [comment]
## Case4: paddle.optimizer.lr.PiecewiseDecay

Reproduced Case：

```python
import paddle
schedular = paddle.optimizer.lr.PiecewiseDecay(boundaries=[], values=[])
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "PiecewiseDecay.py", line 4, in <module>
    schedular = paddle.optimizer.lr.PiecewiseDecay(boundaries=[], values=[])
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/optimizer/lr.py", line 392, in __init__
    super().__init__(last_epoch=last_epoch, verbose=verbose)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/optimizer/lr.py", line 106, in __init__
    self.step()
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/optimizer/lr.py", line 129, in step
    self.last_lr = self.get_lr()
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/optimizer/lr.py", line 398, in get_lr
    return self.values[len(self.values) - 1]
IndexError: list index out of range
```

**Comment by Ligoml** [comment]
## Case5: paddle.unstack

Reproduced Case：

```python
import paddle
import numpy as np
array = np.array([], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [0]), dtype='float32')
paddle.unstack(x, axis=1)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "test_unstack.py", line 7, in <module>
    paddle.unstack(x, axis=1)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 507, in unstack
    num = x.shape[axis]
IndexError: list index out of range
```

**Comment by Ligoml** [comment]
## Case6: paddle.moveaxis

Reproduced Case：

```python
import paddle
import numpy as np
array = np.array([], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [0]), dtype='float32')
paddle.moveaxis(x, source=[], destination=[])
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "test_moveaxis.py", line 7, in <module>
    paddle.moveaxis(x, source=[], destination=[])
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 4471, in moveaxis
    if count[0][1] > 1:
IndexError: list index out of range
```

**Comment by Ligoml** [comment]
## Case7: paddle.static.nn.spectral_norm

Reproduced Case：

```python
import paddle
import numpy as np
paddle.enable_static()
x = paddle.static.data(name='weight', shape=[1, 1], dtype='float32')
paddle.static.nn.spectral_norm(x, dim=-5, eps=0.0)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    paddle.static.nn.spectral_norm(x, dim=-5, eps=0.0)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 4276, in spectral_norm
    h = input_shape[dim]
IndexError: tuple index out of range
```

**Comment by Ligoml** [comment]
## Case8: paddle.static.nn.nce

Reproduced Case：

```python
import paddle
import numpy as np
paddle.enable_static()
x = paddle.static.data(name='x', shape=[1], dtype='float32')
label = paddle.static.data(name='label', shape=[1], dtype='int')
paddle.static.nn.nce(x, label, 1)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 8, in <module>
    paddle.static.nn.nce(x, label, 1)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 553, in __impl__
    return func(*args, **kwargs)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/layers/loss.py", line 710, in nce
    dim = input.shape[1]
IndexError: tuple index out of range
```

**Comment by Ligoml** [comment]
## Case9: paddle.static.nn.deform_conv2d

Reproduced Case：

```python
import paddle
import numpy as np
paddle.enable_static()
x = paddle.static.data(name='x', shape=[0], dtype='float32')
offset = paddle.static.data(name='offset', shape=[0], dtype='float32')
mask = paddle.static.data(name='mask', shape=[0, 0, 0], dtype='float32')
paddle.static.nn.deform_conv2d(x, offset, mask, 0, 0, deformable_groups=0)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 9, in <module>
    paddle.static.nn.deform_conv2d(x, offset, mask, 0, 0, deformable_groups=0)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 553, in __impl__
    return func(*args, **kwargs)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/static/nn/common.py", line 578, in deform_conv2d
    return deformable_conv(
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/static/nn/common.py", line 329, in deformable_conv
    num_channels = input.shape[1]
IndexError: tuple index out of range
```

**Comment by Ligoml** [comment]
## Case10: paddle.static.nn.conv2d_transpose

Reproduced Case：

```python
import paddle
import numpy as np
paddle.enable_static()
input = paddle.static.data("input", shape=[0, 0, 0, 0], dtype="float32")
paddle.static.nn.conv2d_transpose(input, 0)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    paddle.static.nn.conv2d_transpose(input, 0)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 4621, in conv2d_transpose
    output_size[0]
IndexError: list index out of range
```

**Comment by Ligoml** [comment]
## Case11: paddle.static.nn.data_norm

Reproduced Case：

```python
import paddle
import numpy as np
paddle.enable_static()
input = paddle.static.data("", shape=[0], dtype="float32")
paddle.static.nn.data_norm(input)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    paddle.static.nn.data_norm(input)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 553, in __impl__
    return func(*args, **kwargs)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 3833, in data_norm
    channel_num = input_shape[1]
IndexError: tuple index out of range
```

**Comment by Ligoml** [comment]
## Case12: paddle.static.nn.bilinear_tensor_product

Reproduced Case：

```python
import paddle
import numpy as np
paddle.enable_static()
x = paddle.static.data("", shape=[0], dtype="float32")
y = paddle.static.data("", shape=[0], dtype="float32")
paddle.static.nn.bilinear_tensor_product(x, y ,1000)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 8, in <module>
    paddle.static.nn.bilinear_tensor_product(x, y ,1000)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 14585, in bilinear_tensor_product
    param_shape = [size, x.shape[1], y.shape[1]]
IndexError: tuple index out of range
```

**Comment by Ligoml** [comment]
## Case13: paddle.static.nn.batch_norm

Reproduced Case：

```python
import paddle
import numpy as np
paddle.enable_static()
input = paddle.static.data("", shape=[0], dtype="float32")
paddle.static.nn.batch_norm(input)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 7, in <module>
    paddle.static.nn.batch_norm(input)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 3144, in batch_norm
    channel_num = input_shape[1]
IndexError: tuple index out of range
```

**Comment by Ligoml** [comment]
## Case14: paddle.nn.functional.glu

Reproduced Case：

```python
import paddle
import numpy as np
paddle.enable_static()
x = paddle.static.data(name='x', shape=[1, 2, 3], dtype='float32')
paddle.nn.functional.glu(x, axis=256)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    paddle.nn.functional.glu(x, axis=256)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/nn/functional/activation.py", line 1687, in glu
    a, b = chunk(x, 2, axis=axis, name=name)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 3133, in chunk
    return split(x, num_or_sections=chunks, axis=axis, name=name)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 2040, in split
    if isinstance(dim, int) and input_shape[dim] > 0:
IndexError: tuple index out of range
```

**Comment by Ligoml** [comment]
## Case15: paddle.nn.functional.upsample

Reproduced Case：

```python
import paddle
import numpy as np
array = np.array([], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [0, 0, 0, 0]), dtype='float32')
size = paddle.to_tensor(np.reshape(array, [4, 0, 0, 0]), dtype='float32')
array = np.array([1, 2, 3, 4], dtype=np.float32)
scale_factor = paddle.to_tensor(np.reshape(array, [4]), dtype='float32')
paddle.nn.functional.upsample(x, size=size, scale_factor=scale_factor, mode='area')
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 8, in <module>
    paddle.nn.functional.upsample(x, size=size, scale_factor=scale_factor, mode='area')
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 893, in upsample
    return interpolate(
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 433, in interpolate
    return paddle.nn.functional.adaptive_avg_pool2d(x, size)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/nn/functional/pooling.py", line 1821, in adaptive_avg_pool2d
    output_size = [
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/nn/functional/pooling.py", line 1822, in <listcomp>
    item.numpy().item(0) if isinstance(item, Variable) else item
```

**Comment by Ligoml** [comment]
## Case16: paddle.nn.functional.max_unpool2d/max_unpool3d

Reproduced Case：

```python
import paddle
import numpy as np
array = np.array([1], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [1]), dtype='float32')
indices = paddle.to_tensor(np.reshape(array, [1]), dtype='float32')
paddle.nn.functional.max_unpool2d(x, indices, 0, stride=0)
import paddle
import numpy as np
array = np.array([1], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [1]), dtype='float32')
indices = paddle.to_tensor(np.reshape(array, [1]), dtype='float32')
paddle.nn.functional.max_unpool3d(x, indices, 0, stride=0)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    paddle.nn.functional.max_unpool2d(x, indices, 0, stride=0)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/nn/functional/pooling.py", line 1083, in max_unpool2d
    output_size = _unpool_output_size(
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/nn/functional/pooling.py", line 824, in _unpool_output_size
    (input_size[-len(kernel_size) + d] - 1) * stride[d]
IndexError: list index out of range
```

**Comment by Ligoml** [comment]
## Case17: paddle.nn.functional.interpolate

Reproduced Case：

```python
import paddle
import numpy as np
array = np.array([1], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [1, 1, 1, 1]), dtype='float32')
scale_factor = paddle.to_tensor(np.reshape(array, [1, 1, 1, 1]), dtype='float32')
array = np.array([1, 2], dtype=np.float32)
size = paddle.to_tensor(np.reshape(array, [1, 2, 1, 1, 1]), dtype='int64')
paddle.nn.functional.interpolate(x, size=size, scale_factor=scale_factor, mode='area', data_format='NCDHW')
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 9, in <module>
    paddle.nn.functional.interpolate(x, size=size, scale_factor=scale_factor, mode='area', data_format='NCDHW')
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 433, in interpolate
    return paddle.nn.functional.adaptive_avg_pool2d(x, size)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/nn/functional/pooling.py", line 1814, in adaptive_avg_pool2d
    if output_size[1] is None:
IndexError: list index out of range
```

**Comment by Ligoml** [comment]
## Case18: paddle.nn.functional.conv3d_transpose

Reproduced Case：

```python
import paddle
import numpy as np
array = np.array([1], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [1, 1, 1, 1, 1]), dtype='float32')
weight = paddle.to_tensor(np.reshape(array, [1]), dtype='float32')
paddle.nn.functional.conv3d_transpose(x, weight, bias=0)
```

Stack Trace Message：

```python
Traceback (most recent call last):
  File "bug.py", line 8, in <module>
    paddle.nn.functional.conv3d_transpose(x, weight, bias=0)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 1749, in conv3d_transpose
    num_filters = weight.shape[1]
IndexError: list index out of range
```

**Comment by Ligoml** [comment]
## Case19: paddle.nn.functional.conv2d_transpose

Reproduced Case：

```python
import paddle
import numpy as np
array = np.array([1], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [1, 1, 1, 1]), dtype='float32')
weight = paddle.to_tensor(np.reshape(array, [1]), dtype='float32')
paddle.nn.functional.conv2d_transpose(x, weight, bias=0)
```

Stack Trace Message：

```python
Traceback (most recent call last):
    paddle.nn.functional.conv2d_transpose(x, weight, bias=0)
  File "/home/work/wangying/paddlepaddle/pdpd_fuzz_protobuf/pdpd-env/clang_pd_fuzz_env/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 1319, in conv2d_transpose
    num_filters = weight.shape[1]
IndexError: list index out of range
```
