### ISSUE TITLE
Broken Debug build type after #49116 - Assertion error

### ISSUE THREAD

**Issue by tsocha** [PaddlePaddle/Paddle#50027]
### 问题描述 Issue Description

During build in `Debug` build type I got an assertion error:
```
[ 96%] Built target jit_layer
[ 96%] Built target kernel_signature_generator
[ 96%] Built target eager_legacy_op_function_generator
[ 96%] Generating libdnnl.so.0
[ 96%] Generating libiomp5.so
[ 96%] copy_if_different <PADDLE_ROOT>/paddle/fluid/pybind/eager_legacy_op_function.cc.tmp to <PADDLE_ROOT>/paddle/fluid/pybind/eager_legacy_op_function.cc
eager_legacy_op_function_generator: <PADDLE_ROOT>/paddle/phi/core/utils/type_registry.h:54: phi::TypeInfo<BaseT> phi::TypeRegistry<BaseT>::RegisterType(const string&) [with BaseT = phi::Ten
sorBase; std::__cxx11::string = std::__cxx11::basic_string<char>]: Assertion `name_to_id_.find(type) == name_to_id_.end()' failed.
Subprocess aborted
make[2]: *** [paddle/fluid/pybind/CMakeFiles/eager_legacy_op_function_generator_cmd.dir/build.make:75: ../paddle/fluid/pybind/eager_legacy_op_function.cc] Error 1
make[1]: *** [CMakeFiles/Makefile2:146226: paddle/fluid/pybind/CMakeFiles/eager_legacy_op_function_generator_cmd.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Built target eager_generator
make: *** [Makefile:136: all] Error 2
```

I performed git bisect and it seems that #49116 is responsible for it.
![obraz](https://user-images.githubusercontent.com/24435886/214591254-9027b683-a9bc-4754-b3fb-646ede5dedca.png)

reproduction steps:
```
cmake .. \
  -DCMAKE_BUILD_TYPE=Debug \
  -DWITH_GPU=OFF \
  -DWITH_AVX=ON \
  -DWITH_MKLDNN=ON \
  -DON_INFER=ON \
  -DWITH_TESTING=OFF \
  -DWITH_INFERENCE_API_TEST=OFF \
  -DWITH_NCCL=OFF \
  -DWITH_LITE=OFF \
  -DWITH_ONNXRUNTIME=OFF \
  -DWITH_XBYAK=OFF \
  -DWITH_RCCL=OFF \
  -DWITH_CRYPTO=OFF \
  -DWITH_PYTHON=ON \
  -DPY_VERSION=3.8 \
&& make -j14 && make -j14 all
```

### 版本&环境信息 Version & Environment Information

```
(.venv) user@host:<PADDLE_ROOT>$ pip install distro
Requirement already satisfied: distro in <HOME>/.venv/lib/python3.8/site-packages (1.6.0)
(.venv) user@host:<PADDLE_ROOT>$ wget https://raw.githubusercontent.com/PaddlePaddle/Paddle/develop/tools/summary_env.py
--2023-01-25 15:43:50--  https://raw.githubusercontent.com/PaddlePaddle/Paddle/develop/tools/summary_env.py
Resolving <PROXY>
Connecting to <PROXY>... connected.
Proxy request sent, awaiting response... 200 OK
Length: 5828 (5.7K) [text/plain]
Saving to: ‘summary_env.py’

summary_env.py                                      100%[=================================================================================================================>]   5.69K  --.-KB/s    in 0s

2023-01-25 15:43:50 (28.3 MB/s) - ‘summary_env.py’ saved [5828/5828]

(.venv) user@host:<PADDLE_ROOT>$ python3 summary_env.py
Traceback (most recent call last):
  File "summary_env.py", line 214, in <module>
    main()
  File "summary_env.py", line 208, in main
    get_driver_info()
  File "summary_env.py", line 176, in get_driver_info
    driver_ver.split('Driver Version:')[1].strip().split(' ')[0]
IndexError: list index out of range
```

Ubuntu 20.04.2 LTS
g++ (Ubuntu 8.4.0-3ubuntu2) 8.4.0
cmake version 3.22.5

Paddle SHA: f7f1dc03d08df665559cfd1fd4998cb2d64e95d9

**Comment by YuanRisheng** [comment]
I fix this issue in this PR:https://github.com/PaddlePaddle/Paddle/pull/50096

**Comment by tsocha** [comment]
After cherry-pick of #50096 Debug build works again.
Thanks.
