### ISSUE TITLE
hapi_mnist_bf16_static.py - RuntimeError in function ConvOneDNNHandlerT

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#50024]
### bug描述 Describe the Bug

paddle_paddle/build/python/paddle/tests/hapi_mnist_bf16_static.py test application is not working properly. 
Returns an error: 
```
I0116 23:08:01.824071 51418 interpretercore.cc:258] New Executor is Running.
I0116 23:08:01.824502 51418 onednn_context.cc:80] oneDNN v2.6.0
W0116 23:08:01.962066 51418 interpreter_util.cc:886] conv2d raises an exception paddle::PD_Exception, function "ConvOneDNNHandlerT" is not implemented for data type `bfloat16`
  [/repos/paddle_paddle/paddle/phi/kernels/onednn/conv_function.h:140]
download training data and load training data
Training BF16
The loss value printed in the log is the current step, and the metric is the average value of previous steps.
Epoch 1/2
Traceback (most recent call last):
  File "/logs_paddle_paddle/build/python/paddle/tests/hapi_mnist_bf16_static.py", line 138, in <module>
    main(args)
  File "/logs_paddle_paddle/build/python/paddle/tests/hapi_mnist_bf16_static.py", line 119, in main
    model.fit(train_dataset, epochs=2, batch_size=batch_size, verbose=1)
  File "/usr/local/lib/python3.9/dist-packages/paddle/hapi/model.py", line 1927, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/usr/local/lib/python3.9/dist-packages/paddle/hapi/model.py", line 2280, in _run_one_epoch
    outs = getattr(self, mode + '_batch')(*_inputs)
  File "/usr/local/lib/python3.9/dist-packages/paddle/hapi/model.py", line 1195, in train_batch
    loss = self._adapter.train_batch(inputs, labels, update)
  File "/usr/local/lib/python3.9/dist-packages/paddle/hapi/model.py", line 309, in train_batch
    return self._run(inputs, labels)
  File "/usr/local/lib/python3.9/dist-packages/paddle/hapi/model.py", line 537, in _run
    rets = self._executor.run(
  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/executor.py", line 1563, in run
    res = self._run_impl(
  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/executor.py", line 1820, in _run_impl
    return new_exe.run(
  File "/usr/local/lib/python3.9/dist-packages/paddle/fluid/executor.py", line 671, in run
    tensors = self._new_exe.run(
RuntimeError: function "ConvOneDNNHandlerT" is not implemented for data type `bfloat16`
  [/repos/paddle_paddle/paddle/phi/kernels/onednn/conv_function.h:140]
```
### Run command:
```
FLAGS_use_mkldnn=true  python /paddle_paddle/build/python/paddle/tests/hapi_mnist_bf16_static.py --bf16=True
```

### PaddlePaddle branch: 
develop

### CMAKE Flags:
``
-DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_INFERENCE_API_TEST=ON -DWITH_DISTRIBUTE=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DINFERENCE_DEMO_INSTALL_DIR=/data/PaddlePaddle/pp_models -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_COVERAGE=OFF -DPY_VERSION=3.9 -DCMAKE_C_COMPILER=/usr/bin/gcc-8.2 -DCMAKE_CXX_COMPILER=/usr/bin/g++-8.2
``
### Environment
```
            OS: Ubuntu18.04 with mkldnn 
 cmake version: 3.20.0
      Compiler: GCC 8.2
```

**Comment by iclementine** [comment]
Yes. There is some (seemingly unnecessary) restriction on the data type of conv2d 's kernel. But the bfloat16 kernel for conv2d op on ONEDNN backend has never been tested, we are working on verifying if it can work as expected.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/16222986/216284647-9cd00b31-53f3-470e-a574-59183a3bfe7e.png">

Update:

Adding bfloat16 support for the macro `PD_VISIT_FLOAT_AND_INT8_TYPES` makes the error shift to another place. It would then yeild same result as in https://github.com/PaddlePaddle/Paddle/issues/50026.

RuntimeError: could not create a primitive descriptor iterator
