### ISSUE TITLE
Paddle安装成功，但运行检查脚本时出错

### ISSUE THREAD

**Issue by code953** [PaddlePaddle/Paddle#50023]
### 问题描述 Issue Description

Paddle安装成功，但运行检查脚本时出错

> 报错信息
Running verify PaddlePaddle program ...
W0124 21:56:10.481693  1080 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.0, Runtime API Version: 11.6
W0124 21:56:10.499675  1080 gpu_resources.cc:91] device: 0, cuDNN Version: 8.7.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\paddle\utils\install_check.py", line 270, in run_check
    _run_dygraph_single(use_cuda, use_xpu, use_npu)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\paddle\utils\install_check.py", line 136, in _run_dygraph_single
    linear_out = linear(input_tensor)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\paddle\nn\layer\common.py", line 175, in forward
    out = F.linear(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\paddle\nn\functional\common.py", line 1882, in linear
    return _C_ops.linear(x, weight, bias)
OSError: Invalid enum backend type `63`.
  [..\paddle/phi/common/backend.h:140]

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.4.1
Paddle With CUDA: True

OS: Windows 10
GCC version: N/A
Clang version: N/A
CMake version: N/A
Libc version: N/A
Python version: 3.10.8

CUDA version: 11.6.124

Build cuda_11.6.r11.6/compiler.31057947_0
cuDNN version: N/A
Nvidia driver version: 527.41
Nvidia driver List: 
GPU 0: NVIDIA GeForce GTX 1050

****************************************

**Comment by ForFishes** [comment]
您好，我看你文件名字是中文，改成英文试一下，看看能否解决。

**Comment by code953** [comment]
> 你好，我看你文件名是中文，改成英文试一下，看能不能解决。

版本&环境信息已查询成功，能麻烦看下报错信息吗？

**Comment by zhwesky2010** [comment]
@sffffre  你好，这个 `Invalid enum backend type 63.` 在某些机器上会触发，是一个已知bug。我们会定位并修复

**Comment by sffffre** [comment]
那是否影响正常使用呢？

**Comment by code953** [comment]
那是否影响正常使用呢？  @zhouwei25

**Comment by zhwesky2010** [comment]
> 

可以试试paddle.set_device切换为CPU

**Comment by WesternTrail** [comment]
@zhouwei25 定位快2个月了，请问你们修复得怎么样了？？？

**Comment by zhwesky2010** [comment]
@WesternTrail @sffffre 你好，该问题已修复，可以安装最新的develop版本whl包试试
`python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/windows/gpu/develop.html`

**Comment by WesternTrail** [comment]
@zhwesky2010 感谢，有效！
