### ISSUE TITLE
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.   

### ISSUE THREAD

**Issue by lichuantao6626** [PaddlePaddle/Paddle#50189]
### 问题描述 Issue Description

根据官网版本要求，我安装了paddle=2.4.1,paddlenlp=2.5.0,然后根据https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers安装教程安装了ppdiffusers，并测试了提供的示例：
```python
import paddle
from ppdiffusers import StableDiffusionPipeline

# 可选模型权重
# CompVis/stable-diffusion-v1-4
# runwayml/stable-diffusion-v1-5
# stabilityai/stable-diffusion-2-base （原始策略 512x512）
# stabilityai/stable-diffusion-2 （v-objective 768x768）
# Linaqruf/anything-v3.0
# ......
pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2")

# 设置随机种子，我们可以复现下面的结果！
paddle.seed(5232132133)
prompt = "a portrait of shiba inu with a red cap growing on its head. intricate. lifelike. soft light. sony a 7 r iv 5 5 mm. cinematic post - processing "
image = pipe(prompt, guidance_scale=7.5, height=768, width=768).images[0]

image.save("shiba_dog_with_a_red_cap.png")
这个示例也运行程序了，但是我测试https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers/examples/textual_inversion微调的例子，根据官网的示例，我执行1了：
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
# 这里需要输入刚才下载的图片所保存的文件目录
export DATA_DIR="cat_toy_images"

python -u train_textual_inversion.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --train_data_dir=$DATA_DIR \
  --learnable_property="object" \
  --placeholder_token="<cat-toy>" --initializer_token="toy" \
  --height=512 \
  --width=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --max_train_steps=3000 \
  --learning_rate=5.0e-04 \
  --scale_lr \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --seed 42 \
  --output_dir="textual_inversion_cat"
这个命令，然后报了一个错：
Train Steps:   0%|                                                                                   | 0/3000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_textual_inversion.py", line 672, in <module>
    main()
  File "train_textual_inversion.py", line 597, in main
    latents = vae.encode(batch["pixel_values"]).latent_dist.sample()
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/ppdiffusers/models/vae.py", line 572, in encode
    h = self.encoder(x)
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/ppdiffusers/models/vae.py", line 133, in forward
    sample = self.conv_in(sample)
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 712, in forward
    out = F.conv._conv_nd(
  File "/opt/data/anaconda3_0203/envs/paddle_env/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 140, in _conv_nd
    pre_bias = _C_ops.conv2d(
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.
  [Hint: Please search for the error code(8) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/kernels/gpudnn/conv_kernel.cu:376)

Train Steps:   0%|          
```

根据错误提示，没有发现有用的解决问题的方法，请问各位大神这个是哪里的问题。

### 版本&环境信息 Version & Environment Information

硬件信息：
![image](https://user-images.githubusercontent.com/102787771/216531107-44c0274d-ae81-4f8f-b173-92ffdc475d93.png)

centos7.9  x86_64

python环境：Python 3.8.16

**Comment by ZHUI** [comment]
请检查一下 paddle的安装是否有问题。运行：
```python
paddle.utils.install_check()
```

**Comment by lichuantao6626** [comment]
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0203 07:27:38.360721 12964 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 11.7
W0203 07:27:38.373066 12964 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

paddle安装时正常的，运行检查如上，是没有问题的

**Comment by lichuantao6626** [comment]
运行您给的paddle.utils.install_check()命令报错，：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable


![image](https://user-images.githubusercontent.com/102787771/216539185-87768d51-6eed-4411-ad51-fb704d6abda9.png)

**Comment by ZHUI** [comment]
这个 issue 应该也是cudnn路径问题吧

**Comment by Atopis** [comment]
> 运行您给的paddle.utils.install_check（）命令报错，： 回溯（最近一次调用）： 文件“”，第 1 行，在 TypeError 中： 'module' 对象不可调用
> 
> ![图像](https://user-images.githubusercontent.com/102787771/216539185-87768d51-6eed-4411-ad51-fb704d6abda9.png)

请问你解决没有，我和你问题一样，不知道咋弄，cudnn路径咋会有问题呢，不就是放到cuda下面么

**Comment by lichuantao6626** [comment]
暂时还没有解决

**Comment by Atopis** [comment]
> 这个 issue 应该也是cudnn路径问题吧

请问  能详细说说这个cudnn路径问题是什么情况吗，该怎么解决？按官网中的paddle.utils.run_check()，是没有问题的。谢谢

**Comment by heyiconan** [comment]
一样的问题,各种版本装来装去,最后还是这个报错,不知道啥情况,插眼

**Comment by ZACP-DERMATOLOGY** [comment]
我也是这个问题日了

**Comment by adady** [comment]
batch_size 设置小一些试试，有可能显存不够
