### ISSUE TITLE
PaddleSeg模型本地部署推理时报EOFError

### ISSUE THREAD

**Issue by Arthus666** [PaddlePaddle/Paddle#50217]
### bug描述 Describe the Bug

安装的是cpu版本的paddle

推理命令
```python
import os

# 执行推理任务
os.system(
    '''cd D:/Python/MySeg/PaddleSeg/contrib/MedicalSeg/ & \
        python nnunet/infer.py --image_folder D:/Python/MySeg/test_input \
        --output_folder D:/Python/MySeg/test_output \
        --model_paths D:/Python/MySeg/baseline_model/model.pdmodel \
        --param_paths D:/Python/MySeg/baseline_model/model.pdiparams \
        --plan_path D:/Python/MySeg/baseline_params/nnUNetPlansv2.1_plans_3D.pkl \
        --postprocessing_json_path D:/Python/MySeg/baseline_params/postprocessing.json \
        --model_type cascade_lowres''')

```

报错信息
```python
D:\Anaconda\python.exe D:/Python/MySeg/main.py
model type:  cascade_lowres
The plan path:  D:/Python/MySeg/baseline_params/nnUNetPlansv2.1_plans_3D.pkl
The model paths:  ['D:/Python/MySeg/baseline_model/model.pdmodel']
The postprocessing json path:  D:/Python/MySeg/baseline_params/postprocessing.json
Use GPU
E0204 22:41:53.878157  3768 analysis_config.cc:96] Please compile with gpu to EnableGpu()
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [matmul_v2_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]e[0m
e[32m--- Running IR pass [matmul_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [constant_folding_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0204 22:41:54.014245  3768 memory_optimize_pass.cc:219] Cluster name : conv3d_38.tmp_0  size: 160000
I0204 22:41:54.014245  3768 memory_optimize_pass.cc:219] Cluster name : concat_4.tmp_0  size: 524288000
I0204 22:41:54.014245  3768 memory_optimize_pass.cc:219] Cluster name : conv3d_39.tmp_1  size: 640000
I0204 22:41:54.014245  3768 memory_optimize_pass.cc:219] Cluster name : leaky_relu_7.tmp_0  size: 4096000
I0204 22:41:54.014245  3768 memory_optimize_pass.cc:219] Cluster name : x  size: 8192000
I0204 22:41:54.014245  3768 memory_optimize_pass.cc:219] Cluster name : leaky_relu_0.tmp_0  size: 262144000
I0204 22:41:54.014245  3768 memory_optimize_pass.cc:219] Cluster name : leaky_relu_18.tmp_0  size: 65536000
I0204 22:41:54.014245  3768 memory_optimize_pass.cc:219] Cluster name : conv3d_transpose_9.tmp_0  size: 262144000
I0204 22:41:54.014245  3768 memory_optimize_pass.cc:219] Cluster name : leaky_relu_5.tmp_0  size: 16384000
I0204 22:41:54.014245  3768 memory_optimize_pass.cc:219] Cluster name : instance_norm_10.tmp_1  size: 4
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0204 22:41:54.036252  3768 analysis_predictor.cc:1314] ======= optimize end =======
I0204 22:41:54.036252  3768 naive_executor.cc:110] ---  skip [feed], feed -> x
I0204 22:41:54.037251  3768 naive_executor.cc:110] ---  skip [softmax_0.tmp_0], fetch -> fetch
This model expects 1 input modalities for each image.
Found 1 unique case ids, here are some examples:  ['0f593c1e-4bb8-470f-a87b-fee3dbd3b3ed']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 1
number of cases that still need to be predicted: 1
starting preprocessing generator
file list:  [['D:/Python/MySeg/test_input\\0f593c1e-4bb8-470f-a87b-fee3dbd3b3ed_0000.nii.gz']]
preprocess output files:  ['D:/Python/MySeg/test_output\\0f593c1e-4bb8-470f-a87b-fee3dbd3b3ed.nii.gz']
starting prediction...
Traceback (most recent call last):
  File "D:\Python\MySeg\PaddleSeg\contrib\MedicalSeg\nnunet\infer.py", line 288, in <module>
    main(args)
  File "D:\Python\MySeg\PaddleSeg\contrib\MedicalSeg\nnunet\infer.py", line 268, in main
    predict_from_folder(
  File "D:\Python\MySeg\PaddleSeg\contrib\MedicalSeg\nnunet\predict.py", line 260, in predict_from_folder
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    return predict_cases(
  File "D:\Python\MySeg\PaddleSeg\contrib\MedicalSeg\nnunet\utils\predict_utils.py", line 238, in predict_cases
    for preprocessed in preprocessing:
  File "D:\Python\MySeg\PaddleSeg\contrib\MedicalSeg\nnunet\utils\predict_utils.py", line 137, in preprocess_multithreaded
    pr.start()
  File "D:\Anaconda\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Anaconda\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Anaconda\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Anaconda\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Anaconda\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'StaticPredictor.__init__.<locals>.<lambda>'
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Anaconda\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

Process finished with exit code 0

```

**Comment by shiyutang** [comment]
建议使用gpu版本的paddle进行重新验证，基于nnunet的模型推理较为耗时，cpu推理时间可能不可接受。
另外如果有条件建议使用linux进行推理，nnunet的部署暂时没有在windows端进行验证。实验获得任何进一步结果欢迎继续在本条issue下回复。
