### ISSUE TITLE
OSError: (External) CUDA error(98), invalid device function.

### ISSUE THREAD

**Issue by Vimos** [PaddlePaddle/Paddle#50279]
### 请提出你的问题 Please ask your question

```
Python 3.9.13 (main, Aug 25 2022, 23:26:10)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import paddle

In [2]: paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0207 11:11:11.576819 96184 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 5.2, Driver API Version: 11.6, Runtime API Version: 11.3
W0207 11:11:11.582988 96184 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

安装检测通过！但是仍然报下面错误：
```shell
W0207 10:24:28.373817 96079 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 5.2, Driver API Version: 11.6, Runtime API Version: 11.3
W0207 10:24:28.375903 96079 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[2023-02-07 10:24:28,767] [    INFO] - All model checkpoint weights were used when initializing UNIMOLMHeadModel.

[2023-02-07 10:24:28,767] [    INFO] - All the weights of UNIMOLMHeadModel were initialized from the model checkpoint at unimo-text-1.0.
If your task is similar to the task the model of the checkpoint was trained on, you can already use UNIMOLMHeadModel for predictions without further training.
[2023-02-07 10:24:28,767] [    INFO] - Already cached /home/vimos/.paddlenlp/models/unimo-text-1.0/unimo-text-1.0-vocab.txt
[2023-02-07 10:24:28,779] [    INFO] - tokenizer config file saved in /home/vimos/.paddlenlp/models/unimo-text-1.0/tokenizer_config.json
[2023-02-07 10:24:28,779] [    INFO] - Special tokens file saved in /home/vimos/.paddlenlp/models/unimo-text-1.0/special_tokens_map.json

Epoch 1/6
Traceback (most recent call last):
  File "/home/vimos/git/faithful-nlg/run_gen.py", line 244, in <module>
    run(args)
  File "/home/vimos/git/faithful-nlg/run_gen.py", line 158, in run
    optimizer.step()
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/paddle/optimizer/adamw.py", line 578, in step
    optimize_ops = self._apply_optimize(loss=None,
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/paddle/optimizer/optimizer.py", line 1152, in _apply_optimize
    params_grads = self._grad_clip(params_grads)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/paddle/fluid/clip.py", line 193, in __call__
    return self._dygraph_clip(params_grads)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/paddle/fluid/clip.py", line 505, in _dygraph_clip
    sum_square = _squared_l2_norm(merge_grad)
  File "/home/vimos/anaconda3/lib/python3.9/site-packages/paddle/fluid/clip.py", line 76, in _squared_l2_norm
    return _C_ops.squared_l2_norm(x)
OSError: (External) CUDA error(98), invalid device function.
  [Hint: Please search for the error code(98) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/kernels/funcs/squared_l2_norm.h:86)
```

不过，像这种算符问题，难道和GPU有关？
```
    Product Name                          : NVIDIA GeForce GTX TITAN X
    Product Brand                         : GeForce
    Product Architecture                  : Maxwell
```

**Comment by tink2123** [comment]
可能是运行时库和环境不匹配造成。建议使用10系以上N卡进行模型训练，或者转到AI Studio等平台完成训练。

**Comment by Vimos** [comment]
这应该是个bug，同样的配置3090能跑，但是gtx titan跑不了。

**Comment by Vimos** [comment]
在该卡上的更多错误
```shell
W0220 14:28:58.281258 170562 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 5.2, Driver API Version: 11.6, Runtime API Version: 11.6
W0220 14:28:58.284783 170562 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
[1]    170562 IOT instruction (core dumped)  ipython
```

**Comment by Vimos** [comment]
```
cudaErrorInvalidDeviceFunction = 98
The requested device function does not exist or is not compiled for the proper device architecture.
```
编译配置需要兼容一下。
