### ISSUE TITLE
2.4版本的lstm无法在gpu下运行

### ISSUE THREAD

**Issue by Feng1909** [PaddlePaddle/Paddle#50273]
### bug描述 Describe the Bug

代码：
```
class MyLSTMModel(nn.Layer):
    def __init__(self):
        super(MyLSTMModel,self).__init__()
        self.rnn = paddle.nn.LSTM(input_size=4, hidden_size=10)
        self.flatten = paddle.nn.Flatten()
        self.fc=nn.Linear(10,2)

        
    def forward(self,input):
        out, (h, c)=self.rnn(input)
        out =self.flatten(out)
        out=self.fc(out)
        return out
paddle.set_device('gpu:0')  # can only be used on AI Studio
# paddle.set_device('cpu')
model.prepare(optimizer=paddle.optimizer.Adam(learning_rate=0.001, parameters=model.parameters()),
              loss=paddle.nn.MSELoss(reduction='mean'))
model.fit(train_dataset,
          eval_data=test_dataset,
          eval_freq=1,
          epochs=10,
          batch_size=1000,
          save_dir='model',
          log_freq=100,
          save_freq=10,
          shuffle=True, 
          drop_last=True,
          verbose=1)
'''
无法在2.4版本运行，可在2.3版本运行

'''Traceback (most recent call last):
  File "train.py", line 49, in <module>
    verbose=1)
  File "/home/feng1909/Documents/miniconda3/envs/vehicle/lib/python3.7/site-packages/paddle/hapi/model.py", line 1781, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "/home/feng1909/Documents/miniconda3/envs/vehicle/lib/python3.7/site-packages/paddle/hapi/model.py", line 2112, in _run_one_epoch
    outs = getattr(self, mode + '_batch')(*_inputs)
  File "/home/feng1909/Documents/miniconda3/envs/vehicle/lib/python3.7/site-packages/paddle/hapi/model.py", line 1102, in train_batch
    loss = self._adapter.train_batch(inputs, labels, update)
  File "/home/feng1909/Documents/miniconda3/envs/vehicle/lib/python3.7/site-packages/paddle/hapi/model.py", line 725, in train_batch
    outputs = self.model.network(*[to_variable(x) for x in inputs])
  File "/home/feng1909/Documents/miniconda3/envs/vehicle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/feng1909/high_param_opt/ML/model.py", line 15, in forward
    out, (h, c)=self.rnn(input)
  File "/home/feng1909/Documents/miniconda3/envs/vehicle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/feng1909/Documents/miniconda3/envs/vehicle/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1073, in forward
    for _ in range(self.state_components)
  File "/home/feng1909/Documents/miniconda3/envs/vehicle/lib/python3.7/site-packages/paddle/nn/layer/rnn.py", line 1073, in <listcomp>
    for _ in range(self.state_components)
  File "/home/feng1909/Documents/miniconda3/envs/vehicle/lib/python3.7/site-packages/paddle/fluid/layers/tensor.py", line 909, in fill_constant_batch_size_like
    input_dim_idx, output_dim_idx, place)
NotImplementedError: (Unimplemented) Unsupported backend `Undefined` when casting it to paddle place type. (at /paddle/paddle/phi/core/compat/convert_utils.cc:103)'''

### 其他补充信息 Additional Supplementary Information

_No response_

**Comment by joey12300** [comment]
你好，可以发一个全一点的代码吗？直接复制你的代码跑不了

**Comment by ZhangzrJerry** [comment]
看起来我遇到了相同的问题
***
本地环境
paddlepaddle-gpu 2.4.1
cudnn 8.7
cuda 11.7
***
这部分代码可以运行不报错
```py
import paddle
from paddle import nn
import paddle.nn.functional as F

class MyNet(nn.Layer):
    def __init__(self):
        super(MyNet, self).__init__()
        self.lstm1 = nn.LSTM(
            input_size=7,
            hidden_size=10,
            direction='bidirect',
            num_layers=1,
            time_major=False
        )
        self.lstm2 = nn.LSTM(
            input_size=7,
            hidden_size=15,
            direction='bidirect',
            num_layers=10,
            time_major=False
        )
        self.fc1 = nn.Linear(35, 60)
        self.fc2 = nn.Linear(90,20)
        self.fc3 = nn.Linear(35,1)
        pass
    def forward(self, nordata, stddata, input):
        nordata = self.lstm1(nordata)[0][:,-1]
        stddata = self.lstm2(stddata)[0][:,-1]
        scadata = paddle.reshape(input,(1,-1))
        x = paddle.concat((nordata,scadata),axis=1)
        x = self.fc1(x)
        x = F.relu(x)
        x = F.dropout(x)
        x = paddle.concat((x,stddata),axis=1)
        x = self.fc2(x)
        x = F.relu(x)
        x = F.dropout(x)
        x = paddle.concat((x,scadata),axis=1)
        x = self.fc3(x)
        x = F.sigmoid(x)
        return x
    pass
a = paddle.reshape(paddle.to_tensor(MyDataset()[0][0],dtype='float32'),(-1,64,7))
b = paddle.reshape(paddle.to_tensor(MyDataset()[0][1],dtype='float32'),(-1,64,7))
c = paddle.to_tensor(MyDataset()[0][2],dtype='float32')
MyNet()(a,b,c)
```
***
以下代码会报错
```py
# 从定义好的数据集取出数据
paddle.set_device('gpu')
trainloader = paddle.io.DataLoader(MyDataset())
for x in trainloader:
    print(x)
    break
```
x的相关细节
```
[Tensor(shape=[1, 64, 7], dtype=float64, place=Place(gpu_pinned), stop_gradient=True,
       [[[0.96096087, 0.93008475, 0.97952757, 0.95567861, 0.95400008,
          0.44230769, 0.43750000],
         [0.96096087, 0.93008475, 0.97952757, 0.95290873, 0.95400008,
          0.44230769, 0.43750000],
         [0.96096087, 0.93008475, 0.97952757, 0.95567861, 0.95400008,
          0.44230769, 0.43750000],
         [0.96096087, 0.93008475, 0.97952757, 0.95567861, 0.95400008,
          0.44230769, 0.43750000],
         [0.96096087, 0.93220339, 0.97952757, 0.95567861, 0.95400008,
          0.44230769, 0.43750000],
         [0.96096087, 0.93220339, 0.97952757, 0.95567861, 0.95400008,
          0.44230769, 0.43750000],
         [0.96096087, 0.93220339, 0.97952757, 0.95567861, 0.95400008,
          0.44230769, 0.43750000],
         [0.96096087, 0.93220339, 0.97952757, 0.95567861, 0.95599994,
          0.44230769, 0.43750000],
         [0.96096087, 0.93220339, 0.97952757, 0.95844882, 0.95599994,
          0.44230769, 0.43750000],
         [0.96396406, 0.93220339, 0.97952757, 0.95844882, 0.95400008,
          0.44230769, 0.43750000],
         [0.96396406, 0.93220339, 0.97952757, 0.95844882, 0.95599994,
          0.44230769, 0.43750000],
         [0.96396406, 0.93220339, 0.97952757, 0.95844882, 0.95599994,
          0.44230769, 0.43750000],
...
       [[0.96663851, 0.93183923, 0.97952759, 0.96152180, 0.95846874, 0.43719953,
         0.43750000, 0.00356578, 0.00088270, 0.00000000, 0.00418724, 0.00307697,
         0.00849357, 0.        , 0.25074500]]), Tensor(shape=[1], dtype=float32, place=Place(gpu_pinned), stop_gradient=True,
       [0.])]
```
完整错误
```---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[67], line 1
----> 1 MyNet()(x[0],x[1],x[2])

File ~/anaconda3/envs/globalenv/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py:948, in Layer.__call__(self, *inputs, **kwargs)
    945 if (not in_declarative_mode()) and (not self._forward_pre_hooks) \
    946     and (not self._forward_post_hooks) and (not self._built) and in_dygraph_mode() and (not in_profiler_mode()):
    947     self._build_once(*inputs, **kwargs)
--> 948     return self.forward(*inputs, **kwargs)
    949 else:
    950     return self._dygraph_call_func(*inputs, **kwargs)

Cell In[62], line 27, in MyNet.forward(self, nordata, stddata, input)
     26 def forward(self, nordata, stddata, input):
---> 27     nordata = self.lstm1(nordata)[0][:,-1]
     28     stddata = self.lstm2(stddata)[0][:,-1]
     29     scadata = paddle.reshape(input,(1,-1))

File ~/anaconda3/envs/globalenv/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py:948, in Layer.__call__(self, *inputs, **kwargs)
    945 if (not in_declarative_mode()) and (not self._forward_pre_hooks) \
    946     and (not self._forward_post_hooks) and (not self._built) and in_dygraph_mode() and (not in_profiler_mode()):
    947     self._build_once(*inputs, **kwargs)
--> 948     return self.forward(*inputs, **kwargs)
    949 else:
...
    910 out.stop_gradient = True
    911 return out

NotImplementedError: (Unimplemented) Unsupported backend `Undefined` when casting it to paddle place type. (at /paddle/paddle/phi/core/compat/convert_utils.cc:103)
```

**Comment by ZhangzrJerry** [comment]
经过我的排查,我发现尽管我自定义`dataset`输出的是`np.astype('float32')`,`paddle.io.DataLoader`迭代器给出的数据都是`dtype=float64, place=Place(gpu_pinned)`
我把代码修改为如下即可正常运行
```py
trainloader = paddle.io.DataLoader(MyDataset())
paddle.set_device('gpu')
for x in trainloader:
    print(x)
    break
a = paddle.to_tensor(x[0], place='gpu:0', dtype='float32')
b = paddle.to_tensor(x[1], place='gpu:0', dtype='float32')
c = paddle.to_tensor(x[2], place='gpu:0', dtype='float32')
MyNet()(a,b,c)
```
