### ISSUE TITLE
paddle.split num_or_sections 参数不支持tensor输入

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/Paddle#50324]
### bug描述 Describe the Bug

# num_or_sections 参数不支持tensor输入

```python
>>> import paddle
>>> x = paddle.rand([5,2])
>>> paddle.split(x, paddle.shape(x)[-1], axis=-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ssd2/zhonghui03/anaconda3/envs/py37/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 1976, in split
    "received %s." % (type(num_or_sections))
TypeError: The type of 'num_or_sections' in split must be int, list or tuple in imperative mode, but received <class 'paddle.Tensor'>.
>>> paddle.split(x, x.shape[-1], axis=-1)
[Tensor(shape=[5, 1], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [[0.64788604],
        [0.25522688],
        [0.07560758],
        [0.40375733],
        [0.69014204]]), Tensor(shape=[5, 1], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [[0.30408362],
        [0.07870690],
        [0.42044351],
        [0.08717484],
        [0.55772632]])]
>>> paddle.version.commit
'4743cc8b9a8d77ea47e08a42a16246b538bda56f'
```

# 参数行为与torch对不齐

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/split_cn.html#split
https://pytorch.org/docs/stable/generated/torch.split.html

```
paddle.split(x, num_or_sections, axis=0, name=None)
torch.split(tensor, split_size_or_sections, dim=0)

# 表示 输入为 int 时，paddle表示切的份数，torch表示切的大小。 
```

**Comment by gongel** [comment]
已反馈负责人
