### ISSUE TITLE
@to_static未能正确处理函数递归

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#50368]
### bug描述 Describe the Bug

复现代码：
```python
import paddle

def foo(x):
  def bar(x):
    if x[0] > 0:
      x[0] -= 1
      x[1] += 1
      bar(x)
  bar(x)
  return x

print(paddle.jit.to_static(foo)(paddle.to_tensor([3, 0])))
```
BUG日志：
```
backward prim enabled:  False
forward prim enabled:  False
Traceback (most recent call last):
  File "b.py", line 12, in <module>
    print(paddle.jit.to_static(foo)(paddle.to_tensor([3, 0])))
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 464, in __call__
    error_data.raise_new_exception()
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/error.py", line 446, in raise_new_exception
    raise new_exception from None
RecursionError: In transformed code:

    File "b.py", line 9, in foo
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 8, in bar
	bar(x)
    File "b.py", line 5, in bar
	if x[0] > 0:
    File "b.py", line 6, in bar
        def bar(x):
          if x[0] > 0:
            x[0] -= 1
            ~~~~~~~~~ <--- HERE
            x[1] += 1
            bar(x)

    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/math_op_patch.py", line 375, in __impl__
	return scalar_method(self, other_var)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/math_op_patch.py", line 331, in _scalar_sub_
	return _scalar_op_(var, 1.0, -value)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/math_op_patch.py", line 298, in _scalar_op_
	attrs={"scale": scale, "bias": bias},
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 4077, in append_op
	attrs=kwargs.get("attrs", None),
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3058, in __init__
	self._update_desc_attr(attr_name, attr_val)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3397, in _update_desc_attr
	elif isinstance(val, list) and _all_is_type(val, Variable):
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 1379, in _all_is_type
	return all(isinstance(v, expected_type) for v in vals)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 1379, in <genexpr>
	return all(isinstance(v, expected_type) for v in vals)
    File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 1389, in __instancecheck__
	return issubclass(t, Variable)

    RecursionError: maximum recursion depth exceeded while calling a Python object

```
此时应该发生了栈溢出。

### 其他补充信息 Additional Supplementary Information

编译paddle所用的代码版本: develop:e44ff495346eab962bcaa764778f0cabc78dfce6

**Comment by Aurelius84** [comment]
递归函数逻辑在飞桨的@to_static逻辑是明确不支持的，因为组网期Tensor没有数据区，无法触发递归终止条件。见：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/jit/grammar_list_cn.html
