### ISSUE TITLE
@to_static不能在python repl环境中使用

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#50363]
### bug描述 Describe the Bug

复现代码：
```python
>>> import paddle
>>> paddle.jit.to_static(lambda x:x)(paddle.to_tensor([1, 2, 3]))
```
BUG日志：
```python
backward prim enabled:  False
forward prim enabled:  False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 470, in __call__
    raise e
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 440, in __call__
    *args, **kwargs, is_train=self._is_train_mode()
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 553, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 1185, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 1151, in _build_once
    **cache_key.kwargs
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 78, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 959, in from_func_spec
    static_func = convert_to_static(dygraph_function)
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 156, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 91, in convert_with_cache
    static_func = self._convert(func)
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/program_translator.py", line 118, in _convert
    source_code = func_to_source_code(func)
  File "/usr/local/lib/python3.7/dist-packages/paddle/jit/dy2static/utils.py", line 647, in func_to_source_code
    source_code_list, _ = inspect.getsourcelines(function)
  File "/usr/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.7/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

### 其他补充信息 Additional Supplementary Information

编译paddle所用的代码版本:  develop:e44ff495346eab962bcaa764778f0cabc78dfce6

**Comment by Aurelius84** [comment]
目前对于类似lambda表达式直接作为to_static的对象暂未友好支持，SCT（Souce Code Transformation）的方案目前是从用户改高频语法逐步支持的
