### ISSUE TITLE
命令行执行paddlespeech tts报错zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by yiliyili** [PaddlePaddle/Paddle#50594]
### 问题描述 Issue Description

环境cpu 最新版本paddlespeech
$ paddlespeech tts --input "你好,再见" --output /home/wwwuser/output.wav
Traceback (most recent call last):
  File "/home/wwwuser/tools/venv/bin/paddlespeech", line 8, in <module>
    sys.exit(_execute())
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/paddlespeech/cli/entry.py", line 40, in _execute
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/paddlespeech/cli/tts/__init__.py", line 14, in <module>
    from .infer import TTSExecutor
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/paddlespeech/cli/tts/infer.py", line 33, in <module>
    from paddlespeech.t2s.exps.syn_utils import get_am_inference
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/paddlespeech/t2s/__init__.py", line 18, in <module>
    from . import frontend
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/paddlespeech/t2s/frontend/__init__.py", line 16, in <module>
    from .phonectic import *
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/paddlespeech/t2s/frontend/phonectic.py", line 20, in <module>
    from g2p_en import G2p
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/g2p_en/__init__.py", line 1, in <module>
    from .g2p import G2p
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/g2p_en/g2p.py", line 22, in <module>
    nltk.data.find('taggers/averaged_perceptron_tagger.zip')
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/nltk/data.py", line 542, in find
    return ZipFilePathPointer(p, zipentry)
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/nltk/data.py", line 394, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/nltk/compat.py", line 41, in _decorator
    return init_func(*args, **kwargs)
  File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/nltk/data.py", line 935, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/home/wwwuser/tools/venv/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/home/wwwuser/tools/venv/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.3.2
Paddle With CUDA: False

OS: centos 7
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: N/A
CMake version: version 2.8.12.2
Libc version: glibc 2.17
Python version: 3.7.16

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by zh794390558** [comment]
下载文件可能破损，请重新下载。

**Comment by yiliyili** [comment]
> 下载文件可能破损，请重新下载。

请重新下载什么文件?

**Comment by zh794390558** [comment]
```
from g2p_en import G2p
File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/g2p_en/init.py", line 1, in
from .g2p import G2p
File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/g2p_en/g2p.py", line 22, in
nltk.data.find('taggers/averaged_perceptron_tagger.zip')
File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/nltk/data.py", line 542, in find
return ZipFilePathPointer(p, zipentry)
File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/nltk/compat.py", line 41, in _decorator
return init_func(*args, **kwargs)
File "/home/wwwuser/tools/venv/lib/python3.7/site-packages/nltk/data.py", line 394, in init
zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
```

应该是nltk的数据，可以搜索下nltk repo看下。

**Comment by TogetsuDo** [comment]
问题解决了吗XD
