### ISSUE TITLE
paddle2.3训练过程中dataloader报错

### ISSUE THREAD

**Issue by ludc506** [PaddlePaddle/Paddle#50716]
### bug描述 Describe the Bug

```
ERROR:root:DataLoader reader thread failed((Unavailable) File descriptor /paddle_26563_2524008688 open failed
  [Hint: Expected fd != -1, but received fd:-1 == -1:-1.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:244)
) to read data from workers' result queue.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/paddlejob/workspace/env_run/anaconda3/envs/py37_meta_pd-2.3.0_cu11/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/paddlejob/workspace/env_run/anaconda3/envs/py37_meta_pd-2.3.0_cu11/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/paddlejob/workspace/env_run/anaconda3/envs/py37_meta_pd-2.3.0_cu11/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 530, in _thread_loop
    batch = self._get_data()
  File "/root/paddlejob/workspace/env_run/anaconda3/envs/py37_meta_pd-2.3.0_cu11/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 642, in _get_data
    six.reraise(*sys.exc_info())
  File "/root/paddlejob/workspace/env_run/anaconda3/envs/py37_meta_pd-2.3.0_cu11/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/root/paddlejob/workspace/env_run/anaconda3/envs/py37_meta_pd-2.3.0_cu11/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 616, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/root/paddlejob/workspace/env_run/anaconda3/envs/py37_meta_pd-2.3.0_cu11/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
RuntimeError: (Unavailable) File descriptor /paddle_26563_2524008688 open failed
  [Hint: Expected fd != -1, but received fd:-1 == -1:-1.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:244)


Traceback (most recent call last):
  File "tools/train3d.py", line 173, in <module>
    main()
  File "tools/train3d.py", line 169, in main
    run(FLAGS, cfg)
  File "tools/train3d.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/root/paddlejob/workspace/env_run/dynamic-c3-3d/ppdet/engine/trainer.py", line 333, in train
    for data in self.loader:
  File "/root/paddlejob/workspace/env_run/anaconda3/envs/py37_meta_pd-2.3.0_cu11/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 742, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
```

**Comment by DesmonDay** [comment]
有试过最新的paddle版本吗，比如paddle 2.4之类的。
