### ISSUE TITLE
自定义NMS出错

### ISSUE THREAD

**Issue by zkyseu** [PaddlePaddle/Paddle#50896]
### 请提出你的问题 Please ask your question

您好，我在AiStudio上自定义NMS的CUDA算子报错：
`/home/aistudio/PPlanedet/pplanedet/ops/nms.cpp:37:16: error: expected constructor, destructor, or type conversion before ‘(’ token
 PYBIND11_MODULE(PADDLE_EXTENSION_NAME, m) 

nms.cpp的内容如下：
#include <paddle/extension.h>
#include <vector>
#include <iostream>

#define CHECK_INPUT(x) PD_CHECK(x.is_gpu(), #x " must be a GPU Tensor.")

std::vector<paddle::Tensor> nms_cuda_forward(
        const paddle::Tensor& boxes,
        const paddle::Tensor& idx,
        float& nms_overlap_thresh,
        unsigned long& top_k);

std::vector<paddle::Tensor> nms_forward(
        const paddle::Tensor& boxes,
        const paddle::Tensor& scores,
        float& thresh,
        unsigned long& top_k) {

    auto idx = std::get<1>(paddle::argsort(scores,0,true));
    CHECK_INPUT(boxes);
    CHECK_INPUT(idx);

    return nms_cuda_forward(boxes, idx, thresh, top_k);
}

// PD_BUILD_OP(nms_forward_)
//     .Inputs({"boxes"})
//     .Outputs({"output"})
//     .Attrs({"scores: paddle::Tensor",
//             "thresh: float",
//             "top_k: unsigned long"})
//     .SetKernelFn(PD_KERNEL(nms_forward)
//     .SetInferShapeFn(PD_INFER_SHAPE(nmsInferShape))
//     .SetInferDtypeFn(PD_INFER_DTYPE(nmsInferDtype)););

PYBIND11_MODULE(PADDLE_EXTENSION_NAME, m) {
    m.def("nms_forward", &nms_forward, "NMS");
}

可以帮我看一下如何才能编译通过，其中nms_cuda_forward在另一个文件中定义了

**Comment by zkyseu** [comment]
您好，当我使用Paddle自带的自定义算子的方式进行编译，出现如下的错误
`/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/include/paddle/phi/api/ext/op_meta_info.h:185:68: error: incomplete type ‘paddle::KernelFuncImpl<std::vector<paddle::experimental::Tensor> (*)(const paddle::experimental::Tensor&, const paddle::experimental::Tensor&, float&, long unsigned int&), nms_forward>::ComputeCallHelper<float&, long unsigned int&, paddle::TypeTag<int> >’ used in nested name specifier
       ComputeCallHelper<
       ~~~~~~~~~~~~~~~~~~                                            
           Tail...>::template Compute<in_idx + 1, attr_idx, out_idx>(ctx,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
                                                                     pargs...,
                                                                     ~~~~~~~~~
                                                                     arg);`

nms.cpp里面的代码如下所示。
`
#include <paddle/extension.h>
#include <vector>
#include <iostream>

#define CHECK_INPUT(x) PD_CHECK(x.is_gpu(), #x " must be a GPU Tensor.")

std::vector<paddle::Tensor> nms_cuda_forward(
        const paddle::Tensor& boxes,
        const paddle::Tensor& idx,
        float& nms_overlap_thresh,
        unsigned long& top_k);

std::vector<paddle::Tensor> nms_forward(
        const paddle::Tensor& boxes,
        const paddle::Tensor& scores,
        float& thresh,
        unsigned long& top_k) {


    auto idx = std::get<1>(paddle::argsort(scores,0,true));
    CHECK_INPUT(boxes);
    CHECK_INPUT(idx);

    return nms_cuda_forward(boxes, idx, thresh, top_k);
}

PD_BUILD_OP(nms_forward_)
    .Inputs({"boxes"})
    .Outputs({"output"})
    .Attrs({"scores: paddle::Tensor",
            "thresh: float",
            "top_k: unsigned long"})
    .SetKernelFn(PD_KERNEL(nms_forward)
    .SetInferShapeFn(PD_INFER_SHAPE(nmsInferShape))
    .SetInferDtypeFn(PD_INFER_DTYPE(nmsInferDtype)););

// PYBIND11_MODULE(nms, m) {
//     m.def("nms_forward", &nms_forward, "NMS");
// }
`

可以帮我看一下这是什么原因吗，谢谢

**Comment by zkyseu** [comment]
给个建议，Paddle文档里面对于C++自定义算子只提供了relu这种最简单的算子，建议增加一些复杂算子，有多输入或者多输出那种，增加文档的实用性。不然，真的找不到太多例子可以借鉴

**Comment by 2742195759** [comment]
自定义算子还不支持这个数据类型：unsigned long，所以编译报错了。麻烦换成 int64_t 这个数据类型试试？
参考章节：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html#attribute

**Comment by zkyseu** [comment]
> int64_t

@2742195759 
您好，感谢回复，编译是通过了，但是生成.so文件后我使用python进行import后报如下错误
`ImportError: /home/aistudio/PPlanedet/pplanedet/ops/nms_impl.so: undefined symbol: _Z16nms_cuda_forwardRKN6paddle12experimental6TensorES3_fl`

import 代码如下
```
aistudio@jupyter-296821-5568014:~/PPlanedet/pplanedet/ops$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nms_imp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/aistudio/PPlanedet/pplanedet/ops/nms_impl.so: undefined symbol: _Z16nms_cuda_forwardRKN6paddle12experimental6TensorES3_fl
```

**Comment by jiahy0825** [comment]
> .Attrs({"scores: paddle::Tensor",

Tensor 应该作为 `Inputs`，而非 `Attrs`。对于多输入的语句，可以写成：
`.Inputs({"boxes", "scores"})`

**Comment by zkyseu** [comment]
@jiahy0825 @2742195759 您好，我按照要求进行修改后还是报import错误，具体的cc文件代码如下，可以帮我看一下哪里有问题吗
```
#include <paddle/extension.h>
#include <vector>
#include <iostream>
// #include </home/aistudio/PPlanedet/pplanedet/ops/nms_kernel.h>

#define CHECK_INPUT(x) PD_CHECK(x.is_gpu(), #x " must be a GPU Tensor.")

// {
//     std::vector<paddle::Tensor> nms_forward(
//             const paddle::Tensor& boxes,
//             const paddle::Tensor& scores,
//             const float thresh,
//             const unsigned long top_k);    
//     std::vector<paddle::Tensor> nms_cuda_forward(
//             const paddle::Tensor& boxes,
//             const paddle::Tensor& idx,
//             const float nms_overlap_thresh,
//             const unsigned long top_k);
// }

std::vector<paddle::Tensor> nms_cuda_forward(
        const paddle::Tensor& boxes,
        const paddle::Tensor& idx,
        const float nms_overlap_thresh,
        const int64_t top_k);


std::vector<paddle::Tensor> nms_forward(
        const paddle::Tensor& boxes,
        const paddle::Tensor& scores,
        const float thresh,
        const int64_t top_k) {


    auto idx = std::get<1>(paddle::argsort(scores,0,true));
    CHECK_INPUT(boxes);
    CHECK_INPUT(idx);

    return nms_cuda_forward(boxes, idx, thresh, top_k);
}

// // 维度推导
// std::vector<std::vector<int64_t>> RunInferShape(
//     std::vector<int64_t> boxes_shape,
//     std::vector<int64_t> scores_shape,
// ) 
// {
//     const int box_num = boxes_shape[0];
//     const int keep_num = box_num;
//     std::vector<int64_t> keep{box_num,box_num,box_num};
//     return {keep};
// }

// //类型推导
// std::vector<paddle::DataType> RunInferDtype(
//     paddle::DataType boxes_dtype,
//     paddle::DataType scores_dtype,
// ) 
// {
//     return {boxes_dtype,boxes_dtype,scores_dtype};
// }

PD_BUILD_OP(nms_forward_)
    .Inputs({"boxes","scores","thresh","top_k"})
    .Outputs({"keep","num_to_keep","parent_object_index"})
    .Attrs({"thresh: float",
            "top_k: int64_t"})
    .SetKernelFn(PD_KERNEL(nms_forward));

// PYBIND11_MODULE(nms_, m) {
//     m.def("nms_forward", &nms_forward, "NMS");
// }

**Comment by jiahy0825** [comment]
在注册算子时，Inputs 中只需要传入 Tensor 对应的名称，所以 `PD_BUILD_OP` 部分的代码应为：

```
PD_BUILD_OP(nms_forward_)
    .Inputs({"boxes","scores"})  // 去掉了 "thresh" 和 "top_k"
    .Outputs({"keep","num_to_keep","parent_object_index"})
    .Attrs({"thresh: float",
            "top_k: int64_t"})
    .SetKernelFn(PD_KERNEL(nms_forward));
```

如果仍有 import 报错，建议同时附上编写的 `setup.py` 文件代码（使用 setuptools 编译），或者 `load` 函数的调用代码（使用即时编译），便于进一步定位问题。

**Comment by jiahy0825** [comment]
> 给个建议，Paddle文档里面对于C++自定义算子只提供了relu这种最简单的算子，建议增加一些复杂算子，有多输入或者多输出那种，增加文档的实用性。不然，真的找不到太多例子可以借鉴

感谢反馈～后续会考虑进一步优化文档。

**Comment by zkyseu** [comment]
@2742195759 @jiahy0825 您好，以下是setup.py里面的内容
```
import setuptools
import sys
import glob
from paddle.utils.cpp_extension import CUDAExtension,setup,BuildExtension

import pplanedet #这是同目录下的文件夹

long_description = "A Tookit for lane detection based on PaddlePaddle"

with open("requirements.txt") as file:
    REQUIRED_PACKAGES = file.read()

setup(
    name = 'pplanedet.ops.nms_impl',
    ext_modules=CUDAExtension(
        sources=glob.glob('./pplanedet/ops/*.c*')  # 支持同时编译多个 OP
    )    
)

setuptools.setup(
    name="pplanedet",
    version='0.0.2',
    author="kunyangzhou",
    author_email="zhoukunyangmcgill@163.com",
    description=long_description,
    long_description=long_description,
    long_description_content_type="text/plain",
    url="https://github.com/zkyseu/PPlanedet",
    packages=setuptools.find_packages(),
    include_package_data=True,
    setup_requires=['cython', 'numpy'],
    install_requires=REQUIRED_PACKAGES,
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    license='MIT License',
    entry_points={'console_scripts': ['pplanedet=pplanedet.command:main', ]})
```

我顺带加上nms_kernel.cu文件内容，请您帮我定位一下具体的问题
```
#include <paddle/extension.h>
#include <vector>
#include <cuda.h>
#include <cuda_runtime.h>
#include <iostream>
#define BLOCK 512

#define MAX_COL_BLOCKS 1000
#define STRIDE 4
#define N_OFFSETS 72 // if you use more than 73 offsets you will have to adjust this value
#define N_STRIPS (N_OFFSETS - 1)
#define PROP_SIZE (5 + N_OFFSETS)
#define DATASET_OFFSET 0

#define DIVUP(m,n) (((m)+(n)-1) / (n))
int64_t const threadsPerBlock = sizeof(int64_t) * 8;

template <typename data_t>
// __device__ inline data_t devIoU(data_t const * const a, data_t const * const b) {
__device__ inline bool devIoU(data_t const * const a, data_t const * const b, const float threshold) {
  const int start_a = (int) (a[2] * N_STRIPS - DATASET_OFFSET + 0.5); // 0.5 rounding trick
  const int start_b = (int) (b[2] * N_STRIPS - DATASET_OFFSET + 0.5);
  const int start = max(start_a, start_b);
  const int end_a = start_a + a[4] - 1 + 0.5 - ((a[4] - 1) < 0); //  - (x<0) trick to adjust for negative numbers (in case length is 0)
  const int end_b = start_b + b[4] - 1 + 0.5 - ((b[4] - 1) < 0);
  const int end = min(min(end_a, end_b), N_OFFSETS - 1);
  // if (end < start) return 1e9;
  if (end < start) return false;
  data_t dist = 0;
  for(unsigned char i = 5 + start; i <= 5 + end; ++i) {
    if (a[i] < b[i]) {
      dist += b[i] - a[i];
    } else {
      dist += a[i] - b[i];
    }
  }
  // return (dist / (end - start + 1)) < threshold;
  return dist < (threshold * (end - start + 1));
  // return dist / (end - start + 1);
}

template <typename data_t>
__global__ void nms_kernel(const int64_t n_boxes, const data_t nms_overlap_thresh,
                           const data_t *dev_boxes, const int64_t *idx, int64_t *dev_mask) {
  const int64_t row_start = blockIdx.y;
  const int64_t col_start = blockIdx.x;

  if (row_start > col_start) return;

  const int row_size =
        min(n_boxes - row_start * threadsPerBlock, threadsPerBlock);
  const int col_size =
        min(n_boxes - col_start * threadsPerBlock, threadsPerBlock);

  __shared__ data_t block_boxes[threadsPerBlock * PROP_SIZE];
  if (threadIdx.x < col_size) {
    for (int i = 0; i <  PROP_SIZE; ++i) {
      block_boxes[threadIdx.x * PROP_SIZE + i] = dev_boxes[idx[(threadsPerBlock * col_start + threadIdx.x)] * PROP_SIZE + i];
    }
  }
  __syncthreads();

  if (threadIdx.x < row_size) {
    const int cur_box_idx = threadsPerBlock * row_start + threadIdx.x;
    const data_t *cur_box = dev_boxes + idx[cur_box_idx] * PROP_SIZE;
    int i = 0;
    int64_t t = 0;
    int start = 0;
    if (row_start == col_start) {
      start = threadIdx.x + 1;
    }
    for (i = start; i < col_size; i++) {
      if (devIoU(cur_box, block_boxes + i * PROP_SIZE, nms_overlap_thresh)) {
        t |= 1ULL << i;
      }
    }
    const int col_blocks = DIVUP(n_boxes, threadsPerBlock);
    dev_mask[cur_box_idx * col_blocks + col_start] = t;
  }
}

__global__ void nms_collect(const int64_t boxes_num, const int64_t col_blocks, int64_t top_k, const int64_t *idx, const int64_t *mask, int64_t *keep, int64_t *parent_object_index, int64_t *num_to_keep) {
  int64_t remv[MAX_COL_BLOCKS];
  int64_t num_to_keep_ = 0;

  for (int i = 0; i < col_blocks; i++) {
      remv[i] = 0;
  }

  for (int i = 0; i < boxes_num; ++i) {
      parent_object_index[i] = 0;
  }

  for (int i = 0; i < boxes_num; i++) {
    int nblock = i / threadsPerBlock;
    int inblock = i % threadsPerBlock;


    if (!(remv[nblock] & (1ULL << inblock))) {
      int64_t idxi = idx[i];
      keep[num_to_keep_] = idxi;
      const int64_t *p = &mask[0] + i * col_blocks;
      for (int j = nblock; j < col_blocks; j++) {
        remv[j] |= p[j];
      }
      for (int j = i; j < boxes_num; j++) {
        int nblockj = j / threadsPerBlock;
        int inblockj = j % threadsPerBlock;
        if (p[nblockj] & (1ULL << inblockj))
            parent_object_index[idx[j]] = num_to_keep_+1;
      }
      parent_object_index[idx[i]] = num_to_keep_+1;

      num_to_keep_++;

      if (num_to_keep_==top_k)
          break;
    }
  }

  // Initialize the rest of the keep array to avoid uninitialized values.
  for (int i = num_to_keep_; i < boxes_num; ++i)
      keep[i] = 0;

  *num_to_keep = min(top_k,num_to_keep_);
}

std::vector<paddle::Tensor> nms_cuda_forward(
        const paddle::Tensor boxes,
        const paddle::Tensor idx,
        const float nms_overlap_thresh,
        const int64_t top_k) {

  const auto boxes_num = boxes.shape()[0];
  PD_CHECK(boxes.shape()[0] == PROP_SIZE, "Wrong number of offsets. Please adjust `PROP_SIZE`");

  const int col_blocks = DIVUP(boxes_num, threadsPerBlock);

  PD_CHECK (col_blocks < MAX_COL_BLOCKS, "The number of column blocks must be less than MAX_COL_BLOCKS. Increase the MAX_COL_BLOCKS constant if needed.");

  auto mask = paddle::empty({boxes_num * col_blocks}, paddle::DataType::INT64,paddle::GPUPlace());

  dim3 blocks(DIVUP(boxes_num, threadsPerBlock),
              DIVUP(boxes_num, threadsPerBlock));
  dim3 threads(threadsPerBlock);

  PD_DISPATCH_FLOATING_TYPES(boxes.type(), "nms_cuda_forward", ([&] {
    nms_kernel<<<blocks, threads>>>(boxes_num,
                                    (data_t)nms_overlap_thresh,
                                    boxes.data<data_t>(),
                                    idx.data<int64_t>(),
                                    mask.data<int64_t>());
  }));

  auto keep = paddle::empty({boxes_num}, paddle::DataType::INT64);
  auto parent_object_index = paddle::empty({boxes_num}, paddle::DataType::INT64);
  auto num_to_keep = paddle::empty({}, paddle::DataType::INT64);

  nms_collect<<<1, 1>>>(boxes_num, col_blocks, top_k,
                        idx.data<int64_t>(),
                        mask.data<int64_t>(),
                        keep.data<int64_t>(),
                        parent_object_index.data<int64_t>(),
                        num_to_keep.data<int64_t>());


  return {keep,num_to_keep,parent_object_index};
}
```

**Comment by jiahy0825** [comment]
> 在注册算子时，Inputs 中只需要传入 Tensor 对应的名称，所以 `PD_BUILD_OP` 部分的代码应为：
> 
> ```
> PD_BUILD_OP(nms_forward_)
>     .Inputs({"boxes","scores"})  // 去掉了 "thresh" 和 "top_k"
>     .Outputs({"keep","num_to_keep","parent_object_index"})
>     .Attrs({"thresh: float",
>             "top_k: int64_t"})
>     .SetKernelFn(PD_KERNEL(nms_forward));
> ```

是否有参考这个修改呢？修改后报错信息是什么

**Comment by zkyseu** [comment]
@jiahy0825 已经参照您的提示修改了，这是修改后的cc文件

```
#include <paddle/extension.h>
#include <vector>
#include <iostream>

#define CHECK_INPUT(x) PD_CHECK(x.is_gpu(), #x " must be a GPU Tensor.")

std::vector<paddle::Tensor> nms_cuda_forward(
        const paddle::Tensor& boxes,
        const paddle::Tensor& idx,
        const float nms_overlap_thresh,
        const int64_t top_k);


std::vector<paddle::Tensor> nms_forward(
        const paddle::Tensor& boxes,
        const paddle::Tensor& scores,
        const float thresh,
        const int64_t top_k) {


    auto idx = std::get<1>(paddle::argsort(scores,0,true));
    CHECK_INPUT(boxes);
    CHECK_INPUT(idx);

    return nms_cuda_forward(boxes, idx, thresh, top_k);
}

PD_BUILD_OP(nms_forward_)
    .Inputs({"boxes","scores"})
    .Outputs({"keep","num_to_keep","parent_object_index"})
    .Attrs({"thresh: float",
            "top_k: int64_t"})
    .SetKernelFn(PD_KERNEL(nms_forward));
```

下面是报错的信息
```
>>> import nms_impl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/aistudio/PPlanedet/pplanedet/ops/nms_impl.so: undefined symbol: _Z16nms_cuda_forwardRKN6paddle12experimental6TensorES3_fl
>>> 
```

**Comment by jiahy0825** [comment]
我在本地测试时，是可以正常 import 的，下面是我 import 的步骤。

**1. 只测试自定义算子，去掉多余代码**

```
import setuptools
import sys
import glob
from paddle.utils.cpp_extension import CUDAExtension,setup,BuildExtension

# import pplanedet #这是同目录下的文件夹

long_description = "A Tookit for lane detection based on PaddlePaddle"

# with open("requirements.txt") as file:
#     REQUIRED_PACKAGES = file.read()

setup(
    name = 'pplanedet.ops.nms_impl',
    ext_modules=CUDAExtension(
        # sources=glob.glob('./pplanedet/ops/*.c*')  # 支持同时编译多个 OP
        sources=["nms_kernel.cu", "nms_kernel.cc"]  # 支持同时编译多个 OP（改成了您提供的 .cu 文件和 .cc 文件）
    )    
)

# setuptools.setup(
#     name="pplanedet",
#     version='0.0.2',
#     author="kunyangzhou",
#     author_email="zhoukunyangmcgill@163.com",
#     description=long_description,
#     long_description=long_description,
#     long_description_content_type="text/plain",
#     url="https://github.com/zkyseu/PPlanedet",
#     packages=setuptools.find_packages(),
#     include_package_data=True,
#     setup_requires=['cython', 'numpy'],
#     install_requires=REQUIRED_PACKAGES,
#     classifiers=[
#         "Programming Language :: Python :: 3",
#         "License :: OSI Approved :: MIT License",
#         "Operating System :: OS Independent",
#     ],
#     license='MIT License',
#     entry_points={'console_scripts': ['pplanedet=pplanedet.command:main', ]})
```

**2. 测试 import（结果正常）**
```
import paddle
import pplanedet.ops.nms_impl
```

有几个建议：
1. 自定义算子 setup 函数中的 name 参数可以考虑换一个名字，可能是因为和 setuptools.setup 中的 name 参数有冲突
2. python 端调用时，先调用一下 `import paddle` 语句
3. 检查 setup 函数中 sources 参数的文件路径，确保正确

如果仍有问题，希望能提供下机器环境的详细配置、PaddlePaddle 版本，以及完整的最小可复现代码。

祝好

**Comment by zkyseu** [comment]
@jiahy0825 我这边测试成功了，谢谢您！

**Comment by zkyseu** [comment]
@jiahy0825 我刚刚再项目中测试时候，又遇到一个新的问题，我这里提供python测试的代码
```
import nms_impl


def nms(boxes, scores, overlap, top_k):
    return nms_impl.nms_forward_(boxes, scores, overlap, top_k)

if __name__ == "__main__":
    #for test
    import paddle
    boxes = paddle.rand((20,4))
    scores = paddle.rand((20,1))
    overlap = 0.5
    top_k = 10
    out = nms(boxes,scores,overlap,top_k)
```

运行的时候会报如下的错误，就是以上cpp和cu文件生成的.so文件
`python: symbol lookup error: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/nms_impl-0.0.0-py3.7-linux-x86_64.egg/nms_impl_pd_.so: undefined symbol: _Z16nms_cuda_forwardRKN6paddle12experimental6TensorES3_fl`

**Comment by jiahy0825** [comment]
建议首先查看官方文档，检查是否用法上有问题～
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html

如果仍有疑问，希望提供一个最小复现集合的代码。梳理这个代码的过程，也是对照官方文档，梳理自己思路的过程。直接张贴大段代码，太难针对性调试了。

**Comment by zkyseu** [comment]
好的，我再看看，谢谢

**Comment by jiahy0825** [comment]
@zkyseu 刚刚定位到了问题，是 `.cu` 文件中的函数签名有误～

```
std::vector<paddle::Tensor> nms_cuda_forward(
        const paddle::Tensor& boxes,    //  此处应为 const paddle::Tensor&，而非 const paddle::Tensor
        const paddle::Tensor& idx,      //  此处应为 const paddle::Tensor&，而非 const paddle::Tensor
        const float nms_overlap_thresh,
        const int64_t top_k)
```

修改后，代码已经可以跑起来了，但是还会报下面的错误，应该是代码实现的问题。

<img width="888" alt="image" src="https://user-images.githubusercontent.com/17810795/221569075-382a8fbf-3464-42d8-9a1e-8f645c05a2be.png">
