### ISSUE TITLE
小数据在DistributedBatchSampler时报错AssertionError `assert len(indices) == self.total_size`

### ISSUE THREAD

**Issue by Yam0214** [PaddlePaddle/Paddle#50954]
#### 描述

notation:
* 分布式运行的gpu数目：`n_device`
* 数据集中样本的数目：`n_sample`
  
当`n_device > 2 * n_sample`时，报错AssertionError `assert len(indices) == self.total_size`

#### 复现

新建一个`test_dataloader.py`文件，写入：
```python
import paddle
from paddlenlp.utils.log import logger
from paddle.io import Dataset, DataLoader, DistributedBatchSampler

class RandomDataset(Dataset):
    def __init__(self, data_num=2):
        self.data_num = data_num

    def __getitem__(self, idx):
        return idx, paddle.randn((2,))
    
    def __len__(self):
        return self.data_num


def main():
    ds = RandomDataset(data_num=2)
    sampler = DistributedBatchSampler(ds, batch_size=3)
    dataloader = DataLoader(
        ds, 
        batch_sampler=sampler, 
        num_workers=0,
        )

    for idx, data in dataloader:
        logger.info("rank: {}\tdata_idx: {}".format(paddle.distributed.get_rank(), idx.numpy()))


if __name__ == '__main__':
    main()
```
分布式运行上述代码，
```shell
python -m paddle.distributed.launch --gpus 0,1,2,3,4 test_dataloader.py
```

#### 报错信息

报错如下
```shell
Traceback (most recent call last):
  File "/root/miniconda3/envs/paddle2.4/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/paddle2.4/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/paddle2.4/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 212, in _thread_loop
    indices = next(self._sampler_iter)
  File "/root/miniconda3/envs/paddle2.4/lib/python3.7/site-packages/paddle/fluid/dataloader/batch_sampler.py", line 263, in __iter__
    assert len(indices) == self.total_size
AssertionError
```

**Comment by zoooo0820** [comment]
你好，问题已收到，我们会评估一下这种case的行为应该如何设计

**Comment by heavengate** [comment]
如果sample数小于device数，每个device都没法分到1个sample，这种本来也是没法跑的吧
