### ISSUE TITLE
运行hifigan csmsc的run.sh报错

### ISSUE THREAD

**Issue by wrz1999** [PaddlePaddle/Paddle#51050]
### 请提出你的问题 Please ask your question

[2023-03-01 12:36:45] [INFO] [trainer.py:167]  iter: 1/2500000, Rank: 0, , avg_reader_cost: 0.63253 sec, avg_batch_cost: 0.63257 sec, avg_samples: 16, avg_ips: 25.29360 sequences/sec
Exception in main training loop: (InvalidArgument) The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [16, 1, 8400], X's size = 134400, 'shape' is [16, 1, 0, 2], the capacity of 'shape' is 268800.
  [Hint: Expected capacity == in_size, but received capacity:268800 != in_size:134400.] (at /paddle/paddle/phi/infermeta/unary.cc:1435)

Traceback (most recent call last):
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/training/updaters/standard_updater.py", line 110, in update
    self.update_core(batch)
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/models/hifigan/hifigan_updater.py", line 141, in update_core
    p = self.discriminator(wav)
  File "/opt/conda/envs/pad/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/models/hifigan/hifigan.py", line 765, in forward
    mpd_outs = self.mpd(x)
  File "/opt/conda/envs/pad/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/models/hifigan/hifigan.py", line 426, in forward
    outs += [f(x)]
  File "/opt/conda/envs/pad/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/models/hifigan/hifigan.py", line 340, in forward
    x = x.reshape([b, c, t // self.period, self.period])
  File "/opt/conda/envs/pad/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 3543, in reshape
    out = _C_ops.reshape(x, shape)
Trainer extensions will try to handle the extension. Then all extensions will finalize.Traceback (most recent call last):
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/hifigan/train.py", line 274, in <module>
    main()
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/hifigan/train.py", line 270, in main
    train_sp(args, config)
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/exps/gan_vocoder/hifigan/train.py", line 239, in train_sp
    trainer.run()
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/training/trainer.py", line 198, in run
    six.reraise(*exc_info)
  File "/opt/conda/envs/pad/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/training/trainer.py", line 149, in run
    update()
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/training/updaters/standard_updater.py", line 110, in update
    self.update_core(batch)
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/models/hifigan/hifigan_updater.py", line 141, in update_core
    p = self.discriminator(wav)
  File "/opt/conda/envs/pad/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/models/hifigan/hifigan.py", line 765, in forward
    mpd_outs = self.mpd(x)
  File "/opt/conda/envs/pad/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/models/hifigan/hifigan.py", line 426, in forward
    outs += [f(x)]
  File "/opt/conda/envs/pad/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/rzwang/PaddleSpeech/paddlespeech/t2s/models/hifigan/hifigan.py", line 340, in forward
    x = x.reshape([b, c, t // self.period, self.period])
  File "/opt/conda/envs/pad/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 3543, in reshape
    out = _C_ops.reshape(x, shape)
ValueError: (InvalidArgument) The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [16, 1, 8400], X's size = 134400, 'shape' is [16, 1, 0, 2], the capacity of 'shape' is 268800.
  [Hint: Expected capacity == in_size, but received capacity:268800 != in_size:134400.] (at /paddle/paddle/phi/infermeta/unary.cc:1435)

**Comment by linjieccc** [comment]
@wrz1999 你好，PaddleSpeech的问题可以在这里咨询下：https://github.com/PaddlePaddle/PaddleSpeech/issues
