### ISSUE TITLE
某些shape的tensor进行fold操作时报错

### ISSUE THREAD

**Issue by flytocc** [PaddlePaddle/Paddle#51192]
### bug描述 Describe the Bug

问题描述：
如题，在进行fold操作时，某些shape的tensor会引发报错。

测试代码：
```python
import paddle
bs = 128  # 当bs不大于64时不报错
paddle.nn.functional.fold(paddle.randn([bs,256,256]),output_sizes=[32,32],kernel_sizes=[2,2],strides=[2,2])
```

报错信息：
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 2354, in fold
    x, output_sizes, kernel_sizes, strides, paddings, dilations
RuntimeError: (PreconditionNotMet) Tensor's dimension is out of bound.Tensor's dimension must be equal or less than the size of its memory.But received Tensor's dimension is 524288, memory's size is 262144.
  [Hint: Expected numel() * SizeOf(dtype()) <= memory_size(), but received numel() * SizeOf(dtype()):524288 > memory_size():262144.] (at /paddle/paddle/phi/core/dense_tensor_impl.cc:58)
```

### 其他补充信息 Additional Supplementary Information

测试环境：
3090+CUDA11.6+paddle2.4.1+python3.9 或 aistudio（V100+CUDA11.2+paddle2.4.0+python3.7）

**Comment by yt605155624** [comment]
无法复现，可能是你的硬件配置低，可以换个配置高的环境试试

**Comment by flytocc** [comment]
> 无法复复现，可能是你的硬件配置低，可以换个配置高的环境试试

这是我的配置
```
Ubuntu20.04 kernel 5.15.0-56-generic
Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz
128GB 内存
4*3090 (24GB显存) 
CUDA 11.6.124 + CUDNN 8.4.1
paddlepaddle-gpu 2.4.1.post116
1 TB SSD + 3TB HDD
```

**Comment by yt605155624** [comment]
如果你一定要用这么大的 shape, 可以到 aistudio 换成 32G 的显卡试试

**Comment by flytocc** [comment]
> 无法复复现，可能是你的硬件配置低，可以换个配置高的环境试试

另外我在aistudio上也复现了这个bug
https://aistudio.baidu.com/aistudio/projectdetail/5629355

> 如果你一定要用这么大的 shape, 可以到 aistudio 换成 32G 的显卡试试

这个shape不算大，只能算是轻量级的。在pytorch上只占用显存不到800MB

**Comment by flytocc** [comment]
> 这个shape不算大，只能算是轻量级的。在pytorch上只占用显存不到800MB

在pytorch中，fold这个操作只增加了34MB显存占用，内存占用基本没变化。

在aistudio中，使用的是V100 32GB

**Comment by flytocc** [comment]
@yt605155624 请问你复现了这个bug吗？

**Comment by flytocc** [comment]
我今天又在aistudio上试了试，在paddle 2.3.2和2.4.0能比较稳定的复现，2.5.0暂时没能复现出来
