### ISSUE TITLE
使用Conda安装GPU版Paddle 2.4.2报错current_repodata.json找不到

### ISSUE THREAD

**Issue by wuxianshen** [PaddlePaddle/Paddle#51198]
### 请提出你的问题 Please ask your question

使用Conda安装GPU版Paddle 2.4.2，报错，错误提示如下：

```
conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\gateways\repodata\__init__.py", line 132, in conda_http_errors
        yield
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\gateways\repodata\__init__.py", line 101, in repodata
        response.raise_for_status()
      File "C:\Users\tao\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://mirrors.bfsu.edu.cn/anaconda/cloud/Paddle/win-64/current_repodata.json

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\tao\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "C:\Users\tao\AppData\Roaming\Python\Python39\site-packages\simplejson\__init__.py", line 525, in loads
        return _default_decoder.decode(s)
      File "C:\Users\tao\AppData\Roaming\Python\Python39\site-packages\simplejson\decoder.py", line 372, in decode
        obj, end = self.raw_decode(s)
      File "C:\Users\tao\AppData\Roaming\Python\Python39\site-packages\simplejson\decoder.py", line 402, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\cli\main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\cli\conda_argparse.py", line 91, in do_call
        return getattr(module, func_name)(args, parser)
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\notices\core.py", line 103, in wrapper
        return_value = func(*args, **kwargs)
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\cli\install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\core\solve.py", line 132, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\core\solve.py", line 175, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\core\solve.py", line 280, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\common\io.py", line 84, in decorated
        return f(*args, **kwds)
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\core\solve.py", line 447, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\core\solve.py", line 1060, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\core\index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\core\subdir_data.py", line 124, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "D:\Software\Anaconda3\2022_10\lib\concurrent\futures\_base.py", line 609, in result_iterator
        yield fs.pop().result()
      File "D:\Software\Anaconda3\2022_10\lib\concurrent\futures\_base.py", line 446, in result
        return self.__get_result()
      File "D:\Software\Anaconda3\2022_10\lib\concurrent\futures\_base.py", line 391, in __get_result
        raise self._exception
      File "D:\Software\Anaconda3\2022_10\lib\concurrent\futures\thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\core\subdir_data.py", line 113, in <lambda>
        subdir_query = lambda url: tuple(
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\core\subdir_data.py", line 129, in query
        self.load()
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\core\subdir_data.py", line 215, in load
        _internal_state = self._load()
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\core\subdir_data.py", line 323, in _load
        raw_repodata_str = self._repo.repodata(mod_etag_headers)
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\gateways\repodata\__init__.py", line 101, in repodata
        response.raise_for_status()
      File "D:\Software\Anaconda3\2022_10\lib\contextlib.py", line 137, in __exit__
        self.gen.throw(typ, value, traceback)
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\gateways\repodata\__init__.py", line 179, in conda_http_errors
        raise RepodataIsEmpty(
      File "D:\Software\Anaconda3\2022_10\lib\site-packages\conda\exceptions.py", line 461, in __init__
        body = response.json()
      File "C:\Users\tao\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

$ D:\Software\Anaconda3\2022_10\Scripts\conda-script.py install paddlepaddle-gpu==2.4.2 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=paddle_tt
                CONDA_EXE=D:\Software\Anaconda3\2022_10\condabin\..\Scripts\conda.exe
               CONDA_EXES="D:\Software\Anaconda3\2022_10\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=D:\File\AnacondaEnvs\envs\paddle_tt
           CONDA_PREFIX_1=D:\Software\Anaconda3\2022_10
    CONDA_PROMPT_MODIFIER=(paddle_tt)
         CONDA_PYTHON_EXE=D:\Software\Anaconda3\2022_10\python.exe
               CONDA_ROOT=D:\Software\Anaconda3\2022_10
              CONDA_SHLVL=2
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\tao
               LD_PRELOAD=<not set>
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=D:\File\AnacondaEnvs\envs\paddle_tt;D:\File\AnacondaEnvs\envs\paddle_t
                          t\Library\mingw-w64\bin;D:\File\AnacondaEnvs\envs\paddle_tt\Library\us
                          r\bin;D:\File\AnacondaEnvs\envs\paddle_tt\Library\bin;D:\File\Anaconda
                          Envs\envs\paddle_tt\Scripts;D:\File\AnacondaEnvs\envs\paddle_tt\bin;D:
                          \Software\Anaconda3\2022_10\condabin;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v11.7\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v11.7\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\S
                          ystem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\Sys
                          tem32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files\dotnet;C:\Program Files\NVIDIA
                          Corporation\Nsight Compute 2022.2.1;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v11.7\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v11.7\lib;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v11.7\include;C:\Program Files\NVIDIA GPU Computing Toolk
                          it\CUDA\v11.7\libnvvp;D:\Software\Java\JDK17\bin;D:\Software\Git\cmd;D
                          :\Software\Strawberry\c\bin;D:\Software\Strawberry\perl\site\bin;D:\So
                          ftware\Strawberry\perl\bin;C:\Users\tao\AppData\Local\Microsoft\Window
                          sApps;C:\Users\tao\.dotnet\tools;C:\Users\tao\AppData\Local\JetBrains\
                          Toolbox\scripts;D:\Path;D:\Software\NASM
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : D:\File\AnacondaEnvs\envs\paddle_tt
    active env location : D:\File\AnacondaEnvs\envs\paddle_tt
            shell level : 2
       user config file : C:\Users\tao\.condarc
 populated config files :
          conda version : 23.1.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __win=0=0
       base environment : D:\Software\Anaconda3\2022_10  (writable)
      conda av data dir : D:\Software\Anaconda3\2022_10\etc\conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Software\Anaconda3\2022_10\pkgs
                          C:\Users\tao\.conda\pkgs
                          C:\Users\tao\AppData\Local\conda\conda\pkgs
       envs directories : D:\Software\Anaconda3\2022_10\envs
                          C:\Users\tao\.conda\envs
                          C:\Users\tao\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.9.13 Windows/10 Windows/10.0.22621
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: n

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false


(paddle_tt) C:\Windows\System32>conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.7
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=11.7
  - paddlepaddle-gpu==2.4.2

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by yt605155624** [comment]
可以尝试在 paddle 官方的 docker 中安装，避免一些环境问题

**Comment by wuxianshen** [comment]
是在Windows平台使用paddle，没有docker用怎么办呢；
之前conda安装一直可以成功，从昨天开始一直报错找不到https://mirrors.bfsu.edu.cn/anaconda/cloud/Paddle/win-64/current_repodata.json；
我看https://mirrors.bfsu.edu.cn/anaconda/cloud/Paddle/win-64/下是有repodata.json没有current_repodata.json；
这个是我自己电脑的问题，还是仓库的问题呢？

**Comment by yt605155624** [comment]
1. windows 应该也能 WSL 或者 git bash 里面用 docker ，你自己研究下
2. 那你确认下“之前可以成功”的 paddle 版本

**Comment by wuxianshen** [comment]
之前就是用官网建议命令安装的2.4.2：
conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
新建conda环境后，再用这个命令，就报上面提到的HttpError错误了

**Comment by yt605155624** [comment]
如果相同的 paddle 版本，之前可以安装现在不行，大概率是你自己环境的问题

**Comment by wuxianshen** [comment]
好的谢谢
