### ISSUE TITLE
The unit testing of test_lstm_unit_op fails frequently.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#5123]
Need to fix it.

```
[14:10:12]	218/239 Test #222: test_lstm_unit_op ...........................***Failed 1.62 sec
[14:10:12]	.F
[14:10:12]	======================================================================
[14:10:12]	FAIL: test_check_output (__main__.LstmUnitTest)
[14:10:12]	----------------------------------------------------------------------
[14:10:12]	Traceback (most recent call last):
[14:10:12]	File "test_lstm_unit_op.py", line 31, in test_check_output
[14:10:12]	self.check_output()
[14:10:12]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 367, in check_output
[14:10:12]	self.check_output_with_place(place, atol)
[14:10:12]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 356, in check_output_with_place
[14:10:12]	"Output (" + out_name + ") has diff at " + str(place))
[14:10:12]	AssertionError: Output (H) has diff at GPUPlace(0)
```

**Comment by typhoonzero** [comment]
@qingqing01 can we close this now?
