### ISSUE TITLE
[install] paddle.utils.run_check error

### ISSUE THREAD

**Issue by gouzil** [PaddlePaddle/Paddle#51437]
### 问题描述 Issue Description

编译版本为 cpu，没能在官网的 develop 包中复现

git commit ```f3cac96659d5f8a5a924609acc5fbe60f34279f7```

编译命令
```bash
aistudio@jupyter-885527-5559808:~/git/paddle-temp/build-cpu$ cmake .. -DPY_VERSION=3.7 -DWITH_GPU=OFF
aistudio@jupyter-885527-5559808:~/git/paddle-temp/build-cpu$ make -j$(nproc)
```

报错

```bash
aistudio@jupyter-885527-5559808:~/git/paddle-temp/build-cpu$ python -c "import paddle;paddle.utils.run_check()"
Running verify PaddlePaddle program ... 
I0309 11:56:23.336211  3929 interpretercore.cc:280] New Executor is Running.
I0309 11:56:23.833209  3929 interpreter_util.cc:591] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
/home/aistudio/.local/lib/python3.8/site-packages/paddle/distributed/spawn.py:304: UserWarning: Your model will be trained under CPUONLY mode by using GLOO,because CPUPlace is specified manually or your installed PaddlePaddle only support CPU Device.
  warnings.warn(
I0309 11:56:28.716774  4076 tcp_utils.cc:105] Retry to connect to 127.0.0.1:57751 while the server is not yet listening.
I0309 11:56:29.455873  4075 tcp_utils.cc:179] The server starts to listen on IP_ANY:57751
I0309 11:56:29.513974  4075 tcp_utils.cc:128] Successfully connected to 127.0.0.1:57751
I0309 11:56:31.717129  4076 tcp_utils.cc:128] Successfully connected to 127.0.0.1:57751
I0309 11:56:32.313839  4188 tcp_store.cc:270] receive shutdown event and so quit from MasterDaemon run loop


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1678362992 (unix time) try "date -d @1678362992" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e800000f59) received by PID 4075 (TID 0x7ff7ca630740) from PID 3929 ***]

WARNING:root:PaddlePaddle meets some problem with 2 CPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests 
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
WARNING:root:
 Original Error is: 

----------------------------------------------
Process 1 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File "/home/aistudio/.local/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 394, in _func_wrapper
    result = func(*args)
  File "/home/aistudio/.local/lib/python3.8/site-packages/paddle/utils/install_check.py", line 199, in train_for_run_parallel
    paddle.distributed.init_parallel_env()
  File "/home/aistudio/.local/lib/python3.8/site-packages/paddle/distributed/parallel.py", line 1098, in init_parallel_env
    pg = _new_process_group_impl(
  File "/home/aistudio/.local/lib/python3.8/site-packages/paddle/distributed/collective.py", line 152, in _new_process_group_impl
    pg = core.ProcessGroupGloo.create(store, rank, world_size, group_id)
AttributeError: module 'paddle.fluid.libpaddle' has no attribute 'ProcessGroupGloo'

PaddlePaddle is installed successfully ONLY for single CPU! Let's start deep learning with PaddlePaddle now.
```

### 版本&环境信息 Version & Environment Information

环境为aistudio框架开发

**Comment by yeliang2258** [comment]
没明白是什么意思，看最后的提示，是成功安装了CPU版本，在使用过程中是有什么问题吗？

**Comment by gouzil** [comment]
> 没明白是什么意思，看最后的提示，是成功安装了CPU版本，在使用过程中是有什么问题吗？

正常运行应该是这样的
```bash
aistudio@jupyter-885527-5559808:~/git/Paddle/build-cpu$  python -c "import paddle;paddle.utils.run_check()"
Running verify PaddlePaddle program ... 
I0309 15:38:55.459897  9083 interpretercore.cc:280] New Executor is Running.
I0309 15:38:55.477388  9083 interpreter_util.cc:597] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
/home/aistudio/.local/lib/python3.8/site-packages/paddle/distributed/spawn.py:304: UserWarning: Your model will be trained under CPUONLY mode by using GLOO,because CPUPlace is specified manually or your installed PaddlePaddle only support CPU Device.
  warnings.warn(
I0309 15:38:56.603699  9131 tcp_utils.cc:179] The server starts to listen on IP_ANY:41349
I0309 15:38:56.603920  9131 tcp_utils.cc:128] Successfully connected to 127.0.0.1:41349
I0309 15:38:56.604075  9133 tcp_utils.cc:128] Successfully connected to 127.0.0.1:41349
I0309 15:38:56.963019  9164 tcp_store.cc:270] receive shutdown event and so quit from MasterDaemon run loop
PaddlePaddle works well on 2 CPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

而且安装了cpu版本不应该提示检测NCCL
