### ISSUE TITLE
使用了归一化函数一直报错

### ISSUE THREAD

**Issue by fighterzhao** [PaddlePaddle/Paddle#51448]
### bug描述 Describe the Bug

Traceback (most recent call last):
  File "D:\pycharm\PyCharm Community Edition 2022.2.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\pycharm\PyCharm Community Edition 2022.2.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\project\GAN\SAR_OPT\Mygan\train.py", line 46, in <module>
    model.optimize_parameters()  # calculate loss functions, get gradients, update network weights
  File "E:\project\GAN\SAR_OPT\Mygan\model.py", line 79, in optimize_parameters
    self.forward()                   # compute fake images: G(A)
  File "E:\project\GAN\SAR_OPT\Mygan\model.py", line 49, in forward
    self.fake_B = self.netG(self.real_A)  # G(A)
  File "D:\python\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\python\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\project\GAN\SAR_OPT\Mygan\networks.py", line 73, in forward
    x2=self.down2(x1)
  File "D:\python\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\python\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\project\GAN\SAR_OPT\Mygan\networks.py", line 22, in forward
    x=self.bn(x)
  File "D:\python\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\python\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\python\lib\site-packages\paddle\nn\layer\norm.py", line 101, in forward
    return instance_norm(
  File "D:\python\lib\site-packages\paddle\nn\functional\norm.py", line 405, in instance_norm
    out, _, _ = _C_ops.instance_norm(x, weight, bias, "epsilon", eps,
OSError: (External) CUDNN error(14), CUDNN_STATUS_VERSION_MISMATCH. 
  [Hint: Please search for the error code(14) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at ../paddle/fluid/operators/instance_norm_op.cu:238)
  [operator < instance_norm > error]

**Comment by yeliang2258** [comment]
这个应该是安装问题，需要安装的PaddlePaddle版本和你的cuda、cudnn版本匹配
