### ISSUE TITLE
PaddleOCR does not work on Azure container instances

### ISSUE THREAD

**Issue by Xichen96** [PaddlePaddle/Paddle#51455]
### bug描述 Describe the Bug

PaddleOCR doesn't work on Azure container instances. Even simple init does't work. Sample code does work on dev machine and container. Container is debian:latest with the following setup:

apt install -y python3 python3-pip ffmpeg libespeak-dev

pip3 install remi pyttsx3 opencv-python paddlepaddle paddleocr

And here is the error in python command line. I can grant you access to a container instance if you want to.

Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from paddleocr import PaddleOCR, draw_ocr
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0309 17:58:54.947854  2494 default_variables.cpp:433] Fail to open /proc/self/io: No such file or directory [2]
>>> ocr = PaddleOCR(use_angle_cls=True)
[2023/03/09 17:59:29] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/root/.paddleocr/whl/det/ch/ch_PP-OCRv3_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/root/.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/usr/local/lib/python3.10/dist-packages/paddleocr/ppocr/utils/ppocr_keys_v1.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='/root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, ocr=True, recovery=False, use_pdf2docx_api=False, lang='ch', det=True, rec=True, type='ocr', ocr_version='PP-OCRv3', structure_version='PP-StructureV2')
[libprotobuf ERROR /paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/message_lite.cc:119] Can't parse message of type "paddle.framework.proto.VarType.TensorDesc" because it is missing required fields: data_type
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/paddleocr/paddleocr.py", line 523, in __init__
    super().__init__(params)
  File "/usr/local/lib/python3.10/dist-packages/paddleocr/tools/infer/predict_system.py", line 47, in __init__
    self.text_recognizer = predict_rec.TextRecognizer(args)
  File "/usr/local/lib/python3.10/dist-packages/paddleocr/tools/infer/predict_rec.py", line 120, in __init__
    utility.create_predictor(args, 'rec', logger)
  File "/usr/local/lib/python3.10/dist-packages/paddleocr/tools/infer/utility.py", line 277, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) Cannot parse tensor desc
  [Hint: Expected desc.ParseFromArray(buf.get(), size) == true, but received desc.ParseFromArray(buf.get(), size):0 != true:1.] (at /paddle/paddle/fluid/framework/tensor_util.cc:938)
  [operator < load_combine > error]

**Comment by Caozhou1995** [comment]
已反馈给相关技术人员

**Comment by Caozhou1995** [comment]
麻烦移步PaddleOCR Repo
