### ISSUE TITLE
OSError: (External) CUDA error(98), invalid device function. 

### ISSUE THREAD

**Issue by Yzgfc** [PaddlePaddle/Paddle#51574]
### bug描述 Describe the Bug

使用examples测试question_generation/unimo-text中按md文档训练时报错
train_args
```
LAUNCH INFO 2023-03-13 17:30:22,944 Pod failed
LAUNCH ERROR 2023-03-13 17:30:22,945 Container failed !!!
Container rank 0 status failed cmd ['/home/nlp/miniconda3/envs/sakura/bin/python', '-u', 'train.py', '--dataset_name=dureader_qg', '--model_name_or_path=unimo-text-1.0', '--save_dir=./unimo/finetune/checkpoints', '--output_path', './unimo/finetune/predict.txt', '--logging_steps=100', '--save_steps=500', '--epochs=20', '--batch_size=16', '--learning_rate=1e-5', '--warmup_proportion=0.02', '--weight_decay=0.01', '--max_seq_len=512', '--max_target_len=30', '--do_train', '--do_predict', '--max_dec_len=20', '--min_dec_len=3', '--num_return_sequences=1', '--template=1', '--device=gpu'] code 1 log ./unimo/finetune/log/workerlog.0 
env {'XDG_SESSION_ID': '2', 'HOSTNAME': 'jhc5-240.90', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'HISTSIZE': '1000', 'SSH_CLIENT': '180.167.34.210 2904 12598', 'CONDA_SHLVL': '3', 'PERL5LIB': '/home/nlp/perl5/lib/perl5:', 'CONDA_PROMPT_MODIFIER': '(sakura) ', 'QTDIR': '/usr/lib64/qt-3.3', 'OLDPWD': '/home/nlp/sakura/cuda', 'QTINC': '/usr/lib64/qt-3.3/include', 'PERL_MB_OPT': '--install_base /home/nlp/perl5', 'SSH_TTY': '/dev/pts/0', 'QT_GRAPHICSSYSTEM_CHECKED': '1', 'CUDA_HOME': '/usr/local/cuda', 'USER': 'nlp', 'LD_LIBRARY_PATH': '/usr/local/cuda-11.2/lib64:/usr/lib/x86_64-linux-gnu', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:', 'CONDA_EXE': '/home/nlp/miniconda3/bin/conda', '_CE_CONDA': '', 'CONDA_PREFIX_1': '/home/nlp/miniconda3', 'MAIL': '/var/spool/mail/nlp', 'PATH': '/usr/local/cuda/bin:/home/nlp/miniconda3/envs/sakura/bin:/home/nlp/miniconda3/condabin:/usr/lib64/qt-3.3/bin:/home/nlp/perl5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/nlp/.local/bin:/home/nlp/bin', 'CONDA_PREFIX_2': '/home/nlp/miniconda3/envs/sak_test', 'CONDA_PREFIX': '/home/nlp/miniconda3/envs/sakura', 'PWD': '/home/nlp/sakura/unimo-text', 'LANG': 'zh_CN.UTF-8', 'KDEDIRS': '/usr', '_CE_M': '', 'HISTCONTROL': 'ignoredups', 'SHLVL': '1', 'HOME': '/home/nlp', 'PERL_LOCAL_LIB_ROOT': ':/home/nlp/perl5', 'CONDA_PYTHON_EXE': '/home/nlp/miniconda3/bin/python', 'LOGNAME': 'nlp', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'XDG_DATA_DIRS': '/home/nlp/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share', 'SSH_CONNECTION': '180.167.34.210 2904 122.226.240.90 12598', 'CONDA_DEFAULT_ENV': 'sakura', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'XDG_RUNTIME_DIR': '/run/user/1000', 'QT_PLUGIN_PATH': '/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins', 'CUDA_ROOT': '/usr/local/cuda', 'PERL_MM_OPT': 'INSTALL_BASE=/home/nlp/perl5', '_': '/home/nlp/miniconda3/envs/sakura/bin/python', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'POD_NAME': 'xphmhg', 'PADDLE_MASTER': '122.226.240.90:42375', 'PADDLE_GLOBAL_SIZE': '1', 'PADDLE_LOCAL_SIZE': '1', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '122.226.240.90:42376', 'PADDLE_CURRENT_ENDPOINT': '122.226.240.90:42376', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '1', 'PADDLE_RANK_IN_NODE': '0', 'FLAGS_selected_gpus': '0'}
LAUNCH INFO 2023-03-13 17:30:22,945 ------------------------- ERROR LOG DETAIL -------------------------
e task the model of the checkpoint was trained on, you can already use UNIMOLMHeadModel for predictions without further training.
Epoch 1/20
Traceback (most recent call last):
  File "train.py", line 281, in <module>
    run(args)
  File "train.py", line 188, in run
    optimizer.step()
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/paddle/optimizer/adamw.py", line 578, in step
    optimize_ops = self._apply_optimize(loss=None,
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/paddle/optimizer/optimizer.py", line 1152, in _apply_optimize
    params_grads = self._grad_clip(params_grads)
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/paddle/fluid/clip.py", line 193, in __call__
    return self._dygraph_clip(params_grads)
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/paddle/fluid/clip.py", line 505, in _dygraph_clip
    sum_square = _squared_l2_norm(merge_grad)
  File "/home/nlp/miniconda3/envs/sakura/lib/python3.8/site-packages/paddle/fluid/clip.py", line 76, in _squared_l2_norm
    return _C_ops.squared_l2_norm(x)
OSError: (External) CUDA error(98), invalid device function. 
  [Hint: Please search for the error code(98) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/kernels/funcs/squared_l2_norm.h:86)
```
nvidia-smi
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:04:00.0 Off |                    0 |
| N/A   29C    P8    27W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:05:00.0 Off |                    0 |
| N/A   38C    P8    30W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 00000000:84:00.0 Off |                    0 |
| N/A   18C    P8    26W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 00000000:85:00.0 Off |                    0 |
| N/A   26C    P8    29W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
nvcc -V
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0
```

**Comment by zhengqiwen1997** [comment]
可以尝试下paddle的cuda10.2的包，10.2支持的架构比11.2低。
