### ISSUE TITLE
GPU版paddle安装校验paddle.utils.run_check()时报错：OSError和ExternalError: CUBLAS error(1)，急急急！！！

### ISSUE THREAD

**Issue by ZYNORl** [PaddlePaddle/Paddle#51592]
### bug描述 Describe the Bug

- 刚刚接触PaddleSeg，本想跑下项目，但是需要 `import paddle`，就要安装该包。
- 我是在Ubuntu 18.04下，Conda下新建的py3.7下进行的。
- 本机的环境按照[官方教程](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/conda/linux-conda.html)：CUDA：10.2，cuDNN: 7.6.5进行搭建，搭建效果如下图。
![image](https://user-images.githubusercontent.com/54138779/224716571-21d72aa9-dd63-4b26-ba98-0811a911b6c6.png)
![image](https://user-images.githubusercontent.com/54138779/224716770-766d1dd1-976f-44d8-b9ed-9fa7a96bba3d.png)
![image](https://user-images.githubusercontent.com/54138779/224717126-6e8e7159-38be-4562-b560-21822c59aec9.png)
- 可以看到，我有两张k80的显卡，但是我并没有配置NCCL进行多卡选中。
- 而且，值得注意的是，我在上述环境准备好后，只是在我的虚拟环境下按照上述教程用`conda install paddlepaddle-gpu==2.4.2 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
`命令安装了paddle，并无任何其它包的下载。
- 随后执行`import paddle`，并无异样
- 但用‘paddle.utils.run_check()’校验安装是否成功时，没有出现期待的`PaddlePaddle is installed successfully!`
- 出现了以下报错，并将`Traceback`记录如下：
```
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0313 21:10:36.411721  3853 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 3.7, Driver API Version: 10.2, Runtime API Version: 10.2
W0313 21:10:36.417307  3853 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/utils/install_check.py", line 269, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/utils/install_check.py", line 176, in _run_static_single
    fetch_list=[out.name, param_grads[1].name])
  File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1459, in run
    return_merged=return_merged)
  File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1662, in _run_impl
    return_numpy)
  File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 632, in run
    fetch_list)._move_to_list()
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/utils/install_check.py", line 159, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/utils/install_check.py", line 38, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 1915, in linear
      attrs=attrs,
    File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4046, in append_op
      attrs=kwargs.get("attrs", None),
    File "/home/lab419/anaconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2879, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUBLAS error(1). 
      [Hint: Please search for the error code(1) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/backends/gpu/gpu_resources.cc:156)
      [operator < matmul_v2 > error]
``


### 其他补充信息 Additional Supplementary Information

## **感谢回复，答主的建议将对小白十分有用。**

**Comment by zhengqiwen1997** [comment]
Tesla K80显卡为sm37架构，但是paddle不支持这个架构。建议使用sm 52 60 61 70 75 80 86的GPU进行编译。
可以参考我们GPU架构号与GPU型号的对应表：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html，进行GPU的选择。

**Comment by ZYNORl** [comment]
> Tesla K80显卡为sm37架构，但是paddle不支持这个架构。建议使用sm 52 60 61 70 75 80 86的GPU进行编译。 可以参考我们GPU架构号与GPU型号的对应表：[https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html，进行GPU的选择。](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html%EF%BC%8C%E8%BF%9B%E8%A1%8CGPU%E7%9A%84%E9%80%89%E6%8B%A9%E3%80%82)
链接打不开，呜呜呜

**Comment by zhengqiwen1997** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html

**Comment by ZYNORl** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html

![image](https://user-images.githubusercontent.com/54138779/224915006-66b9b05f-11f4-4c34-b61c-fcc37f259b19.png)
这里显示的是支持呀

**Comment by zhengqiwen1997** [comment]
这个文档还未更新，目前是已经不支持了。

**Comment by ZYNORl** [comment]
> 这个文档还未更新，目前是已经不支持了。

ok, 谢谢。

**Comment by liangwenxin** [comment]
> 这个文档还未更新，目前是已经不支持了。

你好，我也遇到了同样的问题，使用的是两块TiTan x显卡，现在还是支持吗

**Comment by minghua-123** [comment]
ExternalError: CUBLAS error(1). 
      [Hint: 'CUBLAS_STATUS_NOT_INITIALIZED'.  The cuBLAS library was not initialized. This is usually caused by the lack of a prior cublasCreate() call, an error in the CUDA Runtime API called by the cuBLAS routine, or an error in the hardware setup.  To correct: call cublasCreate() prior to the function call; and check that the hardware, an appropriate version of the driver, and the cuBLAS library are correctly installed.  ] (at ..\paddle\phi\backends\gpu\gpu_resources.cc:235)
      [operator < matmul_v2 > error]

**Comment by minghua-123** [comment]
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\fluid\platform\device\gpu\gpu_info.cc:123)

**Comment by tongcu** [comment]
similar question ：
