### ISSUE TITLE
test_sum_op failed

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5183]
One of my document-only PR https://github.com/PaddlePaddle/Paddle/pull/5177 failed at

```
[16:09:59]	170/246 Test #171: test_sum_op .................................***Failed 2.61 sec
[16:09:59]	.E
[16:09:59]	======================================================================
[16:09:59]	ERROR: test_check_output (__main__.TestSumOp)
[16:09:59]	----------------------------------------------------------------------
[16:09:59]	Traceback (most recent call last):
[16:09:59]	File "test_sum_op.py", line 17, in test_check_output
[16:09:59]	self.check_output()
[16:09:59]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 315, in check_output
[16:09:59]	self.check_output_with_place(place, atol)
[16:09:59]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 258, in check_output_with_place
[16:09:59]	feed_map = self.feed_var(inputs, place)
[16:09:59]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 218, in feed_var
[16:09:59]	tensor.set(np_value, place)
[16:09:59]	EnforceNotMet: ptr_ should not be null
[16:09:59]	Insufficient GPU memory to allocation. at [/paddle/paddle/framework/tensor.h:165]
[16:09:59]	PaddlePaddle Call Stacks:
[16:09:59]	0 0x7f570343244cp paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 572
[16:09:59]	1 0x7f570345a871p paddle::framework::Tensor::mutable_data(boost::variant<paddle::platform::GPUPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::type_index) + 2417
[16:09:59]	2 0x7f570345b3cap float* paddle::framework::Tensor::mutable_data<float>(boost::variant<paddle::platform::GPUPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>) + 90
[16:09:59]	3 0x7f570345b50cp void paddle::pybind::PyCUDATensorSetFromArray<float>(paddle::framework::Tensor&, pybind11::array_t<float, 17>, paddle::platform::GPUPlace&) + 284
[16:09:59]	4 0x7f57034469c5p void pybind11::detail::argument_loader<paddle::framework::Tensor&, pybind11::array_t<float, 17>, paddle::platform::GPUPlace&>::call_impl<void, void (*&)(paddle::framework::Tensor&, pybind11::array_t<float, 17>, paddle::platform::GPUPlace&), 0ul, 1ul, 2ul>(void (*&)(paddle::framework::Tensor&, pybind11::array_t<float, 17>, paddle::platform::GPUPlace&), pybind11::detail::index_sequence<0ul, 1ul, 2ul>) + 85
[16:09:59]	5 0x7f570344d975p void pybind11::cpp_function::initialize<void (*&)(paddle::framework::Tensor&, pybind11::array_t<float, 17>, paddle::platform::GPUPlace&), void, paddle::framework::Tensor&, pybind11::array_t<float, 17>, paddle::platform::GPUPlace&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (*&)(paddle::framework::Tensor&, pybind11::array_t<float, 17>, paddle::platform::GPUPlace&), void (*)(paddle::framework::Tensor&, pybind11::array_t<float, 17>, paddle::platform::GPUPlace&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) + 517
[16:09:59]	6 0x7f5703443724p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
[16:09:59]	7 0x4cada2p PyEval_EvalFrameEx + 28066
[16:09:59]	8 0x4c9d8fp PyEval_EvalFrameEx + 23951
[16:09:59]	9 0x4c2765p PyEval_EvalCodeEx + 597
[16:09:59]	10 0x4ca8d1p PyEval_EvalFrameEx + 26833
[16:09:59]	11 0x4c2765p PyEval_EvalCodeEx + 597
[16:09:59]	12 0x4ca099p PyEval_EvalFrameEx + 24729
[16:09:59]	13 0x4c9d8fp PyEval_EvalFrameEx + 23951
[16:09:59]	14 0x4c2765p PyEval_EvalCodeEx + 597
[16:09:59]	15 0x4de8b8p
[16:09:59]	16 0x4b0cb3p PyObject_Call + 67
[16:09:59]	17 0x4c6ad1p PyEval_EvalFrameEx + 10961
[16:09:59]	18 0x4c2765p PyEval_EvalCodeEx + 597
[16:09:59]	19 0x4de6fep
[16:09:59]	20 0x4b0cb3p PyObject_Call + 67
[16:09:59]	21 0x4f492ep
[16:09:59]	22 0x4b0cb3p PyObject_Call + 67
[16:09:59]	23 0x553187p
[16:09:59]	24 0x4b0cb3p PyObject_Call + 67
[16:09:59]	25 0x4c9fafp PyEval_EvalFrameEx + 24495
[16:09:59]	26 0x4c2765p PyEval_EvalCodeEx + 597
[16:09:59]	27 0x4de8b8p
[16:09:59]	28 0x4b0cb3p PyObject_Call + 67
[16:09:59]	29 0x4c6ad1p PyEval_EvalFrameEx + 10961
[16:09:59]	30 0x4c2765p PyEval_EvalCodeEx + 597
[16:09:59]	31 0x4de6fep
[16:09:59]	32 0x4b0cb3p PyObject_Call + 67
[16:09:59]	33 0x4f492ep
[16:09:59]	34 0x4b0cb3p PyObject_Call + 67
[16:09:59]	35 0x553187p
[16:09:59]	36 0x4b0cb3p PyObject_Call + 67
[16:09:59]	37 0x4c9fafp PyEval_EvalFrameEx + 24495
[16:09:59]	38 0x4c2765p PyEval_EvalCodeEx + 597
[16:09:59]	39 0x4de8b8p
[16:09:59]	40 0x4b0cb3p PyObject_Call + 67
[16:09:59]	41 0x4c6ad1p PyEval_EvalFrameEx + 10961
[16:09:59]	42 0x4c2765p PyEval_EvalCodeEx + 597
[16:09:59]	43 0x4de6fep
[16:09:59]	44 0x4b0cb3p PyObject_Call + 67
[16:09:59]	45 0x4f492ep
[16:09:59]	46 0x4b0cb3p PyObject_Call + 67
[16:09:59]	47 0x553187p
[16:09:59]	48 0x4b0cb3p PyObject_Call + 67
[16:09:59]	49 0x4c9fafp PyEval_EvalFrameEx + 24495
[16:09:59]	50 0x4c9d8fp PyEval_EvalFrameEx + 23951
[16:09:59]	51 0x4c9d8fp PyEval_EvalFrameEx + 23951
[16:09:59]	52 0x4c2765p PyEval_EvalCodeEx + 597
[16:09:59]	53 0x4de6fep
[16:09:59]	54 0x4b0cb3p PyObject_Call + 67
[16:09:59]	55 0x4f492ep
[16:09:59]	56 0x4b0cb3p PyObject_Call + 67
[16:09:59]	57 0x4f46a7p
[16:09:59]	58 0x4b670cp
[16:09:59]	59 0x4b0cb3p PyObject_Call + 67
[16:09:59]	60 0x4c9fafp PyEval_EvalFrameEx + 24495
[16:09:59]	61 0x4c2765p PyEval_EvalCodeEx + 597
[16:09:59]	62 0x4c2509p PyEval_EvalCode + 25
[16:09:59]	63 0x4f1defp
[16:09:59]	64 0x4ec652p PyRun_FileExFlags + 130
[16:09:59]	65 0x4eae31p PyRun_SimpleFileExFlags + 401
[16:09:59]	66 0x49e14ap Py_Main + 1674
[16:09:59]	67 0x7f5735d28830p __libc_start_main + 240
[16:09:59]	68 0x49d9d9p _start + 41
[16:09:59]	
[16:09:59]	
[16:09:59]	----------------------------------------------------------------------
[16:09:59]	Ran 2 tests in 1.477s
[16:09:59]	
[16:09:59]	FAILED (errors=1)
```

**Comment by wangkuiyi** [comment]
I see `[16:09:59]	Insufficient GPU memory to allocation. at [/paddle/paddle/framework/tensor.h:165]`

Could be someone is using our CI server for experiments.

**Comment by wangkuiyi** [comment]
```
Wang Helin
@Wang Yi  I double checked the GPU memory usage on that machine, I think it's because concurrent GPU tests take more memory than 11G, and caused out-of-memory

Wang Helin
We can either reduce the ctest concurrent count, or reduce the unit test memory utilization, I think unit test should not take that much memory (we can always use a smaller network).

```

**Comment by QiJune** [comment]
#5193 will help after we set `FLAGS_fraction_of_gpu_memory_to_use=0.20` env variable for each unittest.
