### ISSUE TITLE
multinomial算子不支持FP16

### ISSUE THREAD

**Issue by linjieccc** [PaddlePaddle/Paddle#51852]
### bug描述 Describe the Bug

FP16下使用paddle.multinomial报错：

```python
import paddle

paddle.set_default_dtype("float16")

x = paddle.to_tensor([0.5535528, 0.20714243, 0.01162981, 0.51577556])

paddle.multinomial(x)
```

Traceback:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    paddle.multinomial(x)
  File "/usr/local/lib/python3.7/dist-packages/paddle/tensor/random.py", line 188, in multinomial
    return _C_ops.multinomial(x, num_samples, replacement)
RuntimeError: (NotFound) The kernel with key (GPU, Undefined(AnyLayout), float16) of kernel `multinomial` is not registered and fail to fallback to CPU one. Selected wrong DataType `float16`. Paddle support following DataTypes: float64, float32.
  [Hint: Expected kernel_iter != iter->second.end(), but received kernel_iter == iter->second.end().] (at /paddle/paddle/phi/core/kernel_factory.cc:258)
```

**Comment by wuyefeilin** [comment]
目前框架正对一批算子进行低精度的支持哈
