### ISSUE TITLE
运行测试时出现：ExternalError: CUBLAS error(50)

### ISSUE THREAD

**Issue by MK0820** [PaddlePaddle/Paddle#51917]
### 问题描述 Issue Description

```python
In [1]: import paddle

In [2]: paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0321 16:35:24.683157 84329 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.7, Runtime API Version: 11.7
W0321 16:35:24.687981 84329 gpu_resources.cc:91] device: 0, cuDNN Version: 8.7.

You are running using the stub version of cublas

You are running using the stub version of cublas

You are running using the stub version of cublas

You are running using the stub version of cublas

You are running using the stub version of cublas
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[2], line 1
----> 1 paddle.utils.run_check()

File ~/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/utils/install_check.py:269, in run_check()
    266     device_list = paddle.static.cpu_places(device_count=2)
    267 device_count = len(device_list)
--> 269 _run_static_single(use_cuda, use_xpu, use_npu)
    270 _run_dygraph_single(use_cuda, use_xpu, use_npu)
    271 print("PaddlePaddle works well on 1 {}.".format(device_str))

File ~/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/utils/install_check.py:174, in _run_static_single(use_cuda, use_xpu, use_npu)
    172     exe = paddle.static.Executor(place)
    173     exe.run(startup_prog)
--> 174     exe.run(train_prog,
    175             feed={input.name: _prepare_data(1)},
    176             fetch_list=[out.name, param_grads[1].name])
    177 paddle.disable_static()

File ~/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/fluid/executor.py:1463, in Executor.run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1461     return res
   1462 except Exception as e:
-> 1463     six.reraise(*sys.exc_info())

File ~/anaconda3/envs/pp/lib/python3.9/site-packages/six.py:719, in reraise(tp, value, tb)
    717     if value.__traceback__ is not tb:
    718         raise value.with_traceback(tb)
--> 719     raise value
    720 finally:
    721     value = None

File ~/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/fluid/executor.py:1450, in Executor.run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1447     self._log_force_set_program_cache(use_program_cache)
   1449 try:
-> 1450     res = self._run_impl(program=program,
   1451                          feed=feed,
   1452                          fetch_list=fetch_list,
   1453                          feed_var_name=feed_var_name,
   1454                          fetch_var_name=fetch_var_name,
   1455                          scope=scope,
   1456                          return_numpy=return_numpy,
   1457                          use_program_cache=use_program_cache,
   1458                          use_prune=use_prune,
   1459                          return_merged=return_merged)
   1460     core.update_autotune_status()
   1461     return res

File ~/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/fluid/executor.py:1661, in Executor._run_impl(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, return_merged, use_prune)
   1658         else:
   1659             tensor._copy_from(cpu_tensor, self.place)
-> 1661     return new_exe.run(scope, list(feed.keys()), fetch_list,
   1662                        return_numpy)
   1664 compiled = isinstance(program, compiler.CompiledProgram)
   1666 # Check if fluid.data() variable no feed data

File ~/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/fluid/executor.py:631, in _StandaloneExecutor.run(self, scope, feed_names, fetch_list, return_numpy)
    620 """
    621 Args:
    622     feed_names(list): This parameter represents the input names of the model.
   (...)
    627         the type of the return value is a list of :code:`LoDTensor`. The default is True.
    628 """
    629 fetch_list = self._check_fetch(fetch_list)
--> 631 tensors = self._new_exe.run(scope, feed_names,
    632                             fetch_list)._move_to_list()
    633 if return_numpy:
    634     return as_numpy(tensors, copy=True)

OSError: In user code:

    File "/home/my/anaconda3/envs/pp/bin/ipython", line 8, in <module>
      sys.exit(start_ipython())
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/IPython/__init__.py", line 124, in start_ipython
      return launch_new_instance(argv=argv, **kwargs)
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/traitlets/config/application.py", line 1043, in launch_instance
      app.start()
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/IPython/terminal/ipapp.py", line 318, in start
      self.shell.mainloop()
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 887, in mainloop
      self.interact()
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py", line 880, in interact
      self.run_cell(code, store_history=True)
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2961, in run_cell
      result = self._run_cell(
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3016, in _run_cell
      result = runner(coro)
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3221, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3400, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-2-afc005eaa74e>", line 1, in <module>
      paddle.utils.run_check()
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/utils/install_check.py", line 159, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/utils/install_check.py", line 38, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/nn/functional/common.py", line 1911, in linear
      helper.append_op(
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/fluid/framework.py", line 4040, in append_op
      op = Operator(
    File "/home/my/anaconda3/envs/pp/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2879, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUBLAS error(50). 
      [Hint: Please search for the error code(50) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/backends/gpu/gpu_resources.cc:156)
      [operator < matmul_v2 > error]
```

### 版本&环境信息 Version & Environment Information

Paddle: paddlepaddle-gpu 2.4.2.post117

OS: Ubuntu 20.04.5 LTS
python: 3.9.0
GCC: 9.4.0

GPU: NVIDIA A100 80G
CUDA: 11.7
cudnn: 8.7
driver:  515.65.01
cuBLAS: 11.10.3.66

**Comment by MK0820** [comment]
在 https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t 并没有找到error code 50相关内容。

**Comment by zhengqiwen1997** [comment]
你好，可以用nvcc -V看下cuda版本是不是11.7；若暂时看不出问题，请尝试用官网的docker方法进行安装。

**Comment by Cccccc-c** [comment]
me.too

Paddle: paddlepaddle-gpu 2.4.2.post117

OS: Ubuntu 22.04.5 LTS
Python 3.10.6
gcc version 11.3.0 

GPU: NVIDIA 3090
CUDA: 11.7
cudnn: cudnn-linux-x86_64-8.9.2.26_cuda11-archive
 Driver Version: 530.30.02
libcublas.so.11.10.3.66

**Comment by zhengqiwen1997** [comment]
cuda11.7 请配合 cudnn8.4 使用。
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html

**Comment by anyUesr** [comment]
请问一下你解决这个问题了吗？我也有相同的问题

**Comment by RymUYeon** [comment]
你好 该问题解决了吗？我遇到了相同的问题。
