### ISSUE TITLE
paddle.vision.datasets.Cifar10接口数据路径问题

### ISSUE THREAD

**Issue by alixiu** [PaddlePaddle/Paddle#52095]
### bug描述 Describe the Bug

# # paddlepaddle 2.4.1
import paddle.vision.datasets as dset
import paddle.vision.transforms as transforms

mean = [x / 255 for x in [125.3, 123.0, 113.9]]
std = [x / 255 for x in [63.0, 62.1, 66.7]]

test_data = dset.Cifar10('./data/cifar.python/cifar-10-batches-py/', mode='test', transform=test_transform, download=True)

执行后报错：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maxiu/anaconda3/envs/paddle-cpu/lib/python3.10/site-packages/paddle/vision/datasets/cifar.py", line 146, in __init__
    self._load_data()
  File "/home/maxiu/anaconda3/envs/paddle-cpu/lib/python3.10/site-packages/paddle/vision/datasets/cifar.py", line 157, in _load_data
    with tarfile.open(self.data_file, mode='r') as f:
  File "/home/maxiu/anaconda3/envs/paddle-cpu/lib/python3.10/tarfile.py", line 1632, in open
    return func(name, "r", fileobj, **kwargs)
  File "/home/maxiu/anaconda3/envs/paddle-cpu/lib/python3.10/tarfile.py", line 1698, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/home/maxiu/anaconda3/envs/paddle-cpu/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
IsADirectoryError: [Errno 21] Is a directory: './data/cifar.python/cifar-10-batches-py/'

./data/cifar.python/cifar-10-batches-py/目录下存在cifar10的测试数据和训练数据
$ ls ./data/cifar.python/cifar-10-batches-py/
$batches.meta  data_batch_1  data_batch_2  data_batch_3  data_batch_4  data_batch_5  readme.html  test_batch

**Comment by FeixLiu** [comment]
确认下指定目录 `./data/cifar.python/cifar-10-batches-py/` 这个目录是否存在。

**Comment by alixiu** [comment]
目录是存在的

**Comment by alixiu** [comment]
> 确认下指定目录 `./data/cifar.python/cifar-10-batches-py/` 这个目录是否存在。

如果目录不存在也应该报错：找不到目录吧

**Comment by FeixLiu** [comment]
报错信息是这个路径不是一个目录 `IsADirectoryError`。可以确认下该路径是否的确是一个 directory

**Comment by alixiu** [comment]
> 报错信息是这个路径不是一个目录 `IsADirectoryError`。可以确认下该路径是否的确是一个 directory

是一个目录
$ os.path.isdir('/home/maxiu/Paddle-EE/paddle_ee_pruning/data/cifar.python/cifar-10-batches-py')
$ True
$ test_data = dset.Cifar10('/home/maxiu/Paddle-EE/paddle_ee_pruning/data/cifar.python/cifar-10-batches-py/', mode='test', transform=test_transform, download=True)
仍然报错：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maxiu/anaconda3/envs/paddle-cpu/lib/python3.10/site-packages/paddle/vision/datasets/cifar.py", line 146, in __init__
    self._load_data()
  File "/home/maxiu/anaconda3/envs/paddle-cpu/lib/python3.10/site-packages/paddle/vision/datasets/cifar.py", line 157, in _load_data
    with tarfile.open(self.data_file, mode='r') as f:
  File "/home/maxiu/anaconda3/envs/paddle-cpu/lib/python3.10/tarfile.py", line 1632, in open
    return func(name, "r", fileobj, **kwargs)
  File "/home/maxiu/anaconda3/envs/paddle-cpu/lib/python3.10/tarfile.py", line 1698, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/home/maxiu/anaconda3/envs/paddle-cpu/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
IsADirectoryError: [Errno 21] Is a directory: '/home/maxiu/Paddle-EE/paddle_ee_pruning/data/cifar.python/cifar-10-batches-py/'

**Comment by FeixLiu** [comment]
这个是gzip的错，要打开一个gzip的包，但是打开了一个文件夹。api应该是需要一个gzip包的路径。

**Comment by alixiu** [comment]
我明白了，这里要传入的路径是数据集压缩包的路径，压缩包必须是gzip格式，比如/data/cifar10/cifar-10-python.tar.gz，而不是一个目录，如果方便的话，还请在接口参数中说明这一点

**Comment by luotao1** [comment]
@alixiu 欢迎提一个PR增强下这个接口说明～
