### ISSUE TITLE
PaddleSeg套件下尝试本地windows推理vnet模型报RuntimeError

### ISSUE THREAD

**Issue by Arthus666** [PaddlePaddle/Paddle#52146]
### bug描述 Describe the Bug

使用paddle-cpu推理vnet模型

![image](https://user-images.githubusercontent.com/76039868/227724441-44a49af7-b8cc-4b3e-91d4-9286106f1c77.png)

```
D:\Anaconda\python.exe D:/Python/Vnet/main.py
D:\Python\Vnet\PaddleSeg\contrib\MedicalSeg\deploy\python\..\..\tools\preprocess_utils\preprocessing.py:18: DeprecationWarning: Please use `map_coordinates` from the `scipy.ndimage` namespace, the `scipy.ndimage.interpolation` namespace is deprecated.
  from scipy.ndimage.interpolation import map_coordinates
D:\Python\Vnet\PaddleSeg\contrib\MedicalSeg\deploy\python\..\..\medicalseg\transforms\functional.py:23: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter, gaussian_gradient_magnitude
D:\Python\Vnet\PaddleSeg\contrib\MedicalSeg\deploy\python\..\..\medicalseg\transforms\functional.py:23: DeprecationWarning: Please use `gaussian_gradient_magnitude` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter, gaussian_gradient_magnitude
2023-03-25 22:19:52 [INFO]	Use CPU
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [matmul_v2_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]e[0m
e[32m--- Running IR pass [matmul_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [constant_folding_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0325 22:19:52.534404 54760 memory_optimize_pass.cc:219] Cluster name : conv3d_34.tmp_1  size: 1024
I0325 22:19:52.534404 54760 memory_optimize_pass.cc:219] Cluster name : prelu_7.tmp_0  size: 256
I0325 22:19:52.534404 54760 memory_optimize_pass.cc:219] Cluster name : sync_batch_norm_15.tmp_0  size: 1024
I0325 22:19:52.534404 54760 memory_optimize_pass.cc:219] Cluster name : concat_0.tmp_0  size: 1024
I0325 22:19:52.534404 54760 memory_optimize_pass.cc:219] Cluster name : conv3d_35.tmp_1  size: 1024
I0325 22:19:52.534404 54760 memory_optimize_pass.cc:219] Cluster name : sync_batch_norm_14.tmp_0  size: 1024
I0325 22:19:52.534404 54760 memory_optimize_pass.cc:219] Cluster name : prelu_12.tmp_0  size: 512
I0325 22:19:52.534404 54760 memory_optimize_pass.cc:219] Cluster name : prelu_3.tmp_0  size: 128
I0325 22:19:52.534404 54760 memory_optimize_pass.cc:219] Cluster name : prelu_0.tmp_0  size: 64
I0325 22:19:52.534404 54760 memory_optimize_pass.cc:219] Cluster name : x  size: 4
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0325 22:19:52.596418 54760 analysis_predictor.cc:1314] ======= optimize end =======
I0325 22:19:52.596418 54760 naive_executor.cc:110] ---  skip [feed], feed -> x
Traceback (most recent call last):
  File "D:\Python\Vnet\PaddleSeg\contrib\MedicalSeg\deploy\python\competition_infer.py", line 586, in <module>
    main(args)
  File "D:\Python\Vnet\PaddleSeg\contrib\MedicalSeg\deploy\python\competition_infer.py", line 572, in main
    predictor = Predictor(args)
  File "D:\Python\Vnet\PaddleSeg\contrib\MedicalSeg\deploy\python\competition_infer.py", line 298, in __init__
    self.predictor = create_predictor(self.pred_cfg)
RuntimeError: (NotFound) Operator (sync_batch_norm) is not registered.
  [Hint: op_info_ptr should not be null.] (at ..\paddle/fluid/framework/op_info.h:156)


Process finished with exit code 0
```

**Comment by shiyutang** [comment]
你好，建议去除下面所示的syncbn后重新进行导出和infer：
https://github.com/PaddlePaddle/PaddleSeg/blob/41efd46667c05a13cae519f93ba42d0ca5a24043/contrib/MedicalSeg/medicalseg/cvlibs/config.py#L322
