### ISSUE TITLE
ImportError: cannot import name '_switch_declarative_mode_guard_' from 'paddle.fluid.dygraph.base' 

### ISSUE THREAD

**Issue by Liqq1** [PaddlePaddle/Paddle#52177]
### bug描述 Describe the Bug

在运行paddle项目(python train.py)的过程中，我遇到了如下错误.不知道是否和静态图/动态图有关
可通过如下链接达到项目：https://aistudio.baidu.com/bd-gpu-02/user/725530/5810187/notebooks/5810187.ipynb

```/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from paddleslim.dygraph.quant import QAT
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/__init__.py", line 17, in <module>
    from paddleslim import prune
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/__init__.py", line 16, in <module>
    from .pruner import *
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/prune/pruner.py", line 20, in <module>
    from ..core import VarWrapper, OpWrapper, GraphWrapper
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/__init__.py", line 19, in <module>
    from ..core import dygraph
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddleslim/core/dygraph.py", line 8, in <module>
    from paddle.fluid.dygraph.base import program_desc_tracing_guard, _switch_declarative_mode_guard_
ImportError: cannot import name '_switch_declarative_mode_guard_' from 'paddle.fluid.dygraph.base' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py)```


### 其他补充信息 Additional Supplementary Information

_No response_

**Comment by AnnaTrainingG** [comment]
请问具体报错的paddle版本是什么呢？ 建议使用Paddle最新的安装包，或者nightly安装包：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by Liqq1** [comment]
> 请问具体报错的paddle版本是什么呢？ 建议使用Paddle最新的安装包，或者nightly安装包：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

我的环境是：paddle提供的-V100 16GB，cuda版本是11.2
我按照如下语句安装了paddle：
`python -m pip install paddlepaddle-gpu==2.4.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`

但在执行python train.py时，出现如下错误
```
Error: Can not import paddle core while this file exists: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "train.py", line 1, in <module>
    import paddle
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/core.py", line 338, in <module>
    raise e
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

貌似最开始的issue是paddleslim带来的错误;而现在还没有走到paddleslim这一步就报错了。paddleslim我使用是如下版本：
`Successfully installed paddleslim-2.4.1 swig-4.1.1`

**Comment by AnnaTrainingG** [comment]
这种通常是Paddle安装包安装不完全导致的，可以直接uninstall 然后在重新安装，可以尝试安装Paddle最新的安装包

**Comment by Liqq1** [comment]
> 这种通常是Paddle安装包安装不完全导致的，可以直接uninstall 然后在重新安装，可以尝试安装Paddle最新的安装包

我uninstall 然后在重新安装后，还是相同的报错。
请问最新版本指的是哪一个呀？

**Comment by AnnaTrainingG** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html 可以安装一下dev版本

**Comment by Liqq1** [comment]
请问具体是哪一个命令？不太了解dev版本。 另外这个报错好像是paddleslim引起的，import paddle是没有问题的，还需要去修改paddle的版本吗？

**Comment by Liqq1** [comment]
请问具体是哪一个命令？不太了解dev版本。 另外这个报错好像是paddleslim引起的，import paddle是没有问题的，还需要去修改paddle的版本吗？

**Comment by Liqq1** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html 可以安装一下dev版本

我把paddleslim从最新版本降低到2.0.0可以运行了。可能新版本中需要import from的函数名称改变了；

**Comment by AnnaTrainingG** [comment]
嗯嗯 好的，问题解决就好。应该是版本升级过程中名称改变导致的。
