### ISSUE TITLE
运行时出现OSError: (External) CUDNN error(1), CUDNN_STATUS_NOT_INITIALIZED.错误

### ISSUE THREAD

**Issue by dwyzzy** [PaddlePaddle/Paddle#52181]
### 问题描述 Please describe your issue

参考https://github.com/PaddlePaddle/Paddle/issues/34938#issuecomment-899450221  中的测试,没有问题:

```
Python 3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> paddle.device.get_cudnn_version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'paddle' is not defined
>>> import paddle
>>> paddle.device.get_cudnn_version()
8101
>>> a = np.zeros([3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'np' is not defined
>>> import numpy as np
>>> a = np.zeros([3])
>>> pd_a = paddle.to_tensor(a)
>>> pd_a
Tensor(shape=[3], dtype=float64, place=Place(gpu:0), stop_gradient=True,
       [0., 0., 0.])
>>> emb = paddle.create_parameter([3, 3], dtype='float32')
W0327 14:45:26.357821 13021 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0327 14:45:26.357913 13021 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
>>> emb
Parameter containing:
Tensor(shape=[3, 3], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [[ 0.30249882, -0.52442175, -0.95941085],
        [ 0.26945496,  0.81000209,  0.03986478],
        [ 0.17552829,  0.68394887,  0.11605537]])
```

但是实际运行的时候会报错:
```
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddlenlp/trainer/trainer.py", line 679, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddlenlp/trainer/trainer.py", line 1369, in training_step
    loss = self.compute_loss(model, inputs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddlenlp/trainer/trainer.py", line 1331, in compute_loss
    outputs = model(**inputs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "run_train.py", line 54, in forward
    outputs = self.glm(input_ids, position_ids, attention_mask, return_dict=return_dict)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddlenlp/transformers/glm/modeling.py", line 680, in forward
    outputs = self.transformer(word_embeddings, position_ids, attention_mask, cache, return_dict)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddlenlp/transformers/glm/modeling.py", line 363, in forward
    hidden_states = self.recompute_training(layer, hidden_states, attention_mask, cache=mem_i)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddlenlp/transformers/glm/modeling.py", line 303, in recompute_training
    hidden_states = recompute(create_custom_forward(layer_module), hidden_states, ltor_mask, cache)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddle/distributed/fleet/utils/__init__.py", line 129, in recompute
    return fleet.recompute.recompute(function, *args, **kwargs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddle/distributed/fleet/recompute/recompute.py", line 503, in recompute
    return RecomputeFunction.apply(function, preserve, *args, **kwargs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddle/distributed/fleet/recompute/recompute.py", line 299, in forward
    outputs = run_function(*args, **kwargs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddlenlp/transformers/glm/modeling.py", line 299, in custom_forward
    return module(*inputs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddlenlp/transformers/glm/modeling.py", line 213, in forward
    attention_output = self.attention(layernorm_output, ltor_mask, cache)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddlenlp/transformers/glm/modeling.py", line 178, in forward
    attention_probs = F.softmax(attention_scores, axis=-1)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddle/nn/functional/activation.py", line 1142, in softmax
    return _C_ops.softmax(outs_cast, axis)
OSError: (External) CUDNN error(1), CUDNN_STATUS_NOT_INITIALIZED.
  [Hint: Please search for the error code(1) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/backends/gpu/gpu_resources.cc:227)
```

环境信息
```
Paddle version: 2.4.2
Paddle With CUDA: True

OS: ubuntu 18.04
GCC version: (GCC) 8.2.0
Clang version: 3.8.0 (tags/RELEASE_380/final)
CMake version: version 3.16.0
Libc version: glibc 2.27
Python version: 3.8.16

CUDA version: 10.2.89
cuDNN version: 8.1.1
Nvidia driver version: 440.33.01
Nvidia driver List:
GPU 0: Tesla P40
GPU 1: Tesla P40
GPU 2: Tesla P40
GPU 3: Tesla P40
GPU 4: Tesla P40
GPU 5: Tesla P40
GPU 6: Tesla P40
GPU 7: Tesla P40
```

**Comment by dwyzzy** [comment]
问题可在调用F.softmax的时候稳定复现

```
Python 3.8.16 (default, Mar  2 2023, 03:21:46)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> import paddle.nn.functional as F
>>> a = paddle.to_tensor([0.1, 0.2, 0.7])
>>> a
Tensor(shape=[3], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [0.10000000, 0.20000000, 0.69999999])
>>> F.softmax(a)

W0327 15:14:02.087484 13770 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0327 15:14:02.092368 13770 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/paddle/nn/functional/activation.py", line 1142, in softmax
    return _C_ops.softmax(outs_cast, axis)
OSError: (External) CUDNN error(1), CUDNN_STATUS_NOT_INITIALIZED.
  [Hint: Please search for the error code(1) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/backends/gpu/gpu_resources.cc:227)
```

**Comment by AnnaTrainingG** [comment]
你好，可以尝试拉取paddle最新的安装包进行测试，目前我本地验证的是运行ok的。https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html

**Comment by StanfordAgula** [comment]
> 你好，可以尝试拉取paddle最新的安装包进行测试，目前我本地验证的是运行ok的。https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html

网址中所有版本均尝试一遍，还是报楼主的错误。

**Comment by kaixin-bai** [comment]
这个报错有后续更新吗？

**Comment by jimmyflycv** [comment]
i just met the same error here when running paddleocr demo.

**Comment by hello2mao** [comment]
+1

**Comment by StanfordAgula** [comment]
paddlespeech版本多换些试试 我折腾了13个 找到一个合适的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hongbin Mao ***@***.***&gt;
发送时间: 2023年7月17日 17:35
收件人: PaddlePaddle/Paddle ***@***.***&gt;
抄送: StanfordAgula ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [PaddlePaddle/Paddle] 运行时出现OSError: (External) CUDNN error(1), CUDNN_STATUS_NOT_INITIALIZED.错误 (Issue #52181)





 
+1

**Comment by skysbird** [comment]
兼容性差的可以
