### ISSUE TITLE
模型训练时优化器报类型错误

### ISSUE THREAD

**Issue by censhallwe** [PaddlePaddle/Paddle#52278]
### 问题描述 Please describe your issue

我在自己的模型剪枝完之后准备重训练，但是一直提示我类型错误，但我看了一下模型参数、传入的张量、损失等等，都是float32-gpu类型，不知道是哪里不对了，想查文档但是查不到9和10代表的什么数据类型
报错信息如下：
Traceback (most recent call last):
  File "prune_accsr.py", line 553, in <module>
    main(0.1)
  File "prune_accsr.py", line 540, in main
    optim.step()
  File "/home/ubuntu/anaconda3/envs/accmpeg2/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/anaconda3/envs/accmpeg2/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/accmpeg2/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/anaconda3/envs/accmpeg2/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/accmpeg2/lib/python3.7/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/accmpeg2/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 550, in step
    param_group_idx=0,
  File "/home/ubuntu/anaconda3/envs/accmpeg2/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 1167, in _apply_optimize
    params_grads, param_group_idx=param_group_idx
  File "/home/ubuntu/anaconda3/envs/accmpeg2/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 948, in _create_optimization_pass
    target_block, param_and_grad
  File "/home/ubuntu/anaconda3/envs/accmpeg2/lib/python3.7/site-packages/paddle/optimizer/adam.py", line 398, in _append_optimize_op
    False,
ValueError: (InvalidArgument) The type of data we are trying to retrieve does not match the type of data currently contained in the container.
  [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():9 != paddle::experimental::CppTypeToDataType<T>::Type():10.] (at /paddle/paddle/phi/core/dense_tensor.cc:143)
训练部分代码如下：
    print("Start to retrain model")
    losses = []
    epoches = 1000
    model.train()
    print(model.parameters())
    optim = paddle.optimizer.Adam(learning_rate=0.001, parameters=model.parameters())
    for epoch in range(epoches):
        for i in range(len(my_dataset)):
            image, label = my_dataset[i]
            out = model(image)
            out = paddle.nn.functional.softmax(out, axis=1)[0,1:2,:,:]
            label = label[0,:,:,:]
            loss = paddle.nn.functional.cross_entropy(paddle.transpose(out, perm=[1,2,0]), paddle.transpose(label,perm=[1,2,0]), soft_label=True, use_softmax=False)
            loss.backward()
            if i%500==0:
                losses.append(loss.numpy())
                print("epoch:{}, batch_id: {}, loss is: {}".format(epoch, i, loss.numpy()))
            optim.step()
            optim.clear_grad()

**Comment by GuoxiaWang** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/16953187/228448276-7f53c2e5-ac5f-4a60-bb08-d6176fb00e25.png">


9 表示 paddle.int64
10 表示 paddle.float32

**Comment by censhallwe** [comment]
> <img alt="image" width="665" src="https://user-images.githubusercontent.com/16953187/228448276-7f53c2e5-ac5f-4a60-bb08-d6176fb00e25.png">
> 
> 9 表示 paddle.int64 10 表示 paddle.float32

感谢您的解答。我再去想想看是哪里传入了int64类型的数据，我之前看了的都是float32类型的。您有什么见解吗？是这个Adam的step()导致产生了int64类型数据吗？如果您有思路的话麻烦告诉我，感谢。

**Comment by GuoxiaWang** [comment]
主要是看看参数类型，遍历出来，全部打印一下一下类型

**Comment by censhallwe** [comment]
> 主要是看看参数类型，遍历出来，全部打印一下一下类型

感谢，辛苦了
