### ISSUE TITLE
ARMV8版paddle编译完成后在安装paddlenlp使用"from paddlenlp import Taskflow"时,报错"ModuleNotFoundError: No module named 'paddle.fluid.layers.utils"

### ISSUE THREAD

**Issue by AlexZssss** [PaddlePaddle/Paddle#52326]
### 请提出你的问题 Please ask your question

1.按照官网编译ARMV8架构paddle成功后，执行“paddle.utils.run_check()” 显示success，未报错
`
(base) [root@test001 dist]# python
Python 3.7.16 (default, Jan 17 2023, 15:51:26) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
I0329 11:42:35.902480 2357129 interpretercore.cc:282] New Executor is Running.
I0329 11:42:35.911159 2357129 interpreter_util.cc:559] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
`
2.在pip 安装 paddenlp后，导入`>>> from paddlenlp import Taskflow`时，报错没有"utils"类
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.7/site-packages/paddlenlp/__init__.py", line 24, in <module>
    from . import data
  File "/root/miniconda3/lib/python3.7/site-packages/paddlenlp/data/__init__.py", line 16, in <module>
    from .data_collator import *
  File "/root/miniconda3/lib/python3.7/site-packages/paddlenlp/data/data_collator.py", line 23, in <module>
    from ..transformers.tokenizer_utils_base import BatchEncoding, PretrainedTokenizerBase, PaddingStrategy
  File "/root/miniconda3/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py", line 15, in <module>
    from .model_utils import PretrainedModel, register_base_model
  File "/root/miniconda3/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py", line 33, in <module>
    from .generation_utils import GenerationMixin
  File "/root/miniconda3/lib/python3.7/site-packages/paddlenlp/transformers/generation_utils.py", line 24, in <module>
    from paddle.fluid.layers.utils import map_structure
ModuleNotFoundError: No module named 'paddle.fluid.layers.utils'
`
3.查看pip安装的paddle包发现和x86的有区别
arm版
![image](https://user-images.githubusercontent.com/129347663/228706960-b77b04ec-0ced-44ca-bc34-f49ad5f6a522.png)
x86版
![image](https://user-images.githubusercontent.com/129347663/228708192-e497798d-f9fb-461d-8b0f-a7e7fada96ba.png)
最后：请问这是我编译的问题吗？

**Comment by ronny1996** [comment]
你好，paddle.fluid.layers.utils 已删除，可以尝试使用最新的paddlenlp或者在paddlenlp repo提issue

**Comment by AlexZssss** [comment]
> 你好，paddle.fluid.layers.utils 已删除，可以尝试使用最新的paddlenlp或者在paddlenlp repo提issue
好的，谢谢您

**Comment by w5688414** [comment]
I met the same problem:

```
rom paddle.fluid.layers.utils import map_structure
ModuleNotFoundError: No module named 'paddle.fluid.layers.utils'
```

then upgrade paddlenlp to 2.5.2 solved my problem
