### ISSUE TITLE
Can not import paddle core while this file exists: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by llagin** [PaddlePaddle/Paddle#52383]
### bug描述 Describe the Bug

MedicalSeg-nnUNet使用教程中遇到的问题。
环境：PaddlePaddle 2.3.2
           Python: 3.7.4
代码：
# 3D-UNet训练
%cd ~/PaddleSeg/contrib/MedicalSeg/
!python train.py --config configs/nnunet/msd_lung/nnunet_3d_fullres_msd_lung_fold0.yml --log_iters 20 --precision fp16 --nnunet --save_dir output/3d_unet/fold0 --save_interval 1000 --use_vdl
详细报错信息
/home/aistudio/PaddleSeg/contrib/MedicalSeg
Error: Can not import paddle core while this file exists: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    import paddle
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/core.py", line 338, in <module>
    raise e
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

**Comment by KimBioInfoStudio** [comment]
> ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

你有GPU卡吗？装CUDA了吗？ 如果没有，先尝试CPU版本

**Comment by llagin** [comment]
thanks，bug解决了，是gpu的问题

**Comment by 1chengxuxiaobai1** [comment]
您好，怎么解决的呢，我也有一样的问题
