### ISSUE TITLE
Error: Can not import paddle core while this file exists: c:\users\caijiamin\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\libpaddle.pyd

### ISSUE THREAD

**Issue by PassionateBro** [PaddlePaddle/Paddle#52410]
### 请提出你的问题 Please ask your question

我在进行 quick start 中执行  paddleocr --image_dir imgs_en/img_12.jpg --rec false 等尝试测试官图的时候，报错如下：
`Error: Can not import paddle core while this file exists: c:\users\caijiamin\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\libpaddle.pyd
Traceback (most recent call last):
  File "c:\users\caijiamin\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\caijiamin\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\caijiamin\AppData\Local\Programs\Python\Python38\Scripts\paddleocr.exe\__main__.py", line 4, in <module>
  File "c:\users\caijiamin\appdata\local\programs\python\python38\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "c:\users\caijiamin\appdata\local\programs\python\python38\lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
  File "c:\users\caijiamin\appdata\local\programs\python\python38\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "c:\users\caijiamin\appdata\local\programs\python\python38\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "c:\users\caijiamin\appdata\local\programs\python\python38\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "c:\users\caijiamin\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "c:\users\caijiamin\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\framework.py", line 37, in <module>
    from . import core
  File "c:\users\caijiamin\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\core.py", line 338, in <module>
    raise e
  File "c:\users\caijiamin\appdata\local\programs\python\python38\lib\site-packages\paddle\fluid\core.py", line 274, in <module>
    from . import libpaddle
ImportError: DLL load failed while importing libpaddle: ▒Ҳ▒▒▒ָ▒▒▒▒ģ▒顣
`
py version: 3.8.5
PaddlePaddle == 2.4.2
windows 环境
求赐教

**Comment by CtfGo** [comment]
@PassionateBro 你好，可以验证一下paddle安装是否有问题 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html#sanyanzhenganzhuang
```
import paddle
paddle.utils.run_check()
```

**Comment by PassionateBro** [comment]
我执行import paddle时，抛出了同样的错误
`>>> import paddle
Error: Can not import paddle core while this file exists: C:\Users\caijiamin\AppData\Local\Programs\Python\Python38\lib\site-packages\paddle\fluid\libpaddle.pyd`

**Comment by PassionateBro** [comment]
> @PassionateBro 你好，可以验证一下paddle安装是否有问题 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html#sanyanzhenganzhuang
> 
> ```
> import paddle
> paddle.utils.run_check()
> ```

**Comment by jiayaozhang** [comment]
I got the same error 

![image](https://github.com/PaddlePaddle/Paddle/assets/38579506/29bbc1af-933f-4ac6-be63-ed0dae4d205d)


And when I try 

```python
import paddle
```

shows the below error

![image](https://github.com/PaddlePaddle/Paddle/assets/38579506/e43574ce-1b83-40f2-94af-eafff912ef0c)

How to fix then? Do I need to uninstall paddlepaddle and reinstall again?

Nvidia 4090 with i9-13900k
