### ISSUE TITLE
The gradient check of the CRF operator fails after merging the latest dev branch.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#5250]
The gradient check of the CRF operator fails after I only `git merge develop`. (The gradient check success before merging the develop.) 

I found many operators have been removed from the gradient checks due to some changes in the unittest framework.

```text
248/253 Test #253: test_linear_chain_crf_op ....................***Failed 3.22 sec
[19:27:21]	FF.
[19:27:21]	======================================================================
[19:27:21]	FAIL: test_check_grad (__main__.TestLinearChainCrfOp)
[19:27:21]	----------------------------------------------------------------------
[19:27:21]	Traceback (most recent call last):
[19:27:21]	File "test_linear_chain_crf_op.py", line 134, in test_check_grad
[19:27:21]	self.check_grad(["Emission", "Transition"], "LogLikelihood")
[19:27:21]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 375, in check_grad
[19:27:21]	"Gradient Check On %s" % str(cpu_place))
[19:27:21]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 336, in __assert_is_close
[19:27:21]	self.assertLessEqual(max_diff, max_relative_error, err_msg())
[19:27:21]	AssertionError: Gradient Check On CPUPlace Variable Emission max gradient diff 2.000001 over limit 0.005000, the first error element is 0, 0.019604, 0.058811
[19:27:21]	
[19:27:21]	======================================================================
[19:27:21]	FAIL: test_check_grad_ignore_transition (__main__.TestLinearChainCrfOp)
[19:27:21]	----------------------------------------------------------------------
[19:27:21]	Traceback (most recent call last):
[19:27:21]	File "test_linear_chain_crf_op.py", line 138, in test_check_grad_ignore_transition
[19:27:21]	["Emission"], "LogLikelihood", no_grad_set=set("Transition"))
[19:27:21]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 375, in check_grad
[19:27:21]	"Gradient Check On %s" % str(cpu_place))
[19:27:21]	File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 336, in __assert_is_close
[19:27:21]	self.assertLessEqual(max_diff, max_relative_error, err_msg())
[19:27:21]	AssertionError: Gradient Check On CPUPlace Variable Emission max gradient diff 2.000001 over limit 0.005000, the first error element is 0, 0.028454, 0.085362
[19:27:21]	
[19:27:21]	----------------------------------------------------------------------
```

**Comment by lcy-seso** [comment]
I guess this may due to the current implementation of CRF does backpropagate the gradients it receives?  Am I right?
