### ISSUE TITLE
驱动版本兼容问题： no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by wucheng-dev** [PaddlePaddle/Paddle#52586]
### 问题描述 Issue Description

安装使用PaddlePaddle  check不通过，版本驱动不识别

### 版本&环境信息 Version & Environment Information

系统环境：

- PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

- NAME="Debian GNU/Linux"

- VERSION_ID="11"

- VERSION="11 (bullseye)"

显卡：英伟达 K80
PaddlePaddle版本： 2.2.2.post112
CUDA Version: 11.2     
Python版本： 3.9.12
安装方式：conda install paddlepaddle-gpu==2.2.2 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
执行check脚本，报错：
W0406 16:50:57.833088 2986766 operator.cc:248] uniform_random raises an exception thrust::system::system_error, parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/appops/anaconda3/envs/bobo02/lib/python3.9/site-packages/paddle/utils/install_check.py", line 196, in run_check
    _run_static_single(use_cuda)
  File "/home/appops/anaconda3/envs/bobo02/lib/python3.9/site-packages/paddle/utils/install_check.py", line 124, in _run_static_single
    exe.run(startup_prog)
  File "/home/appops/anaconda3/envs/bobo02/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1262, in run
    six.reraise(*sys.exc_info())
  File "/home/appops/anaconda3/envs/bobo02/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/appops/anaconda3/envs/bobo02/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1250, in run
    return self._run_impl(
  File "/home/appops/anaconda3/envs/bobo02/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1394, in _run_impl
    return self._run_program(
  File "/home/appops/anaconda3/envs/bobo02/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1491, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
RuntimeError: parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the devic

**Comment by zhengqiwen1997** [comment]
![image](https://user-images.githubusercontent.com/118182234/230583459-4d53732c-3205-43de-b677-b7b47b69fc2d.png)
请提供 检查系统环境 的信息
