### ISSUE TITLE
【分布式训练问题】RuntimeError: (PermissionDenied) Tensor '' used in gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by linjieccc** [PaddlePaddle/Paddle#52744]
### bug描述 Describe the Bug

复现方式：

```python
import paddle
import paddle.nn as nn

from paddlenlp.transformers import LlamaPretrainedModel, LlamaConfig, LlamaModel


class LogExpLoss(nn.Layer):
    def forward(self, chosen_reward: paddle.Tensor, reject_reward: paddle.Tensor) -> paddle.Tensor:
        loss = paddle.log(1 + paddle.exp(reject_reward - chosen_reward)).mean()
        return loss


class RewardModel(LlamaPretrainedModel):
    def __init__(self, config: LlamaConfig):
        super().__init__(config)
        self.llama = LlamaModel(config)
        self.value_head = nn.Linear(config.hidden_size, 1, bias_attr=False)
        self.value_head.weight.set_value(
            paddle.tensor.normal(
                mean=0.0,
                std=1 / (config.hidden_size + 1),
                shape=self.value_head.weight.shape,
            )
        )
        self.criterion = LogExpLoss()
        self.apply(self.init_weights)

    def forward(
        self,
        chosen_ids,
        reject_ids,
        c_mask=None,
        r_mask=None,
    ):
        chosen_output = self.llama(
            chosen_ids, 
            attention_mask=c_mask, 
            return_dict=True
        )
        chosen_logits = chosen_output.last_hidden_state
        reject_output = self.llama(
            reject_ids, 
            attention_mask=r_mask, 
            return_dict=True
        )
        reject_logits = reject_output.last_hidden_state
        chosen_logits = (chosen_logits * c_mask.unsqueeze(axis=2)).sum(axis=1) / c_mask.sum(
            axis=1, keepdim=True
        )
        reject_logits = (reject_logits * r_mask.unsqueeze(axis=2)).sum(axis=1) / r_mask.sum(
            axis=1, keepdim=True
        )

        chosen_reward = self.value_head(chosen_logits)
        reject_reward = self.value_head(reject_logits)

        loss = self.criterion(chosen_reward, reject_reward)

        reward_score = chosen_reward - reject_reward
        return (loss, reward_score)


tensor_parallel_degree = paddle.distributed.get_world_size()
tensor_parallel_rank = paddle.distributed.get_rank()
strategy = paddle.distributed.fleet.DistributedStrategy()
strategy.hybrid_configs = {
    "dp_degree": 1,
    "mp_degree": tensor_parallel_degree,
    "pp_degree": 1,
    "sharding_degree": 1,
}
paddle.distributed.fleet.init(is_collective=True, strategy=strategy)

input_ids = paddle.to_tensor(
    [
        [2, 2, 1, 29871, 13, 13, 29950, 7889, 29901, 1724, 2],
        [2, 2, 1, 29871, 13, 13, 29950, 7889, 2, 2, 2],
    ]
)
r_mask = c_mask = input_ids.not_equal(paddle.to_tensor(2))


model = RewardModel.from_pretrained(
    "facebookresearch/tiny-random-llama",
    tensor_parallel_degree=tensor_parallel_degree,
    tensor_parallel_rank=tensor_parallel_rank,
)

loss, logits = model(input_ids, input_ids, r_mask, c_mask)

print((loss, logits))
loss.backward()
```

Traceback:
```
Traceback (most recent call last):
  File "demo.py", line 92, in <module>
    loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 325, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
RuntimeError: (PermissionDenied) Tensor '' used in gradient computation has been modified by an inplace operation. Its version is 2 but the expected version is 1. Please fix your code to void calling an inplace operator after using the Tensor which will used in gradient computation.
  [Hint: Expected tensor_version == wrapper_version_snapshot, but received tensor_version:2 != wrapper_version_snapshot:1.] (at /paddle/paddle/fluid/eager/tensor_wrapper.h:212)
```

### 其他补充信息 Additional Supplementary Information

paddle和paddlenlp需要使用develop分支的代码

**Comment by ForFishes** [comment]
您好，从报错来看，是组网中使用了inplace操作，导致对其中的反向计算发生了错误。这里建议需要找到反向报错的算子，知道附近的inplace算子，进行排查。

**Comment by linjieccc** [comment]
@ForFishes 单卡训练正常，且2.4.2版本还能正常MP训练，切换到最新的develop分支后出现这个报错

**Comment by ForFishes** [comment]
您好，尝试使用在mplayer输入上，通过clone绕过这个问题。
