### ISSUE TITLE
FLAGS_check_nan_inf无法使用

### ISSUE THREAD

**Issue by linjieccc** [PaddlePaddle/Paddle#52837]
### bug描述 Describe the Bug

```shell
export FLAGS_check_nan_inf=1
export FLAGS_check_nan_inf_level=3
```

使用最新develop版本打开nan inf检查开关后报错如下：

```
Traceback (most recent call last):
  File "finetune_generation.py", line 183, in <module>
    main()
  File "finetune_generation.py", line 164, in main
    data_collator=collate_fn,
  File "/workspace/fix-nan/PaddleNLP/examples/language_model/llama/utils.py", line 29, in __init__
    super().__init__(**kwargs)
  File "/workspace/fix-nan/PaddleNLP/paddlenlp/trainer/trainer.py", line 298, in __init__
    paddle.amp.decorate(models=model, level=self.args.fp16_opt_level)
  File "/usr/local/lib/python3.7/dist-packages/paddle/amp/auto_cast.py", line 764, in decorate
    models, optimizers, level, dtype, master_weight, save_dtype
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/amp/auto_cast.py", line 577, in amp_decorate
    models = pure_fp16_initialize(models=models)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/amp/auto_cast.py", line 212, in pure_fp16_initialize
    dtype='float16', include_sublayers=False, floating_only=True
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/layers.py", line 2129, in _to_impl
    self._apply(transform, device, dtype, blocking, include_sublayers)
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/layers.py", line 2006, in _apply
    self._buffers[key] = func(buf, device, dtype, blocking)
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/layers.py", line 2125, in transform
    return self._transform(t, device, dtype, blocking)
  File "/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/layers.py", line 2028, in _transform
    gpu_memory_available = core.gpu_memory_available()
OSError: (External) CUDA error(9), invalid configuration argument. 
  [Hint: Please search for the error code(9) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/fluid/platform/device/gpu/gpu_info.cc:130)
```

**Comment by AnnaTrainingG** [comment]
在train训练开始之前 开启 这两个环境变量：export FLAGS_check_nan_inf=1
export FLAGS_check_nan_inf_level=3

**Comment by AnnaTrainingG** [comment]
修复PR 已经合入，https://github.com/PaddlePaddle/Paddle/pull/53422 请拉取最新develop分支，改修复已合入2.5版本
