### ISSUE TITLE
双显卡训练突然中断，请问是为什么

### ISSUE THREAD

**Issue by happybear1015** [PaddlePaddle/Paddle#52922]
### bug描述 Describe the Bug

[2023/04/14 14:13:39] ppcls ERROR: Exception occured when parse line: /media/uvtec/LV_XIN/v18/HT/64#HT100-TS_26_gd8mul_fib3_dif.jpg with msg: [Errno 2] No such file or directory: '/media/uvtec/LV_XIN/v18/HT/64#HT100-TS_26_gd8mul_fib3_dif.jpg'
[2023/04/14 14:13:39] ppcls ERROR: Exception occured when parse line: /media/uvtec/LV_XIN/v18/HT/HT329-_8_gd8mul_fib3_dif.jpg with msg: [Errno 2] No such file or directory: '/media/uvtec/LV_XIN/v18/HT/HT329-_8_gd8mul_fib3_dif.jpg'
Process Process-926:
Traceback (most recent call last):
  File "tools/train.py", line 34, in <module>
    engine.train()
  File "/home/uvtec/桌面/PaddleClas/ppcls/engine/engine.py", line 356, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "/home/uvtec/桌面/PaddleClas/ppcls/engine/train/train.py", line 88, in train_epoch
    update_loss(engine, loss_dict, batch_size)
  File "/home/uvtec/桌面/PaddleClas/ppcls/engine/train/utils.py", line 37, in update_loss
    trainer.output_info[key].update(loss_dict[key].numpy()[0], batch_size)
  File "/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/paddle/fluid/multiprocess_utils.py", line 135, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 3037243) exited unexpectedly with code 1. Error detailed are lost due to multiprocessing. Rerunning with:
  1. If run DataLoader by DataLoader.from_generator(...), run with DataLoader.from_generator(..., use_multiprocess=False) may give better error trace.
  2. If run DataLoader by DataLoader(dataset, ...), run with DataLoader(dataset, ..., num_workers=0) may give better error trace (at /paddle/paddle/fluid/imperative/data_loader.cc:161)

I0414 14:13:39.635922 10941 tcp_store.cc:257] receive shutdown event and so quit from MasterDaemon run loop
LAUNCH INFO 2023-04-14 14:13:43,697 Exit code 1

**Comment by wanghuancoder** [comment]
你好，你的问题是否有按提示修改DataLoader的并行数量呢？
If run DataLoader by DataLoader.from_generator(...), run with DataLoader.from_generator(..., use_multiprocess=False) may give better error trace.
If run DataLoader by DataLoader(dataset, ...), run with DataLoader(dataset, ..., num_workers=0) may give better error trace (at /paddle/paddle/fluid/imperative/data_loader.cc:161)

如果没有，你先尝试改一下。如果有，仍不能解决问题，可以让 @heavengate 帮忙看看
