### ISSUE TITLE
test_sparse_transpose_op random failure

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#53008]
### bug描述 Describe the Bug

test_sparse_transpose_op randomly failed.

Environment:
```
GPU: V100 or P100
Paddle version: 2.4.2 or develop
Paddle With CUDA: True
OS: ubuntu 20.04
Python version: 3.8.10
```

To reproduce, run the UT for hundreds of times:
```
$ cat test.sh
set -ex
for ((i=1;i<=500;i++))
do
    echo $i
    python test_sparse_transpose_op.py
done
```

After a lot of running(>2000 times), I observed 3 different errors:

```
+ python test_sparse_transpose_op.py
W0417 14:15:06.284749 32397 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.1, Runtime API Version: 11.7
W0417 14:15:06.285634 32397 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.
E..
======================================================================
ERROR: test_transpose_2d (__main__.TestTranspose)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_sparse_transpose_op.py", line 50, in test_transpose_2d
    self.check_result([2, 5], [0, 1], 'coo')
  File "test_sparse_transpose_op.py", line 45, in check_result
    np.testing.assert_allclose(sp_x.grad.to_dense().numpy(),
AttributeError: 'NoneType' object has no attribute 'to_dense'

----------------------------------------------------------------------
```

```
+ python test_sparse_transpose_op.py
W0417 14:17:06.283701 34783 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.1, Runtime API Version: 11.7
W0417 14:17:06.284631 34783 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.
E..
======================================================================
ERROR: test_transpose_2d (__main__.TestTranspose)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_sparse_transpose_op.py", line 53, in test_transpose_2d
    self.check_result([2, 5], [1, 0], 'csr')
  File "test_sparse_transpose_op.py", line 38, in check_result
    sp_out = paddle.sparse.transpose(sp_x, dims)
  File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/sparse/unary.py", line 154, in transpose
    return _C_ops.sparse_transpose(x, perm)
ValueError: (InvalidArgument) The type of data we are trying to retrieve does not match the type of data currently contained in the container.
  [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():10 != paddle::experimental::CppTypeToDataType<T>::Type():9.] (at /paddle/paddle/phi/core/dense_tensor.cc:143)
```

```
+ python test_sparse_transpose_op.py
W0417 12:05:13.806095 12887 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 12.1, Runtime API Version: 12.1
W0417 12:05:13.807978 12887 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.
E..
======================================================================
ERROR: test_transpose_2d (__main__.TestTranspose)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_sparse_transpose_op.py", line 53, in test_transpose_2d
    self.check_result([2, 5], [0, 1], 'csr')
  File "test_sparse_transpose_op.py", line 38, in check_result
    sp_out = paddle.sparse.transpose(sp_x, dims)
  File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/sparse/unary.py", line 154, in transpose
    return _C_ops.sparse_transpose(x, perm)
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when DenseTensor::place() is called.
  [Hint: holder_ should not be null.] (at /opt/paddle/paddle/paddle/phi/core/dense_tensor_impl.cc:62)

```

**Comment by zkh2016** [comment]
@zrr1999 能否看下这个问题

**Comment by zrr1999** [comment]
修复问题的pr：https://github.com/PaddlePaddle/Paddle/pull/53038

**Comment by Wong4j** [comment]
Hi @zrr1999 , 我们刚遇到一个新的相关的issue，麻烦看下是否也已经被解决。看你的pr主要是修改的Async的cudnMemcpy和cudaMalloc，但这个ut是cpu的实现，不知道是不是相同的问题。（同样是循环跑很多次才能复现issue）
```
test 1349
    Start 1349: test_sparse_utils_op

1349: Test command: /opt/cmake-3.25.1-linux-x86_64/bin/cmake "-E" "env" "PYTHONPATH=/opt/paddle/paddle/build/python" "/usr/bin/python3.8" "/opt/paddle/paddle/tools/test_runner.py" "test_sparse_utils_op"
1349: Working Directory: /opt/paddle/paddle/build/python/paddle/fluid/tests/unittests
1349: Test timeout computed to be: 10000000
1349: W0420 04:02:09.834213  7777 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.1, Runtime API Version: 12.1
1349: W0420 04:02:09.835141  7777 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.
1349: test_sparse_utils_op failed
1349:  ...........E.............
1349: ======================================================================
1349: ERROR: test_batch_csr (test_sparse_utils_op.TestSparseConvert)
1349: ----------------------------------------------------------------------
1349: Traceback (most recent call last):
1349:   File "/opt/paddle/paddle/build/python/paddle/fluid/tests/unittests/test_sparse_utils_op.py", line 334, in test_batch_csr
1349:     verify(dense_x)
1349:   File "/opt/paddle/paddle/build/python/paddle/fluid/tests/unittests/test_sparse_utils_op.py", line 321, in verify
1349:     out = sparse_x.to_dense()
1349:   File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
1349:     return caller(func, *(extras + args), **kw)
1349:   File "/opt/paddle/paddle/build/python/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
1349:     return wrapped_func(*args, **kwargs)
1349:   File "/opt/paddle/paddle/build/python/paddle/fluid/framework.py", line 534, in __impl__
1349:     return func(*args, **kwargs)
1349:   File "/opt/paddle/paddle/build/python/paddle/fluid/dygraph/varbase_patch_methods.py", line 954, in to_dense
1349:     return _C_ops.sparse_to_dense(self)
1349: OSError: function "CsrToCooCPUKernel" is not implemented for data type `float32`
1349:   [/opt/paddle/paddle/paddle/phi/kernels/sparse/cpu/sparse_utils_kernel.cc:164]
1349:
1349: ----------------------------------------------------------------------
1349: Ran 25 tests in 1.257s
1349:
1349: FAILED (errors=1)
1349:
1/1 Test #1349: test_sparse_utils_op .............***Failed    5.53 sec
```

**Comment by zkh2016** [comment]
> Hi @zrr1999 , 我们刚遇到一个新的相关的issue，麻烦看下是否也已经被解决。看你的pr主要是修改的Async的cudnMemcpy和cudaMalloc，但这个ut是cpu的实现，不知道是不是相同的问题。（同样是循环跑很多次才能复现issue）
> 
> ```
> test 1349
>     Start 1349: test_sparse_utils_op
> 
> 1349: Test command: /opt/cmake-3.25.1-linux-x86_64/bin/cmake "-E" "env" "PYTHONPATH=/opt/paddle/paddle/build/python" "/usr/bin/python3.8" "/opt/paddle/paddle/tools/test_runner.py" "test_sparse_utils_op"
> 1349: Working Directory: /opt/paddle/paddle/build/python/paddle/fluid/tests/unittests
> 1349: Test timeout computed to be: 10000000
> 1349: W0420 04:02:09.834213  7777 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.1, Runtime API Version: 12.1
> 1349: W0420 04:02:09.835141  7777 gpu_resources.cc:91] device: 0, cuDNN Version: 8.9.
> 1349: test_sparse_utils_op failed
> 1349:  ...........E.............
> 1349: ======================================================================
> 1349: ERROR: test_batch_csr (test_sparse_utils_op.TestSparseConvert)
> 1349: ----------------------------------------------------------------------
> 1349: Traceback (most recent call last):
> 1349:   File "/opt/paddle/paddle/build/python/paddle/fluid/tests/unittests/test_sparse_utils_op.py", line 334, in test_batch_csr
> 1349:     verify(dense_x)
> 1349:   File "/opt/paddle/paddle/build/python/paddle/fluid/tests/unittests/test_sparse_utils_op.py", line 321, in verify
> 1349:     out = sparse_x.to_dense()
> 1349:   File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
> 1349:     return caller(func, *(extras + args), **kw)
> 1349:   File "/opt/paddle/paddle/build/python/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
> 1349:     return wrapped_func(*args, **kwargs)
> 1349:   File "/opt/paddle/paddle/build/python/paddle/fluid/framework.py", line 534, in __impl__
> 1349:     return func(*args, **kwargs)
> 1349:   File "/opt/paddle/paddle/build/python/paddle/fluid/dygraph/varbase_patch_methods.py", line 954, in to_dense
> 1349:     return _C_ops.sparse_to_dense(self)
> 1349: OSError: function "CsrToCooCPUKernel" is not implemented for data type `float32`
> 1349:   [/opt/paddle/paddle/paddle/phi/kernels/sparse/cpu/sparse_utils_kernel.cc:164]
> 1349:
> 1349: ----------------------------------------------------------------------
> 1349: Ran 25 tests in 1.257s
> 1349:
> 1349: FAILED (errors=1)
> 1349:
> 1/1 Test #1349: test_sparse_utils_op .............***Failed    5.53 sec
> ```

这个应该是其他问题，我这边看下

**Comment by Wong4j** [comment]
Hi @zkh2016 @zrr1999 , cherry pick新的两个PR之后， test_sparse_transpose_op这个UT不再报错。
但是我前面补充的test_sparse_utils_op这个UT仍然会出错，失败率挺高的，跑10次fail 2次。这个有修复吗？

**Comment by zkh2016** [comment]
> Hi @zkh2016 @zrr1999 , cherry pick新的两个PR之后， test_sparse_transpose_op这个UT不再报错。 但是我前面补充的test_sparse_utils_op这个UT仍然会出错，失败率挺高的，跑10次fail 2次。这个有修复吗？

已定位到问题，正在修复中

**Comment by Wong4j** [comment]
Verified. Close this issue.
