### ISSUE TITLE
x2paddle  转换onnx模型报错

### ISSUE THREAD

**Issue by xman1991** [PaddlePaddle/Paddle#53156]
### bug描述 Describe the Bug

========= 1 OPs are not supported yet ===========
========== ScatterElements ============
Traceback (most recent call last):
  File "/home/kylin/.conda/envs/paddle_py37/bin/x2paddle", line 8, in <module>
    sys.exit(main())
  File "/home/kylin/.conda/envs/paddle_py37/lib/python3.7/site-packages/x2paddle/convert.py", line 497, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/kylin/.conda/envs/paddle_py37/lib/python3.7/site-packages/x2paddle/convert.py", line 304, in onnx2paddle
    mapper = ONNXOpMapper(model)
  File "/home/kylin/.conda/envs/paddle_py37/lib/python3.7/site-packages/x2paddle/op_mapper/onnx2paddle/onnx_op_mapper.py", line 38, in __init__
    raise Exception("Model is not supported yet.")
Exception: Model is not supported yet.

### 其他补充信息 Additional Supplementary Information

software: kylin v10、cuda-10.2 、cudnn-8.2.1、paddle2.4源码编译；
hardware:phytium d2000、gtx1060

**Comment by xman1991** [comment]
x_86上是同样的错误，好像是没这个算子，提需求你们多久可以实现这个算子呢？
