### ISSUE TITLE
模型添加 register_forward_pre_hook 怎么转静态图

### ISSUE THREAD

**Issue by ShaominFan** [PaddlePaddle/Paddle#53215]
### 请提出你的问题 Please ask your question

```python
def forward_pre_hook(layer, input):
    """
    归一化到[0,1]
    """
    pixel_max = paddle.full(shape=[1], fill_value=255.0, dtype='float32')
    input_return = paddle.divide(input, pixel_max)
    return input_return

rn = resnet18(pretrained=True, num_classes=0, with_pool=True)
rn.conv1.register_forward_pre_hook(forward_pre_hook)

paddle.jit.save(model, path, input_spec=[paddle.static.InputSpec(shape=[None, 1, 3, 224, 224], dtype='int64')])
```
save转静态图失败，报错是一个tuple，不是tensor

**Comment by Bobholamovic** [comment]
请贴出具体的报错信息，便于我们排查问题~ 如果有可能的话，希望给出能够跑通的最小可复现例子

**Comment by Bobholamovic** [comment]
这里有一个case好像可以复现这个问题：

```python
import paddle


def forward_pre_hook(layer, input):
    return paddle.divide(input, 2)


class CustomModel(paddle.nn.Layer):
    def __init__(self):
        super().__init__()
        self.conv = paddle.nn.Conv1D(3, 3, 1)
    
    def forward(self, x):
        x = self.conv(x)
        return x + 1


x = paddle.to_tensor([1.0, 2.0, 3.0], dtype='float32')
model = CustomModel()
model.conv.register_forward_pre_hook(forward_pre_hook)
paddle.jit.save(model, 'save/model', input_spec=[paddle.static.InputSpec(shape=[None, 3, 3], dtype='float32')])
```

错误提示如下：

```plain
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    paddle.jit.save(model, 'save/model', input_spec=[paddle.static.InputSpec(shape=[None, 3, 3], dtype='float32')])
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 649, in wrapper
    func(layer, path, input_spec, **configs)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
    return func(*args, **kwargs)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 943, in save
    with_hook=with_hook)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in concrete_program_specify_input_spec
    is_train=self._is_train_mode())
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 485, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 955, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 944, in _build_once
    **cache_key.kwargs)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
    return func(*args, **kwargs)
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 895, in from_func_spec
    error_data.raise_new_exception()
  File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 350, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
TypeError: In transformed code:


    File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 782, in apply_pre_hooks
        hook_result = forward_pre_hook(self.class_instance, inputs)
    File "test.py", line 5, in forward_pre_hook
        return paddle.divide(input, 2)
    File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/tensor/math.py", line 724, in divide
        return _elementwise_op(LayerHelper(op_type, **locals()))
    File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/tensor/math.py", line 486, in _elementwise_op
        original_op_type)
    File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 85, in check_variable_and_dtype
        check_type(input, input_name, Variable, op_name, extra_message)
    File "/ssd2/linmanhui/anaconda3/envs/Default/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 125, in check_type
        (input_name, op_name, expected_type, type(input), extra_message))

    TypeError: The type of 'x' in elementwise_div must be (<class 'paddle.fluid.framework.Variable'>, <class 'paddle.fluid.libpaddle.VarBase'>, <class 'paddle.Tensor'>), but received <class 'tuple'>. 
```

辛苦 @ShaominFan 确认一下遇到的是不是这个问题哈~

**Comment by ShaominFan** [comment]
嗯嗯 是的 
    TypeError: The type of 'x' in elementwise_div must be (<class 'paddle.fluid.framework.Variable'>, <class 'paddle.fluid.libpaddle.VarBase'>, <class 'paddle.Tensor'>), but received <class 'tuple'>. 
我也是遇到这个问题，感觉这个函数动态图转静态图有点问题

**Comment by Bobholamovic** [comment]
好的~ 看起来这可能是一个bug，我们的动转静相关同学会跟进这个问题

**Comment by Aurelius84** [comment]
@ShaominFan 从[官方文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Layer_cn.html#register-forward-pre-hook-hook)介绍来看，hook函数里的两个输入参数：layer 和 input，其中第二的参数默认推荐是一个tuple。
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/9301846/233998228-5f02dba4-3dfd-4e56-8631-0b0c13568510.png">



我尝试了下，动态图下input不传入tuple在某些场景下是可以的，但更多推荐按照input是tuple来写hook逻辑，例如：
```python
import paddle


def forward_pre_hook(layer, inputs):
    return paddle.divide(inputs[0], inputs[0])


class CustomModel(paddle.nn.Layer):
    def __init__(self):
        super().__init__()
        self.conv = paddle.nn.Conv1D(3, 3, 1)
    
    def forward(self, x):
        x = self.conv(x)
        return x + 1


x = paddle.randn([2,3,3], dtype='float32')
model = CustomModel()
model.conv.register_forward_pre_hook(forward_pre_hook)
paddle.jit.save(model, 'save/model', input_spec=[paddle.static.InputSpec(shape=[None, 3, 3], dtype='float32')])
# model(x)
```
