### ISSUE TITLE
飞腾arm64架构使用-DWITH_GPU=OFF参数编译出来的paddlepaddle，安装paddlespeech后，运行demo有 list index out of range报错

### ISSUE THREAD

**Issue by wuzhaohui100** [PaddlePaddle/Paddle#53367]
### bug描述 Describe the Bug

系统：麒麟V10SP1
架构：飞腾 arm64
python:python3.8

编译方法
git clone https://gitee.com/PaddlePaddle/Paddle.git
cd Paddle
git checkout develop
pip3 install -r python/requirements.txt
mkdir build && cd build
ulimit -n 4096
cmake .. -DPY_VERSION=3.8 -DPYTHON_EXECUTABLE=which python3 -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_GPU=OFF
make TARGET=ARMV8 -j$(nproc)

安装编译出来的whl文件

然后安装paddlespeech

运行demo会有如下报错
$ paddlespeech asr --lang zh --input zh.wav
[2023-04-26 13:34:48,142] [ ERROR] - list index out of range
Traceback (most recent call last):
File "/home/kylin/.local/lib/python3.8/site-packages/paddlespeech/cli/asr/infer.py", line 314, in infer
result_transcripts = self.model.decode(
File "/home/kylin/.local/lib/python3.8/site-packages/decorator.py", line 232, in fun
return caller(func, *(extras + args), **kw)
File "/home/kylin/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 350, in _decorate_function
return func(*args, **kwargs)
File "/home/kylin/.local/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 819, in decode
hyp = self.attention_rescoring(
File "/home/kylin/.local/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 533, in attention_rescoring
assert speech.shape[0] == speech_lengths.shape[0]
IndexError: list index out of range
KeyError: 'result'

如果使用没有添加-DWITH_GPU=OFF参数编译出来的paddlepaddle就是正常的
$ paddlespeech asr --lang zh --input zh.wav
我认为跑步最重要的就是给我带来了身体健康

**Comment by kangguangli** [comment]
你好，这里看起来没有在框架层抛出异常，还是套件库内部报错。这应该不是你编译的问题，我使用paddle官方提供的cpu版本的develop包，运行paddlespeech也会报同样的问题，使用2.4版本则无此问题，可能是develop近期改动带来的问题。
我这边再定位下，后面和你沟通，感谢反馈。

**Comment by wuzhaohui100** [comment]
> 你好，这里看起来没有在框架层抛出异常，还是套件库内部报错。这应该不是你编译的问题，我使用paddle官方提供的cpu版本的develop包，运行paddlespeech也会报同样的问题，使用2.4版本则无此问题，可能是develop近期改动带来的问题。 我这边再定位下，后面和你沟通，感谢反馈。

我这边使用release/2.4、v2.4.1、v2.4.2编译的CPU版本，都会有如下报错，即使使用高版本的patchelf也有同样的问题。
$ python3
Python 3.8.2 (default, May 10 2021, 05:51:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /home/kylin/.local/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: /home/kylin/.local/lib/python3.8/site-packages/paddle/fluid/libpaddle.so: undefined symbol: shm_unlink

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/fluid/core.py", line 333, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined
>>> paddle.utils.run_check()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'paddle' is not defined

**Comment by kangguangli** [comment]
可能以前的版本对其他设备编译支持的不太好，这里看起来编译出来有点问题，还是用develop编译吧。之前的问题应该是套件库的逻辑需要修改适配，我找相关同事看一下，修复后你可以再试一下。

**Comment by kangguangli** [comment]
目前确认是paddleSpeech需要适配下0维tensor，相关同学正在处理，可能需要一段时间。

**Comment by khushbookk** [comment]
PaddleSpeech/paddlespeech/s2t/exps/u2/bin
/test_wav.py 

Line 81 - add
ilen = paddle.to_tensor(feat.shape[0])
ilen = paddle.reshape(ilen, [1])

This worked for me.
