### ISSUE TITLE
对部分参数使用EMA

### ISSUE THREAD

**Issue by cwings316** [PaddlePaddle/Paddle#53401]
### 请提出你的问题 Please ask your question

如何只对网络中的部分参数（如_cls_out）使用EMA？网络中其他参数已被冻结。
我尝试设置参数的do_model_average，但是运行报错。代码和保存信息如下：
```
def do_ema(name):
    prefix = ["_cls_out"]
    for pf in prefix:
        if pf in name:
            return True
    return False
for param in fluid.default_main_program().global_block().all_parameters():
    if do_ema(param.name):
        param.do_model_average = True
    else:
        param.do_model_average = False
```
```
Traceback (most recent call last):                                                                                                                                                                     
  File "ernie/run_classifier_v1.py", line 628, in <module>                                                                                                                                             
    main(args)                                                                                                                                                                                         
  File "ernie/run_classifier_v1.py", line 198, in main                                                                                                                                                 
    ema.update()                                                                                                                                                                                       
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/optimizer.py", line 4274, in update                                                                                                        
    1 - self._decay_var)                                                                                                                                                                               
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/math_op_patch.py", line 288, in __impl__                                                                                            
    return scalar_method(self, other_var)                                                                                                                                                              
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/math_op_patch.py", line 249, in _scalar_rsub_                                                                                       
    return _scalar_op_(var, -1.0, value)                                                                                                                                                               
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/math_op_patch.py", line 208, in _scalar_op_                                                                                         
    out = create_new_tmp_var(block, var.dtype)                                                                                                                                                         
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/math_op_patch.py", line 79, in create_new_tmp_var                                                                                   
    return block.create_var(name=tmp_name, dtype=dtype)                                                                                                                                                
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3428, in create_var                                                                                                    
    var = Variable(block=self, *args, **kwargs)                                                                                                                                                        
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 1322, in __init__                                                                                                      
    dtype))                                                                                                                                                                                            
ValueError: Variable 'tmp_49' has been created before. The previous data type is paddle.int64, the new data type is paddle.float32. They are not matched. 
```

**Comment by USTCKAY** [comment]
你好，请问是训练的PaddleNLP的模型遇到的问题吗？可以去PaddleNLP的代码仓库提issue哦 https://github.com/PaddlePaddle/PaddleNLP/issues

**Comment by cwings316** [comment]
不是PaddleNLP的模型

**Comment by USTCKAY** [comment]
请问一下你的paddle是什么版本的？还有就是跟你确认一下你使用的是动态图吗？目前paddle的动态图还不支持ExponentialMovingAverage

**Comment by cwings316** [comment]
paddle版本是2.3.0，用的是静态图

**Comment by USTCKAY** [comment]
有试过升级到最新版本的paddle还会报错吗

**Comment by cwings316** [comment]
没试过升级版本，我使用的这个环境必须得使用2.3.0版本。。
或者您先别管这个报错信息了，您告诉我对部分参数进行EMA的方法就行。

**Comment by LiYuRio** [comment]
看着tmp_49名字冲突了，可能有两个program用了同一个变量名，麻烦检查一下，可以把ema的创建通过with program.guard到一起，或者再加一个with unique_name保证命名唯一
