### ISSUE TITLE
paddle报错：KeyError: 'create_py_reader'

### ISSUE THREAD

**Issue by zhangpeng-HEBUT** [PaddlePaddle/Paddle#53474]
### 请提出你的问题 Please ask your question

在运行项目的时候，paddle报错：KeyError: 'create_py_reader'，我paddle版本是2.4.2
![image](https://user-images.githubusercontent.com/85481717/235336526-dd97d97f-031f-4ef9-8e8d-bc2d037167fe.png)

**Comment by zhangpeng-HEBUT** [comment]
报错代码：
`/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/layers/io.py:720: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  'paddle.fluid.layers.py_reader() may be deprecated in the near future. '
[WARNING] 2023-04-30 11:56:12,678 [       io.py:  720]:	paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
I0430 11:56:12.678824 441271 reader_py.cc:406] init_lod_tensor_blocking_queue
/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/framework.py:4006: DeprecationWarning: Op `create_py_reader` is executed through `append_op` under the dynamic mode, the corresponding API implementation needs to be upgraded to using `_C_ops` method.
  DeprecationWarning,
DEBUG:	classify
zp11111
Traceback (most recent call last):
  File "./src/train_de.py", line 380, in <module>
    main(args)
  File "./src/train_de.py", line 155, in main
    fleet_handle=fleet)
  File "/data/c21/zp/PAIR/model/src/finetune/dual_encoder.py", line 60, in create_model
    use_double_buffer=True)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 727, in py_reader
    use_double_buffer=use_double_buffer)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 452, in _py_reader
    'ranks': ranks
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4028, in append_op
    inplace_map,
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 316, in trace_op
    stop_gradient, inplace_map)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 121, in eager_legacy_trace_op
    function_ptr = _legacy_C_ops.__dict__[op_type]
KeyError: 'create_py_reader'`

**Comment by zhangpeng-HEBUT** [comment]
报错代码：
`/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/layers/io.py:720: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  'paddle.fluid.layers.py_reader() may be deprecated in the near future. '
[WARNING] 2023-04-30 11:56:12,678 [       io.py:  720]:	paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
I0430 11:56:12.678824 441271 reader_py.cc:406] init_lod_tensor_blocking_queue
/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/framework.py:4006: DeprecationWarning: Op `create_py_reader` is executed through `append_op` under the dynamic mode, the corresponding API implementation needs to be upgraded to using `_C_ops` method.
  DeprecationWarning,
DEBUG:	classify
zp11111
Traceback (most recent call last):
  File "./src/train_de.py", line 380, in <module>
    main(args)
  File "./src/train_de.py", line 155, in main
    fleet_handle=fleet)
  File "/data/c21/zp/PAIR/model/src/finetune/dual_encoder.py", line 60, in create_model
    use_double_buffer=True)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 727, in py_reader
    use_double_buffer=use_double_buffer)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 452, in _py_reader
    'ranks': ranks
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4028, in append_op
    inplace_map,
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 316, in trace_op
    stop_gradient, inplace_map)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 121, in eager_legacy_trace_op
    function_ptr = _legacy_C_ops.__dict__[op_type]
KeyError: 'create_py_reader'`

**Comment by zhangpeng-HEBUT** [comment]
报错代码：
/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/layers/io.py:720: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  'paddle.fluid.layers.py_reader() may be deprecated in the near future. '
[WARNING] 2023-04-30 11:56:12,678 [       io.py:  720]:	paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
I0430 11:56:12.678824 441271 reader_py.cc:406] init_lod_tensor_blocking_queue
/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/framework.py:4006: DeprecationWarning: Op `create_py_reader` is executed through `append_op` under the dynamic mode, the corresponding API implementation needs to be upgraded to using `_C_ops` method.
  DeprecationWarning,
DEBUG:	classify
zp11111
Traceback (most recent call last):
  File "./src/train_de.py", line 380, in <module>
    main(args)
  File "./src/train_de.py", line 155, in main
    fleet_handle=fleet)
  File "/data/c21/zp/PAIR/model/src/finetune/dual_encoder.py", line 60, in create_model
    use_double_buffer=True)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 727, in py_reader
    use_double_buffer=use_double_buffer)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/layers/io.py", line 452, in _py_reader
    'ranks': ranks
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4028, in append_op
    inplace_map,
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 316, in trace_op
    stop_gradient, inplace_map)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 121, in eager_legacy_trace_op
    function_ptr = _legacy_C_ops.__dict__[op_type]
KeyError: 'create_py_reader'

**Comment by zengshao0622** [comment]
请提供最小可复现例子，以便能够定位问题

**Comment by hellohawaii** [comment]
I met the same problem. I am using conda env, Python3.8.17, conda env, 3090 GPU, CUDA 11.7. I install paddlepaddle-gpu 2.4.2.post117 via `conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`

Here is a minimal example:

```python
import paddle.fluid as fluid
pyreader = fluid.layers.py_reader(
    capacity=60,
    shapes=[[-1, 11, 1],
            [-1, 11, 1],
            [-1, 1], [-1, 1], [-1, 1],
            [11, 11, 1]],
    dtypes=[
        'int64', 'float32', 'int64', 'int64', 'int64', 'int64'],
    lod_levels=[0, 0, 0, 0, 0, 0],
    name="train_reader",
use_double_buffer = True)
```

In fact, this is the code from PaddlePaddle reasearch repo, GRAN. See [the original link](https://github.com/PaddlePaddle/Research/blob/9f08f2fab73b71ade93b584eb311f707a4437923/KG/ACL2021_GRAN/src/run.py#L115C11-L115C11). I also found [this post](https://aistudio.baidu.com/paddle/forum/topic/show/2296315).

Of course, I got a lot of deprecated warnings:
```
/home/username/.local/lib/python3.8/site-packages/setuptools/sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/home/username/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/username/software/miniconda3/envs/my_paddle/lib/python3.8/site-packages/paddle/fluid/layers/io.py:719: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn(
WARNING:root:paddle.fluid.layers.py_reader() may be deprecated in the near future. Please use paddle.fluid.io.DataLoader.from_generator() instead.
/home/username/software/miniconda3/envs/my_paddle/lib/python3.8/site-packages/paddle/fluid/framework.py:4002: DeprecationWarning: Op `create_py_reader` is executed through `append_op` under the dynamic mode, the corresponding API implementation needs to be upgraded to using `_C_ops` method.
  warnings.warn(
Traceback (most recent call last):
  File "debug_paddle.py", line 2, in <module>
    pyreader = fluid.layers.py_reader(
  File "/home/username/software/miniconda3/envs/my_paddle/lib/python3.8/site-packages/paddle/fluid/layers/io.py", line 722, in py_reader
    return _py_reader(capacity=capacity,
  File "/home/username/software/miniconda3/envs/my_paddle/lib/python3.8/site-packages/paddle/fluid/layers/io.py", line 444, in _py_reader
    startup_blk.append_op(type='create_py_reader',
  File "/home/username/software/miniconda3/envs/my_paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 4022, in append_op
    _dygraph_tracer().trace_op(
  File "/home/username/software/miniconda3/envs/my_paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 313, in trace_op
    self.eager_legacy_trace_op(type, inputs, outputs, attrs,
  File "/home/username/software/miniconda3/envs/my_paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/tracer.py", line 120, in eager_legacy_trace_op
    function_ptr = _legacy_C_ops.__dict__[op_type]
KeyError: 'create_py_reader'
```

**Comment by xingtinajiao** [comment]
我也遇到了相同的问题
