### ISSUE TITLE
Paddle3D动态图转静态图后，部署推理，未开启TensorRT正常运行，开启TensorRT报错

### ISSUE THREAD

**Issue by wayyeah** [PaddlePaddle/Paddle#53571]
### 请提出你的问题 Please ask your question

Paddle3D自己迁移的模型，动态图转静态图后，部署推理，未开启TensorRT正常运行，开启TensorRT报错，
报错提醒：
```
Traceback (most recent call last):
  File "infer.py", line 227, in <module>
    main(args)
  File "infer.py", line 214, in main
    box3d_lidar, label_preds, scores = run(predictor, points)
  File "infer.py", line 175, in run
    predictor.run()
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when DenseTensor::place() is called.
  [Hint: holder_ should not be null.] (at /paddle/paddle/phi/core/dense_tensor_impl.cc:65)
``` 
环境：paddlepaddle-gpu=2.4.1.post112 cuda=11.1 python3.8 cudnn=8.0.5

**Comment by GGBond8488** [comment]
Hello, 可以提供更详细的信息吗，像是最小可复现代码

**Comment by wayyeah** [comment]
> Hello, 可以提供更详细的信息吗，像是最小可复现代码

代码链接：https://pan.baidu.com/s/1OjlWEfJSUJr1KkM7Kk5vmQ?pwd=1234 
提取码：1234，下载后解压放入Paddle3D/deploy文件夹，在ted/python目录 运行sh infer.sh,当infer.sh里的 --use_trt 0 运行正常   --use_trt 1 运行错误 @GGBond8488

**Comment by GGBond8488** [comment]
hello, 这个问题在最新的develop版本已经解决，你可以试试

**Comment by wayyeah** [comment]
> hello, 这个问题在最新的develop版本已经解决，你可以试试

@GGBond8488 感谢你的回答，但是使用develop版本又有新的问题，
```
for i in range(100):
        start_time = time.time()
        box3d_lidar, label_preds, scores = run(predictor, points)
        print("Inference time: {}".format(time.time() - start_time))
        print("box3d_lidar:",box3d_lidar)
        print("scores:",scores)
        print("label_preds:",label_preds)
```
执行这段代码，循环会出错，未开启TensorRT时执行结果和报错如下：
```
Inference time: 1.3819530010223389
box3d_lidar: [[47.11278    37.181038   -0.7997543   4.0007024   1.5923994   1.518592
   3.547555  ]
 [29.621191    4.985384   -0.23711422  3.734477    1.6541712   1.5111346
   6.6684666 ]
 [47.202225   37.28475    -0.80866796  4.027546    1.6296084   1.5103899
   3.54422   ]
 [47.0522     36.9995     -0.8355719   3.761516    1.567605    1.5077277
   3.5528688 ]
 [29.576378    4.967171   -0.25412387  3.6974387   1.6196731   1.5356464
   6.689636  ]
 [47.29857    37.112972   -0.81279725  4.1038003   1.6345972   1.5020945
   3.4407    ]
 [46.780994   37.022137   -0.8082027   3.5428605   1.6176652   1.515478
   3.531879  ]
 [29.542582    4.977382   -0.23949146  3.7242725   1.6374884   1.5393728
   6.686978  ]
 [47.23849    36.990658   -0.8110658   3.8906777   1.5969933   1.4956212
   3.5211027 ]
 [29.697796    5.0045075  -0.26033205  3.9629471   1.6655415   1.5187908
   6.680036  ]
 [29.715714    4.9439554  -0.276369    4.0695043   1.6509775   1.4993026
   6.710293  ]
 [29.77691     4.8944116  -0.24895129  3.9901772   1.6594616   1.5212518
   6.5910854 ]]
scores: [0.30183202 0.5708696  0.2717124  0.5223582  0.484469   0.30595976
 0.27135316 0.4368051  0.4057037  0.38476557 0.66486484 0.5857314 ]
label_preds: [1 1 1 1 1 1 1 1 1 1 1 1]
Inference time: 0.0704505443572998
box3d_lidar: []
scores: []
label_preds: []
Traceback (most recent call last):
  File "/home/aistudio/work/Paddle3D/deploy/ted/python/infer.py", line 236, in <module>
    main(args)
  File "/home/aistudio/work/Paddle3D/deploy/ted/python/infer.py", line 218, in main
    box3d_lidar, label_preds, scores = run(predictor, points)
  File "/home/aistudio/work/Paddle3D/deploy/ted/python/infer.py", line 172, in run
    predictor.run()
OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED. 
  [Hint: Please search for the error code(9) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at ../paddle/phi/kernels/fusion/gpu/conv_fusion_kernel.cu:611)
  [operator < conv2d_fusion > error]
```
在开启TensorRT加速后，执行结果和报错如下：
```
Inference time: 1.541944980621338
box3d_lidar: []
scores: []
label_preds: []
Inference time: 0.15513134002685547
box3d_lidar: [[ 0.4998609   0.50007665  0.50077486  0.50112325  0.5006991   0.5001778
   0.49865216]
 [ 0.4998609   0.50007665  0.50077486  0.50112325  0.5006991   0.5001778
   0.49865216]
 [ 0.4998609   0.50007665  0.50077486  0.50112325  0.5006991   0.5001778
   0.49865216]
 [ 0.4998609   0.50007665  0.50077486  0.50112325  0.5006991   0.5001778
   0.49865216]
 [ 0.4998609   0.50007665  0.50077486  0.50112325  0.5006991   0.5001778
   0.49865216]
 [ 0.4998609   0.50007665  0.50077486  0.50112325  0.5006991   0.5001778
   0.49865216]
 [ 0.4998609   0.50007665  0.50077486  0.50112325  0.5006991   0.5001778
   0.49865216]
 [ 0.4998609  38.308693   -0.38686493  0.59594303  1.         -0.939471
  -0.34262836]
 [45.635387   35.915      -1.4412371   0.34262836  0.34262836  0.34262836
   1.        ]
 [28.694275    3.604108    1.1892648   0.78779465 -0.61593807  0.78779465
   0.78779465]
 [46.468006   35.33947    -0.9113128  -0.46626613  0.46626613  0.46626613
  -0.8846445 ]
 [29.481688    5.6447954  -0.45497814  1.          0.86028004  0.5098218
  -0.5098218 ]
 [47.883938   37.11417    -1.0274227  -0.5098218  -0.5098218   1.
  -0.8973329 ]
 [33.183315   39.004135   -0.6972663  -0.8973329   0.44135433  0.44135433
   0.44135433]
 [46.382324   36.34668     0.83852327 -0.6412562  -0.6412562   0.76732683
  -0.6412562 ]
 [47.571335   38.97431    -0.9350763  -0.7914284  -0.61126196  0.61126196
   0.61126196]
 [28.531033    4.7952037   0.28396845  0.61126196  1.          0.9406619
   0.33934516]
 [47.340946   38.32428    -0.4924283  -0.33934516 -0.33934516 -0.33934516
   1.        ]
 [46.84322    38.781525   -1.4986073   0.5504198  -0.83488804  0.5504198
   0.5504198 ]
 [47.00248    40.197758   -0.39521194 -0.8604107   0.8604107   0.8604107
  -0.50960135]
 [47.971992   40.852474    1.1312509   1.          0.8630117   0.50518394
  -0.50518394]
 [29.028612    5.5983977  -0.9319967  -0.50518394 -0.50518394  1.
  -0.50487924]
 [43.99849    36.395287    0.11580056 -0.50487924  0.86319     0.86319
   0.86319   ]
 [48.150974   39.13688    -2.2570553   0.9117659   0.9117659  -0.41071036
   0.9117659 ]
 [38.822807   41.03677     1.3270106  -0.747389   -0.66438675  0.66438675
   0.66438675]
 [48.155125   42.065105   -0.285977    0.66438675  1.         -0.7405562
  -0.6719945 ]
 [45.756393   40.185352   -0.70689476  0.6719945   0.6719945   0.6719945
   1.        ]
 [47.101055   40.48583    -0.37788963 -0.31849393  0.9479249  -0.31849393
  -0.31849393]
 [44.37196    41.478252   -0.60913813  0.6412365  -0.6412365  -0.6412365
   0.76734334]
 [38.661636   42.194225   -2.3911448   1.          0.46453658  0.88555396
  -0.88555396]
 [45.763737   41.283417   -2.0287392  -0.88555396 -0.88555396  1.
  -0.7463195 ]
 [39.217262   41.990555   -0.1697669  -0.7463195   0.66558796  0.66558796
   0.66558796]
 [42.931747   40.917233   -1.3081661   0.6773257   0.6773257  -0.7356833
   0.6773257 ]
 [45.731857   41.242508    1.122703   -0.7200554  -0.6939166   0.6939166
   0.6939166 ]
 [44.90069    35.200146   -0.16163635  0.6939166   1.         -0.74779755
  -0.66392684]
 [38.07958    40.179947   -0.7690287   0.66392684  0.66392684  0.66392684
   1.        ]
 [43.390633   40.10442    -0.5969689  -0.70988244  0.7043202  -0.70988244
  -0.70988244]
 [44.96768    40.724808   -1.4030662  -0.65445006  0.65445006  0.65445006
  -0.75610524]
 [31.040277   41.555893   -1.6659298   1.         -0.71845037 -0.6955783
   0.6955783 ]
 [29.794718    4.811655    0.38598233  0.6955783   0.6955783   1.
  -0.7378026 ]
 [38.835842   42.056896   -0.1622423  -0.7378026   0.6750166   0.6750166
   0.6750166 ]
 [46.54921    40.947605   -1.3873475   0.69594884  0.69594884 -0.71809137
   0.69594884]
 [27.64597     2.7613926  -0.4845125  -0.7106207  -0.7035753   0.7035753
   0.7035753 ]
 [30.587904   40.07768    -0.4874686   0.7035753   1.          0.04146467
   0.99913996]
 [46.912167   36.27401     0.8480326  -0.99913996 -0.99913996 -0.99913996
   1.        ]
 [43.595158   43.052773   -1.22642     0.66348565 -0.74818903  0.66348565
   0.66348565]
 [43.18776    39.8384     -0.41825992 -0.6849062   0.6849062   0.6849062
  -0.72863126]
 [40.2831     41.221207    0.7432335   1.         -0.7245784  -0.6891924
   0.6891924 ]
 [48.11826    42.157646   -0.19300407  0.6891924   0.6891924   1.
   0.50210106]
 [44.868084   37.54173    -1.6665118   0.50210106 -0.864809   -0.864809
  -0.864809  ]]
scores: [0.4998609  0.50007665 0.50077486 0.50112325 0.5006991  0.5001778
 0.49865216 0.4998609  0.50007665 0.50077486 0.50112325 0.5006991
 0.5001778  0.49865216 0.4998609  0.50007665 0.50077486 0.50112325
 0.5006991  0.5001778  0.49865216 0.4998609  0.50007665 0.50077486
 0.50112325 0.5006991  0.5001778  0.49865216 0.4998609  0.50007665
 0.50077486 0.50112325 0.5006991  0.5001778  0.49865216 0.4998609
 0.50007665 0.50077486 0.50112325 0.5006991  0.5001778  0.49865216
 0.4998609  0.50007665 0.50077486 0.50112325 0.5006991  0.5001778
 0.49865216 0.4998609 ]
label_preds: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1]
W0515 17:53:30.762804  4233 operator.cc:804] sparse_conv3d raises an exception thrust::system::system_error, scan failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
Traceback (most recent call last):
  File "/home/aistudio/work/Paddle3D/deploy/ted/python/infer.py", line 236, in <module>
    main(args)
  File "/home/aistudio/work/Paddle3D/deploy/ted/python/infer.py", line 218, in main
    box3d_lidar, label_preds, scores = run(predictor, points)
  File "/home/aistudio/work/Paddle3D/deploy/ted/python/infer.py", line 172, in run
    predictor.run()
RuntimeError: scan failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```
在旧版本的paddle中未开启TensorRT加速，循环是能正常执行的

**Comment by GGBond8488** [comment]
请问paddle-infrence 以及 paddle3D各自的版本是什么呢

**Comment by wayyeah** [comment]
> 请问paddle-infrence 以及 paddle3D各自的版本是什么呢

paddle3d 1.0.0  paddlepaddle-gpu .0.0.post112最新develop

**Comment by GGBond8488** [comment]
> > 请问paddle-infrence 以及 paddle3D各自的版本是什么呢
> 
> paddle3d 1.0.0 paddlepaddle-gpu .0.0.post112最新develop

看起来前面几次没有问题，是否显存不足呢？

**Comment by wayyeah** [comment]
> > > 请问paddle-infrence 以及 paddle3D各自的版本是什么呢
> > 
> > 
> > paddle3d 1.0.0 paddlepaddle-gpu .0.0.post112最新develop
> 
> 看起来前面几次没有问题，是否显存不足呢？


![image](https://github.com/PaddlePaddle/Paddle/assets/53206282/c0a5fc7f-d613-4d8e-996b-198894f8b3ca)
应该不是吧，因为在paddlepaddle2.4.2版本能正常执行，只是TensorRT加速报错，而上面的 两次循环的执行结果都不同了，输入是一致的，每次循环结果应该也要一致才对
