### ISSUE TITLE
paddle.jit.save导出静态图模型怎么样保持原图宽高输入？

### ISSUE THREAD

**Issue by wzz981** [PaddlePaddle/Paddle#53759]
### 请提出你的问题 Please ask your question

我保存的模型的程序语句是以下：  
```
from paddle.static import InputSpec
static_mode = paddle.jit.to_static(netG, input_spec=[InputSpec(shape=     ？？？      , name='x')])
paddle.jit.save(static_mode, '/logo_drop/model/erase')
```
其中，shape=     ？？？     应该怎么输入，我搜索过以同样方法保存模型的官方文档和其他人的语句大多是shape=[None,784]或shape=[None, 3, 224, 224]这样，但是我想要宽高能够保持原图尺寸，shape应该怎么设置

我试过shape=[None, 3, None, None]，但是因为我的模型网络用到了`paddle.nn.functional.F.pad`,所以这样设置时，报错以下：
```
pad_h = (self.padder_size - h % self.padder_size) % self.padder_size
pad_w = (self.padder_size - w % self.padder_size) % self.padder_size
input = F.pad(input, [0, pad_w, 0, pad_h])
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
return input

File "D:\miniconda\Lib\site-packages\paddle\nn\functional\common.py", line 1724, in pad
helper.append_op(File "D:\miniconda\Lib\site-packages\paddle\fluid\layer_helper.py", line 45, in append_op
return self.main_program.current_block().append_op(*args, **kwargs)
File "D:\miniconda\Lib\site-packages\paddle\fluid\framework.py", line 4017, in append_op
op = Operator(File "D:\miniconda\Lib\site-packages\paddle\fluid\framework.py", line 2991, in __init__
self._update_desc_attr(attr_name, attr_val)
File "D:\miniconda\Lib\site-packages\paddle\fluid\framework.py", line 3339, in _update_desc_attr
self._update_desc_plain_attr(name, val)
File "D:\miniconda\Lib\site-packages\paddle\fluid\framework.py", line 3363, in _update_desc_plain_attr
desc._set_int32s_attr(name, val)

TypeError: _set_int32s_attr(): incompatible function arguments. The following argument types are supported:
1. (self: paddle.fluid.libpaddle.OpDesc, arg0: str, arg1: List[int]) -> None

Invoked with: <paddle.fluid.libpaddle.OpDesc object at 0x000001C1BA91EDB0>, 'paddings', [0, var tmp_9 : LOD_TENSOR.shape(1,).dtype(int32).stop_gradient(False), 0, var tmp_4 : LOD_TENSOR.shape(1,).dtype(int32).stop_gradient(False), 0, 0]
```

**Comment by YanhuiDua** [comment]
你好，这个想要能够保持原图尺寸，直接指定shapeshape=[None, 3, 224, 224]就可以了

**Comment by wzz981** [comment]
> 你好，这个想要能够保持原图尺寸，直接指定shapeshape=[None, 3, 224, 224]就可以了

谢谢你的回答，原图不是224*224也能保持是吗，比如1000*900也能保持，不会被修改为224*224吗

**Comment by YanhuiDua** [comment]
就是指定shape=[None, None, H, W]，H，W分别是原图的尺寸

**Comment by wzz981** [comment]
> 就是指定shape=[None, None, H, W]，H，W分别是原图的尺寸

额，图片不是一直会是同一个尺寸，不同图片基本都是不同尺寸的，hw是会变化的，图像进行尺寸变换后，模型效果不太好，所以我想原图尺寸放入

**Comment by YanhuiDua** [comment]
如果图片尺寸会变换的话，就应该是动态shape，指定-1，-1；如果尺寸不变化，就指定hw就可以；请问下现在是设置了hw后，在pad后会报错是吗？

**Comment by wzz981** [comment]
> 如果图片尺寸会变换的话，就应该是动态shape，指定-1，-1；如果尺寸不变化，就指定hw就可以；请问下现在是设置了hw后，在pad后会报错是吗？

设置具体hw不会报错，但是设置shape=[None, 3, -1, -1]和shape=[None, 3, None, None]会报错上面因为pad产生的问题。

**Comment by wzz981** [comment]
> 如果图片尺寸会变换的话，就应该是动态shape，指定-1，-1；如果尺寸不变化，就指定hw就可以；请问下现在是设置了hw后，在pad后会报错是吗？

设置具体hw的话不会报错,但是设置shape =[None，3，None，None]会报错，就是上面那里的报错信息。试过设置shape =[None，3，-1，-1]也是因为用到了pad的问题,报错信息为以下：

```
Traceback (most recent call last):
  File "D:\miniconda\Lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-6439be594000>", line 11, in <module>
  File "D:\miniconda\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\dygraph\jit.py", line 649, in wrapper
    func(layer, path, input_spec, **configs)
  File "D:\miniconda\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\dygraph\base.py", line 67, in __impl__
    return func(*args, **kwargs)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\dygraph\jit.py", line 927, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "D:\miniconda\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 577, in concrete_program_specify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "D:\miniconda\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 485, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\miniconda\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 955, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 939, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "D:\miniconda\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\dygraph\base.py", line 67, in __impl__
    return func(*args, **kwargs)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 895, in from_func_spec
    error_data.raise_new_exception()
  File "D:\miniconda\Lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 350, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
TypeError: In transformed code:
    File "D:\python_Code_application\Python_program\run.py", line 161, in forward
	x = self.check_image_size(x)
    File "D:\python_Code_application\Python_program\run.py", line 154, in check_image_size

pad_h = (self.padder_size - h % self.padder_size) % self.padder_size
pad_w = (self.padder_size - w % self.padder_size) % self.padder_size
input = F.pad(input, [0, pad_w, 0, pad_h])
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
return input

  File "D:\miniconda\Lib\site-packages\paddle\nn\functional\common.py", line 1724, in pad
helper.append_op(
  File "D:\miniconda\Lib\site-packages\paddle\fluid\layer_helper.py", line 45, in append_op
return self.main_program.current_block().append_op(*args, **kwargs)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\framework.py", line 4017, in append_op
op = Operator(
  File "D:\miniconda\Lib\site-packages\paddle\fluid\framework.py", line 2991, in __init__
self._update_desc_attr(attr_name, attr_val)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\framework.py", line 3339, in _update_desc_attr
self._update_desc_plain_attr(name, val)
  File "D:\miniconda\Lib\site-packages\paddle\fluid\framework.py", line 3363, in _update_desc_plain_attr
desc._set_int32s_attr(name, val)

TypeError: _set_int32s_attr(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.fluid.libpaddle.OpDesc, arg0: str, arg1: List[int]) -> None

Invoked with: <paddle.fluid.libpaddle.OpDesc object at 0x000001DF935D1D70>, 'paddings', [0, var tmp_9 : 
LOD_TENSOR.shape(1,).dtype(int32).stop_gradient(False), 0, var tmp_4 : 
LOD_TENSOR.shape(1,).dtype(int32).stop_gradient(False), 0, 0]
```

**Comment by YanhuiDua** [comment]
你好，完整的最小复现代码麻烦提供一下

**Comment by wzz981** [comment]
> 你好,完整的最小复现代码麻烦提供一下

模型文件有点大传不了，我认为是pad问题，无法设置为-1，以下为使用到pad部分
```
class my_net(nn.Layer):
……
def check_image_size(self, x)
  pad_h = (self.padder_size - h % self.padder_size) % self.padder_size
  pad_w = (self.padder_size - w % self.padder_size) % self.padder_size
  input = F.pad(input, [0, pad_w, 0, pad_h])
return input

def forward(self, x):
  # x: 3, h, w
  # downsample
  B, C, H, W = x.shape
  x = self.check_image_size(x)
  x = ConvWithActivation(3, 32, kernel_size=4, stride=2, padding=1)  # 32, h/2,w/2
  x = ConvWithActivation(32, 32, kernel_size=3, stride=1, padding=1)
  ……
  return x
```

**Comment by wzz981** [comment]
> 你好,完整的最小复现代码麻烦提供一下

模型文件有点大传不了，我认为是pad问题，无法设置为-1，以下为使用到pad部分

```
class my_net(nn.Layer):
……
def check_image_size(self, input)
  pad_h = (self.padder_size - h % self.padder_size) % self.padder_size
  pad_w = (self.padder_size - w % self.padder_size) % self.padder_size
  input = F.pad(input, [0, pad_w, 0, pad_h])
return input

def forward(self, x):
  # x: 3, h, w
  # downsample
  B, C, H, W = x.shape
  x = self.check_image_size(x)
  x = ConvWithActivation(3, 32, kernel_size=4, stride=2, padding=1)  # 32, h/2,w/2
  x = ConvWithActivation(32, 32, kernel_size=3, stride=1, padding=1)
  ……
  return x

# 加载模型
model = my_net()
weights = paddle.load(model_path)
model.load_dict(weights)
model.eval()

static_mode = paddle.jit.to_static(model, input_spec=[InputSpec(shape=[None, 3, -1, -1], name='x')])
paddle.jit.save(static_mode, '/model')
```

**Comment by YanhuiDua** [comment]
你看，看报错像是pad输入类型不对，可以把模型与pad无关的部分删掉，重新save下model，然后把最小的复现代码和model发到我个人邮箱dyh10280@163.com，我帮你debug一下

**Comment by YanhuiDua** [comment]
你好，主要是因为pad的参数类型错误，可以参考下这个issue的解决方法：https://github.com/PaddlePaddle/Paddle/issues/52392

**Comment by wzz981** [comment]
> 你好,主要是因为衬垫的参数类型错误,可以参考下这个问题的解决方法：#52392

谢谢你的帮助，已经解决。我想知道这种自己训练出来的模型能否使用openvino加速呢，我尝试用openvino出现错误：
```
from openvino.runtime import Core,Dimension

model_dir = "./model"
model_file_path = model_dir + "/inference.pdmodel"
params_file_path = model_dir + "/inference.pdiparams"

# 初始化检测模型的Inference Engine
ie = Core()
net = ie.read_model(model=model_file_path, weights=params_file_path)
compiled_model = ie.compile_model(model=net, device_name="CPU")
```

报错信息如下：
```
Traceback (most recent call last):
  File "D:\miniconda\Lib\site-packages\IPython\core\interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-0e549f9539a9>", line 1, in <module>
    runfile('D:/python_Code_application/Python_program/test_openvino.py', wdir='D:/python_Code_application/Python_program/demo')
  File "D:\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm 2020.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/python_Code_application/Python_program/test_openvino.py", line 10, in <module>
    det_net = det_ie.read_model(model=det_model_file_path, weights=det_params_file_path)
RuntimeError: Check 'creator_it != CREATORS_MAP.end()' failed at C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\frontends\paddle\src\frontend.cpp:45:
FrontEnd API failed with OpConversionFailure: :
No creator found for set_value node.
```

**Comment by YanhuiDua** [comment]
你好，需要将inference model转换为onnx模型，再转换为openvino模型，具体参考https://github.com/PaddlePaddle/PaddleX/blob/f33e4a0d3227a5b7eda3676d2b59bde5a1fea19a/deploy/cpp/docs/compile/openvino/openvino_linux.md

**Comment by YanhuiDua** [comment]
你好，没有其他问题的话，这个issue先关闭了哈～有问题欢迎再提问~
