### ISSUE TITLE
安装cuda11.6版本的paddlepaddle 运行报错（ImportError: libcudartso.11.0: cannot open shared object file: No such file or directory）

### ISSUE THREAD

**Issue by zgz757183190** [PaddlePaddle/Paddle#53775]
### bug描述 Describe the Bug

版本信息：
  python:3.8
  conda:11.6

安装命令：
conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge 

代码测试：
import paddle
paddle.fluid.install_check.run_check()

报错信息：

Error: Can not import paddle core while this file exists: /home/yuan/anaconda3/envs/test_pp/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/home/yuan/PycharmProjects/test_pp/main.py", line 1, in <module>
    import paddle
  File "/home/yuan/anaconda3/envs/test_pp/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/yuan/anaconda3/envs/test_pp/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/yuan/anaconda3/envs/test_pp/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/yuan/anaconda3/envs/test_pp/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/yuan/anaconda3/envs/test_pp/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/yuan/anaconda3/envs/test_pp/lib/python3.8/site-packages/paddle/fluid/core.py", line 338, in <module>
    raise e
  File "/home/yuan/anaconda3/envs/test_pp/lib/python3.8/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

急急急急！！！！

大佬帮忙加急一下，万分感谢！！！！

**Comment by zgz757183190** [comment]
系统环境：

![image](https://github.com/PaddlePaddle/Paddle/assets/19298723/3b9fd8d2-8d57-41df-857b-2acc42508142)

**Comment by zgz757183190** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/19298723/bec3f601-f084-4a3c-a995-2d1b4919c739)

**Comment by zgz757183190** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/19298723/4d32178c-7da0-4284-b499-5bd71f0ed4f9)

**Comment by zgz757183190** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/19298723/035182aa-df25-420e-a1e0-3ae8a40968fd)

**Comment by zgz757183190** [comment]
还得靠自己！！！



出结果了，下次有铁子遇到请参考:  https://blog.csdn.net/qq_38308388/article/details/129528132

找到存在libcudart.so.11.0的位置，比如在/usr/local/cuda-11.X/lib64/位置下找到了该文件，则在命令框中添加路径即可，注意，一次有效，关闭该命令框之后再打开失效，若要一直有效，可以把这句加在bashrc里。

export LD_LIBRARY_PATH=/usr/local/cuda-11.X/lib64/:$LD_LIBRARY_PATH

**Comment by YanhuiDua** [comment]
你好，感谢贡献
