### ISSUE TITLE
安装完GPU版paddle2.4.2后，运行paddle.utils.run_check()，报错CUDA error(700)

### ISSUE THREAD

**Issue by sunze992** [PaddlePaddle/Paddle#53817]
### 问题描述 Issue Description

安装完GPU版paddle2.4.2后，想测试一下是否能够正常使用，运行paddle.utils.run_check()，报错CUDA error(700)

nvcc -V可以正确显示
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```

具体报错如下:
```
Running verify PaddlePaddle program ... 
W0515 17:40:51.843617 125232 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W0515 17:40:51.847362 125232 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/utils/install_check.py", line 174, in _run_static_single
    exe.run(train_prog,
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1450, in run
    res = self._run_impl(program=program,
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1661, in _run_impl
    return new_exe.run(scope, list(feed.keys()), fetch_list,
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 631, in run
    tensors = self._new_exe.run(scope, feed_names,
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/utils/install_check.py", line 174, in _run_static_single
      exe.run(train_prog,
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1450, in run
      res = self._run_impl(program=program,
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1639, in _run_impl
      program, new_exe = self._executor_cache.get_program_and_executor(
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 743, in get_program_and_executor
      return self._get_cached_program_and_executor(
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 782, in _get_program_and_executor
      program = _add_feed_fetch_ops(program=inner_program,
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 392, in _add_feed_fetch_ops
      global_block.append_op(type=fetch_op,
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/framework.py", line 4040, in append_op
      op = Operator(
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2879, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDA error(700), an illegal memory access was encountered. 
      [Hint: Please search for the error code(700) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:252)
      [operator < fetch_v2 > error]
>>> paddle.install_check.run_check()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'paddle' has no attribute 'install_check'
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/utils/install_check.py", line 173, in _run_static_single
    exe.run(startup_prog)
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1463, in run
    six.reraise(*sys.exc_info())
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1450, in run
    res = self._run_impl(program=program,
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1661, in _run_impl
    return new_exe.run(scope, list(feed.keys()), fetch_list,
  File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/executor.py", line 631, in run
    tensors = self._new_exe.run(scope, feed_names,
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/utils/install_check.py", line 269, in run_check
      _run_static_single(use_cuda, use_xpu, use_npu)
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/utils/install_check.py", line 159, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/utils/install_check.py", line 37, in _simple_network
      bias = paddle.create_parameter(shape=[3], dtype="float32")
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/layers/tensor.py", line 152, in create_parameter
      return helper.create_parameter(attr, shape, convert_dtype(dtype), is_bias,
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
      self.startup_program.global_block().create_parameter(
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/framework.py", line 3988, in create_parameter
      initializer(param, self)
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/initializer.py", line 56, in __call__
      return self.forward(param, block)
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/initializer.py", line 649, in forward
      op = block.append_op(type="uniform_random",
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/framework.py", line 4040, in append_op
      op = Operator(
    File "/home/sunze/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2879, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDA error(700), an illegal memory access was encountered. 
      [Hint: Please search for the error code(700) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/fluid/platform/device/gpu/gpu_info.cc:142)
      [operator < uniform_random > error]


```

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.4.2
Paddle With CUDA: True

OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: N/A
Libc version: glibc 2.31
Python version: 3.9.16

CUDA version: 11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
cuDNN version: N/A
Nvidia driver version: 510.73.05
Nvidia driver List: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

****************************************

**Comment by ghostxsl** [comment]
看报错信息，应该是环境没有配置好，建议使用paddle官方发布的docker试一下呢

**Comment by jimmyflycv** [comment]
i have got the same error log.
totally refer to the install guide.
