### ISSUE TITLE
2.4.2  gpu版本安装后train 报这个错误

### ISSUE THREAD

**Issue by yzzky** [PaddlePaddle/Paddle#53832]
### 请提出你的问题 Please ask your question

W0516 09:31:58.492738 18117 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "../../../tools/trainer.py", line 227, in <module>
    main(args)
  File "../../../tools/trainer.py", line 98, in main
    dy_model = dy_model_class.create_model(config)
  File "/data/paddle/PaddleRec/models/rank/wide_deep/dygraph_model.py", line 36, in create_model
    sparse_input_slot - 1, fc_sizes)
  File "/data/paddle/PaddleRec/models/rank/wide_deep/net.py", line 45, in __init__
    if paddle.is_compiled_with_custom_device('npu'):
AttributeError: module 'paddle' has no attribute 'is_compiled_with_custom_device'

**Comment by nemonameless** [comment]
请安装更高版本，如paddle develop版本，已自测过develop版本有paddle.is_compiled_with_custom_device
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
