### ISSUE TITLE
安装2.4.2版本完成以后运行 paddle.utils.run_check() 错误

### ISSUE THREAD

**Issue by niudakok** [PaddlePaddle/Paddle#53849]
### 问题描述 Issue Description

PS E:\python3.10> python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Python3.10\lib\site-packages\paddle\utils\install_check.py", line 270, in run_check
    _run_dygraph_single(use_cuda, use_xpu, use_npu)
  File "E:\Python3.10\lib\site-packages\paddle\utils\install_check.py", line 136, in _run_dygraph_single
    linear_out = linear(input_tensor)
  File "E:\Python3.10\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "E:\Python3.10\lib\site-packages\paddle\nn\layer\common.py", line 175, in forward
    out = F.linear(
  File "E:\Python3.10\lib\site-packages\paddle\nn\functional\common.py", line 1886, in linear
    return _C_ops.linear(x, weight, bias)
OSError: Invalid enum backend type `64`.
  [..\paddle/phi/common/backend.h:140]

### 版本&环境信息 Version & Environment Information

PS E:\python3.10> python summary_env.py
****************************************
Paddle version: 2.4.2
Paddle With CUDA: False

OS: Windows 10
GCC version: N/A
Clang version: N/A
CMake version: N/A
Libc version: N/A
Python version: 3.10.11

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by niudakok** [comment]
我安装的是cpu版的paddle
python -m pip install paddlepaddle==2.4.2 -i https://mirror.baidu.com/pypi/simple

**Comment by nemonameless** [comment]
你好，win平台可以安装最新的develop版本whl包试试

相关问题：https://github.com/PaddlePaddle/Paddle/issues/49964

**Comment by niudakok** [comment]
好的.谢谢解答 我装2.3.2版本试试

**Comment by niudakok** [comment]
2.3.2版本 在我电脑上安装检测通过!

**Comment by niudakok** [comment]
晚上又重新安装了最新的develop版本whl包 ,也检测通过了
