### ISSUE TITLE
麒麟V10  鲲鹏ARM  python3.8容器内编译完成后  导入模块  验证报错

### ISSUE THREAD

**Issue by wanghaocun** [PaddlePaddle/Paddle#53911]
### 问题描述 Issue Description

```bash
[100%] Built target paddle_python
root@host-192-168-1-28:/home/pp-build/Paddle/build# ls python/dist/
paddlepaddle-2.4.2-cp38-cp38-linux_aarch64.whl
root@host-192-168-1-28:/home/pp-build/Paddle/build# cd python/dist/
root@host-192-168-1-28:/home/pp-build/Paddle/build/python/dist# pip install -U paddlepaddle-2.4.2-cp38-cp38-linux_aarch64.whl
Processing ./paddlepaddle-2.4.2-cp38-cp38-linux_aarch64.whl
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.8/site-packages (from paddlepaddle==2.4.2) (1.24.3)
Requirement already satisfied: decorator in /usr/local/lib/python3.8/site-packages (from paddlepaddle==2.4.2) (5.1.1)
Requirement already satisfied: paddle-bfloat==0.1.7 in /usr/local/lib/python3.8/site-packages (from paddlepaddle==2.4.2) (0.1.7)
Requirement already satisfied: opt-einsum==3.3.0 in /usr/local/lib/python3.8/site-packages (from paddlepaddle==2.4.2) (3.3.0)
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.8/site-packages (from paddlepaddle==2.4.2) (2.30.0)
Requirement already satisfied: astor in /usr/local/lib/python3.8/site-packages (from paddlepaddle==2.4.2) (0.8.1)
Collecting protobuf<=3.20.0,>=3.1.0
  Downloading protobuf-3.20.0-cp38-cp38-manylinux2014_aarch64.whl (918 kB)
     |████████████████████████████████| 918 kB 154 kB/s
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: Pillow in /usr/local/lib/python3.8/site-packages (from paddlepaddle==2.4.2) (9.5.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/site-packages (from requests>=2.20.0->paddlepaddle==2.4.2) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/site-packages (from requests>=2.20.0->paddlepaddle==2.4.2) (2023.5.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.8/site-packages (from requests>=2.20.0->paddlepaddle==2.4.2) (2.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/site-packages (from requests>=2.20.0->paddlepaddle==2.4.2) (3.1.0)
Installing collected packages: six, protobuf, paddlepaddle
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.23.0
    Uninstalling protobuf-4.23.0:
      Successfully uninstalled protobuf-4.23.0
Successfully installed paddlepaddle-2.4.2 protobuf-3.20.0 six-1.16.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 23.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@host-192-168-1-28:/home/pp-build/Paddle/build/python/dist# python
Python 3.8.12 (default, Dec 21 2021, 07:14:57)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: /usr/local/lib/python3.8/site-packages/paddle/fluid/libpaddle.so: undefined symbol: shm_unlink

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/core.py", line 333, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined
>>> import paddle
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: /usr/local/lib/python3.8/site-packages/paddle/fluid/libpaddle.so: undefined symbol: shm_unlink

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/lib/python3.8/site-packages/paddle/fluid/core.py", line 333, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined
>>>
```

### 版本&环境信息 Version & Environment Information

root@host-192-168-1-28:/home/pp-build/Paddle/build/python/dist# python summary_env.py
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: debian 11
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: N/A
CMake version: version 3.16.8
Libc version: glibc 2.31
Python version: 3.8.12

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by tink2123** [comment]
尝试下将paddle完全卸载，然后重新安装

**Comment by wanghaocun** [comment]
> 尝试下将paddle完全卸载，然后重新安装

怎么算是完全卸载 ?

**Comment by tink2123** [comment]
`python -m pip list | grep paddle` 确认python环境下没有paddle

**Comment by hitzhu** [comment]
最后解决了吗问题

**Comment by wanghaocun** [comment]
> 最后解决了吗问题

没  最后还是在宿主机编译的
