### ISSUE TITLE
基于ERNIE1.0 预训练模型训练时报错

### ISSUE THREAD

**Issue by Zengfanxu1111** [PaddlePaddle/Paddle#53920]
### 请提出你的问题 Please ask your question

报错信息如下
Traceback (most recent call last):
  File "E:\Paddle-NLP项目\ERNIR-UIE\finetune.py", line 136, in <module>
    train()
  File "E:\Paddle-NLP项目\ERNIR-UIE\finetune.py", line 107, in train
    loss = paddle.mean(loss_fn(logits, labels))
  File "C:\Users\54367\miniconda3\envs\paddle_only\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\54367\miniconda3\envs\paddle_only\lib\site-packages\paddle\nn\layer\loss.py", line 377, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "C:\Users\54367\miniconda3\envs\paddle_only\lib\site-packages\paddle\nn\functional\loss.py", line 2566, in cross_entropy
    _, out = _C_ops.cross_entropy_with_softmax(
**ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:36 != labels_dims[i]:37.] (at ..\paddle\phi\infermeta\binary.cc:908)**
此前我打印了logits的shape和labels的shape：
epoch:0 - step:17 - loss: 1.706241
[36, 40, 61]
[36, 40]
epoch:0 - step:18 - loss: 1.421550
[36, 28, 61]
[36, 28]
epoch:0 - step:19 - loss: 1.938876
[36, 31, 61]
[36, 31]
epoch:0 - step:20 - loss: 1.720889
[36, 36, 61]
[36, 37]
在第20个step之后就会报这个错误，不是运行时马上就报
而且在paddle的BML codelab运行就不会报错，其他环境就会
原项目地址如下https://aistudio.baidu.com/aistudio/projectdetail/6191097?forkThirdPart=1

**Comment by minghaoBD** [comment]
你好，Paddle-NLP的项目建议去这里询问哈
https://github.com/PaddlePaddle/PaddleNLP/issues
