### ISSUE TITLE
PaddlePaddle 2.5 has multiple bugs with Ubuntu 22.04+CUDA 12.x

### ISSUE THREAD

**Issue by jeng1220** [PaddlePaddle/Paddle#53939]
## bug描述 Describe the Bug
因 NGC 統一升到 Ubuntu 22.04 + CUDA 12.1
我們測 Paddle 2.4 + Ubuntu 22.04 + CUDA 12.1 後 BRPC 報錯
根據 https://github.com/PaddlePaddle/Paddle/issues/52842 的建議，編譯加 `-Bsymbolic`
但因 BRPC 相關的 patch 基於 develop branch
和 Paddle 2.4 差異太大，故我們改用 Paddle 2.5 + Ubuntu 22.04 + CUDA 12.1 再測一次
結果測出更多的錯誤

## System Info ##
* PaddlePaddle v2.5.0-rc0(f55b387)
* OS/Ubuntu 22.04
* GCC 11.3.0
* Python 3.10.6
* CUDA 12.1.105
* NVIDIA Driver 525.85.12
* cuDNN 8.9.1.23
* NCCL 2.18.1
* TensorRT 8.6.1.2

## Device ##
* H100
* A100
* T4
* V100

## Bug list and Log ##
[paddlepaddle_v2.5.0-rc0_bugs.xlsx](https://github.com/PaddlePaddle/Paddle/files/11505926/paddlepaddle_v2.5.0-rc0_bugs.xlsx)

**Comment by Wong4j** [comment]
编译选项加上-Bsymbolic，可能会导致singleton实例化出错，Bug list表格中的`test_analysis_predictor`这个UT fail就是这个原因。

复现代码
//singleton.h
```
#pragma once
#include <iostream>

class MySingleton {
public:
    static MySingleton& getInstance() {
        static MySingleton instance;
        return instance;
    }
private:
    MySingleton() {
        std::cout << "MySingleton constructor" << std::endl;
    }
    ~MySingleton() {}
};
```
// foo.h
```
#include "singleton.h"
void foo();
```
// foo.cpp
```
#include "foo.h"
void foo() {
  MySingleton& singleton = MySingleton::getInstance();
}
```
// test.cpp
```
#include "foo.h"
int main() {
  foo();
  MySingleton& singleton = MySingleton::getInstance();
}
```
// compile and run
```
g++ -std=c++14 --shared -fPIC -o libfoo.so foo.cpp
g++ -std=c++14 -o test test.cpp -L. -lfoo
./test
```
不加-Wl,-Bsymbolic会调用一次ctor，加了-Wl,-Bsymbolic会调用两次ctor

**Comment by minghaoBD** [comment]
https://github.com/PaddlePaddle/Paddle/issues/52842 的后续问题

**Comment by jeng1220** [comment]
之所以編譯加 `-Bsymbolic` 是根據 https://github.com/PaddlePaddle/Paddle/issues/52842 的建議

**Comment by jeng1220** [comment]
1. 因使用 `-Bsymbolic` 會造成[更多問題](https://github.com/PaddlePaddle/Paddle/issues/52842#issuecomment-1552802571)，故其不是解決問題的方案
2. #54057 修復了部分問題
3. CMake 裡鏈接邏輯仍待解決，需避免[重複鏈接](https://github.com/PaddlePaddle/Paddle/issues/52842#issuecomment-1556478219)
4. numpy 版本不一致會導致 CI 錯誤, #54102

**Comment by jeng1220** [comment]
待 PaddlePaddle 2.5 正式版後，我們將重新測試

**Comment by jeng1220** [comment]
我們測試了最近的`release/2.5` branch (b01729b)，仍有 54 個錯誤

[bug_list_b01729b.xlsx](https://github.com/PaddlePaddle/Paddle/files/11726003/bug_list_b01729b.xlsx)

@tianshuo78520a ^^^

**Comment by jeng1220** [comment]
> 我們測試了最近的`release/2.5` branch (b01729b)，仍有 54 個錯誤
> 
> [bug_list_b01729b.xlsx](https://github.com/PaddlePaddle/Paddle/files/11726003/bug_list_b01729b.xlsx)
> 
> @tianshuo78520a ^^^

昨晚測了目前最新的 release/2.5 branch (4c820d5ea1f407eb685c127c45de0fdfd5ce00e3)，但問題依舊

更新: 附上每個錯誤的 log
[bug_list_4c820d5.xlsx](https://github.com/PaddlePaddle/Paddle/files/11730501/bug_list_4c820d5.xlsx)

**Comment by tianshuo78520a** [comment]
单测还在修复中

**Comment by jeng1220** [comment]
目前測試 release/2.5 (558ae9c) 仍有23 bugs:

[bug_list_558ae9c.xlsx](https://github.com/PaddlePaddle/Paddle/files/11891030/bug_list_558ae9c.xlsx)

**Comment by jeng1220** [comment]
目前測試最新的 release/2.5 ([1d8116a](https://github.com/PaddlePaddle/Paddle/commit/1d8116a5178f456aeb11e6c6d2617c4882ad25ab)) 仍有 27 bugs:
[bug_list_1d8116a.xlsx](https://github.com/PaddlePaddle/Paddle/files/11901225/bug_list_1d8116a.xlsx)

**Comment by jeng1220** [comment]
目前測試 release/2.5 branch 仍有 14 bugs:
[bug_list.csv](https://github.com/PaddlePaddle/Paddle/files/11970431/bug_list.csv)

**Comment by jeng1220** [comment]
最新的bug list:
```sh
                                                       0     1    2
test_collective_alltoall_api (Timeout)              A100   NaN  NaN
test_eig_op (Failed)                                A100  H100  NaN
test_imperative_out_scale (Failed)                  P100   NaN  NaN
test_post_training_quantization_mobilenetv1 (Fa...  A100   NaN  NaN
test_the_one_ps (Timeout)                           V100   NaN  NaN
test_trt_convert_multiclass_nms (Failed)              T4   NaN  NaN
test_trt_convert_pool2d (Timeout)                   A100  V100   T4
test_trt_convert_scale (Timeout)                    A100   NaN  NaN
```

**Comment by jeng1220** [comment]
目前 release/2.5 觀測到的 bugs:

* test_dataloader_dataset (Failed), V100
```
ERROR: Unexpected segmentation fault encountered in DataLoader workers.

Exception in thread Thread-3 (_thread_loop):
Traceback (most recent call last):
  File "/opt/paddle/paddle/build/python/paddle/io/dataloader/dataloader_iter.py", line 693, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 114, in get
test_dataloader_dataset failed
 ..E
======================================================================
ERROR: test_single_process (test_dataloader_dataset.TestDatasetWithDiffOutputPlace)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/paddle/paddle/build/test/legacy_test/test_dataloader_dataset.py", line 66, in test_single_process
    self.run_check_on_cpu()
  File "/opt/paddle/paddle/build/test/legacy_test/test_dataloader_dataset.py", line 60, in run_check_on_cpu
    for image, label in loader:
  File "/opt/paddle/paddle/build/python/paddle/io/dataloader/dataloader_iter.py", line 825, in __next__
    self._reader.read_next_list()[0]
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /opt/paddle/paddle/paddle/fluid/operators/reader/blocking_queue.h:171)
```

* test_eig_op_static_build (Failed), V100

```
Mismatched elements: 9 / 9 (100%)
Max absolute difference: 1.79374022
Max relative difference: 22.56094463
 x: array([[1.873247, 0.484213, 0.715022],
       [0.627915, 0.718921, 0.526067],
       [0.678937, 0.232749, 0.407832]])
 y: array([[0.079506, 0.43861 , 0.673699],
       [0.620497, 1.288239, 0.532555],
       [0.633102, 0.276989, 1.632255]])
```

* test_trt_convert_top_k_v2 (Failed), H100

```
Mismatched elements: 24 / 3072 (0.781%)
Max absolute difference: 23
Max relative difference: 5.25
 x: array([[[[ 8,  2, 17],
         [21, 14, 25],
         [ 9,  0, 24],...
 y: array([[[[ 8,  2, 17],
         [21, 14, 25],
         [ 9,  0, 24],...[0m
```

* test_communicator_geo (Failed), A100
```
ValueError: (InvalidArgument) The ret status must be 0 when barrier with table
  [Hint: Expected status == 0, but received status:-1 != 0:0.] (at /opt/paddle/paddle/paddle/fluid/distributed/ps/service/communicator/communicator.h:325)
```

**Comment by jeng1220** [comment]
目前release/2.5仍會看到 ~~3個~~ 2個測試會出錯

~~* test_trt_convert_multiclass_nms3~~
~~Mismatched elements: 300 / 480 (62.5%)~~
~~Max absolute difference: 16.~~
~~Max relative difference: 8.~~
~~x: array([[9.900e+01, 7.920e+03, 0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00],~~
~~[9.900e+01, 7.921e+03, 4.000e+00, 5.000e+00, 6.000e+00, 7.000e+00],~~
~~[9.900e+01, 7.922e+03, 8.000e+00, 9.000e+00, 1.000e+01, 1.100e+01],...~~
~~y: array([[9.900e+01, 7.920e+03, 8.000e+00, 9.000e+00, 1.000e+01, 1.100e+01],~~
~~[9.900e+01, 7.920e+03, 4.000e+00, 5.000e+00, 6.000e+00, 7.000e+00],~~
~~[9.900e+01, 7.920e+03, 0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00],...[0m~~
~~test_trt_convert_multiclass_nms3 failed~~

* test_trt_convert_multiclass_nms3，NVIDIA已發現原因並修正，會再提交PR


* test_trt_convert_swish，仍未知原因，且不好複現
```python
Mismatched elements: 7680 / 12288 (62.5%)
Max absolute difference: 0.95257413
Max relative difference: 1.
 x: array([[[0.952637, 0.952637, 0.952637, ..., 0.952637, 0.952637,
         0.952637],
        [0.952637, 0.952637, 0.952637, ..., 0.952637, 0.952637,...
 y: array([[[0.952574, 0.952574, 0.952574, ..., 0.952574, 0.952574,
         0.952574],
        [0.952574, 0.952574, 0.952574, ..., 0.952574, 0.952574,...[0m
test_trt_convert_swish failed
```

* test_communicator_geo，仍未知原因，且不好複現
```python
ERROR: test_communicator (test_communicator_geo.TestCommunicatorGeoEnd2End)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/paddle/paddle/build/test/legacy_test/test_communicator_geo.py", line 156, in test_communicator
    self.run_ut()
...
  File "/opt/paddle/paddle/build/python/paddle/distributed/communicator.py", line 198, in init_params
    self.communicator_.init_params(context)
ValueError: (InvalidArgument) The ret status must be 0 when barrier with table
  [Hint: Expected status == 0, but received status:-1 != 0:0.] (at /opt/paddle/paddle/paddle/fluid/distributed/ps/service/communicator/communicator.h:325)
```

**Comment by jeng1220** [comment]
近一週測試發現的錯誤:

* test_distribution_lognormal (Failed), A100
```python
Not equal to tolerance rtol=0.1, atol=0
Mismatched elements: 1 / 4 (25%)
Max absolute difference: 2.01486243e+08
Max relative difference: 0.13014176
 x: array([1.749692e+09, 1.723038e+02, 1.511067e+04, 1.652744e+02])
 y: array([1.548206e+09, 1.718550e+02, 1.498884e+04, 1.663073e+02])
```

*  test_triplet_margin_with_distance_loss (Failed), V100
```python
Not equal to tolerance rtol=1e-05, atol=1e-08
Mismatched elements: 1 / 5 (20%)
Max absolute difference: 1.37133538e-06
Max relative difference: 3.27540337e-05
 x: array([0.564523, 0.228575, 0.029713, 0.      , 0.924746])
 y: array([0.564522, 0.228577, 0.029714, 0.      , 0.924746])
```

test_trt_convert_top_k_v2 (Failed), H100
```python
Not equal to tolerance rtol=1e-08, atol=0.001
Mismatched elements: 21 / 4096 (0.513%)
Max absolute difference: 24
Max relative difference: 1.
 x: array([[[[ 7],
         [13],
         [29],...
 y: array([[[[ 7],
         [13],
         [29],...
```

* test_trt_convert_multiclass_nms (Failed), V100
```python
Not equal to tolerance rtol=1e-08, atol=0.01
Mismatched elements: 144 / 240 (60%)
Max absolute difference: 28.
Max relative difference: 8.
 x: array([[399.      ,   0.49875 ,   0.      ,   1.      ,   2.      ,
          3.      ],
       [399.      ,   0.498813,   4.      ,   5.      ,   6.      ,...
 y: array([[399.      ,   0.498779,   8.      ,   9.      ,  10.      ,
         11.      ],
       [399.      ,   0.498779,   4.      ,   5.      ,   6.      ,...
```

* test_communicator_geo (Failed), A100
```python
ValueError: (InvalidArgument) The ret status must be 0 when barrier with table
  [Hint: Expected status == 0, but received status:-1 != 0:0.] (at /opt/paddle/paddle/paddle/fluid/distributed/ps/service/communicator/communicator.h:325)
```

* test_custom_conj (Failed), V100
```python
Traceback (most recent call last):
  File "/opt/paddle/paddle/build/test/custom_op/test_custom_conj.py", line 33, in <module>
    custom_ops = load(
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/cpp_extension/cpp_extension.py", line 947, in load
    custom_op_api = _import_module_from_library(name, build_base_dir, verbose)
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/cpp_extension/extension_utils.py", line 976, in _import_module_from_library
    op_names = load_op_meta_info_and_register_op(ext_path)
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/cpp_extension/extension_utils.py", line 159, in load_op_meta_info_and_register_op
    core.load_op_meta_info_and_register_op(lib_filename)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (/root/.cache/paddle_extensions/custom_conj_jit/custom_conj_jit.so) that Paddle depends on is not configured correctly. (error code is /root/.cache/paddle_extensions/custom_conj_jit/custom_conj_jit.so: file too short)
```

* test_trt_convert_grid_sampler (Failed), A100
```python
Not equal to tolerance rtol=1e-08, atol=0.001
Mismatched elements: 5 / 27 (18.5%)
Max absolute difference: 0.00197434
Max relative difference: 0.00544222
 x: array([[[[0.434326, 0.186157, 0.771484],
         [0.519531, 0.542969, 0.54541 ],
         [0.620117, 0.246704, 0.633789]],...
 y: array([[[[0.434438, 0.186389, 0.773459],
         [0.518131, 0.541974, 0.544859],
         [0.620485, 0.247085, 0.633282]],...
```

* test_trt_convert_multiclass_nms3 (Failed), H100
```python
Not equal to tolerance rtol=1e-08, atol=0.01
Mismatched elements: 79 / 120 (65.8%)
Max absolute difference: 16.
Max relative difference: 4.
 x: array([[3.990e+02, 7.980e+03, 0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00],
       [3.990e+02, 7.981e+03, 4.000e+00, 5.000e+00, 6.000e+00, 7.000e+00],
       [3.990e+02, 7.982e+03, 8.000e+00, 9.000e+00, 1.000e+01, 1.100e+01],...
 y: array([[3.990e+02, 7.980e+03, 4.000e+00, 5.000e+00, 6.000e+00, 7.000e+00],
       [3.990e+02, 7.980e+03, 0.000e+00, 1.000e+00, 2.000e+00, 3.000e+00],
       [3.990e+02, 7.984e+03, 2.400e+01, 2.500e+01, 2.600e+01, 2.700e+01],...
```

* test_trt_convert_swish (Failed), H100
```python
Not equal to tolerance rtol=0.001, atol=0.001
Mismatched elements: 2048 / 12288 (16.7%)
Max absolute difference: 0.73105854
Max relative difference: 1.
 x: array([[[0.730957, 0.730957, 0.730957, ..., 0.730957, 0.730957,
         0.730957],
        [0.730957, 0.730957, 0.730957, ..., 0.730957, 0.730957,...
 y: array([[[0.731059, 0.731059, 0.731059, ..., 0.731059, 0.731059,
         0.731059],
        [0.731059, 0.731059, 0.731059, ..., 0.731059, 0.731059,...
```

* test_uniform_random_inplace_op (Failed), H100
```python
Not equal to tolerance rtol=0, atol=0.001
Mismatched elements: 1 / 10 (10%)
Max absolute difference: 0.00101786
Max relative difference: 0.0101786
 x: array([0.099745, 0.098982, 0.100159, 0.099927, 0.099751, 0.100425,
       0.100226, 0.100031, 0.100302, 0.100452], dtype=float32)
 y: array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])
```

* test_eig_op (Failed), A100
```python
Not equal to tolerance rtol=1e-05, atol=1e-05
Mismatched elements: 9 / 9 (100%)
Max absolute difference: 0.69208855
Max relative difference: 0.71385156
 x: array([[0.788521, 3.233261, 0.210453],
       [0.81322 , 1.108579, 0.854655],
       [0.50107 , 1.129663, 1.1029  ]])
 y: array([[1.48061 , 2.641189, 0.68328 ],
       [0.924399, 0.646835, 0.659329],
       [0.487099, 1.160397, 0.872556]])
```

**Comment by jeng1220** [comment]
@onecatcn,

The steps to reproduce:
1. 從 NGC 下載 PaddlePaddle container
```bash
$ docker pull nvcr.io/nvidia/paddlepaddle:23.08-py3
```
2. 進入 container
```bash
$ docker run -it --gpus all --net="host" --ipc=host nvcr.io/nvidia/paddlepaddle:23.08-py3 /bin/bash
```
3. 下載 PaddlePaddle 2.5 分支
```bash
$ git clone https://github.com/PaddlePaddle/Paddle.git
$ cd Paddle
$ git checkout release/2.5 -b release/2.5
```
4. 打上 PaddlePaddle 2.5 和 CUDA 12.2 兼容性補丁
```bash
$ git cherry-pick b2c797a
```
5. 編譯 PaddlePaddle 2.5 分支
```bash
$ export CCACHE_DIR="<your ccache path>"
$ export ARCH_FLAGS="-march=sandybridge -mtune=broadwell"
$ export CXX_FLAGS="$ARCH_FLAGS -Wno-error=range-loop-construct -Wno-error=maybe-uninitialized -Wno-error=switch -faligned-new=32"
$ export CUDA_FLAGS="-t2 --forward-unknown-to-host-compiler -Xfatbin=-compress-all $ARCH_FLAGS -lineinfo"

$ cmake -Bbuild -S. \
    -GNinja \
    -DINFERENCE_DEMO_INSTALL_DIR=<your dataset path> \
    -DCMAKE_CXX_FLAGS="$CXX_FLAGS" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_FLAGS="$CUDA_FLAGS" \
    -DCUDA_ARCH_NAME=Manual \
    -DCUDA_ARCH_BIN="70 80 90" \
    -DWITH_INCREMENTAL_COVERAGE=OFF \
    -DWITH_INFERENCE_API_TEST=ON \
    -DWITH_DISTRIBUTE=ON \
    -DWITH_COVERAGE=OFF \
    -DWITH_TENSORRT=ON \
    -DWITH_TESTING=ON \
    -DWITH_CONTRIB=ON \
    -DWITH_ROCM=OFF \
    -DWITH_RCCL=OFF \
    -DWITH_STRIP=ON \
    -DWITH_MKL=OFF \
    -DWITH_AVX=ON \
    -DWITH_GPU=ON \
    -DWITH_PYTHON=ON \
    -DWITH_CUDNN_FRONTEND=ON \
    -DPY_VERSION=$PYVER \
    -Wno-dev

$ time --verbose cmake --build ./build -j`nproc`
```
6. 編譯完成後安裝 PaddlePaddle 2.5
```bash
#建議先卸載預裝的paddlepaddle-gpu
$ sudo pip uninstall paddlepaddle-gpu 
$ sudo pip install ./build/python/dist/paddlepaddle_gpu-2.5.0-cp310-cp310-linux_x86_64.whl
```

7. 執行有錯誤的測試 (因錯誤是隨機發生，須執行多次才能觀察到錯誤)
```bash
$ cd build
$ ctest -R test_eig_op
```
建議寫個腳本執行測試多次，例如
```bash
#!/bin/bash

for i in {1..100};
do
    ctest -R test_eig_op
done
```
其他已觀察到的隨機錯:
```bash
$ ctest -R test_distribution_lognormal
$ ctest -R test_triplet_margin_with_distance_loss
$ ctest -R test_trt_convert_top_k_v2
$ ctest -R test_trt_convert_multiclass_nms
$ ctest -R test_communicator_geo
$ ctest -R test_custom_conj
$ ctest -R test_trt_convert_grid_sampler
$ ctest -R test_trt_convert_multiclass_nms3
$ ctest -R test_trt_convert_swish
$ ctest -R test_uniform_random_inplace_op
```

**Comment by onecatcn** [comment]
1. test_triplet_margin_with_distance_loss 
    develop: https://github.com/PaddlePaddle/Paddle/pull/57222 已合入
    release/2.5: https://github.com/PaddlePaddle/Paddle/pull/57254 待合入
2. test_uniform_random_inplace_op
    develop: https://github.com/PaddlePaddle/Paddle/pull/57225 已合入
    release/2.5: https://github.com/PaddlePaddle/Paddle/pull/57380 待合入
3. test_distribution_lognormal
    develop:https://github.com/PaddlePaddle/Paddle/pull/57320 已合入
    release/2.5:https://github.com/PaddlePaddle/Paddle/pull/57429 待合入

**Comment by sneaxiy** [comment]
@jeng1220 请问`test_communicator_geo`单测是否可以考虑临时disable掉？目前来看复现成本比较高，且属于Paddle的CPUPS功能，应该不影响NGC发版。

**Comment by jeng1220** [comment]
> @jeng1220 请问`test_communicator_geo`单测是否可以考虑临时disable掉？目前来看复现成本比较高，且属于Paddle的CPUPS功能，应该不影响NGC发版。

可以的，謝謝回覆

**Comment by jeng1220** [comment]
目前沒看到 test_custom_conj 有錯，故先關閉此issue
