### ISSUE TITLE
反向 tensor为空

### ISSUE THREAD

**Issue by HarperCy** [PaddlePaddle/Paddle#54039]
### bug描述 Describe the Bug

如题

Traceback (most recent call last):
  File "finetune_generation.py", line 239, in <module>
    main()
  File "finetune_generation.py", line 217, in main
    train_result = trainer.train(resume_from_checkpoint=last_checkpoint)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp-2.5.2.post0-py3.7.egg/paddlenlp/trainer/trainer.py", line 710, in train
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddlenlp-2.5.2.post0-py3.7.egg/paddlenlp/trainer/trainer.py", line 1473, in training_step
    loss.backward()
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 476, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/tensor_patch_methods.py", line 298, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
ValueError: (InvalidArgument) Required tensor shall not be nullptr, but received nullptr.
  [Hint: tensor should not be null.] (at /Paddle/eb/Paddle/paddle/phi/core/device_context.cc:142)

是一个可以在gpu上跑通的模型，切换的xpu就出现反向tensor为空的情况

**Comment by qili93** [comment]
Hi @HarperCy，

日志信息无法具体定位问题，请提供复现步骤以便定位具体问题

1. Paddle版本，包括commit id，可以通过 `python -c "import paddle; paddle.version.show()"` 命令获取
2. 可复现的最小代码，如果是飞桨开源套件的模型，请提供代码地址和运行命令即可
