### ISSUE TITLE
import torch后paddle报错OSError: (External) CUBLAS error(15).

### ISSUE THREAD

**Issue by linjieccc** [PaddlePaddle/Paddle#54063]
### bug描述 Describe the Bug

```python
import torch
import paddle

linear = paddle.nn.Linear(2, 4)
x = paddle.randn((3, 2), dtype="float32")
linear(x)
```

Traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/paddle/nn/layer/common.py", line 174, in forward
    out = F.linear(
  File "/root/anaconda3/lib/python3.10/site-packages/paddle/nn/functional/common.py", line 1842, in linear
    return _C_ops.linear(x, weight, bias)
OSError: (External) CUBLAS error(15). 
  [Hint: Please search for the error code(15) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at ../paddle/phi/kernels/funcs/blas/blas_impl.cu.h:37)
  [operator < linear > error]
```

### 其他补充信息 Additional Supplementary Information

版本信息：
```
paddle为nightly版本
torch == 2.0.1
```

**Comment by cuicheng01** [comment]
如果不引入torch不会有问题是吗？

**Comment by cuicheng01** [comment]
我这里测试没有问题哈，重新安装再试一下呢？
![image](https://github.com/PaddlePaddle/Paddle/assets/45199522/b952131e-d4cf-4656-9fc5-02f2db999718)

**Comment by linuxonly801** [comment]
我也是同样的错误。如果不引入torch是不会报错的。引入torch就会报错。
想问一下@cuicheng01，你的torch和paddle都是GPU版本的吗？
我这边发现，如果torch是GPU版本的，paddle是CPU版本的，是可以运行的。
但如果torch和paddle都是GPU版本的，就会报错。
