### ISSUE TITLE
The type of data we are trying to retrieve does not match the type of data currently contained in the container.

### ISSUE THREAD

**Issue by tangpanyu** [PaddlePaddle/Paddle#54101]
### 请提出你的问题 Please ask your question

`class Contrastive_head(nn.Layer):

    def __init__(self,num_patches,num_layers, input_dim, mlp_dim, output_dim, last_bn=True):
        super().__init__()
        mlp=[]
        for l in range(num_layers):
            dim1 = input_dim if l==0 else mlp_dim
            dim2 = output_dim if l== num_layers-1 else mlp_dim

            mlp.append(nn.Linear(dim1,dim2,bias_attr=False))

            if l <num_layers-1:
                mlp.append((nn.BatchNorm1D(num_patches)))
                mlp.append(nn.ReLU())

            elif last_bn:
                mlp.append(nn.BatchNorm1D(num_patches))
        self.mlp = nn.Sequential(*mlp)

    def forward(self, x):
        return self.mlp(x)`

Traceback (most recent call last):
  File "train.py", line 105, in <module>
    loss_c, loss_r = model(x1,x2,m=0.999,thre=0.5)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 774, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/models/builder.py", line 124, in forward
    slots,attn = self.encoder(x1)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/models/builder.py", line 47, in forward
    x0 = self.head0(x[0])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/models/builder.py", line 29, in forward
    return self.mlp(x)
 File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/models/builder.py", line 29, in forward
    return self.mlp(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py", line 725, in forward
    use_global_stats=self._use_global_stats,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/norm.py", line 233, in batch_norm
    False,
ValueError: (InvalidArgument) The type of data we are trying to retrieve does not match the type of data currently contained in the container.
  [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():15 != paddle::experimental::CppTypeToDataType<T>::Type():10.] (at /paddle/paddle/phi/core/dense_tensor.cc:143)

paddle版本2.40
python3.7
`for epoch in range(start_epoch,args.epochs):
    model.train()

    for batch,image in enumerate(train_loader):
        global_step = epoch * train_epoch_size + batch
        # image = image.cuda()
        x1,x2 = image[0].cuda(),image[1].cuda()
        with paddle.amp.auto_cast(custom_white_list={'elementwise_add'}, level='O1'):
            loss_c, loss_r = model(x1,x2,m=0.999,thre=thre)
            loss = loss_c + loss_r
        scaled = (scaler.scale(loss)).backward()
        for name,param in model.name_parameters():
            print(f'{name},{param.grad}')
        scaler.step(optim)
        scaler.update()
        scheduler.step()
        optim.clear_grad()`

**Comment by tangpanyu** [comment]
把这一段删掉能正常运行，用了混合精度训练的方式。

**Comment by cxxly** [comment]
问题解决了嘛，您的意思是不开自动混合精度没问题，开自动混合精度报错嘛，能否贴下完整代码

**Comment by tangpanyu** [comment]
> 问题解决了嘛，您的意思是不开自动混合精度没问题，开自动混合精度报错嘛，能否贴下完整代码

没有，不知道和混合精度有没有问题。用layernorm没事，用batchnorm1d就报这个问题

**Comment by cxxly** [comment]
麻烦能不能提供个可复现的代码，我本地复现下

**Comment by tangpanyu** [comment]
> 麻烦能不能提供个可复现的代码，我本地复现下

https://aistudio.baidu.com/aistudio/projectdetail/6222701?contributionType=1,我这半精度和batchnorm随便一个用的话读数据集也会报错

**Comment by cxxly** [comment]
batchnorm1d我这边没有复现

**Comment by cxxly** [comment]
抱歉，这个PR时间较长了，我先close；如果还有需求，再重新打开，另外，麻烦您尽量提供一个最小复现环境
