### ISSUE TITLE
训练模型时候报错constructorError: could not determine a constructor for the tag '!YOLOv5LRDecay'

### ISSUE THREAD

**Issue by weidazhaoooo** [PaddlePaddle/Paddle#54147]
### 请提出你的问题 Please ask your question

运行：!CUDA_VISIBLE_DEVICES=0 python tools/train.py -c configs/yolov5/yolov5_m_300e_coco.yml --eval --amp -o weights=../autodl-tmp/output/yolov5_m_300e_coco/model_final.pdparams --vdl_log_dir=../autodl-tmp/log_dir/yolov5_m_300e_coco时候
报错：
WARNING: OMP_NUM_THREADS set to 14, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
PLEASE USE OMP_NUM_THREADS WISELY.
Traceback (most recent call last):
  File "tools/train.py", line 198, in <module>
    main()
  File "tools/train.py", line 152, in main
    cfg = load_config(FLAGS.config)
  File "/root/PaddleDetection/ppdet/core/workspace.py", line 123, in load_config
    cfg = _load_config_with_base(file_path)
  File "/root/PaddleDetection/ppdet/core/workspace.py", line 101, in _load_config_with_base
    base_cfg = _load_config_with_base(base_yml)
  File "/root/PaddleDetection/ppdet/core/workspace.py", line 88, in _load_config_with_base
    file_cfg = yaml.load(f, Loader=yaml.Loader)
  File "/root/miniconda3/lib/python3.8/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 408, in construct_yaml_seq
    data.extend(self.construct_sequence(node))
  File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 129, in construct_sequence
    return [self.construct_object(child, deep=deep)
  File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 129, in <listcomp>
    return [self.construct_object(child, deep=deep)
  File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!YOLOv5LRDecay'
  in "configs/yolov5/_base_/optimizer_300e_high.yml", line 6, column 5

**Comment by Shixiaowei02** [comment]
您好，这个报错可能和 `env OMP_NUM_THREADS` 配置无关，这个环境变量只影响性能；请看下这个报错是如何导致的
```
File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 427, in construct_undefined
raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!YOLOv5LRDecay'
in "configs/yolov5/base/optimizer_300e_high.yml", line 6, column 5
```

**Comment by weiyaokun** [comment]
> ### 请提出你的问题 Please ask your question
> 运行：!CUDA_VISIBLE_DEVICES=0 python tools/train.py -c configs/yolov5/yolov5_m_300e_coco.yml --eval --amp -o weights=../autodl-tmp/output/yolov5_m_300e_coco/model_final.pdparams --vdl_log_dir=../autodl-tmp/log_dir/yolov5_m_300e_coco时候 报错： WARNING: OMP_NUM_THREADS set to 14, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads. PLEASE USE OMP_NUM_THREADS WISELY. Traceback (most recent call last): File "tools/train.py", line 198, in main() File "tools/train.py", line 152, in main cfg = load_config(FLAGS.config) File "/root/PaddleDetection/ppdet/core/workspace.py", line 123, in load_config cfg = _load_config_with_base(file_path) File "/root/PaddleDetection/ppdet/core/workspace.py", line 101, in _load_config_with_base base_cfg = _load_config_with_base(base_yml) File "/root/PaddleDetection/ppdet/core/workspace.py", line 88, in _load_config_with_base file_cfg = yaml.load(f, Loader=yaml.Loader) File "/root/miniconda3/lib/python3.8/site-packages/yaml/**init**.py", line 81, in load return loader.get_single_data() File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 51, in get_single_data return self.construct_document(node) File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 60, in construct_document for dummy in generator: File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 408, in construct_yaml_seq data.extend(self.construct_sequence(node)) File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 129, in construct_sequence return [self.construct_object(child, deep=deep) File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 129, in return [self.construct_object(child, deep=deep) File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 100, in construct_object data = constructor(self, node) File "/root/miniconda3/lib/python3.8/site-packages/yaml/constructor.py", line 427, in construct_undefined raise ConstructorError(None, None, yaml.constructor.ConstructorError: could not determine a constructor for the tag '!YOLOv5LRDecay' in "configs/yolov5/_base_/optimizer_300e_high.yml", line 6, column 5

请问您解决这个问题了吗

**Comment by weidazhaoooo** [comment]
您好 抱歉没有及时看到，已经解决了。重新安装了paddle
