### ISSUE TITLE
Paddle2.4.2的交叉熵维度计算问题

### ISSUE THREAD

**Issue by Zengfanxu1111** [PaddlePaddle/Paddle#54167]
### 请提出你的问题 Please ask your question

我在官方的环境中BML codelab用自己的数据集可以正常训练，但是在本地环境运行时会报如下错误
```
[36, 33, 57]
[36, 33]
Traceback (most recent call last):
  File "E:\Paddle-NLP项目\ERNIR-UIE\finetune.py", line 139, in <module>
    train()
  File "E:\Paddle-NLP项目\ERNIR-UIE\finetune.py", line 110, in train
    loss = paddle.mean(loss_fn(logits, labels)) 
  File "C:\Users\54367\miniconda3\envs\paddle_only\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\54367\miniconda3\envs\paddle_only\lib\site-packages\paddle\nn\layer\loss.py", line 377, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "C:\Users\54367\miniconda3\envs\paddle_only\lib\site-packages\paddle\nn\functional\loss.py", line 2566, in cross_entropy
    _, out = _C_ops.cross_entropy_with_softmax(
ValueError: (InvalidArgument) If Attr(soft_label) == true,  the axis dimension of Input(X) and Input(Label) should be equal.
  [Hint: Expected logits_dims[axis] == labels_dims[axis], but received logits_dims[axis]:57 != labels_dims[axis]:1.] (at ..\paddle\phi\infermeta\binary.cc:928)
```
其中[36, 33, 57]是logits的shape，[36，33]是labels的shape，我看了一下官方环境的paddle版本是2.3.2，我本地是2.4.2，不知道是不是版本的问题，如果是的话希望可以告知下2.4.2版本的解决方法，感激不尽。

**Comment by 2742195759** [comment]
麻烦确认一下呢：这里报错信息显示： but received logits_dims[axis]:57 != labels_dims[axis]:1，你的 labels_dims 索引到的结果时 1 。和你的打印结果不符合。还有就是麻烦附上这个 axis 的值和相关的代码？

**Comment by Zengfanxu1111** [comment]
=========axis相关代码如下：=======
ignore_label = -1
batchify_fn = lambda samples, fn=Tuple(
    Pad(axis=0, pad_val=tokenizer.pad_token_id),  # input_ids
    Pad(axis=0, pad_val=tokenizer.pad_token_type_id),  # token_type_ids
    Stack(),  # seq_len
    Pad(axis=0, pad_val=ignore_label)  # labels
): fn(samples)

train_loader = paddle.io.DataLoader(
    dataset=train_ds,
    batch_size=36,
    return_list=True,
    collate_fn=batchify_fn)
dev_loader = paddle.io.DataLoader(
    dataset=dev_ds,
    batch_size=36,
    return_list=True,
    collate_fn=batchify_fn)
test_loader = paddle.io.DataLoader(
    dataset=test_ds,
    batch_size=36,
    return_list=True,
    collate_fn=batchify_fn)
=================报错代码位置如下：==============
    for epoch in range(10):
        for idx, (input_ids, token_type_ids, length, labels) in enumerate(train_loader):
            logits = model(input_ids, token_type_ids)
            print(logits.shape)
            print(labels.shape)
            loss = paddle.mean(loss_fn(logits, labels)) 

==在打印了logits和labels的shape之后，在loss那一行报的错误=======

**Comment by 2742195759** [comment]
是不是开了 soft_label 呢，这个值默认是 False，但是报错显示你是True：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/cross_entropy_cn.html#cross-entropy
![image](https://github.com/PaddlePaddle/Paddle/assets/16025309/05ba9ba6-e291-4e8f-a1a2-1c6f4bd3c3a6)

**Comment by Zengfanxu1111** [comment]
修改之后解决了！谢谢你！因为之前在网上查softlabel的作用，我以为是多分类任务需要改成true，所以就改成true了，再次表示感谢！
