### ISSUE TITLE
AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

### ISSUE THREAD

**Issue by tangpanyu** [PaddlePaddle/Paddle#54269]
### 请提出你的问题 Please ask your question

`import os
import numpy as np
from PIL import Image
from paddle.io import Dataset
import paddle.vision.transforms as T
from pycocotools.coco import COCO

transforms_1 = T.Compose([
    T.RandomHorizontalFlip(),
    T.RandomResizedCrop(size=224,scale=(0.6,1.0),interpolation='bicubic'),
    T.ColorJitter(0.8,0.8,0.8,0.4),
    T.ToTensor(),
])
transforms_2 = T.Compose([
    T.RandomHorizontalFlip(),
    T.RandomResizedCrop(size=224,scale=(0.6,1.0),interpolation='bicubic'),
    T.ColorJitter(0.8,0.8,0.8,0.4),
    T.ToTensor(),
])
class CocoSegmentationDataset(Dataset):

    def __init__(self, root_dir, annotation_file, transforms_1=transforms_1, transforms_2 = transforms_2,training = True):
        super(CocoSegmentationDataset, self).__init__()
        self.root_dir = root_dir
        self.transforms_1 = transforms_1
        self.transforms_2 = transforms_2

        self.training = training
        self.coco = COCO(annotation_file)
        self.image_ids = list(sorted(self.coco.imgs.keys()))

    def __getitem__(self, idx):
        img_id = self.image_ids[idx]
        img_info = self.coco.loadImgs(img_id)[0]
        img_path = os.path.join(self.root_dir, img_info['file_name'])

        # Load image
        img = Image.open(img_path).convert('RGB')
        imag_1 = self.transforms_1(img)
        imag_2 = self.transforms_2(img)
        return (imag_1,imag_2)

    def __len__(self):
        return len(self.image_ids)

    def _generate_masks(self, annotations, image_size):
        masks = []
        for ann in annotations:
            mask = self.coco.annToMask(ann)
            mask = Image.fromarray(mask)
            mask = mask.resize(image_size, resample=Image.NEAREST)
            mask = np.array(mask)
            masks.append(mask)
        return masks
`
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/home/aistudio/datasets/coco_dataset.py", line 39, in __getitem__
    imag_1 = self.transforms_1(img)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/transforms.py", line 118, in __call__
    raise e
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/transforms.py", line 113, in __call__
    data = f(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/transforms.py", line 269, in __call__
    outputs.append(apply_func(inputs[i]))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/transforms.py", line 355, in _apply_image
    return F.to_tensor(img, self.data_format)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/functional.py", line 82, in to_tensor
    return F_pil.to_tensor(pic, data_format)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/functional_pil.py", line 88, in to_tensor
    img = paddle.to_tensor(np.array(pic, copy=False))
  File "<decorator-gen-163>", line 2, in to_tensor
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 433, in __impl__
    ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

W0601 14:32:52.737848  1587 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0601 14:32:52.740722  1587 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.

**Comment by tangpanyu** [comment]
加了paddle.disable_static()还是一样

**Comment by ZhangHandi** [comment]
> 加了paddle.disable_static()还是一样

请问paddle版本是什么呢？

**Comment by tangpanyu** [comment]
2.3.2,
2.4.1报错File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "/home/aistudio/datasets/coco_dataset.py", line 40, in __getitem__
    imag_1 = self.transforms_1(img)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 133, in __call__
    raise e
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 126, in __call__
    data = f(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 286, in __call__
    outputs.append(apply_func(inputs[i]))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 372, in _apply_image
    return F.to_tensor(img, self.data_format)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/functional.py", line 82, in to_tensor
    return F_pil.to_tensor(pic, data_format)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/functional_pil.py", line 88, in to_tensor
    img = paddle.to_tensor(np.array(pic, copy=False))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/tensor/creation.py", line 554, in to_tensor
    return _to_tensor_static(data, dtype, stop_gradient)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/tensor/creation.py", line 472, in _to_tensor_static
    output = assign(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/tensor/creation.py", line 1824, in assign
    raise TypeError(
TypeError: When the type of 'input' in assign is numpy.ndarray, the data type of 'input' must be bool, float32, int32 or int64, but received uint8.
前面的图片没问题,到了某一张就有问题了,ToTensor,我单独打印出来出问题的那张显示也没问题,不太懂

**Comment by tangpanyu** [comment]
fail to perform transform [<paddle.vision.transforms.transforms.ToTensor object at 0x7fe0786705e0>] with error: When the type of 'input' in assign is numpy.ndarray, the data type of 'input' must be bool, float32, int32 or int64, but received uint8. and stack:

**Comment by ZhangHandi** [comment]
看报错是读入的type有问题，可以尝试读入图片后用numpy.array指定一下type，看看是否报错

**Comment by tangpanyu** [comment]
> 看报错是读入的type有问题，可以尝试读入图片后用numpy.array指定一下type，看看是否报错
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/fluid/dataloader/fetcher.py", line 125, in fetch
    data.append(self.dataset[idx])
  File "/home/aistudio/datasets/coco_dataset.py", line 41, in __getitem__
    imag_1 = self.transforms_1(img)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 133, in __call__
    raise e
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 126, in __call__
    data = f(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 286, in __call__
    outputs.append(apply_func(inputs[i]))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 1049, in _apply_image
    return transform(img)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 133, in __call__
    raise e
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 126, in __call__
    data = f(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 286, in __call__
    outputs.append(apply_func(inputs[i]))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/transforms.py", line 828, in _apply_image
    return F.adjust_brightness(img, brightness_factor)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/functional.py", line 409, in adjust_brightness
    return F_cv2.adjust_brightness(img, brightness_factor)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.9/site-packages/paddle/vision/transforms/functional_cv2.py", line 318, in adjust_brightness
    return cv2.LUT(img, table)
cv2.error: OpenCV(4.6.0) /io/opencv/modules/core/src/lut.cpp:366: error: (-215:Assertion failed) (lutcn == cn || lutcn == 1) && _lut.total() == 256 && _lut.isContinuous() && (depth == CV_8U || depth == CV_8S) in function 'LUT'

**Comment by GSHZhang** [comment]
请问文件解决了吗

**Comment by SuperKsa** [comment]
这是该死的静态模式判断出现了问题。
解决的办法：
在你的代码逻辑即将送到paddle时加上`paddle.disable_static()`

意思是禁用静态模式，需要注意的是，一定要确保在【每次】代码执行时都能触发`paddle.disable_static()`，因为可能别的模块也在同时开启他。

触发错误的文件：/paddle/tensor/creation.py
具体的地方`def to_tensor()`：
`
    if in_dynamic_mode():
        return _to_tensor_non_static(data, dtype, place, stop_gradient)
`

你可以在每次运行时debug输出in_dynamic_mode()的值，即可明白我所说的，这个问题困扰了我将近三天。
我希望官方能考虑，这个模式应该由参数传入决定if的判断条件，建议修改如下：
1、给函数增加参数：
`
def to_tensor(data, dtype=None, place=None, stop_gradient=True, dynamic_mode=None):
     .......
     .......

     if dynamic_mode is None:  # 如果为None 则使用全局函数
           dynamic_mode = in_dynamic_mode()
     if dynamic_mode:
`
