### ISSUE TITLE
量化训练报(External) CUDNN error(14), CUDNN_STATUS_VERSION_MISMATCH

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/Paddle#54295]
### bug描述 Describe the Bug

我在做paddleslim量化训练时，报此错误。但是我做普通目标检测的训练时则没事
我的CUDA是11.6，CUDNN是8.4，也按照官方的对照关系，是正确的。但是在做paddleslim量化训练时还是报这个错误，具体信息如下
ppdet.data.source.coco INFO: Load [2220 samples valid, 1347 samples invalid] in file /home/deepiot/ai/dataset/coco/train.json.
W0602 10:01:17.182619  2125 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.6
W0602 10:01:17.184988  2125 gpu_resources.cc:149] device: 0, cuDNN Version: 8.4.
I0602 10:01:24.907119  2125 interpretercore.cc:237] New Executor is Running.
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
。。。。。。
2023-06-02 10:01:28,788-INFO: devices: gpu
2023-06-02 10:01:37,888-INFO: Selected strategies: ['qat_dis']
2023-06-02 10:01:46,315-INFO: train config.distill_node_pair: ['teacher_conv2d_305.tmp_1', 'conv2d_305.tmp_1', 'teacher_conv2d_309.tmp_0', 'conv2d_309.tmp_0', 'teacher_conv2d_312.tmp_1', 'conv2d_312.tmp_1', 'teacher_conv2d_316.tmp_0', 'conv2d_316.tmp_0', 'teacher_conv2d_319.tmp_1', 'conv2d_319.tmp_1', 'teacher_conv2d_323.tmp_0', 'conv2d_323.tmp_0']
2023-06-02 10:01:46,617-INFO: quant_aware config {'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max', 'weight_bits': 8, 'activation_bits': 8, 'not_quant_pattern': ['skip_quant'], 'quantize_op_types': ['conv2d', 'depthwise_conv2d', 'conv2d_transpose', 'mul', 'matmul', 'matmul_v2'], 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9, 'for_tensorrt': False, 'is_full_quantize': False, 'onnx_format': True, 'quant_post_first': False, 'scale_trainable': True, 'deploy_backend': None, 'name': 'Distillation', 'loss': 'l2', 'node': [], 'alpha': 1.0, 'teacher_model_dir': '/home/deepiot/ai/models/ppyoloe_plus_crn_l_80e_coco_animal8', 'teacher_model_filename': 'model.pdmodel', 'teacher_params_filename': 'model.pdiparams', 'quant_config': <paddle.static.quantization.quant_config.BaseQuantizer object at 0x7fa29afadaf0>}
Adding quant op with weight:|██████████████████████████████████████████| 468/468
Adding quant activation op:|███████████████████████████████████████████| 960/960
Adding OutScale op:|███████████████████████████████████████████████████| 464/464
2023-06-02 10:01:51,738-INFO: quant_aware config {'weight_quantize_type': 'channel_wise_abs_max', 'activation_quantize_type': 'moving_average_abs_max', 'weight_bits': 8, 'activation_bits': 8, 'not_quant_pattern': ['skip_quant'], 'quantize_op_types': ['conv2d', 'depthwise_conv2d', 'conv2d_transpose', 'mul', 'matmul', 'matmul_v2'], 'dtype': 'int8', 'window_size': 10000, 'moving_rate': 0.9, 'for_tensorrt': False, 'is_full_quantize': False, 'onnx_format': True, 'quant_post_first': False, 'scale_trainable': True, 'deploy_backend': None, 'name': 'Distillation', 'loss': 'l2', 'node': [], 'alpha': 1.0, 'teacher_model_dir': '/home/deepiot/ai/models/ppyoloe_plus_crn_l_80e_coco_animal8', 'teacher_model_filename': 'model.pdmodel', 'teacher_params_filename': 'model.pdiparams', 'quant_config': <paddle.static.quantization.quant_config.BaseQuantizer object at 0x7fa298a8c910>}
Adding quant op with weight:|████████████████████████████████████████| 1774/1774
Adding quant activation op:|█████████████████████████████████████████| 2266/2266
Adding OutScale op:|███████████████████████████████████████████████████| 929/929
I0602 10:02:42.918552  2125 interpreter_util.cc:518] Standalone Executor is Used.
Traceback (most recent call last):
  File "/home/deepiot/ai/PaddleSlim/example/auto_compression/detection/run.py", line 202, in <module>
    main()
  File "/home/deepiot/ai/PaddleSlim/example/auto_compression/detection/run.py", line 192, in main
    ac.compress()
  File "/home/deepiot/anaconda3/envs/paddle_slim/lib/python3.9/site-packages/paddleslim-0.0.0.dev0-py3.9.egg/paddleslim/auto_compression/compressor.py", line 586, in compress
  File "/home/deepiot/anaconda3/envs/paddle_slim/lib/python3.9/site-packages/paddleslim-0.0.0.dev0-py3.9.egg/paddleslim/auto_compression/compressor.py", line 780, in single_strategy_compress
  File "/home/deepiot/anaconda3/envs/paddle_slim/lib/python3.9/site-packages/paddleslim-0.0.0.dev0-py3.9.egg/paddleslim/auto_compression/compressor.py", line 799, in _start_train
  File "/home/deepiot/anaconda3/envs/paddle_slim/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1426, in run
    res = self._run_impl(
  File "/home/deepiot/anaconda3/envs/paddle_slim/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1658, in _run_impl
    ret = new_exe.run(
  File "/home/deepiot/anaconda3/envs/paddle_slim/lib/python3.9/site-packages/paddle/fluid/executor.py", line 654, in run
    tensors = self._new_exe.run(
OSError: (External) CUDNN error(14), CUDNN_STATUS_VERSION_MISMATCH. 
  [Hint: Please search for the error code(14) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at ../paddle/phi/kernels/gpudnn/pool_grad_kernel.cu:284)
  [operator < pool2d_grad > error]

**Comment by an1018** [comment]
执行paddle.utils.run_check()报错吗

**Comment by truthsun22** [comment]
> 执行paddle.utils.run_check()报错吗

找到原因了，官方说安装paddle，cuda11.6对应cudnn版本是8.4.0。但是我安装完paddle，查看conda list发现python安装的cudnn库是8.4.1的。于是我又从英伟达官方下载了8.4.1的CUDNN重新安装就不报错了。应该是官方paddle安装库里面cudnn版本对应有问题
