### ISSUE TITLE
跑paddlespeech流式语音合成的demo报错

### ISSUE THREAD

**Issue by dongchao139** [PaddlePaddle/Paddle#54472]
### bug描述 Describe the Bug

所用的demo:
```
https://github.com/PaddlePaddle/PaddleSpeech/blob/develop/demos/streaming_asr_server
```
环境;
- Windows版本: win10 22H2
- WSL版本: Ubuntu22.04
- Python版本:3.8
- Cuda版本: 11.7
- paddle版本: paddlepaddle-gpu==2.4.2.post117
- 显卡: NVIDIA GeForce 940MX
- 显卡驱动:
root@DESKTOP-N1VBR8B:/home/donnchao/netstar-paddle-service# nvidia-smi
Thu Jun  8 18:13:14 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.50                 Driver Version: 531.79       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce 940MX            On | 00000000:02:00.0 Off |                  N/A |
| N/A    0C    P8               N/A /  N/A|   1928MiB /  2048MiB |      7%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A       460      C   /python3.8                                N/A      |
|    0   N/A  N/A       619      C   /python3.8                                N/A      |
+---------------------------------------------------------------------------------------+

报错信息:
```txt
root@DESKTOP-N1VBR8B:/home/donnchao/netstar-paddle-service# python3 src/main.py
W0608 17:52:23.794795   619 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 5.0, Driver API Version: 12.1, Runtime API Version: 11.7
W0608 17:52:23.795691   619 gpu_resources.cc:91] device: 0, cuDNN Version: 8.8.
2023-06-08 17:52:24.173 | INFO     | paddlespeech.s2t.modules.embedding:__init__:150 - max len: 5000
[2023-06-08 17:52:32,734] [    INFO] - Already cached /root/.paddlenlp/models/bert-base-chinese/bert-base-chinese-vocab.txt
[2023-06-08 17:52:32,746] [    INFO] - tokenizer config file saved in /root/.paddlenlp/models/bert-base-chinese/tokenizer_config.json
[2023-06-08 17:52:32,746] [    INFO] - Special tokens file saved in /root/.paddlenlp/models/bert-base-chinese/special_tokens_map.json
[2023-06-08 17:52:34,041] [    INFO] - start to init the engine
[2023-06-08 17:52:34,042] [    INFO] - asr : online engine.
2023-06-08 17:52:38.759 | INFO     | paddlespeech.s2t.modules.embedding:__init__:150 - max len: 5000
[2023-06-08 17:52:44,145] [    INFO] - Initialize ASR server engine successfully on device: gpu:0.
INFO:     Started server process [619]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8090 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 38850) - "WebSocket /paddlespeech/asr/streaming" [accepted]
INFO:     connection open
[2023-06-08 17:56:20,669] [    INFO] - first and second beam size: 10, 10
[2023-06-08 17:56:20,669] [    INFO] - Endpont Opts: OnlineCTCEndpoingOpt(frame_shift_in_ms=10, blank=0, blank_threshold=0.8, rule1=OnlineCTCEndpointRule(must_contain_nonsilence=False, min_trailing_silence=5000, min_utterance_length=0), rule2=OnlineCTCEndpointRule(must_contain_nonsilence=True, min_trailing_silence=1000, min_utterance_length=0), rule3=OnlineCTCEndpointRule(must_contain_nonsilence=False, min_trailing_silence=0, min_utterance_length=20000))
[2023-06-08 17:56:21,283] [    INFO] - Online ASR extract the feat
[2023-06-08 17:56:22,313] [    INFO] - we will use the transformer like model : conformer_online_wenetspeech
[2023-06-08 17:56:22,314] [    INFO] - Online ASR extract the feat
[2023-06-08 17:56:22,330] [    INFO] - we will use the transformer like model : conformer_online_wenetspeech
[2023-06-08 17:56:22,331] [    INFO] - Online ASR extract the feat
[2023-06-08 17:56:22,347] [    INFO] - we will use the transformer like model : conformer_online_wenetspeech
[2023-06-08 17:56:22,348] [    INFO] - Online ASR extract the feat
[2023-06-08 17:56:22,363] [    INFO] - we will use the transformer like model : conformer_online_wenetspeech
[2023-06-08 17:56:22,364] [    INFO] - Online ASR extract the feat
[2023-06-08 17:56:22,381] [    INFO] - we will use the transformer like model : conformer_online_wenetspeech
[2023-06-08 17:56:22,381] [    INFO] - Online ASR extract the feat
[2023-06-08 17:56:22,401] [    INFO] - we will use the transformer like model : conformer_online_wenetspeech
[2023-06-08 17:56:22,402] [    INFO] - Online ASR extract the feat
[2023-06-08 17:56:22,421] [    INFO] - we will use the transformer like model : conformer_online_wenetspeech
[2023-06-08 17:56:22,421] [    INFO] - Online ASR extract the feat
[2023-06-08 17:56:22,444] [    INFO] - we will use the transformer like model : conformer_online_wenetspeech
[2023-06-08 17:56:22,444] [    INFO] - start to do model forward
[2023-06-08 17:56:29,403] [    INFO] - start to ctc prefix search
[2023-06-08 17:56:29,403] [    INFO] - effect first and second beam size: 10, 10
E0608 17:56:29.404129   619 top_k_function_cuda.h:1003] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
E0608 17:56:29.444546   619 top_k_function_cuda.h:1003] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
[2023-06-08 17:56:29,445] [   ERROR] - (OutOfRange) The starting index 34745229312 of slice is out of bounds in tensor 0-th axis, it shound be in the range of [-5538, 5538). (at /paddle/paddle/fluid/pybind/slice_utils.h:209)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 338, in decode
    self.advance_decoding(is_finished)
  File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 504, in advance_decoding
    self.searcher.search(ctc_probs, self.cached_feat.place)
  File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/server/engine/asr/online/ctc_search.py", line 108, in search
    ps = logp[s].item()
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 753, in __getitem__
    return self._getitem_index_not_tensor(item)
IndexError: (OutOfRange) The starting index 34745229312 of slice is out of bounds in tensor 0-th axis, it shound be in the range of [-5538, 5538). (at /paddle/paddle/fluid/pybind/slice_utils.h:209)

[2023-06-08 17:56:29,456] [    INFO] - Online ASR extract the feat
[2023-06-08 17:56:29,492] [    INFO] - we will use the transformer like model : conformer_online_wenetspeech
[2023-06-08 17:56:29,493] [    INFO] - start to do model forward
[2023-06-08 17:56:29,775] [    INFO] - start to ctc prefix search
[2023-06-08 17:56:29,775] [    INFO] - effect first and second beam size: 10, 10
E0608 17:56:29.776302   619 top_k_function_cuda.h:1003] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
E0608 17:56:29.805565   619 top_k_function_cuda.h:1003] TopKOP failed as could not launch cub::DeviceSegmentedRadixSort::SortPairsDescending to calculate temp_storage_bytes, status: invalid device function
[2023-06-08 17:56:29,806] [   ERROR] - (OutOfRange) The starting index 34394905088 of slice is out of bounds in tensor 0-th axis, it shound be in the range of [-5538, 5538). (at /paddle/paddle/fluid/pybind/slice_utils.h:209)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 338, in decode
    self.advance_decoding(is_finished)
  File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/server/engine/asr/online/python/asr_engine.py", line 504, in advance_decoding
    self.searcher.search(ctc_probs, self.cached_feat.place)
  File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/base.py", line 375, in _decorate_function
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddlespeech/server/engine/asr/online/ctc_search.py", line 108, in search
    ps = logp[s].item()
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 753, in __getitem__
    return self._getitem_index_not_tensor(item)
IndexError: (OutOfRange) The starting index 34394905088 of slice is out of bounds in tensor 0-th axis, it shound be in the range of [-5538, 5538). (at /paddle/paddle/fluid/pybind/slice_utils.h:209)
```

**Comment by andyjiang1116** [comment]
可以到 https://github.com/PaddlePaddle/PaddleSpeech 下面提问~

**Comment by juelietq** [comment]
问下解决了吗？运行paddle3D也遇见了这个问题
