### ISSUE TITLE
pyinstaller -D -w xxx.py 打包出错

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/Paddle#54471]
### bug描述 Describe the Bug

[libprotobuf FATAL third_party/protobuf-lite/common.cc:87] This program was compiled against version 3.1.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.14.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/paddle/build/paddle/fluid/framework/framework.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.1.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.14.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/paddle/build/paddle/fluid/framework/framework.pb.cc".)
Fatal Python error: Aborted

Current thread 0x00007f7bc0913740 (most recent call first):
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1166 in create_module
  File "<frozen importlib._bootstrap>", line 556 in module_from_spec
  File "<frozen importlib._bootstrap>", line 657 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1042 in _handle_fromlist
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/core.py", line 274 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 848 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1042 in _handle_fromlist
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 37 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 848 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1042 in _handle_fromlist
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/__init__.py", line 36 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 848 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/usr/local/lib/python3.8/dist-packages/paddle/framework/random.py", line 16 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 848 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1042 in _handle_fromlist
  File "/usr/local/lib/python3.8/dist-packages/paddle/framework/__init__.py", line 17 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 848 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "/usr/local/lib/python3.8/dist-packages/paddle/__init__.py", line 25 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 848 in exec_module
  File "<frozen importlib._bootstrap>", line 671 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 975 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 961 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 991 in _find_and_load
  File ".local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 178 in find_binary_dependencies
  File ".local/lib/python3.8/site-packages/PyInstaller/isolated/_child.py", line 63 in run_next_command
  File ".local/lib/python3.8/site-packages/PyInstaller/isolated/_child.py", line 96 in <module>
Traceback (most recent call last):
  File ".local/lib/python3.8/site-packages/PyInstaller/isolated/_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
  File ".local/lib/python3.8/site-packages/PyInstaller/isolated/_parent.py", line 293, in call
    ok, output = loads(b64decode(self._read_handle.readline()))
EOFError: EOF read where object expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".local/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File ".local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File ".local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File ".local/lib/python3.8/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File ".local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 1007, in main
    build(specfile, distpath, workpath, clean_build)
  File ".local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 929, in build
    exec(code, spec_namespace)
  File "lpsensorsto/FaPiao_OCR/textcurve_sim/towillamnmodel/SealDetOcr.spec", line 7, in <module>
    a = Analysis(
  File ".local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 429, in __init__
    self.__postinit__()
  File ".local/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File ".local/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 737, in assemble
    isolated.call(find_binary_dependencies, self.binaries, self.binding_redirects, collected_packages)
  File ".local/lib/python3.8/site-packages/PyInstaller/isolated/_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
  File ".local/lib/python3.8/site-packages/PyInstaller/isolated/_parent.py", line 247, in __exit__
    self._write_handle.flush()
BrokenPipeError: [Errno 32] Broken pipe

### 其他补充信息 Additional Supplementary Information

paddle 2.4.2 cuda 116

**Comment by andyjiang1116** [comment]
看报错是Protocol的版本问题，更新一下版本试试

**Comment by cqray1990** [comment]
> 看报错是Protocol的版本问题，更新一下版本试试

absl-py==1.3.0
addict==2.4.0
aiofiles==23.1.0
aiohttp==3.8.4
aiosignal==1.3.1
altair==4.2.2
altgraph==0.17.3
anyconfig==0.13.0
anyio==3.6.2
apex==0.1
appdirs==1.4.4
apturl==0.5.2
asgiref==3.6.0
astor==0.8.1
asttokens==2.2.1
astunparse==1.6.3
async-timeout==4.0.2
attrdict==2.0.1
attrs==22.2.0
Babel==2.12.1
backcall==0.2.0
# Editable install with no version control (bazierlib==0.1)
-e /home/lgx/lpsensorsto/FaPiao_OCR/textcurve_sim
bce-python-sdk==0.8.79
bcrypt==3.1.7
beautifulsoup4==4.11.1
blinker==1.4
Brlapi==0.7.0
Brotli==1.0.9
bs4==0.0.1
cachetools==5.2.0
certifi==2019.11.28
cffi==1.15.1
cfgv==3.3.1
chardet==3.0.4
charset-normalizer==3.0.1
click==8.1.3
colorama==0.4.3
coloredlogs==15.0.1
colorlog==6.7.0
command-not-found==0.3
commonmark==0.9.1
cryptography==2.8
cssselect==1.2.0
cssutils==2.6.0
cupshelpers==1.0
cycler==0.11.0
datasets==2.10.1
dbus-python==1.2.16
decorator==5.1.1
defer==1.0.6
dill==0.3.4
distlib==0.3.6
distro==1.4.0
distro-info===0.23ubuntu1
docker-pycreds==0.4.0
duplicity==0.8.12.0
easydict==1.10
entrypoints==0.3
et-xmlfile==1.1.0
executing==1.2.0
fast-tokenizer-python==1.0.2
fastapi==0.94.0
fastdeploy-gpu-python==1.0.6
fastdeploy-tools==0.0.5
fasteners==0.14.1
ffmpy==0.3.0
filelock==3.8.0
flake8==6.0.0
Flask==2.2.3
Flask-Babel==2.0.0
flatbuffers==2.0.7
fonttools==4.38.0
frozenlist==1.3.3
fsspec==2023.3.0
future==0.18.2
gast==0.4.0
gevent==22.10.2
geventhttpclient==2.0.2
gitdb==4.0.10
GitPython==3.1.30
google-auth==2.14.1
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
gradio==3.20.1
greenlet==2.0.2
grpcio==1.50.0
h11==0.12.0
h5py==3.7.0
hanlp==2.1.0b44
hanlp-common==0.0.19
hanlp-downloader==0.0.25
hanlp-trie==0.0.5
httpcore==0.15.0
httplib2==0.14.0
httpx==0.23.0
huggingface-hub==0.13.1
humanfriendly==10.0
identify==2.5.19
idna==2.8
imageio==2.22.4
imgaug==0.4.0
imgviz==1.5.1
importlib-metadata==5.0.0
importlib-resources==5.12.0
ipython==8.10.0
itsdangerous==2.1.2
jedi==0.18.2
jieba==0.42.1
Jinja2==3.1.2
jiwer==3.0.1
joblib==1.2.0
jsonschema==4.17.3
keras==2.10.0
Keras-Preprocessing==1.1.2
keyring==18.0.1
kiwisolver==1.4.4
labelImg==1.8.6
labelme==5.0.5
LAC==2.1.0
language-selector==0.1
lanms-neo==1.0.2
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
Levenshtein==0.20.8
libclang==14.0.6
linkify-it-py==2.0.0
lmdb==1.3.0
lockfile==0.12.2
loguru==0.6.0
louis==3.12.0
lxml==4.9.1
macaroonbakery==1.3.1
Mako==1.1.0
Markdown==3.4.1
markdown-it-py==2.2.0
MarkupSafe==2.1.1
matplotlib==3.2.2
matplotlib-inline==0.1.6
mccabe==0.7.0
mdit-py-plugins==0.3.3
mdurl==0.1.2
monotonic==1.5
mpmath==1.2.1
multidict==6.0.4
multiprocess==0.70.12.2
natsort==8.2.0
netifaces==0.10.4
netron==6.1.8
networkx==2.8.8
ninja==1.11.1
nltk==3.7
nodeenv==1.7.0
numpy==1.23.4
nvidia-pyindex==1.0.9
oauthlib==3.1.0
olefile==0.46
onnx==1.12.0
onnx-simplifier==0.4.10
onnxconverter-common==1.13.0
onnxmltools==1.11.2
onnxoptimizer==0.3.2
onnxruntime==1.13.1
opencv-contrib-python==4.2.0.34
opencv-python==4.2.0.34
openpyxl==3.1.2
opt-einsum==3.3.0
orjson==3.8.7
packaging==21.3
paddle-bfloat==0.1.7
paddle2onnx==1.0.5
paddlefsl==1.1.0
paddlenlp==2.5.2
paddlepaddle-gpu==2.4.2.post116
pandas==1.5.2
paramiko==2.6.0
parso==0.8.3
pathtools==0.1.2
pbr==5.11.1
pexpect==4.6.0
phrasetree==0.0.8
pickleshare==0.7.5
Pillow==8.4.0
pkgutil_resolve_name==1.3.10
platformdirs==3.1.0
Polygon3==3.0.9.1
pre-commit==3.1.1
premailer==3.10.0
presets==0.1.3
prettytable==3.6.0
promise==2.3
prompt-toolkit==3.0.36
protobuf==3.20.0
psutil==5.9.4
pure-eval==0.2.2
pyarrow==11.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycairo==1.16.2
pyclipper==1.3.0.post3
pycocotools==2.0.6
pycodestyle==2.10.0
pycorrector==0.4.6
pycparser==2.21
pycryptodome==3.17
pycuda==2022.2.2
pycups==1.9.73
pydantic==1.10.6
pydub==0.25.1
pyflakes==3.0.1
Pygments==2.13.0
PyGObject==3.36.0
pyinstaller==5.11.0
pyinstaller-hooks-contrib==2023.3
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
pynvml==11.4.1
pyparsing==3.0.9
pypinyin==0.47.1
PyQt5==5.15.4
pyqt5-plugins==5.15.4.2.2
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
pyqt5-tools==5.15.4.3.2
pyRFC3339==1.1
pyrsistent==0.19.3
python-apt==2.0.1+ubuntu0.20.4.1
python-dateutil==2.8.2
python-debian===0.1.36ubuntu1
python-docx==0.8.11
python-dotenv==0.21.0
python-multipart==0.0.6
python-rapidjson==1.9
pytools==2022.1.14
pytorch-quantization==2.1.2
pytz==2022.7.1
PyWavelets==1.4.1
pyxdg==0.26
PyYAML==5.3.1
qt5-applications==5.15.2.2.2
qt5-tools==5.15.2.1.2
QtPy==2.3.0
rapidfuzz==2.13.7
rarfile==4.0
regex==2022.10.31
reportlab==3.5.34
requests==2.28.2
requests-oauthlib==1.3.1
requests-unixsocket==0.2.0
responses==0.18.0
rfc3986==1.5.0
rich==12.6.0
rsa==4.9
sacremoses==0.0.53
scikit-image==0.19.3
scikit-learn==1.1.3
scipy==1.9.3
screen-resolution-extra==0.0.0
seaborn==0.12.1
SecretStorage==2.3.1
sentencepiece==0.1.97
sentry-sdk==1.12.1
seqeval==1.2.2
setproctitle==1.3.2
setuptools-scm==7.1.0
Shapely==1.8.5.post1
shortuuid==1.0.11
simplejson==3.16.0
sip==4.19.21
six==1.14.0
skl2onnx==1.14.0
smmap==5.0.0
sniffio==1.3.0
soupsieve==2.3.2.post1
sphinx-glpi-theme==0.3
ssh-import-id==5.10
stack-data==0.6.2
starlette==0.26.0.post1
sympy==1.11.1
systemd-python==234
tabulate==0.9.0
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-estimator==2.10.0
tensorflow-gpu==2.10.0
tensorflow-io-gcs-filesystem==0.27.0
tensorrt==8.5.2.2
termcolor==2.1.0
testresources==2.0.1
tf-slim==1.1.0
tf2onnx==1.13.0
thop==0.1.1.post2209072238
threadpoolctl==3.1.0
tifffile==2022.10.10
tokenizers==0.13.3
tomli==2.0.1
toolz==0.12.0
toposort==1.5
torch==1.13.1+cu116
torch-summary==1.4.5
torchaudio==0.13.1+cu116
torchinfo==1.8.0
torchstat==0.0.7
torchvision==0.14.1+cu116
tqdm==4.64.1
traitlets==5.9.0
transformers==4.24.0
tritonclient==2.31.0
typer==0.7.0
typing_extensions==4.4.0
ubuntu-advantage-tools==8001
ubuntu-drivers-common==0.0.0
uc-micro-py==1.0.1
uff==0.6.9
ufw==0.36
unattended-upgrades==0.1
urllib3==1.26.13
usb-creator==0.3.7
uvicorn==0.16.0
virtualenv==20.20.0
visualdl==2.0.0
wadllib==1.3.3
wandb==0.13.7
wcwidth==0.2.6
websocket-client==1.4.2
websockets==10.4
Werkzeug==2.2.2
wrapt==1.14.1
x2paddle==1.4.0
xkit==0.0.0
xlrd==1.2.0
xxhash==3.2.0
yarl==1.8.2
zipp==3.10.0
zope.event==4.6
zope.interface==5.5.2
安装paddle的时候自动回安装3.20.0的，这个环境就是打包不了奇怪

**Comment by andyjiang1116** [comment]
> This program was compiled against version 3.1.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.14.0)

可以再手动安装下这个库试试

**Comment by cqray1990** [comment]
> > This program was compiled against version 3.1.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.14.0)
> 
> 可以再手动安装下这个库试试

这个库不是已经有了？pip install protobuf?

**Comment by andyjiang1116** [comment]
> pip install protobuf?

在后面加上版本号

**Comment by cqray1990** [comment]
> > pip install protobuf?
> 
> 在后面加上版本号

paddle 需要 protobuf 3.20.0 如果 pip install protobuf==3.1,版本就和paddle不兼容

**Comment by andyjiang1116** [comment]
> > > pip install protobuf?
> > 
> > 
> > 在后面加上版本号
> 
> paddle 需要 protobuf 3.20.0 如果 pip install protobuf==3.1,版本就和paddle不兼容

试试降低下paddle版本
