### ISSUE TITLE
 paddle_serving_client 转换模型异常

### ISSUE THREAD

**Issue by Gxiaodiao** [PaddlePaddle/Paddle#54710]
### 请提出你的问题 Please ask your question

paddle_serving_client 版本是0.9.0
在转换的时候异常
代码如下：
`import paddle_serving_client.io as serving_io
serving_io.inference_model_to_serving("./output_model_recall/0", serving_server="./output_model_recall/serving_server", serving_client="./output_model_recall/serving_client",  model_filename="rec.pdopt", params_filename="rec_inference.pdiparams")
#serving_io.inference_model_to_serving("./output_model_recall/4", serving_server="serving_model", serving_client="client_conf",  model_filename=None, params_filename=None)`
异常信息：
`Traceback (most recent call last):
  File "convert_data.py", line 2, in <module>
    serving_io.inference_model_to_serving("./output_model_recall/0", serving_server="./output_model_recall/serving_server", serving_client="./output_model_recall/serving_client",  model_filename="rec.pdopt", params_filename="rec_inference.pdiparams")
  File "/root/miniconda3/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 334, in inference_model_to_serving
    fluid.io.load_inference_model(dirname=dirname, executor=exe, model_filename=model_filename, params_filename=params_filename)
  File "/root/miniconda3/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 558, in __impl__
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/io.py", line 1559, in load_inference_model
    program = Program.parse_from_string(program_desc_str)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 6301, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at /paddle/paddle/fluid/framework/program_desc.cc:143)`
麻烦帮忙看下，谢谢

**Comment by kuizhiqing** [comment]
根据以上信息无法判断问题，请提供更详细的背景和预期、与预期不符等信息。

**Comment by Gxiaodiao** [comment]
源码里面，电影这个demo，训练的召回模型，进行模型转换，提示出错：
InvalidArgumentError: Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 1904018048 found).
这是什么原因导致
