### ISSUE TITLE
代码没改，fitune 出错

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/Paddle#54722]
### bug描述 Describe the Bug

只是把代码拷贝另外的电脑训练，什么没改，搭建环境训练就出错

Traceback (most recent call last):
  File "/PaddleNLP/model_zoo/uie/finetune.py", line 262, in <module>
    main()
  File "/PaddleNLP/model_zoo/uie/finetune.py", line 193, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/anaconda3/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 716, in train
    self._maybe_log_save_evaluate(tr_loss, model, epoch, ignore_keys_for_eval, inputs=inputs)
  File "/anaconda3/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 810, in _maybe_log_save_evaluate
    tr_loss_scalar = self._nested_gather(tr_loss).mean().item()
  File "/anaconda3/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 1954, in _nested_gather
    tensors = distributed_concat(tensors)
  File "/anaconda3/lib/python3.9/site-packages/paddlenlp/trainer/utils/helper.py", line 45, in distributed_concat
    concat = paddle.concat(output_tensors, axis=0)
  File "/anaconda3/lib/python3.9/site-packages/paddle/tensor/manipulation.py", line 1121, in concat
    return _C_ops.concat(input, axis)
ValueError: (InvalidArgument) The axis is expected to be in range of [0, 0), but got 0
  [Hint: Expected axis >= -rank && axis < rank == true, but received axis >= -rank && axis < rank:0 != true:1.] (at ../paddle/phi/infermeta/multiary.cc:961)

I0617 11:36:27.897624 56351 tcp_store.cc:273] receive shutdown event and so quit from MasterDaemon run loop
LAUNCH INFO 2023-06-17 11:36:29,599 Exit code 1
[2023-06-17 11:36:29,599] [    INFO] controller.py:153 - Exit code 1

### 其他补充信息 Additional Supplementary Information

只是把代码拷贝另外的电脑训练，什么没改，搭建环境训练就出错

Traceback (most recent call last):
  File "/PaddleNLP/model_zoo/uie/finetune.py", line 262, in <module>
    main()
  File "/PaddleNLP/model_zoo/uie/finetune.py", line 193, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/anaconda3/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 716, in train
    self._maybe_log_save_evaluate(tr_loss, model, epoch, ignore_keys_for_eval, inputs=inputs)
  File "/anaconda3/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 810, in _maybe_log_save_evaluate
    tr_loss_scalar = self._nested_gather(tr_loss).mean().item()
  File "/anaconda3/lib/python3.9/site-packages/paddlenlp/trainer/trainer.py", line 1954, in _nested_gather
    tensors = distributed_concat(tensors)
  File "/anaconda3/lib/python3.9/site-packages/paddlenlp/trainer/utils/helper.py", line 45, in distributed_concat
    concat = paddle.concat(output_tensors, axis=0)
  File "/anaconda3/lib/python3.9/site-packages/paddle/tensor/manipulation.py", line 1121, in concat
    return _C_ops.concat(input, axis)
ValueError: (InvalidArgument) The axis is expected to be in range of [0, 0), but got 0
  [Hint: Expected axis >= -rank && axis < rank == true, but received axis >= -rank && axis < rank:0 != true:1.] (at ../paddle/phi/infermeta/multiary.cc:961)

I0617 11:36:27.897624 56351 tcp_store.cc:273] receive shutdown event and so quit from MasterDaemon run loop
LAUNCH INFO 2023-06-17 11:36:29,599 Exit code 1
[2023-06-17 11:36:29,599] [    INFO] controller.py:153 - Exit code 1

**Comment by FeixLiu** [comment]
感谢您的提问，稍后会有paddlenlp的同学来看具体的问题

**Comment by FeixLiu** [comment]
建议去paddlenlp的repo下提issue，https://github.com/PaddlePaddle/PaddleNLP ，这样问题的流转会更高效

**Comment by cqray1990** [comment]
> 建议去paddlenlp的repo下提issue，https://github.com/PaddlePaddle/PaddleNLP ，这样问题的流转会更高效
我安装的paddle版本 develop版本，不是paddlenlp的问题，但是我重新安装paddle2.4.2 又和fastdeploy的版本1.0.7不相配，可是我需要用这两个库 paddlenlp版本2.5.2，这几个库的版本有时候总是有问题
@FeixLiu

**Comment by FeixLiu** [comment]
> > 建议去paddlenlp的repo下提issue，https://github.com/PaddlePaddle/PaddleNLP ，这样问题的流转会更高效
> > 我安装的paddle版本 develop版本，不是paddlenlp的问题，但是我重新安装paddle2.4.2 又和fastdeploy的版本1.0.7不相配，可是我需要用这两个库 paddlenlp版本2.5.2，这几个库的版本有时候总是有问题
> > @FeixLiu

我的意思是，可能是一个paddlenlp的使用问题～在某些场景下没有正确使用套件导致的

**Comment by wawltor** [comment]
> > 建议去paddlenlp的repo下提issue，https://github.com/PaddlePaddle/PaddleNLP ，这样问题的流转会更高效
> > 我安装的paddle版本 develop版本，不是paddlenlp的问题，但是我重新安装paddle2.4.2 又和fastdeploy的版本1.0.7不相配，可是我需要用这两个库 paddlenlp版本2.5.2，这几个库的版本有时候总是有问题
> > @FeixLiu

如果是FD的一些兼容问题，建议在使用的时候直接使用Taskflow来做预测，因为Taskflow的预测部分直接使用训练的paddle版本，并且加速效果和FD基本一致，这样可以避免三个工具版本带来不兼容的问题

**Comment by kiangkiangkiang** [comment]
I had the same problem when using gpu for training with the cli: python -u -m paddle.distributed.launch --gpus "0,1,2,3" run_train.py

The problem is: ValueError: (InvalidArgument) The axis is expected to be in range of [0, 0), but got 0
  [Hint: Expected axis >= -rank && axis < rank == true, but received axis >= -rank && axis < rank:0 != true:1.] (at ../paddle/phi/infermeta/multiary.cc:961)
I0724 08:15:51.265156 16199 tcp_store.cc:273] receive shutdown event and so quit from MasterDaemon run loop
LAUNCH INFO 2023-07-24 08:15:52,223 Exit code 1

What I solved the problem is to downgrade the paddlepaddle-gpu (from 2.5.0 to 2.4.2.post116) using python -m pip install paddlepaddle-gpu==2.4.2.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

Hope that is helpful for you :)

**Comment by Celestine45m** [comment]
> python -m pip install paddlepaddle-gpu==2.4.2.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

有效，感谢
