### ISSUE TITLE
Paddle 高阶微分 broadcast 形状错误导致 backward 报错

### ISSUE THREAD

**Issue by HydrogenSulfate** [PaddlePaddle/Paddle#54742]
### bug描述 Describe the Bug

给 PaddleScience 添加 Stan 激活函数时发现该激活函数在高阶微分 hessian 下会报错

以下是最小复现代码
``` py
import paddle
from paddle import nn
from paddle.nn import functional as F


class Stan(nn.Layer):
    def __init__(self, out_features: int = 1):
        super().__init__()
        self.beta = self.create_parameter(
            shape=(out_features,),
            default_initializer=nn.initializer.Constant(1),
        )

    def forward(self, x):
        # TODO: manually broadcast beta to x.shape for preventing backward error yet.
        print(self.beta.shape, x.shape)
        # return F.tanh(x) * (1 + paddle.broadcast_to(self.beta, x.shape) * x) # 手动broadcast正常运行
        return F.tanh(x) * (1 + self.beta * x) # 自动broadcast则报错


def jacobian(y, x):
    return paddle.grad(y, x, create_graph=True)[0]


def hessian(y, x):
    return jacobian(jacobian(y, x), x)


model = nn.Sequential(
    nn.Linear(2, 1),
    Stan(1),
)

batch_size = 17
x, y = paddle.randn([batch_size, 1]), paddle.randn([batch_size, 1])
x.stop_gradient = False
y.stop_gradient = False

z = model(paddle.concat([x, y], axis=1))

loss = hessian(z, x) + hessian(z, y)

loss = loss.sum()

loss.backward()
```

``` log
W0619 07:59:27.617540 32501 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.8, Runtime API Version: 11.6
W0619 07:59:27.624457 32501 gpu_resources.cc:149] device: 0, cuDNN Version: 8.4.
[1] [17, 1]
Traceback (most recent call last):
  File "./test_stan.py", line 52, in <module>
    loss.backward()
  File "./anaconda3/envs/paddle_nightly_build/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "./anaconda3/envs/paddle_nightly_build/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "./anaconda3/envs/paddle_nightly_build/lib/python3.7/site-packages/paddle/fluid/framework.py", line 449, in __impl__
    return func(*args, **kwargs)
  File "./anaconda3/envs/paddle_nightly_build/lib/python3.7/site-packages/paddle/fluid/dygraph/tensor_patch_methods.py", line 298, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
ValueError: (InvalidArgument) The 0-th dimension of input tensor is expected to be equal with the 0-th dimension of output tensor 1 or 1, but received 17.
  [Hint: Expected in_dim[in_idx] == out_dims[in_idx] || in_dim[in_idx] == 1 == true, but received in_dim[in_idx] == out_dims[in_idx] || in_dim[in_idx] == 1:0 != true:1.] (at ../paddle/phi/kernels/funcs/dims_simplifier.h:144)
```

**Comment by GuoxiaWang** [comment]
`export GLOG_v=4`

在运行的shell脚本里加这个环境变量，然后看看 log 中执行到哪个  op 了。

**Comment by zhwesky2010** [comment]
@HydrogenSulfate 你好，请问是哪个版本出现的呢，是2.4吗
