### ISSUE TITLE
CenterOS 7  python3.6 安装 PaddlePaddle2.4报错

### ISSUE THREAD

**Issue by Swing00** [PaddlePaddle/Paddle#54853]
### 问题描述 Issue Description

安装过程无问题，验证时报错

`>>> import paddle
Error: Can not import paddle core while this file exists: /usr/local/python3/lib/python3.6/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/python3/lib/python3.6/site-packages/paddle/fluid/libpaddle.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/python3/lib/python3.6/site-packages/paddle/fluid/core.py", line 333, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined`

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: centos 7
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: N/A
CMake version: N/A
Libc version: glibc 2.17
Python version: 3.6.8

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by thisjiang** [comment]
> GLIBCXX_3.4.20' not found
> GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

看上去是环境问题，当前Paddle要求gcc 需要 5.4 以上，建议使用 8.2.0，详情见：
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html#anzhuangbiyaodegongju

这里更推荐您使用官方提供的docker来构建环境：
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html

**Comment by Swing00** [comment]
能否直接提供离线下载的镜像，内网环境pull不到

**Comment by thisjiang** [comment]
非常抱歉。docker并没有官方提供的离线镜像，不过您可以先在能联网的机器上通过docker pull拉下来镜像后，通过docker save保存docker镜像到本地，然后通过docker load -i来加载保存的镜像

**Comment by Swing00** [comment]
目前看来也只能这样了，后续有考虑提供吗

**Comment by thisjiang** [comment]
后续应该不会考虑提供离线镜像，不过您这个需求我可以反馈下~具体是否提供还需经过内部讨论评估后确认。您可以随时在docker hub查看paddle提供的最新镜像：https://hub.docker.com/r/paddlepaddle/paddle/tags

**Comment by Swing00** [comment]
好的，十分感谢
