### ISSUE TITLE
There are no kernels which are registered in the conv2d operator.

### ISSUE THREAD

**Issue by skye-z** [PaddlePaddle/Paddle#54915]
### 问题描述
我尝试使用`go`去调用`paddle`, 官方demo都可以正常运行, 但在`ppocr`引入后问题就来了
1. 输入`[]float32`: 这里需要使用`opencv`的`Mat`将图片读出为`[]float32`数据, 但是`opencv`中的`gflags`和`paddle`的冲突了, 当前使用的开发设备 **不具备自行编译** 的条件, 所以尝试不使用`opencv`
2. 输入`[]uint8`: 在不使用`opencv`的情况下, 使用`go`自带的`image`将图片读出为`[]uint8`数据, 此时程序可以运行到输入数据给`tensor`这一步, 然后报错如标题所示.

### 图片读出为`[]uint8`的代码
```go
// img对象从外部传入
rect := img.Bounds()
// 彩转灰度
rgba := image.NewGray(rect)
draw.Draw(rgba, rect, img, rect.Min, draw.Src)
// [此步报错] 将像素数据输入到 tensor
input.CopyFromCpu(rgba.Pix)
```
### 报错信息
```shell
[DET] Stert 2023-06-27 18:16:56
[DET] Input Image
libc++abi: terminating due to uncaught exception of type phi::enforce::EnforceNotMet: 

  Compile Traceback (most recent call last):
    File "tools/export_model.py", line 172, in <module>
      main()
    File "tools/export_model.py", line 165, in main
      sub_model_save_path, logger)
    File "tools/export_model.py", line 99, in export_single_model
      paddle.jit.save(model, save_path)
    File "<decorator-gen-101>", line 2, in save
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save
      inner_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-99>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 79, in forward
      x = self.backbone(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 146, in forward
      x = self.conv(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 179, in forward
      x = self.conv(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 677, in forward
      use_cudnn=self._use_cudnn)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 148, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------

----------------------
Error Message Summary:
----------------------
UnimplementedError: There are no kernels which are registered in the conv2d operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /Users/paddle/xly/workspace/compile_infer/Paddle/paddle/fluid/framework/operator.cc:2247)
  [operator < conv2d > error]
SIGABRT: abort
PC=0x7ff8099a61f2 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x100232730, 0xc00018fd38)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc00018fd10 sp=0xc00018fcd8 pc=0x100006a3c
github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi._Cfunc_PD_PredictorRun(0x100b04810)
        _cgo_gotypes.go:1329 +0x49 fp=0xc00018fd38 sp=0xc00018fd10 pc=0x10022e129
github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi.(*Predictor).Run.func1(0x0?)
        /Users/zhaoguiyang/go/pkg/mod/github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi@v0.0.0-20230619060011-feff99f5e164/predictor.go:145 +0x46 fp=0xc00018fd70 sp=0xc00018fd38 pc=0x10022f7e6
github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi.(*Predictor).Run(0x100304e80?)
        /Users/zhaoguiyang/go/pkg/mod/github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi@v0.0.0-20230619060011-feff99f5e164/predictor.go:145 +0x19 fp=0xc00018fd88 sp=0xc00018fd70 pc=0x10022f779
micro-ocr/ocr.(*GoDET).Run(0xc00018ff18, {0x100306278, 0xc000174680})
        /Users/zhaoguiyang/Desktop/Workspace/Golang/micro-ocr/ocr/det.go:39 +0x2f6 fp=0xc00018fee8 sp=0xc00018fd88 pc=0x100231296
main.runDemo()
        /Users/zhaoguiyang/Desktop/Workspace/Golang/micro-ocr/main.go:34 +0xb3 fp=0xc00018ff38 sp=0xc00018fee8 pc=0x1002317b3
main.main()
        /Users/zhaoguiyang/Desktop/Workspace/Golang/micro-ocr/main.go:25 +0x5d fp=0xc00018ff80 sp=0xc00018ff38 pc=0x1002316dd
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc00018ffe0 sp=0xc00018ff80 pc=0x100038b87
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc00018ffe8 sp=0xc00018ffe0 pc=0x100067b01

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000044fb0 sp=0xc000044f90 pc=0x100038fb6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000044fe0 sp=0xc000044fb0 pc=0x100038df0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000044fe8 sp=0xc000044fe0 pc=0x100067b01
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:293 +0x25

goroutine 18 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000040780 sp=0xc000040760 pc=0x100038fb6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:278 +0x8e fp=0xc0000407c8 sp=0xc000040780 pc=0x100025f4e
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000407e0 sp=0xc0000407c8 pc=0x10001b3c6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x100067b01
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 19 [GC scavenge wait]:
runtime.gopark(0xc00008e000?, 0x1003020d8?, 0x1?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000040f70 sp=0xc000040f50 pc=0x100038fb6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x100487da0)
        /usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000040fa0 sp=0xc000040f70 pc=0x100023e33
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:628 +0x45 fp=0xc000040fc8 sp=0xc000040fa0 pc=0x100024405
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000040fe0 sp=0xc000040fc8 pc=0x10001b366
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000040fe8 sp=0xc000040fe0 pc=0x100067b01
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 34 [finalizer wait]:
runtime.gopark(0x1a0?, 0x1004882c0?, 0xa0?, 0x41?, 0xc000044770?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000044628 sp=0xc000044608 pc=0x100038fb6
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000447e0 sp=0xc000044628 pc=0x10001a407
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000447e8 sp=0xc0000447e0 pc=0x100067b01
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:163 +0x45

rax    0x0
rbx    0x7ff84d0b1340
rcx    0x7ff7bfefe2f8
rdx    0x0
rdi    0x103
rsi    0x6
rbp    0x7ff7bfefe320
rsp    0x7ff7bfefe2f8
r8     0x7ff7bfefe1c0
r9     0x7ff80999b6fe
r10    0x0
r11    0x246
r12    0x103
r13    0x3000000008
r14    0x6
r15    0x16
rip    0x7ff8099a61f2
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
exit status 2
```

**Comment by FrostML** [comment]
可以用 netron 打开模型结构文件，看看模型的输入是需要什么数据类型的。最好是和模型本身要求的输入的数据类型匹配。

**Comment by skye-z** [comment]
> 可以用 netron 打开模型结构文件，看看模型的输入是需要什么数据类型的。最好是和模型本身要求的输入的数据类型匹配。

使用 `netron` 打开 `ch_PP-OCRv3_det_infer` 显示需要输入 `[]float32`, 数据转换后输入进去报 `The size of Op(Conv) inputs should not be 0.` 错误, 这应该不只是数据类型的问题

```shell
[DET] Input Image
libc++abi: terminating due to uncaught exception of type phi::enforce::EnforceNotMet: 

  Compile Traceback (most recent call last):
    File "tools/export_model.py", line 172, in <module>
      main()
    File "tools/export_model.py", line 165, in main
      sub_model_save_path, logger)
    File "tools/export_model.py", line 99, in export_single_model
      paddle.jit.save(model, save_path)
    File "<decorator-gen-101>", line 2, in save
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save
      inner_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-99>", line 2, in from_func_spec
      
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 79, in forward
      x = self.backbone(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 146, in forward
      x = self.conv(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/backbones/det_mobilenet_v3.py", line 179, in forward
      x = self.conv(x)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 677, in forward
      use_cudnn=self._use_cudnn)
    File "/usr/local/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 148, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/usr/local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The size of Op(Conv) inputs should not be 0.
  [Hint: Expected in_dims[i] != 0, but received in_dims[i]:0 == 0:0.] (at /Users/paddle/xly/workspace/compile_infer/Paddle/paddle/phi/infermeta/binary.cc:465)
  [operator < conv2d > error]
SIGABRT: abort
PC=0x7ff8099a61f2 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall]:
runtime.cgocall(0x10022b030, 0xc000052db0)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc000052d88 sp=0xc000052d50 pc=0x10000735c
github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi._Cfunc_PD_PredictorRun(0x100de09c0)
        _cgo_gotypes.go:1329 +0x49 fp=0xc000052db0 sp=0xc000052d88 pc=0x100226b29
github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi.(*Predictor).Run.func1(0x0?)
        /Users/zhaoguiyang/go/pkg/mod/github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi@v0.0.0-20230619060011-feff99f5e164/predictor.go:145 +0x46 fp=0xc000052de8 sp=0xc000052db0 pc=0x1002280e6
github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi.(*Predictor).Run(0x1002fc8c0?)
        /Users/zhaoguiyang/go/pkg/mod/github.com/paddlepaddle/paddle/paddle/fluid/inference/goapi@v0.0.0-20230619060011-feff99f5e164/predictor.go:145 +0x19 fp=0xc000052e00 sp=0xc000052de8 pc=0x100228079
micro-ocr/ocr.(*GoDET).Run(0xc000052f18, {0x1002fdc88, 0xc000174680})
        /Users/zhaoguiyang/Desktop/Workspace/Golang/micro-ocr/ocr/det.go:36 +0x18e fp=0xc000052ee8 sp=0xc000052e00 pc=0x1002298ee
main.runDemo()
        /Users/zhaoguiyang/Desktop/Workspace/Golang/micro-ocr/main.go:34 +0xb3 fp=0xc000052f38 sp=0xc000052ee8 pc=0x10022a0b3
main.main()
        /Users/zhaoguiyang/Desktop/Workspace/Golang/micro-ocr/main.go:25 +0x5d fp=0xc000052f80 sp=0xc000052f38 pc=0x100229fdd
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x207 fp=0xc000052fe0 sp=0xc000052f80 pc=0x1000394a7
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000052fe8 sp=0xc000052fe0 pc=0x100068421

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000044fb0 sp=0xc000044f90 pc=0x1000398d6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:305 +0xb0 fp=0xc000044fe0 sp=0xc000044fb0 pc=0x100039710
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000044fe8 sp=0xc000044fe0 pc=0x100068421
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:293 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000045780 sp=0xc000045760 pc=0x1000398d6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:319 +0xde fp=0xc0000457c8 sp=0xc000045780 pc=0x1000268be
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x26 fp=0xc0000457e0 sp=0xc0000457c8 pc=0x10001bce6
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000457e8 sp=0xc0000457e0 pc=0x100068421
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x6b

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xebdc9bf4885f6?, 0xb86793?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000045f70 sp=0xc000045f50 pc=0x1000398d6
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x10047bd60)
        /usr/local/go/src/runtime/mgcscavenge.go:400 +0x53 fp=0xc000045fa0 sp=0xc000045f70 pc=0x100024753
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:633 +0x65 fp=0xc000045fc8 sp=0xc000045fa0 pc=0x100024d45
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x26 fp=0xc000045fe0 sp=0xc000045fc8 pc=0x10001bc86
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x100068421
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xaa

goroutine 18 [finalizer wait]:
runtime.gopark(0x1a0?, 0x10047c280?, 0xa0?, 0x61?, 0xc000044770?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000044628 sp=0xc000044608 pc=0x1000398d6
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000447e0 sp=0xc000044628 pc=0x10001ad27
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000447e8 sp=0xc0000447e0 pc=0x100068421
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:163 +0x45

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000040750 sp=0xc000040730 pc=0x1000398d6
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000407e0 sp=0xc000040750 pc=0x10001d851
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x100068421
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 34 [GC worker (idle)]:
runtime.gopark(0xebdc9bf456622?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000092750 sp=0xc000092730 pc=0x1000398d6
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000927e0 sp=0xc000092750 pc=0x10001d851
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000927e8 sp=0xc0000927e0 pc=0x100068421
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 5 [GC worker (idle)]:
runtime.gopark(0xebdc9bf455489?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000046750 sp=0xc000046730 pc=0x1000398d6
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc0000467e0 sp=0xc000046750 pc=0x10001d851
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc0000467e8 sp=0xc0000467e0 pc=0x100068421
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x25

goroutine 6 [GC worker (idle)]:
runtime.gopark(0xebdc9bf4d982f?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xd6 fp=0xc000046f50 sp=0xc000046f30 pc=0x1000398d6
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xf1 fp=0xc000046fe0 sp=0xc000046f50 pc=0x10001d851
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1598 +0x1 fp=0xc000046fe8 sp=0xc000046fe0 pc=0x100068421
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x25

rax    0x0
rbx    0x7ff84d0b1340
rcx    0x7ff7bfefe2f8
rdx    0x0
rdi    0x103
rsi    0x6
rbp    0x7ff7bfefe320
rsp    0x7ff7bfefe2f8
r8     0x7ff7bfefe1c0
r9     0x7ff80999b6fe
```

**Comment by FrostML** [comment]
如果说模型的输入都已经提供还会出现类似的错误，可能需要结合的模型来分析下。
方便在 [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR/issues) 提一个 issue 吗，可以把当前的 issue 链接过去，看看 OCR 这边能否给些排查建议。

**Comment by skye-z** [comment]
> 如果说模型的输入都已经提供还会出现类似的错误，可能需要结合的模型来分析下。 方便在 [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR/issues) 提一个 issue 吗，可以把当前的 issue 链接过去，看看 OCR 这边能否给些排查建议。

好的, 非常感谢 🤝
