### ISSUE TITLE
分布式训练报错，Pod failed, Container failed

### ISSUE THREAD

**Issue by zoubaobao** [PaddlePaddle/Paddle#54979]
### 问题描述 Please describe your issue
=================
我正在使用Paddle尝试训练gpt3，执行如下训练脚本时报错
```
#!/bin/bash
set -x
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"
ulimit -c 0

export FLAGS_call_stack_level=2
python -u -m paddle.distributed.launch \
    --log_dir log_use_recompute_true \
    ./tools/train.py \
    -c ./ppfleetx/configs/nlp/gpt/pretrain_gpt_175B_mp8_pp16.yaml \
    -o Model.num_layers=6 \
    -o Model.use_fused_dropout_add=False \
    -o Distributed.mp_degree=8 \
    -o Distributed.pp_degree=1 \
    -o Engine.mix_precision.enable=True \
    -o Global.device=gpu \
    -o Global.local_batch_size=64 \
    -o Engine.max_steps=5
```
=================
### 错误信息如下：

```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
LAUNCH INFO 2023-06-29 02:33:04,325 -----------  Configuration  ----------------------
LAUNCH INFO 2023-06-29 02:33:04,325 auto_parallel_config: None
LAUNCH INFO 2023-06-29 02:33:04,325 auto_tuner_json: None
LAUNCH INFO 2023-06-29 02:33:04,325 devices: None
LAUNCH INFO 2023-06-29 02:33:04,325 elastic_level: -1
LAUNCH INFO 2023-06-29 02:33:04,325 elastic_timeout: 30
LAUNCH INFO 2023-06-29 02:33:04,325 gloo_port: 6767
LAUNCH INFO 2023-06-29 02:33:04,325 host: None
LAUNCH INFO 2023-06-29 02:33:04,325 ips: None
LAUNCH INFO 2023-06-29 02:33:04,325 job_id: default
LAUNCH INFO 2023-06-29 02:33:04,325 legacy: False
LAUNCH INFO 2023-06-29 02:33:04,325 log_dir: log_use_recompute_true
LAUNCH INFO 2023-06-29 02:33:04,326 log_level: INFO
LAUNCH INFO 2023-06-29 02:33:04,326 log_overwrite: False
LAUNCH INFO 2023-06-29 02:33:04,326 master: None
LAUNCH INFO 2023-06-29 02:33:04,326 max_restart: 3
LAUNCH INFO 2023-06-29 02:33:04,326 nnodes: 1
LAUNCH INFO 2023-06-29 02:33:04,326 nproc_per_node: None
LAUNCH INFO 2023-06-29 02:33:04,326 rank: -1
LAUNCH INFO 2023-06-29 02:33:04,326 run_mode: collective
LAUNCH INFO 2023-06-29 02:33:04,326 server_num: None
LAUNCH INFO 2023-06-29 02:33:04,326 servers: 
LAUNCH INFO 2023-06-29 02:33:04,326 sort_ip: False
LAUNCH INFO 2023-06-29 02:33:04,326 start_port: 6070
LAUNCH INFO 2023-06-29 02:33:04,326 trainer_num: None
LAUNCH INFO 2023-06-29 02:33:04,326 trainers: 
LAUNCH INFO 2023-06-29 02:33:04,326 training_script: ./tools/train.py
LAUNCH INFO 2023-06-29 02:33:04,326 training_script_args: ['-c', './ppfleetx/configs/nlp/gpt/pretrain_gpt_175B_mp8_pp16.yaml', '-o', 'Model.num_layers=6', '-o', 'Model.use_fused_dropout_add=False', '-o', 'Distributed.mp_degree=8', '-o', 'Distributed.pp_degree=1', '-o', 'Engine.mix_precision.enable=True', '-o', 'Global.device=gpu', '-o', 'Global.local_batch_size=64', '-o', 'Engine.max_steps=5']
LAUNCH INFO 2023-06-29 02:33:04,326 with_gloo: 1
LAUNCH INFO 2023-06-29 02:33:04,326 --------------------------------------------------
LAUNCH INFO 2023-06-29 02:33:04,327 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2023-06-29 02:33:04,328 Run Pod: nsllst, replicas 8, status ready
LAUNCH INFO 2023-06-29 02:33:04,414 Watching Pod: nsllst, replicas 8, status running
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py:401: UserWarning: PaddlePaddle version 2.3.0 or higher is required, but 0.0.0 installed, Maybe you are using a develop version, please make sure the version is good with your code.
A new field (use_fused_dropout_add) detected!
[2023-06-29 02:33:08,719] [    INFO] distributed_strategy.py:160 - distributed strategy initialized

I0629 02:33:08.720763 227962 tcp_utils.cc:181] The server starts to listen on IP_ANY:44130
I0629 02:33:08.720959 227962 tcp_utils.cc:130] Successfully connected to 172.17.0.4:44130
LAUNCH INFO 2023-06-29 02:33:13,426 Pod failed
LAUNCH ERROR 2023-06-29 02:33:13,426 Container failed !!!
Container rank 1 status failed cmd ['/usr/bin/python', '-u', './tools/train.py', '-c', './ppfleetx/configs/nlp/gpt/pretrain_gpt_175B_mp8_pp16.yaml', '-o', 'Model.num_layers=6', '-o', 'Model.use_fused_dropout_add=False', '-o', 'Distributed.mp_degree=8', '-o', 'Distributed.pp_degree=1', '-o', 'Engine.mix_precision.enable=True', '-o', 'Global.device=gpu', '-o', 'Global.local_batch_size=64', '-o', 'Engine.max_steps=5'] code -9 log log_use_recompute_true/workerlog.1 
env {'GREP_COLOR': '1;31', 'CUDNN_VERSION': '8.4.1', 'NV_LIBCUBLAS_DEV_VERSION': '11.10.1.25-1', 'NV_CUDA_COMPAT_PACKAGE': 'cuda-compat-11-7', 'LC_ALL': 'en_US.UTF-8', 'LD_LIBRARY_PATH': '/usr/local/lib/python3.7/dist-packages/cv2/../../lib64:/usr/local/cuda-11.7/targets/x86_64-linux/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64', 'LANG': 'en_US.UTF-8', 'NV_LIBNPP_DEV_PACKAGE': 'libnpp-dev-11-7=11.7.3.21-1', 'REMOTE_CONTAINERS': 'true', 'HOSTNAME': 'f7d31cafdebe', 'REMOTE_CONTAINERS_SOCKETS': '["/tmp/vscode-ssh-auth-e246606e-9435-47f8-98c7-21f8f8e71a99.sock","/root/.gnupg/S.gpg-agent"]', 'WITH_GPU': 'ON', 'COLORTERM': 'truecolor', 'VSCODE_GIT_ASKPASS_EXTRA_ARGS': '', 'NV_LIBNPP_VERSION': '11.7.3.21-1', 'NV_NVPROF_DEV_PACKAGE': 'cuda-nvprof-11-7=11.7.50-1', 'NVIDIA_VISIBLE_DEVICES': 'all', 'SSH_AUTH_SOCK': '/tmp/vscode-ssh-auth-e246606e-9435-47f8-98c7-21f8f8e71a99.sock', 'NV_NVPROF_VERSION': '11.7.50-1', 'NV_LIBCUSPARSE_VERSION': '11.7.3.50-1', 'NV_LIBCUBLAS_DEV_PACKAGE': 'libcublas-dev-11-7=11.10.1.25-1', 'FLAGS_call_stack_level': '2', 'GOPATH': '/root/gopath', 'PWD': '/root/fengchen03/gpt/gpt3/PaddleNLP/model_zoo/gpt-3', 'NVARCH': 'x86_64', 'HOME': '/root', 'NV_LIBCUSPARSE_DEV_VERSION': '11.7.3.50-1', 'GOROOT': '/usr/local/go', 'BROWSER': '/root/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/bin/helpers/browser.sh', 'VSCODE_GIT_ASKPASS_NODE': '/root/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/node', 'TERM_PROGRAM': 'vscode', 'CLICOLOR': '1', 'TERM_PROGRAM_VERSION': '1.79.2', 'DEBIAN_FRONTEND': 'noninteractive', 'NV_CUDA_LIB_VERSION': '11.7.0-1', 'REMOTE_CONTAINERS_IPC': '/tmp/vscode-remote-containers-ipc-e246606e-9435-47f8-98c7-21f8f8e71a99.sock', 'GREP_OPTIONS': '--color=auto', 'VSCODE_IPC_HOOK_CLI': '/tmp/vscode-ipc-8b9728a1-28de-4ad6-a718-6fb4cfb424b1.sock', 'NV_LIBNPP_PACKAGE': 'libnpp-11-7=11.7.3.21-1', 'LIBRARY_PATH': '/usr/local/cuda/lib64/stubs', 'NV_NVTX_VERSION': '11.7.50-1', 'NV_LIBCUBLAS_VERSION': '11.10.1.25-1', 'NV_LIBCUBLAS_PACKAGE': 'libcublas-11-7=11.10.1.25-1', 'NV_CUDA_CUDART_DEV_VERSION': '11.7.60-1', 'VSCODE_GIT_ASKPASS_MAIN': '/root/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/git/dist/askpass-main.js', 'SHELL': '/bin/bash', 'TERM': 'xterm-256color', 'NV_NVML_DEV_VERSION': '11.7.50-1', 'WITH_AVX': 'ON', 'CUDA_VERSION': '11.7.0', 'NV_LIBCUBLAS_PACKAGE_NAME': 'libcublas-11-7', 'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility', 'CUDA_VISIBLE_DEVICES': '0,1,2,3,4,5,6,7', 'SHLVL': '3', 'LANGUAGE': 'en_US.UTF-8', 'VSCODE_GIT_IPC_HANDLE': '/tmp/vscode-git-c6cc1beadc.sock', 'NV_LIBCUBLAS_DEV_PACKAGE_NAME': 'libcublas-dev-11-7', 'NVIDIA_REQUIRE_CUDA': 'cuda>=11.7 brand=tesla,driver>=450,driver<451 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=unknown,driver>=510,driver<511 brand=nvidia,driver>=510,driver<511 brand=nvidiartx,driver>=510,driver<511 brand=quadrortx,driver>=510,driver<511', 'NV_LIBNPP_DEV_VERSION': '11.7.3.21-1', 'NV_CUDA_CUDART_VERSION': '11.7.60-1', 'GIT_ASKPASS': '/root/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/git/dist/askpass.sh', 'PATH': '/root/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/bin/remote-cli:/home/cmake-3.16.0-Linux-x86_64/bin:/usr/local/gcc-8.2/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/gopath/bin', '_': '/usr/bin/python', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/usr/local/lib/python3.7/dist-packages/cv2/qt/plugins', 'QT_QPA_FONTDIR': '/usr/local/lib/python3.7/dist-packages/cv2/qt/fonts', 'POD_NAME': 'nsllst', 'PADDLE_MASTER': '172.17.0.4:44130', 'PADDLE_GLOBAL_SIZE': '8', 'PADDLE_LOCAL_SIZE': '8', 'PADDLE_GLOBAL_RANK': '1', 'PADDLE_LOCAL_RANK': '1', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '172.17.0.4:44131,172.17.0.4:44132,172.17.0.4:44133,172.17.0.4:44134,172.17.0.4:44135,172.17.0.4:44136,172.17.0.4:44137,172.17.0.4:44138', 'PADDLE_CURRENT_ENDPOINT': '172.17.0.4:44132', 'PADDLE_TRAINER_ID': '1', 'PADDLE_TRAINERS_NUM': '8', 'PADDLE_RANK_IN_NODE': '1', 'FLAGS_selected_gpus': '1'}
LAUNCH INFO 2023-06-29 02:33:13,426 ------------------------- ERROR LOG DETAIL -------------------------
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py:401: UserWarning: PaddlePaddle version 2.3.0 or higher is required, but 0.0.0 installed, Maybe you are using a develop version, please make sure the version is good with your code.
A new field (use_fused_dropout_add) detected!
[2023-06-29 02:33:07,935] [    INFO] distributed_strategy.py:160 - distributed strategy initialized

I0629 02:33:07.937285 227964 tcp_utils.cc:107] Retry to connect to 172.17.0.4:44130 while the server is not yet listening.
I0629 02:33:10.938038 227964 tcp_utils.cc:130] Successfully connected to 172.17.0.4:44130
LAUNCH INFO 2023-06-29 02:33:15,437 Exit code -15
```

--------
workerlog.2 报错如下
---------
```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py:401: UserWarning: PaddlePaddle version 2.3.0 or higher is required, but 0.0.0 installed, Maybe you are using a develop version, please make sure the version is good with your code.
A new field (use_fused_dropout_add) detected!
[2023-06-29 02:33:08,913] [    INFO] distributed_strategy.py:160 - distributed strategy initialized

##### Modified FLAGS detected
FLAGS(name='FLAGS_call_stack_level', current_value=2, default_value=1)
FLAGS(name='FLAGS_selected_gpus', current_value='5', default_value='')

I0629 02:33:08.914842 227972 tcp_utils.cc:130] Successfully connected to 172.17.0.4:44130
Traceback (most recent call last):
  File "./tools/train.py", line 48, in <module>
    env.init_dist_env(cfg)
  File "/root/fengchen03/gpt/gpt3/PaddleNLP/model_zoo/gpt-3/ppfleetx/distributed/apis/env.py", line 158, in init_dist_env
    hcg = comm_groups.create_hcg(strategy, hcg_name=config.Distributed.hcg)
  File "/root/fengchen03/gpt/gpt3/PaddleNLP/model_zoo/gpt-3/ppfleetx/distributed/apis/comm_groups.py", line 28, in create_hcg
    fleet.init(is_collective=True, strategy=strategy)
  File "/usr/local/lib/python3.7/dist-packages/paddle/distributed/fleet/fleet.py", line 305, in init
    paddle.distributed.init_parallel_env()
  File "/usr/local/lib/python3.7/dist-packages/paddle/distributed/parallel.py", line 1098, in init_parallel_env
    paddle.distributed.barrier(group=group)
  File "/usr/local/lib/python3.7/dist-packages/paddle/distributed/communication/group.py", line 328, in barrier
    task = group.process_group.barrier(device_id)
ValueError: 
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
```
0   paddle::distributed::ProcessGroupNCCL::Barrier(paddle::distributed::BarrierOptions const&)
1   paddle::distributed::ProcessGroupNCCL::AllReduce(phi::DenseTensor*, phi::DenseTensor const&, paddle::distributed::AllreduceOptions const&, bool, bool)
2   paddle::distributed::ProcessGroupNCCL::RunFnInNCCLEnv(std::function<void (ncclComm*, CUstream_st*)>, phi::DenseTensor const&, paddle::distributed::CommType, bool, bool)
3   paddle::distributed::ProcessGroupNCCL::CreateNCCLEnvCache(phi::Place const&, std::string const&)
4   paddle::distributed::ProcessGroupNCCL::BroadcastUniqueNCCLID(ncclUniqueId*)
5   phi::distributed::TCPStore::get(std::string const&)
6   phi::distributed::TCPStore::wait(std::string const&)
7   void phi::distributed::tcputils::receive_bytes<phi::distributed::ReplyType>(int, phi::distributed::ReplyType*, unsigned long)
8   phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
9   phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)
```

----------------------
Error Message Summary:
----------------------
```
InvalidArgumentError: TCP receive error. Details: Success.
  [Hint: Expected byte_received > 0, but received byte_received:0 <= 0:0.] (at ../paddle/phi/core/distributed/store/tcp_utils.h:107)
```

2，4，5，6卡都是这个错误
请问如何解决，感谢🙏

**Comment by ForFishes** [comment]
您好，看样子可能和环境有关。请测试一下：
`paddle.utils.run_check()`

**Comment by zouzy5137** [comment]
> 您好，看样子可能和环境有关。请测试一下： `paddle.utils.run_check()`

谢谢，刚才重新执行了脚本，又可以正常训练了。看起来是显卡间通信的问题。
