### ISSUE TITLE
test_post_training_quantization_resnet50 UT failed in Paddle 2.5

### ISSUE THREAD

**Issue by leo0519** [PaddlePaddle/Paddle#55034]
### bug描述 Describe the Bug

- 版本、环境信息：
    1. PaddlePaddle版本：2.5.0.post120
    2. CPU/GPU：A100
    3. Docker：paddlepaddle/paddle:2.5.0-gpu-cuda12.0-cudnn8.9-trt8.6
    4. Python版本号：3.10.12
    5. 显存信息

```bash
****************************************
Paddle version: 2.5.0
Paddle With CUDA: True

OS: ubuntu 20.04
GCC version: (GCC) 12.2.0
Clang version: 3.8.0 (tags/RELEASE_380/final)
CMake version: version 3.16.0
Libc version: glibc 2.31
Python version: 3.10.12

CUDA version: 12.0.140
Build cuda_12.0.r12.0/compiler.32267302_0
cuDNN version: N/A
Nvidia driver version: 525.105.17
Nvidia driver List:
GPU 0: NVIDIA A100-PCIE-40GB


****************************************
```

- 复现步骤

```bash
docker run -it --rm --gpus all paddlepaddle/paddle:2.5.0-gpu-cuda12.0-cudnn8.9-trt8.6 bash -c 'git clone https://github.com/PaddlePaddle/Paddle.git --branch release/2.5; python Paddle/test/quantization/test_post_training_quantization_resnet50.py'
```

-问题描述：请详细描述您的问题，同步贴出报错信息、日志/代码关键片段

錯誤 log 如下
```bash
λ 8398388b581d /home python Paddle/test/quantization/test_post_training_quantization_resnet50.py
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Cache file /root/.cache/paddle/dataset/int8/download/calibration_test_data.tar.gz not found, downloading http://paddle-inference-dist.bj.bcebos.com/int8/calibration_test_data.tar.gz
Begin to download
item 3307/3307 [============================>.] - ETA: 0s - 8ms/item
Download finished
Data is downloaded at /root/.cache/paddle/dataset/int8/download/calibration_test_data.tar.gz
Cache file /root/.cache/paddle/dataset/int8/download/resnet50_int8_model_combined.tar.gz not found, downloading http://paddle-inference-dist.bj.bcebos.com/int8/resnet50_int8_model_combined.tar.gz
Begin to download
item 23232/23232 [============================>.] - ETA: 0s - 5ms/item
Download finished
Data is downloaded at /root/.cache/paddle/dataset/int8/download/resnet50_int8_model_combined.tar.gz
Start FP32 inference for ResNet-50 on 100 images ...
Fri Jun 30 06:43:33-WARNING: The old way to load inference model is deprecated. model path: /root/.cache/paddle/dataset/int8/download/ResNet-50/MobileNetV1_infer/model.pdmodel, params path: /root/.cache/paddle/dataset/int8/download/ResNet-50/MobileNetV1_infer/model.pdiparams
EData is downloaded at /root/.cache/paddle/dataset/int8/download/calibration_test_data.tar.gz
Data is downloaded at /root/.cache/paddle/dataset/int8/download/resnet50_int8_model_combined.tar.gz
Start FP32 inference for ResNet-50 on 100 images ...
Fri Jun 30 06:43:34-WARNING: The old way to load inference model is deprecated. model path: /root/.cache/paddle/dataset/int8/download/ResNet-50/MobileNetV1_infer/model.pdmodel, params path: /root/.cache/paddle/dataset/int8/download/ResNet-50/MobileNetV1_infer/model.pdiparams
E
======================================================================
ERROR: test_post_training_resnet50 (__main__.TestPostTrainingForResnet50)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/test/quantization/test_post_training_quantization_resnet50.py", line 40, in test_post_training_resnet50
    self.run_test(
  File "/home/Paddle/test/quantization/test_post_training_quantization_mobilenetv1.py", line 344, in run_test
    (fp32_throughput, fp32_latency, fp32_acc1) = self.run_program(
  File "/home/Paddle/test/quantization/test_post_training_quantization_mobilenetv1.py", line 218, in run_program
    ] = paddle.static.load_inference_model(
  File "/usr/local/lib/python3.10/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/framework.py", line 473, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/static/io.py", line 849, in load_inference_model
    program_bytes = load_from_file(model_path)
  File "/usr/local/lib/python3.10/dist-packages/paddle/static/io.py", line 721, in load_from_file
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/paddle/dataset/int8/download/ResNet-50/MobileNetV1_infer/model.pdmodel'

======================================================================
ERROR: test_post_training_resnet50 (__main__.TestPostTrainingForResnet50ONNXFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/Paddle/test/quantization/test_post_training_quantization_resnet50.py", line 71, in test_post_training_resnet50
    self.run_test(
  File "/home/Paddle/test/quantization/test_post_training_quantization_mobilenetv1.py", line 344, in run_test
    (fp32_throughput, fp32_latency, fp32_acc1) = self.run_program(
  File "/home/Paddle/test/quantization/test_post_training_quantization_mobilenetv1.py", line 218, in run_program
    ] = paddle.static.load_inference_model(
  File "/usr/local/lib/python3.10/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/framework.py", line 473, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/static/io.py", line 849, in load_inference_model
    program_bytes = load_from_file(model_path)
  File "/usr/local/lib/python3.10/dist-packages/paddle/static/io.py", line 721, in load_from_file
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/paddle/dataset/int8/download/ResNet-50/MobileNetV1_infer/model.pdmodel'

----------------------------------------------------------------------
Ran 2 tests in 146.317s

FAILED (errors=2)
```

初步調查是因 test_post_quantization_mobilenetv1 UT 當中 [L345](https://github.com/PaddlePaddle/Paddle/blob/develop/test/quantization/test_post_training_quantization_mobilenetv1.py#L345) 和 [L353](https://github.com/PaddlePaddle/Paddle/blob/develop/test/quantization/test_post_training_quantization_mobilenetv1.py#L353) 模型路徑寫死，導致 test_post_quantization_resnet50 import 該 class 後找不到模型

路徑問題處理後會發現第二個 bug 如下
```bash
======================================================================
ERROR: test_post_training_resnet50 (__main__.TestPostTrainingForResnet50)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/paddle/paddle/build/test/quantization/test_post_training_quantization_resnet50.py", line 41, in test_post_training_resnet50
    self.run_test(
  File "/opt/paddle/paddle/build/test/quantization/test_post_training_quantization_mobilenetv1.py", line 345, in run_test
    (fp32_throughput, fp32_latency, fp32_acc1) = self.run_program(
  File "/opt/paddle/paddle/build/test/quantization/test_post_training_quantization_mobilenetv1.py", line 238, in run_program
    pred = exe.run(
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 1392, in run
    res = self._run_impl(
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 1583, in _run_impl
    program, new_exe = self._executor_cache.get_program_and_executor(
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 759, in get_program_and_executor
    return self._get_cached_program_and_executor(
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 826, in _get_program_and_executor
    program = _add_feed_fetch_ops(
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 378, in _add_feed_fetch_ops
    if not has_feed_operators(global_block, feed, feed_var_name):
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 291, in has_feed_operators
    raise Exception(
Exception: 'feed_targets' does not have label variable

======================================================================
ERROR: test_post_training_resnet50 (__main__.TestPostTrainingForResnet50ONNXFormat)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/paddle/paddle/build/test/quantization/test_post_training_quantization_resnet50.py", line 74, in test_post_training_resnet50
    self.run_test(
  File "/opt/paddle/paddle/build/test/quantization/test_post_training_quantization_mobilenetv1.py", line 345, in run_test
    (fp32_throughput, fp32_latency, fp32_acc1) = self.run_program(
  File "/opt/paddle/paddle/build/test/quantization/test_post_training_quantization_mobilenetv1.py", line 238, in run_program
    pred = exe.run(
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 1392, in run
    res = self._run_impl(
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 1583, in _run_impl
    program, new_exe = self._executor_cache.get_program_and_executor(
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 759, in get_program_and_executor
    return self._get_cached_program_and_executor(
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 826, in _get_program_and_executor
    program = _add_feed_fetch_ops(
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 378, in _add_feed_fetch_ops
    if not has_feed_operators(global_block, feed, feed_var_name):
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/executor.py", line 291, in has_feed_operators
    raise Exception(
Exception: 'feed_targets' does not have label variable

----------------------------------------------------------------------
```

error message 顯示與模型輸入有關

**Comment by leo0519** [comment]
This bug was fixed in https://github.com/PaddlePaddle/Paddle/pull/55035.
Close this issue.
