### ISSUE TITLE
Submit MPI job failed

### ISSUE THREAD

**Issue by alanse7en** [PaddlePaddle/Paddle#5509]
```
Traceback (most recent call last):
  File "/home/rd/paddle/output/submit.py", line 303, in <module>
    no_prefix_train_args_dict, ).run()
  File "/home/rd/paddle/output/submit.py", line 77, in run
    self._do_poster_request()
  File "/home/rd/paddle/output/submit.py", line 168, in _do_poster_request
    connection = urllib2.urlopen(request)
  File "/home/rd/.jumbo/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/home/rd/.jumbo/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/home/rd/.jumbo/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/home/rd/.jumbo/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/home/rd/.jumbo/lib/python2.7/site-packages/poster/streaminghttp.py", line 142, in http_open
    return self.do_open(StreamingHTTPConnection, req)
  File "/home/rd/.jumbo/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/home/rd/.jumbo/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/home/rd/.jumbo/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/home/rd/.jumbo/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```
通过v2版本的receiver提交mpi集群任务，报错信息如上。

**Comment by chengduoZH** [comment]
这是因为receiver机器的磁盘满了，现在好了。

**建议thirdparty不要上传太大的文件**

**Comment by typhoonzero** [comment]
类似的问题，还有可能是在submit的过程中Ctrl+C中断掉触发receiver的bug。此类问题需要联系paddle同学重启服务
