### ISSUE TITLE
ssd更换数据集训练问题

### ISSUE THREAD

**Issue by andmiles2go** [PaddlePaddle/Paddle#5515]
我首先是使用了demo中推荐的pascal voc数据集进行gpu训练，模型训练的很顺利。
现在我们需要提升检测模型的性能，尝试不同的数据集。
我的做法是这样的：
1 从mscoco的官网下载2014的trainval数据集，annotation按照voc的标注格式做了适配，制作新的训练，测试和标签列表。
2 更改了config/pascal_voc_conf.py,修改分类数量为coco数据集的分类数量 __C.CLASS_NUM = 80
3 更新了train.py中的训练，测试和标签列表
然后我启动训练，碰到了如下问题。
```
Traceback (most recent call last):
  File "train_coco.py", line 84, in <module>
    init_model_path='./vgg/vgg_model.tar.gz')
  File "train_coco.py", line 25, in train
    parameters.init_from_tar(gzip.open(init_model_path))
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 384, in init_from_tar
    self.set(pname, tar_param.get(pname))
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 266, in set
    self.__setitem__(key=parameter_name, value=value)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 219, in __setitem__
    (shape, value.shape))
ValueError: Value shape mismatch, expect (1, 2211840), should (1, 580608)
```
看起来，用来fine tuning的vgg模型启动时出了问题。
我注意到，文档最后一段有提到：
Another important thing is to change the size of the image and the size of the object to change the configuration of the network structure. Use config/vgg_config.py to create the custom configuration file. For more details, please refer to
这里看的不是很明白，代码库里也并没有config/vgg_config.py 

请问我还需要什么样的修改，才可以在coco数据集上训练ssd呢？
谢谢

**Comment by chengduoZH** [comment]
> 代码库里也并没有config/vgg_config.py

文档未及时更新，应该是config/pascal_voc_conf.py

**Comment by andmiles2go** [comment]
@NHZlX
根据你的建议，进行了如下修改

1 mbox_block的参数问题
主要修改loc_filters, conf_filters
参数确定的方法，我主要参照ssd_block函数中的两条计算公式
`loc_filters = (len(aspect_ratio) * 2 + 1 + len(max_size)) * 4`
和
`conf_filters = (len(aspect_ratio) * 2 + 1 + len(max_size)) * cfg.CLASS_NUM`
我粗浅的理解，其中location不变，confidence会随着分类数变化，需要修改。aspect_ratio和max_size来自不同层的网络参数

代码中，我找到需要修改的三处，分别是
conv4_3层的预测输出：
`conv4_3_norm_mbox_loc, conv4_3_norm_mbox_conf =  mbox_block("conv4_3_norm", conv4_3_norm, 512, 3, 12, 63)`
修改为
`conv4_3_norm_mbox_loc, conv4_3_norm_mbox_conf = mbox_block("conv4_3_norm_", conv4_3_norm, 512, 3, 3 * 4, 3 * cfg.CLASS_NUM)`

fc7层的预测输出：
`fc7_mbox_loc, fc7_mbox_conf = mbox_block("fc7", fc7, 1024, 3, 24, 126)`
修改为
`fc7_mbox_loc, fc7_mbox_conf = mbox_block("fc7_", fc7, 1024, 3, 24, 6 * cfg.CLASS_NUM)`

pool6层的预测输出：
`pool6_mbox_loc, pool6_mbox_conf = mbox_block("pool6", pool6, 256, 3, 24, 126)`
修改为
`pool6_mbox_loc, pool6_mbox_conf = mbox_block("pool6_", pool6, 256, 3, 24, 6 * cfg.CLASS_NUM )`

2 命名问题
以上三处mbox_block的第一个参数均加了下划线，做到unique

然后我尝试着重新训练，结果依然是这个问题：
`Traceback (most recent call last):
  File "train_coco.py", line 84, in <module>
    init_model_path='./vgg/vgg_model.tar.gz')
  File "train_coco.py", line 25, in train
    parameters.init_from_tar(gzip.open(init_model_path))
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 384, in init_from_tar
    self.set(pname, tar_param.get(pname))
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 266, in set
    self.__setitem__(key=parameter_name, value=value)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 219, in __setitem__
    (shape, value.shape))
ValueError: Value shape mismatch, expect (1, 2211840), should (1, 580608)`

看起来并没有生效。我觉得可能还是pre train模型参数的问题。
请问如何解决这个问题？
谢谢～

**Comment by NHZlX** [comment]
```
fc7_mbox_loc, fc7_mbox_conf = mbox_block("fc7f", fc7, 1024, 3, 24, 12)
```
中的后两个参数需要根据自己的数据改动的，
这两个参数分别代表
1: location的feature map 输出个数， 即`loc_filters`
2: confidence 的feature map的个数， 即`conf_filters`
这俩的计算分别如下： 
```
loc_filters = (len(aspect_ratio) * 2 + 1 + len(max_size)) * 4
conf_filters = (
            len(aspect_ratio) * 2 + 1 + len(max_size)) * cfg.CLASS_NUM
```

**Comment by andmiles2go** [comment]
@NHZlX 
我的计算方法跟你的公式是一样的，我再分解的详细一些哈, 以计算conv4_3为例。
conv4_3层的预测输出，几个关键的网络参数如下：

__C.NET.CONV4 = edict()
__C.NET.CONV4.PB = edict()
__C.NET.CONV4.PB.MIN_SIZE = [30]
__C.NET.CONV4.PB.ASPECT_RATIO = [2.]
__C.NET.CONV4.PB.VARIANCE = [0.1, 0.1, 0.2, 0.2]

1 输出的位置框回归：
`loc_filters = (len(aspect_ratio) * 2 + 1 + len(max_size)) * 4`
aspect_ratio为[2.] max_size缺失故为0
大小为（len([2.]) * 2 + 1 + 0 ）* 4 = 3 * 4 = 12
无论分类数是否变化，该值均为12

2 分类置信度的输出：
`conf_filters = (
            len(aspect_ratio) * 2 + 1 + len(max_size)) * cfg.CLASS_NUM`
如上，len(aspect_ratio) * 2 + 1 + len(max_size) = 3
当分类数为21时，conf_filters = 3 * 21 = 63，即原代码中的大小
此处我改为 3 * cfg.CLASS_NUM，可以根据配置变化，在coco数据集上，该值为3 * 80 = 240

fc7和pool6的改法和上边类似，只是根据网络配置文件，这两个的
len(aspect_ratio) * 2 + 1 + len(max_size) = 6
所以有
loc_filters = 6 * 4 = 24 
conf_filters = 6 * cfg.CLASS_NUM = 6 * 80 = 480

请指正，谢谢～

**Comment by NHZlX** [comment]
@andmiles2go  这个配置是没有问题的，那你是遇到什么问题了呢

**Comment by andmiles2go** [comment]
@NHZlX 
我改完之后，还是这个错误

Traceback (most recent call last): File "train_coco.py", line 84, in <module> init_model_path='./vgg/vgg_model.tar.gz') File "train_coco.py", line 25, in train parameters.init_from_tar(gzip.open(init_model_path)) File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 384, in init_from_tar self.set(pname, tar_param.get(pname)) File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 266, in set self.__setitem__(key=parameter_name, value=value) File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 219, in __setitem__ (shape, value.shape)) ValueError: Value shape mismatch, expect (1, 2211840), should (1, 580608)

**Comment by NHZlX** [comment]
请问， `mbox_block("fc7f", fc7, 1024, 3, 24, 12)` 第一个参数，即layer名字改了么

**Comment by andmiles2go** [comment]
fc7层的预测输出：
fc7_mbox_loc, fc7_mbox_conf = mbox_block("fc7", fc7, 1024, 3, 24, 126)
修改为
fc7_mbox_loc, fc7_mbox_conf = mbox_block("fc7_", fc7, 1024, 3, 24, 6 * cfg.CLASS_NUM)

名字我统一加了下划线，改了

**Comment by gongweibao** [comment]
Close it since no activity.
