### ISSUE TITLE
根据官方教程搭建的基于LSTM的情感分析模型，动转静后，使用Pycharm运行代码，在Python Console窗口开始训练会报错，但是在Run窗口可以正常训练，也试过其他模型，动转静后，报一样的错误

### ISSUE THREAD

**Issue by zzwtop1** [PaddlePaddle/Paddle#55163]
### bug描述 Describe the Bug

代码链接：https://www.paddlepaddle.org.cn/tutorials/projectdetail/3464735

paddle版本2.4.1
操作系统：windows10
pycharm版本信息：
PyCharm 2022.2.4 (Community Edition)
Build #PC-222.4459.20, built on November 17, 2022
Runtime version: 17.0.5+7-b469.71 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

报错信息：
Traceback (most recent call last):
  File "E:\anaconda\envs\tf2.4.1\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 285, in <module>
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 411, in __call__
    raise e
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 384, in __call__
    concrete_program, partial_program_layer = self.get_concrete_program(
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 485, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 955, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 939, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\base.py", line 67, in __impl__
    return func(*args, **kwargs)
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 848, in from_func_spec
    static_func = convert_to_static(dygraph_function)
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 142, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 77, in convert_with_cache
    static_func = self._convert(func)
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 104, in _convert
    source_code = func_to_source_code(func)
  File "E:\anaconda\envs\tf2.4.1\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\utils.py", line 703, in func_to_source_code
    source_code_list, _ = inspect.getsourcelines(function)
  File "E:\anaconda\envs\tf2.4.1\lib\inspect.py", line 979, in getsourcelines
    lines, lnum = findsource(object)
  File "E:\anaconda\envs\tf2.4.1\lib\inspect.py", line 798, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

**Comment by FlyingQianMM** [comment]
> 但是在Run窗口可以正常训练

可能跟您的pycharm环境配置有关 。建议您还是直接在终端运行代码
