### ISSUE TITLE
paddle 2.5 在 arm macos 上执行 `paddle.linalg.lu` 出错

### ISSUE THREAD

**Issue by GreatV** [PaddlePaddle/Paddle#55189]
### bug描述 Describe the Bug

```python
import paddle
A = paddle.to_tensor(data=[[[0.3591, -0.0479, -0.2174], [-0.6957, -1.4667, 
    1.4384], [0.0735, 0.1147, 0.0513]], [[-1.2565, -2.1263, 0.8075], [-
    0.3665, -3.354, -0.9417], [-0.1299, -0.0689, -0.6207]]])
A_LU = paddle.empty_like(x=A)
pivots = paddle.empty(shape=(2, 3), dtype='int32')
tmp_lu, tmp_p = paddle.linalg.lu(x=A, pivot=True, get_infos=False)
```

```shell
Traceback (most recent call last):
  File "/Users/wangxin/repos/PaConvert/test_project/paddle_temp.py", line 7, in <module>
    tmp_lu, tmp_p = paddle.linalg.lu(x=A, pivot=True, get_infos=False)
  File "/Users/wangxin/miniconda3/envs/paconvert/lib/python3.10/site-packages/paddle/tensor/linalg.py", line 2184, in lu
    lu, p, info = _C_ops.lu(x, pivot)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (liblapack.3.dylib) that Paddle depends on is not configured correctly. (error code is dlopen(/usr/local/cuda/lib/liblapack.3.dylib, 0x0005): tried: '/usr/local/cuda/lib/liblapack.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/cuda/lib/liblapack.3.dylib' (no such file), '/usr/local/cuda/lib/liblapack.3.dylib' (no such file))
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /Users/paddle/xly/workspace/9fc77989-de12-406f-9c25-c7ddd992fc3c/Paddle/paddle/phi/backends/dynload/dynamic_loader.cc:301)
```

### 其他补充信息 Additional Supplementary Information

安装命令

```
 python -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple --force-reinstall
```

python 版本 3.10

手动编译paddle后发现`liblapack`使用的是x86架构的动态库

<img width="609" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/17264618/6a14917f-4b09-481c-9998-7afdb2a0a2c5">

**Comment by winter-wang** [comment]
这个感觉像是安装问题。您可以运行run_check()看看是否正常。

**Comment by GreatV** [comment]
@winter-wang run_check() 是正常的

```python
paddle.utils.run_check()
```
```
Running verify PaddlePaddle program ... 
I0706 13:08:57.961102 3747585536 program_interpreter.cc:171] New Executor is Running.
I0706 13:08:58.010413 3747585536 interpreter_util.cc:529] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

**Comment by winter-wang** [comment]
你好，目前paddle不支持arm mac下的安装使用。
