### ISSUE TITLE
xpu下调用内置模型报错

### ISSUE THREAD

**Issue by MiltonZheng** [PaddlePaddle/Paddle#55192]
### 环境
CPU：飞腾S2500
系统：麒麟V10
xpu：昆仑k200
### 问题描述
运行官方的MNIST手写字识别示例代码[https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/quick_start_cn.html](url)，调用lenet模型时报错
`Traceback (most recent call last):

  File "/root/CSSPaddleVer/test.py", line 19, in <module>
    lenet = paddle.vision.models.LeNet(num_classes=10)

  File "/root/miniforge3/envs/paddle/lib/python3.7/site-packages/paddle/vision/models/lenet.py", line 51, in __init__
    nn.Conv2D(1, 6, 3, stride=1, padding=1),

  File "/root/miniforge3/envs/paddle/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 698, in __init__
    data_format=data_format,

  File "/root/miniforge3/envs/paddle/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 159, in __init__
    default_initializer=_get_default_param_initializer(),

  File "/root/miniforge3/envs/paddle/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 716, in create_parameter
    temp_attr, shape, dtype, is_bias, default_initializer

  File "/root/miniforge3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 429, in create_parameter
    **attr._to_kwargs(with_initializer=True)

  File "/root/miniforge3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3935, in create_parameter
    initializer(param, self)

  File "/root/miniforge3/envs/paddle/lib/python3.7/site-packages/paddle/nn/initializer/initializer.py", line 40, in __call__
    return self.forward(param, block)

  File "/root/miniforge3/envs/paddle/lib/python3.7/site-packages/paddle/nn/initializer/normal.py", line 77, in forward
    place,

OSError: (External) normal XDNN Error, XDNN_INVALID_PARAM  (at /root/Paddle/paddle/phi/kernels/xpu/gaussian_kernel.cc:43)`

**Comment by winter-wang** [comment]
这个问题可能是由于算子gaussian_random的kernel升级没有考虑K200的硬件状态。
你可以刷一下这个环境变量再试试。
export XPU_BLACK_LIST="gaussian_random"
让gaussian_random跑在cpu上看看会不会有问题。

**Comment by MiltonZheng** [comment]
> 这个问题可能是由于算子gaussian_random的kernel升级没有考虑K200的硬件状态。 你可以刷一下这个环境变量再试试。 export XPU_BLACK_LIST="gaussian_random" 让gaussian_random跑在cpu上看看会不会有问题。

解决了，感谢！
