### ISSUE TITLE
paddledetection训练偶发性报错（DataLoader reader thread failed((Unavailable) File descriptor /paddle_20389_3786003212 open failed）

### ISSUE THREAD

**Issue by alexlzp** [PaddlePaddle/Paddle#55224]
### 问题描述 Please describe your issue

paddledetection在训练过程中偶尔会发生如下报错：
ERROR:root:DataLoader reader thread failed((Unavailable) File descriptor /paddle_20389_3786003212 open failed
  [Hint: Expected fd != -1, but received fd:-1 == -1:-1.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:92)
) to read data from workers' result queue.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/luzipeng/paddledetection_qlrle/python_build/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/luzipeng/paddledetection_qlrle/python_build/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/luzipeng/paddledetection_qlrle/python_build/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _thread_loop
    batch = self._get_data()
  File "/home/luzipeng/paddledetection_qlrle/python_build/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 609, in _get_data
    six.reraise(*sys.exc_info())
  File "/home/luzipeng/paddledetection_qlrle/python_build/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/luzipeng/paddledetection_qlrle/python_build/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 583, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/luzipeng/paddledetection_qlrle/python_build/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
RuntimeError: (Unavailable) File descriptor /paddle_20389_3786003212 open failed
  [Hint: Expected fd != -1, but received fd:-1 == -1:-1.] (at /paddle/paddle/fluid/memory/allocation/mmap_allocator.cc:92)

Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main()
  File "tools/train.py", line 174, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 128, in run
    trainer.train(FLAGS.eval)
  File "/home/luzipeng/paddledetection_qlrle/ppdet/engine/trainer.py", line 428, in train
    for step_id, data in enumerate(self.loader):
  File "/home/luzipeng/paddledetection_qlrle/ppdet/data/reader.py", line 209, in __next__
    return next(self.loader)
  File "/home/luzipeng/paddledetection_qlrle/python_build/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 697, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

INFO 2023-07-07 12:06:26,754 launch_utils.py:319] terminate process group gid:10665
INFO 2023-07-07 12:06:26,755 launch_utils.py:319] terminate process group gid:10668
INFO 2023-07-07 12:06:26,755 launch_utils.py:319] terminate process group gid:10671
INFO 2023-07-07 12:06:26,755 launch_utils.py:319] terminate process group gid:10674
INFO 2023-07-07 12:06:26,755 launch_utils.py:319] terminate process group gid:10677
INFO 2023-07-07 12:06:26,755 launch_utils.py:319] terminate process group gid:10680
INFO 2023-07-07 12:06:26,756 launch_utils.py:319] terminate process group gid:10684
INFO 2023-07-07 12:06:30,761 launch_utils.py:340] terminate all the procs
ERROR 2023-07-07 12:06:30,761 launch_utils.py:603] ABORT!!! Out of all 8 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2023-07-07 12:06:34,765 launch_utils.py:340] terminate all the procs
INFO 2023-07-07 12:06:34,765 launch.py:304] Local processes completed.

    
     
机器配置如下：
Fri Jul  7 12:20:37 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  On   | 00000000:3D:00.0 Off |                    0 |
| N/A   38C    P0    68W / 250W |   8878MiB / 40536MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-PCI...  On   | 00000000:3E:00.0 Off |                    0 |
| N/A   38C    P0    66W / 250W |   7852MiB / 40536MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

    
    
尝试调整worker_num、batchsize，依然无法解决。

**Comment by LiYuRio** [comment]
这个问题看着像dataloader读数据出了问题，能在paddledetection仓库提一下issue，详细描述一下复现步骤吗
