### ISSUE TITLE
训练每隔几个epoch就报错DataLoader process exited is killed by signal: Killed.

### ISSUE THREAD

**Issue by kamiLight** [PaddlePaddle/Paddle#55315]
### bug描述 Describe the Bug

多卡训练时，每隔几个epoch就会报错DataLoader process exited is killed by signal: Killed.
docker信息：registry.baidubce.com/paddlepaddle/paddle:2.4.2-gpu-cuda11.2-cudnn8.2-trt8.0
报错信息：
```
LAUNCH WARNING 2023-07-10 10:41:22,268 save gpu log failed
W0710 10:42:42.017282 23501 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0710 10:42:42.017271 23548 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
LAUNCH WARNING 2023-07-10 10:42:51,386 save gpu log failed
W0710 10:43:27.474828 23548 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
2023-07-10 10:43:32,325 -     INFO - [TRAIN] epoch=3/40, iter=22140/380640 , loss=4.797453, hm_loss=2.585052, hm_loss-0=0.405748, hm_loss-1=0.602194, hm_loss-2=0.575108, hm_loss-3=0.574856, hm_
loss-4=0.427146, loc_loss=2.212402, loc_loss-0=0.319184, loc_loss-1=0.295079, loc_loss-2=0.455909, loc_loss-3=0.550447, loc_loss-4=0.591782, num_positive=314.000000, num_positive-0=65.500000, n
um_positive-1=26.800001, num_positive-2=71.400002, num_positive-3=48.299999, num_positive-4=102.000000, total_loss=4.716412, lr=0.000146 | ELA 02:56:40, ETA 4529:09:56
2023-07-10 10:43:37,221 -     INFO - [TRAIN] epoch=3/40, iter=22150/380640 , loss=4.498109, hm_loss=2.386786, hm_loss-0=0.369409, hm_loss-1=0.575831, hm_loss-2=0.559404, hm_loss-3=0.498552, hm_
loss-4=0.383590, loc_loss=2.111322, loc_loss-0=0.291463, loc_loss-1=0.274432, loc_loss-2=0.422855, loc_loss-3=0.542440, loc_loss-4=0.580132, num_positive=273.600006, num_positive-0=70.200005, n
um_positive-1=27.600000, num_positive-2=49.200001, num_positive-3=48.400002, num_positive-4=78.200005, total_loss=4.560521, lr=0.000146 | ELA 02:56:45, ETA 57:03:42
2023-07-10 10:43:42,612 -     INFO - [TRAIN] epoch=3/40, iter=22160/380640 , loss=4.555935, hm_loss=2.364072, hm_loss-0=0.357376, hm_loss-1=0.654953, hm_loss-2=0.513128, hm_loss-3=0.453254, hm_
loss-4=0.385361, loc_loss=2.191863, loc_loss-0=0.298293, loc_loss-1=0.335780, loc_loss-2=0.436632, loc_loss-3=0.529388, loc_loss-4=0.591771, num_positive=257.100006, num_positive-0=55.600002, n
um_positive-1=25.500000, num_positive-2=50.500000, num_positive-3=46.900002, num_positive-4=78.599998, total_loss=4.502719, lr=0.000146 | ELA 02:56:51, ETA 63:36:34
LAUNCH WARNING 2023-07-10 10:44:17,285 save gpu log failed
2023-07-10 10:47:07,330 -     INFO - [TRAIN] epoch=3/40, iter=22170/380640 , loss=4.447310, hm_loss=2.324514, hm_loss-0=0.347287, hm_loss-1=0.518928, hm_loss-2=0.495549, hm_loss-3=0.494910, hm_
loss-4=0.467840, loc_loss=2.122796, loc_loss-0=0.280107, loc_loss-1=0.279884, loc_loss-2=0.433043, loc_loss-3=0.541464, loc_loss-4=0.588298, num_positive=271.000000, num_positive-0=50.200001, n
um_positive-1=30.400000, num_positive-2=53.299999, num_positive-3=50.000000, num_positive-4=87.099998, total_loss=4.565982, lr=0.000146 | ELA 03:00:15, ETA 5550:54:10
2023-07-10 10:51:05,670 -     INFO - [TRAIN] epoch=3/40, iter=22180/380640 , loss=4.482444, hm_loss=2.335912, hm_loss-0=0.463677, hm_loss-1=0.528029, hm_loss-2=0.524921, hm_loss-3=0.485580, hm_
loss-4=0.333706, loc_loss=2.146532, loc_loss-0=0.305639, loc_loss-1=0.291279, loc_loss-2=0.441736, loc_loss-3=0.532100, loc_loss-4=0.575778, num_positive=290.899994, num_positive-0=46.700001, n
um_positive-1=25.500000, num_positive-2=59.299999, num_positive-3=46.299999, num_positive-4=113.099998, total_loss=4.461382, lr=0.000146 | ELA 03:04:14, ETA 1054:04:44
W0710 10:52:50.613250 23501 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0710 10:52:50.613246 23548 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
LAUNCH INFO 2023-07-10 10:54:04,636 Pod failed
LAUNCH ERROR 2023-07-10 10:54:04,637 Container failed !!!
Container rank 2 status failed cmd ['/usr/bin/python', '-u', 'tools/train.py', '--config', 'configs/centerpoint/centerpoint_pillars_02voxel_apollo.yml', '--save_dir', 'output/centerpoint/center
point_test_break/', '--save_interval', '2', '--num_workers', '6', '--keep_checkpoint_max', '50'] code 1 log log/workerlog.2 
env {'GREP_COLOR': '1;31', 'CUDNN_VERSION': '8.1.1.33', 'LC_ALL': 'en_US.UTF-8', 'LD_LIBRARY_PATH': '/usr/local/lib/python3.7/dist-packages/cv2/../../lib64:/usr/local/TensorRT-8.0.3.4/lib:/usr/
local/cuda-11.2/targets/x86_64-linux/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64', 'LANG': 'en_US.UTF-8', 'HOSTNAME': '92c12e4ad2e1', 'OLDPWD': '/', 'WITH_GPU': 'ON', 'NVIDIA_VISIBLE_DEVI
CES': 'all', 'NCCL_VERSION': '2.8.4', 'GOPATH': '/root/gopath', 'PWD': '/paddle3d_20230616', 'HOME': '/root', 'GOROOT': '/usr/local/go', 'CLICOLOR': '1', 'DEBIAN_FRONTEND': 'noninteractive', 'G
REP_OPTIONS': '--color=auto', 'LIBRARY_PATH': '/usr/local/cuda/lib64/stubs', 'TERM': 'xterm', 'WITH_AVX': 'ON', 'CUDA_VERSION': '11.2.1', 'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility', 'SHLVL
': '1', 'LANGUAGE': 'en_US.UTF-8', 'NVIDIA_REQUIRE_CUDA': 'cuda>=11.2 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=440,driver<441 driver>=450,driver<451', 'PATH': '/home/cmake-3.16.0-
Linux-x86_64/bin:/usr/local/gcc-8.2/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/gopath/bin', 'PS1': '\\[\\
033[1;33m\\]λ \\[\\033[1;37m\\]\\h \\[\\033[1;32m\\]\\w \\[\\033[0m\\]', '_': '/usr/bin/python', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/usr/local/lib
/python3.7/dist-packages/cv2/qt/plugins', 'QT_QPA_FONTDIR': '/usr/local/lib/python3.7/dist-packages/cv2/qt/fonts', 'POD_NAME': 'wkwiqm', 'PADDLE_MASTER': '169.254.30.2:60734', 'PADDLE_GLOBAL_SI
ZE': '4', 'PADDLE_LOCAL_SIZE': '4', 'PADDLE_GLOBAL_RANK': '2', 'PADDLE_LOCAL_RANK': '2', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '169.254.30.2:60735,169.254.30.2:60736,169.254.30.2:60
737,169.254.30.2:60738', 'PADDLE_CURRENT_ENDPOINT': '169.254.30.2:60737', 'PADDLE_TRAINER_ID': '2', 'PADDLE_TRAINERS_NUM': '4', 'PADDLE_RANK_IN_NODE': '2', 'FLAGS_selected_gpus': '2'}
LAUNCH INFO 2023-07-10 10:54:04,637 ------------------------- ERROR LOG DETAIL -------------------------
e use an alias or script
2023-07-10 07:47:11,472 -     INFO - voxelize builded success!
W0710 10:42:42.017269 23549 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0710 10:43:27.474831 23549 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
W0710 10:52:50.613226 23549 sampler.cpp:189] bvar is busy at sampling for 2 seconds!
Traceback (most recent call last):
  File "tools/train.py", line 207, in <module>
    main(args)
  File "tools/train.py", line 202, in main
    trainer.train()
  File "/paddle3d_20230616/paddle3d/apis/trainer.py", line 298, in train
    amp_cfg=self.amp_cfg)
  File "/paddle3d_20230616/paddle3d/apis/pipeline.py", line 71, in training_step
    optimizer.after_iter()
  File "/paddle3d_20230616/paddle3d/models/optimizers/optimizers.py", line 118, in after_iter
    self.regularize()
  File "/paddle3d_20230616/paddle3d/models/optimizers/optimizers.py", line 83, in regularize
    param.set_value(param * scale_value)
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 203, in set_value
    framework._current_expected_place())
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 703, in __array__
    array = self.numpy()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/multiprocess_utils.py", line 135, in __handler__
    core._throw_error_if_process_failed()
SystemError: (Fatal) DataLoader process (pid 24641) exited is killed by signal: Killed. (at /paddle/paddle/fluid/imperative/data_loader.cc:188)

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 623, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 536, in _thread_loop
    batch = self._get_data()
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 639, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 5 workers exit unexpectedly, pids: 24641, 24647, 24653, 24659, 24695

LAUNCH INFO 2023-07-10 10:54:25,845 Exit code -15
```

**Comment by kangguangli** [comment]
你好，可以提供下可复现代码吗？
一个比较可能的原因是数据格式的问题，可以将报错时的数据打印出来看看

**Comment by kamiLight** [comment]
我看了一下其他的issue，我的这个问题貌似是内存泄漏引起的，而且这个bug到现在都没解

**Comment by kangguangli** [comment]
这也是一种可能，但目前也不能确定就是这个原因。如果可以的话，最好能提供一下最小可复现代码，方便排查。

**Comment by GuangmingCao** [comment]
我也遇到这个问题了，为什么被close？
