### ISSUE TITLE
Error: Can not import paddle core while this file exists ..... /lib/python3.9/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by ykn96** [PaddlePaddle/Paddle#55377]
### bug描述 Describe the Bug

Importing paddle on my python3.9 virtual environment gets me an error, i am unable to import paddle due to the existence of a certain file. I have tried paddlepaddle-gpu 2.4.2 and 2.50, both versions do not work.

I have consulted this other issue here https://github.com/PaddlePaddle/Paddle/issues/48681, https://github.com/PaddlePaddle/PaddleOCR/issues/1304 but it does not work for me.

i have ran ``` export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/aevas/Desktop/pyenvs/newpy39/lib```

```
>>> import paddle
Error: Can not import paddle core while this file exists: /home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

I have ran ``` pip install paddlepaddle-gpu``` 

This is my nvidia-smi output
```
-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.199.02   Driver Version: 470.199.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P3    20W /  N/A |      9MiB / 16125MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2804      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      3022      G   ...ome-remote-desktop-daemon        3MiB |
+-----------------------------------------------------------------------------+
```

### 其他补充信息 Additional Supplementary Information
I tried running the following in a jupyter notebook in my virtual environment

```
>>> import paddle
>>> paddle.utils.run_check()

Running verify PaddlePaddle program ... 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[15], line 1
----> 1 paddle.utils.run_check()

File ~/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py:249, in run_check()
    246     device_list = paddle.static.cpu_places(device_count=1)
    247 device_count = len(device_list)
--> 249 _run_static_single(use_cuda, use_xpu)
    250 _run_dygraph_single(use_cuda, use_xpu)
    251 print(f"PaddlePaddle works well on 1 {device_str}.")

File ~/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py:146, in _run_static_single(use_cuda, use_xpu)
    143         place = paddle.CPUPlace()
    145     exe = paddle.static.Executor(place)
--> 146     exe.run(startup_prog)
    147     exe.run(
    148         train_prog,
    149         feed={input.name: _prepare_data()},
    150         fetch_list=[out.name, param_grads[1].name],
    151     )
    152 paddle.disable_static()

File ~/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/executor.py:1392, in Executor.run(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, use_prune)
   1383     use_program_cache = force_use_program_cache in [
   1384         1,
   1385         '1',
   (...)
   1388         'true',
   1389     ]
   1390     self._log_force_set_program_cache(use_program_cache)
-> 1392 res = self._run_impl(
   1393     program=program,
   1394     feed=feed,
   1395     fetch_list=fetch_list,
   1396     feed_var_name=feed_var_name,
   1397     fetch_var_name=fetch_var_name,
   1398     scope=scope,
   1399     return_numpy=return_numpy,
   1400     use_program_cache=use_program_cache,
   1401     use_prune=use_prune,
   1402 )
   1403 core.update_autotune_status()
   1404 return res

File ~/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/executor.py:1618, in Executor._run_impl(self, program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy, use_program_cache, use_prune)
   1615     else:
   1616         tensor._copy_from(cpu_tensor, self.place)
-> 1618 ret = new_exe.run(
   1619     scope, list(feed.keys()), fetch_list, return_numpy
   1620 )
   1621 set_flags(stored_flag)
   1622 return ret

File ~/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/executor.py:654, in _StandaloneExecutor.run(self, scope, feed_names, fetch_list, return_numpy)
    643 """
    644 Args:
    645     feed_names(list): This parameter represents the input names of the model.
   (...)
    650         the type of the return value is a list of :code:`LoDTensor`. The default is True.
    651 """
    652 fetch_list = self._check_fetch(fetch_list)
--> 654 tensors = self._new_exe.run(
    655     scope, feed_names, fetch_list
    656 )._move_to_list()
    657 if return_numpy:
    658     return as_numpy(tensors, copy=True)

RuntimeError: In user code:

    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/ipykernel_launcher.py", line 17, in <module>
      app.launch_new_instance()
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/traitlets/config/application.py", line 1041, in launch_instance
      app.start()
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 724, in start
      self.io_loop.start()
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 215, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
      self._run_once()
    File "/usr/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
      handle._run()
    File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
      self._context.run(self._callback, *self._args)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 512, in dispatch_queue
      await self.process_one()
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 501, in process_one
      await dispatch(*args)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 408, in dispatch_shell
      await result
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 731, in execute_request
      reply_content = await reply_content
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 417, in do_execute
      res = shell.run_cell(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 540, in run_cell
      return super().run_cell(*args, **kwargs)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 2945, in run_cell
      result = self._run_cell(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3000, in _run_cell
      return runner(coro)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
      coro.send(None)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3203, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3382, in run_ast_nodes
      if await self.run_code(code, result, async_=asy):
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "/tmp/ipykernel_6998/2045286854.py", line 1, in <module>
      paddle.utils.run_check()
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 249, in run_check
      _run_static_single(use_cuda, use_xpu)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 133, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 31, in _simple_network
      weight = paddle.create_parameter(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/tensor/creation.py", line 222, in create_parameter
      return helper.create_parameter(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/layer_helper_base.py", line 432, in create_parameter
      self.startup_program.global_block().create_parameter(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 3935, in create_parameter
      initializer(param, self)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/nn/initializer/initializer.py", line 40, in __call__
      return self.forward(param, block)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/nn/initializer/constant.py", line 65, in forward
      op = block.append_op(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 4013, in append_op
      op = Operator(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2781, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
      [Hint: cudnn_dso_handle should not be null.] (at ../paddle/phi/backends/dynload/cudnn.cc:64)
      [operator < fill_constant > error]



>>> print(paddle.__version__)
2.5.0

```

**Comment by ykn96** [comment]
Is this a problem with my CUDA version ? Or is this a problem with selecting wrong version paddle to do pip install ?

**Comment by USTCKAY** [comment]
Hi, please check whether `libcudart.so.11.0` exists in your environment and is added to `LD_LIBRARY_PATH`.And could you please provide the cuDNN version in your environment?

**Comment by ykn96** [comment]
I have libcudart.so installed
```
 whereis libcudart.so.11.0
libcudart.so.11.0: /usr/lib/x86_64-linux-gnu/libcudart.so.11.0
```


Inside /etc/ld.so.conf.d
```
# Multiarch support
/usr/local/lib/x86_64-linux-gnu
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
```
Since the directory contains libcudart.so.11.0, sudo ldconfig should load it. Is that right? 



Strangely, i am unable to find the cuDNN files, despite having nvidia-smi being able to run, and other frameworks such as pytorch work on my laptop
```
cat /usr/local/cuda/version.txt
cat: /usr/local/cuda/version.txt: No such file or directory

 cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
cat: /usr/local/cuda/include/cudnn.h: No such file or directory

cat /usr/include/cudnn.h | grep CUDNN_MAJOR -A 2
cat: /usr/include/cudnn.h: No such file or directory
```

The driver installation seems to be valid though
```
cat /proc/driver/nvidia/version 
NVRM version: NVIDIA UNIX x86_64 Kernel Module  470.199.02  Thu May 11 11:46:56 UTC 2023
GCC version:  gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1) 
```

**Comment by ykn96** [comment]
Seems like i can import paddle now

But i have gotten another error when verifying the install with paddle.utils.run_check()
```
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
I0714 09:49:56.078572 16365 interpretercore.cc:237] New Executor is Running.
W0714 09:49:56.079103 16365 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.5
W0714 09:49:56.079572 16365 dynamic_loader.cc:303] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 249, in run_check
    _run_static_single(use_cuda, use_xpu)
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 146, in _run_static_single
    exe.run(startup_prog)
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1392, in run
    res = self._run_impl(
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1618, in _run_impl
    ret = new_exe.run(
  File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/executor.py", line 654, in run
    tensors = self._new_exe.run(
RuntimeError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 249, in run_check
      _run_static_single(use_cuda, use_xpu)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 133, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 31, in _simple_network
      weight = paddle.create_parameter(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/tensor/creation.py", line 222, in create_parameter
      return helper.create_parameter(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/layer_helper_base.py", line 432, in create_parameter
      self.startup_program.global_block().create_parameter(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 3935, in create_parameter
      initializer(param, self)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/nn/initializer/initializer.py", line 40, in __call__
      return self.forward(param, block)
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/nn/initializer/constant.py", line 65, in forward
      op = block.append_op(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 4013, in append_op
      op = Operator(
    File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2781, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
      [Hint: cudnn_dso_handle should not be null.] (at ../paddle/phi/backends/dynload/cudnn.cc:64)
      [operator < fill_constant > error]
```

**Comment by USTCKAY** [comment]
> Seems like i can import paddle now
> 
> But i have gotten another error when verifying the install with paddle.utils.run_check()
> 
> ```
> >>> import paddle
> >>> paddle.utils.run_check()
> Running verify PaddlePaddle program ... 
> I0714 09:49:56.078572 16365 interpretercore.cc:237] New Executor is Running.
> W0714 09:49:56.079103 16365 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.5
> W0714 09:49:56.079572 16365 dynamic_loader.cc:303] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
>   Suggestions:
>   1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
>   2. Configure third-party dynamic library environment variables as follows:
>   - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
>   - Windows: set PATH by `set PATH=XXX;
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 249, in run_check
>     _run_static_single(use_cuda, use_xpu)
>   File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 146, in _run_static_single
>     exe.run(startup_prog)
>   File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1392, in run
>     res = self._run_impl(
>   File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/executor.py", line 1618, in _run_impl
>     ret = new_exe.run(
>   File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/executor.py", line 654, in run
>     tensors = self._new_exe.run(
> RuntimeError: In user code:
> 
>     File "<stdin>", line 1, in <module>
>       
>     File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 249, in run_check
>       _run_static_single(use_cuda, use_xpu)
>     File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 133, in _run_static_single
>       input, out, weight = _simple_network()
>     File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/utils/install_check.py", line 31, in _simple_network
>       weight = paddle.create_parameter(
>     File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/tensor/creation.py", line 222, in create_parameter
>       return helper.create_parameter(
>     File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/layer_helper_base.py", line 432, in create_parameter
>       self.startup_program.global_block().create_parameter(
>     File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 3935, in create_parameter
>       initializer(param, self)
>     File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/nn/initializer/initializer.py", line 40, in __call__
>       return self.forward(param, block)
>     File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/nn/initializer/constant.py", line 65, in forward
>       op = block.append_op(
>     File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 4013, in append_op
>       op = Operator(
>     File "/home/aevas/Desktop/pyenvs/newpy39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 2781, in __init__
>       for frame in traceback.extract_stack():
> 
>     PreconditionNotMetError: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
>       [Hint: cudnn_dso_handle should not be null.] (at ../paddle/phi/backends/dynload/cudnn.cc:64)
>       [operator < fill_constant > error]
> ```

Hi, it seems that you have not installed cudnn properly, maybe you should try to reinstall it.

**Comment by ykn96** [comment]
@USTCKAY ok i have reinstalled my cuda and cudnn and it seems to be ok!

```
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
I0717 09:40:58.291146 12137 interpretercore.cc:237] New Executor is Running.
W0717 09:40:58.292129 12137 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.2, Runtime API Version: 11.7
W0717 09:40:58.293215 12137 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
I0717 09:41:00.817838 12137 interpreter_util.cc:518] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
>>> exit()
```

In case people need, these were helpful
- https://gist.github.com/primus852/b6bac167509e6f352efb8a462dcf1854
- https://stackoverflow.com/questions/39643013/gzip-stdin-not-in-gzip-format-tar-child-returned-status-1-tar-error-is-not-r
Thank you for your help

**Comment by USTCKAY** [comment]
> @USTCKAY ok i have reinstalled my cuda and cudnn and it seems to be ok!
> 
> ```
> >>> import paddle
> >>> paddle.utils.run_check()
> Running verify PaddlePaddle program ... 
> I0717 09:40:58.291146 12137 interpretercore.cc:237] New Executor is Running.
> W0717 09:40:58.292129 12137 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.2, Runtime API Version: 11.7
> W0717 09:40:58.293215 12137 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
> I0717 09:41:00.817838 12137 interpreter_util.cc:518] Standalone Executor is Used.
> PaddlePaddle works well on 1 GPU.
> PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
> >>> exit()
> ```
> 
> In case people need, these were helpful
> 
> * https://gist.github.com/primus852/b6bac167509e6f352efb8a462dcf1854
> * https://stackoverflow.com/questions/39643013/gzip-stdin-not-in-gzip-format-tar-child-returned-status-1-tar-error-is-not-r
>   Thank you for your help

Congrats！

**Comment by PeterPanWF** [comment]
Solved
`sudo apt-get install libpython3.8-dev #python3.8  `
lack of software packs
