### ISSUE TITLE
PaddleDetection部署在nvidia jetson平台进行预测发生异常

### ISSUE THREAD

**Issue by nibnahzuh** [PaddlePaddle/Paddle#55452]
### 我在jetson nano和jetson agx上使用PaddleDetection的ppvehicle，当使用gpu进行预测，调用官方公布的模型ppyoloe_plus_tiny作为检测和跟踪模型时，无法跑通视频测试示例，提示需要分配16EB的显存，报显存溢出错误，我测试了对源码没有任何改动的版本，依旧出现了这一错误，而在nvidia 3090 gpu上可以正常运行，此问题未出现，且实时监测显存消耗大概为8g不到。

我在命令行的输入即为[ppvehicle预测部署的示例输入](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/pipeline/docs/tutorials/PPVehicle_QUICK_STARTED.md#%E9%A2%84%E6%B5%8B%E9%83%A8%E7%BD%B2)，具体如下：
"""python deploy/pipeline/pipeline.py --config deploy/pipeline/config/examples/infer_cfg_illegal_parking.yml \
                                                   --video_file=../my_video.mp4 \
                                                   --device=gpu \
                                                   --draw_center_traj \
                                                   --illegal_parking_time=3 \
                                                   --region_type=custom \
                                                   --region_polygon 600 300 1300 300 1300 800 600 800"""

具体报错信息如下：
```
Traceback (most recent call last):
  File "deploy/pipeline/pipeline.py", line 1321, in <module>
    main()
  File "deploy/pipeline/pipeline.py", line 1308, in main
    pipeline.run_multithreads()
  File "deploy/pipeline/pipeline.py", line 179, in run_multithreads
    self.predictor.run(self.input)
  File "deploy/pipeline/pipeline.py", line 533, in run
    self.predict_video(input, thread_idx=thread_idx)
  File "deploy/pipeline/pipeline.py", line 753, in predict_video
    res = self.mot_predictor.predict_image(
  File "/root/transport/test/PaddleDetection/deploy/pptracking/python/mot_sde_infer.py", line 538, in predict_image
    result = self.predict()
  File "/root/transport/test/PaddleDetection/deploy/pptracking/python/det_infer.py", line 165, in predict
    self.predictor.run()
RuntimeError:
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
5   void phi::WhereIndexKernel<bool, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor*)
6   void phi::funcs::SelectKernel<bool, bool, long, 0, phi::IndexFunctor<bool, long, long> >(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor*, phi::IndexFunctor<bool, long, long>)
7   phi::DenseTensor::mutable_data(phi::Place const&, paddle::experimental::DataType, unsigned long)
8   paddle::memory::AllocShared(phi::Place const&, unsigned long)
9   paddle::memory::allocation::AllocatorFacade::AllocShared(phi::Place const&, unsigned long)
10  paddle::memory::allocation::AllocatorFacade::Alloc(phi::Place const&, unsigned long)
11  paddle::memory::allocation::StatAllocator::AllocateImpl(unsigned long)
12  paddle::memory::allocation::RetryAllocator::AllocateImpl(unsigned long)
13  paddle::memory::allocation::Allocator::Allocate(unsigned long)
14  paddle::memory::allocation::StreamSafeCUDAAllocator::AllocateImpl(unsigned long)
15  paddle::memory::allocation::Allocator::Allocate(unsigned long)
16  paddle::memory::allocation::AutoGrowthBestFitAllocator::AllocateImpl(unsigned long)
17  paddle::memory::allocation::Allocator::Allocate(unsigned long)
18  paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
19  std::string phi::enforce::GetCompleteTraceBackString<std::string >(std::string&&, char const*, int)
20  phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 15.052681EB memory on GPU 0, 11.643288GB memory has been allocated and available memory is only 18.176891GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /home/paddle/data/xly/workspace/24116/Paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:81)
```

另外，在jetson平台上使用其他官方公布的检测和跟踪模型时，如mot_ppyoloe_s_36e_ppvehicle和mot_ppyoloe_l_36e_ppvehicle，产生了其他错误，这一情况在nvidia 3090 gpu上也未出现。

具体报错信息如下：
```
Traceback (most recent call last):
  File "deploy/pipeline/pipeline.py", line 1321, in <module>
    main()
  File "deploy/pipeline/pipeline.py", line 1308, in main
    pipeline.run_multithreads()
  File "deploy/pipeline/pipeline.py", line 179, in run_multithreads
    self.predictor.run(self.input)
  File "deploy/pipeline/pipeline.py", line 533, in run
    self.predict_video(input, thread_idx=thread_idx)
  File "deploy/pipeline/pipeline.py", line 791, in predict_video
    object_in_region_info, illegal_parking_dict = update_object_info(
  File "/root/transport/test/PaddleDetection/deploy/pptracking/python/mot/utils.py", line 383, in update_object_info
    if not in_quadrangle([center_x, center_y], entrance, im_h, im_w):
  File "/root/transport/test/PaddleDetection/deploy/pptracking/python/mot/utils.py", line 432, in in_quadrangle
    p = tuple(map(int, point))
ValueError: cannot convert float NaN to integer
```

**Comment by zengshao0622** [comment]
Jetson平台算力相比3090差距较大，可以尝试参考一下文档中的建议进行Jeston平台的适配：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/pipeline/docs/tutorials/PPVehicle_QUICK_STARTED.md#jetson%E9%83%A8%E7%BD%B2%E8%AF%B4%E6%98%8E

**Comment by nibnahzuh** [comment]
> Jetson平台算力相比3090差距较大，可以尝试参考一下文档中的建议进行Jeston平台的适配：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/pipeline/docs/tutorials/PPVehicle_QUICK_STARTED.md#jetson%E9%83%A8%E7%BD%B2%E8%AF%B4%E6%98%8E

您好，我正是使用上述链接中的PP-YOLOE-Plus Tiny模型产生的显存溢出报错，并开启了跳帧检测，但报的需要分配**15EB**显存有些不合理，不是**15GB**。

**Comment by zengshao0622** [comment]
建议到PaddleDetection repo咨询一下：https://github.com/PaddlePaddle/PaddleDetection
