### ISSUE TITLE
[NPU] 单机多卡分布式训练提示RuntimeError: (NotFound) The kernel sync_batch_norm is not registered

### ISSUE THREAD

**Issue by 535205856** [PaddlePaddle/Paddle#55481]
### bug描述 Describe the Bug

单机多卡报错
python -m paddle.distributed.fleet.launch --run_mode=collective --npus="4,5,6,7" tools/train.py -c configs/yolov3/yolov3_darknet53_270e_roadsign.yml -o use_npu=True

npu的分布式训练目前paddle应该不支持，我这边本地修改了lanch.py和lanch_utils.py文件可以进行分类的resnet50的多npu训练，但是检测这边报错

单机单卡可以训练

单机多卡训练异常报错，

Traceback (most recent call last):
File "tools/train.py", line 205, in
main()
File "tools/train.py", line 201, in main
run(FLAGS, cfg)
File "tools/train.py", line 151, in run
trainer.train(FLAGS.eval)
File "/workspace/PaddleDetection/ppdet/engine/trainer.py", line 539, in train
outputs = model(data)
File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1253, in call
return self.forward(*inputs, **kwargs)
File "/opt/py37env/lib/python3.7/site-packages/paddle/distributed/parallel.py", line 534, in forward
outputs = self._layers(*inputs, **kwargs)
File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1253, in call
return self.forward(*inputs, **kwargs)
File "/workspace/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 60, in forward
out = self.get_loss()
File "/workspace/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 147, in get_loss
return self.forward()
File "/workspace/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 81, in forward
body_feats = self.backbone(self.inputs)
File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1253, in call
return self.forward(*inputs, **kwargs)
File "/workspace/PaddleDetection/ppdet/modeling/backbones/darknet.py", line 330, in forward
out = self.conv0(x)
File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1253, in call
return self.forward(*inputs, **kwargs)
File "/workspace/PaddleDetection/ppdet/modeling/backbones/darknet.py", line 77, in forward
out = self.batch_norm(out)
File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/layers.py", line 1253, in call
return self.forward(*inputs, **kwargs)
File "/opt/py37env/lib/python3.7/site-packages/paddle/nn/layer/norm.py", line 1557, in forward
False,
RuntimeError: (NotFound) The kernel sync_batch_norm is not registered.
[Hint: Expected iter != kernels.end(), but received iter == kernels.end().] (at /paddle/paddle/phi/core/kernel_factory.cc:219)

### 其他补充信息 Additional Supplementary Information

宿主机机器环境是 昇腾910npu + 鲲鹏920 arm cpu 的 ubuntu 环境
镜像使用是npu文档中的镜像 registry.baidubce.com/device/paddle-npu:cann601-ubuntu18-aarch64-gcc82

使用的是PaddleCustomDevice插件式的方式使用npu进行的训练

**Comment by jiahy0825** [comment]
您好，请问用的 Paddle 版本是多少，方便换用 develop 版本试一下吗？

**Comment by 535205856** [comment]
> 您好，请问用的 Paddle 版本是多少，方便换用 develop 版本试一下吗？

使用的是7月4号晚上的打的develop的nightly 版本

https://github.com/PaddlePaddle/PaddleCustomDevice/issues/694#issuecomment-1638024380

PaddleCustomDevice方面的回答：“目前npu不支持sync_bn算子，需要替换为普通的bn算子；”，在问下啊，现在paddle现在的develop版本对npu能支持这些算子吗，或者对npu都支持哪些算子，支持哪些算子对应的网络模型，性能如何，有没详细的说明

**Comment by ronny1996** [comment]
@535205856 你好，npu支持的算子可以在这里看到 https://github.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/npu/kernels

网络模型中如果缺少算子支持，通常是会fallback到cpu（如果cpu有）

这里报错只是不支持 sync_batch_norm kernel，你可以修改组网使用普通的bn代替，或者在 paddle custom device 提需求 npu 支持 sync_batch_norm，如果只是需要验证多卡，建议修改组网使用普通的bn
