### ISSUE TITLE
麒麟系统编译paddle时Python安装编译好的whl包时报错

### ISSUE THREAD

**Issue by Phoenix2Legend** [PaddlePaddle/Paddle#55512]
### bug描述 Describe the Bug

在麒麟v10系统上编译paddle，系统内核为Linux-4.4.131-20200710.kylin.desktop-generic-aarch64-with-Kylin-V10-juniper;CPU为Phytium,FT-2000/4(64位，4核)。参考文档链接为：https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_phytium_cn.html。在完成命令python3 -m pip install -U paddlepaddle-0.0.0-cp37-cp37m-linux_aarch64.whl后报错：
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-berk85a8/paddle-bfloat/
You are using pip version 18.1, however version 23.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by qili93** [comment]
请问您这里参考文档进行源码编译是成功的，之后在pip安装阶段报错对吗？

根据错误提示信息应该是依赖库 paddle-bfloat 安装错误，可以试试看 pip install -U paddle-bfloat 是否可以运行成功。

**Comment by Phoenix2Legend** [comment]
输入pip install -U paddle-bfloat 命令后报错
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'

输入pip3 install -U paddle-bfloat命令后显示如下：
 root@wangan-GW-001M1A-FTF:/home/wangan/桌面# pip3 install -U paddle-bfloat
Requirement already satisfied: paddle-bfloat in /usr/local/lib/python3.9/site-packages (0.1.7)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@wangan-GW-001M1A-FTF:/home/wangan/桌面#

**Comment by Phoenix2Legend** [comment]
命令python -m pip install -U paddlepaddle-0.0.0-cp37-cp37m-linux_aarch64.whl结束后完整报错为：
root@wangan-GW-001M1A-FTF:/home/wangan/桌面# python -m pip install -U paddlepaddle-0.0.0-cp37-cp37m-linux_aarch64.whl 
Processing ./paddlepaddle-0.0.0-cp37-cp37m-linux_aarch64.whl
Collecting numpy>=1.13 (from paddlepaddle==0.0.0)
  Using cached https://files.pythonhosted.org/packages/45/b7/de7b8e67f2232c26af57c205aaad29fe17754f793404f59c8a730c7a191a/numpy-1.21.6.zip
  Installing build dependencies ... done
Collecting httpx (from paddlepaddle==0.0.0)
  Using cached https://files.pythonhosted.org/packages/ec/91/e41f64f03d2a13aee7e8c819d82ee3aa7cdc484d18c0ae859742597d5aa0/httpx-0.24.1-py3-none-any.whl
Collecting opt-einsum==3.3.0 (from paddlepaddle==0.0.0)
  Using cached https://files.pythonhosted.org/packages/bc/19/404708a7e54ad2798907210462fd950c3442ea51acc8790f3da48d2bee8b/opt_einsum-3.3.0-py3-none-any.whl
Collecting astor (from paddlepaddle==0.0.0)
  Using cached https://files.pythonhosted.org/packages/c3/88/97eef84f48fa04fbd6750e62dcceafba6c63c81b7ac1420856c8dcc0a3f9/astor-0.8.1-py2.py3-none-any.whl
Collecting decorator (from paddlepaddle==0.0.0)
  Using cached https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl
Collecting Pillow (from paddlepaddle==0.0.0)
  Using cached https://files.pythonhosted.org/packages/00/d5/4903f310765e0ff2b8e91ffe55031ac6af77d982f0156061e20a4d1a8b2d/Pillow-9.5.0.tar.gz
Collecting protobuf>=3.20.2; platform_system != "Windows" (from paddlepaddle==0.0.0)
  Using cached https://files.pythonhosted.org/packages/b0/07/fb712cce15ba456f7c24b82b97c8a7db2233f07037ffe61c9011660c592a/protobuf-4.23.4-py3-none-any.whl
Collecting paddle-bfloat==0.1.7 (from paddlepaddle==0.0.0)
  Using cached https://files.pythonhosted.org/packages/46/0a/6dc932c8471b86c8331bdaeaf1765be091e18974b359c9c358f0c021eeff/paddle_bfloat-0.1.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-ogyz_vb5/numpy-1.25.1/setup.py", line 22, in <module>
        setattr(__builtins__, name, value)
    RuntimeError: Python version >= 3.9 required.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uzl1j7iz/paddle-bfloat/setup.py", line 52, in <module>
        cmdclass={'build_ext': my_build_ext})
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/wangan/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "/home/wangan/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1075, in obtain
        return installer(requirement)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/home/wangan/python3.7/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/wangan/python3.7/lib/python3.7/contextlib.py", line 130, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/wangan/python3.7/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-ogyz_vb5/numpy-1.25.1/setup.py", line 22, in <module>
        setattr(__builtins__, name, value)
    RuntimeError: Python version >= 3.9 required.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-uzl1j7iz/paddle-bfloat/
You are using pip version 18.1, however version 23.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@wangan-GW-001M1A-FTF:/home/wangan/桌面#

**Comment by Phoenix2Legend** [comment]
whl包是用Python3.7编的但是现在提示说Python版本必须大于等于3.9，这不是矛盾吗？应该怎么解决

**Comment by qili93** [comment]
根据错误提示，这个是在安装numpy 1.25.1时候报错，根据Numpy的版本信息，1.25.1仅支持python 3.9 - 3.11的版本，您这里需要先安装一个低版本的numpy后再安装 paddlepaddle的whl包试下，或者您也可以尝试升级你的python版本到3.9。

Numpy 的 python版本要求见：https://github.com/numpy/numpy/releases/tag/v1.25.1

![image](https://github.com/PaddlePaddle/Paddle/assets/16605440/6da96586-3dad-46b6-957c-64639960f306)

**Comment by Phoenix2Legend** [comment]
root@wangan-GW-001M1A-FTF:/home/wangan/桌面# pip install numpy==1.16.2
Collecting numpy==1.16.2
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f76ef5100>: Failed to establish a new connection: [Errno 101] 网络不可达')': /packages/cf/8d/6345b4f32b37945fedc1e027e83970005fc9c699068d2f566b82826515f2/numpy-1.16.2.zip
^CERROR: Operation cancelled by user
