### ISSUE TITLE
MTMTC : IndexError: list index out of range

### ISSUE THREAD

**Issue by FrankMMMMMM** [PaddlePaddle/Paddle#55543]
### 请提出你的问题 Please ask your question

您好 

我按照安装文档进行PaddleDetection安装（PaddlePaddle==2.5.2）并进行测试通过

我按照（https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.6/deploy/pptracking/python#4-%E8%BD%A6%E8%BE%86%E8%B7%A8%E9%95%9C%E5%A4%B4%E8%B7%9F%E8%B8%AA%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B）的步骤运行代码，除tracker外没有更改任何地方。但是出现如下错误，该如何解决？

“
Traceback (most recent call last):
  File "deploy/pptracking/python/mot_sde_infer.py", line 952, in <module>
    main()
  File "deploy/pptracking/python/mot_sde_infer.py", line 921, in main
    detector.predict_mtmct(FLAGS.mtmct_dir, mtmct_cfg)
  File "deploy/pptracking/python/mot_sde_infer.py", line 865, in predict_mtmct
    roi_dir=roi_dir)
  File "/home/aistudio/MTMCT/PaddleDetection-release-2.6/deploy/pptracking/python/mot/mtmct/postprocess.py", line 148, in gen_res
    cid = scene_cluster[idx]
IndexError: list index out of range
”
![image](https://github.com/PaddlePaddle/Paddle/assets/92253265/85980fed-856d-469f-bee5-a3ca607ebbfd)

感谢回复！

**Comment by JunnYu** [comment]
你好，这个问题可以到 https://github.com/PaddlePaddle/PaddleDetection/issues 去咨询一下

**Comment by FrankMMMMMM** [comment]
才发现 咨询错地方了 
感谢
