### ISSUE TITLE
c_split backward failure in dygraph

### ISSUE THREAD

**Issue by Tom-Zheng** [PaddlePaddle/Paddle#55565]
### bug描述 Describe the Bug

c_split backward encounters error:

```
Traceback (most recent call last):
  File "/home/scratch.tizheng_sw/projects/transformerengine/test_c_split.py", line 34, in <module>
    b.backward(grad)
  File "/usr/local/lib/python3.10/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/framework.py", line 449, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/dygraph/tensor_patch_methods.py", line 298, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when DenseTensor::place() is called.
  [Hint: holder_ should not be null.] (at /opt/paddle/paddle/paddle/phi/core/dense_tensor_impl.cc:58)
  [operator < c_allgather > error]
```

Reproduce code:

```
# file: test_c_split.py
import paddle
import numpy as np
import random
import paddle.distributed as dist
import paddle.fluid as fluid
import paddle.distributed.fleet as fleet
from paddle.distributed.fleet.layers.mpu import mp_ops

def set_random_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    paddle.seed(seed)

strategy = fleet.DistributedStrategy()
strategy.hybrid_configs = {
    "dp_degree": 1,
    "mp_degree": 2,
    "pp_degree": 1,
}
fleet.init(is_collective=True, strategy=strategy)

hcg = fleet.get_hybrid_communicate_group()
group = hcg.get_model_parallel_group()
rank_id = dist.get_rank()

set_random_seed(1024)

a = paddle.rand([8, 16])
a.stop_gradient = False

b = mp_ops._c_split(a, group=group)

grad = paddle.rand([8, 8])
b.backward(grad)

print('a:', a)
print(f'rank: {rank_id}; b: {b}')
print('a.grad: ', a.grad)
```

Reproduce command:
```
CUDA_VISIBLE_DEVICES=0,1 python -m paddle.distributed.launch test_c_split.py
```

**Comment by Tom-Zheng** [comment]
麻烦分布式的同学解答一下。

**Comment by ForFishes** [comment]
您好，这个_c_split并不是一个对外使用的API，不能使用它的反向。如果需要可以使用 ``RowParallelLinear`` 来实现MP的计算。

**Comment by Tom-Zheng** [comment]
@ForFishes 但用`RowParallelLinear`一样会有这个问题, 因为`RowParallelLinear` 在forward中调用了`_c_split`.

复现代码:
```python
# file: test_c_split.py
import paddle
import numpy as np
import random
import paddle.distributed as dist
import paddle.fluid as fluid
import paddle.distributed.fleet as fleet
from paddle.distributed.fleet.layers.mpu import mp_ops

def set_random_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    paddle.seed(seed)

strategy = fleet.DistributedStrategy()
strategy.hybrid_configs = {
    "dp_degree": 1,
    "mp_degree": 2,
    "pp_degree": 1,
}
fleet.init(is_collective=True, strategy=strategy)

hcg = fleet.get_hybrid_communicate_group()
group = hcg.get_model_parallel_group()
rank_id = dist.get_rank()

set_random_seed(1024)

a = paddle.rand([8, 16])
a.stop_gradient = False

# b = mp_ops._c_split(a, group=group)
layer = fleet.meta_parallel.RowParallelLinear(
            16,
            16,
            input_is_parallel=False,
            has_bias=True)

b = layer(a)

grad = paddle.rand([8, 16])
b.backward(grad)

print('a:', a)
print(f'rank: {rank_id}; b: {b}')
print('a.grad: ', a.grad)
```
错误log:

```
Traceback (most recent call last):
  File "/home/scratch.tizheng_sw/tmp/test_c_split.py", line 42, in <module>
    b.backward(grad)
  File "/usr/local/lib/python3.10/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/framework.py", line 449, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/dygraph/tensor_patch_methods.py", line 298, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when DenseTensor::place() is called.
  [Hint: holder_ should not be null.] (at /opt/paddle/paddle/paddle/phi/core/dense_tensor_impl.cc:58)
  [operator < c_allgather > error]
```

**Comment by ForFishes** [comment]
您好，目前看确实是bug，后续进行修复这个问题。

**Comment by tianshuo78520a** [comment]
[PR56917](https://github.com/PaddlePaddle/Paddle/pull/56917) 应该可以解决问题

**Comment by Tom-Zheng** [comment]
@tianshuo78520a 测试OK

**Comment by Tom-Zheng** [comment]
Good to close.
