### ISSUE TITLE
test_imperative_signal_handler单测不通过

### ISSUE THREAD

**Issue by zepingWww** [PaddlePaddle/Paddle#55591]
### 请提出你的问题 Please ask your question

在docker中paddle编译完成后，通过paddle_build.sh进行单测，发现test_imperative_signal_handler failed。
报的错误有点奇怪，提示increasing the shared storage space，但是我已经在docker中分配了16g共享内存了。

```
test 1175
    Start 1175: test_imperative_signal_handler

1175: Test command: /usr/local/bin/cmake "-E" "env" "PYTHONPATH=/root/Paddle/build/python" "/root/miniconda3/envs/paddle_build/bin/python3.8" "/root/Paddle/tools/test_runner.py" "test_imperative_signal_handler"
1175: Test timeout computed to be: 10000000
1175: ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
1175:
1175: ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
1175:
1175: ERROR: Unexpected segmentation fault encountered in DataLoader workers.
1175:
1175: test_imperative_signal_handler failed
1175:  ..F.
1175: ======================================================================
1175: FAIL: test_child_process_killed_by_sigsegv (test_imperative_signal_handler.DygraphDataLoaderSingalHandler)
1175: ----------------------------------------------------------------------
1175: Traceback (most recent call last):
1175:   File "/root/Paddle/build/test/legacy_test/test_imperative_signal_handler.py", line 79, in try_except_exit
1175:     time.sleep(5)
1175:   File "/root/Paddle/build/test/legacy_test/test_imperative_signal_handler.py", line 32, in __handler__
1175:     core._throw_error_if_process_failed()
1175: SystemError: (Fatal) DataLoader process (pid   1. If run DataLoader by DataLoader.from_generator(...), queue capacity is set by from_generator(..., capacity=xx, ...).
1175:   2. If run DataLoader by DataLoader(dataset, ...), queue capacity is set as 2 times of the max value of num_workers and len(places).
1175:   3. If run by DataLoader(dataset, ..., use_shared_memory=True), set use_shared_memory=False for not using shared memory.) exited is killed by signal: 16112.
1175:   It may be caused by insufficient shared storage space. This problem usually occurs when using docker as a development environment.
1175:   Please use command `df -h` to check the storage space of `/dev/shm`. Shared storage space needs to be greater than (DataLoader Num * DataLoader queue capacity * 1 batch data size).
1175:   You can solve this problem by increasing the shared storage space or reducing the queue capacity appropriately.
1175: Bus error (at /root/Paddle/paddle/fluid/imperative/data_loader.cc:184)
1175:
1175:
1175: During handling of the above exception, another exception occurred:
1175:
1175: Traceback (most recent call last):
1175:   File "/root/Paddle/build/test/legacy_test/test_imperative_signal_handler.py", line 88, in test_child_process_killed_by_sigsegv
1175:     exception = try_except_exit()
1175:   File "/root/Paddle/build/test/legacy_test/test_imperative_signal_handler.py", line 81, in try_except_exit
1175:     self.assertIn("Segmentation fault", str(ex))
1175: AssertionError: 'Segmentation fault' not found in '(Fatal) DataLoader process (pid   1. If run DataLoader by DataLoader.from_generator(...), queue capacity is set by from_generator(..., capacity=xx, ...).\n  2. If run DataLoader by DataLoader(dataset, ...), queue capacity is set as 2 times of the max value of num_workers and len(places).\n  3. If run by DataLoader(dataset, ..., use_shared_memory=True), set use_shared_memory=False for not using shared memory.) exited is killed by signal: 16112.\n  It may be caused by insufficient shared storage space. This problem usually occurs when using docker as a development environment.\n  Please use command `df -h` to check the storage space of `/dev/shm`. Shared storage space needs to be greater than (DataLoader Num * DataLoader queue capacity * 1 batch data size).\n  You can solve this problem by increasing the shared storage space or reducing the queue capacity appropriately.\nBus error (at /root/Paddle/paddle/fluid/imperative/data_loader.cc:184)\n'
1175:
1175: ----------------------------------------------------------------------
1175: Ran 4 tests in 11.504s
1175:
1175: FAILED (failures=1)
1175:
1/1 Test #1175: test_imperative_signal_handler ...***Failed   14.94 sec
```

**Comment by risemeup1** [comment]
这是dataloador挂了吧，或许只是16g的共享内存还不够？并且这个单测好像已经废弃了，可以不管

**Comment by zepingWww** [comment]
> 这是dataloador挂了吧，或许只是16g的共享内存还不够？并且这个单测好像已经废弃了，可以不管

是我docker的问题，看上去是响应脚本太慢了，后来我修改了一下可以了，处理segv信号的时候接受到bus的原因。
