### ISSUE TITLE
preprocess.sh脚本出错

### ISSUE THREAD

**Issue by shouwangzhe** [PaddlePaddle/Paddle#556]
Traceback (most recent call last):
  File "preprocess.py", line 40, in <module>
    parse_queue = Queue(maxsize=max_queue_size + num_tokenize)
  File "/home/work/opdir/lvpengbin/soft/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/multiprocessing/__init__.py", line 217, in Queue
    from multiprocessing.queues import Queue
  File "/home/work/opdir/lvpengbin/soft/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/multiprocessing/queues.py", line 48, in <module>
    from .synchronize import Lock, BoundedSemaphore, Semaphore, Condition
  File "/home/work/opdir/lvpengbin/soft/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/multiprocessing/synchronize.py", line 59, in <module>
    " function, see issue 3770.")
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

**Comment by reyoung** [comment]
Duplicated with #472

**Comment by backyes** [comment]
duplicated issue, so close it.
