### ISSUE TITLE
argument 'X' (position 0) must be Tensor, but got Tensor

### ISSUE THREAD

**Issue by 1034829217** [PaddlePaddle/Paddle#55749]
### bug描述 Describe the Bug

Traceback (most recent call last):
  File "train_VDSH_paddle.py", line 109, in <module>
    logprob_w, mu, logvar = model(xb)
  File "/data2/zgq/miniconda3/envs/temp1/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data2/zgq/VDSH/models/VDSH_paddle.py", line 48, in forward
    mu, logvar = self.encode(document_mat)
  File "/data2/zgq/VDSH/models/VDSH_paddle.py", line 34, in encode
    h = self.encoder(doc_mat)
  File "/data2/zgq/miniconda3/envs/temp1/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data2/zgq/miniconda3/envs/temp1/lib/python3.8/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/data2/zgq/miniconda3/envs/temp1/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data2/zgq/miniconda3/envs/temp1/lib/python3.8/site-packages/paddle/nn/layer/common.py", line 171, in forward
    out = F.linear(
  File "/data2/zgq/miniconda3/envs/temp1/lib/python3.8/site-packages/paddle/nn/functional/common.py", line 1473, in linear
    pre_bias = _C_ops.matmul_v2(x, weight, 'trans_x', False, 'trans_y',
ValueError: (InvalidArgument) matmul_v2(): argument 'X' (position 0) must be Tensor, but got Tensor (at /paddle/paddle/fluid/pybind/op_function.h:816)

PaddleX推理程序报错

**Comment by zhwesky2010** [comment]
@1034829217 请问这个代码是不是有问题，这个显示是matmul第一个输入参数不是参数，请检查下输入是否正确
