### ISSUE TITLE
pyinstaller 无法打包 import paddle

### ISSUE THREAD

**Issue by gl94** [PaddlePaddle/Paddle#55750]
### 请提出你的问题 Please ask your question

使用conda环境安装了paddle cpu 2.5.0版本，我的工程目录如下：
![图片](https://github.com/PaddlePaddle/Paddle/assets/26252750/2adfd9e7-f9b6-409d-9687-28de04d4e70b)
我的main函数仅仅是import paddle并使用paddle.__verison__
![图片](https://github.com/PaddlePaddle/Paddle/assets/26252750/ae12ed84-1f8f-44eb-a68c-eee1b71f8a81)
在conda环境下运行main函数运行正常：
![图片](https://github.com/PaddlePaddle/Paddle/assets/26252750/4e9b729d-18a7-497a-ab1b-bb54ef943438)
使用最简单的打包命令：
![图片](https://github.com/PaddlePaddle/Paddle/assets/26252750/855e86b0-2662-4424-bbc7-06a545ce49e2)
在dist文件夹下也能找到paddle包：
![图片](https://github.com/PaddlePaddle/Paddle/assets/26252750/7ed825b7-0b4b-47eb-b0b9-89d745e9b5e1)
运行./dist/test/test失败：
./dist/test/test
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import paddle
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/__init__.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/framework/__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/framework/random.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/fluid/__init__.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/fluid/framework.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "paddle/fluid/core.py", line 394, in <module>
  File "paddle/fluid/core.py", line 386, in set_paddle_lib_path
TypeError: sequence item 0: expected str instance, NoneType found
[56416] Failed to execute script 'test' due to unhandled exception!
此外也尝试在anaconda/envs/fast/lib/python3.7/site-packages中找到paddle和paddleocr文件夹拷贝到dist/test/文件夹下:
![图片](https://github.com/PaddlePaddle/Paddle/assets/26252750/52a2d1cd-3779-4fca-9fb9-f9ba5e68e5f4)
![图片](https://github.com/PaddlePaddle/Paddle/assets/26252750/cb9e2e46-f56d-4eb0-b090-4a7232e54644)
依旧无法运行，出现同样的错误

**Comment by warmpine** [comment]
一样的问题，请问现在解决了吗

**Comment by gl94** [comment]
> 

Ubuntu下Import paddle后面没有尝试了，fastdeploy版本的推理可以打包，openvino推理，把site-packages下面那些openvino的动态库放进去就可以了。或者你在windows下试试Qpt，参考https://www.bilibili.com/video/BV16r4y1W7uv

**Comment by gl94** [comment]
> 一样的问题，请问现在解决了吗

Ubuntu下Import paddle后面没有尝试了，fastdeploy版本的推理可以打包，openvino推理，把site-packages下面那些openvino的动态库放进去就可以了。或者你在windows下试试Qpt，参考https://www.bilibili.com/video/BV16r4y1W7uv

**Comment by gl94** [comment]
> 一样的问题，请问现在解决了吗

fastdeploy用openvino或者TRT推理，绕过了import paddle，后面服务化部署你需要自己在外面包一层web服务

**Comment by tianzuishiwo** [comment]
解决方案参考 https://blog.csdn.net/aqqwvfbukn/article/details/120553124

**Comment by gl94** [comment]
> 解决方案参考 https://blog.csdn.net/aqqwvfbukn/article/details/120553124

厉害了 谢谢

**Comment by xunxun2022** [comment]
我也遇到一样的问题，难道是paddle不能pyinstaller吗？

**Comment by PlumBlossomMaid** [comment]
打包Paddle建议使用前熊厂资深深度学习大佬GT的[QPT](https://github.com/QPT-Family/QPT)项目，成功率要比pyinstaller高很多。
