### ISSUE TITLE
windows安装paddlepaddle库后，一直报错，linux正常运行

### ISSUE THREAD

**Issue by zhaohong-ponyai** [PaddlePaddle/Paddle#55878]
### bug描述 Describe the Bug

通过官方文档，安装paddlepaddle库
python -m pip install paddlepaddle -i https://pypi.tuna.tsinghua.edu.cn/simple

然后运行检查语句
import paddle

报错如下：
Error: Can not import paddle core while this file exists: K:\code\py_demo\venv\lib\site-packages\paddle\fluid\libpaddle.pyd
Traceback (most recent call last):
  File "K:\code\py_demo\venv\lib\site-packages\paddle\fluid\core.py", line 269, in <module>
    from . import libpaddle
ImportError: DLL load failed while importing libpaddle: 动态链接库(DLL)初始化例程失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\code\py_demo\venv\lib\site-packages\paddleocr\__init__.py", line 14, in <module>
    from .paddleocr import *
  File "K:\code\py_demo\venv\lib\site-packages\paddleocr\paddleocr.py", line 21, in <module>
    import paddle
  File "K:\code\py_demo\venv\lib\site-packages\paddle\__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "K:\code\py_demo\venv\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "K:\code\py_demo\venv\lib\site-packages\paddle\framework\random.py", line 17, in <module>
    from paddle import fluid
  File "K:\code\py_demo\venv\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "K:\code\py_demo\venv\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "K:\code\py_demo\venv\lib\site-packages\paddle\fluid\core.py", line 351, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined

### 其他补充信息 Additional Supplementary Information
环境：windows10
python：Python 3.10.11
paddlepaddle-2.5.1
无GPU版本

补充：
同样代码，在linux上面跑正常运行，在windows上面跑一直提示上面报错，试过安装其他版本的paddle也是报错

**Comment by lyuwenyu** [comment]
在安装时候加上版本号试一下 eg. paddlepaddle==2.5.1

**Comment by hxi667** [comment]
我也是这个问题，安装完后报错
![image](https://github.com/PaddlePaddle/Paddle/assets/48883474/df37345a-47de-4f93-9917-ea98ddadedcb)
，
win10
cuda版本10.2
python版本3.10
安装命令
python -m pip install paddlepaddle-gpu==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
