### ISSUE TITLE
AssertionError: Optimizer set error, conv2d_0.w_0_moment1_0 should in state dict

### ISSUE THREAD

**Issue by Husky1999** [PaddlePaddle/Paddle#55900]
### 请提出你的问题 Please ask your question

在加载所保存模型后继续训练时报错，加载代码如下

self.model.load(self.model_params)

报错信息如下：

Traceback (most recent call last):
  File "D:/work//ui/main.py", line 369, in pushButton_train
    self.train_model.train()                                                 # 开始迁移
  File "D:\work\\ui\fine_tuning.py", line 69, in train
    self.model.fit(train_data=self.train_custom_dataset,
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\paddle\hapi\model.py", line 1929, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\paddle\hapi\model.py", line 2282, in _run_one_epoch
    outs = getattr(self, mode + '_batch')(*_inputs)
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\paddle\hapi\model.py", line 1207, in train_batch
    loss = self._adapter.train_batch(inputs, labels, update)
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\paddle\hapi\model.py", line 821, in train_batch
    self.model._optimizer.minimize(final_loss)
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\paddle\optimizer\optimizer.py", line 1394, in minimize
    optimize_ops = self._apply_optimize(
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\paddle\optimizer\optimizer.py", line 1166, in _apply_optimize
    optimize_ops = self._create_optimization_pass(
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\paddle\optimizer\optimizer.py", line 924, in _create_optimization_pass
    self._create_accumulators(
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\paddle\optimizer\adam.py", line 337, in _create_accumulators
    self._add_moments_pows(p)
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\paddle\optimizer\adam.py", line 293, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "D:\Users\ESI\anaconda3\envs\ppaddle\lib\site-packages\paddle\optimizer\optimizer.py", line 753, in _add_accumulator
    assert (
AssertionError: Optimizer set error, conv2d_0.w_0_moment1_0 should in state dict

当所保存模型不包含优化器参数（.pdopt文件）时，不报错，依据问题搜索，报错原因可判断为命名空间中已经有了conv2d，命名不匹配

报错参考链接：
https://aistudio.baidu.com/paddle/forum/topic/show/989540
https://github.com/PaddlePaddle/Paddle/issues/37968

当前方案：
当前项目需要对训练后的模型加载继续训练，重启编译器并不适合该项目
加载模型时不加载优化器参数（.pdopt文件），精度损失严重，不适合该项目
只使用SGD优化器，项目需包括adam等多个优化器，不适合该项目

请问有无其他解决方案

**Comment by zhiboniu** [comment]
是不是模型保存后，又改了模型结构，导致重新加载时optimizer里的参数跟模型对不上？

**Comment by Husky1999** [comment]
> 

模型结构没有更改，但继续训练时又重新实例化了一边模型

**Comment by zhiboniu** [comment]
如果没有更新应该命名会是一样的，你可以检查一下保存前后的模型结构，这个conv2d_0.w_0_moment1_0是怎么发生变化的。
