### ISSUE TITLE
CTR model fail to run due to no attribute 'sparse_vector'

### ISSUE THREAD

**Issue by tanzhongyibidu** [PaddlePaddle/Paddle#5606]
when I run CTR models from http://staging.paddlepaddle.org/docs/develop/models/ctr/README.html, the script is "python train.py --train_data_path ./output/train.txt --test_data_path ./output/test.txt --data_meta_file ./output/data.meta.txt --model_type=0"
I am using latest paddle docker image, 
it failed, the error message is "INFO:paddle:dnn input dim: 61
INFO:paddle:lr input dim: 10040001
Traceback (most recent call last):
  File "train.py", line 111, in <module>
    train()
  File "train.py", line 66, in train
    is_infer=False)
  File "/home/workspace/models/ctr/network_conf.py", line 34, in __init__
    self._declare_input_layers()
  File "/home/workspace/models/ctr/network_conf.py", line 53, in _declare_input_layers
    type=paddle.data_type.sparse_vector(self.lr_input_dim))
AttributeError: 'module' object has no attribute 'sparse_vector'

**Comment by pkuyym** [comment]
您试试这个类型 sparse_non_value_slot

**Comment by tanzhongyibidu** [comment]
diff --git a/ctr/network_conf.py b/ctr/network_conf.py
index b01e487..b04f252 100644
--- a/ctr/network_conf.py
+++ b/ctr/network_conf.py
@@ -50,7 +50,7 @@ class CTRmodel(object):
 
         self.lr_merged_input = layer.data(
             name='lr_input',
-            type=paddle.data_type.sparse_vector(self.lr_input_dim))
+            type=paddle.data_type.sparse_non_value_slot(self.lr_input_dim))
 
         if not self.is_infer:
             self.click = paddle.layer.data(

改为如上之后，再跑train.py, 报如下的错误
Traceback (most recent call last):
  File "train.py", line 111, in <module>
    train()
  File "train.py", line 107, in train
    num_passes=args.num_passes)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/trainer.py", line 169, in train
    in_args = feeder(data_batch)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 282, in __call__
    return self.convert(dat, argument)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/data_feeder.py", line 133, in convert
    return DataProviderConverter.convert(self, reorder_data(dat), argument)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 277, in convert
    scanner.finish_scan(argument)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 180, in finish_scan
    m.sparseCopyFrom(self.__rows__, self.__cols__, self.__value__)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 1193, in sparseCopyFrom
    return _swig_paddle.Matrix_sparseCopyFrom(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'Matrix_sparseCopyFrom'.
  Possible C/C++ prototypes are:
    Matrix::sparseCopyFrom(std::vector< int,std::allocator< int > > const &,std::vector< int,std::allocator< int > > const &,std::vector< float,std::allocator< float > > const &)
    Matrix::sparseCopyFrom(std::vector< int,std::allocator< int > > const &,std::vector< int,std::allocator< int > > const &)

**Comment by pkuyym** [comment]
Please change ```sparse_vector``` to ```sparse_float_vector```
