### ISSUE TITLE
import paddle error - cpu

### ISSUE THREAD

**Issue by zorro-gridi** [PaddlePaddle/Paddle#56097]
### 请提出你的问题 Please ask your question

>>> import paddle
Error: Can not import paddle core while this file exists: /home/zorro/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zorro/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/home/zorro/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/zorro/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/home/zorro/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/zorro/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/zorro/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/home/zorro/miniconda3/envs/paddle/lib/python3.10/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: /lib64/libssl.so.1.1: symbol BIO_dgram_sctp_wait_for_dry, version OPENSSL_1_1_0 not defined in file libcrypto.so.1.1 with link time reference
>>>

**Comment by zhengqiwen1997** [comment]
请升级openssl到v1.1.1再尝试。若还不行，请提供安装方式和操作系统环境。

**Comment by zorro-gridi** [comment]
环境删除重装可以了，不知道是不是之前使用gpu环境的原因。
