### ISSUE TITLE
Error: Can not import paddle core while this file exists: /Users/username/env/lib/python3.8/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by prnvsheth** [PaddlePaddle/Paddle#56244]
### bug描述 Describe the Bug

`from paddleocr import PaddleOCR`

Error: Can not import paddle core while this file exists: /Users/users/env/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/env/lib/python3.8/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/Users/username/env/lib/python3.8/site-packages/paddleocr/paddleocr.py", line 21, in <module>
    import paddle
  File "/Users/username/env/lib/python3.8/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/Users/username/env/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/Users/username/env/lib/python3.8/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/Users/username/env/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/Users/username/env/lib/python3.8/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/Users/username/env/lib/python3.8/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/Users/username/env/lib/python3.8/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: dlopen(/Users/username/env/lib/python3.8/site-packages/paddle/fluid/libpaddle.so, 2): Symbol not found: __ZNSt3__113basic_filebufIcNS_11char_traitsIcEEE5closeEv
  Referenced from: /Users/username/env/lib/python3.8/site-packages/paddle/fluid/libpaddle.so (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib

Tried to set LD_LIBRARY_PATH as /Users/username/env/lib but issue is not resolved using this.

macOS Catalina 10.15.7
python 3.8.10
paddlepaddle 2.5.1
paddleocr 2.7.0.2

**Comment by zhengqiwen1997** [comment]
可以参考https://stackoverflow.com/questions/76388016/error-can-not-import-paddle-core-while-this-file-exists，重新安装下试试

**Comment by prnvsheth** [comment]
This did not resolve my problem, it seems the latest version of paddlepaddle (2.5.1) is built for MacOS 13 whereas I have MacOS 10.15 and hence it did not work. I installed paddlepaddle (2.3.2) and am able to use paddleOCR properly. Please close the issue for now.

**Comment by yanhuixie** [comment]
好悲伤的故事。。难道macOS 13.x以下的版本不再支持了吗？
