### ISSUE TITLE
paddle.load 错误

### ISSUE THREAD

**Issue by yangguohao** [PaddlePaddle/Paddle#56628]
### bug描述 Describe the Bug

问题：在完成的 aistudio 脚本任务的下载输出中下载训练后的模型参数 *.pdparams 的文件，之后在本地使用 paddle.load 加载却出现报错。

后面尝试复现该错误，发现模型在没训练之前直接进行 save 和 load 都是正常的。但是我训练好的模型参数就不行，训练的过程也没有其他报错。

此 issues 记录一下，看看之后是否有其他人遇到类似的问题。

### 其他补充信息 Additional Supplementary Information

```
Traceback (most recent call last):
  File "C:\Users\62367\miniconda3\envs\paddle_develop\lib\site-packages\paddle\framework\io.py", line 1067, in load
    load_result = pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: pickle data was truncated

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\62367\miniconda3\envs\paddle_develop\lib\site-packages\paddle\framework\io.py", line 1105, in load
    tensor, _ = _load_selected_rows(path)
  File "C:\Users\62367\miniconda3\envs\paddle_develop\lib\site-packages\paddle\framework\io.py", line 610, in _load_selected_rows
    _seek = core.load_selected_rows(temp_sr, file_name)
ValueError: (InvalidArgument) Only version 0 SelectedRows is supported.
  [Hint: Expected version == 0U, but received version:2996110464 != 0U:0.] (at ..\paddle\fluid\framework\selected_rows_utils.cc:71)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\62367\miniconda3\envs\paddle_develop\lib\site-packages\paddle\framework\io.py", line 1109, in load
    tensor, _ = _load_lod_tensor(path)
  File "C:\Users\62367\miniconda3\envs\paddle_develop\lib\site-packages\paddle\framework\io.py", line 567, in _load_lod_tensor
    _seek = paddle.fluid.core.load_lod_tensor(temp_t, file_name)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 2996110464 found).
  [Hint: Expected version == 0U, but received version:2996110464 != 0U:0.] (at ..\paddle\fluid\framework\lod_tensor.cc:301)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\62367\miniconda3\envs\paddle_develop\lib\site-packages\paddle\framework\io.py", line 1120, in load
    program = Program.parse_from_string(
  File "C:\Users\62367\miniconda3\envs\paddle_develop\lib\site-packages\paddle\fluid\framework.py", line 6534, in parse_from_string
    p.desc = core.ProgramDesc(binary_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at ..\paddle\fluid\framework\program_desc.cc:150)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\62367\pythonProject\Paddle\test.py", line 83, in <module>
    load_test()
  File "C:\Users\62367\pythonProject\Paddle\test.py", line 79, in load_test
    paddle.load('model_best.pdparams')
  File "C:\Users\62367\miniconda3\envs\paddle_develop\lib\site-packages\paddle\framework\io.py", line 1125, in load
    raise ValueError(
ValueError: `paddle.load` can not parse the file:model_best.pdparams.
```

**Comment by yangguohao** [comment]
已经补充了报错信息 @sunzhongkai588

**Comment by wuhuachaocoding** [comment]
@YuanRisheng 辛苦帮忙看下用户的这个问题

**Comment by YuanRisheng** [comment]
请问一下模型参数保存是怎么保存的，是使用paddle.save保存的吗

**Comment by yangguohao** [comment]
是的 大概是这样
```
#     if(best_accuracy<eval_accu):
#         best_accuracy=eval_accu
#         # 保存模型
#         save_param_path = os.path.join(best_dir, 'model_best.pdparams')
#         paddle.save(model.state_dict(), save_param_path)
```

**Comment by YuanRisheng** [comment]
把复现代码发一下，我复现一下问题

**Comment by yangguohao** [comment]
> 把复现代码发一下，我复现一下问题

```
import paddle
from paddle.vision import models
import paddle
from paddlenlp.transformers import AutoModel, AutoTokenizer, ErnieMModel, ErnieMTokenizer,ErnieViLModel,ErnieViLProcessor
from paddle.nn import functional as F
from paddle import nn
# import matplotlib.pyplot as plt
from paddleclas import CSWinTransformer_large_224
import numpy as np

class VisionModel(nn.Layer):
    def __init__(self):
        super(VisionModel, self).__init__()
        model = CSWinTransformer_large_224(pretrained=True, class_num=1024)
        # child = list(model.children())
        # self.model = nn.Sequential(child[0], *list(child[1].children()), child[2])
        self.model = model
    def forward(self, x):
        return self.model(x)
        

class NetWork(nn.Layer):
    def __init__(self, mode):
        super(NetWork, self).__init__()
        self.mode = mode           
        self.ernie = AutoModel.from_pretrained('ernie-3.0-xbase-zh')
        self.tokenizer = AutoTokenizer.from_pretrained('ernie-3.0-xbase-zh')
        text_feature_dim = 1024
        image_feature_dim = 1024
        self.resnet = VisionModel()
        self.fuse = AutoModel.from_pretrained('bert-large-cased').encoder
        self.norm = nn.LayerNorm(text_feature_dim)
        self.classifier = nn.Sequential(nn.Linear(5*text_feature_dim, 1024), nn.GELU(True), nn.Linear(1024, 3))
        self.attention_text = nn.MultiHeadAttention(text_feature_dim,16)
        self.attention_image = nn.MultiHeadAttention(image_feature_dim,16)

    def forward(self,qCap,qImg,caps,imgs):
        encode_dict_qcap = self.tokenizer(text = qCap ,max_length = 128 ,truncation=True, padding='max_length')
        input_ids_qcap = encode_dict_qcap['input_ids']
        input_ids_qcap = paddle.to_tensor(input_ids_qcap)
        qcap_feature, pooled_output= self.ernie(input_ids_qcap) #(b,length,dim)
        
        caps_feature = []
        for i,caption in enumerate (caps):
            encode_dict_cap = self.tokenizer(text = caption ,max_length = 128 ,truncation=True, padding='max_length')
            input_ids_caps = encode_dict_cap['input_ids']
            input_ids_caps = paddle.to_tensor(input_ids_caps)
            cap_feature, pooled_output= self.ernie(input_ids_caps) #(b,length,dim)
            caps_feature.append(cap_feature)
        caps_feature = paddle.stack(caps_feature,axis=0) #(b,num,length,dim)
        caps_feature = caps_feature.mean(axis=1)#(b,length,dim)
        
        imgs_features = []
        qImg_features = []
        for img in imgs:
            imgs_feature = self.resnet(img) #(length,dim)
            imgs_features.append(imgs_feature)
        for qImage in qImg:
            qImg_feature = self.resnet(qImage.unsqueeze(axis=0)) #(1,dim)
            qImg_features.append(qImg_feature)
        qImg_feature = paddle.stack(qImg_features,axis=0) #(b,1,dim)
        imgs_features = paddle.stack(imgs_features,axis=0) #(b,length,dim)
        
        fuse_feature = self.norm(self.fuse(paddle.concat(x=[caps_feature, imgs_features], axis=1)).mean(axis=1))
        caps_feature = self.attention_text(qcap_feature, caps_feature, caps_feature)
        imgs_features = self.attention_image(qImg_feature, imgs_features, imgs_features)
        
        feature = paddle.concat(x=[fuse_feature, qcap_feature.mean(axis=1), caps_feature.mean(axis=1), qImg_feature.mean(axis=1), imgs_features.mean(axis=1)], axis=1)
        logits = self.classifier(feature)
        return logits

```
以上是模型部分的代码，其他的部分在这个[项目](https://aistudio.baidu.com/studio/project/partial/verify/6574751/92ddd22fcf2e4f848e99d024e1968c92)下的这个版本内
![image](https://github.com/PaddlePaddle/Paddle/assets/70266361/cf7883dc-0534-4590-9a5f-caa29707113a)

**Comment by YuanRisheng** [comment]
这个代码我这里布置复现难度较大，这个能否提供一下最小复现代码。或者能否看一下，你能成功保存加载的参数文件大小和加载失败的参数文件大小是否有明显区别？从上边的报错信息来看，可能是保存下来的文件出现了损坏，可以尝试将一个model的state_dict分成几个param文件进行保存，然后对这几个param文件进行加载看是否能解决这个问题。

**Comment by yangguohao** [comment]
最小复现代码我需要再看看，还有一些问题这是在什么情况下导致了保存的文件损坏（也没有任何的报错）。要如何把model的state_dict分别保存再加载。

**Comment by YuanRisheng** [comment]
文件损坏有可能和机器有关系，这个概率比较低，但也不是不可能。model的state_dict本质上是一个dict的字典，所以思路是这样：可以把这个dict分成多个dict，比如拆成2个或者更多个，然后对这多个dict分别使用paddle.save方法进行保存，然后再对应保存后的多个文件再使用多次paddle.load方法进行加载，看load还是否报错

**Comment by yangguohao** [comment]
好的，感谢回复
