### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'imread'

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#5667]
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 271, in handle_worker
    r = mapper(sample)
  File "reader.py", line 12, in train_mapper
    img = paddle.image.load_image(img)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 139, in load_image
    im = cv2.imread(file, flag)
AttributeError: 'NoneType' object has no attribute 'imread'
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 271, in handle_worker
    r = mapper(sample)
  File "reader.py", line 12, in train_mapper
    img = paddle.image.load_image(img)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 139, in load_image
    im = cv2.imread(file, flag)
AttributeError: 'NoneType' object has no attribute 'imread'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 271, in handle_worker
    r = mapper(sample)
  File "reader.py", line 12, in train_mapper
    img = paddle.image.load_image(img)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 139, in load_image
    im = cv2.imread(file, flag)
AttributeError: 'NoneType' object has no attribute 'imread'

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 271, in handle_worker
    r = mapper(sample)
  File "reader.py", line 12, in train_mapper
    img = paddle.image.load_image(img)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 139, in load_image
    im = cv2.imread(file, flag)
AttributeError: 'NoneType' object has no attribute 'imread'

**Comment by guoshengCS** [comment]
应该是缺少cv2吧，可以单独试下这个么

**Comment by 466821202** [comment]
就是缺少cv2, paddle book docker 里面没有  在研究怎么装呢
