### ISSUE TITLE
安装成功，import paddle导入失败

### ISSUE THREAD

**Issue by csw1844** [PaddlePaddle/Paddle#56778]
### 问题描述 Issue Description

Installing collected packages: urllib3, six, protobuf, Pillow, numpy, idna, decorator, charset-normalizer, astor, requests, paddlepaddle-gpu
Successfully installed Pillow-9.5.0 astor-0.8.1 charset-normalizer-3.2.0 decorator-5.1.1 idna-3.4 numpy-1.21.6 paddlepaddle-gpu-2.2.2.post110 protobuf-4.24.2 requests-2.31.0 six-1.16.0 urllib3-2.0.4

>>> import paddle
Error: Can not import avx core while this file exists: /home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core.py", line 294, in <module>
    raise e
  File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core_avx.so: symbol GOMP_parallel, version VERSION not defined in file libiomp5.so with link time reference
安装失败
CUDA 电脑装了很多cuda版本 链接到的是11.3

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: centos 7
GCC version: (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
Clang version: N/A
CMake version: version 2.8.12.2
Libc version: glibc 2.9
Python version: 3.7.0

CUDA version: 11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0
cuDNN version: 8.4.1
Nvidia driver version: 530.30.02
Nvidia driver List: 
GPU 0: NVIDIA GeForce RTX 3090

****************************************

**Comment by ZzSean** [comment]
你好，可以尝试`sudo apt install libgomp1`
参考https://github.com/PaddlePaddle/Paddle/issues/45146

**Comment by csw1844** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by csw1844** [comment]
> 你好，可以尝试`sudo apt install libgomp1` 参考#45146
(paddle1) [chen@node01 ~]$ sudo yum install libgomp
[sudo] chen 的密码：
已加载插件：fastestmirror, langpacks, nvidia
Loading mirror speeds from cached hostfile
 * base: mirrors.cqu.edu.cn
 * centos-sclo-rh: mirrors.ustc.edu.cn
 * centos-sclo-sclo: mirrors.cqu.edu.cn
 * epel: mirrors.bfsu.edu.cn
 * extras: mirrors.cqu.edu.cn
 * updates: mirrors.ustc.edu.cn
软件包 libgomp-4.8.5-44.el7.x86_64 已安装并且是最新版本
(paddle1) [chen@node01 ~]$ python
Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import avx core while this file exists: /home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .fluid import monkey_patch_variable
  File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core.py", line 294, in <module>
    raise e
  File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core.py", line 256, in <module>
    from .core_avx import *
ImportError: /home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core_avx.so: symbol GOMP_parallel, version VERSION not defined in file libiomp5.so with link time reference

你好，还是一样的问题，难道是没有软链接到这个嘛，还是说没有添加到系统路径
@ZzSean

**Comment by ZzSean** [comment]
那可以尝试手动把这个lib的路径加入到`LD_LIBRARY_PATH`中

**Comment by ZzSean** [comment]
若无问题将关闭此issue

**Comment by xlnn** [comment]
> ### 问题描述 Issue Description
> Installing collected packages: urllib3, six, protobuf, Pillow, numpy, idna, decorator, charset-normalizer, astor, requests, paddlepaddle-gpu Successfully installed Pillow-9.5.0 astor-0.8.1 charset-normalizer-3.2.0 decorator-5.1.1 idna-3.4 numpy-1.21.6 paddlepaddle-gpu-2.2.2.post110 protobuf-4.24.2 requests-2.31.0 six-1.16.0 urllib3-2.0.4
> 
> > > > import paddle
> > > > Error: Can not import avx core while this file exists: /home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core_avx.so
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/**init**.py", line 25, in 
> > > > from .fluid import monkey_patch_variable
> > > > File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/**init**.py", line 36, in 
> > > > from . import framework
> > > > File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in 
> > > > from . import core
> > > > File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core.py", line 294, in 
> > > > raise e
> > > > File "/home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core.py", line 256, in 
> > > > from .core_avx import *
> > > > ImportError: /home/chen/.conda/envs/paddle1/lib/python3.7/site-packages/paddle/fluid/core_avx.so: symbol GOMP_parallel, version VERSION not defined in file libiomp5.so with link time reference
> > > > 安装失败
> > > > CUDA 电脑装了很多cuda版本 链接到的是11.3
> 
> ### 版本&环境信息 Version & Environment Information
> Paddle version: N/A Paddle With CUDA: N/A
> 
> OS: centos 7 GCC version: (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2) Clang version: N/A CMake version: version 2.8.12.2 Libc version: glibc 2.9 Python version: 3.7.0
> 
> CUDA version: 11.4.120 Build cuda_11.4.r11.4/compiler.30300941_0 cuDNN version: 8.4.1 Nvidia driver version: 530.30.02 Nvidia driver List: GPU 0: NVIDIA GeForce RTX 3090

我也有这样的问题，这个paddle好难安装。如下所示。
```
>>> import paddle
Error: Can not import paddle core while this file exists: /home/class1/.conda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/class1/.conda/envs/paddle/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/class1/.conda/envs/paddle/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/class1/.conda/envs/paddle/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/class1/.conda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/class1/.conda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/class1/.conda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 338, in <module>
    raise e
  File "/home/class1/.conda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: /home/class1/.conda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/libpaddle.so: symbol GOMP_parallel, version VERSION not defined in file libiomp5.so with link time reference
```

**Comment by csw1844** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
