### ISSUE TITLE
Paddle缺少library

### ISSUE THREAD

**Issue by czmmiao** [PaddlePaddle/Paddle#56823]
### 请提出你的问题 Please ask your question

python parser.py

仅仅是model = lp.models.PaddleDetectionlayoutModel(config path="lp://Publ ayNet/ppyolov2 r50vd dcn 365e/config"
就报如下错误了：

Traceback (most recent call last):File "/home/user/chat/parser.py",line 17,in <module>
model = lp.models.PaddleDetectionlayoutModel(config path="lp://Publ ayNet/ppyolov2 r50vd dcn 365e/config"

File "/home/user/anaconda3/lib/python3.11/site-packages/layoutparser/models/base layoutmodel.py", line 87,in __new__
   requires backends(cls， CIS.DEPENDENCIES)
File "/home/user/anaconda3/lib/python3.11/site-packages/layoutparser/file utils.py", line 175, in requires backends
   raise ImportError(
ImportError: PaddleDetectionLayoutModel requires the PaddlePaddle library butt wa5not found in your environment.  Checkout the instructions on the installation page: https://github.com/PaddlePaddle/Paddle and follow the ones that match your environment.

**Comment by JamesLim-sy** [comment]
请检查是否安装了Paddle
