### ISSUE TITLE
ImportError: No module named TrainerConfig_pb2

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#5694]
Traceback (most recent call last):
  File "/paddle/work/paddle/trainer/config_parser.py", line 85, in <module>
    from paddle.proto.DataConfig_pb2 import DataConfig
  File "/paddle/work/paddle/proto/__init__.py", line 15, in <module>
    from paddle.proto.TrainerConfig_pb2 import OptimizationConfig, TrainerConfig
ImportError: No module named TrainerConfig_pb2
Traceback (most recent call last):
  File "./train.py", line 3, in <module>
    import paddle.v2 as paddle
  File "/paddle/work/paddle/v2/__init__.py", line 15, in <module>
    import optimizer
  File "/paddle/work/paddle/v2/optimizer.py", line 15, in <module>
    import paddle.trainer_config_helpers.config_parser_utils as config_parser_utils
  File "/paddle/work/paddle/trainer_config_helpers/__init__.py", line 16, in <module>
    from data_sources import *
  File "/paddle/work/paddle/trainer_config_helpers/data_sources.py", line 17, in <module>
    from paddle.trainer.config_parser import *
  File "/paddle/work/paddle/trainer/config_parser.py", line 85, in <module>
    from paddle.proto.DataConfig_pb2 import DataConfig
  File "/paddle/work/paddle/proto/__init__.py", line 15, in <module>
    from paddle.proto.TrainerConfig_pb2 import OptimizationConfig, TrainerConfig
ImportError: No module named TrainerConfig_pb2

**Comment by wanghaoshuang** [comment]
麻烦看下你的` $PYTHONPATH/site-packages/paddle/proto/ `下有没有TrainerConfig_pb2.py这个文件？

**Comment by Yancey1989** [comment]
由于这个issue长时间未更新，先关闭它了，如果问题依然存在请重新打开它。
