### ISSUE TITLE
自己标注模型数据，训练后，调用模型测试命令报错

### ISSUE THREAD

**Issue by zhangshenghang** [PaddlePaddle/Paddle#57091]
### 请提出你的问题 Please ask your question

自己标注模型数据，训练后，调用模型测试命令把报错，标注了10条数据，运行官方提供的样例数据训练的模型就可以成功，自己标注的失败

环境信息
```
GPU型号：RTX 3090
显存：24GB
CUDA:11.7
python 3.8
```
样本构建命令
```python
python label_studio.py \
    --label_studio_file ./data2/project-4-at-2023-09-07-06-13-78e5962b.json \
    --task_type ext \
    --save_dir ./data2 \
    --splits 0.8 0.1 0.1 \
    --options "正向" "负向" "未提及" \
    --negative_ratio 5 \
    --is_shuffle True \
    --seed 1000
```
模型训练命令
```python
python -u -m paddle.distributed.launch --gpus "0" finetune.py \
  --train_path ./data2/train.json \
  --dev_path ./data2/dev.json \
  --save_dir ./checkpoint2 \
  --learning_rate 1e-5 \
  --batch_size 1 \
  --max_seq_len 512 \
  --num_epochs 3 \
  --model uie-senta-base \
  --seed 1000 \
  --logging_steps 10 \
  --valid_steps 100 \
  --device gpu
```

模型测试命令
```python
python evaluate.py \
    --model_path ./checkpoint2/model_best \
    --test_path ./data2/test.json \
    --batch_size 16 \
    --max_seq_len 512 \
    --debug
```
运行结果
```
.../sentiment_analysis/unified_sentiment_extraction python evaluate.py \
>     --model_path ./checkpoint2/model_best \
>     --test_path ./data2/test.json \
>     --batch_size 16 \
>     --max_seq_len 512 \
>     --debug
/root/anaconda3/envs/nlp/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-09-08 09:51:58,639] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load './checkpoint2/model_best'.
[2023-09-08 09:51:58,666] [    INFO] - Loading configuration file ./checkpoint2/model_best/config.json
[2023-09-08 09:51:58,667] [    INFO] - Loading weights file ./checkpoint2/model_best/model_state.pdparams
[2023-09-08 09:51:59,341] [    INFO] - Loaded weights file from disk, setting weights to model.
W0908 09:51:59.346676 59224 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
W0908 09:51:59.353842 59224 gpu_resources.cc:149] device: 0, cuDNN Version: 8.5.
[2023-09-08 09:52:01,946] [    INFO] - All model checkpoint weights were used when initializing UIE.

[2023-09-08 09:52:01,946] [    INFO] - All the weights of UIE were initialized from the model checkpoint at ./checkpoint2/model_best.
If your task is similar to the task the model of the checkpoint was trained on, you can already use UIE for predictions without further training.
  0%|                                                                                                       | 0/1 [00:00<?, ?it/s]/root/anaconda3/envs/nlp/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils_base.py:2478: FutureWarning: The `max_seq_len` argument is deprecated and will be removed in a future version, please use `max_length` instead.
  warnings.warn(
/root/anaconda3/envs/nlp/lib/python3.8/site-packages/paddlenlp/transformers/tokenizer_utils_base.py:1878: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.78s/it]
[2023-09-08 09:52:03,765] [    INFO] - -----------------------------
[2023-09-08 09:52:03,765] [    INFO] - Class Name: 观点词
[2023-09-08 09:52:03,766] [    INFO] - Evaluation Precision: 0.00000 | Recall: 0.00000 | F1: 0.00000
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 35.92it/s]
[2023-09-08 09:52:03,796] [    INFO] - -----------------------------
[2023-09-08 09:52:03,796] [    INFO] - Class Name: 评价维度
[2023-09-08 09:52:03,796] [    INFO] - Evaluation Precision: 0.00000 | Recall: 0.00000 | F1: 0.00000
  0%|                                                                                                       | 0/1 [00:00<?, ?it/s]Exception in thread Thread-4:
Traceback (most recent call last):
  File "/root/anaconda3/envs/nlp/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/nlp/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/nlp/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 247, in _thread_loop
    batch = self._dataset_fetcher.fetch(
  File "/root/anaconda3/envs/nlp/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 127, in fetch
    data.append(self.dataset[idx])
  File "/root/anaconda3/envs/nlp/lib/python3.8/site-packages/paddlenlp/datasets/dataset.py", line 256, in __getitem__
    return self._transform(self.new_data[idx]) if self._transform_pipline else self.new_data[idx]
KeyError: 0
```

![image](https://github.com/PaddlePaddle/PaddleNLP/assets/29418975/30bc0263-48b9-49ec-a6f8-bb0efaf22c94)

**Comment by zhangshenghang** [comment]
有的时候还会提示这个错误
```
.../sentiment_analysis/unified_sentiment_extraction   python evaluate.py \
>     --model_path ./checkpoint4/model_best \
>     --test_path ./data4/test.json \
>     --batch_size 1 \
>     --max_seq_len 512 \
>     --debug
/root/anaconda3/envs/nlp/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2023-09-08 10:22:36,259] [    INFO] - We are using <class 'paddlenlp.transformers.ernie.tokenizer.ErnieTokenizer'> to load './checkpoint4/model_best'.
[2023-09-08 10:22:36,288] [    INFO] - Loading configuration file ./checkpoint4/model_best/config.json
[2023-09-08 10:22:36,289] [    INFO] - Loading weights file ./checkpoint4/model_best/model_state.pdparams
[2023-09-08 10:22:37,009] [    INFO] - Loaded weights file from disk, setting weights to model.
W0908 10:22:37.021351 43964 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
W0908 10:22:37.029762 43964 gpu_resources.cc:149] device: 0, cuDNN Version: 8.5.
[2023-09-08 10:22:39,648] [    INFO] - All model checkpoint weights were used when initializing UIE.

[2023-09-08 10:22:39,648] [    INFO] - All the weights of UIE were initialized from the model checkpoint at ./checkpoint4/model_best.
If your task is similar to the task the model of the checkpoint was trained on, you can already use UIE for predictions without further training.
Traceback (most recent call last):
  File "evaluate.py", line 122, in <module>
    do_eval()
  File "evaluate.py", line 76, in do_eval
    relation_type_dict = get_relation_type_dict(relation_data)
  File "/opt/jast/PaddleNLP-2.6.0/applications/sentiment_analysis/unified_sentiment_extraction/utils.py", line 256, in get_relation_type_dict
    relation_type_dict.setdefault(match, []).append(relation_data[i][1])
AttributeError: 'dict' object has no attribute 'append'
```

**Comment by FlyingQianMM** [comment]
您好，PaddleNLP相关的使用问题可以在https://github.com/PaddlePaddle/PaddleNLP 的issue空间讨论～
