### ISSUE TITLE
ExternalError: XPU conv kernel return wrong value[1 xpu api invalid param]

### ISSUE THREAD

**Issue by HelloRay123** [PaddlePaddle/Paddle#57142]
### bug描述 Describe the Bug

使用demo: https://github.com/PaddlePaddle/Paddle-Inference-Demo.git, xpu/resnet50, 在本地调用demo推理时报错，报错信息如下，平台为海光cpu+r200
resnet50 git:(master) ✗ python infer_resnet.py --model_file=./resnet50/inference.pdmodel --params_file=./resnet50/inference.pdiparams
[INFO][BKCL][baidu/xpu/bkcl/src/globals.cpp:51] set BKCL timeout to 600 seconds
[INFO][BKCL][baidu/xpu/bkcl/src/globals.cpp:52] set BKCL RING BUFFER SIZE to 1048576
XPURT /home/anaconda3/envs/py37_test/lib/python3.7/site-packages/paddle/fluid/../libs/libxpurt.so loaded
I0909 15:24:33.896591  7905 analysis_config.cc:424] use_dlnne_:0
I0909 15:24:33.896637  7905 analysis_config.cc:424] use_dlnne_:0
I0909 15:24:33.896661  7905 analysis_config.cc:424] use_dlnne_:0
I0909 15:24:33.896713  7905 analysis_config.cc:424] use_dlnne_:0
I0909 15:24:33.896726  7905 analysis_predictor.cc:155] Profiler is deactivated, and no profiling report will be generated.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [squeeze2_matmul_fuse_pass]
--- Running IR pass [reshape2_matmul_fuse_pass]
I0909 15:24:34.002950  7905 graph_pattern_detector.cc:91] ---  detected 1 subgraphs
--- Running IR pass [flatten2_matmul_fuse_pass]
--- Running IR pass [map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
I0909 15:24:34.006093  7905 graph_pattern_detector.cc:91] ---  detected 1 subgraphs
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0909 15:24:34.044224  7905 graph_pattern_detector.cc:91] ---  detected 53 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [memory_optimize_pass]
I0909 15:24:34.080053  7905 memory_optimize_pass.cc:199] Cluster name : conv2d_67.tmp_0  size: 1605632
I0909 15:24:34.080080  7905 memory_optimize_pass.cc:199] Cluster name : inputs  size: 602112
I0909 15:24:34.080085  7905 memory_optimize_pass.cc:199] Cluster name : elementwise_add_0  size: 3211264
I0909 15:24:34.080090  7905 memory_optimize_pass.cc:199] Cluster name : batch_norm_3.tmp_2  size: 3211264
I0909 15:24:34.080096  7905 memory_optimize_pass.cc:199] Cluster name : batch_norm_4.tmp_2  size: 3211264
--- Running analysis [memory_optimize_pass]
I0909 15:24:34.082901  7905 memory_optimize_pass.cc:199] Cluster name : conv2d_67.tmp_0  size: 100352
I0909 15:24:34.082911  7905 memory_optimize_pass.cc:199] Cluster name : batch_norm_3.tmp_2  size: 401408
I0909 15:24:34.082916  7905 memory_optimize_pass.cc:199] Cluster name : inputs  size: 602112
I0909 15:24:34.082921  7905 memory_optimize_pass.cc:199] Cluster name : elementwise_add_0  size: 1605632
I0909 15:24:34.082929  7905 memory_optimize_pass.cc:199] Cluster name : batch_norm_4.tmp_2  size: 802816
--- Running analysis [memory_optimize_pass]
I0909 15:24:34.084689  7905 memory_optimize_pass.cc:199] Cluster name : conv2d_67.tmp_0  size: 100352
I0909 15:24:34.084697  7905 memory_optimize_pass.cc:199] Cluster name : batch_norm_3.tmp_2  size: 401408
I0909 15:24:34.084702  7905 memory_optimize_pass.cc:199] Cluster name : inputs  size: 602112
I0909 15:24:34.084707  7905 memory_optimize_pass.cc:199] Cluster name : elementwise_add_0  size: 1605632
I0909 15:24:34.084713  7905 memory_optimize_pass.cc:199] Cluster name : batch_norm_4.tmp_2  size: 802816
--- Running analysis [ir_graph_to_program_pass]
I0909 15:24:34.119151  7905 analysis_predictor.cc:595] ======= optimize end =======
I0909 15:24:34.120741  7905 naive_executor.cc:98] ---  skip [feed], feed -> inputs
I0909 15:24:34.123297  7905 naive_executor.cc:98] ---  skip [batch_norm_3.tmp_2], fetch -> fetch
Premature end of JPEG file
[WARN][XPURT][xpu_llsync_cginfo:1419] ioctl() fail, (807) Unknown IOCTL command
W0909 15:24:34.140506  7905 device_context.cc:195] Please NOTE: xpu device: 0
Traceback (most recent call last):
  File "infer_resnet.py", line 79, in <module>
    result = run(pred, [img])
  File "infer_resnet.py", line 35, in run
    predictor.run()
OSError: 

  Compile Traceback (most recent call last):
    File "tools/export_model.py", line 79, in <module>
      main()
    File "tools/export_model.py", line 75, in main
      paddle.jit.save(model, os.path.join(args.output_path, "inference"))
    File "<decorator-gen-60>", line 2, in save
      
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/base.py", line 39, in __impl__
      return func(*args, **kwargs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/jit.py", line 680, in save
      concrete_program = static_func.concrete_program_specify_input_spec(
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 487, in concrete_program_specify_input_spec
      concrete_program, _ = self.get_concrete_program(
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 698, in _build_once
      concrete_program = ConcreteProgram.from_func_spec(
    File "<decorator-gen-58>", line 2, in from_func_spec
      
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/base.py", line 39, in __impl__
      return func(*args, **kwargs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "tools/export_model.py", line 51, in forward
      x = self.pre_net(inputs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/wilber/repo/PaddleClas/ppcls/modeling/architectures/resnet.py", line 280, in forward
      y = self.conv(inputs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/wilber/repo/PaddleClas/ppcls/modeling/architectures/resnet.py", line 69, in forward
      y = self._conv(inputs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/nn/layer/conv.py", line 648, in forward
      out = F.conv._conv_nd(
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/nn/functional/conv.py", line 143, in _conv_nd
      helper.append_op(
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/framework.py", line 3017, in append_op
      op = Operator(
    File "/wilber/repo/Paddle_wilber/build_2.0/python/paddle/fluid/framework.py", line 2107, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::XPUPlace, false, 0ul, paddle::operators::GemmConvXPUKernel<paddle::platform::XPUDeviceContext, float> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   paddle::operators::GemmConvXPUKernel<paddle::platform::XPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
7   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
8   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
ExternalError: XPU conv kernel return wrong value[1 xpu api invalid param]
  [Hint: Expected r == XPU_SUCCESS, but received r:1 != XPU_SUCCESS:0.] (at /paddle/paddle/fluid/operators/conv_op_xpu.cc:64)
  [operator < conv2d > error]
W0909 15:24:34.203203  7905 naive_best_fit_allocator.cc:207] Release XPU pool is not supported now, no action here.

**Comment by hong19860320** [comment]
看起来用的是比较老的 Paddle 库，可以 uninstall paddlepaddle-xpu ，然后重新按照这个新版的 https://paddle-device.bj.bcebos.com/develop/xpu/paddlepaddle_xpu-0.0.0-cp39-cp39-linux_x86_64.whl
