### ISSUE TITLE
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.

### ISSUE THREAD

**Issue by VanderLinde1** [PaddlePaddle/Paddle#57242]
### 请提出你的问题 Please ask your question

Traceback (most recent call last):
  File "tools/train.py", line 195, in <module>
    main(args)
  File "tools/train.py", line 170, in main
    train(
  File "e:\paddleseg\paddleseg\core\train.py", line 243, in train
    loss.backward()
  File "E:\anaconda\envs\pytorch\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\anaconda\envs\pytorch\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "E:\anaconda\envs\pytorch\lib\site-packages\paddle\fluid\framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "E:\anaconda\envs\pytorch\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 297, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.
  [Hint: Please search for the error code(8) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at C:\home\workspace\Paddle\paddle\phi\kernels\gpudnn\conv_grad_kernel.cu:502)
我将一张8000*5000的图片通过labelme标注，图片中有3中物体，我用0,1,2,来表示，我将原图和标注切分成若干个512*512小图，挑选出只含有0,1,2,和背景的图，并单独训练0,1,2，当我训练1,2，这两类时模型没有报错，当我训练0时出现上述错误。

**Comment by xiaoguoguo626807** [comment]
建议从单独训练和同时训练的网络结构和数据特性查找一下不同点。如果调整网络还不能解决，请给出完整的复现代码我们查看一下。
