### ISSUE TITLE
paddle fleet分布式框架 设置参数不同学习率时报错

### ISSUE THREAD

**Issue by lwgkzl** [PaddlePaddle/Paddle#57318]
### 请提出你的问题 Please ask your question

paddle版本： 2.2.1.
背景： 多任务学习中，同一个backbone模型有不同的头学习不同的任务， 期望各个头fc层的学习率可以不一样，但是设置的时候会有如下错误：
错误信息如下：
Traceback (most recent call last):
File "run_batch_fine_grained.py", line 466, in
train(args)
File "run_batch_fine_grained.py", line 283, in train
optimizer.minimize(loss)
File "/py37/lib/python3.7/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 1501, in minimize
loss, startup_program, parameter_list, no_grad_set=no_grad_set)
File "/py37/lib/python3.7/site-packages/paddle/distributed/fleet/meta_optimizers/meta_optimizer_base.py", line 95, in minimize
loss, startup_program, parameter_list, no_grad_set)
File "/py37/lib/python3.7/site-packages/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py", line 516, in minimize_impl
self._apply_sharding_pass(params_grads)
File "/py37/lib/python3.7/site-packages/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py", line 295, in _apply_sharding_pass
self._split_program(main_block)
File "/py37/lib/python3.7/site-packages/paddle/distributed/fleet/meta_optimizers/sharding_optimizer.py", line 746, in _split_program
assert (int(op.attr('op_role')) != int(OpRole.Optimize))
AssertionError

**Comment by kangguangli** [comment]
可以给出一个最小可复现样例吗？从报错栈上看不出太多信息，只能看出某个op的op_role属性设置不符合要求。

**Comment by lwgkzl** [comment]
这个op的设置是由于学习率的设置导致的，代码整理起来比较麻烦， 方便如流吗

**Comment by kangguangli** [comment]
可以

**Comment by lwgkzl** [comment]
请问该怎么联系你

**Comment by lwgkzl** [comment]
似乎不能通过设置参数的learning rate来设置多学习率， 而应该通过 adamw中的lr ratio参数。 示例如下： 
![image](https://github.com/PaddlePaddle/Paddle/assets/30727306/61bcf75e-5214-47ad-b6f8-b1e93c82ec12)
