### ISSUE TITLE
`paddle.Tensor.subtract` 存在非预期行为与异常

### ISSUE THREAD

**Issue by RedContritio** [PaddlePaddle/Paddle#57328]
### bug描述 Describe the Bug

`paddle.Tensor.subtract`、`paddle.Tensor.subtract_` 与 `-` 语义存在较大差异，以至于缺乏可用性。

```python
import paddle
a = paddle.to_tensor([0.5])
b = paddle.to_tensor([1])
print(a - b)                     # 满足预期 -0.5
print(a.subtract(b))        # 不满足预期，异常
print(a.subtract_(b))      # 不满足预期，非期望大整数
```

运行结果如下：

```bash
Python 3.8.10
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> a = paddle.to_tensor([0.5])
>>> b = paddle.to_tensor([1])
>>> print(a - b)                     # 满足预期 -0.5
Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=True,
       [-0.50000000])
>>> print(a.subtract(b))        # 不满足预期，异常
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/user18302289/paddleProjects/PaConvert/venv/lib/python3.8/site-packages/paddle/tensor/math.py", line 829, in subtract
    return _C_ops.subtract(x, y)
ValueError: (InvalidArgument) The type of data we are trying to retrieve (int64) does not match the type of data (float32) currently contained in the container.
  [Hint: Expected dtype() == phi::CppTypeToDataType<T>::Type(), but received dtype():10 != phi::CppTypeToDataType<T>::Type():9.] (at /paddle/paddle/phi/core/dense_tensor.cc:170)

>>> print(a.subtract_(b))      # 不满足预期，非期望大整数
Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [7310313481140445215])
>>>
```

**Comment by kangguangli** [comment]
感谢同学的反馈和给出的用例，后续我们会及时修复，进展会在issue中同步。

**Comment by Bobholamovic** [comment]
你好，`paddle.subtract`与`-`不等同是刻意的，前者需要两个输入tensor具有相同的数据类型，相比后者更加底层（不涉及tensor类型的隐式转换从而具有更高的效率）。

在这个例子中，`a`和`b`分别具有`float32`和`int64`类型，因此不满足`paddle.subtract`的要求。将`b = paddle.to_tensor([1])`修改为`paddle.to_tensor([1.])`可以得到“预期”的结果。
