### ISSUE TITLE
在开发API时，用LayerHelper进行静态图组网中proto信息的创建依据？

### ISSUE THREAD

**Issue by cocoshe** [PaddlePaddle/Paddle#57419]
### 请提出你的问题 Please ask your question

此为调用log函数
```python
import paddle
  
x = paddle.to_tensor([1, 2, 3])

paddle.enable_static()
x = paddle.static.data(name='X', shape=x.shape, dtype=x.dtype)

print(x)

out = paddle.log(x)
print(out)
```
运行上面的代码，下面是pdb查看proto中的`log`组网信息，想问一下 `name: "X"` 和 `name: "Out"` 是在哪里确定的呢？是在`math.py`中的 `LayerHelper`中确定的吗？
https://github.com/PaddlePaddle/Paddle/blob/50669e07a5c4e98a96d5d8057b0b10effc7e0204/python/paddle/tensor/math.py#L187

> debug查看log的proto信息
```
(Pdb) OpProtoHolder.instance().get_op_proto('log')
type: "log"
inputs {
  name: "X"
  comment: "(Tensor), input 0 of log op."
}
outputs {
  name: "Out"
  comment: "(Tensor), output 0 of log op."
}
attrs {
  name: "op_role"
  type: INT
  comment: "The role of this operator"
  extra: true
}
attrs {
  name: "op_role_var"
  type: STRINGS
  comment: "Optimized for variable"
  extra: true
}
attrs {
  name: "op_namescope"
  type: STRING
  comment: "Operator name with namescope."
  extra: true
}
attrs {
  name: "op_callstack"
  type: STRINGS
  comment: "Callstack for Op Creation."
  extra: true
}
attrs {
  name: "op_device"
  type: STRING
  comment: "Device type of this operator."
  extra: true
}
attrs {
  name: "with_quant_attr"
  type: BOOLEAN
  comment: "Whether the operator has attributes used by quantization. "
  extra: true
}
comment: "\nTODO: Documentation of log op.\n"

```

**Comment by cocoshe** [comment]
@zoooo0820 您方便解答嘛？

**Comment by cocoshe** [comment]
动态图没问题，就是在测静态图的时候会有下面的情况，不太明白是哪里出了问题
```
Traceback (most recent call last):
  File "mytest.py", line 16, in <module>
    out = paddle.copysign(x, y)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/tensor/math.py", line 7044, in copysign
    helper.append_op(
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/base/layer_helper.py", line 45, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/base/framework.py", line 4368, in append_op
    op = Operator(
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/base/framework.py", line 2960, in __init__
    assert (
AssertionError: Input x not found
```

**Comment by zengshao0622** [comment]
是的，由算子实现时，静态图模式下需要使用LayerHelper添加该算子，并确定静态图中的输入输出变量名。详情参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/api_contributing_guides/new_python_api_cn.html#c

**Comment by cocoshe** [comment]
> 是的，由算子实现时，静态图模式下需要使用LayerHelper添加该算子，并确定静态图中的输入输出变量名。详情参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/api_contributing_guides/new_python_api_cn.html#c

嗯嗯感谢解答~，我阅读过这份文档。
最初我是这样写的：
```python
helper.append_op(
    type='copysign', inputs={'X': x, 'Y': y}, outputs={'Out': out}
)
```
于是才有了上面`AssertionError: Input x not found`的问题，而后我把inputs和outputs的首字母大写改成小写，也就是
` inputs={'x': x, 'y': y}, outputs={'out': out}`，然后解决了`Input x not found`这个问题。


但是我在开发API的时候，修改了math.py下的LayerHelper中inputs的key（'x'改成'XX'，'y'改成''YY'，'out'改成'OOut'），如下：
```python
    if in_dynamic_mode():
        return _C_ops.copysign(x, y)
    else:
        helper = LayerHelper("copysign", **locals())
        out = helper.create_variable_for_type_inference(dtype=x.dtype)
        helper.append_op(
            # 修改了这里inputs的key
            type='copysign', inputs={'XX': x, 'YY': y}, outputs={'OOut': out}
        )
        return out
```
但是在测试时还是出现了一连串 `AssertionError: Input x not found`（按理来说不是应该是去找'XX'了吗？）
```
root@autodl-container-71164ea666-fac93834:~/autodl-tmp/Paddle/build# ctest -R test_copysign_op -V
UpdateCTestConfiguration  from :/root/autodl-tmp/Paddle/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/root/autodl-tmp/Paddle/build/DartConfiguration.tcl
Test project /root/autodl-tmp/Paddle/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 804
    Start 804: test_copysign_op

804: Test command: /usr/local/bin/cmake "-E" "env" "PYTHONPATH=/root/autodl-tmp/Paddle/build/python" "/root/miniconda3/bin/python3" "/root/autodl-tmp/Paddle/tools/test_runner.py" "test_copysign_op"
804: Working Directory: /root/autodl-tmp/Paddle/build/test/legacy_test
804: Test timeout computed to be: 10000000
804: W0918 12:42:18.567437 19365 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.2, Runtime API Version: 11.3
804: W0918 12:42:18.570410 19365 gpu_resources.cc:149] device: 0, cuDNN Version: 8.2.
804: I0918 12:42:18.593542 19365 program_interpreter.cc:136] New Executor is Running.
804: WARNING: OMP_NUM_THREADS set to 12, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
804: PLEASE USE OMP_NUM_THREADS WISELY.
804: test_copysign_op failed
804:  .F.F.F.F.F.F.F.E.F.F.F.F.F.F.F
804: ======================================================================
804: ERROR: tearDownClass (test_copysign_op.TestCopySignOp)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/eager_op_test.py", line 476, in tearDownClass
804:     raise AssertionError(
804: AssertionError: This test of copysign op needs check_grad with fp64 precision.
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignAPI)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignCPU)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignFloat32)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignFloat64)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignGPU)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignInt32)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignInt64)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignSpecialZeroCase1)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignSpecialZeroCase2)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignZeroCase1)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignZeroCase2)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignZeroCase3)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignZeroDimCase1)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ======================================================================
804: FAIL: test_static_api (test_copysign_op.TestCopySignZeroDimCase2)
804: ----------------------------------------------------------------------
804: Traceback (most recent call last):
804:   File "/root/autodl-tmp/Paddle/build/test/legacy_test/test_copysign_op.py", line 68, in test_static_api
804:     out = paddle.copysign(x, y)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/tensor/math.py", line 7044, in copysign
804:     helper.append_op(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/layer_helper.py", line 45, in append_op
804:     return self.main_program.current_block().append_op(*args, **kwargs)
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 4368, in append_op
804:     op = Operator(
804:   File "/root/autodl-tmp/Paddle/build/python/paddle/base/framework.py", line 2960, in __init__
804:     assert (
804: AssertionError: Input x not found
804: 
804: ----------------------------------------------------------------------
804: Ran 29 tests in 1.644s
804: 
804: FAILED (failures=14, errors=1)
804: 
1/1 Test #804: test_copysign_op .................***Failed    4.06 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   4.13 sec

The following tests FAILED:
        804 - test_copysign_op (Failed)
Errors while running CTest
Output from these tests are in: /root/autodl-tmp/Paddle/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```
修改了LayerHelper的key，重新make -j编译，但是看样子并没有生效（依然在找'x'），我不太熟悉组网过程中proto的机制（难道是有缓存吗，还是什么原因？），不知道您有什么看法吗？

**Comment by zengshao0622** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/108920665/cc79ed63-d857-482a-81a3-8cb5017f2856)
建议确认一下该API的python接口输入变量命名和append op时是否一致
