### ISSUE TITLE
[dependency conflicts] paddlepaddle-gpu 2.4.2.post117 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.2 which is incompatible.

### ISSUE THREAD

**Issue by neuxys** [PaddlePaddle/Paddle#57547]
### 问题描述 Issue Description

正确安装了paddlepaddle-gpu 2.4.2.post117，然后在使用命令`pip install paddlespeech`安装paddlespeech的时候提示冲突如下：

`Installing collected packages: protobuf, paddlespeech
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.0
    Uninstalling protobuf-3.20.0:
      Successfully uninstalled protobuf-3.20.0`

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlepaddle-gpu 2.4.2.post117 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.2 which is incompatible`

看起来原因是：paddlepaddle-gpu 2.4.2.post117要求protobuf<=3.20.0,>=3.1.0，但是安装paddlespeech的时候又把paddle已经安装好的protobuf-3.20.0更新为了3.20.2，从而报了这个冲突，显然，在接下来运行paddlespeech会报错。

附件信息：最开始我安装的paddle是paddlepaddle-gpu 2.5.0.post117，同样用命令`pip install paddlespeech`安装了paddlespeech，但是在运行paddlespeech时出现了错误，具体错误信息详见[这里](https://github.com/PaddlePaddle/Paddle/issues/57470)，在这个issus中，[Charles-hit](https://github.com/Charles-hit)推荐我降低paddlepaddle的版本到2.4，因此，才有了本issus的现象。

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.4.2
Paddle With CUDA: 2.4.2.post117

OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: N/A
CMake version: version 3.27.4
Libc version: glibc 2.31
Python version: 3.8.13

CUDA version: 11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
cuDNN version: 8.4.1
Nvidia driver version: 515.43.04
Nvidia driver List: 
GPU 0: NVIDIA GeForce GTX 1050 Ti
GPU 1: NVIDIA GeForce GTX 1050 Ti
****************************************

**Comment by JunnYu** [comment]
你好，我看你安装时候爆出的 error 其实不算是error，主要是安装的时候的版本不兼容。实际是可以使用的，建议你安装后实际测试一下之前tts的代码看看有没有报错信息

**Comment by neuxys** [comment]
感谢您的回复 @JunnYu !

运行`paddlespeech tts --input "你好，欢迎使用百度飞桨深度学习框架！" --output output.wav`，输出如下：

/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/home/james/anaconda3/envs/paddle/bin/paddlespeech", line 8, in <module>
    sys.exit(_execute())
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlespeech/cli/entry.py", line 40, in _execute
    exec("from {} import {}".format(module, cls))
  File "<string>", line 1, in <module>
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlespeech/cli/tts/__init__.py", line 14, in <module>
    from .infer import TTSExecutor
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlespeech/cli/tts/infer.py", line 33, in <module>
    from paddlespeech.t2s.exps.syn_utils import get_am_inference
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlespeech/t2s/exps/syn_utils.py", line 35, in <module>
    from paddlespeech.t2s.frontend.mix_frontend import MixFrontend
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlespeech/t2s/frontend/mix_frontend.py", line 22, in <module>
    from paddlespeech.t2s.frontend.zh_frontend import Frontend
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlespeech/t2s/frontend/zh_frontend.py", line 31, in <module>
    from paddlespeech.t2s.frontend.g2pw import G2PWOnnxConverter
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlespeech/t2s/frontend/g2pw/__init__.py", line 1, in <module>
    from .onnx_api import G2PWOnnxConverter
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlespeech/t2s/frontend/g2pw/onnx_api.py", line 28, in <module>
    from paddlenlp.transformers import BertTokenizer
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/__init__.py", line 35, in <module>
    from . import (
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/data/__init__.py", line 18, in <module>
    from .data_collator import *
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/data/data_collator.py", line 26, in <module>
    from ..transformers import BertTokenizer
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/transformers/__init__.py", line 17, in <module>
    from .model_utils import PretrainedModel, register_base_model
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/transformers/model_utils.py", line 62, in <module>
    from ..generation import GenerationConfig, GenerationMixin
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/generation/__init__.py", line 15, in <module>
    from .logits_process import (
  File "/home/james/anaconda3/envs/paddle/lib/python3.8/site-packages/paddlenlp/generation/logits_process.py", line 22, in <module>
    from paddle.nn.layer.layers import in_declarative_mode
ModuleNotFoundError: No module named 'paddle.nn.layer.layers'

**Comment by neuxys** [comment]
找到了[解决问题的办法](https://github.com/PaddlePaddle/PaddleSpeech/issues/3485#issuecomment-1715145045)
原话是：_当你使用pip安装paddlepaddle 2.4.2时 会自动安装最新版的paddlenlp 目前paddlenlp版本是2.6.0 该版本与paddlepaddle 2.4.2不兼容会报这个错 你需要手动pip安装paddlenlp 2.5.2版本即可_

**Comment by JunnYu** [comment]
是的，当前paddle几个库的protobuf版本都不太一致，用起来可能会出一些问题，因此需要自己手动寻找能用的一些版本
