### ISSUE TITLE
通过编译paddlepaddle源码的方式在import paddle时遇到了name 'libpaddle' is not defined的错误

### ISSUE THREAD

**Issue by lijialin1999** [PaddlePaddle/Paddle#57654]
### 问题描述 Issue Description

Python 3.7.5 (default, Sep 14 2023, 04:20:48) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/core.py", line 268, in <module>
    from . import libpaddle
ImportError: /usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/libpaddle.so: undefined symbol: pthread_atfork

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import base
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/framework.py", line 33, in <module>
    from . import core
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/core.py", line 369, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined

### 版本&环境信息 Version & Environment Information

![1695383290711](https://github.com/PaddlePaddle/Paddle/assets/145744711/bd2cfc4c-f1a6-4665-a972-a9c9dc59091f)

**Comment by lijialin1999** [comment]
dock的创建方式如下
# 下载 Dockerfile
$ wget https://paddlelite-demo.bj.bcebos.com/devices/huawei/ascend/kunpeng920_arm/Ascend_ubuntu18.04_aarch64.Dockerfile
# 通过 Dockerfile 生成镜像
$ docker build --network=host -f Ascend_ubuntu18.04_aarch64.Dockerfile -t paddlelite/ascend_aarch64:cann_3.3.0 .
# 创建容器
$ docker run -itd --name=ascend-aarch64 --net=host -v $PWD:/Work -w /Work --device=/dev/davinci0 --device=/dev/davinci_manager --device=/dev/hisi_hdc --device /dev/devmm_svm -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi  -v /usr/local/Ascend/driver/:/usr/local/Ascend/driver/ paddlelite/ascend_aarch64:cann_3.3.0 /bin/bash
# 进入容器
$ docker exec -it ascend-aarch64 /bin/bash
# 确认容器的 Ascend 环境是否创建成功
$ npu-smi info

然后源码的编译代码使用的下列代码
cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF

**Comment by lijialin1999** [comment]
docker使用下面的方式创建的
下载 Dockerfile
$ wget https://paddlelite-demo.bj.bcebos.com/devices/huawei/ascend/kunpeng920_arm/Ascend_ubuntu18.04_aarch64.Dockerfile
通过 Dockerfile 生成镜像
$ docker build --network=host -f Ascend_ubuntu18.04_aarch64.Dockerfile -t paddlelite/ascend_aarch64:cann_3.3.0 .
创建容器
$ docker run -itd --name=ascend-aarch64 --net=host -v $PWD:/Work -w /Work --device=/dev/davinci0 --device=/dev/davinci_manager --device=/dev/hisi_hdc --device /dev/devmm_svm -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi  -v /usr/local/Ascend/driver/:/usr/local/Ascend/driver/ paddlelite/ascend_aarch64:cann_3.3.0 /bin/bash
进入容器
$ docker exec -it ascend-aarch64 /bin/bash
paddle源码使用下面的代码编译的
cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF

**Comment by qili93** [comment]
您好，Paddle目前对昇腾910的支持全部已经迁移到了PaddleCustomDevice，请参考这个文档中的标准镜像进行源码编译和安装 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md

**Comment by lijialin1999** [comment]
> 您好，Paddle目前对昇腾910的支持全部已经迁移到了PaddleCustomDevice，请参考这个文档中的标准镜像进行源码编译和安装 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md

所以现在这个https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html  文档的安装方法已经不适用了吗？
