### ISSUE TITLE
windows10 多卡环境

### ISSUE THREAD

**Issue by hesongyu28** [PaddlePaddle/Paddle#57743]
我的主机装了p40 24G 和 p100 16G两张显卡 cuda安装的11.8版本。
是不是在windows下安装了多张显卡就不能使用paddle的gpu版本。
是不是必须拔掉一张显卡才能使用？

我在执行python -c "import paddle;paddle.utils.run_check()"时会报一个NCCL的错误。
/*
Running verify PaddlePaddle program ...
I0926 17:31:32.863062  4984 interpretercore.cc:237] New Executor is Running.
W0926 17:31:32.863062  4984 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W0926 17:31:32.863062  4984 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.0, Driver API Version: 11.8, Runtime API Version: 11.8
W0926 17:31:32.878702  4984 gpu_resources.cc:149] device: 0, cuDNN Version: 8.6.
I0926 17:31:33.988088  4984 interpreter_util.cc:518] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_selected_gpus', current_value='1', default_value='')
=======================================================================
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_selected_gpus', current_value='0', default_value='')
=======================================================================
I0926 17:31:38.144781  5276 tcp_utils.cc:181] The server starts to listen on IP_ANY:49876
I0926 17:31:38.144781  5276 tcp_utils.cc:130] Successfully connected to 127.0.0.1:49876
I0926 17:31:38.628737  2864 tcp_utils.cc:130] Successfully connected to 127.0.0.1:49876
[2023-09-26 17:31:39,238] [ WARNING] install_check.py:265 - PaddlePaddle meets some problem with 2 GPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
[2023-09-26 17:31:39,238] [ WARNING] install_check.py:275 -
 Original Error is:

----------------------------------------------
Process 1 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\distributed\spawn.py", line 348, in _func_wrapper
    result = func(*args)
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\utils\install_check.py", line 177, in train_for_run_parallel
    paddle.distributed.init_parallel_env()
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\distributed\parallel.py", line 1084, in init_parallel_env
    pg = _new_process_group_impl(
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\distributed\collective.py", line 154, in _new_process_group_impl
    pg = core.ProcessGroupNCCL.create(store, rank, world_size, group_id)
AttributeError: module 'paddle.fluid.libpaddle' has no attribute 'ProcessGroupNCCL'

PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\utils\install_check.py", line 282, in run_check
    raise e
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\utils\install_check.py", line 255, in run_check
    _run_parallel(device_list)
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\utils\install_check.py", line 206, in _run_parallel
    paddle.distributed.spawn(train_for_run_parallel, nprocs=len(device_list))
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\distributed\spawn.py", line 595, in spawn
    while not context.join():
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\distributed\spawn.py", line 399, in join
    self._throw_exception(error_index)
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\distributed\spawn.py", line 423, in _throw_exception
    raise Exception(msg)
Exception:

----------------------------------------------
Process 1 terminated with the following error:
----------------------------------------------

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\distributed\spawn.py", line 348, in _func_wrapper
    result = func(*args)
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\utils\install_check.py", line 177, in train_for_run_parallel
    paddle.distributed.init_parallel_env()
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\distributed\parallel.py", line 1084, in init_parallel_env
    pg = _new_process_group_impl(
  File "C:\ProgramData\anaconda3\envs\padd\lib\site-packages\paddle\distributed\collective.py", line 154, in _new_process_group_impl
    pg = core.ProcessGroupNCCL.create(store, rank, world_size, group_id)
AttributeError: module 'paddle.fluid.libpaddle' has no attribute 'ProcessGroupNCCL'
*/

nvidia-smi
Tue Sep 26 17:44:01 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 522.06       Driver Version: 522.06       CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P40          TCC   | 00000000:04:00.0 Off |                  Off |
| N/A   41C    P8     9W / 250W |      8MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE... TCC   | 00000000:42:00.0 Off |                  Off |
| N/A   63C    P0    29W / 250W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by engineer1109** [comment]
windows不支持多卡。编译的时候 -DWITH_NCCL=OFF
