### ISSUE TITLE
cuda和cudnn，建议版本会报错CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/Paddle#57750]
### bug描述 Describe the Bug

官网写着
CUDA 工具包 11.7 配合 cuDNN v8.4.1，

https://github.com/PaddlePaddle/PaddleGAN/blob/develop/docs/zh_CN/tutorials/nafnet.md

测试报错

paddle2.51 和 2.4 都一样

```
[09/26 14:26:03] ppgan INFO: Found C:\Users\monke\.cache\ppgan\NAFNet_Denoising.pdparams
W0926 14:26:06.026473 14536 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.2, Runtime API Version: 11.7
W0926 14:26:06.052229 14536 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
  0%|                                                                                                                                                                           | 0/1 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "applications/tools/nafnet_denoising.py", line 59, in <module>
    predictor.run(images_path=args.images_path)
  File "E:\2023_ShuJu_WEB\PaddleGAN-develop\ppgan\apps\nafnet_predictor.py", line 142, in run
    output = self.generator(img_L)
  File "E:\anaconda3\envs\PaddleGan\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "E:\2023_ShuJu_WEB\PaddleGAN-develop\ppgan\models\generators\nafnet.py", line 360, in forward
    x = self.intro(inp)
  File "E:\anaconda3\envs\PaddleGan\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "E:\anaconda3\envs\PaddleGan\lib\site-packages\paddle\nn\layer\conv.py", line 712, in forward
    out = F.conv._conv_nd(
  File "E:\anaconda3\envs\PaddleGan\lib\site-packages\paddle\nn\functional\conv.py", line 140, in _conv_nd
    pre_bias = _C_ops.conv2d(
OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.
  [Hint: Please search for the error code(9) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at ../paddle/fluid/platform/device/gpu/cuda/cudnn_desc.h:177)
```

**Comment by engineer1109** [comment]
你这个是release的Bug。
https://github.com/PaddlePaddle/Paddle/issues/50853
这个Bug持续了很长时间，几个月之久。
develop应该是修复的

**Comment by monkeycc** [comment]
develop可以解决
没问题了

是这个问题 @engineer1109

**Comment by monkeycc** [comment]
但是又会产生新的问题

https://github.com/PaddlePaddle/PaddleGAN/blob/develop/docs/zh_CN/tutorials/swinir.md
python applications/tools/swinir_denoising.py --images_path ${PATH_OF_IMAGE}


```

Traceback (most recent call last):
  File "applications/tools/swinir_denoising.py", line 20, in <module>
    from ppgan.apps import SwinIRPredictor
  File "E:\anaconda3\envs\PaddleGan\lib\site-packages\ppgan\apps\__init__.py", line 16, in <module>
    from .deepremaster_predictor import DeepRemasterPredictor
  File "E:\anaconda3\envs\PaddleGan\lib\site-packages\ppgan\apps\deepremaster_predictor.py", line 24, in <module>
    from ppgan.models.generators.remaster import NetworkR, NetworkC
  File "E:\anaconda3\envs\PaddleGan\lib\site-packages\ppgan\models\__init__.py", line 29, in <module>
    from .starganv2_model import StarGANv2Model
  File "E:\anaconda3\envs\PaddleGan\lib\site-packages\ppgan\models\starganv2_model.py", line 5, in <module>
    from paddle.fluid.layers.nn import soft_relu
ModuleNotFoundError: No module named 'paddle.fluid'
```

**Comment by engineer1109** [comment]
paddle.fluid改名为paddle.base

**Comment by Ultraman6** [comment]
怎么解决的啊

**Comment by Ultraman6** [comment]
develop修复是什么意思啊
