### ISSUE TITLE
Error: Can not import paddle core while this file exists: /opt/thingy/data/venv/lib/python3.10/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by baudneo** [PaddlePaddle/Paddle#57873]
### bug描述 Describe the Bug

I installed paddlepaddle-gpu into a venv and then installled paddleocr. Installing paddleOCR completly destroyed my venv, it uninstalled opencv 4.8 and all sorts of other stuff.

I tried running a simple example and am getting this error, There is another error as well:

```
╰─❯ python3
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddleocr
Error: Can not import paddle core while this file exists: /opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 21, in <module>
    import paddle
  File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

Why does paddleOCR depend on an outdated, high risk SSl library? Why Do I need to install libssl 1.1 for an OCR library?

**Comment by baudneo** [comment]
Installing in a brand new venv gives me the same results.

```
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddleocr
Error: Can not import paddle core while this file exists: /root/test/lib/python3.10/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/test/lib/python3.10/site-packages/paddleocr/__init__.py", line 14, in <module>
    from .paddleocr import *
  File "/root/test/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 21, in <module>
    import paddle
  File "/root/test/lib/python3.10/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/root/test/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/root/test/lib/python3.10/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/root/test/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/root/test/lib/python3.10/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/root/test/lib/python3.10/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/root/test/lib/python3.10/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by baudneo** [comment]
paddlepaddle-gpu was used.

**Comment by heavyrain-lzy** [comment]
If you install the `paddlepaddle-gpu` of which version is `develop`,  there is not 'fluid' package any more. But the `paddleOCR` still use the code `from paddle import fluid`. My suggestion is that you can use `paddlepaddle-gpu==2.5.1` or any other version but not `develop` version by the command `python -m pip install paddlepaddle-gpu==2.5.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html` , refering to [PaddlePaddle Quick Start](https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/pip/linux-pip_en.html)

**Comment by baudneo** [comment]
Hi, thanks for the reply. I followed your advice and uninstalled the version of paddlepaddle-gpu i had and reinstalled 2.5.1.

Now I get a different error:

```
  Traceback (most recent call last):
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
      result = await app(  # type: ignore[func-returns-value]
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
      return await self.app(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
      await super().__call__(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
      await self.middleware_stack(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
      raise exc
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
      await self.app(scope, receive, _send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
      raise exc
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
      await self.app(scope, receive, sender)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
      raise e
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
      await self.app(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
      await route.handle(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
      await self.app(scope, receive, send)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
      response = await func(request)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
      raw_response = await run_endpoint_function(
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
      return await dependant.call(**values)
    File "/opt/zm_ml/src/zm_ml/Server/app.py", line 445, in get_annotated_image
      detections, images = await detect(hints_, [image], return_image=True)
    File "/opt/zm_ml/src/zm_ml/Server/app.py", line 311, in detect
      img_dets.append(await detector.detect(image))
    File "/opt/zm_ml/src/zm_ml/Server/Models/config.py", line 1448, in detect
      return await self.model.detect(images)
    File "/opt/zm_ml/src/zm_ml/Server/ML/Detectors/onnx_runtime.py", line 176, in detect
      ocr_results = self.ocr(cropped_image)
    File "/opt/zm_ml/src/zm_ml/Server/ML/Detectors/ocr.py", line 119, in ocr
      result = self.ocr_reader.ocr(transformed_img)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 661, in ocr
      dt_boxes, rec_res, _ = self.__call__(img, cls)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddleocr/tools/infer/predict_system.py", line 76, in __call__
      dt_boxes, elapse = self.text_detector(img)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddleocr/tools/infer/predict_det.py", line 273, in __call__
      post_result = self.postprocess_op(preds, shape_list)
    File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddleocr/ppocr/postprocess/db_postprocess.py", line 224, in __call__
      pred = pred[:, 0, :, :]
  IndexError: too many indices for array: array is 2-dimensional, but 4 were indexed
```

**Comment by heavyrain-lzy** [comment]
Please give the more detail information or code indicating how to reproduct the bug.

**Comment by baudneo** [comment]
# How I installed paddleocr

1. create a new venv
2. activate venv
3. install paddlepaddle-gpu==2.5.1
4. install paddleocr
5. write test code (see following code block)
6. run test program in venv
7. get errors
```
 1822  python3 -m venv ./paddle_venv
 1823  source paddle_venv/bin/activate
 1824  python3 -m pip install paddlepaddle-gpu==2.5.1
 1825  python3 -m pip install paddleocr
 1826 <REDACTED - Unrelated to this>
 1827  nano ~/test.py
 1828  chmod +x ~/test.py
 1829  ~/test.py
```


# Error
```
╰─❯ ~/test.py
[2023/10/06 21:41:57] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=True, use_xpu=False, use_npu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='/tmp/paddle/models', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='/tmp/paddle/models', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='/root/paddle_venv/lib/python3.10/site-packages/paddleocr/ppocr/utils/en_dict.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=True, cls_model_dir='/tmp/paddle/models', cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir=None, merge_no_span_structure=True, table_char_dict_path=None, layout_model_dir=None, layout_dict_path=None, layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, ocr=True, recovery=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='en', det=True, rec=True, type='ocr', ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
Reader instantiated in 4.80602 seconds
[2023/10/06 21:42:03] ppocr DEBUG: dt_boxes num : 1, elapsed : 0.9135284423828125
Traceback (most recent call last):
  File "/root/test.py", line 27, in <module>
    result = ocr_reader.ocr(image)
  File "/root/paddle_venv/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 661, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "/root/paddle_venv/lib/python3.10/site-packages/paddleocr/tools/infer/predict_system.py", line 99, in __call__
    img_crop_list, angle_list, elapse = self.text_classifier(
  File "/root/paddle_venv/lib/python3.10/site-packages/paddleocr/tools/infer/predict_cls.py", line 111, in __call__
    self.predictor.run()
ValueError: In user code:

    File "tools/export_model.py", line 187, in <module>
      main()
    File "tools/export_model.py", line 179, in main
      sub_model_save_path, logger)
    File "tools/export_model.py", line 106, in export_single_model
      paddle.jit.save(model, save_path)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 629, in wrapper
      func(layer, path, input_spec, **configs)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 857, in save
      inner_input_spec, with_hook=with_hook)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
      *desired_input_spec, with_hook=with_hook)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
      **cache_key.kwargs)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpnwredzuu.py", line 30, in forward
      false_fn_1, (x,), (x,), (x,))
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
      out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/architectures/base_model.py", line 82, in forward
      x = self.neck(x)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/paddle/debug/PaddleOCR/ppocr/modeling/necks/db_fpn.py", line 247, in forward
      in5, scale_factor=2, mode="nearest", align_mode=1)  # 1/16
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 347, in __impl__
      attrs={'axis': axis})
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/root/anaconda3/envs/fgd/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 96, 3, 12] and the shape of Y = [1, 96, 4, 12]. Received [3] in X is not equal to [4] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ../paddle/phi/kernels/funcs/common_shape.h:86)
      [operator < elementwise_add > error]
```

# Reproducible error code
```
#! /root/paddle_venv/bin/python3
import time
from paddleocr import PaddleOCR
import cv2

s = time.perf_counter()

ocr_reader = PaddleOCR(
    use_angle_cls=True,
    lang="en",
    det_model_dir=str(
        "/tmp/paddle/models"
    ),
    rec_model_dir=str(
        "/tmp/paddle/models"
    ),
    cls_model_dir=str(
        "/tmp/paddle/models"
    ),
)
print(
    f"Reader instantiated in {time.perf_counter() - s:.5f} seconds"
)

image = cv2.imread("/shared/test/imgGray.jpg")

result = ocr_reader.ocr(image)

print(f"result from paddleOCR: {result}")


```

**Comment by heavyrain-lzy** [comment]
The  issue has been already reproducted using the code in the `test.py`. The reason is that it is not allowed that `det_model_dir `, `rec_model_dir ` and `cls_model_dir ` are the same. In order to solve the problem, you should give them different values, such as:
```
#! /root/paddle_venv/bin/python3
import time
from paddleocr import PaddleOCR
import cv2

s = time.perf_counter()

ocr_reader = PaddleOCR(
    use_angle_cls=True,
    lang="en",
    det_model_dir=str(
        "/tmp/paddle/det_models"
    ),
    rec_model_dir=str(
        "/tmp/paddle/rec_models"
    ),
    cls_model_dir=str(
        "/tmp/paddle/cls_models"
    ),
)
print(
    f"Reader instantiated in {time.perf_counter() - s:.5f} seconds"
)

image = cv2.imread("/shared/test/imgGray.jpg")

result = ocr_reader.ocr(image)

print(f"result from paddleOCR: {result}")


```

**Comment by hhxdestiny** [comment]
> ### bug 描述 描述 Bug
> 我将 paddlepaddle-gpu 安装到 venv 中，然后安装了 paddleocr。安装 paddleOCR 完全破坏了我的 venv，它卸载了 opencv 4.8 和各种其他东西。
> 
> 我尝试运行一个简单的示例并收到此错误，还有另一个错误：
> 
> ```
> ╰─❯ python3
> Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import paddleocr
> Error: Can not import paddle core while this file exists: /opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/fluid/libpaddle.so
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddleocr/__init__.py", line 14, in <module>
>     from .paddleocr import *
>   File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddleocr/paddleocr.py", line 21, in <module>
>     import paddle
>   File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/__init__.py", line 31, in <module>
>     from .framework import monkey_patch_variable
>   File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
>     from . import random  # noqa: F401
>   File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/framework/random.py", line 17, in <module>
>     from paddle import fluid
>   File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 36, in <module>
>     from . import framework
>   File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/fluid/framework.py", line 35, in <module>
>     from . import core
>   File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/fluid/core.py", line 356, in <module>
>     raise e
>   File "/opt/zm_ml/data/venv/lib/python3.10/site-packages/paddle/fluid/core.py", line 269, in <module>
>     from . import libpaddle
> ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
> ```
> 
> 为什么 paddleOCR 依赖于过时的、高风险的 SSl 库？为什么 OCR 库需要安装 libssl 1.1？
> 
> ### 其他补充信息 附加补充信息
> _没有反应_

When I use pip to install paddlepaddle-gpu in conda env, your problem will be replicated, but when I use conda to install paddlepaddle-gpu in conda env, it can work normally. Perhaps venv does not have the ability to manage dynamic libraries using pip, so libpaddle.so cannot find libssl. so.1.1.1 and libcrypto. so.1.1.1

**Comment by heavyrain-lzy** [comment]
If the errors mentioned in the issue have been solved or  still exist, please leave a comment.

**Comment by baudneo** [comment]
> If the errors mentioned in the issue have been solved or still exist, please leave a comment.

Hi sorry it's thanksgiving weekend here in Canada so I hadn't had time to check. I just checked and your solution solves the problem. Thank you for your help!

**Comment by heavyrain-lzy** [comment]
> > If the errors mentioned in the issue have been solved or still exist, please leave a comment.
> 
> Hi sorry it's thanksgiving weekend here in Canada so I hadn't had time to check. I just checked and your solution solves the problem. Thank you for your help!

Happy thanksgiving weekend!
