### ISSUE TITLE
安装后出现ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yuenoble** [PaddlePaddle/Paddle#58119]
### 问题描述 Issue Description

环境：
python3.10.0

安装CPU版本
pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple

启动 import paddle 报错：

```python
>>> import paddle
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/lib/python3.10/dist-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

### 版本&环境信息 Version & Environment Information

python3.10.0

CPU版本

安装命令
```python
pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
```

**Comment by yuenoble** [comment]
补充，openssl 版本

```bash
openssl version
OpenSSL 1.1.1t  7 Feb 2023
```

**Comment by wencan** [comment]
openssl 1.1 怎么安装的？
试试sudo ldconfig -v

**Comment by zhoutianzi666** [comment]
看看自己的机器上是否有这个 文件呢？
<img width="890" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/39978853/cdd587ce-f5d0-44f8-9f00-b93cad631809">
我的机器上是有的哦
