### ISSUE TITLE
[grad bugs] GRU和LSTM grad 时: Required tensor shall not be nullptr, but received nullptr

### ISSUE THREAD

**Issue by DrownFish19** [PaddlePaddle/Paddle#58158]
### bug描述 Describe the Bug

复现代码
```python
import paddle 
from paddle import nn

class FUNC(nn.Layer):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(2, 128)
        self.linear2 = nn.Linear(128, 2)

        self.rnn = paddle.nn.LSTM(2, 128, 2, time_major=False)

    def forward(self, t, y0, lags, y_lags):
        h = self.linear1(y0**3)  # [B, D] => [B, D]
        h_lags = paddle.mean(self.rnn(y_lags)[0], axis=-2)  # [B, T, D] => [B, D]
        re = self.linear2(h + h_lags)  # [10, 128]
        return re
    

t, y0, lags, y_lags = paddle.rand([1]), paddle.rand([10, 2]), paddle.rand([5]), paddle.rand([10, 5, 2])
y_lags.stop_gradient = False

func = FUNC()

eval = func(t, y0, lags, y_lags)
paddle.grad(
    outputs=[eval],
    inputs=[y_lags],
    allow_unused=True,
    retain_graph=True,
)[0]
```
error日志
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/drownfish19/anaconda3/envs/paddle-2.5.1/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/Users/drownfish19/anaconda3/envs/paddle-2.5.1/lib/python3.10/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/Users/drownfish19/anaconda3/envs/paddle-2.5.1/lib/python3.10/site-packages/paddle/fluid/framework.py", line 462, in __impl__
    return func(*args, **kwargs)
  File "/Users/drownfish19/anaconda3/envs/paddle-2.5.1/lib/python3.10/site-packages/paddle/fluid/dygraph/base.py", line 814, in grad
    return core.eager.run_partial_grad(
ValueError: (InvalidArgument) Required tensor shall not be nullptr, but received nullptr.
  [Hint: tensor should not be null.] (at /Users/paddle/xly/workspace/dee476bb-8870-4675-a114-a40f0e20581f/Paddle/paddle/phi/core/device_context.cc:142)
```

**Comment by ming1753** [comment]
您好，感谢您的反馈，API负责人正在跟进中。
