### ISSUE TITLE
paddle安装包对int8模型量化的支持

### ISSUE THREAD

**Issue by Sophia-stargithub** [PaddlePaddle/Paddle#58267]
### 需求描述 Feature Description

是只有paddle2.4以上支持int8模型量化吗，在arm-cpu上编译得到的paddle2.3.1安装包没有enable_mkldnn_int8功能

**Comment by Sophia-stargithub** [comment]
E1020 12:49:29.119931 2777066 analysis_config.cc:579] Please compile with MKLDNN first to use MKLDNN
Traceback (most recent call last):
  File "/u01/liuhongyu/code/air_relation/main_sever.py", line 5, in <module>
    from relation_extract import extract
  File "/u01/liuhongyu/code/air_relation/relation_extract.py", line 12, in <module>
    my_ie = UIEPredictor(model="uie-base", schema=schema, task_path='./uie_model_utc_v5', precision="int8") # , predictor_type="onnx_runtime"
  File "/u01/liuhongyu/code/air_relation/uie_infer.py", line 28, in __init__
    self.get_inference_model()
  File "/u01/liuhongyu/code/air_relation/uie_infer.py", line 37, in get_inference_model
    self.prepare_static_mode()
  File "/u01/liuhongyu/code/air_relation/uie_infer.py", line 51, in prepare_static_mode
    self.config.enable_mkldnn_int8()
AttributeError: 'paddle.fluid.libpaddle.AnalysisConfig' object has no attribute 'enable_mkldnn_int8'


arm版本cpu，鲲鹏920，编译得到paddle2.4.1安装包，cpu运行时候做的int8模型量化报错，这个怎么解决呢

**Comment by vivienfanghuagood** [comment]
请问用的cmake编译选项是什么呢？

**Comment by Sophia-stargithub** [comment]
> 请问用的cmake编译选项是什么呢？

cmake .. \
-D PY_VERSION=3 \
-D PYTHON_EXECUTABLE=`which python3` \
-D WITH_ARM=ON \
-D WITH_TESTING=OFF \
-D CMAKE_BUILD_TYPE=Release \
-D ON_INFER=ON \
-D WITH_XBYAK=OFF \
-D CMAKE_CXX_FLAGS="-Wno-error -w" \
-D WITH_GPU=OFF \
-D WITH_NCCL=OFF \
-D WITH_RCCL=OFF \
-D WITH_AVX=OFF

**Comment by Sophia-stargithub** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/111474220/f104e3eb-9d96-4981-a7a4-f381c729d9dd)

**Comment by vivienfanghuagood** [comment]
> > 请问用的cmake编译选项是什么呢？
> 
> cmake .. -D PY_VERSION=3 -D PYTHON_EXECUTABLE=`which python3` -D WITH_ARM=ON -D WITH_TESTING=OFF -D CMAKE_BUILD_TYPE=Release -D ON_INFER=ON -D WITH_XBYAK=OFF -D CMAKE_CXX_FLAGS="-Wno-error -w" -D WITH_GPU=OFF -D WITH_NCCL=OFF -D WITH_RCCL=OFF -D WITH_AVX=OFF

加上-DWITH_MKL=ON -DWITH_AVX=ON试试呢

**Comment by Sophia-stargithub** [comment]
> > > 请问用的cmake编译选项是什么呢？
> > 
> > 
> > cmake .. -D PY_VERSION=3 -D PYTHON_EXECUTABLE=`which python3` -D WITH_ARM=ON -D WITH_TESTING=OFF -D CMAKE_BUILD_TYPE=Release -D ON_INFER=ON -D WITH_XBYAK=OFF -D CMAKE_CXX_FLAGS="-Wno-error -w" -D WITH_GPU=OFF -D WITH_NCCL=OFF -D WITH_RCCL=OFF -D WITH_AVX=OFF
> 
> 加上-DWITH_MKL=ON -DWITH_AVX=ON试试呢

cmake时候显示警告，avx指令，mkldnn不可用；arm-cpu是不支持mkldnn使用的吧，所以编译不成功？
