### ISSUE TITLE
一些算子在模型训练中的反向传播过程无法复现

### ISSUE THREAD

**Issue by Rruown** [PaddlePaddle/Paddle#58779]
【版本】
paddlepaddle-gpu    2.5.2.post117

【问题】
我在使用PaddleSeg release2.8 的deeplabv3模型的训练过程中，发现一些pool2d算子的反向过程无法单独复现，但是有些可以复现，
我执行的训练脚本如下：
```
#!/bin/bash

export CUDA_VISIBLE_DEVICES=0

python tools/train.py \
    --config configs/deeplabv3p/deeplabv3p_resnet50_os8_cityscapes_1024x512_80k.yml \
    --device gpu \
    --iters=200 \
    --num_workers 8 \
    --log_iters 1 \
    --seed 22 \
    --use_vdl \
    --amp_level O1 \
    --precision fp16
```

ppseg修改：抓取pool2d第二次调用（第一次调用可以对齐）的前反向数据
在模型训练前将pool2d替换为ReplacePoo2d
```
idx = 0

class ReplacePool2d:
    def __init__(self, func) -> None:
        self._func = func

    def __call__(self, *args: Any, **kwds: Any) -> Any:
        global idx
        if idx == 1:
            paddle.save(args, "pool2d.input")
            args[0].register_hook(lambda grad: paddle.save(grad, "pool2d.gradout"))

        out = self._func(*args, **kwds)

        if idx == 1:
            paddle.save(out, "pool2d.output")
            out.register_hook(lambda grad: paddle.save(grad, "pool2d.gradin"))

        idx += 1

        return out


pool2d = ReplacePool2d(paddle._C_ops.pool2d)
    

paddle._C_ops.pool2d = pool2d
```

我的复现脚本如下：
```
import paddle
import numpy as np


input = list(paddle.load("pool2d.input"))
output = paddle.load("pool2d.output")


grad_input = paddle.load("pool2d.gradin")
grad_output = paddle.load("pool2d.gradout")

x = input[0]

x.stop_gradient = False

input[0] = x

print("input:\n", x)

with paddle.amp.auto_cast():
    res = paddle._C_ops.pool2d(*input)

np.testing.assert_allclose(res.numpy(), output.numpy())

paddle.autograd.backward([res], [grad_input])

np.testing.assert_allclose(grad_output.numpy(), x.grad.numpy())
```

复现结果：
```
input:
 Tensor(shape=[2, 256, 128, 256], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [[[[0.08898926, 0.09606934, 0.12841797, ..., 0.07189941,
           0.08270264, 0.08081055],
          [0.19799805, 0.35986328, 0.23352051, ..., 0.20886230,
           0.35327148, 0.23950195],
          [0.12432861, 0.29736328, 0.24551392, ..., 0.27075195,
           0.34448242, 0.14123535],
          ...,
          [0.34338379, 0.07234192, 0.15917969, ..., 0.29333496,
           0.56527710, 0.97024536],
          [1.23263550, 0.76251221, 0.79092407, ..., 0.70764160,
           0.30116272, 0.58740234],
          [0.03967285, 0.06286621, 0.06842041, ..., 0.01340485,
           0.01972961, 0.07128906]],

         [[0.38430023, 0.32293701, 0.29077530, ..., 0.09545898,
           0.10703659, 0.52838135],
          [0.30532074, 0.38359070, 0.48766136, ..., 0.40299988,
           0.50015259, 0.63407898],
          [0.10212708, 0.29876709, 0.41861725, ..., 0.49089432,
           0.54346466, 0.56965637],
          ...,
          [0.02996826, 0.02426147, 0.02132416, ..., 0.20308685,
           0.31541443, 0.47804832],
          [0.02290344, 0.03052521, 0.02709961, ..., 0.18470764,
           0.41485596, 0.52857208],
          [0.02381516, 0.13063049, 0.02696991, ..., 0.45545959,
           0.36685944, 0.54072571]],

         [[1.43908691, 0.99542236, 0.94097900, ..., 0.78979492,
           0.42854309, 0.14416504],
          [0.95098877, 0.        , 0.19262695, ..., 0.01831055,
           0.03399658, 0.17834473],
          [0.78912354, 0.05004883, 0.04742432, ..., 0.26245117,
           0.35595703, 0.14416504],
          ...,
          [0.23846436, 0.16687012, 0.36865234, ..., 0.20800781,
           0.21960449, 0.52435303],
          [0.55498505, 0.32373047, 0.26293945, ..., 0.35058594,
           0.12432861, 0.37408447],
          [0.83465576, 0.37023926, 0.43676758, ..., 0.00150776,
           0.11959839, 0.13592529]],

         ...,

         [[0.01675081, 0.02505493, 0.02637482, ..., 0.24826956,
           0.40795511, 0.01683807],
          [0.01905441, 0.01676059, 0.11755753, ..., 0.35220766,
           0.48985291, 0.01483774],
          [0.01795578, 0.29688835, 0.25222421, ..., 0.37034607,
           0.28289223, 0.01787186],
          ...,
          [0.01844406, 0.00678253, 0.20537567, ..., 0.39097500,
           0.30363941, 0.25812149],
          [0.30095673, 0.19508362, 0.18073654, ..., 0.76029396,
           0.54669952, 0.67733622],
          [0.02639771, 0.47508240, 0.47248769, ..., 0.64205170,
           0.61753845, 0.79418445]],

         [[0.07101250, 0.30220413, 0.09014416, ..., 0.41696477,
           0.54284668, 0.42120361],
          [0.56979179, 0.33437729, 0.07987976, ..., 0.32292938,
           0.61436081, 0.08357573],
          [0.28501511, 0.28502274, 0.16113281, ..., 0.32774734,
           0.42129326, 0.39950180],
          ...,
          [0.41929626, 0.19755554, 0.22217560, ..., 0.44442940,
           0.30990028, 0.32714844],
          [0.18845367, 0.00152206, 0.09182739, ..., 0.35153580,
           0.49765205, 0.52344131],
          [0.01657104, 0.01187229, 0.51293564, ..., 0.60832977,
           0.81758118, 0.83338165]],

         [[0.        , 0.12097168, 0.03515625, ..., 0.        ,
           0.        , 0.        ],
          [0.        , 0.        , 0.        , ..., 0.        ,
           0.        , 0.        ],
          [0.        , 0.05823135, 0.        , ..., 0.06091309,
           1.15203857, 0.56875610],
          ...,
          [0.11004639, 0.        , 0.        , ..., 0.        ,
           0.01268768, 0.        ],
          [0.        , 0.        , 0.        , ..., 0.        ,
           0.        , 0.        ],
          [0.67605591, 0.03990936, 0.06768799, ..., 0.21051025,
           0.00094223, 0.48999023]]],


        [[[0.11541748, 0.02839661, 0.12927246, ..., 0.25463867,
           0.08007812, 0.08728027],
          [0.24072266, 0.11267090, 0.24780273, ..., 0.29217529,
           0.20654297, 0.17529297],
          [0.24319077, 0.19738770, 0.18005371, ..., 0.28240204,
           0.16846728, 0.05007935],
          ...,
          [0.41991138, 0.05651855, 0.36729431, ..., 0.22436523,
           0.56052780, 0.13122559],
          [0.42102051, 0.33445740, 0.23107910, ..., 0.35947418,
           0.64483643, 0.45968628],
          [0.12658691, 0.11352539, 0.12127686, ..., 0.10015869,
           0.05108643, 0.06634521]],

         [[0.02907562, 0.09383392, 0.06273651, ..., 0.02375031,
           0.02377510, 0.13999176],
          [0.16343307, 0.37560654, 0.15715027, ..., 0.15024376,
           0.32582855, 0.07968140],
          [0.12987947, 0.36473846, 0.36560822, ..., 0.11118317,
           0.14895630, 0.05210876],
          ...,
          [0.15925217, 0.09266281, 0.16097260, ..., 0.23437500,
           0.34320068, 0.41931915],
          [0.28970718, 0.28896952, 0.19286728, ..., 0.27574921,
           0.26698685, 0.53138733],
          [0.20357513, 0.18938446, 0.20951843, ..., 0.42420959,
           0.33816147, 0.45552063]],

         [[1.05560303, 0.67456055, 0.77018738, ..., 0.41168213,
           0.77124023, 0.82553101],
          [0.75390625, 0.27807617, 0.18933105, ..., 0.23339844,
           0.18969727, 0.46362305],
          [0.75402832, 0.32373047, 0.33447266, ..., 0.39286804,
           0.08105469, 0.22926331],
          ...,
          [0.26257324, 0.36425781, 0.36621094, ..., 0.35522461,
           0.27465820, 0.03585815],
          [0.24584961, 0.21545410, 0.15612793, ..., 0.31298828,
           0.28857422, 0.61003876],
          [0.15405273, 0.20208740, 0.31860352, ..., 1.04064941,
           0.28662109, 0.71380615]],

         ...,

         [[0.02229929, 0.07486212, 0.02018070, ..., 0.65809870,
           0.02221966, 0.01760483],
          [0.01428461, 0.13304901, 0.02500343, ..., 0.33998299,
           0.01057243, 0.01888275],
          [0.02757645, 0.02085924, 0.03724837, ..., 0.02175903,
           0.02073860, 0.95300674],
          ...,
          [0.47938538, 0.53771114, 0.89241624, ..., 0.02475977,
           0.53324032, 0.06722832],
          [0.01147652, 0.59294128, 0.52914906, ..., 0.12415695,
           0.02232265, 0.11541224],
          [0.01816559, 0.34815598, 0.86971664, ..., 0.23517609,
           0.20973015, 0.52478600]],

         [[0.22545815, 0.15645647, 0.03432977, ..., 0.08294487,
           0.21361542, 0.14452362],
          [0.44244003, 0.01970673, 0.01432419, ..., 0.02034760,
           0.02137756, 0.01571655],
          [0.24477386, 0.01673889, 0.01446915, ..., 0.23887253,
           0.01572037, 0.01570892],
          ...,
          [0.02579498, 0.15186155, 0.04396915, ..., 0.01226425,
           0.00952911, 0.01412201],
          [0.01734161, 0.12009430, 0.02343750, ..., 0.00897264,
           0.01575851, 0.01631165],
          [0.29176521, 0.13361740, 0.01951599, ..., 0.26070499,
           0.01882935, 0.47815132]],

         [[0.46753693, 0.07305908, 0.        , ..., 0.        ,
           0.75393677, 0.87959290],
          [0.        , 0.        , 0.46078491, ..., 0.        ,
           0.        , 0.        ],
          [0.        , 0.07806396, 0.21660995, ..., 0.        ,
           0.        , 0.        ],
          ...,
          [0.34387207, 0.        , 0.        , ..., 0.29866028,
           1.12899780, 0.67965698],
          [0.24145508, 0.        , 0.        , ..., 0.        ,
           0.        , 0.17083740],
          [0.69793701, 0.66683960, 0.        , ..., 0.37088013,
           0.        , 0.        ]]]])
W1108 18:52:41.164932 2472009 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.7, Runtime API Version: 11.7
W1108 18:52:41.168845 2472009 gpu_resources.cc:149] device: 0, cuDNN Version: 8.7.
Traceback (most recent call last):
  File "recover.py", line 27, in <module>
    np.testing.assert_allclose(grad_output.numpy(), x.grad.numpy())
  File "/data02/application/huangzhen/miniconda3/envs/ppseg_gpu/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1592, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/data02/application/huangzhen/miniconda3/envs/ppseg_gpu/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/data02/application/huangzhen/miniconda3/envs/ppseg_gpu/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 862, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 16776763 / 16777216 (100%)
Max absolute difference: 26.459274
Max relative difference: 14087899.
 x: array([[[[-4.323730e+00, -3.544006e+00,  5.747131e+00, ...,
           1.198151e+00, -3.469055e+00, -2.270355e+00],
         [-5.700684e-02, -1.141357e-01,  5.043274e+00, ...,...
 y: array([[[[-1.53418 , -1.53418 ,  3.699219, ...,  0.375   , -1.828125,
          -1.828125],
         [-1.53418 , -1.53418 ,  3.699219, ...,  0.375   , -1.828125,...
```

可以看到前向能对上结果，但是反向结果对不上

【预期结果】

预期抓取模型中算子的前方向数据应能正确复现

**Comment by Rruown** [comment]
类似的算子不只pool2d，其他算子也有这种情况。有些数据能对齐，有些数据无法对齐，复现和dump数据都是一样的

**Comment by xuxinyi389** [comment]
input = list(paddle.load("pool2d.input")),input的实际输入是什么并未提供，直接调用C++API存在部分参数未指定的风险，建议调用python层提供的API。

**Comment by Rruown** [comment]
> input = list(paddle.load("pool2d.input")),input的实际输入是什么并未提供，直接调用C++API存在部分参数未指定的风险，建议调用python层提供的API。

input就是模型训练过程中实际传给paddle._C_ops.pool2d的数据，通过paddle.save保存的。部分参数未指定是指paddle.save丢失一些参数？或者是执行paddle._C_ops.pool2d前会设置一些tensor的参数或属性（无法被paddle.save保存）？

**Comment by xuxinyi389** [comment]
之前python调用的python层API是什么

**Comment by Rruown** [comment]
> 之前python调用的python层API是什么

paddle.nn.layer.AvgPool2D -> paddle.nn.functional.avg_pool2d

**Comment by Rruown** [comment]
是因为累计梯度
