### ISSUE TITLE
ImportError: cannot import name 'SemLock' from '_multiprocessing' 

### ISSUE THREAD

**Issue by anmingyu11** [PaddlePaddle/Paddle#58802]
### bug描述 Describe the Bug

```
Traceback (most recent call last):
  File "/home/disk3/amy/pyenv/py37/lib/python3.7/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/home/disk3/amy/pyenv/py37/lib/python3.7/lib-dynload/_multiprocessing.cpython-37m-x86_64-linux-gnu.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/disk3/amy/author_redpoint_rank_model/model/trainer.py", line 383, in <module>
    main(args)
  File "/home/disk3/amy/author_redpoint_rank_model/model/trainer.py", line 290, in main
    assert any(train_dataloader(
  File "/home/disk3/amy/pyenv/py37/lib/python3.7/site-packages/paddle/fluid/reader.py", line 570, in __call__
    return self.__iter__()
  File "/home/disk3/amy/pyenv/py37/lib/python3.7/site-packages/paddle/fluid/reader.py", line 567, in __iter__
    return _DataLoaderIterMultiProcess(self)
  File "/home/disk3/amy/pyenv/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 380, in __init__
    self._init_workers()
  File "/home/disk3/amy/pyenv/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 395, in _init_workers
    self._data_queue = multiprocessing.Queue()
  File "/home/disk3/amy/pyenv/py37/lib/python3.7/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/home/disk3/amy/pyenv/py37/lib/python3.7/multiprocessing/queues.py", line 39, in __init__
    from .synchronize import SEM_VALUE_MAX as maxsize
  File "/home/disk3/amy/pyenv/py37/lib/python3.7/multiprocessing/synchronize.py", line 32, in <module>
    " synchronization primitives needed will not" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f761996f710>
Traceback (most recent call last):
  File "/home/disk3/amy/pyenv/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 715, in __del__
    self._try_shutdown_all()
  File "/home/disk3/amy/pyenv/py37/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 505, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
```

原来是3.10，降级到了3.7，一直报这个问题，请问如何解决。读数据的时候出的问题

**Comment by heavengate** [comment]
这个是multiprocessing库的问题哈，DataLoader用到了这个库，可能需要重新安装下muliprocessing库，或者不要用num_workers>0的多进程模式
