### ISSUE TITLE
H100无法训练

### ISSUE THREAD

**Issue by m00nLi** [PaddlePaddle/Paddle#58971]
### bug描述 Describe the Bug

H100无法训练

- os: Ubuntu 22.04
- 显卡： 8*H100
- python: 3.10.13
- Paddle: 2.5.2cu12.0, 2.5.2cu11.7
- PaddleDetection: 2.6.0, 2.7.0

安装完Paddle后测试：
```python
import paddle
print(paddle.utils.run_check())
```
打印输出：
```
Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 GPU.
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_selected_gpus', current_value='0', default_value='')
...
=======================================================================
I1114 10:24:14.534329 1683878 tcp_utils.cc:130] Successfully connected to 127.0.0.1:38551
W1114 10:24:16.243904 1683876 gpu_resources.cc:106] The GPU compute capability in your current machine is 90, which is not supported by Paddle, it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1114 10:24:16.243937 1683876 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 9.0, Driver API Version: 12.2, Runtime API Version: 11.7
W1114 10:24:16.244544 1683876 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
W1114 10:24:16.274400 1683881 gpu_resources.cc:106] The GPU compute capability in your current machine is 90, which is not supported by Paddle, it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1114 10:24:16.274425 1683881 gpu_resources.cc:119] Please NOTE: device: 5, GPU Compute Capability: 9.0, Driver API Version: 12.2, Runtime API Version: 11.7
W1114 10:24:16.274659 1683883 gpu_resources.cc:106] The GPU compute capability in your current machine is 90, which is not supported by Paddle, it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1114 10:24:16.274677 1683883 gpu_resources.cc:119] Please NOTE: device: 7, GPU Compute Capability: 9.0, Driver API Version: 12.2, Runtime API Version: 11.7
W1114 10:24:16.274950 1683881 gpu_resources.cc:149] device: 5, cuDNN Version: 8.9.
W1114 10:24:16.274963 1683878 gpu_resources.cc:106] The GPU compute capability in your current machine is 90, which is not supported by Paddle, it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1114 10:24:16.274983 1683878 gpu_resources.cc:119] Please NOTE: device: 2, GPU Compute Capability: 9.0, Driver API Version: 12.2, Runtime API Version: 11.7
W1114 10:24:16.274989 1683880 gpu_resources.cc:106] The GPU compute capability in your current machine is 90, which is not supported by Paddle, it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1114 10:24:16.275009 1683880 gpu_resources.cc:119] Please NOTE: device: 4, GPU Compute Capability: 9.0, Driver API Version: 12.2, Runtime API Version: 11.7
W1114 10:24:16.275040 1683879 gpu_resources.cc:106] The GPU compute capability in your current machine is 90, which is not supported by Paddle, it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1114 10:24:16.275061 1683879 gpu_resources.cc:119] Please NOTE: device: 3, GPU Compute Capability: 9.0, Driver API Version: 12.2, Runtime API Version: 11.7
W1114 10:24:16.275138 1683883 gpu_resources.cc:149] device: 7, cuDNN Version: 8.9.
W1114 10:24:16.275322 1683882 gpu_resources.cc:106] The GPU compute capability in your current machine is 90, which is not supported by Paddle, it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1114 10:24:16.275342 1683882 gpu_resources.cc:119] Please NOTE: device: 6, GPU Compute Capability: 9.0, Driver API Version: 12.2, Runtime API Version: 11.7
W1114 10:24:16.275445 1683878 gpu_resources.cc:149] device: 2, cuDNN Version: 8.9.
W1114 10:24:16.275472 1683880 gpu_resources.cc:149] device: 4, cuDNN Version: 8.9.
W1114 10:24:16.275645 1683879 gpu_resources.cc:149] device: 3, cuDNN Version: 8.9.
W1114 10:24:16.275943 1683882 gpu_resources.cc:149] device: 6, cuDNN Version: 8.9.
W1114 10:24:16.287230 1683877 gpu_resources.cc:106] The GPU compute capability in your current machine is 90, which is not supported by Paddle, it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W1114 10:24:16.287266 1683877 gpu_resources.cc:119] Please NOTE: device: 1, GPU Compute Capability: 9.0, Driver API Version: 12.2, Runtime API Version: 11.7
W1114 10:24:16.288363 1683877 gpu_resources.cc:149] device: 1, cuDNN Version: 8.9.
I1114 10:24:35.611016 1684020 tcp_store.cc:273] receive shutdown event and so quit from MasterDaemon run loop
PaddlePaddle works well on 8 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
None
```
看输出提示不支持H100的sm_90, `The GPU compute capability in your current machine is 90, which is not supported by Paddle`,但最后又说`PaddlePaddle works well on 8 GPUs.`, `installed successfully`

测试训练PP-YOLOE-Plus，报错：
```
loading annotations into memory...
Done (t=1.26s)
creating index...
index created!
Traceback (most recent call last):
  File "/path/PaddleDetection/tools/train.py", line 202, in <module>
    main()
  File "/path/PaddleDetection/tools/train.py", line 198, in main
    run(FLAGS, cfg)
  File "/path/PaddleDetection/tools/train.py", line 151, in run
    trainer.train(FLAGS.eval)
  File "/path/PaddleDetection/ppdet/engine/trainer.py", line 601, in train
    self._eval_with_loader(self._eval_loader)
  File "/path/PaddleDetection/ppdet/engine/trainer.py", line 632, in _eval_with_loader
    outs = self.model(data)
  File "/home/user/miniconda3/envs/paddle2.5/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/path/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 76, in forward
    outs.append(self.get_pred())
  File "/path/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 150, in get_pred
    return self._forward()
  File "/path/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 126, in _forward
    bbox, bbox_num, nms_keep_idx = self.yolo_head.post_process(
  File "/path/PaddleDetection/ppdet/modeling/heads/ppyoloe_head.py", line 533, in post_process
    bbox_pred, bbox_num, nms_keep_idx = self.nms(pred_bboxes,
  File "/path/PaddleDetection/ppdet/modeling/layers.py", line 564, in __call__
    return ops.multiclass_nms(bboxes, score, **kwargs)
  File "/path/PaddleDetection/ppdet/modeling/ops.py", line 591, in multiclass_nms
    output, index, nms_rois_num = C_ops.multiclass_nms3(bboxes, scores,
OSError: (External) CUDA error(209), no kernel image is available for execution on the device.
  [Hint: 'cudaErrorNoKernelImageForDevice'. This indicates that there is no kernel image available that is suitable for the device. This can occur when a user specifiescode generation options for a particular CUDA source file that do not include the corresponding device configuration.] (at ../paddle/phi/kernels/gpu/multiclass_nms3_kernel.cu:606)
  [operator < multiclass_nms3 > error]
I1114 10:01:51.750474 1661847 tcp_store.cc:273] receive shutdown event and so quit from MasterDaemon run loop
LAUNCH INFO 2023-11-14 10:01:54,109 Exit code 1
[2023-11-14 10:01:54,109] [    INFO] controller.py:149 - Exit code 1

```

**Comment by intersoulest** [comment]
h800同样不能用paddle训练，可能是paddle还没支持这个系列的显卡吧
