### ISSUE TITLE
Paddle静态图下,针对unsqueeze函数下,类型为float16的tensor运行失败

### ISSUE THREAD

**Issue by bapijun** [PaddlePaddle/Paddle#59056]
### bug描述 Describe the Bug

Paddle静态图下,针对unsqueeze函数下,float16的tensor运行失败

给一个简单的测试代码

```python
# paddlepaddle = 2.5.0
import paddle

x = [1., ]
x_shape = [1]
x_dtype = "float16"
place = (
    paddle.CUDAPlace(0)
    if paddle.is_compiled_with_cuda()
    else paddle.CPUPlace()
)

paddle.enable_static()
with paddle.static.program_guard(paddle.static.Program()):
    data_x = paddle.static.data(name = 'x', shape = x_shape, dtype=x_dtype)
    
    out = paddle.unsqueeze(data_x, 0)
    exe = paddle.static.Executor(place)
    res = exe.run(
        feed={
            'x': x,
         
        },
        fetch_list=[out],
    )
    print(res)

```

当前的错误信息为
```
/usr/local/lib/python3.8/dist-packages/paddle/fluid/data_feeder.py:177: UserWarning: The data type of 'input' in unsqueeze only support float16 in GPU now. 
  warnings.warn(
I1116 16:35:07.184154 33958 interpretercore.cc:237] New Executor is Running.
Traceback (most recent call last):
  File "/home/wujun/code/python/paddle/stack/static.py", line 20, in <module>
    res = exe.run(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1392, in run
    res = self._run_impl(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1618, in _run_impl
    ret = new_exe.run(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 654, in run
    tensors = self._new_exe.run(
NotImplementedError: In user code:

    File "/home/code/python/paddle/stack/static.py", line 18, in <module>
      out = paddle.unsqueeze(data_x, 0)
    File "/usr/local/lib/python3.8/dist-packages/paddle/tensor/manipulation.py", line 2646, in unsqueeze
      helper.append_op(
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 4013, in append_op
      op = Operator(
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 2781, in __init__
      for frame in traceback.extract_stack():

    UnimplementedError: There are no kernels which are registered in the unsqueeze2 operator.
      [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/framework/operator.cc:2247)
      [operator < unsqueeze2 > error]
```

**Comment by bapijun** [comment]
根据unsqueeze的文档,函数支持float16类型

**Comment by wangna11BD** [comment]
升级paddle到develop试试呢，我用develop是可以运行的～

**Comment by bapijun** [comment]
> 升级paddle到develop试试呢，我用develop是可以运行的～

ok,我等会试一下
