### ISSUE TITLE
libpaddle import error, Windows10 Home, python 3.10.5

### ISSUE THREAD

**Issue by hsk20011** [PaddlePaddle/Paddle#59329]
### 问题描述 Issue Description

Error: Can not import paddle core while this file exists: C:\WPy64-31050\YYY\ddd\lib\site-packages\paddle\fluid\libpaddle.pyd
Traceback (most recent call last):
  File "C:\WPy64-31050\YYY\ddd\lib\site-packages\paddle\fluid\core.py", line 269, in <module>
    from . import libpaddle
ImportError: DLL load failed while importing libpaddle: DLL 초기화 루틴을 실행할 수 없습니다.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\WPy64-31050\YYY\pdlTst.py", line 8, in <module>
    import paddle
  File "C:\WPy64-31050\YYY\ddd\lib\site-packages\paddle\__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "C:\WPy64-31050\YYY\ddd\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "C:\WPy64-31050\YYY\ddd\lib\site-packages\paddle\framework\random.py", line 17, in <module>
    from paddle import fluid
  File "C:\WPy64-31050\YYY\ddd\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "C:\WPy64-31050\YYY\ddd\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from . import core
  File "C:\WPy64-31050\YYY\ddd\lib\site-packages\paddle\fluid\core.py", line 351, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined

### 版本&环境信息 Version & Environment Information

Windows 10 home
cpu version

**Comment by haohongxiang** [comment]
请参照 https://github.com/PaddlePaddle/Paddle/issues/54218 先尝试下重装64位的pywin32或者创建虚拟环境
