### ISSUE TITLE
关于预测时报错ValueError: No such parameter ___conv_pool_0___conv.w0

### ISSUE THREAD

**Issue by xiangjinxin1019** [PaddlePaddle/Paddle#5939]
原先在docker环境下训练了一个model，现在打算直接在linux环境下使用该模型进行预测，但预测时报错。换docker环境下，预测时没有问题。

`
Traceback (most recent call last):
  File "predict.py", line 190, in <module>
    main()
  File "predict.py", line 169, in main
    input=test_data,
  File "/home/users/xiangjinxin/PaddlePaddle/env2.7-gcc482/lib/python2.7/site-packages/paddle/v2/inference.py", line 154, in infer
    inferer = Inference(output_layer=output_layer, parameters=parameters)
  File "/home/users/xiangjinxin/PaddlePaddle/env2.7-gcc482/lib/python2.7/site-packages/paddle/v2/inference.py", line 50, in __init__
    val.copyFromNumpyArray(parameters.get(name).flatten())
  File "/home/users/xiangjinxin/PaddlePaddle/env2.7-gcc482/lib/python2.7/site-packages/paddle/v2/parameters.py", line 239, in get
    return self.__getitem__(key=parameter_name)
  File "/home/users/xiangjinxin/PaddlePaddle/env2.7-gcc482/lib/python2.7/site-packages/paddle/v2/parameters.py", line 182, in __getitem__
    return self.__getter_inner(key, api.PARAMETER_VALUE)
  File "/home/users/xiangjinxin/PaddlePaddle/env2.7-gcc482/lib/python2.7/site-packages/paddle/v2/parameters.py", line 149, in __getter_inner
    shape = self.get_shape(key)
  File "/home/users/xiangjinxin/PaddlePaddle/env2.7-gcc482/lib/python2.7/site-packages/paddle/v2/parameters.py", line 197, in get_shape
    raise ValueError("No such parameter %s" % key)
ValueError: No such parameter ___conv_pool_0___conv.w0
`

**预测部分的代码：**
`test_data = []
    cur_dir = os.path.dirname(os.getcwd())
    test_dir = os.path.join(cur_dir, 'dataset/small_num_test')
    print 'test_dir:', test_dir

    output_dir = os.path.join(cur_dir, 'holeView_keyboardModel/output6/params_pass_0.tar')
    print 'output_dir:', output_dir
    with open(output_dir, 'r') as f:
        parameters = paddle.parameters.Parameters.from_tar(f)

    # image index
    index = 1
    # total accuacy
    accu_num = 0
    label = None
    for test_img in os.listdir(test_dir):
        test_data.append((load_image(test_dir + '/' + test_img), ))

        label_str = test_img.split('.')[0]
        # print 'label_str is:', label_str
        if label_str == 'correct':
            label = 0
        elif label_str == 'incorrect':
            label = 1
        else:
            print 'label_str error:', label_str
            raise TypeError

        probs = paddle.infer(
            output_layer=predict,
            parameters=parameters,
            input=test_data,
        )`

**Comment by Yancey1989** [comment]
应该是预测环境的Paddle版本比较新导致的，你Docker用的是哪个版本呢？

**Comment by xiangjinxin1019** [comment]
@Yancey1989
你好，我的docker上paddle是0.10.0，linux上刚装的是0.10.5

**Comment by Yancey1989** [comment]
Hi @xiangjinxin1019 , 这问题应该是新版本对模型保存的文件名有过修改，可以尝试下面的方法：
1. 保证训练和预测版本一致， 使用docker进行预测，或者使用新版本的paddlepaddle进行训练
1. 比较track的方法是在linux机器上做一个小数据集训练并保存模型，然后对比两个tar包里的文件名，把不一样的rename一下，再对比下那个protobufstr，不一样的话也替换一下。

**Comment by xiangjinxin1019** [comment]
@Yancey1989，了解了，谢谢你的解答。
顺便问一下，predict.py执行的时候，可以只输出预测的结果，而不要那些模型加载的输出内容吗，在哪里修改配置呢？因为我想把预测做成一种调用服务，predict.py输出的内容越简单越好。

**Comment by Yancey1989** [comment]
有些debug信息是写在C++里需要编译时关闭的，如果做成服务调用的话建议写成一个Http Server。
