### ISSUE TITLE
PIR program encounters data type error

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#59467]
### bug描述 Describe the Bug

I'm developing a new PIR pass, but I encountered the following error when running the unittest.

To reproduce (All data types are set to float16):
```python
import paddle
import numpy as np
from paddle.base import core

shape = (10, 10)
x_np = np.random.normal(loc=0, scale=0.1, size=shape).astype("float16")
y_np = np.random.normal(loc=0, scale=0.1, size=shape).astype("float16")

with paddle.pir_utils.IrGuard():
    main_program = paddle.static.Program()
    with paddle.static.program_guard(main_program):
        x = paddle.static.data(name="x", shape=shape, dtype="float16")
        y = paddle.static.data(name="y", shape=shape, dtype="float16")

        x.stop_gradient = False
        y.stop_gradient = False

        out = paddle.matmul(x, y)
        res1 = paddle.reshape(out, [100,])

        res2, res3 = paddle.autograd.ir_backward.grad(res1, [x, y])

        with paddle.static.scope_guard(paddle.static.Scope()):
            exe = paddle.base.Executor(paddle.base.CUDAPlace(0))
            exe.run(
                main_program,
                feed={"x": x_np, "y": y_np},
            )
```

Error message:
```
I1128 13:43:03.459472 47122 inplace_pass.cc:428] Apply inplace pass on lowering ::pir::Program to Kernel Dialect.
I1128 13:43:03.600842 47122 pir_interpreter.cc:1126] New Executor is BetaRunning.
W1128 13:43:03.602108 47122 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 12.2, Runtime API Version: 12.2
W1128 13:43:03.603127 47122 gpu_resources.cc:164] device: 0, cuDNN Version: 8.9.
I1128 13:43:03.603626 47122 pir_interpreter.cc:1153] New ir interpreter is running in BetaRun mode with multi thread version.
W1128 13:43:03.726270 47333 pir_interpreter.cc:1532] pd_op.matmul_grad raises an EnforceNotMet exception phi::enforce::EnforceNotMet, In user code:


    InvalidArgumentError: The type of data we are trying to retrieve (float32) does not match the type of data (float16) currently contained in the container.
      [Hint: Expected dtype() == phi::CppTypeToDataType<T>::Type(), but received dtype():15 != phi::CppTypeToDataType<T>::Type():10.] (at /workspace/Paddle/paddle/phi/core/dense_tensor.cc:164)
      [operator < pd_kernel.phi_kernel > error]
Traceback (most recent call last):
  File "/workspace/Paddle/test2.py", line 25, in <module>
    exe.run(
  File "/home/jaywan/.local/lib/python3.10/site-packages/paddle/base/executor.py", line 1707, in run
    res = self._run_pir_impl(
  File "/home/jaywan/.local/lib/python3.10/site-packages/paddle/base/executor.py", line 2050, in _run_pir_impl
    ret = new_exe.run(list(feed.keys()), return_numpy)
  File "/home/jaywan/.local/lib/python3.10/site-packages/paddle/base/executor.py", line 821, in run
    tensors = self._new_exe.run(feed_names)._move_to_list()
ValueError: In user code:


    InvalidArgumentError: The type of data we are trying to retrieve (float32) does not match the type of data (float16) currently contained in the container.
      [Hint: Expected dtype() == phi::CppTypeToDataType<T>::Type(), but received dtype():15 != phi::CppTypeToDataType<T>::Type():10.] (at /workspace/Paddle/paddle/phi/core/dense_tensor.cc:164)
      [operator < pd_kernel.phi_kernel > error]
```

**Comment by Wong4j** [comment]
@zyfncg 麻烦有空看一下

**Comment by changeyoung98** [comment]
此问题我在本地没有复现，麻烦同学拉最新代码试一下，可能问题已经修复了。

**Comment by Wong4j** [comment]
最新的代码已经修复
