### ISSUE TITLE
ExternalError: CUBLAS error(15).Hint: 'CUBLAS_STATUS_NOT_SUPPORTED'

### ISSUE THREAD

**Issue by akari0216** [PaddlePaddle/Paddle#59508]
### bug描述 Describe the Bug

**问题描述 Issue Description**

```
import paddle
paddle.utils.run_check()
```

然后报错：
```
Running verify PaddlePaddle program ... 
I1129 16:23:43.485504 21499 interpretercore.cc:237] New Executor is Running.
W1129 16:23:43.486917 21499 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.2
W1129 16:23:43.533617 21499 gpu_resources.cc:149] device: 0, cuDNN Version: 8.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/utils/install_check.py", line 249, in run_check
    _run_static_single(use_cuda, use_xpu)
  File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/utils/install_check.py", line 147, in _run_static_single
    exe.run(
  File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/fluid/executor.py", line 1392, in run
    res = self._run_impl(
  File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/fluid/executor.py", line 1618, in _run_impl
    ret = new_exe.run(
  File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/fluid/executor.py", line 654, in run
    tensors = self._new_exe.run(
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/utils/install_check.py", line 249, in run_check
      _run_static_single(use_cuda, use_xpu)
    File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/utils/install_check.py", line 133, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/utils/install_check.py", line 37, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/nn/functional/common.py", line 1860, in linear
      helper.append_op(
    File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/fluid/framework.py", line 4013, in append_op
      op = Operator(
    File "/home/featurize/work/.local/lib/python3.10/site-packages/paddle/fluid/framework.py", line 2781, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUBLAS error(15). 
      [Hint: 'CUBLAS_STATUS_NOT_SUPPORTED'.  The functionality requested is not supported ] (at ../paddle/phi/kernels/funcs/blas/blas_impl.cu.h:41)
      [operator < matmul_v2 > error]
```

**版本&环境信息 Version & Environment Information**
python:3.10.12
paddlepaddle-gpu:2.5.2.post112
cuda driver api version:12.0
cuda runtime api version:11.8

### 其他补充信息 Additional Supplementary Information

另已设置了$LD_LIBRARY_PATH和$CUDA_HOME

```
echo $LD_LIBRARY_PATH
/usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:
echo $CUDA_HOME
/usr/local/cuda-11.2:/usr/local/cuda:
```

bug仍未解决，参考issue[ ExternalError: CUBLAS error(15) #49519 ](https://github.com/PaddlePaddle/Paddle/issues/49519)

**Comment by From00** [comment]
看起来像是安装环境的问题，建议尝试升级cuda版本看可否解决。

**Comment by risemeup1** [comment]
你安装的包是cuda11.2的包，但是你的cuda版本是12的，保持一致试下呢。这个肯定是环境的问题导致的

**Comment by risemeup1** [comment]
你的驱动是12.0，环境是11.8，然后设置cuda11.2的变量，安装11.2的包

**Comment by risemeup1** [comment]
建议统一下啊

**Comment by djdll** [comment]
import paddle 
paddle.utils.run_check()
