### ISSUE TITLE
paddle2.5.1 Mac版本训练挂掉

### ISSUE THREAD

**Issue by lichangW** [PaddlePaddle/Paddle#60256]
### bug描述 Describe the Bug

这边在mac上安装 pip3 install paddlepaddle==2.5.1， 然后训练会包错，麻烦帮忙看下

Traceback (most recent call last):
  File "./train/command.py", line 11, in <module>
    if __name__=='__main__':main()
  File "./train/command.py", line 10, in main
    except Exception as e:e_type,e_value,e_traceback=sys.exc_info();logger.error('type ==> %s'%e_type.__name__);logger.error('value ==> %s'%e_value);traceback.print_exc(file=open(workflow_conf['log_path'],'a+',encoding='UTF-8'));six.reraise(sys.exc_info()[0],sys.exc_info()[1],sys.exc_info()[2])
  File "/Applications/xxx/Contents/Resources/resources/lib/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "./train/command.py", line 9, in main
    try:args=parse_args();workflow_conf=update_args(args);logger.info('workflow conf: %s'%workflow_conf.keys());pkg,cls=workflow_conf['workflow_type'].split('.');wfw_module=importlib.import_module('rudder_desktop.train.jobs.%s'%pkg);wfw_cls=getattr(wfw_module,cls);wfw_obj=wfw_cls(workflow_conf);wfw_obj.run()
  File "/Applications/xxx/Contents/Resources/resources/lib/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1050, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "rudder_desktop/train/jobs/paddle_detection_workflow.py", line 4, in init rudder_desktop.train.jobs.paddle_detection_workflow
  File "rudder_desktop/train/utils/paddle_utils.py", line 1, in init rudder_desktop.train.utils.paddle_utils
  File "/Applications/飞桨xxx.app/Contents/Resources/resources/lib/cpu_paddle/lib/python3.7/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/Applications/xxx.app/Contents/Resources/resources/lib/cpu_paddle/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/Applications/飞桨xxx.app/Contents/Resources/resources/lib/cpu_paddle/lib/python3.7/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/Applications/飞桨xxx.app/Contents/Resources/resources/lib/cpu_paddle/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/Applications/飞桨xxx.app/Contents/Resources/resources/lib/cpu_paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/Applications/飞桨xxx.app/Contents/Resources/resources/lib/cpu_paddle/lib/python3.7/site-packages/paddle/fluid/core.py", line 351, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined
[ERROR 12-22 12:25:00.205 main.py:29] Subprocess Failed! return code is 1

**Comment by risemeup1** [comment]
是arm的机器还是x86的机器？

**Comment by risemeup1** [comment]
<img width="987" alt="3326367b35807d43cea3eb5e8b6bc877" src="https://github.com/PaddlePaddle/Paddle/assets/62429225/c4efaca0-aab0-4b25-97e2-273353c9e285">
是不是你的python是x86的python，需要用arm版本的。python3 -c "import platform;print(platform.architecture()[0]);print(platform.machine())"
