### ISSUE TITLE
PaddleDetection里边导出serving使用的模型失败

### ISSUE THREAD

**Issue by yootou** [PaddlePaddle/Paddle#60908]
### 请提出你的问题 Please ask your question

![微信图片_20240117201918](https://github.com/PaddlePaddle/Paddle/assets/59105139/bb61039a-73a8-455b-8f9a-75f32636df49)
如图，出现下边的错误：
RuntimeError: Can't call main_program when full_graph=False. Use paddle.jit.to_static(full_graph=True) instead.

**Comment by leowenyang** [comment]
遇到相同的问题， 使用的环境如下：
PaddleDetection 2.7 
Python 3.10.10
PaddlePaddle 2.6.0

**Comment by 3116005131** [comment]
遇到相同的问题

**Comment by xiangwan1** [comment]
我也遇到了这样的问题，我通过Pycharm找到了有个full_graph赋值为None的位置，将它改成了True，然后就可以在CPU上跑了
![Uploading t.png…]()。希望对你有帮助

**Comment by a31413510** [comment]
我也遇到这个问题
在trainer.py修改：
static_model = paddle.jit.to_static(self.model, input_spec=input_spec, full_graph=True)
问题解决

**Comment by m00nLi** [comment]
发布新版本根本没有测试

**Comment by nyh3174680732** [comment]
> 我也遇到这个问题 在trainer.py修改： static_model = paddle.jit.to_static(self.model, input_spec=input_spec, full_graph=True) 问题解决
该方法解决了我的导出问题

**Comment by xychenzhicheng** [comment]
在执行python tools/export_model.py -c configs/yolov3/yolov3_mobilenet_v3_large_ssld_270e_voc.yml \
 -o weights=/home/aistudio/work/best_model.pdparams时，遇到了如下报错：
Traceback (most recent call last):
  File "tools/export_model.py", line 118, in <module>
    main()
  File "tools/export_model.py", line 114, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 80, in run
    trainer.export(FLAGS.output_dir, for_fd=FLAGS.for_fd)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 1230, in export
    save_dir, yaml_name=yaml_name)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 1177, in _get_infer_cfg_and_input_spec
    static_model = paddle.jit.to_static(self.model, input_spec=input_spec, full_graph=True)
TypeError: declarative() got an unexpected keyword argument 'full_graph'


解决方案：对/home/aistudio/PaddleDetection/ppdet/engine/trainer.py文件做如下修改
# static_model = paddle.jit.to_static(self.model, input_spec=input_spec, full_graph=True)
static_model = paddle.jit.to_static(self.model, input_spec=input_spec)
