### ISSUE TITLE
训练中途next(dataloader)报错StopIteration

### ISSUE THREAD

**Issue by LittleRain626** [PaddlePaddle/Paddle#60950]
您好，我在训练过程中自定义数据集和collate_fn，正常训练八代后会报错，重新加载断点模型，训练八代后又会出现同样的错误，请问这个问题应该怎样解决呢？下面是具体的报错日志和collate_fn核心代码。
```
  File "train.py", line 193, in <module>
    main()
  File "train.py", line 189, in main
    run(FLAGS, cfg)
  File "train.py", line 145, in run
    trainer.train(FLAGS.eval)
  File "trainer.py", line 310, in train
    self.train_with_unlabel(model, epoch_id, profiler_options, use_fused_allreduce_gradients)
  File "trainer.py", line 438, in train_with_unlabel
    unlabel_data = next(self.unlabel_loader.__iter__()) 
  File "reader.py", line 342, in __next__
    six.reraise(*sys.exc_info())
  File "/root/anaconda3/envs/paddle/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "reader.py", line 339, in __next__
    return next(self.loader)
  File "/root/anaconda3/envs/paddle/lib/python3.9/site-packages/paddle/io/dataloader/dataloader_iter.py", line 825, in __next__
    self._reader.read_next_list()[0]
StopIteration
I0118 16:39:05.198752 362076 process_group_nccl.cc:132] ProcessGroupNCCL destruct 
I0118 16:39:05.198896 362076 process_group_nccl.cc:132] ProcessGroupNCCL destruct 
I0118 16:39:05.198935 362076 process_group_nccl.cc:132] ProcessGroupNCCL destruct 


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1705567145 (unix time) try "date -d @1705567145" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x5860a) received by PID 362076 (TID 0x7fb994cef200) from PID 361994 ***]

```

```python
@serializable
class DetDataset(Dataset):
    """
    Load detection dataset.

    Args:
        dataset_dir (str): root directory for dataset.
        image_dir (str): directory for images.
        anno_path (str): annotation file path.
        data_fields (list): key name of data dictionary, at least have 'image'.
        sample_num (int): number of samples to load, -1 means all.
        use_default_label (bool): whether to load default label list.
        repeat (int): repeat times for dataset, use in benchmark.
    """

    def __init__(self,
                 dataset_dir=None,
                 image_dir=None,
                 anno_path=None,
                 data_fields=['image'],
                 sample_num=-1,
                 use_default_label=None,
                 repeat=1,
                 **kwargs):
        super(SSOD_DetDataset, self).__init__()
        self.dataset_dir = dataset_dir if dataset_dir is not None else ''
        self.anno_path = anno_path
        self.image_dir = image_dir if image_dir is not None else ''
        self.data_fields = data_fields
        self.sample_num = sample_num
        self.use_default_label = use_default_label
        self.repeat = repeat
        self._epoch = 0
        self._curr_iter = 0

    def __len__(self, ):
        return len(self.roidbs) * self.repeat

    def __call__(self, *args, **kwargs):
        return self

    def __getitem__(self, idx):
        n = len(self.roidbs)
        if self.repeat > 1:
            idx %= n
        # data batch
        roidb = copy.deepcopy(self.roidbs[idx])
        if self.mixup_epoch == 0 or self._epoch < self.mixup_epoch:
            idx = np.random.randint(n)
            roidb = [roidb, copy.deepcopy(self.roidbs[idx])]
        elif self.cutmix_epoch == 0 or self._epoch < self.cutmix_epoch:
            idx = np.random.randint(n)
            roidb = [roidb, copy.deepcopy(self.roidbs[idx])]
        elif self.mosaic_epoch == 0 or self._epoch < self.mosaic_epoch:
            roidb = [roidb, ] + [
                copy.deepcopy(self.roidbs[np.random.randint(n)])
                for _ in range(4)
            ]
        elif self.pre_img_epoch == 0 or self._epoch < self.pre_img_epoch:
            # Add previous image as input, only used in CenterTrack
            idx_pre_img = idx - 1
            if idx_pre_img < 0:
                idx_pre_img = idx + 1
            roidb = [roidb, ] + [copy.deepcopy(self.roidbs[idx_pre_img])]
        if isinstance(roidb, Sequence):
            for r in roidb:
                r['curr_iter'] = self._curr_iter
        else:
            roidb['curr_iter'] = self._curr_iter
        self._curr_iter += 1

        return self.weak_transform(roidb)#, self.strong_transform(roidb)

    def check_or_download_dataset(self):
        self.dataset_dir = get_dataset_path(self.dataset_dir, self.anno_path,
                                            self.image_dir)

    def set_kwargs(self, **kwargs):
        self.mixup_epoch = kwargs.get('mixup_epoch', -1)
        self.cutmix_epoch = kwargs.get('cutmix_epoch', -1)
        self.mosaic_epoch = kwargs.get('mosaic_epoch', -1)
        self.pre_img_epoch = kwargs.get('pre_img_epoch', -1)

    def set_transform(self, strong_transform, weak_transform):
        self.strong_transform = strong_transform
        self.weak_transform = weak_transform

    def set_epoch(self, epoch_id):
        self._epoch = epoch_id

    def parse_dataset(self, ):
        raise NotImplementedError(
            "Need to implement parse_dataset method of Dataset")

    def get_anno(self):
        if self.anno_path is None:
            return
        return os.path.join(self.dataset_dir, self.anno_path)


class BatchCompose(Compose):
    def __init__(self, transforms, num_classes=80, collate_batch=True):
        super(BatchCompose, self).__init__(transforms, num_classes)
        self.collate_batch = collate_batch

    def __call__(self, data):
        weak_data = []
        for i in range(len(data)):
            weak_data.append(deepcopy(data[i]))

        ori_weak_data = deepcopy(weak_data)
        for f in self.transforms_cls:
            try:
                weak_data = f(weak_data)
            except Exception as e:
                stack_info = traceback.format_exc()
                logger.warning("fail to map batch transform [{}] with error: {} and stack:\n{}".format(f, e, str(stack_info)))
                raise e

        # remove keys which is not needed by model
        extra_key = ['h', 'w', 'flipped']
        for k in extra_key:
            for sample in weak_data:
                if k in sample:
                    sample.pop(k)

        weak_batch_data = {}
        for k in weak_data[0].keys():
            tmp_data = []
            for i in range(len(weak_data)):
                tmp_data.append(weak_data[i][k])
            if not 'gt_' in k and not 'is_crowd' in k and not 'difficult' in k:
                tmp_data = np.stack(tmp_data, axis=0)
            weak_batch_data[k] = tmp_data

        return weak_batch_data,  ori_weak_data

@register
class TrainReader(object):
    __shared__ = ['num_classes']
    def __init__(self,
                 strong_transforms=[],
                 weak_transforms=[],
                 batch_transforms=[],
                 batch_size=1,
                 shuffle=True,
                 drop_last=True,
                 num_classes=80,
                 collate_batch=True,
                 use_shared_memory=False,
                 **kwargs):
        # sample transform
        self._strong_transforms = Compose(strong_transforms, num_classes=num_classes)
        self._weak_transforms = Compose(weak_transforms, num_classes=num_classes)

        # batch transfrom 
        self._batch_transforms = BatchCompose(batch_transforms, num_classes, collate_batch)
        self.batch_size = batch_size
        self.shuffle = shuffle
        self.drop_last = drop_last
        self.use_shared_memory = use_shared_memory
        self.kwargs = kwargs


    def __call__(self,
                 dataset,
                 worker_num,
                 batch_sampler=None,
                 return_list=False):
        self.dataset = dataset
        self.dataset.check_or_download_dataset()
        self.dataset.parse_dataset()
        # get data
        self.dataset.set_transform(self._strong_transforms, self._weak_transforms)
        # set kwargs
        self.dataset.set_kwargs(**self.kwargs)
        # batch sampler
        if batch_sampler is None:
            self._batch_sampler = DistributedBatchSampler(
                self.dataset,
                batch_size=self.batch_size,
                shuffle=self.shuffle,
                drop_last=self.drop_last)
        else:
            self._batch_sampler = batch_sampler

        # DataLoader do not start sub-process in Windows and Mac
        # system, do not need to use shared memory
        use_shared_memory = self.use_shared_memory and sys.platform not in ['win32', 'darwin']
        # check whether shared memory size is bigger than 1G(1024M)
        if use_shared_memory:
            shm_size = _get_shared_memory_size_in_M()
            if shm_size is not None and shm_size < 1024.:
                logger.warning("Shared memory size is less than 1G, disable shared_memory in DataLoader")
                use_shared_memory = False

        self.dataloader = DataLoader(
            dataset=self.dataset,
            batch_sampler=self._batch_sampler,
            collate_fn=self._batch_transforms,
            num_workers=worker_num,
            return_list=return_list,
            use_shared_memory=use_shared_memory)
        self.loader = iter(self.dataloader)

        return self

    def __len__(self):
        return len(self._batch_sampler)

    def __iter__(self):
        return self

    def __next__(self):
        try:
            return next(self.loader)
        except:
            print('debug')

```

**Comment by LittleRain626** [comment]
问题已解决，由于中间使用next获取迭代器数据，导致迭代器数据取完了，需要重新iter一下。
