### ISSUE TITLE
分布式cpups静态图时，optimizer.minimize(ltv_model.loss)报错抛出异常：assert id >= 0 and id < len(self.block.program.blocks)

### ISSUE THREAD

**Issue by MingqiFANG** [PaddlePaddle/Paddle#61019]
### bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/Paddle/assets/79917634/26b35589-5773-402c-80f2-8472564bff52)
[2024-01-22 16:13:45,550] [    INFO] distributed_strategy.py:160 - distributed strategy initialized
fl-ps > local_sparse: [], remote_sparse: []
Traceback (most recent call last):
  File "/home/work/fangmingqi/recall_dnn_ps/train.py", line 332, in <module>
    optimizer.minimize(ltv_model.loss)
  File "/home/work/anaconda3/envs/env1/lib/python3.10/site-packages/paddle/distributed/fleet/fleet.py", line 1267, in minimize
    return self._minimize_impl(
  File "/home/work/anaconda3/envs/env1/lib/python3.10/site-packages/paddle/distributed/fleet/fleet.py", line 1555, in _minimize_impl
    self._runtime_handle = RuntimeFactory()._create_runtime(context)
  File "/home/work/anaconda3/envs/env1/lib/python3.10/site-packages/paddle/distributed/fleet/base/runtime_factory.py", line 38, in _create_runtime
    ps_runtime._set_basic_info(context)
  File "/home/work/anaconda3/envs/env1/lib/python3.10/site-packages/paddle/distributed/ps/the_one_ps.py", line 1085, in _set_basic_info
    build_var_distributed(self.context)
  File "/home/work/anaconda3/envs/env1/lib/python3.10/site-packages/paddle/distributed/ps/utils/public.py", line 1475, in build_var_distributed
    sparse_pairs, dense_pairs = get_param_grads(origin_program)
  File "/home/work/anaconda3/envs/env1/lib/python3.10/site-packages/paddle/distributed/ps/utils/public.py", line 1610, in get_param_grads
    sparse_param_grads, dense_param_grads = _get_params_grads(sparse_varnames)
  File "/home/work/anaconda3/envs/env1/lib/python3.10/site-packages/paddle/distributed/ps/utils/public.py", line 1573, in _get_params_grads
    if _is_opt_role_op(op):
  File "/home/work/anaconda3/envs/env1/lib/python3.10/site-packages/paddle/distributed/ps/utils/public.py", line 1556, in _is_opt_role_op
    op.all_attrs()[op_maker.kOpRoleAttrName()]
  File "/home/work/anaconda3/envs/env1/lib/python3.10/site-packages/paddle/fluid/framework.py", line 3486, in all_attrs
    attr_map[n] = self._block_attr(n)
  File "/home/work/anaconda3/envs/env1/lib/python3.10/site-packages/paddle/fluid/framework.py", line 3400, in _block_attr
    assert id >= 0 and id < len(self.block.program.blocks)
AssertionError

**Comment by lugimzzz** [comment]
提供一下使用的paddle版本和可以复现的代码

**Comment by MingqiFANG** [comment]
paddle2.5，请问可以提供入流邮箱什么给我吗？我是内部员工，可复现代码不方便在这边给出
