### ISSUE TITLE
报“AttributeError: 'list' object has no attribute 'ndim'”

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#61258]
`SentenceEmbedding`是我自定义的句向量生成模型，继承了`ErniePretrainedModel`类。在执行以下代码时，
```python
model = SentenceEmbedding.from_pretrained('ernie-tiny')
tokenizer = ErnieTokenizer.from_pretrained('ernie-tiny')
input = tokenizer(['今年我读二年级', '你好', '谢谢你'], max_length=10, padding='max_length', truncation=True, return_overflowing_tokens=False, return_attention_mask=True)
```
报错
```shell
Traceback (most recent call last):
  File "D:\Projects\model.py", line 58, in <module>
    output = model(input)
             ^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Projects\model.py", line 22, in forward
    outputs = self.ernie(input_ids=input['input_ids'], token_type_ids=input['token_type_ids'], attention_mask=input['attention_mask'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 341, in forward
    elif attention_mask.ndim == 2:
         ^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'ndim'
```
看上去是因为tokenize后生成的`attention_mask`是个二维的List，没有`ndim`属性。请问函数`tokenizer`有没有哪个参数能够自动把变量类型转化成相应的？

**Comment by wangguan1995** [comment]
tokenizer定义可以补充一下吗？


报错位置在ERNIE模型的forward方法中，问题代码是对tokenizer的调用。报错的原因是生成的attention_mask是一个二维的List，而List类型没有ndim属性。解决这个问题的方法是在调用tokenizer时，将return_attention_mask参数设置为True，并且使用paddle.to_tensor方法将生成的attention_mask转换为Tensor类型。具体代码如下：


```python
model = SentenceEmbedding.from_pretrained('ernie-tiny')
tokenizer = ErnieTokenizer.from_pretrained('ernie-tiny')
**改这里** -> ErnieTokenizer.attention_mask.ndim = paddle.to_tensor(ErnieTokenizer.attention_mask.ndim)
input = tokenizer(['今年我读二年级', '你好', '谢谢你'], max_length=10, padding='max_length', truncation=True, return_overflowing_tokens=False, return_attention_mask=True)
```

**Comment by Ywandung-Lyou** [comment]
tokenizer时直接用`ernie-tiny`的，换成AutoTokenizer也有着报错。
```python
model = SentenceEmbedding.from_pretrained('ernie-tiny')
from paddlenlp.transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('ernie-tiny')
input = tokenizer(['今年我读二年级', '你好', '谢谢你'], max_length=10, padding='max_length', truncation=True, return_attention_mask=True)
```

**Comment by ghost** [comment]
代码如下修改，依旧报错：
```python
from paddlenlp.transformers import AutoTokenizer
from paddlenlp.transformers import AutoModel
model = AutoModel.from_pretrained('ernie-tiny')
tokenizer = AutoTokenizer.from_pretrained('ernie-tiny')

input = tokenizer(['今年我读二年级', '你好', '谢谢你'], max_length=10, padding='max_length', truncation=True, return_attention_mask=True)
input['attention_mask'] = paddle.to_tensor(input['attention_mask'])

output = model(input)
```
```shell
Traceback (most recent call last):
  File "D:\Projects\SentenceErnie\model.py", line 60, in <module>
    output = model(input)
             ^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 333, in forward
    (input_ids == self.pad_token_id).astype(self.pooler.dense.weight.dtype) * -1e4, axis=[1, 2]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'astype'
```

**Comment by JunnYu** [comment]
model(**input)

**Comment by ghost** [comment]
运行
```python
class SentenceEmbedding (ErniePretrainedModel):
    def __init__ (self, config: ErnieConfig):
        super(SentenceEmbedding, self).__init__(config)
        print(config)
        self.ernie = ErnieModel(config)
        self.dropout = nn.Dropout(config.classifier_dropout if config.classifier_dropout is not None else config.hidden_dropout_prob)

    def forward (self, model_input):
        outputs = self.ernie(input_ids=model_input['input_ids'], token_type_ids=model_input['token_type_ids'], attention_mask=model_input['attention_mask'])

        return outputs[0]

from paddlenlp.transformers import AutoTokenizer

model = SentenceEmbedding.from_pretrained('ernie-tiny')
tokenizer = AutoTokenizer.from_pretrained('ernie-tiny')

input = tokenizer(['今年我读二年级', '你好', '谢谢你'], max_length=10, padding='max_length', truncation=True, return_attention_mask=True)
input['attention_mask'] = paddle.to_tensor(input['attention_mask'])

output = model(**input)
```
时报错
```shell
Traceback (most recent call last):
  File "D:\Projects\SentenceErnie\model.py", line 58, in <module>
    output = model(**input)
             ^^^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SentenceEmbedding.forward() got an unexpected keyword argument 'input_ids'
```
请问这该如何解决？

**Comment by ghost** [comment]
代码改成：

```python
import paddle   
from paddlenlp.transformers import AutoTokenizer, AutoModel

model = AutoModel.from_pretrained('ernie-tiny')
tokenizer = AutoTokenizer.from_pretrained('ernie-tiny')

input = tokenizer(['今年我读二年级', '你好', '谢谢你'], max_length=10, padding='max_length', truncation=True, return_attention_mask=True)
input['attention_mask'] = paddle.to_tensor(input['attention_mask'])

output = model(**input)
```

但依旧报错：

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 347, in forward
    embedding_output = self.embeddings(
                       ^^^^^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 98, in forward
    inputs_embeds = self.word_embeddings(input_ids)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddle\nn\layer\common.py", line 1508, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "D:\Software\Miniconda3\envs\paddle\Lib\site-packages\paddle\nn\functional\input.py", line 229, in embedding
    return _C_ops.embedding(x, weight, padding_idx, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: (InvalidArgument) embedding(): argument 'x' (position 0) must be Tensor, but got list (at ..\paddle\fluid\pybind\eager_utils.cc:1334)
```

**Comment by JunnYu** [comment]
第一、没有return_tensors=pd，第二，没有使用**input, 因为return_tensors=pd后input是个字典（之前是个list，自己打印就可以看到）
```python
import paddle   
from paddlenlp.transformers import AutoTokenizer, AutoModel

model = AutoModel.from_pretrained('ernie-tiny')
tokenizer = AutoTokenizer.from_pretrained('ernie-tiny')
input = tokenizer(['今年我读二年级', '你好', '谢谢你'], max_length=10, padding='max_length', truncation=True, return_attention_mask=True, return_tensors="pd")
output = model(**input)
```
