### ISSUE TITLE
develop cu118：NameError: name 'os' is not defined

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/Paddle#61330]
### bug描述 Describe the Bug

```bash
aistudio@jupyter-168825-7445181:~$ pip install paddlepaddle-gpu==0.0.0.post118 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html --user
Looking in indexes: https://mirror.baidu.com/pypi/simple/, https://mirrors.aliyun.com/pypi/simple/
Looking in links: https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
Collecting paddlepaddle-gpu==0.0.0.post118
  Downloading https://paddle-wheel.bj.bcebos.com/develop/linux/linux-gpu-cuda11.8-cudnn8.6-mkl-gcc8.2-avx/paddlepaddle_gpu-0.0.0.post118-cp310-cp310-linux_x86_64.whl (776.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 776.9/776.9 MB 1.5 MB/s eta 0:00:00
Requirement already satisfied: httpx in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from paddlepaddle-gpu==0.0.0.post118) (0.26.0)
Requirement already satisfied: numpy<2.0,>=1.13 in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from paddlepaddle-gpu==0.0.0.post118) (1.26.2)
Requirement already satisfied: protobuf>=3.20.2 in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from paddlepaddle-gpu==0.0.0.post118) (3.20.3)
Requirement already satisfied: Pillow in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from paddlepaddle-gpu==0.0.0.post118) (10.1.0)
Requirement already satisfied: decorator in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from paddlepaddle-gpu==0.0.0.post118) (5.1.1)
Requirement already satisfied: astor in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from paddlepaddle-gpu==0.0.0.post118) (0.8.1)
Requirement already satisfied: opt-einsum==3.3.0 in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from paddlepaddle-gpu==0.0.0.post118) (3.3.0)
Requirement already satisfied: anyio in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from httpx->paddlepaddle-gpu==0.0.0.post118) (3.7.1)
Requirement already satisfied: certifi in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from httpx->paddlepaddle-gpu==0.0.0.post118) (2023.11.17)
Requirement already satisfied: httpcore==1.* in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from httpx->paddlepaddle-gpu==0.0.0.post118) (1.0.2)
Requirement already satisfied: idna in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from httpx->paddlepaddle-gpu==0.0.0.post118) (3.6)
Requirement already satisfied: sniffio in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from httpx->paddlepaddle-gpu==0.0.0.post118) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from httpcore==1.*->httpx->paddlepaddle-gpu==0.0.0.post118) (0.14.0)
Requirement already satisfied: exceptiongroup in /opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages (from anyio->httpx->paddlepaddle-gpu==0.0.0.post118) (1.2.0)
Installing collected packages: paddlepaddle-gpu
  WARNING: The script fleetrun is installed in '/home/aistudio/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed paddlepaddle-gpu-0.0.0.post118
aistudio@jupyter-168825-7445181:~$ python
Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aistudio/.local/lib/python3.10/site-packages/paddle/__init__.py", line 568, in <module>
    package_dir = os.path.dirname(os.path.abspath(__file__))
NameError: name 'os' is not defined. Did you mean: 'cos'?
>>> 
```

**Comment by JiehangXie** [comment]
目前临时解决办法，在__init__.py文件import os  
但希望官方尽快修复提交新包

**Comment by lijialin03** [comment]
您好，这个错误已于[commit 67b1723](https://github.com/PaddlePaddle/Paddle/commit/67b1723f1a9bec5dd04cde70fd04484eea8b7a97)修复，会尽快发的包，感谢您的反馈～
