### ISSUE TITLE
[develop bug] PPLCNetV2_base 预测模型自动压缩产出量化模型报错：RuntimeError: Unimplemented error. Invalid dimension to be accessed. Now only supports access to dimension 0 to 9, but received dimension is -2.

### ISSUE THREAD

**Issue by EmmonsCurse** [PaddlePaddle/Paddle#61405]
### 问题描述

基于 develop 分支编包，PPLCNetV2_base 预测模型自动压缩产出量化模型报错：RuntimeError: Unimplemented error. Invalid dimension to be accessed. Now only supports access to dimension 0 to 9, but received dimension is -2.

```
I0131 10:58:12.559219 69418 interpreter_util.cc:652] Standalone Executor is Used.
W0131 10:58:12.750082 69418 interpreter_util.cc:985] pool2d_grad raises an exception common::PD_Exception, Unimplemented error. Invalid dimension to be accessed. Now only supports access to dimension 0 to 9, but received dimension is -2.
  [../paddle/common/ddim.h:61]
Traceback (most recent call last):
  File "run.py", line 212, in <module>
    main()
  File "run.py", line 205, in main
    ac.compress()
  File "/opt/_internal/cpython-3.8.0/lib/python3.8/site-packages/paddleslim-0.0.0.dev0-py3.8.egg/paddleslim/auto_compression/compressor.py", line 586, in compress
  File "/opt/_internal/cpython-3.8.0/lib/python3.8/site-packages/paddleslim-0.0.0.dev0-py3.8.egg/paddleslim/auto_compression/compressor.py", line 780, in single_strategy_compress
  File "/opt/_internal/cpython-3.8.0/lib/python3.8/site-packages/paddleslim-0.0.0.dev0-py3.8.egg/paddleslim/auto_compression/compressor.py", line 799, in _start_train
  File "/opt/_internal/cpython-3.8.0/lib/python3.8/site-packages/paddle/base/executor.py", line 1776, in run
    res = self._run_impl(
  File "/opt/_internal/cpython-3.8.0/lib/python3.8/site-packages/paddle/base/executor.py", line 1982, in _run_impl
    ret = new_exe.run(
  File "/opt/_internal/cpython-3.8.0/lib/python3.8/site-packages/paddle/base/executor.py", line 829, in run
    tensors = self._new_exe.run(
RuntimeError: Unimplemented error. Invalid dimension to be accessed. Now only supports access to dimension 0 to 9, but received dimension is -2.
  [../paddle/common/ddim.h:61]
```

### 环境信息

- PaddlePaddle version: develop
- PaddleSlim version: develop(9fe0e73878ab4e18596894c463eaa0432fea2792)
- OS version: CentOS
- Python version: 3.8
- GPU info: T4
- CPU info: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
- docker images: registry.baidubce.com/paddlepaddle/paddle_manylinux_devel:cuda11.2-cudnn8.2-trt8.0-gcc82

### 复现方法
可参照 https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/image_classification
#### 准备环境
```
# 安装 paddlepaddle：
wget https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc82-Cuda112-Trtoff-Py38-Compile/latest/paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl
python -m pip install paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl

# 安装 develop 版本 paddleslim
git clone https://github.com/PaddlePaddle/PaddleSlim.git -b develop

cd PaddleSlim
python setup.py install
python -m pip install -r requirements.txt

# 数据集准备
cd ./example/auto_compression/image_classification

wget https://paddle-qa.bj.bcebos.com/PaddleClas/ILSVRC2012_data_demo.tar
tar xf ILSVRC2012_data_demo.tar
mv ILSVRC2012_data_demo ILSVRC2012

# 模型准备
wget https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/inference/PPLCNetV2_base_infer.tar
tar -xf PPLCNetV2_base_infer.tar
```

#### 执行自动压缩并产出量化模型
```
python run.py --save_dir=./save_quant/PPLCNetV2_base_act_qat/ --config_path=./configs/PPLCNetV2_base/qat_dis.yaml
```

**Comment by zzjjay** [comment]
我这边复现下这个问题，解决后回复你~

**Comment by zzjjay** [comment]
@xiaoluomi

**Comment by xiaoluomi** [comment]
在对PPHGNet_tiny模型进行自动话压缩时，也遇到了类似问题，报错如下：
Adding quant op with weight:|██████████████████████████████████████████| 602/602
Adding quant activation op:|████████████████████████████████████████▉| 1547/1548
Adding OutScale op:|███████████████████████████████████████████████████| 645/645
I0409 08:30:28.530294 17540 interpreter_util.cc:652] Standalone Executor is Used.
2024-04-09 08:30:30,558-INFO: Total iter: 0, epoch: 0, batch: 0, loss: 4.217629909515381 soft_label: 4.217629909515381 
Traceback (most recent call last):
  File "/paddle/PaddleSlim/example/auto_compression/image_classification/run.py", line 212, in <module>
    main()
  File "/paddle/PaddleSlim/example/auto_compression/image_classification/run.py", line 205, in main
    ac.compress()
  File "/usr/local/lib/python3.10/dist-packages/paddleslim-0.0.0.dev0-py3.10.egg/paddleslim/auto_compression/compressor.py", line 586, in compress
    self.single_strategy_compress(strategy, config, strategy_idx,
  File "/usr/local/lib/python3.10/dist-packages/paddleslim-0.0.0.dev0-py3.10.egg/paddleslim/auto_compression/compressor.py", line 780, in single_strategy_compress
    test_program_info = self._start_train(
  File "/usr/local/lib/python3.10/dist-packages/paddleslim-0.0.0.dev0-py3.10.egg/paddleslim/auto_compression/compressor.py", line 799, in _start_train
    loss = self._exe.run(train_program_info.program, \
  File "/usr/local/lib/python3.10/dist-packages/paddle/base/executor.py", line 1783, in run
    res = self._run_impl(
  File "/usr/local/lib/python3.10/dist-packages/paddle/base/executor.py", line 1989, in _run_impl
    ret = new_exe.run(
  File "/usr/local/lib/python3.10/dist-packages/paddle/base/executor.py", line 829, in run
    tensors = self._new_exe.run(
OSError: In user code:

    File "/paddle/PaddleSlim/example/auto_compression/image_classification/run.py", line 212, in <module>
      main()
    File "/paddle/PaddleSlim/example/auto_compression/image_classification/run.py", line 205, in main
      ac.compress()
    File "/usr/local/lib/python3.10/dist-packages/paddleslim-0.0.0.dev0-py3.10.egg/paddleslim/auto_compression/compressor.py", line 586, in compress
      self.single_strategy_compress(strategy, config, strategy_idx,
    File "/usr/local/lib/python3.10/dist-packages/paddleslim-0.0.0.dev0-py3.10.egg/paddleslim/auto_compression/compressor.py", line 769, in single_strategy_compress
      train_program_info, test_program_info = self._prepare_program(
    File "/usr/local/lib/python3.10/dist-packages/paddleslim-0.0.0.dev0-py3.10.egg/paddleslim/auto_compression/compressor.py", line 506, in _prepare_program
      train_program_info, test_program_info = build_distill_program(
    File "/usr/local/lib/python3.10/dist-packages/paddleslim-0.0.0.dev0-py3.10.egg/paddleslim/auto_compression/create_compressed_program.py", line 327, in build_distill_program
      train_program, data_name_map = _load_program_and_merge(
    File "/usr/local/lib/python3.10/dist-packages/paddleslim-0.0.0.dev0-py3.10.egg/paddleslim/auto_compression/create_compressed_program.py", line 219, in _load_program_and_merge
      merge(
    File "/usr/local/lib/python3.10/dist-packages/paddleslim-0.0.0.dev0-py3.10.egg/paddleslim/dist/single_distiller.py", line 197, in merge
      student_program.global_block().append_op(
    File "/usr/local/lib/python3.10/dist-packages/paddle/base/framework.py", line 4580, in append_op
      op = Operator(
    File "/usr/local/lib/python3.10/dist-packages/paddle/base/framework.py", line 3134, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED. 
      [Hint: 'CUDNN_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occur for multiple reasons.  To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed.  Otherwise, this may indicate an internal error/bug in the library.  ] (at ../paddle/phi/kernels/gpudnn/pool_kernel.cu:212)
      [operator < pool2d > error]
但是在paddle2.6.1版本下，两个模型都可以正常跑通，这两个模型报错均与pool2d有关，怀疑是该算子出现了问题
