### ISSUE TITLE
Optimizer set error

### ISSUE THREAD

**Issue by zhang-jinqi** [PaddlePaddle/Paddle#61449]
需求是：我在重新加载模型进行增量的训练中，出现了优化器加载失败的情况；下面是调用的代码和错误信息，想请问下要怎么调整去进行增量训练？

```python
        if base_id != 0:
            model_path = './models/' + str(base_id) + '/save_model/best_model/model.pdparams'
            model = hub.Module(name='bert-base-chinese', task='seq-cls', num_classes=len(label),
                               load_checkpoint=model_path, cache_dir='./bert')
        else:
            model = hub.Module(name='bert-base-chinese', task='seq-cls', num_classes=len(label), cache_dir='./bert')

        # 获取训练数据
        train_dataset = DG.SelfDataset(
            tokenizer=model.get_tokenizer(), max_seq_len=512, mode='train', data_file=train_file, label_list=label)
        dev_dataset = DG.SelfDataset(
            tokenizer=model.get_tokenizer(), max_seq_len=512, mode='dev', data_file=test_file, label_list=label)
        test_dataset = DG.SelfDataset(
            tokenizer=model.get_tokenizer(), max_seq_len=512, mode='test', data_file=dev_file, label_list=label)

        # 设置优化器
        optimizer = paddle.optimizer.Adam(learning_rate=float(config_data['TRAIN']['LEARNING_RATE']),
                                          parameters=model.parameters())

        # 将模型保存在./models/model_id/save_model目录下
        checkpoint_dir = os.path.join('./models', model_id, 'save_model')
        # 创建 Trainer
        trainer = hub.Trainer(model, optimizer, checkpoint_dir=checkpoint_dir,
                              use_gpu=config_data['USE_GPU'])
        # 创建一个线程来训练模型
        train_thread = Thread(target=train_model_thread, args=(trainer, train_dataset, dev_dataset, test_dataset,
                                                               model_id, current_app._get_current_object()))
        train_thread.start()

def train_model_thread(trainer, train_dataset, dev_dataset, test_dataset, model_id, app):
    with app.app_context():
        query_model = db.session.query(Infoclass_model).get(model_id)
        try:
            # 训练模型
            # save_interval：每训练多少轮保存一次模型
            trainer.train(train_dataset, epochs=config_data['TRAIN']['EPOCHS'],
                          batch_size=config_data['TRAIN']['BATCH_SIZE']
                          , eval_dataset=dev_dataset, save_interval=config_data['TRAIN']['SAVE_INTERVAL'])
            model_file = os.path.join('./models', model_id, 'save_model/best_model/model.pdparams')
```

报错信息：
```
Traceback (most recent call last):
  File "/data2/app/TRT/info_category_debug/service/lod_pre_api.py", line 401, in train_model_thread
    trainer.train(train_dataset, epochs=config_data['TRAIN']['EPOCHS'],
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/paddlehub/finetune/trainer.py", line 213, in train
    self.optimizer_step(self.current_epoch, batch_idx, self.optimizer, loss)
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/paddlehub/finetune/trainer.py", line 395, in optimizer_step
    self.optimizer.step()
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/paddle/optimizer/adam.py", line 546, in step
    optimize_ops = self._apply_optimize(
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/paddle/optimizer/optimizer.py", line 1166, in _apply_optimize
    optimize_ops = self._create_optimization_pass(
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/paddle/optimizer/optimizer.py", line 924, in _create_optimization_pass
    self._create_accumulators(
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/paddle/optimizer/adam.py", line 337, in _create_accumulators
    self._add_moments_pows(p)
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/paddle/optimizer/adam.py", line 293, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "/data2/anaconda3/envs/seq_cls/lib/python3.8/site-packages/paddle/optimizer/optimizer.py", line 753, in _add_accumulator
    assert (
AssertionError: Optimizer set error, embedding_15.w_0_moment1_0 should in state dict
```

**Comment by SigureMo** [comment]
> AssertionError: Optimizer set error, embedding_15.w_0_moment1_0 should in state dict

可以确认下 save 前后模型结构是否发生了改变，这里的 `embedding_15.w_0_moment1_0` 是否正常

**Comment by zhang-jinqi** [comment]
> > AssertionError: Optimizer set error, embedding_15.w_0_moment1_0 should in state dict
> 
> 可以确认下 save 前后模型结构是否发生了改变，这里的 `embedding_15.w_0_moment1_0` 是否正常

请问应该要怎么处理呢，不是很明白这个意思

**Comment by SigureMo** [comment]
> 请问应该要怎么处理呢，不是很明白这个意思

看一下两个模型代码以及优化器的 `state_dict` 呢？报错指出 `embedding_15.w_0_moment1_0` 参数是有问题的

**Comment by zhang-jinqi** [comment]
> > 请问应该要怎么处理呢，不是很明白这个意思
> 
> 看一下两个模型代码以及优化器的 `state_dict` 呢？报错指出 `embedding_15.w_0_moment1_0` 参数是有问题的

不是这个意思，我是说那是要怎么处理，或者是有什么可以参考的吗，从文档上面看的解释，我没能理解

**Comment by SigureMo** [comment]
> 不是这个意思，我是说那是要怎么处理，或者是有什么可以参考的吗，从文档上面看的解释，我没能理解

这是两个问题，如果你要解决报错，那么请定位问题，如果你要参考，那么文档上没理解的是什么呢？请指出不理解的区域

**Comment by zhang-jinqi** [comment]
> > 不是这个意思，我是说那是要怎么处理，或者是有什么可以参考的吗，从文档上面看的解释，我没能理解
> 
> 这是两个问题，如果你要解决报错，那么请定位问题，如果你要参考，那么文档上没理解的是什么呢？请指出不理解的区域

![image](https://github.com/PaddlePaddle/Paddle/assets/79257896/3bf4da7f-f6ef-4edd-901c-d501bd8bee25)
![image](https://github.com/PaddlePaddle/Paddle/assets/79257896/3c63fcbb-e80a-40b7-b5da-d825a18c6fd2)
我是基于bert-base-chinese来进行的模型训练，按照文档中的示例，重新设置了优化器
 设置优化器
            optimizer = paddle.optimizer.Adam(learning_rate=float(config_data['TRAIN']['LEARNING_RATE']), parameters=model.parameters())
            opt_dict = paddle.load('./models/' + str(model_id) + '/save_model/best_model/model.pdopt')
            optimizer.set_state_dict(state_dict=opt_dict)，
但是还是不行

**Comment by SigureMo** [comment]
对比 `paddle.load(...)` 的 keys 和你新建优化器的 `state_dict` 查看下差异
