### ISSUE TITLE
通过Receiver提交集群训练任务失败

### ISSUE THREAD

**Issue by bit1002lst** [PaddlePaddle/Paddle#6151]
**# submit脚本如下：**

```
./output/paddle cluster_train \
  --config mobilenet_paddle.py \
  --use_remote_sparse 0 \
  --time_limit 00:30:00 \
  --submitter xxxx \
  --num_nodes 1 \
  --job_priority normal \
  --init_model_path \"\" \
  --fs_name xxxx \
  --fs_ugi xxxx \
  --train_meta_data_path \"\" \
  --test_meta_data_path \"\" \
  --thirdparty datasets \
  --output_path lst_output \
  --where xxx \
  --job_name lst_paddle
```

**# 终端输出信息如下：**
```
('connect to receiver: ', 'xxxx:8090')
...
sh: StatisticFrame.sh: No such file or directory
Start to tar files needed by this job! Please wait...
Tar finished, Start to upload files!
Data Upload success!
==========================================================
Success to submit job to xxx
The job id is 4358 on this cluster! 
More information about this job run command as follow: 
showjob -j 4358 -p xxx
==========================================================

submit failed
2017-12-01 14:04:39,630 INFO execute cmd failed: cd ./core && sh run.sh nodes.configs/xxxxxx/trainer_config_from_python_wrapper.conf gpu
```

**Comment by typhoonzero** [comment]
```
Success to submit job to xxx
The job id is 4358 on this cluster! 
More information about this job run command as follow: 
showjob -j 4358 -p xxx
```

看起来任务是提交成功了，不过这个`submit failed `取决于集群client 返回值是否为0 。目前你可以忽略这个，任务实际是提交成功的。

**Comment by bit1002lst** [comment]
最后一行那里显示run.sh执行失败
2017-12-01 14:04:39,630 INFO execute cmd failed: cd ./core && sh run.sh nodes.configs/xxxxxx/trainer_config_from_python_wrapper.conf gpu
这个run.sh是工具生成的么？trainer_config_from_python_wrapper.conf呢？

**Comment by typhoonzero** [comment]
@bit1002lst `run.sh`等都是receiver内的代码。用于打包任务和提交到集群的。

**Comment by bit1002lst** [comment]
我按照提示showjob -j 4380 -p xxxx输入时会提示以下错误
```

Traceback (most recent call last):
  File "/root/.hgcp/software-install/HGCP_client/bin/../lib/client.py", line 348, in <module>
    version_check.version_check(conf)
  File "/root/.hgcp/software-install/HGCP_client/lib/version_check.py", line 99, in version_check
    res = _download_and_check(download_url, CurTmpPath + download_filename, res_md5sum)
  File "/root/.hgcp/software-install/HGCP_client/lib/version_check.py", line 56, in _download_and_check
    saveFile.write(req.read())
IOError: [Errno 28] No space left on device
```
