### ISSUE TITLE
paddle.jit.save()接口保存模型报错

### ISSUE THREAD

**Issue by SenitCo** [PaddlePaddle/Paddle#61630]
### bug描述 Describe the Bug

动态图组网训练后，采用paddle.jit.save()接口将训练模型转为静态图保存，以便提升推理性能，保存模型时报错信息如下，看提示和Transformer层相关，辛苦帮看下该接口使用方式是否有误。

报错信息：
```python
Traceback (most recent call last):
  File "ctr_train.py", line 135, in <module>
    train(args, file_list)
  File "ctr_train.py", line 88, in train
    model_object.save_model(dp_model, args.save_model_path, is_save_inferece=True, input_size=input_size)
  File "/root/paddlejob/workspace/env_run/ctr_model.py", line 65, in save_model
    paddle.jit.save(model, inference_model_path, input_spec=[input_spec])
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 643, in wrapper
    func(layer, path, input_spec, **configs)
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 52, in __impl__
    return func(*args, **kwargs)
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 932, in save
    with_hook=with_hook)
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 570, in concrete_program_specify_input_spec
    is_train=self._is_train_mode())
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 475, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 945, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 934, in _build_once
    **cache_key.kwargs)
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 52, in __impl__
    return func(*args, **kwargs)
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 885, in from_func_spec
    error_data.raise_new_exception()
  File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 343, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "/root/paddlejob/workspace/env_run/ctr_net.py", line 96, in forward
        # encoder layer
        encoder_output = self.encoder(encoder_input)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE

        # dnn_net layer

    File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 929, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/nn/layer/transformer.py", line 709, in forward
	output = mod(output, src_mask=src_mask)
    File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 929, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/nn/layer/transformer.py", line 592, in forward
	src = self.self_attn(src, src, src, src_mask)
    File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 929, in __call__
	return self._dygraph_call_func(*inputs, **kwargs)
    File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in _dygraph_call_func
	outputs = self.forward(*inputs, **kwargs)
    File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/nn/layer/transformer.py", line 408, in forward
	q, k, v = self._prepare_qkv(query, key, value, cache)
    File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/nn/layer/transformer.py", line 235, in _prepare_qkv
	q = tensor.reshape(x=q, shape=[0, 0, self.num_heads, self.head_dim])
    File "/root/paddlejob/workspace/env_run/thirdparty/paddlebox/paddle_release_home/python3/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 3330, in reshape
```

组网简化逻辑：
```python

class DnnLayer(paddle.nn.Layer):
    """
    DnnLayer
    """
    def __init__(self):
        """
        __init__
        """
        super(DnnLayer, self).__init__()

        # dense input size
        self.dense_input_size = config.q_vec_size * 3 + 1
        
        # normlaization layer
        self.norm_layer = paddle.nn.LayerNorm(
                normalized_shape=self.dense_input_size, name='dense_input_layer_norm')
        
        # encoder layer
        self.encoder = self.encoder_layer(self.encoder_input_size, self.encoder_head_num,
                config.encoder_hidden_dim, hidden_act='gelu', encoder_layer_num=config.encoder_layer_num)
        self.encoder_output_size = self.encoder_input_size

        # dnn_net layer 
        self.dnn_net = self.dnn_block_layer10(self.encoder_output_size)

    def forward(self, dense_input):
        # normlaization layer
        encoder_input = self.norm_layer(dense_input)
        # encoder layer
        encoder_output = self.encoder(encoder_input)
        # dnn_net layer
        dnn_output = self.dnn_net(encoder_output)

    def encoder_layer(self,
                    encoder_input_size,
                    encoder_head_num,
                    encoder_hidden_dim,
                    hidden_act='relu',
                    encoder_layer_num=8):
        encoder_layer = nn.TransformerEncoderLayer(
            encoder_input_size,
            encoder_head_num,
            encoder_hidden_dim,
            activation=hidden_act
        )

        encoder = nn.TransformerEncoder(encoder_layer, encoder_layer_num)
        self.add_sublayer('encoder', encoder)

    return encoder
```

模型保存方式：
```python
def save_model(self, model, save_model_path, is_save_inferece=False, input_size=None):
        """
        将模型参数保存到指定路径。
        """
        if save_model_path is not None and os.path.isdir(save_model_path):
            train_model_path = os.path.join(save_model_path, 'train/ctr.pdiparams')
            paddle.save(model.state_dict(), train_model_path)
            if is_save_inferece and input_size is not None:
                model.eval()
                inference_model_path = os.path.join(save_model_path, 'inference')
                input_spec = paddle.static.InputSpec(
                    shape=[None, input_size], dtype='float32', name='input_spec')
                paddle.jit.save(model, inference_model_path, input_spec=[input_spec])
```

**Comment by liaoxin2** [comment]
根据提供的信息，问题可能出现在forward函数中的encoder(encoder_input)处。请确保encoder_input已正确初始化，并且与encoder的输入规格匹配。另外，还可以尝试使用更详细的调试信息来定位问题，例如打印encoder_input的形状和类型，以及检查encoder的定义和参数是否正确。

**Comment by SenitCo** [comment]
@liaoxin2 paddle.jit.save()接口的input_spec参数是需要和forward方法的参数完全一致吗？假设我forward方法的参数是input=[x1, x2, x3]，实际feed给模型的输入是input_trans=concat(x1, multiply(x2, x3))，这个时候input_spec的大小应该和input一致还是和input_trans一致呢？

**Comment by liaoxin2** [comment]
input_spec参数是用来定义模型输入的规格的，它并不需要和forward方法的参数完全一致。input_spec参数是一个字典，其中键是输入的名称，值是对应输入的形状和数据类型。

在你描述的情况下，input=[x1, x2, x3]是forward方法的参数，而input_trans=concat(x1, multiply(x2, x3))是实际feed给模型的输入。根据这个描述，input_spec的大小应该和input_trans一致，因为input_trans是实际输入的形状和数据类型。所以，你可以将input_spec设置为和input_trans一致来定义模型输入的规格。

**Comment by SenitCo** [comment]
@liaoxin2 我之前是按模型实际输入大小来定义的input_spec，paddle.jit.save()的时候就会报错，改成forward输入的size就能正常save了，看save接口的文档好像也是这么描述的

**Comment by SenitCo** [comment]
<img width="1967" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/12945000/05056a27-ae56-4727-a812-63568f369516">


> @liaoxin2 我之前是按模型实际输入大小来定义的input_spec，paddle.jit.save()的时候就会报错，改成forward输入的size就能正常save了，看save接口的文档好像也是这么描述的
