### ISSUE TITLE
PreconditionNotMet error code 126

### ISSUE THREAD

**Issue by cloudy-sfu** [PaddlePaddle/Paddle#61693]
### bug描述 Describe the Bug

问题类似 #50588 但是使用 CPU 时也出现该问题。

新建文件 `main.py`

```
from paddle import inference

_ = input()
```

使用 `pyinstaller` 打包，打开会引起错误 

```
Traceback (most recent call last):
  File "main.pyw", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ocr.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddleocr\__init__.py", line 25, in <module>
    from paddleocr.tools.infer.utility import init_args
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddleocr\tools\infer\utility.py", line 23, in <module>
    from paddle import inference
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddle\__init__.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddle\base\__init__.py", line 207, in <module>
  File "paddle\base\__init__.py", line 199, in __bootstrap__
RuntimeError: (PreconditionNotMet) The third-party dynamic library (mklml.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:312)
```

事实上并没有使用 GPU.

**Comment by cloudy-sfu** [comment]
Download `mklml_win_2018.0.3.20180406.zip` from [[Microsoft](https://learn.microsoft.com/en-us/cognitive-toolkit/setup-mkl-on-windows)](https://learn.microsoft.com/en-us/cognitive-toolkit/setup-mkl-on-windows), unzip, and put in the program root as directory `mklml_win_2018.0.3.20180406/`. 

```
import os
os.environ['PATH'] += ';' + os.path.abspath('mklml_win_2018.0.3.20180406/lib')
```
