### ISSUE TITLE
无法将fp16类型的模型转换成onnx

### ISSUE THREAD

**Issue by lhou705** [PaddlePaddle/Paddle#61803]
### 请提出你的问题 Please ask your question

您好，当我尝试将apm训练后的fp16模型导出成onnx模型时，出现了错误。
use_amp = True
amp_level = 'O2'
AMP = {'level': amp_level, "save_dtype": 'float16',
       'auto_cast': {'level': amp_level, 'enable': True}}
错误日志：
Traceback (most recent call last):
  File "/home/lhou/lxq/PPLaneDet/tools/train.py", line 52, in <module>
    main(args, cfg)
  File "/home/lhou/lxq/PPLaneDet/tools/train.py", line 33, in main
    trainer.export(args.export)
  File "/home/lhou/lxq/PPLaneDet/pplanedet/engine/trainer.py", line 253, in export
    self.load(checkpoint_path)
  File "/home/lhou/lxq/PPLaneDet/pplanedet/engine/trainer.py", line 249, in load
    self.model.set_state_dict(state_dict)
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/base/framework.py", line 661, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 2090, in set_state_dict
    param.set_value(state)
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/base/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/base/framework.py", line 593, in __impl__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/base/dygraph/tensor_patch_methods.py", line 223, in set_value
    self.dtype == dtype
AssertionError: Variable dtype not match, Variable [ batch_norm2d_0.w_0 ] need tensor with dtype paddle.float32  but load tensor with dtype paddle.float16
在尝试手动将模型类型修改为paddle.float16，则出现新的错误。
Traceback (most recent call last):
  File "/home/lhou/lxq/PPLaneDet/tools/train.py", line 52, in <module>
    main(args, cfg)
  File "/home/lhou/lxq/PPLaneDet/tools/train.py", line 33, in main
    trainer.export(args.export)
  File "/home/lhou/lxq/PPLaneDet/pplanedet/engine/trainer.py", line 259, in export
    paddle.jit.save(self.model, os.path.join(save_path, 'model'), input_spec=input_spec)
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/base/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/jit/api.py", line 809, in wrapper
    func(layer, path, input_spec, **configs)
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/base/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/base/dygraph/base.py", line 68, in __impl__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/jit/api.py", line 1175, in save
    dygraph_state_dict = inner_layer.to_static_state_dict()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1968, in to_static_state_dict
    return self._state_dict_impl(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1921, in _state_dict_impl
    layer_item._state_dict_impl(
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1921, in _state_dict_impl
    layer_item._state_dict_impl(
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1921, in _state_dict_impl
    layer_item._state_dict_impl(
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/nn/layer/layers.py", line 1932, in _state_dict_impl
    hook_result = state_dict_hook(destination)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/amp/auto_cast.py", line 480, in __call__
    param_applied = paddle.cast(param, self._save_dtype)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/tensor/manipulation.py", line 210, in cast
    check_variable_and_dtype(
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/base/data_feeder.py", line 170, in check_variable_and_dtype
    check_type(input, input_name, Variable, op_name, extra_message)
  File "/home/lhou/miniconda3/envs/pp2.6/lib/python3.11/site-packages/paddle/base/data_feeder.py", line 196, in check_type
    raise TypeError(
TypeError: Please use `with base.dygraph.guard()` as context or `base.enable_dygraph()` to switch to imperative mode firstly. Because received 'x' in cast is a imperative Variable.
请问我要怎么解决？模型文件已随附件上传
[best_epoch_67.pd.zip](https://github.com/PaddlePaddle/Paddle/files/14325375/best_epoch_67.pd.zip)

**Comment by lhou705** [comment]
其他信息：
paddlepaddle2.6
cuda 12.0
cudnn 8.9

**Comment by DesmonDay** [comment]
"AssertionError: Variable dtype not match, Variable [ batch_norm2d_0.w_0 ] need tensor with dtype paddle.float32 but load tensor with dtype paddle.float16" 这块地方的意思应该是本来 batch_norm 这块需要的是 fp32类型的 tensor，但是你传入了 fp16类型，所以导致不对。有个办法是你能不能修改 state_dict，把这个 tensor 换成 fp32的看看？

**Comment by DesmonDay** [comment]
你的训练脚本中，在 batch_norm api前是否有设置  auto_cast = False？可以把相关代码截图看看么？

**Comment by DesmonDay** [comment]
另外相关问题也可以在 https://github.com/zkyseu/PPlanedet 的 repo 中提问，应该有更详细的解答。

**Comment by lhou705** [comment]
> 你的训练脚本中，在 batch_norm api前是否有设置 auto_cast = False？可以把相关代码截图看看么？
没有在 batch_norm api前设置 auto_cast = False
和amp相关的训练脚本如下
```python
if self.use_amp:
    with paddle.amp.auto_cast(**self.auto_cast):
        self.outputs = self.model(data)
         loss = self.outputs['loss']
         scaled_loss = self.scaler.scale(loss)
         scaled_loss.backward()
         self.scaler.minimize(self.optimizer, scaled_loss)
```
另外，再尝试将amp模型的保存类型修改为float32后，可以成功导出onnx模型了。

**Comment by DesmonDay** [comment]
嗯嗯，batch_norm并没有完全支持半精度计算，可能是由于这个原因。

**Comment by lhou705** [comment]
问题解决了。
首先，导出模型时，`model`不能使用`paddle.amp.decorate`装饰。
其次，如果导出的模型使用`float16`保存，那么加载权重时必须使用`model.float16()`将模型转换为半精度类型。
最后（存疑），导出模型时的`input_spec`的类型设置为`float16`。
`input_spec = [paddle.static.InputSpec(shape=shape, dtype='float16', name="image")]`
感谢您的帮助。

**Comment by lhou705** [comment]
问题解决了。问题产生的原因主要有这么几个。
1. 导出模型时，模型被`paddle.amp.decorate`装饰了，导致在使用paddle.jit.save时，报错。
2. paddle2onnx不支持将fp16的模型转换成onnx模型。https://github.com/PaddlePaddle/Paddle2ONNX/blob/e8e2a4a37b9d47dae9c423235090e6c294dcc04d/paddle2onnx/parser/parser.cc#L817
3. 模型的数据类型与权重类型不一致。
解决方案也很简单
1. 在导出模型时，不要使用`paddle.amp.decorate`装饰模型。
2. 如果是使用的fp16保存的模型，先将模型转换为fp16加载权重，再将模型转换成fp32进行导出。值得注意的是paddle.jit.save支持导出fp16的模型。
加载权重和导出模型的代码如下
```python
    def load(self, weight_path):
        state_dict = paddle.load(weight_path)
        if 'state_dict' in state_dict:
            state_dict = state_dict['state_dict']
        **if self.use_amp:
            self.model.float16()**
        self.model.set_state_dict(state_dict)

    def export(self, checkpoint_path):
        self.load(checkpoint_path)
        self.logger.info(f'finish loading model from {checkpoint_path}....')
        save_path = self.output_dir
        self.model.eval()
        shape = [1, 3, self.cfg.img_width, self.cfg.img_height]
        input_spec = [paddle.static.InputSpec(shape=shape, dtype='float32', name="image")]
        paddle.jit.save(self.model, os.path.join(save_path, 'model'), input_spec=input_spec)
        **if self.use_amp:
            self.model.float()**
        paddle.onnx.export(self.model,
                           os.path.join(save_path, 'model'),
                           input_spec=input_spec,
                           opset_version=16,
                           enable_onnx_checker=True,
                           export_fp16_model=True,
                           auto_upgrade_opset=True)
        self.logger.info(f'Successfully export model to {save_path}')
```
最后希望可以支持将fp16模型导出成onnx。感谢支持

**Comment by Zheng-Bicheng** [comment]
> 问题解决了。问题产生的原因主要有这么几个。
> 
> 1. 导出模型时，模型被`paddle.amp.decorate`装饰了，导致在使用paddle.jit.save时，报错。
> 2. paddle2onnx不支持将fp16的模型转换成onnx模型。https://github.com/PaddlePaddle/Paddle2ONNX/blob/e8e2a4a37b9d47dae9c423235090e6c294dcc04d/paddle2onnx/parser/parser.cc#L817
> 3. 模型的数据类型与权重类型不一致。
>    解决方案也很简单
> 4. 在导出模型时，不要使用`paddle.amp.decorate`装饰模型。
> 5. 如果是使用的fp16保存的模型，先将模型转换为fp16加载权重，再将模型转换成fp32进行导出。值得注意的是paddle.jit.save支持导出fp16的模型。
>    加载权重和导出模型的代码如下
> 
> ```python
>     def load(self, weight_path):
>         state_dict = paddle.load(weight_path)
>         if 'state_dict' in state_dict:
>             state_dict = state_dict['state_dict']
>         **if self.use_amp:
>             self.model.float16()**
>         self.model.set_state_dict(state_dict)
> 
>     def export(self, checkpoint_path):
>         self.load(checkpoint_path)
>         self.logger.info(f'finish loading model from {checkpoint_path}....')
>         save_path = self.output_dir
>         self.model.eval()
>         shape = [1, 3, self.cfg.img_width, self.cfg.img_height]
>         input_spec = [paddle.static.InputSpec(shape=shape, dtype='float32', name="image")]
>         paddle.jit.save(self.model, os.path.join(save_path, 'model'), input_spec=input_spec)
>         **if self.use_amp:
>             self.model.float()**
>         paddle.onnx.export(self.model,
>                            os.path.join(save_path, 'model'),
>                            input_spec=input_spec,
>                            opset_version=16,
>                            enable_onnx_checker=True,
>                            export_fp16_model=True,
>                            auto_upgrade_opset=True)
>         self.logger.info(f'Successfully export model to {save_path}')
> ```
> 
> 最后希望可以支持将fp16模型导出成onnx。感谢支持

你好，关于无法导出成ONNX的问题，移步Paddle2ONNX的[Issues](https://github.com/PaddlePaddle/Paddle2ONNX/issues)讨论哈，麻烦附带上你的模型。
