### ISSUE TITLE
Ubuntu17.04安装之后初始化报错

### ISSUE THREAD

**Issue by flyyuan** [PaddlePaddle/Paddle#6185]
/usr/bin/python2 /home/bennyshi/PycharmProjects/PaddleForMovie/main.py
Traceback (most recent call last):
  File "/home/bennyshi/PycharmProjects/PaddleForMovie/main.py", line 4, in <module>
    paddle.init(use_gpu=False, trainer_count=1)
  File "/home/bennyshi/.local/lib/python2.7/site-packages/paddle/v2/__init__.py", line 133, in init
    set_omp_mkl_env_vars(kwargs.get('trainer_count', 1))
  File "/home/bennyshi/.local/lib/python2.7/site-packages/paddle/v2/__init__.py", line 105, in set_omp_mkl_env_vars
    num_cores = num_physical_cores()
  File "/home/bennyshi/.local/lib/python2.7/site-packages/paddle/v2/__init__.py", line 90, in num_physical_cores
    "lscpu |grep \"per socket\" |awk -F':' '{print $2}'|xargs")
ValueError: invalid literal for int() with base 10: ''

Process finished with exit code 1

**Comment by flyyuan** [comment]
lscpu |grep \"per socket\" |awk -F':' '{print $2}'|xargs
grep: socket": 没有那个文件或目录
这个命令获取不到信息，导致报错。希望开发组可以加个判断

**Comment by flyyuan** [comment]
解决办法是把Ubuntu的语言修改为英文，因为中文的时候，命令匹配不到per socket。
