### ISSUE TITLE
编译Paddle或者pip安装，run_check时都报错：CUBLAS error(7)

### ISSUE THREAD

**Issue by terrencew** [PaddlePaddle/Paddle#61913]
### 问题描述 Issue Description

尝试按照官方文档pip安装或者自己编译，版本尝试过2.5.2 2.6.0，CUDA版本11.3，CUDNN版本尝试过8.9.2/8.2.1，安装都没问题，但是运行就报错

### 版本&环境信息 Version & Environment Information

Paddle版本：2.5.2 2.6.0
环境信息：（如下是自编译版本下打印的信息，Paddle Version显示0.0.0）
Paddle version: 0.0.0
Paddle With CUDA: True

OS: ubuntu 18.04
GCC version: (GCC) 8.2.0
Clang version: N/A
CMake version: version 3.18.0
Libc version: glibc 2.27
Python version: 3.10.13

CUDA version: 11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
cuDNN version: N/A
Nvidia driver version: 465.19.01
Nvidia driver List:
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX 1080 Ti
GPU 3: NVIDIA GeForce GTX 1080 Ti

CUDA版本: 11.3
CUDNN版本：8.2.1 / 8.9.2
报错信息如下：
import paddle
paddle.>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
I0221 14:54:20.458738 12853 program_interpreter.cc:212] New Executor is Running.
W0221 14:54:20.459381 12853 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.3, Runtime API Version: 11.3
W0221 14:54:20.580924 12853 gpu_resources.cc:164] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/utils/install_check.py", line 273, in run_check
    _run_static_single(use_cuda, use_xpu, use_custom, custom_device_name)
  File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/utils/install_check.py", line 151, in _run_static_single
    exe.run(
  File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/base/executor.py", line 1741, in run
    res = self._run_impl(
  File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/base/executor.py", line 1947, in _run_impl
    ret = new_exe.run(
  File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/base/executor.py", line 826, in run
    tensors = self._new_exe.run(
OSError: In user code:

    File "<stdin>", line 1, in <module>

    File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/utils/install_check.py", line 273, in run_check
      _run_static_single(use_cuda, use_xpu, use_custom, custom_device_name)
    File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/utils/install_check.py", line 135, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/utils/install_check.py", line 37, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/nn/functional/common.py", line 1985, in linear
      helper.append_op(
    File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/base/layer_helper.py", line 49, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/base/framework.py", line 4467, in append_op
      op = Operator(
    File "/home/wx/anaconda3/envs/paddle/lib/python3.10/site-packages/paddle/base/framework.py", line 3016, in __init__
      for frame in traceback.extract_stack():

    ExternalError: CUBLAS error(7).
      [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /home/wx/projects/paddle/Paddle/paddle/phi/backends/gpu/gpu_context.cc:599)
      [operator < matmul_v2 > error]
>>>

**Comment by terrencew** [comment]
已经在issues中搜索过类似问题，但都不能解决本issue问题

**Comment by terrencew** [comment]
CMake编译指令：
cmake .. \
        -DPYTHON_EXECUTABLE:FILEPATH=/home/wx/anaconda3/envs/paddle/bin/python3 \
        -DPYTHON_INCLUDE_DIR:PATH=/home/wx/anaconda3/envs/paddle/include/python3.10 \
        -DPYTHON_LIBRARY:FILEPATH=/home/wx/anaconda3/envs/paddle/lib/ \
        -DWITH_MKL=OFF -DWITH_MKLDNN=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DON_INFER=ON -DWITH_LITE=ON -DWITH_GPU=ON

**Comment by terrencew** [comment]
Anyone There?

**Comment by zyfncg** [comment]
@risemeup1 帮忙看下这个问题是否和gpu型号以及软件版本有关？

**Comment by zyfncg** [comment]
@terrencew 有试过用docker镜像吗？

**Comment by terrencew** [comment]
> @terrencew 有试过用docker镜像吗？

没用过。我在另外一台2080机器上，用pip install，同样配置，2.6.0安装成功了。因此应该是和1080机器型号、软件配置相关

**Comment by zyfncg** [comment]
好的，1080的显卡可能得试试低版本的驱动和相关软件

**Comment by risemeup1** [comment]
检查CUDA版本：确保你的CUDA版本与你使用的PaddlePaddle版本兼容。你可能需要安装不同的PaddlePaddle或CUDA版本。看样子你的CUDA是CUDA11.3，我们提供的包好像没有cuda11.3的

更新驱动程序：更新到最新版的GPU驱动程序可能能解决你的问题。

**Comment by risemeup1** [comment]
> > @terrencew 有试过用docker镜像吗？
> 
> 没用过。我在另外一台2080机器上，用pip install，同样配置，2.6.0安装成功了。因此应该是和1080机器型号、软件配置相关

我们是支持1080机型的，61架构是支持的，应该还是本地的环境问题，建议用docker把

**Comment by terrencew** [comment]
谢谢，我试试docker
