### ISSUE TITLE
need to build `paddle_python` before generating docs for Fluid

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#6224]
Some python file in fluid package import core.so. And core.so depends on paddle_python. We should build paddle_python first before generating docs for Fluid. It's quite time consuming. We need to find a way reduce the time.

**Comment by luotao1** [comment]
http://www.paddlepaddle.org/docs/develop/documentation/en/api/v2/fluid/layers.html can't display successfully.

**Comment by luotao1** [comment]
when `make clean`, and `make paddle_docs`, the error is 
```
/home/luotao02/Paddle/doc/api/v2/fluid/optimizer.rst:22: WARNING: autodoc: failed to import module u'paddle.v2.fluid.optimizer'; the following exception was raised:
Traceback (most recent call last):
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
  File "/home/luotao02/Paddle/python/paddle/v2/fluid/__init__.py", line 2, in <module>
    import framework
  File "/home/luotao02/Paddle/python/paddle/v2/fluid/framework.py", line 4, in <module>
    from . import core
ImportError: cannot import name core
```
