### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'run_server'

### ISSUE THREAD

**Issue by aturbofly** [PaddlePaddle/Paddle#62267]
### 请提出你的问题 Please ask your question

paddle2.3 编译安装采用-DWITH_DISTRIBUTE=ON

执行fleet.run_server() 的时候报如下错误：
  File "/home/work/ctr-model//common/python3.8/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/work/ctr-model//common/python3.8/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/work/ctr-model//common/python3.8/lib/python3.8/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 130, in __impl__
    return func(*args, **kwargs)
  File "/home/work/ctr-model/common/python3.8/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/work//ctr-model/common/python3.8/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/work//ctr-model/common/python3.8/lib/python3.8/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 114, in __impl__
    return func(*args, **kwargs)
  File "/home/work//ctr-model/common/python3.8/lib/python3.8/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 714, in run_server
    self._runtime_handle._run_server()
  File "/home/work//ctr-model/common/python3.8/lib/python3.8/site-packages/paddle/distributed/ps/the_one_ps.py", line 1095, in _run_server
    self._server.run_server(host, int(port))
AttributeError: 'NoneType' object has no attribute 'run_server'

这个是不是编译少加了什么参数的原因？-DWITH_PSLIB=ON 这些？

**Comment by danleifeng** [comment]
-DWITH_PSCORE=ON有开吗，按理说DWITH_DISTRIBUTE=ON默认WITH_PSCORE也是为ON的

**Comment by aturbofly** [comment]
@danleifeng 『-DWITH_PSCORE=ON』这个没有加。在run_server() 前需要自己执行下init_server()么？

不过执行后出现：
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::distributed::FleetWrapper::InitServer(std::string const&, std::vector<std::string, std::allocator<std::string> > const&, int, int, std::vector<paddle::framework::ProgramDesc, std::allocator<paddle::framework::ProgramDesc> > const&)
1   paddle::distributed::PSCore::InitServer(std::string const&, std::vector<std::string, std::allocator<std::string> > const*, int, int, int, std::vector<paddle::framework::ProgramDesc, std::allocator<paddle::framework::ProgramDesc> > const&)
2   paddle::distributed::PSServer::Configure(paddle::distributed::PSParameter const&, paddle::distributed::PSEnvironment&, unsigned long, std::vector<paddle::framework::ProgramDesc, std::allocator<paddle::framework::ProgramDesc> > const&)
3   paddle::distributed::Table::Initialize(paddle::distributed::TableParameter const&, paddle::distributed::FsClientParameter const&)
4   paddle::distributed::MemoryDenseTable::Initialize()
5   paddle::distributed::MemoryDenseTable::InitializeValue()
6   paddle::distributed::MemoryDenseTable::CreateInitializer(std::string const&, std::string const&)
FatalError: `Segmentation fault` is detected by the operating system。
