### ISSUE TITLE
take_along_axis广播行为与NumPy不一致 take_along_axis inconsistent broadcasting behavior with NumPy

### ISSUE THREAD

**Issue by fty1777** [PaddlePaddle/Paddle#62574]
### bug描述 Describe the Bug

bug描述 Describe the Bug

当`indices`需要广播时，`paddle.take_along_axis`会报错，而该情况在NumPy中是合法的。

`paddle.take_along_axis` raises an error in the following case where the `indices` needs to be broadcasted, which is valid and works as intended in NumPy.

```python
# 最小可复现代码。 Sample code to reproduce the problem.

import numpy as np
import paddle


print(
    np.take_along_axis(np.arange(9).reshape(3, 3), np.zeros([5, 1], np.int32), axis=0)
)
print("=" * 100)
print(
    paddle.take_along_axis(
        paddle.arange(9).reshape([3, 3]), paddle.zeros([5, 1]).to("int32"), axis=0
    )
)

```

```shell
aistudio@jupyter-563090-7541750:~$ cat test.py
# 最小可复现代码。 Sample code to reproduce the problem.

import numpy as np
import paddle


print(
    np.take_along_axis(np.arange(9).reshape(3, 3), np.zeros([5, 1], np.int32), axis=0)
)
print("=" * 100)
print(
    paddle.take_along_axis(
        paddle.arange(9).reshape([3, 3]), paddle.zeros([5, 1]).to("int32"), axis=0
    )
)
aistudio@jupyter-563090-7541750:~$ python test.py
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
====================================================================================================
Traceback (most recent call last):
  File "/home/aistudio/test.py", line 12, in <module>
    paddle.take_along_axis(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/tensor/manipulation.py", line 5247, in take_along_axis
    arr = paddle.broadcast_to(arr, broadcast_shape)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/tensor/manipulation.py", line 3627, in broadcast_to
    return _C_ops.expand(x, shape)
ValueError: (InvalidArgument) The value (3) of the non-singleton dimension does not match the corresponding value (1) in shape for expand_v2 op.
  [Hint: Expected vec_in_dims[i] == expand_shape[i], but received vec_in_dims[i]:3 != expand_shape[i]:1.] (at /paddle/paddle/phi/kernels/impl/expand_kernel_impl.h:65)

aistudio@jupyter-563090-7541750:~$ 
```

### 其他补充信息 Additional Supplementary Information

在Paddle BML CodeLab中复现。
Reproduced in a Paddle BML CodeLab project.

**Comment by zhangting2020** [comment]
感谢反馈，后续我们会进行需求评估
