### ISSUE TITLE
按照paddlehub之后，在导入这个模块的时候出现错误。module 'paddle' has no attribute 'fluid'. Did you mean: 'flip'?

### ISSUE THREAD

**Issue by xiaowang-xuexiji** [PaddlePaddle/Paddle#62738]
### bug描述 Describe the Bug

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/paddlehub/__init__.py", line 35, in <module>
    from paddlehub.utils.paddlex import download, ResourceNotFoundError
  File "/usr/local/lib/python3.10/dist-packages/paddlehub/utils/paddlex.py", line 19, in <module>
    from paddlehub.server.server import module_server, CacheUpdater
  File "/usr/local/lib/python3.10/dist-packages/paddlehub/server/__init__.py", line 17, in <module>
    from paddlehub.server.git_source import GitSource
  File "/usr/local/lib/python3.10/dist-packages/paddlehub/server/git_source.py", line 24, in <module>
    from paddlehub.module.module import RunModule
  File "/usr/local/lib/python3.10/dist-packages/paddlehub/module/__init__.py", line 16, in <module>
    from .module import Module
  File "/usr/local/lib/python3.10/dist-packages/paddlehub/module/module.py", line 30, in <module>
    from paddlehub.compat import paddle_utils
  File "/usr/local/lib/python3.10/dist-packages/paddlehub/compat/paddle_utils.py", line 25, in <module>
    paddle.fluid.core.VarDesc.VarType.FP32: "float32",
AttributeError: module 'paddle' has no attribute 'fluid'. Did you mean: 'flip'?

**Comment by winter-wang** [comment]
你好，从飞桨框架 2.5 版本开始，我们已经废弃了 paddle.fluid namespace 下的 API，请使用其他的替代 API。
见
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/Overview_cn.html

**Comment by xiaowang-xuexiji** [comment]
那我要使用paddlehub的话应该安装哪个版本比较合适 paddle版本为2.6.0的情况下

**Comment by winter-wang** [comment]
paddlehub仓库似乎有一段时间没更新了，不确定是否适配了框架2.5以上版本。这个需要你去paddlehub的仓库issue去问一下。

**Comment by xiaofeifei-1** [comment]
> paddlehub仓库似乎有一段时间没更新了，不确定是否适配了框架2.5以上版本。这个需要你去paddlehub的仓库issue去问一下。

不用随意更新API的名称，没有延续性，我也遇到这个问题了，我的版本是2.6
