### ISSUE TITLE
python: symbol lookup error: /opt/conda/envs/py38/lib/python3.8/site-packages/paddle_custom_device/libpaddle-custom-cpu.so: undefined symbol: PD_RegisterPhiKernel

### ISSUE THREAD

**Issue by hanhaowen-mt** [PaddlePaddle/Paddle#62848]
### 请提出你的问题 Please ask your question

尝试跑通Custom device的demo(  https://github.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/custom_cpu 
 )，
首先通过源码安装paddlepaddle:
git clone paddlepaddle（commit id =20a00cf） && mkdir build && cmake .. -DPY_VERSION=3.8 -DWITH_TESTING=OFF -DWITH_MKL=ON -DWITH_GPU=OFF -DON_INFER=ON -DWITH_CUSTOM_DEVICE=ON && make && pip install xxx.whl

然后安装该demo:
cd backends/custom_cpu
设置WITH_TESTING为OFF
mkdir build && cd build
cmake ..
make -j8
pip install dist/paddle_custom_cpu*.whl

执行验证代码python -c "import paddle; print(paddle.device.get_all_custom_device_type())"，报错:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/paddle/__init__.py", line 30, in <module>
    from .base import core  # noqa: F401
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/paddle/base/__init__.py", line 38, in <module>
    from . import (  # noqa: F401
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/paddle/base/backward.py", line 25, in <module>
    from . import core, framework, log_helper, unique_name
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/paddle/base/core.py", line 268, in <module>
    if platform.system().lower() == 'linux':
  File "/opt/conda/envs/py38/lib/python3.8/platform.py", line 897, in system
    return uname().system
  File "/opt/conda/envs/py38/lib/python3.8/platform.py", line 863, in uname
    processor = _syscmd_uname('-p', '')
  File "/opt/conda/envs/py38/lib/python3.8/platform.py", line 617, in _syscmd_uname
    import subprocess
  File "/opt/conda/envs/py38/lib/python3.8/subprocess.py", line 49, in <module>
    import signal
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/paddle/signal.py", line 16, in <module>
    from paddle import _C_ops
  File "/opt/conda/envs/py38/lib/python3.8/site-packages/paddle/_C_ops.py", line 20, in <module>
    for name in dir(core.eager.ops):
AttributeError: partially initialized module 'paddle.base.core' has no attribute 'eager' (most likely due to a circular import)
```

但是如果通过pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/linux/cpu-mkl/develop.html  来安装paddle，然后再用相同的方法来安装custom device，则没有问题。

**Comment by hanhaowen-mt** [comment]
另外我注意到custom device里面好几个backends的readme.md都提到通过 pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/linux/cpu-mkl/develop.html 来安装paddlepaddle，请问一下这个安装的是什么版本的paddle，对应的commit id是多少？

**Comment by hanhaowen-mt** [comment]
破案了，我之前用的是自己的docker，里面gcc版本是9.x，然后刚刚试了一下官方的docker，gcc版本是12，就ok了，看来是gcc版本问题。
