### ISSUE TITLE
docker image paddlepaddle/paddle does not work

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#6309]
```bash
➜  ~ docker pull paddlepaddle/paddle
Using default tag: latest
latest: Pulling from paddlepaddle/paddle
Digest: sha256:85d238e657416ecfb728f29e80e33848eeff199d6c3b9da881af3aa80aeeeb3c
Status: Image is up to date for paddlepaddle/paddle:latest
➜  ~ docker run -v `pwd`:/data paddlepaddle/paddle python /data/test_recognize_digits_conv.py                
Traceback (most recent call last):
  File "/data/test_recognize_digits_conv.py", line 4, in <module>
    import paddle.v2.fluid as fluid
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/__init__.py", line 2, in <module>
    import framework
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/framework.py", line 4, in <module>
    from . import core
ImportError: libcblas.so: cannot open shared object file: No such file or directory
```

**Comment by Yancey1989** [comment]
I think we need to package the `libcblas.so` into whl package, and I will fix this.
```bash
root@1485c7ac07dd:/# ldd /usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/core.so
	linux-vdso.so.1 =>  (0x00007ffd70d9e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fcad69c5000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007fcad6436000)
	libcblas.so => not found
	libmklml_intel.so => /usr/local/lib/libmklml_intel.so (0x00007fcacd5f3000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fcacd270000)
...
```
