### ISSUE TITLE
动静转换，执行异常

### ISSUE THREAD

**Issue by wang-qa** [PaddlePaddle/Paddle#63143]
### bug描述 Describe the Bug

# 环境
使用官网示例https://www.paddlepaddle.org.cn/tutorials/projectdetail/3714002
Python 3.11.2
paddlepaddle                 2.6.1 （CPU）

## 实际：如下

- jupyter notebook

    ```bash 
    epoch_id: 9, batch_id: 1000, loss is: 0.16181564331054688
    epoch_id: 9, batch_id: 2000, loss is: 0.5946303009986877
    epoch_id: 9, batch_id: 3000, loss is: 0.09839227795600891
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    Cell In[1], line 93
         89 # 保存模型结构的*.pdmodel文件
         90 # 保存推理用参数的*.pdiparams文件
         91 # 保存兼容变量信息的*.pdiparams.info文件
         92 paddle.save(model.state_dict(), './mnist.pdparams')
    ---> 93 paddle.jit.save(model, 'runs/mnist_experiment111/model', [paddle.static.InputSpec([-1, 1, 28, 28])])
         95 # print("==>Trained model saved in ./mnist.pdparams")
         96 print("==>保存已训练的模型 ./mnist.pdparams")
    
    File ~/.local/lib/python3.11/site-packages/decorator.py:232, in decorate.<locals>.fun(*args, **kw)
        230 if not kwsyntax:
        231     args, kw = fix(args, kw, sig)
    --> 232 return caller(func, *(extras + args), **kw)
    
    File ~/.local/lib/python3.11/site-packages/paddle/base/wrapped_decorator.py:26, in wrap_decorator.<locals>.__impl__(func, *args, **kwargs)
         23 @decorator.decorator
         24 def __impl__(func, *args, **kwargs):
         25     wrapped_func = decorator_func(func)
    ---> 26     return wrapped_func(*args, **kwargs)
    
    File ~/.local/lib/python3.11/site-packages/paddle/jit/api.py:809, in _run_save_pre_hooks.<locals>.wrapper(layer, path, input_spec, **configs)
        807 for hook in _save_pre_hooks:
        808     hook(layer, input_spec, configs)
    --> 809 func(layer, path, input_spec, **configs)
    
    File ~/.local/lib/python3.11/site-packages/decorator.py:232, in decorate.<locals>.fun(*args, **kw)
        230 if not kwsyntax:
        231     args, kw = fix(args, kw, sig)
    --> 232 return caller(func, *(extras + args), **kw)
    
    File ~/.local/lib/python3.11/site-packages/paddle/base/wrapped_decorator.py:26, in wrap_decorator.<locals>.__impl__(func, *args, **kwargs)
         23 @decorator.decorator
         24 def __impl__(func, *args, **kwargs):
         25     wrapped_func = decorator_func(func)
    ---> 26     return wrapped_func(*args, **kwargs)
    
    File ~/.local/lib/python3.11/site-packages/paddle/base/dygraph/base.py:68, in _switch_to_static_graph_.<locals>.__impl__(*args, **kwargs)
         66 def __impl__(*args, **kwargs):
         67     with framework._dygraph_guard(None):
    ---> 68         return func(*args, **kwargs)
    
    File ~/.local/lib/python3.11/site-packages/paddle/jit/api.py:1104, in save(layer, path, input_spec, **configs)
       1095         property_vals.append(
       1096             (
       1097                 immediate_val,
       1098                 layer.__class__.__name__ + '.' + attr_func,
       1099             )
       1100         )
       1101         continue
       1103     concrete_program = (
    -> 1104         static_func.concrete_program_specify_input_spec(
       1105             inner_input_spec,
       1106             with_hook=with_hook,
       1107             is_prim_infer=is_prim_infer,
       1108         )
       1109     )
       1110 elif 'forward' == attr_func:
       1111     if configs.skip_forward:
       1112         # do not jit.save forward function
    
    File ~/.local/lib/python3.11/site-packages/paddle/jit/dy2static/program_translator.py:969, in ASTStaticFunction.concrete_program_specify_input_spec(self, input_spec, with_hook, is_prim_infer)
        965 if self._function_spec.input_spec is not None:
        966     if input_spec is not None and not input_specs_compatible(
        967         flatten(input_spec), flatten(self._function_spec.input_spec)
        968     ):
    --> 969         raise ValueError(
        970             "The `input_spec`: {} used to construct concrete_program is conflict with the `input_spec`: {} in `@paddle.jit.to_static`".format(
        971                 input_spec, self._function_spec.input_spec
        972             )
        973         )
        974     # NOTE(chenweihang): we should always translated program based on the `input_spec`
        975     # decorated on forward if it is valid
        976     desired_input_spec = self._function_spec.input_spec
    
    ValueError: The `input_spec`: [InputSpec(shape=(-1, 1, 28, 28), dtype=paddle.float32, name=None, stop_gradient=False)] used to construct concrete_program is conflict with the `input_spec`: (InputSpec(shape=(16, 784), dtype=paddle.float32, name=_jst.0.inputs.0, stop_gradient=True),) in `@paddle.jit.to_static`
    
    ```

- pycharm debug

    ```bash
    已连接到 pydev 调试器(内部版本号 233.15026.15)Running verify PaddlePaddle program ... 
    I0401 11:26:15.668777 79940 program_interpreter.cc:212] New Executor is Running.
    I0401 11:26:15.681203 79940 interpreter_util.cc:624] Standalone Executor is Used.
    PaddlePaddle works well on 1 CPU.
    PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
    epoch_id: 0, batch_id: 0, loss is: 2.5776257514953613
    ...
    epoch_id: 9, batch_id: 1000, loss is: 0.6793664693832397
    epoch_id: 9, batch_id: 2000, loss is: 0.5109764933586121
    epoch_id: 9, batch_id: 3000, loss is: 0.24961122870445251
    Traceback (most recent call last):
      File "/home/$HOME/.local/lib/python3.11/site-packages/paddle/base/dygraph/base.py", line 68, in __impl__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/$HOME/.local/lib/python3.11/site-packages/paddle/jit/api.py", line 1104, in save
        static_func.concrete_program_specify_input_spec(
      File "/home/$HOME/.local/lib/python3.11/site-packages/paddle/jit/dy2static/program_translator.py", line 969, in concrete_program_specify_input_spec
        raise ValueError(
    ValueError: The `input_spec`: [InputSpec(shape=(-1, 1, 28, 28), dtype=paddle.float32, name=None, stop_gradient=False)] used to construct concrete_program is conflict with the `input_spec`: (InputSpec(shape=(16, 784), dtype=paddle.float32, name=_jst.0.inputs.0, stop_gradient=True),) in `@paddle.jit.to_static`
    python-BaseException
    
    ```

- pc-A终端执行、pycharm 执行

    ```bash
    Running verify PaddlePaddle program ... 
    I0401 10:57:32.984786 39528 program_interpreter.cc:212] New Executor is Running.
    I0401 10:57:33.374326 39528 interpreter_util.cc:624] Standalone Executor is Used.
    PaddlePaddle works well on 1 CPU.
    PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
    
    
    --------------------------------------
    C++ Traceback (most recent call last):
    --------------------------------------
    0   inflateReset2
    
    ----------------------
    Error Message Summary:
    ----------------------
    FatalError: `Segmentation fault` is detected by the operating system.
      [TimeInfo: *** Aborted at 1711940253 (unix time) try "date -d @1711940253" if you are using GNU date ***]
      [SignalInfo: *** SIGSEGV (@0x0) received by PID 39528 (TID 0x7f9db923e000) from PID 0 ***]
    
    
    进程已结束，退出代码为 139 (interrupted by signal 11:SIGSEGV)
    
    ```

- pc-B终端执行  (正常) paddle==2.4.2

    ```bash
    /home/$HOME/.conda/envs/test3.10/bin/python /home/$HOME/git/study_mode/study_unit_03/study_09_动静部署.py 
    /home/$HOME/.conda/envs/test3.10/lib/python3.10/site-packages/setuptools/sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      import pkg_resources
    /home/$HOME/.conda/envs/test3.10/lib/python3.10/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
    Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
      declare_namespace(pkg)
    Running verify PaddlePaddle program ... 
    PaddlePaddle works well on 1 CPU.
    PaddlePaddle works well on 2 CPUs.
    PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
    /home/$HOME/.conda/envs/test3.10/lib/python3.10/site-packages/paddle/fluid/executor.py:1583: UserWarning: Standalone executor is not used for data parallel
      warnings.warn(
    W0401 11:31:19.966423 1631880 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
    <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
    epoch_id: 0, batch_id: 0, loss is: [2.849697]
    epoch_id: 0, batch_id: 1000, loss is: [0.789385]
    epoch_id: 0, batch_id: 2000, loss is: [0.5124418]
    ...
    epoch_id: 9, batch_id: 2000, loss is: [0.15551275]
    epoch_id: 9, batch_id: 3000, loss is: [0.5546097]
    /home/$HOME/.conda/envs/test3.10/lib/python3.10/site-packages/paddle/fluid/dygraph/jit.py:453: UserWarning: The InputSpec(shape=(-1, 1, 28, 28), dtype=paddle.float32, name=None)'s name is None. When using jit.save, please set InputSepc's name in to_static(input_spec=[]) and jit.save(input_spec=[]) and make sure they are consistent.
      warnings.warn(name_none_error % spec)
    /home/$HOME/.conda/envs/test3.10/lib/python3.10/site-packages/paddle/fluid/dygraph/jit.py:453: UserWarning: The InputSpec(shape=(-1, 784), dtype=paddle.float32, name=None)'s name is None. When using jit.save, please set InputSepc's name in to_static(input_spec=[]) and jit.save(input_spec=[]) and make sure they are consistent.
      warnings.warn(name_none_error % spec)
    ==>保存已训练的模型 ./mnist.pdparams
    ==>保存的推理模型 inference/mnist.
    
    进程已结束，退出代码为 0
    
    
    ```
    

## 执行文件

```python
#!/usr/bin/env python3
# -*- coding:utf-8 -*-

# @Description: 动态图转静态图模型保存
#!/usr/bin/env python3
# -*- coding:utf-8 -*-

# @Description: 动态图转静态图模型保存

##############################################################################
""" 定义网络结构 """
import paddle
# paddle.device.set_device('cpu')


paddle.utils.run_check()
# paddle.disable_signal_handler()



# 定义手写数字识别模型
import paddle


# 定义手写数字识别模型
class MNIST(paddle.nn.Layer):
    def __init__(self):
        super(MNIST, self).__init__()

        # 定义一层全连接层，输出维度是1
        self.fc = paddle.nn.Linear(in_features=784, out_features=10)

    # 定义网络结构的前向计算过程
    @paddle.jit.to_static  # 添加装饰器，使动态图网络结构在静态图模式下运行
    def forward(self, inputs):
        outputs = self.fc(inputs)
        return outputs

##############################################################################
""" 训练并保存 """
import paddle
import paddle.nn.functional as F

# 确保从paddle.vision.datasets.MNIST中加载的图像数据是np.ndarray类型
paddle.vision.set_image_backend('cv2')


# 图像归一化函数，将数据范围为[0, 255]的图像归一化到[-1, 1]
def norm_img(img):
    batch_size = img.shape[0]
    # 归一化图像数据
    img = img / 127.5 - 1
    # 将图像形式reshape为[batch_size, 784]
    img = paddle.reshape(img, [batch_size, 784])

    return img


def train(model):
    model.train()
    # 加载训练集 batch_size 设为 16
    train_loader = paddle.io.DataLoader(paddle.vision.datasets.MNIST(mode='train'),
                                        batch_size=16,
                                        shuffle=True)
    opt = paddle.optimizer.SGD(learning_rate=0.001, parameters=model.parameters())
    EPOCH_NUM = 10
    for epoch in range(EPOCH_NUM):
        for batch_id, data in enumerate(train_loader()):
            images = norm_img(data[0]).astype('float32')
            labels = data[1].astype('int64')

            # 前向计算的过程
            predicts = model(images)

            # 计算损失
            loss = F.cross_entropy(predicts, labels)
            avg_loss = paddle.mean(loss)

            # 每训练了1000批次的数据，打印下当前Loss的情况
            if batch_id % 1000 == 0:
                print("epoch_id: {}, batch_id: {}, loss is: {}".format(epoch, batch_id, avg_loss.numpy()))

            # 后向传播，更新参数的过程
            avg_loss.backward()
            opt.step()
            opt.clear_grad()


model = MNIST()

train(model)

paddle.save(model.state_dict(), './mnist.pdparams')
print("==>Trained model saved in ./mnist.pdparams")

##############################################################################
""" 部署调用 """
# save inference model
from paddle.static import InputSpec
# 加载训练好的模型参数
state_dict = paddle.load("./mnist.pdparams")
# 将训练好的参数读取到网络中
model.set_state_dict(state_dict)
# 设置模型为评估模式
model.eval()

# 保存inference模型
paddle.jit.save(
    layer=model,
    path="inference/mnist",
    input_spec=[InputSpec(shape=[None, 784], dtype='float32')])

print("==>Inference model saved in inference/mnist.")


import numpy as np
import paddle
import paddle.nn.functional as F
# 确保从paddle.vision.datasets.MNIST中加载的图像数据是np.ndarray类型
paddle.vision.set_image_backend('cv2')

# 读取mnist测试数据，获取第一个数据
mnist_test = paddle.vision.datasets.MNIST(mode='test')
test_image, label = mnist_test[0]
# 获取读取到的图像的数字标签
print("The label of readed image is : ", label)

# 将测试图像数据转换为tensor，并reshape为[1, 784]
test_image = paddle.reshape(paddle.to_tensor(test_image), [1, 784])
# 然后执行图像归一化
test_image = norm_img(test_image)
# 加载保存的模型
loaded_model = paddle.jit.load("./inference/mnist")
# 利用加载的模型执行预测
preds = loaded_model(test_image)
pred_label = paddle.argmax(preds)
# 打印预测结果
print("The predicted label is : ", pred_label.numpy())

```

```md
absl-py==2.1.0
anyio==4.3.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
astor==0.8.1
asttokens==2.4.1
astunparse==1.6.3
async-lru==2.0.4
attrs==23.2.0
Babel==2.14.0
beautifulsoup4==4.12.3
bleach==6.1.0
certifi==2024.2.2
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.2
comm==0.2.2
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
docutils==0.20.1
doxypypy==0.8.8.7
doxyqml==0.5.3
executing==2.0.1
fastjsonschema==2.19.1
flatbuffers==24.3.25
flit==3.9.0
flit_core==3.9.0
fqdn==1.5.1
gast==0.5.4
gi-docgen==2023.3
google-pasta==0.2.0
grpcio==1.62.1
h11==0.14.0
h5py==3.10.0
httpcore==1.0.5
httpx==0.27.0
idna==3.6
install==1.3.5
ipykernel==6.29.4
ipython==8.23.0
ipywidgets==8.1.2
isoduration==20.11.0
jedi==0.19.1
Jinja2==3.1.3
json5==0.9.24
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.4
jupyter_client==8.6.1
jupyter_core==5.7.2
jupyter_server==2.13.0
jupyter_server_terminals==0.5.3
jupyterlab==4.1.5
jupyterlab_pygments==0.3.0
jupyterlab_server==2.25.4
jupyterlab_widgets==3.0.10
kapidox==5.106.0
keras==3.1.1
libclang==18.1.1
lxml==5.1.1
Mako==1.3.2
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib-inline==0.1.6
mdurl==0.1.2
meson==1.4.0
mistune==3.0.2
ml-dtypes==0.3.2
namex==0.0.7
nbclient==0.10.0
nbconvert==7.16.3
nbformat==5.10.3
nest-asyncio==1.6.0
networkx==3.2.1
notebook==7.1.2
notebook_shim==0.2.4
numpy==1.26.4
opt-einsum==3.3.0
optree==0.11.0
overrides==7.7.0
packaging==24.0
paddlepaddle==2.6.1
pandocfilters==1.5.1
parso==0.8.3
pexpect==4.9.0
pillow==10.2.0
platformdirs==4.2.0
prometheus_client==0.20.0
prompt-toolkit==3.0.43
protobuf==4.25.3
psutil==5.9.8
ptyprocess==0.7.0
pure-eval==0.2.2
pycairo==1.26.0
pycparser==2.22
Pygments==2.17.2
PyGObject==3.48.1
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
PyYAML==6.0.1
pyzmq==25.1.2
qtconsole==5.5.1
QtPy==2.4.1
referencing==0.34.0
requests==2.31.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.1
rpds-py==0.18.0
Send2Trash==1.8.2
setools==4.5.0.dev0
six==1.16.0
smartypants==2.0.1
sniffio==1.3.1
soupsieve==2.5
stack-data==0.6.3
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tensorflow==2.16.1
tensorflow-io-gcs-filesystem==0.36.0
termcolor==2.4.0
terminado==0.18.1
tinycss2==1.2.1
tomli_w==1.0.0
tornado==6.4
traitlets==5.14.2
types-python-dateutil==2.9.0.20240316
typing_extensions==4.10.0
typogrify==2.0.7
ufw==0.36.1
uri-template==1.3.0
urllib3==2.2.1
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.7.0
Werkzeug==3.0.1
widgetsnbextension==4.0.10
wrapt==1.16.0
```

**Comment by SigureMo** [comment]
> paddle.jit.save(model, 'runs/mnist_experiment111/model', [paddle.static.InputSpec([-1, 1, 28, 28])])


输入不是 `[16, 784]` 吗？为什么这里使用 `[-1, 1, 28, 28]` 呢？使用 `[-1, 784]` 就可以了

**Comment by wang-qa** [comment]
> > paddle.jit.save(model, 'runs/mnist_experiment111/model', [paddle.static.InputSpec([-1, 1, 28, 28])])
> 
> 输入不是 `[16, 784]` 吗？为什么这里使用 `[-1, 1, 28, 28]` 呢？使用 `[-1, 784]` 就可以了

代码未做任何修改，直接用示例运行，就是这个错误

**Comment by SigureMo** [comment]
> 直接用示例运行

哪里的示例呢？官网吗？具体链接是？

**Comment by wang-qa** [comment]
> > 直接用示例运行
> 
> 哪里的示例呢？官网吗？具体链接是？
https://www.paddlepaddle.org.cn/tutorials/projectdetail/3991815

更正一下code
```python
#!/usr/bin/env python3
# -*- coding:utf-8 -*-

# @Description: 动态图转静态图模型保存

##############################################################################
""" 定义网络结构 """
import paddle
# paddle.device.set_device('cpu')


paddle.utils.run_check()
# paddle.disable_signal_handler()



# 定义手写数字识别模型
import paddle


# 定义手写数字识别模型
class MNIST(paddle.nn.Layer):
    def __init__(self):
        super(MNIST, self).__init__()

        # 定义一层全连接层，输出维度是1
        self.fc = paddle.nn.Linear(in_features=784, out_features=10)

    # 定义网络结构的前向计算过程
    @paddle.jit.to_static  # 添加装饰器，使动态图网络结构在静态图模式下运行
    def forward(self, inputs):
        outputs = self.fc(inputs)
        return outputs

##############################################################################
""" 训练并保存 """
import paddle
import paddle.nn.functional as F

# 确保从paddle.vision.datasets.MNIST中加载的图像数据是np.ndarray类型
paddle.vision.set_image_backend('cv2')


# 图像归一化函数，将数据范围为[0, 255]的图像归一化到[-1, 1]
def norm_img(img):
    batch_size = img.shape[0]
    # 归一化图像数据
    img = img / 127.5 - 1
    # 将图像形式reshape为[batch_size, 784]
    img = paddle.reshape(img, [batch_size, 784])

    return img


def train(model):
    model.train()
    # 加载训练集 batch_size 设为 16
    train_loader = paddle.io.DataLoader(paddle.vision.datasets.MNIST(mode='train'),
                                        batch_size=16,
                                        shuffle=True)
    opt = paddle.optimizer.SGD(learning_rate=0.001, parameters=model.parameters())
    EPOCH_NUM = 10
    for epoch in range(EPOCH_NUM):
        for batch_id, data in enumerate(train_loader()):
            images = norm_img(data[0]).astype('float32')
            labels = data[1].astype('int64')

            # 前向计算的过程
            predicts = model(images)

            # 计算损失
            loss = F.cross_entropy(predicts, labels)
            avg_loss = paddle.mean(loss)

            # 每训练了1000批次的数据，打印下当前Loss的情况
            if batch_id % 1000 == 0:
                print("epoch_id: {}, batch_id: {}, loss is: {}".format(epoch, batch_id, avg_loss.numpy()))

            # 后向传播，更新参数的过程
            avg_loss.backward()
            opt.step()
            opt.clear_grad()


model = MNIST()

train(model)

paddle.save(model.state_dict(), './mnist.pdparams')
print("==>Trained model saved in ./mnist.pdparams")

##############################################################################
""" 部署调用 """
# save inference model
from paddle.static import InputSpec
# 加载训练好的模型参数
state_dict = paddle.load("./mnist.pdparams")
# 将训练好的参数读取到网络中
model.set_state_dict(state_dict)
# 设置模型为评估模式
model.eval()

# 保存inference模型
paddle.jit.save(
    layer=model,
    path="inference/mnist",
    input_spec=[InputSpec(shape=[None, 784], dtype='float32')])

print("==>Inference model saved in inference/mnist.")


import numpy as np
import paddle
import paddle.nn.functional as F
# 确保从paddle.vision.datasets.MNIST中加载的图像数据是np.ndarray类型
paddle.vision.set_image_backend('cv2')

# 读取mnist测试数据，获取第一个数据
mnist_test = paddle.vision.datasets.MNIST(mode='test')
test_image, label = mnist_test[0]
# 获取读取到的图像的数字标签
print("The label of readed image is : ", label)

# 将测试图像数据转换为tensor，并reshape为[1, 784]
test_image = paddle.reshape(paddle.to_tensor(test_image), [1, 784])
# 然后执行图像归一化
test_image = norm_img(test_image)
# 加载保存的模型
loaded_model = paddle.jit.load("./inference/mnist")
# 利用加载的模型执行预测
preds = loaded_model(test_image)
pred_label = paddle.argmax(preds)
# 打印预测结果
print("The predicted label is : ", pred_label.numpy())
```

![image](https://github.com/PaddlePaddle/Paddle/assets/58168764/9d87420a-d69d-4d16-a2d3-18a41cbc36da)


debug run
![8629cd79-c1ad-46e5-aadd-738ae81d2522](https://github.com/PaddlePaddle/Paddle/assets/58168764/dcff5fd5-da15-4c08-812f-4df6e6a54a5f)

**Comment by SigureMo** [comment]
更新后的代码可以跑啊，无论 CPU 还是 GPU

**Comment by wang-qa** [comment]
> 更新后的代码可以跑啊，无论 CPU 还是 GPU

估计跟电脑有关
我是安装的cpu版本，debug可以跑，正常执行就报错

**Comment by zhwesky2010** [comment]
@wang-qa 你好，更新后的代码，我这边也是可以直接运行的，应该是你这边机器有问题或者之前代码有问题导致的。使用新的代码运行就可以。
![infoflow 2024-04-11 16-05-10](https://github.com/PaddlePaddle/Paddle/assets/52485244/72f45b76-3aa6-424b-8426-d7114d33c61a)
