### ISSUE TITLE
[CRITICAL] Duplicated layer name: word in layers.py:943

### ISSUE THREAD

**Issue by veridone** [PaddlePaddle/Paddle#6328]
just run example in http://www.paddlepaddle.org/docs/develop/book/06.understand_sentiment/index.cn.html
then errors is :

[CRITICAL 2017-12-06 11:42:46,416 layers.py:943] Duplicated layer name: word
Traceback (most recent call last):
  File "paddle_emo.py", line 186, in <module>
    out = convolution_net(dict_dim, class_dim=class_dim, is_predict=True)
  File "paddle_emo.py", line 13, in convolution_net
    paddle.data_type.integer_value_sequence(input_dim))
  File "/home/spider/.jumbo/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/home/spider/.jumbo/lib/python2.7/site-packages/paddle/v2/layer.py", line 88, in __data_layer__
    l = v1_layers.data_layer(name, type.dim, **kwargs)
  File "/home/spider/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 398, in wrapper
    return method(*args, **kwargs)
  File "/home/spider/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 943, in data_layer
    **ExtraLayerAttribute.to_kwargs(layer_attr))
  File "/home/spider/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3775, in Layer
    return layer_func(name, **xargs)
  File "/home/spider/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 1975, in __init__
    name, 'data', size, inputs=[], device=device)
  File "/home/spider/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 1556, in __init__
    'Duplicated layer name: %s' % name)
  File "/home/spider/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 156, in config_assert
    logger.fatal(msg)
  File "/home/spider/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 4125, in my_fatal
    raise Exception()
Exception

**Comment by jacquesqiao** [comment]
try this file https://github.com/PaddlePaddle/book/blob/develop/06.understand_sentiment/train.py

**Comment by veridone** [comment]
thanks a lot, Course of paddlepaddle.org is old
report a bug, not all linux machine is **S**ocket in v2/__init__.py:86
like
"
Core(s) per socket:    8
CPU **socket(s)**:     2
"

**Comment by luotao1** [comment]
@veridone Thanks for your report, this bug is fixed now:
https://github.com/PaddlePaddle/Paddle/blob/f3c42f607c91f7fe6c9c3b04151baab60e92c16c/python/paddle/v2/__init__.py#L84-L91
