### ISSUE TITLE
hadoop streaming报错： 

### ISSUE THREAD

**Issue by zhangqianjin** [PaddlePaddle/Paddle#6338]
写streaming时候，考虑到数据量比较大，调整了-D stream.memory.limit=10000 -D abaci.job.map.child.memory.mb=10000，可是报错了，这种情况应该调整那个参数解决，谢谢

java.io.IOException: [Hce child exception]StreamingProcess exit with errno 6
	at org.apache.hadoop.mapred.hce.Application.abort(Application.java:968)
	at org.apache.hadoop.mapred.hce.HcePipelineMapRunner.run(HcePipelineMapRunner.java:90)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:468)
	at com.baidu.inf.abaci.dag.slave.DAGAgent.doStartChild(DAGAgent.java:2125)
	at com.baidu.inf.abaci.dag.slave.DAGAgent.access$400(DAGAgent.java:82)
	at com.baidu.inf.abaci.dag.slave.DAGAgent$3.run(DAGAgent.java:1995)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readByte(DataInputStream.java:250)
	at org.apache.hadoop.io.WritableUtils.readVLong(WritableUtils.java:332)
	at org.apache.hadoop.io.WritableUtils.readVInt(WritableUtils.java:353)
	at org.apache.hadoop.mapred.hce.BinaryProtocol$UplinkReaderThread.run(BinaryProtocol.java:108)

-------
updated

**Comment by warnet2git** [comment]
请问这个问题怎么解决的呢？

**Comment by xiaonancs** [comment]
遇到了相同的错误
