### ISSUE TITLE
benchmark sentiment lstm script bug

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#6380]
```txt
Traceback (most recent call last):
  File "benchmark/paddle/understand_sentiment_lstm.py", line 180, in <module>
    run_benchmark(lstm_model, args)
  File "benchmark/paddle/understand_sentiment_lstm.py", line 169, in run_benchmark
    fetch_list=[avg_cost] + accuracy.metrics)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/executor.py", line 144, in run
    self.executor.run(program.desc, scope, 0, True)
paddle.v2.fluid.core.EnforceNotMet: enforce capacity == in_size failed, 128000 != 123104
The size of Input(X) mismatches with Attr(shape). at [/paddle/Paddle/paddle/operators/reshape_op.cc:51]
PaddlePaddle Call Stacks:
0       0x7f7be9d6cb17p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7f7be9fd493fp paddle::operators::ReshapeOp::InferShape(paddle::framework::InferShapeContext*) const + 2239
2       0x7f7bea56757dp paddle::framework::OperatorWithKernel::Run(paddle::framework::Scope const&, paddle::platform::DeviceContext const&) const + 573
3       0x7f7be9e16df5p paddle::framework::Executor::Run(paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool) + 613
4       0x7f7be9d8330ap void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 490
```

**Comment by chengduoZH** [comment]
Similar with https://github.com/PaddlePaddle/Paddle/issues/6265

**Comment by dzhwinter** [comment]
https://github.com/PaddlePaddle/Paddle/issues/6421
