### ISSUE TITLE
Can not find libmklml_intel.so after install the whl package

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#6422]
```bash
>> import paddle.v2 as paddle
>>> paddle.init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/__init__.py", line 119, in init
    import py_paddle.swig_paddle as api
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory
```

**Comment by Yancey1989** [comment]
Close this issue and feel free to reopen if reproduce this situation.
