### ISSUE TITLE
2.6.0在windows上编译cpu版本失败

### ISSUE THREAD

**Issue by xiaohan-W** [PaddlePaddle/Paddle#64516]
### 问题描述 Issue Description

[27/27] Packing whl packages------>>>
FAILED: python/build/.timestamp 
cmd.exe /C "cd /D E:\AI_work\Paddle\Paddle_2.6.0\Paddle\build\python && "C:\Program Files\CMake\bin\cmake.exe" -E copy_directory E:/AI_work/Paddle/Paddle_2.6.0/Paddle/python/paddle E:/AI_work/Paddle/Paddle_2.6.0/Paddle/build/python/paddle/ && "C:\Program Files\CMake\bin\cmake.exe" -E copy_directory E:/AI_work/Paddle/Paddle_2.6.0/Paddle/test E:/AI_work/Paddle/Paddle_2.6.0/Paddle/build/test && "C:\Program Files\CMake\bin\cmake.exe" -E env D:/Python/python.exe setup.py bdist_wheel"
warning: tag 'v2.6.0' is externally known as 'v2.6.1'
fatal: Not a valid object name 2>/dev/null
Traceback (most recent call last):
  File "E:\AI_work\Paddle\Paddle_2.6.0\Paddle\build\python\setup.py", line 981, in <module>
    setup(name='paddlepaddle',
  File "D:\Python\Lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\setuptools\_distutils\core.py", line 146, in setup
    _setup_distribution = dist = klass(attrs)
                                 ^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\setuptools\dist.py", line 318, in __init__
    self.metadata.version = self._normalize_version(self.metadata.version)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\Python\Lib\site-packages\setuptools\dist.py", line 354, in _normalize_version

    normalized = str(Version(version))

                     ^^^^^^^^^^^^^^^^

  File "D:\Python\Lib\site-packages\setuptools\_vendor\packaging\version.py", line 200, in __init__

    raise InvalidVersion(f"Invalid version: '{version}'")

setuptools.extern.packaging.version.InvalidVersion: Invalid version: '2.6.1-0-ge032331bf7'

ninja: build stopped: subcommand failed.

### 版本&环境信息 Version & Environment Information

Python版本：3.11.9
参考编译链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/windows-compile.html

**Comment by xuxinyi389** [comment]
看起来编译源码部分是没有问题的，已经到了最后打包成whl包的步骤了。看报错内容是setuptools报错，可以看看自己的setuptools的版本，可以使用这个版本：setuptools==57.4.0 ; python_version <= '3.11'

**Comment by xiaohan-W** [comment]
> 看起来编译源码部分是没有问题的，已经到了最后打包成whl包的步骤了。看报错内容是setuptools报错，可以看看自己的setuptools的版本，可以使用这个版本：setuptools==57.4.0 ; python_version <= '3.11'

谢谢，这样能解决问题。
另外请教一下，如果想编译MD类型的版本，需要怎么操作？

**Comment by zhangbo9674** [comment]
编译选项添加 -DWITH_MKL=ON -DWITH_MKLDNN=ON
