### ISSUE TITLE
Paddle版本==2.4.0出现ModuleNotFoundError: No module named 'paddle.base'

### ISSUE THREAD

**Issue by jiaqi100** [PaddlePaddle/Paddle#64678]
### bug描述 Describe the Bug

!python tools/train.py -c configs/rtdetr/rtdetr_hgnetv2_x_6x_coco.yml --eval --use_vdl True --vdl_log_dir vdl_log_dir/scalar出现以下错误
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    from ppdet.core.workspace import load_config, merge_config
  File "/home/aistudio/PaddleDetection/ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "/home/aistudio/PaddleDetection/ppdet/data/__init__.py", line 16, in <module>
    from . import transform
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/__init__.py", line 15, in <module>
    from . import operators
  File "/home/aistudio/PaddleDetection/ppdet/data/transform/operators.py", line 56, in <module>
    from ppdet.modeling.keypoint_utils import get_affine_transform, affine_transform
  File "/home/aistudio/PaddleDetection/ppdet/modeling/__init__.py", line 23, in <module>
    from . import heads
  File "/home/aistudio/PaddleDetection/ppdet/modeling/heads/__init__.py", line 17, in <module>
    from . import yolo_head
  File "/home/aistudio/PaddleDetection/ppdet/modeling/heads/yolo_head.py", line 26, in <module>
    from ..losses import IouLoss
  File "/home/aistudio/PaddleDetection/ppdet/modeling/losses/__init__.py", line 34, in <module>
    from . import clrnet_loss
  File "/home/aistudio/PaddleDetection/ppdet/modeling/losses/clrnet_loss.py", line 6, in <module>
    from ppdet.modeling.assigners.clrnet_assigner import assign
  File "/home/aistudio/PaddleDetection/ppdet/modeling/assigners/__init__.py", line 18, in <module>
    from . import simota_assigner
  File "/home/aistudio/PaddleDetection/ppdet/modeling/assigners/simota_assigner.py", line 22, in <module>
    from ppdet.modeling.losses.varifocal_loss import varifocal_loss
  File "/home/aistudio/PaddleDetection/ppdet/modeling/losses/varifocal_loss.py", line 27, in <module>
    from paddle.base.framework import in_dygraph_mode
ModuleNotFoundError: No module named 'paddle.base'

**Comment by zhangting2020** [comment]
建议更新Paddle到2.6版本试试，从报错来看可能是版本太低
