### ISSUE TITLE
在自己的数据集上训练关键信息抽取模型中的SER报错

### ISSUE THREAD

**Issue by kkiskkk** [PaddlePaddle/Paddle#64895]
### 请提出你的问题 Please ask your question

[2024-06-04 16:22:14,518] [    INFO] - Already cached e:\users\WangK16\.paddlenlp\models\vi-layoutxlm-base-uncased\model_state.pdparams
[2024/06/04 16:22:29] ppocr INFO: train dataloader has 41 iters
[2024/06/04 16:22:29] ppocr INFO: valid dataloader has 11 iters
[2024/06/04 16:22:29] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 19 iterations
[2024/06/04 16:43:14] ppocr INFO: epoch: [1/200], global_step: 10, lr: 0.000003, loss: 2.032407, avg_reader_cost: 0.06060 s, avg_batch_cost: 124.52930 s, avg_samples: 8.0, ips: 0.06424 samples/s, eta: 11 days, 19:18:14
eval model::   9%|████████████████▉                                                                                                                                                                         | 1/11 [00:23<03:52, 23.30s/it]Traceback (most recent call last):
  File "tools/train.py", line 227, in <module>
    main(config, device, logger, vdl_writer)
  File "tools/train.py", line 198, in main
    program.train(config, train_dataloader, valid_dataloader, device, model,
  File "E:\work\trace\ocr\PaddleOCR\PaddleOCR-release-2.7\tools\program.py", line 392, in train
    cur_metric = eval(
  File "E:\work\trace\ocr\PaddleOCR\PaddleOCR-release-2.7\tools\program.py", line 540, in eval
    preds = model(batch)
  File "e:\users\WangK16\.conda\envs\paddle_env\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "E:\work\trace\ocr\PaddleOCR\PaddleOCR-release-2.7\ppocr\modeling\architectures\base_model.py", line 86, in forward
    x = self.backbone(x)
  File "e:\users\WangK16\.conda\envs\paddle_env\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "E:\work\trace\ocr\PaddleOCR\PaddleOCR-release-2.7\ppocr\modeling\backbones\vqa_layoutlm.py", line 166, in forward
    x = self.model(
  File "e:\users\WangK16\.conda\envs\paddle_env\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "e:\users\WangK16\.conda\envs\paddle_env\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 951, in forward
    outputs = self.layoutxlm(
  File "e:\users\WangK16\.conda\envs\paddle_env\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "e:\users\WangK16\.conda\envs\paddle_env\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 872, in forward
    text_layout_emb = self._calc_text_embeddings(
  File "e:\users\WangK16\.conda\envs\paddle_env\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 740, in _calc_text_embeddings
    spatial_position_embeddings = self.embeddings._cal_spatial_position_embeddings(bbox)
  File "e:\users\WangK16\.conda\envs\paddle_env\lib\site-packages\paddlenlp\transformers\layoutxlm\modeling.py", line 137, in _cal_spatial_position_embeddings
    lower_position_embeddings = self.y_position_embeddings(bbox[:, :, 3])
  File "e:\users\WangK16\.conda\envs\paddle_env\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "e:\users\WangK16\.conda\envs\paddle_env\lib\site-packages\paddle\nn\layer\common.py", line 1515, in forward
    return F.embedding(
  File "e:\users\WangK16\.conda\envs\paddle_env\lib\site-packages\paddle\nn\functional\input.py", line 205, in embedding
    return _C_ops.embedding(x, weight, padding_idx, sparse)
ValueError: (InvalidArgument) Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 1024, but got 1058. Please check input value.
  [Hint: Expected ids[i] < row_number, but received ids[i]:1058 >= row_number:1024.] (at ..\paddle\phi\kernels\cpu\embedding_kernel.cc:67)

eval model::   9%|████████████████▉                                                                                                                                                                         | 1/11 [00:25<04:12, 25.25s/it]

**Comment by wanghuancoder** [comment]
ValueError: (InvalidArgument) Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 1024, but got 1058. Please check input value.
[Hint: Expected ids[i] < row_number, but received ids[i]:1058 >= row_number:1024.] (at ..\paddle\phi\kernels\cpu\embedding_kernel.cc:67)
这个看起来是你准备的数据存在问题导致的，你可以顺藤摸瓜的自己追溯一下。
我也会请OCR的同学帮你看看。但通过报错能够发现的问题终归有限。

**Comment by tink2123** [comment]
看起来是训练数据的维度问题，可以参考开源的数据检查下标注：https://github.com/PaddlePaddle/PaddleOCR/blob/1ca0c2231abe809f753287be525d180c79a06d72/doc/doc_ch/kie.md#13-%E6%95%B0%E6%8D%AE%E4%B8%8B%E8%BD%BD

同时确认下是否修改了网络的默认配置

**Comment by kkiskkk** [comment]
> 看起来是训练数据的维度问题，可以参考开源的数据检查下标注：https://github.com/PaddlePaddle/PaddleOCR/blob/1ca0c2231abe809f753287be525d180c79a06d72/doc/doc_ch/kie.md#13-%E6%95%B0%E6%8D%AE%E4%B8%8B%E8%BD%BD
> 
> 同时确认下是否修改了网络的默认配置

网络默认配置未修改，标注格式目前也没有发现问题。请问这个是否与验证集的一些文本transcription对应的id不在训练集的id范围内有关？
