### ISSUE TITLE
MacOS 10.15安装paddle cpu版本后import paddle报错

### ISSUE THREAD

**Issue by gerald-luo** [PaddlePaddle/Paddle#65021]
### 问题描述 Issue Description

(paddle_3.8) geraldluo@GeralddeiMac ~ % python3
Python 3.8.19 (default, Mar 20 2024, 15:00:34) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /opt/anaconda3/envs/paddle_3.8/lib/python3.8/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/paddle_3.8/lib/python3.8/site-packages/paddle/__init__.py", line 28, in <module>
    from .base import core  # noqa: F401
  File "/opt/anaconda3/envs/paddle_3.8/lib/python3.8/site-packages/paddle/base/__init__.py", line 36, in <module>
    from . import core
  File "/opt/anaconda3/envs/paddle_3.8/lib/python3.8/site-packages/paddle/base/core.py", line 380, in <module>
    raise e
  File "/opt/anaconda3/envs/paddle_3.8/lib/python3.8/site-packages/paddle/base/core.py", line 268, in <module>
    from . import libpaddle
ImportError: dlopen(/opt/anaconda3/envs/paddle_3.8/lib/python3.8/site-packages/paddle/base/libpaddle.so, 2): Symbol not found: __ZTTNSt3__118basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE
  Referenced from: /opt/anaconda3/envs/paddle_3.8/lib/python3.8/site-packages/paddle/base/../libs/libcommon.dylib (which was built for Mac OS X 13.0)
  Expected in: /usr/lib/libc++.1.dylib

### 版本&环境信息 Version & Environment Information

paddle版本：2.6.1
CPU：Intel(R) Core(TM) i5-4570R
MacOS：10.15.7
Python：3.8

**Comment by Birdylx** [comment]
@gerald-luo 报错信息里有提示`packages/paddle/base/../libs/libcommon.dylib (which was built for Mac OS X 13.0)`，`libcommon.dylib`是在Mac OS X 13.0系统下编译的，和你的不匹配，你可以尝试在你的系统环境里编译，或者尝试下旧版本的paddle whl包

**Comment by gerald-luo** [comment]
安装了paddle版本：2.5.0之后，没有出现这个报错了
