### ISSUE TITLE
拉去paddle docker paddle.utils.run_check()的时候出错

### ISSUE THREAD

**Issue by heianyouling** [PaddlePaddle/Paddle#65162]
### 问题描述 Issue Description

我拉的这个镜像
docker pull paddlepaddle/paddle:2.6.1-gpu-cuda12.0-cudnn8.9-trt8.6
docker run --gpus all --name paddle_docker -v $PWD:/paddle --network=host -it registry.baidubce.com/paddlepaddle/paddle:2.6.1-gpu-cuda12.0-cudnn8.9-trt8.6 /bin/bash
进去docker后
Python
import paddle
paddle.utils.run_check()
报错
Running verify PaddlePaddle program ...
I0614 03:07:09.375766    34 program_interpreter.cc:212] New Executor is Running.
W0614 03:07:09.376313    34 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 12.0
W0614 03:07:09.377041    34 gpu_resources.cc:164] device: 0, cuDNN Version: 8.8.
I0614 03:07:09.471983    34 interpreter_util.cc:624] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_selected_gpus', current_value='2', default_value='')
=======================================================================
I0614 03:07:10.524442   112 tcp_utils.cc:107] Retry to connect to 127.0.0.1:38769 while the server is not yet listening.
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_selected_gpus', current_value='1', default_value='')
=======================================================================
I0614 03:07:10.540831   111 tcp_utils.cc:107] Retry to connect to 127.0.0.1:38769 while the server is not yet listening.
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_selected_gpus', current_value='3', default_value='')
=======================================================================
I0614 03:07:10.541234   113 tcp_utils.cc:107] Retry to connect to 127.0.0.1:38769 while the server is not yet listening.
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_selected_gpus', current_value='0', default_value='')
=======================================================================
I0614 03:07:10.541409   110 tcp_utils.cc:181] The server starts to listen on IP_ANY:38769
I0614 03:07:10.541635   110 tcp_utils.cc:130] Successfully connected to 127.0.0.1:38769
I0614 03:07:13.524809   112 tcp_utils.cc:130] Successfully connected to 127.0.0.1:38769
I0614 03:07:13.541198   111 tcp_utils.cc:130] Successfully connected to 127.0.0.1:38769
I0614 03:07:13.541453   113 tcp_utils.cc:130] Successfully connected to 127.0.0.1:38769
I0614 03:07:13.558444   112 process_group_nccl.cc:129] ProcessGroupNCCL pg_timeout_ 1800000
I0614 03:07:13.558452   111 process_group_nccl.cc:129] ProcessGroupNCCL pg_timeout_ 1800000
I0614 03:07:13.558501   113 process_group_nccl.cc:129] ProcessGroupNCCL pg_timeout_ 1800000
I0614 03:07:13.568851   110 process_group_nccl.cc:129] ProcessGroupNCCL pg_timeout_ 1800000
W0614 03:07:13.811815   113 gpu_resources.cc:119] Please NOTE: device: 3, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 12.0
W0614 03:07:13.812657   113 gpu_resources.cc:164] device: 3, cuDNN Version: 8.8.
W0614 03:07:13.822098   111 gpu_resources.cc:119] Please NOTE: device: 1, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 12.0
W0614 03:07:13.822937   111 gpu_resources.cc:164] device: 1, cuDNN Version: 8.8.
W0614 03:07:13.830044   112 gpu_resources.cc:119] Please NOTE: device: 2, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 12.0
W0614 03:07:13.830883   112 gpu_resources.cc:164] device: 2, cuDNN Version: 8.8.
W0614 03:07:13.835356   110 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 12.0
W0614 03:07:13.836182   110 gpu_resources.cc:164] device: 0, cuDNN Version: 8.8.

--------------------------------------
--------------------------------------
C++ Traceback (most recent call last):
C++ Traceback (most recent call last):
--------------------------------------
--------------------------------------
No stack trace in paddle, may be caused by external reasons.
No stack trace in paddle, may be caused by external reasons.

----------------------
----------------------
Error Message Summary:
Error Message Summary:
----------------------
----------------------
FatalError: `Access to an undefined portion of a memory object` is detected by the operating system.
  [TimeInfo: *** Aborted at 1718334434 (unix time) try "date -d @1718334434" if you are using GNU date ***]
  [SignalInfo: *** SIGBUS (@0x7fd06113ffe0) received by PID 111 (TID 0x7fd0a5dd9700) from PID 1628700640 ***]
FatalError: `Access to an undefined portion of a memory object` is detected by the operating system.
  [TimeInfo: *** Aborted at 1718334434 (unix time) try "date -d @1718334434" if you are using GNU date ***]
  [SignalInfo: *** SIGBUS (@0x7ff725ffefe0) received by PID 112 (TID 0x7ff76edd7700) from PID 637530080 ***]

--------------------------------------
--------------------------------------
C++ Traceback (most recent call last):
C++ Traceback (most recent call last):
--------------------------------------
--------------------------------------
No stack trace in paddle, may be caused by external reasons.
No stack trace in paddle, may be caused by external reasons.

----------------------
----------------------
Error Message Summary:
Error Message Summary:
----------------------
----------------------
FatalError: `Access to an undefined portion of a memory object` is detected by the operating system.
  [TimeInfo: *** Aborted at 1718334434 (unix time) try "date -d @1718334434" if you are using GNU date ***]
  [SignalInfo: *** SIGBUS (@0x7fc025031fe0) received by PID 113 (TID 0x7fc06dc0d700) from PID 620961760 ***]
FatalError: `Access to an undefined portion of a memory object` is detected by the operating system.
  [TimeInfo: *** Aborted at 1718334434 (unix time) try "date -d @1718334434" if you are using GNU date ***]
  [SignalInfo: *** SIGBUS (@0x7fbc1113ffe0) received by PID 110 (TID 0x7fbc617fe700) from PID 286523360 ***]

[2024-06-14 03:07:15,150] [ WARNING] install_check.py:289 - PaddlePaddle meets some problem with 4 GPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
[2024-06-14 03:07:15,150] [ WARNING] install_check.py:297 -
 Original Error is: Process 1 terminated with signal SIGBUS.
PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 302, in run_check
    raise e
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 283, in run_check
    _run_parallel(device_list)
  File "/usr/local/lib/python3.10/dist-packages/paddle/utils/install_check.py", line 210, in _run_parallel
    paddle.distributed.spawn(train_for_run_parallel, nprocs=len(device_list))
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 614, in spawn
    while not context.join():
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 423, in join
    self._throw_exception(error_index)
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/spawn.py", line 430, in _throw_exception
    raise Exception(
Exception: Process 1 terminated with signal SIGBUS.
请问是什么问题

### 版本&环境信息 Version & Environment Information

![微信图片_20240614111219](https://github.com/PaddlePaddle/Paddle/assets/49261165/88132951-8ae5-4cd6-8a38-78bca01bd73c)
paddle:2.6.1-gpu-cuda12.0-cudnn8.9-trt8.6

**Comment by liuxdxd** [comment]
博主你好，请问你是从哪个镜像仓库拉的paddle的镜像，方便告知下吗

**Comment by Charles-hit** [comment]
您好 感谢您的反馈，这个问题已经找相关同学在看了，最近会给您回复哈。

**Comment by tianshuo78520a** [comment]
设置CUDA_VISIBLE_DEVICES=0 再执行paddle.utils.run_check()呢
