### ISSUE TITLE
海光DCU ImportError: libgalaxyhip.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/Paddle#65227]
### bug描述 Describe the Bug

海光的机器，想实现启动docker后自动训练功能：
docker-compose.yaml的配置：
```
version: "2.4"

services:
  perf_train_resnet50_pd:
    build:
      context: .
      dockerfile: Dockerfile
    ipc: host
    privileged: true
    image: resnet50_pd_v1:latest
    container_name: resnet50_pd_container
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    hostname: training
    volumes:
      - ../datasets:/data
      - ../results:/results
      - $PWD/PaddleClas:/workspace
    command: bash train.sh
    restart: on-failure

networks:
  host:
    name: host
    external: true
```
train.sh里面的文件：
```
python -c "import paddle"
```
然后会报错：

```
Error: Can not import paddle core while this file exists: /opt/py310/lib/python3.10/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/py310/lib/python3.10/site-packages/paddle/__init__.py", line 37, in <module>
    from .base import core  # noqa: F401
  File "/opt/py310/lib/python3.10/site-packages/paddle/base/__init__.py", line 38, in <module>
    from . import (  # noqa: F401
  File "/opt/py310/lib/python3.10/site-packages/paddle/base/backward.py", line 25, in <module>
    from . import core, framework, log_helper, unique_name
  File "/opt/py310/lib/python3.10/site-packages/paddle/base/core.py", line 383, in <module>
    raise e
  File "/opt/py310/lib/python3.10/site-packages/paddle/base/core.py", line 267, in <module>
    from . import libpaddle
ImportError: libgalaxyhip.so.5: cannot open shared object file: No such file or directory
```

**Comment by qili93** [comment]
您好，请问您这里使用的是什么镜像，以及Paddle的WHL安装包是哪里获取的呢？

这个错误可能是Paddle WHL的安装版本和镜像中的DTK版本不匹配导致的。

你可以先看下镜像的opt目录下看下DTK的版本，并find命令查找一下 libgalaxyhip 这个库

例如如下截图中，DTK版本是24.04，能在 /opt/dtk-24.04 目录下找到 libgalaxyhip.so.5

![image](https://github.com/PaddlePaddle/Paddle/assets/16605440/bbe13470-2cba-4271-98be-e9260d8b5f7a)

请提供下您运行的镜像和Paddle WHL包的下载地址，谢谢！

**Comment by w5688414** [comment]
我运行 find / -name libgalaxyhip.so* 2>/dev/null，结果如下：
```
/opt/dtk-23.10.1/lib/libgalaxyhip.so
/opt/dtk-23.10.1/lib/libgalaxyhip.so.5
/opt/dtk-23.10.1/lib/libgalaxyhip.so.4
/opt/dtk-23.10.1/hip/lib/libgalaxyhip.so
/opt/dtk-23.10.1/hip/lib/libgalaxyhip.so.5.2.23453.269-23afd42c
/opt/dtk-23.10.1/hip/lib/libgalaxyhip.so.5
/opt/dtk-23.10.1/hip/lib/libgalaxyhip.so.4
```

**Comment by qili93** [comment]
> 我运行 find / -name libgalaxyhip.so* 2>/dev/null，结果如下：
> 
> ```
> /opt/dtk-23.10.1/lib/libgalaxyhip.so
> /opt/dtk-23.10.1/lib/libgalaxyhip.so.5
> /opt/dtk-23.10.1/lib/libgalaxyhip.so.4
> /opt/dtk-23.10.1/hip/lib/libgalaxyhip.so
> /opt/dtk-23.10.1/hip/lib/libgalaxyhip.so.5.2.23453.269-23afd42c
> /opt/dtk-23.10.1/hip/lib/libgalaxyhip.so.5
> /opt/dtk-23.10.1/hip/lib/libgalaxyhip.so.4
> ```

环境应该是对的，应该是登陆容器环境之后默认在 /root/.bashrc里面配置了 source /opt/dtk-23.10.1/env.sh

如果您这里不是通过Bash登陆的容器，就需要手动运行一下 source /opt/dtk-23.10.1/env.sh 设置下DTK的环境变量。
