### ISSUE TITLE
Paddle.nn.LSTM 模型使用.to('gpu:0')报错

### ISSUE THREAD

**Issue by huhaohao525** [PaddlePaddle/Paddle#65546]
### bug描述 Describe the Bug

# 问题描述：
使用paddle自带的LSTM模型时，使用.to('gpu:0')报错。

# 环境：
paddle=2.6.1
cuda=11.2
python=3.8

# 最小复现代码：
```
import paddle
net = paddle.nn.LSTM(10, 10, 2)
net.to('gpu:0')
```

# 我的问题：
我重复这个步骤每次都会报错，让另一位同事尝试，也报错，不确定是否和这个环境版本组合有关？也请反馈是否可以复现。翻看源码，这块可能和_dropout_state的显存分配有关。

# 错误信息：
```
λ 28ba4b759b7b /code python3.8
Python 3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
>>> net = paddle.nn.LSTM(10, 10, 2)
W0628 07:16:38.726099 96675 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 11.2
W0628 07:16:38.735044 96675 gpu_resources.cc:164] device: 0, cuDNN Version: 8.1.
>>> net.to('gpu:0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/layers.py", line 2190, in to
    return self._to_impl(
  File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/layers.py", line 2340, in _to_impl
    self._apply(transform, device, dtype, blocking, include_sublayers)
  File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/layers.py", line 2217, in _apply
    self._buffers[key] = func(buf, device, dtype, blocking)
  File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/layers.py", line 2336, in transform
    return self._transform(t, device, dtype, blocking)
  File "/usr/local/lib/python3.8/dist-packages/paddle/nn/layer/layers.py", line 2263, in _transform
    new_t = t_casted._copy_to(device, blocking)
RuntimeError: (PreconditionNotMet) Tensor's dimension is out of bound.Tensor's dimension must be equal or less than the size of its memory.But received Tensor's dimension is 1, memory's size is 0.
  [Hint: Expected numel() * SizeOf(dtype()) <= memory_size(), but received numel() * SizeOf(dtype()):1 > memory_size():0.] (at ../paddle/phi/core/dense_tensor_impl.cc:55)
```

**Comment by pkuzyc** [comment]
bug 已经复现，可能是某个参数没有初始化，正在排查中

**Comment by pkuzyc** [comment]
这个问题主要是 RNN 模型里 dropout_state 用了一种特殊的创建方式导致的：
```
 self._dropout_state = self.create_variable(
    dtype=core.VarDesc.VarType.UINT8,
    name=f"dropout_state{NON_PERSISTABLE_VAR_NAME_SUFFIX}",
)
```
目前还没有一种好方法能快速解决，后续排期修复。

**Comment by huhaohao525** [comment]
好的，那项目暂时绕过这块，等后续修复。
