### ISSUE TITLE
关于paddle.incubate.nn.functional.block_multihead_attention函数

### ISSUE THREAD

**Issue by wojiaoshihua** [PaddlePaddle/Paddle#65603]
### 请提出你的问题 Please ask your question

当我在跑paddlenlp的模型推理时，出现了如下报错，这是因为cuda版本过低导致不支持flash_attn吗，我的环境CUDA=11.2
，A100

UnimplementedError: FlashAttention is unsupported, please check the GPU compability and CUDA Version. (at ../paddle/phi/kernels/gpu/flash_attn_utils.h:367)
      [operator < block_multihead_attention > error]
Process Process-1:
Traceback (most recent call last):
  File "/root/anaconda3/envs/visual/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/visual/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/paddlejob/workspace/mywork/origin/PaddleNLP/llm/utils/utils.py", line 761, in read_res
    output_tensor = tensor_queue.get(timeout=1)
  File "/root/anaconda3/envs/visual/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/envs/visual/lib/python3.10/site-packages/paddle/incubate/multiprocessing/reductions.py", line 130, in _rebuild_lodtensor_filename
    lodtensor = cls._new_shared_filename(
RuntimeError: (Unavailable) File descriptor /paddle_25505_0_3639094214 open failed, unable in read-write mode
  [Hint: Expected fd != -1, but received fd:-1 == -1:-1.] (at ../paddle/fluid/memory/allocation/mmap_allocator.cc:85)

**Comment by gongel** [comment]
你好，你的推测很正确，flash_attn最低要求CUDA>=11.6

**Comment by wojiaoshihua** [comment]
> 你好，你的推测很正确，flash_attn最低要求CUDA>=11.6

好的，感谢回复
