### ISSUE TITLE
To_tensor 在 paddlepaddle-gpu 2.6.1 版本不可用

### ISSUE THREAD

**Issue by JamesLim-sy** [PaddlePaddle/Paddle#65729]
### bug描述 Describe the Bug

写了个简单 demo：
```
import paddle
x = paddle.to_tensor([21024, 8000], place=paddle.CUDAPlace(), dtype='bfloat16')
y = paddle.to_tensor([21024, 8000], place=paddle.CUDAPlace(), dtype='bfloat16')
for i in range(10):
    z = paddle.add(x, y)
```

结果报错信息如下：
```
Traceback (most recent call last):
  File "/home/haz/paddle.py", line 1, in <module>
    import paddle
  File "/home/haz/paddle.py", line 2, in <module>
    x = paddle.to_tensor([21024, 8000], place=paddle.CUDAPlace(), dtype='bfloat16')
AttributeError: partially initialized module 'paddle' has no attribute 'to_tensor' (most likely due to a circular import)
```

tenosr 功能都被改崩了??

**Comment by deepllz** [comment]
你好，你的文件名叫paddle，应该是和import paddle冲突了，换个文件名尝试一下。

**Comment by JamesLim-sy** [comment]
Cool，原来是这个问题.
