### ISSUE TITLE
Paddle/CINN  测试算子脚本如何测试寒武纪硬件？

### ISSUE THREAD

**Issue by wangzy0327** [PaddlePaddle/Paddle#65860]
### 请提出你的问题 Please ask your question

这是Paddle下测试conv2d算子的脚本
test/cinn/ops/test_conv2d_op.py

<details>
  <summary>test_conv2d_op.py</summary>

```
from op_test import OpTest, OpTestTool
from op_test_helper import TestCaseHelper

import paddle
from paddle.cinn.common import is_compiled_with_cuda
from paddle.cinn.frontend import NetBuilder
from paddle.cinn.runtime import set_cinn_cudnn_deterministic

set_cinn_cudnn_deterministic(True)
paddle.base.set_flags({'FLAGS_cudnn_deterministic': 1})


@OpTestTool.skip_if(
    not is_compiled_with_cuda(), "x86 test will be skipped due to timeout."
)
class TestConv2dOp(OpTest):
    def setUp(self):
        # print(f"\n{self.__class__.__name__}: {self.case}")
        self.prepare_inputs()

    def prepare_inputs(self):
        self.x_np = self.random(
            shape=self.case["x_shape"], dtype=self.case["dtype"]
        )
        self.w_np = self.random(
            shape=self.case["w_shape"], dtype=self.case["dtype"]
        )
        self.dy_np = self.random(
            shape=self.case["dy_shape"], dtype=self.case["dtype"]
        )

    def build_paddle_program(self, target):
        x = paddle.to_tensor(self.x_np, stop_gradient=False)
        weight = paddle.to_tensor(self.w_np, stop_gradient=False)
        y = paddle.nn.functional.conv2d(
            x,
            weight,
            stride=self.case["stride"],
            padding=self.case["padding"],
            dilation=self.case["dilation"],
            groups=self.case["groups"],
            data_format=self.case["data_format"],
        )
        self.paddle_outputs = [y]
        self.paddle_grads = self.get_paddle_grads(
            [y], [x, weight], [self.dy_np]
        )

    def build_cinn_program(self, target):
        builder = NetBuilder("conv2d")
        x = builder.create_input(
            self.nptype2cinntype(self.case["dtype"]), self.case["x_shape"], "x"
        )
        weight = builder.create_input(
            self.nptype2cinntype(self.case["dtype"]),
            self.case["w_shape"],
            "weight",
        )
        dy = builder.create_input(
            self.nptype2cinntype(self.case["dtype"]),
            self.case["dy_shape"],
            "dy",
        )

        if self.case["data_format"] == "NCHW":
            y = builder.conv2d(
                x,
                weight,
                strides=self.case["stride"],
                paddings=self.case["padding"],
                dilations=self.case["dilation"],
                groups=self.case["groups"],
                data_format=self.case["data_format"],
            )
            x_grad = builder.conv(
                weight,
                dy,
                data_format=self.case["data_format"],
                conv_type="backward_data",
                output_shape=x.shape(),
            )
            weight_grad = builder.conv(
                x,
                dy,
                data_format=self.case["data_format"],
                conv_type="backward_filter",
                output_shape=weight.shape(),
            )
        elif self.case["data_format"] == "NHWC":
            weight_t = builder.transpose(weight, [0, 2, 3, 1])
            y = builder.conv2d(
                x,
                weight_t,
                strides=self.case["stride"],
                paddings=self.case["padding"],
                dilations=self.case["dilation"],
                groups=self.case["groups"],
                data_format=self.case["data_format"],
            )
            x_grad = builder.conv(
                weight_t,
                dy,
                data_format=self.case["data_format"],
                conv_type="backward_data",
                output_shape=x.shape(),
            )
            w_grad = builder.conv(
                x,
                dy,
                data_format=self.case["data_format"],
                conv_type="backward_filter",
                output_shape=weight_t.shape(),
            )
            weight_grad = builder.transpose(w_grad, [0, 3, 1, 2])

        prog = builder.build()
        res = self.get_cinn_output(
            prog,
            target,
            [x, weight, dy],
            [self.x_np, self.w_np, self.dy_np],
            [y, x_grad, weight_grad],
            passes=[],
        )

        self.cinn_outputs = [res[0]]
        self.cinn_grads = [res[1], res[2]]

    def test_check_results(self):
        max_relative_error = (
            self.case["max_relative_error"]
            if "max_relative_error" in self.case
            # else 1e-5
            else 1e-3
        )
        self.check_outputs_and_grads(max_relative_error=max_relative_error)


class TestConv2dOpAll(TestCaseHelper):
    def init_attrs(self):
        self.class_name = "TestConv2dCase"
        self.cls = TestConv2dOp
        self.inputs = [
            {
                "x_shape": [3, 16, 32, 32],
                "w_shape": [16, 16, 3, 3],
                "dy_shape": [3, 16, 30, 30],
                "data_format": "NCHW",
            },
            {
                "x_shape": [3, 16, 64, 64],
                "w_shape": [16, 16, 3, 3],
                "dy_shape": [3, 16, 62, 62],
                "data_format": "NCHW",
            },
            {
                "x_shape": [3, 32, 32, 16],
                "w_shape": [16, 16, 3, 3],
                "dy_shape": [3, 30, 30, 16],
                "data_format": "NHWC",
            },
            {
                "x_shape": [3, 64, 64, 16],
                "w_shape": [16, 16, 3, 3],
                "dy_shape": [3, 62, 62, 16],
                "data_format": "NHWC",
            },
        ]
        self.dtypes = [
            {
                "dtype": "float16",
                "max_relative_error": 1e-3,
            },
            {
                "dtype": "float32",
            },
        ]
        self.attrs = [
            {
                "stride": [1, 1],
                "padding": [0, 0],
                "dilation": [1, 1],
                "groups": 1,
            },
        ]

if __name__ == "__main__":
    TestConv2dOpAll().run()
```

</details>

在寒武纪下执行，测试conv2d的log如下
```
I0709 06:11:37.340034 3500445 init.cc:234] ENV [CUSTOM_DEVICE_ROOT]=/home/wzy/build-python3-10-14/lib/python3.10/site-packages/paddle_custom_device
I0709 06:11:37.340088 3500445 init.cc:143] Try loading custom device libs from: [/home/wzy/build-python3-10-14/lib/python3.10/site-packages/paddle_custom_device]
I0709 06:11:37.360155 3500445 custom_device.cc:1099] Succeed in loading custom runtime in lib: /home/wzy/build-python3-10-14/lib/python3.10/site-packages/paddle_custom_device/libpaddle-custom-mlu.so
I0709 06:11:37.362766 3500445 custom_kernel.cc:63] Succeed in loading 262 custom kernel(s) from loaded lib(s), will be used like native ones.
I0709 06:11:37.362890 3500445 init.cc:155] Finished in LoadCustomDevice with libs_path: [/home/wzy/build-python3-10-14/lib/python3.10/site-packages/paddle_custom_device]
I0709 06:11:37.362923 3500445 init.cc:240] CustomDevice: mlu, visible devices count: 1
W0709 06:11:37.778934 3500445 flags.cc:299] CINN is compiled without cuDNN, this api is invalid!
Traceback (most recent call last):
  File "/home/wzy/Paddle/test/cinn/ops/test_conv2d_op.py", line 26, in <module>
    paddle.base.set_flags({'FLAGS_cudnn_deterministic': 1})
  File "/home/wzy/build-python3-10-14/lib/python3.10/site-packages/paddle/base/framework.py", line 96, in set_flags
    raise ValueError(
ValueError: Flag FLAGS_cudnn_deterministic cannot set its value through this function.
```

如何将其修改为测试寒武纪硬件的测试脚本呢？

**Comment by yuanlehome** [comment]
您好，您是要在寒武纪芯片下测试CINN吗？如果是，CINN不支持寒武纪芯片。如果不是，请进一步明确下问题/需求。如果和CINN无关，而是想测试conv2d算子在寒武纪芯片下的情况，可以关注下 https://github.com/PaddlePaddle/PaddleCustomDevice

**Comment by yuanlehome** [comment]
您好，如果没有进一步的问题，我这里先把这个issue关闭了。如果还有问题，您随时可以重启此issue。
