### ISSUE TITLE
在XPU上编译安装Paddle验证报错

### ISSUE THREAD

**Issue by MiltonZheng** [PaddlePaddle/Paddle#66135]
### 请提出你的问题 Please ask your question

软硬件配置：操作系统飞腾2500S，加速卡昆仑R200，
gcc版本8.3.0，cmake版本3.16.5，python版本3.7.4
Paddle分支release/2.5

问题描述：编译过程没有遇到问题，但是编译安装完成后执行utils.run_check()报如下错误。
我尝试执行了一下其他程序，也会报类似的算子错误，请问可能是什么原因导致的呢？
```
[root@node10 dist]# python3
Python 3.7.4 (default, Sep 30 2020, 17:30:15) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
XPURT /usr/local/lib64/python3.7/site-packages/paddle/fluid/../libs/libxpurt.so.1 loaded
XPURT /usr/local/lib64/python3.7/site-packages/paddle/fluid/../libs/libxpurt.so loaded
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
I0717 18:21:18.498073 43280 interpretercore.cc:237] New Executor is Running.
W0717 18:21:18.498564 43280 xpu_context.cc:169] Please NOTE: xpu device: 0
autotune_file fc {} not exist
[WARN][XPURT][xpu_llwait:675] ioctl() fail, (714) Exception in kernel execution
[WARN][XPURT][xpu_llwait:675] ioctl() fail, (714) Exception in kernel execution
[WARN][XPURT][xpu_lllaunch_async:543] ioctl() fail, (712) Operation not supported
[WARN][XPURT][xpu_launch_async:327] fail on kernel ty=CDNN name='_ZN4xpu29findmax1dIfEEvPKT_xPf' ncl=6 nco=8
[WARN][XPURT][xpu_lllaunch_async:543] ioctl() fail, (712) Operation not supported
[WARN][XPURT][xpu_launch_async:327] fail on kernel ty=CDNN name='_ZN4xpu29findmax1dIfEEvPKT_xPf' ncl=6 nco=8
[WARN][XPURT][xpu_lllaunch_async:543] ioctl() fail, (712) Operation not supported
[WARN][XPURT][xpu_launch_async:327] fail on kernel ty=CDNN name='_ZN4xpu211fc_one_loopIfffffsfLb0ELb0EEEv10MMArgsBaseIT_T0_T1_T2_T3_E14LargeBlockArgs9BlockArgs12FragmentArgs12L2inSRAMArgs13L2outSRAMArgs12L1inSRAMArgs13L1outSRAMArgs10LoadAFirstibbbb' ncl=6 nco=8
[WARN][XPURT][xpu_lllaunch_async:543] ioctl() fail, (712) Operation not supported
[WARN][XPURT][xpu_launch_async:327] fail on kernel ty=CLUSTER name='_ZN4xpu218common_calc_mn_mtnILi0EfEEvPKT0_S3_PS1_xxx' ncl=8 nco=64
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.7/site-packages/paddle/utils/install_check.py", line 249, in run_check
    _run_static_single(use_cuda, use_xpu)
  File "/usr/local/lib64/python3.7/site-packages/paddle/utils/install_check.py", line 150, in _run_static_single
    fetch_list=[out.name, param_grads[1].name],
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/executor.py", line 1401, in run
    use_prune=use_prune,
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/executor.py", line 1619, in _run_impl
    scope, list(feed.keys()), fetch_list, return_numpy
  File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/executor.py", line 655, in run
    scope, feed_names, fetch_list
OSError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/usr/local/lib64/python3.7/site-packages/paddle/utils/install_check.py", line 249, in run_check
      _run_static_single(use_cuda, use_xpu)
    File "/usr/local/lib64/python3.7/site-packages/paddle/utils/install_check.py", line 133, in _run_static_single
      input, out, weight = _simple_network()
    File "/usr/local/lib64/python3.7/site-packages/paddle/utils/install_check.py", line 37, in _simple_network
      linear_out = paddle.nn.functional.linear(x=input, weight=weight, bias=bias)
    File "/usr/local/lib64/python3.7/site-packages/paddle/nn/functional/common.py", line 1872, in linear
      attrs={'axis': -1},
    File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/layer_helper.py", line 45, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/framework.py", line 4019, in append_op
      attrs=kwargs.get("attrs", None),
    File "/usr/local/lib64/python3.7/site-packages/paddle/fluid/framework.py", line 2781, in __init__
      for frame in traceback.extract_stack():

    ExternalError: elementwise XDNN Error, XDNN_RUNTIME_ERROR  (at /root/zmh/Paddle/paddle/phi/kernels/xpu/elementwise.h:104)
      [operator < elementwise_add > error]
>>> exit()
```

**Comment by lijialin03** [comment]
您好，我们正在联系相关开发同学进行复现，复现后会尽快联系您，感谢您的反馈！

**Comment by MiltonZheng** [comment]
你好，更换release/2.6分支编译后问题已经解决
