### ISSUE TITLE
同时import paddle和torch报错找不到cudnn

### ISSUE THREAD

**Issue by lyxxxyl** [PaddlePaddle/Paddle#66947]
### bug描述 Describe the Bug

发生了和 [66669#](https://github.com/PaddlePaddle/Paddle/issues/66669#issue-2433750183) 一样的问题
同时import torch 和import paddle 时将会报错

```
Traceback (most recent call last):
  File "D:\Project\PyC\demo.py", line 117, in <module>
    import torch
  File "D:\Python3\lib\site-packages\torch\__init__.py", line 122, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "D:\Python3\lib\site-packages\torch\lib\cudnn_adv_train64_8.dll" or one of its dependencies.
```

应该与 [这个问题](https://github.com/PaddlePaddle/PaddleOCR/issues/604#issue-684461312) 是类似的，先import torch或paddle都会报错。
我的环境是CUDA 11.8，cudnn 8.6.0，python 3.8.0
![1722564526045](https://github.com/user-attachments/assets/e117ab54-1ca7-433f-ab45-f6d3447eb5dd)
![1722564580862](https://github.com/user-attachments/assets/ec2ae8c8-33a9-4968-8d3c-ebb7c53f0a0a)

paddle是按照官网命令下载的，之前用的是paddlepaddle 2.6-cuda11.7，与pytorch同时引用会报错gpu占用问题，和 [142#](https://github.com/RapidAI/RapidOCR/issues/142#issue-2066649141)，按照里面的方法重新下了paddle
`python -m pip install --pre paddlepaddle-gpu -i https://www.paddlepaddle.org.cn/packages/nightly/cu118/`

**Comment by lyxxxyl** [comment]
单独使用时两个库都正常，且可以使用gpu加速
但是显示的cudnn版本都与我系统所安装的不同
系统所安装的cudnn为 cudnn-windows-x86_64-8.6.0.163_cuda11-archive 是按照Paddle官网所要求
![1722567106991](https://github.com/user-attachments/assets/4586b8cd-33bb-4c54-b167-fe8a14777c81)

验证paddle安装没有问题
```
import paddle
paddle.utils.run_check()
```
输出为
```
Running verify PaddlePaddle program ... 
I0802 10:53:56.846289  7704 program_interpreter.cc:243] New Executor is Running.
W0802 10:53:56.846289  7704 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 11.8
W0802 10:53:56.846289  7704 gpu_resources.cc:164] device: 0, cuDNN Version: 8.9.
I0802 10:53:58.990527  7704 interpreter_util.cc:647] Standalone Executor is Used.
PaddlePaddle works well on 1 GPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```
且使用paddleocr正常

验证torch
```
import torch
print(torch.cuda.is_available())
print(torch.backends.cudnn.is_available())
print(torch.cuda_version)
print(torch.backends.cudnn.version())
```
输出为
```
True
True
11.8
8700
```

发现两个cudnn版本都不是系统中所装的cudnn 8.6.0，是否真如 [604#](https://github.com/PaddlePaddle/PaddleOCR/issues/604#issue-684461312) 中的评论所说一样，该如何解决呢
![1722568054351](https://github.com/user-attachments/assets/7f0754d3-f3f4-4adb-9d61-a847905ebaad)

**Comment by wangna11BD** [comment]
参考这个issue https://github.com/PaddlePaddle/Paddle/issues/56812, paddle换成paddle-gpu 2.4.0试试呢

**Comment by lyxxxyl** [comment]
上面发的报错是先import paddle 再 import torch的，先torch 后 paddle报错如下
```
Traceback (most recent call last):
  File "D:\Project\PyC\demo.py", line 115, in <module>
    import paddle
  File "D:\Python3\lib\site-packages\paddle\__init__.py", line 721, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "D:\Python3\lib\site-packages\paddle\..\nvidia\cudnn\bin\cudnn_adv_infer64_8.dll" or one of its dependencies.
```

**Comment by lyxxxyl** [comment]
> 参考这个issue #56812, paddle换成paddle-gpu 2.4.0试试呢

这个办法是可以的，我之前用paddle-gpu 2.4.2-post117和 torch 1.13.0-cu117是可行的
就是会报一堆警告
```
D:\software\Python38\python.exe D:\code\omniglue\demo16.py 
D:\software\Python38\lib\site-packages\pkg_resources\__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

D:\software\Python38\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)

D:\software\Python38\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)

D:\software\Python38\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
```

我看 [142#](https://github.com/RapidAI/RapidOCR/issues/142#issue-2066649141) 的方法还以为新版本解决了，想试一下，然后就报了这样的错误

**Comment by ChaoII** [comment]
遇到了同样的问题

**Comment by DoiiarX** [comment]
paddle怎么老解决不了这种环境问题？

**Comment by wojiaoyishang** [comment]
我找到解决方法了，找不到文件是因为 torch 加载的 cudnn dll 和 Paddle 使用的 dll 冲突导致的。经过排查之后发现，Paddle 会优先使用 site-packages\paddle\nvidia\cudnn\bin 下的 dll ，而 torch 会使用 site-packages\torch\lib 下的 dll：

![Image](https://github.com/user-attachments/assets/231f6112-85ea-4034-b2e4-8bfdf9cd09d9)

冲突的 dll 如下：

![Image](https://github.com/user-attachments/assets/8b59a855-e322-4105-8f0f-3be9eb0da87f)

所以这里有两个解决方法，第一就是将  site-packages\torch\lib 下相关的 cuddn dll 复制到 site-packages\paddle\nvidia\cudnn\bin 下。

第二个就是直接在 pip 中删除 nvidia-cudnn-cu12 （如果是 cuda11.8 就是  nvidia-cudnn-cu11）：

```bash
pip uninstall nvidia-cudnn-cu12 
```

删除之后，paddleocr 就不会默认去使用 nvidia\cudnn\bin 下的 dll 了。

这样一来就可以共存了：

![Image](https://github.com/user-attachments/assets/52bf0e83-5907-4ca7-aa39-8705a6892ccf)

**这种方式需要电脑中已经存在cudnn的环境，不然单独使用 paddleocr 会出问题**

附上配置：

```
paddleocr                2.9.1
paddlepaddle-gpu         3.0.0rc1
torch                    2.6.0+cu126
torchaudio               2.6.0+cu126
torchsde                 0.2.6
torchvision              0.21.0+cu126
```

**Comment by lifei** [comment]
torch附带的版本：
![Image](https://github.com/user-attachments/assets/88b13f03-350e-479b-9627-ccef7c71d3e7)
paddle依赖的版本：`pip install nvidia-cudnn-cu11==8.9.4.19`
![Image](https://github.com/user-attachments/assets/c601a3a1-c28f-4bc4-a5d3-135d650fe829)

奔着这个思路，将其中一个版本升级到另一个相同的版本：`pip install nvidia-cudnn-cu11==9.1.0.70` 试一下。

然后我们会发现paddle把版本号写死了。
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddlepaddle-gpu 3.0.0b1 requires nvidia-cudnn-cu11==8.9.4.19, but you have nvidia-cudnn-cu11 9.1.0.70 which is incompatible.
Successfully installed nvidia-cudnn-cu11-9.1.0.70
```

但是不影响程序的运行：

```
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cublas\bin\cublas64_11.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cublas\bin\cublasLt64_11.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cublas\bin\nvblas64_11.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cuda_nvrtc\bin\nvrtc-builtins64_118.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cuda_nvrtc\bin\nvrtc64_112_0.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cuda_runtime\bin\cudart64_110.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cudnn\bin\cudnn64_9.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cudnn\bin\cudnn_adv64_9.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cudnn\bin\cudnn_cnn64_9.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cudnn\bin\cudnn_engines_precompiled64_9.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cudnn\bin\cudnn_engines_runtime_compiled64_9.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cudnn\bin\cudnn_graph64_9.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cudnn\bin\cudnn_heuristic64_9.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cudnn\bin\cudnn_ops64_9.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cufft\bin\cufft64_10.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cufft\bin\cufftw64_10.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\curand\bin\curand64_10.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cusolver\bin\cusolver64_11.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cusolver\bin\cusolverMg64_11.dll
C:\Software\Python3\lib\site-packages\paddle\..\nvidia\cusparse\bin\cusparse64_11.dll
```

**Comment by mijiutang** [comment]
之前也被找不到cudnn困扰了很久，不懂为什么这样。刚才试了下，先import torch就不会报错，具体推理还没试。（paddle3.0、torch2.71、cuda 12.6。）

<img width="1182" height="1038" alt="Image" src="https://github.com/user-attachments/assets/419d9d5b-7eb8-4acf-956b-e5fa582c0569" />
<img width="1180" height="832" alt="Image" src="https://github.com/user-attachments/assets/e5d1a90d-a5d3-4e13-8f97-a83e340f1127" />

**Comment by SoftCharacter** [comment]
> 我找到解决方法了，找不到文件是因为 torch 加载的 cudnn dll 和 Paddle 使用的 dll 冲突导致的。经过排查之后发现，Paddle 会优先使用 site-packages\paddle\nvidia\cudnn\bin 下的 dll ，而 torch 会使用 site-packages\torch\lib 下的 dll：
> 
> ![Image](https://github.com/user-attachments/assets/231f6112-85ea-4034-b2e4-8bfdf9cd09d9)
> 
> 冲突的 dll 如下：
> 
> ![Image](https://github.com/user-attachments/assets/8b59a855-e322-4105-8f0f-3be9eb0da87f)
> 
> 所以这里有两个解决方法，第一就是将 site-packages\torch\lib 下相关的 cuddn dll 复制到 site-packages\paddle\nvidia\cudnn\bin 下。
> 
> 第二个就是直接在 pip 中删除 nvidia-cudnn-cu12 （如果是 cuda11.8 就是 nvidia-cudnn-cu11）：
> 
> pip uninstall nvidia-cudnn-cu12 
> 删除之后，paddleocr 就不会默认去使用 nvidia\cudnn\bin 下的 dll 了。
> 
> 这样一来就可以共存了：
> 
> ![Image](https://github.com/user-attachments/assets/52bf0e83-5907-4ca7-aa39-8705a6892ccf)
> 
> **这种方式需要电脑中已经存在cudnn的环境，不然单独使用 paddleocr 会出问题**
> 
> 附上配置：
> 
> ```
> paddleocr                2.9.1
> paddlepaddle-gpu         3.0.0rc1
> torch                    2.6.0+cu126
> torchaudio               2.6.0+cu126
> torchsde                 0.2.6
> torchvision              0.21.0+cu126
> ```

正解 
但是如果你想要使用复制dll文件的方法，请先确认paddle的cuda版本和torch的是否一致。
另外你可能会发现在site-packages\paddle\路径下没有nvidia\，你可以根据报错信息手动创建，比如我的报错信息是

> OSError: [WinError 127] 找不到指定的程序。 Error loading "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\paddle\..\nvidia\cudnn\bin\cudnn_cnn64_9.dll" or one of its dependencies.

你需要先手动修改paddle的__ init __ .py文件第813-815行

<img width="708" height="229" alt="Image" src="https://github.com/user-attachments/assets/e70efdb2-538c-4266-8f98-0aa66f7b2a09" />

然后手动创建路径并拷贝dll文件

<img width="804" height="428" alt="Image" src="https://github.com/user-attachments/assets/847185f4-6888-4264-be84-8fff3460a234" />

**Comment by lxl9754** [comment]
将paddle的dll替换成torch的dll，已解决
