### ISSUE TITLE
Ubuntu 24.04 LTS , core_avx.so,_dl_sym, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/Paddle#67990]
### 请提出你的问题 Please ask your question

```python
Error: Can not import avx core while this file exists: /home/mm/anaconda3/envs/paddlex38/lib/python3.8/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "1.py", line 1, in <module>
    import paddle
  File "/home/mm/anaconda3/envs/paddlex38/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/mm/anaconda3/envs/paddlex38/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/mm/anaconda3/envs/paddlex38/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/mm/anaconda3/envs/paddlex38/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/mm/anaconda3/envs/paddlex38/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/mm/anaconda3/envs/paddlex38/lib/python3.8/site-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/home/mm/anaconda3/envs/paddlex38/lib/python3.8/site-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /home/mm/anaconda3/envs/paddlex38/lib/python3.8/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
```

**Comment by warrentdrew** [comment]
Hello, could you please provide more information about your environment, e.g. paddle version, gcc version.
