### ISSUE TITLE
RuntimeError: cudnnGetConvolutionForwardAlgorithm not found.

### ISSUE THREAD

**Issue by Ameng2126** [PaddlePaddle/Paddle#68040]
### 请提出你的问题 Please ask your question

E0905 22:01:35.493234 15876 port.cc:36] Load symbol cudnnGetConvolutionForwardAlgorithm failed.
Traceback (most recent call last):
  File "E:\Py\PaddleOCR-re\ocrDemo.py", line 20, in <module>
    main()
  File "E:\Py\PaddleOCR-re\ocrDemo.py", line 11, in main
    result = paddleocr.ocr(img)
  File "E:\Py\PaddleOCR-re\paddleocr.py", line 680, in ocr
    dt_boxes, rec_res, _ = self.__call__(img, cls)
  File "E:\Py\PaddleOCR-re\tools\infer\predict_system.py", line 76, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "E:\Py\PaddleOCR-re\tools\infer\predict_det.py", line 245, in __call__
    self.predictor.run()
RuntimeError: cudnnGetConvolutionForwardAlgorithm not found.

**Comment by Ameng2126** [comment]
![aaa](https://github.com/user-attachments/assets/96a880cd-45f4-4820-89a0-beae5384a863)
执行了该脚本报的问题

**Comment by YanhuiDua** [comment]
你好，这个是PaddleOCR的问题，可以去PaddleOCR仓库提问：https://github.com/PaddlePaddle/PaddleOCR

另外，建议确认使用的Paddle/PaddleOCR版本是匹配的
