### ISSUE TITLE
Group Sharded相关测试无法通过

### ISSUE THREAD

**Issue by TimeYWL** [PaddlePaddle/Paddle#68103]
### bug描述 Describe the Bug

**相关问题：**
在Paddle自带的单元测试中：
```
test/collective/fleet/test_dygraph_sharding_stage2.py
```
测试用例`TestDygraphShardingStage2`无法通过测试。
**运行环境：**
device: A800; docker:`registry.baidubce.com/paddlepaddle/paddle:2.6.1-gpu-cuda12.0-cudnn8.9-trt8.6`。
**运行指令：**
1.`cd test/collective/fleet`
2.`PYTHONPATH=../.. python -m unittest test_dygraph_sharding_stage2.TestDygraphShardingStage2`
**运行结果：**
第一个case：
```
Traceback (most recent call last):
  File "/workspace/Paddle/test/collective/fleet/dygraph_group_sharded_stage2.py", line 264, in <module>
    test_dp_stage2()
  File "/workspace/Paddle/test/collective/fleet/dygraph_group_sharded_stage2.py", line 212, in test_dp_stage2
    np.testing.assert_allclose(
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 797, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=0

Mismatched elements: 5001 / 1000000 (0.5%)
Max absolute difference: 1.1175871e-08
Max relative difference: 0.01386711
 x: array([[-0.050128, -0.027002,  0.0414  , ...,  0.02847 ,  0.058367,
        -0.059115],
       [-0.035266,  0.057357,  0.017441, ...,  0.002649,  0.06032 ,...
 y: array([[-0.050128, -0.027002,  0.0414  , ...,  0.02847 ,  0.058367,
        -0.059115],
       [-0.035266,  0.057357,  0.017441, ...,  0.002649,  0.06032 ,...
Traceback (most recent call last):
  File "/workspace/Paddle/test/collective/fleet/dygraph_group_sharded_stage2.py", line 264, in <module>
    test_dp_stage2()
  File "/workspace/Paddle/test/collective/fleet/dygraph_group_sharded_stage2.py", line 212, in test_dp_stage2
    np.testing.assert_allclose(
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 797, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=0

Mismatched elements: 5001 / 1000000 (0.5%)
Max absolute difference: 1.1175871e-08
Max relative difference: 0.01386711
 x: array([[-0.050128, -0.027002,  0.0414  , ...,  0.02847 ,  0.058367,
        -0.059115],
       [-0.035266,  0.057357,  0.017441, ...,  0.002649,  0.06032 ,...
 y: array([[-0.050128, -0.027002,  0.0414  , ...,  0.02847 ,  0.058367,
        -0.059115],
       [-0.035266,  0.057357,  0.017441, ...,  0.002649,  0.06032 ,...
```
第三个case：
```
Traceback (most recent call last):
  File "/workspace/Paddle/test/collective/fleet/dygraph_group_sharded_stage2_comm_overlap.py", line 253, in <module>
    test_dp_stage2()
  File "/workspace/Paddle/test/collective/fleet/dygraph_group_sharded_stage2_comm_overlap.py", line 203, in test_dp_stage2
    np.testing.assert_allclose(
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 797, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=0

Mismatched elements: 5001 / 1000000 (0.5%)
Max absolute difference: 1.1175871e-08
Max relative difference: 0.01386711
 x: array([[-0.050128, -0.027002,  0.0414  , ...,  0.02847 ,  0.058367,
        -0.059115],
       [-0.035266,  0.057357,  0.017441, ...,  0.002649,  0.06032 ,...
 y: array([[-0.050128, -0.027002,  0.0414  , ...,  0.02847 ,  0.058367,
        -0.059115],
       [-0.035266,  0.057357,  0.017441, ...,  0.002649,  0.06032 ,...
Traceback (most recent call last):
  File "/workspace/Paddle/test/collective/fleet/dygraph_group_sharded_stage2_comm_overlap.py", line 253, in <module>
    test_dp_stage2()
  File "/workspace/Paddle/test/collective/fleet/dygraph_group_sharded_stage2_comm_overlap.py", line 203, in test_dp_stage2
    np.testing.assert_allclose(
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 797, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=1e-06, atol=0

Mismatched elements: 5001 / 1000000 (0.5%)
Max absolute difference: 1.1175871e-08
Max relative difference: 0.01386711
 x: array([[-0.050128, -0.027002,  0.0414  , ...,  0.02847 ,  0.058367,
        -0.059115],
       [-0.035266,  0.057357,  0.017441, ...,  0.002649,  0.06032 ,...
 y: array([[-0.050128, -0.027002,  0.0414  , ...,  0.02847 ,  0.058367,
        -0.059115],
       [-0.035266,  0.057357,  0.017441, ...,  0.002649,  0.06032 ,...
[2024-09-10 05:04:21,239] [   ERROR] launch_utils.py:551 - ABORT!!! Out of all ['127.0.0.1:45681', '127.0.0.1:38423'] trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
E
======================================================================
ERROR: test_dygraph_sharding_stage2 (test_dygraph_sharding_stage2.TestDygraphShardingStage2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/Paddle/test/collective/fleet/test_dygraph_sharding_stage2.py", line 25, in test_dygraph_sharding_stage2
    self.run_mnist_2accelerators('dygraph_group_sharded_stage2.py')
  File "/workspace/Paddle/test/legacy_test/test_parallel_dygraph_dataparallel.py", line 204, in run_mnist_2accelerators
    alive = watch_local_trainers(procs, cluster.trainers_endpoints())
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/utils/launch_utils.py", line 544, in watch_local_trainers
    sys.exit(1)
SystemExit: 1

======================================================================
ERROR: test_dygraph_sharding_stage2_with_comm_overlap (test_dygraph_sharding_stage2.TestDygraphShardingStage2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/Paddle/test/collective/fleet/test_dygraph_sharding_stage2.py", line 31, in test_dygraph_sharding_stage2_with_comm_overlap
    self.run_mnist_2accelerators(
  File "/workspace/Paddle/test/legacy_test/test_parallel_dygraph_dataparallel.py", line 204, in run_mnist_2accelerators
    alive = watch_local_trainers(procs, cluster.trainers_endpoints())
  File "/usr/local/lib/python3.10/dist-packages/paddle/distributed/utils/launch_utils.py", line 544, in watch_local_trainers
    sys.exit(1)
SystemExit: 1

----------------------------------------------------------------------
Ran 3 tests in 219.207s

FAILED (errors=2)
```

**Comment by pkuzyc** [comment]
在最新的 develop 下单测正常，可以拉一下最新的代码。

我这边的本地测试命令：
```
cd build
ctest -R test_dygraph_sharding_stage2 -V
```

测试结果：
<img width="623" alt="image" src="https://github.com/user-attachments/assets/3f2fca6b-0589-44e6-bd53-5716ba17cb06">

**Comment by TimeYWL** [comment]
你好，我这边在最新的commit上编译出来的Paddle同样有这种问题：

![image](https://github.com/user-attachments/assets/a68db7ea-84c2-43fc-8b98-852302d6aa7c)

具体错误跟上面提出来的详情一致。

**Comment by TimeYWL** [comment]
> 在最新的 develop 下单测正常，可以拉一下最新的代码。
> 
> 我这边的本地测试命令：
> 
> ```
> cd build
> ctest -R test_dygraph_sharding_stage2 -V
> ```
> 
> 测试结果： <img alt="image" width="623" src="https://private-user-images.githubusercontent.com/32740647/365638545-3f2fca6b-0589-44e6-bd53-5716ba17cb06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMjAzNzgsIm5iZiI6MTcyNjAyMDA3OCwicGF0aCI6Ii8zMjc0MDY0Ny8zNjU2Mzg1NDUtM2YyZmNhNmItMDU4OS00NGU2LWJkNTMtNTcxNmJhMTdjYjA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDAyMDExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNWQwYWEyYjA3ZjJjMDMzOGQyODBhNjg3YzkzODU5ZGZmMDNmNzdhMmE5OTYyZTFiMTZiN2EyMzAyYTY2NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xlf1-EDxSRyLl44tRZzaPdFFyGeb2Pnzg3Z_fbjevZs">

请问可以告知一下您的测试环境吗？

**Comment by pkuzyc** [comment]
我是 V100 的 gpu，cuda11.8，nccl 12.15.5

**Comment by TimeYWL** [comment]
> 我是 V100 的 gpu，cuda11.8，nccl 12.15.5

我这边是A800，cuda 12.0， nccl 2.17.1，有什么办法可以规避这个错误吗? :(

**Comment by pkuzyc** [comment]
改一下环境变量，NVIDIA_TF32_OVERRIDE=0，我这边测试可以通过

**Comment by TimeYWL** [comment]
> PYTHONPATH=../.. python -m unittest test_dygraph_sharding_stage2.TestDygraphShardingStage2

我这边加了这个环境变量后，可以过了，可以请教一下这个环境变量的作用嘛

**Comment by pkuzyc** [comment]
设置成0表示禁止使用 TF32 格式去计算，TF32的精度比 float32 低，导致结果不一样了
