### ISSUE TITLE
npu 安装后未通过健康检查

### ISSUE THREAD

**Issue by ShaunLeeblob** [PaddlePaddle/Paddle#68398]
### bug描述 Describe the Bug

$python -c "import paddle; paddle.utils.run_check()"
I0924 10:13:14.683907 1205166 init.cc:236] ENV [CUSTOM_DEVICE_ROOT]=/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.10/site-packages/paddle_custom_device
I0924 10:13:14.683976 1205166 init.cc:145] Try loading custom device libs from: [/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.10/site-packages/paddle_custom_device]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.10/site-packages/paddle/__init__.py", line 33, in <module>
    from .base import core  # noqa: F401
  File "/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.10/site-packages/paddle/base/__init__.py", line 207, in <module>
    __bootstrap__()
  File "/home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.10/site-packages/paddle/base/__init__.py", line 199, in __bootstrap__
    core.init_devices()
ValueError: (InvalidArgument) Fail to open library: /home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.10/site-packages/paddle_custom_device/libpaddle-custom-npu.so with error: libatb.so: cannot open shared object file: No such file or directory
  [Hint: dso_handle should not be null.] (at /paddle/paddle/fluid/platform/init.cc:152)

**Comment by wangguan1995** [comment]
@Sunting78

**Comment by rover5056** [comment]
请问这个问题解决了么？

**Comment by flow3rdown** [comment]
请问这个问题解决了吗？
