### ISSUE TITLE
cannot import properly on windows with python3.10

### ISSUE THREAD

**Issue by jianlins** [PaddlePaddle/Paddle#68620]
### 🔎 Search before asking

- [X] I have searched the PaddleOCR [Docs](https://paddlepaddle.github.io/PaddleOCR/) and found no similar bug report.
- [X] I have searched the PaddleOCR [Issues](https://github.com/PaddlePaddle/PaddleOCR/issues) and found no similar bug report.
- [X] I have searched the PaddleOCR [Discussions](https://github.com/PaddlePaddle/PaddleOCR/discussions) and found no similar bug report.

### 🐛 Bug (问题描述)

When using: 
from paddleocr import PaddleOCR
Get the following error:
lib\site-packages\paddle\base\core.py:375
    [366](file:///xxxxx/lib/site-packages/paddle/base/core.py:366) if has_paddle_dy_lib:
    [367](file:///xxxxx/lib/site-packages/paddle/base/core.py:367)     sys.stderr.write(
    [368](file:///xxxxx/lib/site-packages/paddle/base/core.py:368)         'Error: Can not import paddle core while this file exists: '
    [369](file:///xxxxx/lib/site-packages/paddle/base/core.py:369)         + current_path
   (...)
    [373](file:///xxxxx/lib/site-packages/paddle/base/core.py:373)         + '\n'
    [374](file:///xxxxx/lib/site-packages/paddle/base/core.py:374)     )
--> [375](file:///xxxxx/lib/site-packages/paddle/base/core.py:375) if not avx_supported() and libpaddle.is_compiled_with_avx():
    [376](file:///xxxxx/lib/site-packages/paddle/base/core.py:376)     sys.stderr.write(
    [377](file:///xxxxx/lib/site-packages/paddle/base/core.py:377)         "Error: Your machine doesn't support AVX, but the installed PaddlePaddle is avx core, "
    [378](file:///xxxxx/lib/site-packages/paddle/base/core.py:378)         "you should reinstall paddlepaddle with no-avx core.\n"
    [379](file:///xxxxx/lib/site-packages/paddle/base/core.py:379)     )
    [380](file:///xxxxx/lib/site-packages/paddle/base/core.py:380) raise e

NameError: name 'libpaddle' is not defined

### 🏃‍♂️ Environment (运行环境)

on windows 11 arm, not sure if other windows have the same issue.
conda create --name testocr python=3.10 pip
pip install  paddlepaddle paddleocr

### 🌰 Minimal Reproducible Example (最小可复现问题的Demo)

python -c "from paddleocr import PaddleOCR;"

**Comment by wangna11BD** [comment]
你的paddle未成功安装，windows安装paddle需要avx的包，你的机器不支持avx，可以运行paddle.utils.run_check() 确认paddle未成功安装。

**Comment by jianlins** [comment]
There is no avx here: https://github.com/PaddlePaddle/Paddle/blob/develop/python/requirements.txt
Is this package I should try to install ? https://pypi.org/project/avx/
But this is likely a python2 package.

**Comment by xuxinyi389** [comment]
arm 架构不支持 avx指令集，你在历史编译产物里找到如下链接，你可以安装Python3.8后使用： https://paddle-wheel.bj.bcebos.com/2.4.2/windows/windows-cpu-noavx-mkl-vs2017/paddlepaddle-2.4.2-cp38-cp38-win_amd64.whl

**Comment by Thomastar** [comment]
**环境如下**
CPU：鲲鹏920
系统：麒麟V10-sp2
ARM64架构
安装的paddle是使用：[paddlepaddle-3.0.0-cp310-cp310-manylinux2014_aarch64.whl](https://paddle-whl.bj.bcebos.com/stable/cpu/paddlepaddle/paddlepaddle-3.0.0-cp310-cp310-manylinux2014_aarch64.whl)


**问题如下**
我使用 paddle.utils.run_check() 是显示成功的。但是也是抛出异常：
`Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/paddle/base/core.py", line 267, in <module>
    from . import libpaddle
ImportError: /lib64/libgomp.so.1: cannot allocate memory in static TLS block

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ocr/code/ocr/test.py", line 12, in <module>
    ocr = PaddleOCR(
  File "/usr/local/lib/python3.10/site-packages/paddleocr/_pipelines/ocr.py", line 144, in __init__
    super().__init__(**base_params)
  File "/usr/local/lib/python3.10/site-packages/paddleocr/_pipelines/base.py", line 73, in __init__
    self.paddlex_pipeline = self._create_paddlex_pipeline()
  File "/usr/local/lib/python3.10/site-packages/paddleocr/_pipelines/base.py", line 106, in _create_paddlex_pipeline
    kwargs = prepare_common_init_args(None, self._common_args)
  File "/usr/local/lib/python3.10/site-packages/paddleocr/_common_args.py", line 81, in prepare_common_init_args
    from paddle.inference import Config
  File "/usr/local/lib/python3.10/site-packages/paddle/__init__.py", line 38, in <module>
    from .base import core  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/paddle/base/__init__.py", line 38, in <module>
    from . import (  # noqa: F401
  File "/usr/local/lib/python3.10/site-packages/paddle/base/backward.py", line 28, in <module>
    from . import core, framework, log_helper, unique_name
  File "/usr/local/lib/python3.10/site-packages/paddle/base/core.py", line 382, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined`
