### ISSUE TITLE
使用reader.py读取灰度图像时报错,is_color=True是是正常的,但是is_color=False就错了

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#6875]
使用[https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L12](https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L12)读取图片时,代码如下:
```
def train_mapper(sample):
    '''
    map image path to type needed by model input layer for the training set
    '''
    img, label = sample
    img = paddle.image.load_image(img,is_color=False)
    print img.size
    img = paddle.image.simple_transform(img, 256, 28, True)
    return img.flatten().astype('float32'), label
```
当`img = paddle.image.load_image(img,is_color=False)`设`is_color=True`是是正常的,但是`is_color=False`就错了,报错如下:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 271, in handle_worker
    r = mapper(sample)
  File "/media/wang/软件/ubuntu/paddlepaddle/pycharm/PycharmProjects/TestVerificationCode/myreader.py", line 13, in train_mapper
    img = paddle.image.simple_transform(img, 256, 28, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 289, in simple_transform
    im = resize_short(im, resize_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 158, in resize_short
    assert im.shape[-1] == 1 or im.shape[-1] == 3
AssertionError
```
项目GitHub地址：[https://github.com/yeyupiaoling/TestVerificationCode](https://github.com/yeyupiaoling/TestVerificationCode)

**Comment by livc** [comment]
https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L13

**Comment by yeyupiaoling** [comment]
@livc 
* [https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py#L277](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py#L277)这行代码的`is_color=False`参数根本就没有用上
* 所以在这一行代码[https://github.com/yeyupiaoling/TestVerificationCode/blob/master/myreader.py#L22](https://github.com/yeyupiaoling/TestVerificationCode/blob/master/myreader.py#L22)就已经是报错的了.

**Comment by livc** [comment]
看你的log报错是在这行
`img = paddle.image.simple_transform(img, 256, 28, True)`

而不是
`img = paddle.image.load_image(img,is_color=False)`

**Comment by yeyupiaoling** [comment]
但是我按照你说的

> https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L13
加个参数 is_color=False

也是出错哦，是不是调用的方法不对，`img = paddle.image.simple_transform(img, 256, 28, True)`

**Comment by livc** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py#L166

这个assert判断图像是否是灰度的标准是根据通道数，但你的灰度图像的输入可能是二维的，也就是没有第三个通道维度（如果有应该是1），因此这个assert没过，你可以先把这行注释掉试试。

**Comment by yeyupiaoling** [comment]
把这代码[https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py#L166](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py#L166)注释之后,还是报错,报错如下:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 271, in handle_worker
    r = mapper(sample)
  File "/media/wang/软件/ubuntu/paddlepaddle/pycharm/PycharmProjects/TestVerificationCode/myreader.py", line 13, in train_mapper
    img = image.simple_transform(img, 256, 28, True)
  File "/media/wang/软件/ubuntu/paddlepaddle/pycharm/PycharmProjects/TestVerificationCode/image.py", line 312, in simple_transform
    im = random_crop(im, crop_size)
  File "/media/wang/软件/ubuntu/paddlepaddle/pycharm/PycharmProjects/TestVerificationCode/image.py", line 254, in random_crop
    im = im[h_start:h_end, w_start:w_end, :]
IndexError: too many indices for array
```
我打印了`print "There im.shape[-1] is %d" % im.shape[-1]`,输出如下:
`There im.shape[-1] is 28`
为什么不是那行代码中的,输出1或3

**Comment by livc** [comment]
> 但你的灰度图像的输入可能是二维的，也就是没有第三个通道维度（如果有应该是1），因此这个assert没过

你这样处理吧
```
    img = paddle.image.load_image(img,is_color=False)
    (x, y) = img.shape
    img = img.reshape(x, y, 1)
    img = paddle.image.simple_transform(img, 256, 28, True)
```

**Comment by yeyupiaoling** [comment]
@livc 还是包前面的错
```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 271, in handle_worker
    r = mapper(sample)
  File "/media/wang/软件/ubuntu/paddlepaddle/pycharm/PycharmProjects/TestVerificationCode/myreader.py", line 14, in train_mapper
    img = paddle.image.simple_transform(img, 256, 28, True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 291, in simple_transform
    im = random_crop(im, crop_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/image.py", line 240, in random_crop
    im = im[h_start:h_end, w_start:w_end, :]
IndexError: too many indices for array
```
你能run一下我[https://github.com/yeyupiaoling/TestVerificationCode](https://github.com/yeyupiaoling/TestVerificationCode)这个例子吗?看看是什么问题,谢谢您

**Comment by livc** [comment]
在 
https://github.com/PaddlePaddle/Paddle/blob/d4d8f742a3bc4366bf410bc9ff29c0c32666bf60/python/paddle/v2/image.py#L307
之后同样加上两行
```python
    (x, y) = im.shape
    im = im.reshape(x, y, 1)
```

**Comment by yeyupiaoling** [comment]
@livc 可以正常使用了,感谢感谢
