### ISSUE TITLE
 paddle.utils.run_check()报错

### ISSUE THREAD

**Issue by Catherine-aka** [PaddlePaddle/Paddle#69096]
### bug描述 Describe the Bug

在环境里执行 paddle.utils.run_check()报错信息如下：
![image](https://github.com/user-attachments/assets/ae0b534b-5c53-4b9b-a8f8-91a5225ccd19)
根据提示信息，nvcc --version查看cuda的版本是11.8，随后在paddle官网安装建议版本的paddlepaddle-gpu，
![image](https://github.com/user-attachments/assets/56f9c446-fbe1-4e46-bb5f-2a55b8244207)
再次执行paddle.utils.run_check()还是同样的报错。

**Comment by risemeup1** [comment]
你好，sm90架构需要paddle的包是cuda12，你安装cuda12.3就好，不用管你本地的cuda版本，我们的包不依赖你本地额cuda的版本，即使你的环境是cuda11.8也可以用我们的cuda12。3的包

**Comment by chenyu-x** [comment]
> 你好，sm90架构需要paddle的包是cuda12，你安装cuda12.3就好，不用管你本地的cuda版本，我们的包不依赖你本地额cuda的版本，即使你的环境是cuda11.8也可以用我们的cuda12。3的包

我机器的驱动是12.2，cuda要安装12.3吗？
Fri Nov  1 00:11:10 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.06             Driver Version: 535.183.06   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  CF-NG-HZZ1-O                   On  | 00000000:18:00.0 Off |                    0 |
| N/A   52C    P0             190W / 700W |  70062MiB / 81559MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  CF-NG-HZZ1-O                   On  | 00000000:38:00.0 Off |                    0 |
| N/A   39C    P0             173W / 700W |  70124MiB / 81559MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  CF-NG-HZZ1-O                   On  | 00000000:49:00.0 Off |                    0 |
| N/A   51C    P0             184W / 700W |  70110MiB / 81559MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  CF-NG-HZZ1-O                   On  | 00000000:59:00.0 Off |                    0 |
| N/A   37C    P0             170W / 700W |  70124MiB / 81559MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   4  CF-NG-HZZ1-O                   On  | 00000000:9B:00.0 Off |                    0 |
| N/A   38C    P0             166W / 700W |  70110MiB / 81559MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   5  CF-NG-HZZ1-O                   On  | 00000000:BB:00.0 Off |                    0 |
| N/A   51C    P0             174W / 700W |  70126MiB / 81559MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   6  CF-NG-HZZ1-O                   On  | 00000000:CA:00.0 Off |                    0 |
| N/A   36C    P0             165W / 700W |  70118MiB / 81559MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   7  CF-NG-HZZ1-O                   On  | 00000000:DA:00.0 Off |                    0 |
| N/A   51C    P0             175W / 700W |  69732MiB / 81559MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

**Comment by chenyu-x** [comment]
> 你好，sm90架构需要paddle的包是cuda12，你安装cuda12.3就好，不用管你本地的cuda版本，我们的包不依赖你本地额cuda的版本，即使你的环境是cuda11.8也可以用我们的cuda12。3的包

无论安装2.6.1还是3.0的带cuda12的paddlepaddle-gpu，import paddle都会出现以下问题：
Error: Can not import paddle core while this file exists: /home/ray/anaconda3/lib/python3.9/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ray/anaconda3/lib/python3.9/site-packages/paddle/__init__.py", line 33, in <module>
    from .base import core  # noqa: F401
  File "/home/ray/anaconda3/lib/python3.9/site-packages/paddle/base/__init__.py", line 38, in <module>
    from . import (  # noqa: F401
  File "/home/ray/anaconda3/lib/python3.9/site-packages/paddle/base/backward.py", line 25, in <module>
    from . import core, framework, log_helper, unique_name
  File "/home/ray/anaconda3/lib/python3.9/site-packages/paddle/base/core.py", line 384, in <module>
    raise e
  File "/home/ray/anaconda3/lib/python3.9/site-packages/paddle/base/core.py", line 267, in <module>
    from . import libpaddle
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /home/ray/anaconda3/lib/python3.9/site-packages/paddle/base/libpaddle.so)

**Comment by ccl-private** [comment]
@Catherine-aka 这个问题我今天刚解决，是gcc版本要11,把系统gcc升级到11才有CXXABI_1.3.13
这个命令可以看你现在是否支持CXXABI_1.3.13：
nm -D /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI

如果你是ubuntu20系统
sudo apt install --reinstall ca-certificates
sudo add-apt-repository --update ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-11 g++-11
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 160
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 160
在看看CXXABI_1.3.13是否已经有了nm -D /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI
有就成功了

**Comment by chenyu-x** [comment]
> 你好，sm90架构需要paddle的包是cuda12，你安装cuda12.3就好，不用管你本地的cuda版本，我们的包不依赖你本地额cuda的版本，即使你的环境是cuda11.8也可以用我们的cuda12。3的包

![image](https://github.com/user-attachments/assets/0ee9cbce-d29a-4c62-99b9-06aa815120c1)
安装完提示报错，cuda的驱动是12.2，但是paddle使用的cuda是12.3还是报错不兼容。所以sm90架构需要cuda12，但是官方只有cuda12.3的paddle版本吗？

**Comment by chenyu-x** [comment]
> @Catherine-aka 这个问题我今天刚解决，是gcc版本要11,把系统gcc升级到11才有CXXABI_1.3.13 这个命令可以看你现在是否支持CXXABI_1.3.13： nm -D /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI
> 
> 如果你是ubuntu20系统 sudo apt install --reinstall ca-certificates sudo add-apt-repository --update ppa:ubuntu-toolchain-r/test sudo apt update sudo apt install gcc-11 g++-11 sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 160 sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 160 在看看CXXABI_1.3.13是否已经有了nm -D /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXXABI 有就成功了

感谢！！，gcc这个问题已经解决！

**Comment by risemeup1** [comment]
cuda12.3的包就可以啊，你不用关心你本地的cuda版本，直接下载paddle的官网的cuda12.3的包，我理解是可以用的，是遇到什么问题了吗？

**Comment by chenyu-x** [comment]
> cuda12.3的包就可以啊，你不用关心你本地的cuda版本，直接下载paddle的官网的cuda12.3的包，我理解是可以用的，是遇到什么问题了吗？

目前安装了paddle3.0.0b1cuda12.3,运行了一个简单的矩阵运算，nvidia-smi能看到gpu被使用，结果也正确。但是会有这个warning，是paddle编译的cuda版本和runtime API版本不同，这个问题需要解决吗，看提示问题还不小
![image](https://github.com/user-attachments/assets/4cf20fdd-c2ec-4b03-a901-d6f8158a8860)

**Comment by HAweiqi** [comment]
nvcc -V：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

nvidia-smi：
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 472.19       Driver Version: 472.19       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A    0C    P8     2W /  N/A |    134MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

cuda安装的是10.2， cudnn7.6.x，paddle-gpu=2.5.2，运行的时候报错，我看官网里面paddle-gpu=2.5.2是支持CUDA10.2的啊，
# CUDA 10.2
python -m pip install paddlepaddle-gpu==2.5.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
为什么运行的时候还是出现下面的错误啊？

W1223 11:46:16.143543  1652 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.4, Runtime API Version: 11.8
W1223 11:46:16.144539  1652 dynamic_loader.cc:274] Note: [Recommend] copy cudnn into CUDA installation directory.
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.

**Comment by HAweiqi** [comment]
运行paddle.utils.run_check()的时候还出现了下面的报错，请问这要怎么解决啊？
![HZOKA8%B0JRR_D`}V3TLKO6](https://github.com/user-attachments/assets/f49128d4-9b22-4f77-bd55-1d9a1205bda1)
