### ISSUE TITLE
OpTest和Paddle API冲突

### ISSUE THREAD

**Issue by TimeYWL** [PaddlePaddle/Paddle#69416]
### bug描述 Describe the Bug

运行test/legacy_test下面的测试用例，会报以下错误：
```
ERROR: test_check_output (test_activation_op.TestExpFp32_Prim)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/Paddle-Develop/build/test/legacy_test/test_activation_op.py", line 132, in test_check_output
    self.check_output(
  File "/workspace/Paddle-Develop/build/test/legacy_test/op_test.py", line 2954, in check_output
    res = self.check_output_with_place(
  File "/workspace/Paddle-Develop/build/test/legacy_test/op_test.py", line 2787, in check_output_with_place
    dygraph_checker.check()
  File "/workspace/Paddle-Develop/build/test/legacy_test/op_test.py", line 2334, in check
    self.calculate_output()
  File "/workspace/Paddle-Develop/build/test/legacy_test/op_test.py", line 2406, in calculate_output
    dygraph_outs = self.op_test._calc_python_api_output(place)
  File "/workspace/Paddle-Develop/build/test/legacy_test/op_test.py", line 1160, in _calc_python_api_output
    else self.append_input_output_for_dygraph(
  File "/workspace/Paddle-Develop/build/test/legacy_test/op_test.py", line 1064, in append_input_output_for_dygraph
    v = create_var(
  File "/workspace/Paddle-Develop/build/test/legacy_test/op_test.py", line 1013, in create_var
    type=core.VarDesc.VarType.DENSE_TENSOR,
AttributeError: type object 'paddle.base.libpaddle.VarType' has no attribute 'DENSE_TENSOR'
```
怀疑是paddle最新的api和OpTest之间使用的api有冲突？

**Comment by co63oc** [comment]
core.VarDesc.VarType.LOD_TENSOR已修改为core.VarDesc.VarType.DENSE_TENSOR，请 **安装** 最新版本paddle

**Comment by TimeYWL** [comment]
> DENSE_TENSOR

怀疑LOD_TENSOR修改为DENSE_TENSOR的过程中，未在rocm环境下实现，或许此[PR](https://github.com/PaddlePaddle/Paddle/pull/69341/files#diff-1e7c39fe8f6604a048ff1aaea26adae1447729f59277d085b64ca8fc6e068c1f)出了问题？
在编译develop版的paddle后，运行以下指令报错：
```
Python 3.10.12 (main, May 26 2024, 00:14:02) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import  paddle
>>> a = paddle.base.core.VarDesc.VarType.DENSE_TENSOR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'paddle.base.libpaddle.VarType' has no attribute 'DENSE_TENSOR'
>>> 
```

**Comment by co63oc** [comment]
可以查看 paddle.base.core.VarDesc.VarType.LOD_TENSOR 是否存在，如果这个存在是旧的版本

**Comment by co63oc** [comment]
![image](https://github.com/user-attachments/assets/91b91e22-4ea8-4502-9189-ac05c2c7daf9)
试了安装新版本，可能是最新版本还没有编译，那或者等新安装包编译或者用源码编译了
