### ISSUE TITLE
推理报错，之前在另一台机器上可以，换设备失败  [Hint: Expected desc.ParseFromArray(buf.get(), size) == true, but received desc.ParseFromArray(buf.get(), size):0 != true:1.] (at ..\paddle\fluid\framework\tensor_util.cc:679)   [operator < load_combine > error]

### ISSUE THREAD

**Issue by yza99016** [PaddlePaddle/Paddle#69493]
### bug描述 Describe the Bug

[2024/11/19 12:41:00] ppocr DEBUG: Namespace(help='==SUPPRESS==', use_gpu=False, use_xpu=False, use_npu=False, ir_optim=True, use_tensorrt=False, min_subgraph_size=15, precision='fp32', gpu_mem=500, gpu_id=0, image_dir=None, page_num=0, det_algorithm='DB', det_model_dir='C:\\Users\\LCYY/.paddleocr/whl\\det\\ch\\ch_PP-OCRv4_det_infer', det_limit_side_len=960, det_limit_type='max', det_box_type='quad', det_db_thresh=0.3, det_db_box_thresh=0.6, det_db_unclip_ratio=1.5, max_batch_size=10, use_dilation=False, det_db_score_mode='fast', det_east_score_thresh=0.8, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_sast_score_thresh=0.5, det_sast_nms_thresh=0.2, det_pse_thresh=0, det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, scales=[8, 16, 32], alpha=1.0, beta=1.0, fourier_degree=5, rec_algorithm='SVTR_LCNet', rec_model_dir='C:\\Users\\LCYY/.paddleocr/whl\\rec\\ch\\ch_PP-OCRv4_rec_infer', rec_image_inverse=True, rec_image_shape='3, 48, 320', rec_batch_num=6, max_text_length=25, rec_char_dict_path='C:\\Users\\LCYY\\anaconda3\\envs\\ocrr\\lib\\site-packages\\paddleocr\\ppocr\\utils\\ppocr_keys_v1.txt', use_space_char=True, vis_font_path='./doc/fonts/simfang.ttf', drop_score=0.5, e2e_algorithm='PGNet', e2e_model_dir=None, e2e_limit_side_len=768, e2e_limit_type='max', e2e_pgnet_score_thresh=0.5, e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_pgnet_valid_set='totaltext', e2e_pgnet_mode='fast', use_angle_cls=False, cls_model_dir=None, cls_image_shape='3, 48, 192', label_list=['0', '180'], cls_batch_num=6, cls_thresh=0.9, enable_mkldnn=False, cpu_threads=10, use_pdserving=False, warmup=False, sr_model_dir=None, sr_image_shape='3, 32, 128', sr_batch_num=1, draw_img_save_dir='./inference_results', save_crop_res=False, crop_res_save_dir='./output', use_mp=False, total_process_num=1, process_id=0, benchmark=False, save_log_path='./log_output/', show_log=True, use_onnx=False, output='./output', table_max_len=488, table_algorithm='TableAttn', table_model_dir='C:\\Users\\LCYY/.paddleocr/whl\\table\\ch_ppstructure_mobile_v2.0_SLANet_infer', merge_no_span_structure=True, table_char_dict_path='C:\\Users\\LCYY\\anaconda3\\envs\\ocrr\\lib\\site-packages\\paddleocr\\ppocr\\utils\\dict\\table_structure_dict_ch.txt', layout_model_dir='C:\\Users\\LCYY/.paddleocr/whl\\layout\\picodet_lcnet_x1_0_fgd_layout_cdla_infer', layout_dict_path='C:\\Users\\LCYY\\anaconda3\\envs\\ocrr\\lib\\site-packages\\paddleocr\\ppocr\\utils\\dict\\layout_dict\\layout_cdla_dict.txt', layout_score_threshold=0.5, layout_nms_threshold=0.5, kie_algorithm='LayoutXLM', ser_model_dir=None, re_model_dir=None, use_visual_backbone=True, ser_dict_path='../train_data/XFUND/class_list_xfun.txt', ocr_order_method=None, mode='structure', image_orientation=False, layout=True, table=True, ocr=True, recovery=False, use_pdf2docx_api=False, invert=False, binarize=False, alphacolor=(255, 255, 255), lang='ch', det=True, rec=True, type='ocr', ocr_version='PP-OCRv4', structure_version='PP-StructureV2')
[libprotobuf ERROR C:\home\workspace\Paddle\third_party\protobuf\src\google\protobuf\message_lite.cc:121] Can't parse message of type "paddle.framework.proto.VarType.TensorDesc" because it is missing required fields: data_type
Traceback (most recent call last):
  File "C:\Users\LCYY\Desktop\pythonProject\ocr.py", line 93, in <module>
    process_pdf(pdf_file)
  File "C:\Users\LCYY\Desktop\pythonProject\ocr.py", line 86, in process_pdf
    extract_paragraphs(pdf_name, input_path, output_text_folder, output_image_folder)
  File "C:\Users\LCYY\Desktop\pythonProject\ocr.py", line 26, in extract_paragraphs
    pp_structure = PPStructure(use_gpu=True)
  File "C:\Users\LCYY\anaconda3\envs\ocrr\lib\site-packages\paddleocr\paddleocr.py", line 762, in __init__
    super().__init__(params)
  File "C:\Users\LCYY\anaconda3\envs\ocrr\lib\site-packages\paddleocr\ppstructure\predict_system.py", line 69, in __init__
    self.text_system = TextSystem(args)
  File "C:\Users\LCYY\anaconda3\envs\ocrr\lib\site-packages\paddleocr\tools\infer\predict_system.py", line 47, in __init__
    self.text_recognizer = predict_rec.TextRecognizer(args)
  File "C:\Users\LCYY\anaconda3\envs\ocrr\lib\site-packages\paddleocr\tools\infer\predict_rec.py", line 127, in __init__
    utility.create_predictor(args, 'rec', logger)
  File "C:\Users\LCYY\anaconda3\envs\ocrr\lib\site-packages\paddleocr\tools\infer\utility.py", line 280, in create_predictor
    predictor = inference.create_predictor(config)
ValueError: (InvalidArgument) Cannot parse tensor desc
  [Hint: Expected desc.ParseFromArray(buf.get(), size) == true, but received desc.ParseFromArray(buf.get(), size):0 != true:1.] (at ..\paddle\fluid\framework\tensor_util.cc:679)
  [operator < load_combine > error]

**Comment by HydrogenSulfate** [comment]
这个可能需要麻烦 @cuicheng01 看一下了，PaddleOCR的PPStructure模型

**Comment by yza99016** [comment]
解决了，把之前下载的模型删除后重新下载就可以了
