### ISSUE TITLE
[Bug] 随机出现 `expand_v2` 的 `shape` 不匹配问题

### ISSUE THREAD

**Issue by megemini** [PaddlePaddle/Paddle#69884]
### bug描述 Describe the Bug

``` python
# paddlepaddle 3.0beta 或者 dev 版本
import paddle

paddle.set_device('cpu') # gpu 也会出现同样问题

index_a = 2
index_b = 3

a = paddle.zeros([index_a, index_b])
b = paddle.rand([index_a, index_b]) > 0.5
fake = paddle.rand(a[b].shape)
# breakpoint()
a[b] = fake
print('-'*20)

```

随机出现 `expand_v2` 的 `shape` 不匹配问题：

``` shell

aistudio@jupyter-942478-8569537:~$ pip list | grep paddle
paddle2onnx         1.1.0
paddlepaddle-gpu    0.0.0.post118
aistudio@jupyter-942478-8569537:~$ python test_indices.py 
Traceback (most recent call last):
  File "test_indices.py", line 12, in <module>
    a[b] = fake
  File "/home/aistudio/.local/lib/python3.8/site-packages/paddle/base/dygraph/tensor_patch_methods.py", line 1002, in __setitem__
    return self._setitem_dygraph(item, value)
ValueError: (InvalidArgument) The value (2) of the non-singleton dimension does not match the corresponding value (3) in shape for expand_v2 op.
  [Hint: Expected vec_in_dims[i] == expand_shape[i], but received vec_in_dims[i]:2 != expand_shape[i]:3.] (at /paddle/paddle/phi/kernels/impl/expand_kernel_impl.h:65)

aistudio@jupyter-942478-8569537:~$ python test_indices.py 
--------------------
aistudio@jupyter-942478-8569537:~$ python test_indices.py 
--------------------
aistudio@jupyter-942478-8569537:~$ python test_indices.py 
Traceback (most recent call last):
  File "test_indices.py", line 12, in <module>
    a[b] = fake
  File "/home/aistudio/.local/lib/python3.8/site-packages/paddle/base/dygraph/tensor_patch_methods.py", line 1002, in __setitem__
    return self._setitem_dygraph(item, value)
ValueError: (InvalidArgument) The value (4) of the non-singleton dimension does not match the corresponding value (3) in shape for expand_v2 op.
  [Hint: Expected vec_in_dims[i] == expand_shape[i], but received vec_in_dims[i]:4 != expand_shape[i]:3.] (at /paddle/paddle/phi/kernels/impl/expand_kernel_impl.h:65)

```

paddle 2.5  版本未出现同样问题。

aistudio 环境可稳定复现此偶发问题 ～ 多位同学已复现 ～ 

@zxcd @SigureMo  @Liyulingyue @GreatV

**Comment by lijialin03** [comment]
我们正在联系相关人员解决，感谢您的反馈～

**Comment by lijialin03** [comment]
您好，相关人员反馈该问题几天前已修复，详见此PR https://github.com/PaddlePaddle/Paddle/pull/69480 ，经验证已解决，可以尝试重拉最新版本的develop版本的paddle，感谢您的反馈

**Comment by megemini** [comment]
感谢！经验证，新的 dev 版本暂未遇到问题 ～ 

官网的 dev 版本链接换掉了，之前不知道 ... ...
