### ISSUE TITLE
安装报错。

### ISSUE THREAD

**Issue by jiyuwangbupt** [PaddlePaddle/Paddle#70069]
### bug描述 Describe the Bug

(new_paddle_env) jyw@jyw-Z790-GAMING-X-AX:~$ python
Python 3.8.20 (default, Oct  3 2024, 15:24:27) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
I1209 16:01:34.574815 170444 program_interpreter.cc:212] New Executor is Running.
W1209 16:01:34.575874 170444 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.6, Runtime API Version: 11.7
W1209 16:01:34.575943 170444 dynamic_loader.cc:314] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 273, in run_check
    _run_static_single(use_cuda, use_xpu, use_custom, custom_device_name)
  File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 150, in _run_static_single
    exe.run(startup_prog)
  File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/executor.py", line 1746, in run
    res = self._run_impl(
  File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/executor.py", line 1952, in _run_impl
    ret = new_exe.run(
  File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/executor.py", line 831, in run
    tensors = self._new_exe.run(
RuntimeError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 273, in run_check
      _run_static_single(use_cuda, use_xpu, use_custom, custom_device_name)
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 135, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 31, in _simple_network
      weight = paddle.create_parameter(
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/tensor/creation.py", line 228, in create_parameter
      return helper.create_parameter(
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/layer_helper_base.py", line 444, in create_parameter
      self.startup_program.global_block().create_parameter(
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/framework.py", line 4381, in create_parameter
      initializer(param, self)
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/nn/initializer/initializer.py", line 40, in __call__
      return self.forward(param, block)
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/nn/initializer/constant.py", line 84, in forward
      op = block.append_op(
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/framework.py", line 4467, in append_op
      op = Operator(
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/framework.py", line 3016, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
      [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:64)
      [operator < fill_constant > error]
>>> exit()
(new_paddle_env) jyw@jyw-Z790-GAMING-X-AX:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
(new_paddle_env) jyw@jyw-Z790-GAMING-X-AX:~$ nvidia-smi
Mon Dec  9 16:02:21 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:01:00.0 Off |                  Off |
|  0%   48C    P0            173W /  450W |   17180MiB /  24564MiB |     33%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1712      G   /usr/lib/xorg/Xorg                             18MiB |
|    0   N/A  N/A      1861      G   /usr/bin/gnome-shell                            8MiB |
|    0   N/A  N/A      2207      G   /usr/libexec/gnome-initial-setup                6MiB |
|    0   N/A  N/A     87495      C   python                                       8612MiB |
|    0   N/A  N/A     87754      C   python                                       8500MiB |
+-----------------------------------------------------------------------------------------+

### 其他补充信息 Additional Supplementary Information

(new_paddle_env) jyw@jyw-Z790-GAMING-X-AX:~$ python
Python 3.8.20 (default, Oct  3 2024, 15:24:27) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
I1209 16:01:34.574815 170444 program_interpreter.cc:212] New Executor is Running.
W1209 16:01:34.575874 170444 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.6, Runtime API Version: 11.7
W1209 16:01:34.575943 170444 dynamic_loader.cc:314] The third-party dynamic library (libcudnn.so) that Paddle depends on is not configured correctly. (error code is /usr/local/cuda/lib64/libcudnn.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 273, in run_check
    _run_static_single(use_cuda, use_xpu, use_custom, custom_device_name)
  File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 150, in _run_static_single
    exe.run(startup_prog)
  File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/executor.py", line 1746, in run
    res = self._run_impl(
  File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/executor.py", line 1952, in _run_impl
    ret = new_exe.run(
  File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/executor.py", line 831, in run
    tensors = self._new_exe.run(
RuntimeError: In user code:

    File "<stdin>", line 1, in <module>
      
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 273, in run_check
      _run_static_single(use_cuda, use_xpu, use_custom, custom_device_name)
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 135, in _run_static_single
      input, out, weight = _simple_network()
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/utils/install_check.py", line 31, in _simple_network
      weight = paddle.create_parameter(
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/tensor/creation.py", line 228, in create_parameter
      return helper.create_parameter(
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/layer_helper_base.py", line 444, in create_parameter
      self.startup_program.global_block().create_parameter(
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/framework.py", line 4381, in create_parameter
      initializer(param, self)
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/nn/initializer/initializer.py", line 40, in __call__
      return self.forward(param, block)
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/nn/initializer/constant.py", line 84, in forward
      op = block.append_op(
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/framework.py", line 4467, in append_op
      op = Operator(
    File "/home/jyw/anaconda3/envs/new_paddle_env/lib/python3.8/site-packages/paddle/base/framework.py", line 3016, in __init__
      for frame in traceback.extract_stack():

    PreconditionNotMetError: Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
      [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:64)
      [operator < fill_constant > error]
>>> exit()
(new_paddle_env) jyw@jyw-Z790-GAMING-X-AX:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
(new_paddle_env) jyw@jyw-Z790-GAMING-X-AX:~$ nvidia-smi
Mon Dec  9 16:02:21 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:01:00.0 Off |                  Off |
|  0%   48C    P0            173W /  450W |   17180MiB /  24564MiB |     33%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1712      G   /usr/lib/xorg/Xorg                             18MiB |
|    0   N/A  N/A      1861      G   /usr/bin/gnome-shell                            8MiB |
|    0   N/A  N/A      2207      G   /usr/libexec/gnome-initial-setup                6MiB |
|    0   N/A  N/A     87495      C   python                                       8612MiB |
|    0   N/A  N/A     87754      C   python                                       8500MiB |
+-----------------------------------------------------------------------------------------+

**Comment by risemeup1** [comment]
find / -name "libcudnn.so"在哪儿，找到之后，export LD_LIBRARY_PATH=这个目录，然后试试可以解决吗

**Comment by jiyuwangbupt** [comment]
> find / -name "libcudnn.so"在哪儿，找到之后，export LD_LIBRARY_PATH=这个目录，然后试试可以解决吗

不可以，我在很久之前镜像里面安装的版本是可以的。然后现在我想在conda虚拟环境下安装发现不行。

**Comment by jiyuwangbupt** [comment]
> find / -name "libcudnn.so"在哪儿，找到之后，export LD_LIBRARY_PATH=这个目录，然后试试可以解决吗

https://github.com/PaddlePaddle/Paddle/issues/70393。我重新又开了个conda虚拟环境，现在变成这样了
