### ISSUE TITLE
error in sentiment preprocess

### ISSUE THREAD

**Issue by leonardgithub** [PaddlePaddle/Paddle#704]
version: cpu-devel

root@a3c00be3fe01:~/paddle/demo/sentiment# pip show paddle
---
Name: paddle
Version: 0.9.0a0
Location: /usr/local/lib/python2.7/dist-packages
Requires:

============================================================
root@a3c00be3fe01:~/paddle/demo/sentiment# ./preprocess.sh 
Start to preprcess...
Traceback (most recent call last):
  File "preprocess.py", line 359, in <module>
    main()
  File "preprocess.py", line 355, in main
    data_creator.create_dataset()
  File "preprocess.py", line 172, in create_dataset
    train_data, train_lab_set = self.data_list(self.train_dir)
  File "preprocess.py", line 132, in data_list
    label_set = get_label_set_from_dir(path)
  File "/usr/local/lib/python2.7/dist-packages/paddle/utils/preprocess_util.py", line 88, in get_label_set_from_dir
    dirs = list_dirs(path)
  File "/usr/local/lib/python2.7/dist-packages/paddle/utils/preprocess_util.py", line 55, in list_dirs
    os.path.join(path, d) for d in next(os.walk(path))[1]
StopIteration

**Comment by backyes** [comment]
@leonardgithub 

I can not recognize the root cause from log you paste. Can you show us more background informations? Thanks a lot.

**Comment by leonardgithub** [comment]
@backyes It seems OK now, just run sudo apt-get install unzip before ./preprocess.sh.
It is recommended add this command on the doc web site such as http://www.paddlepaddle.org/doc/demo/sentiment_analysis/sentiment_analysis.html, because there is no unzip in the docker image by default
