### ISSUE TITLE
Unknown input layer 'emb1_2_dot_mul' for layer concat_layer

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#7155]
RT，想使用paddle的 element wise的操作，代码如下：

emb1_2_dot_mul_op=paddle.layer.dotmul_operator(a=emb1_1_pooling,
                                               b=emb1_2_pooling)
emb1_2_dot_mul= paddle.layer.mixed(name="emb1_2_dot_mul")
emb1_2_dot_mul+=emb1_2_dot_mul_op
emb1_2_dot_mul_size=64

concat_layer=paddle.layer.concat( name="concat_layer",
                                  input=[emb1_1_pooling, emb1_2_pooling, emb1_3_pooling, emb1_4_pooling, data5, data6, emb1_7_pooling, emb1_8_pooling,
                                          data10, emb1_12, data13, data14, data15, data16, data17,
                                         emb1_18_pooling, data19, emb1_20, emb1_21, emb1_22, data23, emb1_24,emb1_25,
                                         data26, data27, data28, emb1_29, emb1_30, emb1_31, emb1_32,
                                         emb1_2_cos_sim, emb3_4_cos_sim, emb7_8_cos_sim, emb1_2_dot_mul, emb3_4_dot_mul, emb7_8_dot_mul])

但是本地运行时出如下错误，请问
1） element wise product的用法对么
2）上述错误该如何处理

[CRITICAL 2018-01-03 10:49:09,849 layers.py:2837] Unknown input layer 'emb1_2_dot_mul' for layer concat_layer
Traceback (most recent call last):
  File "dnn_experiment_online_p_daily_local.py", line 922, in <module>
    emb1_2_cos_sim, emb3_4_cos_sim, emb7_8_cos_sim, emb1_2_dot_mul, emb3_4_dot_mul, emb7_8_dot_mul])
  File "/home/forum/yishijie/paddlepaddle_loacal/paddle/python27/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/home/forum/yishijie/paddlepaddle_loacal/paddle/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/forum/yishijie/paddlepaddle_loacal/paddle/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/forum/yishijie/paddlepaddle_loacal/paddle/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 350, in wrapper
    return method(*args, **kwargs)
  File "/home/forum/yishijie/paddlepaddle_loacal/paddle/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 2837, in concat_layer
    **ExtraLayerAttribute.to_kwargs(layer_attr))
  File "/home/forum/yishijie/paddlepaddle_loacal/paddle/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3136, in Layer
    return layer_func(name, **xargs)
  File "/home/forum/yishijie/paddlepaddle_loacal/paddle/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 2835, in __init__
    name, 'concat', 0, inputs=inputs, **xargs)
  File "/home/forum/yishijie/paddlepaddle_loacal/paddle/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 1415, in __init__
    (input_layer_name, name))
  File "/home/forum/yishijie/paddlepaddle_loacal/paddle/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 156, in config_assert
    logger.fatal(msg)
  File "/home/forum/yishijie/paddlepaddle_loacal/paddle/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3482, in my_fatal
    raise Exception()
Exception

**Comment by sweetsky0901** [comment]
是emb1_2_dot_mul的类型不适合做concat_layer的输入吧。
您使用的是paddle的什么版本？

**Comment by youan1** [comment]
emb1_2_dot_mul是mixed_layer类型，不能作为concat_layer的输入么，怎么查看paddle 的版本，另外element wise product的用法对么

emb1_2_dot_mul_op=paddle.layer.dotmul_operator(a=emb1_1_pooling,
b=emb1_2_pooling)
emb1_2_dot_mul= paddle.layer.mixed(name="emb1_2_dot_mul")
emb1_2_dot_mul+=emb1_2_dot_mul_op
emb1_2_dot_mul_size=64

**Comment by typhoonzero** [comment]
Close due to low activity, feel free to reopen.
