### ISSUE TITLE
在服务器docker镜像运行generate_sequence_by_rnn_lm例子报错

### ISSUE THREAD

**Issue by Why404NotFound** [PaddlePaddle/Paddle#7194]
报错信息如下：
[CRITICAL 2018-01-04 06:38:33,743 default_decorators.py:49] Must use keyword arguments for non-positional args
Traceback (most recent call last):
  File "train.py", line 128, in <module>
    main()
  File "train.py", line 124, in main
    num_passes=20)
  File "train.py", line 47, in train
    sum_eval = paddle.evaluator.sum(topology)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 49, in __wrapper__
    "Must use keyword arguments for non-positional args")
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3517, in my_fatal
    raise Exception()

另外我在mac通过pip安装的有单机版，运行就是正常的

**Comment by wanghaox** [comment]
补充一下调用参数

Must use keyword arguments for non-positional args
应该是参数输入有问题，必须指定参数名的方式输入

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
