### ISSUE TITLE
[CRITICAL 2018-01-04 14:02:42,360 layers.py:959] Duplicated layer name: word

### ISSUE THREAD

**Issue by wrchow** [PaddlePaddle/Paddle#7198]
Test with Pass 4, {'classification_error_evaluator': 0.5014399886131287}
Training finished.
Traceback (most recent call last):
  File "query_dnn_single.py", line 170, in <module>
    dnn_infer(file_name=param_file_name)
  File "query_dnn_single.py", line 145, in dnn_infer
    out = convolution_net(dict_dim, class_dim=class_dim, is_predict=True)
  File "query_dnn_single.py", line 49, in convolution_net
    paddle.data_type.integer_value_sequence(input_dim))
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/v2/layer.py", line 88, in __data_layer__
    l = v1_layers.data_layer(name, type.dim, **kwargs)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 415, in wrapper
    return method(*args, **kwargs)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 959, in data_layer
    **ExtraLayerAttribute.to_kwargs(layer_attr))
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3933, in Layer
    return layer_func(name, **xargs)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 1985, in __init__
    name, 'data', size, inputs=[], device=device)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 1550, in __init__
    'Duplicated layer name: %s' % name)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 156, in config_assert
    logger.fatal(msg)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 4283, in my_fatal
    raise Exception()
Exception

**Comment by wrchow** [comment]
1. 出现 :code:`Duplicated layer name` 错误怎么办
--------------------------------------------------

出现该错误的原因一般是用户对不同layer的参数 :code:`name` 设置了相同的取值。遇到该错误时，先找出参数 :code:`name` 取值相同的layer，然后将这些layer的参数 :code:`name` 设置为不同的值。

**Comment by wanghaox** [comment]
请参考 https://github.com/PaddlePaddle/Paddle/issues/6328

**Comment by wrchow** [comment]
train和test不能同时执行

**Comment by defineconst** [comment]
在Flask第一次预测不抱错，发起请求第二次就报错了，有知道为什么吗？
