### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by lqniunjunlper** [PaddlePaddle/Paddle#7275]
、、、、/04.word2vec> /data/anaconda2/bin/python train.py 
Traceback (most recent call last):
  File "/data/anaconda2/lib/python2.7/site-packages/paddlepaddle_gpu-0.0.0-py2.7-linux-x86_64.egg/paddle/trainer/config_parser.py", line 85, in <module>
    from paddle.proto.DataConfig_pb2 import DataConfig
  File "/data/anaconda2/lib/python2.7/site-packages/paddlepaddle_gpu-0.0.0-py2.7-linux-x86_64.egg/paddle/proto/__init__.py", line 15, in <module>
    from paddle.proto.TrainerConfig_pb2 import OptimizationConfig, TrainerConfig
  File "/data/anaconda2/lib/python2.7/site-packages/paddlepaddle_gpu-0.0.0-py2.7-linux-x86_64.egg/paddle/proto/TrainerConfig_pb2.py", line 16, in <module>
    import DataConfig_pb2 as DataConfig__pb2
File "/data/anaconda2/lib/python2.7/site-packages/paddlepaddle_gpu-0.0.0-py2.7-linux-x86_64.egg/paddle/proto/DataConfig_pb2.py", line 41, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'

**Comment by JiayiFeng** [comment]
请问您用的是paddle book里的样例程序吗？有没有对数据集和脚本进行过修改？paddle的安装途径是什么呢？

**Comment by lqniunjunlper** [comment]
@JiayiFeng paddle是源码安装的。是样例程序，train的时候都是这个error。没有对数据集做任何修改。。。

**Comment by lqniunjunlper** [comment]
@JiayiFeng 用python 封装太多了。。。各种问题。有没有pure c++ API，NN layers用protobuf config文件做input。直接跑c++的。

**Comment by lqniunjunlper** [comment]
@JiayiFeng 感觉安装paddle花费的精力都可以自己写一个简单版的了。太不友好了啊。。。

**Comment by JiayiFeng** [comment]
我们有用来做预测的C API。这里有一个还未merge的PR，里面有各种关于C API使用的文档，供你参考：
https://github.com/PaddlePaddle/Paddle/pull/6596

**Comment by JiayiFeng** [comment]
我在本地尝试了这个demo，没有复现您遇到的问题。一般来说这个错误是Paddle版本低导致的，请试一下将Paddle和book都更新到develop分支的最新版本。

**Comment by reyoung** [comment]
这个是编译Paddle的Protobuf与系统中的Protobuf版本不一致造成的。

目前Paddle使用的protobuf版本是3.1 ， https://github.com/PaddlePaddle/Paddle/blob/develop/python/requirements.txt#L3

如果是自己编译的Paddle，请确定编译时protobuf版本和使用的protobuf版本一致。
