### ISSUE TITLE
gpu memory reuse problem

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#7313]
reproduce script benchmark/fluid/vgg16.py --data_set=flowers

```shell
Traceback (most recent call last):
  File "fluid/vgg16.py", line 176, in <module>
    main()
  File "fluid/vgg16.py", line 154, in main
    fetch_list=[avg_cost] + accuracy.metrics)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/executor.py", line 171, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.v2.fluid.core.EnforceNotMet: CUBLAS: internal error,  at [/tmp/Paddle/paddle/operators/math/math_function.cu:41]
PaddlePaddle Call Stacks:
0       0x7fe896b20857p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 727
1       0x7fe8975a83ffp void paddle::operators::math::gemm<paddle::platform::CUDADeviceContext, float>(paddle::platform::CUDADeviceContext const&, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) + 311
2       0x7fe8975a8c83p void paddle::operators::math::matmul<paddle::platform::CUDADeviceContext, float>(paddle::platform::CUDADeviceContext const&, paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, float, paddle::framework::Tensor*, float) + 869
3       0x7fe896e780aap paddle::operators::MulGradKernel<paddle::platform::CUDADeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 1994
4       0x7fe897576601p paddle::framework::OperatorWithKernel::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 2129
5       0x7fe896bd291cp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 972
6       0x7fe896b38853p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 579
7       0x7fe896b3649dp pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1229
8             0x4cad00p PyEval_EvalFrameEx + 28048
9             0x4c2705p PyEval_EvalCodeEx + 597
10            0x4ca088p PyEval_EvalFrameEx + 24856
11            0x4c2705p PyEval_EvalCodeEx + 597
12            0x4ca7dfp PyEval_EvalFrameEx + 26735
13            0x4c2705p PyEval_EvalCodeEx + 597
14            0x4c24a9p PyEval_EvalCode + 25
15            0x4f19efp
16            0x4ec372p PyRun_FileExFlags + 130
17            0x4eaaf1p PyRun_SimpleFileExFlags + 401
18            0x49e208p Py_Main + 1736
19      0x7fe8b3e7e830p __libc_start_main + 240
20            0x49da59p _start + 41

```

**Comment by chengduoZH** [comment]
> reproduce script benchmark/fluid.py 

Where is the `fluid.py`? Is this script `benchmark/fluid/vgg16.py`?

**Comment by dzhwinter** [comment]
fixed and yes. @chengduoZH

**Comment by buzzf** [comment]
how did you fix this problem? @dzhwinter  my question seems similar to yours. #10607

**Comment by dzhwinter** [comment]
This issue has been fixed if load the correct version cuda.
