### ISSUE TITLE
ci test fail, test_nce failed

### ISSUE THREAD

**Issue by wanghaox** [PaddlePaddle/Paddle#7380]
https://paddleci.ngrok.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=22716&_focus=9570

[12:25:11]	153/320 Test #154: test_nce ....................................***Failed 1.99 sec
[12:25:11]	..F.
[12:25:11]	======================================================================
[12:25:11]	FAIL: test_check_grad (__main__.TestNCECase1)
[12:25:11]	----------------------------------------------------------------------
[12:25:11]	Traceback (most recent call last):
[12:25:11]	File "test_nce.py", line 89, in test_check_grad
[12:25:11]	["Input", "Weight", "Bias"], "Cost", max_relative_error=0.02)
[12:25:11]	File "/paddle/python/paddle/v2/fluid/tests/op_test.py", line 379, in check_grad
[12:25:11]	"Gradient Check On %s" % str(cpu_place))
[12:25:11]	File "/paddle/python/paddle/v2/fluid/tests/op_test.py", line 340, in __assert_is_close
[12:25:11]	self.assertLessEqual(max_diff, max_relative_error, err_msg())
[12:25:11]	AssertionError: Gradient Check On CPUPlace Variable Input max gradient diff 181.835266 over limit 0.020000, the first error element is 0, -0.059903, 2.178237

**Comment by tonyyang-svail** [comment]
I have experienced the same problem. Any clue on this?
