### ISSUE TITLE
GPU version can not run without GPU

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#7416]
When I am trying to run the GPU verison PaddlePaddle on a machine that GPU can not be used, it shows me error:

```
Traceback (most recent call last):
  File "notest_recognize_digits_conv_dist.py", line 4, in <module>
    import paddle.v2.fluid as fluid
  File "/home/helin/.local/lib/python2.7/site-packages/paddle/v2/fluid/__init__.py", line 51, in <module>
    __read_gflags_from_env__()
  File "/home/helin/.local/lib/python2.7/site-packages/paddle/v2/fluid/__init__.py", line 46, in __read_gflags_from_env__
    core.init_devices(["CPU", "GPU:0"])
paddle.v2.fluid.core.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: no CUDA-capable device is detected at [/home/helin/repo/Paddle/paddle/platform/gpu_info.cc:32]
```

Please note that I am using CPUPlace() only for the executor, it should just run on CPU as written in code, rather than crashing.

**Comment by chengduoZH** [comment]
this issue has been solved by https://github.com/PaddlePaddle/Paddle/pull/7528
