### ISSUE TITLE
Distributed transpiled pserver ProgramDesc can not be printed by Python

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#7419]
```
print(pserver_prog.to_string(True))
```

gives error:

```
Traceback (most recent call last):
  File "notest_recognize_digits_conv_dist.py", line 58, in <module>
    print(pserver_prog.to_string(False))
  File "/home/helin/.local/lib/python2.7/site-packages/paddle/v2/fluid/framework.py", line 763, in to_string
    proto = framework_pb2.ProgramDesc.FromString(str(protostr))
  File "/home/helin/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 780, in FromString
    message.MergeFromString(s)
  File "/home/helin/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1087, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/home/helin/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1123, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/home/helin/.local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 612, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/home/helin/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1123, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/home/helin/.local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 612, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/home/helin/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1123, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/home/helin/.local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 612, in DecodeRepeatedField
    if value.add()._InternalParse(buffer, pos, new_pos) != new_pos:
  File "/home/helin/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1123, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/home/helin/.local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 502, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "/home/helin/.local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 469, in _ConvertToUnicode
    return local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf8' codec can't decode byte 0xa5 in position 1: 'utf8' codec can't decode byte 0xa5 in position 1: invalid start byte in field: paddle.framework.proto.OpDesc.Attr.s
```

From the error message it looks like Python can not parse non-utf8 `proto::string` (used by attribute "OptimizeProgram").

Being able to print string helps us to write unit test that compares the ProgramDescs, I am planning to fix it by changing attribute "OptimizeProgram"'s type to `proto::bytes`.

**Comment by helinwang** [comment]
Looks like creating `proto::bytes` is pretty hard, because we use
```
using Attribute =
    boost::variant<boost::blank, int, float, std::string, std::vector<int>,
                   std::vector<float>, std::vector<std::string>, bool,
                   std::vector<bool>, BlockDesc*>
```
to track the type (e.g., `proto::string`, `proto::bool`), but `proto::bytes` and `proto::string` both use `std::string` as the underlying c++ type.

**Comment by helinwang** [comment]
Instead, I will create unit test that verifies `optimize_sub_program` rather than the `optimize_program` (optimize_sub_program) does not need binary attribute, and currently there is not much to verify for the optimize program.

**Comment by helinwang** [comment]
I think https://github.com/PaddlePaddle/Paddle/issues/7343 is a better idea.

**Comment by typhoonzero** [comment]
I've encountered the same issue. I have to delete the `VLOG` line in `executor` to debug multinode program.
