### ISSUE TITLE
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zengjialuo** [PaddlePaddle/Paddle#7477]
在开放云的机器，原来版本是0.10.0,  遇到了多GPU预测结果错误的问题，所以升级了0.11.0。

升级方式，pip uninstall之后执行`pip install paddlepaddle_gpu-0.11.0-cp27-cp27mu-linux_x86_64.whl` （cuda8.0_cudnn5_avx_mkl版本）

跑任务时报：
```
Traceback (most recent call last):
  File "mem_test.py", line 15, in <module>
    paddle.init(use_gpu=False, trainer_count=1)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/__init__.py", line 128, in init
    import py_paddle.swig_paddle as api
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory
```

paddle version:
```
/usr/local/bin/paddle: line 40: printf: PANIC:: invalid number
PaddlePaddle 0.11.0, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF
```

请问，有什么快速的方法能解决吗？

**Comment by Yancey1989** [comment]
检查下`/usr/local/lib/`下是否有mkl的库呢？

**Comment by zengjialuo** [comment]
@Yancey1989 有

**Comment by Yancey1989** [comment]
执行下`ldconfig`，或者把`/usr/local/lib/`加到LD_LIBRARY_PATH下面吧: `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`

**Comment by zengjialuo** [comment]
嗯，解决了，谢谢@Yancey1989
