### ISSUE TITLE
CPU only unit test fails on some operators.

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#7546]
Binaries were built by `cmake -DWITH_COVERAGE=ON -DWITH_GPU=OFF -DWITH_MKL=OFF ..`

failed tests:

```
The following tests FAILED:
	147 - test_conv2d_op (Failed)
	148 - test_conv2d_transpose_op (Failed)
	149 - test_conv3d_op (Failed)
	150 - test_conv3d_transpose_op (Failed)
	219 - test_norm_op (OTHER_FAULT)
	227 - test_pool2d_op (Failed)
	228 - test_pool3d_op (Failed)
	233 - test_print_op (Failed)
	286 - test_label_semantic_roles (Failed)
```

some error logs: 
```
ERROR: test_check_output (__main__.TestCUDNNCase6)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_pool3d_op.py", line 99, in test_check_output
    self.check_output_with_place(place, atol=1e-5)
  File "/Users/baidu/go/src/github.com/PaddlePaddle/Paddle/python/paddle/v2/fluid/tests/op_test.py", line 276, in check_output_with_place
    feed_map = self.feed_var(inputs, place)
  File "/Users/baidu/go/src/github.com/PaddlePaddle/Paddle/python/paddle/v2/fluid/tests/op_test.py", line 245, in feed_var
    tensor.set(self.inputs[var_name], place)
TypeError: set(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.v2.fluid.core.Tensor, arg0: numpy.ndarray[float32], arg1: paddle::platform::CPUPlace) -> None
    2. (self: paddle.v2.fluid.core.Tensor, arg0: numpy.ndarray[int32], arg1: paddle::platform::CPUPlace) -> None
    3. (self: paddle.v2.fluid.core.Tensor, arg0: numpy.ndarray[float64], arg1: paddle::platform::CPUPlace) -> None
    4. (self: paddle.v2.fluid.core.Tensor, arg0: numpy.ndarray[int64], arg1: paddle::platform::CPUPlace) -> None
    5. (self: paddle.v2.fluid.core.Tensor, arg0: numpy.ndarray[bool], arg1: paddle::platform::CPUPlace) -> None
...
ERROR: test_backward (__main__.TestPrintOpGPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_print_op.py", line 63, in setUp
    self.x_tensor.set(tensor_np, self.place)
TypeError: set(): incompatible function arguments. The following argument types are supported:
    1. (self: paddle.v2.fluid.core.Tensor, arg0: numpy.ndarray[float32], arg1: paddle::platform::CPUPlace) -> None
    2. (self: paddle.v2.fluid.core.Tensor, arg0: numpy.ndarray[int32], arg1: paddle::platform::CPUPlace) -> None
    3. (self: paddle.v2.fluid.core.Tensor, arg0: numpy.ndarray[float64], arg1: paddle::platform::CPUPlace) -> None
    4. (self: paddle.v2.fluid.core.Tensor, arg0: numpy.ndarray[int64], arg1: paddle::platform::CPUPlace) -> None
    5. (self: paddle.v2.fluid.core.Tensor, arg0: numpy.ndarray[bool], arg1: paddle::platform::CPUPlace) -> None

Invoked with: <paddle.v2.fluid.core.LoDTensor object at 0x11fc257e0>, array([[  9.42935944e-01,   9.69691992e-01,   1.25991538e-01],
       [  3.44808817e-01,   4.29206935e-04,   3.35851520e-01]], dtype=float32), <paddle.v2.fluid.core.CUDAPlace object at 0x11fc259c0>
```

**Comment by typhoonzero** [comment]
The current CI only build with `WITH_GPU=OFF` but did not run the tests.

**Comment by chengduoZH** [comment]
https://github.com/PaddlePaddle/Paddle/blob/052c05be34c543ce9aeeea8e48de269a0c4709af/python/paddle/v2/fluid/tests/test_conv2d_op.py#L213-L216

`TestCUDNN` should check whether compiling with gpu, `core.is_compile_gpu()`.

**Comment by chengduoZH** [comment]
Maybe this [PR](https://github.com/PaddlePaddle/Paddle/pull/7536) will solve part of those problems.
