### ISSUE TITLE
ImportError: libwarpctc.so: cannot open shared object file: No such file or directory in develop branch

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#7718]
Steps to reproduce:

Build PaddlePaddle using Docker, environments:
```
export WITH_GPU=OFF
export WITH_DISTRIBUTE=ON
```

Then build a new Docker image using the output whl package, and run a fluid program results in:
```
Traceback (most recent call last):
  File "/workspace/vgg16.py", line 8, in <module>
    import paddle.v2.fluid as fluid
  File "/usr/local/lib/python2.7/site-packages/paddle/v2/fluid/__init__.py", line 17, in <module>
    import framework
  File "/usr/local/lib/python2.7/site-packages/paddle/v2/fluid/framework.py", line 21, in <module>
    from . import core
ImportError: libwarpctc.so: cannot open shared object file: No such file or directory
```

**Comment by typhoonzero** [comment]
Run `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` will fix, closing.
