### ISSUE TITLE
关于PyDataProvider2的使用

### ISSUE THREAD

**Issue by hiahiahu** [PaddlePaddle/Paddle#773]
1、求支持原始dataprovider中的StringSlot功能
2、新接口有无getNextBatch()那种可以本地单独调试dataprovider的函数？ 求支持。。
3、一边训练一边测试的时候，如果调用不同的函数，使用不同的字典，新接口用如下使用方式会报错：
![image](https://cloud.githubusercontent.com/assets/21326658/20998806/78fb2052-bd4b-11e6-943a-d7f25d76af14.png)，
求问正确的打开方式
```
Traceback (most recent call last):
  File "/home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer/config_parser.py", line 3113, in parse_config_and_serialize
    config = parse_config(config_file, config_arg_str)
  File "/home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer/config_parser.py", line 3089, in parse_config
    execfile(config_file, make_config_environment(config_file, config_args))
  File "PS76.conf", line 42, in <module>
    {'dictionary': dict_path}]
  File "/home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/data_sources.py", line 203, in define_py_data_sources2
    data_cls=None)
  File "/home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/data_sources.py", line 153, in define_py_data_sources
    train_args, train_async, data_cls)
  File "/home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/data_sources.py", line 94, in define_py_data_source
    async_load_data=async))
  File "/home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/data_sources.py", line 85, in py_data2
    data.load_data_object = load_data_object
  File "/home/hupeng/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 454, in setter
    type_checker.CheckValue(new_value)
  File "/home/hupeng/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py", line 117, in CheckValue
    raise TypeError(message)
TypeError: ['processData', 'processData_test'] has type <type 'list'>, but expected one of: (<type 'str'>, <type 'unicode'>)
F1208 13:39:52.866513 24726 PythonUtil.cpp:130] Check failed: (ret) != nullptr Python Error: <type 'exceptions.TypeError'> : ['processData', 'processData_test'] has type <type 'list'>, but expected one of: (<type 'str'>, <type 'unicode'>)
Python Callstack:
            /home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer/config_parser.py : 3113
            /home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer/config_parser.py : 3089
            PS76.conf : 42
            /home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/data_sources.py : 203
            /home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/data_sources.py : 153
            /home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/data_sources.py : 94
            /home/hupeng/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/data_sources.py : 85
            /home/hupeng/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/python_message.py : 454
            /home/hupeng/.jumbo/lib/python2.7/site-packages/google/protobuf/internal/type_checkers.py : 117
```

**Comment by backyes** [comment]
@reyoung 

麻烦给出解释，如果会开发，并给出plan

**Comment by reyoung** [comment]
> 1、求支持原始dataprovider中的StringSlot功能

目前没有plan支持这个功能，可能会支持这个功能。

> 2、新接口有无getNextBatch()那种可以本地单独调试dataprovider的函数？ 求支持。。

目前没有plan支持这个功能，也不会支持这个功能，调试code可以直接启动python进程调试。

> 一边训练一边测试的时候，如果调用不同的函数，使用不同的字典，新接口用如下使用方式会报错

请升级到最新版本。
