### ISSUE TITLE
Error caused by 'import paddle.v2.fluid as fluid':  No module named registry

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#7735]
好像是https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/layers/math_op_patch.py#L16 文件里找不到registry模块

报错信息：
```
>>> import paddle.v2.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zhangchao/.jumbo/lib/python2.7/site-packages/paddle/v2/fluid/__init__.py", line 24, in <module>
    import evaluator
  File "/home/zhangchao/.jumbo/lib/python2.7/site-packages/paddle/v2/fluid/evaluator.py", line 17, in <module>
    import layers
  File "/home/zhangchao/.jumbo/lib/python2.7/site-packages/paddle/v2/fluid/layers/__init__.py", line 27, in <module>
    import math_op_patch
  File "/home/zhangchao/.jumbo/lib/python2.7/site-packages/paddle/v2/fluid/layers/math_op_patch.py", line 16, in <module>
    from ..registry import OpProtoHolder
ImportError: No module named registry
```
git commit id:

c80af6ffaa7362dc23ca87ae9be1a8467ee948f0

**Comment by luotao1** [comment]
The same error for all the PRs now.
