### ISSUE TITLE
nce_layer() got an unexpected keyword argument 'act'

### ISSUE THREAD

**Issue by Bella-Zhao** [PaddlePaddle/Paddle#7825]
按照http://paddlepaddle.org/docs/develop/models/nce_cost/README.html
![image](https://user-images.githubusercontent.com/29970079/35324081-985af4b2-012a-11e8-99cd-0968683203e8.png)
nce层有act这个key。

但是运行以下代码：
```python
paddle.layer.nce(
                input=self._fc_1,
                label=self._target_item,
                num_classes=len(self._feature_dict['history_clicked_items']),
                param_attr=paddle.attr.Param(name="nce_w"),
                bias_attr=paddle.attr.Param(name="nce_b"),
                act=paddle.activation.Sigmoid(),
                num_neg_samples=5,
                neg_distribution=self._item_freq)
```
报错：
```
Traceback (most recent call last):
  File "train.py", line 126, in <module>
    train()
  File "train.py", line 94, in train
    is_infer=False).model_cost
  File "/Users/hujian04/workspace/models-fork/youtube_recall/network_conf.py", line 29, in __init__
    self.model_cost = self._build_dnn_model()
  File "/Users/hujian04/workspace/models-fork/youtube_recall/network_conf.py", line 152, in _build_dnn_model
    neg_distribution=self._item_freq)
  File "/Users/hujian04/anaconda2/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/Users/hujian04/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/Users/hujian04/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/Users/hujian04/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/Users/hujian04/anaconda2/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 415, in wrapper
    return method(*args, **kwargs)
TypeError: nce_layer() got an unexpected keyword argument 'act'
```

请问到底要不要加这个这个‘act’？

**Comment by Yancey1989** [comment]
不需要的，nce使用sigmoid作为激活函数，稍后我更新下文档。
