### ISSUE TITLE
seqToseq_net.py locally train is ok, but mpi  train failed 

### ISSUE THREAD

**Issue by zhouyuan0828** [PaddlePaddle/Paddle#786]
job log url:http://10.73.227.37:8920/fileview.html?path=/home/normandy/maybach/208709/
failed reason is as below, could you guys help a look?
Thu Dec  8 12:08:31 2016[1,0]<stderr>:TypeError: simple_attention() got an unexpected keyword argument 'encoded_proj'

**Comment by backyes** [comment]
@zhouyuan0828 

建议能尝试将问题从集群中独立出来，
```
Thu Dec  8 12:08:28 2016[1,0]<stderr>:+ ./paddle_trainer --num_gradient_servers=1 --trainer_id=0 --pservers=10.73.227.37 --rdma_tcp=tcp --nics=xgbe0 --port=7164 --ports_num=1 --log_period=10 --num_passes=16 --trainer_count=8 --saving_period=1 --local=0 --config=conf/trainer_config.conf --save_dir=./output --use_gpu=0
Thu Dec  8 12:08:31 2016[1,0]<stderr>:Traceback (most recent call last):
Thu Dec  8 12:08:31 2016[1,0]<stderr>:  File "/home/normandy/maybach/208709/workspace/paddle/paddle/trainer/config_parser.py", line 3248, in parse_config_and_serialize
Thu Dec  8 12:08:31 2016[1,0]<stderr>:    config = parse_config(config_file, config_arg_str)
Thu Dec  8 12:08:31 2016[1,0]<stderr>:  File "/home/normandy/maybach/208709/workspace/paddle/paddle/trainer/config_parser.py", line 3224, in parse_config
Thu Dec  8 12:08:31 2016[1,0]<stderr>:    execfile(config_file, make_config_environment(config_file, config_args))
Thu Dec  8 12:08:31 2016[1,0]<stderr>:  File "conf/trainer_config.conf", line 49, in <module>
Thu Dec  8 12:08:31 2016[1,0]<stderr>:    gru_encoder_decoder(train_conf, is_generating)
Thu Dec  8 12:08:31 2016[1,0]<stderr>:  File "/home/normandy/maybach/208709/workspace/seqToseq_net.py", line 159, in gru_encoder_decoder
Thu Dec  8 12:08:31 2016[1,0]<stderr>:    input=group_inputs)
Thu Dec  8 12:08:31 2016[1,0]<stderr>:  File "/home/normandy/maybach/208709/workspace/paddle/paddle/trainer_config_helpers/default_decorators.py", line 31, in __wrapper__
Thu Dec  8 12:08:31 2016[1,0]<stderr>:    return func(*args, **kwargs)
Thu Dec  8 12:08:31 2016[1,0]<stderr>:  File "/home/normandy/maybach/208709/workspace/paddle/paddle/trainer_config_helpers/layers.py", line 1559, in recurrent_group
Thu Dec  8 12:08:31 2016[1,0]<stderr>:    layer_outs = step(*in_args)
Thu Dec  8 12:08:31 2016[1,0]<stderr>:  File "/home/normandy/maybach/208709/workspace/seqToseq_net.py", line 118, in gru_decoder_with_attention
Thu Dec  8 12:08:31 2016[1,0]<stderr>:    decoder_state=decoder_mem, )
Thu Dec  8 12:08:31 2016[1,0]<stderr>:  File "/home/normandy/maybach/208709/workspace/paddle/paddle/trainer_config_helpers/default_decorators.py", line 31, in __wrapper__
Thu Dec  8 12:08:31 2016[1,0]<stderr>:    return func(*args, **kwargs)
Thu Dec  8 12:08:31 2016[1,0]<stderr>:  File "/home/normandy/maybach/208709/workspace/paddle/paddle/trainer_config_helpers/default_decorators.py", line 31, in __wrapper__
Thu Dec  8 12:08:31 2016[1,0]<stderr>:    return func(*args, **kwargs)
Thu Dec  8 12:08:31 2016[1,0]<stderr>:TypeError: simple_attention() got an unexpected keyword argument 'encoded_proj'

```

你的错误如上。我理解是你的demo版本和paddl二进制版本不一致所致。 请参照：http://deeplearning.baidu.com/doc/install.html中提供的最新receiver，更新自己的receiver，然后重试。 操作之前建议稍微全面的了解下百度内部集群训练的文档。

**Comment by zhouyuan0828** [comment]
thanks ！ It is running now.
