### ISSUE TITLE
Distributed train error in develop branch paddle.v2.fluid.core.EnforceNotMet:  at [/paddle/paddle/operators/send_op.cc:47]

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#7878]
After https://github.com/PaddlePaddle/Paddle/pull/7705 merged, I tested with starting 10 pservers and 10 trainers using different ports on one node, results following error: 

```
Traceback (most recent call last):
  File "dist_test.py", line 85, in <module>
    fetch_list=[avg_cost] + accuracy.metrics)
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/executor.py", line 273, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.v2.fluid.core.EnforceNotMet:  at [/paddle/paddle/operators/send_op.cc:47]
PaddlePaddle Call Stacks:
0       0x7f1d6a3160f2p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 482
1       0x7f1d6a834963p paddle::operators::SendOp::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1427
2       0x7f1d6a3b2225p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 1317
3       0x7f1d6a328311p _ZZN8pybind1112cpp_function10initializeIZNS0_C1IvN6paddle9framework8ExecutorEJRKNS4_11ProgramDescEPNS4_5ScopeEibbEJNS_4nameENS_9is_methodENS_7siblingEEEEMT0_FT_DpT1_EDpRKT2_EUlPS5_S8_SA_ibbE_vJSO_S8_SA_ibbEJSB_SC_SD_EEEvOSF_PFSE_SH_ESN_ENUlRNS_6detail13function_callEE1_4_FUNESV_ + 545
4       0x7f1d6a33dd82p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2338
5       0x7f1d9d17dce8p PyEval_EvalFrameEx + 28264
6       0x7f1d9d18037dp PyEval_EvalCodeEx + 2061
7       0x7f1d9d17dd70p PyEval_EvalFrameEx + 28400
8       0x7f1d9d18037dp PyEval_EvalCodeEx + 2061
9       0x7f1d9d1804b2p PyEval_EvalCode + 50
10      0x7f1d9d1aa1c2p PyRun_FileExFlags + 146
11      0x7f1d9d1ab559p PyRun_SimpleFileExFlags + 217
12      0x7f1d9d1c11ddp Py_Main + 3149
13      0x7f1d9c454d1dp __libc_start_main + 253
14            0x4006b1p
```

The error was returned from this line: https://github.com/PaddlePaddle/Paddle/pull/7705/files#diff-57e3ecaeaa8dc2b8099075c0bf3db474R121 @helinwang can you please take a look at this?

**Comment by helinwang** [comment]
Sorry about the bug! This should fix it: https://github.com/PaddlePaddle/Paddle/pull/7889
