### ISSUE TITLE
paddle paddle.layer.concat的结果输出给paddle.layer.batch_norm报错

### ISSUE THREAD

**Issue by littlecrab999** [PaddlePaddle/Paddle#7897]
使用paddle实现dense net时，遇见以下错误。
[INFO 2018-01-26 18:30:55,664 layers.py:3244] output for dense block00norm1: c = 24, h = 32, w = 32, size = 24576
[INFO 2018-01-26 18:30:55,666 layers.py:2689] output for dense block00conv1: c = 10, h = 32, w = 32, size = 10240
[INFO 2018-01-26 18:30:55,667 layers.py:3244] output for dense block00norm2: c = 10, h = 32, w = 32, size = 10240
[INFO 2018-01-26 18:30:55,671 layers.py:2689] output for dense block00conv2: c = 5, h = 32, w = 32, size = 5120
finish first net
[CRITICAL 2018-01-26 18:30:55,673 layers.py:3244] Input layer dense block00cat: Incorrect input image size 32 * 32 for input image pixels 1
Traceback (most recent call last):
  File "train.py", line 45, in <module>
    main()
  File "train.py", line 24, in main
    out = dense_net.dense_net(img, growth_rate=5, block_config=(6, 6, 6))
  File "/home/work/chenchaojie/paddle_test/dense_net.py", line 47, in dense_net
    bn_size, growth_rate, drop_rate)
  File "/home/work/chenchaojie/paddle_test/dense_net.py", line 28, in dense_block
    layer = dense_layer(name + str(i), layer, num_features + i * growth_rate, growth_rate, bn_size, drop_rate)
  File "/home/work/chenchaojie/paddle_test/dense_net.py", line 4, in dense_layer
    norm1 = paddle.layer.batch_norm(name=name + 'norm1', input=input, batch_norm_type="batch_norm", act=paddle.activation.Relu())
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 415, in wrapper
    return method(*args, **kwargs)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 3244, in batch_norm_layer
    **ExtraLayerAttribute.to_kwargs(layer_attr))
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3896, in Layer
    return layer_func(name, **xargs)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 2485, in __init__
    parse_image(self.inputs[0].image, input_layer.name, image_conf)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 1318, in parse_image
    get_img_size(input_layer_name, image_conf.channels)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 1212, in get_img_size
    % (input_layer_name, img_size, img_size_y, img_pixels))
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 156, in config_assert
    logger.fatal(msg)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 4246, in my_fatal
    raise Exception()
Exception

代码中相关实现如下：

```
def dense_layer(name, input, channels, growth_rate, bn_size, drop_rate):
    norm1 = paddle.layer.batch_norm(name=name + 'norm1', input=input, batch_norm_type="batch_norm", act=paddle.activation.Relu())
    conv1 = paddle.layer.img_conv(name=name + 'conv1', input=norm1, num_channels=channels, 
                filter_size=1, num_filters=bn_size * growth_rate, stride=1, bias_attr=False, act=paddle.activation.Linear())
    norm2 = paddle.layer.batch_norm(name=name + 'norm2', input=conv1, act=paddle.activation.Relu())
    conv2 = paddle.layer.img_conv(name=name + 'conv2', input=norm2, num_channels=bn_size * growth_rate, 
                filter_size=3, num_filters=growth_rate, stride=1, padding=1, bias_attr=False, act=paddle.activation.Linear())
    
    ret = conv2
    if drop_rate > 0:
        ret = paddle.layer.dropout(input=conv2, dropout_rate=drop_rate)
    cat = paddle.layer.concat(name=name + 'cat', input=[input, ret])
    return cat 
```

```
def dense_net(input, growth_rate, block_config=(6,6,6), compression=0.5, num_init_features=24, bn_size=2, drop_rate=0, avgpool_size=8,num_classes=10):
    
    assert 0 < compression <= 1, 'compression of densenet should be between 0 and 1'
    conv0 = paddle.layer.img_conv(
        name='dense_net_conv',
        input=input,
        filter_size=3,
        num_channels=3,
        num_filters=num_init_features,
        stride=1,
        padding=1,
        act=paddle.activation.Linear(),
        bias_attr=False)
    num_features = num_init_features
    for i, num_layers in enumerate(block_config):
        block = dense_block('dense block' + str(i), conv0, num_layers,num_features,
                    bn_size, growth_rate, drop_rate)
        num_features = num_features + num_layers * growth_rate
        if i != len(block_config) - 1:
            block = transition('transition' + str(i), block, num_features, int(num_features * compression))
            num_features = int(num_features * compression)
        conv0 = block
```
￼因为有多层的dense net模块，每一层的处理包括batch_normalize，conv以及可选的drop out，每一层将输入和输出concat后作为下一层的输入，以此实现网络的dense连接。但是concat结果做batch_normalize时出现错误，将batch_normalize注释掉后运行正常。

我想concat是在channel维度做的拼接，比如10*32*32与5*32*32concat后得到15*32*32的中间结果，为什么concat后的结果不能进行BN呢？

**Comment by luotao1** [comment]
> 我想concat是在channel维度做的拼接

目前concat不能指定是在channel维度做的拼接。做的是chw维度的拼接，将nchw的格式认为是一个矩阵[n, chw]的话。两个矩阵[n, c1h1w1]和[n, c2h2w2]拼接完后的大矩阵是[n, c1h1w1+c2h2w2].

fluid的concat可以指定channel轴进行拼接。
