### ISSUE TITLE
出现AssertionError的Bug

### ISSUE THREAD

**Issue by yanmengqi** [PaddlePaddle/Paddle#8047]
使用paddlepaddle进行机器翻译训练,使用的语料是中英文语料,已分词已对齐
        引用训练集直接更改的.cache/paddle/wmt/wmt14.tgz里的内容,其他代码参数未修改,在开始程序后出现AssertionError错误.
报错的信息如下:
`I0201 20:07:38.419838 13473 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=2 
I0201 20:07:38.691911 13473 GradientMachine.cpp:94] Initing parameters..
I0201 20:07:41.030560 13473 GradientMachine.cpp:101] Init parameters done.
Traceback (most recent call last):
  File "train.py", line 163, in <module>
    main()
  File "train.py", line 159, in main
    train()
  File "train.py", line 154, in train
    feeding=feeding)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/trainer.py", line 162, in train
    for batch_id, data_batch in enumerate(reader()):
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/minibatch.py", line 33, in batch_reader
    for instance in r:
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/reader/decorator.py", line 70, in data_reader
    for e in reader():
  File "/home/yanmengqi/桌面/mt_with_external_memory/data_utils.py", line 12, in new_reader
    for ins in reader():
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/dataset/wmt14.py", line 73, in reader
    src_dict, trg_dict = __read_to_dict__(tar_file, dict_size)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/dataset/wmt14.py", line 60, in __read_to_dict__
    assert len(names) == 1
AssertionError
`

**Comment by guoshengCS** [comment]
不太清楚你那边数据的细节，但是这个报错是因为压缩包里存在多个以src.dict或trg.dict结尾的文件 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/dataset/wmt14.py#L68

**Comment by yanmengqi** [comment]
非常感谢,我想我大概知道是为什么了.

**Comment by jzh1992** [comment]
问下楼主是什么原因，我也遇到同样的BUG
