### ISSUE TITLE
Run fluid with GPU id > 0 causing error: paddle.v2.fluid.core.EnforceNotMet: 'Place' is not supported

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#8089]
My code: https://github.com/typhoonzero/Paddle/blob/a5acad11e8ead60413192143a0822daa408f67aa/benchmark/cluster/vgg16/vgg16_fluid.py
Complete log:

```
-----------  Configuration Arguments -----------
batch_size: 128
data_format: NCHW
data_set: cifar10
device: GPU
device_id: 1
learning_rate: 0.001
local: True
num_passes: 50
------------------------------------------------
Traceback (most recent call last):
  File "vgg16_fluid.py", line 277, in <module>
    main()
  File "vgg16_fluid.py", line 197, in main
    exe.run(fluid.default_startup_program())
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/executor.py", line 273, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.v2.fluid.core.EnforceNotMet: 'Place' is not supported, Please re-compile with WITH_GPU option at [/paddle/paddle/platform/device_context.cc:26]
PaddlePaddle Call Stacks:
0       0x7fb30f7a33e2p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 482
1       0x7fb31029e385p paddle::platform::DeviceContextPool::Get(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 245
2       0x7fb30f847d08p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 1192
3       0x7fb30f7bb241p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 545
4       0x7fb30f7b5092p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2338
5             0x4c37edp PyEval_EvalFrameEx + 31165
6             0x4b9ab6p PyEval_EvalCodeEx + 774
7             0x4c16e7p PyEval_EvalFrameEx + 22711
8             0x4b9ab6p PyEval_EvalCodeEx + 774
9             0x4c1e6fp PyEval_EvalFrameEx + 24639
10            0x4b9ab6p PyEval_EvalCodeEx + 774
11            0x4eb30fp
12            0x4e5422p PyRun_FileExFlags + 130
13            0x4e3cd6p PyRun_SimpleFileExFlags + 390
14            0x493ae2p Py_Main + 1554
15      0x7fb35e9d4830p __libc_start_main + 240
16            0x4933e9p _start + 41
```

Steps to reproduce:

1. Start a docker image and mount Nvidia drivers and /dev files into the docker image
1. Run the script using `python vgg16_fluid.py --local 1 --device GPU --device_id 0` runs OK
1. Run the script using `python vgg16_fluid.py --local 1 --device GPU --device_id 1` fails

**Comment by typhoonzero** [comment]
Closing, I found the reason. I was using `alpha.kubernetes.io/nvidia-gpu: 1` to require GPU resource from one Kubernetes node, docker uses `--device` to put one of the GPU into the container for use. Though I can see all the device files under `/dev/`, but they have no access inside the container.
