### ISSUE TITLE
__init__ Errors after installing

### ISSUE THREAD

**Issue by wondervictor** [PaddlePaddle/Paddle#8202]
````
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.v2 as paddle
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 85, in <module>
    from paddle.proto.DataConfig_pb2 import DataConfig
  File "/usr/local/lib/python2.7/dist-packages/paddle/proto/__init__.py", line 15, in <module>
    from paddle.proto.TrainerConfig_pb2 import OptimizationConfig, TrainerConfig
  File "/usr/local/lib/python2.7/dist-packages/paddle/proto/TrainerConfig_pb2.py", line 16, in <module>
    import DataConfig_pb2 as DataConfig__pb2
  File "/usr/local/lib/python2.7/dist-packages/paddle/proto/DataConfig_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x10\x44\x61taConfig.proto\x12\x06paddle\"b\n\rFileGroupConf\x12\x19\n\x0equeue_capacity\x18\x01 \x01(\r:\x01\x31\x12\x1a\n\x0fload_file_count\x18\x02 \x01(\x05:\x01\x31\x12\x1a\n\x0fload_thread_num\x18\x03 \x01(\x05:\x01\x31\"\x91\x04\n\nDataConfig\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\r\n\x05\x66iles\x18\x03 \x01(\t\x12\x10\n\x08\x66\x65\x61t_dim\x18\x04 \x01(\x05\x12\x11\n\tslot_dims\x18\x05 \x03(\x05\x12\x13\n\x0b\x63ontext_len\x18\x06 \x01(\x05\x12\x17\n\x0f\x62uffer_capacity\x18\x07 \x01(\x04\x12\x1c\n\x10train_sample_num\x18\x08 \x01(\x03:\x02-1\x12\x19\n\rfile_load_num\x18\t \x01(\x05:\x02-1\x12\x1e\n\x0f\x61sync_load_data\x18\x0c \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08\x66or_test\x18\x0e \x01(\x08:\x05\x66\x61lse\x12.\n\x0f\x66ile_group_conf\x18\x0f \x01(\x0b\x32\x15.paddle.FileGroupConf\x12\x17\n\x0f\x66loat_slot_dims\x18\x10 \x03(\x05\x12\x16\n\x0e\x63onstant_slots\x18\x14 \x03(\x01\x12\x18\n\x10load_data_module\x18\x15 \x01(\t\x12\x18\n\x10load_data_object\x18\x16 \x01(\t\x12\x16\n\x0eload_data_args\x18\x17 \x01(\t\x12,\n\x10sub_data_configs\x18\x18 \x03(\x0b\x32\x12.paddle.DataConfig\x12\x12\n\ndata_ratio\x18\x19 \x01(\x05\x12\x1a\n\x0cis_main_data\x18\x1a \x01(\x08:\x04true\x12\x16\n\x0busage_ratio\x18\x1b \x01(\x01:\x01\x31')
TypeError: __init__() got an unexpected keyword argument 'syntax'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/__init__.py", line 15, in <module>
    import optimizer
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/optimizer.py", line 15, in <module>
    import paddle.trainer_config_helpers.config_parser_utils as config_parser_utils
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/__init__.py", line 16, in <module>
    from data_sources import *
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/data_sources.py", line 17, in <module>
    from paddle.trainer.config_parser import *
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 85, in <module>
    from paddle.proto.DataConfig_pb2 import DataConfig
  File "/usr/local/lib/python2.7/dist-packages/paddle/proto/__init__.py", line 15, in <module>
    from paddle.proto.TrainerConfig_pb2 import OptimizationConfig, TrainerConfig
  File "/usr/local/lib/python2.7/dist-packages/paddle/proto/TrainerConfig_pb2.py", line 16, in <module>
    import DataConfig_pb2 as DataConfig__pb2
  File "/usr/local/lib/python2.7/dist-packages/paddle/proto/DataConfig_pb2.py", line 22, in <module>
    serialized_pb=_b('\n\x10\x44\x61taConfig.proto\x12\x06paddle\"b\n\rFileGroupConf\x12\x19\n\x0equeue_capacity\x18\x01 \x01(\r:\x01\x31\x12\x1a\n\x0fload_file_count\x18\x02 \x01(\x05:\x01\x31\x12\x1a\n\x0fload_thread_num\x18\x03 \x01(\x05:\x01\x31\"\x91\x04\n\nDataConfig\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\r\n\x05\x66iles\x18\x03 \x01(\t\x12\x10\n\x08\x66\x65\x61t_dim\x18\x04 \x01(\x05\x12\x11\n\tslot_dims\x18\x05 \x03(\x05\x12\x13\n\x0b\x63ontext_len\x18\x06 \x01(\x05\x12\x17\n\x0f\x62uffer_capacity\x18\x07 \x01(\x04\x12\x1c\n\x10train_sample_num\x18\x08 \x01(\x03:\x02-1\x12\x19\n\rfile_load_num\x18\t \x01(\x05:\x02-1\x12\x1e\n\x0f\x61sync_load_data\x18\x0c \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08\x66or_test\x18\x0e \x01(\x08:\x05\x66\x61lse\x12.\n\x0f\x66ile_group_conf\x18\x0f \x01(\x0b\x32\x15.paddle.FileGroupConf\x12\x17\n\x0f\x66loat_slot_dims\x18\x10 \x03(\x05\x12\x16\n\x0e\x63onstant_slots\x18\x14 \x03(\x01\x12\x18\n\x10load_data_module\x18\x15 \x01(\t\x12\x18\n\x10load_data_object\x18\x16 \x01(\t\x12\x16\n\x0eload_data_args\x18\x17 \x01(\t\x12,\n\x10sub_data_configs\x18\x18 \x03(\x0b\x32\x12.paddle.DataConfig\x12\x12\n\ndata_ratio\x18\x19 \x01(\x05\x12\x1a\n\x0cis_main_data\x18\x1a \x01(\x08:\x04true\x12\x16\n\x0busage_ratio\x18\x1b \x01(\x01:\x01\x31')
TypeError: __init__() got an unexpected keyword argument 'syntax'
````

**Comment by JiayiFeng** [comment]
This error usually shows that protobuf is not installed correctly. Please reinstall your protobuf (both in pip and brew if you are using mac) first. Thanks.

**Comment by wondervictor** [comment]
Thanks, I've fixed it with your help!
