### ISSUE TITLE
仿照场景文字识别例子做车牌识别，保存的参数是错的

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8279]
**因为车牌是有中文的，所以label和标签字典都是有中文的，label有中文，使用模型预测是就报错，日志如下：**
```
Traceback (most recent call last):
  File "infer.py", line 64, in <module>
    result = infer(img_path, model_path, image_shape, label_dict_path)
  File "infer.py", line 40, in infer
    parameters = paddle.parameters.Parameters.from_tar(gzip.open(model_path))
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 292, in from_tar
    for finfo in tar:
  File "/usr/lib/python2.7/tarfile.py", line 2508, in next
    tarinfo = self.tarfile.next()
  File "/usr/lib/python2.7/tarfile.py", line 2348, in next
    self.fileobj.seek(self.offset - 1)
  File "/usr/lib/python2.7/gzip.py", line 443, in seek
    self.read(1024)
  File "/usr/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 315, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 354, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x627501ed != 0xd6a0572L
```

**Comment by will-am** [comment]
模型保存需要时.tar.gz格式的

**Comment by yeyupiaoling** [comment]
@will-am 是保存为`.tar.gz`，一样的代码，如果把label的中文去掉就正常的。不会报这个错

**Comment by will-am** [comment]
那估计是编码的问题，建议先把中文转成数字或英文

**Comment by yeyupiaoling** [comment]
@will-am 
如果这个就不是端到端了。我在看看问题的出处，你没试过场景文字识别是中文的吗？

**Comment by will-am** [comment]
我没做过中文的场景识别，不过根据我之前做别的经验，中文需要处理好编码的问题

**Comment by yeyupiaoling** [comment]
@will-am 
现在又可以了，好像不是中文的问题。
可能是我的数据集太小，导致一个pass训练过快，模型没有正常保存
