### ISSUE TITLE
Meet bug when run  the fluid model.

### ISSUE THREAD

**Issue by NHZlX** [PaddlePaddle/Paddle#8283]
the model config can be see [here]
(https://github.com/NHZlX/models/blob/e9e084be77a6321f29793a156e709eec06cbdeb3/fluid/image_classification/mobilenet.py)
the log is ：

```
Traceback (most recent call last):
  File "mobilenet.py", line 203, in <module>
    train(learning_rate=0.005, batch_size=40, num_passes=400)
  File "mobilenet.py", line 181, in train
    fetch_list=[avg_cost] + accuracy.metrics)
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/fluid/executor.py", line 304, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.v2.fluid.core.EnforceNotMet: enforce holder_->size() >= memory_size() + offset_ failed, 64225280 < 64254080
Tensor's dims_ is out of bound. Call Tensor::mutable_data first to re-allocate memory.
or maybe the required data-type mismatches the data already stored. at [/home/vis/gaoyuan/Paddle/Paddle/paddle/framework/tensor_impl.h:68]
PaddlePaddle Call Stacks: 
0       0x7fb5c9ab2f12p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 576
1       0x7fb5c9ab3e20p paddle::framework::Tensor::check_memory_size() const + 610
2       0x7fb5c9c417f7p float const* paddle::framework::Tensor::data<float>() const + 27
3       0x7fb5caacaf11p void paddle::operators::math::matmul<paddle::platform::CPUDeviceContext, float>(paddle::platform::CPUDeviceContext const&, paddle::framework::Tensor const&, bool, paddle::framework::Tensor const&, bool, float, paddle::framework::Tensor*, float) + 715
4       0x7fb5ca878e40p paddle::operators::GemmConvKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const + 2936
5       0x7fb5caaa7373p paddle::framework::OperatorWithKernel::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 2561
6       0x7fb5c9c08b38p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 2918
7       0x7fb5c9ad82bap pybind11::cpp_function::cpp_function<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}::operator()(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) const + 144
8       0x7fb5c9b2a6e9p void pybind11::detail::argument_loader<paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool>::call_impl<void, pybind11::cpp_function::cpp_function<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul>(pybind11::cpp_function::cpp_function<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&, pybind11::detail::index_sequence<0ul, 1ul, 2ul, 3ul, 4ul, 5ul>) + 213
9       0x7fb5c9b0a082p _ZN8pybind116detail15argument_loaderIIPN6paddle9framework8ExecutorERKNS3_11ProgramDescEPNS3_5ScopeEibbEE4callIvRZNS_12cpp_functionC1IvS4_IS8_SA_ibbEINS_4nameENS_9is_methodENS_7siblingEEEEMT0_FT_DpT1_EDpRKT2_EUlS5_S8_SA_ibbE_EENSt9enable_ifIXsrSt7is_voidIT_E5valueENS0_9void_typeEE4typeEOT0_ + 52
10      0x7fb5c9af5648p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::operator()(pybind11::detail::function_call) const + 186
11      0x7fb5c9af5a89p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 29
12      0x7fb5c9aad979p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2448
13      0x7fb607d7ae24p PyEval_EvalFrameEx + 35060
14      0x7fb607d7babep PyEval_EvalCodeEx + 2206
15      0x7fb607d7b077p PyEval_EvalFrameEx + 35655
16      0x7fb607d7babep PyEval_EvalCodeEx + 2206
17      0x7fb607d7b077p PyEval_EvalFrameEx + 35655
18      0x7fb607d7babep PyEval_EvalCodeEx + 2206
19      0x7fb607d7bbd2p PyEval_EvalCode + 50
20      0x7fb607d9c1b0p PyRun_FileExFlags + 176
21      0x7fb607d9c38fp PyRun_SimpleFileExFlags + 239
22      0x7fb607db1cd4p Py_Main + 3188
23        0x318ae1ecddp __libc_start_main + 253
24            0x400649p

Exception in thread Thread-5 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/dataset/flowers.py", line 65, in default_mapper
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-4 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/dataset/flowers.py", line 65, in default_mapper
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-6 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/dataset/flowers.py", line 65, in default_mapper
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-12 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 275, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/Queue.py", line 138, in put
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 384, in notify
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-11 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/dataset/flowers.py", line 65, in default_mapper
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/dataset/flowers.py", line 65, in default_mapper
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-8 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/dataset/flowers.py", line 65, in default_mapper
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-9 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/dataset/flowers.py", line 65, in default_mapper
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-13 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/dataset/flowers.py", line 63, in default_mapper
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-10 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/dataset/flowers.py", line 65, in default_mapper
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/dataset/flowers.py", line 65, in default_mapper
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
 Exception in thread Thread-7 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/threading.py", line 754, in run
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/reader/decorator.py", line 274, in handle_worker
  File "/home/vis/gaoyuan/opt/python-build/lib/python2.7/site-packages/paddle/v2/dataset/flowers.py", line 65, in default_mapper
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

```

**Comment by jacquesqiao** [comment]
fixed

**Comment by JoyeeL** [comment]
> fixed

how to solve this problem

**Comment by luotao1** [comment]
@JoyeeL Please update the paddle version to 1.4.1.
