### ISSUE TITLE
ImportError: No module named py_paddle

### ISSUE THREAD

**Issue by keain** [PaddlePaddle/Paddle#830]

**Comment by qingqing01** [comment]
Please give more details about your work environment.   

In addition,  please make sure that you have install Paddle with swig. The guide is in last part in  this link:  http://www.paddlepaddle.org/doc/build/build_from_source.html

**Comment by keain** [comment]
我的错误提示是下面这样的；我的cmake 加了-DWITH_SWIG_PY=ON选项；我看到有个#865这个issue似乎和我的有些类似，不过是我通过源码安装的，不是通过build.sh一键编译的
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "py_paddle/util.py", line 19, in <module>
    import swig_paddle
  File "py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "py_paddle/swig_paddle.py", line 20, in swig_import_helper
    import _swig_paddle
ImportError: No module named _swig_paddle

**Comment by keain** [comment]
另外我没有在我的目录下面找到_swig_paddle.so这个库，是不是也有问题呢

**Comment by keain** [comment]
@qingqing01 ，能解答一下么

**Comment by qingqing01** [comment]
通过源码install之后，是否有 `pip install py_paddle-xxx.whl `这个呢？ 比如，我install之后, 在我的安装路径下有：

```
install_path/opt/paddle/share/wheels/py_paddle-0.0.0-cp27-cp27mu-linux_x86_64.whl
```
需要install这个包，即：

```
pip install  install_path/opt/paddle/share/wheels/py_paddle-0.0.0-cp27-cp27mu-linux_x86_64.whl
```

**Comment by backyes** [comment]
@keain 

paddle python包安装是delay到第一次运行paddle命令的时候，但是并没有考虑用户执行python解释器，然后import py_paddle的情况。 因此， 一般执行import py_paddle的时候，需要手动shell 下输入 **paddle train --help ** 触发一下， 即可。 

@reyoung delay安装的问题，能否优化下？ 原来具体设计delay安装的原因是啥？是否再统筹考虑下， 这种delay的设计，感觉不太合理。 如果是其他特殊需求要求这种 delay安装， 不知道能否换一种策略。

**Comment by keain** [comment]
@qingqing01 ，我之前有没pip install，然后我操作了一下，再import py_paddle, 报了新的错误
ImportError: /home/.jumbo/lib/python2.7/site-packages/py_paddle/_swig_paddle.so: undefined symbol: _ZTVSt12bad_weak_ptr

**Comment by keain** [comment]
@backyes ,按照你的说法操作了，还是报ImportError: /home/.jumbo/lib/python2.7/site-packages/py_paddle/_swig_paddle.so: undefined symbol: _ZTVSt12bad_weak_ptr

**Comment by luotao1** [comment]
Too old to close this issue. If question is not resolved, we can reopen the issue.

**Comment by sshmyeclipse** [comment]
mac 环境下运行housing.py出现以下错误，麻烦帮忙解决下，谢谢🙏
 File "housing.py", line 4, in <module>
    paddle.init(use_gpu=False, trainer_count=1)
  File "/Users/ruidu/Library/Python/2.7/lib/python/site-packages/paddle/v2/__init__.py", line 119, in init
    import py_paddle.swig_paddle as api
  File "/Users/ruidu/Library/Python/2.7/lib/python/site-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/Users/ruidu/Library/Python/2.7/lib/python/site-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/Users/ruidu/Library/Python/2.7/lib/python/site-packages/py_paddle/swig_paddle.py", line 17, in <module>
    _swig_paddle = swig_import_helper()
  File "/Users/ruidu/Library/Python/2.7/lib/python/site-packages/py_paddle/swig_paddle.py", line 16, in swig_import_helper
    return importlib.import_module('_swig_paddle')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _swig_paddle

**Comment by jinfagang** [comment]
Same issue here, I think Paddle team are dispersion on those distribution of paddle. I just installed the newest paddle from pip, write a simple program just got same error. Abviously, the whl file not valid at all and upload directly to distribution. This is not responsible to Paddle community. **Hope paddle team solve this as soon as possible***
