### ISSUE TITLE
Build Paddle docker image encounter errors like can not remove file under /tmp

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#8331]
We received recent user feedbacks reporting building Docker image fail, this error is due to https://github.com/moby/moby/issues/9572, which is a Linux kernel overlayfs bug. You can reproduce this problem using the commands in the above link.

The recommended fix is to try to use another [storage dirvers](https://docs.docker.com/storage/storagedriver/select-storage-driver/) like aufs or device mapper.

Sample error logs when building docker image:

```
 Found existing installation: pytz 2014.10
    Uninstalling pytz-2014.10:
      Successfully uninstalled pytz-2014.10
  Found existing installation: requests 2.9.2
    Uninstalling requests-2.9.2:
      Successfully uninstalled requests-2.9.2
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 795, in install
    requirement.commit_uninstall()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 767, in commit_uninstall
    self.uninstalled.commit()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 142, in commit
    git python-pip python-dev openssh-server bison libnccl-dev \
    rmtree(self.save_dir)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 110, in rmtree_errorhandler
    if os.stat(path).st_mode & stat.S_IREAD:
OSError: [Errno 2] No such file or directory: '/tmp/pip-rJH6_m-uninstall/usr/local/lib/python2.7/dist-packages/requests-2.9.2.dist-info/DESCRIPTION.rst'
The command '/bin/sh -c pip install --upgrade pip -i http://mirrors.aliyun.com
```

**Comment by typhoonzero** [comment]
Thanks for @jacquesqiao to find the reason of this issue!

**Comment by xjqbest** [comment]
我也遇到了同样的问题  请问是怎么解决的 谢谢
我试了加如下选项，并不管用
-i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
