### ISSUE TITLE
book demo run failed

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#8383]
It's failed on book demo `test_word2vec.py`

```
ERROR: test_cpu_dense_normal (__main__.W2VTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_word2vec.py", line 207, in __impl__
    main(use_cuda=use_cuda, is_sparse=is_sparse, parallel=parallel)
  File "test_word2vec.py", line 183, in main
    train(use_cuda, is_sparse, parallel, save_dirname)
  File "test_word2vec.py", line 166, in train
    fetch_list=[avg_cost])
  File "/paddle/build/python/build/lib-python/paddle/v2/fluid/executor.py", line 290, in run
    self.executor.run(program.desc, scope, 0, True, True)
EnforceNotMet: holder_ should not be null
Tensor holds no memory. Call Tensor::mutable_data first. at [/paddle/paddle/fluid/framework/tensor_impl.h:63]
PaddlePaddle Call Stacks:
0       0x7f6f81785fecp paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 572
1       0x7f6f81788f2fp paddle::framework::Tensor::check_memory_size() const + 303
2       0x7f6f8178a974p unsigned long* paddle::framework::Tensor::data<unsigned long>() + 36
3       0x7f6f81ed3bd8p paddle::framework::operator<<(std::ostream&, std::vector<paddle::framework::Vector<unsigned long>, std::allocator<paddle::framework::Vector<unsigned long> > > const&) + 104
4       0x7f6f81e78493p paddle::framework::OperatorBase::DebugStringEx[abi:cxx11](paddle::framework::Scope const*) const + 1043
5       0x7f6f8185359cp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 1532
6       0x7f6f817a2fe7p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::operator()(pybind11::detail::function_call) const + 567
7       0x7f6f817a31aep void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 14
8       0x7f6f8179ff74p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
9             0x4cad00p PyEval_EvalFrameEx + 28048
10            0x4c2705p PyEval_EvalCodeEx + 597
11            0x4ca088p PyEval_EvalFrameEx + 24856
12            0x4c2705p PyEval_EvalCodeEx + 597
13            0x4ca7dfp PyEval_EvalFrameEx + 26735
14            0x4c2705p PyEval_EvalCodeEx + 597
15            0x4ca7dfp PyEval_EvalFrameEx + 26735
16            0x4c2705p PyEval_EvalCodeEx + 597
17            0x4ca7dfp PyEval_EvalFrameEx + 26735
18            0x4c2705p PyEval_EvalCodeEx + 597
19            0x4de858p
20            0x4b0c93p PyObject_Call + 67
21            0x4c6ef6p PyEval_EvalFrameEx + 12166
22            0x4c2705p PyEval_EvalCodeEx + 597
23            0x4de69ep
24            0x4b0c93p PyObject_Call + 67
25            0x4f452ep
26            0x4b0c93p PyObject_Call + 67
27            0x552397p
28            0x4b0c93p PyObject_Call + 67
29            0x4c9f9fp PyEval_EvalFrameEx + 24623
30            0x4c2705p PyEval_EvalCodeEx + 597
31            0x4de858p
32            0x4b0c93p PyObject_Call + 67
33            0x4c6ef6p PyEval_EvalFrameEx + 12166
34            0x4c2705p PyEval_EvalCodeEx + 597
35            0x4de69ep
36            0x4b0c93p PyObject_Call + 67
37            0x4f452ep
38            0x4b0c93p PyObject_Call + 67
39            0x552397p
40            0x4b0c93p PyObject_Call + 67
41            0x4c9f9fp PyEval_EvalFrameEx + 24623
42            0x4c2705p PyEval_EvalCodeEx + 597
43            0x4de858p
44            0x4b0c93p PyObject_Call + 67
45            0x4c6ef6p PyEval_EvalFrameEx + 12166
46            0x4c2705p PyEval_EvalCodeEx + 597
47            0x4de69ep
48            0x4b0c93p PyObject_Call + 67
49            0x4f452ep
50            0x4b0c93p PyObject_Call + 67
51            0x552397p
52            0x4b0c93p PyObject_Call + 67
53            0x4c9f9fp PyEval_EvalFrameEx + 24623
54            0x4c9d7fp PyEval_EvalFrameEx + 24079
55            0x4c9d7fp PyEval_EvalFrameEx + 24079
56            0x4c2705p PyEval_EvalCodeEx + 597
57            0x4de69ep
58            0x4b0c93p PyObject_Call + 67
59            0x4f452ep
60            0x4b0c93p PyObject_Call + 67
61            0x4f42a7p
62            0x4b669cp
63            0x4b0c93p PyObject_Call + 67
64            0x4c9f9fp PyEval_EvalFrameEx + 24623
65            0x4c2705p PyEval_EvalCodeEx + 597
66            0x4c24a9p PyEval_EvalCode + 25
67            0x4f19efp
68            0x4ec372p PyRun_FileExFlags + 130
69            0x4eaaf1p PyRun_SimpleFileExFlags + 401
70            0x49e208p Py_Main + 1736
71      0x7f6fca6fc830p __libc_start_main + 240
72            0x49da59p _start + 41


----------------------------------------------------------------------
Ran 8 tests in 2.715s
```

**Comment by Yancey1989** [comment]
Duplicated with #8368
