### ISSUE TITLE
develop branch CI fails at test_rnn_encoder_decoder.py

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#8392]
detailed log:

```
[21:12:11] :	 [Step 1/1] Traceback (most recent call last):
[21:12:11] :	 [Step 1/1]   File "test_rnn_encoder_decoder.py", line 273, in test_cuda
[21:12:11] :	 [Step 1/1]     main(use_cuda=True)
[21:12:11] :	 [Step 1/1]   File "test_rnn_encoder_decoder.py", line 266, in main
[21:12:11] :	 [Step 1/1]     train(use_cuda, save_dirname)
[21:12:11] :	 [Step 1/1]   File "test_rnn_encoder_decoder.py", line 207, in train
[21:12:11] :	 [Step 1/1]     fetch_list=[avg_cost])
[21:12:11] :	 [Step 1/1]   File "/paddle/build/python/build/lib-python/paddle/v2/fluid/executor.py", line 290, in run
[21:12:11] :	 [Step 1/1]     self.executor.run(program.desc, scope, 0, True, True)
[21:12:11] :	 [Step 1/1] EnforceNotMet: cudaMemcpyAsync failed in paddle::platform::GpuMemcpyAsync: an illegal memory access was encountered at [/paddle/paddle/fluid/platform/gpu_info.cc:97]
[21:12:11] :	 [Step 1/1] PaddlePaddle Call Stacks: 
[21:12:11] :	 [Step 1/1] 0       0x7f3656c2223cp paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 572
[21:12:11] :	 [Step 1/1] 1       0x7f36577f1428p paddle::platform::GpuMemcpyAsync(void*, void const*, unsigned long, cudaMemcpyKind, CUstream_st*) + 296
[21:12:11] :	 [Step 1/1] 2       0x7f3656c2715fp paddle::framework::Copy(paddle::framework::Tensor const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::platform::DeviceContext const&, paddle::framework::Tensor*) + 1167
[21:12:11] :	 [Step 1/1] 3       0x7f3656f6b476p paddle::operators::FetchOp::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 598
[21:12:11] :	 [Step 1/1] 4       0x7f3656cf35a2p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 1490
[21:12:11] :	 [Step 1/1] 5       0x7f3656c3e793p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 579
[21:12:11] :	 [Step 1/1] 6       0x7f3656c3c4d4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
[21:12:11] :	 [Step 1/1] 7             0x4c37edp PyEval_EvalFrameEx + 31165
[21:12:11] :	 [Step 1/1] 8             0x4b9ab6p PyEval_EvalCodeEx + 774
[21:12:11] :	 [Step 1/1] 9             0x4c16e7p PyEval_EvalFrameEx + 22711
[21:12:11] :	 [Step 1/1] 10            0x4b9ab6p PyEval_EvalCodeEx + 774
[21:12:11] :	 [Step 1/1] 11            0x4c16e7p PyEval_EvalFrameEx + 22711
[21:12:11] :	 [Step 1/1] 12            0x4b9ab6p PyEval_EvalCodeEx + 774
[21:12:11] :	 [Step 1/1] 13            0x4c1e6fp PyEval_EvalFrameEx + 24639
[21:12:11] :	 [Step 1/1] 14            0x4c136fp PyEval_EvalFrameEx + 21823
[21:12:11] :	 [Step 1/1] 15            0x4b9ab6p PyEval_EvalCodeEx + 774
[21:12:11] :	 [Step 1/1] 16            0x4d55f3p
[21:12:11] :	 [Step 1/1] 17            0x4a577ep PyObject_Call + 62
[21:12:11] :	 [Step 1/1] 18            0x4bed3dp PyEval_EvalFrameEx + 12045
[21:12:11] :	 [Step 1/1] 19            0x4b9ab6p PyEval_EvalCodeEx + 774
[21:12:11] :	 [Step 1/1] 20            0x4d54b9p
[21:12:11] :	 [Step 1/1] 21            0x4eebeep
[21:12:11] :	 [Step 1/1] 22            0x4a577ep PyObject_Call + 62
[21:12:11] :	 [Step 1/1] 23            0x548253p
[21:12:11] :	 [Step 1/1] 24            0x4c15bfp PyEval_EvalFrameEx + 22415
[21:12:11] :	 [Step 1/1] 25            0x4b9ab6p PyEval_EvalCodeEx + 774
[21:12:11] :	 [Step 1/1] 26            0x4d55f3p
[21:12:11] :	 [Step 1/1] 27            0x4a577ep PyObject_Call + 62
[21:12:11] :	 [Step 1/1] 28            0x4bed3dp PyEval_EvalFrameEx + 12045
[21:12:11] :	 [Step 1/1] 29            0x4b9ab6p PyEval_EvalCodeEx + 774
[21:12:11] :	 [Step 1/1] 30            0x4d54b9p
[21:12:11] :	 [Step 1/1] 31            0x4eebeep
[21:12:11] :	 [Step 1/1] 32            0x4a577ep PyObject_Call + 62
[21:12:11] :	 [Step 1/1] 33            0x548253p
[21:12:11] :	 [Step 1/1] 34            0x4c15bfp PyEval_EvalFrameEx + 22415
[21:12:11] :	 [Step 1/1] 35            0x4b9ab6p PyEval_EvalCodeEx + 774
[21:12:11] :	 [Step 1/1] 36            0x4d55f3p
[21:12:11] :	 [Step 1/1] 37            0x4a577ep PyObject_Call + 62
[21:12:11] :	 [Step 1/1] 38            0x4bed3dp PyEval_EvalFrameEx + 12045
[21:12:11] :	 [Step 1/1] 39            0x4b9ab6p PyEval_EvalCodeEx + 774
[21:12:11] :	 [Step 1/1] 40            0x4d54b9p
[21:12:11] :	 [Step 1/1] 41            0x4eebeep
[21:12:11] :	 [Step 1/1] 42            0x4a577ep PyObject_Call + 62
[21:12:11] :	 [Step 1/1] 43            0x548253p
[21:12:11] :	 [Step 1/1] 44            0x4c15bfp PyEval_EvalFrameEx + 22415
[21:12:11] :	 [Step 1/1] 45            0x4c136fp PyEval_EvalFrameEx + 21823
[21:12:11] :	 [Step 1/1] 46            0x4c136fp PyEval_EvalFrameEx + 21823
[21:12:11] :	 [Step 1/1] 47            0x4b9ab6p PyEval_EvalCodeEx + 774
[21:12:11] :	 [Step 1/1] 48            0x4d54b9p
[21:12:11] :	 [Step 1/1] 49            0x4eebeep
[21:12:11] :	 [Step 1/1] 50            0x4ee7f6p
[21:12:11] :	 [Step 1/1] 51            0x4aa9abp
[21:12:11] :	 [Step 1/1] 52            0x4c15bfp PyEval_EvalFrameEx + 22415
[21:12:11] :	 [Step 1/1] 53            0x4b9ab6p PyEval_EvalCodeEx + 774
[21:12:11] :	 [Step 1/1] 54            0x4eb30fp
[21:12:11] :	 [Step 1/1] 55            0x4e5422p PyRun_FileExFlags + 130
[21:12:11] :	 [Step 1/1] 56            0x4e3cd6p PyRun_SimpleFileExFlags + 390
[21:12:11] :	 [Step 1/1] 57            0x493ae2p Py_Main + 1554
[21:12:11] :	 [Step 1/1] 58      0x7f36766f2830p __libc_start_main + 240
[21:12:11] :	 [Step 1/1] 59            0x4933e9p _start + 41
[21:12:11] :	 [Step 1/1] 
[21:12:11] :	 [Step 1/1] 
[21:12:11] :	 [Step 1/1] 
```

**Comment by jacquesqiao** [comment]
fixed by https://github.com/PaddlePaddle/Paddle/pull/8377
