### ISSUE TITLE
在训练模型的过程中得到RuntimeError异常

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#8476]
异常信息如下：
>Traceback (most recent call last):
  File "entry_point.py", line 6, in <module>
    train.train()
  File "/home/zzhzz/PycharmProjects/tbcnn/tbcnn/embeddings/train.py", line 56, in train
    fetch_list=[loss]
  File "/home/zzhzz/venv/local/lib/python2.7/site-packages/paddle/v2/fluid/executor.py", line 304, in run
    self.executor.run(program.desc, scope, 0, True, True)
RuntimeError: boost::bad_get: failed value get using boost::get

请问有什么办法可以解决？
模型链接如下：
https://github.com/zzhzz/nn_model/blob/master/network.py

**Comment by zzhzz** [comment]
模型对应的论文如下：
https://arxiv.org/abs/1409.3358

**Comment by wangkuiyi** [comment]
谢谢反馈！你是怎么运行这个例子的呢？是用Docker吗？能否贴一下你的命令行，以便Paddle team的同学们复现这个错误，然后debug？

**Comment by zzhzz** [comment]
该问题在最新版本的paddle中已经被解决了，谢谢！
