### ISSUE TITLE
holder_ should not be null, Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:119]

### ISSUE THREAD

**Issue by xymyeah** [PaddlePaddle/Paddle#8508]
在运行fluid notest_dist_fit_a_line和machine_translation demo的时候出现了错误，请帮忙看看
使用的是下面的最新代码build的
https://github.com/PaddlePaddle/Paddle/commit/78cc64a55cbba36cef56d8436a583323e001b7e5
```
Traceback (most recent call last):
  File "trainer.py", line 94, in <module>
    fluid.io.save_persistables(exe, "./output/model/")
  File "/usr/local/lib/python2.7/site-packages/paddle/v2/fluid/io.py", line 153, in save_persistables
    save_file_name=save_file_name)
  File "/usr/local/lib/python2.7/site-packages/paddle/v2/fluid/io.py", line 98, in save_vars
    save_file_name=save_file_name)
  File "/usr/local/lib/python2.7/site-packages/paddle/v2/fluid/io.py", line 126, in save_vars
    executor.run(save_program)
  File "/usr/local/lib/python2.7/site-packages/paddle/v2/fluid/executor.py", line 290, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.v2.fluid.core.EnforceNotMet: holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:119]
PaddlePaddle Call Stacks: 
0       0x7f6ce0a00e42p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 482
1       0x7f6ce0a01f73p paddle::framework::Tensor::type() const + 147
2       0x7f6ce1493c1dp paddle::framework::TensorToStream(std::ostream&, paddle::framework::Tensor const&, paddle::platform::DeviceContext const&) + 93
3       0x7f6ce145a3e8p paddle::framework::SerializeToStream(std::ostream&, paddle::framework::LoDTensor const&, paddle::platform::DeviceContext const&) + 408
4       0x7f6ce11998f8p paddle::operators::SaveOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1544
5       0x7f6ce0a7d42fp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 1279
6       0x7f6ce0a14271p _ZZN8pybind1112cpp_function10initializeIZNS0_C1IvN6paddle9framework8ExecutorEIRKNS4_11ProgramDescEPNS4_5ScopeEibbEINS_4nameENS_9is_methodENS_7siblingEEEEMT0_FT_DpT1_EDpRKT2_EUlPS5_S8_SA_ibbE_vISO_S8_SA_ibbEISB_SC_SD_EEEvOSF_PFSE_SH_ESN_ENUlRNS_6detail13function_callEE1_4_FUNESV_ + 545
7       0x7f6ce0a0e172p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2338
8       0x7f6d6929c631p PyEval_EvalFrameEx + 24497
9       0x7f6d6929dbcep PyEval_EvalCodeEx + 2190
10      0x7f6d6929c20ap PyEval_EvalFrameEx + 23434
11      0x7f6d6929dbcep PyEval_EvalCodeEx + 2190
12      0x7f6d6929c20ap PyEval_EvalFrameEx + 23434
13      0x7f6d6929dbcep PyEval_EvalCodeEx + 2190
14      0x7f6d6929c20ap PyEval_EvalFrameEx + 23434
15      0x7f6d6929dbcep PyEval_EvalCodeEx + 2190
16      0x7f6d6929c20ap PyEval_EvalFrameEx + 23434
17      0x7f6d6929dbcep PyEval_EvalCodeEx + 2190
18      0x7f6d6929dce2p PyEval_EvalCode + 50
19      0x7f6d692bd9e0p PyRun_FileExFlags + 176
20      0x7f6d692bdbbfp PyRun_SimpleFileExFlags + 239
21      0x7f6d692d3454p Py_Main + 3188
22      0x7f6d68587cddp __libc_start_main + 253
23            0x400649p
```

**Comment by Yancey1989** [comment]
我还没能复现这个问题，最近有修过一些bug，可以用最新的代码再试下？

**Comment by Yancey1989** [comment]
Close this inactive issue, please feel free to reopen it.
