### ISSUE TITLE
Demo of `fc_gan` raise exception

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#8529]
The exception is

```
Traceback (most recent call last):
  File "/opt/pycharm-2017.3.3/helpers/pydev/pydev_run_in_console.py", line 53, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/reyoung/Paddle/python/paddle/v2/fluid/tests/demo/fc_gan.py", line 171, in <module>
    main()
  File "/home/reyoung/Paddle/python/paddle/v2/fluid/tests/demo/fc_gan.py", line 119, in main
    p.name for p in g_program.global_block().all_parameters()
  File "/home/reyoung/Paddle/python/paddle/v2/fluid/optimizer.py", line 237, in minimize
    startup_program)
  File "/home/reyoung/Paddle/python/paddle/v2/fluid/optimizer.py", line 205, in create_optimization_pass
    param_and_grad)
  File "/home/reyoung/Paddle/python/paddle/v2/fluid/optimizer.py", line 432, in _append_optimize_op
    "epsilon": self._epsilon
  File "/home/reyoung/Paddle/python/paddle/v2/fluid/framework.py", line 825, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/home/reyoung/Paddle/python/paddle/v2/fluid/framework.py", line 501, in __init__
    self.desc.infer_shape(self.block.desc)
EnforceNotMet: Input(LearningRate) of AdamOp should not be null. at [/home/reyoung/Paddle/paddle/fluid/operators/adam_op.cc:34]
PaddlePaddle Call Stacks: 
0       0x7f71571de41ap paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 442
1       0x7f7157d02f59p paddle::operators::AdamOp::InferShape(paddle::framework::InferShapeContext*) const + 6243
2       0x7f71572e25dcp
3       0x7f71572e48e6p
4       0x7f71572e6e69p std::function<void (paddle::framework::InferShapeContext*)>::operator()(paddle::framework::InferShapeContext*) const + 73
5       0x7f71572e2f2cp paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1318
6       0x7f715728c1dap pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}::operator()(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&) const + 112
7       0x7f71572ac453p void pybind11::detail::argument_loader<paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&>::call_impl<void, pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}&, 0ul, 1ul>(pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}&, pybind11::detail::index_sequence<0ul, 1ul>) + 91
8       0x7f71572a3facp std::enable_if<std::is_void<void>::value, pybind11::detail::void_type>::type pybind11::detail::argument_loader<paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&>::call<void, pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}&>(pybind11::cpp_function::cpp_function<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}&) + 54
9       0x7f7157299c18p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}, void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}&&, void (*)(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::operator()(pybind11::detail::function_call) const + 156
10      0x7f7157299d89p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}, void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}&&, void (*)(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 29
11      0x7f71571d8e34p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2461
12      0x555e4c8d7480p PyEval_EvalFrameEx + 28432
13      0x555e4c8ced45p PyEval_EvalCodeEx + 565
14      0x555e4c8ebc38p
15      0x555e4c8bd413p PyObject_Call + 67
16      0x555e4c90235ep
17      0x555e4c8bd413p PyObject_Call + 67
18      0x555e4c902097p
19      0x555e4c8c2f34p
20      0x555e4c8bd413p PyObject_Call + 67
21      0x555e4c8d7998p PyEval_EvalFrameEx + 29736
22      0x555e4c8ced45p PyEval_EvalCodeEx + 565
23      0x555e4c8d6f15p PyEval_EvalFrameEx + 27045
24      0x555e4c8d642fp PyEval_EvalFrameEx + 24255
25      0x555e4c8ced45p PyEval_EvalCodeEx + 565
26      0x555e4c8d6738p PyEval_EvalFrameEx + 25032
27      0x555e4c8ced45p PyEval_EvalCodeEx + 565
28      0x555e4c8d6738p PyEval_EvalFrameEx + 25032
29      0x555e4c8d642fp PyEval_EvalFrameEx + 24255
30      0x555e4c8ced45p PyEval_EvalCodeEx + 565
31      0x555e4c8ceb09p PyEval_EvalCode + 25
32      0x555e4c8ff14fp
33      0x555e4c8f9fc2p PyRun_FileExFlags + 130
34      0x555e4c9626f0p
35      0x555e4c8d0b9ap PyEval_EvalFrameEx + 1578
36      0x555e4c8ced45p PyEval_EvalCodeEx + 565
37      0x555e4c8d6738p PyEval_EvalFrameEx + 25032
38      0x555e4c8ced45p PyEval_EvalCodeEx + 565
39      0x555e4c8ceb09p PyEval_EvalCode + 25
40      0x555e4c8ff14fp
41      0x555e4c8f9fc2p PyRun_FileExFlags + 130
42      0x555e4c8f9b0ep PyRun_SimpleFileExFlags + 414
43      0x555e4c8aaaa1p Py_Main + 1729
44      0x7f7191836f2ap __libc_start_main + 234
45      0x555e4c8aa2cap _start + 42
```

It seems that we change the code and break this demo.

**Comment by jacquesqiao** [comment]
## reason
In fc_gan demo, there are two programs that need to be optimized, but currently, the optimizer will only create learning_rate_var once. So the second program will not find the learning rate var.

## detail
`optimizer.minimize(loss, ...)` will create optimize ops and related variables in the block of `loss`. The current optimizer has a filed `optimizer._global_learning_rate` which will be created only once, in the fc_gan demo, the optimizer.minimize is called twice for two losses in two program, so the second optimizer.minimize cannot find learning rate variable in its Program.

## solution
create learning rate var for each program it optimized.
