### ISSUE TITLE
仿照目标检查例子做车牌检查，初始化model是出错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8530]
我是参考https://github.com/PaddlePaddle/models/tree/develop/ssd 这个例子来做车牌检测的，在使用官方给出的模型作为初始化模型的时候，报错，可能是我只有两个类别，错误信息如下：
```
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    init_model_path='../models/vgg_model.tar.gz')
  File "train.py", line 31, in train
    parameters.init_from_tar(gzip.open(init_model_path))
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 399, in init_from_tar
    self.set(pname, tar_param.get(pname))
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 270, in set
    self.__setitem__(key=parameter_name, value=value)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 223, in __setitem__
    (shape, value.shape))
ValueError: Value shape mismatch, expect (1, 27648), should (1, 290304)
```
如果不使用官方给出的模型作为初始化参数就会出现浮点异常，我在 #8488 有提过
```
Thread [140023146039040] Forwarding detection_output, 
*** Aborted at 1519445972 (unix time) try "date -d @1519445972" if you are using GNU date ***

PC: @                0x0 (unknown)

*** SIGFPE (@0x7f59e1d15a18) received by PID 62813 (TID 0x7f59ade14700) from PID 18446744073203178008; stack trace: ***

    @     0x7f59e29eb390 (unknown)

    @     0x7f59e1d15a18 __expf_finite

    @     0x7f59e1d1d42f expf

    @     0x7f59af7dc339 paddle::decodeBBoxWithVar()

    @     0x7f59af7e66f1 paddle::DetectionOutputLayer::forward()

    @     0x7f59af847f4d paddle::NeuralNetwork::forward()

    @     0x7f59af86a014 paddle::TrainerThread::forward()

    @     0x7f59af86b315 paddle::TrainerThread::computeThread()

    @     0x7f59d98d7c80 (unknown)

    @     0x7f59e29e16ba start_thread

    @     0x7f59e271741d clone

    @                0x0 (unknown)
Floating point exception (core dumped)

```

项目地址：https://github.com/yeyupiaoling/TestPlateNumber

**Comment by QiJune** [comment]
1. ssd模型直接训练确实容易出现浮点异常，一般需要加载预训练的参数。

2. 这里需要先得到适合自己数据集的预训练模型。

3. 具体如何进行预训练，请 @pkuyym 来帮忙解答一下吧，谢谢！

**Comment by yeyupiaoling** [comment]
@pkuyym 
如何做预训练呢？在问题描述中我提供了项目的地址，里面已经包括数据集了。

**Comment by yeyupiaoling** [comment]
@pkuyym @QiJune @qingqing01 
求帮助

**Comment by pkuyym** [comment]
@yeyupiaoling 可以尝试使用提供的模型的部分参数来初始化模型，一般来讲，需要更改的部分是跟类别相关的，底层的conv层是一致的，这种情况下，可以只load部分参数来做初始化，理论上可以缓解FPE问题

**Comment by yeyupiaoling** [comment]
@pkuyym 
如何直接使用官方提供的模型初始化是报下面的错误的，我的类别只有1个，加上一background，就2个。您说的加载部分的参数初始化，如何做到？谢谢
```
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    init_model_path='../models/vgg_model.tar.gz')
  File "train.py", line 31, in train
    parameters.init_from_tar(gzip.open(init_model_path))
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 399, in init_from_tar
    self.set(pname, tar_param.get(pname))
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 270, in set
    self.__setitem__(key=parameter_name, value=value)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 223, in __setitem__
    (shape, value.shape))
ValueError: Value shape mismatch, expect (1, 27648), should (1, 290304)
```

**Comment by yeyupiaoling** [comment]
@pkuyym 
可以讲讲如何预训练吗？

**Comment by pkuyym** [comment]
@yeyupiaoling hi，假设你知道SSD的原理，这样可以把预训练的模型参数里面跟类别相关的参数全部删除掉，然后重新打包，加载打包后的模型。第一步就是找到所有与类别数相关的参数，印象中那些1D的卷积跟类别相关，把这些parameter删掉

**Comment by yeyupiaoling** [comment]
@pkuyym 
如果你这个假设不成立呢
>假设你知道SSD的原理

官方的预训练模型：http://paddlepaddle.bj.bcebos.com/model_zoo/detection/ssd_model/vgg_model.tar.gz 我不知道该删除哪些~

**Comment by pkuyym** [comment]
@yeyupiaoling 
![4dc3bd20653fadeb98a2f285180589fa](https://user-images.githubusercontent.com/5782283/36717757-4843c434-1bda-11e8-8278-b696e4151ee1.png)
解压后可以看到这些参数（截取了一部分），你可以把文件名中包含mbox的文件都删掉，然后重新打包一下，注意打包文件不要包含原始的tar文件，以及目录层级只有一层

**Comment by yeyupiaoling** [comment]
@pkuyym 
谢谢，我的问题可以得到解决的，虽然还不会如何预训练，但是这样能解决我的问题，谢谢您~
