### ISSUE TITLE
test_parallel_do failed in multi-GPU environment

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#8561]
nvidia-smi print following:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.111                Driver Version: 384.111                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    Off  | 00000000:04:00.0 Off |                  N/A |
| 27%   48C    P2    55W / 250W |  11679MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    Off  | 00000000:05:00.0 Off |                  N/A |
| 27%   47C    P2    56W / 250W |  11539MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN X (Pascal)    Off  | 00000000:08:00.0 Off |                  N/A |
| 25%   44C    P2    56W / 250W |    708MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN X (Pascal)    Off  | 00000000:09:00.0 Off |                  N/A |
| 25%   45C    P2    54W / 250W |    473MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  TITAN X (Pascal)    Off  | 00000000:84:00.0 Off |                  N/A |
| 27%   48C    P2    55W / 250W |    473MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  TITAN X (Pascal)    Off  | 00000000:85:00.0 Off |                  N/A |
| 29%   51C    P2    55W / 250W |    473MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  TITAN X (Pascal)    Off  | 00000000:88:00.0 Off |                  N/A |
| 31%   53C    P2    56W / 250W |    371MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  TITAN X (Pascal)    Off  | 00000000:89:00.0 Off |                  N/A |
| 23%   38C    P0    55W / 250W |    176MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

And test_parallel_do will fails, the error log is following:
```
ERROR: test_simple_fc (__main__.ParallelOpTestMultipleInput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_parallel_op.py", line 213, in test_simple_fc
    fetch=['fc1.w@GRAD', 'fc2.w@GRAD', 'fc3.w@GRAD'])
  File "test_parallel_op.py", line 69, in run_test
    use_parallel=True)
  File "test_parallel_op.py", line 135, in _run_test_impl_
    return exe.run(main, feed=feed, fetch_list=fetch)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 290, in run
    self.executor.run(program.desc, scope, 0, True, True)
EnforceNotMet: misaligned address at [/root/paddle/paddle/fluid/platform/device_context.cc:153]
PaddlePaddle Call Stacks:
0       0x7f2b359f665cp paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 572
1       0x7f2b365d9792p paddle::platform::CUDADeviceContext::Wait() const + 466
2       0x7f2b3635aa60p paddle::operators::WaitOnPlaces(std::vector<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > >) + 64
3       0x7f2b363660bep paddle::operators::ParallelDoGradOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 1694
4       0x7f2b35a9b0a6p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 1526
5       0x7f2b35a12bf3p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 579
6       0x7f2b35a10934p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
7             0x4c37edp PyEval_EvalFrameEx + 31165
8             0x4b9ab6p PyEval_EvalCodeEx + 774
9             0x4c16e7p PyEval_EvalFrameEx + 22711
10            0x4b9ab6p PyEval_EvalCodeEx + 774
11            0x4c16e7p PyEval_EvalFrameEx + 22711
12            0x4b9ab6p PyEval_EvalCodeEx + 774
13            0x4c1e6fp PyEval_EvalFrameEx + 24639
14            0x4c136fp PyEval_EvalFrameEx + 21823
15            0x4b9ab6p PyEval_EvalCodeEx + 774
16            0x4d55f3p
17            0x4a577ep PyObject_Call + 62
18            0x4bed3dp PyEval_EvalFrameEx + 12045
19            0x4b9ab6p PyEval_EvalCodeEx + 774
20            0x4d54b9p
21            0x4eebeep
22            0x4a577ep PyObject_Call + 62
23            0x548253p
24            0x4c15bfp PyEval_EvalFrameEx + 22415
25            0x4b9ab6p PyEval_EvalCodeEx + 774
26            0x4d55f3p
27            0x4a577ep PyObject_Call + 62
28            0x4bed3dp PyEval_EvalFrameEx + 12045
29            0x4b9ab6p PyEval_EvalCodeEx + 774
30            0x4d54b9p
31            0x4eebeep
32            0x4a577ep PyObject_Call + 62
33            0x548253p
34            0x4c15bfp PyEval_EvalFrameEx + 22415
35            0x4b9ab6p PyEval_EvalCodeEx + 774
36            0x4d55f3p
37            0x4a577ep PyObject_Call + 62
38            0x4bed3dp PyEval_EvalFrameEx + 12045
39            0x4b9ab6p PyEval_EvalCodeEx + 774
40            0x4d54b9p
41            0x4eebeep
42            0x4a577ep PyObject_Call + 62
43            0x548253p
44            0x4c15bfp PyEval_EvalFrameEx + 22415
45            0x4c136fp PyEval_EvalFrameEx + 21823
46            0x4c136fp PyEval_EvalFrameEx + 21823
47            0x4b9ab6p PyEval_EvalCodeEx + 774
48            0x4d54b9p
49            0x4eebeep
50            0x4ee7f6p
51            0x4aa9abp
52            0x4c15bfp PyEval_EvalFrameEx + 22415
53            0x4b9ab6p PyEval_EvalCodeEx + 774
54            0x4eb30fp
55            0x4e5422p PyRun_FileExFlags + 130
56            0x4e3cd6p PyRun_SimpleFileExFlags + 390
57            0x493ae2p Py_Main + 1554
58      0x7f2bc759f830p __libc_start_main + 240
59            0x4933e9p _start + 41


----------------------------------------------------------------------
Ran 3 tests in 1.824s

FAILED (errors=1)
```

**Comment by QiJune** [comment]
I have made several times test, I find that it will fail occasionally.
I am trying to find out the reason.
