### ISSUE TITLE
Fluid 分布式训练 test_image_classification.py error

### ISSUE THREAD

**Issue by seiriosPlus** [PaddlePaddle/Paddle#8632]
训练过程中出现如下异常：
Traceback (most recent call last):
  File "test_image_classification.py", line 267, in <module>
    Traceback (most recent call last):
  File "test_image_classification.py", line 267, in <module>
    main('resnet', use_cuda=False, is_local=False)
  File "test_image_classification.py", line 234, in main
    main('resnet', use_cuda=False, is_local=False)
  File "test_image_classification.py", line 234, in main
    train(net_type, use_cuda, save_dirname, is_local)
  File "test_image_classification.py", line 195, in train
    train(net_type, use_cuda, save_dirname, is_local)
  File "test_image_classification.py", line 195, in train
    train_loop(t.get_trainer_program())
  File "test_image_classification.py", line 143, in train_loop
    train_loop(t.get_trainer_program())
  File "test_image_classification.py", line 143, in train_loop
exe.run(main_program, feed=feeder.feed(data))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 290, in run
        exe.run(main_program, feed=feeder.feed(data))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 290, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet:  at [/home/paddle/Paddle/paddle/fluid/operators/send_op.cc:77]

version: 0.11.0 with distribute
os: ubuntu 14.04
python 2.7

**Comment by Yancey1989** [comment]
Looks like communication error, please make sure pserver instance is ready before start trainer.
And `GLOG_v=4 GLOG_logtostderr=1` would provide more detail logs.

**Comment by seiriosPlus** [comment]
I have fixed it in the latest code in https://github.com/seiriosPlus/fluid_benchmark/blob/master/image_classification/se_resnext_cluster.py
