### ISSUE TITLE
dist demo fit_a_line.py run failed

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#8675]
`fit_a_line.py` run failed with more than 2 pserver instances.

```bash
Traceback (most recent call last):
  File "test_fit_a_line.py", line 159, in <module>
    train(False, "fit_a_line.inference.model", False)
  File "test_fit_a_line.py", line 89, in train
    trainers=trainers)
  File "/paddle/build/python/build/lib-python/paddle/fluid/distribute_transpiler.py", line 216, in transpile
    eplist = split_method(send_inputs, pserver_endpoints)
  File "/paddle/build/python/build/lib-python/paddle/fluid/distributed_spliter.py", line 39, in round_robin
    assert (len(varlist) > len(pserver_endpoints))
AssertionError
```

**Comment by Yancey1989** [comment]
Will close this issue, it's not a bug, just because the parameter is too small, can not split into more blocks.
