### ISSUE TITLE
cuda8.0/cudnn5版paddle执行报错

### ISSUE THREAD

**Issue by bbgasj** [PaddlePaddle/Paddle#8713]
使用模型库里的dssm程序，原来的paddle可以跑，现在打算在p40上跑，据说要用cuda8编译的，下载最新版本的：paddlepaddle_gpu-0.11.0-cp27-cp27m-linux_x86_64.whl安装执行后报如下错误？

```bash
[CRITICAL 2018-03-02 18:37:35,832 layers.py:1069] When the name field of param_attr is manually specified and the input is a list, the param_attr should also be a list with each item being the param_attr for each input item. If only one named param_attr is provided, all the input items would share this parameter.
Traceback (most recent call last):
  File "train.py", line 268, in <module>
    use_gpu=args.use_gpu)
  File "train.py", line 186, in train
    share_embed=share_embed)()
  File "/home/work/fengxinwei/paddle-paddle/dssm/network_conf.py", line 74, in __call__
    return self.model_type_creater()
  File "/home/work/fengxinwei/paddle-paddle/dssm/network_conf.py", line 173, in _build_classification_model
    is_classification=True)
  File "/home/work/fengxinwei/paddle-paddle/dssm/network_conf.py", line 273, in _build_classification_or_regression_model
    x = self.model_arch_creater(input, prefix=prefixs[id])
  File "/home/work/fengxinwei/paddle-paddle/dssm/network_conf.py", line 59, in _model_arch_creater
    dnn = self.create_dnn(sent_vec, prefix)
  File "/home/work/fengxinwei/paddle-paddle/dssm/network_conf.py", line 165, in create_dnn
    bias_attr=ParamAttr(name='%s.b' % name, initial_std=0.))
  File "/home/work/fengxinwei/paddle-paddle/dssm/python_gpu_paddle/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/home/work/fengxinwei/paddle-paddle/dssm/python_gpu_paddle/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/work/fengxinwei/paddle-paddle/dssm/python_gpu_paddle/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/work/fengxinwei/paddle-paddle/dssm/python_gpu_paddle/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/work/fengxinwei/paddle-paddle/dssm/python_gpu_paddle/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/work/fengxinwei/paddle-paddle/dssm/python_gpu_paddle/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 415, in wrapper
    return method(*args, **kwargs)
  File "/home/work/fengxinwei/paddle-paddle/dssm/python_gpu_paddle/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 1069, in fc_layer
    "When the name field of param_attr is manually specified "
  File "/home/work/fengxinwei/paddle-paddle/dssm/python_gpu_paddle/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 4293, in my_fatal
    raise Exception()
Exception
```

**Comment by chengduoZH** [comment]
您再检查一下FC这一层是怎么配置的，方便的话贴一下这个的配置

**Comment by bbgasj** [comment]
找到原因了，官方dssm里的fc是基于0.10写的，我之前的paddle应该也是0.10的。
0.10和0.11在这块有如下区别：
https://github.com/PaddlePaddle/Paddle/blob/release/0.10.0/python/paddle/trainer_config_helpers/layers.py#L921
https://github.com/PaddlePaddle/Paddle/blob/9580c4507772f718dd90e9dc5bb64943e60a1b85/python/paddle/trainer_config_helpers/layers.py#L1053

**Comment by Yancey1989** [comment]
CI上现在只保留最近3个月的历史数据，目前最早的在：
```bash
wget "https://guest:@paddleci.ngrok.io/repository/download/Manylinux1_Cuda80cudnn5cp27cp27mu/22201:id/paddlepaddle_gpu-0.11.0-cp27-cp27m-linux_x86_64.whl"
```
可以先试下。

**Comment by bbgasj** [comment]
看最新版dssm修复了这个问题，可以close了
https://github.com/PaddlePaddle/models/blob/develop/dssm/network_conf.py#L154
