### ISSUE TITLE
请问如何检查receiver的状态

### ISSUE THREAD

**Issue by hijkzzz** [PaddlePaddle/Paddle#8722]
```
connect to receiver:  yq01-idl-gpu-offline14.yq01.baidu.com:8090
compressing thirdparty files
finished to pack request
starting to submit to server
Traceback (most recent call last):
  File "/home/work/paddle/output/submit.py", line 288, in <module>
    no_prefix_train_args_dict, ).run()
  File "/home/work/paddle/output/submit.py", line 73, in run
    self._do_poster_request()
  File "/home/work/paddle/output/submit.py", line 162, in _do_poster_request
    print urllib2.urlopen(request).read()
  File "/home/work/.jumbo/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/home/work/.jumbo/lib/python2.7/urllib2.py", line 400, in open
    response = self._open(req, data)
  File "/home/work/.jumbo/lib/python2.7/urllib2.py", line 418, in _open
    '_open', req)
  File "/home/work/.jumbo/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/home/work/.jumbo/lib/python2.7/site-packages/poster/streaminghttp.py", line 142, in http_open
    return self.do_open(StreamingHTTPConnection, req)
  File "/home/work/.jumbo/lib/python2.7/urllib2.py", line 1180, in do_open
    r = h.getresponse(buffering=True)
  File "/home/work/.jumbo/lib/python2.7/httplib.py", line 1030, in getresponse
    response.begin()
  File "/home/work/.jumbo/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/home/work/.jumbo/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

```
通过curl访问返回是OK说明端口没问题
但receiver实际上挂了
这样严重影响了线上任务的运行
请问如何有效检测并且切换receiver

**Comment by kuke** [comment]
用户现在还不能检查receiver的状态，以后会升级receiver来解决这个问题
