### ISSUE TITLE
pip install paddlepaddle faild

### ISSUE THREAD

**Issue by wangtao169447** [PaddlePaddle/Paddle#8743]
when i run command like this "pip install paddlepaddle faild", which throws exception below: 

Exception:
Traceback (most recent call last):
  File "/home/test/Python-2.7.3/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/test/Python-2.7.3/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/test/Python-2.7.3/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/test/Python-2.7.3/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/home/test/Python-2.7.3/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/home/test/Python-2.7.3/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/home/test/Python-2.7.3/lib/python2.7/shutil.py", line 297, in move
    rmtree(src)
  File "/home/test/Python-2.7.3/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/home/test/Python-2.7.3/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/home/test/Python-2.7.3/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/home/test/Python-2.7.3/lib/python2.7/shutil.py", line 245, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/home/test/Python-2.7.3/lib/python2.7/shutil.py", line 254, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/test/Python-2.7.3/lib/python2.7/shutil.py", line 252, in rmtree
    os.rmdir(path)
OSError: [Errno 22] Invalid argument: '/home/test/Python-2.7.3/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg/requests/packages/urllib3/contrib'

**Comment by pkuyym** [comment]
You mean `pip install paddlepaddle ` instead of `pip install paddlepaddle faild`?
If so, please provide more detailed information like the machine and os.

**Comment by guoshengCS** [comment]
Close this issue due to inactivity and please feel free to reopen it if needed.
