### ISSUE TITLE
How to stop layer's gradient like Tensorflow in Fluid

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/Paddle#8756]
```
fc1 = fluid.layers.fc(x, 128)
```
In Tensorflow, We can stop gradient by using fc1 = tf.stop_gradient(fc1) and the gradient will not pass by this layer.
Do we have same mechanism in fluid? 
I tried using fc1.stop_gradient=False but it didn't work.

**Comment by TomorrowIsAnOtherDay** [comment]
@guoshengCS 
Oh, I set it to be False, But I could't launch my program.Here is program information:
```
Failed to load OpenCL runtime
Traceback (most recent call last):
  File "agent.py", line 60, in <module>
    model = Model()
  File "agent.py", line 16, in __init__
    self._build_net()
  File "agent.py", line 41, in _build_net
    optimizer.minimize(cost)
  File "/home/ol/anaconda2/envs/paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 221, in minimize
    [error_clip_callback])
  File "/home/ol/anaconda2/envs/paddle/lib/python2.7/site-packages/paddle/fluid/backward.py", line 489, in append_backward
    raise ValueError("param %s is not in map" % param)
ValueError: param fc1_b is not in map
```

**Comment by guoshengCS** [comment]
请 @JiayiFeng 帮忙确认下`append_backward`是否对`no_grad_set`进行了正确的处理，也欢迎 @TomorrowIsAnOtherDay 提供建议，一下是错误复现代码。

```
import numpy as np

import paddle.v2 as paddle
import paddle.fluid as fluid


def program():
    x = fluid.layers.data(name='x', shape=[64, 32], dtype='float32', append_batch_size=False)
    out = fluid.layers.fc(x, size=32, param_attr='fc_param', bias_attr=True)
    out.stop_gradient = True
    out = fluid.layers.mean(out)
    return out


def main():
    place = fluid.CPUPlace()
    #place = fluid.CUDAPlace(0)
    exe = fluid.Executor(place)
    out = program()
    optimizer = fluid.optimizer.SGD(learning_rate=0.1)
    optimizer.minimize(out)
    out_ = exe.run(fluid.framework.default_startup_program())
    data_input = {}
    in_tensor = fluid.LoDTensor()
    in_tensor.set(np.random.random([64, 32]).astype("float32"), place)
    data_input['x'] = in_tensor
    for i in range(10):
       param_grad = exe.run(fluid.framework.default_main_program(), feed=data_input, fetch_list=['fc_param@GRAD'])[0]
       print param_grad


if __name__ == "__main__":
    main()
```

**Comment by TomorrowIsAnOtherDay** [comment]
https://github.com/PaddlePaddle/Paddle/blob/ea4e6c7af78adecc009b847379f6df5db224ed45/python/paddle/fluid/backward.py#L488
I suppose add `continue` after this line instead of `raise ValueError`

**Comment by JiayiFeng** [comment]
@TomorrowIsAnOtherDay  I think you are right. It looks like a bug introduced in recent developments. I have pushed a new PR to fix it. Thank you so much for your feedback!

**Comment by TomorrowIsAnOtherDay** [comment]
@guoshengCS @JiayiFeng 
Thanks  for quick feedback~
Wish fluid be better and better sincerely!
