### ISSUE TITLE
fully connected layer作为lstm输入问题

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#8774]
多个全联接层作为序列输入lstm
网络结构至fully connected layers部分都能跑通，但加入lstm后，出现如下错误：
```
F0306 06:04:09.414822  1037 LstmLayer.cpp:155] Check failed: input.sequenceStartPositions 
*** Check failure stack trace: ***
    @     0x7f5e44ff8a5d  google::LogMessage::Fail()
    @     0x7f5e44ffc50c  google::LogMessage::SendToLog()
    @     0x7f5e44ff8583  google::LogMessage::Flush()
    @     0x7f5e44ffda1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5e44d49882  paddle::LstmLayer::forward()
    @     0x7f5e44bd7e3d  paddle::NeuralNetwork::forward()
    @     0x7f5e44bd8a93  paddle::GradientMachine::forwardBackward()
    @     0x7f5e44fd4764  GradientMachine::forwardBackward()
    @     0x7f5e44b70fc9  _wrap_GradientMachine_forwardBackward
    @           0x4c30ce  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c16e7  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c16e7  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4eb30f  (unknown)
    @           0x4e5422  PyRun_FileExFlags
    @           0x4e3cd6  PyRun_SimpleFileExFlags
    @           0x493ae2  Py_Main
    @     0x7f5e61cde830  __libc_start_main
    @           0x4933e9  _start
    @              (nil)  (unknown)
Aborted (core dumped)
```
加入lstm的模型结构如下：
```
...

fc_layer_1_dict = {}
for iter in range(13):
	fc_1 = paddle.layer.fc(input=pool_layer_4_dict[iter], size=10*4, act=paddle.activation.Relu())
	fc_layer_1_dict[iter] = fc_1

lstm_layer_1_dict = {}
lstm = paddle.layer.lstmemory(input=fc_layer_1_dict[0],bias_attr=paddle.attr.Param(initial_std=0., l2_rate=0.))
lstm_layer_1_dict[0] = lstm

inputs = [fc_layer_1_dict[0],lstm]
for iter in range(1,13):
	fc = paddle.layer.fc(input=[fc_layer_1_dict[iter],lstm],
							size=10*4,
							act=paddle.activation.Linear())
        lstm_layer_1_dict[iter] = paddle.layer.lstmemory(input=fc,bias_attr=paddle.attr.Param(initial_std=0., l2_rate=0.))
	inputs = [fc, lstm_layer_1_dict[iter]]

fc_last = paddle.layer.pooling(input=inputs[0], pooling_type=paddle.pooling.Max())
lstm_last = paddle.layer.pooling(input=inputs[1], pooling_type=paddle.pooling.Max())

```

**Comment by guoshengCS** [comment]
这里应该是序列输入没有正确处理的问题，报错和 #8768 类似，请说明下所使用的data layer和reader

**Comment by hyo009** [comment]
数据输入为13个图片向量
```
input_dict = {}
for iter in range(13):
	image = paddle.layer.data(name="img{}".format(iter), type=paddle.data_type.dense_vector(IMG_VECTOR_SIZE))
	input_dict[iter] = image
```
lstm之前网络结构为4层conv+maxpooling
conv_layer_1_dict = {}
pool_layer_1_dict = {}
 for iter in range(13):
	conv_1 = paddle.layer.img_conv(input=input_dict[iter], filter_size=3, filter_size_y=3,
                      num_channels=1,
                      num_filters=16, stride=1,
                      bias_attr=False,
                      act=paddle.activation.Relu())
	conv_layer_1_dict[iter] = conv_1

	maxpool_1 = paddle.layer.img_pool(input=conv_layer_1_dict[iter],
                         pool_size=2,
                         pool_size_y=2,
                         num_channels=16,
                         stride=1,
                         stride_y=1)
	pool_layer_1_dict[iter] = maxpool_1

...
用全联接层flatten后放入lstm：
```
fc_layer_1_dict = {}
for iter in range(13):
	fc_1 = paddle.layer.fc(input=pool_layer_4_dict[iter], size=10*4, act=paddle.activation.Relu())
	fc_layer_1_dict[iter] = fc_1

lstm_layer_1_dict = {}
lstm = paddle.layer.lstmemory(input=fc_layer_1_dict[0],bias_attr=paddle.attr.Param(initial_std=0., l2_rate=0.))
lstm_layer_1_dict[0] = lstm

inputs = [fc_layer_1_dict[0],lstm]
for iter in range(1,13):
	fc = paddle.layer.fc(input=[fc_layer_1_dict[iter],lstm],
							size=10*4,
							act=paddle.activation.Linear())
	lstm_layer_1_dict[iter] = paddle.layer.lstmemory(input=fc,bias_attr=paddle.attr.Param(initial_std=0., l2_rate=0.))
	inputs = [fc, lstm_layer_1_dict[iter]]

fc_last = paddle.layer.pooling(input=inputs[0], pooling_type=paddle.pooling.Max())
lstm_last = paddle.layer.pooling(input=inputs[1], pooling_type=paddle.pooling.Max())
```

reader()函数中yield 13个长度为IMG_VECTOR_SIZE的整数向量和一个float类型的label

**Comment by guoshengCS** [comment]
如果一条样本包含多帧图片，这些多帧图片特征对应只有一个data layer，其type为`paddle.data_type.dense_vector_sequence(IMG_VECTOR_SIZE)`，reader中yield后每条样本特征相应的需要格式`[[IMG0_feature0, IMG0_feature1],[IMG1_feature0, IMG1_feature1]]...`

**Comment by hyo009** [comment]
dense_vector_sequence如何接入img_conv层, 还有我想把卷积和pooling层的输出直接放入lstm该如何操作？有相关例子吗？谢谢！

**Comment by guoshengCS** [comment]
dense_vector_sequence的接口使用方式和正常的dense_vector没有差别，可以像dense_vector那样直接接入img_conv层。卷积和pooling层的输出放入lstm的话需要使用block_expand这个layer，例子可以参考这里 https://github.com/PaddlePaddle/models/blob/develop/scene_text_recognition/network_conf.py#L54

**Comment by hyo009** [comment]
在reader()中yield img_sequence，img_sequence是一个形式为[[img0_fea0, img0_fea1,...], [img1_fea0, img1_fea1,...], ...]。

定义data layer：
`img_seq = paddle.layer.data(name="img_sequence", type=paddle.data_type.dense_vector_sequence(IMG_VECTOR_SIZE))`

在模型中：
```
conv_1 = paddle.layer.img_conv(input=img_seq, filter_size=3, filter_size_y=3,
                      num_channels=1,
                      num_filters=16, stride=1,
                      bias_attr=False,
                      act=paddle.activation.Relu())
```

出现报错：
```
[INFO 2018-03-07 02:41:51,905 layers.py:2714] output for __conv_0__: c = 16, h = 48, w = 48, size = 36864
[CRITICAL 2018-03-07 02:41:51,907 layers.py:2714] Input layer __conv_0__: Incorrect input image size 48 * 48 for input image pixels 36864
Traceback (most recent call last):
  File "test_lstm.py", line 246, in <module>
    main()
  File "test_lstm.py", line 198, in main
    predict = convolutional_neural_network(img_seq)
  File "test_lstm.py", line 109, in convolutional_neural_network
    act=paddle.activation.Relu())
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 415, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 2714, in img_conv_layer
    **ExtraLayerAttribute.to_kwargs(layer_attr))
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3943, in Layer
    return layer_func(name, **xargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 2110, in __init__
    conv_conf, num_filters)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 1379, in parse_conv
    get_img_size(input_layer_name, conv.channels)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 1217, in get_img_size
    % (input_layer_name, img_size, img_size_y, img_pixels))
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 161, in config_assert
    logger.fatal(msg)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 4293, in my_fatal
    raise Exception()
Exception
```

**Comment by guoshengCS** [comment]
yield训练数据时要用`yield img_sequence, label`

**Comment by hyo009** [comment]
解决了，多谢！
