### ISSUE TITLE
bow文本分类，运行报错

### ISSUE THREAD

**Issue by gmcather** [PaddlePaddle/Paddle#8819]
```
Traceback (most recent call last):
  File "scripts/test_bow_maxpooling.py", line 65, in <module>
    size=hid_dim2)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 180, in fc
    "y_num_col_dims": 1})
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 45, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 806, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 482, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core.EnforceNotMet: enforce x_dims.size() > x_num_col_dims failed, 1 <= 1
The input tensor X's rank of MulOp should be larger than x_num_col_dims. at [/paddle/Paddle/paddle/fluid/operators/mul_op.cc:43]
PaddlePaddle Call Stacks:
0       0x7fa1ccc9c13cp paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 572
1       0x7fa1cce30843p paddle::operators::MulOpShapeInference::operator()(paddle::framework::InferShapeContext*) const + 1811
2       0x7fa1cce311e2p std::_Function_handler<void (paddle::framework::InferShapeContext*), paddle::framework::details::OpInfoFiller<paddle::operators::MulOpShapeInference, (paddle::framework::details::OpInfoFillType)4>::operator()(char const*, paddle::framework::OpInfo*) const::{lambda(paddle::framework::InferShapeContext*)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::InferShapeContext*&&) + 50
3       0x7fa1ccd2871ap paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1050
4       0x7fa1cccf331fp void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}, void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}&&, void (*)(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 223
5       0x7fa1cccb6114p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 1236
6             0x4c37edp PyEval_EvalFrameEx + 31165
7             0x4b9ab6p PyEval_EvalCodeEx + 774
8             0x4d55f3p
9             0x4eebeep
10            0x4ee7f6p
11            0x4aa9abp
12            0x4a577ep PyObject_Call + 62
13            0x4bed3dp PyEval_EvalFrameEx + 12045
14            0x4b9ab6p PyEval_EvalCodeEx + 774
15            0x4d55f3p
16            0x4a577ep PyObject_Call + 62
17            0x4bed3dp PyEval_EvalFrameEx + 12045
18            0x4b9ab6p PyEval_EvalCodeEx + 774
19            0x4c1e6fp PyEval_EvalFrameEx + 24639
20            0x4b9ab6p PyEval_EvalCodeEx + 774
21            0x4c16e7p PyEval_EvalFrameEx + 22711
22            0x4b9ab6p PyEval_EvalCodeEx + 774
23            0x4eb30fp
24            0x4e5422p PyRun_FileExFlags + 130
25            0x4e3cd6p PyRun_SimpleFileExFlags + 390
26            0x493ae2p Py_Main + 1554
27      0x7fa1ffbb0830p __libc_start_main + 240
28            0x4933e9p _start + 41
```

```python
from __future__ import print_function
import numpy as np
import paddle.v2 as paddle
import paddle.fluid as fluid
import sys
# just define to_lodtensor function for inner call
def to_lodtensor(data, place):
    seq_lens = [len(seq) for seq in data]
    cur_len = 0
    lod = [cur_len]
    for l in seq_lens:
        cur_len += l
        lod.append(cur_len)
    flattened_data = np.concatenate(data, axis=0).astype("int64")
    flattened_data = flattened_data.reshape([len(flattened_data), 1])
    res = fluid.LoDTensor()
    res.set(flattened_data, place)
    res.set_lod([lod])
    return res

def load_vocab(filename):
    vocab = {}
    with open(filename) as f:
        wid = 0
        for line in f:
            vocab[line.strip()] = wid
            wid += 1
    return vocab

# load word dict with paddle inner function
word_dict = load_vocab(sys.argv[1])
word_dict["<unk>"] = len(word_dict)
print(len(word_dict))
# vocabulary size
dict_dim = len(word_dict)

# embedding dim
emb_dim = 128

# hidden dim
hid_dim = 128

# hidden dim2
hid_dim2 = 96

# class num
class_dim = 2

# input text data
data = fluid.layers.data(
    name="words", shape=[1], dtype="int64", lod_level=1)

# label data
label = fluid.layers.data(name="label", shape=[1], dtype="int64")

# embedding
emb = fluid.layers.embedding(input=data, size=[dict_dim, emb_dim])

bow = fluid.layers.reduce_sum(
    input=emb,
    dim=1)

# fc layer after conv
fc_1 = fluid.layers.fc(input=bow,
                       size=hid_dim2)

# probability of each class
prediction = fluid.layers.fc(input=[fc_1],
                             size=class_dim,
                             act="softmax")

# cross entropy loss
cost = fluid.layers.cross_entropy(input=prediction, label=label)

# mean loss
avg_cost = fluid.layers.mean(x=cost)

# SGD optimizer
sgd_optimizer = fluid.optimizer.SGD(learning_rate=0.01)
sgd_optimizer.minimize(avg_cost)

# accuracy metric
accuracy = fluid.evaluator.Accuracy(input=prediction, label=label)
print("type:acc")
print(type(accuracy))
inference_program = fluid.default_main_program().clone()
with fluid.program_guard(inference_program):
    test_target = accuracy.metrics + accuracy.states
    inference_program = fluid.io.get_inference_program(test_target)

# train data set
BATCH_SIZE = 4
train_reader = paddle.batch(
    paddle.reader.shuffle(
        paddle.dataset.imdb.train(word_dict), buf_size=50000),
    batch_size=BATCH_SIZE)
test_reader = paddle.batch(
    paddle.reader.shuffle(
        paddle.dataset.imdb.test(word_dict), buf_size=50000),
    batch_size=BATCH_SIZE)

tmp = paddle.dataset.imdb.test(word_dict)
print(tmp)

# train in cpu
place = fluid.CPUPlace()
def test(exe):
    accuracy.reset(exe)
    for batch_id, data in enumerate(test_reader()):
        input_seq = to_lodtensor(map(lambda x:x[0], data), place)
        y_data = np.array(map(lambda x: x[1], data)).astype("int64")
        y_data = y_data.reshape([-1, 1])
        acc = exe.run(inference_program,
                      feed={"words": input_seq,
                            "label": y_data})
    return accuracy.eval(exe)

# just like session in tensorflow
exe = fluid.Executor(place)

# like placeholder
feeder = fluid.DataFeeder(feed_list=[data, label], place=place)

# not sure what's going on here
exe.run(fluid.default_startup_program())

# loop for 30 epochs, print acc ever 1000 batch
PASS_NUM = 1
for pass_id in xrange(PASS_NUM):
    accuracy.reset(exe)
    for data in train_reader():
        cost_val, acc_val = exe.run(fluid.default_main_program(),
                                    feed=feeder.feed(data),
                                    fetch_list=[avg_cost, accuracy.metrics[0]])
        pass_acc = accuracy.eval(exe)
    # save model every epoch
    pass_test_acc = test(exe)
    print("test_acc: %f" % pass_test_acc)
```

**Comment by guoshengCS** [comment]
```
bow = fluid.layers.reduce_sum(
    input=emb,
    dim=1)
```
这里`bow`包含的tensor会是1维的，可以加上`keep_dim=True`保持reduce前的维度。

**Comment by gmcather** [comment]
尝试keep_dim=True和dim=0, dim=1, dim=2, dim=-1等组合，发现仍然报错，可能是其它问题

**Comment by gmcather** [comment]
我后面没用bow了，改成sequence_pool(input=data, pool_type=sum)，好像就不报错了，是这么用吗？
