### ISSUE TITLE
ImportError: No module named dump_v2_config

### ISSUE THREAD

**Issue by zhaofenqiang** [PaddlePaddle/Paddle#8823]
I run the command `python mnist_v2.py` following this [guide](http://paddlepaddle.org/docs/develop/documentation/zh/howto/capi/workflow_of_capi_cn.html#).

And then encounter the error:

> Traceback (most recent call last):
  File "merge_v2_model.py", line 17, in <module>
    from mnist_v2 import network
  File "/home/zfq/Paddle/paddle/capi/examples/model_inference/dense/mnist_v2.py", line 24, in <module>
    from paddle.utils.dump_v2_config import dump_v2_config
ImportError: No module named dump_v2_config

Anyone know why? Many thanks!

**Comment by zhaofenqiang** [comment]
According to the method in this issue [#6534](https://github.com/PaddlePaddle/Paddle/issues/6534#issuecomment-351027547), I have solved this problem. So the raw guide or the code may have some problem.
