### ISSUE TITLE
我已经升级到PaddlePaddle 0.11.0了，怎么导入fluid时报错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8939]
我使用`pip install paddlepaddle-gpu -U`升级了PaddlePaddle
我使用`paddle version`命令查看了PaddlePaddle的版本：
```
/usr/local/bin/paddle: line 131: [: too many arguments
  File "<stdin>", line 3
    if LooseVersion("0.10.0
                          ^
SyntaxError: EOL while scanning string literal
PaddlePaddle 0.11.0, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: OFF
    with_mkldnn: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF
```

在导入包的时候报错：
```
Traceback (most recent call last):
  File "mobilenet.py", line 4, in <module>
    import paddle.fluid as fluid
ImportError: No module named fluid
```
**这是为啥？**

**Comment by peterzhang2029** [comment]
试试 import paddle.v2.fluid as fluid

**Comment by yeyupiaoling** [comment]
@peterzhang2029 
对了，但是有新的错误：
```
Traceback (most recent call last):
  File "mobilenet.py", line 85, in <module>
    train(learning_rate=0.005, batch_size=128, num_passes=300)
  File "mobilenet.py", line 27, in train
    regularization=fluid.regularizer.L2Decay(5 * 1e-5))
TypeError: __init__() got an unexpected keyword argument 'regularization'
```

是这行代码：https://github.com/PaddlePaddle/models/blob/df8060e7022fcac12fd33a8adf098c0663d8152d/fluid/image_classification/mobilenet.py#L170-L173

**Comment by peterzhang2029** [comment]
这个估计是版本问题，这个配置用的paddle版本应该更新一些。可以更新paddle试试。

**Comment by yeyupiaoling** [comment]
@peterzhang2029 
嗯嗯，我更新到最新就没问题了
