### ISSUE TITLE
demo里的mnist跑不过

### ISSUE THREAD

**Issue by sarawon** [PaddlePaddle/Paddle#895]
安装的是paddle 0.8.0版本 deb包 跑mnist时候报错：
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3113, in parse_config_and_serialize
    config = parse_config(config_file, config_arg_str)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3089, in parse_config
    execfile(config_file, make_config_environment(config_file, config_args))
  File "vgg_16_mnist.py", line 47, in <module>
    inputs(img, lbl)
NameError: name 'inputs' is not defined

像是低版本的兼容问题？怎么修复呢？

**Comment by backyes** [comment]
@sarawon 

百度同学， 从deeplearning.baidu.com/doc 开始， 一键编译安装paddle， 然后用一键安装源码里的Paddle/demo 进行学习。 这样不会有版本问题。

你的问题应该是版本问题导致的。

**Comment by sarawon** [comment]
我们是要上云，用的deb安装包 如果要用这个版本的话 有什么方法改下吗？

**Comment by gongweibao** [comment]
Closing this issue due to inactivity, feel free to reopen it.
