### ISSUE TITLE
Develop branch fluid distribute transpiler error: KeyError: u'learning_rate_0'

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#9019]
Test to run: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/test_recognize_digits.py

```
Traceback (most recent call last):
  File "dist_test.py", line 281, in <module>
    main(False, False, "conv", False)
  File "dist_test.py", line 237, in main
    params_filename=params_filename)
  File "dist_test.py", line 177, in train
    pserver_prog = t.get_pserver_program(current_endpoint)
  File "/paddle/build/python/build/lib-python/paddle/fluid/distribute_transpiler.py", line 312, in get_pserver_program
    self._append_pserver_ops(optimize_block, op, endpoint)
  File "/paddle/build/python/build/lib-python/paddle/fluid/distribute_transpiler.py", line 579, in _append_pserver_ops
    new_inputs[key] = pserver_block.vars[opt_op.input(key)[0]]
KeyError: u'learning_rate_0'
```

**Comment by gongweibao** [comment]
I'm checking it now!
