### ISSUE TITLE
单层softmax训练报错NotImplementedError

### ISSUE THREAD

**Issue by wchange** [PaddlePaddle/Paddle#902]
Traceback (most recent call last):
Thu Dec 15 11:16:14 2016[1,37]<stderr>:  File "workspace/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3408, in parse_config_and_serialize
Thu Dec 15 11:16:14 2016[1,37]<stderr>:    config = parse_config(config_file, config_arg_str)
Thu Dec 15 11:16:14 2016[1,37]<stderr>:  File "workspace/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3384, in parse_config
Thu Dec 15 11:16:14 2016[1,37]<stderr>:    execfile(config_file, make_config_environment(config_file, config_args))
Thu Dec 15 11:16:14 2016[1,37]<stderr>:  File "conf/trainer_config.conf", line 63, in <module>
Thu Dec 15 11:16:14 2016[1,37]<stderr>:    regularization=L2Regularization(8e-4)
Thu Dec 15 11:16:14 2016[1,37]<stderr>:  File "workspace/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
Thu Dec 15 11:16:14 2016[1,37]<stderr>:    return func(*args, **kwargs)
Thu Dec 15 11:16:14 2016[1,37]<stderr>:  File "workspace/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
Thu Dec 15 11:16:14 2016[1,37]<stderr>:    return func(*args, **kwargs)
Thu Dec 15 11:16:14 2016[1,37]<stderr>:  File "workspace/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/optimizers.py", line 422, in settings
Thu Dec 15 11:16:14 2016[1,37]<stderr>:    kwargs = __extends__(kwargs, learning_method.to_setting_kwargs())
Thu Dec 15 11:16:14 2016[1,37]<stderr>:  File "workspace/python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/optimizers.py", line 71, in to_setting_kwargs
Thu Dec 15 11:16:14 2016[1,37]<stderr>:    raise NotImplementedError()
Thu Dec 15 11:16:14 2016[1,37]<stderr>:NotImplementedError

**Comment by luotao1** [comment]
请贴上你的网络配置

**Comment by wchange** [comment]
define_py_data_sources2(train_list=trn,
                        test_list=tst,
                        module="user_image_provider",
                        obj=process,
                        args={})

batch_size = 16 if not is_predict else 1
settings(
    batch_size=batch_size,
    learning_rate=2e-4,
    learning_method=BaseSGDOptimizer(),
    regularization=L2Regularization(8e-4)
)

data = data_layer(name="input", size=40135)
output = fc_layer(input=data, size=2, act=SoftmaxActivation())

if not is_predict:
    label = data_layer(name="label", size=2)

    classification_cost(input=output, label=label)
    cls = classification_cost(input=output, label=label)
    outputs(cls)

**Comment by luotao1** [comment]
learning_method=BaseSGDOptimizer()这行可以去掉，默认就是SGD

**Comment by wchange** [comment]
不好使啊，之前是下面的配置
```
settings(
    batch_size=batch_size,
    learning_rate=2e-4,
    learning_method=AdamOptimizer(),
    regularization=L2Regularization(8e-4),
    gradient_clipping_threshold=25
)
```
报Floating point exception

**Comment by backyes** [comment]
@luotao1 

BaseSGDOptimizer这个基类不应该被暴露的吧， 感觉要发个pr，用__all__避免这个基类的导出。

**Comment by wchange** [comment]
现在其实就想做个ctr预估，训练一个lr模型，请问能否提供一个比较通用的配置？

**Comment by luotao1** [comment]
@backyes @reyoung 在__all__中把BaseSGDOptimizer直接去掉可以么？

**Comment by wchange** [comment]
sparse_vector有什么使用限制吗？定义域之类的？

**Comment by gongweibao** [comment]
Closing this issue due to inactivity, feel free to reopen it.

**Comment by NHZlX** [comment]
I close this issue due to inactivity. please feel free to reopen it.
