### ISSUE TITLE
An error occured when using "fluid.optimizer.Momentum"

### ISSUE THREAD

**Issue by BigFishMaster** [PaddlePaddle/Paddle#9024]
I use the python code of SE_ResNeXt in issue #8990 . Single card result is ok. 
However,  when parallel = True,  "regularization=fluid.regularizer.L2Decay(1e-4)" can not be used as following:
```python
optimizer = fluid.optimizer.Momentum(
        learning_rate=fluid.layers.piecewise_decay(
            boundaries = bd,
            values = lr
        ),
        momentum=0.9,
        regularization=fluid.regularizer.L2Decay(1e-4))
```
the error message is:
```python
Traceback (most recent call last):
  File "se_resnext50_parallel.py", line 250, in <module>
    train(learning_rate=0.1, batch_size=256, num_passes=120, init_model=None)
  File "se_resnext50_parallel.py", line 177, in train
    opts = optimizer.minimize(avg_cost)
  File "/home/ssd1/yancanxiang/code_paddle/se_resnext50_parallel_MSRA_imagenet1000/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 230, in minimize
    self.regularization)
  File "/home/ssd1/yancanxiang/code_paddle/se_resnext50_parallel_MSRA_imagenet1000/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/regularizer.py", line 51, in append_regularization_ops
    regularization_term = regularization(param, grad.block)
AttributeError: 'NoneType' object has no attribute 'block'
```
If I delete this code, It can run nomally. 
```python
optimizer = fluid.optimizer.Momentum(
        learning_rate=fluid.layers.piecewise_decay(
            boundaries = bd,
            values = lr
        ),
        momentum=0.9)
```

**Comment by jacquesqiao** [comment]
@BigFishMaster I test on the newest code, the problem does not appear, can you test on the newest code again?
