### ISSUE TITLE
AttributeError: 'module' object has no attribute 'framework_pb2'

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#9127]
```
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 17, in <module>
    import framework
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/fluid/framework.py", line 21, in <module>
    import proto.framework_pb2 as framework_pb2
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/fluid/proto/framework_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/pkg_resources/__init__.py", line 22, in <module>
    import io
  File "io.py", line 17, in <module>
    from paddle.fluid.evaluator import Evaluator
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/fluid/evaluator.py", line 17, in <module>
    import layers
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/__init__.py", line 15, in <module>
    import ops
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/ops.py", line 14, in <module>
    from layer_function_generator import generate_layer_fn
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/fluid/layers/layer_function_generator.py", line 21, in <module>
    framework_pb2 = proto.framework_pb2
AttributeError: 'module' object has no attribute 'framework_pb2'
```

**Comment by QiaoShin** [comment]
No module named 'framework_pb2' with latest commit when I use pyinstaller

**Comment by 4realDev** [comment]
@QiaoShin I have the same problem.
