### ISSUE TITLE
fluid 分布式GPU作业（带并行化）出现如下异常

### ISSUE THREAD

**Issue by xymyeah** [PaddlePaddle/Paddle#9383]
1个pserver、1个trainer（8卡）的分布式gpu作业，trainer出现如下异常
```
Traceback (most recent call last):                                                                                                                                                                                       
  File "trainer.py", line 206, in <module>                                                                                                                                                                               
    train_main(use_cuda=True, is_parallel=True, is_sparse=True)                                                                                                                                                          
  File "trainer.py", line 202, in train_main                                                                                                                                                                             
    train_loop(t.get_trainer_program())                                                                                                                                                                                  
  File "trainer.py", line 164, in train_loop                                                                                                                                                                             
    fetch_list=[average_cost])                                                                                                                                                                                           
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 349, in run                                                                                                                               
    self.executor.run(program_cache.desc, scope, 0, True, True)                                                                                                                                                          
paddle.fluid.core.EnforceNotMet: holder_ should not be null                                                                                                                                                              
Tensor not initialized yet when Tensor::place() is called. at [/paddle/paddle/fluid/framework/tensor.h:113]                                                                                                              
PaddlePaddle Call Stacks:   
0       0x7fdceb4584a6p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486                                                                                      
1       0x7fdceb45958ep paddle::framework::Tensor::place() const + 158                                                                                                                                                   
2       0x7fdcebd1690bp paddle::operators::CopyOrShare(paddle::framework::Variable const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost:                                                
:detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::varia                                                
nt::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boo                                                
st::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::va                                                
riant::void_, boost::detail::variant::void_> const&, paddle::framework::Variable*) + 347                                                                                                                                 
3       0x7fdcebd185bfp paddle::operators::ParallelDoGradOp::AccumulateGrad(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform                                                
::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, bo                                                
ost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::v                                                
ariant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_,                                                
 boost::detail::variant::void_, boost::detail::variant::void_> const&, std::vector<paddle::framework::Scope*, std::allocator<paddle::framework::Scope*> > const&, std::ve                                                
ctor<boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_,                                                
 boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail                                                
::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::voi                                                
d_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>, std::allocator<boost::variant<paddle::pl                                                
atform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_                                                
, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detai                                                
l::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::vo                                                
id_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> > > const&) const + 575                                                                                                
4       0x7fdcebd1aa61p paddle::operators::ParallelDoGradOp::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPl                                                
ace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::de                                                
tail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant:                                                
:void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost:                                                
:detail::variant::void_, boost::detail::variant::void_> const&) const + 2449                                                                                                                                             
5       0x7fdcebfaa2a8p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boo                                                
st::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::va                                                
riant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_,                                                 
boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail:                                                
:variant::void_, boost::detail::variant::void_> const&) + 88                                                                                                                                                             
6       0x7fdceb4e8b4ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool) + 1086                                                        
7       0x7fdceb4e9b70p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 64                                                                         
8       0x7fdceb46d85bp _ZZN8pybind1112cpp_function10initializeIZNS0_C1IvN6paddle9framework8ExecutorEIRKNS4_11ProgramDescEPNS4_5ScopeEibbEINS_4nameENS_9is_methodENS_7sib                                                
lingEEEEMT0_FT_DpT1_EDpRKT2_EUlPS5_S8_SA_ibbE_vISO_S8_SA_ibbEISB_SC_SD_EEEvOSF_PFSE_SH_ESN_ENUlRNS_6detail13function_callEE1_4_FUNESV_ + 555                                                                             
9       0x7fdceb4672b4p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596                                                                                                                          
10      0x7fdd3f096631p PyEval_EvalFrameEx + 24497                                                                                                                                                                       
11      0x7fdd3f097bcep PyEval_EvalCodeEx + 2190                                                                                                                                                                         
12      0x7fdd3f09620ap PyEval_EvalFrameEx + 23434                                                                                                                                                                       
13      0x7fdd3f097bcep PyEval_EvalCodeEx + 2190                                                                                                                                                                         
14      0x7fdd3f09620ap PyEval_EvalFrameEx + 23434                                                                                                                                                                       
15      0x7fdd3f097bcep PyEval_EvalCodeEx + 2190                                                                                                                                                                         
16      0x7fdd3f09620ap PyEval_EvalFrameEx + 23434                                                                                                                                                                       
17      0x7fdd3f097bcep PyEval_EvalCodeEx + 2190                                                                                                                                                                         
18      0x7fdd3f097ce2p PyEval_EvalCode + 50                                                                                                                                                                             
19      0x7fdd3f0b79e0p PyRun_FileExFlags + 176                                                                                                                                                                          
20      0x7fdd3f0b7bbfp PyRun_SimpleFileExFlags + 239                                                                                                                                                                    
21      0x7fdd3f0cd454p Py_Main + 3188                                                                                                                                                                                   
22      0x7fdd3e381cddp __libc_start_main + 253                                                                                                                                                                          
23            0x400649p                                                                                                                                                                                                  
```

**Comment by tonyyang-svail** [comment]
@xymyeah 我们目前开发还没有做paralleldo和psserver的支持。paralleldo的主要运用是单机多卡。

**Comment by typhoonzero** [comment]
现在已经支持parallelexecuter 的多机多卡功能，先关闭了。
