### ISSUE TITLE
关于v2.layer.mixed用法. v2.layer.mixed doesn't seem to accept layer.data as input

### ISSUE THREAD

**Issue by rulai-huiyingl** [PaddlePaddle/Paddle#9390]
Hi,
有一个什么也不学的小网络如下：
```
    paddle.init(use_gpu=False)
    ones = layer.data(name='ones',
                      type=paddle.data_type.dense_vector(300))
    persp_vec = layer.mixed(input=ones)    #This line is problematic

    parameters = paddle.parameters.create(persp_vec)
    parameters.set('ones', np.ones([300, ]))
```
构建的时候出错如下：
```
I0326 15:14:33.636606  5607 Util.cpp:166] commandline:  --use_gpu=False 
Traceback (most recent call last):
  File "training/doc_classification/test.py", line 75, in <module>
    main()
  File "training/doc_classification/test.py", line 45, in main
    persp_vec = layer.mixed(input=ones)
  File "/usr/local/lib/python2.7/site-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/usr/local/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 415, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 925, in mixed_layer
    m += input
  File "/usr/local/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py", line 845, in __exit__
    raise exc_value
AssertionError

```
paddlepaddle==0.10.7
不知道为什么这里layer.mixed为什么会出错
Your help appreciated! 十分感谢！

**Comment by wanghaoshuang** [comment]
Mixed layer使用方法如下：
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L867
从日志看，应该是这句出错：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L926
Mixed_layer的size默认是0的，建议你设置下mixed layer的size.

**Comment by rulai-huiyingl** [comment]
谢谢 @wanghaoshuang ！
改过mixed的size参数，还是一样的错误。以及关于mixed的参数之前我也有过疑惑  
https://github.com/PaddlePaddle/Paddle/issues/7331

以及mixed layer对输入似乎有一些要求？ 以下的代码也不行
```
    raw_out = layer.recurrent_group(input=[sim_seq],
                                    step=step_func)

    output = layer.mixed(input=raw_out,
                         act=act.Softmax(),
                         size=0)
```
报错是
```
Traceback (most recent call last):
  File "test.py", line 131, in <module>
    main()
  File "test.py", line 70, in main
    size=0)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 398, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 907, in mixed_layer
    m += input
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 829, in __exit__
    raise exc_value
AssertionError
```

**Comment by wanghaoshuang** [comment]
你把size改成多少？改成300也不行？

**Comment by rulai-huiyingl** [comment]
谢谢 @wanghaoshuang ～
有full_matrix_projection就是可以的。只是这里加了个全连接层不符合我们的需求了。。。:(
mixed_layer的输入规定有地方可以查吗？

**Comment by wanghaoshuang** [comment]
你可以使用 [identity projection](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L548), 这样就符合你们要求了。

**Comment by rulai-huiyingl** [comment]
啊对，谢谢！ @wanghaoshuang
