### ISSUE TITLE
Paddle V2 capi启动出core

### ISSUE THREAD

**Issue by heroes999** [PaddlePaddle/Paddle#9534]
内网下载的paddle capi tar包，使用paddle v2 capi。上线后发现1台机器出现如下crash：

```
(gdb) bt
#0  0x00007fd45ff4ca88 in paddle::ParameterUpdaterHookConfig::SharedCtor() ()
   from /home/work/dmas_20180330-152534/bin/libpaddle_capi_shared.so
#1  0x00007fd45ff4caed in paddle::ParameterUpdaterHookConfig::ParameterUpdaterHookConfig() ()
   from /home/work/dmas_20180330-152534/bin/libpaddle_capi_shared.so
#2  0x00007fd45ff4dc0c in paddle::protobuf_InitDefaults_ParameterConfig_2eproto_impl() ()
   from /home/work/dmas_20180330-152534/bin/libpaddle_capi_shared.so
#3  0x00007fd45ffb3460 in google::protobuf::internal::FunctionClosure0::Run() ()
   from /home/work/dmas_20180330-152534/bin/libpaddle_capi_shared.so
#4  0x00007fd45ffb4581 in google::protobuf::GoogleOnceInitImpl(long*, google::protobuf::Closure*) ()
   from /home/work/dmas_20180330-152534/bin/libpaddle_capi_shared.so
#5  0x00007fd45ff4c6fa in paddle::protobuf_InitDefaults_ParameterConfig_2eproto() ()
   from /home/work/dmas_20180330-152534/bin/libpaddle_capi_shared.so
#6  0x00007fd45ff4c74f in paddle::protobuf_AddDesc_ParameterConfig_2eproto_impl() ()
   from /home/work/dmas_20180330-152534/bin/libpaddle_capi_shared.so
#7  0x00007fd45ffb3460 in google::protobuf::internal::FunctionClosure0::Run() ()
   from /home/work/dmas_20180330-152534/bin/libpaddle_capi_shared.so
#8  0x00007fd45ffb4581 in google::protobuf::GoogleOnceInitImpl(long*, google::protobuf::Closure*) ()
   from /home/work/dmas_20180330-152534/bin/libpaddle_capi_shared.so
#9  0x00007fd45ff4c7ca in paddle::protobuf_AddDesc_ParameterConfig_2eproto() ()
   from /home/work/dmas_20180330-152534/bin/libpaddle_capi_shared.so
#10 0x00007fd47393580a in call_init.part () from /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2
#11 0x00007fd4739358f3 in _dl_init_internal () from /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2
#12 0x00007fd4739281ca in _dl_start_user () from /opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2
```

这个应该还是attach so的阶段，没有其他的日志。
请问解决方案。

**Comment by JiayiFeng** [comment]
既然是多台机器中的一台出问题，这些机器的环境是否有区别？

另外报错信息请尽量以文字而不是截屏形式给出，保证信息完整的同时方便以后的同学搜索查阅。

**Comment by heroes999** [comment]
已经转换成文本格式。@JiayiFeng

我理解可能是attach so这个操作可能依赖到系统层的东西。问下主要看哪环境上哪方面的diff。

**Comment by JiayiFeng** [comment]
通过线下与用户的沟通，基本确认是CPU不支持AVX指令集的原因

**Comment by Yancey1989** [comment]
Close this inactive issue, please feel free to reopen it.
