### ISSUE TITLE
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by damengdameng** [PaddlePaddle/Paddle#9631]
i`m a novice in the field of tensorflow and this is my first time to ask a question on the github .orz.. If I have something wrong with my description, please criticize me more! Thank you~

（新手菜鸟 第一次在github上提问 如有不当 请多批评指正！谢谢～）

-Ubuntu16.04LTS
-intel i5
-GT740M...
-tensorflow 1.4.1(gpu)
-python 3.5.2
-CUDA8.0
-cuDNN6.0

when i run a 3dcnn+lstm network,i got this warning:
(原本装了gpu版本的tensorflow，在运行3DCNN+LSTM的深度学习网络时出现了这样的warning：)

Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA

so i searched on the github and installed  tensorflow-1.4.1-cp35-cp35m-linux_x86_64.whl  l from here:https://github.com/mind/wheels/releases/tag/tf1.4.1-cpu 
（然后在github上搜索了一下，好像是编译的问题，于是在https://github.com/mind/wheels/releases/tag/tf1.4.1-cpu  下载了wheel然后安装了。）

then......here comes the error i can`t fix TOT
（然后。。。就出现了这个error TOT 按照网上的方法添加了环境变量，还是不行。。）

求助！！
ask for help!!!

**Comment by damengdameng** [comment]
'''
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dameng/PycharmProjects/1/train.py", line 6, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libmklml_intel.so: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
'''

**Comment by qingqing01** [comment]
@damengdameng 关于TensorFlow的问题，请移步至TF官方渠道提问，谢谢~  :)
