### ISSUE TITLE
test_parallel_executor

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#9690]
```

[13:45:09][Step 1/1]  96/124 Test  #90: test_parallel_executor ..........................***Failed   27.11 sec
[13:45:09][Step 1/1] test_batchnorm_fc (test_parallel_executor.TestMNIST) ... [2.7106557 2.8602777] [1.0695171 0.9322908]
[13:45:09][Step 1/1] [2.302585 2.302585] [2.0781438 2.0781438]
[13:45:09][Step 1/1] ok
[13:45:09][Step 1/1] test_simple_fc (test_parallel_executor.TestMNIST) ... [2.299374  2.4102025] [1.6239367 1.6833193]
[13:45:09][Step 1/1] [2.679364  2.5005164] [1.8873956 1.6990144]
[13:45:09][Step 1/1] ERROR
[13:45:09][Step 1/1] test_resnet (test_parallel_executor.TestResnet) ... ERROR
[13:45:09][Step 1/1] test_main (test_parallel_executor.TestTransformer) ... skipped 'transformer is buggy in multi gpu'
[13:45:09][Step 1/1] 
[13:45:09][Step 1/1] ======================================================================
[13:45:09][Step 1/1] ERROR: test_simple_fc (test_parallel_executor.TestMNIST)
[13:45:09][Step 1/1] ----------------------------------------------------------------------
[13:45:09][Step 1/1] Traceback (most recent call last):
[13:45:09][Step 1/1]   File "test_parallel_executor.py", line 258, in test_simple_fc
[13:45:09][Step 1/1]     "label": label})
[13:45:09][Step 1/1]   File "test_parallel_executor.py", line 218, in check_network_convergence
[13:45:09][Step 1/1]     exe.run([], feed_dict=feed_dict)
[13:45:09][Step 1/1]   File "/paddle/build/python/paddle/fluid/parallel_executor.py", line 91, in run
[13:45:09][Step 1/1]     self.executor.run(fetch_list, fetch_var_name, feed_tensor_dict)
[13:45:09][Step 1/1] EnforceNotMet: an illegal memory access was encountered at [/paddle/paddle/fluid/framework/details/op_handle_base.cc:80]
[13:45:09][Step 1/1] PaddlePaddle Call Stacks: 
[13:45:09][Step 1/1] 0       0x7fc95d7313ecp paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 572
[13:45:09][Step 1/1] 1       0x7fc95e31f5ffp paddle::framework::details::OpHandleBase::Wait(paddle::platform::DeviceContext*) + 511
[13:45:09][Step 1/1] 2       0x7fc95e310cedp paddle::framework::details::ComputationOpHandle::RunImpl() + 205
[13:45:09][Step 1/1] 3       0x7fc95e31fb59p paddle::framework::details::OpHandleBase::Run(bool) + 393
[13:45:09][Step 1/1] 4       0x7fc95e316dfap
[13:45:09][Step 1/1] 5       0x7fc95e197a1ep std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) + 46
[13:45:09][Step 1/1] 6       0x7fc9ef554a99p
[13:45:09][Step 1/1] 7       0x7fc95e314ebdp
[13:45:09][Step 1/1] 8       0x7fc95e31ad04p std::thread::_Impl<std::_Bind_simple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1} ()> >::_M_run() + 340
[13:45:09][Step 1/1] 9       0x7fc9e9df8c80p
[13:45:09][Step 1/1] 10      0x7fc9ef54d6bap
[13:45:09][Step 1/1] 11      0x7fc9ef28341dp clone + 109
[13:45:09][Step 1/1] 
[13:45:09][Step 1/1] 
[13:45:09][Step 1/1] ======================================================================
[13:45:09][Step 1/1] ERROR: test_resnet (test_parallel_executor.TestResnet)
[13:45:09][Step 1/1] ----------------------------------------------------------------------
[13:45:09][Step 1/1] Traceback (most recent call last):
[13:45:09][Step 1/1]   File "test_parallel_executor.py", line 295, in test_resnet
[13:45:09][Step 1/1]     batch_size=batch_size)
[13:45:09][Step 1/1]   File "test_parallel_executor.py", line 210, in check_network_convergence
[13:45:09][Step 1/1]     exe = fluid.ParallelExecutor(loss_name=loss.name, use_cuda=True)
[13:45:09][Step 1/1]   File "/paddle/build/python/paddle/fluid/parallel_executor.py", line 69, in __init__
[13:45:09][Step 1/1]     allow_op_delay)
[13:45:09][Step 1/1] RuntimeError: function_attributes(): after cudaFuncGetAttributes: an illegal memory access was encountered
[13:45:09][Step 1/1] 
[13:45:09][Step 1/1] ----------------------------------------------------------------------
[13:45:09][Step 1/1] Ran 4 tests in 12.506s
[13:45:09][Step 1/1] 
[13:45:09][Step 1/1] FAILED (errors=2, skipped=1)
[13:45:09][Step 1/1] 
```

**Comment by dzhwinter** [comment]
This issue has been fixed in the latest develop branch, Please reopen if it occurs again.
