### ISSUE TITLE
no core.so found in whl package when built on MacOS

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#9721]

**Comment by luotao1** [comment]
On my server, the error is:
```
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 34, in <module>
    from core import LoDTensor, CPUPlace, CUDAPlace, CUDAPinnedPlace
ImportError: cannot import name CUDAPinnedPlace
```
