### ISSUE TITLE
Python import error: ImportError: cannot import name CUDAPinnedPlace

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/Paddle#9734]
```
>>> import paddle.fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luotao02/.jumbo/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 34, in <module>
    from core import LoDTensor, CPUPlace, CUDAPlace, CUDAPinnedPlace
ImportError: cannot import name CUDAPinnedPlace
```

**A temporary solution is to delete CUDAPinnedPlace**

**Comment by luotao1** [comment]
Duplicated with https://github.com/PaddlePaddle/Paddle/issues/9721#issuecomment-379516153, and it's already been fixed.

**Comment by chengduoZH** [comment]
@luotao1  I see, thanks!
