### ISSUE TITLE
python import error

### ISSUE THREAD

**Issue by BryceLuminary** [PaddlePaddle/Paddle#9745]
您好，我按照官网教程，在非 docker 环境下源码编译了 paddle，并运行
pip install ~/paddle/Paddle/build/python/dist/paddlepaddle-0.11.1a2-cp27-cp27mu-linux_x86_64.whl
；但是在 python 中输入 import paddle 时会出现 ImportError: 

Warning with import paddle: you should not
     import paddle from the source directory; please install paddlepaddle*.whl firstly.Traceback (most recent call last):
  File "./test_inference_model_io.py", line 18, in <module>
    import paddle.fluid.core as core
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/__init__.py", line 17, in <module>
    import framework
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 22, in <module>
    from . import core
ImportError: cannot import name core

请问这是什么原因呢？谢谢！

**Comment by typhoonzero** [comment]
您好，请pull下最新的develop分支的代码，这个问题今天在：https://github.com/PaddlePaddle/Paddle/issues/9721 已经修复了。
