### ISSUE TITLE
Operator "sin" has not been registered.

### ISSUE THREAD

**Issue by jshower** [PaddlePaddle/Paddle#9749]
gpu版编译完成，运行python -c "import paddle.fluid"，出现下面错误，不知是否是个例
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/__init__.py", line 23, in <module>
    import io
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/io.py", line 17, in <module>
    from paddle.fluid.evaluator import Evaluator
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/evaluator.py", line 17, in <module>
    import layers
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/__init__.py", line 15, in <module>
    import ops
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/ops.py", line 77, in <module>
    globals()[_OP] = generate_layer_fn(_OP)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/layer_function_generator.py", line 108, in generate_layer_fn
    op_proto = OpProtoHolder.instance().get_op_proto(op_type)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 357, in get_op_proto
    raise ValueError("Operator \"%s\" has not been registered." % type)
ValueError: Operator "sin" has not been registered.
```

**Comment by walloollaw** [comment]
same with me when i compile cpu version,
>>> import paddle.fluid as fluid
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vis/wanglong03/tool/python276/lib/python2.7/site-packages/paddle/fluid/__init__.py", line 23, in <module>
    import io
  File "/home/vis/wanglong03/tool/python276/lib/python2.7/site-packages/paddle/fluid/io.py", line 17, in <module>
    from paddle.fluid.evaluator import Evaluator
  File "/home/vis/wanglong03/tool/python276/lib/python2.7/site-packages/paddle/fluid/evaluator.py", line 18, in <module>
    import layers
  File "/home/vis/wanglong03/tool/python276/lib/python2.7/site-packages/paddle/fluid/layers/__init__.py", line 15, in <module>
    import ops
  File "/home/vis/wanglong03/tool/python276/lib/python2.7/site-packages/paddle/fluid/layers/ops.py", line 77, in <module>
    globals()[_OP] = generate_layer_fn(_OP)
  File "/home/vis/wanglong03/tool/python276/lib/python2.7/site-packages/paddle/fluid/layers/layer_function_generator.py", line 108, in generate_layer_fn
    op_proto = OpProtoHolder.instance().get_op_proto(op_type)
  File "/home/vis/wanglong03/tool/python276/lib/python2.7/site-packages/paddle/fluid/framework.py", line 357, in get_op_proto
    raise ValueError("Operator \"%s\" has not been registered." % type)
ValueError: Operator "sin" has not been registered

**Comment by walloollaw** [comment]
it's work now after i rm the core.so in source code before compiling.

**Comment by wangyang59** [comment]
@walloollaw 
Thanks a lot for the suggestions! I solved the problem with your method.
