### ISSUE TITLE
MPI paddle版本不支持resize layer

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#9758]
提交MPI任务报错：
```
Traceback (most recent call last):
  File "conf/trainer_config.conf", line 529, in <module>
    main()
  File "conf/trainer_config.conf", line 447, in main
    fc_spd_comb, fc_conf_comb, fc_gmm_comb)
  File "conf/trainer_config.conf", line 377, in convolutional_neural_network
    resize_fc_pre = paddle.layer.resize(input=pre_lstm_output, size=15*20)
AttributeError: 'module' object has no attribute 'resize'
```

尝试将job中的workspace/python27-gcc482/lib/python2.7/site-packages/paddle/layers.py文件下载后，对照https://github.com/PaddlePaddle/Paddle/blob/d02a68c4472d3b85559f82c026896bf2cf563b07/python/paddle/trainer_config_helpers/layers.py
添加resize_layer相关内容，然后通过thirdparty中的before_hook.sh替换job中的文件：
```
rm ./python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.py
rm ./python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/layers.pyc
cp thirdparty/thirdparty/layers.py ./python27-gcc482/lib/python2.7/site-packages/paddle/trainer_config_helpers/
```

但还是相同报错。

**Comment by chengduoZH** [comment]
仅仅修改layers.py文件是不够的
错误信息提示没有`resize`的layer，可能你装paddle版本有点老，建议卸载当前的paddle并安装最新的paddle。

**Comment by hyo009** [comment]
提交MPI集群任务也需要更新本地的paddle版本吗？

**Comment by chengduoZH** [comment]
您这个错误是本地paddle报的吗？

**Comment by hyo009** [comment]
不是，是train.log里的，我的提交命令是
```
./paddle cluster_train \
  --config lstm_cluster_job.py \
  --use_remote_sparse 0 \
  --time_limit 10:00:00 \
  --submitter huangyiou \
  --num_nodes 1 \
  --job_priority normal \
  --init_model_path /app/lbs/lbs-guiji/users/huangyiou/P40/ \
  --fs_name hdfs://yq01-heng-hdfs.dmop.baidu.com:54310 \
  --fs_ugi *** \
  --train_meta_data_path \"\" \
  --test_meta_data_path \"\" \
  --train_data_path /app/lbs/lbs-guiji/users/huangyiou/new_model/s3_create_train_data_norm_comb \
  --test_data_path  /app/lbs/lbs-guiji/users/huangyiou/new_model/s3_create_train_data_norm_12_0015_P40 \
  --output_path /app/lbs/lbs-guiji/users/huangyiou/P40/ \
  --thirdparty thirdparty \
  --where yq01-hic-p40_3_8_slurm_cluster \
  --job_name paddle_cluster_traffic_prediction
```

**Comment by chengduoZH** [comment]
可以试着按这个wiki里的来操作，提交一个新版本的paddle
http://wiki.baidu.com/pages/viewpage.action?pageId=327596461

**Comment by chengduoZH** [comment]
请问问题解决了吗

**Comment by chengduoZH** [comment]
该issue长时间没有回复，暂且可以关闭了，如果还有疑问可以重新打开
