### ISSUE TITLE
Cannot import cudapinnedplace from core

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#9805]
This happens when I am testing operators on local machine.

```
    Start 211: test_activation_op

211: Test command: /usr/bin/env "PYTHONPATH=/paddle/build/python" "/usr/bin/python2.7" "-u" "-m" "unittest" "--verbose" "test_activation_op"
211: Test timeout computed to be: 9.99988e+06
211: Traceback (most recent call last):
211:   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
211:     "__main__", fname, loader, pkg_name)
211:   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
211:     exec code in run_globals
211:   File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
211:     main(module=None)
211:   File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
211:     self.parseArgs(argv)
211:   File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
211:     self.createTests()
211:   File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
211:     self.module)
211:   File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
211:     suites = [self.loadTestsFromName(name, module) for name in names]
211:   File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
211:     module = __import__('.'.join(parts_copy))
211:   File "test_activation_op.py", line 17, in <module>
211:     import paddle.fluid.core as core
211:   File "/paddle/build/python/paddle/fluid/__init__.py", line 34, in <module>
211:     from core import LoDTensor, CPUPlace, CUDAPlace, CUDAPinnedPlace
211: ImportError: cannot import name CUDAPinnedPlace
1/1 Test #211: test_activation_op ...............***Failed    1.01 sec
```

**Comment by tonyyang-svail** [comment]
I have seen a similar error. Any idea on this?

**Comment by chengduoZH** [comment]
It's already been fixed. https://github.com/PaddlePaddle/Paddle/issues/9721#issuecomment-379516153

**Comment by chengduoZH** [comment]
Recently, there are some issues similar to this, for example, #9797, #9796, #9721, it seems that all those issues are caused by this [PR](https://github.com/PaddlePaddle/Paddle/pull/9512/files).

**Comment by kexinzhao** [comment]
Recompilation with the latest code did remove the error.
Thanks @chengduoZH for the info!

**Comment by helinwang** [comment]
removing the `build` folder is probably not enough. Need to run `git clean -dxf` to remove everything (including the files ignored by .gitignore).
