### ISSUE TITLE
test_fc_op.TestFCMKLDNNOp fails on no-avx2 machine

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#9873]
If the machine doesn't find avx2, or we turn `WITH_MKLDNN=OFF`, the test_fc_op.TestFCMKLDNNOp fails:
```
176: ERROR: test_check_output (test_fc_op.TestFCMKLDNNOp4)
176: ----------------------------------------------------------------------
176: Traceback (most recent call last):
176:   File "test_fc_op.py", line 61, in test_check_output
176:     self.check_output()
176:   File "op_test.py", line 348, in check_output
176:     self.check_output_with_place(place, atol)
176:   File "op_test.py", line 291, in check_output_with_place
176:     outs, fetch_list = self._calc_output(place)
176:   File "op_test.py", line 267, in _calc_output
176:     attrs=self.attrs if hasattr(self, "attrs") else dict())
176:   File "/home/luotao02/Paddle/build/python/paddle/fluid/framework.py", line 835, in append_op
176:     op = Operator(block=self, desc=op_desc, *args, **kwargs)
176:   File "/home/luotao02/Paddle/build/python/paddle/fluid/framework.py", line 494, in __init__
176:     self.desc.infer_shape(self.block.desc)
176: EnforceNotMet: fc's infer_shape has not been registered at [/home/luotao02/Paddle/paddle/fluid/framework/op_desc.cc:361]
176: PaddlePaddle Call Stacks: 
176: 0       0x7f1978c5e496p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
176: 1       0x7f1978cd6eb2p paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const + 1154
176: 2       0x7f1978caf835p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}, void, paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::OpDesc, paddle::framework::BlockDesc const&, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::OpDesc::*)(paddle::framework::BlockDesc const&) const, pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&)#1}&&, void (*)(paddle::framework::OpDesc const*, paddle::framework::BlockDesc const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 213
176: 3       0x7f1978c6f2eap pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2602
176: 4       0x7f19b15a03e4p PyEval_EvalFrameEx + 25956
```
The ci log is: https://paddleci.ngrok.io/viewLog.html?buildId=33167&tab=buildLog&buildTypeId=Paddle_PrCi&logTab=tree&filter=all&_focus=11720
```
[05:48:07][Step 1/1] test_check_grad_no_weight (test_fc_op.TestFCMKLDNNOp) ... ERROR
[05:48:07][Step 1/1] test_check_grad_normal (test_fc_op.TestFCMKLDNNOp) ... ERROR
[05:48:07][Step 1/1] test_check_output (test_fc_op.TestFCMKLDNNOp) ... ERROR
[05:48:07][Step 1/1] test_check_grad_no_weight (test_fc_op.TestFCMKLDNNOp1) ... ERROR
[05:48:07][Step 1/1] test_check_grad_normal (test_fc_op.TestFCMKLDNNOp1) ... ERROR
[05:48:07][Step 1/1] test_check_output (test_fc_op.TestFCMKLDNNOp1) ... ERROR
[05:48:07][Step 1/1] test_check_grad_no_weight (test_fc_op.TestFCMKLDNNOp2) ... ERROR
[05:48:07][Step 1/1] test_check_grad_normal (test_fc_op.TestFCMKLDNNOp2) ... ERROR
[05:48:07][Step 1/1] test_check_output (test_fc_op.TestFCMKLDNNOp2) ... ERROR
[05:48:07][Step 1/1] test_check_grad_no_weight (test_fc_op.TestFCMKLDNNOp3) ... ERROR
[05:48:07][Step 1/1] test_check_grad_normal (test_fc_op.TestFCMKLDNNOp3) ... ERROR
[05:48:07][Step 1/1] test_check_output (test_fc_op.TestFCMKLDNNOp3) ... ERROR
[05:48:07][Step 1/1] test_check_grad_no_weight (test_fc_op.TestFCMKLDNNOp4) ... ERROR
[05:48:07][Step 1/1] test_check_grad_normal (test_fc_op.TestFCMKLDNNOp4) ... ERROR
[05:48:07][Step 1/1] test_check_output (test_fc_op.TestFCMKLDNNOp4) ... ERROR
```

**Comment by luotao1** [comment]
@mozga-intel Could you help fix this issue? Thanks very much!

**Comment by mozga-intel** [comment]
@luotao1 Sure.
