### ISSUE TITLE
mkldnn fc kernel error 

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#9877]
compile command 
```txt
cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKL=OFF -DWITH_DOC=ON -DWITH_STYLE_CHECK=OFF; make -j paddle_python
```
```txt
Traceback (most recent call last):
  File "fluid/mnist.py", line 24, in <module>
    import paddle.fluid as fluid
  File "/paddle/Paddle/build/python/build/lib-python/paddle/fluid/__init__.py", line 17, in <module>
    import framework
  File "/paddle/Paddle/build/python/build/lib-python/paddle/fluid/framework.py", line 22, in <module>
    from . import core
ImportError: /paddle/Paddle/build/python/build/lib-python/paddle/fluid/core.so: undefined symbol: _Z32TouchOpKernelRegistrar_fc_MKLDNNv
```

**Comment by luotao1** [comment]
Discussed with @dzhwinter, the reason is that `/paddle/Paddle/build/python/build/lib-python/paddle/fluid/core.so` is a wrong version
![image](https://user-images.githubusercontent.com/6836917/38672451-d113f64e-3e80-11e8-9c8f-007ad4ed9397.png)
After re-compiled, this problem is fixed.
